### ISSUE TITLE
[Bug] Sending OAuth 2.0 Request Returns New Blank Window

### ISSUE THREAD

**Issue by sc0ttwad3** [getinsomnia/insomnia#1000]
Running Windows 10 build 17692
Insomia v5.16.6

To recreate (I used a fresh installation of the latest Insomnia download for Windows to verify, twice):

Step-by-step follow the tutorial [GitHub API Authentication using OAuth 2.0](https://insomnia.rest/blog/oauth2-github-api/) 

Send the correctly setup request and when prompted complete the sign in with your GitHub credentials and authorize the OAuth application.

Problem occurs at this point: only a new blank window shows up instead of results while the preview pane in the original Insomnia window continues counting. You're only exit is to manually cancel the request.

Screenshot:

![insomnia-problem-white-screen](https://user-images.githubusercontent.com/1682691/41813652-20b343b6-7708-11e8-97f6-951451aaf237.jpg)

**Comment by gschier** [comment]
Quick question before I try and reproduce on my end: Is the `redirect_url` the same one you entered in GitHub when creating the OAuth app?

**Comment by sc0ttwad3** [comment]
@gschier It is the same.  I just re-confirmed that everything matches what is specified or assigned from the app registration in GitHub OAuth Application Settings.  I've also tried putting in the OAuth 2 values manually and then using env vars via sub-environment JSON values and same result.

Of additional note is the new blank window doesn't close even if you click in the preview pane to cancel the request. However, if you click to close the blank window, the request gets canceled.

**Comment by lunatic-coding** [comment]
I am having the same issue. Don't know how to fix it.

**Comment by forrest-lookback** [comment]
I'm also encountering this even on the latest release release of Insomnia, what can we provide data wise to try and get this resolved?

**Comment by denniseffing** [comment]
I have the same issue when my identity provider is hosted using a self-signed TLS certificate, even though "Validate certificates" is set to off in Insomnia settings.

**Comment by sraze** [comment]
I had the same issue - see below for what fixed it for me. 

STEPS:
- Attempt an OAuth connection, as per OP
- Click on [Fetch Tokens] button

EXPECTED: 
- Browser window opens, with which I can grant requested permission 

ACTUAL:
- New blank instance of Insomnia opens
- That's all

Only option then is to close the spawned Insomina window, whereupon the original Insomnia window says "Authorization window closed."

RESOLUTION:

Problem was that my AUTHORIZATION URL value in my Insomnia OAuth settings was incorrect.  Once that was correct, then it worked as advertised, with the spawned Insomnia instance wrapping a web page where I could complete the authorization process.

**Comment by denniseffing** [comment]
@sraze My authorization URL is correct. It works when using HTTP instead of HTTPS, however that is only a workaround, not a solution. Many development environments use self signed SSL certificates or the Let's Encrypt Staging environment. Insomnia OAuth won't work in these environments.

**Comment by denniseffing** [comment]
@gschier Would you mind taking another look at this issue?

**Comment by vvidovic** [comment]
There is still no solution for self-signed URLs?
