### ISSUE TITLE
[Feature Request] Content-Encoding GZip on Request

### ISSUE THREAD

**Issue by nsankaranarayanan** [getinsomnia/insomnia#1002]
- Insomnia Version: 5.16.6
- Operating System: Windows 10

## Details
Currently Insomnia doesn't seem to to send gzipped request contents when the "Content-Encoding" request header is set to gzip.

**Comment by gschier** [comment]
It's my understanding that `Content-Encoding` is not a standardized request header, but only a response header. 

This isn't an RFC, but this wikipedia page does not mention `Content-Encoding` as a request header https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Request_fields

**Comment by nsankaranarayanan** [comment]
@gschier I am reading the RFC and I don't see anything that says that the content-encoding is only a response header. See for yourself https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

Also see this link where there is a demonstration of sending gzipped content using curl.
http://yasassriratnayake.blogspot.com/2015/08/sending-gzip-request-using-curl.html

**Comment by gschier** [comment]
Oh, yes! I see it

> If the content-coding of an entity in a request message is not acceptable to the origin server...

You didn't mention that Insomnia throws an error when you try this

![image](https://user-images.githubusercontent.com/587576/41873596-7be1d54a-7893-11e8-80b5-9998aba53e12.png)


Since Curl supports it then it should be possible for Insomnia to do it as well (since it uses `libcurl`). I'll see if there's a flag somewhere..

**Comment by gschier** [comment]
Hmm, it looks like Curl won't do the request encoding for you (like it does with responses). The example you posted shows that you need to manually gzip the file before sending it via curl.

**Comment by nsankaranarayanan** [comment]
@gschier You have to treat this the same way as the response encoding where Insomnia automatically unzips based on the response header.
If you don't want to automatically zip based on the request header then can you at least provide a button or checkbox where we explicitly tell Insomnia to zip?
