### ISSUE TITLE
[Feature Request] Add group endpoints by tags for swagger

### ISSUE THREAD

**Issue by Azef1** [getinsomnia/insomnia#1004]
- Insomnia Version: 5.16.6
- Operating System: Win10 x64

## Details
Hi, 

I like to use Insomnia because UI is simple effective ! but an option is missing: "I would like to see requests grouped by tags"
 
## Example

1. Go to: [http://petstore.swagger.io/#/pet](http://petstore.swagger.io/#/pet ). You can see 3 endpoints ( pet; store and user). 
2. Import json API definition in Insomnia (Import/Export Data --> Import Data --> From URL and set : https://petstore.swagger.io/v2/swagger.json)
3. You can see on left panel requests aren't grouped :(    it's unreadable
![image](https://user-images.githubusercontent.com/15362041/41866130-87f63db4-78af-11e8-93e8-c271779003fd.png)

## Goal
I think, i will be better if requests are grouped by tags (pet; store; user) , something like that :  (
![image](https://user-images.githubusercontent.com/15362041/41866752-5c1e6570-78b1-11e8-8065-c605e9445224.png)

**Comment by gschier** [comment]
That sounds like a reasonable thing to do, not knowing anything about Swagger.

**Comment by thewheat** [comment]
Hope it is ok that I worked on this as I forgot to mention before writing up the code 🙈 
- So if somebody else had dibs on it, feel free to ignore the PR. 
- My PR is here https://github.com/getinsomnia/insomnia/pull/1211
