### ISSUE TITLE
[Bug] Environment (Recursive/Non-Recursive) Variables Not Detected

### ISSUE THREAD

**Issue by paulleduc** [getinsomnia/insomnia#1005]
- Insomnia Version: 5.16.6
- Operating System: OSX 10.12.4

## Details

Trying to follow the examples provided in the docs (https://support.insomnia.rest/article/18-environment-variables), I am unable to get variables functioning in both my base environment or any sub environments. 

My Base Environment:
```
{
	"base_url": "{{ protocol }}",
	"protocol": "https"
}
```

The auto-suggest feature does not contain any of my environment variables to select (such as `protocol`), and when I enter the param manually using `{{}}` like above, I get a warning symbol next to the variable, and the following warning when I click on it: "attempted to output null or undefined value".

![screen shot 2018-06-25 at 12 11 26 pm](https://user-images.githubusercontent.com/1308031/41870552-3d5f0238-7871-11e8-98b4-f90715a9a74d.png)

I have tried restarting the application, as well as referencing variables from other environments. No environment variables seem to appear in the auto-suggest box. This is my first time using Insomnia, using a fresh download, not even any requests created yet.

**Comment by gschier** [comment]
I just reproduced on my end. It looks like everything works correctly as long as an active request is selected from the sidebar. Can you confirm this?

**Comment by paulleduc** [comment]
Yes you're right, it worked as expected as soon as I created at least one request and selected it. It only seems to be an issue when no requests have been created yet. Thanks!
