### ISSUE TITLE
[Feature Request] Auth0 Support

### ISSUE THREAD

**Issue by delianides** [getinsomnia/insomnia#1008]
- Insomnia Version: 5.16.6
- Operating System: MacOS 10.13.5 (17F77)

## Details

There's no specific issue. But I wanted to get some feedback. Currently using the Oauth 2.0 Auth method there is no way to request a jwt token from Auth0. I can request an access token that will allow me to make further requests to the `/userinfo` endpoint. But if I'm using auth0 to authenticate a connection to a separate API, I can't seem to get an jwt `access_token` with my user data. It seems the `Implicit` grant type is missing the `audience` option which is needed to retrieve a full jwt access token.

Does it make sense to add an Auth0 auth method to the list to simplify development for anyone wanting to use their service?  Or is this something you think a plugin can do (with window redirect authentication)?

I'm happy to work on this!

**Comment by gschier** [comment]
There was an audience field added for Auth0 [a while ago](https://github.com/getinsomnia/insomnia/pull/679), although only on the Client Credentials grant type. I'd be happy to accept a PR adding it to the Implicit type.

**Comment by delianides** [comment]
@gschier cool, ill get it working and submit a PR.

**Comment by gschier** [comment]
Awesome! Let me know if you have any questions 😄
