### ISSUE TITLE
How to trigger request from another one / chain requests execution ?

### ISSUE THREAD

**Issue by rgarrigue** [getinsomnia/insomnia#1010]
Hi

It's just a quick question. Is it possible for a request to trigger another which it depends on via something like this ?

![image](https://user-images.githubusercontent.com/1872031/41901879-5999eb04-7932-11e8-88d7-de8093725eb8.png)

Or hard dependency or any alike feature to send multiple requests at once

Best regards,

**Comment by gschier** [comment]
Hey @rgarrigue. This issue is being discussed over on #286
