### ISSUE TITLE
[Bug] Weird graphical glitch when setting wrong index in folder variable thingy

### ISSUE THREAD

**Issue by tippl** [getinsomnia/insomnia#1014]
Ok, this is a weird one so good luck trying to fix it. This only happens on the folder variables, when normal variables point to nonexistent values this doesn't happen.
[video since i probably couldn't explain](https://streamable.com/t9r9t)

**Comment by gschier** [comment]
Woah, I was able to get two symbols! 
![image](https://user-images.githubusercontent.com/587576/41954666-8778cd38-79aa-11e8-85eb-0064da7e8acf.png)

**Comment by tippl** [comment]
Yeah, i did too. It keeps rapidly alternating between no symbol, 1 and 2.

**Comment by tippl** [comment]
It still happens, just less often. I think it might be having 2 error states, something like "variable not found" and "needs to be between 0-3". Because the "url" variable i saved result of that one to exhibits the same bug.

**Comment by gschier** [comment]
Oh, that didn't quite fix it. I see the real problem.

**Comment by gschier** [comment]
It's because the mouseover event updates the text, but the icon is added after a slight delay. Just have to make those a single op

**Comment by gschier** [comment]
Bam! Should work perfectly now 👍
