### ISSUE TITLE
[Feature Request] Add tags to requests for quick context switch

### ISSUE THREAD

**Issue by 4ekki** [getinsomnia/insomnia#1016]
- Insomnia Version: 5.16.6
- Operating System: Win 10

## Details
The story: 
I have a lot of requests (100+) in the requests tree. Also, I usually follow some scenarios during the work. F.e., scenario 1, "creating new user": I run one request that 'creates' new user, several 'updates', 'complete', after that I usually 'login' and request some parameters with 'viewer'. 
Scenario 2, "deposit money": I 'login', request parameters with 'viewer', check 'depositOptions', run 'createDeposit' and 'forceNotification'. 

What I want is to be able to mark my requests with tags and, after that, be able to promptly filter requests with specific tag and hide all others. 
I cannot do it by folders since I use them for product-wise hierarhy, not scenario-wise. Also, single request can be used in several scenarios. For the cases above, 'login' request would have 'newUser' and 'deposit' tags. 

Example: 
![image](https://user-images.githubusercontent.com/38757986/41996340-438f68d0-7a5d-11e8-872b-91339c15cae9.png)
And on clicking any 'deposit' tag, all requests without it are hidden: 
![image](https://user-images.githubusercontent.com/38757986/41996650-3df8dbda-7a5e-11e8-915c-b326d2ac2ded.png)

**Comment by 4ekki** [comment]
Sorry for designing this in MS Paint xD Just wanted to quickly visualise this idea.

**Comment by gschier** [comment]
I think I understand. Folders are useful for a single dimension of categorization, but you want tags to categorize in a 2nd, 3rd, ... dimension.

I definitely think this idea has potential, but I wonder how many others this would be useful too?

Anyway. I have an idea for how this could be implemented in a non-intrusive way. Let me know what you think.

- Define tags in the current workspace's Settings dialog
- In the request dropdown in the sidebar, show the tags selector near the bottom to toggle tags on/off
- Somehow show tags beside the requests. Your mockup is good, but what happens for long tag names or multiple tags on each request when the sidebar is skinnier? Should they minimize to just show a colored line?
- Currently, the request method can be filtered specifically using the sidebar filtering mechanism. I think it makes sense to re-use the sidebar filter to search for tags as well. Let me know if you can think of a reason that this may not work.

Again, I would love some feedback from others on this as well. I'll send out a tweet to ask for comments.

**Comment by dgoosens** [comment]
Like the idea...

For the filter, I suggest you implement it more or less like the issues in GitHub:  
`is:open is:issue`  
The used keyword `is` could also be `tag` or simply `t`

I agree with the tags... This will be problematic for long tags...  
Maybe something like this would be better:
![insomnia](https://user-images.githubusercontent.com/1250047/41998593-70bfb186-7a5b-11e8-9289-65c28bde9661.png)

The bullet would contain the first letters of the tag names:

- Deposit becomes `D`
- New User becomes `NU`

On hover over the bullet, the full tag name could be shown

Finally, maybe it should be possible to have a context menu on those bullets:

- exclude XX
- only show XX

**Comment by 4ekki** [comment]
Regarding long tag names/multiple tags - they can collapse to tiny label icons or stack like a deck of cards, f.e.: 
![default](https://user-images.githubusercontent.com/38757986/41998803-4ae4bbf6-7a64-11e8-8d83-00580727cd1a.png)
Also, full tag name can be shown only on hovering mouse over it and be truncated to the first letter in icon view.

**Comment by 4ekki** [comment]
Regarding combining tags and search bar, I think these two should work independently - I might want to search specific request within the list that is already filtered by tag. I like the way @dgoosens suggests, this should work fine.

**Comment by 4ekki** [comment]
@gschier, did you have any ideas how to proceed with this one?
