### ISSUE TITLE
[Feature Request] Disable certain requests by environment

### ISSUE THREAD

**Issue by hughgardiner** [getinsomnia/insomnia#1017]
## Details
For many reasons, there are requests that should never be allowed to be made in a Production environment, but are very useful in development/lower environments. It would be nice if you could disable certain requests when a specific environment is set

**Comment by gschier** [comment]
Hmm, it's possible to make a [request hook plugin](https://support.insomnia.rest/article/26-plugins#request-hook-api) that does this.

- Add hook to intercept all requests being sent
- Store regular expression patterns in environment to ignore certain URLs
- From request hook, check for any ignore patterns environment variable
- Compare patters to URL of current request
- If pattern matches, throw an exception (will prevent request from sending)

I imagine an environment that looks something like this:

```json
{
  "IGNORE_PATTERNS": [
    ".*/admin/delete-user",
    ".*/delete-hard-drive"
  ]
}
```

**Comment by 4ekki** [comment]
I've workarounded this with special variable that corrupts hostname for production environments and is empty for test ones: 
![image](https://user-images.githubusercontent.com/38757986/42159601-096cb9b6-7dfd-11e8-9a26-71ef68bcade4.png)

Not very reliable solution, but still it works =)

**Comment by hughgardiner** [comment]
@gschier was able to do so with ease, thanks for pointing me in that direction!

**Comment by gschier** [comment]
Woo, no problem 😊👍

**Comment by Arusey** [comment]
> ## Details
> For many reasons, there are requests that should never be allowed to be made in a Production environment, but are very useful in development/lower environments. It would be nice if you could disable certain requests when a specific environment is set

Would love to know how you fixed this issue

**Comment by ankitkesarwani** [comment]
@gschier 
Is there any way through which I can prevent request without throwing an exception?
Because If I will throw an exception it will remove the response of that request and I want to retain the response of that request.

**Comment by gschier** [comment]
@ankitkesarwani there is no way to "cancel" a response like you are suggesting. You can, however, view older responses using the dropdown in the top-right.

**Comment by ankitkesarwani** [comment]
Okay then what is the way through which I can access those older responses in code?
