### ISSUE TITLE
[Bug] Manage Environments JSON validation needs newline

### ISSUE THREAD

**Issue by iMinnesotan** [getinsomnia/insomnia#1018]
- Insomnia Version: 5.16.6 (5.16.6.2073)
- Operating System: MacOS 10.13.3

## Details

In the Manage Environments dialog I won't see JSON validation errors unless there is a newline at the end of the JSON. I was frustrated that `NaN` was always substituted for keys that contained dashes `-` instead of underscores `_` and it took a while to reveal the problem.

**Comment by gschier** [comment]
Hmm, I can't reproduce this. I see the errors (it's actually a warning) even without a newline.

![image](https://user-images.githubusercontent.com/587576/42057289-e19d46f4-7aea-11e8-8ead-78ebc8505d06.png)

**Comment by iMinnesotan** [comment]
Weird. I was able to change the value in `"hi-there"` without triggering the validation message. I had opened and closed the dialog multiple times but never revealed the message until I added a newline. Not sure how I got things into that state but it was rather stubborn. So, I also cannot force that to happen again.

**Comment by gschier** [comment]
Perhaps it's time to build that error check right into the environment code editor so it's more prominent. I'll see how easy this is to do.

**Comment by gschier** [comment]
Would be nice if it was displayed as a normal JSON validation error

![image](https://user-images.githubusercontent.com/587576/42057691-269264c8-7aec-11e8-955c-2d718252dbd3.png)

**Comment by gschier** [comment]
Hmm, looks like it's non-trivial to do that
