### ISSUE TITLE
[Bug] Overwriting a variable breaks full resolve of variables

### ISSUE THREAD

**Issue by tippl** [getinsomnia/insomnia#1020]
When a variable in sub environment overwrites a variable from base environment, variables used in overwriting variable are not fully resolved by correct priority.

As this is bit hard to explain attaching a test case file: [debug.zip](https://github.com/getinsomnia/insomnia/files/2150028/debug.zip)
(.zip because github doesn't allow .json)

**Comment by gschier** [comment]
I got it working with your test case but also got it working with a slightly more challenging example (See commit for test case)

**Comment by tippl** [comment]
Tested it out too, works perfectly. :+1:

**Comment by gschier** [comment]
Woo! I was afraid that one would be a lot more difficult
