### ISSUE TITLE
[Bug] Union Operator in JSONPath doesn't work as expected

### ISSUE THREAD

**Issue by pyk** [getinsomnia/insomnia#1021]
- Insomnia Version: v5.16.6
- Operating System: macOS 10.13.4

## Details

Union operator in JSONPath doesn't work as expected ([reference](http://goessner.net/articles/JsonPath/)).

Current behaviour:

Query: `$.data.samples[*]['field1','field2']`

Result:
```
[
   "value1entry0",
   "value2entry0",
   "value1entry1",
   "value2entry1",
]
```

expected result:

```
[
   {
       "field1": "value1entry0",
       "field2":  "value2entry0"
   },
   {
       "field1": "value1entry1",
       "field2":  "value2entry1"
   }
]
```

**Comment by gschier** [comment]
I don't see anywhere on that page that specifies the output type. Can you point me to the correct section?

**Comment by 4ekki** [comment]
I believe this is intended behavior, AFAIK JSONPath should return values, not 'key:value' pairs. 
Tried this in a couple of online tools (http://jsonpath.com, http://www.jsonquerytool.com/#/JSONPath), they work that way. 
With union operator: 
![image](https://user-images.githubusercontent.com/38757986/42159257-be2541d6-7dfb-11e8-9966-1a21c502bb60.png)
Just a single filter: 
![image](https://user-images.githubusercontent.com/38757986/42159268-ca5ddb5c-7dfb-11e8-8b20-e24c56ef8194.png)

@pyk, probably, you need to request parent of these fields. Like this: 
![image](https://user-images.githubusercontent.com/38757986/42159319-041500a0-7dfc-11e8-9a60-3d6737198e4f.png)

**Comment by pyk** [comment]
Hi @gschier, I mean the following section:

```
Union operator in XPath results in a combination of node sets. JSONPath allows alternate names or array indices as a set.
```

But I think, I misunderstood the spec. sorry, I will close this issue.

@4ekki hi,I will try that. thanks so much!
