### ISSUE TITLE
[Bug] App shows white screen on startup

### ISSUE THREAD

**Issue by bitshadow** [getinsomnia/insomnia#1022]
- Insomnia Version: 5.16.6
- Operating System: Mac OS Sierra

## Details

```
jignesh@~$ /Applications/Insomnia.app/Contents/MacOS/Insomnia ; exit;
[fix] Running database repairs
Failed to parse zoomFactor TypeError: Cannot read property 'getItem' of null
    at getZoomFactor (/Applications/Insomnia.app/Contents/Resources/app.asar/main.min.js:2277:30)
    at Object.createWindow (/Applications/Insomnia.app/Contents/Resources/app.asar/main.min.js:1953:22)
    at App.module.exports.app.on (/Applications/Insomnia.app/Contents/Resources/app.asar/main.min.js:5848:78)
    at emitTwo (events.js:125:13)
    at App.emit (events.js:213:7)
Failed to parse window bounds TypeError: Cannot read property 'getItem' of null
    at getBounds (/Applications/Insomnia.app/Contents/Resources/app.asar/main.min.js:2259:26)
    at Object.createWindow (/Applications/Insomnia.app/Contents/Resources/app.asar/main.min.js:1954:44)
    at App.module.exports.app.on (/Applications/Insomnia.app/Contents/Resources/app.asar/main.min.js:5848:78)
    at emitTwo (events.js:125:13)
    at App.emit (events.js:213:7)
[main] Loading file:///Applications/Insomnia.app/Contents/Resources/app.asar/renderer.html
[db] Initialized DB at /Users/jignesh/Library/Application Support/Insomnia/insomnia.$TYPE.db
[localstorage] Initialized at /Users/jignesh/Library/Application Support/Insomnia/localStorage
[main] Loading file:///Applications/Insomnia.app/Contents/Resources/app.asar/renderer.html
[updater] Using url https://updates.insomnia.rest/builds/check/mac?v=5.16.6&channel=stable
[updater] Checking for updates url=https://updates.insomnia.rest/builds/check/mac?v=5.16.6&channel=stable
```

That looks like some localstorage issue in the system. any ideas what could be going on there?
`window.localStorage.getItem`

**Comment by gschier** [comment]
Hmm, those errors wouldn't make the app crash, since they're surrounded in a try/catch

https://github.com/getinsomnia/insomnia/blob/develop/packages/insomnia-app/app/main/window-utils.js#L411-L421

Since it's a UI error, you probably want to look in View > Toggle DevTools > Console for errors

**Comment by bitshadow** [comment]
I wasn't able to see any logs in the console. "Reload your app" message was showing up there.

Looks like something related to settings. I followed your instructions from here and It worked.
https://github.com/getinsomnia/insomnia/issues/282#issuecomment-305854828

I will reopen this issue if it comes up again.

**Comment by ViggoV** [comment]
I get a white screen followed by a crash everytime I launch Insomnia, since some point recently.. I suspect it's related to a macos update.

**Comment by NicoSB** [comment]
I have the same problem as @ViggoV but on Windows 10 since the last update. Even installing an older version does not fix the problem.

**Comment by joseffb-mla** [comment]
deleting ~/Library/Application Support/insomnia.Response.db worked for me and saved my history.

**Comment by samarthya** [comment]
Deleting deleting ~/Library/Application Support/Insomnia/insomnia.Response.db worked for me.
