### ISSUE TITLE
[Bug] Error: Unrecognized or bad HTTP Content or Transfer-Encoding

### ISSUE THREAD

**Issue by drpain** [getinsomnia/insomnia#1025]
- Insomnia Version: 5.16.6
- Operating System: Linux (Ubuntu 1804)

## Details
There seems to be a bit of an issue when the Transfer-Encoding response header is set to *

```Error: Unrecognized or bad HTTP Content or Transfer-Encoding``` 

Other clients like Postman, and browsers list Chrome are able to read and display this request.

**Comment by gschier** [comment]
Hmm, ya it seems like a recent version of `libcurl` became more strict about this. Insomnia bumped its `libcurl` version for Windows and Linux recently, which is why this issue came up. At first glance, it doesn't look like there is any option to configure this behavior.

**Comment by Jossnaz** [comment]
@drpain why was this closed?

**Comment by drpain** [comment]
We were doing some non standard HTTP things in our code. The team that was responsible for this piece of software on our side was setting invalid HTTP headers. 

They were setting: `Content-Encoding: *` which is BS.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

**Comment by Jossnaz** [comment]
> We were doing some non standard HTTP things in our code. The team that was responsible for this piece of software on our side was setting invalid HTTP headers.
> 
> They were setting: `Content-Encoding: *` which is BS.
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

problem is I get the same thing when trying to reach a 3rd party end point. Not sure what I can do. Postman seems to return random symbols... probably I can debug it in the browser but its not optimal...

**Comment by janhapke** [comment]
Ran into the same issue while requesting data from a 3rd party endpoint. What helped for me was to go into the Header Tab in insomnia and manually specify `Accept-Encoding`: `gzip, deflate, br`.

Whether that helps probably depends on the 3rd party endpoint, though.
