### ISSUE TITLE
[Bug] JSON is parsed wrong

### ISSUE THREAD

**Issue by Gennnji** [getinsomnia/insomnia#1026]
- Insomnia Version: 6.0.0-beta.1
- Operating System: MacOS High Sierra

## Details

I run my url as usual expecting parsed JSON response, but it become like this:
![image](https://user-images.githubusercontent.com/6366684/42157921-a3d85a56-7df7-11e8-9fb4-6565834f5de8.png)

I expect this:
![image](https://user-images.githubusercontent.com/6366684/42158014-ec5df952-7df7-11e8-86dd-76560915a23f.png)

**Comment by Gennnji** [comment]
Again in 6.0.0-beta.2.2283

**Comment by gschier** [comment]
It looks like you have a missing double quote before the first "A".

**Comment by Gennnji** [comment]
That's not me) It's the result of parsing, I think. But, 6.0.2 fixed it! Great!
