### ISSUE TITLE
[Feature Request] Allow access to cookie value from other domains

### ISSUE THREAD

**Issue by coolhome** [getinsomnia/insomnia#1028]
- Insomnia Version: 5.16.6
- Operating System: Windows 10 64-bit

## Details
Currently, there is no way to use a cookie value from a different domain. You are only able to use cookies from the URL of your request. 

One of our applications uses javascript from the site with the cookie and provides a different backend service with these cookie values via a header.

**Comment by coolhome** [comment]
I was playing with the plugin system and it would be very beneficial if there was a Cookies model I could add or use. I notice theres a cookie jar but to my knowledge there will only ever be one?

![image](https://user-images.githubusercontent.com/700740/42185010-65bf5558-7e15-11e8-94da-66061bc98010.png)

I ended up with a quick non production ready plugin for the mean time.
https://gist.git.labs.bankozarks.com/preston/78a89df1afd0b63b14938298f6d7292e

**Comment by gschier** [comment]
Hmm, that is quite an interesting use case! I think it should definitely be supported. 

I don't have access to view the link you provided, so forgive me if this is the same thing that you did, but it would probably be easy to add an _override url_ parameter to the existing Request => Cookie tag that you provided a screenshot of. 

Although, I agree that it would probably also be good to expose some sort of cookie API for plugins to use.

**Comment by coolhome** [comment]
@gschier I have made the gist public.

**Comment by gschier** [comment]
I still get stuck here 
![image](https://user-images.githubusercontent.com/587576/42196165-7a760ad4-7e4a-11e8-91e5-07358db0f3e7.png)

**Comment by coolhome** [comment]
@gschier I have updated the link to the github gist. Sorry about that. 

I like the idea of adding it to the request plugin but the verbaige on the plugin description is a little weird since it says `current request`.

**Comment by gschier** [comment]
Ya, it would be kind of a "hack" to add it to the current request plugin, now that you mention it. 

Yes! I like the Gist you sent. I think an external cookie jar tag makes a lot more sense. I'll add one tomorrow and get it into the next release.
