### ISSUE TITLE
[BUG] Template Tag double quotes aren't escaped in JSON

### ISSUE THREAD

**Issue by JavaFrame** [getinsomnia/insomnia#1030]
- Insomnia Version: 5.16.6
- Operating System: Ubuntu 16.04 & Windows 7

## Details
If you use a quot (single or double) in a JSONPath in an environment then the json path won't be escaped properly.

For example the JSONPath `$.data[?(@.formName=="EOS-Abnahme Protokoll" && @.versionId==69)]`,
it will translate to 
`"submitionId": "{% response 'body', 'req_525189fc59f842748426b27683438059', '$.data[?(@.formName=="EOS-Abnahme Protokoll" && @.versionId==69)].submissionId' %}"`

Notice the " in the filter. As a workaround, you can change in the preference to the Nunjuck Power User Modus and escape the quots manually, but this requires a restart and it is much more comfortable with the ui (for me at least).

![screenshot2](https://user-images.githubusercontent.com/9285506/42283242-2c5ce740-7fa9-11e8-9a3e-f6946eaaf6e3.png)

I hope this helps.
- Sebastian

**Comment by gschier** [comment]
Ah yes, I think this has been reported before. It's a tricky one to fix properly since the tag editor has no concept of the language that it's being used inside of. Different escaping strategies would be needed for every content-type (JSON, XML, etc).

One workaround for now is to use single quotes instead. These will automatically be escaped at the Nunjucks tag level, ending up with something like this:

```json
"{% response 'body', 'req_525189fc59f842748426b27683438059', '$.data[?(@.formName==\'EOS-Abnahme Protokoll\' && @.versionId==69)].submissionId' %}"
```

**Comment by gschier** [comment]
Hmm, nvm. Apparently escaped single quotes are not valid JSON either 😦

**Comment by relgames** [comment]
Hi, I faced the same issue: can't use single quotes in JSONPath, like $.data['my-test']

Is there a workaround?

**Comment by JavaFrame** [comment]
The only workaround I found (haven't checked since I write the issue) is to switch to the Nunjuck Power User Modus in the settings (a restart is required) and escape it manually and then switch back again.

**Comment by JavaFrame** [comment]
The only workaround I found (haven't checked since I write the issue) is to switch to the Nunjuck Power User Modus in the settings (a restart is required) and escape it manually and then switch back again.

**Comment by soderluk** [comment]
> Hi, I faced the same issue: can't use single quotes in JSONPath, like $.data['my-test']
> 
> Is there a workaround?

@gschier gave me this workaround, that worked:
```
{
  "filter": "$['@something']",
  "testing": "{% response 'body', 'req_abc', filter, 'never' %}"
}
```

**Comment by gschier** [comment]
Also, the fix included in https://github.com/getinsomnia/insomnia/commit/8adee60c8671291712b8ad33f6bbc1e43c453c16 will be released soon!
