### ISSUE TITLE
[Bug] Result preview pane does not refresh when it does not have focus

### ISSUE THREAD

**Issue by mlambley** [getinsomnia/insomnia#1031]
- Insomnia Version:
![image](https://user-images.githubusercontent.com/17264636/42296354-3ca1d9a0-8038-11e8-996d-b892b0a5a7ac.png)
- Operating System: Windows 10

## Details
- Click Send on a url, see the response
- Click into Header to see the headers which were sent to the client
- Change the url to one which will produce a different response
- Press Send
- See the different headers (good!)
- See that the header pane still has focus (great!)
- Click on Preview
- See that it still has the previous response, and that it hasn't updated
- Click Send again while the preview pane has focus
- See that it now updates the response

The Preview pane needs to update even when Header, Cookie, Timeline or any of the other tabs are selected.

But please do not fix this by forcing the preview pane to receive focus every time you click send! I want to able to review the headers generated by different requests without having to click on the header tab after each send.

Thank you.

**Comment by gschier** [comment]
Woah, I can't believe no one has noticed this before. I think this actually has to do with Codemirror not updating when it's not visible. I hope this is an easy one to fix...

**Comment by rickychandra** [comment]
Hi, I would like to work on this. :smile:
