### ISSUE TITLE
[Feature Request] Setting to not automatically suggest values while typing a url

### ISSUE THREAD

**Issue by mlambley** [getinsomnia/insomnia#1032]
- Insomnia Version:
![image](https://user-images.githubusercontent.com/17264636/42296354-3ca1d9a0-8038-11e8-996d-b892b0a5a7ac.png)
- Operating System: Windows 10

## Details
![image](https://user-images.githubusercontent.com/17264636/42297221-3e8c29a6-8041-11e8-99ba-cc44cba55ce7.png)
As I'm typing a url, the above appears. If I press enter in the ~800ms before it appears, it sends the request, which is what I want. Unfortunately if that box appears, pressing enter selects the first option and messes up my url.

Could there be an setting to make it only appear when I press Ctrl+Space?

**Comment by gschier** [comment]
Sure, this sounds like it would be useful to the general userbase. It would probably be best to have a setting to control the completion delay (with 0 meaning never). We could also change the number of match characters required for it to show automatically.

I won't have time to work on this right away but here's where the delay logic lives if you, or someone from the community, wants to work on it first

https://github.com/getinsomnia/insomnia/blob/26e9b646bd8f6ff0049b9fec71332fd66ae451c1/packages/insomnia-app/app/ui/components/codemirror/extensions/autocomplete.js#L152-L155

**Comment by antimodern** [comment]
How come this isn't resolve yet? This auto completion is driving me nuts! :smile:

**Comment by mlambley** [comment]
I'm not too familiar with Node and Gregory has enough on his plate I
suppose. Holding out for someone in the community to pick this one up.

**Comment by mlambley** [comment]
I didn't notice there was a PR already
It was opened less than a week ago. Chill homie.

**Comment by gschier** [comment]
Haha, ya, it was the holidays! Merged now 😄
