### ISSUE TITLE
[Feature Request] Save response into template

### ISSUE THREAD

**Issue by Leandros** [getinsomnia/insomnia#1033]
The following scenario: 

An authenticated API. Every request requires an `Authorization` header (for example a JWT bearer token). A `/login` endpoint is used to login and obtain a JWT. 

Every single time I want to use the API I have to copy the JWT from the response into the template to be used by the other requests. It would be great if a template could be updated by a response of an executed query.

**Comment by Leandros** [comment]
This is awesome! Thanks. Love Insomnia. Great work. 😍

**Comment by gschier** [comment]
🤗
