### ISSUE TITLE
[bug] OAuth2  Implicit grant type without  "prompt=none" parameter.

### ISSUE THREAD

**Issue by keklabs** [getinsomnia/insomnia#1037]
- Insomnia Version: 5.16.6
- Operating System: Windows10

## Details

When I try to use OAuth2 authetication configuration with  GRANT TYPE:  Implicit,  the request from Insomnia is send with  "prompt=none"  parameter.  This blocks the opening of Browser popup window, so it is not possible to  authenticate to OpenIdConnect server with my credentials.

**Comment by gschier** [comment]
Hmm, as far as I know, Insomnia does not supply a `prompt` parameter anywhere. Where are you seeing this?
