### ISSUE TITLE
[Feature request]  - OAuth2  - support for  discovery standard

### ISSUE THREAD

**Issue by keklabs** [getinsomnia/insomnia#1038]
- Insomnia Version: 5.16.6
- Operating System: Windows10

## Details

Please add support for OAuth2  discovery support to simplify OAuth2  authentication configuration by one URI.

https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig

Then we can use following URIs for configuration of endpoints, like:

https://accounts.google.com/.well-known/openid-configuration
https://login.microsoftonline.com/common/.well-known/openid-configuration

**Comment by RichiCoder1** [comment]
Resurrecting this issue. Especially when using OpenID, it'd be nice to specify the Issuer rather than each url.
