### ISSUE TITLE
Not starting if not in admin mode?

### ISSUE THREAD

**Issue by jholovacs** [getinsomnia/insomnia#1040]
The only way I can get Insomnia to start on my PC is if I run as a local administrator.  What could cause that?

**Comment by gschier** [comment]
I'm not sure. What errors are you seeing when you don't?

**Comment by jholovacs** [comment]
No errors; it just doesn't start.  click/ doubleclick the shortcut, nothing
happens.  Right-click, Run as Administrator, it runs fine.

**Comment by gschier** [comment]
Are there any errors if you launch it from the command prompt?

**Comment by jholovacs** [comment]
I found the problem when I tried to run from the command prompt.

For some reason, I was not the owner of my AppData folder.  I got an access
denied.  Very weird.  Once I reset my AppData folder security, it runs fine.

**Comment by gschier** [comment]
Awesome! 😄
