### ISSUE TITLE
[Bug] character omitted if followed by a special character in preview mode

### ISSUE THREAD

**Issue by DiederikvandenB** [getinsomnia/insomnia#1048]
- Insomnia Version: v6.0.0-beta.1
- Operating System: 10.13.4

## Details
Hi!

I ran in to a bug when previewing my response in the preview or the source code preview modes. When the response contains strings containing a special character (like é or €), the character preceding it will be omitted. See the example below. The name should be "Grand Café" and the price string is missing the space between the "r" and the "€".

When I select the raw preview mode I get these values:
`"name":"Grand Caf\u00e9"`
`"price_string":"2 voor \u20ac12,50"`

So the response from the server is correct.

```
{
	"data": {
		"overview": [
			{
				"name": "Grand Caé",
				"deals": [
					{
						"is_redeemable": true,
						"price_string": "2 voor€12,50"
					}
				]
			}
		]
	}
}
```

Cheers!

**Comment by gschier** [comment]
Fixed this in https://github.com/getinsomnia/insomnia/commit/3d73cfa2a8236ed162a08c0588fdc2c4ad7a2d7a
