### ISSUE TITLE
[Feature Request] - Make URLs in headers clickable

### ISSUE THREAD

**Issue by lyrixx** [getinsomnia/insomnia#1050]
- Insomnia Version:
>Version 5.16.6
>Shell 1.8.4
>Node 8.2.1
>V8 5.9.211.38
>Architecture x64
- Operating System: 
>Ubuntu 18.04

## Details

Hello. I'm using Symfony to build my API, and Symfony uses Headers to set a link [to the debug panel](https://symfony.com/blog/new-in-symfony-2-4-quicker-access-to-the-profiler-when-working-on-an-api).

So, it would be awesome to be able to click on such value.

![image](https://user-images.githubusercontent.com/408368/42943412-f9797774-8b62-11e8-90b0-81a9399370ed.png)

**Comment by lyrixx** [comment]
Oh no, dont't close it please, Mr `@stale` Bot

**Comment by gschier** [comment]
Won't be closed now!

**Comment by gschier** [comment]
Also, I think this would be a great little feature to add 😄

**Comment by lyrixx** [comment]
Thanks

**Comment by KarthikSiddarth** [comment]
Hi Guys,
I have started working on implementing this feature, will update you guys once I complete it.
Thanks.
