### ISSUE TITLE
[Feature Request] Add ability to set environmental variable via Request/Response Hooks

### ISSUE THREAD

**Issue by FrostxPhoenix** [getinsomnia/insomnia#1051]
Insomnia Version: 5.16.6
Operating System: Windows 10

I have API calls that require an access token in the header. However this access token can be attained with a variety of different API calls. Therefore, I only have two options currently: force myself to use one api call (which is a security risk as some users shouldn't have access) or have 4+ of the same Authorization headers and toggle them off an on depending on use-case.

I believe it would be far easier if there was a way to set an environmental variable similar to how you can get an environmental variable.

**Comment by hughgardiner** [comment]
I've run into the same issue where I have multiple of the requests with different JSON bodies, and would love it if each of these requests could populate an environment variable via a Response Hook

**Comment by gschier** [comment]
This seems like a good thing for plugins to be able to do!

**Comment by ayozebarrera** [comment]
Looking for the same feature! would be great
