### ISSUE TITLE
[Feature Request] Allow JSON objects in request body

### ISSUE THREAD

**Issue by z-ax** [getinsomnia/insomnia#1057]
- Insomnia Version: 5.16.6 (5.16.6.2073)
- Operating System: macOS

## Details

I need to use the same `acquirer` object for each request (among other parameters and not it the root of the request body). And it can be changed with Environment.
Pretty weird that I can't pass the object simply as is (it becomes `[object Object]`).

And another weird thing. If I pass variables into JSON body I still have to have quotes around the variable, like `"{{acquirer}}"` to make JSON valid.

Can't just use `JSON.stringify()` to avoid this kind of weirdness and a valid JSON sent into JSON Body? :)

The only way to use it now is to do pretty weird stuff, like on the screenshot attached - per-property variables. If I have to do this for each request it is very redundant.

<img width="242" alt="image" src="https://user-images.githubusercontent.com/1391015/43132260-e2606ff4-8f43-11e8-9969-492a2bce08ef.png">

**Comment by gschier** [comment]
You can stringify using the Nunjucks `dump` filter like `{{ acquirer | dump }}`. You'll sell get a syntax error warning but you can ignore it (there's another issue for that somewhere).

**Comment by z-ax** [comment]
@gschier yes, thank you! But out-of-the box support for this kind of stuff would be very nice :)
