### ISSUE TITLE
[Feature Request] -  Add CoAP protocol support

### ISSUE THREAD

**Issue by AndreMaz** [getinsomnia/insomnia#1059]
This is a feature request to add support for [CoAP protocol](http://coap.technology/).
CoAP can be seen as a lightweight version of HTTP that is specially designed for Internet of Things. 
**Detail**
Since the Web of Things is becoming *the thing* (pun intended) (examples: [W3C](https://www.w3.org/WoT/WG/), [Mozilla IoT](https://iot.mozilla.org/), [OCF](https://openconnectivity.org/)) where even constrained devices expose their data though REST APIs it becomes necessary to have a reliable testing tool. However, to this date, there is none. So adding CoAP support would be a really great feature.

**Who will benefit from this feature?**
Pretty much everyone who is working on IoT and wants to test their CoAP-based REST APIs.

**How Insomnia will benefit from this feature?**
CoAP support will expand the Insomnia's user base. 
For example,  the OCF, a consortium supported by [major IT players](https://openconnectivity.org/foundation/membership-list)), relies heavily on CoAP protocol. Therefore, everyone who is working with OCF's data model would gladly use Insomnia Client.

**Changes affected by this feature**
All changes will be under the hood so there are no GUI changes

**Is it stable?**
Yes, the CoAP was standardized in 2014 and since then hasn't changed.

**Comment by gschier** [comment]
Sorry I didn't see this sooner. Insomnia uses `libcurl` for networking so it's basically up to Curl to add support for it. It looks like there is some talk already but I don't see this happening for a while: https://curl.haxx.se/mail/lib-2016-06/0027.html
