### ISSUE TITLE
Cursor doesn't appear in text boxes

### ISSUE THREAD

**Issue by KevinSnyderCodes** [getinsomnia/insomnia#1061]
- Insomnia Version: 6.0.0.2287
- Operating System: macOS 10.13.5

## Details

The cursor doesn't appear in various text boxes under the request editor.

Video demonstration: https://gfycat.com/AbsolutePerfectBoto

There may be other places where this is happening, but these are the ones I've encountered.

**Comment by gschier** [comment]
Hmm, this seems to only be happening on the production build. Will get this fixed tomorrow.

**Comment by yura3d** [comment]
I have the same behaviour on Windows 10.

**Comment by zhuSilence** [comment]
Yeah, I changed the theme then I found the cursor finally. Thanks!

**Comment by gschier** [comment]
It's fixed in 6.0.1
