### ISSUE TITLE
Broken changelog

### ISSUE THREAD

**Issue by maxime1992** [getinsomnia/insomnia#1062]
https://insomnia.rest/changelog/6.0.0

![image](https://user-images.githubusercontent.com/4950209/43164093-1e2930e0-8f88-11e8-90f8-bd25999e59a7.png)

**Comment by gschier** [comment]
Hmm, works for me!

**Comment by maxime1992** [comment]
@gschier weird. I just checked again and still the same :man_shrugging: 

Anything I can do to help narrowing down the problem?

**Comment by gschier** [comment]
It might be cached in your region from before it went live. 

I just cleared the cache. Did that help for you?
