### ISSUE TITLE
[Bug] Prompt with default doesn't prompt when expected

### ISSUE THREAD

**Issue by jsolt** [getinsomnia/insomnia#1063]
- Insomnia Version: 6.0.0
- Operating System: Windows 10

## Details

I just got updated to v6.0 and my prompts with default values have stopped prompting.

1. Create a request with no prompt
1. Add a prompt
1. Send the request, fill in the prompt window
1. Edit the prompt and add a default value
1. Send the request, the prompt doesn't open
1. Edit the prompt and remove the default value
1. Send the request, the prompt doesn't open

**Comment by jsolt** [comment]
Update, after playing around a little the behavior is a little more nuanced

The actual behavior I'm seeing is a sort of "caching" experience
1. Create a request with no prompt
1. Add a prompt
1. Send the request, fill in the prompt window
1. Edit the prompt and add a default value
1. Send the request, the prompt doesn't open
1. **Send the request, the prompt opens.**
1. Edit the prompt and remove the default value
1. Send the request, the prompt doesn't open
1. **Send the request, the prompt opens.**

I also see the caching behavior if I switch environments
1. On a request that has a prompt send the request, fill in the prompt
1. Change the environment
1. Send the request, the prompt doesn't open
1. Send the request, the prompt opens

**Comment by DazedNConfused-** [comment]
Chiming in because I have this exact same issue, which has rendered the 'prompt' template tag useless for _prompt-once_ scenarios.

This behavior started with the 6.0 update.

**Comment by gschier** [comment]
Will be fixing this soon

**Comment by jsolt** [comment]
Any update on this? I'm really excited to have this back :)

**Comment by gschier** [comment]
Sorry, I've been away for a bit due to personal issues. Back now though and will try to get this done this week!

**Comment by DazedNConfused-** [comment]
Have there been any updates on this issue? Since the update of July this feature has been disabled in the practical sense (and the early Beta releases have not addressed it either). 

With large collections with multiple prompts (whose values change in a daily basis), the current state of affairs is highly disruptive to a normal test workflow, to the point of almost being unbearable.

**Comment by jsolt** [comment]
Has this been released? I see it was closed, but I'm still not seeing prompts if I have a default selected.

OS: Windows 10
Insomnia: 
Version 6.2.0
Shell undefined
Node 10.2.0
V8 6.6.346.32
Architecture x64

libcurl/7.57.0-DEV
OpenSSL/1.0.2o
zlib/1.2.11
libssh/1.7.0_DEV
