### ISSUE TITLE
[Question] Grab a specific JSON value based on another key?

### ISSUE THREAD

**Issue by joemonk** [getinsomnia/insomnia#1064]
- Insomnia Version: 5.16.6
- Operating System: Windows 10 Professional

## Details
I have been toying with the template tags as well as a little Nunjucks customizing but I can't figure out how to do something, if it is possible in Insomnia.

What I would like to do is grab a value from a JSON formatted response based on a key and use this like a variable.

For example, what I have is a response from a previous GET servers and I would like to retrieve the id value for a server which has the name 'server001'. I can do this using:

`
{% response 'body', 'req_b98399ff1a8d4c20b96989274406ccf0', '$.servers[?(@.name == "server001")].id' %}
`
which returns:
ace90bc0-cdc6-44c6-8315-9d86826e5c03

This would work except that I would like to be able to either get a prompt for server name so that I don't have to hardcode this. Or if a variable could be used in place of it perhaps.

Not sure if this is something that is intended or not but it would definitely save me a lot of time in my day.

Love the application by the way, keep up the good work!

**Comment by gschier** [comment]
I haven't tested this, but you may be able to take advantage of Nunjuck's string concatenation.

Possibly create a new environment variable `"server": "{% prompt ... %}"`, then change your response tag to something like `{% response 'body', 'req_b98399ff1a8d4c20b96989274406ccf0', '$.servers[?(@.name == "' + server + '")].id' %}`

**Comment by joemonk** [comment]
Hey, this works great except that I can't seem to find any working example of the prompt. This definitely sends the request I would like but I never get prompted to enter anything. Is there some doc or anything related to prompt syntax?

**Comment by gschier** [comment]
There seems to be a bug in the latest update related to the prompt #1063
