### ISSUE TITLE
[Feature Request] Base64 Decode response or specific response field

### ISSUE THREAD

**Issue by SyedWasiHaider** [getinsomnia/insomnia#1065]
## Details

Would be awesome if you could base64 decode some string field 

like base64($.store.books.author)

**Comment by ColDog** [comment]
Hey this would be great actually, I would be open to making a PR for this as well if this is a desirable feature.

**Comment by Robert430404** [comment]
@gschier Is there some interest in merging a feature like this into core? I would like to develop something to make this available since my company has base64 encoded response values.

If you would be open to merging it in, I'd invest the time in developing it.

**Comment by gschier** [comment]
I do have interest into supporting this in Insomnia but I think the solution should be generic enough to handle more than just base64 decoding. I've thought about providing an additional filter type that can execute arbitrary JS but that could open up potential security issues.

For now, I would recommend forking the Insomnia Response Tag plugin and extending it to suit your needs.
