### ISSUE TITLE
[Bug] - Insomnia 6.0 JSON beautify break with HTML fields

### ISSUE THREAD

**Issue by julienperrault** [getinsomnia/insomnia#1067]
Hi, 
I just update my Insomnia version to 6.0. But something is wrong : when you get a JSON response with a HMTL field, the preview tab do weird things. 

Look at it : 

- A previous version of Insomnia : ![a previous version of Insomnia](https://user-images.githubusercontent.com/16414614/43187466-bda029a8-8ff1-11e8-8d74-174d6c79796e.PNG)
- In Insomnia 6.0 ![Insomnia 6.0](https://user-images.githubusercontent.com/16414614/43187465-bd802716-8ff1-11e8-8e29-37848d60a4b3.PNG)

## Configuration
- Insomnia Version: 6.0
- Operating System: Windows 10 Pro

## Details
Return in a JSON, a field with HTML tag on it.

**Comment by julienperrault** [comment]
You can test with this a GET on this URL : http://www.elysee.fr/chronologie/download/json
Look at entity 18628 or 18414.

**Comment by gschier** [comment]
Oh, this was fixed a while ago
