### ISSUE TITLE
[Bug] List of requests is scrolled to the bottom when moving the mouse cursor while scrolling the list with mouse wheel

### ISSUE THREAD

**Issue by 4ekki** [getinsomnia/insomnia#1072]
- Insomnia Version: 6.0.0
- Operating System: Windows 10

## Details
[Bug] List of requests is scrolled to the bottom when moving the mouse cursor while scrolling the list with mouse wheel

S2R: 
1. Have a long list of requests to enable vertical scrollbar 
2. Scroll the list to the bottom
3. Use mouse wheel to scroll the list upward, don't move the mouse 
4. Use mouse wheel to scroll the list upward, move the mouse while spinning the wheel

As a result, on s.3 the list is scrolled fine while on s.4 the list of requests is reset to the very bottom. 

Also reproducable when scrolling downward, but is less noticeable in this case. 
See the example on the gif - during the first two scrolls I keep the cursor stable and move it on 3+ iteration: 
![gif](https://user-images.githubusercontent.com/38757986/43204731-592e6c58-902a-11e8-8536-5049cf27636c.gif)

**Comment by 4ekki** [comment]
@gschier, this one is back in 6.5.0

**Comment by gschier** [comment]
Will take a look. The sidebar did change a bit to accommodate the new request pinning feature 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by develohpanda** [comment]
Hmm @4ekki are the reproduction steps the same this time around? I installed 6.5.3 fresh and can't seem to reproduce it. 😄

**Comment by 4ekki** [comment]
Doesn't reproduce in 6.5.1 and 6.5.3, looks like it was fixed.

**Comment by gschier** [comment]
Glad it's fixed! I don't remember fixing this on purpose 🤣
