### ISSUE TITLE
Preview Json garbled

### ISSUE THREAD

**Issue by tony-zxw** [getinsomnia/insomnia#1076]
- Insomnia Version: 6.0.0
![version](https://user-images.githubusercontent.com/15209334/43241177-99effcaa-90cc-11e8-975d-b49d006cd2c9.png)

- Operating System: Windows 10
![os_version](https://user-images.githubusercontent.com/15209334/43241315-4bb5df36-90cd-11e8-9da9-cff7998c9fec.png)

## Details
![error1](https://user-images.githubusercontent.com/15209334/43241398-ca0e2cee-90cd-11e8-89f6-d700d0632b0d.png)

RawData: {"code":1000,"message":"id\u4e0d\u5b58\u5728"}

**Comment by DmitriyD** [comment]
Yeah, same here with cyrillic unicode characters. Escape sequences are visible but shouldn't.

**Comment by gschier** [comment]
Fixed by https://github.com/getinsomnia/insomnia/commit/9e1af8952c7e39fe7082a7b7b4fa439cb751fce8
