### ISSUE TITLE
[Improvement] Dark text cursor is hard to spot on dark themes

### ISSUE THREAD

**Issue by steffenagger** [getinsomnia/insomnia#1078]
- Insomnia Version: 6.0.1
- Operating System: macOS High Sierra (10.13.6)

## Details

On Mac (black cursors by default), the text cursor can be quite hard to spot when using dark themes.

![image](https://user-images.githubusercontent.com/5254755/43258648-cdba9412-90d3-11e8-9d5c-a58706dec711.png)

A solution for electron apps is currently in vscode: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/lines/viewLines.css#L42

I only noticed this after themes were made free for all (which is awesome btw!). And I believe this to be primarily a Mac/Linux issue (maybe if you opt in to dark cursors on windows?).

Thanks for a nice app/tool!

**Comment by steffenagger** [comment]
After upgrading to macOS Mojave (10.14), the default text cursor now supports dark themes out of the box (I wonder why 😄).

**Comment by gschier** [comment]
Oh yes! That looks way better now. Going to close this issue then 👍 😄
