### ISSUE TITLE
6.0.1 still shows UTF-8 escapes in GraphQL mode

### ISSUE THREAD

**Issue by yura3d** [getinsomnia/insomnia#1079]
- Insomnia Version: 6.0.1
- Operating System: Windows 10

## Details

In 6.0.0 all responses was contained UTF-8 escapes because of issue.
In 6.0.1 this issue was fixed for HTTP queries, but it still remains for GraphQL queries.

My screen:
![image](https://user-images.githubusercontent.com/10958696/43261186-8503c818-90e4-11e8-852d-b7d4eb6e2374.png)

**Comment by gschier** [comment]
Closed by https://github.com/getinsomnia/insomnia/commit/9e1af8952c7e39fe7082a7b7b4fa439cb751fce8
