### ISSUE TITLE
[Bug] Content type of Response is lost

### ISSUE THREAD

**Issue by Djaler** [getinsomnia/insomnia#1080]
- Insomnia Version: 6.0.0
- Operating System: Debian 9

## Details

I have one request, which response is a binary data (application/octet-stream). I want to resend this binary data as one of field of another request (multipart/form-data). And I pick entire response body using function. But this field is treated as a string, not a bytes.
This is what I see in request body:
```
| --X-INSOMNIA-BOUNDARY
| Content-Disposition: form-data; name="data"
| e��~��d��/^(S��<�`y��i�;R
| --X-INSOMNIA-BOUNDARY--
```
There are no content-type for part.

Instead, if I export response to file, and then pick it request, all works good. And this is what I see in request body:
```
| --X-INSOMNIA-BOUNDARY
| Content-Disposition: form-data; name="data"; filename="CipherBinary_symmetric-1532611513940.bin"
| Content-Type: application/octet-stream
| e��~��d��/^(S��<�`y��i�;R
| --X-INSOMNIA-BOUNDARY--
```

**Comment by Djaler** [comment]
The issue is still there. No need to close this

**Comment by gschier** [comment]
Hmm, this may actually be fairly difficult to do. Currently, template tags have no way to store binary data. It's converted to a string during the Nunjucks template render and then assumed a string from then on.
