### ISSUE TITLE
[Feature Request] Invalid JSON error message should include line number

### ISSUE THREAD

**Issue by jhalterman** [getinsomnia/insomnia#1082]
Insomnia 6.0.1

## Details

I noticed that the work space editor has a JSON validator that spits out an error message like `Unexpected token } in JSON at position 199`. Overall this isn't that useful. It would be better if the line number could be mentioned along with the column (if possible).

**Comment by gschier** [comment]
What do you mean when you say workspace editor? Can you provide a screenshot?

**Comment by jhalterman** [comment]
Sorry - I meant environment editor :)

<img width="816" alt="screen shot 2018-07-26 at 6 55 22 pm" src="https://user-images.githubusercontent.com/228804/43297321-79a5e91c-9105-11e8-8af7-08856c388161.png">

**Comment by gschier** [comment]
Good point. I wonder how hard that is to do.

FYI the error also shows inline in the environment JSON

![image](https://user-images.githubusercontent.com/587576/43302001-090b385c-911d-11e8-9a0b-314bf4453b0a.png)

**Comment by jhalterman** [comment]
Ah cool, didn't notice that 👍
