### ISSUE TITLE
[Bug] Nested variables do not work in the Base Environment

### ISSUE THREAD

**Issue by jhalterman** [getinsomnia/insomnia#1083]
Insomnia 6.0.1

## Details

It appears that nested variables do not work when defined in the Base Environment:

```json
"db": {
  "password": "foo"
}
```

`{{ db.password }}` yields `attempted to output null or undefined value.`

Workaround is to define nested variables inside of each environment.

**Comment by gschier** [comment]
I have a feeling you're probably overwriting the `db` property in a sub environment (?)

Note: environments are joined using a shallow merge.

**Comment by jhalterman** [comment]
I am using the same nested structures in the Base environment and sub-environments. I was assuming that sub-environments would be deep merged on top of the base.

**Comment by gschier** [comment]
No, it's a strict overwrite, unfortunately

**Comment by jhalterman** [comment]
Any reason why it shouldn't be a deep merge? It makes the nested environment variables less useful if they can't be abstracted to the base environment and overridden where needed.

**Comment by gschier** [comment]
There are pros and cons to both methods. Shallow merge was chosen at the beginning so that's what it is. It would be difficult to change now without breaking existing users setups

**Comment by jhalterman** [comment]
I'm actually not sure this would break anyone. If `db.password` in the base environment suddenly starts working, sub-environments that currently use that variable would still override it.

**Comment by gschier** [comment]
There are many other use cases, many of which we can't even imagine.

One example is if someone includes a user object in a base environment and overrides it in a sub environment with different keys. Perhaps they are serializing it to JSON and sending it in the request body.
