### ISSUE TITLE
[Bug] Decorated type deeper than introspection query

### ISSUE THREAD

**Issue by tkallioras** [getinsomnia/insomnia#1086]
- Insomnia Version: 6.0.0
- Operating System: macOS 10.14

## Details

I have a data structure that corresponds to GeoJSON Multipolygon, which is:

[[[[Float!]!]!]!]!

However I get the error: decorated type deeper than introspection query

I presume it has to do with the nested array. Is there a way to introspect this kind of data structure, or to not lose introspection on the whole graph?

Here is a type with a field (multipolygon) that produces the issue

type GeoJSON {
  type: String!
  boundingbox: [Float!]
  point: [Float!]
  multipoint: [[Float!]!]
  linestring: [[Float!]!]
  multilinestring: [[[Float!]!]!]
  polygon: [[[Float!]!]!]
  multipolygon: [[[[Float!]!]!]!]
}
The problem starts on field multipolygon. If I erase this, everything works the way it should.

**Comment by gschier** [comment]
That's an interesting one. It looks like this might be solved by updating our graphql dependency (Insomnia does not deal directly with introspection queries).
