### ISSUE TITLE
[Bug] - Post / Patch requests with AWS IAM v4 headers fail

### ISSUE THREAD

**Issue by 6wl** [getinsomnia/insomnia#1089]
- Insomnia Version: 6.0.1
- Operating System: Fedora 28

## Details
Use the AWS IAM v4 auth type to make a GET request to an execute-api type request
Notice the request works, and signature is generated with SignedHeaders=host;x-amz-date,
Now make a post or patch request.
This fails due to signature.  Suspect its something in the generation is incorrect, SignedHeaders=content-length;content-type;host;x-amz-date,

## Notes
This is a regression from 5.16.2 in which it was working

**Comment by gschier** [comment]
I think that should do the trick ^

**Comment by gschier** [comment]
Important line being https://github.com/getinsomnia/insomnia/commit/7af8514e424556d5d5c88505815b7b3b3e75d9ec#diff-e62f6f04cd81b19a422e5be246248e92R1011

**Comment by 6wl** [comment]
Verified working.  Thanks for the fix.

**Comment by gschier** [comment]
Nice, thanks for testing that. Will be released today
