### ISSUE TITLE
[Distribution] No 6.0.1 in Snap

### ISSUE THREAD

**Issue by Djaler** [getinsomnia/insomnia#1090]
There are not 6.0.1 update in Snap

**Comment by Gabb1995** [comment]
can confirm, didnt get 6.0.1 either.

**Comment by gschier** [comment]
Snapcraft did something that broke the build. Haven't been able to fix it yet

**Comment by gschier** [comment]
Working on this one today

**Comment by gschier** [comment]
In summary, the Snapcraft server seems to have been upgraded, which caused the packaging method of `electron-builder` to generate a binary with an unexpected signature. 

I've upgraded `electron-builder` locally but that seems to have broken A LOT of stuff.

**Comment by gschier** [comment]
Related https://github.com/electron-userland/electron-builder/commit/cb5034d

**Comment by gschier** [comment]
Should be live now!

![image](https://user-images.githubusercontent.com/587576/43600707-3260c10e-9640-11e8-9ca9-abd5de870fc3.png)
