### ISSUE TITLE
[Bug] filter response body line is too small

### ISSUE THREAD

**Issue by carmineesposito73** [getinsomnia/insomnia#1093]
## Versions
```
$ snap list insomnia 
Name      Version  Rev  Tracking  Publisher    Notes
insomnia  6.0.0    17   stable    gschier1990  -

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
```
## Details
The filter response body line (lower right corner) is too small, so the upper part of the filter string is cut.
I haven't find a way to resize it.

![insomnia-xpath-filter](https://user-images.githubusercontent.com/38761873/43450304-becab3e6-94b2-11e8-8ab4-4ab0fba493a0.png)

**Comment by Gabb1995** [comment]
Same happens with Search in response
![screenshot from 2018-08-02 17 18 28](https://user-images.githubusercontent.com/20728259/43593486-2ba05c2a-9678-11e8-8c53-f31a05b923bf.png)

**Comment by gschier** [comment]
So probably all inputs then? I think it may be related to the font used on Ubuntu

**Comment by Gabb1995** [comment]
Havent been able to replicate it in other inputs just these two.

**Comment by carmineesposito73** [comment]
I don't know when, but the issue disappeared

$ snap list insomnia 
Name      Version  Rev  Tracking  Publisher    Notes
insomnia  6.0.2    19   stable    gschier1990  -

$ cat /etc/*rel*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10

**Comment by carmineesposito73** [comment]
I don't know when, but the issue disappeared

$ snap list insomnia 
Name      Version  Rev  Tracking  Publisher    Notes
insomnia  6.0.2    19   stable    gschier1990  -

$ cat /etc/*rel*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10

**Comment by carmineesposito73** [comment]
I don't know when, but the issue disappeared

$ snap list insomnia 
Name      Version  Rev  Tracking  Publisher    Notes
insomnia  6.0.2    19   stable    gschier1990  -

$ cat /etc/*rel*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
