### ISSUE TITLE
[Bug] Bearer Auth does not get reset when disabling Auth

### ISSUE THREAD

**Issue by jonasbrenig** [getinsomnia/insomnia#1095]
[Bug] – Bearer Auth does not get reset when disabling Auth

After switching through multiple Auth-methods and finally disabling Autho completely,
the API-response was still unauthenticated.
I found out that the previously selected Bearer Auth was still active, even though Auth was disabled completely at that time.
(see Screenshot)

- Insomnia Version: v6.0.1
- Operating System: Windows 10 Pro 
Version 10.0.17134 Build 17134

![image 3](https://user-images.githubusercontent.com/41997211/43520887-9f5e0a7a-9594-11e8-9122-ed784fdf89fd.png)

**Comment by gschier** [comment]
Your screenshot is of the Headers tab, which shows the headers that your server responded with. That header is your server's way of telling you that you supplied the wrong token (or no token in this case).

You can see the actual request headers in the Timeline tab.

**Comment by gschier** [comment]
Going to close this one as it seems like it's related to your server, not the app.
