### ISSUE TITLE
[Bug] Blank Screen on Request Centos Tar Install 6.0.1

### ISSUE THREAD

**Issue by jidol** [getinsomnia/insomnia#1096]
[Bug] – Each request I send seems to send then blanks the whole screen to white.

- Insomnia Version: 6.0.1
- Operating System: CentOS 7

## Details
Any request results in the screen going blank to white.  
Started on version 5.16.6 and upgraded due to the issue but it is still happening.

**Comment by gschier** [comment]
Can you post the output from View > Toggle DevTools > Console?

**Comment by jidol** [comment]
It just posts that it has disconnected.

**Comment by jidol** [comment]
![screenshot from 2018-08-01 13-53-19](https://user-images.githubusercontent.com/3466376/43545137-489ca720-9592-11e8-973b-53a4bbe710a3.png)

**Comment by jidol** [comment]
Interestingly I ran a different endpoint and it works which makes me think it is special to the error returned perhaps.

**Comment by jidol** [comment]
Curl of the command returns as

<html>Moved <a href="https://<address>/status">HERE</a> permanently, use https please</html>

**Comment by loconox** [comment]
Hi, not sure if it's the same issue, but I also have a blank screen.

Version 6.0.1
Shell 1.8.7
Node 8.2.1
V8 5.9.211.38
Architecture x64

libcurl/7.59.0 OpenSSL/1.1.0h zlib/1.2.11 nghttp2/1.31.1

Error in console : 
```
/opt/Insomnia/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16634 Download the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
bundle.js:1076 [db] Initialized DB client
bundle.js:6421 Uncaught (in promise) TypeError: Cannot read property 'show' of undefined
    at showModal (bundle.js:6421)
    at showError (bundle.js:6417)
    at _traversePluginPath (bundle.js:24799)
    at getPlugins (bundle.js:24839)
    at <anonymous>
```

**Comment by loconox** [comment]
Hi, not sure if it's the same issue, but I also have a blank screen.

Version 6.0.1
Shell 1.8.7
Node 8.2.1
V8 5.9.211.38
Architecture x64

libcurl/7.59.0 OpenSSL/1.1.0h zlib/1.2.11 nghttp2/1.31.1

Error in console : 
```
/opt/Insomnia/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:16634 Download the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
bundle.js:1076 [db] Initialized DB client
bundle.js:6421 Uncaught (in promise) TypeError: Cannot read property 'show' of undefined
    at showModal (bundle.js:6421)
    at showError (bundle.js:6417)
    at _traversePluginPath (bundle.js:24799)
    at getPlugins (bundle.js:24839)
    at <anonymous>
```

**Comment by loconox** [comment]
BTW, I've installed Insomnia from Snap (version 6.0.0) and it's working.

**Comment by gschier** [comment]
@loconox looks like a plugin is causing an error for you. You aren't, by any chance, using the XDebug plugin are you? (that one had an issue last week)

**Comment by loconox** [comment]
@gschier You are right, I removed the xdebug plugin and it's working. Thanks

**Comment by gschier** [comment]
I think it's fixed now if you want to reinstall it

**Comment by Navds** [comment]
Hi @gschier, how did it get fixed ? I have the same issue with  AppImage installation in #976

**Comment by jidol** [comment]
I also don't understand what fix was applied since this was initially my report.

**Comment by gschier** [comment]
Sorry, closed due to previous comment but didn't realize that wasn't the original issue
