### ISSUE TITLE
[bug]Json unicode decode error

### ISSUE THREAD

**Issue by isatiso** [getinsomnia/insomnia#1098]
- Issue #1088
- Insomnia Version: 6.0.1
- Operating System: Windows 10

## Details

similar to issue #1088 
Issue still here after isomnia update to version 6.0.1:

```
{
	"status": 1001,
	"msg": "可\u8fdb行\u5355笔\u9ad8于2K或\u7d2f计\u4ea4易\u91d1额\u5927于5W的\u4ea4易",
	"data": {}
}
```

want it like this:

```
{
	"status": 1001,
	"msg": "可进行单笔高于2K或累计交易金额大于5W的交易",
	"data": {}
}
```

raw data:

```
{"status": 1001, "msg": "\u53ef\u8fdb\u884c\u5355\u7b14\u9ad8\u4e8e2K\u6216\u7d2f\u8ba1\u4ea4\u6613\u91d1\u989d\u5927\u4e8e5W\u7684\u4ea4\u6613", "data": {}}
```

It seems like every two charactors that one of them miss-decode.

**Comment by gschier** [comment]
This was fixed but is not yet deployed. Will be in 6.0.2

**Comment by gschier** [comment]
6.0.2 is released now
