### ISSUE TITLE
[Question] Requests to API Gateway on custom domain result in 403 error

### ISSUE THREAD

**Issue by SpaceHeroGuide** [getinsomnia/insomnia#1099]
I'm not sure if it's a misconfiguration by me or a bug. Requests in Insomnia to my AWS Lambda GraphQL result in a 403 Cloudfront error while the same request in Altair returns a response. If I'm not using the Cloudfront url but the API Gateway url the request works.

- Insomnia Version: 6.0.1 (6.0.1.2298)
- Operating System: MacOS High Sierra 10.13.6 (17G65)

## Details
1. Create a GraphQL request to `https://v4.wertungsheft.io/graphql` with body:
```graphql
query {
  search(input: "bau") {
    clubs {
      id
    }
  }
}
```
2. Use headers `Content-Type: application/json` and `Access-Control-Allow-Origin: *`
3. Response when sending request:
```bash
403 ERROR

The request could not be satisfied.

Bad request. 
Generated by cloudfront (CloudFront)
```

However if I use Altair, the API Gateway URL or if I perform the request with apollo-link to Cloudfront I get a response of the API:
```json
{
    "data": {
        "search": {
            "clubs": null,
        }
    },
    "errors": [
        {
            "message": "pq: relation \"clubs\" does not exist",
            "path": [
                "search",
                "clubs"
            ]
        }
    ]
}
```
I've tried to figure out why the request in Insomnia fails but I could not find out what I'm missing.

**Comment by gschier** [comment]
Hmm, it worked for me

![image](https://user-images.githubusercontent.com/587576/43599429-6868c9a8-963c-11e8-8a52-e268acbc634a.png)

**Comment by SpaceHeroGuide** [comment]
Sorry, forgot to mention that I'm doing a GET request.

**Comment by gschier** [comment]
Get requests aren't supported by Insomnia for GraphQL

**Comment by mohitmonu23** [comment]
I need to validate Access token via keycloak filter in API gateway.
