### ISSUE TITLE
[Question] can requestHooks modify GET params

### ISSUE THREAD

**Issue by Rand01ph** [getinsomnia/insomnia#1101]
- Insomnia Version: 5.15.0
- Operating System: Linux

## Details
I wan't to write a plugins for custom auth.
But I don't know how to hook request for modify GET params, now I write a plugins to generate params string to concat by hand.

[this is my plugins](https://www.npmjs.com/package/insomna-plugin-nswaf)

**Comment by gschier** [comment]
The documentation hasn't been updated yet but I'm pretty sure I added a setParameter method a while ago

**Comment by gschier** [comment]
You can see the up-to-date API methods here https://github.com/getinsomnia/insomnia/blob/b99af49a3ede931bc9e0dff43de88281b8ec2d4d/packages/insomnia-app/app/plugins/context/request.js#L131

**Comment by gschier** [comment]
And some tests here: https://github.com/getinsomnia/insomnia/blob/b99af49a3ede931bc9e0dff43de88281b8ec2d4d/packages/insomnia-app/app/plugins/context/__tests__/request.test.js#L116

**Comment by Rand01ph** [comment]
Thanks, i will try it.
