### ISSUE TITLE
[Question] Adding an array as query parameter

### ISSUE THREAD

**Issue by X39** [getinsomnia/insomnia#1102]
- Insomnia Version: 6.0.1
- Operating System: Windows 10

## Details

I currently try to add a array-based GET parameter to my url using the query tab.
However, i am not able to append that `[]` to the very end of the parameter names properly due to conversion (gets to their respective URLEncoded codes `%5B%5D`)

is there any way to add array based query parameters which i just missed?

**Comment by X39** [comment]
uhm ... this may be stale but the question still remains unanswered lil bot.

**Comment by gschier** [comment]
This might be a potential workaround for now https://github.com/getinsomnia/insomnia/issues/1182

**Comment by PeterBocan** [comment]
@gschier why? Why workarounding something that should work out of the box? Maybe in the next version of Insomnia, we may see an array support.

**Comment by mi-mazouz** [comment]
any updates?

**Comment by gabcamilo** [comment]
I managed to pass the array parameters like this:

![image](https://user-images.githubusercontent.com/11711471/71824841-35340880-3079-11ea-842c-15fec876ce69.png)

Works just fine :)

**Comment by lsotoj** [comment]
I have the same question, I need send an array by insomia to my mongoDB. I'm using the next code:
{
	"users": ["i76trdfghjk", "i65rdfgiol"]
}

But it does not work. the result is:

**{
  "error": "",
  "body": [
    {
      "users": [],
      "_id": "5f0d49cf80697d62e4ea283b",
      "__v": 0
    }
  ]
}**

A empty array.

**Comment by iabduul7** [comment]
> I managed to pass the array parameters like this:
> 
> ![image](https://user-images.githubusercontent.com/11711471/71824841-35340880-3079-11ea-842c-15fec876ce69.png)
> 
> Works just fine :)


![image](https://user-images.githubusercontent.com/24309704/113873871-a4ddf980-97ce-11eb-8068-c203eef2f71c.png)
for sending nested array you do something like this

which gives you this result
![image](https://user-images.githubusercontent.com/24309704/113873970-bfb06e00-97ce-11eb-8efd-009b34a0e6c3.png)

**Comment by dimitropoulos** [comment]
I would appreciate it, if possible, if someone would provide a direct step to reproduce what is seen as the broken behavior and then provide an example (that I can run, myself) of what the ideal behavior would look like.

I can use that information to write a failing test that I can then make pass by implementing the proper behavior.

for example, using something like mockbin.org would be good.

**Comment by X39** [comment]
![image](https://user-images.githubusercontent.com/1886428/113879426-cb923500-97ba-11eb-882d-3c8304c46d7c.png)
Literally that is the issue here (and still is as seen here)

**Comment by iabduul7** [comment]
> ![image](https://user-images.githubusercontent.com/1886428/113879426-cb923500-97ba-11eb-882d-3c8304c46d7c.png)
> Literally that is the issue here (and still is as seen here)

You are sending this array in url params, that obviously won't work.. send your array in multipart-formdata (Change body of the request)

**Comment by X39** [comment]
So the proposed solution is to convince all API vendors using `[]` in their query parameters to not use unescaped `[]` in them?

**Comment by iabduul7** [comment]
Unfortunately, I guess yes 🤦‍♂️

**Comment by dimitropoulos** [comment]
> all API vendors

@X39  Can you give me an example of a few such APIs?  Not saying you're wrong but I just haven't seen this use-case before and I'd like to better understand it.

**Comment by X39** [comment]
One example would be, what triggered this ticket initially: (The Magento 2 search endpoints)[https://magento.redoc.ly/2.3.6-guest/tag/search#operation/searchV1SearchGet]

Another more broad is APIs, explicitly displaying array query parameters as such (eg. `...?item[]=something&item[]=foo`)
tho ... depending on the URL parser used, this will work

The main issue now is that it seems that pretty much all APIs i have encountered will treat the key part of the query parameter different from the value one (that is: taking it explicit)
The option to thus at least turn off that behavior of URL-Encoding everything would be nice (eg. another checkbox in the UI)

More insight: https://medium.com/raml-api/arrays-in-query-params-33189628fa68

**Comment by iabduul7** [comment]
> One example would be, what triggered this ticket initially: (The Magento 2 search endpoints)[https://magento.redoc.ly/2.3.6-guest/tag/search#operation/searchV1SearchGet]
> 
> Another more broad is APIs, explicitly displaying array query parameters as such (eg. `...?item[]=something&item[]=foo`)
> tho ... depending on the URL parser used, this will work
> 
> The main issue now is that it seems that pretty much all APIs i have encountered will treat the key part of the query parameter different from the value one (that is: taking it explicit)
> The option to thus at least turn off that behavior of URL-Encoding everything would be nice (eg. another checkbox in the UI)
> 
> More insight: https://medium.com/raml-api/arrays-in-query-params-33189628fa68


well, the things is whenever you hit some url in browser's url tab, it kind of automatically encodes the url and it's a standardized way to open and share urls... if you don't encode, it may produce some unexpected behaviors and may not open the intended url.
