### ISSUE TITLE
Lost the projects, requests and insomnia.WorkspaceMeta corrupted.

### ISSUE THREAD

**Issue by ManualTester** [getinsomnia/insomnia#1104]
- Insomnia Version:  1.18.10807.101 
- Operating System:  Windows 7

## Details

Lost the projects, requests and insomnia.WorkspaceMeta corrupted, getting JavaScript error occur in the main process when tried to launch Insomnia app.

![2018-08-07 14_52_31-error](https://user-images.githubusercontent.com/15177608/43804791-1db9c91a-9a52-11e8-8802-ccfb65fdd07e.png)

How to recover all the projects and respective request added to insomnia?, Please help!!!

**Comment by gschier** [comment]
If it's the workspacemeta db that's corrupted you should just be able to delete it and restart the app

**Comment by ManualTester** [comment]
@gschier  : Thanks a lot for your advise, It worked as suggested. I deleted the old workspacemeta and restarted the Insomnia, I can see all my project/request and data now. Thanks again for your help.

**Comment by gschier** [comment]
Awesome, glad to hear 👍

**Comment by gschier** [comment]
Just wanted to add that you can local Insomnia's data directory from the Help menu.

![img_0088](https://user-images.githubusercontent.com/587576/51340077-07b31100-1a5c-11e9-99e0-eff3fb3eca02.png)

**Comment by yashrs** [comment]
In my case, CookieJar.db was corrupted, so I deleted it and it worked. For anyone else facing this issue, take a backup of all files and delete all files from AppData folder.

After this, start replacing each file in AppData folder from the backup you took and start Insomnia till you get error. Now you know which file has the error :) Just hope that Requests.. is not the file .. otherwise that means you have lost all your requests...

Thanks,
Yash :)

**Comment by tobecwb** [comment]
I tested a new install (never used Insomnia), and got the same problem, but with version 6.4.2!
Deleted all appdata\local\insomnia folder, installed again, and the error continue.

Windows 10 x64.

**Comment by gschier** [comment]
If it's a fresh install it's likely a different problem. Perhaps insufficient permissions to write the dB files?

**Comment by ValorMorgan** [comment]
I've recently now seen the same issue and it's hauntingly familiar to errors I was seeing on Postman (why I switched to Insomnia in the first place).  Assuming nedb is the issue (as both use this), this team may find it worthwhile to dig into the issue along with the Postman team / nedb team.
Postman issue describing the same thing: [Postman fails to start on Windows 10.0.17763.437](https://github.com/postmanlabs/postman-app-support/issues/6296)

**Comment by gschier** [comment]
@ValorMorgan can you provide an example of the "corrupt" file?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ValorMorgan** [comment]
> 
> 
> @ValorMorgan can you provide an example of the "corrupt" file?
> 
> Sent with [GitHawk](http://githawk.com)

I formatted the source for readability but on first open, this file is in a single line.  Note: I replaced my cookies with `[...]` for privacy.  None of the cookies appeared to be the issue though (in my testing, I removed the cookies and saw the error message still).

```
{
	"_id": "jar_ab6bec8fdb5e40d78c8a88918db7577c",
	"type": "CookieJar",
	"parentId": "wrk_645debbe0a5442ada2696bd4a6d628f6",
	"modified": 1556826628833,
	"created": 1551217001897,
	"name": "Default Jar",
	"cookies": [...]
}
```

Example in one line (saving as one line fixes the issue):
```
{"_id": "jar_ab6bec8fdb5e40d78c8a88918db7577c","type": "CookieJar","parentId": "wrk_645debbe0a5442ada2696bd4a6d628f6","modified": 1556826628833,"created": 1551217001897,"name": "Default Jar","cookies": [...]}
```

Cookie structure (for reference):
```
{
	"creation": string (date),
	"domain": string,
	"hostOnly": boolean,
	"httpOnly": boolean,
	"id": string,
	"key": string (hashed),
	"lastAccessed": string (date),
	"path": string,
	"secure": boolean,
	"value": string (hashed)
}
```

**Comment by gschier** [comment]
@ValorMorgan, is there any way you could attach a raw version of the DB file that broke it? If it's line endings causing the issue, then I won't be able to copy your example to reproduce the problem.

I think part of the issue here might be that NeDB uses a 10% corruption limit. For a DB with only a few bytes of data in it, one "invalid" line ending might be all it takes to prevent it from loading.

**Comment by gschier** [comment]
I just changed the corruption threshold from 10% to 90% to see if that prevents some of this.

**Comment by ValorMorgan** [comment]
Git doesn't let me post a `.db` file but here's the file with a `.txt` extension.  I went through and removed private data in strings (left stuff outside strings alone).  Note the trailing `}` on the 2nd line.
[insomnia.CookieJar.db.txt](https://github.com/getinsomnia/insomnia/files/3166539/insomnia.CookieJar.db.txt)

**Comment by gschier** [comment]
@ValorMorgan in your example, the trailing `}` is on its own line. Previously, you mentioned it was on a single line. Can you confirm this?

**Comment by ValorMorgan** [comment]
> 
> 
> @ValorMorgan in your example, the trailing `}` is on its own line. Previously, you mentioned it was on a single line. Can you confirm this?

I cannot fully confirm.  At this point, my backups were either modified for my testing or to show what I have here.

Off memory, the trailing `}` was on its own line when I first had the issue.  I am able to confirm that simply adding a 2nd line in the `.db` files with text (not an empty line) does cause the 10% corruption message.

Apologies for losing the very original source file...

**Comment by gschier** [comment]
Don't worry about it. It's just a bit unfortunate not to know the exact reason.

**Comment by anniecruz13** [comment]
I just fixed my problem by editing the insomnia.CookieJar.db file to remove a couple of extra carriage returns.

**Comment by arjamizo** [comment]
I suggest creating a `git` repository inside https://support.insomnia.rest/article/48-frequently-asked-questions#technical-questions _Where does the application store data?_

then do you not need to worry :)
