### ISSUE TITLE
Schema explorer

### ISSUE THREAD

**Issue by hzawawi12** [getinsomnia/insomnia#1106]
- Insomnia Version: ___Version 6.0.1 (6.0.1.2298)
- Operating System: ___ macOs High Sierra

## Details

Would be nice to have a schema explorer that show different mutations/queries available for a particular service.
Schema will include the different input/output types expected and help in writing the different queries/mutations in the client.

**Comment by gschier** [comment]
Closing this as it's a duplicate of #451
