### ISSUE TITLE
[Feature Request] UI/UX: Greatly Improve list of workspaces

### ISSUE THREAD

**Issue by csotiriou** [getinsomnia/insomnia#1107]
Hello,

I am currently loving insomnia, and it has helped me in many ways (me and my team).

Since we are heavily investing in microservices (and we will have a huge amount of them) the APIs that are going to be used are many. Like, way too many. Therefore, there are many workspaces that will need to be created for that.

I would really like to have a way to categorize / organize my workspaces, since they will soon reach 30-40.

There are a few things I would personally find very helpful: 

- Adding tags to workspaces
- Add an autocomplete search field in the dropdown that displays the list of workspaces, which will be able to autocomplete those tags or search by workspace name.
- Add folder support to the list of workspaces, so that the user can categorize better the workspaces he has.

What does everyone think about this?

**Comment by gschier** [comment]
I'm interested in what others have to say about this too.

As for your bullets, the second one is already in Insomnia. All dropdowns within the app are filterable (just start typing). You can also switch workspaces using the quick switcher CMD+P although, depending on your filter text, certain requests may be matched as well.

**Comment by gschier** [comment]
![screenflick movie 72](https://user-images.githubusercontent.com/587576/43911550-c3e910c6-9bcd-11e8-9ee8-87eb8871bbbe.gif)
