### ISSUE TITLE
[Feature Request] one-way sync options

### ISSUE THREAD

**Issue by matthew-noken** [getinsomnia/insomnia#1108]
Hello!

We just signed up for your team plan and use Insomnia pretty heavily in our development workflow. One thing has come up that I wanted to see about getting implemented, if possible.

We have a workflow where certain people are workspace publishers and others are subscribers. It would be helpful if this were codified in the client, such that for the Share Workspace screen there were the additional options of "Publishing to [organization]" and "Subscribed to [organization]". One person could set their client to publish and others could set theirs to subscribe, and they wouldn't have to worry on either side that the "canonical" workspace is overwritten accidentally.

To replicate this functionality currently, a subscriber must keep their sync mode disabled, then set it to manual, sync, and set it back to disabled.

Thanks!

**Comment by matthew-noken** [comment]
Any chance we'll see this feature? I've rethought it and think that we only need a subscribe option. With sync mode, two owners can be publishers but also sync between themselves, while everyone else can subscribe to the most recent change.

**Comment by gschier** [comment]
Woops, I'm no sure how I missed this one. I'm currently working on some improvements to the sync system to give it a more git-like workflow. I'll keep this in mind as I work on it.

**Comment by matthew-noken** [comment]
Would still like to see this!

**Comment by gschier** [comment]
Working on it!

![image](https://user-images.githubusercontent.com/587576/49834846-6a353500-fd6b-11e8-83a1-cbb4a9c21617.png)

Going to close this one as it's already being addressed

**Comment by matthew-noken** [comment]
Looks great! Is there a ticket where I can follow the progress on this?

**Comment by gschier** [comment]
No, it's still too early to share anything

**Comment by gschier** [comment]
I'll try to put a PR once things are a bit more stable, then work in it in the open
