### ISSUE TITLE
[Feature Request] - Star/Favorite/Pin requests

### ISSUE THREAD

**Issue by 6utt3rfly** [getinsomnia/insomnia#1109]
My work-space has numerous folders for all of the CRUD endpoints for various resources. We're sharing these endpoints among our team and each folder uses environment variables to set the base url. It would be nice if I could star/pin/bookmark or somehow make a private list of shortcuts to these requests that wouldn't sync to other users but would still allow environment variables to be maintained.

This could potentially be workable with something like #576 where a global history of requests would allow for clicking between recent requests irrespective of environment/workspace

Insomnia version 6.0.2

**Comment by gschier** [comment]
I think there is another issue somewhere around here that's similar but I can't find it. I think this would be a great feature and would probably also resolve the need for tabs (has been requested as well). 

I imagine a _pin_ toggle in the request dropdown menu and a new sidebar section at the top to show pinned requests.

**Comment by develohpanda** [comment]
Duplicate of #1344.

Funny, @gschier we had the same idea to resolve this! I just saw it come up in the list because of the stale bot.
