### ISSUE TITLE
[Bug] Possible to use 'Request => url' function as Query value

### ISSUE THREAD

**Issue by 4ekki** [getinsomnia/insomnia#1111]
- Insomnia Version: 6.02
- Operating System: Windows 10

## Details
[Bug] Possible to use 'Request => url' function as Query value: 
![image](https://user-images.githubusercontent.com/38757986/43946974-6ba80eb8-9c8f-11e8-9d1e-f087b40816ab.png)
After doing this Insomnia hangs sometimes. I think it goes to infinite loop with adding parameter to url and recalculating the url

**Comment by gschier** [comment]
Hmm, this may be a tricky one to fix. It's definitely infinite recursion. Any ideas?
