### ISSUE TITLE
[Bug] Request context menu has horizontal scrollbar when requests panel is narrow

### ISSUE THREAD

**Issue by 4ekki** [getinsomnia/insomnia#1113]
- Insomnia Version: 6.0.2
- Operating System: Windows 10 

## Details
Request context menu's width is limited to the width of requests panel: 
Normal width: 
![image](https://user-images.githubusercontent.com/38757986/43952044-6577cbce-9c9d-11e8-899a-dd0209718f7f.png)

Narrow: 
![image](https://user-images.githubusercontent.com/38757986/43952054-6c523592-9c9d-11e8-847f-2a3058822f1f.png)

**Comment by 4ekki** [comment]
Not stale

**Comment by gschier** [comment]
![image](https://user-images.githubusercontent.com/587576/47111816-96787d80-d222-11e8-96fa-1da6c7797450.png)

**Comment by 4ekki** [comment]
![image](https://user-images.githubusercontent.com/38757986/48339811-b9574f80-e671-11e8-8ed6-8afa7d3c1821.png)
Please note that this is still actual in 6.2.0

**Comment by gschier** [comment]
Hmm, that's strange. I can't seem to reproduce the problem. 
![image](https://user-images.githubusercontent.com/587576/48358304-7ba1f900-e668-11e8-9d31-d029e7a6c27f.png)

**Comment by gschier** [comment]
Does it happen all the time, or only in certain cases?

**Comment by gschier** [comment]
Ya, you were right @4ekki! Should be all fixed now (next release)
