### ISSUE TITLE
Valid CURL string broken in insomnia.

### ISSUE THREAD

**Issue by ripley** [getinsomnia/insomnia#1121]
- Insomnia Version: 6.0.2 (6.0.2.2311)
- Operating System: Mac High Sierra.

## After pasting into insomia, a valid curl request is broken.

The request is like:

```shell
curl 'https://jmpview.hd.com/view-vlsi/rest/v1/queryservice/query' -H 'Pragma: no-cache' -H 'Origin: https://jmpview.hd.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6' -H 'CSRFToken: a9a1686c-c8a9-4969-86ad-d20f358b259c' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36' -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json, text/plain, */*' -H 'Cache-Control: no-cache' -H 'Referer: https://jmpview.hd.com/newadmin/' -H 'Cookie: JSESSIONID=FD6DA1B917A3654FF8D71EDACB016686; CSRFToken=a9a1686c-c8a9-4969-86ad-d20f358b259c' -H 'Connection: keep-alive' --data-binary $'{\n  "queryEntityType": "SessionLocalSummaryView",\n  "sortDescending": false,\n  "startingOffset": 0,\n  "filter": {\n    "type": "Equals",\n    "memberName": "referenceData.user",\n    "value": "UserOrGroup/Uy0xLTUtMjEtNzU5MjgyMzg1LTIyNDA4OTI5NTYtMzQyMDc3NTMzOC0xMTEx"\n  }\n}' --compressed --insecure
```

It works in command line but cannot be executed after pasting into insomnia.

The "--data-binary" field becomes a invalid json string in insomnia, I manually formatted it then it works.

**Comment by gschier** [comment]
Ya, it looks like it doesn't know what to do with the newline characters. What does the `$` mean in that context?

**Comment by ripley** [comment]
I saws it for the first time as well. It works as ... "so basically the command says 'scan the string for escape characters and print the formatted string then convert that printed string to binary' " according to [stackoverflow](https://unix.stackexchange.com/questions/115612/understanding-two-flags-and-a-dollar-sign-in-a-curl-command).

It's a rare case, insomnia always works fine.

**Comment by carmineesposito73** [comment]
I have the same issue:
the url is
```
http://VCLOUD-HOST/api/query?type=edgeGateway&filter=(name==EDGE_GW_NAME)
```
using insomnia I get a response that says
```
Expression name%3D%3DEDGE_GW_NAME is not a comparison expression`
```
while using curl works fine.

I've realized that insomnia escapes `==` with `%3D%3D` so the url becames
```
http://VCLOUD-HOST/api/query?type=edgeGateway&format=records&filter=(name%3D%3DEDGE_GW_NAME)
```
here the traces captured with wireshark

[curl_vs_insomnia.txt](https://github.com/getinsomnia/insomnia/files/2483007/curl_vs_insomnia.txt)

**Comment by Numenorean** [comment]
any news? --data-binary is still unsupported while importing request as curl, but it's really annoying to upload raw data as file each time i need to send octet-stream(not an image or smth like that). It will be cool if insomina becomes support that
