### ISSUE TITLE
[Feature Request] rewrite domain and http security when storing cookies.

### ISSUE THREAD

**Issue by wederbrand** [getinsomnia/insomnia#1122]
- Insomnia Version: 5.16.6
Shell 1.8.4
Node 8.2.1
V8 5.9.211.38
Architecture x64

libcurl/7.59.0 OpenSSL/1.1.0h zlib/1.2.11 nghttp2/1.31.1

- Operating System: linux mint

## Details
I often replace one or more of the components from a production setup with locally deployed services.

The ones in production returns cookies with production domain set but for me to be able to continue on to locally deployed versions I need to change the domain and the Secure-option to localhost and off, respectively, to be able to continue. 

While this is possible do manually it would be create if it where easier. Either an option to always send all cookies, regardless of domain, or to use cookies for some domains even if the call is made to localhost (or other).

Thanks.

**Comment by gschier** [comment]
You can get around this by using the Cookie tag to get the cookie value from a different URL and setting the Cookie header manually.

![image](https://user-images.githubusercontent.com/587576/44215800-6557d000-a141-11e8-948b-19e73af96227.png)

Here's an example of how to fill out the tag details after clicking on it.

![image](https://user-images.githubusercontent.com/587576/44215787-5a9d3b00-a141-11e8-8b96-62e488e592cc.png)

**Comment by wederbrand** [comment]
Great!
It didn't work exactly as in your screenshots (the cookie name was not automatically copied) but it works.

**Comment by gschier** [comment]
Yes, both the cookie name and URL must be typed by the user. Glad you got it working!
