### ISSUE TITLE
[Bug] Playing nice with VPNs

### ISSUE THREAD

**Issue by jhalterman** [getinsomnia/insomnia#1125]
Insomnia 6.0.2
MacOS Sierra

## Details

I'm using a REST API on an AWS VPC that only allows traffic from certain IPs, so hitting the API requires connecting to a VPN. If I try to hit the API with Insomnia when I'm not on the VPN I get a 401, but even after connecting to the VPN I still get a 401 whereas curl works fine.

I discovered that if I restart Insomnia and try again, requests succeed. I also discovered that after being on the VPN for a few minutes the problem will clear up on its own and requests start to succeed.

I'm not entirely sure why this is - perhaps Insomnia is persisting connections internally rather than re-establishing them after the VPN connection is made? Or possibly it's caching my request or response?

**Comment by gschier** [comment]
This is because libcurl reuses connections for a certain period of time. You can set the keepalive header on your requests to prevent this

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive

**Comment by jhalterman** [comment]
Thanks 👍
