### ISSUE TITLE
[Bug] Team sync is not match

### ISSUE THREAD

**Issue by gimdongwoo** [getinsomnia/insomnia#1128]
- Insomnia Version: 6.0.2(Stable), 6.0.3(Beta-1)
- Operating System: macOS

## Details

We tested all day to use insomnia on our team.
However, the team sync result has continued to fall in different situations from each person.
We are S/W development company.
So, we have conducted various tests.
In all cases, Team sync did not work properly.
Each of us has a different collection.

**Comment by Fyb3roptik** [comment]
I am having this same issue. I created a new Workspace and am trying to share it with my team, but it will not pull on their end. Running the latest stable macos version

**Comment by gimdongwoo** [comment]
@gschier Reopen issue, please.
Eventually, our team canceled the subscription to Insomnia.
This product can not be used.

**Comment by gimdongwoo** [comment]
https://github.com/getinsomnia/insomnia/issues/1335
