### ISSUE TITLE
[Feature Request] Recent requests menu

### ISSUE THREAD

**Issue by xeptore** [getinsomnia/insomnia#1138]
[Feature Request] – Provide concrete use cases to go along with these requests

- Insomnia Version: 6.0.2  
- Operating System: Ubuntu 18.04 

## Details
hi.
i have created a _workspace_ with a long list of requests. after grouping them into **Folders** it is still a bit hard to find recently used requests and walking through directories to find the last request i used.
i think it is really useful to add a header menu (like what exists in code editors) that stores 5 or 10 recently used requests. or maybe ordering them by date from left to right. i still dont have any idea about where that menu is better to be, but i think it is handy if it placed somewhere on top of the request url or even in a dropdown menu.

thanks.

**Comment by gschier** [comment]
I like how text editors like VSCode does it. Basically, the file switcher menu shows (by default) the most recently used files.

![image](https://user-images.githubusercontent.com/587576/44684824-0be08280-aa18-11e8-91d6-f6fba5ab16e3.png)

IntelliJ does something similar but in a dedicated menu.

![image](https://user-images.githubusercontent.com/587576/44684836-1864db00-aa18-11e8-9ad7-848921870663.png)

Insomnia already has a request switcher so maybe we could auto-sort them there to start. 

![image](https://user-images.githubusercontent.com/587576/44684926-48ac7980-aa18-11e8-87ad-c47dc411fc87.png)

**Comment by gschier** [comment]
Right now they aren't sorted in any order (I think it's random, grouped by folder). This would be fairly easy to implement. We could start tracking access times for each request (in the `RequestMeta` model) and then use that to sort the list.

**Comment by xeptore** [comment]
yes, youre right. there was a place where recent requests stored and can be accessed from, but i think a menu with tabs of requests is still more useful. something like what vscode has implemented.
![image](https://user-images.githubusercontent.com/29199390/44700030-2f4d1100-aa9c-11e8-80e3-c2b6f7ab861a.png)
i know it will be longer and longer as the user creates and uses new requests, but it can be configured via a `setting` like thing or it may be always a fixed number of recently used requests, 5 or 10. about grouping them, i think there is no need to, just sorting them by the last time they get used (when the user issues the request and hits the **Send** button, _`last used time`_ of that tab gets updated and it replaced as the most left tab in the recently used requests tab)

i know it may seem a bad idea to implement, but i found it useful, even with 5 or 6 recently used items.

thanks

**Comment by bukajsytlos** [comment]
Please please implement this sorting feature. Its really hard to navigate in workspace with lot of requests.
Thanks

**Comment by bukajsytlos** [comment]
thank you
