### ISSUE TITLE
[Feature Request] Custom OAuth 2.0 parameters

### ISSUE THREAD

**Issue by mrtus** [getinsomnia/insomnia#1140]
In order to test custom OAuth 2.0 grants it would be really helpful to be able to set custom parameters

e.g. Slack https://api.slack.com/docs/oauth allows you to set a `state` or a `team` in their `/authorize` request.

### Current Behavior
- As a user I am limited to the default OAuth 2.0 parameters.

### Expected Behavior
- As a user who would like to use custom OAuth 2.0 grants I can set custom parameters so that I can also make request to custom OAuth 2.0 grants using Insomnia OAuth 2.0 functionality.

**Comment by gschier** [comment]
`state` is a native OAuth 2.0 field and is available in Insomnia. `team` is not, however, and would benefit from a custom params feature. 

In general, would custom params only need to be sent on the authorize request or also on the fetch/refresh requests? (I'm not an OAuth expert)

**Comment by mrtus** [comment]
I am not sure about that as I am not an OAuth expert either. But looking at the flow it would make sense to only have them set on the authorize request because your token should already be defined after that.

There is also another solution, in which we can just pass the params with the authorize url:
`/oauth/authorize?team=<param-value>` This is offcourse also a solution/workaround if it is decided to not implement this for Insomnia 👍

**Comment by gschier** [comment]
Oh nice, I never thought of adding them directly to the authorize URL. Nice workaround! (for now)

**Comment by szechyjs** [comment]
I'd like to see the ability to add custom parameters to both the authorize and the token requests. Currently the lack of this is prohibiting me from using the OAuth feature with a few APIs.

**Comment by mrtus** [comment]
@szechyjs This should solve it no?
>There is also another solution, in which we can just pass the params with the authorize url:
/oauth/authorize?team=<param-value> This is offcourse also a solution/workaround if it is decided to not implement this for Insomnia 👍

**Comment by szechyjs** [comment]
@mrtus thanks, that workaround works!
