### ISSUE TITLE
[Feature Request] App url handling

### ISSUE THREAD

**Issue by mira-kovar** [getinsomnia/insomnia#1141]
Hi!
I would love to see feature like this:
`insomnia://import?method=GET&url=https://someapi.com?a=1&...`

So I could create html button like this to open insomnia:
`<a href="insomnia://xxx">open this request in insomnia</a>`

What do you think?

**Comment by gschier** [comment]
It already exists, but is undocumented and only works on Win/Mac.

You can import an Insomnia export file with the following URL: `insomnia://app/import?uri=http://foo.com/bar.json` (the `file://` URI also works)

**Comment by mira-kovar** [comment]
Thanks!
