### ISSUE TITLE
Json body not sent with POST

### ISSUE THREAD

**Issue by kitsu** [getinsomnia/insomnia#1144]
- Insomnia Version: 6.0.2
- Operating System: Win7

## Details

I'm extending a WebApi2 ODataV4 end point with CRUD operations. I'm trying to test my POST (add) action, but the body is always empty. Here is a screenshot showing the body content and the zero content-length:

![2018-08-29 13-03-41](https://user-images.githubusercontent.com/2218853/44812486-23d91300-ab8c-11e8-9a01-e44d1b0ec04c.png)

When I make the same request with Fiddler it actually works, so it seems you are not including the body?

I really like Insomnia, and I've used it to build and debug all kinds of things, but this is the first time I've tried posting with a body.

**Comment by gschier** [comment]
No problem. `libcurl` is the thing that handles the NTLM negotiation. Some Googling indicates that there have been similar problems in the past regarding this so it could be a bug in `libcurl`, which would be unfortunate.
