### ISSUE TITLE
[Feature Request] Generating Code - PowerShell

### ISSUE THREAD

**Issue by soerenkk** [getinsomnia/insomnia#1145]
I've recently discovered this program. It is an invaluable and versatile tool which I'm sure I will be using way more.

Creating different workspaces for different projects, but also letting me save and (re-)use different REST calls, and my testings, that is a true blessing.

I've noticed that the program also features code generation, which I know will be useful in upcoming projects.

Even though the generate code is available for the most common programming languages, I'm actually missing the possibility to generate code for PowerShell.

I'm currently creating a PowerShell integration with a web interface, which isn't an API. With the PowerShell code generation, I will be able to skip about half of the actions, and about 2/3 of the total work I have to do. I'm sure I wont be the only one benefiting from adding code generation for PowerShell.

Hope you will at least consider the option.

Best Regards
//Me

**Comment by coolhome** [comment]
This might be a good resource for whoever wants to implement this https://github.com/chromium/chromium/blob/9a08a5e480434999d3cfa852b35c45aae1ea9b48/third_party/blink/renderer/devtools/front_end/network/NetworkLogView.js#L1781-L1833

**Comment by coolhome** [comment]
Chrome's Developer Tools has the ability to copy network requests as PowerShell. This might be a good resource for whoever wants to implement this.
https://github.com/chromium/chromium/blob/9a08a5e480434999d3cfa852b35c45aae1ea9b48/third_party/blink/renderer/devtools/front_end/network/NetworkLogView.js#L1781-L1833

**Comment by gschier** [comment]
Should be in soon! https://github.com/Kong/httpsnippet/pull/127

**Comment by coolhome** [comment]
This was released with 6.5.1 I believe -- confirmed working (y) 

https://insomnia.rest/changelog/6.5.1/
