### ISSUE TITLE
[Bug] JSONPath filter changes 64-bit integers

### ISSUE THREAD

**Issue by PatrickPijnappel** [getinsomnia/insomnia#1146]
- Insomnia Version: 6.02
- Operating System: macOS 10.13.6 (17G65)

## Details

When applying any JSONPath filter (even just `$`) to the response, 64-bit integers in the response are changed (rounded?), e.g. take any response containing `438544484291054295`, filter using e.g. `$`, and it will become `438544484291054300`.

**Comment by Fengxq2014** [comment]
Is there a solution to this problem
