### ISSUE TITLE
[Feature Request] More helpful error message when single quotes detected in JSON

### ISSUE THREAD

**Issue by agilgur5** [getinsomnia/insomnia#1150]
- Insomnia Version: 6.0.2
- Operating System: macOS High Sierra 10.13.6

## Details

Currently if you use the JSON format and use single quotes, the editor will (confusingly) tell you "expected STRING, got undefined". Single quotes are in fact strings, but invalid JSON, and therefore a very common error, so I think a more informative error message would be much more helpful. I also couldn't figure out how to do a find and replace to change the single quotes to double quotes.

P.S. Finally had a use case to try this out after following you on Twitter for a while (and discovering this from your profile) haha

**Comment by gschier** [comment]
Hmm, that is an odd error message. This message comes from the `jsonlint` package, which I'm probably not familiar enough with to debug. I just updated `jsonlint` but it was only a minor patch bump so it may not have changed anything.

Also, woo! Hello from Twitter 😄
