### ISSUE TITLE
[Bug] StartUp Error, stringSlice breaking Insomnia

### ISSUE THREAD

**Issue by battenstudio** [getinsomnia/insomnia#1152]
- Insomnia Version: 6.0.2
- Operating System: Windows 10 Pro x64

## Details

![image](https://user-images.githubusercontent.com/30214586/45016606-6d5ead80-b025-11e8-84a3-ae306d25d686.png)
(Leaving this here for the github search):
`Error: "toString()" failed
at stringSlice (buffer.js:556:443) 
at Buffer.toString (buffer.js:629:10)
at tryToString (fs.js:509:15)
at FsReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)`

Tried to send a xml file with a size of about 4mb (ca. 75.000 rows) as a Post.
It worked several of times, but suddenly it doesn't work anymore.
 Maybe I clicked the send button to often, because there was always a little pause after clicking the send button, before the loading spinner appeared.

Now I can't use Insomnia anymore, because the View isnt even rendering, only the window shell is appearing. Killing the Process didnt worked out.
Is There a fix where i keep my "workspace"? So if I install it again i dont lose all my requests.

**Comment by FabioTeixeira** [comment]
I got the same issue... But i'm in mac
![image](https://user-images.githubusercontent.com/1254341/45258647-f887cc80-b3b2-11e8-9227-a2ea6b7d257b.png)

I was also trying to POST a xml file with ~15mb.

**Comment by battenstudio** [comment]
The temporary fix isn't working, error dialog is still coming up.
And the Insomnia window is still white, except for the menu (application/Edit/...). But that was the case even before deleting the responses folder.

**Comment by dchw** [comment]
Interesting. I am in the same boat here on MacOS, but sending 300Mb POST requests. I can no longer launch Insomnia, and the workaround suggested by @gschier did not work for me either. Any other ideas?

I had quite a few requests set up in there that I would rather not lose...

**Comment by dchw** [comment]
I am not sure if this is how I was _supposed_ to do it, but I found that there were some huge requests in `~/Library/Applications Support/Insomnia/insomnia.Request.db`. I removed the lines that contained the huge request (in my case, the last 10 or so), and Insomnia began working again.

**Comment by gschier** [comment]
I just thought of this, but you could also open `insomnia.WorkspaceMeta.db` and set `activeRequestId` to `null`. If you restart Insomnia with this set to `null`, no request will be selected and you will be able to delete the large request from the sidebar without opening it.

**Comment by jdpipkin** [comment]
I'm having the same issue. @gschier unfortunately none of the fixes seem to be working for me as well
