### ISSUE TITLE
[Feature Request] Export excel file download 

### ISSUE THREAD

**Issue by xiongxin** [getinsomnia/insomnia#1154]
I have an api export excel file, but insomnia get binary format response. I want insomnia can download this excel file for me.

sorry for my poor english.

**Comment by gschier** [comment]
If you are only looking to download the file you can do that from the preview mode dropdown

![image](https://user-images.githubusercontent.com/587576/45250164-9324d480-b2fb-11e8-8239-c54dd8b722e6.png)

**Comment by xiongxin** [comment]
@gschier Thanks, it work to me.

**Comment by gschier** [comment]
😄
