### ISSUE TITLE
[Question] Difference configuration between Insomnia app and chrome app

### ISSUE THREAD

**Issue by PierrickG34** [getinsomnia/insomnia#1159]
- Insomnia Version: 6.0.2
- Operating System: Windows 7

## Details
Hi ! 

I'm trying to acces to my local API for debug and test, it's works on the chrome application (old version :() but doesn't in the windows application.
Do you know why ? What is the difference or the configuration to add to the windows application ?

I've tried to use the cURL and import in the windows application but there is nothing about the configuration, just the url.
The error on the windows app : 
![image](https://user-images.githubusercontent.com/12444077/45291714-41df3580-b4f3-11e8-80ff-763d90515813.png)
Success on the chrome app : 
![image](https://user-images.githubusercontent.com/12444077/45291865-984c7400-b4f3-11e8-83e9-8ab44478c109.png)

**Comment by gschier** [comment]
The main difference between the two applications is that the Chrome app uses the Chrome network stack to send requests while the Windows app uses `libcurl`. The most common cause for problems that I've seen is that the Windows app does not autodetect proxy configurations. So, if you have a proxy setup on your machine, you will have to configure that manually in the Windows app.

If you post the contents of the Timeline tab it may provide some more details as to what happened?

**Comment by PierrickG34** [comment]
Hi Gregory !

Thanks for the details :) I'v test with and without the proxy configuration on the windows application but it's not that. After a look in the Timeline tab, it was the ssl certificate, I just uncheck the 'Validate SSL Certificates' and it's work fine !

Thanks a lot, the windows app is so much better than the chrome app haha :)

Thanks for the work you do on this app :+1: 

Bye :)

**Comment by gschier** [comment]
Awesome! I'm glad you got it working 😄 🎉
