### ISSUE TITLE
[Feature Request] Ordered workspace list

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#1161]
- Insomnia Version: 6.0.2
- Operating System: Arch Linux

## Details

Hi there!

I would like to request a feature to always show the "Switch Workspace" list ordered. For each microservice we have a dedicated workspace, and since the workspace list got big, it became hard to find where is the workspace I need, because the list isn't ordered.

I think an option on preferences to enable this feature would be nice.

Best regards,
Rafael Pacheco.

**Comment by gschier** [comment]
Sorting sounds like a good idea.

Also, every dropdown in Insomnia is filterable (just start typing) so that might be a potential workaround for the short-term.

**Comment by Masov** [comment]
Hi! I'm on it!
