### ISSUE TITLE
[Feature Request] Customizable keybindings

### ISSUE THREAD

**Issue by adiachenko** [getinsomnia/insomnia#1162]
- Insomnia Version: 6.0.2
- Operating System: MacOS 10.13.6

## Details

I can't trigger autocomplete by hitting ^Space, because the shortcut is already reserved for system use (namely selecting the input source). Please note, that I have multiple input sources enabled on my Mac which might or might not be necessary to replicate the issue. And even if I disable the default binding in system preferences, the show autocomplete shortcut in Insomnia still doesn't work for me. It seems like something is going on there.

**Comment by gschier** [comment]
This seems like it's probably not an issue with Insomnia itself. Perhaps you need to restart your system after disabling the shortcut to "free up" the binding for Insomnia to use?

**Comment by adiachenko** [comment]
@gschier Thanks, restarting the system indeed helped. 

Still, I feel like the better way to address this would be to change the shortcut in Insomnia. Binding autocomplete to one of the most widely used system shortcuts just doesn't seem like a very good idea made worse by the fact that keyboard shortcuts aren't customizable.

**Comment by gschier** [comment]
The reason Ctrl-Space was chosen was because many other editors use the same keybinding for autocomplete: IntelliJ, Atom, VSCode, Sublime Text, ...

I definitely agree with you that shortcuts keybindings should be editable but I think the default of Ctrl-Space is the right choice.

**Comment by gschier** [comment]
Coincidentally, I set up an additional language yesterday for someone else to use my laptop and ran into the same issue today. I couldn't figure out why the input language kept switching back and forth on me 😆

I thought there was already an issue for customizable shortcuts but I can't find it. I'm going to rename this issue to match what needs to be done. Thanks for the submitting this 👍 💯

**Comment by rickychandra** [comment]
Hi, I would like to work on this. :smile:
I suppose we are going to support more than one keymaps for a hotkey (like the send request hotkey that has multiple keymaps: ctrl+r, ctrl+enter, f5).

**Comment by danielo515** [comment]
I am in the same exact situation. How is this going?

**Comment by rickychandra** [comment]
Hi @gschier, any update on the pull request? I have actually finished the keybindings editor (the complete feature). Do you want me to push the update to this PR, or create another PR after this one is merged?

**Comment by gschier** [comment]
@rickychandra sorry, I've just been busy. Another PR would be appreciated 😃. My goal is to deal with all the open PRs next week!

**Comment by spro** [comment]
For some reason I am not able to bind "Show Autocomplete" to anything but the default. I can remove it, which predictably makes it not work anymore, but it continues not to work with a custom shortcut. Re-defining the original Ctrl+Space shortcut makes it work again.

**Comment by rickychandra** [comment]
@spro please create a new issue for this. I hope I could help look into this in these days.
