### ISSUE TITLE
[Feature Request] request level extra info for plugin system

### ISSUE THREAD

**Issue by yittg** [getinsomnia/insomnia#1163]
## Details

Plugin system now intercept request/response, but one plugin self may not know what the request is, missing some extra info to describe the request that the plugin known, say tags and meta info.
Insomnia may provide a interface for plugin system to provide its known tags, when plugin intercept a request, it will handle(or not) according to the tags and meta info request carried.
And may provide a ui for user to (multi)select tags and fill corresponding meta info.

**Comment by gschier** [comment]
I think I understand what you are describing. However, it always helps to provide examples. Can you outline, in detail, an example use-case for this?

**Comment by yittg** [comment]
[**default-headers**](https://github.com/getinsomnia/insomnia/tree/develop/plugins/insomnia-plugin-default-headers) plugin as a simple example
**default-headers** provide a ability, _add predefined headers_, but for all requests and with same default headers of `DEFAULT_HEADERS`.
But some request don't need this default headers and some needs other different headers.(may can be reached by multi workspace, so this is just a example)
Here _add predefined headers_ is a tag provided by this plugin, and `DEFAULT_HEADERS` is the meta info, all of these exposed to user to choose and fill. only when user choose this tag , the plugin will get the meta info user filled(here is `DEFAULT_HEADERS` or others environment variable) and do something corresponding(here is _add predefined headers_).
Again this is just a simple example, to explain how all works. Thanks, and more grateful is accepted.

**Comment by yittg** [comment]
Actually, i've implemented a [draft](https://github.com/yittg/insomnia/commit/67a98b0edf7ebdd3268b79078df5c9a4884208b8) about this feature some days ago. But now, i can't build it smoothly when rebased to the latest of insomnia main line, and i think it would be better if merged back to the main line with better and insomnia-idiomatic implementation.

**Comment by gschier** [comment]
Thanks for the example, it totally makes sense.

I think I remember you sharing that fork a while ago. Did you ever have any screenshots of what it looked like? I think it'd be worth discussing it a bit more and that would be a good starting point.

**Comment by gschier** [comment]
Oh I see. Then you can type an arbitrary string into it as a value for various configuration properties. Smart!

It might be cool to make use of the format used to create the Template Tag forms to make things more user-friendly. 

https://github.com/getinsomnia/insomnia/blob/a921c9c0542d824759b49d8457f4a9326e446490/plugins/insomnia-plugin-response/index.js#L5

**Comment by yittg** [comment]
@gschier So, is this proposal accepted❓

**Comment by gschier** [comment]
Yep, I think this would be a great addition!

I'm not 100% convinced that this feature justifies taking up a whole tab but it's probably fine as long as we can hide the tab when no plugins require tags. I'm also not sure where else to put it that would be easily-accessible.
