### ISSUE TITLE
[Feature Request] Ability to select for which Environments a Query Parameter will be enabled

### ISSUE THREAD

**Issue by flmbray** [getinsomnia/insomnia#1165]
- Insomnia Version: 6.02
- Operating System: Windows 7

## Details

For debugging purposes, some of our REST API calls allow additional query parameters to be sent in our "dev" enviornment, but these same parameters will generate errors in our "test" and "prod" environments.  Currently, this means I have to manually enable/disable some query parameters when switching between environments by using the "Enabled" checkbox on the query parameter.  I would like to be able to select for which specific environments a query parameter would be enabled (instead of just a single checkbox that applies to all environments) ideally via a drop-down box that has checkboxes for each defined environment.

**Comment by badazz11** [comment]
Comment:/-(a3s😟

**Comment by gschier** [comment]
This feature seems a little too niche to implement as a first-party feature. This can be done via a plugin, however.

## Option 1 – Default Query Parameters

If the query parameters are static for each environment, you could copy how the [Default Headers](https://www.npmjs.com/package/insomnia-plugin-default-headers) plugin works and define default query parameters for each environment.

## Option 2 – Query Parameters Blacklist

Similar to Option 1, you could define a list of blacklisted query parameters in the environment and have a plugin remove them in a request hook.
