### ISSUE TITLE
[Bug] Can't use template tags/environment variables in graphql query variables

### ISSUE THREAD

**Issue by hvdklauw** [getinsomnia/insomnia#1169]
- Insomnia Version: 6.0.2.2311 & 6.0.3-beta.1.2319
- Operating System: macOS 10.13.6

## Details

I can press ctrl+space no popup will show allowing me to select a response tag.

This makes setting up chained requests a real pain because I have to manually extract values from responses and paste them in there.

Updating to the beta channel did not fix it

**Comment by gschier** [comment]
Hmm, it should be working. Here's what it should look like:

![image](https://user-images.githubusercontent.com/587576/45918473-89e84b80-be55-11e8-9736-04c68f1acf82.png)

**Comment by hvdklauw** [comment]
Yeah, I know, just does not work for me, on the query and header tabs it works fine.

**Comment by gschier** [comment]
That's strange. Any errors in View > Toggle DevTools > Console?

**Comment by hvdklauw** [comment]
I did some debugging by searching in the source for the hints-container and I get as far as the cm.showHint call after which DevTools says the main screen reloaded or something like that

**Comment by hvdklauw** [comment]
Ok, found it after recreating the query and it all working, somehow the "skip rendering of request body" was enabled for my queries, disabling that fixed it on the original query too.

I have no idea how that got enabled, but I guess the error was between user and chair ;-)

**Comment by gschier** [comment]
Oooh, ya that makes sense 👍
