### ISSUE TITLE
[Question] Client certificate not being sent?

### ISSUE THREAD

**Issue by JoelSanchez** [getinsomnia/insomnia#1171]
Insomia version: 6.0.2
OS: Archlinux,  kernel: x86_64 Linux 4.18.9-arch1-1-ARCH

I can use a client cerficate with its key file and passphrase in both CURL and Postman, but not in Insomnia, even though I'm doing the exact same thing.

The CURL command is something like this:

```
 curl -i -v -X GET -s -k --cert crt_file.crt:mypassphrase --key my-key.pem https://localhost:8443/whatever
```

I fill the form like this (in Postman and Insomnia):
- Host: localhost:8443
- CRT file: same as in CURL's --cert
- Key file: same as CURL's --key
- Passphrase: same as in CURL's --cert

How can I know what's going wrong? Thank you

**Comment by gschier** [comment]
Hmm, it should be sending. Do you see anything in the Timeline tab?

**Comment by JoelSanchez** [comment]
Sorry, I got it working. Using "*" won't work, and just "localhost" won't work either. "localhost:8443" does work, though. Thank you for telling me about the timeline tab!

**Comment by gschier** [comment]
Nice!
