### ISSUE TITLE
[Improvement] Import variables from Postman Collection

### ISSUE THREAD

**Issue by verglor** [getinsomnia/insomnia#1172]
Postman Collection format 2.0 contains "variable" array.
It would be very useful if it could be imported to local environment as well.

**Comment by gschier** [comment]
Can you please link to the documentation or provide an example+screenshot of this "variable" array? I'm not sure what it is.

**Comment by verglor** [comment]
Hi @gschier, please see [Postman Collection Format v2.0.0](https://schema.getpostman.com/json/collection/v2.0.0/docs/index.html)

You can define collection variables in *EDIT COLLECTION* window (by selecting *Edit* in collection context menu):
![](http://blog.getpostman.com/wp-content/uploads/2017/12/image2-1200x746.png)

**Comment by gschier** [comment]
Oh okay, so those are different from environments then. Insomnia supports the environment export format but yet, collection variables could also be supported.

**Comment by dhruv944** [comment]
@gschier I don't see the concept of collection in insomnia. so what is the advantage of adding collections variables?

I am interested in picking up this task.
