### ISSUE TITLE
[Feature Request] EDN content-type in requests and responses

### ISSUE THREAD

**Issue by JoelSanchez** [getinsomnia/insomnia#1173]
I'm a Clojure developer, and I'd love to have EDN support in Insomnia. EDN is like JSON but it's a subset of the Clojure language.

![image](https://user-images.githubusercontent.com/8020017/45970358-95df3380-c036-11e8-9a14-94eefc416bea.png)
As you can see, I am suffering.

Thank you

**Comment by gschier** [comment]
It looks like this might be possible with the EDN Codemirror plugin https://github.com/halohalospecial/codemirror-elixir-mode

**Comment by JoelSanchez** [comment]
Hey, I got this. Turns out CodeMirror's support for Clojure is already there...
![image](https://user-images.githubusercontent.com/8020017/46002564-b6e36b00-c0ae-11e8-840b-32d1becc62f8.png)
Now I just need a prettifier to fix the whitespace and indentation.

**Comment by JoelSanchez** [comment]
Can I be assigned to finish this?

**Comment by JoelSanchez** [comment]
#1176 merged!

**Comment by gschier** [comment]
WoooO!
