### ISSUE TITLE
[Feature Request] Set cookies externally (from a browser)

### ISSUE THREAD

**Issue by Mosho1** [getinsomnia/insomnia#1178]
## Details

My use case is a server that sets a cookie that is used for development purposes. I get this cookie set in chrome and would like to somehow export it with a click to insomnia. Right now I have to copy/paste it and it's pretty inconvenient.

**Comment by gschier** [comment]
Could you make the same request that sets the cookie within Insomnia? that's how I usually do it. 

Nevertheless, a browser extension to do this is an interesting idea but not something I have the time to work on. Perhaps this could come out of the community? 😉

**Comment by stembrino** [comment]
I've developed a Chrome plugin that performs this integration. You can check out the demos in the README: https://github.com/stembrino/clipboard-curl-cookie/tree/master.
