### ISSUE TITLE
help with auth settings for Firebase app

### ISSUE THREAD

**Issue by jonathan-chin** [getinsomnia/insomnia#1180]
This is absolutely amazing and speeds up my development time. However, some of my endpoints require authentication through Firebase's email-and-password auth service. I can't use a service account because I need a user to be logged in (to get their UID etc),

Anyone have an idea about how I can set this up?

**Comment by gschier** [comment]
If it uses OAuth 2.0 you should be able to use insomnia’s OAuth support.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonathan-chin** [comment]
Is there a guide somewhere? I'm just unsure where to fet all the info to fill into the Insomnia settings.

**Comment by gschier** [comment]
It really depends on the type of auth you need. I'm not familiar with Firebase auth. If you could provide some more details on this then I could offer some advice.

A while ago I did write a blog post on the OAuth 2.0 stuff but it was for the GitHub API. Might still be worth a read to understand how it works. Again, this will only be relevant if FB supports OAuth 2.0 https://insomnia.rest/blog/oauth2-github-api/

**Comment by joshuarichards001** [comment]
For anyone still struggling with this issue, I wrote an article on it here. Hope this helps.

https://medium.com/@josh-richards/using-firebase-auth-in-insomnia-7a43fb92a8f8
