### ISSUE TITLE
Disable encode [ and ] symbols

### ISSUE THREAD

**Issue by 4n70w4** [getinsomnia/insomnia#1182]
Version 6.0.2
Shell 1.8.7
Node 8.2.1
V8 5.9.211.38
Architecture x64

libcurl/7.51.0-DEV OpenSSL/1.0.2j zlib/1.2.8 libssh2/1.6.1_DEV

## Details

Hi! I need make request like: /callback.php?order_id=399722&amount=7701&transaction_ids=[%22098c826353e2fdb6e476%22]

But Insomnia convert request to /callback.php?order_id=399722&amount=7701&transaction_ids=%5B%22098c826353e2fdb6e476%22%5D

[ replaced to %5B
] replaced to %5D

For my script, it is critical to receive a query in accuracy and without conversion. I spent the whole day looking for a mistake, but it turned out that this insomnia changes the request.

**Comment by 4n70w4** [comment]
Solved by disable «Automatically encode special characters in URL» in «Request Settings».
The option is well hidden, its location is not obvious.

![image](https://user-images.githubusercontent.com/38257723/46181521-0b653100-c2cf-11e8-9112-66689bf74d68.png)

**Comment by gschier** [comment]
Yes, it's well-hidden because it's not highly-used 😉

**Comment by RVRX** [comment]
Where is this setting located in the current version?
Would be nice if the location was added to this page in the docs: https://docs.insomnia.rest/insomnia/encoding#troubleshoot-special-character-issues

**Comment by oarthursilva** [comment]
> Solved by disable «Automatically encode special characters in URL» in «Request Settings». The option is well hidden, its location is not obvious.
> 
> ![image](https://user-images.githubusercontent.com/38257723/46181521-0b653100-c2cf-11e8-9112-66689bf74d68.png)

thanks, it worked for me :)

**Comment by evs-xsarus** [comment]
@RVRX  location found:

![image](https://github.com/Kong/insomnia/assets/44158071/7a488c3f-6491-49cf-af55-3397b3e3ec49)

**Comment by evs-xsarus** [comment]
This setting only applies on the URL, could this be added to the entries in the query tab?

**Comment by guidsen** [comment]
Unfortunately, query parameters are still escaped... Really annoying. Worked with several APIs that cannot handle the escaped version. Any way it can be fully disabled?
