### ISSUE TITLE
 [Feature Request] Add option for self-hosting the Insomnia account server

### ISSUE THREAD

**Issue by xMateMCPE** [getinsomnia/insomnia#1185]
You can add an account to the Insomnia client, but you cannot self-host it. This is the only thing thats keeping me from changing to Insomnia. If someone could add an option for self-hosting, that would be appreciated.

**Comment by gschier** [comment]
Please see the original discussion on the topic here: https://github.com/getinsomnia/insomnia/issues/190#issuecomment-300964765
