### ISSUE TITLE
[Feature Request] «Import from URL» to POST Form

### ISSUE THREAD

**Issue by 4n70w4** [getinsomnia/insomnia#1187]
Version 6.0.2
Shell 1.8.7
Node 8.2.1
V8 5.9.211.38
Architecture x64

libcurl/7.51.0-DEV OpenSSL/1.0.2j zlib/1.2.8 libssh2/1.6.1_DEV

## Details

Hi! I need fast fill form fields from URL like «Import from URL» from «Query»:
LMI_MODE=1&LMI_PAYMENT_AMOUNT=0.50&LMI_PAYMENT_NO=4&LMI_PAYER_COUNTRYID=RU&LMI_PAYER_PCOUNTRYID=RU&LMI_SYS_INVS_NO=750&LMI_SYS_TRANS_NO=555&LMI_SYS_TRANS_DATE=20181001%2B03%3A46%3A35

![image](https://user-images.githubusercontent.com/38257723/46265482-8e84c200-c52f-11e8-85c8-2ee2751c3d22.png)

**Comment by gschier** [comment]
I don't think this should be added to the app because the query params are not related to the request body in any way.

However, there _is_ a way to do it already:

![form](https://user-images.githubusercontent.com/587576/46352196-329d6480-c627-11e8-864f-357cb9d6be9d.gif)

**Comment by 4n70w4** [comment]
Thanks, this is what I need. But it is pretty damn obvious. I believe that we need to seriously work with usability and user expiriens.
