### ISSUE TITLE
[Bug] Python Requests code generation drops query string parameters

### ISSUE THREAD

**Issue by c22** [getinsomnia/insomnia#1188]
- Insomnia Version: 6.0.2 (6.0.2.2311)
- Operating System: macOS Sierra 10.12.6

## Details

If you try to generate code using the "Python > Requests" method, it seems to ignore what's in the querystring, I checked all the other code generators (including Python http.client) and they don't seem to be affected by this issue.

To reproduce:

`https://test.null/test?bug=true`

Result:
```
import requests

url = "https://test.null/test"

payload = ""
response = requests.request("GET", url, data=payload)

print(response.text)
```

Expected result:
```
import requests

url = "https://test.null/test"

payload = {'bug': 'true'}
response = requests.request("GET", url, data=payload)

print(response.text)
```

**Comment by c22** [comment]
Note that I'm not really sure what the expected usage pattern of requests is when you need to POST data in the BODY *and* have a querystring parameter in the URL.

**Comment by thewheat** [comment]
Hi! I'd like to work on this if possible 😃
