### ISSUE TITLE
[Bug] Code generation reverses order of query string parameters

### ISSUE THREAD

**Issue by c22** [getinsomnia/insomnia#1189]
- Insomnia Version: 6.0.2 (6.0.2.2311)
- Operating System: macOS Sierra 10.12.6

## Details

Not that it should matter under most circumstances, but I noticed the code generator reverses the order of the query string from the original request. This happens with all the generators, so it's probably happening at the parser stage. I imagine querystring parameters are being popped off the end of the URL (haven't checked the code).

To reproduce:

`https://test.null/test?a=1&b=2&c=3`

Result (Shell HTTPie Example):
```
http GET 'https://test.null/test?c=3&b=2&a=1'
```

Expected result:
```
http GET 'https://test.null/test?a=1&b=2&c=3'
```

Probably a low priority bug but also something that is likely easy to fix :)

**Comment by jamesallured** [comment]
I'd like to pick this up! 😎

**Comment by gschier** [comment]
Thanks for taking care of this @jamesallured!
