### ISSUE TITLE
[Feature Request] Alllow use env variables in token's fields

### ISSUE THREAD

**Issue by mykolaivashchuk** [getinsomnia/insomnia#1190]
For testing requests, I create one long live token. 
Now I couldn't put it in env var and just type the name of a variable when I'm creating a new request.
![image](https://user-images.githubusercontent.com/42264703/46336685-38e60d80-c634-11e8-9c6e-b3146d6853ca.png)

So my proposal is to add the possibility to use environments variables in request token and access token fields.

I think it will be cool and useful feature.

**Comment by gschier** [comment]
Hmm, I agree that it would be useful but it might be a bit complicated to support it. 

For now, If you already have a token you could also add it directly as a header, which is what the OAuth 2 integration would do anyway.

![image](https://user-images.githubusercontent.com/587576/46350452-d1739200-c622-11e8-96d0-92e84830b212.png)
