### ISSUE TITLE
[bug] Not rendering fonts correctly

### ISSUE THREAD

**Issue by beeblebrox3** [getinsomnia/insomnia#1194]
- Insomnia Version: 6.0.2 (installed via snap)
- Operating System: Elementary OS 5 Beta

## Details
This started yesterday. When I open, all characters are replaced by some kind of `?`:

![image](https://user-images.githubusercontent.com/767624/46354467-0ee11b00-c635-11e8-8efc-635d2d78d413.png)

**Comment by beeblebrox3** [comment]
When I restart the system it come back to normal, but after resume from suspension this happen again.
I'm trying the AppImage version and is working fine. Really weird behavior 🤔

**Comment by gschier** [comment]
Going to close this one for now as it seems like an environment-specific issue. However, I want to mention that a recent version of Insomnia added the ability to change the font. Not sure if that would help the situation, but it might!
