### ISSUE TITLE
[Bug] A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by RGTimothy** [getinsomnia/insomnia#1195]
- Insomnia Version: 6.0.2
- Operating System: Ubuntu 18.04

## Details

My Insomnia is just stop working. It will always show forever loading whenever I execute any request. This window error came up right after I click Insomnia icon to run it. I can't export any of my requests as well. Please help. Thanks.

![screenshot from 2018-10-03 12-51-33](https://user-images.githubusercontent.com/3026828/46392289-17a42080-c70b-11e8-92c0-4d6271a3b134.png)

**Comment by Masov** [comment]
@RGTimothy I think it is related to this issue: #1152 
I hope you will find an answer.

**Comment by gschier** [comment]
I think that means the local request DB (could also be another DB file) is too large to open. Have you been sending requests with large bodies?

**Comment by RGTimothy** [comment]
> @RGTimothy I think it could be related to this issue: #1152
> I hope you will find an answer.

It doesn't work. I've just reinstalled it :)

@gschier yes I did. Actually it was a post request with base64 string of an image, that's why. Thank you for helping me.

**Comment by xopi24** [comment]
its not working on me too. I have not yet exported by insomnia files :(

**Comment by durinf** [comment]
"JavaScript Error occured in the Main Process"
is happening on ver. 6.20 / 6.2.3 
There are no steps to reproduce. Simply,
try and install it (admin or not does not matter)

**Comment by Deividev365** [comment]
i just opened the insomnia using the run as administrator and it solved out. I hope it can help. if it keeps showing the same err, try reinstalling the application
