### ISSUE TITLE
[Bug] The interface looks like the 90s (snap)

### ISSUE THREAD

**Issue by samuelcecilio** [getinsomnia/insomnia#1196]
In the snap version, the interface looks like the 90s:

![captura de tela de 2018-10-03 09-58-39](https://user-images.githubusercontent.com/30150045/46411895-4a421f00-c6f3-11e8-9832-37ebf3596e4b.png)

Some snap applications seem to use the right theme, for example Mailspring:

![captura de tela de 2018-10-03 10-14-23](https://user-images.githubusercontent.com/30150045/46412555-40b9b680-c6f5-11e8-922a-04e424732afd.png)

**Comment by gschier** [comment]
Anyone know what might be the cause of this? I think this only happens on certain Linux distros

**Comment by evanslify** [comment]
I can reproduce this on Fedora 28. Current version on snap is 6.0.2, but this doesn't happen when running run repo.

**Comment by evanslify** [comment]
While running snap-installed `insomnia`, it shows:

```
$ LD_LIBRARY_PATH=/usr/lib64/gtk-3.0/modules/:$LD_LIBRARY_PATH insomnia
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
[fix] Running database repairs
[db] Initialized DB at /home/es/snap/insomnia/19/.config/Insomnia/insomnia.$TYPE.db
[localstorage] Initialized at /home/es/snap/insomnia/19/.config/Insomnia/localStorage
[main] Loading file:///snap/insomnia/19/app/resources/app.asar/renderer.html
[updater] Updater not running platform=linux dev=false
```

I do have these two libraries installed:

```
$ locate libcanberra-gtk-module.so
/usr/lib64/gtk-2.0/modules/libcanberra-gtk-module.so
/usr/lib64/gtk-3.0/modules/libcanberra-gtk-module.so
$ locate pk-gtk-module.so
/usr/lib64/gtk-2.0/modules/libpk-gtk-module.so
/usr/lib64/gtk-3.0/modules/libpk-gtk-module.so
```

If I run `/var/lib/snapd/snap/insomnia/current/app/insomnia`, it displays as intended and no error message shown. Since snapcraft apps run with their own libraries, and both files are missing from `snapd/snap/insomnia/current/lib`, adding these two libraries to `snapcraft.yml` or merely adding `/usr/lib64/gtk-3.0/modules/` to `$LD_LIBRARY_PATH can remedy this.

**Comment by evanslify** [comment]
Since `snapcraft.yaml` isn't in the repo, I cannot send a PR on this. It's up to you @gschier

**Comment by evanslify** [comment]
Sorry about the comment before; I went the wrong direction, it doesn't have anything to do with missing modules...

What part looks like 90s?

**Comment by samuelcecilio** [comment]
The menu bar and the "About" window. Some applications work fine, Mailspring for example.

````
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
````

````
$ snap --version
-----------------------------
snap       2.35.2
snapd      2.35.2
series     16
linuxmint  19
kernel     4.15.0-36-generic

$ snap info insomnia
-----------------------------
name:      insomnia
summary:   Insomnia REST Client
publisher: Gregory Schier (gschier1990)
contact:   https://insomnia.rest/support/
license:   unset
description: |
  A powerful REST API Client with cookie management, environment variables, code generation,
  and authentication for Mac, Window, and Linux.
commands:
  - insomnia
snap-id:      ZtF4mLp5Bededu3S65ocO6HfGXCtcvZ9
tracking:     stable
refresh-date: today at 15:07 -03
channels:                     
  stable:    6.0.2 (19) 120MB -
  candidate: ↑                
  beta:      ↑                
  edge:      0.1   (7)  4kB   devmode
installed:   6.0.2 (19) 120MB -
````

**Comment by samuelcecilio** [comment]
I dont know when or how, but this has been solved.

**Comment by gschier** [comment]
Woo! I updated some dependencies a little while ago so something might have fixed it. Thanks for the update! 😄
