### ISSUE TITLE
[Feature Request] Allow adding multiple endpoints for the same request

### ISSUE THREAD

**Issue by FinalButterfly** [getinsomnia/insomnia#1199]
I would like to propose adding the ability to have multiple endpoints for the same request. Any normal development environment will have multiple deployments of the same API, ranging from localhost to dev/devtest/preprod/prod. All of them have different endpoints. So, in a scenario where a developer wants to retain the same request body, query and headers, but wants to change the URL, it would be more convenient to have a drop-down list of all possible endpoints (excluding the query arguments), rather than making Ctrl+D duplicates and changing the endpoints manually. This would aid usability immensely and clean up the request list of duplicates, also speeding up testing of different deployments.

**Comment by yura3d** [comment]
If I correctly undestood your question, you need to use Environments feature.
Simply create new environment by clicking the icon below the workspace name (I have created one, so my screen differs from what you will see):
![image](https://user-images.githubusercontent.com/10958696/46587288-bc6b8880-ca92-11e8-8894-5dfa90e34ddd.png)
Then you can set environment name and specify variables, that you can use in your request headers, body and... URL.
For example:
![image](https://user-images.githubusercontent.com/10958696/46587196-22571080-ca91-11e8-90b2-4cdeeadc841e.png)
After that open any your request and simply start typing in the URL field the name of your request variable, and Insomnia will suggest you to insert it:
![image](https://user-images.githubusercontent.com/10958696/46587231-b32dec00-ca91-11e8-95eb-d373570f4b19.png)
You need to repeat the last step for all of your requests.
Now, by changing your environment (as shown on the 1st screen) you can choose endpoint for your requests just by 1 action.

**Comment by FinalButterfly** [comment]
Oh! Thank you. That's just what I needed. I did not search the UI enough for this. I'm sorry.
