### ISSUE TITLE
[Bug] GraphQL query variables editor flickers

### ISSUE THREAD

**Issue by berkaey** [getinsomnia/insomnia#1204]
- Insomnia Version: 6.0.2
- Operating System: macOS Mojave

## Details

Hey there, I just noticed if you have a long GraphQL query variables and then if you scroll a little bit. a click can shift the position of the editor. for ex: if you click on first row, editor instantly snaps to bottom, cursor position is correct only scroll position is wrong, I guess.

**Comment by gschier** [comment]
Hmm, yep I can confirm this. Will see if it's an easy fix.

**Comment by gschier** [comment]
Turns out it's not an easy fix 😢

**Comment by jdorleans** [comment]
It's been a while this is happening and, unfortunately, it's very annoying. @gschier Would that be a way to fix it by now or any workaround?
