### ISSUE TITLE
[Feature Request] Disabling update checking

### ISSUE THREAD

**Issue by xMateMCPE** [getinsomnia/insomnia#1210]
Hey. I would like to request an option to disable the update checking. I have disabled automatic update downloading, but the new update popup still shows up if a new update is available. If there would be an option in the settings to disable checking for updates, that would be appreciated.

**Comment by artywhite** [comment]
@Meyito, are you going to work with this issue? I'd like to try it as well :)

**Comment by gschier** [comment]
I would send a new parameter to the notification data called `disableUpdateNotifcation: true`. I'll add a check on the backend to not show the update notification when that parameter is present.

https://github.com/getinsomnia/insomnia/blob/99de4725fa036bf6268ce5921f2f3b7fcb41807f/packages/insomnia-app/app/ui/components/toast.js#L88

You can search the codebase for the existing `updateAutomatically` to see how to add a new setting.

**Comment by artywhite** [comment]
I was thinking about adding new setting called `checkForUpdates` - checkbox above `Automatically download and install updates` and if it's unchecked just not start interval checkings for updates https://github.com/getinsomnia/insomnia/blob/99de4725fa036bf6268ce5921f2f3b7fcb41807f/packages/insomnia-app/app/main/updates.js#L96

**Comment by gschier** [comment]
That's what `settings.updateAutomatically` already does on Windows and Mac. 

https://github.com/getinsomnia/insomnia/blob/99de4725fa036bf6268ce5921f2f3b7fcb41807f/packages/insomnia-app/app/main/updates.js#L47-L49

However, since there is no support for automatic updates on Linux, the notification endpoint notifies Linux users if the version that's passed is out of date.

**Comment by artywhite** [comment]
Sorry, didn't realize from beginning there is another update notification showing trigger except auto updater.
I've opened PR https://github.com/getinsomnia/insomnia/pull/1234

@Meyito, sorry I've taken this issue from you, can't wait more :)
