### ISSUE TITLE
[Bug] Alt + Shift problem

### ISSUE THREAD

**Issue by mmilanovic4** [getinsomnia/insomnia#1212]
- Insomnia Version: 6.0.2
- Operating System: Linux Mint 18.3 Sylvia (XFCE DE)

## Details

Hi,

I have found following problem: when I press `Alt + Shift` to change keyboard input language, menu is toggled on. Here are steps to reproduce:

- Check "Hide Menu Bar" in Insomnia > Preferences
- Press `Alt + Shift` to change keyboard language input, language is changed but menu is toggled on and focus is lost from the input field to the menu bar

![insomnia](https://user-images.githubusercontent.com/24554925/46909255-967d3280-cf2f-11e8-95de-41300e2ac401.gif)

I saw that similiar problem existed in VS Code, which is also project based on Electron.js, however that issue seems to be resolved there now.

**Comment by gschier** [comment]
This behavior is handled by Electron itself, so it should be fixed when I get around to upgrading Electron

**Comment by gschier** [comment]
Can you confirm if this is still an issue?

**Comment by mmilanovic4** [comment]
Insomnia version 6.2.3 - yes, it is.
