### ISSUE TITLE
[Bug] Body replaced by GraphQL body when switching requests quickly

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#1216]
Hard to explain, so here's a screen recording. Only seems to happen with GraphQL.
![screenflick movie 3](https://user-images.githubusercontent.com/587576/46991806-6bccde80-d0d5-11e8-8e87-b15b4d8ddf14.gif)

**Comment by cruhl** [comment]
This has been a major issue for me in recent days; it's gotten to the point where Insomnia is almost unusable. Thanks for creating this issue!

**Comment by gschier** [comment]
Figured out the issue and started on a fix. Quite a bit of refactoring/testing to do but should be in the next release 😄
