### ISSUE TITLE
Blank Screen on Linux Mint 17

### ISSUE THREAD

**Issue by matsinet** [getinsomnia/insomnia#1218]
- Insomnia Version: 6.0.2
- Operating System:
Kernel: 4.4.0-137-generic x86_64 (64 bit) 
Desktop: Cinnamon 2.6.13
Distro: Linux Mint 17.2 Rafaela

## Details

When executing a request the electron window goes blank (white) and the following error is displayed in the console:

[fix] Running database repairs
[db] Initialized DB at /home/mthomas/.config/Insomnia/insomnia.$TYPE.db
[localstorage] Initialized at /home/mthomas/.config/Insomnia/localStorage
[main] Loading file:///opt/Insomnia/resources/app.asar/renderer.html
[updater] Updater not running platform=linux dev=false
/opt/Insomnia/insomnia --type=renderer --enable-experimental-web-platform-features --no-sandbox --primordial-pipe-token=59795771281C79D7C0B755A5ED5F33E5 --lang=en-US --app-path=/opt/Insomnia/resources/app.asar --node-integration=true --webview-tag=true --no-sandbox --enable-pinch --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;0,16,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;1,16,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;2,16,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;3,16,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553;4,16,3553 --disable-accelerated-video-decode --disable-webrtc-hw-vp8-encoding --service-request-channel-token=59795771281C79D7C0B755A5ED5F33E5 --renderer-client-id=4 --shared-files=v8_natives_data:100,v8_snapshot_data:101: relocation error: /tmp/.org.chromium.Chromium.pSWhpw: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

Note: Downgrading to 6.0.1 resolves the issue.

**Comment by gschier** [comment]
Closing in favor of https://github.com/getinsomnia/insomnia/issues/1208
