### ISSUE TITLE
[Feature Request] Disable/Change frequency of GraphQL Introspection Queries

### ISSUE THREAD

**Issue by andrewackerman** [getinsomnia/insomnia#1219]
- Insomnia Version: 6.0.2
- Operating System: Mac OS 10.14

## Details

Please add a feature to lower the frequency of (or disable entirely) Insomnia sending introspection queries to the URL. I'm in the process of creating and debugging a GraphQL API using AWS Lambda+Serverless, and every time I make a call to my local instance, GraphQL follows it up with an introspection query, which produces a massive literal wall of text in the log output making debugging incredibly frustrating. I've been able to work around the issue by filtering out introspection queries on the API side, but that doesn't stop Insomnia from trying anyway and producing error popups every time it does. And when I'm not actively debugging the API itself, the autocomplete feature is nice to have, but it's annoying to have to keep going into the API to turn the filter on and off.

Proposed features

- Add an options menu for GraphQL, either as part of the preferences window or in the GraphQL tab (perhaps next to the "Prettify GraphQL" button).
- Add an "Enable Automatic Introspection" check box that, when unchecked, disables the automatic introspection.
- Add an "Enable Introspection After Query" check box that, when unchecked, disables the introspection query made after a normal GraphQL query.
- Add a "Change Introspection Interval" text field that accepts a positive integer for how many seconds pass between introspection queries. (This text box is grayed out if "Enable Automatic Introspection" is unchecked.)

I'm not sure what behavior the autocompletion should take if introspection is disabled entirely. Either it should be disabled as well, or it should use the last successful introspection that it received. Perhaps that can be a configurable setting as well.

**Comment by gschier** [comment]
I agree, it's a lot of fetching. It could probably be optimized a bit to not fetch so often but a manual toggle would be easy to add, and very useful.

There's already a way to manually trigger the introspection request, so I suggest just adding a "manual mode" toggle beside that for now.

![image](https://user-images.githubusercontent.com/587576/47130287-fbee5d80-d266-11e8-8f0e-001382563b8f.png)

**Comment by Maxwell2022** [comment]
+1000 for this, it's soooo annoying!  was okay when my schema was small to medium size. Now I need to increase my terminal line buffers in order to scroll back to the top see my debug message.

It's doing it **after** every request. I'd love to me able to manually trigger it when I need
