### ISSUE TITLE
[Feature Request] Add Request-Environment Tab

### ISSUE THREAD

**Issue by frederic-kneier** [getinsomnia/insomnia#1223]
It would be very helpful to be able to set preconfigured environment variables in the request window in an additional tab like the tab for query parameters.

A simple example would be part of the url or query parameters that are meant to be changed often like id values.

**Comment by wwselleck** [comment]
> A simple example would be part of the url or query parameters that are meant to be changed often like id values

For query parameters, how would this be different from the current query parameters tab?

**Comment by frederic-kneier** [comment]
Not only for query parameters but for variables in general

**Comment by frederic-kneier** [comment]
The main idea is to prepare a general request that can be customized by setting enviroment variables in an additional tab. This way the given variables can be used throughout the request eg in request url, query parameters, body and auth

**Comment by frederic-kneier** [comment]
An example would be a prepared request that can be parameterized using an additional tab with environment variables on a request scope. The tab can be designed just like the query parameters tab (key -> value) and those values in conjunction with the higher environment variables can be used in url, body, query parameters, headers and authentication

**Comment by frederic-kneier** [comment]
An example would be a prepared request that can be parameterized using an additional tab with environment variables on a request scope. The tab can be designed just like the query parameters tab (key -> value) and those values in conjunction with the higher environment variables can be used in url, body, query parameters, headers and authentication

**Comment by frederic-kneier** [comment]
An example would be a prepared request that can be parameterized using an additional tab with environment variables on a request scope. The tab can be designed just like the query parameters tab (key -> value) and those values in conjunction with the higher environment variables can be used in url, body, query parameters, headers and authentication.

Sorry for the reposts but my comments seem to vanish and reappear.

**Comment by frederic-kneier** [comment]
An example would be a prepared request that can be parameterized using an additional tab with environment variables on a request scope. The tab can be designed just like the query parameters tab (key -> value) and those values in conjunction with the higher environment variables can be used in url, body, query parameters, headers and authentication.

Sorry for the reposts but my comments seem to vanish and reappear.

**Comment by joshuaflanagan** [comment]
This is somewhat like the feature I need. Although I do not want to tie it to a specific request. I think of it as a "session environment". I don't want to create a persisted "Environment" every time I want to vary some variable values. I want to be able to define variables that I am using in the current session, and those variables can be used in any context that Environment variables can be used, across multiple Requests (just like Environment variables).

This is very useful when you make requests to the same endpoints _for many different users_. For example, if I have thousands of different credentials for a given endpoint, I don't want to create thousands of different environments, each configured with an `api_key` and `base_url` variable. I just want to set the values for a single account in my current "session" and use them across different requests, until I change them.

The Environment Priority becomes:

Session (highest priority)
Folder Environment 
Sub Environment
Base Environment (lowest priority)

I picture it as a collapsible text area in the left Sidebar, under the list of requests. The text area is the same editor you get when you use Manage Environments. You define a JSON hash with the variable values you want.
