### ISSUE TITLE
[Feature Request] - Possibility to change data folder from commandline

### ISSUE THREAD

**Issue by keklabs** [getinsomnia/insomnia#1225]
- Insomnia Version: 6.0.2
- Operating System: Windows 10

## Details

I want to control where will be the insomnia data stored and loaded from.  I tried to change %APPDATA% environment variable before run of insomnia.exe, but this has no effect - insomnia still uses the user default appdata folder. 

It will be very helpfull if I can run insomnia with some command line parameter  or set some ENV variable for it like:

insomnia.exe  -data c:\workdir\insomnia\data

or

insomnia.exe  -d c:\workdir\insomnia\data

or

set INSOMNIA_DATA_PATH=c:\workdir\insomnia\data
insomnia.exe

This provides the possibility to run more instances of insomnia initialized from differend data folders, or specify  path, which I use for data  or  than I can specify my project folder managed by GIT, without need to always reimport and reexport all workspaces in one insomnia instance. 

Thank you for your great tool.

**Comment by danothemen** [comment]
Added your third suggestion in pull 1229
