### ISSUE TITLE
[Bug] Can't select a portion of a response without launching a browser window

### ISSUE THREAD

**Issue by scott-r-lindsey** [getinsomnia/insomnia#1232]
- Insomnia Version: 6.0.2
- Operating System: Linux Mint 18

## Details

Insomnia is very aggressive about launching links in responses -- so much so that even selecting a portion of a link triggers a new browser window.

If possible, a drag should be handled differently than a click, because it is impossible to select a link without launching it, which may cause un-intended side-effects like updating of cookies, starting of jobs, etc.

**Comment by SystemDisc** [comment]
This really needs to be fixed. Please add an option to not automatically create links from URLs.

**Comment by SystemDisc** [comment]
@gschier You rock!

**Comment by gschier** [comment]
You too! Thanks for reminding me about this 😄
