### ISSUE TITLE
[Bug] specific type of data responses freeze the app

### ISSUE THREAD

**Issue by snasaio** [getinsomnia/insomnia#1242]
- Insomnia Version: 6.0.2
- Operating System: Windows 10

## Details

This is similar to the old issue with large responses.  I had a large set of data return that is under the MB (only 700kb) threshold but still freezes the UI.  The result set was a single column CSV file with 59k rows only containing a 4 digit number.

A more generic fix would be to find a way to let the user open the app without it loading the preview so the user can delete just the one bad response. Sort of like a safe mode.

[dumpProjectRawData-1540429369042.zip](https://github.com/getinsomnia/insomnia/files/2532007/dumpProjectRawData-1540429369042.zip)

**Comment by gschier** [comment]
Ah yes, this makes sense. CSV responses get rendered as an HTML table, which is not optimized for performance. A proper fix for this would be to not load all rows by default, and show a "load more" button at the bottom.

Were you able to get the app running again? If not, you can delete individual responses from the data folder, accessible from Help > Show App Data Folder.

**Comment by gschier** [comment]
Having some sort of "safe mode" like you said would also be nice and would cover a broader set of cases. I wish there were a way in JS to tell when it's stuck trying to render too much HTML and toggle safe mode automatically 😭

**Comment by snasaio** [comment]
That would be nice.  You could create a started load / loaded correctly
flag that could show you if it failed so it can automatically not load it
next time the UI is open.

**Comment by gschier** [comment]
Oh that's a great idea!!! 👏👏👏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
