### ISSUE TITLE
[Bug] https status 102 not supported

### ISSUE THREAD

**Issue by samisagit** [getinsomnia/insomnia#1247]
- Insomnia Version: v6.0.2
- Operating System: Ubuntu 17.04

## Details
When using Insomnia to make request that returns an http response code of 102 (Processing) it indicates that no headers or data were returned. Linked to this issue is the fact that because this status isn't supported the request takes ~2 seconds to output this error:

`Error: Server returned nothing (no headers, no data)`

rather than immediately stating the code isn't supported.

Could insomnia either support this response code, or if that's not in scope support a more useful error message such as "http code not supported" if the code is sent by the API but not supported by Insomnia to save confusion.

Happy to submit a PR if this is worth a shout.

**Comment by gschier** [comment]
Hey @samisagit. I'm not quite sure what's happening here. Insomnia uses `libcurl` to make requests, which I can confirm returns an error (see example below). I'm not, however, seeing the delay you speak of. If you can post the result from the Timeline tab or provide a public URL that can reproduce the problem, I may be able to see the issue.

```
curl -v http://httpbin.org/status/102  
*   Trying 54.174.228.92...
* TCP_NODELAY set
* Connected to httpbin.org (54.174.228.92) port 80 (#0)
> GET /status/102 HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 102 PROCESSING
< Connection: keep-alive
< Server: gunicorn/19.9.0
< Date: Tue, 06 Nov 2018 00:08:02 GMT
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=utf-8
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Via: 1.1 vegur
* Illegal or missing hexadecimal sequence in chunked-encoding
* stopped the pause stream!
* Closing connection 0
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
```
