### ISSUE TITLE
[Bug] Cannot disable cookies

### ISSUE THREAD

**Issue by mlambley** [getinsomnia/insomnia#1248]
- Insomnia Version: 6.0.2
- Operating System: Mac

I'm using basic auth as required by the shopify api. Get requests work fine, but post requests just 301 redirect. I'm getting the response:

```
{
  "errors": "For security reasons, requests using HTTP Basic Authentication cannot include cookies."
}
```

I've looked through the settings and cannot find where cookies are configured. Please advise and/or implement a way to disable all cookies. Thank you.

**Comment by gschier** [comment]
You can disable cookies in the settings for a request

![image](https://user-images.githubusercontent.com/587576/48034505-b4544680-e12d-11e8-8cbd-6ba174476839.png)

![image](https://user-images.githubusercontent.com/587576/48034510-bae2be00-e12d-11e8-8ba0-24e34f86ad30.png)
