### ISSUE TITLE
[Feature Request] – Add support for client certificates on Smart Cards

### ISSUE THREAD

**Issue by egret85** [getinsomnia/insomnia#1250]
- Insomnia Version: 6.0.2
- Operating System: Windows 10

## Details

Please add support for client certificates on smart cards with the new Insomnia standalone app.  The Insomnia Chrome App (v2.7.0) allows this.  The current option for adding client certificates in the standalone app does not work for this case due to not having access to the private key directly.

**Comment by gschier** [comment]
Can you explain what a smart card is? Also, where does Chrome get the private key from?

For some background, Insomnia uses the `libcurl` library to send requests. If you can figure out a way to get your request working with Curl via the command line, you _should_ be able to get it working in Insomnia.

**Comment by egret85** [comment]
A smart card is a plastic card with a built in microprocessor that contains a certificate and private key (similar tech to new chip credit cards).  Access to the private key must be don't through the card driver and uses a PIN.  Most smart card middleware solution provide access through PKCS11 via a dll.  

Chrome seems to use the Windows APIs for certificates to use the built in Windows certificate stores.  Since Windows has built in support for these types of hardware tokens, it seems to just work.  When using the chrome app version of insomnia to call an endpoint requiring client certificates, Chrome displays a popup asking to select the certificate.  This popup lists all the certificates in the current users Windows certificate store and this includes the smart card certificates.  Selecting one of them causes Windows to prompt for a PIN and the call works.

Smart cards are a fairly common way enterprise and government handle client certificates for authentication.

**Comment by egret85** [comment]
for libcurl, it seems that support for the windows certificate stores requires building libcurl with Windows SSPI and Schannel support instead of OpenSSL.

**Comment by gschier** [comment]
Sorry, I've been away for a while. Yes that makes sense. This feature is probably too niche for me to work on but I'd be open to a community contribution. Unfortunately, I can't really offer any advice here because I'm also in the dark when it comes to this stuff.
