### ISSUE TITLE
[Feature Request]Request parameters allow multiple tabs

### ISSUE THREAD

**Issue by oooo0oooo0** [getinsomnia/insomnia#1251]
- Insomnia Version: 6.0.2
- Operating System: windows 10

## Details

There are different parameters in different environments, but I need to manually modify the parameters after switching environments.
Ideally, the parameter allows multiple tabs, which makes it easy to switch between different parameters depending on the environment.

**Comment by gschier** [comment]
This isn't ideal, but it could work depending on what you're doing. 

For this, you could set all the parameters in a single environment variable and add the variable to the end of the URL (instead of the Params tab)
