### ISSUE TITLE
[Bug] Base enviroment resets when unsynced device returns

### ISSUE THREAD

**Issue by brolaugh** [getinsomnia/insomnia#1252]
- Insomnia Version: 6.0.2
- Operating System: Windows 10

## Details
My development team uses shared workspaces for our development and we've noticed that when a device which haven't been synced in a couple of weeks reconnects to the workspace it resets the base enviroment its(the unsynced device) last version for everyone.

We only use base enviroment and private enviroment so I don't know if the "normal" enviroments are affected.

**Comment by gschier** [comment]
It's possible that you could be seeing the effect of the automatic conflict resolution strategy. When both the client and server representations of a synced resource have changed, the client will select the one that was modified most recently. So, if I client had not synced in a while, but had modified a resource more recently than the one on the server, it will be overwritten.

Please let me know if that sounds like it could be the issue. If not, feel free to reach out to support@insomnia.rest with your account details and I can take a closer look.

FYI, I have received quite a lot of questions along these lines which has prompted me to begin working on a more git-like sync model to help make work with teams more predictable. I can't provide a roadmap yet but any feedback on this would be appreciated

**Comment by brolaugh** [comment]
It's great to hear that you're working on git-like sync. 
I've sent an email regarding my account details.
