### ISSUE TITLE
Sending XML UTF-8 body with accented vowels (Spanish), get encoded as two bytes

### ISSUE THREAD

**Issue by ppazos** [getinsomnia/insomnia#1260]
- Insomnia Version: 5.16.6
- Operating System: Linux Mint 17.3 (Ubuntu 14.04)

## Details

Sending a POST request with XML body, and capturing the traffic with Wireshark, noticed that "é" is sent as two bytes 0xC3 0xA9 (hex). "é" should be encoded in one byte using UTF-8 with value 130 decimal (0x82).

My XML is like:

```
<?xml version="1.0" encoding="UTF-8"?>
<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:voc="urn:hl7-org:v3/voc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <typeId extension="POCD_HD000040" root="2.16.840.1.113883.1.3"/>
  <id root="db734647-fc99-424c-a864-7e3cda82e703"/>
  <code code="34133-9" codeSystem="2.16.840.1.113883.6.1" displayName="Summarization of episode note"/>
  <title>Carné de Salud</title><!-- ****** HERE IS THE PROBLEM ***** -->
  ...
</ClinicalDocument>
```

In Wireshark I see the correct bytes for "Carn" then two bytes for the "é".

Also tried with Content-TYpe: application/xml;charset=utf-8 the result is the same as having just application/xml

**Comment by gschier** [comment]
Does `curl` showcase the same behavior when run from the command line?
