### ISSUE TITLE
[Bug] GraphQL Intellisense ignores default values for non-null parameters

### ISSUE THREAD

**Issue by andrewackerman** [getinsomnia/insomnia#1261]
- Insomnia Version: 6.2.0
- Operating System: Mac OS Mojave 10.14

## Details

The new addition that limits the introspection query is awesome, but I've found a bug with how the Intellisense handles the results. I have a number of query functions that take optional parameters. These parameters are implemented as non-null types with default values. An example of such looks like this:

    accounts(count: Int! = -1, skip: Int! = 0): [Account!]

(The purpose of such being that I can treat the function like a database query, passing along the count and skip values to the corresponding SQL query in the backend.)

When Insomnia pulls the schema from the introspection query, I get the red underlines on all the function calls where these parameters aren't specified, saying that the parameters are "required but not provided".

![screen shot 2018-11-15 at 12 47 33 pm](https://user-images.githubusercontent.com/35783214/48577604-c031cc80-e8d4-11e8-898c-32df49405677.png)

This is incorrect behavior, as the schema should deduce by the presence of a default value that even though the parameter is not nullable, it is still optional. **From what I can tell, this behavior is consistent across all functions, whether they are the root query or a nested query.**

For reference, this is the relevant part of the introspection query that shows the types and default values of the parameters:

```json
{
  "name": "accounts",
  "description": null,
  "args": [
    {
      "name": "count",
      "description": null,
      "type": {
        "kind": "NON_NULL",
        "name": null,
        "ofType": {
          "kind": "SCALAR",
          "name": "Int",
          "ofType": null
        }
      },
      "defaultValue": "-1"
    },
    {
      "name": "skip",
      "description": null,
      "type": {
        "kind": "NON_NULL",
        "name": null,
        "ofType": {
          "kind": "SCALAR",
          "name": "Int",
          "ofType": null
        }
      },
      "defaultValue": "0"
    }
  ],
  "type": {
    "kind": "LIST",
    "name": null,
    "ofType": {
      "kind": "NON_NULL",
      "name": null,
      "ofType": {
        "kind": "OBJECT",
        "name": "Account",
        "ofType": null
      }
    }
  },
  "isDeprecated": false,
  "deprecationReason": null
}
```

**Comment by gschier** [comment]
This behavior is entirely handled by the `graphql` and `codemirror-graphql` packages. It looks like there's are new versions so I'll bump them and see if that fixes things.
