### ISSUE TITLE
[Feature Request] Ability To Toggle Displaying Complete Content

### ISSUE THREAD

**Issue by karthicraghupathi** [getinsomnia/insomnia#1262]
- Insomnia Version: 6.2.0.2505
- Operating System: macOS High Sierra 10.13.6

## Details

The timeline feature in Insomnia is great to show complete debug log of an API request.

Today the content is automatically hidden if the size of the data chunk is above some hardcoded value. This is referenced here: https://github.com/getinsomnia/insomnia/issues/174#issuecomment-407432995

Here is an example of what this looks like:

<img width="1180" alt="unhide_content" src="https://user-images.githubusercontent.com/1508545/48583808-16633780-e8f6-11e8-9852-e91f532c5ece.png">

I'm requesting the ability to toggle the automatic hiding. When working with API creators, it would be great to just give them a dump of the timeline view to show exactly what was sent and what response was received.

**Comment by clintharris** [comment]
+1. Being able to see the multipart form payload--even if the data chunks are hidden or abbreviated--would be really helpful.

**Comment by gschier** [comment]
Hmm, it looks like there's already a `settingMaxTimelineDataSize` on the `Request` model. Just need to add the UI to the request settings dialog. Would be an easy one if someone wanted to take a look.

**Comment by littlewulu** [comment]
+1. I was in the same predicament.

**Comment by RuslanZavacky** [comment]
@gschier is there a way how to change this setting now, without UI changes?

**Comment by gschier** [comment]
Not at the moment. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gschier** [comment]
This will be live in the next release

![image](https://user-images.githubusercontent.com/587576/56847426-915e5000-688f-11e9-8fbb-df0a7dce06f6.png)
