### ISSUE TITLE
[Feature Request] Add Hawk ext feature

### ISSUE THREAD

**Issue by rpless** [getinsomnia/insomnia#1263]
- Insomnia Version: 6.2.0
- Operating System: macOS High Sierra 10.13.6

Hawk supports an ext feature for including application specific information beyond user and key inside the authorization header. This is used because Hawk only considers `Host` and `Content-Type` in the MAC calculation. See the [Hawk repo](https://github.com/hueniverse/hawk#coverage-limitations) for a more detailed explanation. 

In practice, this would mean adding another field in https://github.com/getinsomnia/insomnia/blob/develop/packages/insomnia-app/app/ui/components/editors/auth/hawk-auth.js and updating the hawk-auth file to include `ext` in the calculation.

I think this is pretty low impact change that would let user's make use of more of Hawk's functionality.
I'm happy to make a PR for this.

**Comment by gschier** [comment]
PR is welcome 👍🤗

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
