### ISSUE TITLE
[Feature Request] Search method in text

### ISSUE THREAD

**Issue by umanking** [getinsomnia/insomnia#1268]
- Insomnia Version: ___
- Operating System: ___

## Details

I want you to develop new Feature "search method in text" 
I hava a lot of rest api in my workspace. 
sometimes, I want to find my rest api call that I want to
but i can't!!

**Comment by gschier** [comment]
Can you give an example of something you want to search? It may already be possible from the request switcher dialog Cmd/Ctrl + P
