### ISSUE TITLE
[Bug] Variables reported as non-existent on GraphQL Mutations

### ISSUE THREAD

**Issue by thanpolas** [getinsomnia/insomnia#1270]
- Insomnia Version: 6.2.0
- Operating System: OSX Mojave

## Details

When writing graphql mutations, the editor reports the variables as non-existing, while the mutation execution works ok.

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/2a193A233U0A052v323R/Image%202018-11-21%20at%2011.51.09%20AM.png)

**Comment by gschier** [comment]
This behavior is controlled by the `graphql` and `codemirror-graphql` plugins. I just updated both of them and it looks like it may have fixed the issue.
