### ISSUE TITLE
[Feature Request] Choose which folders to export from a workspace

### ISSUE THREAD

**Issue by soderluk** [getinsomnia/insomnia#1273]
- Insomnia Version: Version 6.2.0
- Operating System: Ubuntu 18.04

## Details

I have one workspace with a bunch of folders containing a lot of requests. When exporting, I can only choose the current, or another workspace. This exports everything in the workspace. 

It would be great if I could choose which folders in the workspace to export, instead of exporting everything. This is useful e.g. when only a part of an APIs requests needs to be exported to the project repository.

**Comment by gschier** [comment]
I like this idea. Would it be okay to just have the ability to export a single folder, or would you need to be able to export multiple?

**Comment by soderluk** [comment]
Multiple folders would be great! E.g. I have a folder containing all requests for one part of the API, then another folder with all requests for another part of the API, I'd like to be able to choose those two folders to export, and skip all the rest random folders with other API calls.

This structure is legacy from my Postman times, and hadn't really figured out the workspace layout in insomnia yet, but I'm working towards that. But to do that, I want to be able to export separate folders, either one or more.

**Comment by ydorea** [comment]
This would be a very helpful improvement! Now when I want to copy a request or some specific folders, I have to create another workspace just for exporting them.

**Comment by gschier** [comment]
It should be fairly easy to implement this as a feature (I think). Anyone want to take a crack at it?

**Comment by gschier** [comment]
Awesome! Let me know if you need any help. 

One thing to note, which you may have though of already, is you need to make sure the necessary environments are also exported. I think the only thing needed is to make sure the parent folders and the workspace environments remain included in the export.
