### ISSUE TITLE
[Bug] shared sync with subfolders does not work

### ISSUE THREAD

**Issue by SBejga** [getinsomnia/insomnia#1278]
- Insomnia Version: 6.2.0
- Operating System: macOS 10.14.1 (mojave)

## Details

We are sharing a workspace with several folders. Some of them contain again folders. 
We found out that a folder will not synced to my team mates when it has subfolders. This was reproducable with a new shared workspace. 

- Create new workspace with two folders
  - one containing one subfolder containing a request
  - one containing one request (without subfolder)
- share the workspace
- team mate opens shared workspace, he will just see the folder containing the request, but not the folder with subfolder.

**Comment by gschier** [comment]
Hmm, I have tried to reproduce this locally but everything seems to be working fine. Does this happen for all subfolders you try? What if you create/sync a fresh workspace?
