### ISSUE TITLE
Request disappears after I accidentally clicked "Move" in request settings

### ISSUE THREAD

**Issue by oliverjanik** [getinsomnia/insomnia#1280]
- Insomnia Version: 6.2.0
- Operating System: Win 10

## Details

After putting hard work into setting up my request and writing documentation my request just disappeared. Why? I accidentally clicked "Move" in Request setting dialog:

![image](https://user-images.githubusercontent.com/2280140/49121840-1a378680-f306-11e8-9f5e-74cd983944b5.png)

This is very frustrating experience. Should there not be a validation before you move a request to a blackhole?

Also why on earth do the dialogues not have an OK or Save or Apply buttons? Instead they automatically apply settings. This is extremely counter-intuitive for Windows users at least. To successfully exit the dialog and have my changes applied I need to press "X" in the top right corner. I always pause for a second to make sure I'm not actually cancelling my changes.

I clicked Move because of muscle memory. The way that button is positioned it looks like an OK button if you're not careful.

**Comment by gschier** [comment]
I agree that it's frustrating and it definitely wasn't done on purpose, that's for sure! Some bugs are bound to slip through the cracks

🤗

**Comment by oliverjanik** [comment]
Thank you for your prompt response.
