### ISSUE TITLE
[Feature Request] request setting to skip rendering of response body

### ISSUE THREAD

**Issue by snasaio** [getinsomnia/insomnia#1281]
- Insomnia Version: 6.2
- Operating System: Windows 10

## Details
Please add a request setting to skip rendering of response body.

I have a few resquests that return a large amount in a csv.  The response is not big enough to freeze the app, but I dont want to wait for it to render anyway.

**Comment by gschier** [comment]
You can change the preview type to "Source Code" 

![image](https://user-images.githubusercontent.com/587576/49193570-8093c780-f34d-11e8-9746-06d1b6e26c49.png)

**Comment by snasaio** [comment]
that works
