### ISSUE TITLE
[Bug] Client certificates not working on 6.2.0

### ISSUE THREAD

**Issue by jvtrigueros** [getinsomnia/insomnia#1284]
- Insomnia Version: 6.0.2, 6.2.0
- Operating System: macOS Mojave

## Details

In version 6.0.2, when adding Client Certificates, they would be used correctly to authenticate against my server. However, when upgrading to 6.2.0, this no longer works, the only error I get is:
```
Error: Problem with the local SSL certificate
```

To reproduce:
* Open `Workspace Settings`
* Navigate to `Client Certificates`
* Add New
* Then fill in the host and add a `CRT File` and `Key File`
* Perform a GET request to the specified host

Let me know if there's any more info I can gather from my client, there were no errors in the Developer Console.

**Comment by GrayedFox** [comment]
I can confirm this bug and would add that adding the valid signing root CA certificate (cert.pem) in place of the servers signed cert and key also does not work. 

The error I get is "peer certificate cannot be authenticated with given CA certificates". It is not clear to me whether I need to specify a port or not (the dialogue says port is optional, but I have QA trust issues...).

![insomnia-cert-bug](https://user-images.githubusercontent.com/6493307/49237960-b6918400-f3ff-11e8-9eb1-fc8dcefd2aa2.png)

**Comment by rruizt** [comment]
I'm running 6.2.0 and I cannot reproduce the bug.

OS: Ubuntu 18.04

I've configured CRT, Key and Passphrase and everything works as expected.

**Comment by GrayedFox** [comment]
@rruizt would you mind sending a picture of your certificate setup? (like my screenshot) - I would be keen to see if anything is different!

**Comment by gschier** [comment]
I don't think anything would have changed in the app to break client certificates. However, on Mac, Insomnia uses the OS version of `libcurl` and macOS High Sierra (or maybe Mohave, I forget) changed the SSL library that `libcurl` was built with, affecting some cert stuff. 

Did you just update your OS recently?

**Comment by jvtrigueros** [comment]
That's what I thought initially too, but I downloaded both versions of Insomnia, 6.0.2 and 6.2.0. Configure them the same, side by side, run the same query and can repro 100% of the time.

If there's any log output that I can capture from the app I'll gladly provide these, I just don't know where they would be.

**Comment by gschier** [comment]
Oh, that's very strange. There might be some debug info printed in the Timeline tab. 

If not, then if you can provide a dummy CRT/Key file, I could use it to test on my end?

**Comment by rruizt** [comment]
@GrayedFox Here is the screenshot. The host part is redacted but it's basically the hostname without any port numbers.

![screenshot from 2018-11-30 18-01-24](https://user-images.githubusercontent.com/7413098/49304092-a941cb80-f4cb-11e8-8097-3bb0105f967c.jpg)

May I suggest to test with a key that requires a passphrase?

**Comment by GrayedFox** [comment]
Ah, I should maybe mention that am running Ubuntu LTS 18.04 with the latest Insomnia (6.2.3)

**Comment by gschier** [comment]
Hmm, @jvtrigueros I don't get the same thing on Mac (Mojave) on Insomnia 6.2.3

```
* Using libcurl/7.54.0 LibreSSL/2.6.4 zlib/1.2.11 nghttp2/1.24.1
```

**Comment by jvtrigueros** [comment]
Ok so I figured out the issue, I did `brew install curl` but I needed to do `brew install curl --with-nghttp2`.

This triggers the installation of curl with openssl instead of Apple's SSL library.

I will also add that using the default curl on Mojave works as expected, just not when installing with brew using no flags.

Thanks again for the help! All is well, I'll close this issue.

**Comment by GrayedFox** [comment]
This might indeed be the solution for Ubuntu as well, if a specific OpenSSL version is required? 

My installed vesion is `OpenSSL 1.1.0g` - is this the version Insomnia expects?

**Comment by jvtrigueros** [comment]
Perhaps, after installing curl with those flags, this is what `--version` outputs for me:
```
curl 7.62.0 (x86_64-apple-darwin18.2.0) libcurl/7.62.0 OpenSSL/1.0.2q zlib/1.2.11 brotli/1.0.7 libidn2/2.0.5 nghttp2/1.35.0
Release-Date: 2018-10-31
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy 
```

But please look at the Timeline tab, that's what cracked the whole thing open for me and allowed me to see it was an issue with SSL.

**Comment by gschier** [comment]
@GrayedFox the Linux builds _should_ be using a bundled version of OpenSSL but it seems like a few people are having issues around SSL so maybe the linking is not being honored. If you can post the curl version that your Insomnia installation is using (2nd line in Timeline tab), that would be great.

**Comment by GrayedFox** [comment]
Yes here you go (note that I changed my local stack to be http instead of https to get around this, not sure if that info is pertinent)

```
...
* Using libcurl/7.61.1 OpenSSL/1.1.0h zlib/1.2.11 nghttp2/1.29.0
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
...
```
