### ISSUE TITLE
[Feature Request] Display full request path when selecting a request for a `Response` tag

### ISSUE THREAD

**Issue by TeeSeal** [getinsomnia/insomnia#1286]
It's really nice that Insomnia can grab parameters from other responses in order to build requests, it saves me a lot of copy-pasting. I also like to keep my stuff neatly organized so I use a lot of folder nesting with Insomnia (which kind of backfired).

Currently, in the window where you get to configure a `Response` tag, you can select the request you want to grab the response from, in the list you can see the request name and the name of the folder it is in (if any).
```
[Auth] GET Authorize URL
```

However, when you have a lot of folder nesting, and the structure of the upper level folders is similar, it becomes really hard to identify the requests you're looking for. For example:

```
cool_apis
- API_1
- - Auth
- - - GET Authorize URL
- API_2
- - Auth
- - - GET Authorize URL
```

For the structure shown above you will see the following in the select list:
```
[Auth] GET Authorize URL
[Auth] GET Authorize URL
```
without being able to tell which request comes from `API_1` and which comes from `API_2`.
It would be nice to have them look like:
```
[API_1][Auth] GET Authorize URL
[API_2][Auth] GET Authorize URL
```
Perhaps make the the displayed nesting level configurable somehow?
As in for `2` it will be `[API_1][Auth]`, for 3 `[cool_apis][API_1][Auth]` etc.

**Comment by gschier** [comment]
That's a good idea 💡 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rickychandra** [comment]
Hi, I would like to work on this :smile:.

**Comment by TeeSeal** [comment]
@rickychandra Hey thanks for taking this on. I took a look at your PR and the issue seems to be a lot simpler to solve than I thought, haha. Guess I was just scared of diving yet into another codebase.

**Comment by rickychandra** [comment]
Hi @TeeSeal, I think this one is quite simple too lol. I am new to contributing to Insomnia, but I find the codebase is pretty easy to follow though.
