### ISSUE TITLE
[Feature Request] Save Samples/Collection of body requests so you can test different use cases

### ISSUE THREAD

**Issue by lapswr** [getinsomnia/insomnia#1287]
- Insomnia Version: 6.2.3
- Operating System: Windows 10

## Details

It would be helpful if there was a way to save different request bodies for testing different use cases.

![image](https://user-images.githubusercontent.com/2635037/49296884-50fdd000-f4b1-11e8-868b-28e1699e9d04.png)

**Comment by gschier** [comment]
This has been asked a few times before. Supporting multiple bodies would lead to also supporting multiple headers, query, etc. The recommended way to handle this is to make multiple requests

**Comment by Fyb3roptik** [comment]
In my use case I wouldnt need different headers or anything. I simply want to have a way to have different body templates for different situations.

**Comment by tommyc38** [comment]
@gschier, I think this is a valid feature request.  My use case involves an API for media processing with editing support.  The request bodies are large and under development which means they are changing quite a bit. Moreover, I don't want to have to duplicate the request body dozens of times in insomnia for incremental changes and then have to change each request when the api changes.  Below is how I envision this solution would work in insomnia:

1. create request body template and save it
2. create a request as usual in insomonia with an option for "JSON From Template" which opens a dialog
3. select the template and insomnia creates the request as usual with an empty json object
4. the cursor would immediately make you select which key in the template you would like to change (for that request)
5. select the json key and insomnia inserts it like an environment variable.  (add other keys for additional changes)
6. add the changes you want to make as the value, set your headers, etc.
7. make request (insomnia replaces the changes you make in the template body for the request)

Pro's
- only a few places would need to be updated when apis change.
- It would be much more clear which part of the request body the request is updating/testing
- less chance for errors in request bodies
- quicker development

Below is a link to AWS's media convert job request api as an example.  You can see it's huge (and is similar to mine).  Imagine trying to test all of these variations under insomnia without templates? 

https://docs.aws.amazon.com/mediaconvert/latest/apireference/jobs-id.html#jobs-id-schemas

**Comment by abdellahi-brahim** [comment]
was this addressed?
