### ISSUE TITLE
Windows 10 64Bit installation error

### ISSUE THREAD

**Issue by oliversarfas** [getinsomnia/insomnia#1290]
- Insomnia Version: Attempting installation 6.2.3
- Operating System: Windows 10

## Details

Attempting to install, get the following issue;

![image](https://user-images.githubusercontent.com/12659572/49373356-b9d58a00-f6f5-11e8-8a42-f11c2e703f45.png)

I have flushed out my AppData\Local directory, and run the installer as an admin to see if that helps - no avail.

_Reproduction steps_
- Be on Windows 10
- Download latest installer from insomnia.rest
- Run installer

**Comment by gschier** [comment]
The data would be in appdata/roaming I think

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by oliversarfas** [comment]
@gschier thanks for coming back to me.

I cleared out appdata/roaming and it works now.

I did however lose all my environments files which isn't ideal

**Comment by matoval** [comment]
Thank you I couldn't open the app and I cleared the appdata/roaming/insomnia and now its working.
