### ISSUE TITLE
[Feature Request] Replace characters in environment variable

### ISSUE THREAD

**Issue by Limero** [getinsomnia/insomnia#1291]
I have a environment variable that is set automatically with Requests Chaining by calling `/auth`.

`/auth` returns a string within quotes that is assigned to the variable and then used in other requests by setting their header to that. The problem is that the server expects the auth key to be a string without quotes, so it doesn't work.

**Tldr;** A way to replace characters when using an environment variable would be very useful. Like replacing `"` with an empty space.

**Comment by gschier** [comment]
Not the most elegant solution but if you put your Response tag (for chaining) in an environment, you can create another environment variable to modify it. Here's an example:

```json
{
  "foo": "bar",
  "foo_replaced": "{{ foo | replace('bar', 'baz') }}"
}
```

Note, Insomnia just uses [Nunjucks](https://mozilla.github.io/nunjucks/templating.html) so there's also a lot more you can do.

**Comment by ajaydwarkani** [comment]
@gschier 

> Not the most elegant solution but if you put your Response tag (for chaining) in an environment, you can create another environment variable to modify it. Here's an example:
> 
> ```json
> {
>   "foo": "bar",
>   "foo_replaced": "{{ foo | replace('bar', 'baz') }}"
> }
> ```
> 
> Note, Insomnia just uses [Nunjucks](https://mozilla.github.io/nunjucks/templating.html) so there's also a lot more you can do.

I tried the replace function but it's doing nothing. Here is what I tried

```json
{
  "obj": {
     "id": "someId@dotcom",
     "name": "some name"
  },
  "secondVar": "secondVarValue",
  "id": "{% JSONpath _.obj, id %}",  // Extract "id" from "Obj"
  "finalId": "{{ id | replace('@dotcom', '') }}_{{ secondVar }}"
}
```

But this works
```json
{
   "id": "someId@dotcom",
  "newId": "{{ Id | replace('@dotcom', '') }}"
}
```

Am I doing something wrong here?

**Comment by ajaydwarkani** [comment]
I figured. You cannot use the `replace` function when concatenating with another variable. Instead, you should first concatenate the variables and then apply the `replace` function on the new variable

Here is the fix, might help others

```json
{
  "obj": {
     "id": "someId@dotcom",
     "name": "some name"
  },
  "secondVar": "secondVarValue",
  "id": "{% JSONpath _.obj, id %}",  // Extract "id" from "Obj"
  "idTmp": "{{ id }}_{{ secondVar }}",
  "finalId": "{{ idTemp | replace('@dotcom', '') }}"
}
```

**Comment by ajaydwarkani** [comment]
I figured. You cannot use the `replace` function when concatenating with another variable. Instead, you should first concatenate the variables and then apply the `replace` function on the new variable

Here is the fix, might help others

```json
{
  "obj": {
     "id": "someId@dotcom",
     "name": "some name"
  },
  "secondVar": "secondVarValue",
  "id": "{% JSONpath _.obj, id %}",  // Extract "id" from "Obj"
  "idTmp": "{{ id }}_{{ anotherVar }}",
  "finalId": "{{ idTemp | replace('@dotcom', '') }}"
}
```
