### ISSUE TITLE
[Freature Request] Pretty GraphQL

### ISSUE THREAD

**Issue by umanking** [getinsomnia/insomnia#1296]
- Insomnia Version: ___Version 6.2.0 (6.2.0.2505)
- Operating System: ___Mac Mojave 10.14.1 (18B75)

## Details

I want you to develop Pretty GraphQL Feature more deatils
right now, all of the data in parameters is that like this

![screen shot 2018-12-10 at 3 21 50 pm](https://user-images.githubusercontent.com/28615416/49714190-5916f600-fc8f-11e8-8de7-a8e50733ec0a.png)

but I want to sort like that
![screen shot 2018-12-10 at 3 22 33 pm](https://user-images.githubusercontent.com/28615416/49714212-6f24b680-fc8f-11e8-8fbf-3e521f641e8e.png)

Thanks !

**Comment by gschier** [comment]
Hi @umanking, 

Insomnia uses the `graphql` package's `print()` function to do prettifying currently. Perhaps you could take a look to see if it's supported? If it is, I'd be happy to discuss changing the behavior in Insomnia.
