### ISSUE TITLE
[Feature Request] Plugin lifecycle

### ISSUE THREAD

**Issue by syl20lego** [getinsomnia/insomnia#1297]
- Insomnia Version: 6.2.3
- Operating System: MacOs

## Details
I'm writing a plugin where I would need to do some "expensive" logic and would like to only do it when the form is changed. Currently the plugin run is call multiples times during the execution but there is no way to know why and what was the intention. I tried to manage the state internally but I was not successful. 

Maybe I'm missing something and this is already possible but so far here what I noticed.
For example the plugin is being called:
- When Plugins manager load the plugin
- When Manage Environments is being loaded: here the plugin is called 3 times
- When opening the Edit Tag: here the plugin is called 4 times
- When changing a value: call twice, once with the previous and once with new values, a single call with previous values in the context would be useful)
- When press refresh: call twice, once with the previous and once with new values, a single call with previous values in the context would be useful)
- When press Done:  call twice, once with the previous and once with new values, a single call with previous values in the context would be useful)
- Again when manage Environment is refresh (after modal close): Same called 3 times

I most cases, I think we should have the plugin called only once per "action".

The context should include an Enum with the lifecycle value and could looks something like:
- Initialize
- Evaluate
- Change (context also contains previous values)

The mapping would be something like:
- When Plugins manager: Initialize
- When Manage Environments: Evaluate
- When opening the Edit Tag: : Evaluate
- When changing a value: Change
- When press refresh: Evaluate or could be change?
- When press Done:  Evaluate
- Again when manage Environment is refresh (after modal close): Evaluate

Of course feel free to use a totally different lifecycle logic but providing one would be very useful for plugin developers.

**Comment by syl20lego** [comment]
Thanks for the feedback, I got it working following your suggestion. 
I use the form data (args) as the key instead of the id, so I just concatenate the the args. Since in my case I'm just interested when the form data changed.
BTW the  context.meta.requestId always return the last request._id so the quick return never works
```
  if (!id) {
        return '';
      }
```

**Comment by gschier** [comment]
Oh nice! Glad you got something working 👍😀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by syl20lego** [comment]
thanks, I published it to npm if you want to take a look
https://www.npmjs.com/package/insomnia-plugin-aws-cognito-token

**Comment by gschier** [comment]
Ohhh, I see. When you said "form" you meant the tag editor, no the request body form data.

A couple things to note:

1. You can add `validate: v => (v ? '' : 'Required')` to each arg to get better feedback if a user does not enter one (although still good to throw exceptions during render like you're doing)
2. `JSON.stringify()` does not guarantee key order so you may want to change it to `[ UserPoolId, ClientId, Username, Password ].join('::')` or something similar.

Other than those extremely minor things, it looks awesome! Mind if I send a tweet about it?
