### ISSUE TITLE
[Bug] Sync stuck at 97.9%, Sync Pending

### ISSUE THREAD

**Issue by scottrobertson** [getinsomnia/insomnia#1298]
- Insomnia Version: 6.2.3 (6.2.3.2532)
- Operating System: MacOS 10.14.2 Beta (18C52a)

## Details

This is going to be a rather useless ticket, as i have no idea how to reproduce or replicate it, but my sync is stuck at 97.9%, and it shows "Sync Pending". Tried searching for these issues, but i see nothing. Tried rebooting etc.

Edit: Just confirmed, it is actually syncing, so perhaps it's just a local state issue?

Let me know if there is anything i can do to help debug.

**Comment by gschier** [comment]
It could be a variety of things (hard to tell) but I haven't heard of this issue happening before. I suggest logging out and back in, which will clear the local sync cache. Can you see if that helps?
