### ISSUE TITLE
[Feature Request] Support CRT and Key files for Mac

### ISSUE THREAD

**Issue by emjburns** [getinsomnia/insomnia#1305]
I am a user of the Netflix team subscription for Insomina (super happy with it!). We use certificates internally and the easiest path is to use CRT and Key files. In the [support article]( https://support.insomnia.rest/article/51-client-certificates) it mentions that this format is not available for mac. I'd love for this feature to be available! It would make life easier.

**Comment by gschier** [comment]
Hi @emjburns! I think this may actually be supported now, if you're on macOS High Sierra or later. Let me explain.

The certificate handling in Insomnia is delegated to the `libcurl` library. On the Mac build, Insomnia uses the version of `libcurl` installed on your system. Since macOS High Sierra, Apple now includes a version of `libcurl` that uses `LibreSSL` instead of `Secure Transport` which, I think no longer supports p12 certificates and only CRT/Key pairs. 

Can you let me know what OS you're on and any error messages you see in the Timeline tab related to certificate handling when trying CRT/Key files?

**Comment by emjburns** [comment]
Hi @gschier, thanks for the quick reply! I'm on macOS High Sierra (10.12.6). When I try to use the CRT/Key, I see:

```* Using libcurl/7.54.0 SecureTransport zlib/1.2.8
* Enable automatic URL encoding
* Disable SSL validation
* Enable cookie sending with jar of 17 cookies
* Adding SSL PEM certificate
* Adding SSL KEY certificate
* Hostname in DNS cache was stale, zapped
*   Trying <IP>...
* TCP_NODELAY set
* Connected to <dnsname> (<IP>) port 7004 (#13)
* WARNING: SSL: CURLOPT_SSLKEY is ignored by Secure Transport. The private key must be in the Keychain.
* WARNING: SSL: The Security framework only supports loading identities that are in PKCS#12 format.
* SSL: Can't load the certificate "</My/CRT>" and its private key: OSStatus -25299
* Closing connection 13```

This makes me think that I should upgrade my OS?

**Comment by gschier** [comment]
Hmm, what does Insomnia say your Curl version is? It should say at the start of the Timeline tab.

![image](https://user-images.githubusercontent.com/587576/50018107-2ffeaa00-ff9c-11e8-8699-54b3f58020a1.png)

I'll leave the decision of upgrading your OS to you but I'm pretty sure you should already have the updated Curl version on High Sierra.

**Comment by emjburns** [comment]
Oh darn thought I pasted that line too:

```* Using libcurl/7.54.0 SecureTransport zlib/1.2.8
```

**Comment by emjburns** [comment]
Ha pasting the * accidently made that line not show up.

**Comment by gschier** [comment]
Lol 😄 

You mentioned that you were on macOS High Sierra 10.12 but High Sierra is 10.13 (10.12 is Sierra). And, now 10.14 Mohave is out already! 

I suspect upgrading your OS would work but I can't take responsibility for recommending that you do it (stuff might break for you).

**Comment by emjburns** [comment]
Was due for an upgrade anyways, updated my OS and also Insomnia and now it is working! Oops you're right about Sierra vs High Sierra. Thank you so much for your help!!

**Comment by gschier** [comment]
Awesome! It looks like it's time to update the docs (and perhaps the certificate dialog).
