### ISSUE TITLE
[Question] Default user-agent, Inconsistancy between request & "Copy as Curl"

### ISSUE THREAD

**Issue by PierrickP** [getinsomnia/insomnia#1309]
- Insomnia Version: 6.3.1

## Details

With the most simple query (GET with just an url), why a default `user-agent` is setted ? https://webhook.site/#/1531597c-5ce7-4fd6-a6eb-f202978fc22f/1a4ef060-403e-414f-98be-cf0a9775849d/1

If we use the functionnality "Copy as Curl", the default user-agent is not setted. 

```
curl --request GET \
  --url https://webhook.site/1531597c-5ce7-4fd6-a6eb-f202978fc22f
```

This could result in a different reply between insomia and curl.

I would prefer to not have user-agent per default but if it's "mandatory", this user-agent should be exported on curl request.

Thanks

**Comment by AL1L** [comment]
I get where you're coming from because none of the HTTP Headers are required in a Request in the HTTP specification.

**Comment by gschier** [comment]
Yep, the default headers should be updated to match the ones for regular requests 👍

**Comment by PierrickP** [comment]
So the default parameter for `User-agent` should be "no user-agent" ?

**Comment by PierrickP** [comment]
ok i agree it's often necessary.
To be consistency, in curl export, the default user-agent should be set

**Comment by rsharifnasab** [comment]
any changes on this issue?
