### ISSUE TITLE
[Feature Request] Proof Key for Code Exchange (PKCE) Support

### ISSUE THREAD

**Issue by mikeahmarani** [getinsomnia/insomnia#1310]
See spec here: https://oauth.net/2/pkce/

Would be a nice feature to support. A very secure OAuth 2 flow for 3rd party mobile use of an API.

**Comment by 0xdevalias** [comment]
This issue isn't stale, and this is still a very much desired flow. Postman is finally getting around to implementing it apparently, so if others end up here with a need, check out https://github.com/postmanlabs/postman-app-support/issues/3825

**Edit:** seems this is a dupe of https://github.com/Kong/insomnia/issues/1653

**Comment by Kirschbaumke** [comment]
This is still a valid feature we would like to have. We are developing and would like to use the PKCE in Insomnia.
This is currently **not** available, but it is in Postman.
