### ISSUE TITLE
Duplicate requests being sent

### ISSUE THREAD

**Issue by jdalrymple** [getinsomnia/insomnia#1312]
- Insomnia Version: 6.3
- Operating System: windows 10

## Details

When sending a request to a service running locally, insomnia seems to be sending the request twice. I've tried with many different local services and obtain the same problem.

Note: I am using the Send button not a shortcut

**Comment by jdalrymple** [comment]
Ill investigate to see if its happens with externally hosted services, but i doubt their will be a difference

**Comment by jdalrymple** [comment]
Fixed by updating to 6.3.1

**Comment by gschier** [comment]
Yep, this is a duplicate of #1307
