### ISSUE TITLE
[Question] Updating HTTP Snippets

### ISSUE THREAD

**Issue by peoplenarthax** [getinsomnia/insomnia#1313]
## Details

There are some [PRs in httpsnippets](https://github.com/Kong/httpsnippet/pulls) (package that we rely on when generating code) that would improve insomnia (like Fetch support which I opened myself) or improve cases but the project seems to have stopped activity (yes, there has been package updates but no movements in the code or updates of the current snippets.

Is insomnia align with just getting updates from [httpsnippets](https://github.com/Kong/httpsnippet)? Is it wanted to maintain its own fork instead?

**Comment by gschier** [comment]
Ah yes, this should be done, thanks for the reminder!

**Comment by peoplenarthax** [comment]
So, getinsomnia will develop over the fork of httpsnippets and any modification to code generators should be PR here? I have one PR that I can try to merge then

**Comment by gschier** [comment]
Oh sorry, I thought you meant the PRs had been merged into `httpsnippet` but now I realize they haven't. For now, if you want to manually port the PRs to the `httpsnippet` package in the Insomnia project I'd be happy to merge them in https://github.com/getinsomnia/insomnia/tree/develop/packages/insomnia-httpsnippet

**Comment by peoplenarthax** [comment]
Just opened the PR to close this :D https://github.com/getinsomnia/insomnia/pull/1343
