### ISSUE TITLE
[Bug] Submission of User-Agent in the Header invalidates authentication for AWS IAM v1

### ISSUE THREAD

**Issue by commodon** [getinsomnia/insomnia#1315]
[Bug] – Attempting to authenticate with AWS IAM v1 results with 401 Unauthorized to be received

[Feature Request] – Please remove (or provide ability to users to remove) the "User-Agent" string from the header

- Insomnia Version: 6.3.2
- Shell 3.0.4
- Node 10.2.0
- V8 6.6346.32
- Architecture x64
- Operating System: Windows 7 Pro 64bit

## Details

When attempting to authenticate with API to AWS, there are Three Steps to be performed:

1. Create a Canonical Request, see https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html
2. Create a String to Sign, see http://docs.aws.amazon.com/general/latest/gr/sigv4-create-string-to-sign.html
3. Create a Signature, see http://docs.aws.amazon.com/general/latest/gr/sigv4-calculate-signature.html

In regards to Step One, the following examples show how to construct the canonical form of a request to IAM. The original request might look like this as it is sent from the client to AWS, except that this example does not include the signing information yet. Additionally note for HTTP/1.1 requests, you must include the host header at a minimum. Standard headers like content-type are optional.

Example request:

```
GET https://iam.amazonaws.com/?Action=ListUsers&Version=2010-05-08 HTTP/1.1
Host: iam.amazonaws.com
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20150830T123600Z

```
In my attempt of using Insomina after configuring the access_key, secret_key, region, service for AWS, as well as adding "Accept: application/vnd.api+json" to the Header as it is required for my API, I consistently receive 401 Unauthorized with every GET request.

NOTE: I know my base_url, access_key and secret_keys are correct as I am able to authenticate using tools different than Insomnia.

Here is the *sanitized* output from the Timeline of one of my attempt(s):

```
* Preparing request to https://api.example.net/v1/sensors
* Using libcurl/7.57.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.7.0_DEV
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Disable cookie sending due to user setting
* Connection 17 seems to be dead!
* Closing connection 17
* TLSv1.2 (OUT), TLS alert, Client hello (1):
*   Trying 52.44.142.215...
* TCP_NODELAY set
* Connected to api.example.net (52.44.142.215) port 443 (#19)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\Users\XXXXXXXX\AppData\Local\Temp\insomnia_6.3.2\2017-09-20.pem
*   CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; CN=*.example.net
*  start date: Oct  6 18:00:07 2018 GMT
*  expire date: Dec  5 16:49:19 2019 GMT
*  subjectAltName: host "api.example.net" matched cert's "*.example.net"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.

> GET /v1/sensors HTTP/1.1
> Host: api.example.net
> User-Agent: insomnia/6.3.2
> Accept: application/vnd.api+json
> X-Amz-Date: 20181221T153418Z
> Authorization: AWS4-HMAC-SHA256 Credential=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/20181221/us-east-1/localhost/aws4_request, SignedHeaders=host;x-amz-date, Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

< HTTP/1.1 401 Unauthorized
< Server: nginx/1.10.2
< Date: Fri, 21 Dec 2018 15:34:19 GMT
< Content-Type: text/plain
< Content-Length: 0
< Connection: keep-alive
< WWW-Authenticate: AWS4-HMAC-SHA256
< Cache-Control: no-cache
< X-Request-Id: 65027e13-17e8-4614-9ea7-988ad7520bc1
< X-Runtime: 0.003833

* Connection #19 to host api.example.net left intact
```

In reviewing the HEADER reflected above, it appears to reflect the insertion of a "User-Agent" string, which is outside of what should be required by AWS IAM,

I suspect if the User-Agent string can be removed from the header, the ability of providing a valid signature for the request will lead to successful authentication

**Comment by commodon** [comment]
This issue remains unresolved and as such prevents the success of being able to AWS IAM

**Comment by gschier** [comment]
To clarify, are you generating the signature manually or using Insomnia's built-in AWS auth helper?

**Comment by commodon** [comment]
using the built-in AWS Auth helper
