### ISSUE TITLE
[Bug] White screen when starting

### ISSUE THREAD

**Issue by D3faIt** [getinsomnia/insomnia#1316]
- Insomnia Version: 6.3.2
- Operating System: Windows 8.1 64-bit

## Details

Hi.

I just installed this application today because Postman wouldn't start (white screen).
This application seems to have the same issue?
It starts up and only displays a white screen

![2018-12-21 20_26_09-cfish - c__users_chiya _webserver_fisk - _search_index php - phpstorm 2017](https://user-images.githubusercontent.com/8147434/50359940-bef06100-055e-11e9-9b15-484637667506.png)

### Note

- I have 4 monitors (one 165hz, three 60hz)
- I have a Hashtag in my username (Chiya#)

Are there any fix to this?

**Comment by commodon** [comment]
I tried both versions (x86 and x64) of Postmand and had the same issue. It appears to be video related, but . I couldn't figure out the cause, so I switched to Insomnia and I've not had an issue. I am using Insomnia x64 on Windows 7 (64bit). In researching Postman, it appears this is a frequent issue and others have reported it as being a GPU related bug

**Comment by D3faIt** [comment]
@commodon This is my Hardware: 

- CPU: AMD Ryzen 5 1600
- GPU: NVIDIA GeForce GTX 1080 Ti
- Motherboard: X370 GAMING PLUS (MS-7A33)
- RAM: 4x Corsair DDR4 8 GB (32 GB total)

I will try updating the Graphic card driver and see if it helps.
Are you sure the Hashtag in the username isn't a cause of this?
In python this would comment out the paths and username for example

**Comment by D3faIt** [comment]
Updating GPU drivers didn't help.

Both Postman and Insomnia shows a white screen.

I really hope we can find a solution for the issue.

**Comment by AL1L** [comment]
It doesn't have something to do with the GPU, check out this page maybe it helps https://discuss.atom.io/t/white-screen-on-startup/42544/12 (ignore the Atom specific stuff)

**Comment by D3faIt** [comment]
> It doesn't have something to do with the GPU, check out this page maybe it helps https://discuss.atom.io/t/white-screen-on-startup/42544/12 (ignore the Atom specific stuff)

Hmm. This did not work.

I tried Windows 7, Windows XP, run as Administrator and Scaling on high DPI.

Another thing to note, is that I have a 165hz display (in the middle), the rest 3 is 60hz (4 monitors total)

**Comment by aindong** [comment]
Did anyone solved this issue already? I also did experienced this problem

**Comment by warmwaffles** [comment]
I am getting this problem as well

ArchLinux
BSPWM

**Comment by D3faIt** [comment]
@warmwaffles It's working for me on Arch Linux (i3-gaps).
Try in another Desktop environment maybe?

**Comment by warmwaffles** [comment]
> Try in another Desktop environment maybe?

I can attempt in gnome I think. But this worked about a month ago. It only goes all white when I pop the preferences window open. May try nuke the local cache and see if that clears the issue

**Comment by pwrigshi** [comment]
have you tried `--disable-gpu` flag? it helped me.

**Comment by AL1L** [comment]
> have you tried `--disable-gpu` flag? it helped me.

Yes, this was tried

https://github.com/getinsomnia/insomnia/issues/1316#issuecomment-454241363

**Comment by gschier** [comment]
There might be a visible error in View > Toggle DevTools > Console. There also might be a visible error if you launch it from the command line.

**Comment by gschier** [comment]
Also, I'm not sure if this will make a difference, but there is another installation method for Insomnia from Portapps that might be worth a try: https://portapps.io/app/insomnia-portable/

**Comment by D3faIt** [comment]
I have now completely switched over to linux, and it's working.

If anyone else has this problem, it would be nice to figure out the solution for this

**Comment by kevin-hv** [comment]
I am getting a white screen on start with the latest MacOS Catalina

<img width="655" alt="Screenshot 2019-12-12 at 17 40 00" src="https://user-images.githubusercontent.com/44970281/70731208-9bda3680-1d06-11ea-9501-618cf9ce6a18.png">

**Comment by gschier** [comment]
@kevin-hv can you please submit a new issue with the full details of your problem?

**Comment by kevin-hv** [comment]
@gschier Sure, on it
