### ISSUE TITLE
[Feature Request] - Disable autocomplete when typing

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#1320]
- Insomnia Version: 6.3.2
- Operating System: Arch Linux

## Details

Hi there!

Insomnia is about testing APIs, right? In order to test the APIs we may change some variables in the URL, change some values on the json body, and so on.

The problem I found since I started using Insomnia is the autocomplete getting in the way more often than helping.

For example, If I finished some API test on the `user/1/teams` endpoint, and want to test user 5 for example, I would go to the URL and change 1 for 5, then hit enter to send the request. The problem is, when I type 5, Insomnia suggests this:

![image](https://user-images.githubusercontent.com/12160864/50516336-6e629180-0a91-11e9-8df0-4d3e9e5e3f8a.png)

If I hit enter to test the endpoint, I'll actually get the autocomplete suggestion:

![image](https://user-images.githubusercontent.com/12160864/50516372-a4077a80-0a91-11e9-9b00-892eeb5115a7.png)

So now I have to erase that, type 5 again, make sure I don't hit the autocomplete suggestion, and then test the API. The 5 is just an example, there are many others autocomplete suggestions out there.

I'm not asking to disable the autocomplete, but instead fire it just when I want, by hitting Ctrl+Space for example. So an option to disable autocomplete only when typing would be nice :smiley:

**Comment by rickychandra** [comment]
Duplicate of #1032.

**Comment by rafaelrenanpacheco** [comment]
Indeed, thanks!
