### ISSUE TITLE
[Bug] Time is not synced

### ISSUE THREAD

**Issue by nicktunac** [getinsomnia/insomnia#1322]
- Insomnia Version: 
![image](https://user-images.githubusercontent.com/7882308/50629688-96159600-0f78-11e9-9254-511f9baf5fb1.png)
- Operating System: Windows 10

## Details

The time is not synced with the local machine.
In timeline tab, the time is not showing the accurate time.
![image](https://user-images.githubusercontent.com/7882308/50629771-ed1b6b00-0f78-11e9-8b68-ed3fb5a40d29.png)

**Comment by AL1L** [comment]
The time there is in the GMT/UTC timezone, take a look at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date

**Comment by gschier** [comment]
Yes, this time is a header that is sent back with the response from the server. Insomnia has no control over what the value is.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
