### ISSUE TITLE
Add JSONpath context to "Generate code" 

### ISSUE THREAD

**Issue by jermon** [getinsomnia/insomnia#1324]
- Insomnia Version: ___ 6.3.2
- Operating System: ___ windows 7

## Details

Add the context in the JSONpath field to generated code.

**Comment by gschier** [comment]
Can you explain in more detail what you mean by this? I don't understand

**Comment by jermon** [comment]
Yes.
If the user has a Json path selection in insomnia.
A coldeline should be constructed in the generated code to represent this.

I.e $.store.book[0].author shoud generate :
```javascript
var author = JsonPath.read(document, "$.store.book[0].author")
```

**Comment by gschier** [comment]
I'm not sure this is a feasible request. Insomnia supports code generation for many different languages and frameworks, which may or may not have working or consistent JSONPath (and XPath for XML) libraries.
