### ISSUE TITLE
[Feature] Same query fields for requests folder

### ISSUE THREAD

**Issue by 4n70w4** [getinsomnia/insomnia#1326]
I need add 2-4 same fields to group (folder) of request. In current i should manually copy-paste fiield by field in each request. It is tiresome and not user-friendly. And can also forget about some fields.

![image](https://user-images.githubusercontent.com/38257723/50720219-cca6fa00-10b9-11e9-871d-6c9b5e5094aa.png)

I want that it was possible to set fields once for a group (folder) or an easy way to copy them into other requests.

**Comment by 4n70w4** [comment]
up?

**Comment by 4n70w4** [comment]
Still relevant, for example, to automatically add a get-parameter or a header with a acces-token only 1 time, but not in every request.

**Comment by 4n70w4** [comment]
up

**Comment by gschier** [comment]
Sounds like a good use for this! https://www.npmjs.com/package/insomnia-plugin-defaults
