### ISSUE TITLE
[Feature] Search request in edit tag window

### ISSUE THREAD

**Issue by 4n70w4** [getinsomnia/insomnia#1327]
Hi! I work with 100+ request and very hard search necessary request for use results of one request in another request.

![image](https://user-images.githubusercontent.com/38257723/50720932-f5ce8700-10c7-11e9-897f-7a499387765a.png)

I suggest to make search by request list

**Comment by gschier** [comment]
I agree, this would be awesome!

**Comment by 4n70w4** [comment]
Still relevant.
