### ISSUE TITLE
[Feature Request] Comment out multiple lines with shortcut

### ISSUE THREAD

**Issue by D3faIt** [getinsomnia/insomnia#1330]
- Insomnia Version: 6.3.2
- Operating System: Arch Linux 4.18.1

## Details

I know PHPStorm and sublime text has this function. Simply mark all the lines you want to comment out, and press `CTRL+/`

Here is an example:
### Before

![2019-01-07-053035_1440x900_scrot](https://user-images.githubusercontent.com/8147434/50749253-056fdc00-123e-11e9-8b31-9c3881516406.png)

### After

![2019-01-07-053247_1440x900_scrot](https://user-images.githubusercontent.com/8147434/50749261-0f91da80-123e-11e9-8025-56b62c4560b8.png)

This function would really speed up my work.

**Comment by AL1L** [comment]
JSON doesn't have comments, Would you want it to just skip the lines when sending the request like how you can toggle headers and query parameters?

**Comment by D3faIt** [comment]
> JSON doesn't have comments, Would you want it to just skip the lines when sending the request like how you can toggle headers and query parameters?

Yes, JSON doesn't have comments, but this query in the screenshot DOES work.
It might be handled by the program, and not sent

**Comment by gschier** [comment]
No, Insomnia does not modify the contents of the response body when sending. The comments will be sent if they are in there. Note, you can use the comment syntax for the templating system if you want comments that aren't sent: `{# this is a comment #}`
