### ISSUE TITLE
Issues with localhost

### ISSUE THREAD

**Issue by mattdodge** [getinsomnia/insomnia#1331]
- Insomnia Version: 6.3.2
- Operating System: Mac OS X 10.13.6

## Details

After a recent Insomnia update (it happened in the background so I'm not exactly sure what my previous version was) calls to a server on `localhost` just return "Error: Couldn't connect to server" now. Replacing `localhost` with `127.0.0.1` works, and using `localhost` in a corresponding `curl` command also works.

I realize there aren't a lot of details with this issue, but hoping it can strike a chord. Is there any information I can provide or testing I can do?

**Comment by gschier** [comment]
Hmm, I'm not sure what could have caused this. On Mac, Insomnia uses the built-in OS `libcurl` library so it should work the same both in Insomnia and with Curl from the command line.

**Comment by mattdodge** [comment]
I just went through to try and come up with some better steps to reproduce and now it's not happening anymore. So obviously that's good news! I had restarted my computer since originally reporting, it is almost certainly something on my end it seems. Closing this issue, sorry for the false report!

I swear I'm not crazy...😮

**Comment by gschier** [comment]
Hehe, well I'm glad it's working now!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gschier** [comment]
That's strange. DNS lookup isn't really my area of expertise. I did some Googling but couldn't find much. It seems the order of `/etc/hosts` doesn't matter so maybe it's random for any given lookup.

As for the location of the cache, I'm not actually sure where it's stored or for how long (in-memory I think), but I can almost guarantee it doesn't share the same one as the `curl` command line utility.

**Comment by gschier** [comment]
If you want to try and dig into it that would be good but it seems to me like it's probably not an Insomnia issue. If your server is running on `0.0.0.0` (IPv4) and you have both IPv4 and IPv6 localhost entries in your hosts file, it makes sense that a DNS lookup could potentially return the IPv6 address and send the request there by mistake.

**Comment by mattdodge** [comment]
I actually had tried adding a `.local` endpoint in my `/etc/hosts` file. That was actually the "other issues with IPv4/IPv6 mixups recently" I mentioned earlier. What's weird is if I put an IPv4 entry in my `/etc/hosts` for `app.local`, say, then sometimes the DNS resolution will take ~5 seconds before returning the entry in `/etc/hosts`. For some reason (maybe at my router??) it's wanting to use IPv6 for DNS lookups. I really thought `/etc/hosts` was the first stop on any kind of hostname lookup though. I have no idea why this has all started recently but I'll see if I can get to the bottom of it.

**Comment by RakshithaCT** [comment]
Error: Couldn't connect to server

**Comment by Madzeedy** [comment]
@RakshithaCT Did you find anything regarding that error you stated up there?
