### ISSUE TITLE
[Feature Request] HATEOAS Support

### ISSUE THREAD

**Issue by matt-bates-hypr** [getinsomnia/insomnia#1332]
- Insomnia Version: 6.3.1
- Operating System: Windows 10

## Details

I am using Insomnia with a HATEOAS REST application which is great except that every time I click on a URL I am taken to a web browser rather than exploring the application within Insomnia. It would be really good if when a URL in a response was clicked a new request was made with the same headers (so that authentication works), and the response was displayed.

**Comment by wederer** [comment]
This is related to #662. You can not even copy an URL from the JSON response to quickly create a new request.

**Comment by FlorianFusseder** [comment]
Same use case for me! A new tab with the same Auth headers would be a cool feature!

**Comment by scottmmmm** [comment]
I closed the feature request that @rafaelrenanpacheco referenced above, since it duplicates this one.

I'd love to see some of the features discussed here added to Insomnia, so it's +1 from me.

**Comment by scottmmmm** [comment]
Oh no, just noticed this has been closed by the stale bot! :(
