### ISSUE TITLE
[Question] Save/read requests to/from file

### ISSUE THREAD

**Issue by barell** [getinsomnia/insomnia#1333]
- Insomnia Version: 6.2.3
- Operating System: Ubuntu 16.04

## Details

Question: is it possible to copy or save request to a file and restore it later, for example on another computer? 

Use case: I'm working on a request which has 30 post fields and if I switch to another computer, there is no way to copy the whole request and paste to another Insomnia client. I don't want to put all 30 post fields manually again. I was looking for a feature where you can save whole request to a file, transfer that file to another computer and load it back to Insomnia.

I know it is also possible to generate curl code but it would be even great if it's possible to generate Insomnia request from curl code too.

**Comment by barell** [comment]
Thanks for suggestion. I didn't know there is workspace export/import.

I was looking for something like per request export, when you right click on single request and have option to export and then import that single request somewhere else.

**Comment by gschier** [comment]
You could use Copy as Curl to get something similar, although you will lose any Insomnia-specific info like variables. You can past a Curl command into the URL bar to import it.

**Comment by barell** [comment]
> You could use Copy as Curl to get something similar, although you will lose any Insomnia-specific info like variables. You can past a Curl command into the URL bar to import it.

I just tried it and it's all I needed! I just realised there is even a tip message when creating a new request.

I'm going to close this issue.

**Comment by gschier** [comment]
Woo! 😊
