### ISSUE TITLE
[feature] Giving first-class (display) support for `X-HTTP-Method-Override`

### ISSUE THREAD

**Issue by wonderbeyond** [getinsomnia/insomnia#1334]
I am using POST method while I mean GET, as implied through `X-HTTP-Method-Override`.
Because I want a GET request with json payload as complex query statements, like below:

![image](https://user-images.githubusercontent.com/228361/50954196-ae456200-14f0-11e9-9793-394d7d7d3430.png)

Can we have a first-class display support for this behaviour? maybe like:

![image](https://user-images.githubusercontent.com/228361/50956641-2a42a880-14f7-11e9-81ec-6e5bdc2e87a6.png)

For about `X-HTTP-Method-Override`, see https://developer.mailchimp.com/documentation/mailchimp/guides/an-introduction-to-rest/
or http://flask.pocoo.org/docs/1.0/patterns/methodoverrides/ or http://www.gorillatoolkit.org/pkg/handlers#HTTPMethodOverrideHandler

**Comment by gschier** [comment]
Hmm, this is an interesting one. I feel like that header isn't very common but I don't think it'd be too difficult to implement such a feature. I'm open to a community contribution if it's simple to implement 👍
