### ISSUE TITLE
[Bug] Team Workspace Sync not working properly

### ISSUE THREAD

**Issue by Fyb3roptik** [getinsomnia/insomnia#1335]
- Insomnia Version: 6.3.2.2588
- Operating System: Macos 10.14.2

## Details

I created a new Workspace and am trying to share it with my team. I shared it and typed in my password, but the team cannot see it on their end. It is not pulling down to their client

**Comment by gschier** [comment]
Replied via support email

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Fyb3roptik** [comment]
For someone else's edification, I had to go into Preferences > Account and logout, then login and then sync again. Did this on both clients and that fixed it

**Comment by DASPRiD** [comment]
We just experienced the same issue with Insomnia 7.0.6. A team member created two new request and only one was synced over.

**Comment by jeremiahsmall** [comment]
FWIW, we worked around it in this case by duplicating the request that wasn't sync'd and then deleting the original.
