### ISSUE TITLE
[Bug] More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss.

### ISSUE THREAD

**Issue by devshark** [getinsomnia/insomnia#1337]
- Insomnia Version: 6.3.2
- Operating System: Windows 10 x64

## Details
I cannot open the Insomnia app. It always shows the attached screenshot and then closes. Before this happened, I closed the app properly and then restarted my PC. I don't want to uninstall & reinstall the app as it might delete all my workspace.

![2019-01-16 10_03_32-window](https://user-images.githubusercontent.com/769245/51222338-48d1f500-1978-11e9-902e-5b874779c156.png)

**Comment by gschier** [comment]
Please see the following issue 
https://github.com/getinsomnia/insomnia/issues/1104
