### ISSUE TITLE
[Bug] Cookies with an expiry of epoch 0 are still being sent

### ISSUE THREAD

**Issue by comburo** [getinsomnia/insomnia#1340]
- Insomnia Version: 6.3.2
- Operating System: Windows 10 Pro

## Details
I'm testing an API where I login, get some profile data about my account and then logout. After the logout subsequent login requests fail with a Varnish error: 503 backend fetch failed. I've tracked the issue down to a JSESSIONID cookie being sent. When I remove the cookie it all works.
But here is the kicker: when logging out, most cookies (including the JSESSIONID cookie) get an expiry of epoch 0. So I would expect the cookie to not being sent by the Insomnia client, since it expired on 1970-01-01T00:00:00.000Z. But instead, Insomnia is still sending the cookie along. Manually editing the cookie to expire at 1970-01-01T00:00:01.000Z (so epoch +1) does work. Now Insomia sees the cookie has expired and will not send it.

This cookie is received at logout:
> Set-Cookie: JSESSIONID=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT

But then, sending a new requests Insomnia still sends the cookie along:
> DELETE /url HTTP/1.1
> Host: server
> User-Agent: insomnia/6.3.2
> Cookie: JSESSIONID=; sessionId=5d419a93-d349-1bbf-88bd-956770ec40c7
> Accept: */*

(The other "sessionId" being sent in the request was not expired, so that works as expected)

**Comment by comburo** [comment]
I kind of assumed Curl, being a command line tool, does not remember state between each invocation. So cookies being set by one request, won't be known for the next request.
Still, to be a 100% sure I performed the bunch of requests from the command line and like I expected, no cookies are transferred from one request to the next.

So command line Curl does not reproduce this problem, because I have to specify each (cookie) header for each new request.

**Comment by gschier** [comment]
You can tell curl (command line) to use a local file to store/send cookies from to get persistent sessions

**Comment by comburo** [comment]
It seems that CURL is handling the cookies the wrong way.
I did a request that should remove the cookie. I can see this in the verbose response:
`< HTTP/1.1 200 OK
* Replaced cookie sessionId="b659c9a3-b4cd-0004-5de9-168a254dad11" for domain example.com, path /, expire 0
< Set-Cookie: sessionId=b659c9a3-b4cd-0004-5de9-168a254dad11; Path=/; HttpOnly; Secure
`

But when I do a new request:
`> DELETE /session HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: example.com
> Accept: */*
> Cookie: sessionId=b659c9a3-b4cd-0004-5de9-168a254dad11
`
It's still sending the sessionId cookie, even though it's expired.

Also, just to let you know. I no longer have a stake in this issue. I'll be moving back to Postman. I really like Insomnia, but since the API I need to test has implemented XSRF tokens, being unable to copy a header value from any successful request, like mentioned here https://github.com/getinsomnia/insomnia/issues/217 is really inconvenient for me. Aside from a login needed to done first, all other requests can be in any arbitrary order, so Request Chaining won't solve my issue.
