### ISSUE TITLE
[Bug] Dialogs don't work from within request / response hooks in plugins

### ISSUE THREAD

**Issue by amjd** [getinsomnia/insomnia#1341]
- Insomnia Version: 6.3.2
- Operating System: macOS High Sierra (10.13.6)

## Details
Triggering dialogs from within request or response hooks in plugins doesn't work currently. This is what I used in the response hook of a plugin:

```js
await context.app.alert("Sample title", "Sample message");
const val = await context.app.prompt("Sample prompt");
```

On adding a breakpoint, I observed that they both seem to resolve an empty promise within an `if` condition that checks something called the render purpose.

I found that render purpose can have two values: `RENDER_PURPOSE_GENERAL` and `RENDER_PURPOSE_SEND`. The former is the default and doesn’t allow one to show dialogs / alerts.

The render purpose is specified in a property of `RenderContext` object, which seems to be only available in template tags, and not within request / response hooks, which is what my plugin uses.

Maybe the render purpose needs to be set to `RENDER_PURPOSE_SEND` whenever a plugin code is executed.

**Comment by matthijssn** [comment]
Same issue here. I tried to open a prompt from a requestgroupaction, but the mentioned property is set to "no_render", so no dialog is rendered.
