### ISSUE TITLE
[Feature Request] Sticky request in the left menu.

### ISSUE THREAD

**Issue by Lokocr** [getinsomnia/insomnia#1344]
##Add sticky request in top of the left menu.

- Insomnia Version: 6.3.1
- Operating System: Linux Mate (Ubuntu 18.04.1 LTS)

## Details

I think it should be a good idea to have some sticky request, for example, when you have a important request like Token generator for authentication but are you have more than 30 other request saved in the request menu (left one in the UI).

![image](https://user-images.githubusercontent.com/1214120/51550399-e1152180-1e31-11e9-8f96-87563aea74fa.png)

I could be store in the same menu but with a flag or somthing like that, something that make a difference look from the other ones.

**Comment by gschier** [comment]
Yes! This one has been in the back of my head for a while now. Essentially, the ability to pin requests (a common feature in many apps).

Also, it looks like you'd benefit from putting some of those in folders 😆🙃

**Comment by viktree** [comment]
@gschier Never contributed to open source before, but I use insomnia every day and would definitely find value in this feature valuable. I would love to take a crack at it this, if that is okay.

**Comment by gschier** [comment]
@viktree it's definitely okay if you want to try 😃

**Comment by brendano86** [comment]
@viktree are you still looking to do this?  I was *also* considering it 😄

**Comment by viktree** [comment]
@brendano86 Kinda left this for a little while. Have at it 😄

**Comment by develohpanda** [comment]
@brendano86 any progress from your end? Otherwise I will pick this up.

**Comment by develohpanda** [comment]
@gschier I've started on this and my approach (for both request and request group) is to:
1) Create a `Pin/Unpin` option in the action menu dropdown
2) Show section identical to the `sidebar-list` between the `filter` and `sidebar-list`, for pinned items (hidden if no pinned items)
3) Show a `fa-thumb-tack` on pinned items

I'm yet to figure out sizing constraints for the pinned rows and all rows, but will make sure they are easy to differentiate. This is the only way I could think of having sticky/pinned items that stay at the top while the rest of the section scrolls.

Am I on the right track?

**Comment by gschier** [comment]
It sounds like you're on the right track @develohpanda 😄 

If you want some early feedback feel free to create a PR with what you have.
