### ISSUE TITLE
[Bug] Insomnia fails to start on Fedora 29

### ISSUE THREAD

**Issue by theomessin** [getinsomnia/insomnia#1347]
- Insomnia Version: `6.3.2`
- Operating System: `Fedora 29 (4.20.3-200.fc29.x86_64)`

## Details

Insomnia completely fails to start. Tried reinstalling, updating OS, etc. Can't really help with reproducing this. Hoping to get some pointers on how to go about fixing this though. Running `insomnia &` will start a process which will instantly exit: 

```
% insomnia &                                                                  ~
[1] 8807
%                                                                             ~
[1]  + 8807 exit 1     insomnia
```

**Comment by gschier** [comment]
Any errors if you run it in the foreground? Does Insomnia show anything?

Did you use the Snap image or the AppImage package?

**Comment by theomessin** [comment]
Closing this cause it's hogging my dashboard. Still don't know why the Snap didn't work. Just us the AppImage.

**Comment by ludop-usharesoft** [comment]
Same problem here with fedora 29.

**Comment by l217** [comment]
I solved the problem in fedora 29 by downloading the rpm and installing with dnf
link [Realeses](https://github.com/getinsomnia/insomnia/releases)

**Comment by gschier** [comment]
I'm glad to hear the RPM worked! I've updated the build system to publish an RPM package to GitHub releases for all future updates. Closing this one for now

**Comment by ThHareau** [comment]
I had a similar issue with slack on fedora (which is also using electron). I don't know if it's related. 

Anyway, the rpm worked for me also

https://ask.fedoraproject.org/en/question/129141/slack-not-running-on-fedora-29/

**Comment by kaitlynbrown** [comment]
A link to the rpm on the download page would be nice too btw (since the snap doesn't seem to work at all)

**Comment by mbn18** [comment]
Same problem

- Insomnia Version: 16-2.39  Rev: 6964
- Operating System: Fedora 29 (updated regularly)

## Details

Was installed using snap: https://snapcraft.io/insomnia

Can no longer start it:

```
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
[fix] Running database repairs
[db] Initialized DB at /home/miki/snap/insomnia/30/.config/Insomnia/insomnia.$TYPE.db
Init responses DB
[localstorage] Initialized at /home/miki/snap/insomnia/30/.config/Insomnia/localStorage
Trace/breakpoint trap (core dumped)
```

**Comment by shivdhar** [comment]
> A link to the rpm on the download page would be nice too btw (since the snap doesn't seem to work at all)

+1 for a clear RPM link and "Install instructions for Fedora/CentOS" on the downloads page.

 I only found out that an RPM -- my first installation preference -- existed through this issue. Snaps are always a pain to work with.

**Comment by FaisalFehad** [comment]
Couldn't even install the RPM version as I'm getting 'Bad PGP signature' when trying to install it on Fedora with Discover.  

Update: Apparently this is caused by a. bug with dnf package manager. doing
 $ sudo dnf filename
seems to do the installation just fine.

**Comment by mariusa** [comment]
@theomessin +1 for a clear RPM link and "Install instructions for Fedora/CentOS" on the downloads page, please

**Comment by zoedsoupe** [comment]
I'm using the snap package and having the same issue. I'm on Manjaro gnome

Using the AppImage for now, but there's a way to recover my data once I can't even open the app? I didn't backed up some of my data. 

![Screenshot from 2020-06-02 14-59-21](https://user-images.githubusercontent.com/44469426/83553519-ab7e4f00-a4e1-11ea-9d87-b0742c4ac570.png)

**Comment by Felipe00** [comment]
Manjaro 29 too, I faced this issue few days ago. I tried to open in a virtual machine and got same error:
```
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
[fix] Running database repairs
[db] Initialized DB at /home/lacroiix/snap/insomnia/62/.config/Insomnia/insomnia.$TYPE.db
Init responses DB
[localstorage] Initialized at /home/lacroiix/snap/insomnia/62/.config/Insomnia/localStorage
Trace/breakpoint trap (imagem do núcleo gravada)

```
Can someone to enlighten us?

**Comment by tebruno99** [comment]
Same issue for me. I found a reference to Electron apps not working because the dbus error: 

https://github.com/snapcore/snapd/pull/7129
https://github.com/IsmaelMartinez/teams-for-linux/issues/175

I haven't seen a clear solution that would make it work.

```
snap --version
snap     2.45.2-1
snapd    2.45.2-1
series   16
```

**Comment by kaitlynbrown** [comment]
@theomessin please re-open this issue so that it can be addressed
