### ISSUE TITLE
[Feature request] Fixed Docs width is too short

### ISSUE THREAD

**Issue by ESnark** [getinsomnia/insomnia#1350]
- Insomnia Version: 6.3.2.2588
- Operating System: macOS 10.14.2

## Details

The document content area is too narrow regardless of the window size and this is very disturbing to read documents.
For now, The Doc tab is good enough to deliver descriptions but I think It can be better.

**Comment by ESnark** [comment]
<img width="816" alt="screen shot 2019-01-30 at 11 27 46 am" src="https://user-images.githubusercontent.com/31977180/51954368-48ab1c80-2483-11e9-8e71-9e6c3a6e9a13.png">
@gschier This is a screenshot of the full-sized window and max width docs at the same time.

**Comment by gschier** [comment]
This is intentional so the with does not get any wider than the optimal reading width of 60-80 characters.

**Comment by ESnark** [comment]
Sorry for the delay. If you say so, I won't ask about the problem anymore. But I still think that a wider document will be more useful.
