### ISSUE TITLE
[Bug] Requests hanging with SSL Validation disabled

### ISSUE THREAD

**Issue by sheharyarn** [getinsomnia/insomnia#1352]
- Insomnia Version: 6.3.2 (6.3.2.2588)
- Operating System: macOS Mojave 10.14.2

## Details

I have a local webserver running on both HTTP and HTTPS with a self-signed certificate. GraphQL requests work as expected when using HTTP, but when using HTTPS (with SSL validation disabled), the requests never complete. A timer appears that's constant increasing and the request never finishes. I don't see any incoming requests in the web server either (the web server works correctly, I've tested it with GraphIQL and Apollo javascript client).

<img width="595" alt="image" src="https://user-images.githubusercontent.com/2355108/51811917-4d9e7f00-227d-11e9-8168-8a07f6292830.png">

**Comment by gschier** [comment]
Anything useful in the Timeline tab?

**Comment by sheharyarn** [comment]
Hey @gschier. This is all there is in the Timeline Tab. Important thing to note here is that the connection closes pretty quickly (within ~2 seconds), but the spinner keeps spinning until you cancel the request manually:

```
* Preparing request to https://app.dev/graphql
* Using libcurl/7.52.1 OpenSSL/1.0.2p zlib/1.2.11
* Disable timeout
* Enable automatic URL encoding
* Disable SSL validation
* Enable cookie sending with jar of 0 cookies
* Found bundle for host myapptest.com: 0x7fddb9d6ae68 [can pipeline]
* Hostname shey.slabdev.com was found in DNS cache
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to app.dev (127.0.0.1) port 4000 (#113)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
*   CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* Curl_http_done: called premature == 1
* Closing connection 113
```

**Comment by sheharyarn** [comment]
@gschier Were you able to figure out what's causing this?

**Comment by abdullahumer** [comment]
I faced the same issue.
