### ISSUE TITLE
[Feature request] add completion suggestions to "Filter response body"

### ISSUE THREAD

**Issue by toughengineer** [getinsomnia/insomnia#1353]
XPath and JSONPath filtering of response body is AWESOME!

It would be even more awesome if it showed completion suggestions in a pop-up list while you enter an XPath or a JSONPath for filtering.

- Insomnia Version: 6.3.2
- Operating System: Windows 10

## Details

When you enter correct query or you are entering a query that is not yet correct, the initial response body is replaced with current query result or an empty result, or an error message. Since the initial contents are hidden from you, it is hard to compose queries because you have no reference immediately in front of you.
Providing completion suggestions while you type a query will significantly improve this experience.

**Comment by gschier** [comment]
I agree this would be awesome! Unfortunately, I don't think any libraries exist for that yet so it'd be a large amount of work.

**Comment by toughengineer** [comment]
I'm not a javascript developer by _any_ stretch but here is what I would do.

For JSONPath let's look at default example at https://codebeautify.org/jsonpath-tester.
When I type `$.` it is equivalent to the initial JSON so you just iterate over top level element names and spew them in the pop-up list, in this case it's just `employees`.

OK, now I type `$.employees.` and in fact want to have the top level element names from the result of the query `$.employees` which is the query I am typing but without the last dot `.` and everything that follows. Top level element of the query `$.employees` is `employee` so we spew it in the pop-up list.

Now if I write `$.employees.employee.` it's an error because `employee` is an array.

OK, let's query all the array elements so I write `$.employees.employee[*].` and by the same rule we gather top level elements from the result of the query `$.employees.employee[*]` without the last dot and everything that follows. We get `id`, `firstName`, `lastName` and `photo` and that's what we put in the pop-up list.

I think something similar can be done for XPath.

I am willing to help to implement this feature. How can I help to make it happen?

Just in case it changes, here is the example:
<details><summary>click to expand</summary>
<p>

```javascript
{
  "employees": {
    "employee": [
      {
        "id": "1",
        "firstName": "Tom",
        "lastName": "Cruise",
        "photo": "https://pbs.twimg.com/profile_images/735509975649378305/B81JwLT7.jpg"
      },
      {
        "id": "2",
        "firstName": "Maria",
        "lastName": "Sharapova",
        "photo": "https://pbs.twimg.com/profile_images/3424509849/bfa1b9121afc39d1dcdb53cfc423bf12.jpeg"
      },
      {
        "id": "3",
        "firstName": "James",
        "lastName": "Bond",
        "photo": "https://pbs.twimg.com/profile_images/664886718559076352/M00cOLrh.jpg"
      }
    ]
  }
}
```

</p>
</details>

**Comment by toughengineer** [comment]
By the way [here](http://react-jsonpath-editor.surge.sh/) is a demo of an awesome implementation of autocomplete for JSONPath: https://github.com/JeanBaptisteWATENBERG/react-jsonpath-editor
