### ISSUE TITLE
[Bug] No importers found for file (swagger 2.0)

### ISSUE THREAD

**Issue by alxpsr** [getinsomnia/insomnia#1354]
- Insomnia Version: 6.3.2
- Operating System: windows 10_x64

## Details
I'm trying to import my `swagger.json` into Insomnia, but got an error: `No importers found for file`. Swagger version is 2.0. What i'm doing wrong?

**Comment by gschier** [comment]
Can you post an example `swagger.json` that reproduces the problem?

**Comment by Tiberriver256** [comment]
Same here on the latest version

**Comment by WasserEsser** [comment]
We're facing the same issue. We have been supplied three swagger.json files and only one of them can get imported.

**Comment by alxpsr** [comment]
any progress? 🙄

**Comment by dominik-lekse** [comment]
I have tried to import the following Swagger 2.0 spec without success: "No importes found for file"

https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2019-02-01/managedClusters.json

**Comment by Dracer5** [comment]
A lot of people experiencing with bug. Will you provide further info?

**Comment by gschier** [comment]
Just took a look at this and it seems like `$ref` attributes are causing the issues.

@alxpsr's example file returns the following error:

```
Error resolving $ref pointer "/Users/gschier/Workspace/insomnia/desktop/packages/insomnia-app/#/definitions/Dto.Document.DocumetnDto". 
Token "definitions" does not exist.
```

@dominik-lekse's example returns the following error:

```
Error opening file "/Users/gschier/Workspace/insomnia/desktop/packages/insomnia-app/examples/ManagedClustersList.json" 
ENOENT: no such file or directory, open '/Users/gschier/Workspace/insomnia/desktop/packages/insomnia-app/examples/ManagedClustersList.json'
```

It looks like $refs are only for linking to documentation reference so there errors probably should be ignored. I just refactored the import module to try continuing if the Swagger validation fails. This should fix the problem I think.

**Comment by gschier** [comment]
Also, thank you @alxpsr for the test case file. I've included it in the test suite fixtures

**Comment by rmedaer** [comment]
I figured out that there is the same bug in OpenAPI importer (`openapi3.js`). Here is the output of my console:

```
openapi3.js?9a64:87 SyntaxError: Error resolving $ref pointer "/(...)/insomnia/packages/insomnia-app/#/components/schemas/api-version". 
```

I guess we could apply the same fix ?

**Comment by rmedaer** [comment]
Here is my patch: #1515
