### ISSUE TITLE
Space in installation directory breaks plugin installation on Windows

### ISSUE THREAD

**Issue by dunkelstern** [getinsomnia/insomnia#1355]
- Insomnia Version: 3.6.2
- Operating System: Windows 10

## Details

When trying to install a plugin from the preferences window you will be presented an error when the installation directory contains a space. This will probably happen often because Windows uses your `Firstname Lastname` tuple as directory name for your home-directory and the insomnia installer installs into your `AppData` directory. (But even if it did install to `Program Files` or `Program Files (x86)` the same would happen)

Screenshot:
![grafik](https://user-images.githubusercontent.com/456385/51904882-197fa700-23c0-11e9-9a29-1b73115e7e7a.png)

Text of error message:
```
insomnia-plugin-default-headers npm error: Command failed: "C:\Users\Johannes Schriewer\AppData\Local\insomnia\app-6.3.2\Insomnia.exe" --no-deprecation C:\Users\Johannes Schriewer\AppData\Local\insomnia\app-6.3.2\resources\bin\yarn-standalone.js info insomnia-plugin-default-headers --json
internal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module 'C:\Users\Johannes'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
```

If you correctly quote the path to the `yarn-standalone.js` it seems to work.

**Comment by gschier** [comment]
Dang, I was pretty sure I fixed this a while ago

**Comment by franticallycodes** [comment]
Hi there; just switched from Postman and I love Insomnia.

I'm having this same issue when trying to install a different package.
```
insomnia-plugin-customtimestamp npm error: Command failed: "C:\Users\Martin Cross\AppData\Local\insomnia\app-6.3.2\Insomnia.exe" --no-deprecation C:\Users\Martin Cross\AppData\Local\insomnia\app-6.3.2\resources\bin\yarn-standalone.js info insomnia-plugin-customtimestamp --json
internal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module 'C:\Users\Martin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
```

**Comment by gschier** [comment]
What is the appropriate way to escape spaces on Windows? There is currently some logic that surrounds the path with quotes but that doesn't solve it according the the continued reports.

https://github.com/getinsomnia/insomnia/blob/e68b1b186c41b5938dd01015cd74fb0045508053/packages/insomnia-app/app/plugins/install.js#L184-L192
