### ISSUE TITLE
[Feature Request] Copy-Paste headers, data, etc. from Chrome/Firefox

### ISSUE THREAD

**Issue by dragondave** [getinsomnia/insomnia#1356]
- Insomnia Version: 6.3.2
- Operating System: Linux (Ubuntu 18.10 I think) 

Often I'm reverse-engineering existing APIs, so the first port of call will be asking "what request is the browser already making?" So I'll be visiting the Network table of the Inspect panel in my browser, and copying the headers as-is to see if I can replicate the behaviour, then work out what all the bits do.

When copy-pasted from the Inspect tab the headers/data look like this:

```
key: value
Another-Key: another-value
```

i.e. each item separated by a newline, each key separated from the value by colon-space, `: `.

In Python I'm using the one-liner

```head = dict([[h.partition(': ')[0], h.partition(': ')[2]] for h in headers.strip().split('\n')])```

to instantly convert the data into a dictionary suitable for throwing at the 'requests' library.
(This effectively splits on the first `: `, it's possible the value could contain it, but the key can't.

----

So, what I'm wondering is if when:

* pasting text into the Headers or Query tab
* that text contains `: ` on each non-blank line
* [optional] the thing before the `: ` looks like a valid header/data key
* [optional, discouraged] the text is multi-line

the text could be parsed as multiple key-value pairs appropriately?

No worries if this isn't your use-case, etc... just thought I'd let you know of a feature that might be of use to some people.

**Comment by gschier** [comment]
Have you tried the "Bulk Editor" in the headers tab? It seems like it does exactly this.
