### ISSUE TITLE
[Bug] Renaming env variable makes requests invalid

### ISSUE THREAD

**Issue by pinggi** [getinsomnia/insomnia#1357]
- Insomnia Version: 6.3.2
- Operating System: Win10

## Details

1. Create env. variable {service_url}
2. Create 20 requests having url starting with "{service_url}/"
3. Rename the env. variable
4. All 20 requests are invalid. There is asterisk mark in a triangle instead of the env. variable.

You need to manually fix the 20 requests manually!
The env. variable should be renamed for every request automatically!

**Comment by natebrunette** [comment]
boop

**Comment by mih-kopylov** [comment]
Are there any plans to fix that?

**Comment by mih-kopylov** [comment]
Hey, could you please reopen it?
