### ISSUE TITLE
[Feature Request] Authentication Feature should have own Timeline and Code Generation

### ISSUE THREAD

**Issue by krainboltgreene** [getinsomnia/insomnia#1358]
- Insomnia Version: 6.3.1 (6.3.1.2586)
- Operating System: macos 10.13.6 (17G3025)

## Details

Normal requests have a Timeline pane and a Generate Code action, however things like the OAuth2 pane have neither.

**Comment by gschier** [comment]
Ya, the code generation is done through an open source library that doesn't know about those things...

Unfortunately, a lot of the authentication stuff is complicated and handled by `libcurl` under the hood, making writing code generation really difficult in a lot of cases (such as Windows NTLM auth)

**Comment by gschier** [comment]
Timeline entries for OAuth 1/2 might be possible though
