### ISSUE TITLE
[Bug] When duplicating request right before some folder, new request is placed below the folder

### ISSUE THREAD

**Issue by 4ekki** [getinsomnia/insomnia#1361]
[Bug] When duplicating request right before some folder, new request is placed below the folder
- Insomnia Version: 6.3.2
- Operating System: Windows 10

## Details
![gif](https://user-images.githubusercontent.com/38757986/52064525-770d2280-257d-11e9-9597-acb3b8fa6f13.gif)
Expected that duplicated request is placed right below original one.

**Comment by maniutek20** [comment]
@4ekki You have a lot of luck: I can't add request or folder (Win10 Home)
