### ISSUE TITLE
[Feature Request] Option to import queries from Apollo's Operation Registry

### ISSUE THREAD

**Issue by jhalborg** [getinsomnia/insomnia#1364]
Our team are heavy Apollo users, and we use the [Apollo Registry](https://www.apollographql.com/docs/platform/operation-registry.html) amongst other things. The TL;DR of the registry is that it allows us to upload all of our queries from our frontend clients (mobile/web) to the Apollo Platform, and then on the backend say 'Do not allow arbitrary queries against our production API, only allow the ones uploaded from our client projects using the API key' which is amazing in terms of security, as well as allowing some performance optimisations. 

Our team has just recently discovered Insomnia, and it looks really cool! But what would be really, really cool is if we could somehow provide our Apollo API key to the app (maybe through a plugin), and then have it download all of our registered queries to be run from Insomnia, with an option to update them from the registry as needed. 

I hope it makes sense, otherwise I'll gladly provide more info 🙌

**Comment by gschier** [comment]
Does Apollo support exporting data like this? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jhalborg** [comment]
Yes,

https://github.com/apollographql/apollo-tooling#apollo-clientextract-output

😄

**Comment by gschier** [comment]
I'm not sure I understand what you mean by that. Perhaps you could provide some code examples?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jhalborg** [comment]
Sure, 

If you have a project using Apollo as a GraphQL client, the project will have the queries and mutations in `gql` tags. These queries and mutations can be extracted into a `json` file by using the command `apollo client:extract`, the docs for which is linked above. This outputs the queries into a `manifest.json` file that looks something like this:

```
{
  "version": 1,
  "operations": [
    {
      "signature": "e3eb...f8d",
      "document": "mutation UploadSubmission($campaignId:ID!,$caption:String!,$imageIds:[ID!]!,$postMediaType:PostMediaType!){campaignSubmissionCreate(campaignId:$campaignId,caption:$caption,imageIds:$imageIds,postMediaType:$postMediaType){__typename id}}",
      "metadata": {
        "engineSignature": "mutation UploadSubmission($campaignId:ID!,$caption:String!,$imageIds:[ID!]!,$postMediaType:PostMediaType!){campaignSubmissionCreate(campaignId:$campaignId,caption:$caption,imageIds:$imageIds,postMediaType:$postMediaType){__typename id}}"
      }
    },
    {
      "signature": "7196ab33...2ca",
      "document": "mutation PushNotificationTokenRegister($token:String!){registerNotificationToken(token:$token){__typename id}}",
      "metadata": {
        "engineSignature": "mutation PushNotificationTokenRegister($token:String!){registerNotificationToken(token:$token){__typename id}}"
      }
    },
  ]
}
```

If one could import a `manifest.json` into Insomnia and it would parse and create all these queries/mutations, one would be able to very easily create and maintain all client operations your project **actually** uses instead of hand-typed and maintained approximations (or by doing a lot of copy pasting). It could even be integrated into a CI flow, so that your queries across multiple clients (i.e. mobile app, web app1, web app 2) would all extract their queries, merge them into a single `manifest` importable by the team into their Insomnia clients. 

This would, in my opinion, provide tremendous value to Apollo users of Insomnia (which I could imagine is a quite high percentage given Apollo's ubiquity in the GraphQL space)

I hope that makes sense?

**Comment by gschier** [comment]
Okay, that makes more sense now for sure. I was initially confused as to where the queries were coming from but it makes sense that it's extracted from source code (I have a small amount of experience with Apollo). 

Would you be interested in writing an importer for this? If so, you can check out the existing ones here for reference https://github.com/getinsomnia/insomnia/tree/develop/packages/insomnia-importers
