### ISSUE TITLE
[Bug] Invalid XML response encoding presentation

### ISSUE THREAD

**Issue by shadeglare** [getinsomnia/insomnia#1368]
There's a wrong XML response encoding presentation when making requests to XML web services with response encodings like `<?xml version="1.0" encoding="Windows-1251"?>`. As a workaround I can save a response as a file and open it via any text editor with a proper encoding but it's quite annoying.

Insomnia: 6.3.2 (6.3.2.2588)
MacOS: 10.14.2

Wrong encoding example:
<img width="193" alt="screen shot 2019-02-11 at 8 26 05 am" src="https://user-images.githubusercontent.com/995484/52547191-d289ac80-2dd6-11e9-8481-0a21aa005dd1.png">

**Comment by Dmitrevicz** [comment]
Same on Insomnia Response Preview when response is html and charset is set like this **`charset=windows-1251`**. 
**Expected** results on Response Preview tab: `Включен отладочный режим`
**Actual** results: `Р’РєР»СЋС‡РµРЅ РѕС‚Р»Р°РґРѕС‡РЅС‹Р№ СЂРµР¶РёРј`
