### ISSUE TITLE
[Suggestion] Add TroubleShooting

### ISSUE THREAD

**Issue by Ding-Fan** [getinsomnia/insomnia#1369]
- Insomnia Version: Version 6.3.2
- Operating System: 4.14.94-1-MANJARO

## Details

Please add this to [TroubleShooting](https://support.insomnia.rest/article/23-installation#linux):

After installed snap, you might need `systemctl restart snapd.service` . [More details](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1631514)

**Comment by gschier** [comment]
Thanks. Added.
