### ISSUE TITLE
[Question] TemplateTag plugin ordering

### ISSUE THREAD

**Issue by tehmantra** [getinsomnia/insomnia#1370]
- Insomnia Version: 6.3.2
- Operating System: Windows 10 Pro x64 1809

## Details

Hi,
Im writing a plugin for Insomnia to help with an API I'm testing.
Basically, we need to provide the same value multiple times in the request, and the value must be unique per request.
I'm using `insomnia-plugin-faker` to generate random numbers.

```json
{
  "example": "{% faker 'random', '', '', '', '', '', '', '', '', '', '', '', '', 'number', '', '', 'en' %}",
```

Then elsewhere in the request, I use my plugin to get this value.
```json
  "reference": "{% requestbodyjsonpath 'req_a71e53d53e1e4ebab20df69d4c95a779', '$.example' %}"
}
```

Unfortunately, this doesn't work as I need it to... It does seem to apply both plugins, but the values for `example` and `reference` are different. Which I assume means that my plugin is running first, replacing my tag with the faker tag. Then faker is running and replacing the faker tag with the random number. 

e.g.
```json
{
  "example": "123",
  "reference": "456"
}
```

Interestingly, if i change `example` to use an environment variable, then it just renders the environment variable tag.
e.g.
template:
```json
{
  "example": "{{i}}",
  "reference": "{% requestbodyjsonpath 'req_a71e53d53e1e4ebab20df69d4c95a779', '$.example' %}"
}
```
rendered request:
```json
{
  "example": "123",
  "reference": "{{i}}"
} 
```

Is there an intended behaviour for this type of plugin?
Would it be possible to explicitly order plugins?
Would it be possible to run plugins _after_ environment variable replacements? (Maybe this will break other plugins)
Should I look for '{{ }}' tags within my plugin and manually lookup environment variables?

Cheers,
Michael

**Comment by gschier** [comment]
I think you might be able to replace `'$.example'` with simply `example` and Nunjucks will include the variable for you. Can you see if that works? 

I think there's also a `render()` method exposed to plugins so you could render the `{% faker .... %}` tag directly from inside your plugin, although that would be kind of a hack.

**Comment by tehmantra** [comment]
Thanks for the reply. I decided to just use environment variables for anything that needed to be shared.
