### ISSUE TITLE
JMeter exporter

### ISSUE THREAD

**Issue by BackDoorManUC** [getinsomnia/insomnia#1376]
It would be nice to have support for exporting to JMeter (*.jmx file extension, it's just an XML). I think there exists something like this for Postman.

https://wiki.apache.org/jmeter/JmxTestPlan

**Comment by gschier** [comment]
Insomnia uses the httpsnippet library for code snippets. Feel free to submit a PR or issue on that project

https://github.com/Kong/httpsnippet

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
