### ISSUE TITLE
[Feature Request] Batch Delete

### ISSUE THREAD

**Issue by afk-mario** [getinsomnia/insomnia#1377]
- Insomnia Version:  6.3.2
- Operating System: Arch Linux

## Details
So I imported a HAR file and suddenly my Insomnia is filled with request I don't really like, my bad, but there doesn't seem to be a easy fast wat to delete multiple entries? Maybe a simple keyboard shortcut to delete without confirmation or not using the mouse would be enough, but Ideally I would like to select a group or requests and being able to delete them.

**Comment by afk-mcz** [comment]
Found you can use `shift + control + delete`  it would be nice if it showed up on the context menu when you right click a request
