### ISSUE TITLE
[Feature Request] launch same request several times with many args

### ISSUE THREAD

**Issue by danielo515** [getinsomnia/insomnia#1379]
## Details
This is a feature request.

Sometimes you want to use a list of values to trigger the same request multiple times. This is a tedious task now because you need to change the value manually and trigger the same request again.
Ideally, I want to provide a list, maybe extracted from a previous request and launch one request several times, one per each value on that list.

Regard

**Comment by danielo515** [comment]
I would love some human interaction. Even just for telling me that this is not going to be implemented

**Comment by gschier** [comment]
Sorry @danielo515! Some issue slip through the cracks. You may want to take a look at this: https://github.com/getinsomnia/insomnia/issues/774#issuecomment-489363559

**Comment by danielo515** [comment]
Thanks for the answer @gschier 
Does that mean that I have to write a plugin per each set of requests I want to send? Or that I should install a plugin that allows me to do that?
Thanks!

**Comment by gschier** [comment]
The latter – Install/create a plugin that allows you to do that

**Comment by kris-luminar** [comment]
I'm astounded this feature does exist yet in Insomnia. Might start making the long switch back to PostMan.
