### ISSUE TITLE
[Feature Request]  Load data presets

### ISSUE THREAD

**Issue by sturose** [getinsomnia/insomnia#1380]
- Insomnia Version: ___ 6.3.2
- Operating System: ___ All

## Details

Sometimes I want to have sets of pre-defined variable values (very much like how Environment variables work), but I just want to select them/click on them, and have them replace the values that currently exist for the corresponding global variables.  

In other words, not switching environments, but loading up datasets (e.g. I could predefine different users/addresses). 

Unlike environments, there would be no need to present the name of the dataset that was loaded on the main window, it would be a simple click to load the data, then just go back to business as usual.  It might be helpful to be able to filter out datasets via a bar to type the name with partial matches returned too.

**Comment by gschier** [comment]
A long time ago there was some discussion on adding the ability to activate multiple environments at once. Along with the use cases presented at the time, I think it could also solve your problem.

For example, you could activate **Production** and **User A** at the same time.
