### ISSUE TITLE
Disabling analytics (privacy)

### ISSUE THREAD

**Issue by jackTaw88** [getinsomnia/insomnia#1381]
Hi,

I had write here but the topic was closed: https://github.com/getinsomnia/insomnia/issues/665

I did not see this option to remove analytics. I am using 6.3.2 version.

I understand if you need statistics or not, but at least make it optional.

Thank you

**Comment by gschier** [comment]
Analytics were remove entirely from the application here https://github.com/getinsomnia/insomnia/commit/f918e647c05ad23a3b3e4347d793077732f9d86f
