### ISSUE TITLE
[Feature Request] Proxy configurable per request

### ISSUE THREAD

**Issue by inacho** [getinsomnia/insomnia#1385]
- Insomnia Version: 6.3.2
- Operating System: MacOS 10.14.3

## Details

In the company I'm currently working there are many internal APIs and all of them must be accessed by an internal proxy. The problem is that depending of the API, the proxy settings are different.
Currently the proxy settings of Insomnia are application wide, so I need to remember the settings for each API and change it manually every time.

It would be very convenient if the proxy settings could be overridden inside the request.

Thanks for developing this awesome application.

**Comment by asyba** [comment]
Unstale, please.

**Comment by hanlong-chen-1047** [comment]
Yes, please unstale this

**Comment by jacob-winkler** [comment]
Unstale please. This would be super valuable to many of us.

**Comment by n3tn0de** [comment]
Please unstale 🙏
