### ISSUE TITLE
[Feature Request] Duplicate auth

### ISSUE THREAD

**Issue by gspartners** [getinsomnia/insomnia#1386]
Hi

I really love using Insomnia! I have one request though.
When I duplicate a request, it doesn't duplicate the authorisation. Shouldn't it do it, since I'm using the duplicate functionality? If not, is it something you thing might be a good idea to implement?

Looking forward to be hearing from you.

**Comment by gschier** [comment]
Can you provide a screencast for this? To my knowledge, authentication settings _are_ duplicated successfully.
