### ISSUE TITLE
JSON validation fails

### ISSUE THREAD

**Issue by RisAbd** [getinsomnia/insomnia#1388]
- Insomnia Version: 

  Version 6.3.2
  Shell 3.0.4
  Node 10.2.0
  V8 6.6.346.32
  Architecture x64

  libcurl/7.61.1 OpenSSL/1.1.0h zlib/1.2.11 nghttp2/1.29.0
- Operating System: 
  Ubuntu 18.04.2 LTS

## Details

![screenshot from 2019-02-25 15-42-46](https://user-images.githubusercontent.com/19926490/53328836-0acfd580-3915-11e9-9d54-8c82f4e3ee3d.png)

i don't know how to explain this issue...
this placeholders or, let's say, dynamic value generators (awesome feature BTW) in json bodies written as is and fails JSON validation, of course because of syntax error.
```javascript
{
	"ads": "ebd8be85-161e-49d1-826b-df422a74d3ae",
	"start": 1551057662,
	"end": <some_integer_value_here>1551088705</some_integer_value_here>,
	"user_retention_group_above": 10
}
// becomes
{
	"ads": "ebd8be85-161e-49d1-826b-df422a74d3ae",
	"start": 1551057662,
	"end": {% now 'unix', '' %},
	"user_retention_group_above": 10
}
```

**Comment by gschier** [comment]
I think there's an issue somewhere around here for this already. Unfortunately it's pretty hard to fix.
