### ISSUE TITLE
[Feature Request] Option to always force HTTPS

### ISSUE THREAD

**Issue by patrickf3139** [getinsomnia/insomnia#1390]
It would be really nice if there was an option to force all requests being sent out to be over HTTPS so we don't have to prefix all our urls with https://. I forgot to do that and accidentally sent severals over the clear multiple times, wondering why my requests weren't working, until I realized I had forgotten to prefix my url with https:// (cause if you don't Insomnia assumes http:// I believe).

Thank you for reading this and for making Insomnia!

**Comment by gschier** [comment]
It's now actually possible to write a request hook plugin to do this: https://support.insomnia.rest/article/26-plugins#request-hook-api

You can check the URL of the request while it's being sent and override it to HTTPS if the protocol is not present.
