### ISSUE TITLE
[Feature Request] Multiple Nested Environments

### ISSUE THREAD

**Issue by natebrunette** [getinsomnia/insomnia#1392]
- Insomnia Version: 6.3.2
- Operating System: MacOS 10.14

## Details

This may be a duplicate of #553

It would be nice to have multiple nested levels of environments. My use case is that we have broader environments (dev, staging, prod) and different users within those environments that authenticate differently. Right now, I have to have an environment like `Me - Development` where I put all user and server specific variables. Additionally, users can belong to multiple accounts, so there's another potential level of separation.

Perhaps in the UI, you could select each environment separately starting from the top and it could filter the options for the sub environments.

**Comment by gschier** [comment]
I feel like this is the same as #283. It was closed for being stale but I have reopened it just now.

I've been wanting to do that one for a long time (as you can tell by the date of the issue) but just haven't gotten around to it yet.

**Comment by awkj** [comment]
> I feel like this is the same as #283. It was closed for being stale but I have reopened it just now.
> 
> I've been wanting to do that one for a long time (as you can tell by the date of the issue) but just haven't gotten around to it yet.

Can you describe the plan ?

I use workspace to split my projects, and I think if have environment  can cross workspace should be useful. because domain of company is similar even though project is diffent. but base enviroment limit I to use the same variable.
