### ISSUE TITLE
[Question] New community plugin

### ISSUE THREAD

**Issue by andrew512** [getinsomnia/insomnia#1395]
I wrote a simple plugin to extract a value from an environment variable via regular expression. It helped me solve a particular use case and I thought it could be helpful to others.

If you'd like to add it to the "Community Plugins" section of the support site ([https://support.insomnia.rest/article/26-plugins#community-plugins](https://support.insomnia.rest/article/26-plugins#community-plugins)), here is the info:

* GitHub: [https://github.com/andrew512/insomnia-plugin-regex](https://github.com/andrew512/insomnia-plugin-regex)
* npm: [https://www.npmjs.com/package/insomnia-plugin-regex](https://www.npmjs.com/package/insomnia-plugin-regex)

Insomnia is fantastic so far -- great work.

**Comment by gschier** [comment]
Awesome! I added it to the README 😄
