### ISSUE TITLE
Content Type automatically adds charset utf-8

### ISSUE THREAD

**Issue by fabiocarneiro** [getinsomnia/insomnia#1397]
- Insomnia Version: 6.0.2
- Operating System: Ubuntu 18.10

## Details

Imsonia is automatically adding `charset:UTF-8` to the `Content-Type` header when JSON body is selected and Content-Type header is `application/json`.

This is "wrong" because `application/json` is ALWAYS UTF-8, therefore you should never specify a charset. 

[https://www.iana.org/assignments/media-types/application/json](https://www.iana.org/assignments/media-types/application/json)

This should not be a problem because compliant recipients should just ignore the charset and always consider utf-8. Unfortunately, that is not true and some recipients simply consider "application/json" different than "application/json;charset=utf8", so it would be nice if the charset is removed. 

I did not check the code, but I expect this code is somehow standardized for any media type in this client, so If that is the case I suggest that you somehow define the rules per media type (as in the case of subtypes of text, as per HTML specifications the charset defaults to ISO-8859-1)

**Comment by fabiocarneiro** [comment]
My bad, insomnia is actually sending the correct header without charset. The issue is with the server.

**Comment by mxmlnglt** [comment]
I question where you get that `application/json` is **always** UTF-8?

https://www.iana.org/assignments/media-types/application/json
just mentions that:

> Note:  No "charset" parameter is defined for this registration.
   Adding one really has no effect on compliant recipients.
