### ISSUE TITLE
Moving folder to workspace copies instead

### ISSUE THREAD

**Issue by kitsu** [getinsomnia/insomnia#1398]
### Versions

- Insomnia Version: 6.3.2
- Operating System: Win7

### Details

I was trying to get a little organized this morning, created a new workspace and tried to ship some folders over there. It seemed to work correctly on single requests, but I noticed moved folders still appear in their original workspace.

I checked the request ids between the two workspaces and the requests are separate instances.
I *was* able to delete the old folders + requests after moving, so it is just an inconvenience.

Thanks!

**Comment by gschier** [comment]
Thanks for reporting this! It sounds like it was probably a design oversight and should be fixed
