### ISSUE TITLE
[Feature Request] - Run script on directly on Insomnia

### ISSUE THREAD

**Issue by artoodeeto** [getinsomnia/insomnia#1399]
Hello. Is this possible for a feature that you could run script on insomia? Example.
I have to test something at work where I need to notify my fake user account. so i have this body.
```
{
  "id": "150129",
  "workstep_final": "Completed"
}
```

i need to change the id for every request. Since I have a hundred sample ID's I was thinking of putting them in an array and make a simple script that automates my request. sorry if im not being clear.

**Comment by senoctar** [comment]
This is possible with the [Chance](https://www.npmjs.com/package/insomnia-plugin-chance) plugin.
Install the plugin and use the template tag with "Pick One". Edit the tag an enter the values as an array under Options: 
![image](https://user-images.githubusercontent.com/970918/56248071-8ea17500-60af-11e9-96c5-551df032f098.png)
Your body in the editor should look like this:
![image](https://user-images.githubusercontent.com/970918/56248098-a547cc00-60af-11e9-8b97-076a4fd70053.png)
Once you make a request a random item from the array is picked. You will be able to see the value in the timeline:
![image](https://user-images.githubusercontent.com/970918/56248147-c9a3a880-60af-11e9-8fcc-4099ed725297.png)

**Comment by artoodeeto** [comment]
thank you so much!!! I was thinking of doing a bash script and curl for http. thank you
