### ISSUE TITLE
[Feature Request] Type checking requests

### ISSUE THREAD

**Issue by krainboltgreene** [getinsomnia/insomnia#1400]
Okay, so here's the idea:

What if a plugin could provide type checking for requests? For example, I often mess up jsonapi requests by hand, but with a type checker that could be very easy to detect. Further, you could expand type checking to type check based on auto discovery services like json-home.

**Comment by gschier** [comment]
You can right a plugin right now to type check requests using a request hook. You can use the `getBodyText` method to get the body of the request at send time, validate it against some sort of schema, and show an alert if it fails.
