### ISSUE TITLE
[Improvement] Persist code folding in responses

### ISSUE THREAD

**Issue by kzbt** [getinsomnia/insomnia#1402]
- Insomnia Version: 6.3.2
- Operating System: macOS

## Details

Hello,
Would it be possible to persist the code folding of json responses?
Currently any code folding I've done to a response will be gone if I navigate away to another api. Its quite inconvenient when browsing and comparing large api responses 

# How to replicate
Create two simple endpoints (eg: httpbin.org/get) and execute both of them. Fold the reponses in any way. Use the sidebar to switch between them.
Expected: The code folding is preserved until the next time same request is executed.
Actual: Code folding resets

I would have provided this as an import, but my environment restricts access to outside resources (httpbin, postman-echo etc)

**Comment by gschier** [comment]
I just took a brief look around for ways to do this in [CodeMirror](https://codemirror.net/doc/manual.html) but wasn't able to find a way. There's already some logic for persisting scroll position, selections, cursor, and edit history if someone else wants to look into this further:

https://github.com/getinsomnia/insomnia/blob/0333244d332e5c765e9e02d4666d0b7ac7275255/packages/insomnia-app/app/ui/components/codemirror/code-editor.js#L231-L259

**Comment by develohpanda** [comment]
It's possible to find the `marks`, I'm investing whether it is possible to also set the `marks` when we want to restore state.

![image](https://user-images.githubusercontent.com/4312346/69492497-7b3d6e80-0f08-11ea-9642-89ebff2c4c62.png)
