### ISSUE TITLE
[Feature Request] Show id in collapsed json object

### ISSUE THREAD

**Issue by pinggi** [getinsomnia/insomnia#1404]
- Insomnia Version: 6.3.2
- Operating System: Win10

## Details

I get response with json containing many items (entities). If I am not interested in their content, I can collapse them. However by doing this I loose their id. The collapsed json object is shown as {<-->}, but I'd like to see it's id { id: "99d610d9-cb4d-4c77-981e-f2d90e6134ca", ... }. To see many {<-->} are useless for me.

What I can see:
```
{
    "items": [
        {<-->},
        {<-->},
        {<-->},
        {
            id: "c4e02972-3276-4632-81c0-ac9b3c18867c",
            name: "",
            firstname: "",
            lastName: "",
            age: ""
        }
    ]
}
```

What I'd like to see:

```
{
    "items": [
        { id: "99d610d9-cb4d-4c77-981e-f2d90e6134ca", ... },
        { id: "699717b7-1a3f-4066-aa2c-9d495dc7fc3a", ... },
        { id: "c5578bc6-926d-4e4b-ac87-0091807351b1", ... },
        {
            id: "c4e02972-3276-4632-81c0-ac9b3c18867c",
            name: "",
            firstname: "",
            lastName: "",
            age: ""
        }
    ]
}
```

There could be a configuration - which property to show even when an object is collapsed in the result.

**Comment by sankalpsans** [comment]
Although this might make sense in some use cases, and specifically in yours, I see some issues with this. 

1. "id" is a naming convention that you are using, there might be many more. A possible workaround would be to specify which field is "ID" for you, but that might add more complexity to the product itself (usability).
2. There might be cases where unique identifier are objects with nested structures. Representation there would be really tricky.
3. Might lead to some bloat visually. You generally collapse fields when you don't want to focus on them.

Do you have some design suggestions that address these? Feel free to see if I missed out on some challenges here. 😄

**Comment by pinggi** [comment]
1. The property name doesn't have to be "id" always. It can be configurable by specifying list of the property names in an input field. I'm convinced the input field doesn't hurt the configuration neither the usability.

![image](https://user-images.githubusercontent.com/18471834/54550924-3e9a9a00-49ad-11e9-869f-45424062fb5f.png)

2. If it's not a simple type, then only the name + collapsed sign could be shown. It should be simple not complicated - no nested structures.

![image](https://user-images.githubusercontent.com/18471834/54551151-c97b9480-49ad-11e9-9c1e-6d57b9b1bec3.png)

3.  It could be switchable if needed, for instance:

![image](https://user-images.githubusercontent.com/18471834/54551704-df3d8980-49ae-11e9-9548-1e6fe3d14b63.png)
![image](https://user-images.githubusercontent.com/18471834/54551636-be753400-49ae-11e9-93c7-8a3739f0f11f.png)

^ all of them are just examples, it doesn't need to be implemented exactly like that ;-)

**Comment by gschier** [comment]
This one might be tricky, as code folding is currently done within the CodeMirror text editor itself. It also works for many different languages and formats. 

That being said, if someone wants to take a look and see how difficult it might be to implement, I'm happy to discuss 👍
