### ISSUE TITLE
[Bug] Installer taskbar icon is default Windows Forms icon

### ISSUE THREAD

**Issue by banksio** [getinsomnia/insomnia#1405]
- Insomnia Version: 6.3.2
- Operating System: Windows 10 19H1 Insider Build

## Details

When installing Insomnia via the download button on https://insomnia.rest/, the taskbar icon does not have any title or text associated with it, and the icon is that of the default Windows Forms icon.

![image](https://user-images.githubusercontent.com/30214760/54308671-5f867800-45c6-11e9-93d3-ce82ee2be293.png)

**Comment by banksio** [comment]
If this won't be fixed, is there a way I could create a pull request to cover it?

**Comment by gschier** [comment]
Ah, yes @banksio , that would be awesome if you'd like to take a look. I imagine it's due to something in electron-builder but upgrading to a later version causes the production build to fail unfortunately. 

Going to tag this one so it won't be closed and feel free to take a look if you'd like to help 😄

**Comment by banksio** [comment]
After some research, it was actually a known (issue/feature) in Squirrel.Windows https://github.com/Squirrel/Squirrel.Windows/issues/152, which is the installation framework that's set in `.electronbuilder`. Supposedly there's not meant to be a taskbar icon at all (https://github.com/Squirrel/Squirrel.Windows/pull/184), so I'm not sure why it appears in this case.

Squirrel.Windows is actually deprecated in electron-builder, so the issue probably will not be fixed. They recommend using NSIS instead. Is this something that would be considered?

Also, as a side effect I've actually fixed the bug of the default icon showing up in Control Panel - the correct icon now appears! #1514
