### ISSUE TITLE
[Feature Request] Allow different font styles

### ISSUE THREAD

**Issue by leonbreedt** [getinsomnia/insomnia#1407]
- Insomnia Version: 6.3.2 
- Operating System: macOS

## Details

The ability to choose a font for UI and text editor is great, thank you for adding this. I would like to propose a small tweak. 

I noticed the fonts I use most often do not show up in the drop-down list.

After some investigation it seems some pre-filtering is done to exclude non-italic and non-regular styles, in _general.js_.

I imagine this was probably to avoid duplicates in the drop-down list, but as it happens, the font I prefer for my UI, names its regular style _Book_, and not _Regular_, and I prefer the _Medium_/_Semibold_ style for my text editor, and I actually don't have the other weights installed, so I'm out of luck on both counts, the font effectively doesn't exist from Insomnia's perspective.

Is allowing font style to be selected something that could be considered?

Right now, I've hacked my local build as follows, works great:

```diff
diff --git a/packages/insomnia-app/app/ui/components/settings/general.js b/packages/insomnia-app/app/ui/components/settings/general.js
index 39328491..67eeaea1 100644
--- a/packages/insomnia-app/app/ui/components/settings/general.js
+++ b/packages/insomnia-app/app/ui/components/settings/general.js
@@ -37,7 +37,6 @@ class General extends React.PureComponent<Props, State> {
   componentDidMount() {
     fontManager.getAvailableFonts(allFonts => {
       const fonts = allFonts
-        .filter(i => i.style.toLowerCase() === 'regular' && !i.italic)
         .sort((a, b) => (a.family > b.family ? 1 : -1));
       this.setState({ fonts });
@@ -256,7 +255,7 @@ class General extends React.PureComponent<Props, State> {
                 <option value="__NULL__">-- System Default --</option>
                 {fonts.map((item, index) => (
                   <option key={index} value={item.family}>
-                    {item.family}
+                    {item.family} {item.style}
                   </option>
                 ))}
               </select>
@@ -288,7 +287,7 @@ class General extends React.PureComponent<Props, State> {
                 <option value="__NULL__">-- System Default --</option>
                 {fonts.filter(i => i.monospace).map((item, index) => (
                   <option key={index} value={item.family}>
-                    {item.family}
+                    {item.family} {item.style}
                   </option>
                 ))}
               </select>
```

![image](https://user-images.githubusercontent.com/167841/54387105-6f55a780-46ff-11e9-856b-235a57d748f2.png)

![image](https://user-images.githubusercontent.com/167841/54387125-809eb400-46ff-11e9-997a-ae8a5c8fe5b9.png)

Thoughts?

**Comment by leonbreedt** [comment]
Correction; this hack is not quite right since the settings only stores the family name, and not the selected style - that would also need to be stored for this to work correctly.

**Comment by gschier** [comment]
So your change does not modify the weight?

From what you said, it seems like changing the filter to include `book` may also work?

```js
.filter(i => i.style.toLowerCase() === 'regular' || i.style.toLowerCase() === 'book' && !i.italic)
```

**Comment by gschier** [comment]
Can you specify which font you are using so I can test it out?

**Comment by leonbreedt** [comment]
The UI font is _Circular_, but this is a commercial LineTo font. If you have access to a Mac, the Bodoni font is also using a style name of _Book_. Your suggestion works fine here.

The text font is a custom build of Iosevka I did because I don't like the thin rendering of its Regular style. However, the custom build still ends up having a style of _Medium_, and I don't see a nice workaround for this, because as soon as you include that in the filter, a lot of duplicates will show up in the drop-down, and you'll kind of want to be able to see the style to distinguish them, but this seems like a lot more work for you.

**Comment by gschier** [comment]
Ya, I think I agree that allowing weight selection is probably too complicated compared to demand. I have gone ahead and added "Book" fonts to the filter though so at least they will show up now 😄
