### ISSUE TITLE
Titlebar darker theme, insomnia gets black text instead white.

### ISSUE THREAD

**Issue by otavioschwanck** [getinsomnia/insomnia#1411]
- Insomnia Version: 6.3.2
- Operating System: Linux Mint 19.1 (occurs on Ubuntu 18.10+ with default theme)

## Details

![image](https://user-images.githubusercontent.com/9551316/54771451-121c9300-4be4-11e9-89a6-9cd32801b7da.png)

In full white theme and full dark theme it runs perfectly.  Probabily its a electron issue, it occurs on franz lately.

**Comment by gschier** [comment]
By full dark and full white do you mean Insomnia's themes, or your OS's themes?

**Comment by gschier** [comment]
I know this issue is older, but I'm going to close this one as a duplicate, since there is already discussion on #1454
