### ISSUE TITLE
[Feature Request] Mask preview for user inputs

### ISSUE THREAD

**Issue by exception117** [getinsomnia/insomnia#1412]
- Insomnia Version: 6.3.2.2588
- Operating System: macOS

## Details

For the `Prompt` tag, if the Mask Text option is selected and using the Storage Key option, the value displayed in the Live Preview should also be masked (or the Live Preview should be disabled). The use case is if I'm sharing my screen and pull up the tag editor, I don't want my secret to accidentally be revealed unless I intentionally unmask the text.

**Comment by gschier** [comment]
Ah yes, nice catch. Will fix this right away
