### ISSUE TITLE
[Feature Request] – Hide sensitive information (similar to Basic Auth password).

### ISSUE THREAD

**Issue by codephobia** [getinsomnia/insomnia#1413]
A way to hide tokens, OAuth information, etc from both the input forms, and the response headers. When using the app during content creation (Twitch, YouTube, screencaps, etc) it would be nice to show what is being done without worrying about leaking keys.

**Comment by b3none** [comment]
Potentially viable solution:
https://stackoverflow.com/a/45451268/8471992

**Comment by gschier** [comment]
This makes things bit less user-friendly but the Prompt tag now has a "mask input" checkbox.

![image](https://user-images.githubusercontent.com/587576/56839939-d5266a80-6839-11e9-9b7e-842255b9b59f.png)

And, if you use the "Storage Key" feature, it will only prompt you on first use.

![image](https://user-images.githubusercontent.com/587576/56839956-eb342b00-6839-11e9-83f3-9bcefa398fdc.png)

**Comment by gschier** [comment]
That, of course, does not work for response values. Do you have any ideas of solutions on how to generalize this? It would be possible to write a plugin response hook that uses `getBody` and `setBody` methods to replace sensitive info (maybe via regex or something).

**Comment by Essler** [comment]
Any new possibilities with this?

It's difficult to use Insomnia when demoing or even pair programming without flashing all of your passwords.

The only workaround I've found, for Form and Multipart bodies at least, is to change the sensitive field from _Text_ to _Text (Multi-line)_ and then the value is hidden until clicked on for editing. Though, tokens and headers can't be hidden in this way.
