### ISSUE TITLE
[Bug] Double curly braces with text inside

### ISSUE THREAD

**Issue by sandeeepbethu** [getinsomnia/insomnia#1415]
[Question] – How to pass a request body which has curly braces and text inside it? 
- Insomnia Version: 6.3.2
- Operating System: MacOS HighSierra

## Details
I am seeing encoding issues when i end data like {{store_logo}} in request body. I tried checking and unchecking the box `automatically encode spl characters n URL` but of no use!

**Comment by gschier** [comment]
You can disable rendering of the request body in the request settings.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/587576/55292022-b3110800-53b3-11e9-9be4-da199f9c3033.png">
