### ISSUE TITLE
[Improvement] Parse "Run in Postman" / Environment JSONs

### ISSUE THREAD

**Issue by stdedos** [getinsomnia/insomnia#1417]
- Insomnia Version: _Help->About does not work, no idea :/ `apt-get` hasn't provided an update though_
- Operating System: Ubuntu 16.04.5

## Details

Import from URL should work with e.g.:

* https://app.getpostman.com/run-collection/1755573c5cf5fbf7968b <br/> (`--> Web View` https://app.getpostman.com/view-collection/1755573c5cf5fbf7968b?referrer=https%3A%2F%2Fapp.getpostman.com%2Frun-collection%2F1755573c5cf5fbf7968b<br/>`--> Download JSON` https://app.getpostman.com/api/collections/1755573c5cf5fbf7968b)
* https://developer.okta.com/docs/api/postman/example.oktapreview.com.environment (JSON)

**Comment by gschier** [comment]
I just tried this and found two problems:

1. Insomnia does not support the Postman export format under https://app.getpostman.com/api/collections/1755573c5cf5fbf7968b. Currently it only supports collection format v2
2. Postman does not provide CORS headers on those endpoints so making the request fails. This can be solved by using something other than the HTML5 fetch API but it's a bit of work.
