### ISSUE TITLE
[Feature Request] Export workspace without environments

### ISSUE THREAD

**Issue by ChangeTheCode** [getinsomnia/insomnia#1418]
**[Feature Request]**
I would to like to have a function to export a workspace / collection without my environments. 

Now maybe little bit more explanation for this feature.

If I use insomnia i have in each environments secrets but I store my insomnia in a git like my source code. In this case I have several benefits 
1. My test collection has all request which i need for the current code base
2. I have a history of my changes (I know to compare this json is a hard job but it's better than not having anything)

So but now I don't won't to push my secrets to git. First solution which I see now is do it every time by hand (remove before commit)

**Comment by gschier** [comment]
You can do this by creating "Private Environment"

<img width="373" alt="image" src="https://user-images.githubusercontent.com/587576/56009944-9fb54500-5caf-11e9-81f3-e7d8566133ff.png">

**Comment by platform-kit** [comment]
This is actually pretty crucial to collaborative use, no?

**Comment by ChangeTheCode** [comment]
I checked out what @gschier  has mentioned (sorry I forgot to answer) and it works fine. Like he say, insomnia is asking you if you want to include your private environments. 👍.

So it is totally fine that this ticket is closed.
