### ISSUE TITLE
[Bug] Hover request url overflow with textbox

### ISSUE THREAD

**Issue by nicktunac** [getinsomnia/insomnia#1419]
- Insomnia Version: 
![image](https://user-images.githubusercontent.com/7882308/55148595-778ff700-5183-11e9-927c-933866d40988.png)

- Operating System: Windows 10

## Details

![image](https://user-images.githubusercontent.com/7882308/55148568-6cd56200-5183-11e9-8ba9-45898b5fff49.png)

When checking for the previous requests, and hovering the URL, if the URL is long. It'll not be readable.

**Comment by develohpanda** [comment]
Hey @gschier, I've set up my local env and can take a look at this bug. :)

**Comment by gschier** [comment]
Awesome, thanks @develohpanda !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicktunac** [comment]
Thanks @develohpanda
