### ISSUE TITLE
[Bug] – Typo: PTCH insted PATCH

### ISSUE THREAD

**Issue by helioalb** [getinsomnia/insomnia#1420]
- Insomnia Version: 6.3.2 (6.3.2.2588)
- Operating System: macOS Mojave 10.14.3 (18D109)

## Details

![typo](https://user-images.githubusercontent.com/349951/55171674-8f518600-5157-11e9-912f-a5add0b0a66b.png)

**Comment by gschier** [comment]
Method names are intentionally truncated in the sidebar to a maximum of 4 characters so they don't take up too much space. For example, `DELETE` will become `DEL` and `OPTIONS` will become `OPT`.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/587576/55172733-e43dce00-5150-11e9-9f82-c1123e452235.png">
