### ISSUE TITLE
[Feature Request] JSON to Form-Encoded HTTP POST

### ISSUE THREAD

**Issue by mcnemesis** [getinsomnia/insomnia#1424]
- Insomnia Version: 6.2.3
- Operating System: Win10

## Details

In situations where you (already) have your payload encoded as JSON, it would be great to be able to merely paste in the JSON, and have the option to tell insomnia to post it as a key:value collection that's Form or URL Encoded for example.

**Comment by brendano86** [comment]
Today when switching from JSON to form based, it puts the full JSON blob in the first item.  Would be nice if it did a key/value match instead
