### ISSUE TITLE
[Bug] Insomnia takes 99% of CPU

### ISSUE THREAD

**Issue by pinggi** [getinsomnia/insomnia#1426]
- Insomnia Version: 6.3.2
- Operating System: Win 10

## Details

1. A rest service in a debug mode
2. Insomnia sends a request
3. The rest service is stopped at a break point
4. Insomnia takes 99% of cpu, the laptop starts overheating, the fan is noisy, the cpu throttles, everything is slow and unusable!

This happens when Insomnia is maximized on 4K display.
When it is minimized, it's ok and Insomnia doesn't take so much cpu.
During the debugging (when the service is stopped at a break point) Insomnia shows animation with spent time...
![image](https://user-images.githubusercontent.com/18471834/55564385-11aded00-56f8-11e9-8872-07b7be1a300b.png)
...which could be the reason why the content has to be refreshed and why it takes so much cpu, but it is strange since it also uses GPU and I don't think the GPU wouldn't manage it. I don't have any issue with other apps.

Processes when it happens:
![image](https://user-images.githubusercontent.com/18471834/55564705-c7793b80-56f8-11e9-9180-c43c0f51655e.png)

CPU when it happens:
![image](https://user-images.githubusercontent.com/18471834/55564770-ee377200-56f8-11e9-8cf9-1a1497707327.png)

CPU when it happens and Insomnia is minimized:
![image](https://user-images.githubusercontent.com/18471834/55564807-04ddc900-56f9-11e9-96b8-caff93869366.png)

**Comment by gschier** [comment]
Hmm, that's strange. Well the spinning icon uses a CSS animation which would be GPU-accelerated. I can't seem to reproduce the problem on Mac though.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/587576/56009824-26b5ed80-5caf-11e9-991c-da3ae0945b40.png">

Can you provide your CPU/GPU models?

**Comment by pinggi** [comment]
The models are:
CPU: i7-8650U
GPU: Intel(R) UHD Graphics 620

**Comment by gschier** [comment]
@pinggi can you try starting the app from the command line with the `--disable-gpu` flag?

**Comment by pinggi** [comment]
The flag really helps 👍 

The first line is without the flag and the second one is with it. The graphs are in order: CPU, Commit, Memory, I/O, Network, GPU.
![image](https://user-images.githubusercontent.com/18471834/57313810-9ffb0180-70f0-11e9-8e3e-4032a81822cb.png)

You can see that CPU & GPU goes down with the flag. I can use it as a workaround and start Insomnia always with the flag.

**Comment by gschier** [comment]
Awesome! I'm going to consider this one "fixed" for now then unless it becomes a problem for more users. It seems like it may resolve itself in a future ElectronJS update.

**Comment by Wim-De-Clercq** [comment]
I (and my colleagues) also used to have this issue of 100% cpu while waiting for a request.
While it is better now, there still is a 5-10% cpu difference with the `--disable-gpu` flag. 
If you debug your applications a lot, i think it's still better to disable it.

Intel Core i7-6820HQ
Intel Corporation HD Graphics 530
