### ISSUE TITLE
How to remove double quotes from HTTP response body in environment variable?

### ISSUE THREAD

**Issue by mohanjoyappa** [getinsomnia/insomnia#1428]
- Insomnia Version: 6.3.2
- Operating System: Win 7

## Details

I am trying to use environment variable to capture I previous request's response body  and passing that  response to  my next request. My first request response produces id as  "sampleid"  (response contains double quotes)

Is there any way for me to strip the double quotes so that environment variable stores it as sampleid instead of as "Sampleid"

Example

Request1 : POST http://someurl...../
Response "I-12-Ihhyt-12"

Request 2
POST http://someurl/{id}/remainingurl

I am storing ID as env variable 

Constructed URL for Request 2 comes as http://someurl/%22I-12-Ihhyt-12%22/remainingurl instead of http://someurl/I-12-Ihhyt-12/remainingurl

is there any way to apply substring or similar methods to play with environment variables?

**Comment by gschier** [comment]
Yes, Insomnia variables are just UI on top of Nunjucks template variables. If you enable Nunjucks power user mode in settings you'll be able to see the raw Nunjucks syntax and apply a substring or replace filter on your variable. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mohanjoyappa** [comment]
Excellent. Thank you.

**Comment by lowysoinomed** [comment]
@mohanjoyappa, @gschier  can you share how it solved? 
I have the same problem
![image](https://user-images.githubusercontent.com/71353078/112873503-15329f80-9098-11eb-84ec-ba09bdafe104.png)

![image](https://user-images.githubusercontent.com/71353078/112873569-2e3b5080-9098-11eb-9e92-f2e09baf9946.png)

![image](https://user-images.githubusercontent.com/71353078/112873599-3a271280-9098-11eb-9e20-b802c070766a.png)

**Comment by fernandolisboa** [comment]
@lowysoinomed this solution worked for me!

{{ token.slice(1, -1) }}

https://stackoverflow.com/questions/47881101/is-there-any-way-to-get-a-substring-from-a-string-in-nunjucks-templating-languag

**Comment by lowysoinomed** [comment]
Ôppa @fernandolisboa!!! Thanks for the tip, man! Resolveu certinho!
