### ISSUE TITLE
[Question] 32bit in documentation's category "Installation"

### ISSUE THREAD

**Issue by spider4216** [getinsomnia/insomnia#1431]
The main problem is: documentation's category "[Installation](https://support.insomnia.rest/article/23-installation)" doesn't have any information about 32bit and 64bit in Linux section. 

According to manual I tried to install insomnia on my 32bit pc via snap, but it didn't run. It took some times until I realized that very old version of insomnia from edge channel was used by snap

`snap info insomnia`

```
name:      insomnia
summary:   Insomnia REST Client
...
channels:
  stable:    –                      
  candidate: –                      
  beta:      –                      
  edge:      0.1 2017-11-20 (8) 4kB devmode
```

A few times latter I found documentation's section in chapter "[Freqently Asked Questions](https://support.insomnia.rest/article/48-frequently-asked-questions)"

```
Does Insomnia provide 32-bit binaries?
At this time, Insomnia is 64-bit only.
```
Can you put information about 32bit and 64bit in documentation's Installation chapter at Linux section? Thank you!

**Comment by gschier** [comment]
I appreciate the feedback and I've added a note to the Troubleshooting section 🥇
