### ISSUE TITLE
Disable Autosave

### ISSUE THREAD

**Issue by ferronrsmith** [getinsomnia/insomnia#1434]
Sometimes I want to run a quick test without actually saving the changes. Is there a way to disable the auto-save feature ? Thanks

**Comment by gschier** [comment]
No, There's no way to disable auto save at the moment

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ferronrsmith** [comment]
That’s a bummer, it’s nice at times to have it, but other times it’s annoying. It forces you to use environments even for simple tests just to avoid overwriting existing requests. Is this something that can be added ? Either by a plug-in or to the settings menu ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gschier** [comment]
There's an issue over here that has a bit of a discussion on it https://github.com/getinsomnia/insomnia/issues/1003

I'm going to close this one as a duplicate
