### ISSUE TITLE
[Help] unable install plugun

### ISSUE THREAD

**Issue by parasuramln** [getinsomnia/insomnia#1435]
npm i insomnia-plugin-validator npm error: Command failed: "C:\Users\z003s16f\AppData\Local\insomnia\app-6.3.2\Insomnia.exe" --no-deprecation C:\Users\z003s16f\AppData\Local\insomnia\app-6.3.2\resources\bin\yarn-standalone.js info npm i insomnia-plugin-validator --json
{"type":"error","data":"Too many arguments, maximum of 2."}

**Comment by gschier** [comment]
What did you enter into the plugin field of insomnia?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gschier** [comment]
Going to close this one as it looks like a user error.

From the message you posted, it looks like you entered `npm i insomnia-plugin-validator` instead of `insomnia-plugin-validator` into Insomnia
