### ISSUE TITLE
[Bug] Generate Code for Ruby is not requiring the OpenSSL library when needed

### ISSUE THREAD

**Issue by dcatt-haiku** [getinsomnia/insomnia#1438]
- Insomnia Version: 6.3.2
- Operating System: Mac OS 10.14

**Steps to Reproduce**
1. create a new GET request for https://www.example.com/
2. **Generate Code** for Ruby
3. observe that **require 'openssl'** is not included in the generated code
4. execute generated Ruby code
5. observe an exception for **NameError: uninitialized constant OpenSSL** is raised

_code that is currently generated by the latest client..._
```
require 'uri'
require 'net/http'

url = URI("https://www.example.com/")

http = Net::HTTP.new(url.host, url.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE

request = Net::HTTP::Get.new(url)

response = http.request(request)
puts response.read_body
```

**Comment by gschier** [comment]
Insomnia uses the [`httpsnippet`](https://github.com/Kong/httpsnippet/issues) library for code generation so this bug report should be directed there.

**Comment by gschier** [comment]
Should be fixed now
