### ISSUE TITLE
[Improvement] Warn about invalid environment variable names

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#144]
Nunjucks does not allow `-` in variable names. A common mistake users make is to name variables like `my-variable` and try to use it as `{{ my-variable }}`. However, Nunjucks interprets this as "my subtract variable" and causes confusion.

Solution: Show warning in environment editor when a key of the JSON contains characters that are not valid in Nunjucks. 

Ideally, this could mark the error inline using Codemirror, but would probably be fine as a global warning (above or below the editor) to start.

**Comment by Smashman** [comment]
I came up against this exact issue just now and came here to report the issue.

Please do implement this warning!
