### ISSUE TITLE
[Feature Request] Default Sync Behaviour

### ISSUE THREAD

**Issue by GrayedFox** [getinsomnia/insomnia#1440]
- Insomnia Version: 6.3.2
- Operating System: Windows 10/Ubuntu 18.04LTS

## User Story

As an Insomnia shared collection user, I would like to set a default sync behaviour, so that I don't have to set it each time I open a collection for the first time on a new machine.

**Must Have**
- I can set a default sync behaviour that is tied to my account so that signing in remembers my default sync behaviour preferences (account)

**Nice to Have**
- I can set a default sync behaviour per team, which will be applied to all existing and newly created collections for this team, so that team members can change their local sync behaviour but this won't overwrite the team's defaults (team)

## Background

This thing is, I always set the same settings: manual sync, don't sync cookies or SSL certs. It would be great to not have to tell my team members to do this every time I hire a developer or tester, or have to do it myself for each OS I have installed on each machine!

Keep up the great work.

**Comment by gschier** [comment]
Hi @GrayedFox!

The sync behavior is about to undergo a major change which will address this. In summary, sync will be transitioning to a more Git-like workflow, favoring manual sync over automatic sync. This will give teams much more control over how and what gets synced with team members. I'll leave a few screenshots below of what it will look like.

![](https://user-images.githubusercontent.com/587576/56328740-31e89d80-6135-11e9-98a7-88c6c77016da.png)

![](https://user-images.githubusercontent.com/587576/56328753-46c53100-6135-11e9-8540-710a4fcfb01b.png)

![](https://user-images.githubusercontent.com/587576/56328759-4fb60280-6135-11e9-9c6d-208119f1a0b7.png)

**Comment by GrayedFox** [comment]
Awesome! Thank you kindly for the sneak preview :+1:

**Comment by gschier** [comment]
You can use it now by enabling the beta at the bottom of the app preferences screen. 

Here's a link to the docs as well: https://support.insomnia.rest/article/67-version-control
