### ISSUE TITLE
Built-in URI encoding function

### ISSUE THREAD

**Issue by danizen** [getinsomnia/insomnia#1445]
- Insomnia Version: 6.3.2 (Shell 3.04)
- Operating System: Windows 10 with Node 10.2.0)

## Desired Behavior

If a variable is inserted in the Path of a request, it should be an option on the dialog  for the variable to URI encode the variable or not.  Another option would be to have a `uri_encode` function plugin built-in to insomnia.

## Actual Behavior

When a variable is inserted into the Path of a request, it is not encoded.

## Motivating example

The semantic web application Cedar, from Stanford's metadata center, uses several microservices.  This issue was encountered when attempting to pass `folder_id` as an argument to the folder contents API - see https://resource.metadatacenter.org/api/#!/Folders/get_folders_folder_id_contents

## Workaround

I've created, and tested briefly the following plugin - https://github.com/danizen/insomnia-plugin-encoder.   It works OK, but it would be better to have the option for encoding a Variable or not when it appears in the Request URL, because the UI is then clearer about where the encoded portion of the URL comes from.

## Related Issues

#417 is related, but since the "/" character in the path would need to be encoded as well, it is not a complete solution.

**Comment by Peter-Optiway** [comment]
This would be nice, I'm having the problem above, i get a value from a request that i need to append to a url, but it contains a / making the uri invalid.
Adding a checkbox on the response body attribute to uri encode would solve the problem.
Adding a tag like base64 encode, would not solve the issue as you can't nest tag.

**Comment by ad-si** [comment]
Boy how I hate those stupid auto-closing bots.
Currently I need to insert tokens in XML documents, and this would be quite helpful!
