### ISSUE TITLE
[Bug] - Error: Invalid export format dataStr. Must be "json" or "yaml"

### ISSUE THREAD

**Issue by ypxio** [getinsomnia/insomnia#1447]
- Insomnia Version: Version 6.4.0 (6.4.0.2712)
- Operating System: macOS Sierra (Version 10.12.6)

## Details

When try to export All Workspaces, this error appear. Only works for export to `.yaml` but not for `.json`

![image](https://user-images.githubusercontent.com/1691373/56562639-0c93dd80-65d4-11e9-8db5-ec500816b5da.png)

**Comment by gschier** [comment]
I'll take a look ASAP

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gschier** [comment]
A fix will be out in the next release within the next 24 hours

**Comment by gschier** [comment]
New release is live now: https://insomnia.rest/changelog/6.4.1

**Comment by ypxio** [comment]
Great! thank you for the great work @gschier!
