### ISSUE TITLE
[Bug] OAuth2 Panel not working correctly

### ISSUE THREAD

**Issue by michael-82** [getinsomnia/insomnia#1449]
- Insomnia Version: v6.4.0
- Operating System: ubuntu 19.04

## Details

When trying to change the Grant Type on the OAuth2 Tab, all options are visible in the selectbox, but no matter what I choose, it stays on "Authorization Code". Same when I try to uncheck the "Enabled" Checkbox - nothing happens.

I downloaded 6.3.2 again, and there it was still working.

**Comment by rbrianhazzard** [comment]
Seeing the same issue on Windows 7 - I can't change any of the dropdown / checkbox fields on the OAuth 2 tab. Instead of "Authorization Code", I am seeing "Client Credentials" which is what i had selected prior to upgrading. "Refresh Token" still works for me when passing a valid Access Token URL, Client ID + Client secret (again, using Client Credentials).

**Comment by pcfleischer** [comment]
Same issue for me on mac anything i try to do in oauth authorization dissappears or does not take effect. The same issue exists for both OAuth 1.0 and 2.0

**Comment by gschier** [comment]
I'll get a fix out for this ASAP

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gschier** [comment]
I'll ship a point release within the next 24 hours

**Comment by gschier** [comment]
New release is live now: https://insomnia.rest/changelog/6.4.1

**Comment by dsutphin** [comment]
I am still having this problem with OAuth 1.0 with Insomnia 6.4.1 installed via brew on Mac. OAuth 2.0 does not appear to have this issue.
<img width="554" alt="Screen Shot 2019-04-29 at 11 42 36 AM" src="https://user-images.githubusercontent.com/16996439/56908449-4e110680-6a74-11e9-9ca9-d6ff8549f8f5.png">

**Comment by gschier** [comment]
OAuth 1 was exhibiting the same problem and has been fixed as well but not released. It will be included in a release later today

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gschier** [comment]
Fix is out now in 6.4.2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
