### ISSUE TITLE
[Bug] 6.4.0 exceptionally slow

### ISSUE THREAD

**Issue by abdullahsari** [getinsomnia/insomnia#1450]
- Insomnia Version: 6.4.0
- Operating System: macOS Mojave 10.14.4

## Details

After the automatic update today, I immediately noticed a severe performance hit with the API client. Expanding/collapsing folders take almost half a second and editing is a nightmare now since the changes do not appear instantly. 6.3.2 was working just fine without any issues, using a MBP mid 2015 model. 
I am reverting to the previous release for the moment.

Mouse clicks happen when the left border turns purple
![Folders](https://i.gyazo.com/c4c4115338944e7826bd8d56ba83570a.gif)

I am spamming the A and S keys
![Key spam](https://i.gyazo.com/85e58fb5976a508b0f26531717dd6f7f.gif)

**Comment by gschier** [comment]
Can you let me know roughly how many requests you have? Also, can you try it again on a fresh workspace to see if having fewer requests helps?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rafaelrenanpacheco** [comment]
I had the same issue in a workspace with 91 requests. A temporary fix was to hit `Clear All Responses` responses in the following dialog:

![image](https://user-images.githubusercontent.com/12160864/56611454-3656ff80-65e8-11e9-8a7a-fb1da0b979db.png)

It took around 1-2 minutes to finish this job at 100% CPU usage for the insomnia thread. After that the workspace became responsive again.

**Comment by gschier** [comment]
I'm 90% sure I've identified the regression so I'll have a fix out soon

**Comment by gschier** [comment]
New release is live now: https://insomnia.rest/changelog/6.4.1
