### ISSUE TITLE
[Bug] EDN Formatting, Optional commas highlighted as errors

### ISSUE THREAD

**Issue by kernelp4nic** [getinsomnia/insomnia#1451]
- Insomnia Version: `Version 6.4.0 (6.4.0.2712)`
- Operating System: `macOS Mojave 10.14.4`

## Details

Commas in EDN are highlighted as errors in the latest release:

![image](https://user-images.githubusercontent.com/519481/56581574-a4c99c80-65ab-11e9-81a9-62fe8598b84d.png)

Commas are optional in EDN notation, from docs:

> Elements are generally separated by whitespace. Whitespace, other than within strings, is not otherwise significant, nor need redundant whitespace be preserved during transmissions. Commas , are also considered whitespace, other than within strings.

This wasn't happening on previous releases.

**Comment by gschier** [comment]
It looks like this happened when upgrading Codemirror. 

I can reproduce this on the official Codemirror [Clojure mode demo](https://codemirror.net/mode/clojure/index.html). It seems like [this may be the patch](https://github.com/codemirror/CodeMirror/pull/5582) that introduced it if you'd like to leave a comment there.
