### ISSUE TITLE
[Bug]Click Preference, then Insomnia show a white page

### ISSUE THREAD

**Issue by 317174106** [getinsomnia/insomnia#1453]
- Insomnia Version: 6.4.1
- Operating System: Win7 64

## Details

Click Preference, then Insomnia show a white page.
And the only way is close Insomnia and restart it. I can't open Preference.

![image](https://user-images.githubusercontent.com/25921468/56631052-2db50680-6686-11e9-81b8-9086f21e7084.png)

**Comment by gschier** [comment]
Can you check View > Toggle DevTools > Console to see if any errors come up when you do this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 317174106** [comment]
> Can you check View > Toggle DevTools > Console to see if any errors come up when you do this?
> 
> Sent with [GitHawk](http://githawk.com)

First I open dev tools , then I click Perference, the dev tools was disconnected as below.

I tried to uninstall Insomnia, delete AppData, then reinstall it, but the problem still exists.

![image](https://user-images.githubusercontent.com/25921468/56638796-a2496e80-66a1-11e9-94a5-b0e530004a46.png)

**Comment by runofthemill** [comment]
Having the same issue, but on macOS.

Insomnia 6.4.1.2725
macOS 10.14.4

Screen recording: https://www.dropbox.com/s/6vx8t9jse2w49b6/insomnia-bug.mov?dl=0

**Comment by gschier** [comment]
That's so strange that DevTools would disconnect when opening preferences. 

@317174106 does Help > About work for you?

@runofthemill do you also see the same DevTools disconnect error?

**Comment by runofthemill** [comment]
Yep - you can see it disconnecting at the end of the clip I uploaded!

**Comment by gschier** [comment]
Wow, sorry I didn't even notice your screen recording link (long day 🤪)

I've only ever seen the DevTools disconnect when there has been a problem linking the native libcurl  module. Can you try running the following command from within the console to see if it triggers  the same issue?

```js
require('insomnia-libcurl').Curl.getVersion()
```

**Comment by 317174106** [comment]
@gschier Help --> About is ok

![image](https://user-images.githubusercontent.com/25921468/56714631-fae33f00-6767-11e9-817e-ec60dc566b09.png)

**Comment by 317174106** [comment]
@gschier Help --> About is ok, and the command won't trigger the same issue.

![image](https://user-images.githubusercontent.com/25921468/56714849-9e345400-6768-11e9-8377-e6a8925b7d79.png)

**Comment by leweohlsen** [comment]
Experiencing the same problem with Insomnia 6.4.1.2725 on macOS 10.14.4. DevTools keep disconnecting when the Preferences page flips to white, so I cannot begin to debug the issue.

**Comment by gschier** [comment]
Okay, one more thing to try:

In View > Toggle DevTools > Console, can you try running the following?

```js
require('font-manager').getAvailableFonts(f => console.log('FONTS', f));
```

**Comment by runofthemill** [comment]
No problem with the libcurl command!

```js
require('font-manager');
```

works without a problem.

```js
require('font-manager').getAvailableFonts(f => console.log('FONTS', f));
```

causes a crash:

<img width="567" alt="Screen Shot 2019-04-25 at 6 21 17 PM" src="https://user-images.githubusercontent.com/8418440/56777527-f5e1b800-6786-11e9-840e-7bb914338b87.png">

**Comment by gschier** [comment]
Dang, it looks like we're going to have to make the font manager only available when it's supported. I'm not quite sure why it wouldn't work on Mac since it works on my Mac and Mac is a fairly stable platform. Anyway...

Since I can't reproduce it over here, can you look at the module and see if there's any way to conditionally check if it's going to crash without actually crashing it? ie. figure out a way to hide the feature if it's not supported.

**Comment by 317174106** [comment]
@gschier the second command causes a crash. But I am on win7

**Comment by 317174106** [comment]
Any solution?

**Comment by runofthemill** [comment]
As I have a number of custom fonts installed, it seems likely it's the same issue noted here: https://github.com/foliojs/font-manager/issues/20

I'm not versed in TS dev, but as a test I dropped in https://www.npmjs.com/package/font-scanner linked from https://github.com/foliojs/font-manager/issues/20#issuecomment-445905519, created `packages/insomnia-app/flow-typed/font-scanner.js` with the following content:

```js
// @flow

declare module 'font-scanner' {
  declare module.exports: *;
}
```

and updated the import in `packages/insomnia-app/app/ui/components/settings/general.js`. The preferences pane loaded and did not crash, but no fonts showed as available under `Interface Font` or `Text EditorFont` - just the option "-- System Default --", and the console log returned `null`:

![Screen_Shot_2019-04-25_at_10_47_31_PM](https://user-images.githubusercontent.com/8418440/56786006-37d12500-67ac-11e9-9344-855241d395ed.png)

**Comment by gschier** [comment]
You saved the day @runofthemill! That's all I needed.

**Comment by ylvare** [comment]
Hi, I still have this issue if I download from https://insomnia.rest/download/ or brew cask install insomnia (mac)

**Comment by gschier** [comment]
The Fox is not released yet

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ylvare** [comment]
I understand. Any idea on when it will be?

**Comment by gschier** [comment]
Out now!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ylvare** [comment]
:)

Den tis 30 apr. 2019 00:00Gregory Schier <notifications@github.com> skrev:

**Comment by alannaidon** [comment]
Hi!

I just installed Insomnia on Fedore with Snap and I'm having same problem.


This is the **About** screen
![image](https://user-images.githubusercontent.com/13774879/100479132-0cbb5f80-30cc-11eb-9ccc-c0d5912c3445.png)

**Comment by VictorTelcoBrain** [comment]
I am facing the same issue as @alannaidon on Fedora 33.

**Comment by Wulfheart** [comment]
Manjaro too.

**Comment by dimitropoulos** [comment]
@Wulfheart what version of insomnia are you on, and do you have reproduction steps?

**Comment by Wulfheart** [comment]
Sorry for not providing more specific steps. I will get them soon.
