### ISSUE TITLE
[Bug] Menu is unreadable

### ISSUE THREAD

**Issue by torakiki** [getinsomnia/insomnia#1454]
- Insomnia Version: 6.4.1
- Operating System: Linux Mint 19.1 Cinnamon 4.0.10

## Details
The menu is unreadable:
![image](https://user-images.githubusercontent.com/3884479/56642818-98f7dc00-6678-11e9-97a2-83937624f1a0.png)

See the difference between Insomnia and Nemo:
![image](https://user-images.githubusercontent.com/3884479/56643008-073c9e80-6679-11e9-90c5-f7a264ef5718.png)

**Comment by gschier** [comment]
Was this working before the last update?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by torakiki** [comment]
No, I was using version 6.3.something and it was the same

Il giorno mer 24 apr 2019 alle ore 19:11 Gregory Schier <
notifications@github.com> ha scritto:

**Comment by gschier** [comment]
I'm on a different monitor now and I can now see the black font on the dark gray background. At first I thought the menu items weren't drawing at all.

Do you have any other Electron-based apps you can try this on? I don't think Electron actually lets you control the color of that menu background/font.

**Comment by torakiki** [comment]
![image](https://user-images.githubusercontent.com/3884479/56692170-e2304600-66e1-11e9-996a-423067e46a66.png)
This is based on Electron 4.1.3. It's the menu brought up by `electron-debug` when in development if I'm not mistaken and I didn't set any color or anything and it's like menus in all the other apps in the system

**Comment by gschier** [comment]
It might be fixed then by bumping Insomnia to Electron 4.x. Looks like it's been a common issue for a while:  https://github.com/electron/electron/issues/15194

I ran intro build issues trying to upgrade Electron last week but I'll give it another shot for the next release. There's some more motivation to do so now if it fixes this bug 😄

**Comment by gschier** [comment]
Going to as the same question from #1411. Does this happen on all Insomnia themes?

**Comment by torakiki** [comment]
Yes, tried all of them with the same result.

**Comment by ToX82** [comment]
Hi, I am having the same trouble with ubuntu 19.04 here. Not sure if it's helpful, but when the window is inactive I can actually read the menu items :D

Active window
![active](https://user-images.githubusercontent.com/659492/58457085-215d1700-8126-11e9-96e8-24cf65ef85d8.png)

Inactive window
![inactive](https://user-images.githubusercontent.com/659492/58457087-215d1700-8126-11e9-87d0-34baa890abc7.png)

**Comment by torakiki** [comment]
Updated to 7.0.1 and the issue is gone
