### ISSUE TITLE
[Bug] Using Base64 encode in header not working after update

### ISSUE THREAD

**Issue by soderluk** [getinsomnia/insomnia#1455]
- Insomnia Version: Version 6.4.1
- Operating System: Ubuntu 18.04

## Details
Insomnia was updated today (2019-04-25) at some point automatically, and now that I try to use my existing request, including a header with the function base64 encode, I get an error, and the header value is empty when posting:
![image](https://user-images.githubusercontent.com/6086071/56737937-33891580-6774-11e9-8ad9-a27edd7c54c8.png)
![image](https://user-images.githubusercontent.com/6086071/56738118-9d092400-6774-11e9-867c-c5d339964f54.png)

The variable `basic_auth` is in my environment, and is like so:
`"basic_auth": "{{ client_id  }}:{{ client_secret  }}"`
I double checked that the client_id and client_secret are correctly displayed in the variables.

So this seems to be a bug in the base64 encoding functionality.

**Comment by gschier** [comment]
Ah, it looks like there was a breaking change in the last release for this tag (sorry about that). You'll need to switch the _Kind_ selection to "Normal" and move your `basic_auth` variable into the _Value_ parameter.

**Comment by valdetero** [comment]
I tried doing the above and it still couldn't resolve the error. I had to remove and re-add every encoding tag that I had.

**Comment by gschier** [comment]
Thanks for letting me know. This breaking API change definitely should not have ended up in production but it's a bit late now to fix it, unfortunately.
