### ISSUE TITLE
[Feature Request] Quickly create new request from URL property in response body

### ISSUE THREAD

**Issue by scottmmmm** [getinsomnia/insomnia#1457]
- Insomnia Version: 6.4.1
- Operating System: Ubuntu 16.04 LTS

## Details

When working with REST APIs which make use of lots of hypermedia, it'd be very useful to allow new requests to be created by clicking on properties on a response body which contain URLs.

At the moment, clicking on a property whose value is a URL causes the URL to be opened in my web browser. It'd be much better if clicking on a URL caused a new request to be created at that URL.

The request chaining features of Insomnia are great for working with APIs which make use of HATEOAS - since Tags can easily extract the URLs from a previous request. But browsing such an API in Insomnia would be better served by clicking the URLs directly

Here's an example of the kind of API I'm talking about - note all the links.

![insomnia-response-with-hyperlinks](https://user-images.githubusercontent.com/3959288/56743743-17cf4080-676f-11e9-8047-26dee60163d6.png)
.

**Comment by rafaelrenanpacheco** [comment]
Duplicated.

Some issues were opened and got stalled about this: #662 and #1332

**Comment by scottmmmm** [comment]
Thanks for letting me know. I'll close this issue and lend my support to those ones. It'd be great to have better HATEOAS support in Insonia.

**Comment by scottmmmm** [comment]
Actually I'll reopen this, as the other feature request has been closed by the stale bot.

**Comment by gschier** [comment]
There's actually a still-open issue over here: https://github.com/getinsomnia/insomnia/issues/874

Please feel free to participate in that discussion.
