### ISSUE TITLE
[Question] Possible to use semicolons instead of question mark and ampersands in query string?

### ISSUE THREAD

**Issue by zissakos** [getinsomnia/insomnia#1459]
It seems I cannot change the default behaviour of how the query string is being created.

Insomnia creates this:
`blabla/faqu/subscriptionapi/rest/subscription?param1=value1&param2=value2`

But I want this:
`blabla/faqu/subscriptionapi/rest/subscription;param1=value1;param2=value2`

is that possible?
I added the params in the "Query" tab, was that wrong?

**Comment by gschier** [comment]
Hi @zissakos, thanks for reporting your issue. 

I have never seen that kind of format used before. To my knowledge, it's not part of any common web standard (please correct me if I'm wrong) which is why it's not supported by Insomnia,

**Comment by zissakos** [comment]
The developer of our REST service told me this:
_"The URLs of rest services are created using Matrix Parameters and that is the reason semicolons “;”  are mandatory in the URLs.
“?” and “&” are used in case of Query Parameters, which is not used in our URLs."_

What do you think of this?

**Comment by gschier** [comment]
Matrix parameters seems to be specific to JAX-RS API Java framework and not an actual web standard. If they translated more closely to query parameters then it might be easier, but there is a key difference, which is that there can be multiple instances of matrix parameters.

For example, a URL could like like the one you provided:

```
rest/subscription;param1=value1;param2=value2
```

Or there could be any number of matrix instances like this:

```
rest/subscription;param1=value1;param2=value2/another/foo=bar;baz=qux/end
```
