### ISSUE TITLE
[Improvement] Setting to disable tracking

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#146]
Right now, Insomnia sends data to Google Analytics. Insomnia should allow the user to opt-out of these things via a setting.

**Comment by gschier** [comment]
@marmotz you still going to take a crack at this? Sorry, I removed everyone (including you) from the org after making it open source. Wasn't implying anything.

**Comment by marmotz** [comment]
Sorry for my absence but I have some personal problems right now. 
Also, I'm changing ISPs so I no longer have internet.
I keep you informed when I could get back on insomnia.
Sorry

**Comment by matthewshirley** [comment]
I'll take on this one. (Y)

**Comment by gschier** [comment]
Woo! Sounds good @matthewshirley

**Comment by gschier** [comment]
No problem @marmotz. I hope is well, and I wish you the best! 😄

**Comment by matthewshirley** [comment]
@gschier I've created the pull request. 😄 I'll keep an eye out for your feedback.

**Comment by gschier** [comment]
Thanks @matthewshirley!
