### ISSUE TITLE
[Feature Request] Open new request in editor without a modal

### ISSUE THREAD

**Issue by avin-kavish** [getinsomnia/insomnia#1464]
Currently, hitting `Ctrl + N` opens a modal dialog, prompting for request name, method and body type. These are all optional and configurable in the editor. It would be nice to have the new request just pop up in the editor with default values and allow the user to change whatever values they see fit.
This behaviour is currently implemented in VS Code. Creating a new file in explorer, adds a file in the folder explorer with focus to name it. Hitting `Ctrl + N` opens a new blank file in the editor without any additional prompts.

### Why I think this a better workflow
The current behaviour makes me think of a name for the request first which is a distraction from the primary task of writing the request. Usually a file is named after contents are added to it. Because the file name is based on the contents. I don't know what to name a request till I write it, change it, change it again, change it again and change it again and decide to open a new request.

**Comment by avin-kavish** [comment]
I got an idea: preserve current behaviour and add a new keyboard shortcut,  i.e. Quick Create Action which creates a new request without the modal dialog prompt

**Comment by gschier** [comment]
I like that idea

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
