### ISSUE TITLE
[Feature Request] CPU Render

### ISSUE THREAD

**Issue by pwrigshi** [getinsomnia/insomnia#1465]
This is related to GPU render bug (https://github.com/getinsomnia/insomnia/issues/1316). I have issues also with other apps which use GPU render, e.g. Steam, Discord, Postman, Slack. Some of them have 'disable GPU render' feature (by setting UI option or flag on executable file) which allowed me to use apps normally.

just fyi: got this issue right after one of the Win10 updates. but since Linux user also experience it, it doesn't look like it is platform-dependent.

**Comment by pwrigshi** [comment]
oops, did not know that this app has also --disable-gpu flag. is this for all electron apps?

**Comment by gschier** [comment]
I just learned about it from your comment! Thanks for teaching me something. After some searching, yes, it seem as though all Electron apps support this flag.

**Comment by hinst** [comment]
--disable-gpu does not work on latest Insomnia version 13
