### ISSUE TITLE
[Question] Delete previously shared and sync workspaces?

### ISSUE THREAD

**Issue by AlexC** [getinsomnia/insomnia#1466]
- Insomnia Version: 6.4.1
- Operating System: Ubuntu 16.04

## Details

Once a workspace has been sync and shared, is it possible to delete it? I've tried setting the sharing settings to private and then deleting the workspace, however it always appears under the "Remote workspaces" section.

**Comment by gschier** [comment]
I have definitely experienced this as well in some cases. The workspace will only be deleted remotely if it's set to automatically sync. If that still doesn't work, feel free to send the name of the workspace to support@insomnia.rest along with your account email and I can delete it from my end.

**Comment by gschier** [comment]
I just realized that my response assumed you were using the default sync mechanism, not the new one. There isn't yet the ability to remove remote projects yet but that'll be out soon.

Going to close this one as I've responded to your email.
