### ISSUE TITLE
Is 6.4.1 a beta version?

### ISSUE THREAD

**Issue by suschizu** [getinsomnia/insomnia#1468]
hey @gschier - I'm a bit confused: on GitHub version 6.4.1 is marked as pre-release but on the website 6.4.1 seems to be a stable version (https://insomnia.rest/changelog/) - could you please help me out - thank you!

**Comment by gschier** [comment]
Oh, thanks for pointing this out. I just forgot to change it. Fixed!

**Comment by suschizu** [comment]
Thank you!
