### ISSUE TITLE
Base64 encoding in JSON body fails in 6.4

### ISSUE THREAD

**Issue by harsman** [getinsomnia/insomnia#1472]
Version 6.4.1
Shell 3.0.4
Node 10.2.0
V8 6.6.346.32
Architecture x64
libcurl/7.57.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.7.0_DEV

- Insomnia Version: 6.4.1
- Operating System: Windows 10

## Details

Base64 encoding part of a JSON request body fails with the unspecific error message "error" in Insomnia 6.4.1.

To reproduce:

Create a new environment
Add variable called "encoded" and set the value to "banana" in this environment.
Create a new POST request with a JSON body. Add the following text:
```json
{
    "encoded": "{% base64 'encode', encoded, '' %}"
}
```
Double click on the purple "Base64 => Encode" button. Notice that the Live preview says "error". If you send the request the base64-encoded value of "banana" (e.g. "") is not sent, but instead "" is sent.

**Comment by harsman** [comment]
Possibly related to #1455

**Comment by gschier** [comment]
Yes, this looks like a duplicate of #1455. Can you try deleting the tag and recreating it?

The new format should now be the following:

```
{% base64 'encode', 'normal', myVariableToEncode %}
```

**Comment by harsman** [comment]
I had actually tried recreating previously, but when I looked at the text I had '' instead of a variable reference, so I reinstalled Insomnia and removed the base64 reference completely and added it again and now it works.
