### ISSUE TITLE
[Bug] Links in deprecation tooltips are opened inside Insomnia

### ISSUE THREAD

**Issue by philippguertler** [getinsomnia/insomnia#1473]
- Insomnia Version: 6.4.2
- Operating System: Arch Linux, using AUR for insomnia

## Details

Clicking a link in a deprecation tooltip will open the link inside Insomnia. I was unable to return to the normal Insomnia interface after that. The only way I found to fix this is to restart Insomnia.

The link should be opened in the default browser instead.

![image](https://user-images.githubusercontent.com/13328856/56961426-0f527d80-6b54-11e9-909e-8d9d5565cb5f.png)

**Comment by gschier** [comment]
Thanks for reporting this one. I didn't even realize there could be links in there. I'll get this fixed.
