### ISSUE TITLE
[Bug] Copy as curl is adding \n literal instead of nextline in json data

### ISSUE THREAD

**Issue by abhinavmall** [getinsomnia/insomnia#1475]
- Insomnia Version: 6.4.2
- Operating System: Windows 10 x64

## Details

Feature "Copy as curl"
Copies to clipboard json data having literal \n if you have beautified json.
Example - 
curl --request POST \
  --url http://google.com/ \
  --header 'content-type: application/json' \
  --data '{\n	"key_1": "value_1",\n	"key_2": "value_2"\n}'

These added \n literal creates problems while parsing json.

**Comment by abhinavmall** [comment]
Same request when created using v6.4.1

curl --request POST \
  --url http://google.com/ \
  --header 'content-type: application/json' \
  --data '{
	"key_1": "value_1",
	"key_2": "value_2"
}'

**Comment by gschier** [comment]
Ah yes, this was a regression from moving back to the official `httpsnippet` library. I have a PR about to be merged over there that I'll make sure gets into the next release: https://github.com/Kong/httpsnippet/pull/102

**Comment by gschier** [comment]
Should be back to normal now
