### ISSUE TITLE
[Bug] Template Tag plugin: can't use quotes in `string`

### ISSUE THREAD

**Issue by jbruni** [getinsomnia/insomnia#1480]
- Insomnia Version: 6.4.2
- Operating System: Windows 10

## Details

You can reproduce the bug in these conditions:
- using a Template Tag plugin
- one of the plugin `args` is of type `string`

Now, try using quotes character `"` in the value for the `string` type argument.

Even though the "Live Preview" shows a valid value, the request JSON body parser throws an error.

Maybe this is a duplicate of #1030, but I am not sure of it.

**Comment by jbruni** [comment]
Hmmm... just found this bug reported as a "warning" in `insomnia-plugin-chance` README:

https://www.npmjs.com/package/insomnia-plugin-chance#warning

**Comment by gschier** [comment]
Yes, it's just the linter warning you that it's invalid JSON.

This is because, under the hood, template tags look like this:

```json
{
  "foo": "{% mytag '"some value"' %}"
}
```

The tag is unaware where it's being used so it has no way of knowing that the double quotes inside of it conflict with the JSON string it's being used within.

**Comment by jbruni** [comment]
I see... It works fine when the template engine renders the JSON body provided to the request..

But... why not also apply some parsing to the JSON before it is provided to the linter?

Instead of having `{% mytag '"some value"' %}` string reaching JSON linter... we could apply `JSON.stringify` on it, so the linter would receive a valid syntax:

```json
{
  "foo": "{% mytag '\"some value\"' %}"
}
```

**Comment by gschier** [comment]
This was fixed here: https://github.com/getinsomnia/insomnia/commit/8adee60c8671291712b8ad33f6bbc1e43c453c16

The response tag will now store the filter value in base64 so the quotes won't interfere
