### ISSUE TITLE
[Feature Request] Display number of array items in response when arrays are collapsed

### ISSUE THREAD

**Issue by mobsoftware** [getinsomnia/insomnia#1482]
- Insomnia Version: 6.4.2
- Operating System: Windows 10

## Details

It would be useful if the preview tab on the right displayed the number of items in the response or when arrays are collapsed show the number of items in the arrow between the square brackets like this "[ 99 ]". This can help validate the expected number of items are returned.

**Comment by gschier** [comment]
My response here will be similar to that on https://github.com/getinsomnia/insomnia/issues/1404#issuecomment-490624622

Currently, code folding is currently done within the CodeMirror text editor itself and has support for many languages and formats.

That being said, if someone wants to take a look and see how difficult it might be to implement, I'm happy to discuss 👍
