### ISSUE TITLE
Your client has issued a malformed or illegal request. That’s all we know.

### ISSUE THREAD

**Issue by bulletinmybeard** [getinsomnia/insomnia#1483]
- Insomnia Version: Version 6.4.2 (6.4.2.2759)
- Operating System: macOS Mojave (10.14.4)

I'm using Insomnia for an API developed in Node.js with the help of Sails.js. After every single deployment to our production system, randomly endpoints are throwing the error **400. That’s an error - Your client has issued a malformed or illegal request. That’s all we know.**.

The failing endpoints are not always the same, and if I compare the local request headers and responses from staging and production, there's no difference to find at all. 

Here's a copy of the request timeline with sensitive information blanked:
```
* Preparing request to http://******/movies
* Using libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Hostname ****** was found in DNS cache
*   Trying *****...
* TCP_NODELAY set
* Connected to ***** (*****) port 80 (#22)

> GET /movies HTTP/1.1
> Host: *****
> User-Agent: insomnia/6.4.2
> x-access-token: ******
> Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY
> Accept: */*
> Content-Length: 25

| --X-INSOMNIA-BOUNDARY--

* We are entirely uploaded and fine
* HTTP 1.0, assume close after body

< HTTP/1.0 400 Bad Request
< Content-Type: text/html; charset=UTF-8
< Referrer-Policy: no-referrer
< Content-Length: 1555
< Date: Tue, 07 May 2019 19:02:46 GMT


* Received 1551 B chunk
* Closing connection 22
```
It's a Google error, at least that's how it's rendered within the response preview in Insomnia, and I'm hosting the API within Google Cloud via Kubernetes.

The only difference between my local development and the deployment on staging or production is the NGINX server in between to upstream the express.js server.

It's probably not an Insomnia issue, but maybe you've experienced something similar and have some tips for me to resolve the issue.

**Comment by gschier** [comment]
Are you sending an empty Multipart form on purpose? That looks suspicious 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bulletinmybeard** [comment]
@gschier Damn, you're right!!!!!

After 16 hours of programming, I didn't notice that. Thank you so much.

Changing it to *No Nody* fixed the issue!!!!!


Cheers

**Comment by bulletinmybeard** [comment]
@gschier Damn, you're right!!!!!

After 16 hours of programming, I didn't notice that. Thank you so much.

Changing it to *No Nody* fixed the issue!!!!!


Cheers

**Comment by gschier** [comment]
Hehe, sometimes you just need another set of eyes 😄

**Comment by bulletinmybeard** [comment]
That is so true :D

The cause of the issue was simply my stupidity by cloning existing endpoints and changing the request method, but not how I want to send the data, damn.

Cheers
