### ISSUE TITLE
[Bug]: Not able to use special keys in environment variables

### ISSUE THREAD

**Issue by soderluk** [getinsomnia/insomnia#1484]
- Insomnia Version: Version 6.5.1
- Operating System: Ubuntu 18.04

This issue is similar to #945, but in regards of being able to use the special keys in the environment variable definitions.

## Details

We're returning JSON-LD data from our APIs, with keys such as `@type`, `@context` and `@id`.
Now I'd like to use the response attribute `@id` from one request as an environment variable, but I get the following error: `Unexpected token @ in JSON at position 412`
I'm using the workaround that was suggested in issue 945, but it doesn't seem to apply in the environment configuration.
![Selection_149](https://user-images.githubusercontent.com/6086071/57368335-9d9db380-7193-11e9-94f8-0b49502e1b9c.png)
![Selection_151](https://user-images.githubusercontent.com/6086071/57368343-a1c9d100-7193-11e9-82cb-ab670892084f.png)
![Selection_152](https://user-images.githubusercontent.com/6086071/57368349-a42c2b00-7193-11e9-9114-d6295967d23f.png)

**Comment by gschier** [comment]
... Since this problem basically only occurs in the response tag, we could also just add some logic to make the filter parameter use base64 (or some other encoding) always

**Comment by gschier** [comment]
Since this basically only happens in the response tag, we could also just update that tag specifically to always encode that parameter in base64 or something similar.

**Comment by gschier** [comment]
... Since this problem basically only occurs in the response tag, we could also just add some logic to make the filter parameter use base64 (or some other encoding) always

**Comment by gschier** [comment]
This is not ideal, but I wonder if we could workaround this by coming up with a special encoding for complicated tag arguments.

For example, we could prefix complex arguments with a special encoding function like this

```
{% response 'body', 'req_abc', '__b64:JFsnQGlkJ10=', 'never' %}
```

This, of course, would break compatibility with stock Nunjucks templating but it would solve the problem.

**Comment by soderluk** [comment]
@gschier: Sorry, I didn't find the existing issue. I tried with the `\"$['@id']\"` both in the popup window and in the `{%%}` string format, but didn't get it to work... I'll continue trying to find a solution for that.
Thanks for your responses!
