### ISSUE TITLE
[Feature Request] show time when request was made

### ISSUE THREAD

**Issue by 4ekki** [getinsomnia/insomnia#1488]
- Insomnia Version: 6.4.2
- Operating System: Windows 10

## Details

This may sound quite stupid, but still =) Sometimes I switch to the Insomnia from some other application, see the response and get confused, did I just send the request and this is fresh response or some outdated one? 
It would be handy to expose the time when the request was made to the response header, something like this: 
![image](https://user-images.githubusercontent.com/38757986/57439136-0ea1a180-724e-11e9-8af9-1a0e2fda0070.png)
![image](https://user-images.githubusercontent.com/38757986/57439417-a56e5e00-724e-11e9-812d-f4dd1f4f8cb9.png)

**Comment by gschier** [comment]
I love this suggestion. What about showing the time in the history menu?

![image](https://user-images.githubusercontent.com/587576/57471084-61805680-7258-11e9-872d-21f8c43fb16d.png)

**Comment by 4ekki** [comment]
Looks great! 
Do you have an idea, how to make the relative one show actual info? Probably, the static timestamp is better since you won't need to re-draw it at all.

**Comment by gschier** [comment]
The relative one has a `title` attribute to show the actual info. It also uses the `<TimeFromNow>` component, which automatically updates the value as time passes.

If we want better access to when a request was sent, I suggest also printing a timestamp at the start of the Timeline.

**Comment by gschier** [comment]
![image](https://user-images.githubusercontent.com/587576/57474251-acea3300-725f-11e9-99ef-e2cfb569e340.png)

**Comment by 4ekki** [comment]
Label in the history menu covers my use-case completely. However, could be useful to add this to the Timeline for other cases.

**Comment by gschier** [comment]
Oh, awesome. And I did add it to the timeline as well. I think it'll be useful there too

**Comment by 4ekki** [comment]
@gschier, neat work on this, thank you!
