### ISSUE TITLE
[Question] Silent installation

### ISSUE THREAD

**Issue by verglor** [getinsomnia/insomnia#1489]
Is it possible to install Insomnia (on Windows) silently without automatically starting ?
I would like to add installation of Insomnia to my unattended setup script.

**Comment by gschier** [comment]
I'm not a Windows user but the Windows version of Insomnia is packaged with Squirrel, which might have a way of doing this. I found a GitHub issue that makes it seem like there is a `--silent` flag you can use https://github.com/Squirrel/Squirrel.Windows/issues/1096

**Comment by verglor** [comment]
It works, thanks !
