### ISSUE TITLE
[Feature Request] Official chocolatey package

### ISSUE THREAD

**Issue by verglor** [getinsomnia/insomnia#1490]
It would be great if there is official and up to date chocolatey package of Insomnia.

**Comment by gschier** [comment]
You are probably aware but I just wanted to follow up quickly and point out (for those who are unaware) that there is an unofficial Chocolatey package already: https://chocolatey.org/packages/insomnia-rest-api-client

It seems to be about a month behind usually, though.

**Comment by verglor** [comment]
I know about this, but it seems quite unmaintanied. Auto-updated package whould be better. However since Insomnia seemlessly self-updates it is not so urgent. Problem may probably arrise when you install old version from choco with database from newer version...

**Comment by Deilan** [comment]
This is not stale, please reopen.
