### ISSUE TITLE
[Bug] Default value in promt dialog

### ISSUE THREAD

**Issue by nike-emea-trade** [getinsomnia/insomnia#1494]
- Insomnia Version: 6.5.1
- Operating System: Windows 10

## Details

When adding a default value in the a prompt, I would expect to still see the prompt screen pop up every time I press the send button. This is however not the case. Moreover, the behavior is pretty inconsistent, sometimes it does show the pop-up with the default value, other times it just does the request with the default value filled in. I didn't yet find any logic in when the popup shows or doesn't show, so this seems like buggy behavior to me.

Could be that I'm missing something ofcourse :)

**Comment by gschier** [comment]
So the prompt tag uses storage to ensure it doesn't prompt multiple times during the same request, even if the tag is rendered more than once. There was a bug in the logic that was causing to store the default value before the request had been sent (eg, when previewing the value).

It was a fairly simple fix though, luckily!
