### ISSUE TITLE
[Feature Request] Simple fullscreen mode (OSX)

### ISSUE THREAD

**Issue by o8e** [getinsomnia/insomnia#1495]
Is it possible to have a "simple" fullscreen mode? Similar to iTerm and VSCode, so you can go into fullscreen and still be able to see and tab between other windows.

**Comment by gschier** [comment]
I'm not sure what you mean by this. Can you please provide more info as to what you're looking for?

**Comment by o8e** [comment]
@gschier I'm not really sure of the actual term, but the applications in my original post all refer to it as "simple fullscreen", which I think just means not using the native fullscreen functionality. It allows the window to occupy the whole screen (on OSX) without opening it in a new desktop. If you're using multiple monitors, going into another desktop on one makes the rest of the monitors go black.

Microsoft/vscode/issues#5344 is the issue where VSCode (finally) implemented this.

iTerm's preferences describe the option as:

```
Native full screen windows
===
If enabled, fullscreen windows will animate into a special desktop, as is typical in macOS 10.7 and later. If disabled, fullscreen windows will instantly go fullscreen without changing desktops.
```
