### ISSUE TITLE
[Feature Request] Timestamp-Function (now) with Offset

### ISSUE THREAD

**Issue by vermgit** [getinsomnia/insomnia#1498]
https://github.com/getinsomnia/insomnia/issues/554 makes a lot of sense and I commented a suggested API there:

This makes a lot of sense when having to pass a time period to a remote service. As far as the API is concerned I suggest to implement something like UNIX' `date` has. If that isn't practical, I'd do something like `-4h`, `+20d12h15m`. With `w` for weeks, `d` for days, `h` for hours, `m` for minutes and `s` for seconds.

**Comment by gschier** [comment]
There is a great plugin [`insomnia-plugin-customtimestamp`](https://www.npmjs.com/package/insomnia-plugin-customtimestamp) that supports offsets

**Comment by vermgit** [comment]
Oh, cool :) Thanks
