### ISSUE TITLE
[BUG] Insomnia fail but curl works?

### ISSUE THREAD

**Issue by davibusanello** [getinsomnia/insomnia#1500]
I have the same problem, and I don't have tokens in these requests like `login` endpoint. This request already was in my Workspace for a long time and always worked.

I'm also using in my local development server and the request doesn't reach the server with `Insomnia` however in `curl` works normally.

- OS `Ubuntu 18.04 bionic x86_64 Linux 4.15.0-48-generic`

- Insomnia `v6.5.1`

```
Version 6.5.1
Shell 3.0.4
Node 10.2.0
V8 6.6.346.32
Architecture x64

libcurl/7.61.1 OpenSSL/1.1.0h zlib/1.2.11 nghttp2/1.29.0
```

_Originally posted by @davibusanello in https://github.com/getinsomnia/insomnia/issues/836#issuecomment-491852003_

# Reproducing

1. Define a `POST` request to a `localhost` or `0.0.0.0`
2. Define the JSON body is a login request
3. Send the request
4. Watching the server log, don't received any request
4. Also when this occurs I can't cancel the request in `Insomnia` and need to close de APP
5. `curl` request
```
curl --request POST \
  --url http://0.0.0.0:8000/api/v2/account/login \
  --header 'content-type: application/json' \
  --cookie language=en-US \
  --data '{
        "email": "58594da2aa84sssa09f6ae757e6b7c@lolololo.com",
        "password": "das3112Dada"
}'
```
6. All worked well in curl

**Comment by gschier** [comment]
Can you post the full debug info here from the Timeline tab?

**Comment by davibusanello** [comment]
@gschier The Timeline never appears because request can't be canceled and no timeout occurs.

![Captura de tela de 2019-05-13 14-41-20](https://user-images.githubusercontent.com/160360/57642317-67927200-758d-11e9-92ac-76b9809037bf.png)

**Comment by Gomah** [comment]
Same issue here, tested with 2 laptops using Mojave 10.4.4. It works fine with 6.4.2;

**Comment by davibusanello** [comment]
> Same issue here, tested with 2 laptops using Mojave 10.4.4. It works fine with Insomnia 6.4.2.

@gschier I also make the downgrade to 6.4.2 and everything works fine!

**Comment by gschier** [comment]
@davibusanello @Gomah Did any requests work for you or specific ones? I can't reproduce this on my Mac running 6.5.1.

**Comment by gschier** [comment]
Please also check to see if there are any errors visible in View > Toggle DevTools > Console

**Comment by Gomah** [comment]
@gschier 

#### Using 6.5.1:

I can't see my defined variables
![Screen Shot 2019-05-15 at 9 31 44 am](https://user-images.githubusercontent.com/2362138/57738853-8d865680-76f4-11e9-9c4b-88d407c95bd5.png)

Looks like there's an infinite loop in the console:

![Screen Shot 2019-05-15 at 9 32 24 am](https://user-images.githubusercontent.com/2362138/57738872-9e36cc80-76f4-11e9-889b-02bab4bbdf08.png)

#### Using 6.4.2:
![Screen Shot 2019-05-15 at 9 33 16 am](https://user-images.githubusercontent.com/2362138/57738881-a858cb00-76f4-11e9-9415-38fca4600609.png)

![Screen Shot 2019-05-15 at 9 33 30 am](https://user-images.githubusercontent.com/2362138/57738885-abec5200-76f4-11e9-9597-18c1f61906d1.png)

**Comment by gschier** [comment]
I just talked to someone on Slack with the same issue. For them, it was caused by using the Response Tag in an environment with Trigger Behavior set to "Always".

![image](https://user-images.githubusercontent.com/587576/57780445-46996080-76f6-11e9-8a54-846dd9eeb701.png)

**Comment by gschier** [comment]
Working on a fix!

**Comment by davibusanello** [comment]
> Thanks for the info @Gomah!
> 
> I just talked to someone on Slack with the same issue. For them, it was caused by using the Response Tag in an environment with Trigger Behavior set to "Always".
> 
> ![image](https://user-images.githubusercontent.com/587576/57780445-46996080-76f6-11e9-8a54-846dd9eeb701.png)

Thank you @gschier, I use the Response Tag to in the environment, however the strange is because I don't use those properties with Response Tag in this `login` requests.

![insomnia](https://user-images.githubusercontent.com/160360/57794352-d00e5a00-7719-11e9-847a-4c0da516f3ac.png)

I'm going to wait the fix!

**Comment by gschier** [comment]
It will still happen even if you don't reference those properties in a request. The environments are compiled and rendered no matter what.

**Comment by davibusanello** [comment]
I have already installed the version 6.5.2 and works again!
Thank you!

**Comment by gschier** [comment]
Can you see if this is fixed now in https://insomnia.rest/changelog/6.5.3?

**Comment by gschier** [comment]
Oh, just noticed your comment @davibusanello. I'm so happy it works for you again 😄 👍

**Comment by Gomah** [comment]
Works for me too, thanks @gschier !

**Comment by davibusanello** [comment]
6.5.3 works very well too! Thanks @gschier
