### ISSUE TITLE
[Generate Code]Generate Code is not work on v6.5.1.2798

### ISSUE THREAD

**Issue by xin7c** [getinsomnia/insomnia#1503]
- Insomnia Version: ___v6.5.1.2798
- Operating System: ___mac osx

## Details

![image](https://user-images.githubusercontent.com/11660641/57823259-664d8900-77c9-11e9-8f13-57c3107b6d9b.png)

**Comment by gschier** [comment]
Unfortunately I cannot reproduce this. Can you provide an export of a minimal workspace used to reproduce this/
