### ISSUE TITLE
[Bug] Unable to switch between Sub environments

### ISSUE THREAD

**Issue by yash3x** [getinsomnia/insomnia#1506]
- Insomnia Version: Version 6.5.3 (6.5.3.2835)
- Operating System: macOS Mojave 10.14.4 (18E226)

[Bug] Unable to switch between sub-environments  

Steps to Reproduce:
Create two Sub environments at Manage Environment Panel 
Try to switch between the Sub environments to update values 

**Actual Results:**
Unable to switch between the Sub environments

**Expected Result:**
User must be able to switch between the Sub environments

**Screen recording:**
[View](https://www.dropbox.com/s/sx1f4fx57ln5v59/insomnia_bug.mov?dl=0)

**Comment by gschier** [comment]
Thanks for the helpful screen recording! I can't seem to reproduce this. Can you see if there are any errors in View > Toggle DevTools > Console?

**Comment by yash3x** [comment]
Thanks for your prompt reply. 
I tried to reinstall the application and it seems to have solved the issue. I'm unable to reproduce the issue right now. You may close the issue.

**Comment by gschier** [comment]
Hmm, that's odd. Well let me know if it happens again!
