### ISSUE TITLE
[Bug] GraphQL variables show error before any interaction

### ISSUE THREAD

**Issue by aryzing** [getinsomnia/insomnia#1507]
- Insomnia Version: 6.5.3
- Operating System: Ubuntu 18.04

## Details

An error is dispayed warning about an unused variable, when in fact it is used
![Screenshot 2019-05-17 16:07:25](https://user-images.githubusercontent.com/4924405/57937455-e6551b00-78bd-11e9-9271-03e9f24b32e3.png)

**Comment by gschier** [comment]
Ya, I noticed this one before too. The error disappears as soon as you edit the query, right?

**Comment by aryzing** [comment]
Yes

**Comment by ph55** [comment]
I can confirm. Same issue.
![image](https://user-images.githubusercontent.com/1386622/59163289-94439600-8b07-11e9-9176-2e3db82f1cba.png)

**Comment by n2iw** [comment]
Same issue here! It did disappear after editing the query, but if you switch to anther query and switch back, it is back again.

**Comment by upadmdh** [comment]
Issue still present in
![image](https://user-images.githubusercontent.com/48279464/68932511-cc3abd80-07b8-11ea-8284-9c171e93743e.png)

![image](https://user-images.githubusercontent.com/48279464/68932463-b4633980-07b8-11ea-8dd4-6d1477f71eea.png)
