### ISSUE TITLE
Binary file fails when synchronized to another computer.

### ISSUE THREAD

**Issue by ripvannwinkler** [getinsomnia/insomnia#1508]
- Insomnia Version: 6.5.1
- Operating System: Windows 10 build 17763.475

## Details

I purchased a subscription for the sync feature. When I specify the type "binary file" for a post body on one computer, it works fine. When I attempt to launch the app on the other computer, it fails to load, presumably because it's trying to sync / load the file specified on the previous computer which does not exist. A screenshot of the error message is attached.

In this scenario, I expect maybe a warning or nothing at all (silent fail), but not a fatal error message that prevents me from even correcting the issue on the second computer.

![insomnia file error](https://user-images.githubusercontent.com/130069/57955895-be18ec80-78bc-11e9-9fd5-a33f59edfa7e.png)

**Comment by gschier** [comment]
Currently, Insomnia only syncs the file path for the binary file on the request and _should_ be handling missing files gracefully. Here's what I get on the Mac version:

![image](https://user-images.githubusercontent.com/587576/58030246-374a5680-7aec-11e9-8b3b-e851531d58e4.png)

It seems like this issue may not be related to sync or the "binary file" request body type. The error seems to be coming up before the local database is even loaded. 

A few things:
- Are you using any plugins?
- Does this error happen immediately on startup, before the window shows?
- Can you try uninstalling and reinstalling the app, to see if that helps?
- If that doesn't help, try deleting (back it up first) the `%APPDATA%/Insomnia` directory (where the data is stored) and try relaunching the app

**Comment by ripvannwinkler** [comment]
No plugins. Happens immediately on startup, before the window or anything.
Uninstalling the app entirely and blowing away the insomnia directory in
both AppData (local and roaming) directories fixed it.
