### ISSUE TITLE
Bug: HTTP requests not traced in Network tab of the Developer Tools

### ISSUE THREAD

**Issue by mxmlnglt** [getinsomnia/insomnia#1509]
- Insomnia Version: 6.4.2
- Operating System: Windows 10 Pro (64-bit)

## Details

Apart from a request to https://api.insomnia.rest/notification none of the requests made in the main window are displayed in the Network tab from the Developer Tools.

See: in this case I was refreshing the schema from my local server, but this works with whatever API url you can use.

![Insomnia_no_request_network](https://user-images.githubusercontent.com/29626929/58009771-ae78ee00-7ade-11e9-8014-9ef27991aa54.png)

Below is the timeline the little green bug icon gave me:

* Preparing request to http://localhost:8080/graphql
* Using libcurl/7.57.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.7.0_DEV
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 3 cookies
* Found bundle for host localhost: 0x2927ac8e560 [serially]
* Hostname localhost was found in DNS cache
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#5)
* Server auth using Basic with user 'xxxxxx'

> POST /graphql HTTP/1.1
> Host: localhost:8080
> Authorization: Basic <whatever_for_security_reason>==
> User-Agent: insomnia/6.4.2
> Content-Type: application/graphql
> Accept: */*
> Content-Length: 1765

| {"query":"\n    query IntrospectionQuery {\n      __schema {\n        queryType { name }\n        mutationType { name }\n        subscriptionType { name }\n        types {\n          ...FullType\n        }\n        directives {\n          name\n          description\n          locations\n          args {\n            ...InputValue\n          }\n        }\n      }\n    }\n\n    fragment FullType on __Type {\n      kind\n      name\n      description\n      fields(includeDeprecated: true) {\n        name\n        description\n        args {\n          ...InputValue\n        }\n        type {\n          ...TypeRef\n        }\n        isDeprecated\n        deprecationReason\n      }\n      inputFields {\n        ...InputValue\n      }\n      interfaces {\n        ...TypeRef\n      }\n      enumValues(includeDeprecated: true) {\n        name\n        description\n        isDeprecated\n        deprecationReason\n      }\n      possibleTypes {\n        ...TypeRef\n      }\n    }\n\n    fragment InputValue on __InputValue {\n      name\n      description\n      type { ...TypeRef }\n      defaultValue\n    }\n\n    fragment TypeRef on __Type {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                  ofType {\n                    kind\n                    name\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  ","operationName":"IntrospectionQuery"}

* upload completely sent off: 1765 out of 1765 bytes

< HTTP/1.1 200 
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json;charset=UTF-8
< Content-Length: 115
< Date: Mon, 20 May 2019 08:58:51 GMT

* Received 115 B chunk
* Connection cache is full, closing the oldest one.
* Closing connection 1
* TLSv1.2 (OUT), TLS alert, Client hello (1):
* Connection #5 to host localhost left intact

**Comment by gschier** [comment]
Thanks for the issue 😄 

All Insomnia (user-created) requests are made using the `libcurl` library which is why it's not possible to view them in DevTools. `libcurl` was chosen because it supports more features (auth types, debugging, more specific configuration, etc) which is a great fit for an HTTP debugging app.

Non-user-created requests will continue to use the Chromium network stack because it's better at handling edge-cases like invalid headers or discovering OS proxies. In summary, it will do many strange things in order to try and make a request succeed, while `libcurl` will usually prefer to error instead.

I'm going to close this one as it's not possible to implement.

**Comment by veso0308** [comment]
Is it possible to access the requests history by console?
