### ISSUE TITLE
Content-Type header being overridden

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#151]
Bug Report:

> insomnia seems to constantly override my Content-Type header I'll set it to [text/xml;charset="utf-8"] and when the response comes back the header on my SEND side is either removed completely or changed to [application/text] and I have to go back in and change it again for each time I hit Send.

**Comment by b-hayes** [comment]
yup same issue here. Really annoying for testing. Found some problems with bad content types and am unable to use insomnia to test this issue because no matter what I do it sends application/json instead of what I tell it to send.
