### ISSUE TITLE
[Bug] Auto-switch to top-most recent request on keypress

### ISSUE THREAD

**Issue by gcamp0730** [getinsomnia/insomnia#1512]
- Insomnia Version: 6.5.3.2835
- Operating System: macOS 10.14.5

## Details

**Issue:** Insomnia will switch to whatever item is at the top of the recents menu when you press / release any key

**How to reproduce:**
  - Use Ctrl-Tab to switch to any request
  - Use the mouse to click to a different request (one or more times)
  - Press and release any key
  - Observe that focus has returned to the request at the top of the recents menu

NOTE: I originally believed this to occur when the Cmd key was pressed, but further testing showed that pressing any key after using the mouse to select a different request would trigger the focus being returned to the request at the top of the recents menu.

**Comment by gschier** [comment]
Hmm, this is actually the desired behavior. Ctrl+Tab to open the switcher, then (while still holding Ctrl) Tab or Shift+Tab through the requests, and release Ctrl to activate.

Do you think there's a better way this could be communicated?

**Comment by gcamp0730** [comment]
My instructions for reproducing the issue might need additional explanation.

When I said, "Use Ctrl-Tab to switch to any request" I meant fully releasing Ctrl to activate. If you then use the mouse to select a different request (not in the recents list, but in the workspace view on the left of the screen), the very next key you press will take you back to the request you had previously selected using Ctrl-Tab. If, however, you use Ctrl-Tab to select a request, you are able to press keys / type normally and the input goes where you expect it to go.

**Comment by gschier** [comment]
Oooooh, I see. I think I actually heard the same problem described by someone else (maybe in Slack?) and also couldn't figure out what it was. Thanks for clarifying! I will fix it right now 👍
