### ISSUE TITLE
[Help] Failure when receiving data from the peer in windows 10

### ISSUE THREAD

**Issue by zKauaCodes** [getinsomnia/insomnia#1516]
Hello, I try to make a request for my routes and end up giving error, when running, I already tested on other clients and it worked

**Comment by gschier** [comment]
Hi @zKauaCodes and thanks for the report. Unfortunately this is not enough information to debug the problem. Can you please provide more information? A copy of the Timeline tab would be a great start.

**Comment by zKauaCodes** [comment]
Good here.

* Preparing request to https://localhost:8080/api/group/create
* Using libcurl/7.57.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.7.0_DEV
* Current time is 2019-05-23T23:13:32.209Z
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Enable network proxy for https:
* Connection 3 seems to be dead!
* Closing connection 3
* Hostname localhost was found in DNS cache
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#4)
* allocate connect buffer!
* Establish HTTP proxy tunnel to localhost:8080

> CONNECT localhost:8080 HTTP/1.1
> Host: localhost:8080
> User-Agent: insomnia/6.5.3
> Proxy-Connection: Keep-Alive

* Proxy CONNECT aborted
* CONNECT phase completed!
* Connection #4 to host localhost left intact
