### ISSUE TITLE
Large Files Crash Application

### ISSUE THREAD

**Issue by mlh758** [getinsomnia/insomnia#1517]
- Insomnia Version: Version 6.5.3 (6.5.3.2835)
- Operating System: MacOS Mojave

## Details

This seems related to #282 and #608 but those are both closed and I'm definitely experiencing the problem.

I requested a 2.5MB Excel file through Insomnia and it became unresponsive. This used to work so I think this was broken in a recent update. Also, if I reopen the application after I'm prompted to the application just crashes outright. I had to delete the response database to open Insomnia again.

Edit: It looks like this might be specific to an xml response. I'm getting:
```
<ns:binary xmlns:ns="http://ws.apache.org/commons/ns/payload">
base64encodedbytes... lots of them...
</ns:binary>
```
from the application I was calling now and I think Insomnia might be getting stuck trying to format the xml in the preview.

**Comment by gschier** [comment]
Hi @mlh758,

Are you able to post an example XML file for me to test with?

**Comment by mlh758** [comment]
[data.xml.zip](https://github.com/getinsomnia/insomnia/files/3214202/data.xml.zip)

I zipped the response body up and attached it to this comment.

**Comment by madetara** [comment]
Hi. Same issue here. Insomnia becomes unresponsive whent trying to load heavy response (about 1mb text), which leads to it failing to start

**Comment by madetara** [comment]
![Version info](https://user-images.githubusercontent.com/31938575/58692116-99ca0f00-8396-11e9-8915-a6f42b0601a9.png)
OS: Windows 10

**Comment by doneill** [comment]
I am seeing an issue with responses from json, workaround proposed in #282.  The json responses from the requests were working before so maybe recent introduction as mentioned in the issue description

**Comment by skyhirider** [comment]
I am experiencing Insomnia getting stuck when I get a larger json response back.

I click into the body response window, do Ctrl+A and Insomnia gets stuck. Unsure if I should open a separate issue, but this happened repeatedly. Exporting raw body works.

Wish there was a copy body button that would prevent this issue.

**Comment by kiwiant** [comment]
Same issue on Windows 10 with version 6.5.4 (Shell 3.0.4, Node 10.2.0, V8 6.6.346.32, x64). Exactly the same symptom for me where I try to select the response (530KB) using Ctrl+A or Shift+Ctrl+End the app hangs/becomes unresponsive. Eventually the unresponsive message pops up with the option to "Reload".

I suspect issues [1546](https://github.com/getinsomnia/insomnia/issues/1546) and [1545](https://github.com/getinsomnia/insomnia/issues/1545) are related.

**Comment by JacobSiegle** [comment]
Testing code which zips 3 photos and downloads them - Same issue where the large payload size causes insomnia to go into a loop of death until you clear data. Commented to prevent stale bot.

**Comment by kiwiant** [comment]
Retested with Insomnia 6.6.2 and the app no longer hangs/becomes unresponsive. How about you @skyhirider?

**Comment by JacobSiegle** [comment]
I'm not sure why but running the exact same code again with the exact same files being turned into a zip is not causing the crash bootloop anymore. I would assume clearing whatever insomnia had cached in appdata on windows fixed the issue. Unfortunately I already cleared out my trash so I cannot pull back whatever was in appdata to try to replicate the issue.

**Comment by JarekDerp** [comment]
I think have the same problem?
I wrote a Get API to download a zip file. I accidentally tried to preview the file as "Raw" and it froze the app. When I restart it, it again try to open the zip file in "Raw"...

**Comment by mlh758** [comment]
Forgot this was still open. This has been fixed for me in recent versions. I  see a message that preview is disabled for large files.

**Comment by diego-lipinski-de-castro** [comment]
I tried to show one 3.3mb pdf and now my app is frozen, I can close and open and it remains frozen, Im on Macos 10.15, what Im supposed to do? I really dont want to clear app data and lose everything saved there.

Edit: I went to /users/{username}/app support/insominia/responses and deleted everything in this folder, so the response just fails to load and the app run again as normal

**Comment by gpasq** [comment]
This is still an issue 2 years later.  Sigh.

**Comment by kentcwell** [comment]
FYI: June 2022. This still occurs.

**Comment by gpasq** [comment]
Yeah, they don't care.

**Comment by kentcwell** [comment]
For oversized requests, appears you can remove the entry from the insomnia.Request.db file and recover the app.

**Comment by gpasq** [comment]
You can.  That's fun.  This is 3 year old bug that they have no interest in fixing.  Meh.

**Comment by ghost** [comment]
Well, since my first comment about this issue I changed my place of employment twice. Well, good luck y'all.
