### ISSUE TITLE
[Bug] Plugins are not refreshed correctly

### ISSUE THREAD

**Issue by amjd** [getinsomnia/insomnia#1524]
- Insomnia Version: 6.5.3 (6.5.3.2835)
- Operating System: macOS Mojave (10.14.3)

## Details
When developing a plugin locally, Insomnia doesn't always refresh the plugin from the file system when you click "Reload Plugins" in settings. I have tried this with and without changing the version and with the plugin directory being symlinked vs being copied in the plugins directory.

For all of these cases, the plugin wasn't always refreshed. Restarting Insomnia seems to work though.

**Comment by sarneeh** [comment]
Same here.
