### ISSUE TITLE
[Bug] hosts lookup not refreshed

### ISSUE THREAD

**Issue by AdityaHarindar** [getinsomnia/insomnia#1529]
- Insomnia Version: 6.5.3
- Operating System: Windows 10 1903 (Issue was present on 1809 as well)

## Details

Changes in `C:\Windows\System32\drivers\etc\hosts` (`/etc/hosts`) don't seem to reflect until a restart of insomnia, however the same is not an issue on Ubuntu (18.04). Some services we develop resolve some information from the domain name, for which we need to point that domain to `localhost` for testing.

Eg. 
![Annotation 2019-05-29 100455](https://user-images.githubusercontent.com/18701550/58524077-8b92bc00-81f9-11e9-807d-95f5901bdc7d.png)

**Comment by gschier** [comment]
It might be because Insomnia reuses network connections (well, `libcurl` does)when it can. Do you know if it will eventually refreshes? It looks like `libcurl`'s default DNS cache is set to 60 seconds.

**Comment by AdityaHarindar** [comment]
That seems to do the trick, lookup is successful after about 60 seconds. Thanks!

**Comment by Shawyeok** [comment]
> It might be because Insomnia reuses network connections (well, `libcurl` does)when it can. Do you know if it will eventually refreshes? It looks like `libcurl`'s default DNS cache is set to 60 seconds.

@gschier Add request header `Connection: close` can disable connection reuse. Do you know how to disable libcurl's DNS cache in insominia?

I use same domain name in different environments (e.g. QA/PRE/PROD). Disable cache can really helps in switch env scenario.
