### ISSUE TITLE
[Bug] Changing environment color after editing reverts any changes

### ISSUE THREAD

**Issue by jwir3** [getinsomnia/insomnia#1530]
- Insomnia Version: 6.5.3
```
Version 6.5.3
Shell 3.0.4
Node 10.2.0
V8 6.6.346.32
Architecture x64

libcurl/7.61.1 OpenSSL/1.1.0h zlib/1.2.11 nghttp2/1.29.0
```
- Operating System: Ubuntu 18.04 LTS (Bionic Beaver)

## Details

**Steps to Reproduce**:
1. Open Insomnia, Click 'No Environment' dropdown, select 'Manage Environments', click the '+' next to 'Sub-Environments'.
2. Add the following information to a new environment called 'Foamfactory Local':
```
{
  "protocol": "http",
  "base_url": "0.0.0.0",
  "port": "3000"
}
```
3. Click the 'Color' dropdown, click 'Assign Color', and choose a color (I chose `#7d69cb` but the actual value doesn't matter).
4. Click <kbd>CTRL</kbd>+<kbd>S</kbd> (or, on mac, <kbd>CMD</kbd>+<kbd>S</kbd>) (_Note_: This seems to be the problem. I don't know exactly why I am compulsively hitting this key combination, especially since most text editors save automatically nowadays, but I am. I would expect Insomnia to ignore this key combination).
4. Click 'Done'.
5. Click 'No Environment' dropdown, select 'Manage Environments', select 'FoamFactory Local'.

**Expected Results**:
  - :white_check_mark: The data you entered should be present in the  environment dialog.

**Actual Results**:
  - :x: The data entered into this environment dialog in the previous steps is not present. Instead, only `{}` is shown.

**Comment by gschier** [comment]
I just took a look and it looks like it's the act of changing the color that overwrites any changes made before closing the dialog. It also works the other way. If you select a color, then edit the JSON, the color will not be saved.

Will get a fix for this out in the next release 👍 

Thanks for the detailed explanation!

**Comment by jwir3** [comment]
Awesome! Thanks for the speedy response!
