### ISSUE TITLE
 Insomina Environments with Projects Diappear after Laptop restart

### ISSUE THREAD

**Issue by egopal** [getinsomnia/insomnia#1531]
- Insomnia Version: __6.5.3_
- Operating System: _Windows 10

## Details

I created an environment called REL_Test and added multiple JSON POST Service requests.
Created subfolder as EMP within the above environment folder and moved all the files from the parent REL_Test folder to the child folder
Created one more new parent project as STAGE and created a child folder as EMP and added JSON POST requests .
Restarted my laptop and started the Insomina, all my Folder and Sub-Folder disappear.
Any help to troubleshoot/restore the same will be highly appreciated.

**Comment by gschier** [comment]
Can you clarify how you're using the terms "Environment" and "Project"? I assume you mean to say Workspace instead of Environment. Do you also mean Workspace when you say Project?

**Comment by ianchadwick** [comment]
Sounds like the same problem I'm having. All workspace stuff is inaccessible now after the update.

**Comment by ianchadwick** [comment]
> Sounds like the same problem I'm having. All workspace stuff is inaccessible now after the update. I'm on OSX Mojave.

So... potential user error, seems I just needed to hit CMD+\ to bring it back.

**Comment by egopal** [comment]
Tried the above, it does not work for me in Windows.
I am moving on.
