### ISSUE TITLE
[Bug]File Tag does not let allow selecting file from FS

### ISSUE THREAD

**Issue by JakeQuilty** [getinsomnia/insomnia#1534]
- Insomnia Version: ___6.5.3
- Operating System: ___OSx Sierra 10.12.6

## Details
I can see the files in the menu of the filesystem browser, but unable to select any of them. The files are greyed out and cannot be selected or highlighted in the browser. I can still move around through different directories.
![Screen Shot 2019-05-30 at 12 10 59 PM](https://user-images.githubusercontent.com/44121341/58646684-ed275900-82d3-11e9-9ffe-5fe6229775a4.png)

**Comment by gschier** [comment]
This is already fixed and will be out in the next release 👍
