### ISSUE TITLE
[Feature Request] auto format JSON on request body

### ISSUE THREAD

**Issue by cnarvaa** [getinsomnia/insomnia#1535]
- Insomnia Version: 6.5.3
- Operating System: Windows 10 latest

## Details

I was wondering if it's possible to get an automatic JSON formater for the requests body.
Currently, we have the lintern active so I can see when my JSON is bad formated.

Input:
~~~~
{"menu":{"id":"file","value":"File","popup":{"menuitem":[{"value":"New","onclick":"CreateNewDoc()"},{"value":"Open","onclick":"OpenDoc()"},{"value":"Close","onclick":"CloseDoc()"}]}}}
~~~~

expected output
~~~~
{
  "menu": {
    "id": "file",
    "value": "File",
    "popup": {
      "menuitem": [
        {
          "value": "New",
          "onclick": "CreateNewDoc()"
        },
        {
          "value": "Open",
          "onclick": "OpenDoc()"
        },
        {
          "value": "Close",
          "onclick": "CloseDoc()"
        }
      ]
    }
  }
}
~~~~

I'm thinking maybe in a right click option?

![actual UI menu for json input](https://user-images.githubusercontent.com/7719714/58667391-79994200-82fb-11e9-8a94-ef60231a1200.png)

**Comment by gschier** [comment]
There is a button to format the JSON below the request body

![image](https://user-images.githubusercontent.com/587576/58669125-2af2a480-8309-11e9-8594-bda193cbb795.png)

**Comment by cnarvaa** [comment]
You don't know how much I search for this. I couldn't find it in the documentation and maybe my first options were to find it in the JSON menu or in the click menu.

Thanks for your quick response.

**Comment by zuernBernhard** [comment]
Can we please have this also for Multipart Requests in multiline text fields ? 


![multiline_1](https://user-images.githubusercontent.com/1442798/76216893-afb40c80-6211-11ea-9550-3a57a18efaaa.jpg)

![beautify_2](https://user-images.githubusercontent.com/1442798/76216890-adea4900-6211-11ea-9c4c-fc91cd93dd48.jpg)

**Comment by ap1969** [comment]
2 years of using online prettifiers, and I finally find this post :-)

**Comment by lbedoyas** [comment]
Genial muchas gracias lo necesitaba

**Comment by davincif** [comment]
I searched if a lot too... and just found now.

perhaps if so many people have the same problem, it means that this button isn't in the right place, or perhaps, it shouldn't exist at all, and this action could be automatic.

**Comment by dracan** [comment]
> perhaps if so many people have the same problem, it means that this button isn't in the right place, or perhaps, it shouldn't exist at all, and this action could be automatic.

Gotta agree with @davincif here. I feel really stupid now that I know where the button is - but I did look for a way of doing it, and couldn't find it, and only discovered it by this Github issue.

**Comment by ben-nathanson** [comment]
Adding a +1 here. It doesn't look like a button, my eye doesn't expect a button to be down there... I only found this answer by googling.

**Comment by Fvegini** [comment]
This should be a "right click menu option".

I also only found this feature googling it.
