### ISSUE TITLE
[Bug] File won't be selected when accepting Content-Type suggestion

### ISSUE THREAD

**Issue by maple3142** [getinsomnia/insomnia#1542]
- Insomnia Version: 6.5.4
- Operating System: win10 x64 1903

## Details

Video: https://streamable.com/4nl75

After I click "Yes" in the "Change Content-Type" dialog, the file won't be selected as expected.

**Comment by brendano86** [comment]
I added a fix for this in https://github.com/getinsomnia/insomnia/pull/1584
