### ISSUE TITLE
[Help] Insomnia has become unresponsive

### ISSUE THREAD

**Issue by oliverjanik** [getinsomnia/insomnia#1545]
I'm stuck in this loop. As soon as I open Insomnia it dies on me.

![image](https://user-images.githubusercontent.com/2280140/58776148-7a3c1c00-860c-11e9-832b-4526252e986d.png)

All I did was hit "Send" and re response started loading a bigger (few MB) binary file. I'm assuming Insomnia is trying to load the response into to the UI and just dies doing this.

Should there be a circuit breaker for this? If response is binary or too large, snip it.

Also how do I get unstuck and break this loop ?

**Comment by gschier** [comment]
Hi Oliver,

You should be able to delete the large response from `%APPDATA%/Insomnia/responses` and restart the app.

**Comment by oliverjanik** [comment]
Thank you that worked.

**Comment by Vaunorage** [comment]
Omg, the first time I used it and it kept giving this error over and over again after trying to import my open api file ....

**Comment by anders-softhouse** [comment]
@gschier Hi, I just deleted the latest timeline and response files and Insomnia no longer locks up. Thank you very much.
The files where not extremely huge ( some MB ), but did contain "weird" / control characters.

**Comment by mat926** [comment]
I'm also having this same issue when the response contains a control character or binary encodings. Clearing the folder works, but I would still like to parse the response.
