### ISSUE TITLE
Lags and brakes with a large amount of post data

### ISSUE THREAD

**Issue by 4n70w4** [getinsomnia/insomnia#1549]
If post data > 1mb then interface slows down, the buttons do not work, the animation slows down.

![image](https://user-images.githubusercontent.com/38257723/58893695-4ab70d80-86f9-11e9-8f71-05a806f3150f.png)

@related https://github.com/getinsomnia/insomnia/issues/793

**Comment by vgibilmanno** [comment]
Can confirm I have the same issue. CPU usage of insomnia goes up to about 30% and the process needs to be killed.

**Comment by HeCorr** [comment]
Duplicate of #793
