### ISSUE TITLE
[Bug] Insomnia no longer suggests/intellisenses headers in latest version

### ISSUE THREAD

**Issue by adam-koblentz** [getinsomnia/insomnia#1551]
- Insomnia Version: 6.5.4 (6.5.4.2876)
- Operating System: MacOS Mojave 10.14.5

## Details

Previously in Insomnia, when adding headers, I received suggestions on known/typical headers and some of their known values. For example: 'content-type' and 'application/json'. With the latest version of Insomnia that is no longer happening.

I have a normal GET request as my request type.

**Comment by rafaelrenanpacheco** [comment]
This config if set to 0 will prevent popups (suggestions) from openning as you type:

![image](https://user-images.githubusercontent.com/12160864/59107250-94c50c80-890e-11e9-9a42-64d7eb5eaec2.png)

In order to show suggestions you have to press Ctrl+Space (on not mac keyboards).

**Comment by adam-koblentz** [comment]
> This config if set to 0 will prevent popups (suggestions) from openning as you type:
> 
> ![image](https://user-images.githubusercontent.com/12160864/59107250-94c50c80-890e-11e9-9a42-64d7eb5eaec2.png)
> 
> In order to show suggestions you have to press Ctrl+Space (on non mac keyboards), or change this config to some other value, in milliseconds.

Thanks!
