### ISSUE TITLE
POST Request Json Body Not Sending

### ISSUE THREAD

**Issue by cashcoder88** [getinsomnia/insomnia#1555]
- Insomnia Version: _6.5.4__
- Operating System: _Mac OS High Sierra__

## Details

 For whatever reason the POST req.body would not send through to my API. It was a simple JSON Body object i.e. {"username": "example", "password":"pass"}. At one point I restarted Insomnia and changed around the Body settings and it worked, but then broke again.

**Comment by gschier** [comment]
There should be more info as to what's happening in the Timeline tab.

**Comment by Schlickmann** [comment]
I am also facing this problem.

Timeline tab:

`* Preparing request to http://localhost:5000/signup
* Using libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
* Current time is 2019-06-17T02:34:00.498Z
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Found bundle for host localhost: 0x7f854af75340 [can pipeline]
* Re-using existing connection! (#6) with host localhost
* Connected to localhost (::1) port 5000 (#6)

> POST /signup HTTP/1.1
> Host: localhost:5000
> User-Agent: insomnia/6.5.4
> Content-Type: application/json
> Accept: */*
> Content-Length: 85

| {
| 	"name": "test",
| 	"email": "test",
| 	"password": "12345453",
| 	"user_type": "admin"
| }

* upload completely sent off: 85 out of 85 bytes

< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: application/json; charset=utf-8
< Content-Length: 16
< ETag: W/"10-/VnJyQBB0+b7i4NY83P42KKVWsM"
< Date: Mon, 17 Jun 2019 02:34:00 GMT
< Connection: keep-alive


* Received 16 B chunk
* Connection #6 to host localhost left intact`

**Comment by Schlickmann** [comment]
@cashcoder88 I found my problem.
try to add **this.express.use(express.json())** in your server :)

**Comment by gschier** [comment]
😄

**Comment by wellingtonmacena** [comment]
Bad post requisitions.
I spent hours reviewing my code just to realize the bug wasn't in my application.  You should tell users about the issues software has.

**Comment by StanleySathler** [comment]
What's the issue the software has, @wellingtonmacena? In my case, I came here after thinking the Insomnia had an issue as well, but then I realized I hadn't included the `express.json()` middleware in my application - which means Insomnia was fine.

**Comment by toketas** [comment]
It happened with me. req.body = {} with insomnia, req.body = { content } with postman.

**Comment by ricardoamb** [comment]
Yah. I had the same! but cleaning the json just settind "No Body" and setting "JSON" again solve my prob! Hope solve yours also!
And I break my head thinkin the error is my code! chears!!!

**Comment by loureirorg** [comment]
To me, the problem was sending a "Digest" authentication with a JSON body. I could see on the timeline that the content-length was zero. Once I disabled the authentication, the body was sent.

**Comment by xikz** [comment]
Setting the body to 'no body'  and setting it back to 'json' did the trick for me!

**Comment by Saurja** [comment]
Yeah, that worked for me too! Lol

**Comment by dimitropoulos** [comment]
For what it's worth, I would like to see a mockbin.org link and steps to reproduce this.  If this is an active bug, I imagine the team will care about fixing it.

**Comment by chelfonseca** [comment]
> Yah. I had the same! but cleaning the json just settind "No Body" and setting "JSON" again solve my prob! Hope solve yours also! And I break my head thinkin the error is my code! chears!!!

That worked for me too. Thanks!

**Comment by HenJi** [comment]
This bug still exists, and the "No Body" trick worked for me - Version 2022.6.0

**Comment by haroldallen** [comment]
The issue for me (and probably others) was that I did not have this header:
![image](https://user-images.githubusercontent.com/67546646/202902715-bc4eefeb-8c16-4735-ba43-335b4d31513e.png)
Easily fixed (same as most people) by switching the body type to "No Body" and then back to "JSON".

So the bug seems to be that Insomnia doesn't re-add its header (if you accidentally delete it) without turning JSON body off and on again.

**Comment by SantiagoSchez** [comment]
Same issue here as @rickythefox. It's happening to me after importing from a Swagger URL. All the paths are set as JSON, but the Headers tab is completely empty.

**Comment by scoussens** [comment]
> Same issue here as @rickythefox. It's happening to me after importing from a Swagger URL. All the paths are set as JSON, but the Headers tab is completely empty.

This was my case as well, where I imported from swagger URL. Though it said the content-type was still in my headers, it wasn't actually treating it as such. I had to reset each body to none > JSON.

**Comment by alekseyl1992** [comment]
Had a similar issue, for me the problem was caused by HTTP/2. I switched to HTTP/1.0 in Insomnia Settings and now everything works fine.

**Comment by techwithnaga** [comment]
> @cashcoder88 I found my problem. try to add **this.express.use(express.json())** in your server :)

Lol. Thank you.
