### ISSUE TITLE
AWS Authentication w/o body

### ISSUE THREAD

**Issue by iMinnesotan** [getinsomnia/insomnia#1559]
While following this document https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-snapshots.html I was able to use Insomnia for the PUT request under "Registering a Manual Snapshot Repository" (takes a JSON body) but when I use the PUT request under "To manually take a snapshot" that does not have a body, Insomnia gives me the message, "AWS authentication not supported for provided body type". 

When I configured Postman with the same request and authentication it worked.

- Insomnia Version:  Version 6.5.4 (6.5.4.2876)
- Operating System:  MacOS 10.14.5 

## Details

- AWS IAM v4 Authentication
- PUT request
- No body

"AWS authentication not supported for provided body type"

Same config in Postman is bueno 👍

**Comment by shawnsparks-work** [comment]
Any chance of this actually getting fixed?

**Comment by SlovoTverdo** [comment]
Still no progress? Postman, I've come to you...
