### ISSUE TITLE
[Bug] Plain-text input fields automatically close opening parenthesis

### ISSUE THREAD

**Issue by blacknite** [getinsomnia/insomnia#1560]
- Insomnia Version: 6.5.4
- Operating System: Windows 10 pro x64 (build 16299.1087)

## Details

When using a left parenthesis in the basic authentication field for username or password, a right parenthesis is automatically added after, and the cursor is positioned between them.  This causes an extra character to be inserted where not wanted.

**Comment by gschier** [comment]
Oops, that shouldn't do this. FYI this applies to all plain-text fields.
