### ISSUE TITLE
6.5.4 missing from apt repository

### ISSUE THREAD

**Issue by JayAndCatchFire** [getinsomnia/insomnia#1563]
- Insomnia Version: 6.5.3/6.5.4
- Operating System: Ubuntu Linux 16.04.6 LTS (Xenial Xerus)

## Details

I'm not sure if this is because of #1546, but version 6.5.4 has not been published via the apt repository.

**Comment by gschier** [comment]
Hmm, looks like I may have forgot to hit the Publish button in bintray. Should be fixed now. Thanks for pointing this out 🙏
