### ISSUE TITLE
[Bug] can create more teams and switch between them despite having Plus plan

### ISSUE THREAD

**Issue by GrayedFox** [getinsomnia/insomnia#1564]
Ubuntu 18.04 LTS
Version 6.5.4
Shell 3.0.4
Node 10.2.0
V8 6.6.346.32
Architecture x64

libcurl/7.61.1 OpenSSL/1.1.0h zlib/1.2.11 nghttp2/1.29.0

## Details

The POST endpoint for Insomnia `/teams` is still enabled for Plus plan accounts (despite the GUI hiding this endpoint). I won't list the end point here but from the error I figured out the JSON structure required to create a new team, so now our Plus account has two teams.

Was playing around trying to figure out if I could rename the existing team name. I don't think this is a major concern, but hypothetically, an Insomnia customer could pay for the plus account and create multiple teams which, due to the awesome new sync behaviour (which is essentially a built in VCS), naughty boys and girls could technically get some of the "team" benefits of the team plan without paying for it!

We do share a single account between a few of our internal team members (sorry), and I think we will continue to support Insomnia, especially given it's recent new features and great development and response times, just wanted to give you a heads up. Will let my boss know I think we should upgrade :bowing_man:

**Comment by GrayedFox** [comment]
@gschier thought this might be of interest to you - maybe slipped through the cracks?

**Comment by gschier** [comment]
Thanks. I did indeed miss it. I'll take a look 🙂
