### ISSUE TITLE
Insomnia does not verify local SSL certificate, but curl does

### ISSUE THREAD

**Issue by sarneeh** [getinsomnia/insomnia#1565]
- Insomnia Version: 6.5.4
- Operating System: Ubuntu 18.10

## Details

I have a local server with a self-signed ssl certificate which works fine via browser and also responds correctly with `curl`, but it errors in Insomnia with:

```
Error: Peer certificate cannot be authenticated with given CA certificates
```

I read somewhere here in other issues that Insomnia uses OS's `libcurl`, so I'm kinda confused why does it work simply curling the local server, but it breaks in Insomnia. Any ideas?

**Comment by gschier** [comment]
On Linux, Insomnia includes its own build of libcurl in order to prevent dependency issues with the wide variety of Linux distros that exist. I assume it's working from the command line because your system version of Curl was built in such a way that specifies which directories contain certificates.

**Comment by bartecargo** [comment]
I think that I'm also experiencing this on Windows. I'm running mitmproxy and have installed the proxy certificate on my machine. My browsers (and PowerShell), which respect the Windows certificate store, trust the proxy. However, when I run Insomnia through the proxy, it complains:
>Error: Peer certificate cannot be authenticated with given CA certificates
You could reproduce via mitmproxy, Fiddler, or via self-signed cert.

Version 6.6.2
Shell 3.1.13
Node 10.2.0
V8 6.6.346.32
Architecture x64

libcurl/7.57.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.7.0_DEV

**Comment by nzbart** [comment]
I think that I'm also experiencing this on Windows. I'm running mitmproxy and have installed the proxy certificate on my machine. My browsers (and PowerShell), which respect the Windows certificate store, trust the proxy. However, when I run Insomnia through the proxy, it complains:

>Error: Peer certificate cannot be authenticated with given CA certificates

You could reproduce via mitmproxy, Fiddler, or via self-signed cert.

Version 6.6.2
Shell 3.1.13
Node 10.2.0
V8 6.6.346.32
Architecture x64

libcurl/7.57.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.7.0_DEV
