### ISSUE TITLE
[Feature Request] Send random numbers to REST interface

### ISSUE THREAD

**Issue by e7o-de** [getinsomnia/insomnia#1566]
Just found that awesome REST client and testing my most recent "project" with that. As my backend has some database restraints, the option with the current timestamp is awesome. I'm pushing time-tagged values to an endpoint, and the database has a UNIQUE key on the timestamp, as I only want to have one value per second.

Now, it's a bit annoying that I've got dozens of numbers in my database with all the same value, just being different on the last place of the timestamp. It would be awesome for testing purposes if I could simulate real measured values, so I wanna throw this one as a feature request into the ring :)

Easiest way should be a placeholder like [DIGIT] where there's a number 0..9, so I could just do [D][D][D‌][D] (should cover most use cases), the more complicated one with values (like "between 5 and 13"), but for this I cannot come up with a real case right now :)

**Comment by mpaw** [comment]
@e7o-de This already exists, you just need to install the `insomnia-plugin-randomnumber` plugin. You can then use a random number both in the URL and the request body

![image](https://user-images.githubusercontent.com/5834637/59947402-25393c00-943b-11e9-9cc9-0aad740b9b6a.png)

![image](https://user-images.githubusercontent.com/5834637/59947486-59acf800-943b-11e9-9cd6-6b930e1f66c6.png)

**Comment by e7o-de** [comment]
Awesome, thx. Now I'll figure out what "Yarn error /snap/insomnia/30/insomnia: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory" means (guess I'll drop that stupid snap thing and switch to the repo) :)
