### ISSUE TITLE
[Bug] - Focused item is switched unexpectedly in popup list

### ISSUE THREAD

**Issue by timbset** [getinsomnia/insomnia#1568]
- Insomnia Version: 6.5.4
- Operating System: Windows 10

I ordinary use Insomnia for GraphQL. When I write query, I use the Crtl+Space combination to see popup with possible query fields. If I start navigating in the list using arrows at the same time, focus is reset on first list item after one or two seconds. If I wait for some seconds before navigating, this problem is not reproduced. This is a minor bug but it's very annoying.

**Comment by gschier** [comment]
I'm pretty sure there is another issue around here for this. I haven't been able to reproduce it on my end, which is why it has not yet been fixed. 

...

Found it: https://github.com/getinsomnia/insomnia/issues/1015
