### ISSUE TITLE
Broken link to importers in docs

### ISSUE THREAD

**Issue by Chris2048** [getinsomnia/insomnia#1569]
This page: https://support.insomnia.rest/article/52-importing-and-exporting-data
contains the link: https://github.com/getinsomnia/importers

The link is not valid. I am not sure where it should now lead.

**Comment by gschier** [comment]
Thanks for pointing this out. That repo has been merges into this one, so it should now point to https://github.com/getinsomnia/insomnia/tree/develop/packages/insomnia-importers

I'll update the doc right now
