### ISSUE TITLE
[Bug] Response chaining fails if response contains }}

### ISSUE THREAD

**Issue by StuartChartersE22** [getinsomnia/insomnia#1576]
- Insomnia Version: 6.5.3

## Details
I am chaining responses in a request but there is a value which follows the structure: 
{parent: {child: value}}
There is an error thrown of `expected name as lookup value, got }}`. This prevents the request from working

**Comment by gschier** [comment]
Hmm, this one might be tricky.

Where are you using the Response tag that is failing. Is it included in an environment variable or directly in another request?

The reason it's failing is because it's trying to render the request after including the data from your response dependency.
