### ISSUE TITLE
[Feature Request] Private data inside of public sub-environments

### ISSUE THREAD

**Issue by everscending** [getinsomnia/insomnia#1577]
- Insomnia Version: 6.5.4
- Operating System: OS X

## Details

My team is standardizing on the Insomnia config that we pass on to new developers during on-boarding.  We have sub-environments setup for dev, staging, and production, etc.  And we also have a set of service credentials needed to access the various endpoints, each environment having its own set of credentials.  We do not want these credentials to be exported from Insomnia as it is sensitive info.  Instead we want devs to add this into their config after importing it from the version controlled repo.  This feature is implemented as "private" sub-environments but that doesn't work in this case.  The credentials need to live in the  public sub-environments so they are accessible when those environments are selected.  The feature request is the ability to add sensitive info to public sub-environments in a manner that tells Insomnia not to export it when the time comes, for example:
```
{
  "host": "http://myhost.com",
  "private": {
     "client_id": "123456",
     "client_secret": "sfv765s765sdfvdf" 
  }
}
```

**Comment by gschier** [comment]
If it's just a couple values, I suggest using the Prompt tag to get around this. If you set the "storage key" into the prompt tag configuration, Insomnia will ask for these values upon making the first request and store them locally for future ones.

There is likely to be changes to environments to make "private" environments more accessible but there is currently no official timeline to make that happen.

![image](https://user-images.githubusercontent.com/587576/60368837-ec134580-99bf-11e9-81c4-32658edce9b9.png)

![image](https://user-images.githubusercontent.com/587576/60368750-ae162180-99bf-11e9-9205-70f193de4511.png)

![image](https://user-images.githubusercontent.com/587576/60368773-c0905b00-99bf-11e9-921c-a7b214a247ff.png)
