### ISSUE TITLE
Duplicate workspaces on sync

### ISSUE THREAD

**Issue by boardy** [getinsomnia/insomnia#1578]
- Insomnia Version: 6.5.4
- Operating System: Windows 10

## Details

It looks like there's some issue with synchronisation. I'm not 100% sure what caused it, or when it happened but just noticed when going to the workspace switcher I seem to have a lot of workspaces called "Insomnia" as shown in the attached screenshot. 

![Insomnia Workspaces](https://user-images.githubusercontent.com/4533555/60204461-ca428300-9846-11e9-8c52-ca299360fbb9.PNG)

**Comment by gschier** [comment]
Hi @boardy,

This is likely from logging into new machines (or other team members doing so) and accidentally enabling sync (an easy thing to do by accident) for the default workspace. There may be other reasons for this happening but that seems most likely.

If you send an email to support@insomnia.rest with your account email I can take a look on my end to makes sure it's not a sync bug.

**Comment by boardy** [comment]
Hi @gschier Sorry for late reply. 

I have gone onto new machines (or mostly reinstalled machines), I don't remember turning the sync on but I guess I must have done. 

As it seems to only be duplicating the default one, I think it probably from what you said is more likely to be user error than a sync issue. 

I've cleared out the duplicate defaults and turned sync off, I'll keep an eye out in case I notice it do it again. 

Cheers

Chris

**Comment by gschier** [comment]
Thanks for the detailed reply Chris! I will also see if there's anything that can be done on the application side to make this easier
