### ISSUE TITLE
[Feature Request] Proxy capture requests

### ISSUE THREAD

**Issue by themotu** [getinsomnia/insomnia#1579]
Would be awesome to capture requests made and responses via proxy for mobile dev.

**Comment by gschier** [comment]
Thanks for the request @themotu!

If I understand the request correctly, this feature seems like it's likely too unrelated to Insomnia's core functionality (HTTP client) to implement. I would assume this would be better suited for a tool like Fiddler or Charles Proxy (maybe they already have it).

**Comment by themotu** [comment]
I just thought it would be nice because it would automatically show requests come in and then allow you to edit and re-request after instead of using something else then importing. Thanks though!

**Comment by gschier** [comment]
No problem, I appreciate the request :)

I just want to describe a bit more my reasoning more clearly for you, or anyone else, who might come across this. 

There are a lot of features, similar to this one, that are related to what Insomnia does but do directly fit in with its core use case. These have also been pushed to the side.

One of Insomnia's main advantages, opposed to more general API tools like Postman, is that it's simple and easy to use. Adding tangential features would make it more "powerful" but would bloat the interface, make it harder to maintain, and open it up to an even wider range of feature requests.

In the long term, I hope that functionality like this can be provided by a more robust set of plugin APIs. We probably won't get there for a while but that's the goal. 

I hope that helps explain the reasoning a bit more. Again, I don't think this is a bad request, we just need to draw the line somewhere for now.

:heart:
