### ISSUE TITLE
[Help] 5-second delay before requests sent

### ISSUE THREAD

**Issue by soubhikchatterjee** [getinsomnia/insomnia#1585]
- Insomnia Version:  6.5.4
- Operating System:  MacOS X

## Details
Before making a request, why does it count till 5 seconds? When I make the same request in Postman app it responds instantly.

Is this because I am using a free version of insomnia?

PS: The request is made to a server that is being served by a docker container (a simple nodejs app).

**Comment by gschier** [comment]
Hi @soubhikchatterjee,

Unfortunately, I've never heard of this happening before. There is nothing preventing Insomnia from sending requests immediately. One difference is that Insomnia sends requests using libcurl while Postman uses the Chromium network stack. 

I would guess that the delay might be coming from the DNS lookup. Maybe it's trying to lookup the host on the network before resolving it to a local IP address? Can you try changing `localhost` to `127.0.0.1` and see if that speeds things up?

**Comment by rrenteria-dev** [comment]
This is also happening to me. Seems like a cache DNS issue. If i dont make requests in insomnia for like.. 5 minutes. then i get the 5 second lag on the next request.

**Comment by dimitropoulos** [comment]
@rrenteria-dev if you have some way you know of that we can use to reproduce this please let us know the concrete steps and platform info (os and version, insomnia version).

I have personally never experienced this so the steps you provided above aren't enough (for me, anyway) to reproduce.

**Comment by rrenteria-dev** [comment]
> @rrenteria-dev if you have some way you know of that we can use to reproduce this please let us know the concrete steps and platform info (os and version, insomnia version).
> 
> 
> 
> I have personally never experienced this so the steps you provided above aren't enough (for me, anyway) to reproduce.

Of course. I'll figure out a way for you to reproduce. Thank you.

**Comment by mapleroyal** [comment]
I'm also experiencing this.
MacOS 14.5
Insomnia v9.3.2

If I don't make requests for a minute or so, it does "Sending Request" for exactly 5 seconds before actually sending it.

**Comment by LasseRafn** [comment]
same here, but for Postman! so I doubt its an Insomnia issue specifically

**Comment by mapleroyal** [comment]
@LasseRafn It's been a year, but if memory serves then I solved this by adding an extra line for the relevant urls in `/etc/hosts`.

For each url, I added one below it that uses `::1` instead of `127.0.0.1`.

For example:

```
127.0.0.1	some-site.url
::1		some-site.url
```

**Comment by LasseRafn** [comment]
@mapleroyal thank you thank you thank you thank you ----!! yes that did it. Much appreciated
