### ISSUE TITLE
How to not use environment variables?

### ISSUE THREAD

**Issue by icamys** [getinsomnia/insomnia#1588]
First of all I would like to thank you for your wonderful piece of software! It is very helpful.

I am trying to send in json body a string - `{{_ingest.timestamp}}` and it always is converted to environment variable. Is there any way to avoid the string conversion into variable?

**Comment by icamys** [comment]
For those who are looking for the answer to the same question, there is an option in request settings "Skip rendering of request body" that prevents rendering of environment variables.

![image](https://user-images.githubusercontent.com/6891299/60769092-70f31300-a0d4-11e9-99e4-170f4545daed.png)

**Comment by matthieusieben** [comment]
Is there no way to have it both ways ?

**Comment by sbor23** [comment]
> For those who are looking for the answer to the same question, there is an option in request settings "Skip rendering of request body" that prevents rendering of environment variables.
> 
> ![image](https://user-images.githubusercontent.com/6891299/60769092-70f31300-a0d4-11e9-99e4-170f4545daed.png)

This doesn't seem to exist anymore in the new design... Anyone has a workaround?

**Comment by iuribtt** [comment]
Any update?

**Comment by mls-will** [comment]
@iuribtt @sbor23 , I found it. After the latest update at least, you have to go to the request itself in the left-hand column, click the drop down menu next to the request name, and select 'Setting's. You will see the below:
![image](https://github.com/Kong/insomnia/assets/85503876/e479b6d6-3c24-4018-b244-714091fbeab7)

**Comment by allan-on** [comment]
Does anyone know if this is part of the documentation? Could it be added to the docs?
I couldn't find it in the docs and I had to search if there was a related issue here.

**Comment by wesleyeff** [comment]
I'm unable to open request settings in scratchpad mode. It asks me to login when I try to open it. Anyone else seeing this behavior?

**Comment by xyzones** [comment]
This is not working on 
```

Version: Insomnia 8.6.1
Build date: 2/5/2024
OS: Darwin arm64 23.3.0
Electron: 28.0.0
Node: 18.18.2
Node ABI: 119
V8: 12.0.267.8-electron.0
Architecture: arm64
```

Despite having removed the checkbox is still converting it

**Comment by dubdabasoduba** [comment]
This seems to work on version 9.3.2 for mac. I am just wondering why this can't be done globally?

**Comment by rgregg** [comment]
I found this setting for a regular HTTP request - but no equivalent for a WebSocket request. Is there a way to disable rendering for messages sent via websocket?

**Comment by modatwork** [comment]
this is a work around to use the raw template while enabling the rending feature.

define the environment variable with the template as the value:

```
"key1": "{{ key1 }}"
"key2": "value2" 
```

then in the request: 

```
this is the template we want: {{ key1 }}
this is the rendered text we want: {{ key2 }}
```

we got:

```
this is the template we want: {{ key1 }}
this is the rendered text we want: value2
```
