### ISSUE TITLE
[Bug] Import failed in case of Free-Form Object - OpenAPI 3

### ISSUE THREAD

**Issue by cseke** [getinsomnia/insomnia#1589]
- Insomnia Version: 6.5.4
- Operating System: Ubuntu 18.04

## Details

Import failed (`Cannot convert undefined or null to object`) when a Free-Form Object definition is in OpenAPI (v3) file.

For Example
```
openapi: 3.0.2
info:
  title: Free-Form Object test
  description: >-
    Free-Form Object test

servers:
  - url: http://127.0.0.1
    description: Free-Form Object test

paths:
  /admin-flavors:
    post:
      operationId: create_flavor
      requestBody:
        description: Create a flavor
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/flavor'
      responses:
        default:
          description: Unexpected error

components:

  schemas:

    'flavor':
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: a descriptive name
        extra_specs:
          type:        object
```

https://swagger.io/docs/specification/data-models/data-types/#object

```
        extra_specs:
          type:        object
```

**Comment by indiealexh** [comment]
Same issue, I generate my spec using Apicurio which often infers a null value in the example input json as an Object and breaks the import function of Insomnia, after I edit all the objects to strings the import function works.

**Comment by gschier** [comment]
Looks like this is fixed? The spec give in the original issue seems to work now

**Comment by cseke** [comment]
Confirmed, tested and works in 7.0.5, thank you.
