### ISSUE TITLE
[Feature Request] Schema Fetch

### ISSUE THREAD

**Issue by oscar-corredor** [getinsomnia/insomnia#1593]
- Insomnia Version: 6.5.3
- Operating System: Ubuntu 19.04

## Details

It would be nice to be able to force Insomnia to refetch the schema as during development it can evolve any minute.

Right now I am stuck with a schema version from 12 minutes ago which does not reflect the current state. This ends up in incorrect error reporting.
![image](https://user-images.githubusercontent.com/1540961/60831377-0a76ff00-a17f-11e9-9b9a-1f05e6cab061.png)

**Comment by gschier** [comment]
You can refresh the schema from the menu in the top-right of the query section

![image](https://user-images.githubusercontent.com/587576/60923696-4fb93080-a254-11e9-8aac-b410003add86.png)
