### ISSUE TITLE
[Question] how to customize the appended suffix when duplicate a request

### ISSUE THREAD

**Issue by Antisunny** [getinsomnia/insomnia#1596]
- Insomnia Version: v6.5.4
- Operating System: MacOS Mojave v10.14.5

## Details

Now when duplicated, the new request has a suffix `(Copy)`. If I duplicate this one again, another `(Copy)` will be appended, so on.

I wonder If there is a way to customize the `duplicate` action?

Like,

<img width="260" alt="image" src="https://user-images.githubusercontent.com/2398514/60869538-bee95180-a261-11e9-8c55-91b1c08c4a0b.png">

**Comment by gschier** [comment]
Hey @Antisunny,

There's no way to customize that behavior at this time no but that might be a cool API to allow plugins to hook into.

**Comment by robclancy** [comment]
I think the default is just not good. `(copy)` is never something you will keep, you will always have to rename right after duplicating. IMO it should ask you what to name it when pressing duplicate or at the very least do a number with it incrementing as you go.

**Comment by gschier** [comment]
This will be changed in the next release. It now prompts for a new name on duplication
