### ISSUE TITLE
[Bug] Request item is dragged when trying to select text

### ISSUE THREAD

**Issue by fjcpaschoal** [getinsomnia/insomnia#1601]
- Insomnia Version: 6.5.4
- Operating System: Linux (Mint and Xubuntu) and Windows Server 2012 R2

## Details

When renaming a request, if you try to select the text the item is dragged.

### Steps to reproduce
1 - Double clique on a request item to rename.
2 - Try to select the text using the mouse cursor.

### Exemple
![Peek 2019-07-13 12-09](https://user-images.githubusercontent.com/20227035/61173362-b1391200-a568-11e9-8427-20baa5994675.gif)

**Comment by fjcpaschoal** [comment]
The problem is no longer present in the current version of Insomnia (6.6.2). Thank you for fixing this bug!

**Comment by gschier** [comment]
Woops, I guess I forgot to close it in the commit. Thanks for reporting back! 😁
