### ISSUE TITLE
[Bug] OAuth Authorization data is not stored per environment

### ISSUE THREAD

**Issue by crtl** [getinsomnia/insomnia#1604]
- Insomnia Version: 6.5.4
- Operating System: Windows 10 Home

### Steps to reproduce
1. Setup request with OAuth 2 authorization
2. Request access/refresh tokens
3. Switch environments
4. Tokens are not cleared, requests are unauthorized

When using OAuth2 for authorization and switching environments the access/refresh tokens are not cleared. I have to manually clear/refresh them when switching environments.

I have only tested this with OAuth2.

In my opionion access tokens should be stored/cleared per environment, because environents are normally used to configure production and dev servers in the workspace and therefore normally never share authorization credentials.

**Comment by gschier** [comment]
Duplicate of #260
