### ISSUE TITLE
AWS Authentication signature fails with colon in the URL

### ISSUE THREAD

**Issue by GraemeAllanBryce** [getinsomnia/insomnia#1607]
- Insomnia Version: 6.5.4.2876
- Operating System: MacOS

## Details

For some AWS requests it is necessary to place an Amazon resource ID in the URL.  This can contain a colon as in "eu-west-1:034e2d6e-93be-4937-ad8f-99999999999". 

It is apparent that something fails in the signing of such requests.

**AWS returns an errror:** The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been ....

The headers are:
HTTP/2 403 
```
< content-type: application/json
< content-length: 704
< date: Thu, 18 Jul 2019 11:56:44 GMT
< x-amzn-requestid: 1d1473c4-a953-11e9-bc3d-2d38c9c62657
< x-amzn-errortype: **InvalidSignatureException**
< x-amz-apigw-id: dBOzeEOTDoEFaYg=
< x-cache: Error from cloudfront
< via: 1.1 d31720c3c9aa8c1463d4432230db8a9a.cloudfront.net (CloudFront)
< x-amz-cf-pop: LHR62-C2
< x-amz-cf-id: QYCjyXvILrm8M7bOeEeGzDF5lxhLWw-iE208e2a7T9dRq7xI3KuaZw==
```

Requests to the same endpoint and having the same credentials that do not contain a colon do not suffer this problem.

**Comment by gschier** [comment]
It looks like NodeJS's URL parse function doesn't like colons in hostnames. And, in fact, it seems as though colons are not valid in hostnames. Does AWS mention anything in their docs around this?

![image](https://user-images.githubusercontent.com/587576/63383609-f9123c80-c351-11e9-873b-3f34a62c1e0f.png)

**Comment by gschier** [comment]
Looks like Curl also fails on this 
![image](https://user-images.githubusercontent.com/587576/63383932-a6855000-c352-11e9-893a-42b0062897b7.png)
