### ISSUE TITLE
[Help] HTTPS request does not complete

### ISSUE THREAD

**Issue by chroth7** [getinsomnia/insomnia#1611]
Potential BUG report
When sending any request, e.g. a GET to any HTTPS resource, the request never completes.

Sending a request to a HTTP resource works.

Expected: I send a GET to e.g. https://www.google.com and it returns.
Observed: I just goes on and on and on. I do not see anything useful in the debugging view, just
```
[network] Sending req=req_57fcfd36772c4396ac1b776a0784b354
```
and then nothing, until I cancel.

If I export the req as curl:
```
curl --request GET \
  --url https://www.google.com/
```
and run it in iTerm (macosx mojave), it works.

Also, on my work machine it works as expected - just not on this laptop.

---

- Insomnia Version: 6.5.4.2876
- Operating System: OS X Mojave

## Details

See above.

Great software though, I really want to get this fixed. Any help appreciated.

**Comment by gschier** [comment]
After you cancel, do you see anything useful in the Timeline tab?

**Comment by chroth7** [comment]
@gschier here's an example (kept it open for 20sec):

```

* Preparing request to https://www.google.com/
* Using libcurl/7.52.1 OpenSSL/1.0.2j zlib/1.2.10
* Current time is 2019-08-02T06:51:38.324Z
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 2 cookies
*   Trying 172.217.168.36...
* TCP_NODELAY set
* Connected to www.google.com (172.217.168.36) port 443 (#4)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /opt/local/share/curl/curl-ca-bundle.crt
*   CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
```

**Comment by gschier** [comment]
I notice that you have a non-standard version of `libcurl` being used. Do you get the same version information when you run `curl --version` from the command line?

I'm also running Mojave and I get the following:

```
...
curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
...
```

**Comment by chroth7** [comment]
yes, good point: 

I just updated curl via homebrew and have now:
```
curl 7.65.3 (x86_64-apple-darwin18.6.0) libcurl/7.65.3 SecureTransport zlib/1.2.11
```

but insomnia is still 7.52.1
how can I change that? can't find anything in help files, sry

**Comment by gschier** [comment]
Installing `curl` from homebrew does not overwrite global libraries. See Caveats here:

![image](https://user-images.githubusercontent.com/587576/62646940-71720a00-b91d-11e9-967b-3cb79a4b95a3.png)

Have you ever installed a custom version of curl on your machine? ie. Do you know how you ended up with that other version installed?

I'm not actually sure how to do this off the top of my head but you likely have to overwrite your global libcurl version with the one from homebrew. I don't recommend doing this so proceed at your own risk if you desire. Or, perhaps there is a way to restore the default one that ships with macOS.

**Comment by chroth7** [comment]
Hey @gschier 

thanks for your help and effort - 

sadly, I don't know where that special version might be coming from. In this case, I will investigate some more in the next days and update this issue, should I find something. If you don't mind, I would keep it open for the time being, maybe I am not the only one with that sort of troubles.

Thanks, update will follow
(I desperately want to use Insomnia, as we share Insomnia configs for our projects/envs around the team - great piece of software!)

**Comment by chroth7** [comment]
FYI, no luck yet
