### ISSUE TITLE
[Feature Request] Export as OpenApi 3.0 

### ISSUE THREAD

**Issue by sbeyeler** [getinsomnia/insomnia#1612]
**[Feature Request]**
It would be hugely beneficial to be able to export an Insomnia workspace into the OpenApi (open-sourced Swagger) spec. There is currently a pretty big hurdle to taking an Insomnia workspace and putting it on a API documentation website, as most of the bigger ones out there take an OpenApi spec to automatically generate documentation. 

[Slate can convert from OpenApi](https://github.com/lord/slate/wiki/Slate-Related-Tools#converting-openapi--swagger-definitions-to-slate-compatible-markdown)
[Apiary supports their in-house as well as OpenApi](https://apiary.io/)
[Azure can import from OpenApi](https://docs.microsoft.com/en-us/azure/api-management/import-api-from-oas)
[Apigee can create an api-proxy from OpenApi spec](https://docs.apigee.com/api-platform/tutorials/create-api-proxy-openapi-spec)

This would also allow a more interoperable ecosystem, as I could send my insomnia workspaces to other teams who are not using Insomnia, allowing them to use their tool of choice to test our APIs. This is the key sticking point when it comes to getting approval for purchasing the Teams package as a company - as we don't want to promote a tool that will lock us into a specific ecosystem.

**Comment by misaku** [comment]
i would like see this too, because to be easy make documentation of project

**Comment by abitrolly** [comment]
@misaku need to open another issue.

**Comment by gschier** [comment]
See https://github.com/Kong/insomnia/issues/1778
