### ISSUE TITLE
Doesn't show interface in Windows 10

### ISSUE THREAD

**Issue by vasiledoe** [getinsomnia/insomnia#1615]
I'm using this app for my servers testing and I'm really happy with it, but unfortunately there is an unexpected issue. So app is started and pinned on bottom bar, when I put cursor on it it shows me preview as expected but when I click on it it doesn't open. Also if I click on launcher app icon it starts a new instance with exactly same behavior. I tried to uninstall and install it back but same behavior. 

I'm very disappointed since I have there some useful requests saved.

![image](https://user-images.githubusercontent.com/15106474/62105797-19e3f680-b2ac-11e9-92c1-5247d7f10108.png)

**Comment by gschier** [comment]
Sorry about this! It's a known bug that hasn't been able to be fixed yet. Please see this comment for a temporary workaround: https://github.com/getinsomnia/insomnia/issues/1255#issuecomment-502607674
