### ISSUE TITLE
don't copy tabs in "generate client code" for bash/curl

### ISSUE THREAD

**Issue by buster** [getinsomnia/insomnia#1617]
- Insomnia Version: 6.5.4
- Operating System: Debian
## Details

Copying and pasting a JSON HTTP Request with "generate client code-> curl" copies
tab characters in the clipboard. This makes the request not working in a shell (tabs become interpreted as auto completion tabs).

Please provide a way to
1) replace tabs with spaces in the curl/bash generation
or 2) configure tabs/spaces for the "beautify JSON" command

**Comment by gschier** [comment]
Please see the "Indent with tabs" option in the app preferences to change the beautify behavior:

![image](https://user-images.githubusercontent.com/587576/62473957-de47a180-b76f-11e9-9d9b-9aa7279d2d4f.png)

**Comment by buster** [comment]
Thanks. I was looking into the preferences but somehow i missed it..
