### ISSUE TITLE
[Feature] Sortable Environments

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#162]
Environments should be sortable just like the items in the request sidebar.

**Comment by FlyteWizard** [comment]
<img width="571" alt="Environment Sidebar Sort" src="https://cloud.githubusercontent.com/assets/10472448/25916672/5df70e18-357a-11e7-8baf-7a81aff2fabc.png">

Are you thinking of a click and drag?

**Comment by gschier** [comment]
@FlyteWizard possibly in the dropdown, but it might be easier to implement in the "Manage Environments" sidebar. However, if we got dropdown sorting working then it could also be used to sort workspaces in the main dropdown.

**Comment by FlyteWizard** [comment]
Awesome! I'll start working on this. 

- [ ] "Manage Environments" Sidebar
- [ ] Dropdowm Menu

**Comment by jroyal** [comment]
Click and drag reordering would be really nice.

**Comment by FlyteWizard** [comment]
@jroyal If you would like to work on this, it is now free for the taking :D

**Comment by gschier** [comment]
@FlyteWizard I didn't realize you edited your previous message (GitHub doesn't notify of edits apparently). I can also take this on if I can find some time.

**Comment by jroyal** [comment]
I'll give this a shot as I get some free time this weekend and upcoming week.

**Comment by gschier** [comment]
Awesome, @jroyal! Let me know if you need any guidance 😄

**Comment by kkragenbrink** [comment]
Oi.  Bad Stale-bot.  This is important.

**Comment by gerrytan** [comment]
Omg thx so much @gschier, this has been killing me now I got dozens of envs

**Comment by gschier** [comment]
😄
