### ISSUE TITLE
[UX] Right click sidebar background should show the same options you get from the plus icon

### ISSUE THREAD

**Issue by robclancy** [getinsomnia/insomnia#1625]
Right click sidebar background should show the same options you get from the plus icon that has "New Request" and "New Folder".

**Comment by gschier** [comment]
Good idea!

**Comment by duydosomething** [comment]
I'd like to work on this!

**Comment by bartier** [comment]
@duydosomething Hi! I'm going to try then. I'm going to dedicate to implement this feature.

I'll update if I'm struggling with something (This is going to be my first contribution so you never know haha).

**Comment by ranjan-purbey** [comment]
@bartier @duydosomething any updates on this?

**Comment by bartier** [comment]
@ranjan-purbey Actually no, I'm new to React & Electron, so I couldn't make much progress to do this issue. Feel free to take it If you would like to work on. =]

**Comment by NilayMajorwar** [comment]
Can I work on this one?

**Comment by ranjan-purbey** [comment]
@NilayMajorwar let's wait for @duydosomething 's reply for a couple of days. In case we don't get any update, you can take it up

**Comment by duydosomething** [comment]
@ranjan-purbey @NilayMajorwar Sorry for the late reply! I haven't had time to work on this so feel free to take it :)

**Comment by elemanhillary** [comment]
has this been implemented @ranjan-purbey @NilayMajorwar

**Comment by NilayMajorwar** [comment]
Nope, totally forgot this one :sweat_smile:! You can take it up if you want.

**Comment by elemanhillary** [comment]
@ranjan-purbey @NilayMajorwar this one i think has been already implemented by @gschier , which version are you using of insomnia
look at the screenshot below
<img width="247" alt="Screen Shot 2019-11-13 at 22 21 31" src="https://user-images.githubusercontent.com/14273401/68801074-00e93080-0664-11ea-8028-7035d530d654.png">

**Comment by ranjan-purbey** [comment]
@elemanhillary No it hasn't been implemented. What you have in the screenshot is the menu that you get by right clicking on a folder. Whereas what is being requested here is that you should get a menu containing only the first two options from your screenshot, when you click on the background (i.e. empty space) in the side-panel, much like what you get by clicking on the "plus" icon in the side-panel.

**Comment by elemanhillary** [comment]
@ranjan-purbey am on that i will implement your feature surely
