### ISSUE TITLE
[Bug] Snap doesn't start on Wayland on Linux

### ISSUE THREAD

**Issue by articlecat** [getinsomnia/insomnia#1630]
- Insomnia Version: 6.6.2
- Operating System: Arch Linux

## Details

The insomnia snap doesn't start on Wayland on Linux. When insomnia is run from the shell, the error message is:
```
(insomnia:12259): Gtk-WARNING **: 01:54:29.144: cannot open display: :0
```

**Comment by gschier** [comment]
Seems related to #1622

Some weird stuff has been going on with the Snap package I think. To my knowledge, nothing should have changed in the packaging process so it's hard to pin down what happened.

**Comment by gschier** [comment]
For Wayland, specifically, I think we'd be depending on ElectronJS to support it and it looks like there aren't currently any plans for that. See https://github.com/electron/electron/issues/9056

**Comment by esvm** [comment]
I'm having the same error on Fedora 30 when try to start Insomnia installed via snap

**Comment by altwohill** [comment]
I get the same error. Interestingly using the AppImage package https://updates.insomnia.rest/downloads/linux/latest works fine

**Comment by McEazy2700** [comment]
Damn this is 2023, and I'm still having this issue.

**Comment by bmarwell** [comment]
I switched to Manjaro, so I can install the native app from AUR… I agree it is sad that this doesn't work.
In the meantime I ditched snap entirely. I use a few app images and flatpack, but that's about it. Too many problems with snap.
