### ISSUE TITLE
Auto-complete has broken for existing requests on 6.6.2 update

### ISSUE THREAD

**Issue by LunaticoCR** [getinsomnia/insomnia#1631]
- Insomnia Version: 6.6.2
- Operating System: Mac OS

## Details

This is a weird one, it just started happening after I upgraded to 6.6.2. The auto-complete is not working in some cases for already existing requests. Here's the steps I follow to reproduce:
1. Look for an existing request that already has some JSON in the body, but that JSON doesn't contain any variables
2. Go to one of the JSON fields and try to replace it's value with a variable, delete the text and hit ctrl+space, the auto-complete should popup, but it doesn't

It seems to happen only on already existent requests that don't have variables in it, on existing request that already have variables the auto-complete does open, and on newly created requests it does work fine.

**Comment by gschier** [comment]
Hmm, unfortunately I cannot reproduce this. Can you please check View > Toggle DevTools to see if there are any errors?

P.S. Version 6.6.3 does not exist. Did you mean 6.6.2?

**Comment by LunaticoCR** [comment]
Sorry, type in the version! Yes the latest 6.6.2.

No errors in the DevTools Console.
![image](https://user-images.githubusercontent.com/2124383/62721464-2a127900-ba04-11e9-87df-4af47eafa0fa.png)

**Comment by gschier** [comment]
That's so odd. Can you post a screenshot of your cursor position when trying to trigger autocomplete?

**Comment by LunaticoCR** [comment]
![image](https://user-images.githubusercontent.com/2124383/62770254-8cb25600-ba92-11e9-819a-2825ef78070d.png)

I've tried in many different places, originally the json is much bigger than what's on the screenshot, I trimmed it down to remove sensitive info.
Auto-complete in the url field does work.

**Comment by gschier** [comment]
Did you by any chance have rendering of the request body disabled in the settings of that request?
