### ISSUE TITLE
[Bug] Font weight changed after 6.6.2

### ISSUE THREAD

**Issue by jaredmeakin** [getinsomnia/insomnia#1632]
- Insomnia Version: 6.6.2
- Operating System: Mac OS **10.14.5**

## Details

After opening Insomnia today my editor's font looked super weighted. Not sure if we changed rendering/aliasing or something, but all my fonts are on system defaults.

![image](https://user-images.githubusercontent.com/16892551/62703515-0a049a80-b9af-11e9-8171-23abdf074c53.png)

I was able to find an old screenshot of the sidebar for comparison.

**Old font-weight**
![image](https://user-images.githubusercontent.com/16892551/62703358-a7130380-b9ae-11e9-9ae7-3dbd01e51576.png)

**New font-weight**
![image](https://user-images.githubusercontent.com/16892551/62703354-a4b0a980-b9ae-11e9-92c0-9a2c4eca4ab3.png)

**Comment by gschier** [comment]
I'm not sure I would consider this a bug but you're right, something definitely changed. It looks like the Electron version changed from 3.0 to 3.1 in the last release. Maybe that has something to do with it? 

I think the question is... is this a bad thing? I've had numerous complaints before that font rendering was too skinny and hard to read for some people (especially on Windows and Linux).

**Comment by jaredmeakin** [comment]
When I first encountered it the difference was definitely stark. However, at this point it's something I can live with. If it hasn't been noticed by, or impacted, other users I'd say at this point we close out the issue. Thanks!
