### ISSUE TITLE
[Bug] [Documentation Error] GraphQl Documentation link: https://support.insomnia.rest/article/61-graphql still lists a schema browser as a future feature

### ISSUE THREAD

**Issue by ryan-mccartney** [getinsomnia/insomnia#1634]
## Details

The GraphQL Documentation on the website https://support.insomnia.rest/article/61-graphql
still lists a GraphQL Schema/Documentation browser as a WIP feature, despite its recent release.

> Documentation Browser
Insomnia does not currently provide a GraphQL documentation explorer but this is something that is being considered for the future.

**Comment by gschier** [comment]
Thanks for pointing this out! I've just updated it to reflect the new documentation explorer changes.
