### ISSUE TITLE
[Bug] Error box doesn't appear after closing

### ISSUE THREAD

**Issue by aso824** [getinsomnia/insomnia#1643]
- Insomnia Version: 6.6.2
- Operating System: Mint 19

## Details

While using GraphQL, when refetching schema fails, the red error box appears with details. If I accidentialy close this box, after next refresh, which was triggered manually, I don't see any error message - only "schema not yet fetched". For now, I'm using devtools console, but I'd like to see error box again after unsuccessful manual refreshing schema. It took me a while to figure out why schema was not fetched and error box doesn't appear.

Steps to reproduce:
1. Try to fetch schema with error - in my case, it was bug with introspection in client, probably
2. Close message box with error
3. Use "Refetch schema" again

Result: no error box appears

Also, when backend respond with 500, how I can see the response? In timeline, I see only "Received X B chunk", but I need to use cURL to see full response.

**Comment by gschier** [comment]
Ah yes, the box does not reappear after it is closed, unless you switch requests or restart the app.

I will update the logic to make it "forget" whenever the schema is refreshed manually. Thanks for the suggestion! 🤗

**Comment by gschier** [comment]
For the errors, if you click the green bug icon, you will be able to see more details on why it failed to refresh the schema.

![image](https://user-images.githubusercontent.com/587576/63371928-e1c75500-c339-11e9-8fdc-f3bfb0f706db.png)

**Comment by aso824** [comment]
Thanks, this will be great for newcomers and me, cause I always close that window ;)

If 500 error was returned, I won't see response in timeline tab, as I wrote above:

> Also, when backend respond with 500, how I can see the response? In timeline, I see only "Received X B chunk", but I need to use cURL to see full response.

How I can see what backend respond?

**Comment by gschier** [comment]
Oh I see what you mean. There's no way currently to view the response body in the Timeline tab but we can probably add a "body" tab to that dialog to display the body. Can you open a new issue for that?

**Comment by aso824** [comment]
Thanks for fix. Sure, but I'll try to make this - I wasn't aware that app is written in React :smile: 
If I don't have time for that, I will open issue.
