### ISSUE TITLE
[Bug] Yarn error when trying to install plugin

### ISSUE THREAD

**Issue by aso824** [getinsomnia/insomnia#1648]
- Insomnia Version: `6.6.2`
- Operating System: `Linux Mint 19 (64-bit)`

## Details

**When** I open _Plugins_ tab in _Preferences_
**And** I type anything in box near button "Install Plugin", then I press that button
**Then** red box with error is displayed:

> Yarn error /snap/insomnia/32/insomnia: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

**And** I see in DevTools only this new line: 

> [plugins] Fetching module info from npm

Insomnia is installed via Snap. Only `npm` is installed in OS.

**Comment by gschier** [comment]
Looks like you're experiencing the same thing as in https://github.com/getinsomnia/insomnia/issues/905

The workaround, for now, is to manually install the plugin within the plugins folder using NPM.

**Comment by asyba** [comment]
Similar issue:

![image](https://user-images.githubusercontent.com/1466530/74967851-8c5b2600-53f8-11ea-8ab9-6f26a3dbb20e.png)

**Comment by DamienGarrido** [comment]
Similar issue on Ubuntu Focal :
`Error: Yarn error /snap/insomnia/166/insomnia: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory`

**Comment by Nditah** [comment]
## [Error Installing Plugin in Insomnia](https://docs.insomnia.rest/insomnia/install)

If you installed insomnia via snap, you will encounter this error if you try installing plugin.
![Screenshot from 2022-05-10 09-24-42](https://user-images.githubusercontent.com/32549876/167585062-b4e35c61-e14a-40c1-841d-7636020a75f0.png)

SOLUTION

Remove insomnia
    `snap remove insomnia`

Then

```bash
# Add to sources
echo "deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all" \
    | sudo tee -a /etc/apt/sources.list.d/insomnia.list

# Refresh repository sources and install Insomnia
sudo apt-get update
sudo apt-get install insomnia
```
