### ISSUE TITLE
Using self signed SSL cert: Clicking "Disable SSL Validation" helper button opens up settings dialog with no disable ssl validation option

### ISSUE THREAD

**Issue by deslee** [getinsomnia/insomnia#1651]
The first result on google is a link to a twitter post with a completely different UI. I need to turn off SSL validation to test locally. Please, make it clear how to disable SSL validation in the UI because I've been looking for almost half an hour and I can't find it.

**Comment by gschier** [comment]
Glad you were able to find it 😊

**Comment by isansahoo** [comment]
Having same issue. I can't find where to disable the SSL certificate. Anyone could help me to locate it? Using v7.1.1

**Comment by leonardofa** [comment]
Y can go to Settings on Request/Response disable validate certificates

![image](https://user-images.githubusercontent.com/11917146/79597113-19002880-80b8-11ea-8017-ef924c3eb5d3.png)

**Comment by aaronmannino** [comment]
> Y can go to Settings on Request/Response disable validate certificates

I think the problem is that our eyes are looking for "SSL" and not finding this string. 🙂 Maybe it should say "Validate certificates (SSL)"

**Comment by krossekrabbe** [comment]
@aaronmannino Yes, exactly that is the problem. I was looking for SSL as well and could not find the setting until I googled this issue. Should be renamed to "Validate SSL certificates"

**Comment by aviranco** [comment]
> Found it, it just moved to the middle of the dialog window. Maybe it's time for me to take a break...

Its a challenge, making sure you are investing your time in the right things

> > Y can go to Settings on Request/Response disable validate certificates
> 
> I think the problem is that our eyes are looking for "SSL" and not finding this string. 🙂 Maybe it should say "Validate certificates (SSL)"

Indeed. Or even better open the popup on the relevant field/highlighted.

**Comment by guma256** [comment]
I managed to get it through the following steps
1- Go to Application
2- Select preferences
3- Under general tab scroll down to **Request/ Response** section.  and unchecked **validate certificates** to Disable SSL Validation

**Comment by goofballLogic** [comment]
It would save people a lot of time if you used similar words on the suggestion button "Disable SSL Validation" to the text of the option "Validate certificates"

For some users (me) we automatically scan for the words suggested by the button when trying to carry out the action and the number of options on this dialog makes finding it hard.

**Comment by devbkk** [comment]
Thank you for sharing.

**Comment by fall1600** [comment]
I find this setting so many times until I read this chain
Thank you so much
