### ISSUE TITLE
[Feature Request] Whitelist for Validating SSL Certificates

### ISSUE THREAD

**Issue by alexclst** [getinsomnia/insomnia#1654]
- Insomnia Version: 6.6.2
- Operating System: macOS 10.14.6

## Details

As a follow-up to #1081, Insomnia should have an option to whitelist addresses for SSL certificate validation. Maybe it can even be part of the environment.

I use [Local by Flywheel](https://localbyflywheel.com) to run my development servers. Self-signed certs are generated for HTTPS with Local. I understand that Insomnia cannot validate these certs. But since I want cert validation for all live servers, I need to toggle the preference when switching between dev and live requests. Creating a whitelist of addresses that Insomnia won’t try validating the certs for, while validating every other address’ cert, would eliminate the need for this toggling.

**Comment by tomarsachin2271** [comment]
Any progress on this?
