### ISSUE TITLE
Add default filename with date for exports

### ISSUE THREAD

**Issue by melvinsh** [getinsomnia/insomnia#166]
Hi @gschier,

I'd really like to have better names for exports. In my macOS env it currently uses `Untitled.json` by default. I already wrote some code that generates a much better name. You can check it [here](https://github.com/getinsomnia/insomnia/compare/master...melvinsh:named-export). Please let me know what you think of it.

![screen shot 2017-05-08 at 13 21 51](https://cloud.githubusercontent.com/assets/1312973/25803088/951fd2ca-33f5-11e7-8de9-f729f38ea27e.png)

**Comment by gschier** [comment]
I like it. I created a PR (#167) from your fork. Just had one comment about the name.

**Comment by gschier** [comment]
I merged your PR in with a few minor changes: https://github.com/getinsomnia/insomnia/pull/169

**Comment by melvinsh** [comment]
👍
