### ISSUE TITLE
[Feature Request] Duplicate Sub Environments

### ISSUE THREAD

**Issue by mxmlnglt** [getinsomnia/insomnia#1660]
I'd like to see the possibility to duplicate Sub Environments (the same way we can duplicate Requests, either via right-click menu or Ctrl+D).

- Insomnia Version: 6.5.4
- Operating System: Windows 10 Professional (64-bit)

## Details

Why?

Because right now there aren't Sub-"Sub Environments".
It's useful when you have various combinations of settings, sometimes you'd want to only change a slight part of them. So right now, you have to create an extra Sub Environment, then copy-paste the source settings. That could easily be done via a Duplicate feature.

Probably easier than refactor the whole thing to have "Sub Sub Environments".

**Comment by ranjan-purbey** [comment]
@gschier @mxmlnglt Since the feature has now been merged, can we close this issue?

**Comment by mxmlnglt** [comment]
Yes we can. /close
