### ISSUE TITLE
[Feature Request] Convert HTML/XML entities in responses

### ISSUE THREAD

**Issue by l523402485** [getinsomnia/insomnia#1663]
- Insomnia Version: ___6.6.2
- Operating System: ___Windows 10

## Details

<a href="https://sm.ms/image/cSrg2FlDHNLTOaU" target="_blank"><img src="https://i.loli.net/2019/09/04/cSrg2FlDHNLTOaU.png" ></a>

**Comment by gschier** [comment]
Insomnia does not currently convert [XML/HTML Entities](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references), which is what you are seeing, when displaying response content.

Perhaps there could be a setting to enable this, or it could automatically convert them in "Visual Preview" but not in "Source Code" mode.

**Comment by l523402485** [comment]
Sorry, that's not clear enough.
That is in "Visual Preview" mode.

<a href="https://sm.ms/image/aULcTVtjgXvH3bq" target="_blank"><img src="https://i.loli.net/2019/09/05/aULcTVtjgXvH3bq.png" ></a>
