### ISSUE TITLE
Copy/cut context action is ignored

### ISSUE THREAD

**Issue by RonyOCuinn** [getinsomnia/insomnia#1664]
- Insomnia Version: 6.6.2
- Operating System: Windows 10 1803 (OS Build 17134.984)

## Details

Selecting text in any text input field, right clicking and selecting copy does not place the selected text in the clipboard. Selecting text and copying from the context menu in non-input fields (E.G. response preview) works fine.

Using `Ctrl` + `C` works fine in all locations. This is not an issue [with my mouse](https://github.com/getinsomnia/insomnia/issues/253) or an issue [appearing in other applications](https://github.com/getinsomnia/insomnia/issues/392). It has persisted through restarts.

## Steps to reproduce
1. Select text in any input field.
2. Right click
3. Select copy or cut
4. Try to paste

**Comment by gschier** [comment]
Would you be able to provide a screencast of this? I can't seem to reproduce the problem

**Comment by RonyOCuinn** [comment]
I've come into work this morning and booted up my laptop and now the problem doesn't exist. I'm absolutely sure this occurs after a while. I'll continue to monitor it.
