### ISSUE TITLE
[Question] Better development setup instruction

### ISSUE THREAD

**Issue by Toumash** [getinsomnia/insomnia#1672]
Operating System: Windows 10 64 bit

I was trying to setup a dev environment on windows and there is a problem when following the instruction from the readme.
Running `npm run bootstrap` gives unknown error (no vcbuild.exe in verbose mode), and the final solution ([taken from here](https://stackoverflow.com/a/39235952/3711660)) is to run
```shell
npm install -g --production windows-build-tools
```
Is it obvious to someone who does electron development?
If so, close this issue ;) If not, please include it in the readme

**Comment by gschier** [comment]
Great suggestion! Just added it to the README
