### ISSUE TITLE
[Bug] Sync pending stuck

### ISSUE THREAD

**Issue by MatteoGioioso** [getinsomnia/insomnia#1678]
Trying to sync my account with two installations of insomnia, however it says sync pending 0% and it has been there for hours, so I guess something is wrong.

- Insomnia Version: 6.6.2
- Operating System: Ubuntu 18.04.3 LTS (both OS)

**Comment by gschier** [comment]
Hi @MatteoGioioso, can you send an email to support@insomnia.rest from your account email so I can take a look?

**Comment by MatteoGioioso** [comment]
@gschier Hey, thanks for the answer.
Just to make one thing clear, if the trial period is expired, does the sync still works? Or is it only available for the paid plan?
Thanks

**Comment by gschier** [comment]
Sync is the core features of the paid plan so it will stop working once the trial has expired.

**Comment by MatteoGioioso** [comment]
Ok, then in this case it works as expected since my plan just expired. Thanks for clarifying.
