### ISSUE TITLE
OAuth 1.0 - incorrect signature if special characters in query

### ISSUE THREAD

**Issue by IlyaMar** [getinsomnia/insomnia#1681]
Problem
Request params are being url-encoded twice during OAuth signature calculation. OAuth specification requires only signle url-encoding: https://oauth.net/core/1.0a/#rfc.section.9.1. As result, Insomnia cannot work with our OAuth-protected resource.
 
Details
I issue a GET on this url:
https://ehdjo.brndc83d32b6-cad3dc.aqa.int.zone/aps/2/resources?a%20c

Insomnia generates the following authorization header:
Authorization: OAuth oauth_consumer_key="VcaXEa9a5tGp3vROx6xNLgVnv9LXT4N8", oauth_nonce="UnhVTy", oauth_signature="GET%26https%253A%252F%252Fehdjo.brndc83d32b6-cad3dc.aqa.int.zone%252Faps%252F2%252Fresources%26a%25252520c%253D%2526oauth_consumer_key%253DVcaXEa9a5tGp3vROx6xNLgVnv9LXT4N8%2526oauth_nonce%253DUnhVTy%2526oauth_signature_method%253DPLAINTEXT%2526oauth_timestamp%253D1506018545%2526oauth_version%253D1.0", oauth_signature_method="PLAINTEXT", oauth_timestamp="1506018545", oauth_version="1.0"

Please note I've selected signature method = plaintext for debug purposes.
From this signature we can see that SignatureBaseString contained urldecode("a%25252520c") =  "a%252520c" substring corresponding to request parameters. This means that original request parameters "a%20c" was url-encoded twice:
urlencode(urlencode("a%20c")) = "a%252520c"

More detailzation about OAuth 1.0a spec:
Section 9.1.1. "Normalize Request Parameters" shows that request params are taken as is, without additonal url-encoding, to normalized param string. Params are url-encoded here but it's how they exists in original request url.
Section 9.1.3. "Concatenate Request Elements" says we need to url-encode normalized param string.
So, there is only 1 url-encoding of params during OAuth signature calculation.

- Insomnia Version: ___
5.16.6
- Operating System: ___
Windows 10 x64

![insomnia_oauth_urlencode](https://user-images.githubusercontent.com/2982960/65426792-9cef7c00-de19-11e9-91cf-86906f603b60.png)

**Comment by gschier** [comment]
The reason for this is likely not OAuth-related, but instead has to do with Insomnia's preference to automatically encode special characters.

Does it work if you instead use the unencoded value?

`https://ehdjo.brndc83d32b6-cad3dc.aqa.int.zone/aps/2/resources?a c`
