### ISSUE TITLE
[Feature request] Export API from UI by folder

### ISSUE THREAD

**Issue by aloisdg** [getinsomnia/insomnia#1683]
- Insomnia Version: 6.6.2
- Operating System: Windows 10 Pro 1809

## Details

Coming from Postman to Insomnia, I missed a feature from Postman. There you are able to export a json API by folder.

![image](https://user-images.githubusercontent.com/3449303/65495353-ee017d80-deb6-11e9-84ab-3a7ab1b72ab5.png)

The basic use cases is to share just a single collection instead of a everything to another developer.

Could we have the same feature on Insomnia?

Thank you,

Related to #1661

**Comment by gschier** [comment]
Insomnia sort-of does this already, although it's a bit harder to access. If you go to export a workspace, you are presented with an option to select the folders to include.

![image](https://user-images.githubusercontent.com/587576/65535991-5e100380-deb7-11e9-83e3-0e8f32a7d22f.png)

If you've tried this method before, can you provide some insight as to why this doesn't work for you?
