### ISSUE TITLE
[Feature Request] Automatically parse query parameters from URL

### ISSUE THREAD

**Issue by EugeneAbramchuk** [getinsomnia/insomnia#1684]
When creating a new request and pasting a new URL like
`https://some.service.rest/api/method?aaa=bbb&ccc=ddd`
it would be a major time saving feature if one could turn on an option of Insomnia automatically trimming the URL into:
`https://some.service.rest/api/method`
and populating the query fields:
```
aaa=bbb
ccc=ddd
```

As the requests grow long, it's becoming a nuisance.

**Comment by gschier** [comment]
Just wanted to make sure you're aware that there _is_ a button in the query tab to import the params from the URL.

If this were automated, when would you expect it to happen? I feel like it would be useful when pasting text into the URL but can't think of any other scenarios.

**Comment by EugeneAbramchuk** [comment]
You are totally right @gschier, I apologize. Consider the issue closed :)
