### ISSUE TITLE
Error: Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by cbalano** [getinsomnia/insomnia#1685]
- Insomnia Version: 6.6.2
- Operating System: Windows 10 on Desktop PC

When I am trying to access an SSL endpoint on my private domain, I see the error in the title.

Perhaps the error goes away if I uncheck "Validate certificates" in "Preferences", but I do not want to do that. I want to use SSL verification.

There is ZERO information about why Insomnia does not simply read the global certificate store, or where in the world it looks for root CA certificates on Windows.

If it looked in the global Windows certificate store t would have found a shiny trusted root certificate (self signed) with my private domain name in it. 

So my question is: how do I direct Insomnia to read my private root CA, and therefore I do not need to disable "Validate certificates" in Preferences?

**Comment by gschier** [comment]
On Windows, Insomnia uses a [bundled CA certificate](https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt) that is included in the build.

There's no way to define your own at the moment or to use Window's global cert store. For now, disabling SSL validation is the only option.

There's an open issue to improve support for this in the future: #675

**Comment by xorock** [comment]
Is Insomnia holding any copy of the certificate? The server certificate has expired, it has been replaced by the current one and I am getting this error message even though everything has returned to normal in the regular browser. There was no problem before the certificate expired.

**Comment by Tilogorn** [comment]
@xorock Currently facing the same issue. What was your solution?
