### ISSUE TITLE
Unresponsive

### ISSUE THREAD

**Issue by sandeeepbethu** [getinsomnia/insomnia#1686]
- Insomnia Version: ___6.6
- Operating System: ___Mac Mojave

## Details
I tried pasting some large content by mistake under the url while creating a fresh request, ever since Insomnia has become unresponsive even after multiple tool reloads and machine re starts.... how can I get this back to life without losing my existing bookmarks!!!

**Comment by gschier** [comment]
Hi @sandeeepbethu,

You should be able to local the long snippet you pasted in the Request database and delete it manually. The file in question is titled `insomnia.Request.db` and will be located here:

![image](https://user-images.githubusercontent.com/587576/65726698-87bd5c00-e06a-11e9-9167-333d44745f26.png)
