### ISSUE TITLE
Generate Code in Flutter Code Snippet feature

### ISSUE THREAD

**Issue by jedjie** [getinsomnia/insomnia#1693]
Can I request for a Generate Code in Flutter code snippet generate feature? thank you!

**Comment by gschier** [comment]
Hi @jedjie! The code snippets are provided from the [httpsnippet](https://github.com/Kong/httpsnippet) library. Please create an issue (and/or PR) over there.

**Comment by gschier** [comment]
Going to close this issue and defer further discussion on httpsnippet
