### ISSUE TITLE
missing spaces in json string responses

### ISSUE THREAD

**Issue by adelmang14** [getinsomnia/insomnia#170]
## Overview

- `Insomnia Version:` 5.0.20
- `Operating System:` Win10
- `Summary: ` If a Response is of type "application/json" and contains only a string, the spaces are sometimes not shown in the answer-preview.

**Comment by gschier** [comment]
Hi @adelmang14. Thanks for the report. I have reproduced the bug using the following response body:

```json
"Hello World!"
```

Becomes

```json
"HelloWorld!"
```
