### ISSUE TITLE
On Windows 10 the application window is nowhere to be seen.

### ISSUE THREAD

**Issue by b-hayes** [getinsomnia/insomnia#1702]
- Insomnia Version: 7.0.0
- Operating System: Windows 10

## Details

New to insomnia recently installed don windows 10.

Just tried opening the application again today and was presented with.. nothing.

The app is visible on the task bar I can minimize maximize and quit but cant see the window.
Close and re-opened the app multiple times.

Ended up doing an old work around in rare cases when apps go off the screen, 
hit `alt+space, m, arrow` then move the mouse.
This opens the window menu and select s move and the arrow key then binds the window position to the mouse.
This let me get the app window and pull it into view and seemed somehow the app window was moved off the screen downwards.

I am not sure how it ended up off the screen to begin with, maybe I was running a higher screen resolution at some point and it remembered its position when I closed it and then I changed back to a smaller screen resolution before opening it again.

**Comment by sarraktiti** [comment]
I have the same problem, I tried to reinstall it again but no luck !

**Comment by Roman-Jordan** [comment]
If your Insomnia App is loading off screen after Windows update KB4515384, make sure app is actively selected and press 'F11' this will load it in full screen. Fastest work around I have found...

**Comment by narration-sd** [comment]
Here's another, to get it  on screen until noticed and fixed.

Win-Shift-Up Arrow key gets it, and this also may work if where it originally is ends up on a second monitor.

Nothing I've found will make it hold position on restart, so it's good to have a way that doesn't involve full screen or mouse-moving it each time.

**Comment by sarraktiti** [comment]
> If your Insomnia App is loading off screen after Windows update KB4515384, make sure app is actively selected and press 'F11' this will load it in full screen. Fastest work around I have found...

Thanks Roman, this work around worked for me :)

**Comment by saschaende** [comment]
I have the same problem.

**Comment by Matthieu614** [comment]
I found out that if you delete the file named `bounds` located in `%appdata%\Roaming\Insomnia\localStorage` the window shows up correctly. 

But then the file get recreated, and on the next launch the bug still occurs if the file exists.

**Comment by maugustosemperfi** [comment]
In my case, Insomnia window appears on bottom of screen

![image](https://user-images.githubusercontent.com/26628274/66329304-ac37f480-e904-11e9-9cf9-759d2ab542cb.png)

**Comment by tebruno99** [comment]
Fresh install of windows. Only app installed is Putty. Installed insomnia and now it will only open at the bottom of the screen. If I move it, it will remember the Horizontal position but not the vertical when reopening.

![image](https://user-images.githubusercontent.com/24335/66340549-fe7c1400-e90a-11e9-9e86-7c914b7cb7cc.png)

**Comment by narration-sd** [comment]
confirm - on 7.0.1, window obeys Windows as expected
