### ISSUE TITLE
[Begginer] Contributing to the project 

### ISSUE THREAD

**Issue by bartier** [getinsomnia/insomnia#1709]
Hi guys,

I would like to start contributing to Insominia project but I'm not sure what is the "best" way to start.

For example:

Issue #1660 I would see the implementation of the 'Requests Duplicate Feature'  
![image](https://user-images.githubusercontent.com/18057391/66282990-0fd80880-e898-11e9-9fca-59cda7e19c81.png)
 File I guess I should look: https://github.com/getinsomnia/insomnia/blob/develop/packages/insomnia-app/app/ui/components/dropdowns/request-actions-dropdown.js

The following code I would put a breakpoint and see how this method is implemented to implement to environments:
```
 _handleDuplicate() {
    const { request, handleDuplicateRequest } = this.props;
    handleDuplicateRequest(request);
  }
```

I know this issue is already solved by a PR, it is just a example :)

By the way, is it possible to attach a debug in the function above? 

Anyway, if anyone could suggest any content to learn more about insomnia structure/electron/react/redux/etc I would love :)

Thanks in advance.

**Comment by gschier** [comment]
Insomnia is an Electron application, which means you can debug it the same way you would debug a website.

Personally, I usually add `console.log(...)` commands then view them in DevTools (View > Toggle DevTools) but I've heard other people hook up their IDE's debug tools to Electron somehow (I'm not sure how to do that). 

I would say the best way to learn is to do what you have already started doing which is to take a look at other pull requests and get a feel for how the application is structured. And, if you want to learn a technology to help develop Insomnia, I suggest learning the fundamentals of React and Javascript. That should be enough to get started.

**Comment by bartier** [comment]
Thanks for your attention to answer me. I am going to learn Javascript and React. Maybe someday I'm be able to contribute somehow to Insomnia. :)

I think this issue can be closed now. It was helped to give a direction where to start since I'm  beginning at open source projects.

**Comment by gschier** [comment]
Happy to help 😄 I hope to see you back here sometime in the future 🥇
