### ISSUE TITLE
[BUG] Viewing View > Help crashes Snap build

### ISSUE THREAD

**Issue by DmitryNefedov** [getinsomnia/insomnia#1710]
- Insomnia Version: 6.6.2
- Operating System: Ubuntu 18.04

## Details

Trying to export the whole workplace or even a single request crashes the whole app. It closes down and nothing happens.
Same when try to View -> Help.

Installed with `sudo snap install insomnia` as recommended 
No Plugins installed.

## Steps to reproduce

1. Open insomnia
2. Click on Workplace -> Import/Export -> Export data -> Current Workplace -> Next -> Insomnia4 format -> Done

## Expected behaviour
Workplace is exported

## Actual behaviour
Application crashes

**Comment by gschier** [comment]
Hmm,

**Comment by DmitryNefedov** [comment]
Seems to be fixed in snap `insomnia              7.0.1  `

Thanks!

**Comment by gschier** [comment]
Awesome! I don't think I changed anything so please let me know if you see it happening again.

**Comment by DmitryNefedov** [comment]
The latest snap version that fixed the issue is 7.0.1.
the issue was on 6.6.2
