### ISSUE TITLE
[Feature Request] Import query params on cURL paste

### ISSUE THREAD

**Issue by eliasmeire** [getinsomnia/insomnia#1713]
- Insomnia Version: 7.0.0
- Operating System: macOS 10.14.5

## Details

I think it would be convenient if the queryparams from a pasted cURL would be parsed automatically. There were some similar issues about this before (ex. #1684, #205).

I know about the `Import from URL` button at the bottom of the Query tab (though I only found out about it after reading through issues 😛), but I can't think of a reason for not having them parsed by default. I'm willing to work on this, if you agree it would be an improvement! :smile:

**Comment by Surendrajat** [comment]
+1 for this feature.
As testing with different query values is an essential part of API development, having auto parsing of queries from copied request saves one or more manual steps. I wonder why it's not a default.

**Comment by gschier** [comment]
This sounds like a good thing to implement! Let me know if you need any help 💯

**Comment by Surendrajat** [comment]
@eliasmeire if you could also remove the trailing `?` after parsing, it'll be great as I like API endpoint clean.

**Comment by eliasmeire** [comment]
Thanks @gschier !

@Surendrajat Sure, i'll keep an eye out for the trailing `?` :smile:
