### ISSUE TITLE
[Feature Request] Show enum information in GraphQL schema explorer

### ISSUE THREAD

**Issue by pingvinen** [getinsomnia/insomnia#1716]
- Insomnia Version: 7.0.1
- Operating System: Ubuntu 18.04

## Details

I noticed that the GraphQL schema explorer does not list the available values on enums.

An introspection query like the following will give the information about the given enum:

```
{
  __type(name: "SomeFancyEnum") {
    enumValues {
      name
      description
      isDeprecated
      deprecationReason
    }
  }
}
```

For me, using [HotChocolate for .Net Core](https://hotchocolate.io), the above returns something like:

```
{
  "data": {
    "__type": {
      "enumValues": [
        {
          "name": "REINDEER",
          "description": "Sleigh propulsion system",
          "isDeprecated": false,
          "deprecationReason": null
        },
        {
          "name": "SANTA",
          "description": "Flag a thing as being Santa",
          "isDeprecated": false,
          "deprecationReason": null
        },
        {
          "name": "SATAN",
          "description": "Flag a thing as being Santa",
          "isDeprecated": true,
          "deprecationReason": "Ooops.. typo"
        }
      ]
    }
  }
}
```

**Comment by carlespibernat** [comment]
I was going to open an issue to ask for this feature! 

In GraphQL there is a enum type which is a list of allowed values.

In many GraphiQL interfaces, the documentation shows all the allowed values that an enum can take. This is very useful for the users of the GraphQL API so they can see which values they can use when they are using the API

**Comment by gschier** [comment]
Ah yes, I just forgot to implement docs for enum types. Should be an easy addition! 👍

**Comment by carlespibernat** [comment]
I've also noticed that enum types docs aren't shown too!

**Comment by gschier** [comment]
How's this?

![image](https://user-images.githubusercontent.com/587576/68975008-1a9f8a80-07c0-11ea-8d83-1d9aede26e13.png)

**Comment by pingvinen** [comment]
Thank you for this @gschier. It is a very nice addition :)
