### ISSUE TITLE
[Bug] Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by joeldhenry** [getinsomnia/insomnia#1719]
- Insomnia Version: 7.0.1
- Operating System: Mac OSX 10.15

## Details
During Login, I get this error and cannot login.

![Screen Shot](https://user-images.githubusercontent.com/12555860/66542512-7ef67b00-eb7e-11e9-8754-aaff96ae8218.png)

**Comment by elemanhillary** [comment]
How do i reproduce this error

**Comment by gschier** [comment]
Responded via email
