### ISSUE TITLE
FeatureRequest: toggle on/off automatic cookie sending

### ISSUE THREAD

**Issue by sapeish** [getinsomnia/insomnia#173]
## Overview

- `Insomnia Version:` 5.0.4
- `Operating System:` macOS 10.12.3
- `Summary: ` be able to disable automatic cookie sending

While developing a WS it is very useful to be able to alway send requests without cookies. Currently I need to constantly go to cookies dialog and delete the cookie manually to have a clean request.
It would be very nice to be able to disable (toggle) automatic cookie sending, may it be globally or per Request.

**Comment by gschier** [comment]
It's a bit hidden, but you can do this in the request settings.

![image](https://cloud.githubusercontent.com/assets/587576/25907010/0dc57ca0-355b-11e7-8946-cc0a3e3c8345.png)
![image](https://cloud.githubusercontent.com/assets/587576/25907024/17b0b3f6-355b-11e7-967d-00a7fcbde876.png)

**Comment by sapeish** [comment]
Yes! that suffices, it's hidden but it's what I needed. Thanks

**Comment by gschier** [comment]
Ya, no worries. I should at least add it to the documentation so that it'll come up in a Google search.

**Comment by itsjms** [comment]
insomnia stop setting cookies solution
