### ISSUE TITLE
[BUG] Fails on MacOS less than Catalina 

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [getinsomnia/insomnia#1739]
- Insomnia Version: latest
- Operating System: macOS High Sierra 10.13.6

## Details

Insomnia was working perfectly yesterday. Today I turned on my machine and it won't load. I've screenshot the error below. I've uninstalled and re-installed but it didn't fix the problem. 

![image](https://user-images.githubusercontent.com/19767538/67101068-ed46c900-f18e-11e9-8324-8185d3c36f0a.png)

**Comment by giovanigenerali** [comment]
Here the same error:

![Screen Shot 2019-10-18 at 11 15 03](https://user-images.githubusercontent.com/41435/67101726-8e864d00-f198-11e9-94e3-5ad6d198bf12.png)

**Comment by gschier** [comment]
I just pulled 7.0.2 so no one else gets the update. Working on a fix now. I think this was related to the fact that the last build used GitHub Actions instead of TravisCI which runs in a newer macOS environment.

**Comment by daltonmenezes** [comment]
I just downloaded the app again from the website and now it works fine.

**Comment by gschier** [comment]
Can you all please verify that 7.0.3 works as well and note your OS version? 

Thanks! ❤️

**Comment by Jordan-Eckowitz** [comment]
working now - thanks for the quick fix!

**Comment by daltonmenezes** [comment]
@gschier Everything is working fine. <3

<img src="https://cdn1.imggmi.com/uploads/2019/10/18/de0d82dab849860f7a87d152b54b8a32-full.png"/>
<img src="https://cdn1.imggmi.com/uploads/2019/10/18/858b420a0b1fecce1f49859e99762bce-full.png"/>

**Comment by gschier** [comment]
Awesome! Now I can `GET` some `REST`

.
.
.

🚪🚶

**Comment by jpcmf** [comment]
Thank you for the fast fix guys! Awesome

**Comment by JoshMoreno** [comment]
Not working for me. 
7.0.2 - 7.0.6 via github releases and website `https://updates.insomnia.rest/downloads/mac/{{version}}` do not work for me.

7.0.1 works via the [website](https://updates.insomnia.rest/downloads/mac/7.0.1) and [github](https://github.com/Kong/insomnia/releases/download/v7.0.1/Insomnia-7.0.1.dmg)

Where can I get the Travis CI versions of the latest builds?

Mac Mojave 10.14.6

**Comment by gschier** [comment]
@JoshMoreno can you please create a new issue with your specific details?

you get to the releases on the changelog https://insomnia.rest/changelog/7.0.6
