### ISSUE TITLE
FeatureRequest: be able to see the full request sent

### ISSUE THREAD

**Issue by sapeish** [getinsomnia/insomnia#174]
## Overview

- `Insomnia Version:` 5.0.4
- `Operating System:` macOS 10.12.3
- `Summary: ` be able to see the full request sent

For debugging purposes it is very useful to be able to see the full request sent (like in Chrome Developer Tools). This way it is clearer what non-explicit info was sent: which headers were sent, which cookies were sent, etc.

**Comment by gschier** [comment]
Hey @sapeish. You can see this in the Timeline view of the response pane.

![image](https://cloud.githubusercontent.com/assets/587576/25906900/c5425bf6-355a-11e7-886a-eb7b9f48583e.png)

**Comment by sapeish** [comment]
Nice! that's new right? didn't spot it before. Thanks!

**Comment by gschier** [comment]
@sapeish yep, since version 5 😄

**Comment by SG5** [comment]
@gschier for `multipart/form-data` insomnia doesn't show full content, just `(15.2 KB hidden)`

**Comment by gschier** [comment]
Ya, it hides data chunks above a certain size by default to avoid cluttering the timeline. Feel free to make a new issue for that if you want.

**Comment by lewiscowleschipuk** [comment]
Just a note, this is not the _full request_. It looks like it's missing the body, which is sent (same as @gschier note, but in different language)
