### ISSUE TITLE
[Feature Request] Allow to export/import workspaces by copying/pasting from the clipboard

### ISSUE THREAD

**Issue by thejavascriptman** [getinsomnia/insomnia#1748]
- Insomnia Version: 7.0.3
- Operating System: Linux

## Details

It would be great if Insomnia could allow the user to export and import workspaces by using the clipboard, the changes to the UI would be minimal and it looks like a more convenient alternative to the file/curl method in some scenarios.

## Possible use cases:
* Insomnia is running on a remote machine (e.g. VNC over SSH)
* Insomnia is running in an isolated environment (e.g. Docker, VirtualBox)
* The user wants to share multiple requests over a messaging app such as Slack

Although in the previous scenarios the same could be accomplished by using the existing export/import functionality, it is more complex as it would require the user to preform additional steps such as forward ports (to avoid running Insomnia remotely) or create shared volumes/directories (if running inside Docker/VirtualBox)

### Export
![export](https://user-images.githubusercontent.com/46071365/67287820-c124a280-f516-11e9-82a5-0ecc75b6ee07.jpg)

### Import
![import1](https://user-images.githubusercontent.com/46071365/67287826-c550c000-f516-11e9-88c0-cb302bc2e991.jpg)

**Comment by elemanhillary** [comment]
I approve this feature though am not officially from insomnia am going to take courage and do it
