### ISSUE TITLE
[Bug] Snap does not support TLSv1.3

### ISSUE THREAD

**Issue by alexghr** [getinsomnia/insomnia#1757]
- Insomnia Version:
![image](https://user-images.githubusercontent.com/3816165/67939172-e2495b00-fbc8-11e9-981b-f70072a6678a.png)

- Operating System: Ubuntu 18.04

## Details

The snap-packaged version of Insomnia does not support TLSv1.3. After digging through the sources I think the issue is the old version of OpenSSL that's packaged with the snap:
https://github.com/getinsomnia/insomnia/blob/61b4c6e78dcb2bb95756382ce23dbd9a65f45b09/.github/actions/build-snap/install-dependencies.sh#L33

OpenSSL 1.1.0i (which is the next release after 1.1.0h, the one used in the Dockerfile) is the first OpenSSL release to support TLSv1.3

**Comment by gschier** [comment]
Thanks for pointing this out! Will get it updated for next release.
