### ISSUE TITLE
[Feature Request] Support for loading/saving from file for CVS sync

### ISSUE THREAD

**Issue by j0hnwhyte** [getinsomnia/insomnia#1758]
Other tools like Paw for Mac allow the user to save the workspace to a single file, which can be then added to a CVS system like git. A feature like this allows developers to rely more confidently on this tool because it's not bound to their system or a cloud service which may disappear at any time, but the data is saved in an easy to access shared space.

This way it becomes easier to work with the requests, and the app can become a long term investment for developer.

Also when working with several computers and different projects it's very convenient to just open a file instead of having to login to a specific account or anything like that. Using online accounts or cloud services is just clumsy and not useful. Also working with APIs under NDA requires having local storage, despite all the end-to-end encryption that the app can have, local is just better.

Just dumping and importing a database or a marshalled object could be enough.

**Comment by gschier** [comment]
Ah yes, this is quite a common ask, however, it's difficult to replace the current local database system with something file-based. 

You can, however, already dump/import a workspace from the preferences menu.

![image](https://user-images.githubusercontent.com/587576/67982158-84cd0280-fbf8-11e9-9abc-856a0fa84cda.png)

**Comment by j0hnwhyte** [comment]
I tried that, it's clumsy. As it's so quick to export data, why not making it a menu item, and making the app able to load its files? While you rightfully say it's hard to replace the database with a file-based solution, effectively it's already there, it just needs a few UX changes.

What else do you propose to store the data automatically in the CVS without having to do ten clicks every time the user writes a change in the UI to save the file?

**Comment by muuvmuuv** [comment]
Perfect way of doing this would be with a plugin which exports on save and imports the file it is newer than the current workspace. I think I have worked on something like that a while ago but the Insomnia API stopped me at some point, maybe you @j0hnwhyte have some time to look deeper into that and/or create a PR to expand the Insomnia API at some point?

**Comment by muuvmuuv** [comment]
In the meantime you can use the solution mentioned here, also related to this issue:
https://github.com/Kong/insomnia/issues/1638
