### ISSUE TITLE
Large JSON response may crash Insomnia

### ISSUE THREAD

**Issue by osyanin** [getinsomnia/insomnia#176]
## Overview

- `Insomnia Version:` v5.0.20
- `Operating System:` Win10
- `Summary: ` Large JSON response (350940 strings with objects & arrays). If minimize one of the large arrays, with much objects & arrays inside - Insomnia 100% crashes

A few sentences describing the issue. Try to include as much detail as possible.

## How To Reproduce

All the information needed to reproduce the issue.

- Get request that responds much (350940) or similiar number strings
- Receive response. 
- Try to minimize large array, with half or a little less strings

I could not find logs or crash dump for attach =\

**Comment by gschier** [comment]
Hi @osyanin. That is **a lot** of strings! Code formatting and folding is controlled by [Codemirror](https://codemirror.net/doc/manual.html) so there may not be much that Insomnia can do about this in the short term.

**Comment by gschier** [comment]
Going to close this for now, as there isn't much we can do about it.
