### ISSUE TITLE
Quick requests

### ISSUE THREAD

**Issue by nblackburn** [getinsomnia/insomnia#177]
It would be nice if it was possible to quickly test an endpoint without having to go through the tedious process of creating a workspace.

**Comment by gschier** [comment]
@nblackburn do you have any suggestions for how you'd like Insomnia to facilitate this?

**Comment by nblackburn** [comment]
I guess you would have to have a non-workspace mode to allow this so when you are in one you would have to switch out of that mode to perform ad-hoc tests.

**Comment by gschier** [comment]
@nblackburn I'm still slightly confused as to why this is a problem. When you first launch the app, it creates a default workspace called "Insomnia". Why not just create your requests under there? I usually keep a workspace called "Debugging" for quick one-off requests.

**Comment by nblackburn** [comment]
Because that is making the problem fit the solution.

- All folders sync (i can't imagine why you would want ad-hoc requests to have that behavior).
- You still have to go through the create request model rather than just being able to punch a url in and hit send (an extra step that you could just do in the editor).

The reason this issue exists is because i can see the benefit of a "Quick requests" feature which at the moment is not possible.

**Comment by gschier** [comment]
I think this issue is worth discussing further. I agree that Insomnia does not facilitate quick debugging. For example, a new request requires a name before you can create it. 

However, I don't have any great ideas for how it could fit nicely with Insomnia's current structure. Let me know if you come up with something. Sketches, mockups or rough notes would be awesome. 👍

**Comment by nblackburn** [comment]
@gschier I think there is a way to do it without making changes to that structure. I have had an idea for a variant of the sidebar that could facilitate this and if i have time will create a mockup to demonstate.

**Comment by gschier** [comment]
Awesome 💯

**Comment by nblackburn** [comment]
![insomnia](https://cloud.githubusercontent.com/assets/2931085/26014867/63168940-3756-11e7-885a-a3bf4cc7c192.png)

Perhaps something like this were you can select no workspace where you just have a list of requests and the search.

**Comment by gschier** [comment]
To avoid having to type a request name, the name shown could just be the request's URL.

For your mockup, would the same thing be able to be accomplished by having the app automatically create a workspace named "No Workspace"? What is the reason for not allowing folders?

**Comment by nblackburn** [comment]
@gschier Yes to your first point, as for the second point, it's not a workspace so it doesn't need folders (if you find yourself needing them then that is against the point of this feature).
