### ISSUE TITLE
[Bug] Authorization window no longer works with GitHub

### ISSUE THREAD

**Issue by duncan-brown** [getinsomnia/insomnia#1774]
- Insomnia Version: develop branch at https://github.com/getinsomnia/insomnia/tree/807379781658ab364430b9c44d5e6e7a671165fa/

- Operating System: Mac OS X 10.14.6

## Details

I cannot get Insomnia to perform an OAuth2 authorization against GitHub following https://insomnia.rest/blog/oauth2-github-api/ as the `Authorize` button is greyed out in the authorization window. I can go through the use authentication part of the flow and send my username/password and 2FA code, but when I get to the consent part, I get stuck. The drop-down menu for scope also does not work.

GitHub is also flagging that Insomnia uses an incompatible web client, which may be related.

Screen shots of the OAuth2 flow are attached.

<img width="935" alt="Screen Shot 2019-11-10 at 11 34 39 AM" src="https://user-images.githubusercontent.com/11262902/68547409-6c56a800-03af-11ea-99ba-0b0d672090a5.png">

<img width="935" alt="Screen Shot 2019-11-10 at 11 35 09 AM" src="https://user-images.githubusercontent.com/11262902/68547413-6fea2f00-03af-11ea-8c95-0beab1484a26.png">

<img width="935" alt="Screen Shot 2019-11-10 at 11 35 21 AM" src="https://user-images.githubusercontent.com/11262902/68547414-724c8900-03af-11ea-9121-e589dd205d56.png">

**Comment by gschier** [comment]
Hmm, taking a look at this. Could be caused by using an older version of Electron.

**Comment by gschier** [comment]
Perhaps we could spoof a newer user-agent for now in the `BrowserWindow` options https://electronjs.org/docs/api/browser-window#winloadurlurl-options

**Comment by elemanhillary** [comment]
have failed to reproduce the issue following `https://insomnia.rest/blog/oauth2-github-api/`, I get that after logging in
<img width="804" alt="Screen Shot 2019-11-23 at 18 35 22" src="https://user-images.githubusercontent.com/14273401/69482118-0d1d7c80-0e20-11ea-9d8d-a361320be1a5.png">
