### ISSUE TITLE
[Suggestion] Ability to import exported workspace as a new unique workspace

### ISSUE THREAD

**Issue by tthayer** [getinsomnia/insomnia#178]
Currently if you export a workspace and import it into the same installation, it doesn't appear to do anything. My use case is one where I'm working with two different versions of an API and would like to copy over all my requests into a new project. Environments probably take care of this issue too, though, so maybe this use case is too edge to spend time on?

**Comment by gschier** [comment]
@tthayer currently, if you import a workspace that was exported from the same application, it will overwrite everything that already exists. 

A potential solution would be to treat this case like an operating system does and prompt the user with...

1. Overwrite conflicts
2. Discard conflicts
3. Copy all
