### ISSUE TITLE
[Feature Request] GPQL identifier for GraphQL requests

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#1780]
- Insomnia Version: 7.0.3
- Operating System: Arch Linux 5.3.10

## Details

Would be possible to add an identifier "GPQL" (or something like that) for GraphQL requests? For example, I have to set the following description in order to identify my GraphQL requests:

![image](https://user-images.githubusercontent.com/12160864/68794297-86052300-062d-11ea-9747-45c0d43cf8c5.png)

The `POST` identifier here isn't helping so much. If the identifier became GPQL, I would be able to name those requests like this:

![image](https://user-images.githubusercontent.com/12160864/68794542-fdd34d80-062d-11ea-8027-93a2f81fd287.png)

I understand those identifiers are for HTTP methods, but GraphQL could be an exception.

Best regards,
Rafael Pacheco.

**Comment by gschier** [comment]
I would like Insomnia to remain a general purpose HTTP client, which means not breaking such standards for specific content-types. However, perhaps there is an argument for a generic feature that displays the request body type (JSON, XML, GraphQL, etc) in the sidebar, maybe even under an opt-in setting.

Thoughts on that?

**Comment by rafaelrenanpacheco** [comment]
> perhaps there is an argument for a generic feature that displays the request body type (JSON, XML, GraphQL, etc) in the sidebar, maybe even under an opt-in setting

That would be nice too, maybe the opt-in setting could be per request body type. In my case I just need to see which POST requests are GraphQL. The other request types will be (in my case) 99% JSON, so there's no need to show them on the sidebar.

This, for example, would solve the POST GraphQL identification:

![image](https://user-images.githubusercontent.com/12160864/69055612-f4126700-09ec-11ea-85fb-ddc05bb2c0b8.png)

**Comment by rafaelrenanpacheco** [comment]
Another option, an way more flexible, is a feature to add a badge (like that small graphql on the print above) with any text at all.

For example, for those 2 specific requests I would right click on them, select the "Add badge" option and type "graphql" on it. Even further, the dialog could have a combobox with predefined values (request types) and a field to type any custom value, up to a predefined string length.

What do you think?

**Comment by gschier** [comment]
Good suggestion! I actually merged a PR for the last release that shows the `X-Method-Override` in the sidebar which seems fine to use for GraphQL as well.

How about this?

![image](https://user-images.githubusercontent.com/587576/70171142-1cac8900-169c-11ea-988e-a0cbb97bc36e.png)

**Comment by rafaelrenanpacheco** [comment]
That will solve the issue of identifying POST requests that are GraphQL, thanks :smile:
