### ISSUE TITLE
[Bug] Error when importing using "Run in Insomnia" 

### ISSUE THREAD

**Issue by GabrielRezendi** [getinsomnia/insomnia#1782]
- Insomnia Version: 7.0.3
- Operating System: Windows 10

![image](https://user-images.githubusercontent.com/30303590/68859007-1a6e9480-06c5-11ea-86cc-1d191515458e.png)

## Details
I have created an "Run in Insomnia" button referencing the .json file containg my requests that I've exported from Insomnia, after I click on the button and confirm to chrome the opening of Insomnia I'm shown to the following error: 

![image](https://user-images.githubusercontent.com/30303590/68859541-40e0ff80-06c6-11ea-9c5f-8be033951fd8.png)

**Comment by gschier** [comment]
Can you provide a sample import file that reproduces this error?

**Comment by oscar-bartman** [comment]
Hi @gschier, importing this file here is causing the same issue for me 
[cart-service.yaml.zip](https://github.com/getinsomnia/insomnia/files/3895781/cart-service.yaml.zip)

**Comment by gschier** [comment]
Thanks for providing that example spec! Looks like the problem was that your server URL was set to `/`, which was not accounted for.
