### ISSUE TITLE
[Bug] Regular expressions in JSONPath output filter are not working

### ISSUE THREAD

**Issue by an1muscr33d** [getinsomnia/insomnia#1785]
## [Bug] Regular expressions in JSONPath output filter are not working
- Insomnia Version: 7.0.1
- Operating System: Fedora 30

## Details

Seems that filter the output of the requests calls using JSONPath validations is not working using regular expressions.

It's easy to reproduce the problem, using any regexp in the output filter data field in Insomnia, for example:

```
{
    "store": {
        "book": [
            {
                "category": "reference",
                "author": "Nigel Rees",
                "title": "Sayings of the Century",
                "price": 8.95
            },
            {
                "category": "fiction",
                "author": "Evelyn Waugh",
                "title": "Sword of Honour",
                "price": 12.99
            },
            {
                "category": "fiction",
                "author": "Herman Melville",
                "title": "Moby Dick",
                "isbn": "0-553-21311-3",
                "price": 8.99
            },
            {
                "category": "fiction",
                "author": "J. R. R. Tolkien",
                "title": "The Lord of the Rings",
                "isbn": "0-395-19395-8",
                "price": 22.99
            }
        ],
        "bicycle": {
            "color": "red",
            "price": 19.95
        }
    },
    "expensive": 10
}
```

Using next filtering string works fine:

`$.store.book[?(@.category == 'reference')]`

But trying to use any regexp it doesn't show anything:

`$.store.book[?(@.category =~ /reference/ )]`
`$.store.book[?(@.category =~ /^reference.*/ )]`

Regards

**Comment by gschier** [comment]
The [JSONPath library](https://github.com/dchester/jsonpath) Insomnia uses does not support the regex syntax you describe. However, it does support JavaScript eval, which can be used like this:

```
$.store.book[?(@.category.match(/reference/))]
$.store.book[?(@.category.match(/^reference.*/))]
```

See https://github.com/dchester/jsonpath#evaluating-script-expressions
