### ISSUE TITLE
[BUG] Failed to fetch schema for GraphQL

### ISSUE THREAD

**Issue by JBonwick** [getinsomnia/insomnia#1786]
- Insomnia Version: 7.0.3
- Operating System: macOS Catalina 10.15.1

### Problem
When trying to retrieve a GraphQL schema, we get the following error:
`Failed to fetch schema TypeError: envObject[key].match is not a function`

### Replication
To reproduce this bug, create a new POST request pointing at a GraphQL endpoint e.g. https://api.graphql.jobs/. At this point the schema will be successfully retrieved.

In the base environment, set a variable to a string:
```
{
  "test": "2"
}
```

In your active environment, override this variable with an integer:
```
{
  "test": 2
}
```

With these changes, refreshing the schema will return the error above.

### The Error
The error is thrown from [L74 of render.js](https://github.com/getinsomnia/insomnia/blob/ad278ea01a9b8af3312753f3c90640959add5cc2/packages/insomnia-app/app/common/render.js#L74). The base variable is set and is a string so when the sub environment is set, it returns true for L73 and subsequently attempts to do `.match` on the integer.

### Potential Solution
L73 could modified to avoid this check when one of the variables is not a string:
```
if (typeof renderContext[key] === 'string' && typeof envObject[key] === 'string') {
```
I wasn't convinced this is correct behaviour though as self recursion would potentially still be desired hence I haven't opened a PR.

**Comment by elemanhillary** [comment]
raise a PR cause if 100% its type checking leading  to the error

**Comment by gschier** [comment]
Thanks for identifying the spot in the code @JBonwick! The render system is extensively covered in the test suite so the safety of the change was easy to verify.
