### ISSUE TITLE
Use gitflow and travis (?)

### ISSUE THREAD

**Issue by pagoru** [getinsomnia/insomnia#179]
It's not a real `issue` but if you open the code, the best way to collaborate and work is using the `gitflow` method and integrating `travis`. It's easy:
- Two blocked branches: `master` and `develop`
- You work on `develop`, all the pull requests.
- You must create a branch every time you gonna work on some issue, and you make pull request from this branch to the develop.
- When you want to launch a new version, you make a pull request from the develop to the master and release the version.

[More info](http://danielkummer.github.io/git-flow-cheatsheet)

Benefits:
- Work with other people in easy mode
- A lot of people use gitflow
- Less problems with code
- More control of the code
- Testing the code
- Easy changelog to the releases

😃

**Comment by pagoru** [comment]
Ups, I see now you are using travis.

**Comment by gschier** [comment]
Hi @pagoru. Thanks for the suggestion. I'm not using gitflow explicitly at the moment, but I am using Travis (like you said). Adding a `develop` branch seems like it'd be a good idea.
