### ISSUE TITLE
 Couldn't resolve host name

### ISSUE THREAD

**Issue by narendra-kumawat** [getinsomnia/insomnia#1792]
On local machine for testing purpose, if the host name is like this  ```demo.localhost:8000```  then insomania will throw error like this  ```Couldn't resolve host name```. 

In Postman, this functionality is there but I like to use Insomania and want to force my Company to buy it but everyone is giving the same excuse that I have mentioned above. I would love to have this functionality in Insomania

**Comment by gschier** [comment]
Can you provide more information on this? Where are you defining the `demo.localhost` DNS rules on your system? What operating system are you on? What version of Insomnia are you using?

**Comment by narendra-kumawat** [comment]
![Screenshot from 2019-11-21 23-45-20](https://user-images.githubusercontent.com/39728695/69364828-13451900-0cb9-11ea-9f5c-2af63ecefb6c.png)

**Comment by gschier** [comment]
Have you added `ciimsdemo.localhost` to `/etc/hosts`? There may also be some more info in the Timeline tab.

**Comment by narendra-kumawat** [comment]
@gschier  Thanks man. After adding `sub_domain.localhost` to my host file, it resolved the issue.

**Comment by denisluciano** [comment]
I'm having the same problem. How i do this? Where i find this file?

**Comment by JimB14** [comment]
C:\Windows\System32\drivers\etc\hosts

**Comment by borekb** [comment]
I think that adding a "resolve" option to Insomnia would be a good addition, I've opened a feature request here: https://github.com/Kong/insomnia/discussions/3832.
