### ISSUE TITLE
BSON Formatting

### ISSUE THREAD

**Issue by Lofbergio** [getinsomnia/insomnia#1795]
- Insomnia Version: 7.0.3
- Operating System: W10

## Details

Hi there, just noticed that there is no support for a BSON Content body (http://bsonspec.org/).

Everything works fine if i setup the header but would be nice to have it as an option in the dropdown.
Since its very close to JSON im forced to either sit with parser error in the JSON parser (understandable) or having to turn it off completely.

**Comment by elemanhillary** [comment]
@Lofbergio specify the UI where this issue reside so that PR solving that issue can be raised ASAP

**Comment by gschier** [comment]
Currently Insomnia does not support binary content types. Can you explain how you are getting BSON to work in the current Insomnia app?

**Comment by Lofbergio** [comment]
My bad, after reading about it i had misunderstood that i was just writing the content body in JSON thinking it was Bson. :)
