### ISSUE TITLE
[BUG] Parse error while assiging environment variable from response body attribute

### ISSUE THREAD

**Issue by iokiwi** [getinsomnia/insomnia#1797]
- Insomnia Version: v6.5.4
- Operating System: Linux - Solus 4.0 Fortitude

## Details

When attempting to set the value of a variable in my environment to the body of a response I get a parse error in the window and am unable to save the changes to the environment.

[Image 1](https://imgur.com/v6eKDXr)

The block is configured as follows.

[Image 2](https://imgur.com/dD6wyCN)

Note that the configuration above works flawlessly when included in the URL but causes this error when included in the Environment JSON.

**Context / Background**

I am trying to do this because I would like to be able to assign a meaningful name to the Response -> Body Attribute 'badge' for better readability. The only way I could think of doing this was assinging the body content to a variable and then referencing the variable by name.

[Image 3](https://imgur.com/YNijvBI)

My use case would also be resolved, in part, by allowing the user to specify a custom name to appear in place of `Response -> Body Attribute`. I can raise this as a feature request if this is the desired resolution.

**Comment by gschier** [comment]
You need double-quotes around your response tag.

**Comment by iokiwi** [comment]
Ugh, that's embarrassing. Thanks
