### ISSUE TITLE
Feature Request -- Custom Auth

### ISSUE THREAD

**Issue by fzakaria** [getinsomnia/insomnia#180]
I'd love the ability to do a custom authorization header for requests.
At my current employer we use a private key authorization strategy and it would be great to be able to read a local private key file and then create the signature.

**Comment by gschier** [comment]
This will likely be accomplished by #51 (plugin framework).

**Comment by gschier** [comment]
Closing this for now and have made a note on #51 that this should be a supported use case.

**Comment by fzakaria** [comment]
@gschier thanks.
Maybe i'll just fork it for now and add our internal Auth header implementation.

**Comment by gschier** [comment]
@fzakaria sounds good 👍
