### ISSUE TITLE
[Bug] Branch creation fails for sync

### ISSUE THREAD

**Issue by HarikiRito** [getinsomnia/insomnia#1803]
[Bug] – Can't create a new branch in sync

- Insomnia Version: 7.0.3
- Operating System: Windows 10

## Details
![Image](https://i.imgur.com/zVRtlRI.png)

**Comment by gschier** [comment]
The message does not convey this, but it also has to be more than 3 characters long. I will update the rule to allow 3-character strings, as that was the original intention.
