### ISSUE TITLE
[Performance] 7.0.4 100% CPU usage

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#1814]
- Insomnia Version: 7.0.4
- Operating System: Arch Linux with Gnome 3.34.1

## Details

After updating to 7.0.4 Insomnia started to use 100% of CPU. Every action like selecting a request, sending a request, and so on, freezes the application and after a while, unfreezes. The console doesn't show any log regarding a possible bug.

I also cleared the workspace responses (which took a long time to finish), and still the freezing continues.

Is there something to help debug this problem?

**Comment by gschier** [comment]
Hmm, I'm not sure what could be causing the problem but I'm able to reproduce on my Ubuntu VM. I recommend using the AppImage build in the meantime. The Snap builds have been historically flaky for a while now.

https://github.com/getinsomnia/insomnia/releases/tag/v7.0.4

**Comment by gschier** [comment]
Also, going to leave this here, as it seems like it could be related https://github.com/electron-userland/electron-builder/issues/4320

**Comment by samibh** [comment]
Adding a data point here, noticed the slowdown today as well after the update to 7.0.4, I'm on Xubuntu 18.04, using the Snap build.
![image](https://user-images.githubusercontent.com/3620212/69799770-377e8980-11d4-11ea-814f-77dc517df3e2.png)

Same symptoms, every click on a different request pushes one CPU to 100% and takes ~2 seconds to complete. I don't know if it helps, but the Snap build also really struggled to export workspaces compared to the usual time it takes.

The AppImage version seems snappier so far, so I'll stick with that for now. Let me know if there is anything else I can do to help debug this, as it makes the app too frustrating to use.

**Comment by uuid0** [comment]
I am having similar issues on macos 10.14.6, no plugins installed.
Not everything is slow, e.g. navigation and preferences work fine.

When sending a request with two prompts, the first shows up quickly, the second doesn't. I assume the processing of the input takes a lot of time.
After submitting the second prompt, the request takes several seconds to be processed. The network time is only a couple of ms, though.

Very simple requests, e.g. a GET without any params, also take a lot of time.
I've turned on profiling and it looks as if the application spends most of its time calling `clone @ /Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/clone/clone.js:52` inside a `setTimeout -> dispatch -> (anonymous) -> dispatch -> combination -> reducer` stack.

**Comment by rafaelrenanpacheco** [comment]
> I recommend using the AUR package or AppImage Build in the meantime.

I do use the AUR package. Just run `yay` yesterday, then Insomnia 7.0.4 was listed to update, and I confirmed :smile:

**Comment by SFBorland** [comment]
Having similar issues on MacOS 10.15.1, every action is slow (navigation, calls etc), no plugins installed.

**Comment by gschier** [comment]
Oh, Sorry @rafaelrenanpacheco. I have no idea why I thought you had mentioned Snap the first time 😆

**Comment by rafaelrenanpacheco** [comment]
7.0.5 working like a charm, thanks for the fast response @gschier  :+1:

**Comment by gschier** [comment]
Woo! Glad it worked 😄

**Comment by SFBorland** [comment]
Can confirm, updated to 7.0.5  and so far (20min) it is back to running smooth on MacOS Catalina, thanks for the quick turn around 👍
