### ISSUE TITLE
OAuth2 implicit flow login broken in 7.0.4

### ISSUE THREAD

**Issue by simonwhitaker** [getinsomnia/insomnia#1816]
- Insomnia Version: 7.0.4
- Operating System: macOS 10.15.1

## Details

On Insomnia 7.0.4, OAuth2 auth (implicit flow) is now broken for me. Downgrading to 7.0.3 resolves the issue.

In the dev tools console I see this error, over and over:

> [oauth2] Ignoring URL "https://accounts.google.com/o/oauth2/auth?hd=synthace.com&response_type=code&redirect_uri=https%3A%2F%2Fsynthace-test.eu.auth0.com%2Flogin%2Fcallback&scope=email%20profile&state=[rest of URL deleted]". Didn't match /(access_token=|id_token=)/

To repro the issue:

1. Add a new request
2. Set auth type to **OAuth 2.0**
3. Set grant type to **Implicit**
4. Set authorization URL to `https://synthace-test.eu.auth0.com/authorize`
5. Set client ID to `IIbj3R12Gg8XQYLwThlmjzA4rWg7t01o`
6. Set redirect URL to `http://localhost:8080`
7. Set response type to **Access Token**
8. Set audience to `https://admin-test.antha.com`
9. Click **Refresh Token**

This will attempt to authenticate you with an Auth0 client, which in turn delegates authentication to G Suite. You’ll see a Google-styled prompt to “Log in at Synthace.com”. Click the log in button and you’ll see this issue - the login window hangs with a blank page and the title "Forwarding..."

**Comment by gschier** [comment]
Should be fixed now in 7.0.5!

**Comment by simonwhitaker** [comment]
Awesome! Thanks so much for the fast fix!

**Comment by ArthurVernon-Woodside** [comment]
Hit a similar problem withVersion: Insomnia Core 2020.5.0
Release date: 02/12/2020
OS: Darwin x64 20.1.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
