### ISSUE TITLE
[Feature Request] –  batch change baseurl 

### ISSUE THREAD

**Issue by sendreams** [getinsomnia/insomnia#1821]
the app server maybe in different site, for example, maybe:192.168.1.10:8080 or 202.138.12.103:8090,, etc,  while change the test server, user will be need to change all of the request's base url one by one, sometime will be forget change the base url and get the wrong result.

maybe can set a baseurl in globel, and all of the request in the workspace could use the globel baseurl.

**Comment by gschier** [comment]
You can use Insomnia's [Environment Variables](https://support.insomnia.rest/article/11-getting-started) to accomplish this
