### ISSUE TITLE
[Bug] Does not start anymore - ENOENT - Win10

### ISSUE THREAD

**Issue by black-snow** [getinsomnia/insomnia#1826]
- Insomnia Version: From the error message I figure it's 7.0.5
- Operating System: Windows 10

Worked fine yesterday. Now when I execute Insomnia a receive an exception:

> Uncaught Exception:
> Error: ENOENT: no such file or directory, open
> '\\?\C:\Users\me\AppData\Local\insomnia\app-7.0.5\resources\app...\package.json'
> at Object.fs.openSync (fs.js:577:3)
> ...
> at process.binding.internalModuleReadJSON (ELECTRON_ASAR.js:665:19)
> ...

**Comment by black-snow** [comment]
Reinstalled Insomnia. Closed for me.

**Comment by glyphCezilleSantillan** [comment]
I get this too, and a reinstall did work. But something keeps breaking after a few uses of the app for the last few versions, and I don't want to have to keep reinstalling Insomnia each time.

**Comment by black-snow** [comment]
@glyphCezilleSantillan shall I reopen it for you? Can you provide more details?

**Comment by gschier** [comment]
Please create a new issue with details if you are experiencing issues @glyphCezilleSantillan 🙂

**Comment by Crazometer** [comment]
Also experiencing this

**Comment by GineHyte** [comment]
Try opening it with admin rights. It worked for me.
