### ISSUE TITLE
[Feature request] Request pin/un-pin mechanism

### ISSUE THREAD

**Issue by MontiniCristian** [getinsomnia/insomnia#1827]
[Feature Request] Add request pin mechanism on top of the sidebar

## Details
When working with a lot of requests we need to frequenty search between them. In order to decrase the working time it would be nice to have a pin/un-pin mechanism.
It would be simple: 

- Every request can be pinned on top of the sidebar
- Every request can be un-pinned from the top of the sidebar
- If a request search is performed the pinned request should be available

Thanks!

**Comment by gschier** [comment]
I assumed you closed this after finding the pin mechanism in Insomnia?

For those who may be searching, you can do this from the context menus in the sidebar.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/587576/70641884-4d487180-1c0c-11ea-81e7-96562490e6f8.png">
