### ISSUE TITLE
[Bug] Body type "Text -> Other" reverts to previous body type

### ISSUE THREAD

**Issue by teozkr** [getinsomnia/insomnia#183]
## Overview

- `Insomnia Version:` 5.0.20
- `Operating System:` Arch Linux amd64

The "Text -> Body" body type doesn't work if you've chosen a previous body type before, and instead reverts back to the previous body type as soon as you type something.

## How To Reproduce

- Create a new request
- Set body type to JSON (or XML or Binary File or Multipart Form or Form URL Encoded)
- Set body type to Other
- Type something into the text field
- The field reverts to the previous type

## Other Notes

This does *not* happen if the previous type was No Body. From what I can tell the issue is that it tries to auto-detect the type from the Content-Type header. Since Other doesn't change the header it stays the previous value, and typing something triggers the auto-detection.

Also, the conversion is faulty for "form-style" content-types. If you change type manually then your previous values are pre-filled in the form, but this does not happen when this bug is triggered.

**Comment by gschier** [comment]
Just reproduced this on my end. Thanks for the awesome bug report @teozkr!

**Comment by gschier** [comment]
This was fixed in #183
