### ISSUE TITLE
[Bug] Insomnia sending GET request when it's suposed to POST while using http.

### ISSUE THREAD

**Issue by Drunpy** [getinsomnia/insomnia#1832]
- Operating System: Ubuntu 18.4 LTS
![version info](https://user-images.githubusercontent.com/29728641/70436301-b642b480-1a67-11ea-8bee-9cb8a99f9b4b.png)

Tried to POST to my server mistakenly using HTTP but the request kept arriving as GET.
![Image](https://user-images.githubusercontent.com/29728641/70437031-6cf36480-1a69-11ea-9cbb-128750e19995.jpeg)

It works without problems over https.

**Comment by gschier** [comment]
This is likely because the server is responding with a redirect (perhaps http->https?). During this case, Insomnia will switch from POST to GET.

**Comment by beitomartinez** [comment]
> This is likely because the server is responding with a redirect (perhaps http->https?). During this case, Insomnia will switch from POST to GET.

This worked for me! 🔥

**Comment by raphoester** [comment]
I had the same issue that was caused by me putting a double slash // at some point in the url (ex. localhost/foo//bar/test), and the server was redirecting to the version with only one slash (localhost/foo/bar/test).

**Comment by Jeandcc** [comment]
For me, the issue was with a trailing slash (`/`) that the server I was talking to was enforcing through a redirect.

The solution: Add a `trailing slash (/)` at the end of the request URL.
