### ISSUE TITLE
[Suggestion] F5 and Ctrl + R with same action from button Send 

### ISSUE THREAD

**Issue by joubertredrat** [getinsomnia/insomnia#186]
Hi,

I have a small sugestion for Insomnia, today you need to click on "Send" button to make request on API, but I think that is good idea to add F5 and/or Ctrl + R for make requests like "Send" button.

I myself often press F5 on insomnia sometimes, then I remember that insomnia isn't a browser. :joy: 

What you think guys?

**Comment by gschier** [comment]
`ctrl+Enter` will trigger the current request to send. I would like to try to stay away from duplicate hotkeys as long as possible. However, this "muscle memory" may be common enough to warrant it.

**Comment by gschier** [comment]
Closing this for now. Can resurrect later if needed.
