### ISSUE TITLE
Feature Request - Import request from curl string

### ISSUE THREAD

**Issue by JayAndCatchFire** [getinsomnia/insomnia#187]
A feature I miss from my workflow with Postman was the ability to paste in a cURL command string to create a request.  I was able to copy from Chrome's devtools and paste into the app.

<img width="546" alt="screen shot 2017-05-11 at 12 04 12 pm" src="https://cloud.githubusercontent.com/assets/10983817/25962146/4a8a5146-3642-11e7-98db-9f8d59c0df37.png">

<img width="486" alt="screen shot 2017-05-11 at 12 07 27 pm" src="https://cloud.githubusercontent.com/assets/10983817/25962191/6ea6b4f2-3642-11e7-8db8-dc055eee56df.png">

**Comment by gschier** [comment]
@JayAndCatchFire you can paste curl commands directly into the URL bar and it will be parsed and used to update the current request.

It would probably good to have a more obvious way of doing it (like Postman does) to make it more discoverable, though.

**Comment by JayAndCatchFire** [comment]
Yeah, I had no idea.  That's great news, though!

**Comment by JayAndCatchFire** [comment]
Actually, that's better than great news.  That's a killer feature.  It takes fewer clicks than Postman in import stuff.  I wish this was more prominently documented.

**Comment by gschier** [comment]
Ya, it's super quick once you know about it!

This is a small hint in the dialog, but it's pretty small.

![image](https://cloud.githubusercontent.com/assets/587576/25962927/64ef920c-3634-11e7-9aca-0e1190a1e27e.png)
