### ISSUE TITLE
[Question] Drag And Drop on Pinned Requests

### ISSUE THREAD

**Issue by dcdaz** [getinsomnia/insomnia#1877]
Is there a way of organize pinned requests in a custom way via Drag'n Drop or something like that?

**Comment by filfreire** [comment]
Hi @danesc87, thank you for reporting this issue and sorry for not getting an answer in a long time 🙇 

As of now, you can only organize pinned requests through the default sorting options:
![Image](https://user-images.githubusercontent.com/11976836/180994012-a58d843f-a8ab-4925-a732-f1fe714d525e.png)

Feel free to report any other issues you come across. Also if you think it might be worth changing this issue into a feature request, let us know by re-opening it 👍
