### ISSUE TITLE
[Meta] Consider making a Slack/Discord/Gitter Channel

### ISSUE THREAD

**Issue by ctnordcl** [getinsomnia/insomnia#188]
Since this app is now open source, it would be nice if we all had a common place to discuss bugs, features, and planning for the insomnia app. Slack is great at this, as are the other options listed, but I seriously think we need to go with at least one. I don't mind starting it, but I think it should be done by the maintainers rather than the contributors.

**Comment by gschier** [comment]
Hey @ctnordcl. I had made a Slack team a while ago but it wasn't accessible. I just put up a Slackin server on Heroku. Here you go! https://chat.insomnia.rest/

Not sure where the best place to advertise this would be.

**Comment by gschier** [comment]
Added a badge to the README for now
