### ISSUE TITLE
[Bug] Exported failed due to unexpected error

### ISSUE THREAD

**Issue by elemanhillary-zz** [getinsomnia/insomnia#1882]
After importing [Stripe OpenAPI](https://github.com/stripe/openapi/blob/master/openapi/spec3.json), I exported it to HAR format were I got the error below, I can surely raise a PR for this is approved by the insomnia team
<img width="1030" alt="Screen Shot 2020-01-13 at 10 05 03 AM" src="https://user-images.githubusercontent.com/14273401/72240514-0d025780-35ed-11ea-98d0-08d5f0297ef5.png">

**Comment by filfreire** [comment]
Hi @elemanhillary-zz, thanks for reporting this one, and apologies for not getting back sooner 🙇 

I've attempted to import, and then export the example you have given (https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json) and can no longer reproduce it.

Feel free to open a new ticket if you still have this issue or any other issues.
