### ISSUE TITLE
[Bug] Cant open Preferences > General

### ISSUE THREAD

**Issue by vscncls** [getinsomnia/insomnia#1885]
**Describe the bug**
Opening general preferences makes the insomnia window go white.

**To Reproduce**
1. Open keyboard shortcuts
2. Click general

or

1. Click "Application"
2. Open preferences

**Expected behavior**
Opening the general preferences.

**Screenshots**
![insomnia-general-preferences](https://user-images.githubusercontent.com/47672257/72345276-0b4e9780-36b2-11ea-9b72-fd711ba09500.gif)

**Desktop:**
 - OS: Arch Linux 5.4.10-arch1-1
 - Installation Method: [AUR](https://aur.archlinux.org/packages/insomnia/) 
 - App Version v7.0.6

**Comment by hyshka** [comment]
I have a similar issue except I get the full white page when trying to open preferences at all, perhaps because it defaults to the "General" tab.


- OS: Arch Linux 5.5.8-arch1-1
- Installation Method: AUR
- App Version v7.1.1

**Comment by leonbreedt** [comment]
Also on Arch (5.5.9-arch1-2), AUR package, v7.1.1. 

Something is suspect about the AUR created package, when I build Insomnia from Git repository and run it, it works fine, see screenshot:

![insomnia-preferences](https://user-images.githubusercontent.com/167841/77131524-c1729b00-6ac0-11ea-89c0-edfc352d3743.png)

**Comment by vscncls** [comment]
The AUR package simply [dowloads the official .deb, extracts it, and adds a script that executes it to $PATH](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=insomnia). My guess is, because it's expecting a debian based distro (ubuntu), some dependency got messed up. btw, where did you find instruction to build from source? @leonbreedt

**Comment by leonbreedt** [comment]
Yeah, I suspect as well there's some binary incompatibility with the .deb vs Arch. Perhaps the AUR could instead perform a build as well? I followed the instruction from this repository's README:

```shell
npm run bootstrap
npm run app-package
```
Note that it needs Node.js 10.x, the latest one in the repository causes the build to fail with V8 errors.

I'm using `nodejs-lts-dubnium`.

The app package fails because it tries to do some RPM stuff as well, but by that time it's already built a .deb package from which I could extract the files and run.

@vscncls

**Comment by vscncls** [comment]
Just tested and it works perfectly when built from source!

**Comment by vscncls** [comment]
If anyone is interested, I just adopted and updated the [insomnia-src AUR package](https://aur.archlinux.org/packages/insomnia-src/). Because it's built from source, it doesn't have this bug.

**Comment by igarag** [comment]
Hi,

I have the same problem. Before reinstalling I would like to know if I can export the settings I have configured, is there a path where they are stored? As the configuration can't be opened I can't export it by the usual procedure.

Thank you.

**Comment by igarag** [comment]
Ok, I solved the error by clicking on the drop-down shown in the figure. I hope it helps someone.

![insomnia_error](https://user-images.githubusercontent.com/9017430/120226487-94cf1d00-c247-11eb-8fe5-eb3a8cf7abf3.png)
