### ISSUE TITLE
[Feature Request] Add workspace grouping

### ISSUE THREAD

**Issue by ribice** [getinsomnia/insomnia#1888]
I currently have many Workspaces, and it's hard to navigate between them.

Add a way to group the Workspaces.

**Comment by filfreire** [comment]
Hi @ribice thanks for reporting this!

We have since added the concept of [Projects](https://docs.insomnia.rest/insomnia/projects), and also a Dashboard for each project in order to help navigate this.

Feel free to report any other ideas or issues you come across!
