### ISSUE TITLE
Feature Request: Array as parameter

### ISSUE THREAD

**Issue by JLopeDeB** [getinsomnia/insomnia#1889]
Hi,

I'm opening the issue as per @UkiahSmith  requested. 
I think it'd be a great addition to be able to send arrays as parameters on the multi-form request, especially for http POST. 
In case anyone needs it  before this feature is avaible, I was able to workaround it by directly writing the JSON code like this:

```
{ 
"surname" :  "Lopez",
"name" : "Marta",
"user_id" : 3,
"date" : "1945-05-25",
"phones" : [{"number" : "+552215011192", "type_id": 1"}, {"number" : "+562965454422",  "type_id": 
2}],
"emails" : [{"email" : "robert@example.com", "type_id": 1}, {"email" : "bobby@example.com",  "type_id": 2}]
}
```

**Comment by gschier** [comment]
I'm a bit confused. You are suggesting array support within multi-part form data. However, the example solution you posted is not form data, but JSON.

Can you describe in more detail the exact format you require? Perhaps link to the API docs if they are publicly available?

**Comment by ti0rafa** [comment]
You can already send arrays (at least in version: _Insomnia Core 2020.5.2_):

- Set method to "POST"
- Make sure the header Content-Type is set to "multipart/form-data"
- On the parameters tab select "Multi"

On the parameters tab you need to input something like this:

```
- surname = Lopez
- name = Marta
- user_id = 3
- emails[0]['email'] = robert@example.com
- emails[0]['type_id'] = 1
- emails[1]['email'] = bobby@example.com
- emails[1]['type_id'] = 2
```

But on the API side Im not sure it will detect the value correctly. 

In the JSON example `emails` is an Array of Objects. And I don't think you can send Objects directly, so maybe the API call will fail??. 

But regarding this issue, arrays can be sent using multipart/form-data.

**Comment by kreosus** [comment]
Hi @JLopeDeB,
Good day and I hope that all is well. Have you had a chance to try our new release, located here: https://github.com/Kong/insomnia/releases/?

**Comment by Victornfb** [comment]
@JLopeDeB the answer from @ti0rafa was almost right, but in more recent versions of insomnia this is working:

![image](https://github.com/user-attachments/assets/6cf71fd1-7782-4742-9863-36ffecb383f9)

```bash
curl --request POST \
  --url http://localhost:3333/api/admin/products \
  --header 'Company-Id: 69126f2e-f3b6-4559-8c3c-ec60fa794b01' \
  --header 'Content-Type: multipart/form-data' \
  --header 'User-Agent: insomnia/9.2.0' \
  --form 'name=teste insominia' \
  --form description=anyone \
  --form quantity=100 \
  --form price=12 \
  --form categoryId=92fa21f4-12b5-4b64-a7b1-e1a1878137a7 \
  --form 'image=@/Users/youruser/Downloads/image.png' \
  --form 'customizations[0][name]=teste 1' \
  --form 'customizations[0][maxQuantity]=1' \
  --form 'customizations[0][mandatory]=false'
```
