### ISSUE TITLE
[Feature] Add a proxy filter

### ISSUE THREAD

**Issue by ttrobisch** [getinsomnia/insomnia#189]
## Overview

- `Insomnia Version:` develop branch
- `Operating System:` arch linux
- `Summary: ` Add an option to set a list of hosts which will not get proxied

There should be a possibility to filter localhost from getting proxied. [Have a look at this commit](https://github.com/ttrobisch/insomnia/commit/a33046a2f2fef30be64cb1f5a2222b1f265b167a)

**Comment by gschier** [comment]
@ttrobisch this looks great. Someone actually brought this up via email a while ago but I didn't have the time to spend on it. 

Can you submit a PR so we can discuss further?

Also, libcurl has a [NOPROXY](https://curl.haxx.se/libcurl/c/CURLOPT_NOPROXY.html) option that may be a better fit and it also supports wildcards.

**Comment by ttrobisch** [comment]
I just submitted a [pull request](https://github.com/getinsomnia/insomnia/pull/285)

**Comment by gschier** [comment]
Thanks @ttrobisch. I'll take a look 😄
