### ISSUE TITLE
[Question] Didn't know deleting synced folder would delete it for everyone. How to recover?

### ISSUE THREAD

**Issue by taylorgoolsby** [getinsomnia/insomnia#1892]
**What is your question?**
I had a synced folder that I wanted to remove myself from. I thought the way to do this was to delete it, but I found out that will delete it from all the other team member's Insomnia.

1. How do I recover a deleted folder?
2. How do I remove myself from a synced workspace without deleting it from other team members?

**Comment by gschier** [comment]
Hi @taylorgoolsby,

If you send an email to support@insomnia.rest with the workspace name, I may be able to manually restore it from my end. Please mention this issue in the email.

Currently, it is only possible to share a workspace with all members of a team. There is no way for a single member to opt-out if a workspace is shared.

**Comment by mtio** [comment]
We would really like a way to version control our shared Workspaces, something like how git works would be awesome.

**Comment by DMarby** [comment]
Hi there,

This issue should be resolved in our new sync system, Version Control Sync, which lets you rollback to previous versions of a workspace, amongst other things.
As we are sunsetting legacy sync in favour of it, I'm going to close this issue. You can start using Version Control Sync today by following the instructions here: https://support.insomnia.rest/article/67-version-control#getting-started
Please send an email to support@insomnia.rest if you run into any further sync issues, or have any questions, and we'll be able to provide better assistance.

More information about the sunsetting and Version Control Sync can be found here:
https://insomnia.rest/blog/sunsetting-legacy-sync/
https://support.insomnia.rest/article/67-version-control
