### ISSUE TITLE
Mac preferences

### ISSUE THREAD

**Issue by benrolfe** [getinsomnia/insomnia#1894]
**What is your question?**
My Mac died last week, but I forgot to do an export of my Insomnia requests. I have a hard drive backup - but I don't know where to find the Insomnia settings/preferences/configuration.

Any suggestions as to where I might find the file(s) in my backup?

Thanks.
Ben

**Comment by gschier** [comment]
If you install the app again on your new system, you can view the app data directory in finder from Help > Show AppData Folder.

You should be able to restore all the files from that folder onto your new system.

![image](https://user-images.githubusercontent.com/587576/72749722-d26a6300-3b88-11ea-9274-2c04ca5199a1.png)
