### ISSUE TITLE
Unable to rename Environment (Windows 10)

### ISSUE THREAD

**Issue by chrisjasp** [getinsomnia/insomnia#1896]
I encountered an issue attempting to rename any environment in the Environment Manager dialog. In windows 10, a double tap of a touchpad does not enable editing of the name. If you double click it does work properly but double tap and double click are two separate events for windows 10.

**Comment by gschier** [comment]
By "double tap" do you mean on the touchscreen? It's odd that tapping the touchpad would be a different event than clicking.

If you have any more information about how to handle this properly, please let me know. I don't have a Windows device to test this on.

**Comment by chrisjasp** [comment]
Sorry if my explanation was a little unclear. In my case, my mouse pad has the ability to tap or a full mechanical press. I'm referring to "double tap" as just a double tap on the mouse pad, versus like a full mechanical click on the mouse pad. The latter works to rename an environment, a double tap does not.

**Comment by filfreire** [comment]
Hi @chrisjasp I'm going to go ahead and close this one, but feel free to reopen this issue and share more details on your mouse pad (e.g. model, brand, specs) if you are still facing this issue.
