### ISSUE TITLE
[Question] Import JSON file as body

### ISSUE THREAD

**Issue by packeteer** [getinsomnia/insomnia#1897]
**What is your question?**
Is it possible to import a json file as request body?

**What is the context?**
Customers regularly send us a JSON text file and URL when they have an issue, normally we would then use CURL or HTTPIE to run the JSON

**Comment by gschier** [comment]
You can use the Binary File option to send it. Note, you may have to also add the `Content-Type` header as well.

![image](https://user-images.githubusercontent.com/587576/72750270-625cdc80-3b8a-11ea-8bef-d2ec4e96f905.png)

![image](https://user-images.githubusercontent.com/587576/72750291-76084300-3b8a-11ea-90c1-dd62e5359913.png)
