### ISSUE TITLE
[Feature Request] Include responses in the export file

### ISSUE THREAD

**Issue by dingyaguang117** [getinsomnia/insomnia#1898]
So insomnia-documenter can generate documents with response examples. Thanks very much!

**Comment by filfreire** [comment]
Hi @dingyaguang117 thanks for reporting this!

If you look into [insomnia-documenter's changelog](https://github.com/jozsefsallai/insomnia-documenter/blob/master/CHANGELOG.md), this is now supported by them and you can define response examples there.

Feel free to report any other issues or ideas you come across!
