### ISSUE TITLE
[Bug] Can't get context.data in plugins.

### ISSUE THREAD

**Issue by dingyaguang117** [getinsomnia/insomnia#1900]
[https://support.insomnia.rest/article/26-plugins#context.data](https://support.insomnia.rest/article/26-plugins#context.data)

I viewed the source code of context, it doesn't import data at all.

[https://github.com/Kong/insomnia/blob/0a616fba6b12e3e51e3643f5f85f9fd27471f762/packages/insomnia-app/app/plugins/context/data.js](https://github.com/Kong/insomnia/blob/0a616fba6b12e3e51e3643f5f85f9fd27471f762/packages/insomnia-app/app/plugins/context/data.js)

**Comment by gschier** [comment]
Woops, just implemented this in #1901
