### ISSUE TITLE
[Feature Request] Adding ability to configure the GraphQL schema fetching

### ISSUE THREAD

**Issue by golanw** [getinsomnia/insomnia#1909]
**Is your feature request related to a problem? Please describe.**
Insomnia fails to fetch GraphQL schema from my server - this happens because my server expects a certain header in all requests.

**Describe the solution you'd like**
Will it be possible to add configuration settings that will allow users to add custom headers to the schema fetching request(s)?

**Comment by codybrouwers** [comment]
@golanw I ran into the same issue and was able to fix it by using [this default headers plugin](https://insomnia.rest/plugins/insomnia-plugin-default-headers/). It seems the GraphQL schema fetch request also picks up the headers defined with the plugin.

**Comment by alexandrim0** [comment]
It would be nice to configure Authrization header for fetch schema request because result depends on permissions.

**Comment by kreosus** [comment]
Hi @golanw,
Good day and I hope that all is well. Have you had a chance to try our newest release located here: https://github.com/Kong/insomnia/releases/? If you require any further/future assistance please let us know and we will proceed accordingly. Have a nice day.
