### ISSUE TITLE
Rest

### ISSUE THREAD

**Issue by angiefm50** [getinsomnia/insomnia#191]
## Overview

- `Insomnia Version:` _____
- `Operating System:` _____
- `Summary: ` _____

A few sentences describing the issue. Try to include as much detail as possible.

## How To Reproduce

All the information needed to reproduce the issue.

- This is the first step
- This is the second step
- Further steps, etc.

## Other Notes

Any other information you feel is relevant to the issue including lines of code that
may be causing it, potential solutions, opinions, etc.

**Comment by gschier** [comment]
Hi @angiefm50. This is the default issue template. Did you post this by mistake?
