### ISSUE TITLE
[Question] Referencing of Status Code

### ISSUE THREAD

**Issue by ankitkesarwani** [getinsomnia/insomnia#1912]
I am trying to create a plugin through which I can resend all the failure request in a sequence of request. I am trying to achieve this through _insomnia-plugin-run-folder_ plugin by adding more to it.

I wanted to know the way through which I can access environment variable in this module? Tried multiple way but no luck.

**Comment by kreosus** [comment]
Hi @ankitkesarwani,
Good day and I hope that all is well. I am just checking in with as per this issue and if you require any further assistance. Have a nice day.

**Comment by kreosus** [comment]
Hi @ankitkesarwani 
As we have not heard back from you we are closing this issue out. If you require any further/future assistance please let us know and we will proceed accordingly. Have a nice day.
