### ISSUE TITLE
Support a system wide install on Windows

### ISSUE THREAD

**Issue by hmatt1** [getinsomnia/insomnia#1914]
Insomnia currently installs on a per-user basis on Windows. This is a feature request to add the option to install for all users.

This may be related to https://github.com/Kong/insomnia/issues/1756

**Comment by girlpunk** [comment]
This is still outstanding

**Comment by filfreire** [comment]
Hi @hmatt1 I'm going to go ahead and close this as duplicate of #1756, but I went ahead and marked that one internally as a possible improvement.
