### ISSUE TITLE
[Suggestion] Saving full response

### ISSUE THREAD

**Issue by aldreth** [getinsomnia/insomnia#192]
## Overview

- `Insomnia Version:` Version 5.0.20 (5.0.20.162)
- `Operating System:` os x 10.12.4
- `Summary: ` Is it possible to save the full response - status, headers & body?

I'd like to replicate the output that is saved from
```
curl -is url > example.txt
```

I was excited when I saw `Save to File` on the Preview dropdown, but it just saves the preview. All the required information is available in the Header & the Timeline, but I can't find a way to save it conveniently.

## How To Reproduce

Try to save the full response.

**Comment by gschier** [comment]
Currently, the action only saves the _body_ to a file. This is useful if you want to save the file for future use. 

I'm curious what your need is to have the entire request to a file as opposed to using the Timeline tab?

**Comment by aldreth** [comment]
To use for stubs when my application testing uses external calls, using [webmock](https://github.com/bblimke/webmock).

**Comment by gschier** [comment]
@aldreth Oh, nice! That seems super useful. Are you interested in working on this? Could add another option or a second prompt to save the full HTTP response.

**Comment by aldreth** [comment]
@gschier Give me some hints on where to look and happy to give it a try.

**Comment by gschier** [comment]
Sure thing 😄 

Code that saves the body: <br>https://github.com/getinsomnia/insomnia/blob/develop/app/ui/components/response-pane.js#L55

Dropdown containing Save to File button: <br>https://github.com/getinsomnia/insomnia/blob/develop/app/ui/components/dropdowns/preview-mode-dropdown.js

You can get the headers you need with something like this (untested): 
```js
// Same as what `curl -i` provides
const headersBlob = response.timeline
  .filter(v => v.name === 'HEADER_OUT')
  .map(v => v.value)
  .join('\n')
```

Let me know if you have any questions along the way.
