### ISSUE TITLE
[Bug] Multi-Line field in multipart/form-data adds invalid Content-Type

### ISSUE THREAD

**Issue by Hontaro** [getinsomnia/insomnia#1920]
**Describe the bug**
Adding a multi-line textfield in a multipart/form-data request adds "Content-Type: true" to the form-data field, which is an invalid Content-Type, which can cause servers to reject the request. Probably related to #1813 

**To Reproduce**
1. Create a Multipart Form request in Insomnia
2. Add a Text (Multi-line) field
3. Press Send
4. Check Timeline for the Multipart Form

**Expected behavior**
A valid (text/plain, application/json, ...) or no Content-Type added to the part

**Screenshots**
![grafik](https://user-images.githubusercontent.com/27289425/73543056-60bad080-4436-11ea-89c3-3640daf6b252.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1803
 - Installation Method: Insomnia Setup
 - App Version: v7.0.6

**Additional context**

**Comment by main5tream** [comment]
I have also noticed this issue for the last few months. A workaround is to manually set the text type for each multiline field, but it would be nice to have this fixed!

- OS: Windows 10.0.18362
- Installation Method: Insomnia Setup
- App Version: v7.0.6
