### ISSUE TITLE
[Bug] Ubuntu 18.04 - Crash on application startup

### ISSUE THREAD

**Issue by hug0b** [getinsomnia/insomnia#1922]
**Describe the bug**
The application is unresponsive when launched. It's memory usage goes up to ~2gb and CPU usage spikes, then the application crashes.

Samples of terminal outputs :
```bash
insomnia
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
[fix] Running database repairs
[db] Initialized DB at /home/user/snap/insomnia/55/.config/Insomnia/insomnia.$TYPE.db
Init responses DB
[localstorage] Initialized at /home/user/snap/insomnia/55/.config/Insomnia/localStorage
[main] Loading file:///snap/insomnia/55/resources/app.asar/renderer.html
[updater] Updater not running platform=linux dev=false


#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#
#
#
#FailureMessage Object: 0x7efec8a30120#0 0x0000013f80a3 <unknown>
#1 0x00000354d28b <unknown>
#2 0x7efee19619e8 <unknown>
#3 0x7efee22e0ad0 <unknown>
#4 0x7efee1c19e12 <unknown>
#5 0x7efee1c07f23 <unknown>
#6 0x7efee1c077da <unknown>
#7 0x7efee1c07477 <unknown>
#8 0x7efee1c25d3e <unknown>
#9 0x7efee1bf4e6e <unknown>
#10 0x0000013f9db4 <unknown>
#11 0x00000139a49e <unknown>
#12 0x00000139ab7b <unknown>
#13 0x000001399cfb <unknown>
#14 0x00000137eb7b <unknown>
#15 0x0000013ab031 <unknown>
#16 0x7efee0ee56db <unknown>
#17 0x7efeda92f88f <unknown>
```
```bash
<--- Last few GCs --->

[30216:0x219319d2f000]     4749 ms: Mark-sweep 1386.0 (1464.2) -> 1385.7 (1465.7) MB, 116.5 / 0.0 ms  allocation failure GC in old space requested
[30216:0x219319d2f000]     4911 ms: Mark-sweep 1385.7 (1465.7) -> 1385.7 (1432.7) MB, 161.9 / 5.0 ms  last resort GC in old space requested
[30216:0x219319d2f000]     5070 ms: Mark-sweep 1385.7 (1432.7) -> 1385.7 (1432.2) MB, 158.8 / 4.7 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3463246040bd]
    1: StubFrame [pc: 0x34632465872a]
Security context: 0x16ee90152fe9 <String[7]: file://>
    2: replace(this=0x3630ca7e819 <Very long string[649231954]>,0x3630ca7e841 <JSRegExp <String[6]: ^\s*\n>>,0x18eb7a282441 <String[0]: >)
    3: json [file:///snap/insomnia/55/resources/app.asar/bundle.js:241116] [bytecode=0x2cb898a08f9 offset=806](this=0x37e67bd04159 <Object map = 0x31d543e05d1>,/* anonymous ...
```

**To Reproduce**
Launching the application. I am unsure what caused this suddenly since it worked fine before.

**Expected behavior**
The application is responsive and doesn't crash.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 running LXDE
 - Installation Method: snap
 - App Version: 7.0.6

**Additional context**

**Comment by reeceaw** [comment]
On macOS Mojave 10.14.6 (18G84) I am seeing Insomnia 7.0.6 crash immediately after startup - split second of the app jumping in the dock before closing immediately.

**Comment by soderluk** [comment]
Having this same issue on newest version: 7.1.1 using snap on Ubuntu 18.04.
Tried uninstalling / reinstalling, and downgrading to 7.1.0, but still same issue.
```
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
[fix] Running database repairs
[db] Initialized DB at /home/user/snap/insomnia/62/.config/Insomnia/insomnia.$TYPE.db
Init responses DB
[localstorage] Initialized at /home/user/snap/insomnia/62/.config/Insomnia/localStorage
Trace/breakpoint trap (core dumped)
```

This worked fine a couple of days ago, and now suddenly this happened...

**Comment by hug0b** [comment]
Trying it again today, the app is now version 7.1.1 and seems to behave normally.

**Comment by soderluk** [comment]
I just installed a bunch of updates to my system yesterday... Maybe something there that broke insomnia.

**Comment by soderluk** [comment]
It seems like Snap is somehow broken... My Spotify stopped working as well, with similar Gtk messages. Installing insomnia via apt works.

**Comment by tvelich** [comment]
Seems like a duplicate of https://github.com/Kong/insomnia/issues/1873 and https://github.com/Kong/insomnia/issues/1700

**Comment by soderluk** [comment]
@tvelich At least not 1873, since that freezes the whole system. For me it just won't start with those Gtk messages. Installing insomnia from the repositories works though, so it seems like the snap package is broken somehow.

**Comment by tvelich** [comment]
Still happening on the latest version for me unfortunately. I'm wondering if this has to do with an existing Electron app running already. It seems to not do this as frequently if I close Slack before launching Insomnia.

Edit: FYI, my installation is from `apt`

**Comment by OtavioCapila** [comment]
```
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
[fix] Running database repairs
[db] Initialized DB at /home/otavio/snap/insomnia/65/.config/Insomnia/insomnia.$TYPE.db
Init responses DB
[localstorage] Initialized at /home/otavio/snap/insomnia/65/.config/Insomnia/localStorage
[1]    26683 trace trap (core dumped)  insomnia
```
`snap --version`

> snap    2.44.3-2
> snapd   2.44.3-2
> series  16
> arch    -
> kernel  5.6.7-arch1-1

**Comment by hug0b** [comment]
Closing since I haven't had this error in a while and the issue seems inactive.
