### ISSUE TITLE
[Question] Response chunk size

### ISSUE THREAD

**Issue by karayv** [getinsomnia/insomnia#1924]
**What is your question?**
I'm not sure if it is a bug or question.

Insomnia in the Timeline tab shows me multiple 
_Received 15.1 KB chunk_
messages. The sizes are slightly different, but most of them about ~15 KB.
When I use `curl --raw` I see in chunks size headers that a chunk size is ~512 KB.
I wonder the what is the real chunk size a 15 kb or 512 kb

**What is the context?**
I'm trying to debug large file download in my service. I'm using `transfer-Encoding: chunked`
https://en.wikipedia.org/wiki/Chunked_transfer_encoding
The real chunk size is important for the download speed. FYI I don't set the content length (my service simply doesn't know it).

Thank you!

**Comment by gschier** [comment]
It _is_ indeed ~15kb within Insomnia. I'm not sure why `curl` would be different but it looks like the option might be configurable which defaults to 16kB: https://curl.haxx.se/libcurl/c/CURLOPT_BUFFERSIZE.html
