### ISSUE TITLE
[Feature Request] Set a background image

### ISSUE THREAD

**Issue by manoger** [getinsomnia/insomnia#1931]
Good Mornin' .

I would like to have a way to set a background image in insomnia like Intellij IDE.
Would be a nice feature.

![markdown_image](https://raw.githubusercontent.com/wiki/cocuh/intellij-background-chibichara/screenshot/screenshot1.jpg)

**Comment by manoger** [comment]
Hello?

**Comment by filfreire** [comment]
Hi @manoger, this can be achieved through custom themes. 

For example, by adapting  https://insomnia.rest/plugins/insomnia-plugin-luna-theme, you can get a result like:

![Image](https://user-images.githubusercontent.com/11976836/186620935-c59db6ee-384c-4121-8e62-b2c448e500ab.png)

Hope this helps 👍

**Comment by manoger** [comment]
thanks.
