### ISSUE TITLE
[Question] Swagger Export

### ISSUE THREAD

**Issue by manoger** [getinsomnia/insomnia#1932]
Good Mornin' .

Is there a native way to export swagger or web page documentation?
Browsing in the web i found this https://github.com/mlabouardy/swaggymnia (what would be nice in "a press of button")

**Comment by zakini** [comment]
There's already a feature request for OpenAPI v3 export (#1778) which is the spec that Swagger conforms to

**Comment by manoger** [comment]
Thanks.
