### ISSUE TITLE
[Feature Request] Import cURL with x-www-form-urlencoded or multipart/form-data

### ISSUE THREAD

**Issue by mandaputtra** [getinsomnia/insomnia#1934]
## Is your feature request related to a problem? Please describe.

Step :

1. Make a request with JS `FormData()`
2. Open DevTools and copy as cURL
3. Import that to Insomnia
4. No form data has parsed into Insomnia

I had a problem importing form cURL, when you had your form data as x-form-url-encoded / multipart/form-data why it can't parse the Form Data?

This following cURL can't be imported into Insomnia, it parse the header but not the body.

```
curl 'https://website.com/api' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Accept: application/json, text/plain, */*' -H 'Sec-Fetch-Dest: empty' -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6Ly9pcmlzLmxvY2FsL2FwaS9hZG1pbi9sb2dpbiIsImlhdCI6MTU2ODIwMjU3OSwiZXhwIjoxNTY4MjA2MTc5LCJuYmYiOjE1NjgyMDI1NzksImp0aSI6IkphUXk1cTFSa0NMeXJyam4ifQ.OoTNsJmqweqweqwsadasdqwe1239TRevZHuw1kC6QpWdth0pN2A' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36' -H 'DNT: 1' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryRQ0NDimFIJ05dYrn' -H 'Origin: https://example.com' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://example.com/job/6' -H 'Accept-Language: en-US,en;q=0.9,id;q=0.8' --data-binary $'------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="remarks"\r\n\r\nHEllo\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="user_id"\r\n\r\n1\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="asign_id"\r\n\r\n1\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="status"\r\n\r\nOngoing\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="update_action"\r\n\r\nstatus\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="gps_coordinate"\r\n\r\nnull\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="picture_before"; filename="Screenshot from 2020-01-31 18-28-13.png"\r\nContent-Type: image/png\r\n\r\n\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn--\r\n' --compressed
```

## Describe the solution you'd like

I want Insomnia to also parse the body, like the chrome does, the image / file (the binary part) aren't necessary but the field is must.

## Describe alternatives you've considered

I have no clue on how this feature could be implemented, but seing how the Chrome Dev tools do it maybe they had some regex on cURL ?

The issue are already discussed here #457, I see no `-F` flag when I copied the network request with chrome dev tools.

Additional context
(empty)

**Comment by Joozty** [comment]
I experience the same issue. Would it be possible to fix it? Thanks

**Comment by kreosus** [comment]
Hi @mandaputtra ,
Good day and I hope that all is well. We have figured out that the import as curl works. As seen in the screenshot below:

If you are trying to import as curl, the multi-part form data needs to be in the format of ```--form key=value```; for each key value pair in the form. In the sample you provided your multi-part  data was in 1 string attached to --data-binary. Which Insomnia will not validate as a valid multi-part form.

![Image](https://user-images.githubusercontent.com/59621250/187685748-2da394e6-a6d1-49b5-b42b-a4df6eec82e7.png)
