### ISSUE TITLE
[Bug] Request path randomly truncated

### ISSUE THREAD

**Issue by abalmos** [getinsomnia/insomnia#1938]
**Describe the bug**
Sometimes the URL path is truncated in the actual HTTP request. See the request headers compared to the UI in the below screenshot. `/auf` was truncated to `/a`. It only happens occasionally and I could not find a pattern. 

**To Reproduce**
1. Make a GET request to any path.
2. Sometimes the path is not correct in the HTTP request.

**Expected behavior**
The path in the request to match the path entered

**Screenshots**
![image](https://user-images.githubusercontent.com/1865093/74395999-c61ba380-4dde-11ea-8e24-d96f04d28643.png)

**Desktop (please complete the following information):**
 - OS: Linux Debian Testing 
 - Installation Method: apt
 - App Version v7.1.0

**Additional context**

**Comment by gschier** [comment]
Do you know if it happens if you try sending the request immediately after finishing typing? It's possible that the slight delay required to save the new URL to the local DB is causing a race condition.

**Comment by abalmos** [comment]
No, it was occurring randomly after clicking the `Send` button. The text could be left alone and 9 out of 10 times or so the URL would be truncated as shown. However, a system upgrade and updating to v7.1.1 seems to have resolved it. I'm closing for now and will re-open if I can recreate the behavior.
