### ISSUE TITLE
[Bug] Blank/White Screen

### ISSUE THREAD

**Issue by jtp10181** [getinsomnia/insomnia#1940]
**Describe the bug**
I open the application and get the title bar, menu bar and a large white space. The menus open but clicking on any of them does not do anything (except some of the help options work).

**To Reproduce**
1. Launch the software
2. White screen

**Expected behavior**
Software should work

**Screenshots**
![2020-02-13 10_35_57-Window](https://user-images.githubusercontent.com/99599/74457030-5395dc80-4e4d-11ea-921f-9f7346c9d919.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Installation Method: Downloaded installer from web page
 - App Version 7.1.0

**Additional context**
It used to work, several months ago, possibly was an older version. Went to use it the other day and it wouldn't work. Have rebooted multiple times. Not sure what version I had before but I re-ran the current installer to see if that would fix it, no luck. Also found some older bugs with fixes, tried deleting the app, deleted the appdata folder. Re-installed again, still not working. I saw another post someone said they had the same issue with Postman, so I tried that, which does work fine for me. I tried the 7.0.6 portapps version and it did the same thing.

The only other thing is I saw people mention a GPU issue. I know my nVidia video card driver was updated since the last time the software worked, not sure if that could have done anything.

**Comment by 4n70w4** [comment]
Similar problem.

![image](https://user-images.githubusercontent.com/38257723/78593162-db490780-784e-11ea-9492-a113680f4a80.png)

**Comment by fredngo** [comment]
Same here:

![Screen Shot 2020-08-04 at 10 14 57 PM](https://user-images.githubusercontent.com/11791/89364226-0bd76b80-d6a0-11ea-8939-4032d96b13d4.png)

**Comment by alannaidon** [comment]
Same for me, but the blank screen whos up when I click on **PREFERENCES**

![image](https://user-images.githubusercontent.com/13774879/100606239-e4a84800-32e7-11eb-8bfc-2e7f50cb1bc8.png)

**Comment by michalkolos** [comment]
Experiencing the same problem here. Insomnia goes blank when opening preferences. Also dev tools are crashing at the same time:
![image](https://user-images.githubusercontent.com/13339255/103323488-4a046b80-4a43-11eb-8e84-1277d6cb15b6.png)

The About window looks like this:
![image](https://user-images.githubusercontent.com/13339255/103323538-951e7e80-4a43-11eb-90bd-5cf3a763fdbe.png)

Insomnia version: 2020.5.2 installed through Snap on Manjaro.

**Comment by soldovskii** [comment]
Same for me, at startup

Version: Insomnia Core 2020.5.2
Release date: 10.12.2020
OS: Darwin x64 20.2.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0

![image](https://user-images.githubusercontent.com/7347880/106153277-18113100-61ca-11eb-842d-b4ebde541b57.png)

**Comment by seanonthenet** [comment]
Happens when I save on any *other app's* window. Consistent and repeatable.

Mac Big Sur
Latest Insomnia
Multi-screen setup

**Comment by svaldetero-envoc** [comment]
Happens when I try to Login for my subscription. Keyboard shortcuts work fine though.
![image](https://user-images.githubusercontent.com/54991761/114752721-3a701080-9d1c-11eb-96d8-4a5a9ab04166.png)

**Comment by wdawson** [comment]
Closing for staleness
