### ISSUE TITLE
[Question] Any way to send a HTTP 1.0 request?

### ISSUE THREAD

**Issue by pgp** [getinsomnia/insomnia#1941]
As the subject says, is there any way I can instruct Insomnia to issue a HTTP 1.0 request (e.g. the equivalent of a `curl --http1.0 https://site.tld` command)?

**Comment by kreosus** [comment]
Hi @pgp,

Are you still experiencing this issue, even with our newest release: https://github.com/Kong/insomnia/releases/tag/core%402022.5.0

**Comment by kreosus** [comment]
Hi @pgp 
You can change the HTTP request Preferences as seen below.

https://kongstrong.slack.com/files/U02JCR2AB1V/F03T8NS15FY/image.png?origin_team=T0DS5NB27&origin_channel=D02KGD00TNY

Thank you and have a nice day.
