### ISSUE TITLE
[Bug] Request header reference variable resolves header multiple times

### ISSUE THREAD

**Issue by lauw** [getinsomnia/insomnia#1942]
**Describe the bug**
When referencing a request header value which contains a generated value (for example, uuid) the result is that the uuid gets generated twice, instead of the retrieving the actual header value.

**To Reproduce**
1. Create a new request
2. Add a header with a generated value (e.g. uuid)
3. Add a header with a reference to that header (by name)
4. See request timeline and view different uuid's being outputted.

**Expected behavior**
I expected it to first resolve the referenced header, then use that value as the actual value, instead of resolving it multiple times.

**Screenshots**
<img width="678" alt="Screen Shot 2020-02-14 at 11 47 09" src="https://user-images.githubusercontent.com/397584/74520262-dab38500-4f1f-11ea-9d08-cfcbb727da6e.png">
<img width="472" alt="Screen Shot 2020-02-14 at 11 47 09 1" src="https://user-images.githubusercontent.com/397584/74520267-dedfa280-4f1f-11ea-8598-1b9a368214d4.png">

**Desktop (please complete the following information):**
 - OS: MacOs 10.15.1
 - Installation Method: downloaded from insomnia.rest
 - App Version 7.0.6 (7.0.6.3258)

**Additional context**
This gave me quite a headache, I was generating a hash out of a uuid which I had to send as well as the uuid itself. I gave up a while ago but recently decided to give it another shot and found out that the issue was here instead of in the target api.

**Comment by kreosus** [comment]
Hi @lauw 
Have you tried this on our newest release, available here: https://github.com/Kong/insomnia/releases/tag/core%402022.5.0?
