### ISSUE TITLE
[Feature Request] About: Show version release date

### ISSUE THREAD

**Issue by erlangparasu** [getinsomnia/insomnia#1944]

**Comment by gschier** [comment]
This is a great idea! We should be able to add a timestamp to the `package.json` generated during `build.js > generatePackageJson()` and reference that in the UI.

**Comment by imrishabh18** [comment]
Hey @gschier , i want to work on this issue. Can you guide me how to add this feature ?

**Comment by erlangp** [comment]
I think it's already added in version 7.1.1 Thanks :)

**Comment by develohpanda** [comment]
Hi @imrishabh18, awesome! 🎉 

In the `build.js` file that Greg mentioned, there is a function called `generatePackageJson()` that outputs a `package.json` file containing some app specific data.

In particular, the `package.json` contains a version number. 
https://github.com/Kong/insomnia/blob/0b0c5baa0e55c847583f679becc5dd8c422a6855/packages/insomnia-app/scripts/build.js#L214

This version number is shown in the preferences modal, and I have added the code snippet where the version number is extracted.
<img width="404" alt="Screen Shot 2020-03-27 at 3 50 44 PM" src="https://user-images.githubusercontent.com/4312346/77716330-cb594880-7042-11ea-9414-4f3f65e8d7c7.png">

https://github.com/Kong/insomnia/blob/0b0c5baa0e55c847583f679becc5dd8c422a6855/packages/insomnia-app/app/ui/components/modals/settings-modal.js#L98

For the release date, you would want to follow a similar approach as the version number. 😄 I'll leave it to you to decide where to show the release date, on the UI! ⚡️

**Comment by imrishabh18** [comment]
@develohpanda Hey, thanks for explaining it so clearly. But i am having an issue setting up insomnia. I have cloned this repo and now running `npm run bootstrap` as said in the initial setup dev in readme but this shows an error the `lerna is not recognized as an internal command` so what should i do next. And also apart from cloning this repo do i even need to download insomnia from there website ?

**Comment by develohpanda** [comment]
No worries!

The first command that is run in `npm run bootstrap` is `npm install`, which should install `lerna`.

If you simply run `npm install`, do you see any errors? Also, are you able to see  `@lerna` under `node_modules`?

<img width="484" alt="Screen Shot 2020-03-30 at 2 22 23 PM" src="https://user-images.githubusercontent.com/4312346/77867031-02716900-7292-11ea-9db7-a7f1870d1fbe.png">

Also, we have a development channel in the Insomina Slack where you might be able to get faster answers to this! https://chat.insomnia.rest/ 🏃 

> Apart from cloning this repo do I need to download Insomnia?

Nope! `npm run app-start` will give you a development instance of Insomnia where you can see your changes.
