### ISSUE TITLE
[Bug] "Duplicate" functionality does not create a distinct element

### ISSUE THREAD

**Issue by stdedos** [getinsomnia/insomnia#1945]
**Describe the bug**
"Duplicate" functionality no longer provides a unique name. ~~Therefore, `Ctrl+D, Enter` will override the current duplicated request with itself i.e. effectively noop~~ It seems I found another "feature": Duplicated requests are not created underneath the duplicated element, but rather last (https://github.com/Kong/insomnia/issues/1946).

While it is impossible (and maybe not desirable) to create a globally unique name, it still feels weird that now duplicating elements over and over will give no cohesion: no "naming related to the ancestor" and https://github.com/Kong/insomnia/issues/1946 I cannot longer effectively create some kind of tree structure

_Disclaimer: Maybe I should revise my naming practices or my workflow in general; however, so far it "seems to work better" to just duplicate templates and add whatever bells and whistles to run the appropriate query. It does not, however, change the fact that the proposed name does not appear to be a feature._

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/133706/74646640-e8b51000-5182-11ea-8122-7c7c24f0e03d.png)
_Name of the request is also `search (Copy)`_

**Desktop (please complete the following information):**
```
Version 7.1.0
Shell 3.1.13
Node 10.2.0
V8 6.6.346.32
Architecture x64

libcurl/7.67.0 OpenSSL/1.1.1d zlib/1.2.11 nghttp2/1.29.0
```

**Additional context**

**Comment by wongstein** [comment]
Hello, sorry for the late reply.  This does feel like a feature request and I agree, an easier experience on Insomnia is something we all want.  If you're still interested in this feature, what I'm hearing from the description is that you'd like Insomnia to help with understanding your request "tree structure" as it evolves via duplication (did I get that right?).  What do you use that request-origination tree structure for and how does it help you in your workflow?

**Comment by stdedos** [comment]
Hello @wongstein, and thank you for your response.

Sadly, as the issue report is 2 years old, I don't remember entirely what is this about.
I vaguely remember that for "one flow", multiple requests are needed, in order. Copy-pasting one specific request (e.g. the login one), means that if the login request changes, then I'll have to manually update all of the login copies.

> Unfortunately, I am not using Insomnia anymore; cost (pain) and benefit (usability/necessity) make it a poor choice for me.

**Comment by wongstein** [comment]
Ah I see a bit what you're saying.  The expectation is, if I create children requests from a parent requests, then I expect changes in that parent requests should be propagated down to the children.  

Just a follow up to that: Should a parent request change always override?  For example, let's say you make a change in the child request, and then you change the parent request in the same field.  Should the parent change then override the child changes?

**Comment by stdedos** [comment]
> Just a follow up to that: Should a parent request change always override? For example, let's say you make a change in the child request, and then you change the parent request in the same field. Should the parent change then override the child changes?

If you'd change the same field, nooo, I don't think the child should "hear" about that change. However, if you "undo" the child's override, then parent's value should be used (kinda like system/global/per-dir configuration option schemes: if `system` is set, and then you set `global`, any change above is transparent to "the overriding level and below")

**Comment by gatzjames** [comment]
Closing as there's no support for overrides and linking of duplicates

**Comment by stdedos** [comment]
At least close as "not-planned" 🙏
