### ISSUE TITLE
[Feature Request] Create duplicated requests underneath the original one

### ISSUE THREAD

**Issue by stdedos** [getinsomnia/insomnia#1946]
_See https://github.com/Kong/insomnia/issues/1945_

If underneath vs last was the resolution of a dispute, please give us a configuration option about it.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jgiovaresco** [comment]
👋  @stdedos 

I'm not sure I understand your request. 🤔 

I've been using Insomnia for a while, and I always thought that when you duplicate a request or a folder, the duplicated item is added just below the original item.

![duplicate-request](https://user-images.githubusercontent.com/4171593/96970865-99469100-1514-11eb-9365-84a23a8263b2.gif)

**Comment by stdedos** [comment]
Hello @jgiovaresco. Thank you for your response.

Sadly, as the issue report is 8 months old, even "just" the updates on the repository might have inadvertently fixed the issue I have reported.

Unfortunately, I am not using Insomnia anymore; cost (pain) and benefit (usability/necessity) make it a poor choice for me.
