### ISSUE TITLE
Chrome 66 is incompatible with SameSite=None cookies

### ISSUE THREAD

**Issue by BlazeAgator** [getinsomnia/insomnia#1948]
This is a request to update Insomnia's Electron "embedded" browser  to a version that supports SameSite=None cookies. 

Details
https://www.chromium.org/updates/same-site
 - February, 2020: Enforcement rollout for Chrome 80 Stable: The SameSite-by-default and SameSite=None-requires-Secure behaviors will begin rolling out to Chrome 80 Stable for an initial limited population **starting the week of February 17, 2020**, excluding the US President’s Day holiday on Monday. We will be closely monitoring and evaluating ecosystem impact from this initial limited phase through gradually increasing rollouts. 

Testing other REST clients like ARC, it uses Electron/4.2.2, and this version can successfully handle SameSite=None cookies.

The current behavior with OAuth2.
1) Enter user name and password
2) And instead of being prompted to accept the grant request, I am brought back to the login page

Looking in Fiddler I can see in the header section that the session id has been stripped off in the next request

**Comment by malheleco** [comment]
I'm not sure if it is exactly the same issue or potentially a strongly related one: if a server on localhost (http) returns a `Secure` cookie (`HttpOnly=true; SameSite=None`), Insomnia will store it in its cookie manager but will not send it.
Afaik, localhost should be allowed to use `Secure` for http.
Manually removing the secure flag in insomnia's cookie manager seems to be a workaround.

**Comment by gatzjames** [comment]
Closing as electron is updated to the latest version
