### ISSUE TITLE
[Improvement] Platform specific menus

### ISSUE THREAD

**Issue by ctnordcl** [getinsomnia/insomnia#195]
Since the native UIs and borders and such differ drastically across MacOS, Windows, and Linux, I believe we should make a concerted effort to address this. Electron has a custom menu building interface, and allows you to build menus for each platform, and then load the application with a given menu based on `process.platform`. Doing this would help our users have a more consistent experience across platforms.

**Comment by gschier** [comment]
Insomnia already builds its menu slightly different depending on platform. https://github.com/getinsomnia/insomnia/blob/develop/app/main/window-utils.js#L86

However, I think the placement of each item, as well as naming, could better use each platform's best practices for this.

**Comment by gschier** [comment]
Closing as stale.
