### ISSUE TITLE
[Feature Request] Subversion/SVN support

### ISSUE THREAD

**Issue by d3vk47** [getinsomnia/insomnia#1957]
**Is your feature request related to a problem? Please describe.**
I understand that the Insomnia server is a long ways to come.  Maybe there is a quick option.

**Describe the solution you'd like**
I would like to save my workspaces and the associated requests in a subversion/svn instance.

**Describe alternatives you've considered**
I've considered the Insomnia server, but from what I could see, it is a long time coming.

**Additional context**
It is also practical that other peers can review my requests and either use them or adjust them.  SVN is used in our company and makes it easier to share and control in one place.

**Comment by filfreire** [comment]
Hi @d3vk47, thank you for reporting this issue!

Someone else might correct me here, but for now there are no plans to support Subversion at all. 

Alternatively, you should now be able to use [Insomnia Teams](https://docs.insomnia.rest/insomnia/teams) to safely collaborate with your colleagues on your request collections.

Note for @wdawson: I'm preemptively closing this one, but please re-open if in the meantime we decide from a product perspective we will add Subversion support.
