### ISSUE TITLE
[Feature] Markdown description fields for Requests, Workspaces, and Folders

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#196]
Currently, it is possible to add description text to a workspace via the workspace settings dialog. Many users have requested via email to also be able to add a description to requests and request groups (aka folders). On top of this, the ability to support markdown would be 👌 

![image](https://cloud.githubusercontent.com/assets/587576/26008615/691894c0-36fa-11e7-875e-8b41afe93b75.png)

Things to do:

- Custom React component to preview and edit a markdown description
- Update `Request` and `RequestGroup` models to add `description` field
- (optional) Somehow have a quick way of previewing a description or at least showing that one exists at a glance

**Comment by ValeriaVG** [comment]
There's a steroid markdown for api description https://github.com/apiaryio/api-blueprint .
It has a testing tool based on that description and a service for api-documentation but still is a markdown. Is there a way to integrate Api-blueprint? I'd help with that

**Comment by gschier** [comment]
@ValeriaVG how would you like to see API Blueprint integrated into Insomnia? Are you wanting the ability to generate API documentation? if so, I think that should be a separate discussion. There are a lot of tools and formats out there for doing that. I've played around with [Slate](https://github.com/sdelements/node-slate) previously and enjoyed its simplicity.

Something like Blueprint may be a great use for a data export plugin (#51). 

Happy do discuss further. 😄

**Comment by ValeriaVG** [comment]
@gschier  i'll definitely take a closer look at Slate, thaks for pointing. Mostly I'd like to see not only description and names of method but their required/optional fields, response format etc. In other words something similar to apiary - http://docs.test13486.apiary.io/#reference/0/questions-collection/create-a-new-question . And import/export to .apib

Technically having any markdown for API description and export/import tool will be just the same.

I'll take a look at the plugin framework to see if I can provide any help there

**Comment by ValeriaVG** [comment]
I am working on that issue and I have couple of things to discuss.

First, I think it's better to write a component that would be able to have a changeable  parser/renderer  (to implement a apib/slate/etc plugin later). Planning to use https://github.com/jgm/commonmark.js as default. 

Second, but not less important is a place for the description itself. I think an additional pane between request pane and sidebar would be nice (it needs to have an option to be hidden though). Since description can be long and have some info that user may use as a reference while working with requests, hover-only texts and modal windows doesn't fit much. 

And, a small icon like http://fontawesome.io/icon/book/ or http://fontawesome.io/icon/pencil-square-o/ would be a button to toggle description pane on markdown editor window (if no description provided). It can be same icon in different colors (white - has description, semi-transparent - doesn't have) or different ones. And description pane should have an edit button too.

So, what do you think?

**Comment by gschier** [comment]
Awesome to see you working on this. Just a few thoughts.

I don't think it's necessary to design for a changeable parser/renderer yet. That will be easy to change if/when the time comes.

Is there a specific reason for using commonmark? It looks good but doesn't seem very popular (492 stars).
 [marked](https://github.com/chjj/marked) (12,000 stars) may end up being a better choice in the long run.

As for how to show the documentation in a non-modal way, I think that step could be done in a separate PR. I was thinking to start with a tabbed editor/preview component very similar to the Github editor that I'm writing this comment in right now but without the toolbar on the top-right.

**Comment by ValeriaVG** [comment]
Placed marked and the tabbed editor in the request settings modal window for now. 

I tried different options, but another pane on the screen makes a mess. 

Maybe it can be a good idea to show compiled descriptions in a toast-like window in the bottom left? 

Should I duplicate editor for workspaces, folders etc or first make a pull request with what i have?

**Comment by gschier** [comment]
It's always good to show your code as early as possible 😄 

If you submit a PR with what you have, I'll provide some early feedback. If the editor is modular enough, I don't see a reason not to apply it to requests. Folders don't yet have a settings screen so maybe hold off on folder description for now (unless you _want_ to make one).

**Comment by wonderbeyond** [comment]
Awesome feature. Thus a exported data file can serve as document and demo.

**Comment by carlosvasquezOF** [comment]
Will not this function be done?

**Comment by gschier** [comment]
It will be in the next release

**Comment by Saceone** [comment]
Is it possible to edit folder descriptions? 
In the exported json there is, in fact, an attribute "description". If I manually edit this field with some text, I am able to see it using insomnia-documenter, for example. However, I think it should be possible to edit that from insomnia itself.
