### ISSUE TITLE
[Bug] accessing environmental variables that contain hyphens

### ISSUE THREAD

**Issue by veritascs** [getinsomnia/insomnia#1960]
**Describe the bug**
Environmental variables with a dash in them can't be referenced correctly (ie 'x-client-id' or something).

**To Reproduce**
1. go to env vars `control+e`
2. add a variable with a dash in it, ie `x-client-id`
3. click done
4. go to a request, add a header
5. press `control+space`, select one the new variable
6. hover mouse over the var, see NaN in live preview

**Expected behavior**
See the value you put in your environmental variable.  Additionally, the value is null on actual REST calls.

**Screenshots**
![image](https://user-images.githubusercontent.com/4104863/75069423-009fd300-54a6-11ea-9698-6b45aa9271cb.png)

![image](https://user-images.githubusercontent.com/4104863/75069363-e108aa80-54a5-11ea-85c6-e807b872aabc.png)

**Desktop:**
 - OS: Clear Linux
 - Installation Method: appimage (https://support.insomnia.rest/article/23-installation#linux)
 - App Version, see screen shot below (v7.1.1):
![image](https://user-images.githubusercontent.com/4104863/75069552-3fce2400-54a6-11ea-8b4d-c4da0760fc1d.png)

**Comment by LDT9510** [comment]
I have the same problem, and noticed that this happens excusively when the dash (-) is in the JSON key. Found a closed issue that solved that same problem when the dash was on the value, that works now but when in the key it resolves to NaN.

**Comment by veritascs** [comment]
@XReaper95 can you point me to that resolved issue? Maybe we can help resolve this issue!

**Comment by LDT9510** [comment]
Sure, is this one #456. It looks like I was wrong, because it is exactly the same issue, apparently it has not been resolved for now. So I guess this is a duplicate. I didn't read it all, so maybe there is some workaround.

**Comment by veritascs** [comment]
Looks like #456 is closed because it started showing a warning message. However, this warning message no longer shows...

But #1666 is still open, so I'll close this out because it's a duplicate of the same issue.
