### ISSUE TITLE
[Bug] Required version of Node in the README

### ISSUE THREAD

**Issue by berengerLodi** [getinsomnia/insomnia#1965]
**Describe the bug**
The README states that we need `NodeJs 8`, some people may think we explicitly require the 8 version and not a more recent version.

Shoud we modify it to put NodeJs `8+` instead of `8` ?  
Also, do we still support NodeJS `8` ? It's `EOL` since `December 31 2019`

**Comment by gschier** [comment]
Development should use the same version of Node that is included in the Electron dependency. Currently, it's 10. 

12 won't work right now because it fails to build our native `libcurl` dependency. I'll update the readme to point to the `.nvmrc` included in the project.
