### ISSUE TITLE
Documentation not updated on schema refresh

### ISSUE THREAD

**Issue by dobrynin** [getinsomnia/insomnia#1966]
**Describe the bug**
Refreshing the schema does not refresh the schema documentation.

**To Reproduce**
1. Click schema wrench button 
2. Click 'Show Documentation'
3. Observe the state of the schema as shown in the documentation.
4. Make a change in the schema that should change the docs
5. Click 'Refresh Schema'
6. open the documentation again and see that it has not changed appropriately.

**Expected behavior**
Documentation updates when schema changes.
****
**Desktop**
 - OS: macOS 10.14.6
 - Installation Method: downloaded from internet
 - App Version v7.1.1

**Comment by ranjan-purbey** [comment]
May I take up this issue?

**Comment by develohpanda** [comment]
> May I take up this issue?

Hi @ranjan-purbey, feel free to! Sorry about the late response 🤗 it's been a busy few weeks!
