### ISSUE TITLE
[Feature Request] Allow for running multiple unrelated API requests at the same time

### ISSUE THREAD

**Issue by jamescook000** [getinsomnia/insomnia#1967]
**Is your feature request related to a problem? Please describe.**

When I have configured multiple API requests and I would like to run more than one in order at the same time I have to manually select and run each one individually, for example:

* API Request 1 - Create HostX using some REST API
* API Request 2 - Create HostY using some REST API
* API Request 3 - Create HostZ using some REST API

**Describe the solution you'd like**

I would like to have a definition that I can run and it will run the above three API requests, for example:

* API Batch 1 - Create Hosts
   - API Request 1 - Create HostX using some REST API
   - API Request 2 - Create HostY using some REST API
   - API Request 3 - Create HostZ using some REST API

Then I would click 'API Batch 1 - Create Hosts' and run this, which would in turn run the 3 API requests in order.

**Describe alternatives you've considered**

Unfortunately looking at other methods like other products or Python coding etc...

**Additional context**

No additional context

**Comment by filfreire** [comment]
Hi @jamescook000 thanks for reporting this!

As of now we have a few ways of achieving this.

- You could try to place your requests in a [Design Document](https://docs.insomnia.rest/insomnia/design-documents), and then create a [Test Suite](https://docs.insomnia.rest/insomnia/unit-testing) where you run all of them.

Or

- You could try use a community plugin to achieve this, there are a few available: https://github.com/michaelversus/insomnia-plugin-multiple-requests, https://github.com/rapsalands/insomnia-plugin-exec-suite, https://github.com/harrymilnes/insomnia-plugin-multi-request

Feel free to reach out and report other issues if you come across other ideas and problems.
