### ISSUE TITLE
[Feature Request] Support Base64 encoding files

### ISSUE THREAD

**Issue by aldaris** [getinsomnia/insomnia#1971]
**Is your feature request related to a problem? Please describe.**
I have a REST API that expects a JSON payload along the lines of:

```
{ "someXml": "<base64url encoded XML>" }
```

A more valid use-case:
```
{ "jpegPhoto": "<base64url encoded image>" }
```

It seems like that the Base64 encoding plugin doesn't allow encoding contents of a file, and the File plugin does not allow encoding the contents with Base64, and I couldn't find a way to chain these two plugins together either.

**Describe the solution you'd like**
There is a way to include a file's content in a payload with Base64 encoding applied.

**Describe alternatives you've considered**
Tried to include a file's content by manually copying it to the Value field of the Base64 encoding plugin, but then got a parse error on the JSON payload, so not really sure what happened there.

**Additional context**
![parsing-error](https://user-images.githubusercontent.com/206692/75545202-947d1c00-5a1d-11ea-820b-93632a87d05d.png)

**Comment by gschier** [comment]
The best way to go about this would be to create your own plugin. 

I just did a quick search and it looks like someone already has https://www.npmjs.com/package/insomnia-plugin-base64-file
