### ISSUE TITLE
[Bug] Multiple Requests Sent on Keyboard Shortcut

### ISSUE THREAD

**Issue by bryangateley** [getinsomnia/insomnia#1973]
**Describe the bug**
Standard Shorcuts "Ctrl + Enter", "Ctrl + R", "F5" will send a duplicate request. When clicking send from the UI only one request is sent. 

**To Reproduce**
Create Request. Use keyboard shortcut. 

**Expected behavior**
Only one request to be sent per keyboard shorcut. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1903 for x64 (KB4534132)
 - Installation Method: Download exe
 - App Version V7.1.0

**Comment by nikandlv** [comment]
#### Facing the same issue here.

OS: Kubuntu 19.10
Installation Method: Binary
App Version V7.1.0

**Comment by bryangateley** [comment]
Issue seems to be resolved with V7.1.1 
Edit: Nevermind.

**Comment by gschier** [comment]
Ah yes, I think that was probably related to #1951
