### ISSUE TITLE
[Bug] Json path gives values instead of "key": "value"

### ISSUE THREAD

**Issue by dj13may91** [getinsomnia/insomnia#1974]
**Describe the bug**
Json path gives data (values) instead of "key": "value" where as [http://jsonpath.herokuapp.com/?path=$.store.book[*].author](url) gives data with keys as well.

**To Reproduce**
1. Go to 'https://jsonplaceholder.typicode.com/todos/1'
2. Response: 
`{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}`
3. Adding filter for json path : `$[*]` should give the same data as in above request , while the response in insomnia is
`[
  1,
  1,
  "delectus aut autem",
  false
]`
4. hence the keys are lost and hence i can not query as per json path.

**Comment by gschier** [comment]
Insomnia uses [`jsonpath`](https://www.npmjs.com/package/jsonpath) which may not have the exact behavior of other jsonpath libraries. There don't seem to be any really good ones for NodeJS.

There are plans to make the response filter pluggable to include your own libraries, however, which will provide more flexibility around dealing with issues like this.
