### ISSUE TITLE
[Question] Restore data after fresh OS install

### ISSUE THREAD

**Issue by eregnier** [getinsomnia/insomnia#1975]
**What is your question?**
Hey, First, thank you for Insomnia, it's a very cool software I use more and more every day.

I have an "issue". I formated my linux computer, reinstalled a fresh linux , rsync my home , installed insomnia and ran the program. Then nothing in the UI, my settings are not "read / recognized" even if my .conf/Insomnia folder is populated like the FAQ describes 
![image](https://user-images.githubusercontent.com/5399780/75679547-21c7a700-5c90-11ea-9f6c-b21683cc2304.png)

Mine looks like this and my insomnia is empty :cry: 
![image](https://user-images.githubusercontent.com/5399780/75679575-2db36900-5c90-11ea-878f-e5108a511200.png)

![image](https://user-images.githubusercontent.com/5399780/75679625-49b70a80-5c90-11ea-82ab-27a36680ee00.png)

Nothing in env managements and everywhere else even if the `help>show app data folder` works properly.

Do I have something else to try to recover my settings are they just lost ?

Thank you for any help / suggestion.

**Comment by gschier** [comment]
If your rsync included the `.config/Insomnia` folder, then it should have re-opened with all your data. Did you have a backup that you can pull from?

**Comment by eregnier** [comment]
I have no backup, only the .config/Insomnia folder. It does not work as expected. That's strange as zll other software continued ,working the same with rsync

**Comment by gschier** [comment]
If you inspect the `*.db` files in the `Insomnia/` folder, do you see your data in there?

Also, be sure to check Help > Show AppData Folder within Insomnia to ensure it's pointing to the same place as before.

**Comment by eregnier** [comment]
I should have worked, but it did not . I wiped my work and started another project.

Thank you for your time anyway, Insomnia remains very cool to me ;)

**Comment by NicmeisteR** [comment]
@gschier Thanks! Recently accidentally formatted my pc but still had access to AppData and was able to restore my Workspaces by copying all of the .db files.
