### ISSUE TITLE
[Question] Accessing system env vars from inside Insomnia environments

### ISSUE THREAD

**Issue by arboleya** [getinsomnia/insomnia#1977]
Is it possible to have an environment variable in insomnia, that evaluates the value of a system env var? The goal is not to have hard-coded secrets inside Insomnia env variables, so when we `export`/`import` data, the output files would not have any sensitive information inside them.

Thanks.

**Comment by etauker** [comment]
Hi, I'm looking for the same functionality also.
Any plans for this?

**Comment by etauker** [comment]
Just saw that this is a duplicate of https://github.com/Kong/insomnia/issues/1883.

**Comment by arboleya** [comment]
@etauker Totally, I haven't seen this one. Closing in favor of #1883
