### ISSUE TITLE
[Bug] PDF file saved from response remains locked until Insomnia is closed

### ISSUE THREAD

**Issue by watery** [getinsomnia/insomnia#1979]
I was unsure whether filing this as a _bug_ or _feature request_, I decided for the former in case an open handle is being held after write completion.

**Describe the bug**
I sent a request to a Rest API that returns binary data - a PDF file. I did "Save raw response" from the "Preview" tab submenu, creating a new PDF file.
If I open that file with a reader - I've tried both Foxit PDF Reader and Adobe Acrobat Reader - I get a "sharing violation error" message and the file cannot be opened.

After exiting Insomnia, I can successfully open the file, which has been correctly saved.

**Expected behavior**
Once the save has been completed, the file shouldn't be locked / owned by Insomnia and be freely readable from other applications. This would ease checking several contents too.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Installation Method: downloaded from the homepage
 - App Version 7.1.1

**Comment by guaranadev** [comment]
I have the same problem after any kind of response data is saved to file.

OS: Windows 10
App version: 2020.2.2

**Comment by mustex** [comment]
Same issue here.  Insomnia is still holding a lock onto the saved file and doesn't release the lock until Insomnia is closed.

OS: Windows_NT x64 10.0.18363
App Version: 2020.5.2

**Comment by smarkwell** [comment]
Ditto, work around is to close Insomnia after the response is saved.  Then the file lock is cleared.
(In my scenario it's ZIP files, but the issue isn't file type dependent).  

```
Version: Insomnia Core 2020.5.2
Release date: 12/9/2020
OS: Windows_NT x64 10.0.19042
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0
```
