### ISSUE TITLE
[Bug] Unable to Open "Choose File" Dialog

### ISSUE THREAD

**Issue by collinzh** [getinsomnia/insomnia#1982]
**Describe the bug**
Unable to open "Choose File" window when choosing file type data for multipart form.

**To Reproduce**
1. Go to any "POST" request
2. Change the body type to "Multipart" and 
3. Add a field and change the type to "File"
4. Click on "Choose File"
5. Insomnia freezes for couple seconds, then nothing happens.

**Expected behavior**
User is then allowed to choose a file on their system.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Installation Method: Downloaded from website
 - App Version 7.1.1

**Additional context**
The following information was found in system logs.
![Screen Shot 2020-03-04 at 13 50 57](https://user-images.githubusercontent.com/1828839/75912662-911fd100-5e1f-11ea-9b61-82571baee452.png)

**Comment by collinzh** [comment]
Restarting the computer seems to resolve the issue.

**Comment by gschier** [comment]
I'm guessing it's some sort of permissions issue, not related to Insomnia. Does it work with regular files on your Desktop, for example?

**Comment by collinzh** [comment]
Hey @gschier ,

Thanks for responding. The issue isn't with selecting a specific file, it's about just opening the "Choose File" dialog window. Clicking on "Choose File" button simply freezes Insomnia for a few seconds, and nothing happens.

**Comment by gschier** [comment]
Thanks for clarifying. I'm not able to reproduce the issue on my machine, unfortunately. 

![image](https://user-images.githubusercontent.com/587576/76369327-6b4b6e00-62f0-11ea-8500-e3d7804ca44e.png)

**Comment by filfreire** [comment]
Closing as stale.
