### ISSUE TITLE
[Bug] Default permissions in Ubuntu: record and play sound

### ISSUE THREAD

**Issue by wchest** [getinsomnia/insomnia#1983]
**Describe the bug**
It appears that Insomnia enables the recording and playing of sound on your device by default when installing the application. Using gnome-software to install Insomnia shows a "Permissions" option once Insomnia is installed. Opening the dialog presents two options: 1. "Access files in your home directory", 2. "Play and record sound". Both of these options are checked by default.

**To Reproduce**
1. Go to "Software" in Ubuntu 19.10 and search for Insomnia
2. Install the latest version of Insomnia
3. Once installed, click on the "Permissions" option in the action block "Launch | Remove | Permission"
3. You will see the options to allow permissions for "Access files in your home directory" and "Play and record sound"

**Expected behavior**
I see no obvious reason that Insomnia needs to play or record sound, so would expect that this permission would not be needed. At the very least, I would expect this permission to be off by default. Alternatively, it would be better if the record and play permissions were separate.

**Screenshots**
![insomnia-app-permissions](https://user-images.githubusercontent.com/470326/75923239-86623d80-5e19-11ea-855c-c57eee96d717.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Installation Method: gnome-software
 - App Version: v7.1.1

**Additional context**
N/A

**Comment by gschier** [comment]
Hmm, that's strange. I wonder if it's for the notification system. Do other Electron apps installed from Software trigger the same permission requests?

**Comment by wchest** [comment]
@gschier - good question. I just took a look at two supposed Electron apps (Simplenote and Poddr) from Software. Simplenote does not include any permissions, Poddr, as you could imagine, asks for access to files in the home directory, play and record sound, as well as controlling music and video players (see screenshots). It's definitely possible that Simplenote doesn't use the notifications system at all, and maybe that's why it's not listed.

![Screenshot from 2020-03-08 17-21-40](https://user-images.githubusercontent.com/470326/76174037-e2063100-6161-11ea-8f26-1a48e49753e9.png)

![Screenshot from 2020-03-08 17-23-29](https://user-images.githubusercontent.com/470326/76174040-e4688b00-6161-11ea-8bac-99f96fb66358.png)

**Comment by wchest** [comment]
Nevermind, I spoke too soon. I went back to the Simplenote entry to remove uninstall it and the permissions button appeared. It looks like play and record sound is enabled by default, and they list a few other permissions:

![Screenshot from 2020-03-08 17-28-55](https://user-images.githubusercontent.com/470326/76174098-6eb0ef00-6162-11ea-8c02-a89b53e0b01d.png)

**Comment by gschier** [comment]
Okay, thanks for digging into that a bit! 

I'm going to assume there's nothing we can do about this one as there is not explicit code to handle sound.
