### ISSUE TITLE
[Bug] Can't switch to previous item in response history

### ISSUE THREAD

**Issue by eczex** [getinsomnia/insomnia#1985]
**Describe the bug**
I'm unable to open previous response in history. I can go two steps back, but can't go one step back.

**To Reproduce**
1. Open history menu in top right corner
2. Click on previous item to go one step back.
3. **Nothing happens.**
4. Click on one of the earlier items. 
5. See that response.
6. Click on the item second from the top (same as in step 2).
7. **Last response opens.** 

**Expected behavior**
3. Opens previous response (second from the top).
7. Opens previous response (second from the top).

**Screenshots**
https://yadi.sk/i/he8mbtNQFPzGXg

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.15.3 (19D76)]
 - Installation Method: .dmg from site
 - App Version: 7.1.1.3350

**Additional context**
I noticed this issue after updating to Catalina.

**Comment by eczex** [comment]
It looks like I can't switch to previous responses with the same response code.
https://yadi.sk/i/3WI-YZV_MxzcAw

**Comment by gschier** [comment]
I just reproduced this on my end. Will take a look

**Comment by jgiovaresco** [comment]
@eczex I try to reproduce with the last version of Insomnia, but it seems I can open any of my previous responses.
Could you retry on your hand?

**Comment by DMarby** [comment]
I think this is the same bug as #2675, which has a fix pending in #2735 @jgiovaresco

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.
