### ISSUE TITLE
[Bug] Plugins fail to install via Snap package

### ISSUE THREAD

**Issue by asyba** [getinsomnia/insomnia#1989]
**Describe the bug**
Can't install plugins.
There is no package.json file in the installation folder, so I can't install plugins.

**To Reproduce**
Check images:
![image](https://user-images.githubusercontent.com/1466530/76218283-bb440b00-61f2-11ea-96d8-d5107d548bb9.png)

![image](https://user-images.githubusercontent.com/1466530/76218161-7ddf7d80-61f2-11ea-951c-56f6be75abb0.png)
![image](https://user-images.githubusercontent.com/1466530/76218220-99e31f00-61f2-11ea-92f4-50e60e3ff3a2.png)

![image](https://user-images.githubusercontent.com/1466530/76218198-8cc63000-61f2-11ea-90b8-2b841f491538.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation Method: snap
 - App Version 7.1.1

**Comment by gschier** [comment]
There are two things here, it seems:

1. Plugins fail to install from the UI when using the Snap version
2. NPM requires a `package.json` to install modules

(2) can be solved by running `npm init` from the plugins folder to generate a dummy `package.json`. (1) is a bug, but can be worked-around now by using the `deb` package instead of Snap on Ubuntu.

**Comment by asyba** [comment]
@gschier I should close this or leave open?

**Comment by gschier** [comment]
Will leave it open for now, as it's technically a bug with the Snap package.

**Comment by santiagofn** [comment]
Any news on this? Is any workaround possible?

Edit: I've now read about the deb workaround. Ubuntu offers the snap version by default, as the official package, I never knew there was a custom repository until I entered support.insomnia.rest. I believe most Ubuntu fresh installations will suffer from this.

**Comment by KCulture** [comment]
I am getting a similar error message I am using snap Ubuntu 20.04., insomnia 2021.1.3

![image](https://user-images.githubusercontent.com/860399/119233984-4cde2680-bae0-11eb-8e7d-7079bfaa2924.png)

I assume that I am getting this message for similar reason but what wanted to make sure that it was noted.
Let me know if you believe that this issue is unrelated and I can create a new issue

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

**Comment by thejatmik** [comment]
I am getting similar error but I found the workaround by cloning the plugin repository to Insomnia plugins folder.

Received error message:
![image](https://user-images.githubusercontent.com/13992930/133217570-ae0f2232-af8a-42fa-b9fa-3d831fd2195e.png)

My workaround:
- `cd ~/snap/insomnia/current/.config/Insomnia/plugins/`
- `git clone https://github.com/Malm/insomnia-plugin-save-access-token.git`
- Reload plugins

**Comment by kreosus** [comment]
Hi @asyba 
Do you see the same behavior with our latest release located here: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.4

**Comment by lippertto** [comment]
Hello,
the error still persists with the current snap version. I am using the following version:
```
snap info insomnia | grep installed
installed:    2023.1.0        2023-03-09 (196) 117MB -
```

When I try to install the plugin `insomnia-plugin-path-parameters`, I get the following error:
```
13:47:22.941 › [main] Open Deep Link URL sent from second instance insomnia://plugins/install?name=insomnia-plugin-path-parameters
13:47:29.571 › [plugins] Fetching module info from npm
13:47:29.612 › Error occurred in handler for 'installPlugin': Error: Yarn error /snap/insomnia/196/insomnia: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

    at /snap/insomnia/196/resources/app.asar/main.min.js:39741:18
    at ChildProcess.exithandler (node:child_process:417:5)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1093:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:757:14)
```

**Comment by lippertto** [comment]
I do have the library installed in `/usr/lib/x86_64-linux-gnu/libnss3.so`.
My guess is that the library cannot be accessed from the snap environment. I do not know much about snap internals. But I would guess that the base image that you use for this snap needs the library installed.

**Comment by lippertto** [comment]
I do not know much about snap packages. It looks like the library is already contained. There is already one in the snap directory. 
```
find /snap/insomnia/196/ | grep libnss3
/snap/insomnia/196/usr/lib/x86_64-linux-gnu/libnss3.so
```

I can see that the insomnia binary is looking in the wrong location. ldd gives me the following
```
ldd /snap/insomnia/196/insomnia | grep nss
	libnss3.so => /lib/x86_64-linux-gnu/libnss3.so (0x00007f8977434000)
	libnssutil3.so => /lib/x86_64-linux-gnu/libnssutil3.so (0x00007f8977403000)
```

My libnss3.so is in `usr/lib/x86_64-linux-gnu/libnss3.so` and the snap one is in `/snap/insomnia/196/usr/lib/x86_64-linux-gnu/libnss3.so`. So the build process is messing up something.

**Comment by lippertto** [comment]
Oh, this bug has been raised in a newer ticket. (#4316) I will cross post my last comments here.

**Comment by pedroegg** [comment]
> I am getting similar error but I found the workaround by cloning the plugin repository to Insomnia plugins folder.
> 
> Received error message: ![image](https://user-images.githubusercontent.com/13992930/133217570-ae0f2232-af8a-42fa-b9fa-3d831fd2195e.png)
> 
> My workaround:
> 
> * `cd ~/snap/insomnia/current/.config/Insomnia/plugins/`
> * `git clone https://github.com/Malm/insomnia-plugin-save-access-token.git`
> * Reload plugins

Worked here!

**Comment by Saphyel** [comment]
Any official solution for this??
