### ISSUE TITLE
[Bug] 301 Moved Permanently - Cache Issue

### ISSUE THREAD

**Issue by masseelch** [getinsomnia/insomnia#1991]
**Describe the bug**
Calling a route which returns a 301 response correctly redirects. If the route then no longer returns a 301 insomnia still will redirect to the resource. I cannot find any other way then completely wipe out all insomnia configuration to reset this cached redirect.

**To Reproduce**
1. call a route which returns 301
2. let the route no longer return 301
3. call it again
4. insomnia will redirect like the route still returns the 301

**Expected behavior**
I no longer get redirected.

**Desktop:**
 - OS: manjaro
 - Installation Method: aur
 - App Version v7.1.1

**Comment by gschier** [comment]
Hmm, that's interesting. I guess `libcurl` is remembering 301 (permanent redirect) redirects as it is supposed to. However, you're correct that this behavior does not really make sense for an app like Insomnia.

After some Googling, it doesn't look like there's a way to have libcurl not cache 301s. Does it reset after Insomnia is restarted @masseelch?

**Comment by masseelch** [comment]
Restarting does not reset the cache. A fresh install, which essentially deletes the cache folder of insomnia, does reset the saved 301.

**Comment by masseelch** [comment]
BTW, as far as I know libcurl does not cache anything. But I might be wrong there.

**Comment by gschier** [comment]
I didn't think it cached anything either. Insomnia defers to `libcurl` for all redirect handling so it's hard to say what's going on for sure.

Can you test `curl` (not necessarily the same behavior as libcurl) from the command line to see if it exhibits the same behavior?

**Comment by masseelch** [comment]
Will do on the weekend :+1:

**Comment by masseelch** [comment]
curl does not cache / save 301 responses. 

I called a route, returned 301 and curl followed. 
Called route again, did return 200 and curl did not redirect.

**Comment by TheCataliasTNT2k** [comment]
Still an issue.....
Would be nice, if you can disable the cache completely when you want to do so.......

**Comment by thewheat** [comment]
I could not replicate this on MacOS with a test PHP server. Could the replication steps be missing anything? Or could this be OS dependent?

**Insomnia details**
```
Version: Insomnia Core 2020.4.1
Release date: 9/23/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Test file**
```
<?php
header("HTTP/1.1 301 Moved Permanently");
header("Location: http://www.google.com");
?>
```

**Request when setup a 301 redirect**
![image](https://user-images.githubusercontent.com/892961/97015492-3853a300-157e-11eb-89a0-101b0c2cb960.png)


**Change file content to no longer redirect and get a 200 and file loads**
![image](https://user-images.githubusercontent.com/892961/97015613-59b48f00-157e-11eb-9443-c978f37e1374.png)

**Comment by masseelch** [comment]
I can check again with my setup. Will take me a day or so.

**Comment by masseelch** [comment]
I did another test and the issue still is present. 

**Insomnia details**
```
Version: Insomnia Core 2020.4.1
Release date: 10/26/2020
OS: Linux x64 5.4.67-1-MANJARO
Electron: 9.2.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.72.0 OpenSSL/1.1.1h zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0
```

**My Testserver (Go)**
```
package main

import "net/http"

func main() {
	http.ListenAndServe(":8000", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "https://www.google.com", http.StatusMovedPermanently)
                //w.Write([]byte("Hello World!"))
	}))
}
```

**With 301**
![image](https://user-images.githubusercontent.com/12862103/97186263-5c42fe80-17a1-11eb-924c-8b51fef128cf.png)

**Changed to simple 200 - "Hello World"**
![image](https://user-images.githubusercontent.com/12862103/97186467-9a402280-17a1-11eb-8069-8d965f1c3ece.png)

The issue remains.

**Comment by thewheat** [comment]
I think this could be an OS issue as I couldn't replicate on macOS

![redirect-with-go](https://user-images.githubusercontent.com/892961/97547040-41be8e80-1a08-11eb-8037-4a0a0c0612cb.gif)

**Comment by masseelch** [comment]
Weird! I'll run another test on Debian.

**Comment by masseelch** [comment]
@TheCataliasTNT2k What OS do you use? Happen to be Manjaro or Arch too?

**Comment by jgiovaresco** [comment]
I can't reproduce the issue either :thinking: 

I've tried on Mac

```
Version: Insomnia Core 2020.4.2
Release date: 30/10/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

and on Linux Mint

```
Version: Insomnia Core 2020.4.2
Release date: 10/30/2020
OS: Linux x64 5.4.0-52-generic
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libssh2/1.9.0 nghttp2/1.41.0
```

I'm using a [simple Node.js server](https://github.com/jgiovaresco/node-simple-server) on which I built a [route](https://github.com/jgiovaresco/node-simple-server/blob/master/src/routes/get-with-301-redirect.ts) that will redirect every two requests.

Would it be related to the `libcurl` version? I'm noticing that @masseelch had the version `libcurl/7.72.0` but on my both installations, it was `libcurl/7.69.1`

**Comment by masseelch** [comment]
I downgraded to `libcurl/7.69.1` but the issue still remains. 

However, using Debian everything works like it should. It seems to be anOS issue after all. Closing this then.
