### ISSUE TITLE
[Question] Use templates for multiple graphql examples

### ISSUE THREAD

**Issue by mikeh-35** [getinsomnia/insomnia#2005]
Is it possible to use a templating system to replicate Postman's ability to add multiple examples of queries to a single endpoint?

For example a basic query of:

```
{
  users {
    edges {
      node {
        name
        id
        externalUserId
      }
      cursor
    }
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
      startCursor
    }
  }
}
```

Plus examples of filtered queries such as:

```
query {
    users (criteria: {userId: "13b3ab9c-XXXX-XXXX-XXXX-c4dd07fbbfa4"}){
        edges {
            node {
                name
                id
                externalUserId
            }
            cursor
        }
        pageInfo {
          hasNextPage
          endCursor
          hasPreviousPage
          startCursor
        }
    }
}
```

**Comment by gschier** [comment]
It's not possible with templating, but you can add both queries to a single request and use a fragment to help with duplication:

![image](https://user-images.githubusercontent.com/587576/77351402-f23e1480-6cfa-11ea-977d-d2ff34c68f5d.png)
