### ISSUE TITLE
[Bug] Clicking cancel button to select a file clears existing file

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#201]
## Overview

When using the multipart form body or binary file, the current file is cleared if Cancel is clicked while selecting a new one.

## How To Reproduce

All the information needed to reproduce the issue.

- Select file 
- Click button to change the file
- Click cancel
- Old file is gone

## Other Details

I think it was originally implemented this way to avoid implementing a "Clear" button. However, the "Binary" body type has its own "Reset" button, and the multipart file can be cleared by deleting the form item and re-adding it so I think this change is fine.

**Comment by dmlittle** [comment]
@gschier this can be closed now :)

**Comment by gschier** [comment]
@dmlittle pro tip. It would be closed automatically if you had somthing like "Closes #201" in your PR descripiton 👍
