### ISSUE TITLE
[Feature Request] Store more Response History in Insomnia

### ISSUE THREAD

**Issue by woobhurk** [getinsomnia/insomnia#2010]
Hello! Sorry for my bad English.

Can you make Insomnia store more response history? The current history size is too small for me. If possible, please add an option that can set the history size. Greatly appreciate you work, thanks!

**Comment by starJammer** [comment]
what's the current size?

**Comment by woobhurk** [comment]
> what's the current size?

Well, I don't know. But I can only see no more than 50 entires in history.

**Comment by gschier** [comment]
There's a setting for this in the app preferences 👍 

![image](https://user-images.githubusercontent.com/587576/77971346-46209e80-72a3-11ea-8f4c-fa7fcd1d6b8e.png)

**Comment by woobhurk** [comment]
> There's a setting for this in the app preferences 
> 
> ![image](https://user-images.githubusercontent.com/587576/77971346-46209e80-72a3-11ea-8f4c-fa7fcd1d6b8e.png)

Wow, I have found it everywhere 😁. Thanks very much!
