### ISSUE TITLE
Enhancement request; Provide option to sort Requests on left panel alphabetically.

### ISSUE THREAD

**Issue by dgilbertsei** [getinsomnia/insomnia#2011]
It would be very useful if an option was provide to sort the list of Request items (left panel) alphabetically. Thanks!

**Comment by gschier** [comment]
Hi @dgilbertsei, thanks for the suggestion! Can you provide more context as to why you'd find this feature useful? What problem are you having that would be solved by being able to sort requests by name?

**Comment by dgilbertsei** [comment]
I've created dozens of requests and use a specific naming convention, so it would just be a convenience to have them automatically sort rather than me having to drag each one as it's created to the correct position in the list. This feature is also missing from SoapUI and it's one of the features I was hoping to find in Insomnia. But Insomnia does allow for nested folders which is very useful for organizing many requests.

**Comment by jredl-va** [comment]
I also would find this feature useful, our organization is closing in on 100 individual microservices each with there own series of apis. Being able to sort your collection automatically by name would be a great time saver.

**Comment by bob-laz** [comment]
I would also find this feature useful. being able to keep my folders organized would help me find requests I am looking for much more easily.

**Comment by DavoBR** [comment]
This feature is very useful to keep the requests organized, I was looking for an option to sort them manually but I don't see any

**Comment by develohpanda** [comment]
There was a duplicate issue #2594, which was resolved by #2738. This feature will be a part of the next release, so I will go ahead and close as resolved! 🎉
