### ISSUE TITLE
[Improvement] Plugin API to send new request in response hook

### ISSUE THREAD

**Issue by 4n70w4** [getinsomnia/insomnia#2012]
**Is your feature request related to a problem? Please describe.**
An external API does not always respond successfully. Server errors for example 50x or `429 Too Many Requests` may occur. Manually pressing the send button while waiting for a successful response can be tedious.

**Describe the solution you'd like**
Be able to set the number of retries and the expected/unexpected status codes of the response. As well as the interval between requests.

**Comment by gschier** [comment]
That's an interesting request! I'm not sure it makes sense to add such a specific feature directly to Insomnia, but it would be nice if the plugin API supported creation of such plugins.

Currently, there is a "response hook" plugin API for intercepting responses but there is no exposed way to send a new request from there. If there was, a plugin could be written to intercept all responses, check status code, and resend if necessary.

Note, this may be as simple as exposing the `network` context to the `responseHook` scope https://support.insomnia.rest/article/26-plugins#context.network
