### ISSUE TITLE
[Question] How do i setup insomnia for development having issues ?

### ISSUE THREAD

**Issue by imrishabh18** [getinsomnia/insomnia#2013]
I want to setup insomnia for development. So , I have already forked and cloned the repo. But when running the `npm run bootstrap` as said in the readme intial dev setup it gives an error `lerna not an internal or external command` so how should i go about this. And, do i also need to install the insomnia from the website so that when i make changes in repo it is seen over there ?

**Comment by gschier** [comment]
That's a strange error. `npm run bootstrap` installs lerna before running any lerna commands.

Can you make sure you're running Node 10? If that doesn't work, you may be able to do `npm install -g lerna` as a workaround.

**Comment by imrishabh18** [comment]
@gschier Thanks, I got it solved.
