### ISSUE TITLE
[Feature Request] Add option to show curl 

### ISSUE THREAD

**Issue by ahatzz11** [getinsomnia/insomnia#2016]
**Is your feature request related to a problem? Please describe.**
I used to use PAW and have recently been trying out insomnia. My one big pain point is I can no longer see the curl alongside my request. 

The one thing I find myself doing a lot is having to click on or hover over my `base_url` environment variable as a double check of what that variable is, or using some other command like `cmd+shift+g` to see the curl.

**Describe the solution you'd like**
Paw has a nice option to show the curl on the bottom part of the 'request' panel. This makes it super easy to see exactly what request is being created from all of the environment variables. I am a heavy user of environment variables so seeing everything explicitly in a single spot is really nice.

![image](https://user-images.githubusercontent.com/6256032/77991547-d08bf100-72e9-11ea-94fd-72d72f6a67ce.png)

**Describe alternatives you've considered**
- I've found that the `Timeline` section has most of this information, but to get to the timeline you have to make a request first. 
- I've also found that 'generate curl' - `cmd+shift+g` - gives me exactly what I want (and a bunch of other options other than curl!) but it's still a couple button clicks / hotkey away. Adding this panel to the bottom of the request panel would be a huge perk.

**Comment by tharun208** [comment]
I like to work on this.

**Comment by tharun208** [comment]
can i proceed with a mockup of my own @gschier ?

**Comment by wdawson** [comment]
I'm going to convert this to a Discussion since this is a feature request. Looking forward to getting more feedback over there.
