### ISSUE TITLE
[Feature Request] Add keyboard shortcuts to switch environments

### ISSUE THREAD

**Issue by ahatzz11** [getinsomnia/insomnia#2017]
**Is your feature request related to a problem? Please describe.**
I switch environments a lot and manually having to click (or arrow through) to select environments is something I spend a lot of time doing.

**Describe the solution you'd like**
I'd love to be able to switch environments with hotkeys. It is possible to have many environments and you're able to re-order the environments, so the order of the environments would have to match up with some kind of ordering of hotkeys. 

Here is the current view of the environments:

![image](https://user-images.githubusercontent.com/6256032/77991735-41cba400-72ea-11ea-8786-7a17ea557a27.png)

This _kind of_ reminds me of slack orgs:

![image](https://user-images.githubusercontent.com/6256032/77991779-56a83780-72ea-11ea-8711-a155f0495c65.png)

Slack orgs can be selected by `cmd+n` where `n` is the organization in that position. A very similar system could be used in insomnia, where the first environment on your list is `cmd+1`, the second environment is `cmd+2`, and so on.

A little `cmd+n` icon could be added to each 'shuffle' symbol to indicate that the hotkey is available.

**Describe alternatives you've considered**
So far I've just been using my mouse to select environments. The `cmd+n` hotkey is currently unused.

`cmd+shift+e` and using the arrow keys / typing to filter works fine as well but still not as convenient as `cmd+n` would be.

**Additional context**

**Comment by aesyondu** [comment]
Was just looking for this. `cmd+n` is used though for `New Request` modal.
