### ISSUE TITLE
[Bug] Hotkey to show keyboard shortcuts conflicts with macOS

### ISSUE THREAD

**Issue by ahatzz11** [getinsomnia/insomnia#2018]
**Describe the bug**
The default keyboard shortcut to bring up the keyboard settings is `cmd+shift+/`

![image](https://user-images.githubusercontent.com/6256032/77992323-7855ee80-72eb-11ea-8879-440903b3a6f0.png)

However, macOS has this as a default key binding that brings up the 'help' menu:
![image](https://user-images.githubusercontent.com/6256032/77992369-8c015500-72eb-11ea-8cb5-18466fd04fdb.png)

**To Reproduce**
1. Use `cmd+shift+/` keyboard shortcut
2. Notice the 'help' menu opens instead of the keyboard settings

**Expected behavior**
I'd expect the keyboard settings to pop up. A possible alternative default for this setting would be `cmd+/`.

**Screenshots**
See Above

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103)
 - Installation Method: website download
 - App Version: Version 7.1.1 (7.1.1.3350)

**Additional context**

**Comment by gschier** [comment]
Hmm, this is strange. For me, on macOS, it correctly shows the keyboard shortcuts dialog in Insomnia. 

However, it _does_ conflict with the OS-level shortcut so I agree that we should change the default.

**Comment by mum-never-proud** [comment]
@gschier is someone already working on this PR?

**Comment by elemanhillary-zz** [comment]
can we use this cmd+/ @gschier

**Comment by develohpanda** [comment]
@mum-never-proud as far as I know, nobody is working on this at the moment, feel free to pick it up! 😊 any reasonable key combination is probably okay.

@elemanhillary potentially - does `cmd + /` conflict with the default keybind for commenting code in the editor?

**Comment by elemanhillary-zz** [comment]
@develohpanda yeah, may be we can do ctrl + /

**Comment by gschier** [comment]
Since it's only conflicting on Mac, and seems like a relatively infrequent key combo, I suggest changing _only_ the mac keybinding to `cmd+ctrl+shift+/`.

**Comment by SergioSuarezGil** [comment]
I have found this issue looking for documentation on a shortcut to comment / uncomment one or several lines in graphql, with a shortcut (because there is no context menu) is it possible?

**Comment by develohpanda** [comment]
Hi @SergioSuarezDev, does `cmd + /` work for you to comment/uncomment in GraphQL? That appears to be working as intended. Unfortunately it looks like that's hard-coded and not configurable via Preferences > Keyboard at the moment

**Comment by SergioSuarezGil** [comment]
Unfortunately CMD+/ is not working on European Keyboards. For example, vscode shortcut is **CMD+SHIFT+7**
Check the keyboard bellow:
![](https://user-images.githubusercontent.com/3636232/137198350-bb0682df-98dc-42a1-8cd6-374947d43486.png)

**Comment by develohpanda** [comment]
Oh wow! That's... interesting. I think it should be fairly straightforward to update the hard coded binding to include this one, at the line I linked in another thread. Is that something you'd be interested in trying out and raising a PR for? 😊

**Comment by SergioSuarezGil** [comment]
of course, I will help you in whatever is necessary:  ​=) I'm a regular user of insomnia

(off topic) I imagine that this other functionality is very complex, but uploading files with graphql is very tedious, so I have also added another feature request for it https://github.com/Kong/insomnia/discussions/4110

**Comment by develohpanda** [comment]
Great, thank you!
