### ISSUE TITLE
Show interface Implementations and Implements in GraphQL schema

### ISSUE THREAD

**Issue by djibarian** [getinsomnia/insomnia#2019]
Currently are not shown. It would be good to have them shown in the schema. Otherwise a key part is missing in the documentation if using interfaces. A good example to look at can be found in GraphiQL schema.

**Comment by kreosus** [comment]
Hi @djibarian 
Do you see the same behavior with our latest release located here:
https://github.com/Kong/insomnia/releases/tag/lib%403.6.0

**Comment by kreosus** [comment]
closing as no reply back
