### ISSUE TITLE
sslkeylog feature

### ISSUE THREAD

**Issue by markholden1** [getinsomnia/insomnia#2021]
I have a feature request for Insomnia regarding saving the sslkeylog.
This will help when using Wireshark for packet captures.
We need a feature similar to the -ssl-key-log-file parameter that chrome.exe provides.
It looks like Open SSL 1.1.1 has this feature with a callback function.
Can we get Insomnia updated to Open SSL 1.1.1 and add a feature to save the keylog.
This feature can either be in the core of Insomnia or from a plugin.
Also, if anyone knows of a plugin to do this already, that would also be nice.

https://wiki.wireshark.org/TLS

Open SSL 1.1.1
https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_keylog_callback.html

**Comment by markholden1** [comment]
The latest version appears to honor the SSLKEYLOGFILE environment variable now that Open SSL has been upgraded to 1.1.1 or later.
This issue is complete.  thanks!

**Comment by darcyrush** [comment]
As a note to others; once you add a path to `SSLKEYLOGFILE`, open insomnia via the same terminal and not via the GUI.
