### ISSUE TITLE
[Feature Request] Customizable fallback font

### ISSUE THREAD

**Issue by 7sDream** [getinsomnia/insomnia#2022]
Recently, I need to work with some non-English API, it returns some Chinese and Japanese charcters, but I still want use beautiful code fonts like FiraCode, Cascadia, JetbrainsMono, etc...

But those font can't render CJK chatacters, so it fallback to some, let's say, "system font", but it's little too shin and hard to read for me.

So I'm wordering if insomnia can add a option to customize fallback font? Or like VSCode, use a CSS-like syntax in font setting?

Thanks for your great work!

**Comment by kreosus** [comment]
Hi @7sDream 
Good day and I hope that all is well. Have you tried this on our newest release, available here: https://github.com/Kong/insomnia/releases/tag/core%402022.5.0?

**Comment by 7sDream** [comment]
Yes, It looks nice now, Thank you!
