### ISSUE TITLE
GraphQL query prettification doesn't handle a large number of arguments very well

### ISSUE THREAD

**Issue by chasingmaxwell** [getinsomnia/insomnia#2023]
When a query contains a field or named query with a large number of arguments, the "Prettify GraphQL" button condenses them all down to one line when a multi-line format would be easier to read. Here's a very contrived example:

![Selection_081](https://user-images.githubusercontent.com/3128659/78255378-3bddea80-74c5-11ea-8ee6-625bdf19884b.jpg)

I think something like this would be easier to read:

![Selection_082](https://user-images.githubusercontent.com/3128659/78255564-70ea3d00-74c5-11ea-888e-11b1c7838028.jpg)

Using prettier for the formatting of GraphQL queries would actually do this (and is what tools like playground use).

**Comment by seanghay** [comment]
Love it

**Comment by gschier** [comment]
While I agree that having prettier be part of the app would be awesome, it's a huge dependency to be adding just to format a GraphQL query.

I was talking to the team about this yesterday and we came to the conclusion that this would be great to expose as a plugin API behavior. A "Prettier Format" plugin would be self-contained and easy to install for those who want it.

**Comment by gschier** [comment]
I was talking to the team about this yesterday and we came to the conclusion that this would be great to expose as a plugin API behavior. A "Prettier Format" plugin would be self-contained and easy to install for those who want it.

**Comment by chasingmaxwell** [comment]
Sounds reasonable. I should be able to put that together shortly.

**Comment by rocketraman** [comment]
Work seems to be happening under https://github.com/Kong/insomnia/issues/3242.

**Comment by dimitropoulos** [comment]
this should be fixed by https://github.com/Kong/insomnia/pull/4022 which should be in the next release
