### ISSUE TITLE
[Bug] Application menu is hidden in non-Unity Ubuntu Xenial

### ISSUE THREAD

**Issue by stdedos** [getinsomnia/insomnia#2025]
**Describe the bug**
The application menu is hidden in Ubuntu Xenial, even though the rendering environment is **not** Unity

**To Reproduce**

1. Use xpra in Ubuntu Xenial
2. From a Windows xpra client, start insomnia

**Expected behavior**
Menus are not hidden

**Comment by gschier** [comment]
Can you post a screenshot of the current (and expected if possible) behavior?

**Comment by stdedos** [comment]
It is complicated, but it's easy to imagine how it looks like.

Just, see the window as it appears on normal systems, with the file menu bar ... without that bar

**Comment by kreosus** [comment]
Hi @stdedos 
Do you see the same behavior with our latest release located here: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.4

**Comment by stdedos** [comment]
In Ubuntu Xenial? An ESM LTS?

**Comment by stdedos** [comment]
_Closed as won't do, but who am I to argue ..._
