### ISSUE TITLE
[Question]  how export data with response ?

### ISSUE THREAD

**Issue by benemohamed** [getinsomnia/insomnia#2027]
**What is your question?**
Hey
I am trying to add response on the docs is work fine with Template tag .

 ![Screenshot from 2020-04-04 02-33-47](https://user-images.githubusercontent.com/49129795/78415899-bb320200-761c-11ea-8166-bd0a81eb4f16.png)

![Screenshot from 2020-04-04 02-27-29](https://user-images.githubusercontent.com/49129795/78415797-0861a400-761c-11ea-91be-bc2c675a3d63.png)

but the response not show with Exporting Data

![Screenshot from 2020-04-04 02-31-04](https://user-images.githubusercontent.com/49129795/78415854-5b3b5b80-761c-11ea-9b6b-2764efc58f66.png)

**Comment by wongstein** [comment]
Hi!  Sorry for the late reply.  Have you been able to reproduce this with the latest version of Insomnia?

**Comment by benemohamed** [comment]
Hi, not yet with version
```
Version: Insomnia 2022.5.0
Build date: 8/2/2022
OS: Linux x64 4.15.0-54-generic
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64
```

**Comment by wongstein** [comment]
When you say "the response doesn't show when exporting), in that json, I see:


![Image](https://user-images.githubusercontent.com/12381507/183743633-68d6a205-b47a-4a0f-8ead-5e6013ad7ec5.png)

Are you expecting the output of the response you just ran to be in that exported json?  And if not, what is the expectation?

**Comment by wongstein** [comment]
I'm going to close this issue for now.  This issue does feel like a feature request with the export function.  We need to do thinking about what the purpose is of insomnia spec documents and whether it should include historical responses in that spec.  

In the meantime, if the goal is to have a copy of the latest response somewhere, you can download the response that comes from a tested request:

![Image](https://user-images.githubusercontent.com/12381507/185150948-c7e584aa-37d3-47e3-93d4-38bc56bd2843.png)
