### ISSUE TITLE
[Question] Can I set an environment variable depending on the last run endpoint?

### ISSUE THREAD

**Issue by jason2li** [getinsomnia/insomnia#2028]
**What is your question?**
I'm using JWT authentication.  I have a /SignIn endpoint and a /Refresh endpoint.  Both of them return the same data model, which includes an access token.  I'd like to save the last called endpoint to an environment variable called "accessToken".  Is this possible?

**What is the context?**
In my scenario, the user signs in using the /SignIn endpoint.  I then save the response to an environment variable called "accessToken".  After a certain amount of time that access token will expire, so they need to refresh it by calling the /Refresh endpoint.  Because of this call, the original "accessToken" variable is no longer valid.  I would like to update the variable to use the new, valid, access token from the /Refresh endpoint.

My understanding of both "chaining" and "environment variables" is that they can only consume from a single endpoint.

Is there a way to do this?

**Comment by zappatero** [comment]
I would love to have this features as well. Like in Postman "setEnvironmentVariable".

**Comment by ksugiarto** [comment]
This is a nice and important feature 👍

**Comment by alexejk** [comment]
I was struggling with this for a while, but i realized that with help of a simple plugin I can make it with:

- Response hook to parse response of desired methods and store it in plugin storage context
- Template tag that is used on methods that need part of the response

While i think it would be nice to `setEnvironmentVariable` I believe it will be challenging as there are multiple layers involved (base, env, folder override). Plugin store works very well, and they are very easy to create.

**Comment by ksugiarto** [comment]
Up

**Comment by Eddie-Hartman** [comment]
@develohpanda 
Just reaching out to a contributor here. This feature has been requested multiple times and seems like some people are going to struggle (myself and team included) to migrate from Postman if we can't store responses in variables. #217 and #1167 along with this are asking for it.

It seems like the plugin system has a few plugins to allow this kind of functionality, but it's not ideal.

**Comment by develohpanda** [comment]
Thanks for tagging me @Eddie-Hartman, there's a lot of activity and unfortunately some things go under the radar. Tagging @wdawson here, Wils is our new PM for Insomnia and will be the one who can help prioritise.

As a previous comment mentions this is certainly an involved piece of work _but_ I can see a way in which it could work.
