### ISSUE TITLE
[Bug] [User-Experience] Pressing ESC while renaming object closes whole modal dialog

### ISSUE THREAD

**Issue by pgp** [getinsomnia/insomnia#2029]
**Describe the bug**
In some cases, if one's renaming an object, and presses ESC (to discard rename), the triggered action is exiting the current modal dialog, if any is open

**To Reproduce**
1. Go to 'Manage Environments'
2. Double click on an existing environment to start renaming it
3. Press ESC key
4. The entire environment management window closes

**Expected behavior**
(4.) The environment management window is still open, and renaming is discarded

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - Installation Method: tar.gz
 - App Version 7.1.1

**Additional context**

**Comment by serpilacar** [comment]
I have faced the same problem on Mac. I believe it is a generic problem but I haven't encountered the same problem in other modals. What do you refer by "In some cases" @pgp ?

**Comment by pgp** [comment]
I wrote 'in some cases' because I was not aware whether there were other renamable widgets in contexts other than the environment manager modal window, that triggered the same situation.
