### ISSUE TITLE
[Bug] Query parameter doesn't work if url contain ? character

### ISSUE THREAD

**Issue by bleketux** [getinsomnia/insomnia#2034]
**Describe the bug**
I have a API url endpoint from my friend containing "?" character. When we put additional query, the first query will translate to ampersand "&" character, while it should be "?" character.

**To Reproduce**
1. Create New Request with Get method
2. Put endpoint (for example)t: http://localhost/api/v2/index.php?/todo
3. On Query tab, put key:value with = api-key:xxyy, status:done
4. the url preview show: http://localhost/api/v2/index.php?%2Ftodo&api-key=xxyy&status=done
notice char "&" after todo
5. if we execute, it will produce error message: The URI you submitted has disallowed characters.

**Expected behavior**
The url preview should show: http://localhost/api/v2/index.php?/todo?api-key=xxyy&status=done
notice char "?" after todo

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.1 64bit
 - Installation Method: deb version
 - App Version 7.1.1

**Comment by jgiovaresco** [comment]
👋 @bleketux 

I'm not sure that `http://localhost/api/v2/index.php?/todo` is a valid URL following the standard. If I read the [RFC grammar](https://tools.ietf.org/html/rfc3986#appendix-A) correctly, the `?` is not allowed in the URL path. It is used as the delimiter for the query string.

Therefore I don't think we would implement a "fix" in Insomnia 🤔.

**Comment by bleketux** [comment]
:wave:  Thank you @jgiovaresco , yes, it's definitely wrong setup on backend side, they should follow the standard.
At the time I found this problem, it can be handled by postman. But I agree with you this is not a "fix" since this is not valid, I already asked them (API maintainer) to change and follow the standard with cleaner URL, so I can use only insomnia for dealing with every API out there :smiling_face_with_three_hearts: 
I'll pass the RFC grammar to them :smiley: 

Thank you for your valuable time to take a response. I'll close this issue.
:+1:
