### ISSUE TITLE
[Question] How do I make Insomnia escape json for GraphQL requests like other clients?

### ISSUE THREAD

**Issue by mason** [getinsomnia/insomnia#2036]
**How do I make Insomnia escape json like other clients?**
When using Insomnia, the query variables field accepts json. When looking at the request sent, it looks like this

```
{
  "query": "<My Query>",
  "variables": {
    "input": {
      "id": "1127277c-29fa-467c-8564-44448c0b4a50a"
    }
  }
}
```

When using other clients like Feen GraphQL, the same request may look like this:

```
{
  "query": "<My Query>",
  "variables": "{  \"input\" : {    \"id\": \"1127277c-29fa-467c-8564-4444c0b4a50a\"  }}"
}
```

As you can see, the variables section is a string vs insomnia which sends an object. Is there a way to make insomnia send variables as a long string?

**Comment by srajsushmitha** [comment]
Any luck? I have the same problem too

**Comment by mason** [comment]
Just use postman and use the Pre-request script feature to escape the json @srajsushmitha

**Comment by filfreire** [comment]
Hi @mason and @srajsushmitha you should be able to use the [inception plugin](https://insomnia.rest/plugins/insomnia-plugin-inception) to do this. Feel free to report other issues you may come across.

Related comment: https://github.com/Kong/insomnia/issues/1421#issuecomment-482929134
