### ISSUE TITLE
[Bug] Import of OpenAPI 3 and Swagger 2 fails when contract is missing 'servers' property

### ISSUE THREAD

**Issue by tnicolaysen** [getinsomnia/insomnia#2038]
**Describe the bug**
Importing a contract without the `servers` property yields a cryptic error message.

**To Reproduce**

Importing this API does not work (gives a cryptic error message).
It is missing the `servers` property.

```yaml
openapi: 3.0.1
info:
  title: API missing servers property
  description: Some description
  version: 1.42.0
paths:
  '/some-operation':
    put:
      tags:
        - Some tag
      summary: Some summary
      description: Some description
      operationId: SomeOperation
      parameters:
        - name: someInput
          in: query
      responses:
        '200':
          description: OK
 ```

Importing this API is working fine as it has the `servers` property. 
```yaml
openapi: 3.0.1
info:
  title: API missing servers property
  description: Some description
  version: 1.42.0
servers:
  - url: "https://localhost:80"
paths:
  '/some-operation':
    put:
      tags:
        - Some tag
      summary: Some summary
      description: Some description
      operationId: SomeOperation
      parameters:
        - name: someInput
          in: query
      responses:
        '200':
          description: OK
 ```

**Expected behavior**
A proper error message with an explanation of what is wrong.
(An idea might be to incorporate a tool like [Spectral](https://github.com/stoplightio/spectral) to lint the contract).

Alternatively, Insomnia could be more lenient and ignore this error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: Download and manual install
 - App Version: 7.1.1
 - Node: 10.2.0

**Additional context**
Maybe related to 1640

**Comment by develohpanda** [comment]
Hi @tnicolaysen! Thank you so much for that excellent write up and the example APIs. 💯

#2007 fixes this and has already been merged; it should go out in the next release. It will allow for the import of an API without the servers property defined.

Closing this issue, though I'll link it in the PR. 😄
