### ISSUE TITLE
[Feature Request] Environment cookie jar

### ISSUE THREAD

**Issue by ejose19** [getinsomnia/insomnia#2041]
**Is your feature request related to a problem? Please describe.**
When using multiple users dealing with cookies (like auth cookies), there's no direct way to linking cookies with them.

**Describe the solution you'd like**
When dealing with cookies, insomnia will transverse the environment hierarchy path and use the closest cookie jar

On environment creation, there will be a cookieJar generated, and with a checkbox you can enable disable it

Active cookieJar would be already known at any time since it's related to the closest environment with the flag enabled.

Visualization(s):
```
Workspace
  Environment (cookieJar enabled)
      SubEnvironment (cookieJar enabled) <--- active cookieJar
```
```
Workspace
  Environment (cookieJar enabled) <--- active cookieJar
      SubEnvironment (cookieJar disabled)
```

** Since folders already store environment variables, they could be included too.

**Describe alternatives you've considered**
You either have to:

- creating another workspace (cumbersome and slow to switch)

- logging in and out between calls (very slow and confusing to know current user)

- using cookies in environment variables (you need to set and unset them manually, cumbersome and slow)

- open another instance (best workaround currently, but only jar[0] will be preserved and the rest will be merged if cookie doesn't exists on jar[0])

**Additional context**
Even if implemented standalone, this feature benefits from a nested environment implementation, since you wouldn't need to rely on folders (duplicating requests) or duplicating the sub environments (development - admin / development - user)

**Comment by kreosus** [comment]
Hi @ejose19 

Good day and I hope that all is well. Have you tried this on our newest release, available here: https://github.com/Kong/insomnia/releases/tag/core%402022.5.0?

**Comment by kreosus** [comment]
Hi @ejose19,

As we have not heard back from you we are closing this issue out. If you require any further/future assistance please let us know and we will proceed accordingly. Have a nice day.

**Comment by ejose19** [comment]
Hello @kreosus, I just tried with `2022.5.1` but nothing has changed. I created 2 environments and when one gets a cookie the other also uses it, they're not separated and there's no option to enable/disable cookieJars. Can you tell me what was the change that implemented this FR?

Here's a sample server code (nodejs) I'm using to test:

```js
import Koa from 'koa';
import crypto from 'crypto';

const app = new Koa();

app.use((ctx) => {
    if (ctx.cookies.get('id') === undefined) {
        ctx.cookies.set('id', crypto.randomUUID());
    };

    ctx.body = ctx.cookies.get('id');
});

app.listen(3000);
```
