### ISSUE TITLE
[Question] How do I Force insomnia to open login screen on clicking "Refresh Token'

### ISSUE THREAD

**Issue by manbeing** [getinsomnia/insomnia#2042]
I want to test various users with oauth2 authentication, so i will need the login page is always up after clicking 'Refresh Token'. 

Cookie management doesn't work for me. For example, I was using Google authentication, somehow, Insomnia remembered everything so no login page. I didn't find any google cookies in the cookies management (Ctrl k)

**Comment by develohpanda** [comment]
Hi @manbeing! Restarting the application and refreshing the token should allow for this - as per #647. It would be nice to support logging out in the future (maybe via a plugin 👀), but this workaround should work for now! 🤗

**Comment by develohpanda** [comment]
Looks like this was resolved by https://github.com/Kong/insomnia/pull/2953!
