### ISSUE TITLE
[Bug] Menu bar doesn't hide even with the option unselected in Preferences

### ISSUE THREAD

**Issue by bharath144** [getinsomnia/insomnia#2044]
**Describe the bug**
Menu bar doesn't hide even with the option unselected in Preferences

**To Reproduce**
1. Go to Preferences 
2. Uncheck the 'Hide menu bar' option
3. Go back to the main window
4. Menu bar is still show 

**Expected behavior**
Menu bar should get hidden and can be activated if needed using menu bar mnemonics 

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Installation Method: snap
 - App Version: v7.1.1

**Comment by kodek-sleuth** [comment]
I would like to take this one on

**Comment by kreosus** [comment]
Hi @bharath144 

Have you tried this on our newest release, available here: https://github.com/Kong/insomnia/releases/tag/core%402022.5.0?

**Comment by kreosus** [comment]
Hi @bharath144 

As we have not heard back from you we are closing this issue out. If you require any further/future assistance please let us know and we will proceed accordingly. Have a nice day.
