### ISSUE TITLE
[Bug] Regression: Cannot export data to HAR while using Inception plugin anymore

### ISSUE THREAD

**Issue by pinggi** [getinsomnia/insomnia#2049]
**Describe the bug**
I use Inception plugin which encodes json body. The JSON body contains its tag:
```
{% inception_json  %}
{
...
}
```

When I try to export data to HAR format, it ends up with error:
```
Error: Failed to render "GetMessage:body.text"
 unknown block tag: inception_json
```
![image](https://user-images.githubusercontent.com/18471834/80180236-940a9700-8602-11ea-913e-ba494e622818.png)

**Comment by filfreire** [comment]
Hello @pinggi, I can't reproduce this as of [latest beta release (2022.6.0-beta.1)](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.1).



![Image](https://user-images.githubusercontent.com/11976836/184334859-c2b1ccb3-565f-4e57-ad52-7e49edf01050.png)



I encourage you to try out this latest release and feel free to report any issues you come across.
