### ISSUE TITLE
[Bug] paste from curl, query not parse

### ISSUE THREAD

**Issue by xinshangshangxin** [getinsomnia/insomnia#205]
## Overview
- `Insomnia Version:` 5.0.20
- `Operating System:`  MacOS 10.11.4 (15E65)
- `Summary: ` _(A few sentences describing the issue. Try to include as much detail as possible.)_

insomnia show this,
![image](https://cloud.githubusercontent.com/assets/8779091/26032843/c243fd74-38cf-11e7-9d43-f90145ccb7ce.png)

I want like this
![image](https://cloud.githubusercontent.com/assets/8779091/26032854/0adf0790-38d0-11e7-9241-2c6cc3a0ec99.png)

thanks~

**Comment by gschier** [comment]
@xinshangshangxin there is an _Import from Url_ button at the bottom of the Query tab that can be used for this. It wouldn't be a bad idea to do the import automatically, though, after pasting a Curl command.

![image](https://cloud.githubusercontent.com/assets/587576/26037781/d1f28da0-38af-11e7-9902-70e02e019fc7.png)

**Comment by xinshangshangxin** [comment]
thanks~
