### ISSUE TITLE
[Bug] Import from clipboard

### ISSUE THREAD

**Issue by LamineMbn** [getinsomnia/insomnia#2052]
**Describe the bug**
The import from clipboard doesn't work

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Data'
3. Import from clipboard

**Solution**
In `import.js#importUri`

Replace :
```javascript
...
  } else {
    // Treat everything else as raw text
    rawText = decodeURIComponent(uri);
  }
```

With:
```javascript
...
  } else {
    // Treat everything else as raw text
    rawText = await navigator.clipboard.readText();
  }
```
Already tested and its working.

Can do PR for that if it's relevant.

Thank you

**Comment by develohpanda** [comment]
This is an interesting one... Importing from the clipboard has an explicit handle that reads from the clipboard and attempts an import.
 https://github.com/Kong/insomnia/blob/28e7d928a809402660293189eeccd5bb2c773bb4/packages/insomnia-app/app/ui/redux/modules/global.js#L268-L286

Does your clipboard contain a uri, or the contents of the file?
