### ISSUE TITLE
[Feature Request] Generate Rust Code for Requests

### ISSUE THREAD

**Issue by florrdv** [getinsomnia/insomnia#2054]
**Is your feature request related to a problem? Please describe.**
Insomnia does not currently support Rust code generation for the requests.
**Describe the solution you'd like**
Add Rust support (preferably for the reqwest crate) code generation support to insomnia to save Rust developers lots of time.
**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by rectof** [comment]
https://www.youtube.com/watch?v=OUgKU2One5g
