### ISSUE TITLE
[Feature Request] Notification or progress bar for data export

### ISSUE THREAD

**Issue by EnilPajic** [getinsomnia/insomnia#2055]
**Is your feature request related to a problem? Please describe.**

It may seem a bit annoying to hit "export" button and not know when export is finished.
For now, I hit "export" and periodically check folder if content is there.

**Describe the solution you'd like**

1. notifications: e.g. "Export started" and "Export finished" (or maybe only the last one). It may look same as "new version" notification panel with a button to show exported file in a folder.
2. some progress-bar that is non-modal (hell, even modal progress-bar is better than checking folder). Progress bar may be somewhere in status bar or something (like in JetBrains' tools).

**Describe alternatives you've considered**

I'm exporting requests very often, so I'm really considering writing a small app that utilizes file system watcher and notifying me.

**Additional context**

If matters, I'm using insomnia `7.1.1.3350` for Mac (Catalina).

**Comment by nijikokun** [comment]
Great points, and I think @jitachi you brought up some UX concerns last week around item creation of documents in designer, while this is exports in core it seems like this is similar in topic - notification of something happening / completing, thoughts?

**Comment by tharun208** [comment]
Hi @nijikokun @develohpanda, I like to work on this task. What I have in mind is showing a toast with suitable color for `successful` and `failure` data exports. thoughts?
