### ISSUE TITLE
[Bug] Changelog links are Not-Found

### ISSUE THREAD

**Issue by RodolfoSilva** [getinsomnia/insomnia#2056]
**Describe the bug**
The link of both last pre-release  are Not-Found

Not Found ⇒ https://insomnia.rest/changelog/designer/2020.1.0-beta.1
Not Found ⇒ https://insomnia.rest/changelog/core/2020.1.0-beta.1

**To Reproduce**
1. Go to https://github.com/Kong/insomnia/releases
2. Scroll down to pre-release * Insomnia Designer 2020.1.0-beta.1* or *Insomnia 2020.1.0-beta.1*
2. Click on the link to see Full changelog 
3.  You will be redirected

**Expected behavior**
The release notes

**Screenshots**

![image](https://user-images.githubusercontent.com/1703020/80374151-97a15680-886c-11ea-9770-79245aa620b4.png)

**Comment by nijikokun** [comment]
Nice catch, keep an eye out as we haven't launched the site updates yet, doing a soft launch to ensure codebase sanity and packages are working. Official launch date for Designer is the 29th! Feel free to try it out until then and give feedback ❤️

![](https://media0.giphy.com/media/ncU3bkZ5ghDlS/giphy.gif)

**Comment by RodolfoSilva** [comment]
Thanks @nijikokun

**Comment by gschier** [comment]
Removed the broken links from the release entries for now 👍

**Comment by RodolfoSilva** [comment]
Thanks @gschier
