### ISSUE TITLE
[Question] Postman 4.x support to import collections?

### ISSUE THREAD

**Issue by skynyrd** [getinsomnia/insomnia#206]
## Overview
- `Insomnia Version:` 5.0.20
- `Operating System:`  Ubuntu 17.04
- `Summary: ` Is there a way to import my collections in Postman 4.10.7 to Insomnia?

## How To Reproduce
1. Export Postman collections.
2. Import them to Insomnia via `import from file`.
3. No importers found for file.

## Other Notes

It is already written that I can import Postman v2. I use the latest version, 4.10.7 and is there a way import my collections?

**Comment by gschier** [comment]
@skynyrd this should probably be clarified somewhere in the app, but Postman 4.x is able to export v1 or v2 format. This is the format of the export schema, not the app version.

You can choose the export format when exporting a single collection. 

![image](https://cloud.githubusercontent.com/assets/587576/26037745/de956330-38ae-11e7-8a07-c1033b22a355.png)

I assume you exported data from the Postman settings screen? I had assumed that was v2, but maybe it's actually v1? Nevertheless, _that_ format should probably also be supported.

**Comment by skynyrd** [comment]
In the latest version of Postman, user cannot choose the export version.

![image](https://cloud.githubusercontent.com/assets/7965201/26054423/30b505aa-3975-11e7-9f00-ee688aeb997c.png)

The exported file format is this:
```
{
	"version": 1,
	"collections": [
                    ......
        ],
	"environments": [],
	"headerPresets": [],
	"globals": []
}
```

**Comment by gschier** [comment]
You can select it when exporting a collection via the sidebar. I'm not sure why they don't provide this option in the settings menu as well.

![image](https://cloud.githubusercontent.com/assets/587576/26076166/a7c77b0e-396c-11e7-982b-b81e845090d5.png)

**Comment by skynyrd** [comment]
Ah sorry for wasting your time, I thought that export behaviour is same in the other components.

**Comment by gschier** [comment]
@skynyrd don't feel sorry! 😄 

The app should be responsible for handling both cases 💯 

Added an issue to support Postman v1:  https://github.com/getinsomnia/importers/issues/9
