### ISSUE TITLE
Response autocomplete Handlebars not displaying nicely

### ISSUE THREAD

**Issue by Isanderthul** [getinsomnia/insomnia#2065]
**Describe the bug**
The handlebars do not show the variable nicely, and as seen as raw data, but you cant get to the dialog to pick the response etc, because the UI is not triggering the autocomplete.
<img width="911" alt="Screenshot 2020-04-28 at 08 36 44" src="https://user-images.githubusercontent.com/3693197/80456422-d6e3ac00-892d-11ea-9166-5fa9d3abb857.png">

**To Reproduce**
1. Make a workspace
2. Make a GET to any url eg https://ipv4.icanhazip.com/
3. Make a POST to any url eg https://postman-echo.com/post
3.1 Make a body, say JSON, with {"key:"value"} overwrite value and type resp then autocomplete, select body attribute, and the command string is populated as {% response 'body', '', '', 'never' %} but no UI to select the prameters appears.

**Expected behavior**
I expect the UI to allow me to pick the variables in the autocomplete

**Screenshots**
<img width="392" alt="Screenshot 2020-04-28 at 09 13 45" src="https://user-images.githubusercontent.com/3693197/80458137-9f2a3380-8930-11ea-9203-10eb7e1d942a.png">
<img width="407" alt="Screenshot 2020-04-28 at 09 13 57" src="https://user-images.githubusercontent.com/3693197/80458149-a2252400-8930-11ea-9bf1-b0a0a6f4bb5b.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4 (19E287)]
 - Installation Method: homebrew
 - App Version 7.1.1 (7.1.1.3350)

**Additional context**
None

**Comment by gschier** [comment]
It looks like you may have accidentally enabled the "Raw Template Syntax" setting in app preferences? 

![image](https://user-images.githubusercontent.com/587576/80655736-45ab2d00-8a34-11ea-8f98-59dc86483301.png)

**Comment by Isanderthul** [comment]
Correct 😔, well thanks @gschier its "fixed" now 😅
