### ISSUE TITLE
Git Sync Modal Crashes App

### ISSUE THREAD

**Issue by Natfan** [getinsomnia/insomnia#2075]
**Describe the bug**
When opening Git Sync Respository Settings (described as `[ga] Event Modals, Show, GitRepositorySettingsModal` in the Developer Console) the app seems to crash (white screen) and there is no way to recover without restarting the app.

**To Reproduce**
1. Click on "Setup Git Sync".
    ![Setup Git Sync](https://i.natfan.io/TameWingedBass.png)
2. Click on "Respository Settings".
    ![Respository Settings](https://i.natfan.io/MortifiedAlienatedMealworm.png)
3. The "Configure Respository" popup appears.
    ![Configure Respository](https://i.natfan.io/ClearcutUnhealthyDanishswedishfarmdog.png)
4. However when moving the mouse onto one of the yellow highlighted text boxes (Git URI, Author Name or Author Email), the app crashes. Moving the mouse anywhere else does not cause this behaviour. Clicking outside of the 'Configure Respository' popup or the close button on the 'Configure Respository' screen closes the popup and the app continues to function as expected.

**Expected behavior**
When hovering/clicking on the Git URI, Author Name or Author Email text boxes I would expect to be able to type in them.

**Screenshots**
See above for screenshots of the steps taken. See below for the final result:
![Final output, a white screen. Notice that the titlebar remains](https://i.natfan.io/SillyAngryRainbowfish.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 (Education) 1909 (OS Build 18363.778)
 - Installation Method: Installer found at https://updates.insomnia.rest/downloads/windows/latest?app=com.insomnia.designer
 - App Version:
    Version 2020.1.0
    ShellL 3.1.13
    Node 10.2.0
    V8 6.6.346.32
    Architecture x64
    libcurl/7.57.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.7.0_DEV
    (Note: Adding a "copy to clipboard" button on the Help->About screen would be very useful for bug reports!)

**Additional context**
N/A

**Comment by gschier** [comment]
Thanks for reporting this! We'll take a look

**Comment by nijikokun** [comment]
Having trouble replicating this, is it possible to replicate with the developer console open to see if there are any errors that can be captured?

Here I am able to enter values, and hover over:

![image](https://user-images.githubusercontent.com/198276/80652343-91f26f00-8a2c-11ea-8367-fcf1e416a9fd.png)

I am running version `2020.1.2`

**Comment by Natfan** [comment]
Looks like this was fixed when I reinstalled? Might have just been some lingering issues caused by #2073?

Currently on 2020.1.3, and am no longer getting the error.
