### ISSUE TITLE
[Bug] Esc in environment editor with Vim mode not working

### ISSUE THREAD

**Issue by antonbasic** [getinsomnia/insomnia#208]
## Overview
- `Insomnia Version:` v5.0.20
- `Operating System:`  MacOS 10.12.4 (16E195)
- `Summary: ` When editing an environment using vim key map you cannot use esc to exit insert mode. Esc instead causes the settings modal to close.

## How To Reproduce
1. Set `Text Editor Key Map` to `Vim`
2. Go to `Manage environments`
3. In the editor, press `i` to enter insert mode.
4. Try to exit insert mode by pressing `esc`

**Comment by gschier** [comment]
Hmm... this may be a tricky one to fix. The Vim mode is provided directly by [Codemirror](https://codemirror.net/). All this probably needs is an `e.stopPropagation()` when the escape command fires but, without forking the Codemirror vim mode, might be hard to do.

**Comment by gschier** [comment]
Closing as stale.

**Comment by kitsu** [comment]
Please address this. All you need to do is disable ESC closing the environment modal (which already has two buttons for closing).

**Comment by gschier** [comment]
@kitsu if you want to submit a PR for this I'd be happy to take a look.
