### ISSUE TITLE
Requests are duplicated when switching between design and debug tabs

### ISSUE THREAD

**Issue by ImVexed** [getinsomnia/insomnia#2080]
Upon loading a spec, if you switch back and forth from Design <-> Debug, it will continually append the endpoints and never clear them.

**To Reproduce**
- User any OpenAPI spec, (ex. Petstore)
- Swap to Debug
- Swap to Designer
- Swap to Debug
- Repeat

**Expected behavior**
Only to have 1 set of endpoints

**Screenshots**
![image](https://user-images.githubusercontent.com/10090878/80637214-74fd7200-8a13-11ea-9933-5816ad68a200.png)

**Desktop**
Windows

Using this release https://github.com/Kong/insomnia/releases/tag/designer%402020.1.2

**Comment by gschier** [comment]
Can you please post the API spec you are using?

**Comment by ImVexed** [comment]
The example Petstore spec from https://editor.swagger.io/

**Comment by ImVexed** [comment]
It also seems that there are no endpoints in the duplicate folders: 
![image](https://user-images.githubusercontent.com/10090878/80637712-4d5ad980-8a14-11ea-88fb-05b5a7222a6e.png)

**Comment by gschier** [comment]
Thanks! I think this issue is specific to Swagger 2.0. We'll get that fixed! For now, OpenAPI 3 specs should work

**Comment by reynolek** [comment]
I imagine for the same reasons, but Swagger 2.0 also causes extra environments to be copied (seems to only show up when you restart the app)

**Comment by h8art** [comment]
Any updates? Blocked by this issue

**Comment by wdawson** [comment]
@h8art no updates that I'm aware of on this yet. This issue was mistakenly tagged as a feature request and converted to a Discussion (hence my activity above). I assume this is still happening for you on Swagger 2.0 with the latest Insomnia release?

**Comment by donni106** [comment]
run into the same issue with appending all endpoints on startup, which i imported from a swagger json.
any workaround?

**edit**: i removed the import as designer and imported again as request collection. this way the endpoints will not get duplicated on every startup

**Comment by h8art** [comment]
@wdawson every time when you switch from deisgn to debug it duplicates every endpoint (swagger 2.0)

**Comment by filfreire** [comment]
@Kong/team-insomnia internally this is issue: https://linear.app/insomnia/issue/INS-567/requests-are-duplicated-when-switching-between-design-debug 

It is still reproducible in our [latest release (2022.4.2)](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2).

**Comment by Naxos84** [comment]
it is still reproducable with:

Version: Insomnia 2022.2.1
Release date: 21.3.2022
OS: Windows_NT x64 10.0.19045
Electron: 17.1.0
Node: 16.13.0
V8: 9.8.177.11-electron.0
Architecture: x64

Importing as request collection still works but isn't really a solution.

**Comment by Naxos84** [comment]
I was able to test it with:

Version: Insomnia 2023.1.0
Build date: 9.3.2023
OS: Windows_NT x64 10.0.19045
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

I switched between Design & Debug multiple times and it seemed as if no requests were duplicated.

**Comment by gatzjames** [comment]
Closing as generating requests is now a manual process and there is no override previous data functionality.
