### ISSUE TITLE
Add dropdown arrow indicator for SEND button

### ISSUE THREAD

**Issue by allandiego** [getinsomnia/insomnia#2083]
**Is your feature request related to a problem? Please describe.**
Currently the send options are hidden, you have no way of knowing that you need to use the right click to show up the advanced menu, i just figured out this looking for issues about how to download a file from response

**Describe the solution you'd like**
Add a dropdown arrow like the others elements for example the http method to indicate that there are more options, i think it would be better a new button with the arrow on the side of sent button to keep the default sent action as its the most used one

**Comment by nijikokun** [comment]
Makes sense, we use this pattern in other places, however here, maybe a split button pattern?

Everyone right clicking the send button right now:

![](https://media0.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy-downsized-medium.gif)

**Comment by gschier** [comment]
For some backstory... That dropdown was added years ago but I always thought a down-arrow icon made it look bad, so never added it. I also agree with @nijikokun that having two buttons makes more sense if a single click still triggers an action.

**Comment by allandiego** [comment]
It would be nice also add a highlight to the buttons in the white url bar, maybe a border, it is difficult to distinguish that they are buttons at first sight when you open the program for the first time

**Comment by amaaniqbal** [comment]
Can I work on this issue @nijikokun? I might require some guidance to get started. :)

**Comment by amaaniqbal** [comment]
@gschier @allandiego @nijikokun can I help here?

**Comment by kreosus** [comment]
Hi @allandiego 
Do you see the same behavior with our latest release located here: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.4

**Comment by wongstein** [comment]
This feature has been implemented. Cheers all!
