### ISSUE TITLE
Insomnia Designer, Documentation: Repo folder should be `.insomnia` instead of `.designer`

### ISSUE THREAD

**Issue by rmharrison** [getinsomnia/insomnia#2085]
**Describe the bug**
>  Note: Designer does not currently support repositories that contain files outside the root ".designer" folder.
> In order to clone, the repository must exist and also contain the root .designer/ folder.
https://support.insomnia.rest/article/96-git-sync (accessed 29 April 2020, 21:59 ET)

However, when I look at my git repo:
```
> ls -a
.  ..  .git  .insomnia
```

And if I use the folder `.designer` instead (https://github.com/rmharrison/insomnia-designer-medium/tree/designer-folder-test)
![20200429_Insomnia_Designer_CloneFailure](https://user-images.githubusercontent.com/4275722/80664933-11506480-8a66-11ea-9819-ed237c1cfdd7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Installation Method: `.deb`
 - App Version: [designer@2020.1.3](https://github.com/Kong/insomnia/releases/tag/designer%402020.1.3)

**Root cause resolution**
I couldn't find your support docs hosted in github. Host them in a repo alongside the code, so the support and code are better able to remain in sync.

**Comment by gschier** [comment]
Thanks for reporting this! I went ahead and updated the docs to change references of `.designer` to `.insomnia`
