### ISSUE TITLE
[Bug] Cookie handling regression from v4 to v5

### ISSUE THREAD

**Issue by paol** [getinsomnia/insomnia#209]
## Overview
- `Insomnia Version:` e.g. 5.0.10
- `Operating System:` Tested on Linux
- `Summary: ` Apparently related to the adoption of libcurl, v5.0.10 rejects cookies served from a non-standard port if the cookie domain does not contain the port.

## How To Reproduce

Abridged log:
```
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api/login HTTP/1.1
> Host: localhost:8000

< HTTP/1.1 200 OK
* skipped cookie with bad tailmatch domain: localhost
< Set-Cookie: blabla; Path=/; Domain=localhost
```

This is different from the v4 behavior, and more importantly it's
different from browser behavior. Both would accept this cookie.

## Other Notes

This was previously submitted by email to support@insomnia.rest. I copied the resulting discussion below:

<details>
<summary>Email Thread</summary>

> Hi Pedro,
> 
> I just reproduced this locally and can confirm the difference in behavior. It looks like Curl is rejecting the cookie because the domain does not contain a period (see Curl cookie spec). Unfortunately, it doesn't look like this behavior can be configured.
> 
> I found two workarounds that worked, but both require server-side intervention.
> 
> - Switching localhost server to include a period like "foo.localhost"
> - Omit the Domain attribute entirely in the set-cookie header (Curl will default to the request domain "localhost")
> 
> I'm going to do a bit more digging and see if there's anything I can do client-side to make this work.

> From what I understood from googling the curl message ("skipped cookie with bad tailmatch domain: localhost"), curl special-cases the "localhost" domain, but not if the request was to a non-standard port. Supposedly it would work if the cookie domain had been set to "localhost:8000" but I didn't test that as it would require changing the server.
> 
> Maybe this warrants a bug report against curl.

> Do you have a link for where you read that? It didn't come up in my own search. I just tried with a localhost server on port 80 and got the same tail match error.

> https://bitbucket.org/snippets/rrrbn/B6L4z/the-sane-way-of-curl
> 
> Might be false information, like I said I didn't test it.
> 
> If it's rejecting all localhost cookies, then it's a bigger problem. Judging from this [https://github.com/curl/curl/issues/658] curl people would consider it a bug, so I assume it's supposed to work.

> Oh ya, I did actually see that bitbucket snippet but, when I tested it, still saw a failure.
> 
> I just cracked open the Curl source and found the code https://github.com/curl/curl/blob/66de563482c0fd4324e1eae19809d2499e3c4fa8/lib/cookie.c#L502
> 
> Currently playing around to see if I can get a build that triggers this case (without USE_LIBPSL defined).

</details>

**Comment by gschier** [comment]
@paol thanks for re-submitting this so that it can be tracked and discussed in the open. I spent almost a day trying to figure this one out but couldn't figure out a good solution.

This bug is a result of switching from NodeJS to libcurl for networking in version 5. I _did_ get a build of libcurl (without libpsl) that accepted localhost cookies, but it still would not work on non-standard ports. Given that it is rare to run local servers on standard (80/443) ports, I chose not to continue down that path.

**One workaround** would be to automatically convert `localhost` hostnames to `localhost.insomnia` and use `[CURLOPT_RESOLVE](https://curl.haxx.se/libcurl/c/CURLOPT_RESOLVE.html)` to tell curl to resolve `localhost.insomnia` to the same IP as `localhost`.

Thoughts?

**Comment by paol** [comment]
I'm not sure I understand how that workaround would work. If localhost is converted to localhost.insomnia, then a cookie returned for localhost definitely wouldn't be accepted?

Wouldn't it be simpler for the application to examine the Set-Cookie headers and override libcurl behavior when it needs to? The problem seems to be only with localhost cookies, so if a valid one is detected, just add the cookie to the cookie store regardless of what libcurl does.

**Comment by gschier** [comment]
@paol ya, you're right. That idea _wouldn't_ work unless it also updated the domain in the set-cookie header.

Just put up #220 which switches set-cookie handling from `libcurl` to `tough-cookie`. It still needs some testing and the ability to handle redirects, but it seems like it could work.
