### ISSUE TITLE
Request can't be canceled

### ISSUE THREAD

**Issue by tms1337** [getinsomnia/insomnia#2090]
Let me note that this is a minor issue, but it might tell you something more about request handler potentially.

**Describe the bug**

When using graphQL, if  the server is taking long to respond, if I send request AND try refreshing the schema, and then cancel the request, it cancels the schema fetching, not the request. Request is left hanging.

**To Reproduce**
1. Make a dummy graphql server that will time out at `localhost:1337/graphql` with `Query.hello`. This happened to me in non-dummy server which happened to have longer time to respond, but in order for the issue to be reproducible, we go with this one.
2. Send `Query.hello` request
3. Click "Refresh schema" while the request is still going on
4. Cancel the request by clicking "Cancel the request" on the right side
5. This cancels the "Refresh schema" request, the small toast appears on the bottom of the left part. But the original request is stuck you can't cancel it.

Here is the code for step 1 in `nodejs`:

```
const http = require("http");
const port = 1337;

const requestHandler = (request, response) => {
  request.on("data", (chunk) => {
    console.log(`Data chunk available: ${chunk}`);
  });
};

const server = http.createServer(requestHandler);

server.listen(port, (err) => {
  if (err) {
    return console.log("something bad happened", err);
  }

  console.log(`server is listening on ${port}`);
});

```

**Expected behavior**
The request can't be canceled. I hack it by sending again and then canceling.

**Screenshots**

## 1. Sending the request 

<img src="https://imgur.com/qUflnWW.png" width=1000 height=400>

## 2. Refresh Schema

<img src="https://imgur.com/NhYTiZw.png" width=1000 height=400>

## 3. Cancel the original request, it gets stuck schema gets canceled

<img src="https://imgur.com/qSV4roN.png" width=1000 height=400>

**Desktop (please complete the following information):**
 - macOS

**Comment by chbndrhnns** [comment]
I am also experiencing that a request cannot be cancelled.

```
Version: Insomnia Core 2020.5.2
Release date: 9.12.2020
OS: Darwin x64 18.7.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Comment by gatzjames** [comment]
Closing as this should be working properly now
