### ISSUE TITLE
[Feature Request] Save and close Environment Editor with Ctrl+Enter

### ISSUE THREAD

**Issue by meixger** [getinsomnia/insomnia#2091]
**I would like to press Ctrl+Enter to save and close the Environment Editor.**

I'm always frustrated when i have to leave the keyboard and use the mouse.

The Environment Editor can be opened with Ctrl+E but needs to be closed by pressing the "Done" button.

**Comment by develohpanda** [comment]
Hi @meixger! Pressing escape seems to achieve the same workflow - save the env and close the editor. Does this work for your case? (I'm using macOS, Insomnia v7.1.1)

**Comment by meixger** [comment]
Yes. How embarassig - i realized that pressing escape also saves the env 😌

**Comment by develohpanda** [comment]
No worries! I have seen talk of _not_ saving env changes specifically when pressing escape to close the modal, however for now, this works. 🤗
