### ISSUE TITLE
RAML Support

### ISSUE THREAD

**Issue by aniq-pirzada** [getinsomnia/insomnia#2093]
**Is your feature request related to a problem? Please describe.**
I would like to import RAML (.raml) documents into Insomnia Designer

**Describe the solution you'd like**
RAML is extended from YAML and at the moment Insomnia Designer does not allow to import .raml files.
It would be great to see support for this extension..

**Comment by aniq-pirzada** [comment]
@nijikokun can you add the feature label to this please :)

**Comment by humb1t** [comment]
Would be glad to participate as contributor if this FR will be approved.
