### ISSUE TITLE
Crashes when typing openAPI spec

### ISSUE THREAD

**Issue by LucasSimpson** [getinsomnia/insomnia#2094]
**Describe the bug**
Program crashes

**To Reproduce**
1. Create new blank document, name it whatever
2. Type the following into the spec:
```json
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
```

3. Enter the following line after "servers:":
```
  - urls:
```
4. The program should crash

**Expected behavior**
The program does not crash

**Screenshots**
After step 2: https://allthepics.net/image/t1jsE
After step 3: https://allthepics.net/image/t1yeT

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Home, Version	10.0.18362 Build 18362
 - Installation Method: homebrew
 - App Version:
Version 2020.1.3
Shell 3.1.13
Node 10.2.0
V8 6.6.346.32
Architechture x64

libcurl/7.57.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.7.0_DEV

**Additional**
When it crashes it says to email support, i did, but they responded to open an issue here. Would probably be better to have the app just link to opening an issue instead. Also, I should be able to copy the Insomnia Designer Help -> About info instead of manually typing all that out

**Comment by nijikokun** [comment]
Oof, thanks for reporting this. Getting some eyes on it now 👀 

pinging @develohpanda who has been looking into similar issues 🤗

**Comment by develohpanda** [comment]
It works fine in the state where you previously _copy-pasted_ a spec with servers, and then removed it. Swagger UI shows an error correctly, in that state.

![](https://user-images.githubusercontent.com/4312346/80432038-2edadc80-8947-11ea-8b39-0384ea6a708d.gif)

Reopening a broken spec (that previously showed the error correctly in the design view), shows the reported behavior, therefore rendering the spec unusable.

![reopen](https://user-images.githubusercontent.com/4312346/80432386-2e8f1100-8948-11ea-9430-22b8fa82bff8.gif)

General direction for a fix is to create a safety net around Swagger UI. There are edge cases where the error thrown by the component is fatal (and should not be).
