### ISSUE TITLE
Cannot use Azure DevOps git repo in Insomnia Designer

### ISSUE THREAD

**Issue by dryize** [getinsomnia/insomnia#2095]
**Describe the bug**
In the designer when try to import a git repo hosted in Azure DevOps, nothing happens. 

**To Reproduce**
1. Open Designer
2. Click on 'Create' -> 'Git Clone'
3. Configure using Azure DevOps git repo
4. Click 'Done' and observe nothing happens.
5. Open Developer Tools
6. Observe error message "HTTPError: HTTP Error: 404 Not Found"

**Expected behavior**
New Workspace to be added based on the repo

 - App: Insomnia Designer
 - OS: macOS 10.14.5
 - Installation Method: Package downloaded from website
 - App Version: 2020.1.3

**Additional context**
I did some troubleshooting and found out that, insomnia appends string ".git" to the provided git url. This works with github. But some services live Azure DevOps doesn't support .git URL and returns 404 when queried.

**Workaround**
As a workaround I renamed Azure Git Repo to end with .git (Ex: backend.git). Then when configuring Insomnia I used the url without the .git portion.

**Comment by sonicyeti** [comment]
@dryize Just a quick update, we are looking into full OAuth support for Azure DevOps. We'll touch base shortly!

**Comment by sonicyeti** [comment]
We are exploring options that will expand git support for Azure (among others) however currently we don't have an ETA on when that might ship. Thanks again for identifying this @dryize!

**Comment by Ruan20795** [comment]
I know this issue is closed, and it was mentioned that there isn't an ETA on this, but that was a while ago and was wondering if there is any progress on this?

This is quite critical for us since all our code is hosted in Azure DevOps Git...

**Comment by nizmow** [comment]
I don't see how this needs "support" for Azure Devops. It's just a git repository, and it's a simple mistake on this side to try and append `.git` at the end. Holding me back from using this feature, too.

**Comment by JDCain** [comment]
I'm using DevOps Server which is the onprem version and I am having this issue, so anything related to OAuth would not help since we are not using Azure AD for authentication.
