### ISSUE TITLE
Designer export dropdown says "workspace" instead of "document"

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2098]
**Describe the bug**
Designer verbiage says "Workspace" instead of "Document"

**To Reproduce**
1. `Cmd` + `,` to open the preferences tab
2. Click on data
3. Click Export data

**Expected behavior**
Should use the "document" verbiage from https://github.com/Kong/insomnia/blob/6fc394891d575931a0ca7f9babde3adb6a7452ef/packages/insomnia-app/app/common/strings.js#L7

**Screenshots**
![image](https://user-images.githubusercontent.com/4312346/80343310-c0037200-88b9-11ea-8d24-1f49d06417e7.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Installation Method: DMG install
 - App Version: v2020.1.0-beta.1

**Comment by imrishabh18** [comment]
@develohpanda Can you assign me this issue ?

**Comment by develohpanda** [comment]
Feel free to work on this @imrishabh18 🤗
