### ISSUE TITLE
Axios support for Code Generation

### ISSUE THREAD

**Issue by jacobparis** [getinsomnia/insomnia#2110]
The code generation for Javascript (browser) supports jQuery, fetch, and XHR. For Node.js it supports http, request, and unirequest

Axios is one of the most popular request libraries in the javascript ecosystem, working on both frontend and backend code with the same API and only weighing 5kb after gzipped 

If deemed to be within scope for insomnia, I'd be willing to submit a PR adding code generation Axios support for both Javascript and Node.js categories

**Comment by gschier** [comment]
Thanks for the request! 

It looks like there's already a discussion for axios on the `httpsnippet` library that generates these. Please feel free to participate in that discussion/work 🙂
 https://github.com/Kong/httpsnippet/issues/155

**Comment by jacobparis** [comment]
Oh thanks for the direction 🙏
