### ISSUE TITLE
Design mode's spec validator runs before spec renders in

### ISSUE THREAD

**Issue by reynolek** [getinsomnia/insomnia#2113]
**Describe the bug**
When switching from Debug mode to Design mode with a valid spec, the linter briefly says there is an error on the first line (`'undefined' does not exist @ ''`). Likely the linter is running too soon. You can see the spec file blink in when switching.

**To Reproduce**
1. Enter a valid spec into Design mode
2. Go to Debug mode
3. Switch back to Design mode
4. See linter error red dot on at line 1

**Expected behavior**
Linter runs a bit later in the chain such that a valid spec isnt mark invalid even for ~2 seconds.

**Screenshots**
![insomnia_bug](https://user-images.githubusercontent.com/5934780/81010808-b6bf5b80-8e0b-11ea-97b8-1ccd1d0b435c.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Installation Method: Website
 - App Version: Designer 2020.1.3

**Additional context**
N/A

**Comment by sonicyeti** [comment]
Can't reproduce, verified on @reynolek's env.
