### ISSUE TITLE
[Feature Request] Schema Exploration

### ISSUE THREAD

**Issue by IamFlowZ** [getinsomnia/insomnia#2116]
**What is the context?**
From my experience using insomnia, you can only explore the root query and mutation objects that your schema definition contains. Transitively, you can only explore types that are currently being used by those objects. Any type you define, has to be used be either the root query object or the root mutation object, at one point or another. Otherwise it is inaccessible from within the insomnia documentation explorer. Currently I'm working on a couple projects that use Neo4J and its node libraries to develop a GraphQL service. They add a lot of Neo4J specific types into the schema, so as to make working with the system simpler. (See below image, taken from GraphQL Playground)![Hidden Schema Types](https://user-images.githubusercontent.com/27895218/81091374-21849b80-8ecd-11ea-9097-3e93988aae8a.png) 
Being unable to see these types makes it more difficult to use insomnia, due to missing some types that may not be actively used within the root objects. It can also be inconvenient at times, due to having to dig through the root objects in order to view the definition for a type that is used in the schema. 

**What is your question?**
Would it be possible to view the full schema plainly, without having to descend through the root objects? This makes it simpler to find deeply nested types, as well as types that aren't currently in use by any queries or mutations.

**Comment by nijikokun** [comment]
Hi there 👋 

Is this related to #2019?

Seems like this issue would also benefit from #1864 & #1831

**Comment by IamFlowZ** [comment]
Yes, I would agree that all three could possibly be solved, if you could plainly view a schema file. I've looked at both the introspection query that is called to get the schema, along with the component responsible for rendering the documentation. The introspection query 100% has all the information necessary to display a full schema, what will probably need to be changed is the GraphQLExplorerSchema component. To what extent, I'm not sure because I have yet to try and spin this up in a dev environment.

**Comment by Macavirus** [comment]
Not stale, still a useful feature.

**Comment by gatzjames** [comment]
Closing as this is possible by searching in the documentation explorer
