### ISSUE TITLE
Sharing auth method

### ISSUE THREAD

**Issue by Bogidon** [getinsomnia/insomnia#2118]
**Describe the solution you'd like**
1. An way to easily share an oauth provider as the auth mechanism for a bunch of different endpoints, or an entire environment.
2. Would also love it if the auth cookie is held on to so a new token can be issued without another login.

**Describe alternatives you've considered**
Currently I have one endpoint that has the auth mechanism (OAuth 2) set up. I copy the returned bearer token into the environment config. When the token expires in 2 hours, we have to do the whole process again, including logging into our auth provider. Many of my coworkers consider this too cumbersome to want to use Insomnia.

**Additional context**
I think if Insomnia had an easy way to do this, we'd have had a few monthly licenses by now.

**Comment by nijikokun** [comment]
Welcome @Bogidon 👋 

Oh, I see, something like a shared authentication store that you could reference on requests? Seems like a really good idea actually. I'm wondering if it could be used more than just authentication.

@gschier is there anything like this in the app currently?

**Comment by gschier** [comment]
There was a discussion a long time ago under the feature "Parent Requests" but it was abandoned for various reasons: #598 

For OAuth 2.0, specifically, someone has created a plugin that allows referencing the Access Token from a different request. That way you only have to define the information once. This should solve your immediate problem of manually copying the token into the environment:

https://insomnia.rest/plugins/insomnia-plugin-accesstoken

In general, I like the idea of being able to reference parts of other requests. I think this provides the most flexibility while not overcomplicating the existing UI/UX.

**Comment by Bogidon** [comment]
👋 

In general +1 to referencing parts of other requests. Though, to me the clearest way for auth to work would be if you can declare an auth strategy that can be applied to multiple requests, that would internally only rerun as necessary. That would remove the "oh you have to run this special request first". 

Thanks for the plugin. I tried a [different one](https://github.com/malm/insomnia-plugin-save-access-token) a while ago that I couldn't get working, so I'll give this one a shot.

**Comment by Bogidon** [comment]
@gschier @nijikokun ping that we'd likely pay for Insomnia were this implemented.
