### ISSUE TITLE
Request chaining is not very user friendly.

### ISSUE THREAD

**Issue by rb610** [getinsomnia/insomnia#2122]
how to achieve this using insomnia : 

For example : 

request 1 : login with username and password
response: returns sessionId for user. 
set this sessionId in env variables

request 2 . use this env variable in header or in body of Request # 2

**Comment by gschier** [comment]
I suggest taking a look at the request chaining documentation in Insomnia: https://support.insomnia.rest/article/43-chaining-requests

It sounds like you might be coming from Postman, which has the concept of setting an environment variable after a response. Insomnia, however, solves this problem with a different solution: if you want to reference a sessionId from a separate request, you use the Response template tag to do that:

![image](https://user-images.githubusercontent.com/587576/81235846-c1ffbc00-8fb0-11ea-93a1-17baf3daab29.png)

Note, you can also use this template tag within your environments to get similar functionality to what you mentioned in your issue:

![image](https://user-images.githubusercontent.com/587576/81235877-d2b03200-8fb0-11ea-93f0-2e8e817c8136.png)

There is also a helpful video from the community that shows you how to do exactly what you're asking: https://www.youtube.com/watch?v=sBzM8seASGo

**Comment by rb610** [comment]
thanks very much !

how to run multiple request from single folder?

**Comment by rb610** [comment]
Also, 
1. how to find difference between saved request and unsaved request. is there any notation to distinguish it.

2. How to set expected result, to identify response as pass or fail.
