### ISSUE TITLE
[Feature Request] - Improve error message when variable is not found

### ISSUE THREAD

**Issue by knokio** [getinsomnia/insomnia#2123]
**The error message before sending a request, when some variable is missing is not very clear**

**To Reproduce**
1. In any request add some non-existing variable to the body or headers
2. Send request
3. See error: `attempted to output null or undefined value`

**Expected behavior**
The error should be clearer: `variable not found in body: test_password`

**Screenshots**
These screenshots are one example of this problem.
 
![The request](https://user-images.githubusercontent.com/667278/81161354-5ce1a180-8f83-11ea-95fc-b24b5f1e5c3d.png)
_The request_

![image](https://user-images.githubusercontent.com/667278/81161475-88fd2280-8f83-11ea-9a90-405116abc75a.png)
_The environment configuration. Notice how it's missing the `test_password`_

<img width="700" alt="Screenshot 2020-05-06 at 10 24 35" src="https://user-images.githubusercontent.com/667278/81161640-cbbefa80-8f83-11ea-9a4c-433e890053a4.png">

_The current error message_

**Desktop (please complete the following information):**
 - OS: Mac 10.15.3
 - Installation Method: homebrew
 - App Version 7.1.1

**Comment by wongstein** [comment]
Thanks for the report and the feature request!  We are in the process of rethinking our UX and making improvements.  This was a great point to make that would improve our Users' experience greatly.

**Comment by subnetmarco** [comment]
Being worked on in https://github.com/Kong/insomnia/pull/7227 and will ship in a few weeks.
