### ISSUE TITLE
Windows defender raises security issue while downloading / Installing Designer 2020.1.3

### ISSUE THREAD

**Issue by giladt** [getinsomnia/insomnia#2124]
Got this error message while trying to install `Insomnia.Designer-2020.1.3.exe`.
Apparently because of certificate issue.

![image](https://user-images.githubusercontent.com/2517870/81175969-b1e1df80-8fa4-11ea-9918-cd93209ca344.png)
 
![image](https://user-images.githubusercontent.com/2517870/81175549-0173db80-8fa4-11ea-9e11-8d0b4c9a13c6.png)

**Comment by nijikokun** [comment]
Welcome @giladt 

It will take some time for the certificate to reach it’s installation quota and be “safe”. 😞

Unfortunate issue with new certs.

**Comment by gschier** [comment]
Insomnia (Core) had this problem for months after launch. Hopefully Designer will exit the transition more quickly from having a larger number of users to start with.

As an additional note, virus scanning software will sometimes also flag it for the same reasons, until enough people mark it as "safe".

**Comment by nsankaranarayanan** [comment]
Running into the same issue.
