### ISSUE TITLE
The response should be parsed by Insomnia

### ISSUE THREAD

**Issue by igor-simoes** [getinsomnia/insomnia#2127]
Recently, I migrated from Postman to Insomnia and it worked very well. A few moments ago I tried to get a response from a private service and the result didn't work as expected.

The Header contains:
```
Cache-Control | no-cache
Pragma | no-cache
Content-Type | application/x-gzip; charset=UTF-8
Server | Microsoft-IIS/8.5
X-AspNet-Version | 4.0.30319
X-Powered-By | ASP.NET
...
```

**Screenshots**
I ran the same request in Postman and worked as expected.
Postman
![image](https://user-images.githubusercontent.com/24598778/81178363-77654c00-8f7e-11ea-9e5b-cf62daf764fe.png)
Insomnia
![image](https://user-images.githubusercontent.com/24598778/81178431-906dfd00-8f7e-11ea-84d5-4c96429feb00.png)

**OS**
 - OS: Mint 19.2 Cinnamon
 - Installation Method: apt-get
 - Versions
![image](https://user-images.githubusercontent.com/24598778/81178993-69fc9180-8f7f-11ea-84b8-dd8c7807bff8.png)

**Comment by gschier** [comment]
Can you please provide a public endpoint that can be used to reproduce this?

**Comment by igor-simoes** [comment]
Hi @gschier thanks for the response. I don't know how proceed to reproduce this case, it is a paid service that I don't have access to the server. I stored the response obtained by Postman and I built a simple api to provide the data. The Insomnia got the data with success. I think it is something related to client-side when try to enconding/parsing the data but I really don't know what happened.

**Comment by wongstein** [comment]
Without being to reproduce this error, it's hard for us to know what was in the data that caused the parsing error.  While I understand that this is frustrating to encounter, I feel I should close this issue until more definite details are available.  Please feel free to open a new issue if you are able to give more details
