### ISSUE TITLE
Insomnia freezes lightdm on startup

### ISSUE THREAD

**Issue by yagodorea** [getinsomnia/insomnia#2128]
**Description**
Insomnia sometimes freeze my UI when I try to open it.

I've seen this bug happen in two different scenarios.
- First when I forcibly closed Insomnia in the middle of a request and then tried to open it again. I guess the Responses file wasn't properly closed by then and when Insomnia tried to open it it somehow messed up my lightdm (the screen was frozen and I had to restart my session from tty1). This time I had to erase the file at ~/.config/Insomnia/insomnia.Response.db and the files in the folter 'responses' at the same location. Then Insomnia would start properly.
- Second scenario is when I try to open two instances of Insomnia at the same time, this happens consistently and my guess is it tries to open the Responses file when it's not properly closed. Same lightdm freezing happens.

**To Reproduce**
1. Open Insomnia
2. Shift+Click the Insomnia icon on taskbar to try to open another instance
3. Your screen will freeze (but the processes will not, if theres media playing it will continue playing)
4. To restore your session: Ctrl+Alt+F1 to access tty1, log in, type `sudo service lightdm restart`. You will lose all the session work, as if you had rebooted.

**Expected behavior**
Another Insomnia process starts, or an error is displayed informing why it couldn't be started.

**Computer:**
 - OS: Mint 19.1 (Cinnamon 4.0.10)
 - Installation Method: mintinstall (Software Manager)
 - App Version: v7.1.1

**Comment by gschier** [comment]
Hmm, this sounds like similar behavior to when Insomnia freezes when trying to render really large responses (> 5MB). Did this happen with larger responses, specifically, or did that not matter?

Just one more note, it is currently a bug that you can open multiple Insomnia windows on Linux/Windows. Insomnia does not properly handle having multiple windows open at this time.

**Comment by yagodorea** [comment]
> Hmm, this sounds like similar behavior to when Insomnia freezes when trying to render really large responses (> 5MB). Did this happen with larger responses, specifically, or did that not matter?
> 
> Just one more note, it is currently a bug that you can open multiple Insomnia windows on Linux/Windows. Insomnia does not properly handle having multiple windows open at this time.

I'm not sure that's the case. The overall size of the responses folder was over 5MB, I guess? But I don't think any individual response was that size. Also it never happened while opening any request, just when opening the app itself.

**Comment by yagodorea** [comment]
Updates: it happened again, but instead of having to delete insomnia.Reponse.db to make Insomnia able to open again, I had to delete the insomnia.RequestVersion.db.

**Comment by gatzjames** [comment]
Closing as we now support multiple windows and have gone through many updates to fix similar issues
