### ISSUE TITLE
recursive schema items are empty

### ISSUE THREAD

**Issue by mdaniel** [getinsomnia/insomnia#2137]
**Describe the bug**

When trying to use an OpenAPI file with [a recursive schema definition](https://json-schema.org/understanding-json-schema/structuring.html#recursion), the recursive type is omitted from the schema browser

**To Reproduce**
1. Load the file below
1. Expand the `person` schema
1. Expand the `children` items
1. Observe the list is empty

**Expected behavior**

Either allow expanding the item's type, or a visual indicator that it is a placeholder for a recursive type definition

**Screenshots**
![Screen Shot 2020-05-07 at 9 35 30 PM](https://user-images.githubusercontent.com/22526/81370878-17b88f00-90ab-11ea-9be0-dad9b6dcb739.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6 and Ubuntu 19.10
 - Installation Method: dmg, and also using `master`
 - App Version Version 2020.1.3 (2020.1.3.3486) and also `master`

**Additional context**

The [Swagger Editor website](https://editor.swagger.io/) similarly does not render it, so it could be a problem with some shared library

```yaml
openapi: 3.0.0
info:
  title: recursion is awesome
  version: 0.0.0
paths:
  /person:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/person'
components:
  schemas:
    person:
      type: object
      properties:
        children:
          default: []
          items:
            $ref: '#/components/schemas/person'
          type: array
        # this was just to test if it only affects `type: array`
        friend:
          $ref: '#/components/schemas/person'
        name:
          type: string
```

**Comment by kreosus** [comment]
Hi @mdaniel 
Have you tried this on our newest release, available here: https://github.com/Kong/insomnia/releases/tag/core%402022.5.0?

**Comment by kreosus** [comment]
Hi @mdaniel 

As we have not heard back from you we are closing this issue out. If you require any further/future assistance please let us know and we will proceed accordingly. Have a nice day.
