### ISSUE TITLE
Cannot sync with Gitlab repository

### ISSUE THREAD

**Issue by superj80820** [getinsomnia/insomnia#2138]
**Describe the bug**
Cannot sync with Gitlab repository

**To Reproduce**
1. Set Gitlab [personal access token](https://gitlab.com/profile/personal_access_tokens)
  ![20200508122831](https://i.imgur.com/hDxKRRB.png)
2. Copy token
  ![20200508123023](https://i.imgur.com/7kjrNcU.png)
3. Paste to insomnia designer
  ![20200508122957](https://i.imgur.com/vCFFy8O.png)
4. Pull repository. Get Error
  ![20200508124456](https://i.imgur.com/5MHyA8X.png)
5. Get the authentication error message

  ```
  HTTPError: HTTP Error: 401 Unauthorized
      at Function.discover (/Applications/Insomnia Designer.app/Contents/Resources/app.asar/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:6481:13)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  ```

**Expected behavior**
Can be sync with Gitlab repository

**Desktop**
 - OS: [macOS 10.15.3]
 - Installation Method: [dmg]
 - App Version [2020.1.3.3486]

**Additional context**
I think it may be that the Gitlab authentication method is different from Github. I found that insomnia designer seems to use the `info/refs` API to get repository information. When I tried to use this API to get data, I found that Github and Gitlab responded differently.

I observed through the monitoring tool that the same API responds differently on Github and Gitlab
* Github:
  ```
  Request:
  curl --request GET \
    --url 'https://github.com/superj80820/study-insomnia-designer.git/info/refs?service=git-upload-pack'

  Response:
  001e# service=git-upload-pack
  000001430f97277b0f18d5c035c082067f0913cfd0999230 HEADmulti_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed allow-tip-sha1-in-want allow-reachable-sha1-in-want no-done symref=HEAD:refs/heads/master filter agent=git/github-ge76e9aafbc97
  003f0f97277b0f18d5c035c082067f0913cfd0999230 refs/heads/master
  0000
  ```
* Gitlab:
  ```
  Request:
  curl --request GET \
    --url 'https://gitlab.com/superj80820/study-insomnia-designer.git/info/refs?service=git-upload-pack'

  Response:
  HTTP Basic: Access denied
  ```

**Comment by nijikokun** [comment]
After doing some research, @develohpanda it appears that a combination of Bearer + Scopes + `.git` might resolve the issue. https://github.com/isomorphic-git/isomorphic-git/issues/1082 https://github.com/isomorphic-git/isomorphic-git/issues/1122

**Comment by develohpanda** [comment]
Looks like we're not sending `username` as part of the requests to GitLab. It is only optional for GitHub as per isomorphic-git implementation. I forced it to my username for testing and voila!

![image](https://user-images.githubusercontent.com/4312346/81626068-c31c6780-944e-11ea-858b-e275de8101c6.png) [ref](https://isomorphic-git.org/docs/en/authentication)
