### ISSUE TITLE
Query Variables viewport - Strange jumps in scroll position while editing

### ISSUE THREAD

**Issue by jigarius** [getinsomnia/insomnia#2139]
**Describe the bug**
  * Say, you're preparing a query with a bunch of input vars.
  * When you edit the Query Variables, there are strange jumps in the scroll position unlike I've ever seen in any other app. These result in a negative experience.
  * Seems like the app tries to adjust the scroll such that the line you clicked appears as the last line.

**To Reproduce**
1. Type in a long enough JSON in the input variables area.
2. Try to edit it in a natural way, i.e. scroll with the keyboard, click at random places.
3. You'll notice that the scroll position oddly jumps and makes it hard to track where you were typing.

**Expected behavior**
Scroll position should not be affected unless an actual scroll is intended.

**Screenshots**
If the description above is not helpful, let me know and I'll record a gif.

**Desktop (please complete the following information):**
 - OS: MacOS (latest)
 - Installation Method: Cannot remember - I used the recommended method
 - App Version: 7.1.1.3350

**Additional context**

**Comment by filfreire** [comment]
This is still somewhat reproducible, even on [latest builds](https://github.com/Kong/insomnia/releases) (e.g. [2022.6.0-beta.1](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.1)), although it's sometimes hard to notice.

Here's an example video where I was trying to purposely scroll back and forth from the the top of the list until the bottom, and sometimes indeed I noticed jumps. These jumps seem to happen if we have one field in focus/being edited and then we do the scroll motion.

https://user-images.githubusercontent.com/11976836/184336070-d420e9b4-06a3-4194-a788-cad7b9b4b48f.mov

I'm tempted to close this one, but will mark internally as needs fix for now. 

@jigarius feel free to report any other issues you come across.

**Comment by gatzjames** [comment]
Closing as this is fixed in 8.6.1!
