### ISSUE TITLE
Legacy component migration

### ISSUE THREAD

**Issue by sonicyeti** [getinsomnia/insomnia#2140]
Migrate the following components from legacy to latest instance of Storybook.
- [x] Notice
- [x] Prompt Button
- [x] Help Tooltip
- [x] Forms

~~Editable~~

Visually organize components in storybook mirroring MUI/Boostrap/Foundation

**Comment by sonicyeti** [comment]
@gschier I've created a "helpers" directory for the components where I've moved "intermediate-checkbox.js" to support the Forms component. However the Editable component relies on many deep /insomnia-app/ based items so I'd like to omit editable from this round and touch base on how we can treat those. Perhaps updating the configured context for SB to allow for direct access to /insomnia-app/ related deps but again, want to touch base on it.

**Comment by filfreire** [comment]
@wdawson closing this one, don't think it's applicable no more.
