### ISSUE TITLE
(Insomnia Designer): some text not visible on darker themes

### ISSUE THREAD

**Issue by EnilPajic** [getinsomnia/insomnia#2142]
**Describe the bug**
When switched to darker theme, some text is not visible or it is very hard to see (depending on the theme).

**To Reproduce**
1. Open Insomnia Desginer,
2. create new Blank document
3. Change theme to e.g. Default (dark)

**Expected behavior**
To see the full text, especially 'code syntax'

**Screenshots**
<img width="679" alt="image" src="https://user-images.githubusercontent.com/11429744/81450980-d1832e80-9183-11ea-84a8-169ca42ecee9.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Installation Method: double click on the app, drag to Applications folder
 - App Version: 2020.1.3.3486

**Additional context**
It is not necessary to change theme _after_ the Blank document creation. Theme can be changed anytime and the effect will be the same.
Also, app restart doesn't help. As I can see, it affects only code syntax, e.g. that looks like `this`.

**Comment by sonicyeti** [comment]
Thanks for the feedback!  🙏
