### ISSUE TITLE
GraphQL enumeration auto complete.

### ISSUE THREAD

**Issue by nishantha-kumara** [getinsomnia/insomnia#2147]
I already used many tools such as altair graphql client, apollo graphql client like that. but I moved to insomnia because the interface is very clear and has some valuable features. 

**Today I notice something in insomnia, the enumeration variable does not suggest (autocomplete) so I think this feature is valuable for the developers.**

**Comment by develohpanda** [comment]
Duplicate of #902 (I think?)

@nishantha-kumara please close this issue if #902 sufficiently summarizes what you are after.

**Comment by nishantha-kumara** [comment]
move to #902
