### ISSUE TITLE
Multi-Window, Sync, Workspace ex/import

### ISSUE THREAD

**Issue by crimsonvspurple** [getinsomnia/insomnia#2152]
I'm a heavy user of Insomnia and I even paid for team/sync features at some point.

Generally, these are the issues I have faced:
- open multiple window, you can work on multiple workspaces; but if you by mistake open same workspace on multiple window, depending on what you change, when you close these windows, things get overwritten. Has this been fixed?

- Similarly, people with sync making changes on same/different endpoints in same/different times and often the stuff are overwritten and data is lost (I lost a big chunk and that's why I stopped paying for sync). Has this been fixed?

I'd probably like to get back on paid plan...but last time the experience was terrible.

Additionally,
- Importing workspace is problematic too. Someone makes a change in workspace file. You import it, it overwrites/merges based on last changed date i assume? Things that are deleted, gets added back. Wouldn't it be better if there was a deletion tracking?

- I have seen insomnia imports messing up so much that same workspace appears twice and all requests/chaining gets messed up. Why would importing a workspace result in duplicate? and if it is duplicated, why it would mess up the original one too? Importing should be a clear choice between "fresh import" or "merge import".

**Comment by kreosus** [comment]
Hi @crimsonvspurple 
Have you tried this on our newest release, available here: https://github.com/Kong/insomnia/releases/tag/core%402022.5.0 to see if that resolves your issue? If not please let me know and I will proceed accordingly.

**Comment by crimsonvspurple** [comment]
I'm not seeing any specific change regarding this in latest release.

I use the git sync system that you have introduced for a while and it barely works I guess.

Because it can still mess up the workspace or not allow merge conflicts etc, I had to make the repo person write; others read to be safe.

You really should use one json file for each request so that git properly works.

**Comment by kreosus** [comment]
Hi @crimsonvspurple,

Thank you for reaching back out as to this issue. The issues that you have occurring should be going into a future released version, with no ETA at this time as to which version. These problems will be kept in mind when we re-architect the app. Thank you and have a nice day.

**Comment by jackkav** [comment]
@crimsonvspurple you'll be glad to know in the current beta we re-introduced multiwindow support, and have been working on fixing the issues with sync and import features. You're correct the old import and sync functionality had many problems, we are hoping we have dealt with them all by making import additive only and improving the UX of sync. If you have any more specific issues please open a new one. Thanks for your patience.
