### ISSUE TITLE
Git Sync clone not working on Windows

### ISSUE THREAD

**Issue by bagf** [getinsomnia/insomnia#2153]
**Describe the bug**
When pulling documents using Git Sync a `Error: ENOENT: no such file or directory` error is reported and nothing is updated. This appears to occur on Windows and not OS X.

**To Reproduce**
Quick steps:
1. Create -> Git Clone
2. Paste `https://github.com/bagf/pullcrash.git` into 'Git URI' field
3. Enter your author name and email 
4. Paste authentication token
5. Done

1. Create a 'Blank Document' called 'pullcrash'
2. Open pullcrash and go to debug
3. Create a new request 'My Request'
4. Click 'Setup Git Sync' -> Repository Settings
5. Paste in working Authentication Token, Git URI, Author name and email
6. Click Done
7. Click 'master' to bring up Git Sync menu
8. Click commit
9. Enter 'Testing' as the description and tick all 'Unversioned Objects'
10. Click Commit
11. Open Git Sync menu and Click push
12. Go back to 'Documents' screen and delete the pullcrash document
13. Create using 'Git clone'
14. Paste same details from step 5
15. Click Done

**Expected behavior**
The repository settings modal closes and my pullcrash document is promoted to be imported after cloning the pullcrash Git repository.

**Screenshots**
Committing all objects:
![tickall](https://user-images.githubusercontent.com/2567601/81556741-1e852180-938b-11ea-8502-5cf5f4535051.png)

Console log:
![console](https://user-images.githubusercontent.com/2567601/81557051-9e12f080-938b-11ea-91c0-62ee6bdc0f0e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1909 (OS Build 18363.815)
 - Installation Method: Git Release .exe
 - App Version v2020.1.3

**Additional context**
I don't know if it matters that much but i'm using Git 2.26.2-windows.1 locally and I **do not** have node js installed.

It seems committing and pushing works fine, but pulling results in:
```
bundle.js:250449 Uncaught (in promise) Error: ENOENT: no such file or directory, scandir '\\.insomnia\ApiSpec\'
    at MemPlugin._assertExists (bundle.js:250449)
    at MemPlugin._assertDir (bundle.js:250474)
    at MemPlugin.mkdir (bundle.js:250317)
    at FileSystem.mkdir (C:\Users\rory9\AppData\Local\insomnia-designer\app-2020.1.3\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:391)
    at FileSystem.mkdir (C:\Users\rory9\AppData\Local\insomnia-designer\app-2020.1.3\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:407)
```

**Comment by nijikokun** [comment]
The library we use doesn't rely on your local git so that shouldn't be affecting it. What scopes did you apply to the Access Token?

**Comment by nijikokun** [comment]
> What scopes did you apply to the Access Token?

Appears it's not a scope issue. Just tried using `read` scopes and I can replicate the issue.

![image](https://user-images.githubusercontent.com/198276/81624146-5059b080-93aa-11ea-8af7-ed545221989e.png)

**Comment by bagf** [comment]
I used the repo scope `Full control of private repositories` and the same token worked on OS X version of the app - thanks replying

**Comment by gschier** [comment]
It seems like this is breaking due to the extra slash we're appending in the file path. Unix seems to ignore these extra slashes, which is likely why it's only breaking on Windows.

![image](https://user-images.githubusercontent.com/587576/81988538-81c3bd80-95f0-11ea-8404-a99bf75b3ad4.png)

**Comment by luizxsoto** [comment]
> It seems like this is breaking due to the extra slash we're appending in the file path. Unix seems to ignore these extra slashes, which is likely why it's only breaking on Windows.

In my Windows PowerShell works, but not in Prompt.

![image](https://user-images.githubusercontent.com/37672408/82053452-c3597480-9693-11ea-9363-f43d20effdf5.png)

**Comment by develohpanda** [comment]
Adding some notes from my investigation 🔬 

Isomorphic-git internally does the path concatenation, and does not cater for double slashes. This also happens during cloning. https://github.com/Kong/insomnia/blob/08534699e73ad1a27640fab4a084620efc52c0df/packages/insomnia-app/app/ui/components/wrapper-home.js#L128-L130

Cloning at `dir = '/'` causes the double-slash issue reported in this issue;
Cloning at `dir = ''` defaults internally to `.`, causing another file-access related error (I wonder if this is `ne-db-plugin` related, and not filesystem related);
Cloning with `dir` not defined, causes a fatal error when `isomorphic-git` attempts to access it.

I'm still investigating this one further, but I think this is non-trivial.

I can successfully **clone** by setting the base directory to be, for example, `/base`. This however, fails to diff during commit. Looks like `ne-db-plugin.js` (which to my understanding, allows ne-db to behave as a filesystem for git 🤯) does not cater for a git sync directory where `.insomnia` is **not** the root. Updating that, seems to fix sync on Windows!

**Comment by develohpanda** [comment]
Looks like cloning is failing due to Windows and POSIX returning different results to the following code:
```js
const filePath = path.normalize('//.insomnia/ApiSpec/');
const dirName = path.dirname(filePath);
```

Windows returns `\\.insomnia\ApiSpec\`, while macOS returns `/.insomnia`. The key difference is between the directory name as opposed to the separator. `normalize` handles the double slash as expected on each OS, but `dirname` does not work with the normalized result.

This difference impacts the directory assertion, resulting in the `no such file or directory` error.

https://github.com/Kong/insomnia/blob/08534699e73ad1a27640fab4a084620efc52c0df/packages/insomnia-app/app/sync/git/mem-plugin.js#L186
