### ISSUE TITLE
Support "code_challenge" with OAuth2 Auth Code

### ISSUE THREAD

**Issue by sdc4** [getinsomnia/insomnia#2154]
**Support of "code_challenge" with OAuth2**
Hi, does Insomia support the Pkce "Code Challenge" Machanism with OAuth2 and the Auth Code Flow?

An error is returned, when Pkce is activated, without Pkce insomia can get the token.

Greetings
sdc4

**Comment by aesyondu** [comment]
I was looking for this as well. But if I'm not mistaken, this is already addressed in https://github.com/Kong/insomnia/issues/1653?
