### ISSUE TITLE
Show Dev Tools with ⌘⌥I  (⌃⇧I)

### ISSUE THREAD

**Issue by heptal** [getinsomnia/insomnia#2157]
Show Dev Tools with `⌘⌥I` (or `⌃⇧I`) like all the browsers do, and many Electron apps.

Also, it would be a nice if some level of smarter completion occurred when editing environment JSON - tabbing through the entries, auto-insert quotes, etc. Enter could append a new entry like:
```
{    ...
    "aKey": "aVal",
    "⎽": ""
}
```

**Comment by nicholasraphael** [comment]
I could give this a try if no one else is working on it. What part of the interface does "Dev Tools" refer to here? Additionally, should the last part of this issue about the autocomplete maybe be a separate feature request?

**Comment by nijikokun** [comment]
> What part of the interface does "Dev Tools" refer to here?

It's the built-in developer tools, you can access it through the OS Menu.

> Additionally, should the last part of this issue about the autocomplete maybe be a separate feature request?

Correct! My bad, that one snuck in. cc @heptal

**Comment by nicholasraphael** [comment]
Okay, thanks for clarifying. @nijikokun having trouble finding where the functionality for hotkeys goes. I've added new keys to `hotkeys.js` and also read the `hotkeys-listener.js`. Thanks for your help!

**Comment by nicholasraphael** [comment]
@nijikokun having trouble finding where the functionality for hotkeys goes. I've added new keys to hotkeys.js and also read the hotkeys-listener.js. Thanks for your help!

**Comment by nijikokun** [comment]
Do you mind opening a PR @nicholasraphael so we could review the code to better give feedback?

**Comment by nicholasraphael** [comment]
@nijikokun opened a [PR](https://github.com/Kong/insomnia/pull/2309)

**Comment by gschier** [comment]
Just a quick question @nicholasraphael. What are you needing the dev tools for in the production build? The hotkey _is_ actually enabled in the development version, when building from source but we chose to disable it for production, as we didn't find it very useful (although you can still open it from the View menu).

**Comment by nicholasraphael** [comment]
> Just a quick question @nicholasraphael. What are you needing the dev tools for in the production build? 

It seems this was the request from @heptal just to follow the convention of developer applications having this feature in production. However, if you guys think this is not something the product can benefit from then I haven't done too much work on it yet.
