### ISSUE TITLE
[BUG] Error due to mismatched key in specification is not handled by designer

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2158]
**Describe the bug**
When designing a Swagger 2.0 specification with a mismatched security key (such as `testKey` in the following example), no error is shown in Design view while the import fails when moving to Debug.

Here is an example specification. This is valid yaml, but invalid for a swagger definition.

<details>
<summary>Example</summary>

```yaml
swagger: "2.0"
info:
  version: 1.0.2
  title: Swagger Petstore
paths:
  /users:
    get:
      security:
        - key: []
        - testKey: []
      summary: Returns a list of users.
      produces:
        - application/json
      responses:
        "200":
          description: OK
securityDefinitions:
  key:
    type: "basic"
```
</details>

In editor.swagger.io, this is handled with the following error:
![image](https://user-images.githubusercontent.com/4312346/81614801-a96e2680-9434-11ea-89ce-9a390884e3fe.png)

While Designer does not currently show any error.

![image](https://user-images.githubusercontent.com/4312346/81614841-c145aa80-9434-11ea-9b48-05f520a2fcea.png)

**Expected behavior**
- Visual feedback about the invalid specification

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Installation Method: Dmg
 - App Version: 2020.1.3

**Additional context**
This is related to #2072.

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

**Comment by kreosus** [comment]
Hi @develohpanda,

We were not able to reproduce this error on [latest stable (2022.5.1)](https://github.com/Kong/insomnia/releases/tag/core%402022.5.1) and [latest beta (2022.6.0-beta.2)](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.2).

Are you by any chance able to reproduce with any of these other versions?

**Comment by kreosus** [comment]
closing to lack of activity
