### ISSUE TITLE
Openapi3 spec with empty item in security schema fails to import

### ISSUE THREAD

**Issue by hervehobbes** [getinsomnia/insomnia#2167]
**Describe the bug**
I can't import a Json OpenApi file.

**To Reproduce**
Hello,

I have an OpenApi Json file that generate an error when I try to import it in Insomnia Designer.
This file can be opened in Swgger Editor and this editor does not report any problem.
Here is the error message I have when I try to import the json file :
`
Import Failed
TypeError:
result.summary[_models_WEBPACK_IMPORTED_MODULE_11__.workspace.type]

Import failed
Cannot read property 'type' of undefined
`

For confidentiality reasons I cannot publish this JSON file here but I can send it to you by email.
**Expected behavior**
The file should be imported.

**Desktop (please complete the following information):**
 - Windows 10 Professional Version 10.0.18363 Number 18363
 - Installation via your website
 - App Version [e.g. v7.0.3]

**Comment by develohpanda** [comment]
Hi @hervehobbes! If you toggle devtools, do you see any errors in the console? 

That is unfortunately a fairly generic error (it's on the radar to improve the error output) - to help diagnose, could you please flick an email through to support@insomnia.rest with that specification and I or someone from the team will take a look. ☺️

**Comment by hervehobbes** [comment]
Hello,

Thank you very much for your answer.
Here is the error message I have from the console:

``
[ErrorModal] Cannot read property 'type' of undefined
``

And:

``
[ga] Event Modals, Show, ErrorModal
``

Ok for the email, it is going to be send now.

Bye

**Comment by develohpanda** [comment]
To summarize, the following case is not handled by the openapi3 importer. I'll update the issue title to reflect this. 😄 The following is a snippet from a fixture test within the codebase.

```yaml
openapi: '3.0.2'
info:
  title: Endpoint Security
  version: '1.2'
servers:
  - url: https://api.server.test/v1

components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic

paths:
  /none/basic:
    get:
      security:
        - {}		# causes failure
        - Basic: []
      responses:
        '200':
          description: OK
```

**Comment by hervehobbes** [comment]
Hello,

Thank you for your help ans answer.
I have a route that can be used with and without authentication, that's why
it is written like that.

Thanks again and bye,
Hervé


Le jeu. 14 mai 2020 à 01:58, Opender Singh <notifications@github.com> a
écrit :
