### ISSUE TITLE
Render Failure on incomplete `servers` spec

### ISSUE THREAD

**Issue by raptium** [getinsomnia/insomnia#2171]
**Describe the bug**

**To Reproduce**
1. Create a new document
2. Enter the following
```yaml
openapi: 3.0.0
servers:
  -
```
3. Wait a second
4. A modal dialog titled `Application Error` popped up and the document cannot be edited anymore

**Expected behavior**

Show errors and allow user to edit the document.

**Screenshots**

![image](https://user-images.githubusercontent.com/51584/81899798-36101480-95ee-11ea-8556-9cc643f2bb8e.png)

![image](https://user-images.githubusercontent.com/51584/81900173-e716af00-95ee-11ea-9d68-19255849b651.png)

**Desktop:**
 - OS:  macOS 10.15.3
 - Installation Method: downloaded from the site
 - Version 2020.1.3 (2020.1.3.3486)

**Comment by develohpanda** [comment]
Thanks for the report @raptium! We recently merged a fix (#2131) to catch this failure while rendering the preview. 🙂 

As far as I've experienced, it's only happening while _typing_ the servers section. If you're locked out of a document as a result of this, it will work with the next release.

**Comment by nijikokun** [comment]
Going to close this issue seeing that it has been implemented in #2131 and will be a part of the next release which is slated for next week ❤️ 

I've associated it with the milestone for that release as well.
