### ISSUE TITLE
Lack of feedback for connecting Insomnia Designer to github

### ISSUE THREAD

**Issue by jmccarrell-lmi** [getinsomnia/insomnia#2172]
**Describe the bug**
Lack of feedback for connecting Insomnia Designer to github, mainly where does one get the token for github? Which token is it?

Also, if you hit Done, nothing happens. No error, or feedback that you forgot the token or such. 

**To Reproduce**
1. Click on 'Create" on the top right
2. Click on 'Git Clone'
3. What does the token input represent?

**Expected behavior**
a help marker for the authentication token, perhaps linking to githubs documentation. A notification or any kind of text indicating what was incorrectly filled out in the "Configure Repository" form.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Installation Method: Download from website
 - App Version: Version 2020.1.3 (2020.1.3.3486)

**Comment by bartolomej** [comment]
Okay, so I added a basic tooltip with references to the official documentation for the most popular platforms.
![Screenshot 2020-08-15 at 13 52 55](https://user-images.githubusercontent.com/36109955/90311793-40002700-deff-11ea-8507-c8b8c149b064.png)

I will also try to make some improvements to the error messages.

**Comment by develohpanda** [comment]
Marking this as closed with #2517 - while smart notifications with _why_ auth failed are tricky (we recently added more logging in the console window to help, #2432), having docs about how to generate access tokens for each provider are a good alternative. The rest of the configure docs form is self-explanatory. 😄 🎉
