### ISSUE TITLE
It is possible to record REST requests from the browser?

### ISSUE THREAD

**Issue by icougil** [getinsomnia/insomnia#2173]
Hello,
I'm totally new to Insomnia, so first sorry if this questions was already answered, but I haven't found any question similar to this 😅.
Best and thank you in advance,

** Question **
I'd like to know, is there anything similar to [Postman interceptor](https://www.postman.com/product/postman-interceptor/) that any user can use to save some/all REST requests and save it into Insomnia while browsing the web with any browser. 

** Context **
For a team that could start from scratch for an existing application (or that they would like to create a new group of requests) it could be nice to be able create a new collection with some REST requests that could be performed just by browsing a particular website.

**Comment by filfreire** [comment]
Hi @icougil, thank you for reporting this issue, and sorry for not getting back sooner. We're currently going through old or unanswered issues.

Right now we don't have anything similar to Postman interceptor.

I hope I'm not mistaken, but there are no future plans of implementing this kind of capture/proxying/interceptor for Insomnia. There have also been [issues in the past around this topic](https://github.com/Kong/insomnia/issues/1579).

As a workaround for now you should be able to import curl or har exports that you capture via typical HTTP proxy tools, a few examples:
- https://www.charlesproxy.com/
- https://mitmproxy.org/
- https://www.telerik.com/fiddler

Side-note from personal experience these do a much better job at intercepting traffic.
