### ISSUE TITLE
Unable to access directory during install

### ISSUE THREAD

**Issue by dextermb** [getinsomnia/insomnia#2174]
**Describe the bug**
I've been using core for a good while now and thought I'd checkout designer, but I'm having issues installing using the `.deb` file.

During installation, I get this error, which exits the installation unsuccessfully.
```
chmod: cannot access '/opt/Insomnia Designer/chrome-sandbox': No such file or directory
```

**To Reproduce**
1. Download `.deb`
2. Run `dpkg`
3. See error

**Expected behavior**
The install would run successfully.

**Screenshots**
```
dexter@Raven:~/Downloads$ sudo dpkg -i Insomnia.Designer-2020.1.3.deb 
[sudo] password for dexter: 
Selecting previously unselected package insomnia-designer.
(Reading database ... 220006 files and directories currently installed.)
Preparing to unpack Insomnia.Designer-2020.1.3.deb ...
Unpacking insomnia-designer (2020.1.2) ...
Setting up insomnia-designer (2020.1.2) ...
chmod: cannot access '/opt/Insomnia Designer/chrome-sandbox': No such file or directory
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
```

**Desktop (please complete the following information):**
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by gschier** [comment]
Hmm, I get the same thing. I wonder if it's because there is a space in the path `/opt/Insomnia Designer/chrome-sandbox`?

**Comment by sudoflex** [comment]
Please fix your download links for **Designer** on Linux. They lead to nowhere. Whoever put out the blog post should check the links, esp. for Linux.

**Comment by hgfernan** [comment]
Dear all, I think that somehow the Insomnia installation scripts for Debian fail to provide the missing chrome-sandbox, either by providing it physically, or by finding links to it in a previously installed package.

But what would be the best temporary solution to this problem ?

For instance, I got chrome-sandbox under` /usr/share/code/chrome-sandbox` 

Should I do a symbolic link to it from /opt/Insomnia ?

Of course that won't repair the broken installation process. Should we tinker with the Debian installation scripts to correct the problem ? 

Or maybe it would be better to download the source code for Insomnia, compile it all and then fix manually the missing links ?

**Comment by jmoniatte** [comment]
Just hit this error and was able to fix it with:

```
sudo chmod 4755 /opt/Insomnia/chrome-sandbox
```

(If you try to launch insomnia with `./insomnia`, the console throws an error with instructions for fixing it)
