### ISSUE TITLE
[Feature request] Improve handling of user importing existing project from Git into empty document

### ISSUE THREAD

**Issue by peterskim12** [getinsomnia/insomnia#2181]
I didn't realize the proper way to import an existing workspace from Git into Insomnia was to select Create -> Import From Git Clone. The path I started with was Create -> Blank Document, then tried to set up Git Sync then do a pull, which returned this error:

![image](https://user-images.githubusercontent.com/1675548/81978557-b5571580-95f9-11ea-9fa8-9a81f071d7b6.png)

I know I'm not the only one who's done this before. :) 

I think we should assume this is a likely path a new user might take and either 1) return a more meaningful error and guide them to the right way to set up a project from a Git clone, 2) recognize user intent and just clone the Git repo into the empty doc, or 3) something else? Thanks!

**Comment by filfreire** [comment]
Hi @peterskim12 thanks for reporting this!

In latest versions of Insomnia you should now be able to create a blank/empty Design Document, and afterwards sync it with Git.

Feel free to re-open this issue if you are still having problems or report any other issues you come across.
