### ISSUE TITLE
Ability to remove pending changes with git sync

### ISSUE THREAD

**Issue by jonocairns** [getinsomnia/insomnia#2182]
**Is your feature request related to a problem? Please describe.**
I have an issue where I make some changes to saved endpoints but I wish to revert them as I've likely messed things up :trollface: 

**Describe the solution you'd like**
It'd be nice to have an option similar to `git checkout .` or even `git reset --hard` with a warning dialog before executing 

**Describe alternatives you've considered**
Not really sure this is possible to do other than recloning the repo

**Additional context**
Would be super useful to work out (or hammer fix) potential merge conflicts

**Comment by nijikokun** [comment]
Doh. Good idea.
