### ISSUE TITLE
OAuth2 Implicit with Google broken

### ISSUE THREAD

**Issue by meip** [getinsomnia/insomnia#2185]
**Describe the bug**
When using the implicit OAuth2 flow for our API I can not authenticated with my Google Account anymore. The following message appears after submitting the credentials:

> This browser or app may not be secure.[ Learn more](https://support.google.com/accounts/answer/7675428)
> Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

**To Reproduce**
1. Use a request using oAuth2
1. Use Google as the identity provider for sign in

**Expected behavior**
I think doing some adjustments in the included "browser" of Insomnia could help so that Google is accepting it as a trusted browser again. Or implement [browser-based OAuth](https://developers.google.com/identity/protocols/oauth2/native-app).

**Screenshots**
![image](https://user-images.githubusercontent.com/2386536/82037120-00c4fe80-96a2-11ea-9485-dc92eb4dd40e.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Installation Method: homebrew
 - App Version v7.1.1

**Comment by aeri** [comment]
I also have an issue with Implicit grant, the server returns that:

`{"error":"unsupported_grant_type","message":"The authorization grant type is not supported by the authorization server.","hint":"Check that all required parameters have been provided"}`

Using OAuth 2.0 with Implicit flow, as far as I know it's not necessary to specify `grant_type` the query. Implicit Flow example:

```
https://authorization-server.com/authorize?
  response_type=token
  &client_id=FGfL5iT2aiWzREZabTyO1JOc
  &redirect_uri=https://www.oauth.com/playground/implicit.html
```

App Version v7.1.1

**Comment by kinosang** [comment]
Got this error with 2020.5.2 on Windows 10 x64
Electron 9.1.1

**Comment by rocketraman** [comment]
Also with 2021.3.0, Electron 9.3.5. Will open a separate issue.
