### ISSUE TITLE
[FEATURE REQUEST] - Ability to set env variables as field from the json response

### ISSUE THREAD

**Issue by objque** [getinsomnia/insomnia#2189]
**Is your feature request related to a problem? Please describe.**
Recently I've migrate from the Postman to Insomnia. As a developer, I usually using REST clients for local test new changes in some api's and usually it's CRUD ops like post/patch/delete. This means after I've create some entity, I wanna to save it's **id** or another field to insomnia variable and use it in another requests. 

Now this is possible only by manually copying and pasting the field into each request.

**Describe the solution you'd like**
Ability to set some selected text from the response as value for a variable.

**Describe alternatives you've considered**
This feature already exists in postman.

<img width="430" alt="insomnia" src="https://user-images.githubusercontent.com/7000585/82198095-7defae00-9904-11ea-9deb-6856dbc4e48c.png">

<img width="737" alt="postman" src="https://user-images.githubusercontent.com/7000585/82198121-88aa4300-9904-11ea-8abe-d8ef0da7b709.png">

**Comment by smacktoid** [comment]
Have you read the [chaining requests](https://support.insomnia.rest/article/43-chaining-requests) page of the documentation?

It sounds like you want to use the body attribute tag to grab the id property from the response to another request, and use that as a URL, or attribute in the body of a new request.

In this image you can see the URL has been configured using this type of tag.

![insomnia-response-body-attribute](https://user-images.githubusercontent.com/3959288/82327564-7f89a680-99d6-11ea-90f2-0418d11537b2.png)

This image shows the config, where I've picked the @id attribute from another request. In this example I created the resource in that other request, and I'm using the @id from the response as the URL for my GET request.

![insomnia-response-body-attribute-config](https://user-images.githubusercontent.com/3959288/82327575-83b5c400-99d6-11ea-8e57-83541a70a9fc.png)

**Comment by hancockks** [comment]
As mentioned in https://github.com/Kong/insomnia/issues/217 there are lots of situations where setting an environment variable is superior to request chaining.  The reverse is also true, that request chaining can be more powerful and more intuitive in some cases.

However, I would like to see the ability to set an environment variable for one of the same reasons as mentioned in issue #217. I have a number of rest endpoints that will generate tokens in different methods that can be consumed by another rest endpoint.  Typically, I'll be testing endpoint A+C, then B+C. Request chaining would necessitate creating a separate entry for each chain.

**Comment by ilya-chumakov** [comment]
We considered Insomnia as Postman alternative (we are not satisfied with its pricing),  and the absence of runtime-set global variables was the main reason the proposition was put on hold for now, as our postman collections heavily rely on that feature.
