### ISSUE TITLE
Choose file window doesn't open & Insomnia freezes ❄

### ISSUE THREAD

**Issue by callebdev** [getinsomnia/insomnia#2193]
**Describe the bug**
`Choose File` window isn't opened when I chose file type data for multipart form, Insomnia freezes and nothing happens then.

**To Reproduce**
1. Get in `POST` request
2. Use `MULTIPART` as body type and
3. Add a field
4. Change the type to `"File"`
5. Then -> `Choose File`
Result: Insomnia freezes for couple seconds, then nothing happens.

**Expected behavior**
The window should be opened so that the user could choose a file in their system

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Installation Method: Download from the official site
 - App Version v7.1.1

**Additional context**
Thanks!

**Comment by paulocuambe** [comment]
Hi @callebdev . I don't know why this is happening but someone else reported a similar issue here #1982 . You should read the thread and consider closing this if necessary.

**Comment by callebdev** [comment]
Hi @paulocuambe, thanks for your attention! I'm not using the same computer anymore, so I cannot guarantee whether it has been fixed or no. But according to the issue #1982  seems that this error is not happening in all macOS computers, but some of them, near to `10.15.3` and `10.15.4` versions.

Thanks for mentioning my issue there!
Since I cannot reproduce this error anymore in order to provide a credible information, and there is a similar issue reported, I'll consider closing this one.

Be safe!
