### ISSUE TITLE
variable display bug

### ISSUE THREAD

**Issue by iiinsomnia** [getinsomnia/insomnia#2195]
**Describe the bug**
Expect:

![image](https://user-images.githubusercontent.com/6582246/82310045-73addc80-99f6-11ea-8610-fc42325ebaf4.png)

Actual:

![image](https://user-images.githubusercontent.com/6582246/82310180-a0fa8a80-99f6-11ea-849f-3c187443ab2b.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Installation Method: Download from the official website
 - App Version v7.1.1

**Additional context**

**Comment by develohpanda** [comment]
Hi @iiinsomnia! It looks like you have `Raw template syntax` enabled. If you **uncheck** this, it will show variables as the badge instead of `{{ base_url }}`.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/4312346/82498040-66eacf00-9b43-11ea-9bec-96b19eec01ca.png">
