### ISSUE TITLE
Cannot push to self-managed Gitlab private repository

### ISSUE THREAD

**Issue by msalegre** [getinsomnia/insomnia#2202]
**Describe the bug**
Cannot push to Gitlab repository

**To Reproduce**
1. Generate access token
![image](https://user-images.githubusercontent.com/10949598/82433591-f3d55000-9a91-11ea-98de-8388eb8fa8f6.png)

2. Fill form on insomnia designer
![image](https://user-images.githubusercontent.com/10949598/82433972-84ac2b80-9a92-11ea-959b-d916c70b4bc2.png)

3. Commit and post changes

![image](https://user-images.githubusercontent.com/10949598/82434104-b1604300-9a92-11ea-883a-619f72c9f8a6.png)

**Expected behavior**
Should be able to push 

**Screenshots**
Available scopes on gitlab 12.5.4-ee (differs from !2138)
![image](https://user-images.githubusercontent.com/10949598/82445485-2b99c300-9aa5-11ea-92a7-f4352d6704f5.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Installation Method: dmg
 - App Version: 2020.1.3
 - Gitlab version: 12.5.4-ee

**Comment by develohpanda** [comment]
Hi! Looks like there's an existing auth issue with Gitlab sync and https://github.com/Kong/insomnia/pull/2162 fixes it. This will be out in the next release of Designer. 😊
