### ISSUE TITLE
Null Ingress Path When Generating from Spec

### ISSUE THREAD

**Issue by doctorwu** [getinsomnia/insomnia#2205]
The `generateFromSpec` call creates a null path in certain situations when using kong-for-kubernetes. Attached are two specs, one works and the other doesn't. The delivery-api-service.json is the file that creates a null path. The orders.yaml works as expected.

[o2k.zip](https://github.com/Kong/insomnia/files/4657585/o2k.zip)

**Comment by develohpanda** [comment]
Thanks for reporting! This was recently fixed by https://github.com/Kong/insomnia/pull/2136 and should be included in the next release. 😊
