### ISSUE TITLE
Install plugin, empty box

### ISSUE THREAD

**Issue by jackkav** [getinsomnia/insomnia#2208]
**Describe the bug**
handle empty input when clicking install plugin
**To Reproduce**
install, skip, preferences, plugins, install plugin
**Expected behavior**
Nicer message pointing to https://insomnia.rest/plugins/ to get the package names?
**Screenshots**
![image](https://user-images.githubusercontent.com/3679927/82673096-954ed400-9c41-11ea-95f2-0d722e9f0160.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Installation Method: homebrew
 - App Version v202.1.3

**Comment by nicholasraphael** [comment]
Hey, I'm new and think this looks like a good issue to start and contribute to. If this is not claimed I would like to give this a try.

**Comment by nicholasraphael** [comment]
Added what could be considered a nicer message on error. Someone can review the [PR](https://github.com/Kong/insomnia/pull/2238)
