### ISSUE TITLE
Nowhere to login to Teams Plus account

### ISSUE THREAD

**Issue by jrobinson-efirst** [getinsomnia/insomnia#2209]
After a fresh install of Insomnia Designer on both Mac and Linux, there appears to be nowhere to login to our Teams Plus accounts.

Where do you sign in on Insomnia Designer? I've found where to login on Insomnia Core but I can't find anything on Designer.

**Comment by tcox-enrollfirst** [comment]
Thought I could try to log out and back in, but I also can not for the life of me find anywhere to log out of my account.  Am I missing something?

**Comment by nijikokun** [comment]
Insomnia Designer does not currently support any paid functionality yet.
