### ISSUE TITLE
I can't start app on Manjaro

### ISSUE THREAD

**Issue by porcarelliandrea** [getinsomnia/insomnia#2214]
**Describe the bug**
I can't start app on Manjaro distro. I can't see error on error_logs

**Desktop (please complete the following information):**
CPU: Quad Core Intel Core i7-8650U (-MT MCP-) speed/min/max: 800/400/4200 MHz Kernel: 5.6.11-1-MANJARO x86_64 Up: 57m 
Mem: 5374.7/15893.3 MiB (33.8%) Storage: 476.94 GiB (19.7% used) Procs: 325 Shell: bash 5.0.16 inxi: 3.0.37 

My version Insomnia is:
installed:          7.1.1                      (62) 63MB -

**Comment by porcarelliandrea** [comment]
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
[fix] Running database repairs
[db] Initialized DB at /home/andrea/snap/insomnia/62/.config/Insomnia/insomnia.$TYPE.db
Init responses DB
[localstorage] Initialized at /home/andrea/snap/insomnia/62/.config/Insomnia/localStorage
Rilevato trace/breakpoint (core dump creato)

**Comment by reynolek** [comment]
This appears to be a snap packaging issue. As a work around, perhaps you could try the tarball, or if you have the ability to install from arch linux user repository, you can install it from there (my knowledge of Manjaro is highly limited, so not sure if its possible).

**Comment by tebruno99** [comment]
I found this issue in snapd mentioned in other projects:
snapcore/snapd#7129
IsmaelMartinez/teams-for-linux#175

Where do we get the tarball ? Having a really hard time finding any release other than AppImage and snap instructions on the main site.

**Comment by rlueder** [comment]
@tebruno99 https://github.com/Kong/insomnia/releases/ has all downloads listed

**Comment by kreosus** [comment]
Hi @porcarelliandrea,
Good day and I hope that all is well. Have you tried to use our newest release located here: https://github.com/Kong/insomnia/releases/ I hope that this better assists you and have a nice day.
