### ISSUE TITLE
Implementation of Atlassian ASAP Auth doesn't match the spec

### ISSUE THREAD

**Issue by Gangezilla** [getinsomnia/insomnia#2219]
**Describe the bug**
Hi there! According [to the spec for ASAP](https://s2sauth.bitbucket.io/spec/), you should be able to pass an array of values for the 'audience' field. I've bolded the relevant section from the spec here: `“aud”: audience, as defined by JWT, with the difference that here it is mandatory. Note that the value of this claim may be a single string value **or an array of string values**`. Currently the value is passed as a string, as seen here https://github.com/Kong/insomnia/blob/7bc219422efe14054723c70d097ec53410db989c/packages/insomnia-app/app/ui/components/editors/auth/asap-auth.js#L64 

**To Reproduce**
1. Create a new request
2. Select 'Atlassian ASAP' in the Auth dropdown
3. Fill in a value or series of values. I've tried values like `audience1 audience2`, `[audience1, audience2], `["audience1", "audience2"]`, `audience1, audience2`
4. If you look at the values that get created the token, you'll see that the audience field is a string.

```
{
  iss: 'issuer',
  sub: 'sub',
  aud: 'audience1 audience2',
  jti: '98uhj9889j9889',
  iat: 123123123123,
  exp: 123123123123
}
```

**Expected behavior**
As described in the spec, the audience field should look like `["audience1, "audience2"] instead of "audience1 audience2"

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.15.4]
 - Installation Method: [Download from website](https://insomnia.rest/download/#mac)
 - App Version v7.1.1

**Comment by kreosus** [comment]
Hi @Gangezilla 
Have you been able to reproduce this error from our newest release located here: https://github.com/Kong/insomnia/releases

**Comment by kreosus** [comment]
closing to lack of activity
