### ISSUE TITLE
Bitbucket Server personal access tokens support

### ISSUE THREAD

**Issue by DrMetallius** [getinsomnia/insomnia#2221]
**Is your feature request related to a problem? Please describe.**
Currently it's impossible to work with Bitbucket Server personal tokens. In the version 2020.1.3 it's simply impossible to authenticate with Bitbucket Server as the only option is the tokens which aren't passed correctly to the server. In the version 2020.1.4-alpha.1 it's better since at least I have the option of filling out my login and password in the token field. However, there is still no option to just use personal access tokens.

**Describe the solution you'd like**
Personal access tokens for Bitbucket Server are supported and correctly passed to the server.

**Additional context**
[Atlassian Documentation](https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html) suggests that these tokens are supposed to be passed as bearer tokens, not as a part of basic authentication. However, Insomnia doesn't seem to support this use case.

**Comment by 4n70w4** [comment]
The same issue

**Comment by nijikokun** [comment]
@4n70w4 were you able to at least get it working with your login and password for the time being?

**Comment by RobertWi** [comment]
Same issue here. Insomnia.Designer-2020.4.1 only allows for token. I'm unable to get it working with user/pw
