### ISSUE TITLE
Custom SSL certificate support for git integration

### ISSUE THREAD

**Issue by DrMetallius** [getinsomnia/insomnia#2222]
**Is your feature request related to a problem? Please describe.**
In our company we have a corporate SSL certificate used for our intranet resources. This makes it impossible to use git integration in Insomnia, which, as I assume, uses bundled certificates.

**Describe the solution you'd like**
A perfect solution would be to either pick up the certificates from the system, or at least provide a way to specify them in the application preferences.

**Describe alternatives you've considered**
Right now the only way I managed to bypass these restrictions is by setting the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable to `0`, but this is hardly a convenient and secure solution. This is obviously one the major blockers for adopting Insomnia Designer.

**Comment by nijikokun** [comment]
Welcome @DrMetallius 

Great point, I'm sure other corporations have similar setups, looking into it seems like we will have to use a [custom http agent](https://isomorphic-git.org/docs/en/http) for our git integration.
