### ISSUE TITLE
Changing branches does not update contents of the spec editor

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2224]
**Describe the bug**
Changing branches does not change the contents of the code editor in design

**To Reproduce**
1. Commit a specification while on the master branch
2. Create a new branch
3. Commit changes to the specification on the new branch
4. Switch branches (from the drop-down or branches modal)
5. Observe no change to the editor
6. Reopen the document to see the new contents

**Expected behavior**
The code editor should update to show the updated specification

**Screenshots**
![2020-05-28 11 30 34](https://user-images.githubusercontent.com/4312346/83082366-586a5d80-a0d7-11ea-8231-41fb6b344e5f.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Installation Method: Dev
 - App Version: https://github.com/Kong/insomnia/commit/877a2a17254ff0d6457221a01e5cd63cfe04f1d5

**Comment by develohpanda** [comment]
This is the cause: https://github.com/Kong/insomnia/blob/877a2a17254ff0d6457221a01e5cd63cfe04f1d5/packages/insomnia-app/app/ui/components/codemirror/code-editor.js#L116-L128

**Comment by nijikokun** [comment]
Nice catch, I noticed this while working on a spec and thought it was just me.

**Comment by develohpanda** [comment]
There is a more significant issue here; updating a branch does not update all items as it should (I think this is only related to UI). 🤔 

This is a little tricky to follow, but notice how the JSON value is completely out of sync with the branch... it fixes itself when forced to re-render (ie. switching to a different request and coming back).

![2020-06-01 14 04 27](https://user-images.githubusercontent.com/4312346/83369639-26c40000-a411-11ea-97cb-8831e1b8a080.gif)

Each time I switch branches (with no pending changes), the console reports it has dropped db changes, which also feels wrong.

![image](https://user-images.githubusercontent.com/4312346/83369820-9e922a80-a411-11ea-807d-74803faa1f83.png)
