### ISSUE TITLE
GitLab Sync

### ISSUE THREAD

**Issue by pori4ka** [getinsomnia/insomnia#2225]
**Describe the bug**
Can't sync via GitLab

**To Reproduce**
1. Set Gitlab personal access token
2. Copy token
3. Get the authentication error message
```
HTTPError: HTTP Error: 401 Unauthorized
    at Function.discover (/Applications/Insomnia Designer.app/Contents/Resources/app.asar/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:6481:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Expected behavior**
Can be sync with Gitlab repository

**Desktop (please complete the following information):**
 - macOS 10.14.6
 - Installation Method: dmg package
 - App Version 2020.1.3 (2020.1.3.3486)

**Additional context**
I've seen that it was already fixed in https://github.com/Kong/insomnia/issues/2138, but I still getting the error.

**Comment by reynolek** [comment]
Hey @notaeugene! We have this bug currently fixed from https://github.com/Kong/insomnia/issues/2202 -- This will be released in the next version of Designer, which is coming out very soon!

**Comment by pori4ka** [comment]
@reynolek Thank's for a such fast reply 👍 Ok, I got it. Will be waiting so much)

**Comment by anildigital** [comment]
@reynolek When is the next version coming out? I am using `Version 2020.3.3 (2020.3.3)` and this issue exists.

**Comment by reynolek** [comment]
@anildigital Give 2020.4.0 a shot, it was released this week.

If it still persists, please open a new issue with the details of what you are seeing.

**Comment by reynolek** [comment]
@anildigital Checking in -- Have you tried out 2020.4.0?
