### ISSUE TITLE
Enum variables become undefined if changed to environment variable and back

### ISSUE THREAD

**Issue by k-aziz** [getinsomnia/insomnia#2235]
**Describe the bug**
Enums become undefined when input type is changed to an environment variable and then changed back to the static variable.

When the variable is changed back to a static variable, the live preview displays an error (see below) and the plugin does not run until the enum value is changed.

Once the enum is changed, the value becomes undefined.

**To Reproduce**

Tested using insomnia-plugin-rsa-encrypt

Step 1 - Initialise the plugin with a public rsa key and value to encrypt. Set the "Function" enum to "Encrypt".

<img width="437" alt="Screenshot 2020-06-02 at 11 34 01" src="https://user-images.githubusercontent.com/25666527/83510632-3c92fd00-a4c5-11ea-8e29-ba6381b42c9b.png">

<img width="549" alt="Screenshot 2020-06-02 at 11 33 02" src="https://user-images.githubusercontent.com/25666527/83510811-8976d380-a4c5-11ea-9d52-2e3fd4b81919.png">

Step 2 - Change the Enum input type to environment variable

<img width="442" alt="Screenshot 2020-06-02 at 11 37 09" src="https://user-images.githubusercontent.com/25666527/83510920-b925db80-a4c5-11ea-96ec-fed03227e0b2.png">

The live preview of undefined is expected here, but the variable fn is still correct as it is the value of the environment variable.

Step 3 - Change the Enum input type back to Static Value

The plugin does not run even if you change the values in the RSA Key or Value fields and an error is displayed in the live preview.

<img width="427" alt="Screenshot 2020-06-02 at 11 24 16" src="https://user-images.githubusercontent.com/25666527/83511395-7c0e1900-a4c6-11ea-8f25-e4ed927133f4.png">

The plugin does run, however, once you change the value of the enum. In this case, changing from the default "Encrypt" to "Decrypt". This then shows the value of "fn" as undefined, whereas it should be "DECRYPT".

<img width="566" alt="Screenshot 2020-06-02 at 11 48 39" src="https://user-images.githubusercontent.com/25666527/83512731-90ebac00-a4c8-11ea-89ef-fe981fe246fc.png">

The plugin does not work properly again unless "Function to Perform" is changed to a different plugin and back, which I assume resets it.

**Expected behavior**
The value of the enum passed to the plugin should not be undefined when switched to an environment variable and then back to a static value.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Installation Method: Installer
 - App Version: 2020.2.0

**Comment by gschier** [comment]
Thanks for the detailed explanation! It looks like this is a problem in the Template Tag edit dialog. Switching the input back to "Static Value" isn't actually updating the underlying tag.

I've reproduced this using the built-in Base64 tag. It looks like the quotes are not being added back after switching from "Environment Variable" to "Static Value".

```shell
# Default tag output
{% base64 'encode', 'normal', 'testing' %}

# Change "Kind" input to "Environment Variable"
#   Env used: { "foo": "bar" }
{% base64 'encode', foo, 'testing' %}

# Change "Kind" back to "Static Value"
#   Nothing changes. It *should* be replaced by the quoted value 
#   of foo: 'bar'
{% base64 'encode', foo, 'testing' %}

# Select different "Kind" option from dropdown
#   Change, but quotes are missing, causing it to error looking for
#   variable with name `normal`
{% base64 'encode', normal, 'testing' %}
```
