### ISSUE TITLE
No response found - No responses show up but request goes through

### ISSUE THREAD

**Issue by nataliamelissas** [getinsomnia/insomnia#2237]
**Describe the bug**
A "No response found" log is printed in the console whenever I send any request (Error "No responses for request"). The response section still flashes "Loading..." but it says the response is never received or updated. I know the request is valid though, plus the console shows response status codes.

**To Reproduce**
Things broke after I enabled the plugin system and installed four plugins (default headers, faker, response eval, and save access token). I'm not sure at what point it happened after or during that because I tried out the plugins for a couple of requests and it was fine. 

Out of nowhere, requests stopped working. After deleting the plugins and restarting this issue persisted. I updated to version 2020.2.0 today which didn't help.

Steps to reproduce the behavior (from what I remember):
1. Install the plugins mentioned above and use them (set an environment variable to a Response=BodyAttribute using a function from plugin response-eval.
2. Open the developer console. Send a request that you know works.
3. See the response and console logs.

**Expected behavior**
A regular response.

**Screenshots**
This is when using an invalid bearer token (status code = 401)
<img width="1656" alt="Screen Shot 2020-06-02 at 12 35 33 PM" src="https://user-images.githubusercontent.com/16572690/83556688-9697c080-a4cd-11ea-9a6d-15cd12c734e3.png">

This is with a valid bearer token (200)
<img width="1656" alt="Screen Shot 2020-06-02 at 12 40 58 PM" src="https://user-images.githubusercontent.com/16572690/83557264-951ac800-a4ce-11ea-9e27-e88c10f6a9e7.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.15.1]
 - Installation Method: homebrew (original) and dmg (when updated)
 - App Version v7.1.1 (original) and 2020.2.0 (after update)

**Comment by gschier** [comment]
Hi @nataliamelissas,

It looks like the Response tag is failing to find any responses. Can you check in the app to see if there are any responses visible in the request that it's referencing?

**Comment by nataliamelissas** [comment]
@gschier 
I'm actually not using a template tag of any sort for the particular request shown in the screenshots. I was originally (4 days ago) when it stopped working, but removed it to see if that causing it. 

The example GET request only has a URL and manually inserted Authorization header.

**Comment by gschier** [comment]
@nataliamelissas do you have one in your environment? That would also affect things.

**Comment by nataliamelissas** [comment]
> @nataliamelissas do you have one in your environment? That would also affect things.

Oh okay, I did have one in my environment which I removed. The console prints out less now but I still don't see the response preview.

<img width="1678" alt="Screen Shot 2020-06-03 at 3 22 31 PM" src="https://user-images.githubusercontent.com/16572690/83690526-24e37380-a5ae-11ea-955c-a0ba41886ead.png">

<img width="1270" alt="Screen Shot 2020-06-03 at 3 27 45 PM" src="https://user-images.githubusercontent.com/16572690/83690905-ce2a6980-a5ae-11ea-8832-9d40663e9ea7.png">

**Comment by gschier** [comment]
This is a bit of a long shot, but can you try clearing all responses for your workspace from the workspace settings dialog? 
![image](https://user-images.githubusercontent.com/587576/83694707-7dfed780-a5ad-11ea-9b8e-106aaefcd8a8.png)

Also, can you let me know if you have the "filter responses by environment" setting enabled?
![image](https://user-images.githubusercontent.com/587576/83694756-92db6b00-a5ad-11ea-964f-64a6bb57a6df.png)

**Comment by nataliamelissas** [comment]
I cleared all the responses but the problem is still there. :/
Yes, I have the "filter responses by environment" setting enabled.

**Comment by gschier** [comment]
And the problem is still there even after disabling it?

**Comment by nataliamelissas** [comment]
That worked! Interesting because I never changed the workspace settings. Also, this particular workspace only has a Base Environment.

**Comment by gschier** [comment]
I think there was a release in the past that enabled that setting by default, but has since been reverted. Thanks for your help debugging this issue. That should narrow it down enough to figure out what the problem is 👍

**Comment by coladarci** [comment]
Many apologies for rehashing an old thread!

But I found this because I've been banging my head against the wall with this problem for a long time and interestingly the fix was similar but the complete opposite - UNCHECKING this made things suddenly work. Just in case it can help someone else.. button mash that setting and cross your fingers...

<img width="278" alt="image" src="https://user-images.githubusercontent.com/1004167/224561311-9e842c81-f32f-4ece-9fa6-125ddb2b1c0a.png">
