### ISSUE TITLE
Template tags result in JSON Parse error when used as number

### ISSUE THREAD

**Issue by JohannesMP** [getinsomnia/insomnia#2241]
**Describe the bug**
Sorry if this is a duplicate of an existing issue. This issue is related to https://github.com/Kong/insomnia/issues/973 but with a JSON body instead of a Query.

In my case I'm attempting to send a POST request to API that requires time to be provided as a number and not a string. If I use CTRL+Space and select the Unix Timestamp tag, the query correctly sends but the JSON parser will have an error due to the template syntax not being valid json.

For example:

```
[
	{
		"name": "blah",
		"interval": 10,
		"value": 100,
		"time": {% now 'unix', '' %}
	}
]
```

Results in this parse error:
![image](https://user-images.githubusercontent.com/662874/83575855-43316c80-a4e5-11ea-8e89-f1b5f4fa828d.png)

Is pre-evaluating Template tags before the string is passed to the linter at all an option, or would that be dangerous/slow? I can see how for very large bodies with lots of tags that could be slow since the linter might run every time you make a change.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: Download from Website
 - App Version:
![image](https://user-images.githubusercontent.com/662874/83576019-9efbf580-a4e5-11ea-872e-4ce5c7c7e41b.png)

**Additional context**

**Comment by kavithamadhavaraj** [comment]
Hi @JohannesMP ,

I'm also stuck due to this, were you able to find a workaround?

**Comment by DrompiX** [comment]
Hey @JohannesMP , just try to enclose the template tag inside double quotes. It works for me just fine in `Insomnia v2021.2.2`.
![image](https://user-images.githubusercontent.com/17478824/114872602-29e69580-9e03-11eb-95ba-053fe440fc5a.png)

**Comment by develohpanda** [comment]
This may be possible by extending the linting logic to accept template tag syntax (that's already done for a separate use-case [here](https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/ui/components/codemirror/lint/javascript-async-lint.js) but it seems like a fairly complex approach.

If it suits, for now I suggest wrapping your template tag in double-quotes to make it valid JSON as described in a comment above!

**Comment by solocommand** [comment]
+1 for this issue, in my use case the JSON data is validated and cannot be enclosed in quotes:
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/1778222/154725278-7111f8ad-c8f1-4eec-b0c3-a6442701eb0f.png">
