### ISSUE TITLE
Core Dump on Arch Linux

### ISSUE THREAD

**Issue by iveelsm** [getinsomnia/insomnia#2246]
**Describe the bug**

After installing the Insomnia snap, via `sudo snap install insomnia` per the documentation. It will fail to start on some systems and result in a core dump. The AppImage does not have this problem.

**To Reproduce**
1. sudo snap install insomnia
2. insomnia

**Expected behavior**

I would expect the app to start normally. Like it does with the AppImage.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.6.15-arch1-1
 - Installation Method: snap
 - App Version: Unknown, but recent

**Additional context**

`$ coredumpctl info`

```
           PID: 128025 (insomnia)
           UID: 1000 (iveelsm)
           GID: 1000 (iveelsm)
        Signal: 5 (TRAP)
     Timestamp: Tue 2020-06-02 20:55:54 MDT (11h ago)
  Command Line: /snap/insomnia/62/insomnia
    Executable: /snap/insomnia/62/insomnia
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (iveelsm)
       Boot ID: 9427af5b1c724002aacb7d9b9e1f7aa5
    Machine ID: 58b909b09b654019949dfe020abf39ab
      Hostname: frogman
       Storage: /var/lib/systemd/coredump/core.insomnia.1000.9427af5b1c724002aacb7d9b9e1f7aa5.128025.1591152954000000000000.lz4
       Message: Process 128025 (insomnia) of user 1000 dumped core.
                
                Stack trace of thread 128025:
                #0  0x0000000003f7684f n/a (/snap/insomnia/62/insomnia + 0x3d7684f)
                #1  0x0000000003f7778b n/a (/snap/insomnia/62/insomnia + 0x3d7778b)
                #2  0x0000000003f6c653 n/a (/snap/insomnia/62/insomnia + 0x3d6c653)
                #3  0x0000000003f6c53e n/a (/snap/insomnia/62/insomnia + 0x3d6c53e)
                #4  0x0000000003f7f494 n/a (/snap/insomnia/62/insomnia + 0x3d7f494)
                #5  0x0000000003f7cb7f n/a (/snap/insomnia/62/insomnia + 0x3d7cb7f)
                #6  0x0000000003ec6e29 n/a (/snap/insomnia/62/insomnia + 0x3cc6e29)
                #7  0x0000000003ed87ff n/a (/snap/insomnia/62/insomnia + 0x3cd87ff)
                #8  0x0000000003eccf66 n/a (/snap/insomnia/62/insomnia + 0x3cccf66)
                #9  0x0000000003ef6c03 n/a (/snap/insomnia/62/insomnia + 0x3cf6c03)
                #10 0x0000000004b46507 n/a (/snap/insomnia/62/insomnia + 0x4946507)
```

**Comment by gschier** [comment]
The Snap image has never been very reliable, unfortunately. I suggest trying out the AUR package instead: https://aur.archlinux.org/packages/insomnia/

**Comment by iveelsm** [comment]
@gschier I was able to get it working with [the AppImage](https://support.insomnia.rest/article/23-installation#linux). 

But I just wanted to open this as just as FYI.

**Comment by gschier** [comment]
Thanks! I appreciate it 💯

**Comment by iveelsm** [comment]
@gschier Do you think we should just close this? It seems out of scope. The workaround (using the AppImage) seems to be well understood. So I think we should be good right?

**Comment by wdawson** [comment]
@iveelsm 👋 I'm going to go ahead and close this since you're happy enough with the workaround. 

Feel free to open a Discussion in the Ideas category if you (or anyone else who stumbles upon this issue) would rather see a better solution.

**Comment by iveelsm** [comment]
@wdawson Sounds good! I think the `AppImage` is a better approach anyways. :)
