### ISSUE TITLE
OpenSSL SSL_read: Connection was reset, errno 10054

### ISSUE THREAD

**Issue by DnlCYan** [getinsomnia/insomnia#2251]
Hi!

Today with insomnia latest versions 2020.2.1 I'm getting this error invoking our own REST API:
**OpenSSL SSL_read: Connection was reset, errno 10054**

I don't know when it has updated, but at the beginning of this week, it was working well.

Our API is located at Azure Cloud and I tried different API that we have.
If I call this same API running on my local machine, I got success.

Finally, I downgraded Insomnia for 7.1.1 version, and it started to work again.

So something new at Insomnia latests versions that don't work well invoking API located at Azure infrastructure.

Pasting timeline call:
* Preparing request to https://xxxx.azurewebsites.net:443/api/v1/territories
* Using libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0
* Current time is 2020-06-05T13:28:20.922Z
* Disable timeout
* Enable automatic URL encoding
* Disable SSL validation
* Enable cookie sending with jar of 2 cookies
* Uses proxy env variable no_proxy == '192.168.99.100'
*   Trying x.x.x.x:443...
* Connected to xxxx.azurewebsites.net (x.x.x.x) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:\Users\.......\AppData\Local\Temp\insomnia_2020.2.1\2017-09-20.pem
*   CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.azurewebsites.net
*  start date: Sep 24 02:18:56 2019 GMT
*  expire date: Sep 24 02:18:56 2021 GMT
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 5
*  SSL certificate verify ok.

> GET /api/v1/territories HTTP/1.1
> Host: xxxx.azurewebsites.net
> User-Agent: insomnia/2020.2.1
> Cookie: ARRAffinity=8f8ac6c076f7a9e2132f...
> Authorization: Bearer eyJhbGciOiJSUzI1N...

* OpenSSL SSL_read: Connection was reset, errno 10054
* Closing connection 1

**Comment by wjj28** [comment]
Execute the git command: release ssl verification:
git config --global http.sslVerify "false"

**Comment by kreosus** [comment]
Hi @DnlCYan 
Do you see the same behavior with our latest release located here: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.4

**Comment by DnlCYan** [comment]
@kreosus I have to say that more than 2 years later, I can't recall what were the right steps to reproduce this error.
Though I add that today I'm using Insomnia 2022.5.1 version and I don't have any problem to call this endpoint at Azure.

Thank you for the attention.

**Comment by care198475II** [comment]
> Execute the git command: release ssl verification: git config --global http.sslVerify "false"

well done by this answer, note just type below in git bash interface:

git config --global http.sslVerify "false"

**Comment by EvanHong99** [comment]
For me, it looks like an network issue. I solved this problem several minutes later without changing anything.
