### ISSUE TITLE
Feature Request: ability to expand or collapse all JSON nodes

### ISSUE THREAD

**Issue by NSExceptional** [getinsomnia/insomnia#2252]
When you want to look at the last object in a JSON response, for example, it can be tedious to collapse 50+ objects by hand to get to the last one. Having the ability to collapse the entire response and navigate to where you want to go by expanding specific nodes one at a time can be much faster than collapsing a dozen nodes to get there, or scrolling and reading.

At the least, I would like to have shortcuts added for "expand/collapse all" in the response. Ideally, I'd also like to be able to right click on any node and have an "expand/collapse children" option available as well.

Alternatives considered: I could scroll to the bottom, but shortcuts or options for collapsing would be much faster, and scrolling to the bottom is only feasible when I happen to be looking at the last object in the response. Auto-collapsing is also useful if you want to look at a particular object in the middle of the response or something.

This is not my screenshot, but may be helpful in case what I was referring to was unclear:
![Screenshot](https://user-images.githubusercontent.com/38257723/58696569-802dc500-83a0-11e9-86f6-883edba8f3ed.png)

**Comment by develohpanda** [comment]
Looks like there are `foldAll` and `unfoldAll` operations exposed by CodeMirror that we can use.

https://github.com/codemirror/CodeMirror/blob/84a02bcec14a66f6ae6ca102078cb2dc6afd6349/addon/fold/foldcode.js#L98-L115

These can be added as keyboard shortcuts as well, [for example](https://stackoverflow.com/a/50952541).

**Comment by codeater7** [comment]
Any updates on this ??
