### ISSUE TITLE
Address occaisional race conditions when updating database models

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2253]
See description in #2231 for an example of where a race condition arises.

**Comment by kreosus** [comment]
Hi @develohpanda 

Have you been able to reproduce this error on [latest stable (2022.5.1)](https://github.com/Kong/insomnia/releases/tag/core%402022.5.1) and [latest beta (2022.6.0-beta.2)](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.2).

Are you by any chance able to reproduce with any of these other versions? Thank you.
