### ISSUE TITLE
Insomnia is unable to get OAuth2.0 tokens from Ory Hydra authorization sever

### ISSUE THREAD

**Issue by hsanson** [getinsomnia/insomnia#2254]
**Describe the bug**
Insomnia is unable to fetch OAuth2.0 tokens from [Ory Hydra](https://www.ory.sh/hydra/) authorization server.

Insomnia follows the [Hydra login and cosent](https://www.ory.sh/hydra/docs/login-consent-flow/) flow until Login part. After submitting the login form with valid credentials, insomnia hits the /oauth2/auth endpoint but for some reason it gets a "forbidden" response and the flow stops.

Using [OAuth debugger](https://oauthdebugger.com/) or [Postman](https://postman.com)  works just fine with the same Hydra server. Note that Postman also gets the same error as insomnia but it has an option to use external web browser that does work fine.

**To Reproduce**
1. Install [docker](https://docs.docker.com/get-docker/) to start local Hydra instance.

2. Start a local instance of Hydra Authorization Server

```
docker run --name "hydra" --rm \
    -p 4444:4444 \
    -p 4445:4445 \
    -e DSN=memory \
    -e URLS_SELF_ISSUER=http://localhost:4444 \
    -e URLS_CONSENT=http://localhost:9020/consent \
    -e URLS_LOGIN=http://localhost:9020/login \
    oryd/hydra:v1.5.0-beta.5 serve all --dangerous-force-http
```
3. Create a test OAuth2.0 client in the Hydra instance

```
docker exec hydra hydra clients create --endpoint http://127.0.0.1:4445 \
  --id test --secret secret --grant-types authorization_code,refresh_token \
  --response-types code,id_token --scope openid,offline_access \
  --audience mobile,web --token-endpoint-auth-method none \
  --callbacks https://oauthdebugger.com/debug
```

4. Start local instance of login/consent sample app

```
docker run --rm --name hydra-consent \
  -p 9020:3000 \
  -e HYDRA_ADMIN_URL=http://hydra:4445 \
  -e NODE_TLS_REJECT_UNAUTHORIZED=0 \
  --link hydra \
  oryd/hydra-login-consent-node:v1.3.2
```
5. Configure Insomnia OAuth2.0 auth as shown in the figure:

![image](https://user-images.githubusercontent.com/900716/83943410-ce3c9a80-a836-11ea-843b-7dd122d464f7.png)

**Expected behavior**

After filling and submitting the login form with correct credentials a consent form should be shown and accepting these should open a browser with oauth debugger with success message and OAuth2.0 code.

Instead Hydra returns a forbidden error shown in the error message in insomnia and the flow stops.

With the same exact configuration doing the flow using [OAuth debugger](https://oauthdebugger.com/)  works fine and shows the success screen:

![image](https://user-images.githubusercontent.com/900716/83943581-317afc80-a838-11ea-9301-c02ad687a836.png)

**Desktop (please complete the following information):**
 - OS: Linux Kernel 4.15.0-101-generic
 - Installation Method: Official ubuntu apt source
 - App Version 2020.2.1

**Comment by wdawson** [comment]
We'll track this as part of the feature request for [OAuth through a browser](https://github.com/Kong/insomnia/discussions/3533). I'm assuming that there is some limitation for apps since Postman has the same issue.
