### ISSUE TITLE
OAuth through browser

### ISSUE THREAD

**Issue by StummeJ** [getinsomnia/insomnia#2259]
**Is your feature request related to a problem? Please describe.**
Currently if you try to authenticate through Identity Server 4 using the Google social provider a correlation exception is thrown.  

**Describe the solution you'd like**
Postman has implemented a signin via browser to work around this.  Would it be possible to mimic this behavior?

**Describe alternatives you've considered**
Switching to postman since they have a working solution

**Additional context**
The postman solution works by redirecting to their server to finish the auth, then opening an app magic link back into postman.

**Comment by nijikokun** [comment]
Related to #2254

**Comment by StummeJ** [comment]
@nijikokun  I don't think it is.... this is a cookie issue, also fixed in postman.  With identity server and social logins the cookie is not kept/sent back to the identity server causing a correlation error.

**Comment by nijikokun** [comment]
Gotcha @StummeJ they looked similar! Re-opening!

**Comment by StummeJ** [comment]
Any news on this ?
