### ISSUE TITLE
[Improvement] Show basic auth password if the user wants that

### ISSUE THREAD

**Issue by abshammeri** [getinsomnia/insomnia#226]
Two suggestions:

- Show password on Basic Auth for debugging if the user wants that.
- Make the send button clear ( Colored/Primary Button )  .. I always forget where it is .. it's not clear.

Thanks for this .. one of the greatest product.. it's way better than Postman..

**Comment by gschier** [comment]
Hi @abshammeri. It's not the most obvious feature, but there is an option to show passwords in the app's preferences. 

As for the send button, I'm hesitant to change it at this point since it's been working so far. However, I'll keep it in mind going forward. 

Thanks!
