### ISSUE TITLE
GraphQL | Invalid Syntax Error

### ISSUE THREAD

**Issue by claratorres** [getinsomnia/insomnia#2260]
Invalid Syntax error when adding return fields for a working query.

**To Reproduce**
1. Go to a working query and execute normally (will execute ok).
2. Edit query and add a return field with subselection.
3. Execute again
4. Invalid Syntax error
5. Go back to original query
6. Invalid Syntax error

**Expected behavior**
Not to have invalid syntax error if query is correct.

**Screenshots**
**Query working fine**
![image](https://user-images.githubusercontent.com/66630171/84050443-0aded200-a9ae-11ea-87bf-f963d3d5b439.png)
**Modified query - Invalid Syntax**
![image](https://user-images.githubusercontent.com/66630171/84050579-3497f900-a9ae-11ea-898e-e02dfc7169aa.png)

**Back to original query - Invalid Syntax**
![image](https://user-images.githubusercontent.com/66630171/84050629-44174200-a9ae-11ea-86c4-df89925a7927.png)

**Desktop (please complete the following information): 2020.2.1**
![image](https://user-images.githubusercontent.com/66630171/84050072-91df7a80-a9ad-11ea-9931-13b9aa9b3291.png)

**Additional context**
- It is happening with all saved queries.
- Happens since we updated with latest version.

Many thanks :)

**Comment by withinboredom** [comment]
It seems like it's the last thing entered with a downloaded schema, so this:

```graphql
query {
  currentUser
}
```

results in

```json
{"query":"query {\n  \n}"}
```

You can even just use the github graph to reproduce:

**Comment by pierpeople** [comment]
The current version of Insomnia is basically unusable for GraphQL. I am experiencing some syntax error in both queries and variables.

**Comment by claratorres** [comment]
Version 2020.2.2 has been released and issues seem to be fixed :)

Many thanks! 👍
