### ISSUE TITLE
Custom response tag for chaining requests

### ISSUE THREAD

**Issue by rmclaughlin-nelnet** [getinsomnia/insomnia#2263]
**What is your question?**
I would like to use request chaining, but I need to do some preprocessing on the response data before I can use it in the next request. Can I write a custom response tag (I would want it to function just like the built in response tag, except do some custom processing)? Or can a custom tag access data from a previous response like the response tag does? If so can you give me an example of how this is done?

Right now the only apparent way around this is to store intermediate data in env variables. Is this the best way for custom tags to get request data?

**Comment by gschier** [comment]
I suggest taking a look at the Response Eval plugin. It is a fork of the existing Response tag that adds the ability to execute arbitrary JS on the response. You could possibly make use of that or look at it as a starting point for your own plugin.
