### ISSUE TITLE
Sorry I need to clean this post I apologize. 

### ISSUE THREAD

**Issue by jedelvalled** [getinsomnia/insomnia#2269]
Sorry I need to clean this up.... wrong example

**Comment by jedelvalled** [comment]
Just a small comment the working hash is from Insomnia Version 7.1.1 (7.1.1.3350)

This is a regression.

**Comment by nijikokun** [comment]
> Sorry I need to clean this up.... wrong example

🙆‍♂️ I was wondering if it was me or not

**Comment by jedelvalled** [comment]
> > Sorry I need to clean this up.... wrong example
> 
> 🙆‍♂️ I was wondering if it was me or not

I'm sorry @nijikokun  my bad. (it's me not you)

**Comment by nijikokun** [comment]
Going to close in favor of starting fresh ❤️

**Comment by nijikokun** [comment]
> I'm sorry @nijikokun my bad. (it's me not you)

No worries, we've all been there ❤️
