### ISSUE TITLE
Hash calculations fail on Insomnia 2020.2.2 (Last known good release 7.1.1)

### ISSUE THREAD

**Issue by jedelvalled** [getinsomnia/insomnia#2271]
Since the upgrade to insomnia 2020 Hash caculations fail.  

Formula:
```json
{
  "Mashery_signature_hash_Stg": "{% hash 'md5', 'hex', Sig_Input_HashStg %}",
  "Mashery_Apikey_hashStg": "kahgsertyubnzdfajhywloia",
  "Mashery_Secret_hashStg": "7IJhgHJNH18NALzphANJHk78",
  "Sig_Input_HashStg": "{{ Mashery_Apikey_hashStg }}{{ Mashery_Secret_hashStg }}1591738038",
  "SigConcatenated__Hash_Staging": "{{ Sig_Input_HashStg }}"
}
```

URL: `http://testurl.com?signature={{ Mashery_signature_hash_Stg  }}`

This is the result of the CURL in 7.1.1
```shell
curl --request POST \
  --url 'http://testurl.com/?signature=**92d45a610fdf7452bb25a1ea004f1355**'
```

This is what I get on the Mac and it's the same:
```
jeduardodelvalle@MacBook-Pro platform-tools % md5 -qs kahgsertyubnzdfajhywloia7IJhgHJNH18NALzphANJHk781591738038
**92d45a610fdf7452bb25a1ea004f1355**
```

This is what I get today on Version 2020.2.0 (2020.2.0)

```shell
curl --request POST \
  --url 'http://testurl.com/?signature=**923c2eec4d8d5c949bd9a1fd31011ccc**'
```

The first 2 results are good the new one is not.

**Comment by gschier** [comment]
The latest release contained a slight change to the handling of environment variables. It looks like this has affected your use-case..

In the latest version, environment variables are rendered top to bottom. So, in your example, the hash is being calculated before the variable is rendered.

```shell
$ md5 -qs '{{ Mashery_Apikey_hashStg }}{{ Mashery_Secret_hashStg }}1591738038'
923c2eec4d8d5c949bd9a1fd31011ccc
```

If you re-order your environment variables, you should end up with the correct result again.

```json
{
  "Mashery_Apikey_hashStg": "kahgsertyubnzdfajhywloia",
  "Mashery_Secret_hashStg": "7IJhgHJNH18NALzphANJHk78",
  "Sig_Input_HashStg": "{{ Mashery_Apikey_hashStg }}{{ Mashery_Secret_hashStg }}1591738038",
  "SigConcatenated__Hash_Staging": "{{ Sig_Input_HashStg }}",
  "Mashery_signature_hash_Stg": "{% hash 'md5', 'hex', Sig_Input_HashStg %}"
}
```

**Comment by jedelvalled** [comment]
Done, that resolved the issue. The change actually makes sense... I guess we can close this bug as "Works as Designed". Thank you very much.
