### ISSUE TITLE
Response status code

### ISSUE THREAD

**Issue by alexraileanu** [getinsomnia/insomnia#2273]
previously, it used to be possible to see the description of each status code in the response. something like: `200 OK` or `404 Not Found` or whatever. now, i think since a recent update, it only shows the code and not the text. is this an intended feature? is there any way that i can get the text back?

i am on the latest version (v2020.2.2) on macos 10.15.4.

**Comment by alexraileanu** [comment]
my bad. looking thru the code, it looks like the text of the status should be shown. it is probably a bug of some sort with my api. other requests seem to show the text.

**Comment by gschier** [comment]
The latest version of Insomnia added support for HTTP/2, which does not have a status reason anymore.

**Comment by alexraileanu** [comment]
@gschier ohh, i did not know this. thank you for your help and for the pr! :)
