### ISSUE TITLE
[Improvement] Delete Custom Methods

### ISSUE THREAD

**Issue by bkonia** [getinsomnia/insomnia#228]
Maybe I'm being dense, but I can't find any way to delete Custom Methods?

**Comment by shahalam786** [comment]
Do you have too

**Comment by bkonia** [comment]
@shahalam786, I don't understand your response.

Do I HAVE to? Of course not, but it's annoying to see extraneous Custom Method tags every time I open the Custom Methods box. It's a fairly standard principle of application design that actions should be reversible, meaning if you create an object in an application, there should be a way to remove it.

Insomnia is a beautifully designed, ultra-slick application. The developers have demonstrated tremendous attention to detail, so I'm pretty sure they don't want loose ends like this, which look sloppy and detract from an otherwise first-class UI experience.

**Comment by gschier** [comment]
Hi @bkonia. You are not dense, this was just never implemented 😄 

Also, you are correct that we don't want these loose ends. Thanks for the report 🥇

**Comment by hwaring** [comment]
I can start on this.

**Comment by gschier** [comment]
@hwaring nice! Do you have a plan UI? I was thinking a simple "x" on the right of each method but am open to suggestions.
