### ISSUE TITLE
Copy as CURL with Multipart

### ISSUE THREAD

**Issue by keihuli** [getinsomnia/insomnia#2282]
If you make an Copy with CURL in an POST with an Multipart Body with an choosen file, the file is not include.

1. Get in POST request
2-Use MULTIPART as body type and
3. Add a field
4. Change the type to "File"
5. Then -> Choose File (what you want)
6. right click on the post
7. Copy as CURL
8. Paste IT to an editor
9. Look on the result and see that the file is missing

**Expected behavior**
Include the file as multipart in the curl

**Additional context**
![image](https://user-images.githubusercontent.com/56976981/84392654-ef1c3b80-abfa-11ea-8890-1a2bb1050597.png)

**Comment by engineer-go** [comment]
Have you figured out how to add file yet? I have the same problem - my curl request is not working because the correct file path wasn't copied.

**Comment by keihuli** [comment]
NO. I have no solution...
