### ISSUE TITLE
Folder hiearchy with snapshots and version control

### ISSUE THREAD

**Issue by robinbertram** [getinsomnia/insomnia#2289]
When using snapshots with version control, I'm finding it difficult to track exactly which of my requests that have been modified. I've a lot of folders and subfolders, and the snapshot overview doesn't tell me which folder a request belongs to.

It would be nice to be able to get the hiearchy of the request, something like;
```
Folder > Subfolder > Actual request
```

**Comment by nijikokun** [comment]
See duplicate issue #2597
