### ISSUE TITLE
Insomnia Core Team sync issues

### ISSUE THREAD

**Issue by wsrast** [getinsomnia/insomnia#2290]
Hi, I have a team of 11 that I recently signed up with Insomnia, and we're experiencing some odd behavior with the team sync functionality.

In particular, I've noticed that your sync algorithm has three problems:
1. Syncs are duplicating folders on one machine when changes have been made on another machine
2. Syncs are missing folders which are moved from one workspace to another
3. Environment variables changed in one user's machine are receiving only partial changes on others' machines

In some cases when changes are made to requests inside a folder in a workspace, that same workspace on another machine ends up with two folders named the same thing, which appear to be identical. Only one of these contains the updated changes. It's difficult isolating when this happens.

The missing folder issue is very easy to replicate. Right click any folder in a workspace, choose to duplicate it, then "Move" it to another synced workspace. Wait for or force a sync, and check the other machines in the team after they sync. You'll not see the new folder. In order to make that folder appear, the source machine has to then "Duplicate" the new folder again, this time in the target workspace. The source machine ends up with two copies of the same folder. Force a sync, and the target machine can now see one copy of the folder. The source machine now has to delete the original copy of the folder.

I've seen environment variables get clipped and random spaces. I'm assuming this is because sync runs midway through typing a new value. Even forcing a sync won't update this value until you manually change the value on the source machine, force a sync, and then remove the change and sync again.

Clearly, you guys need to give some attention to your sync logic. Otherwise, Insomnia's a very nice app, particularly for GraphQL.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Installation Method: installer
 - App Version 2020.2.2

**Comment by gschier** [comment]
Hi there. Would you be able to email support@insomnia.rest with your account details so we can take a look? It sounds like something might be off
