### ISSUE TITLE
DOCS - Import by "Run-In-Insomnia Button" 

### ISSUE THREAD

**Issue by kjugi** [getinsomnia/insomnia#2298]
**Describe the bug**
There is a problem when want to import example project from docs: https://insomnia.rest/run/?label=To-Do%20Monkey&uri=https%3A%2F%2Fgist.github.com%2Fgschier%2F27a277ed5dd3b0d2b0bc063482e6417a

After processing to open an app we've got error message "The URI does not contain a valid specification". With Stack trace like this:

```
Error: No importers found for file
    at module.exports.module.exports.convert (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:132323:9)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. [Go to](https://insomnia.rest/run/?label=To-Do%20Monkey&uri=https%3A%2F%2Fgist.github.com%2Fgschier%2F27a277ed5dd3b0d2b0bc063482e6417a)
2. Click on "Run To-Do Monkey"
3. Allow to open insomnia
4. Confirm that you want to import workspace in an app
5. Stack trace with error is showed

**Expected behaviour**
Should import workspace to app. Manually created new button with same gist works. Example [here](https://insomnia.rest/run/?label=Same%20gist%20as%20in%20demo&uri=https%3A%2F%2Fgist.githubusercontent.com%2Fgschier%2F27a277ed5dd3b0d2b0bc063482e6417a%2Fraw%2F478d96ec97b7278cf97c24d96b2603a422a4d0b3%2FInsomnia_2019-05-09.yaml)

**Screenshots**
__

**Desktop:**
 - OS: macOS 10.15.1
 - Installation Method: https://insomnia.rest/download/#mac
 - App Version 2020.2.2 (2020.2.2)

**Comment by thewheat** [comment]
I believe the doc page in reference here is https://support.insomnia.rest/article/68-run-button 
And the button is the 2nd one on the page
![image](https://user-images.githubusercontent.com/892961/95018183-9df3f400-0690-11eb-88d4-33d7d148adb1.png)
