### ISSUE TITLE
"Prettify GraphQL" Incorect Indentations

### ISSUE THREAD

**Issue by elijahjcobb** [getinsomnia/insomnia#2301]
**Describe the bug**
In my preferences, I have "Indent with tabs" enabled and my "Editor Indent Size" is set to 4. However, whenever I click "Prettify GraphQL" in a GraphQL request body, it reformats my request to 2 spaces.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enabled: "Indent with tabs"
1. Set "Editor Indent Size" to 4
1. Entered GraphQL request
1. Clicked "Prettify GraphQL"

**Expected behaviour**
Reformat my request with tabs of an indentation size of 4.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.0.4
 - Installation Method: deb from Website
 - App Version v2020.2.2

**Comment by arjunkesava** [comment]
@nijikokun, I had made a PR for this issue.
Thanks for creating this issue @elijahjcobb

**Comment by minemax-ua** [comment]
I have the same issue. I've set the Editor Indent Size to 3. It works fine when I type from the keyboard, but the "Prettify ..." command doesn't respect it and makes every indent the default size (2).

**Comment by dimitropoulos** [comment]
the PR for this was previously closed because there is not a way for us to implement this with the current insomnia-prettify.  that said, does anyone know of a graphql formatting library that's well tested and could potentially do this for us? if so, please point us in that direction so we can take a look at integrating it.

**Comment by dimitropoulos** [comment]
this should be fixed by https://github.com/Kong/insomnia/pull/4022 which should be in the next release
