### ISSUE TITLE
Seeing another workspaces history and objects when viewing or creating snapshots

### ISSUE THREAD

**Issue by dmeunier** [getinsomnia/insomnia#2303]
We meet some version control problems switching from a workspace to another. I currently see the comments of another workspace when I display the master branch history of the current workspace. Moreover when I want to create a new snapshot I can see all the objects of another workspace as "modified objects".

We are all developing on Linux Operating Systems and we are all up to date (Insomnia 2020.2.2).

**Comment by DMarby** [comment]
Hi @dmeunier,

We just released 2020.4.2 which contains a number of fixes for issues related to the version control beta sync, including this one.

Please give it a try, and if you're still having issues, send us an email at support@insomnia.rest so that we can best assist you with these issues!
