### ISSUE TITLE
Team members not showing up without re-opening dialog

### ISSUE THREAD

**Issue by dmeunier** [getinsomnia/insomnia#2304]
We meet workspace share problems inside our development team. When we want to share a workspace, the select list is very often empty (you have no team) and we have to close and open it again several times before seeing our team.

We are all developing on Linux Operating Systems and we are all up to date (Insomnia 2020.2.2).

**Comment by nijikokun** [comment]
@dmeunier wasn't sure if you meant re-opening the application or the dialog, I assumed the dialog, if that isn't the case can you provide more details 😊

**Comment by dmeunier** [comment]
@nijikokun we have to close and open the "share workspace" dialog several times (not the application).
