### ISSUE TITLE
[Bug] Error when deleting query string parameters

### ISSUE THREAD

**Issue by bkonia** [getinsomnia/insomnia#231]
When I click on the trash can icon to delete a query string parameter, it frequently doesn't delete. Instead, it briefly displays a red exclamation mark icon in place of the trash can.

**Comment by gschier** [comment]
That's a confirmation step. Just need to click once more. I'm open to ideas on how to make this more obvious. Maybe a tooltip the first time?

**Comment by bkonia** [comment]
OK, LOL I see that now, but yeah, it's far from obvious. Honestly, I don't think the confirmation is necessary. Worst case scenario is the user might accidentally delete a single parameter and have to re-enter it. It wouldn't be the end of the world.

**Comment by gschier** [comment]
This "confirm delete" paradigm is used throughout the app so I would like to keep this as consistent as possible. When a delete button has a text component, it becomes much more intuitive. 

![image](https://cloud.githubusercontent.com/assets/587576/26170313/dce338ca-3af5-11e7-888f-8f3ae344619f.png)

There are cases – like deleting a param with an API key or user ID – that would be annoying if they disappeared by accident.

**Comment by bkonia** [comment]
OK, no biggie. Now that I know, it's a non-issue for me, but you should probably make it more intuitive for new users.

**Comment by gschier** [comment]
👍 totally agree
