### ISSUE TITLE
Option to disable HTTP redirects (301)

### ISSUE THREAD

**Issue by leolux** [getinsomnia/insomnia#2314]
As a REST client it should be able to display HTTP request and response headers. But currently insomnia always follows HTTP redirects and does not allow me to inspect HTTP response headers for the very first request. It is quite important to investigate HTTP redirects to ensure everything works as expected. The most important part of HTTP redirects are HTTP headers. So insomnia could be able to inspect those headers when there would be an option to stop the HTTP client to follow redirects.

**Comment by nijikokun** [comment]
Welcome @leolux

You can change the redirect settings for a request by right clicking and choosing "settings":

![image](https://user-images.githubusercontent.com/198276/85790286-dd4f9380-b6e4-11ea-84b2-7f5c65d72282.png)

Then choose the option you'd like from the follow redirects dropdown:

![image](https://user-images.githubusercontent.com/198276/85790392-007a4300-b6e5-11ea-8b8f-c81eee9b93fd.png)

Related to #915
