### ISSUE TITLE
auto repeat interval

### ISSUE THREAD

**Issue by foxjazz** [getinsomnia/insomnia#2317]
**Is your feature request related to a problem? Please describe.**
I would like to add a feature where a test can be re-run at a time interval.

Maybe right click on a post or get request and a menu can come up showing how many times, and interval of test.

**Comment by nijikokun** [comment]
Welcome @foxjazz 👋 

You can currently set a request to be re-run at an interval by right clicking the "Send" button and choosing "Repeat on Interval":

![image](https://user-images.githubusercontent.com/198276/85790602-52bb6400-b6e5-11ea-9fbb-60c0df3323c7.png)

From there enter the desired amount of delay, and click "Start"!

![image](https://user-images.githubusercontent.com/198276/85790653-69fa5180-b6e5-11ea-8e0c-865efe8f9252.png)

Hope this helps ❤
