### ISSUE TITLE
Update libcurl to support SNI/ECDSA certificates

### ISSUE THREAD

**Issue by bkonia** [getinsomnia/insomnia#232]
Sending an HTTPS request to a server using SNI fails with the following error:

* SSL peer handshake failed, the server most likely requires a client certificate to connect
* Curl_http_done: called premature == 1
* Closing connection 2

I'm pretty sure this is happening because you need to update the libcurl version. The URL works fine in a browser and it also works fine in Postman.

**Comment by gschier** [comment]
@bkonia it would be of great help if you could figure out how (if possible) to successfully make a request to your server from the command line using curl and post the necessary flags here.

**Comment by gschier** [comment]
Currently, Insomnia dynamically links to the version of curl installed on your machine

**Comment by bkonia** [comment]
Well, I ran curl from the command line, with no parameters set, against that URL and it worked. So maybe Insomnia is passing some parameter to curl that's causing this error.

**Comment by gschier** [comment]
Hmm. Do you have "Validate SSL Certificates" disabled in the settings?

**Comment by bkonia** [comment]
Well, the certificate is definitely valid, but yes, I have the Validate Certificates setting **disabled**.

**Comment by gschier** [comment]
Can you try enabling it? Surprisingly, sometimes having it disabled causes problems.

**Comment by bkonia** [comment]
Yes, that fixed it, thanks!

**Comment by gschier** [comment]
👌

**Comment by shahalam786** [comment]
Issues and issues

**Comment by ShogunPanda** [comment]
I also ran into the same issue and I finally found this.
I kindly suggest to add to a "known issues" page somewhere.
Anyway, thanks for the wonderful app and support.
