### ISSUE TITLE
Allow to disable popup suggestion

### ISSUE THREAD

**Issue by silvioprog** [getinsomnia/insomnia#2320]
Hi.

It would be nice some option to disable the popup below:

![image](https://user-images.githubusercontent.com/1456829/85620087-aa9c9100-b639-11ea-9bf3-ce881f4469ad.png)

It opens on each typed value (e.g: ```1```), making it hard to typing since we have to use <kbd>Esc</kbd> every typed value.

Cheers

**Comment by gschier** [comment]
Hi @silvioprog! You can disable automatic autocomplete suggestions by setting the **autocomplete popup delay** to 0 in the app preferences.

Note, you will still be able to summon it when needed with ctrl+space

**Comment by silvioprog** [comment]
Solved! Thank you @gschier ! 😃 👍
