### ISSUE TITLE
[website] menus on https://insomnia.rest/graphql/ page don't work

### ISSUE THREAD

**Issue by wesinator** [getinsomnia/insomnia#2322]
**Describe the bug**
The menus on the website graphql page don't work 

(I would report on https://github.com/Kong/insomnia.rest but that project doesn't have issues)

**To Reproduce**
1. https://insomnia.rest/graphql/ 
Try to click the menus (Docs, Plugin, etc.)

Reproduced in FF and Safari 

**Desktop (please complete the following information):**
 - OS: macOS
 - Installation Method: n/a
 - App Version: n/a

**Comment by nijikokun** [comment]
Related to #2323

**Comment by nijikokun** [comment]
Fixed in https://github.com/Kong/insomnia.rest/pull/54
