### ISSUE TITLE
Price link not working on page

### ISSUE THREAD

**Issue by rubendebest** [getinsomnia/insomnia#2323]
**Describe the bug**
Links to "Docs", "Plugins", "Pricing" and "Login" are not working at https://insomnia.rest/plus/

**To Reproduce**
1. Go to https://insomnia.rest/plus/
2. Try to Click on Pricing. It does not work.

**Expected behavior**
1. Links working on https://insomnia.rest/plus/

**Comment by nijikokun** [comment]
Nice catch, recently changed the layouts to make the footer auto-sticky and it seems like this page was missed!

**Comment by nijikokun** [comment]
Fixed by https://github.com/Kong/insomnia.rest/pull/56
