### ISSUE TITLE
Ingress Path Incorrect when Generating Kubernetes Config with openapi-2-kong

### ISSUE THREAD

**Issue by doctorwu** [getinsomnia/insomnia#2327]
**Describe the bug**
When you specify a path in the server url, the Ingress path ends in `.*`, which is not correct. If you specify the strip path annotation in the OAS specification, you will get a 404 when proxying to the upstream. Kong is stripping the whole path.

OAS Snippet:

```
info:
  x-kubernetes-ingress-metadata:
    name: account
    annotations:
      konghq.com/strip-path: "true"
servers:
  - url: http://account.commercial-bank.svc:5000/account
```

My request looks like this: `/account/balances`

Here is my upstream application log when the Ingress path is set to `/account/.*`:
```
[2020-06-26 14:43:05,109] INFO in _internal: 10.1.1.69 - - [26/Jun/2020 14:43:05] "GET / HTTP/1.1" 404 -
```

When you set the Ingress path to `/account` and execute the same request everything works as expected.

```
[2020-06-26 14:45:11,964] INFO in _internal: 10.1.1.69 - - [26/Jun/2020 14:45:11] "GET /balances HTTP/1.1" 200 -
```

**Comment by doctorwu** [comment]
I think the answer lies in the pathType property.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#httpingresspath-v1beta1-networking-k8s-io

**Comment by gatzjames** [comment]
Closing as this is no longer supported inside Insomnia
