### ISSUE TITLE
Designer git commit forces file rights

### ISSUE THREAD

**Issue by skiat** [getinsomnia/insomnia#2331]
**Describe the bug**
All the tracked files are forced and committed without execution rights. i.e. mode 755 resets to 644

**To Reproduce**
1. have git shared project
2. have some file UNRELATED to insomnia / OUTSIDE .insomnia folder with execution right tracked into git
3. change something in an insomnia request/record, then commit and then push

**Expected behavior**
only .insomnia files are touched

**Desktop (please complete the following information):**
 - OS: MS Windows10
 - Installation Method: installer from insomnia website
 - App Version 2020.2.0

**Comment by kreosus** [comment]
Hi @skiat 

Have you been able to reproduce this issue with our latest release: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.2?

**Comment by skiat** [comment]
> Hi @skiat
> 
> Have you been able to reproduce this issue with our latest release: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.2?

Hello kreosus, thanks for your message, unfortunately this bug and the other I posted in the same period did not allow my company to proceed with this version of insomnia. So I did not try it ever again. We are using an insomnia sync with a team account which is doing what we need 😉

**Comment by kreosus** [comment]
Hi @skiat 

Thank you for the suggestion. In the future we will be redesigning our App and the use of Git-Sync that should accommodate you. Have a nice day.
