### ISSUE TITLE
Not able to create build or package executable

### ISSUE THREAD

**Issue by sunil-bagde** [getinsomnia/insomnia#2341]
npm run app-package not able create build package executable

**To Reproduce**

# Install and Link Dependencies
npm run bootstrap

npm run  app-package

**Expected behavior**
Should create build or package 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.15.1]
 - Installation Method: [e.g. homebrew]
 - App Version [e.g. v7.0.3]

**Additional context**
insomnia-app: npm
insomnia-app: WARN deprecated hawk@6.0.2: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
insomnia-app: npm
insomnia-app:  WARN deprecated cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
insomnia-app: npm
insomnia-app:  WARN deprecated sntp@2.1.0: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
insomnia-app: npm WARN deprecated boom@4.3.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
insomnia-app: npm
insomnia-app: WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
insomnia-app: npm
insomnia-app: WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
insomnia-app: npm
insomnia-app: WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
insomnia-app: npm
insomnia-app: WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
insomnia-app: npm ERR!
insomnia-app:  Unexpected end of JSON input while parsing near '...+MIbw\nUcokI2mnCj4Z3+'
insomnia-app: npm
insomnia-app:  ERR! A complete log of this run can be found in:
insomnia-app: npm
insomnia-app: ERR!     /Users/sunilbagde/.npm/_logs/2020-07-03T22_35_31_829Z-debug.log
insomnia-app: child process exited with code 1
insomnia-app: [build] Complete!
insomnia-app: [package] Removing existing directories
insomnia-app: [package] Packaging app
insomnia-app:   • electron-builder  version=21.2.0 os=19.2.0
insomnia-app:   • installing production dependencies  platform=darwin arch=x64 appDir=/Users/sunilbagde/code/http1/packages/insomnia-app/build
insomnia-app: [package] ERROR: { Error: /usr/local/bin/node exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
insomnia-app: Error output:
insomnia-app: Error output:
insomnia-app: npm WARN deprecated hawk@6.0.2: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
insomnia-app: npm WARN deprecated boom@4.3.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
insomnia-app: npm WARN deprecated sntp@2.1.0: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
insomnia-app: npm WARN deprecated cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
insomnia-app: npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
insomnia-app: npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
insomnia-app: npm WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
insomnia-app: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
insomnia-app: npm ERR! Unexpected end of JSON input while parsing near '...+MIbw\nUcokI2mnCj4Z3+'
insomnia-app: npm ERR! A complete log of this run can be found in:
insomnia-app: npm ERR!     /Users/sunilbagde/.npm/_logs/2020-07-03T22_35_35_731Z-debug.log
insomnia-app:     at ChildProcess.childProcess.once.code (/Users/sunilbagde/code/http1/packages/insomnia-app/node_modules/builder-util/src/util.ts:239:14)
insomnia-app:     at Object.onceWrapper (events.js:286:20)
insomnia-app:     at ChildProcess.emit (events.js:198:13)
insomnia-app:     at maybeClose (internal/child_process.js:982:16)
insomnia-app:     at Socket.stream.socket.on (internal/child_process.js:389:11)
insomnia-app:     at Socket.emit (events.js:198:13)
insomnia-app:     at Pipe._handle.close (net.js:606:12)
insomnia-app:   exitCode: 1,
insomnia-app:   alreadyLogged: false,
insomnia-app:   code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE' }
insomnia-app: npm ERR! code ELIFECYCLE
insomnia-app: npm ERR! errno 1
insomnia-app: npm ERR! insomnia-app@2.1.6 package: `node ./scripts/package.js`
insomnia-app: npm ERR! Exit status 1
insomnia-app: npm ERR!
insomnia-app: npm ERR! Failed at the insomnia-app@2.1.6 package script.
insomnia-app: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
insomnia-app: npm ERR! A complete log of this run can be found in:
insomnia-app: npm ERR!     /Users/sunilbagde/.npm/_logs/2020-07-03T22_35_35_801Z-debug.log
lerna ERR! npm run package exited 1 in 'insomnia-app'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insomnia@1.0.0 app-package: `lerna run package --stream --parallel --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the insomnia@1.0.0 app-package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunilbagde/.npm/_logs/2020-07-03T22_35_35_824Z-debug.log
![image](https://user-images.githubusercontent.com/6269292/86500090-5f5a4f00-bdac-11ea-86c7-7a19f321f0f1.png)

**Comment by sunil-bagde** [comment]
Fixed

**Comment by cbrhex** [comment]
@thesunilbagde how?

**Comment by sunil-bagde** [comment]
Old way used mentioned version and removed node_module installed
