### ISSUE TITLE
JSONpath evaluator not working as expected

### ISSUE THREAD

**Issue by abhuyan** [getinsomnia/insomnia#2342]
**Issue**
The JSON path evaluator (https://github.com/dchester/jsonpath) which is being used is not working in the app as expected when multiple keys are given in an expression.

**To Reproduce**
Steps to reproduce the behavior as per the JSON object example given at https://github.com/dchester/jsonpath
1. Try the expression: $.store.book[*].[category,price]
2. No results in Insomnia app

**Expected behaviour**
With the same expression when tried at  https://jsonpath.com/ gave the below result:
[
  "reference",
  8.95,
  "fiction",
  12.99,
  "fiction",
  8.99,
  "fiction",
  22.99
]

**Using OSX Desktop app:**
 - macOS 10.14.6 
 - Installation Method: Directly from the web
 - App Version: 2020.2.2

**Comment by lguzik-bkp** [comment]
I've just stumbled upon this issue, would be awesome to have it fixed. Or even better, a full `jq` support would be very much appreciated! :)

**Comment by dimitropoulos** [comment]
I'm also interested in some improvements here.  Do either of you have any suggestions about what npm would be best to use (see https://github.com/Kong/insomnia/issues/3155 for discussion on jsonpath being deserted).

**Comment by dimitropoulos** [comment]
(accidentally closed, my bad)

**Comment by kreosus** [comment]
Hi @lguzik-bkp 
We have another issue open as for your problem. Please refer to https://github.com/Kong/insomnia/issues/777 for more information.

**Comment by gatzjames** [comment]
Closing as this should be working with jsonpath-plus
