### ISSUE TITLE
Wrong and blurry/pixelated icon

### ISSUE THREAD

**Issue by ranayas** [getinsomnia/insomnia#2345]
- Insomnia Core installed but Insomnia Designer icon is displayed
- Blurry/pixelated icon on the title bar and panel window button
- No icon in title bar of help dialog

**To Reproduce**
1. Open Insomnia
2. See error

**Expected behavior**
Correct icon

**Screenshots**
![inmsonia](https://user-images.githubusercontent.com/65342923/86538106-82bef000-beb9-11ea-88db-fe0797ecbf2e.png)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster) x86_64
 - Desktop environment: Xfce 4.12
 - Installation Method: `sudo apt install insomnia` from `deb https://dl.bintray.com/getinsomnia/Insomnia /` repository
 - App Version: Insomnia Core, Version 2020.2.2

**Comment by ikeblaster** [comment]
Same problem on Windows 10 1909, installed from https://insomnia.rest/download/#windows (updated older version), 2020.3.3.

**Comment by mcorossigo** [comment]
Also confirmed on Windows 10 2004 with Insomnia Core 2020.3.3 (fresh install).
