### ISSUE TITLE
Make JSON inside Designer preview selectable

### ISSUE THREAD

**Issue by 956MB** [getinsomnia/insomnia#2346]
App: Insomnia Designer

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It would be cool if the JSON text inside the 'Example Value' section of the api preview was selectable.

**Describe alternatives you've considered**
N/A

**Additional context**
I don't know if it's the way it's being rendered for preview that makes it not selectable, just wanted to copy a bit of JSON directly from it, if possible.

**Comment by develohpanda** [comment]
Hi @Bloumbs! This is likely fixed by #2296, which should be included in the next release. 🤗 Closing the issue for now, keep an eye out for an update (in a week or so)!

**Comment by 956MB** [comment]
@develohpanda AH, did not see it, my b. 👍
