### ISSUE TITLE
Export Format Specification v4

### ISSUE THREAD

**Issue by vdsimako** [getinsomnia/insomnia#2348]
**What is your question?**
Where I can find export format specification for v4?
Because in v3 specification(https://support.insomnia.rest/article/52-importing-and-exporting-data) request body stores as text.
But in v4 specification request body for json payload type stores as object
```json
{
   "body": {
      "mimeType": "application/json",
      "text": {
         "test": "test"
      }
   }
}
```

same time xml payload exports as text
```json
{
   "body": {
      "mimeType": "application/xml",
      "text": "<test>fasdfa<\/test>"
   }
}
```

**What is the context?**
I wrote a service that convert insomnia workspace into other structure to create performance tests.

**Comment by gschier** [comment]
Hi @vdsimako,

That help document is in-fact version 4's documentation. the fact that it says `3` is an error on our part. 

The `text` property of `body` is always a string. I just exported a test request from Insomnia and this is what it gives.

```json
{
    "mimeType": "application/json",
    "text": "{\n\t\"foo\": \"bar\"\n}"
}
```

![image](https://user-images.githubusercontent.com/587576/86630201-5cfd1e00-bf81-11ea-9f4f-8be0fff32fbb.png)

**Comment by vdsimako** [comment]
Hi @gschier,
I'm using 2020.2.2 version of Insomnia on Mac OS
Here's example
[Insomnia_2020-07-06.json.zip](https://github.com/Kong/insomnia/files/4880827/Insomnia_2020-07-06.json.zip)

<img width="1649" alt="image" src="https://user-images.githubusercontent.com/15703327/86630841-08d05900-bfd6-11ea-84a2-a6eee2547b6e.png">

also was added api_spec type that didn't figured in v3 specification

**Comment by vdsimako** [comment]
@gschier - translation woks as expected.
