### ISSUE TITLE
[Improvement] Support multi-line content in form data

### ISSUE THREAD

**Issue by strictd** [getinsomnia/insomnia#235]
Posting Multi-line content within url-encoded POST.
Pasting content into value field strips any carriage returns from string.

**Comment by gschier** [comment]
The app is already setup to handle newlines (AFAIK), there is just no way to input them into the UI yet.

Here is my first idea for supporting multi-line form input but there may be a better way:

- Similar to how multi-part form has Text and File types, add an additional type for "blob" text
- When type is "blob", show a button that pops a modal dialog to edit multiline text
- If someone pastes multiline text into the single-line input, automatically convert it to "blob"

Let me know if you have any better ideas.
