### ISSUE TITLE
Program starts in wrong display (Ubuntu)

### ISSUE THREAD

**Issue by davidnavas-ashkalabs** [getinsomnia/insomnia#2362]
**Describe the bug**
I'm having this problem where insomnia always starts in the display at the right, not the primary display o secondary display, it starts on the display on the right regardless if it is primary or secondary display.
My setup is a PC monitor set to primary default and a TV on the right for presentations.

**To Reproduce**
1. First of all I'm using Ubuntu 20.04 LTS
2. My setup includes 2 displays the left one is set as primary and the right one is secondary.
3. Installed Insomnia from .deb file downloaded from https://insomnia.rest/
3. When launching the program it starts in the right display (set as secondary)

**Expected behavior**
I would expect the program to open in the primary display, but it opens in the display set at the right side, regardless if it is primary or secondary.

![Screenshot from 2020-07-06 19-13-37](https://user-images.githubusercontent.com/66633169/86970634-4f889500-c135-11ea-8fce-d32eb4241e3d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Installation Method: from .deb file downloaded from https://insomnia.rest/
 - App Version 2020.2.2

**Comment by filfreire** [comment]
Hi @davidnavas-ashkalabs, thanks for reporting this! I'm not entirely certain this is specific to Insomnia, are you by any chance still able to reproduce this using latest Ubuntu and latest Insomnia versions?

**Comment by kreosus** [comment]
Hi @davidnavas-ashkalabs 

As we have not heard back from you we are closing this issue out. If you require any further/future assistance please let us know and we will proceed accordingly. Have a nice day.
