### ISSUE TITLE
Changing branches in git does not remove items, only adds

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2365]
**Describe the bug**
I have two branches - `master`, and `break-test`. The only difference between the two, is that `break-test` has added a new unit test (but it could be anything - a new request, a new environment, etc).

With all changes committed, if I switch `master -> break-test`, the new test is added and I can see it in the UI. Then, switching `break-test -> master`, does not delete the new test, and `master` now shows pending changes. What I have described are the exact steps in the gif below.

**To Reproduce**
1. Setup git sync
1. Add new unit test on `master`
1. Commit `master`
1. Create a new branch - `branch`
1. Add new unit test to `branch`
1. Commit `branch`
1. Checkout `master` - observe the new test doesn't get removed
1. Open commit dialog and rollback changes
1. Checkout `branch` - observe the new test gets added
1. Checkout `master` - observe the new test doesn't get removed

**Expected behavior**
Should change branches correctly, and leave no residual information. This may have adverse effects on non-insomnia files in git.

**Screenshots**
![2020-07-09 13 55 50](https://user-images.githubusercontent.com/4312346/86988702-fa0fbf00-c1ec-11ea-8d3d-f611bba5815b.gif)

**Desktop (please complete the following information):**
- OS: macOS 10.15.3 
- Installation Method: DMG
- App Version v2020.3.0-beta.1

**Comment by filfreire** [comment]
This one is similar to https://github.com/Kong/insomnia/issues/2244. When triaging this with @kreosus we found out that it is still reproducible as of Insomnia version `2022.4.2`.

**Comment by filfreire** [comment]
Closing as "duplicate" in favour of #2244
