### ISSUE TITLE
[Feature Request] Nested Folders

### ISSUE THREAD

**Issue by mattcdavis1** [getinsomnia/insomnia#2366]
I'm having to prefix all my folders by company, service, etc which is a pain and not ideal. I think nested folders are needed for better organization. For example:

* Google
  * Docs
    * Create
    * List
    * Update
  * Drive
  * etc..
* Salesforce
* Mavenlink
  * Invoices
    * Create
    * Update
    * Save
    * Etc..
  * Workspaces
    * Stuff..
* Some Client
  * Forms
    * Form 1
    * Form 2
  * API Integrations
    * Integration 1
    * Etc.

**Comment by develohpanda** [comment]
Hi! Nested folders are supported, curious to see what you're experiencing - feel free to reopen the issue if there is something else you are after. 🤗 

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/4312346/87079678-81574400-c27a-11ea-9017-e9e5f0934c68.png">

**Comment by mattcdavis1** [comment]
Didn't even realize that. Thanks for pointing that out!
