### ISSUE TITLE
CLI navigation not working on git bash for windows

### ISSUE THREAD

**Issue by nijikokun** [getinsomnia/insomnia#2367]
Currently when trying to use a command like `inso run test` the navigation doesn't update when using arrow keys

**Comment by develohpanda** [comment]
Visually it doesn't look quite as nice as Mac, we may need to reconsider how the options display, but functionally it works on both Command Prompt, Windows Powershell, and [cmder](https://cmder.net/). https://recordit.co/vHOLlU7bRF

This report is specifically with `git bash`, which [is not an interactive terminal](https://github.com/vuejs/vue-cli/issues/2117#issuecomment-411568882) therefore won't allow arrow key selection, unless you run the command as `winpty inso.cmd run test`.

![](http://g.recordit.co/HR9tOXEDLk.gif)
