### ISSUE TITLE
"Failed to to fetch schema" message

### ISSUE THREAD

**Issue by miko** [getinsomnia/insomnia#2376]
**Describe the bug**

**To Reproduce**
1. Deploy dgraph/dgraph:master (currently with bad schema introspection)
1. Go to localhost:8080/graphql using GraphQL protocol

**Expected behavior**

Message starting with "Failed to fetch schema" - there is extra "to " in the original message.

**Screenshots**
![insomnia](https://user-images.githubusercontent.com/64889/87105129-5fe66000-c25a-11ea-98c2-033a1e8c5350.jpg)

**Desktop (please complete the following information):**
 - OS:arch linux
 - Installation Method: pacman/yay

 - App Version 2020.3.0

**Comment by JinayJain** [comment]
Hi @develohpanda I would love to work on this issue.

**Comment by develohpanda** [comment]
Hi @JinayJain, sure! Go for it. 🤗
