### ISSUE TITLE
Environment variable is not correctly selected after updating to v2020.3.0

### ISSUE THREAD

**Issue by fransyrcc** [getinsomnia/insomnia#2378]
**Describe the bug**
 When trying to enter an environment variable the variable has an error and it has to be manually updated. 

**To Reproduce**

1. Try to enter a variable in the URL
2. Press `(Control + Space bar)` (mac)
3. Press `Enter` or select from the dropdown list

**Expected behavior**
The variable to be added without need to manually fix it.

**Screenshots**
<img width="1347" alt="Screenshot 2020-07-10 11 25 33" src="https://user-images.githubusercontent.com/31028986/87144953-76afa580-c2a0-11ea-9c68-2403fdc24ad0.png">
<img width="1257" alt="Screenshot 2020-07-10 11 25 49" src="https://user-images.githubusercontent.com/31028986/87144955-7911ff80-c2a0-11ea-9e1c-09137291a520.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Installation Method: update and also download and replace
 - App Version 2020.3.0

**Comment by zakini** [comment]
I'm getting this on Ubuntu 20.04 as well

**Comment by marcohabeck** [comment]
They also no longer work in the documentation!

Variables inserted with the previous versions are displayed, but can no longer be added.

The variable window opens but when you select it, the corsor jumps up. All entries of the filter in the window appear in the documentation field.

**Comment by andreshg112** [comment]
Same here. I have to type `{{base_url}}` in order to make it work.

**Comment by nijikokun** [comment]
Related to #2377

**Comment by develohpanda** [comment]
Reopening this, as it is not related to #2377. We're looking into a fix at the moment.

**Comment by fransyrcc** [comment]
Thanks for that. I tested it in version 2020.3.3  and it works like a charm 😄

**Comment by marcohabeck** [comment]
The problem with the variables in the documentation has been resolved. thank you
