### ISSUE TITLE
Beautify syntax when sending multipart/form-data with Text (multi-line)

### ISSUE THREAD

**Issue by LocalHeroPro** [getinsomnia/insomnia#2380]
**Is your feature request related to a problem? Please describe.**
Can't format syntaxed data when dealing with multipart/form-data and Text (multi-line).

**Describe the solution you'd like**
When I create POST call, and set Structured to `Multipart Form` and add `Text (Multi-line)` and set Editor Syntax to JSON, I want to have the same option as we have on body with type JSON. That option name is `Beautify JSON`!
![image](https://user-images.githubusercontent.com/42643563/87148431-a8c80400-c2ae-11ea-8ba8-1f337a41be02.png)

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://user-images.githubusercontent.com/42643563/87148246-5d155a80-c2ae-11ea-8e0c-20cf681b1bc8.png)
![image](https://user-images.githubusercontent.com/42643563/87148466-bb423d80-c2ae-11ea-930c-e8c1631231e8.png)

**Comment by arjunkesava** [comment]
Hey @nijikokun 
Please check the PR, raised to resolve this issue.
https://github.com/Kong/insomnia/pull/2571
