### ISSUE TITLE
Have you ever tested Insomnia under Windows?

### ISSUE THREAD

**Issue by wlad** [getinsomnia/insomnia#2384]
**What is your question?**
Have you ever tested Insomnia under Windows? 

Usability is a nightmare. Copy & Paste seems to be ignored in all input fields. Can't remember that I had that issue under Linux.

I had to delete the app and install the orange one (although I don't like it at all)

**Comment by DouglasAndre25** [comment]
i'm got the same problem

**Comment by Heisenberg87** [comment]
I've got the same issue, the issue is to do with the new update(2020.3.0)

**Comment by rharkrader** [comment]
I don't think this latest update was tested at all. Same issue on a Mac.

**Comment by nijikokun** [comment]
Duplicate of #2377
