### ISSUE TITLE
Importing cURL no longer automatic

### ISSUE THREAD

**Issue by goddard82** [getinsomnia/insomnia#2390]
**Describe the bug**
Importing cURL now only completes when you press space after pasting.

**To Reproduce**
1. Create a new request or edit the url of an existing one
2. Paste the cURL of a request

**Expected behavior**
The cURL params to be imported automatically; headers etc to be populated. This now _only_ occurs if you press space after pasting the cURL.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Installation Method: homebrew
 - App Version 2020.3.0

**Comment by gschier** [comment]
This was fixed by #2389 and is now live in 2020.3.2
