### ISSUE TITLE
environment variables not populating form or headers correctly

### ISSUE THREAD

**Issue by bkcsfi** [getinsomnia/insomnia#2391]
**Describe the bug**

In 2020.3.0 and 2020.3.2  I am unable to get some environment variables to populate form or header fields correctly

The environment variables appear when I press CTRL-SPACE, but after selecting the completion, the variable appears onscreen in red with a warning triangle, OR the variable appears correct but the query URL Preview shows the variable as NaN

**To Reproduce**
1. Create a new workspace
2. add "BASE_URL" to the base environment
3. create a sub-environment
4. add userid, password and apikey to a new sub-enviroment
5. create a GET request, on query tab add field name api_key, in value use CTRL-SPACE to select apikey. Note that the value of the api key correctly displays in the form but the URL preview shows api_key=NaN (screenshot below)
6. create a POST request, url-form encoded, add form variables username and password. Use env  variables to populate
7. Note in the form that 'username' is highlighted in RED even though it displays the correct value from the sub-environment

**Expected behavior**
Variables should work like they did before 2030.3.0

**Screenshots**

![image](https://user-images.githubusercontent.com/6412502/87193243-4a0e8480-c2c6-11ea-8df8-9d4cc8b7282d.png)

![image](https://user-images.githubusercontent.com/6412502/87193345-817d3100-c2c6-11ea-9710-211e62faffe1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Installation Method: snap
 - App Version 2020.3.2

**Additional context**

I love this program and use it every day.. This is the first time I've had a problem.  Thanks for trying to get 2020.3.2 out, but I think its still not quite right

**Comment by gschier** [comment]
This is fixed in 2020.3.3, which was a separate issue than the one fixed in 2020.3.2

**Comment by bkcsfi** [comment]
thank you for the quick fix, it has resolved the issue for me.

**Comment by awestrate** [comment]
I am seeing this issue again in the current version (2023.2.2)

**Comment by awestrate** [comment]
In my case this is occurring when I have a dash in the environment variable.  I have changed it to an underscore instead.
