### ISSUE TITLE
Cannot cut and paste values into graphQL requests

### ISSUE THREAD

**Issue by JamesK56** [getinsomnia/insomnia#2392]
When I copy and paste into a graphQL request, it is not stored and not sent in the request.  If i click on a different request and then return to the request in question i see that my text is gone.

**Comment by JamesK56** [comment]
Steps to reproduce:
1. copy text
2. past text into message body
3. send request.
4. observe timeline and notice the copied text is not sent.
5. click on a different request
6. return to the request in question
7. notice the text you had pasted into the body is no longer there.

**Comment by nloding** [comment]
This is happening on my regular REST calls also, not just GraphQL.

**Comment by JamesK56** [comment]
2020.3.2 was just released and appears to address this issue.

**Comment by gschier** [comment]
Yes, this was fixed by #2389
