### ISSUE TITLE
Bearer token is not staying. Will copy and paste token then it dissapears

### ISSUE THREAD

**Issue by tcampbPPU** [getinsomnia/insomnia#2395]
**Describe the bug**
I am unable to paste a bearer token and use it in my request. When I paste in my token after a second or two is disappears and is not part of the request.

**To Reproduce**
1. Create New Request
2. Select Bearer Token from Auth dropdown
3. Paste token in
4. Watch the text disappear 

**Expected behavior**
Want to paste Bearer token and use in my request

**Screenshots**
![Screencast-2020-07-11-133333](https://user-images.githubusercontent.com/25044744/87230139-b0a1aa00-c37b-11ea-9831-d1ebbe8c01cc.gif)

**Desktop:**
 - OS: Ubuntu Desktop 20.04
 - Installation Method: snap store
 - App Version: v2020.3.0 (7/9/2020)

**Comment by develohpanda** [comment]
Hiya, this has been resolved in the latest release - 2020.3.3. Please update your client. 😊

**Comment by tcampbPPU** [comment]
Thanks!
