### ISSUE TITLE
GraphQL body from CURL deleted when choosing GraphQL query

### ISSUE THREAD

**Issue by elad-gur** [getinsomnia/insomnia#2396]
**Describe the bug**
Since I've upgraded to 2020.3.3
enabled to create GraphQL request from CURL

I never had problems with that before this version

**To Reproduce**
Steps to reproduce the behaviour:
1. In google chrome copy as curl GraphQL request
2. In insomnia paste the CURl at the address line
3. In insomnia switch the dropdown value from 'JSON' to 'GraphQL'
4. See the body and variables deleted (The Error)

**Expected behaviour**
Before upgrading to this version the GraphQL request was parsed as the body
and the variables were set in the place of the variable

**Screenshots**
![image](https://user-images.githubusercontent.com/50619494/87241528-befbce80-c42c-11ea-8a2b-a572dfc1722c.png)
![image](https://user-images.githubusercontent.com/50619494/87241590-6ed13c00-c42d-11ea-9f62-00588ec78569.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.14.3 ]
 - Installation Method: Auto upgrade
 - App Version v2020.3.3

**Comment by gschier** [comment]
The body will only be preserved if the value of the JSON body is valid for GraphQL.

Based on your screenshot, it appears that your body is _almost_ a GraphQL body but there is an extra `$` at the very beginning, making it unparseable as JSON.
