### ISSUE TITLE
Kebab-case environment variable is NaN

### ISSUE THREAD

**Issue by UAce** [getinsomnia/insomnia#2399]
I created an environment variable in kebab-case and was not able to access it.

**Steps to reproduce the behavior:**
1. Add an environment variable in kebab-case
2. Use it in a request and see the preview is NaN

**Expected behavior**
If kebab-case is not allowed, highlight it as a syntax mistake, else show the correct value

**Screenshots**
![image](https://user-images.githubusercontent.com/19378441/87334360-84696300-c50c-11ea-97f2-83891f561cc6.png)
![image](https://user-images.githubusercontent.com/19378441/87334436-a236c800-c50c-11ea-8dc0-2e490d76c37a.png)

**Context**
OS: Ubuntu 18.04.3 LTS
Insomnia v2020.3.3

**Comment by gschier** [comment]
Ah yes, the dreadful dash problem. There is currently a warning that appears for top-level keys, but it looks like it does not detect nested ones.

![image](https://user-images.githubusercontent.com/587576/87340513-0487cc80-c4fd-11ea-94fa-aaffbac2f27d.png)

An actual inline lint message (as you suggest) would be much nicer for this, as it would be hard to miss too.

**Comment by johanhammar** [comment]
Looks like https://github.com/Kong/insomnia/issues/2684 will solve this?

**Comment by develohpanda** [comment]
Nice find @johanhammar. Yes, sort of. #2684 addresses warnings for nested keys (like in the description above), but #2601 actually added support for kebab-case variables recently, so it is no longer invalid.

I'm going to close this as resolved with #2601. 😄 It will be published with the next beta/stable release.
