### ISSUE TITLE
JSON body not updating when copy pasting as well headers 

### ISSUE THREAD

**Issue by SmritiShrestha** [getinsomnia/insomnia#2400]
**Describe the bug**
For a couple of days, I'm experiencing odd behaviors from insomnia.
1. Copy and paste not working: When I try to copy anything in it by selecting all of the existing contents and paste. It doesn't override existing content.
2. When a param is a change in JSON and request is sent from insomnia, I noticed the request is not being changed when sending and randomly behaving.
Please let us know if we need to do anything.
(Opening ticket based on email reply from Insomnia support)

**To Reproduce**
1. Go to 'Insomnia'
2. Click on 'Modify existing JSON query and send'
3. The request will not be modified as per the latest JSON
3. Similarly, copy paste and content and recheck, copy-paste behaving randomly both in body and header section
4. See error: random request, copy-paste randomness, URL missing message after copy-paste

**Expected behavior**
1. Request send should be the latest request after modification.
2. Copy-pasting URL header should work as expected instead of displaying an error message.
3. JSON body contents should always get updated after pasting.

**Screenshots**
Example Sample: Where a request is not being sent after copy-pasting the header.
![Screenshot from 2020-07-13 23-35-06](https://user-images.githubusercontent.com/11696277/87336555-bc4ec580-c561-11ea-9b58-5dc9e997dbf4.png)

**Desktop (please complete the following information):**
 - LINUX: [Ubuntu 18.04.3 LTS]
 - App Version [e.g. v2020.3.03]

**Comment by gschier** [comment]
Sorry about this! We issued a hotfix release shortly after this one to address the problem. https://insomnia.rest/changelog/core/2020.3.3
