### ISSUE TITLE
JSON Body values missing/resets [Copy-Paste]

### ISSUE THREAD

**Issue by leo-regov** [getinsomnia/insomnia#2405]
**Describe the bug**
Copy and pasting the values in JSON body turns empty on sending request.
Could be the same for anything inside Insomnia.

**To Reproduce**
(Using any backend service)
1. Go to any endpoint with JSON body
2. Paste any values to the JSON
3. Do a request
4. See the log/print of the request
(Just Insomnia)
1. Same steps above (1-2)
2. Switch to another endpoint
3. Go back to the first endpoint with changed values

**Expected behavior**
Values should not reset. The request also uses the previous value when pasting another.

**Screenshots**
First value (manually typed)
![image](https://user-images.githubusercontent.com/66946660/87371725-8be64600-c5b8-11ea-8a85-cb0e7bf8de8f.png)
Result:
![image](https://user-images.githubusercontent.com/66946660/87371809-ac160500-c5b8-11ea-8ff8-89e30f73e8d3.png)

Pasted value
![image](https://user-images.githubusercontent.com/66946660/87371857-d23ba500-c5b8-11ea-9a97-708c99fa2417.png)
Result: Previous value is used.
![image](https://user-images.githubusercontent.com/66946660/87371904-e8e1fc00-c5b8-11ea-92a2-28c6b7b24210.png)

Manually Typed
![image](https://user-images.githubusercontent.com/66946660/87371950-09aa5180-c5b9-11ea-8224-a405d13a326d.png)
Result: Value is now sent
![image](https://user-images.githubusercontent.com/66946660/87371974-1cbd2180-c5b9-11ea-8e0f-34633865992b.png)

Switching endpoint (Select any)
![image](https://user-images.githubusercontent.com/66946660/87372135-660d7100-c5b9-11ea-99b8-45c48ec5c8a3.png)
![image](https://user-images.githubusercontent.com/66946660/87372186-876e5d00-c5b9-11ea-82ed-05e2fd715083.png)
Result: Value resets
![image](https://user-images.githubusercontent.com/66946660/87372217-98b76980-c5b9-11ea-90ec-c0147a5a3070.png)

**Desktop:**
 - OS: [Ubuntu 20.04 LTS]
 - Installation Method: [deb]
 - App Version [v2020.3.0]

**Comment by develohpanda** [comment]
Hi @leo-regov! Thank you for such a detailed report. 🤗 This was fixed in v2020.3.3, soon after the v2020.3.0 release, so if you update you should be good to go!

**Comment by leo-regov** [comment]
Oh thanks.
