### ISSUE TITLE
Swagger OpenAPI 3.0 import does not use tags to group requests in folders

### ISSUE THREAD

**Issue by BoKKeR** [getinsomnia/insomnia#2408]
**Describe the bug**
As described in this issue: https://github.com/Kong/insomnia/issues/1004
Swagger requests should be grouped based on tags. But this only works for swagger 2.0 json/yaml configs. Not for 3.0

**To Reproduce**
1. Importing into insomnia [v2.0](https://petstore.swagger.io/v2/swagger.json) results in folders being generated
2. Importing into insomnia [v3.0](https://dzone.com/articles/a-sample-openapi-30-file-to-get-started) results in folders NOT being generated

Both APIs use tags, but the parsing is not working for 3.0

**Expected behavior**
Have the same parsing 

**Screenshots**
v2 import
![image](https://user-images.githubusercontent.com/2664857/87407591-ad4c2f80-c5c2-11ea-852b-2328fa9d48b8.png)
v3 import 
![image](https://user-images.githubusercontent.com/2664857/87407720-d2d93900-c5c2-11ea-8198-39e68be2444d.png)

**Desktop:**
 - OS: macOS 10.15.5
 - Installation Method: app installer from site
 - App Version v2020.2.2

**Comment by phylor** [comment]
Using an OpenAPI v3 file with [global tags](https://swagger.io/docs/specification/grouping-operations-with-tags/), folders are correctly created for me in Insomnia 2020.3.3.

Note that you need to use global tags (`tags` defined at the root of your file). Local tags per request are ignored by Insomnia.

**Comment by develohpanda** [comment]
Yes that's right^, you need to use global tags, and then apply that global tag onto a request to achieve the desired behavior. 😄 

[Here](https://gist.githubusercontent.com/gschier/4e2278d5a50b4bbf1110755d9b48a9f9/raw/801c05266ae102bcb9288ab92c60f52d45557425/petstore-spec.yaml) is an example V3 spec that groups into folders as expected.

**Comment by BoKKeR** [comment]
Thanks for clearing this up!  

For anyone looking for the nestjs way of doing this:

The tags have to be declared both on the controller level and in the root main.ts file as following:

```ts
@ApiTags('part')                                    <---
@Controller('part')
export class PartController {
  constructor(private readonly partService: PartService) {}

  ....controllers
```


main.ts
```ts
  const options = new DocumentBuilder()
    .setTitle('keyb.io API')
    .setDescription('')
    .addTag('part', 'Parts description')            <---
    .addTag('search', 'Search description').        <---
    .setVersion('1.0')
    .addBearerAuth()
    .build()
```

The tag name has to match the one in the controller.

**Comment by dukesteen** [comment]
For anyone using asp.net 6.0, you can use a document filter to add the tags globally. Here is the code:

```cs
public class GlobalTagsDocumentFilter : IDocumentFilter
{
    public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    {
        var apiControllerClasses = typeof(IAssemblyMarker).Assembly.GetTypes()
            .Where(x => x.GetCustomAttribute<ApiControllerAttribute>() != null).ToList();

        var version = context.ApiDescriptions.First().GetApiVersion();
        
        var tagList = new List<OpenApiTag>();

        foreach (var apiControllerClass in apiControllerClasses)
        {
            var swaggerTagAttribute = apiControllerClass.GetCustomAttribute<TagsAttribute>();
            var apiVersion = apiControllerClass.GetCustomAttribute<ApiVersionAttribute>();

            if (apiVersion == null || !apiVersion.Versions.Contains(version))
                continue;

            if (swaggerTagAttribute != null)
            {
                foreach (var tag in swaggerTagAttribute.Tags)
                {
                    tagList.Add(new()
                    {
                        Name = tag
                    });
                }

                continue;
            }

            tagList.Add(new()
            {
                Name = apiControllerClass.Name.Replace("Controller", ""),
            });
        }
        
        swaggerDoc.Tags = tagList.OrderBy(x => x.Name).ToList();
    }
}
```

This utilizes the `[ApiController]` attribute and the `[Tags]` attribute introduced in asp.net core 6.

**Comment by kraftwerk28** [comment]
For anyone who wants to convert existing swagger.json to be suitable for Insomnia, you can use the following [jq](https://github.com/stedolan/jq) query:
```bash
$ jq '. + { tags: [.paths[][].tags[]] | unique | map({ name: . }) }' <swagger.json >with-tags-swagger.json
```
