### ISSUE TITLE
[Feature] Enable Insomnia to scan `.netrc`

### ISSUE THREAD

**Issue by deiga** [getinsomnia/insomnia#241]
This enables saving sensitive information in your `.netrc` file which many users most likely already use

**Comment by gschier** [comment]
This seems like it would be useful _and_ easy to implement. Curl has support for netrc out of the box. https://curl.haxx.se/libcurl/c/CURLOPT_NETRC.html

**Comment by matthewshirley** [comment]
I'll pick this one up if no one else is working on it. 👍

**Comment by moxuz** [comment]
I'll try to get a PR up for this @deiga
