### ISSUE TITLE
Error installing `insomnia-inso`

### ISSUE THREAD

**Issue by aaronhmiller** [getinsomnia/insomnia#2410]
**Describe the bug**
Cannot install Insomnia CLI (insomnia-inso) due to font-manager error
**To Reproduce**
Following installation guidance here: https://support.insomnia.rest/article/109-cli-installation
1. Install npm
2. Install `npm install -g insomnia-inso` or `sudo npm install -g insomnia-inso`
3. Receive following error:
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/insomnia-inso/node_modules/font-manager
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! font-manager@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the font-manager@0.3.1 install script.

**Expected behavior**
A clean install of insomnia-inso

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: 10.15.5 (MacOS)
 - Installation Method: npm
 - App Version: for Insomnia Designer -> Version 2020.3.3 (2020.3.3)

**Additional context**

**Comment by gschier** [comment]
Oops, it looks like we added `font-manager` to the CLI dependencies by mistake. We will remove it for the next release.

**Comment by develohpanda** [comment]
@aaronhmiller As a workaround for now, you can use Node v10, I'll make a note in the readme. We should, however, fix this. 😄
