### ISSUE TITLE
Header info randomly disappearing and having no effect

### ISSUE THREAD

**Issue by Rillian-Grant** [getinsomnia/insomnia#2411]
**Describe the bug**
Videos: https://drive.google.com/drive/folders/1f2cChQq-Zm_fX5-greVlHKa9PlCdtTl2?usp=sharing
See the video. Note: This happened even when using bulk edit.

**To Reproduce**
See the video.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation Method: snap
 - App Version 2020.3.0

**Comment by gschier** [comment]
Hey @Rillian-Grant, this was fixed in a point release in 2020.3.3 https://insomnia.rest/changelog/core/2020.3.3

**Comment by Rillian-Grant** [comment]
Surely it is an issue that the "stable" snap release has this breaking issue?

**Comment by Rillian-Grant** [comment]
@gschier ?

**Comment by DMarby** [comment]
Hi @Rillian-Grant!

Apologies, we had missed moving the point release from the edge channel to the stable channel on Snapcraft.
This should be remedied now, so you should get the latest version when you update/install from snap.

**Comment by Rillian-Grant** [comment]
Thank you very much
