### ISSUE TITLE
Cursor hided in Preview window

### ISSUE THREAD

**Issue by 3DRaven** [getinsomnia/insomnia#2412]
In preview response window we have cursor but it is hided.

1. OS Ubuntu linux
2. Insomnia 2020.2.2

**Comment by nijikokun** [comment]
@3DRaven do you still see the issue on `2020.3.3`?

**Comment by 3DRaven** [comment]
Yes is it steel here :)

**Comment by gatzjames** [comment]
Closing as this should be now fixed
