### ISSUE TITLE
In request url editor toltip windows is broken

### ISSUE THREAD

**Issue by 3DRaven** [getinsomnia/insomnia#2413]
1. Edit url in url editor field of request
2. Showed tooltip help window.
3. Click to another editor (may be a preview or other)
4. Tooltip window was not hide and still in screen and do not react to any events.
5. Only click to tooltip got this window hide. But then url was broken (edited with helped action in tooltip).

1. OS Ubuntu linux
2. Insomnia 2020.2.2

**Comment by 3DRaven** [comment]
It is "Some time bug"

**Comment by nijikokun** [comment]
Can you confirm that this also happens on `2020.3.3`?

**Comment by 3DRaven** [comment]
No, in 3.3 it fixed or I can't reproduce this behavior.

**Comment by 3DRaven** [comment]
Not. This bug is not fixed in 2020.3.3. I found this bug again. But 
if I click in url edition field -> tooltip window hided
if I click in another windows -> tooltip window not hided.

**Comment by gatzjames** [comment]
Closing as this was related to the code editor and should now be fixed
