### ISSUE TITLE
Disable automatic schema refetching when switching to another saved request

### ISSUE THREAD

**Issue by martasd** [getinsomnia/insomnia#2415]
**Is your feature request related to a problem? Please describe.**

I have saved a number of requests against my API:

![image (11)](https://user-images.githubusercontent.com/591911/87543968-f1643080-c6a5-11ea-9b2e-3c311d799660.png)

Every time I switch to a different request in my workspace the schema gets fetched from the server. The majority of cases the schema does not change, so there is no need to refetch it spending extra time and resources doing so. This happens despite having **Automatic Fetch** disabled and despite using **the same URL** for each request:

![image (12)](https://user-images.githubusercontent.com/591911/87544029-0e006880-c6a6-11ea-82a1-b25d661eea3f.png)

The pain point is that in order to be able to access the schema documentation, I need to wait (in my case about 10s) for the schema to be fetched every time I switch to a different request. This is very uncomfortable as I switch to various requests 20 or 30 times a day.

**Describe the solution you'd like**

I would like to be able to store the schema so that it could be used for multiple defined requests without being refetched. In other words, I would like to be able to disable the automatic fetching of schema when I switch to a different saved request.

**Describe alternatives you've considered**

I would love to be able to use a workaround, but I have not found any so far.

**Comment by martasd** [comment]
Hi @nijikokun. Does this feature request make sense? Do you know if there's any workaround to achieve this?

**Comment by eamigo86** [comment]
Hi @nijikokun, I have the same problem from some time ago and it's really painful to work like this, sometimes I needed to change to Playground to work faster.

__Describe the solution you'd like:__
Ideally, if the last URL the introspection call was made from could be saved or cached for some time (maybe ~1 hour), and if the user switches to another request in Insomnia and the graphql URL is the same, then schema will not be updated automatically. 
Right now, the user always could force the schema update manually if he wants from the "Refresh Schema" option.

**Comment by eamigo86** [comment]
Hi, This behavior continues to occur, please do not close the ticket.
