### ISSUE TITLE
Disappearing Pasted Text

### ISSUE THREAD

**Issue by chriscannon** [getinsomnia/insomnia#2416]
**Describe the bug**
When pasting any text into Insomnia it magically erases itself a couple seconds afterwards (see the screenshot below as an example). As far as I can tell it happens on all pasted text anywhere in the UI. I just happened to find it when setting an auth header.

**To Reproduce**
1. Copy text.
2. Paste it anywhere in the UI.

**Expected behavior**
I expect the text to remain there after pasting it.

**Screenshots**
![Screen capture](https://user-images.githubusercontent.com/439862/87556184-5a3ab100-c684-11ea-80a0-e468c072dc38.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Installation Method: Installer from insomnia.rest
 - App Version 2020.3.0
 - No plugins are installed

**Comment by Rillian-Grant** [comment]
See my issue: https://github.com/Kong/insomnia/issues/2411
It was closed because the issue has been fixed in 2020.3.3 but something really needs to be done as it seems that the version that is released as stable everywhere has this issue.

**Comment by chriscannon** [comment]
Great, thanks!

**Comment by DMarby** [comment]
Hi @chriscannon,

Thank you for the report!

As Rillian-Grant mentioned, this was resolved in a recent point release (2020.3.3), your app should automatically update to it.
To force an immediate upgrade, you can use the "Check for updates" button in the Preferences menu, or download it again from the website.

Please let us know if you run into any further issues.
