### ISSUE TITLE
Add ability to edit variable value

### ISSUE THREAD

**Issue by john-feusi-neuro** [getinsomnia/insomnia#2417]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently, when you click on a variable, you can edit which environment variable is selected using a dropdown. Below, there is a "Live Preview". It would be nice if in the "Live Preview" textarea we could edit the value stored in the variable.

It would be nice if this could be done for the "Edit Tag" modal as well. We have several CRUD requests hooked up where the update URL references the ID returned in the create request using the "Response -> Body Attribute". If I have an ID that I got from somewhere else I want to be able to use that without having to stomp on the work done to hookup the "Response -> Body Attribute".

**Describe alternatives you've considered**
To avoid stomping on the "Response -> Body Attribute", I've considered duplicating the request and using a plain variable but I don't like the idea of having so many duplicate requests.

**Additional context**

**Comment by tpluscode** [comment]
I would like to see this happen too

**Comment by tpluscode** [comment]
Please don't close this
