### ISSUE TITLE
Can I keep the schema in sync with git repository?

### ISSUE THREAD

**Issue by ProteanCode** [getinsomnia/insomnia#2422]
**What is your question?**
Can I keep the schema in sync with git repository? In a way that would allow me to re-export the whole json schema whenever I send / modify a request without manually going through the whole procedure maually.

**What is the context?**
Syncing the API schema using remote code repository

**Comment by gino8080** [comment]
same question, is possiible to change save and get insomia auto re-Import ?

**Comment by ProteanCode** [comment]
If the answer is "no" then its still a correct answer, anybody?

**Comment by nijikokun** [comment]
With designer, you can connect Insomnia to a git repository, push changes, and pull changes. Currently the schema is stored under the `.insomnia` folder and is wrapped with Insomnia meta information. There is an open issue (https://github.com/Kong/insomnia/issues/2082) to address this to allow support of multiple file specifications and specifications to be stored outside of the `.insomnia` folder.
