### ISSUE TITLE
when I  copy and past a URL, Insomnia does not do the request IN Insomnia Core 2020.3.0

### ISSUE THREAD

**Issue by obarra-dev** [getinsomnia/insomnia#2423]
**Describe the bug**
when I  copy and past a URL, Insomnia does not do the request

**To Reproduce**
1. Copy and past a valid URL
2. Click on 'Send'

**Expected behavior**
Insomnia shows: 'Error: URL using bad/illegal format or missing URL'

**Screenshots**
![image](https://user-images.githubusercontent.com/6526801/87719224-69efed80-c789-11ea-9fb7-0b0d5e6a8e09.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App Version Insomnia Core 2020.3.0

**Additional context**
URL GET http://10.30.40.15:9092/mycontext/core/payment/20200715/2000/1000/2000

**Comment by obarra-dev** [comment]
When I put a space before or after the URL, it works OK.

**Comment by gschier** [comment]
Hey @jabbarra! We issued a fix for this last week but it appears you haven't gotten the auto-update yet https://insomnia.rest/changelog/core/2020.3.3

**Comment by obarra-dev** [comment]
@gschier Great. Thanks for the answer. I'm going to get it.
