### ISSUE TITLE
GraphQL: Cannot use non-String prompt value in query variables

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [getinsomnia/insomnia#2424]
**Describe the bug**
I'm trying to use a prompt in our query variables JSON for a numerical value (our backend expects `phoneNumber` to be a `Long`, like `1234445555`):

```
{
	"phoneNumber": {% prompt 'Phone number', '', '', '', false, true %}
}
```

However, this results in an error: `Unexpected token % in JSON at position 19`. Of course if I quote it like:

```json
{
	"phoneNumber": "{% prompt 'Phone number', '', '', '', false, true %}"
}
```

It will render properly, but then the backend complains because it is a `String` value instead of a `Long`.

**To Reproduce**
1. Create a graphQL query or mutation which takes query variables
2. Add prompt into query variables without quotes around it
3. The error will display in the query variables section

**Expected behavior**
Ability to use non-String value (e.g. any valid JSON value) in prompt.

**Screenshots**
![Screen Shot 2020-07-16 at 6 53 40 PM](https://user-images.githubusercontent.com/52473140/87733665-1041f000-c796-11ea-8ab1-8f1847896e43.png)
![Screen Shot 2020-07-16 at 6 53 49 PM](https://user-images.githubusercontent.com/52473140/87733672-133ce080-c796-11ea-8872-9b402162c978.png)

**Desktop (please complete the following information):**
 - MacOS 10.15.5
 - Installation Method: https://insomnia.rest/download/#mac
 - App Version: 2020.3.3

**Comment by solarmosaic-kflorence** [comment]
Related: https://github.com/Kong/insomnia/issues/2264

**Comment by solarmosaic-kflorence** [comment]
This appears to be a duplicate of https://github.com/Kong/insomnia/issues/973 which I somehow did not find in my initial search. Closing.

**Comment by amber-yuan** [comment]
I meet the same issue, did it resolved?
![image](https://user-images.githubusercontent.com/15075236/104161288-967d7d00-542d-11eb-8dee-cf4b5a6c70ab.png)

**Comment by amber-yuan** [comment]
I meet the same issue, the response value is float, it's can't used in query variables.
![image](https://user-images.githubusercontent.com/15075236/104418702-4bd93d80-55b2-11eb-8b55-8b096cf18b7d.png)
