### ISSUE TITLE
The headers values cleared after some second

### ISSUE THREAD

**Issue by amir1369x** [getinsomnia/insomnia#2425]
Wen I add new value to a header's key, after some second the value was cleared

**Screenshots**
![111](https://user-images.githubusercontent.com/10446856/87882377-db8f9c00-ca14-11ea-81d1-e464ffab7311.jpg)

**Desktop:**
 - OS: Archlinux x64
 - Installation Method: from aur packages
 - Insomnia Version 2020.3.0

sorry for my bad english

**Comment by develohpanda** [comment]
We have released a fix for this in 2020.3.3 😊 please update your client!
