### ISSUE TITLE
Environment variables lost after switching tabs [Insomnia Designer]

### ISSUE THREAD

**Issue by goddard82** [getinsomnia/insomnia#2426]
**Describe the bug**
Environmental variables are lost after switching between Debug & Design tabs in Insomnia Designer.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Insomnia Designer & import a api spec (in this case, a .json file)
2. Click on the 'Design' tab & explore.
3. Command + E & open the environment variables. Set a host name, default headers, base path, etc.
4. Perform some actions, then switch to the Debug tab & run some requests.
5. Switch back to the 'Design' tab and back again.

**Expected behavior**
The environmental variables persist across tabs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Installation Method: pkg
 - App Version 2020.3.3

**Additional context**

**Comment by goddard82** [comment]
Apologies, likely a duplicate of #2228

**Comment by nijikokun** [comment]
Indeed it is, noticed it recently while unit testing, definitely can be frustrating! Going to close this one in favor of #2228
