### ISSUE TITLE
Insomnia removes accept header on its own!

### ISSUE THREAD

**Issue by hadifarnoud** [getinsomnia/insomnia#2429]
I can't type anything in Accept header as it removes it on its own. very annoying!
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/589808/88050102-769a8a00-cb6b-11ea-962b-46cdf7daabaf.gif)

Insomnia 2020.3.0
MacOS 10.15.5

**Comment by develohpanda** [comment]
Hi! Thanks for the report, this has been fixed in 2020.3.3 - please update your client 😄
