### ISSUE TITLE
[Feature] Allow wildcards in client certificate definitions

### ISSUE THREAD

**Issue by paulbrimicombe** [getinsomnia/insomnia#243]
Insomia currently allows users to add Client Certificates for specific hosts. I work in an organisation that uses client certs for virtually every web API, and I like to access these through Insomnia. Currently it is very time-consuming to define the same client certificate for every API that I use, especially when the hostname changes with the environment (e.g. `api.stage.mydomain.com` and `api.mydomain.com`).

I propose allowing wildcards in Client Certificate hostnames:

* Setting a Client Certificate for `*.mydomain.com` would provide that certificate to all subdomains of `mydomain.com`.
* Setting a Client Certificate for `api.*.mydomain.com` would provide that certificate for `api.sub.stage.mydomain.com`, `api.stage.mydomain.com` and `api.live.mydomain.com`.

**Comment by gschier** [comment]
I like it. This should be a fairly easy thing to implement. Are you interested in contributing @paulbrimicombe?

**Comment by paulbrimicombe** [comment]
I'm happy to help out @gschier - I had a quick look at the code and it looks like there aren't any tests around this. Am I right or am I looking in the wrong place?

I'll try to get a pull request together in the next couple of days.

**Comment by gschier** [comment]
You are correct @paulbrimicombe, there are no tests around this specific feature yet. However, it might be a good idea to extract the matching logic from `network.js:244` into a helper function and add tests to `network.test.js`.

**Comment by TeyimPila** [comment]
Hello, @gschier I am a newbie in JavaScript, looking for open source projects to get my hands dirty on. This would be a great way for me to learn from the experts. However, I don't know anything about TDD in JavaScript. Also, I would love to ask if this project uses any frameworks.

**Comment by gschier** [comment]
@TeyimPila, Insomnia doesn't use a strict TDD approach, so that's not a big deal. Only the important parts (ie. sending requests) have tests.

If you'd like to contribute, I suggest taking a look at the "Beginner Friendly" issues. https://github.com/getinsomnia/insomnia/issues?q=is%3Aissue+is%3Aopen+label%3A%22Beginner+Friendly+%E2%9D%A4%22

As far as frameworks, Insomnia uses React for the UI.

**Comment by paulbrimicombe** [comment]
Hi @gschier should we close this now that PR #262 has been merged and released?

**Comment by gschier** [comment]
Yep, nice catch @paulbrimicombe! I usually add "Closes #ISSUE" to the PR description if it doesn't have it but I must have missed that one.
