### ISSUE TITLE
Bug: query parameters are ignored when importing Postman collection

### ISSUE THREAD

**Issue by NSExceptional** [getinsomnia/insomnia#2434]
Title. I exported a collection from Postman with a request that has query parameters, and they are not properly imported into Insomnia. It appears to only import the plain URL itself.

**Comment by NSExceptional** [comment]
BUMP

**Comment by wongstein** [comment]
Hi @NSExceptional , sorry for the delayed response.  Have you been able to replicate this with the latest Insomnia version?  And could you provide a test json?

**Comment by wongstein** [comment]
I'm going to close this for now.  Please feel free to reopen when you get time to reproduce on the latest version of Insomnia
