### ISSUE TITLE
Bulk edit for request Query parameters seems broken.

### ISSUE THREAD

**Issue by ewh** [getinsomnia/insomnia#2445]
**Describe the bug**
Bulk edit for request Query parameters is failing (silently not responding).

**To Reproduce**
From the request `Query` tab, click 'Bulk Edit'. Nothing happens in the UI.

**Expected behavior**
Clicking 'Bulk Edit' would presumably enter the bulk edit editor (exactly like when clicking 'Bulk Edit' in the `Header` tab). Instead, nothing seems to happen and in the Insomnia DevTools, this error message is visible: `"Uncaught TypeError: updateSettingsUseBulkParametersEditor is not a function"`.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation Method: snap
 - App Version: 2020.3.3

**Comment by luca0898** [comment]
same hare!

**Environment:**
Windows 10 PRO (build 1909)
Installation method: EXE file
App Version: 2020.3.3
