### ISSUE TITLE
Authentication method of requests reset in debug tab when switching tabs.

### ISSUE THREAD

**Issue by crijke** [getinsomnia/insomnia#2446]
**Describe the bug**
Authentication method of requests in debug tab is reset when switching tabs. 

**To Reproduce**
1. Go to debug tab.
2. Set authentication method of a request to a method different from 'No Authentication' (e.g. Bearer Token and enter token settings.)
3. Switch to design tab.
4. Switch back to debug tab.
5. Authentication method of request has been reset to 'No Authentication'. 

**Expected behavior**
Authentication method of requests should be persisted and not reset to default values when switching tabs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Installation Method: Website Download
 - App Version Insomnia Designer 2020.3.3 (2020.3.3)

**Additional context**

**Comment by nijikokun** [comment]
Seems like another auto-generation artifact related to #2437

**Comment by gschier** [comment]
This is currently the expected behavior. Each time you switch to Debug, all requests are re-generated from the specification. If you want to modify something in the Debug tab, you will first have to duplicate the request (or you can update it within the spec).

**Comment by crijke** [comment]
Ah, I see! My spec contains authentication information however, that is not reflected in the debug tab (see below), so I thought I need to manually update it in the debug tab. 

```
components:
  securitySchemas:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT

```
and     
```
security:
   - bearerAuth: []
```
for individual operations. 

Is this the correct way to do it?

Also I think it would be better to disable the input fields for generated reqeusts instead of silently deleting values on tab change.

**Comment by wdawson** [comment]
Hey @crijke , this issue got moved to discussions by mistake (it was mislabeled). But I just tried to reproduce on Insomnia 2021.4.0 and could not. Are you still seeing this issue?

**Comment by gatzjames** [comment]
Closing as auto-generation from design is no longer happening and shouldnt create this issue
