### ISSUE TITLE
Workspaces for Insomnia Designer

### ISSUE THREAD

**Issue by Nahasean94** [getinsomnia/insomnia#2448]
Insomnia Core supports the concept of Workspaces where one is able to run multiple projects in isolation.
I am unable to find that setting in Insomnia designer. What I see is ability to switch environments say prod and test, but I would want to design multiple projects and export the designs to relevant teams for implementation. Is this feature currently supported in Insomnia Designer?

**Comment by nijikokun** [comment]
Insomnia Designer currently uses documents as separate projects, hopefully this answers your question!

**Comment by Nahasean94** [comment]
I have been using documents but if you have many projects with modules/microservices that share the same names, it quickly becomes to chaotic to differently name them (the problem am facing now). Workspaces help design/create files for different projects in neat isolation.

**Comment by Nahasean94** [comment]
@nijikokun , are there any plans to add workspaces in future? that way I will know what to do in their indefinite absence

**Comment by filfreire** [comment]
@wdawson closing this one, Designer isn't supported now for a long time 😅
