### ISSUE TITLE
Share workspace with 'team name' drop down list shows teams that i left

### ISSUE THREAD

**Issue by natalywadie** [getinsomnia/insomnia#2450]
**Describe the bug**
Teams that i left still appear in share with drop down list and when i try to select a current team, the drop down reloads and still selects the old team

**To Reproduce**
1. Add the user to a team
2. Sync some folders with the team
3. Add the same user to a second team
4. Go to Manage Teams from the user's account
5. Click on 'leave' from the first team
6. Share some different folders with the second team by a different user
7. Open Insomnia Core app where the user is logged in
8. Click on sync button
9. Click on Share Settings
10. Check the 'Share with' drop down list

**Expected behavior**
Only the current team should be displayed, instead old team is displayed and when i try to select the new team, the drop down list reloads and keeps old team selected

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Installation Method: Portal Download
 - App Version v2020.3.3

**Additional context**
None

**Comment by kreosus** [comment]
Hi @natalywadie 

Are you still able to reproduce this error with our latest release: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.2

**Comment by wongstein** [comment]
I am closing out this issue, if this problem reappears please feel free to re-open or make a new Github issue.
