### ISSUE TITLE
Lint errors don't show in editor gutter after reopening document

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2456]
**Describe the bug**
I have a specification which contains errors. When I navigate to home and reopen the document, or navigate to debug/test and come back to design, the gutter does not show lint errors. It refreshes the errors, after I start typing.

**To Reproduce**
1. Introduce lint error into spec
2. Observe errors in gutter
3. Click on "Documents" to go 
4. Click on the document again to open it
5. Observe no errors in gutter
5. Start typing
5. Observe errors in gutter

**Expected behavior**
Should always show errors in gutter if they exist

**Screenshots**
![2020-07-28 12 54 06](https://user-images.githubusercontent.com/4312346/88606850-d6e07d00-d0d1-11ea-976c-40af37691c4e.gif)

**Desktop (please complete the following information):**
 - OS: 10.15.6
 - Installation Method: dev
 - App Version 2020.3.3

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

**Comment by filfreire** [comment]
This one is no longer reproducible in our [latest stable release](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2).
