### ISSUE TITLE
Can no longer use bearer tokens.

### ISSUE THREAD

**Issue by danthemanvsqz** [getinsomnia/insomnia#2461]
Currently when I copy a bearer token into the form the text disappears and when I copy the request to curl I get the header set as authorization: Bearer undefined 

I'm on a Mac to reproduce select Bearer from the authentication selections and copy a bearer token into the form. Then make a request and verify that the token is no longer there.

![image](https://user-images.githubusercontent.com/1470711/88726103-f4b5de00-d0e1-11ea-845b-6522bfda5032.png)

![image](https://user-images.githubusercontent.com/1470711/88726254-3e062d80-d0e2-11ea-85b4-146acb6d2946.png)

![image](https://user-images.githubusercontent.com/1470711/88726319-56764800-d0e2-11ea-826f-3f9e71776a48.png)

Curl request:
curl --request POST \
  --url https://fake-url.com/graphql \
  --header 'authorization: Bearer ' \
  --header 'content-type: application/json' \
  --data '{...}'

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Installation Method: [e.g. homebrew cask
 - App Version 2020.3.0

**Additional context**

**Comment by gschier** [comment]
We have fixed this issue in the latest release https://insomnia.rest/changelog/core/2020.3.3
