### ISSUE TITLE
Swagger version field is provided but it doesn't render

### ISSUE THREAD

**Issue by ricardopt** [getinsomnia/insomnia#2463]
**Describe the bug**
I've added a valid swagger yaml definition (I've been using editor.swagger.io to develop the spec and it's working on production) the first line clearly states the version `swagger: '2.0' ` and the render asks to specify the version.

**Tests done**
I've tested with " as well as '  so it's not a matter of quotation marks.

**Screenshots**
![image](https://user-images.githubusercontent.com/25549631/88780890-8c1f3d80-d183-11ea-9660-ce83c30c25ef.png)

**Desktop (please complete the following information):**
 - Installation Method: linux snap
 - App Version 2020.3.3

**Comment by nijikokun** [comment]
Welcome @ricardopt 👋 

Is it possible to provide the specification so we can test? I'm unable to replicate locally.
