### ISSUE TITLE
Unit Testing Design Implementation @sonicyeti

### ISSUE THREAD

**Issue by sonicyeti** [getinsomnia/insomnia#2464]
We will be performing the following visual and functional tweaks to the existing unit testing MVP.

![unit_testing](https://user-images.githubusercontent.com/52717970/89420367-99e33e80-d700-11ea-9a28-4ed281ed5b35.png)

### Left Rail
**1.**  Integrate new sidebar component in the following format: 
TEST SUITE NAME
	- Test Name
	- Test Name
	- Test Name
TEST SUITE NAME
	- Test Name
**2.** Leverage new sidebar component’s first item contextual menu to replace “New Test Suite” button.

### Center Stage
**3.** ~~Dropdown icon padding (address at component level for global fix)~~
**4.** ~~Horizontally center the lint hint iconography (style like design mode)~~ - **NOT FIXING**
**5.** ~~Max height on testing > overflow scroll 20 lines~~
**6.** ~~Remove dropdown > Play Icon button for Run (NO LABEL)~~
**7.** ~~Remove dropdown > Trash Icon button for Delete (NO LABEL)~~
**8.** ~~Convert existing method dropdown to styled one (leverage method color styling)~~  - **STYLED EXISTING**
**9.** ~~Consistently style the buttons leveraging primary and secondary visual treatment. This issue is more apparent on themes with a dark BG but essentially we have 4 different button styles going currently.~~ 

### Right Rail
**10.** ~~Address padding & line-height issues~~

### Global
**11.** ~~Add a subtle pencil hint on the hover state for all editable input fields. (Environment name via CMD + E, Test & Test Suite Name etc.)~~
**12.** Address issue where long labels on editable fields blows out the layout.
**13.** ~~Address issue where clearing (then saving) and empty label results in the user being unable to see or edit it.~~

### Progress
3, 6, 7, 9: https://github.com/Kong/insomnia/pull/2534
10: https://github.com/Kong/insomnia/pull/2533

### Default Empty State
@erickrico Erick provide me with empty state, mirror Debug

**Comment by filfreire** [comment]
@wdawson, I'm currently cataloguing through all unit test feature related issues.

Marking this one as closed, don't think it's applicable right now.
