### ISSUE TITLE
[Improvement] Improve dock icon size

### ISSUE THREAD

**Issue by vavgustov** [getinsomnia/insomnia#247]
seems dock icon size smaller than it should be

os: os x 10.11.6

![insomnia_dock_icon](https://cloud.githubusercontent.com/assets/312873/26422741/bd631d1a-40d3-11e7-99fb-91f2d3f4bbf7.png)

**Comment by gschier** [comment]
Hey @vavgustov. You are correct. I'm going to update it to be the same size as some other popular ones.

![image](https://cloud.githubusercontent.com/assets/587576/26424793/464a57e4-4087-11e7-9284-d47f8a17dcfa.png)

**Comment by gschier** [comment]
Just updated this. It will be in the next release! 💯
