### ISSUE TITLE
Shift+Tab functionality changed in 2020.3.3

### ISSUE THREAD

**Issue by robross0606** [getinsomnia/insomnia#2470]
The latest version (v2020.3.3) of Insomnia seems to have removed the ability to auto-indent a GraphQL request.  In previous versions keyboard shortcut `SHIFT+TAB` did this.  In the newest version, it shifts everything back one tab but doesn't fix indents.  What is the new shortcut key for auto-indenting GraphQL?

**Comment by philippegirard** [comment]
Open preferences -> Keyboard. It's called `Beautify Active Code Editor` now.
![Screen Shot 2022-02-01 at 4 04 30 PM](https://user-images.githubusercontent.com/8143308/152051225-82121f22-6666-469f-9405-8dd7704901f5.png)
