### ISSUE TITLE
Select all text operation is painfully slow with a large response

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2478]
**Describe the bug**
Code-mirror is great at efficiently rendering a very large amount of text, however both the response focus hotkey (`cmd + '` by default, which selects all text) and the select all (`cmd + a`) operations are _painfully_ slow, and also cause the application to become unresponsive.

Documents:
- 206 KB `https://github.com/tpn/pdfs/raw/master/A%20Comparison%20of%20Programming%20Languages%20in%20Economics%20(16-Jun-2014).pdf`
- 2.2 MB `https://eloquentjavascript.net/Eloquent_JavaScript.pdf`

**To Reproduce**
1. Create a new get request for one of the PDF documents above 
2. Focus the response with the hotkey `cmd + '` OR click on the response and select all `cmd + a`
3. Observe delay, and that the application becomes unresponsive

**Expected behavior**
1. Responsiveness
    - Don't select all if large response? the `response-viewer` has a `blockingBecauseTooLarge` state, which we could use to ignore the select-all step during the response focus hotkey handler https://github.com/Kong/insomnia/blob/e3f9e3c1d4854474053e4ef5b037f97a4fb1aa51/packages/insomnia-app/app/ui/components/viewers/response-viewer.js#L182-L195
2. A faster way to copy all contents
    - Potentially add a `CopyButton` to all appropriate response viewers? ![image](https://user-images.githubusercontent.com/4312346/89152052-685e5c00-d5b6-11ea-9938-19bf5d0c9ff2.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Installation Method: DEV
 - App Version: v2020.3.3

Loosely related to https://github.com/Kong/insomnia/issues/2397

**Comment by aszx87410** [comment]
I like the idea of adding a CopyButton!  But we need to think about the position of the button. The position shown in the picture is blocking the text under the button, I am not sure if it will be an issue. 

Another question for responsiveness, what size should be consider large? maybe > 500kb or 1024kb? And when user try to select the large text, it's better if we can display a message to user, saying that "The response is too large to select. If you just want to copy the response, you can click the button at top right corner."

One more thing to add, maybe we can add a hot key for coping the response to clipboard, it might be helpful as well.

**Comment by develohpanda** [comment]
> The position shown in the picture is blocking the text under the button, I am not sure if it will be an issue.

In the query preview on the left hand side it's _not_ blocking text; text is wrapping around it. 

![2020-08-04 15 47 23](https://user-images.githubusercontent.com/4312346/89250918-ee87aa80-d669-11ea-9fd1-baa3713547a2.gif)

But, I don't quite think that's quite as easy to achieve with CodeMirror, so yes we will need to investigate positioning. Open to ideas; how about in the preview mode dropdown? That has an Actions section, although I would favor a CopyButton if we can find a nice way to integrate it. 😄 

> what size should be consider large?

There are two usages in `ResponseViewer` that check size; one consumes a LARGE_RESPONSE_MB constant, and the other consumes HUGE_RESPONSE_MB. If we could use one of these (or the state derived from it) that would be nice, otherwise any reasonable value that results in a significant slow down of the select-all operation.

Just a note, we wouldn't want to 'disable' select-all altogether; if there is a lot of text it's expected to be slow. It would be good to make more efficient the most likely scenarios where select-all causes slowness: the focus response hotkey (stop automatically selecting all if too large), and copy all text (bypass codemirror with a dedicated copy button).
