### ISSUE TITLE
Escaped tags are rendered on sending a request

### ISSUE THREAD

**Issue by tafli** [getinsomnia/insomnia#2483]
In a requestbody, espaced tags like `{% {{key}} %}` should be rendered and sent as `{{key}}`. Instead it is presented as escaped (grayed out), but on send it will try to render it. Following error is shown: Failed to Render Request. Error: tag name expeced. Caused by the following field: line 0 of Request.body.text.

It is possible to deactivate rendering of a request body in the request settings (Skip rendering of request body). This, however, is not the solution if you use tags that should be rendered and text like {{tag}} that should submitted as such.

**To Reproduce**
1. Create a new POST request (URL does not matter). Select JSON as body.
2. Enter following JSON as body: `{ "key": "A text containing and escaped {% {{tag}} %}." }`
4. Tag will be rendered as `{{tag}}` with a grey background (raw text).
5. Send the request, error appears.

**Expected behavior**
I expect to be able to send requests with tag-like text which is rendered as raw text, as described in Nunjuck documentation: [Nunjuck RAW](https://mozilla.github.io/nunjucks/templating.html#raw)

**Information:**
 - App Version [2020.3.3]

**Comment by nijikokun** [comment]
@tafli I believe raw should be used like following, I haven't tested (will after posting):

```nunjucks
{% raw %}
{{tag}}
{% endraw %}
```

Update, looks like this is the proper usage, let me know if this works for you:

![image](https://user-images.githubusercontent.com/198276/89568646-75f32c00-d7d8-11ea-9e4f-f701cf8617b3.png)

**Comment by tafli** [comment]
@nijikokun Yes, this works indeed as I expect! Thanks!

I also did some other research and found an example with description [here](https://jinja.palletsprojects.com/en/2.11.x/templates/#escaping).

Probably there can be a 'raw' function in the tag edit dialog? When I click now on the tag, it is still marked as 'Base64' function. It might also be easier for others when looking for escaping text.

But for me it's fine this way and I can work with it. Close the issue or use it as Feature Request.

**Comment by gatzjames** [comment]
Closing as resolved
