### ISSUE TITLE
Provide an offline mode for requests

### ISSUE THREAD

**Issue by Lysander** [getinsomnia/insomnia#2486]
It would be nice to have an offline mode (like [HTTPie has](https://httpie.org/docs#offline-mode)) in order to get the *full* HTTP request in a *raw form* even if there is no working / reachable webservice.

I am aware of the *timeline* function but this simply fails *before* it prints out the HTTP request!
Imagine a simple GET request to a not running / existing service on ``localhost:8080``:
```
* Preparing request to http://localhost:8080/
* Current time is 2020-08-05T08:08:21.295Z
* Using libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0
* Using default HTTP version
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 2 cookies
* Connection 11 seems to be dead!
* Closing connection 11
* Hostname localhost was found in DNS cache
*   Trying ::1:8080...
*   Trying 127.0.0.1:8080...
* connect to ::1 port 8080 failed: Connection refused
* connect to 127.0.0.1 port 8080 failed: Connection refused
* Failed to connect to localhost port 8080: Connection refused
* Closing connection 12
```

Only if there *is* a response, you get the request printed:
```
* Preparing request to http://localhost:8080/
* ... left out details
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#13)
* Server auth using Basic with user 'user'

> GET / HTTP/1.1
> Host: localhost:8080
> Authorization: Basic dXNlcjpwYXNzd29yZA==
> User-Agent: insomnia/2020.3.3
> Cookie: JSESSIONID=D33AB17E755CBB53551AD17FC81534F6
> Content-Type: application/json
> Accept: */*

... response left out...
```

**Comment by nijikokun** [comment]
@Lysander interesting feature from HTTPie, wonder if CURL has the same functionality as it's the underlying network lib

**Comment by Lysander** [comment]
> 
> 
> ... wonder if CURL has the same functionality as it's the underlying network lib

Do you really know that? I haven't seen anything in their code that links to anything none python stuff! Imho it is based upon [requests](https://requests.readthedocs.io/en/master/#) which itself doesn't seem to rely on curl.
