### ISSUE TITLE
Masked Prompt variable is visible in hover text

### ISSUE THREAD

**Issue by Lyra2108** [getinsomnia/insomnia#2487]
**Describe the bug**
For BasicAuth I would like to use Prompts to store the password a little bit better. The issue is that while the value is masked if I hover over the Prompt variable, it is no longer be masked if I hover over the variable which contains the Prompt result.
I need to use a variable in an enviorment, because for different servers I need different passwords (and for some it is fine if it is in plain text)

Masked while hovering the Prompt:
![grafik](https://user-images.githubusercontent.com/2102141/89402980-f43bc980-d717-11ea-8cdd-2cf0f6ecfe51.png)

Unmasked while hovering the variable:
![grafik](https://user-images.githubusercontent.com/2102141/89403025-0289e580-d718-11ea-98b9-180e05c939ed.png)

**To Reproduce**
1. Go to 'Manage Enviroment'
2. Add an enviroment variable whos value is a masked prompt
3. Send a request with the prompt and fill it once

**Expected behavior**
I would expect it to be masked every where like it is when I hover the prompt.

**Comment by kreosus** [comment]
Hi @Lyra2108 

Have you been able to reproduce this issue on our newest release, located here: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.4 I await your reply to proceed accordingly.

**Comment by Lyra2108** [comment]
Yes this issue is still reproducable with the latest version.
