### ISSUE TITLE
Read:Content Meaning when compression is enabled

### ISSUE THREAD

**Issue by vaibhavpacharya** [getinsomnia/insomnia#2488]
**What is your question?**
I see read and content properties when i mouse over the response after adding compression in the request header.
Please explain the meaning of the properties.
**What is the context?**
Testing compression for API's.
![read_content](https://user-images.githubusercontent.com/16417441/89452016-e1be9180-d711-11ea-9e49-8d17bdcee7f9.jpg)

**Comment by nijikokun** [comment]
Good question @vaibhavpacharya 

- *Read* is the [entire response payload size](https://github.com/Kong/insomnia/blob/88b0bb784f126fcc880f1db596aa7eb76b75b9fe/packages/insomnia-app/app/plugins/context/response.js#L40)
- *Content* is the [response body payload size](https://github.com/Kong/insomnia/blob/88b0bb784f126fcc880f1db596aa7eb76b75b9fe/packages/insomnia-app/app/plugins/context/response.js#L58)
