### ISSUE TITLE
How about some testing functionality?

### ISSUE THREAD

**Issue by 3DRaven** [getinsomnia/insomnia#2494]
I have lot of requests as "test request for my api". For comfortable testing need to:

1. Start many requests as "one group".
2. Check to responses in this request is same as last time executed. If we have diff, need mark request as "changed response" 
3. Show diff between last and current responses in response preview window.

**Comment by nijikokun** [comment]
@3DRaven - Want to make sure I understand the request correctly, you'd like to be able to make a request, save the response, make the request again, and compare the previous response to the current response?

**Comment by 3DRaven** [comment]
Yes. But need repeat not only one request, need to repeat group of requests (all requests in group) and mark requests where old and new response is different, and show diff.

**Comment by 3DRaven** [comment]
And need to mark group of requests as "contans different responses" (icon or other manner)

**Comment by 3DRaven** [comment]
It may be simplified.

Need just add indicator "two latest responses is same". If we have differences, need to set this indicator as false.

Because for testing we need to manually check diff in current version of app. And many of regression tests is just "all responses is still same".
