### ISSUE TITLE
[Bug] Deleted my folder?!

### ISSUE THREAD

**Issue by krainboltgreene** [getinsomnia/insomnia#250]
## Overview
- `Insomnia Version:` Version 5.1.0 (5.1.0.326)
- `Operating System:`  10.11.6 (15G1510)
- `Summary: ` I no longer have an entire root level folder of requests, despite having a request open that came from that root folder

## How To Reproduce

No freaking clue. I have syncing on and my coworker didn't delete the folder.

**Comment by gschier** [comment]
Hi @krainboltgreene.

I have a feeling that this might be related to #251. In order to help, I'll need some more information from you.

- Do your coworkers still see the missing requests?
- Can you confirm that the sidebar filter is empty?
- Can you do a data export from the app and check if the missing requests appear in there?
- Can you send the email address of your account to support@insomnia.rest so I can look at the logs on my end?

You can also download the previous version of the app here: https://github.com/getinsomnia/insomnia/releases/tag/v5.0.20

**Comment by gschier** [comment]
@krainboltgreene if you feel like it would be easier, we can also talk 1-on-1 in the [Insomnia Slack Group](chat.insomnia.rest) or set up a video call.

**Comment by gschier** [comment]
@krainboltgreene I just found your account and, although I cannot see the data (due to encryption), I count ~25 folders, ~40 requests and ~5 environments are synced to the backend.

**Comment by krainboltgreene** [comment]
@gschier 

> Do your coworkers still see the missing requests?

Ours look the same. I used manual syncing and he had automatic.

> Can you confirm that the sidebar filter is empty?

Yes, we also filtered for it.

> Can you do a data export from the app and check if the missing requests appear in there?

The requests aren't in the export.

> I count ~25 folders, ~40 requests and ~5 environments are synced to the backend.

I have 14 folders locally.

**Comment by gschier** [comment]
@krainboltgreene so just one of the root-level folders was deleted? 

I _do_ see one synced folder on your account that is marked as `deleted`, although it looks like it was last synced on the 18th. Does that timeframe sound correct? 

Also, do you remember the name of the folder? Names and IDs are the only attributes stored unencrypted.

**Comment by krainboltgreene** [comment]
@gschier Since I manually sync, that sounds correct :(

**Comment by krainboltgreene** [comment]
@gschier The name is "Commerce".

**Comment by gschier** [comment]
That's odd. The folder "Commerce" is not marked as deleted and was last synced on the 19th.

A couple more things:

- When you checked the export, did you export with "All Workspaces"?
- Can you try logging out (via Preferences > Account) and logging back in again?

**Comment by krainboltgreene** [comment]
> When you checked the export, did you export with "All Workspaces"?

No, only the current workspace which is the one with the missing root level folder, but it's not in all either.

> Can you try logging out (via Preferences > Account) and logging back in again?

It "Synced" me up, but no new root folder :(

**Comment by gschier** [comment]
Ok @krainboltgreene, I have one last idea for now. 

The following file contains the DB that stores RequestGroups (folders) in JSON format. Can you take a look at it and see if anything looks strange?

```
$HOME/Library/Application\ Support/Insomnia/insomnia.RequestGroup.db
```

There are two things that I think would cause this problem:

1. the folder doesn't exist in the DB file at all. (In this case, the logout/login should have brought it back)
2. the folder has the wrong `parentId` attribute. If it is a root level folder, `parentId` should be the ID of the workspace. (should be the same as other root-level folders in this file)

---

Also, I forgot to suggest this, but you could also try locating the requests in `$HOME/Library/Application\ Support/Insomnia/insomnia.Request.db`.

**Comment by krainboltgreene** [comment]
The file exists, it's 39 lines long. Nothing malformed. I see a "Commerce" entry, and some of the children.

**Comment by krainboltgreene** [comment]
I have found the requests in the requests database.

**Comment by gschier** [comment]
@krainboltgreene is the `parentId` attribute of "Commerce" the same as the other entries in the file?

**Comment by krainboltgreene** [comment]
Boom, looks like they had a folder id as their parent, but it wasn't listed in the UI. I've changed to to match the other roots and it's solved.

**Comment by gschier** [comment]
Hmm, is it possible that the folder was accidentally dragged into another folder? That's the best idea I can come up with for how this could have happened.

I'm glad you were able to recover it, though!

**Comment by krainboltgreene** [comment]
Thanks so much for the help! There was a flurry of UI activity right before it happened but I don't know what I did exactly. Perhaps constraints should be written about the tree?

**Comment by gschier** [comment]
You're welcome!

Nested folders is a feature of Insomnia. If the `parentId` that you changed was a valid folder, the UI would have displayed your folder nested inside of the one it referenced. Did you happen to back up the file before modifying it? I'd be curious to see if the folder it was referencing was indeed a valid folder inside your workspace.
