### ISSUE TITLE
OAuth2.0 populate `access_token` to env

### ISSUE THREAD

**Issue by SerKnight** [getinsomnia/insomnia#2503]
**Is your feature request related to a problem? Please describe.**
I am using the OAuth2 auth tab and love the tooling around refreshing, adding scopes, encoding helpers.

However for all the other routes - we use `Authorization: Bearer #{access_ token}` tab like most OAuth2 API's once the token_set is generated you only need the JWT.

This requires copy & pasting the `access_token` back into the environment which is shared across my whole workspace and all other API calls.

**Describe the solution you'd like**
I know it is possible to setup OAuth2 flow manually and chain the access_token back into my env var: https://support.insomnia.rest/article/43-chaining-requests - But if we go this route, we loose the convenience of the OAuth2.0 tab refresh & client id/secret helpers.

It would be great to have the ability to set the `access_token` in the shared environment after a successful `access/refresh` generation

**Describe alternatives you've considered**
Request chaining

**Additional context**
Let me know if this is on the radar, or if there is another workaround I haven't considered

### OA2 helper Tab
> Manually refresh and copy paste new token set when you need to interact w/ api
<img width="505" alt="Screen Shot 2020-08-10 at 1 11 11 PM" src="https://user-images.githubusercontent.com/2935387/89820907-f97b8880-db0a-11ea-8862-2c1be2c66458.png">

### ENV Var
> Variable where we store (copy/paste) recently generated access token
<img width="559" alt="Screen Shot 2020-08-07 at 10 24 11 AM" src="https://user-images.githubusercontent.com/2935387/89821072-41021480-db0b-11ea-9eba-ac1c063e04df.png">

###  Header
> All other API requests that don't need the OA2 tab, but just the `Authorization: Bearer #{access_token}` header
<img width="674" alt="Screen Shot 2020-08-10 at 1 11 46 PM" src="https://user-images.githubusercontent.com/2935387/89820989-1748ed80-db0b-11ea-967c-1dd8e52b94fc.png">

**Comment by dmythro** [comment]
Oh, that would be awesome and a completely automated flow for me!

**Comment by alexandrim0** [comment]
Also vote for this feature!

**Comment by nijikokun** [comment]
I'm wondering if this could be a plugin?

**Comment by nijikokun** [comment]
This is a great candidate for a plugin, there is even [some prior art](https://github.com/incureforce/insomnia-plugin-oauth2-token-handler/blob/master/plugin.js) which might already satisfy your needs!

**Comment by kitingChris** [comment]
There is now a plugin that handles the OAuth access token.
https://insomnia.rest/plugins/insomnia-plugin-oauth2-token-provider

**Comment by SerKnight** [comment]
Beautiful - Thank you to the developer and for updating the thread..

Note that I did have to change the oA2 token url which is based on the providers token `POST` base url, not the callabck URL. In my case it matched the alternative example in the readme:

`https://identity.xero.com/connect/token`
so in your environment you put 
```
"oauth2_token_url_suffix": "connect/token"
```
