### ISSUE TITLE
[Performance] Latest version using 100% CPU and 2gb of memory?

### ISSUE THREAD

**Issue by krainboltgreene** [getinsomnia/insomnia#251]
## Overview
- `Insomnia Version:` 5.1.0
- `Operating System:`  MacOS

![screen shot 2017-05-24 at 4 04 57 pm](https://cloud.githubusercontent.com/assets/334809/26429264/cf33a714-409a-11e7-91cd-6adf00f095ba.png)
![screen shot 2017-05-24 at 4 05 02 pm](https://cloud.githubusercontent.com/assets/334809/26429263/cf31baf8-409a-11e7-9e2d-da4fd4b24e0f.png)

**Comment by gschier** [comment]
@krainboltgreene how quickly does it jump to this after quitting and restarting the app?

**Comment by krainboltgreene** [comment]
It seems like it's much better behaved.

**Comment by gschier** [comment]
Ok. Let me know if you see it happen again 👌
