### ISSUE TITLE
Insomnia Designer with Schema produces RequestBody null in Debug

### ISSUE THREAD

**Issue by twobiers** [getinsomnia/insomnia#2524]
**Describe the bug**
When Debuging a Request which is defined by using a schema as request body the request body in debugging view is null

**To Reproduce**
The following is a minimal OpenAPI 3 config which reproduces the bug:
```yml
paths:
  "/foo":
    post:
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Foo"
components:
  schemas:
    Foo:
      title: Foo
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
```

**Expected behavior**
As the Example Request Body is generated using the schema I would expect it to be filled in in the debug view as well.

**Screenshots**
The generated Request Body in Preview:
![RequestBody Preview](https://i.imgur.com/wdTcaiw.png)
The Request Body in Debug View:
![RequestBody Debug View](https://i.imgur.com/iNKks5A.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 64 Bit
 - Installation Method: Installer
 - App Version: 2020.3.3

**Additional context**

**Comment by bimbimprasetyoafif** [comment]
Hi, i am also. is it wrong with my swagger or insomnia. idk

**Comment by sdarmofal** [comment]
Hi. I have this problem too. I think that it is problem with $ref in requestBody. For example:
If I tried to use this OpenAPI schema I've got null value in debug:
```yaml
openapi: '3.0.3'
info:
  title: Application API
  description: Documentation for API
  version: v1.0.0
paths:
  /api/auth/login/:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
components:
  schemas:
    Login:
      type: object
      required: ["password"]
      properties:
        username:
          title: Username
          type: string
        email:
          title: Email
          type: string
          format: email
        password:
          title: Password
          type: string
          minLength: 1
```
I've tried another schema and this works well:
```yaml
openapi: '3.0.3'
info:
  title: Application API
  description: Documentation for API
  version: v1.0.0
paths:
  /api/auth/login/:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              login:
              type: object
              required: ["password"]
              properties:
                username:
                  title: Username
                  type: string
                email:
                  title: Email
                  type: string
                  format: email
                password:
                  title: Password
                  type: string
                  minLength: 1
```
This problem occurs in Insomnia Core too. I'm working on Ubuntu 20.04.1

**Comment by dagi3d** [comment]
any update on this?

**Comment by ftpman** [comment]
Hello,

I just changed from `openapi: '3.0.3'` to `openapi: '3.0.2'` and it works well !!

**Comment by aqmalafiq** [comment]
having same issue, any update?

**Comment by develohpanda** [comment]
Thank you for reporting this! I did some investigation and it seems related to the fact that the version of `swagger-parser` used by `insomnia-importers` does not support OpenAPI 3.0.3, and is the likely cause of this issue. As noted above, changing the spec version to 3.0.2 works as intended.

The fix for this, I imagine, simply involves updating to the latest version of `swagger-parser`

This is loosely related to https://github.com/Kong/insomnia/issues/2977, which has an open PR

**Comment by bimbimprasetyoafif** [comment]
> 
> 
> Hi. I have this problem too. I think that it is problem with $ref in requestBody. For example:
> If I tried to use this OpenAPI schema I've got null value in debug:
> 
> ```yaml
> openapi: '3.0.3'
> info:
>   title: Application API
>   description: Documentation for API
>   version: v1.0.0
> paths:
>   /api/auth/login/:
>     post:
>       requestBody:
>         required: true
>         content:
>           application/json:
>             schema:
>               $ref: "#/components/schemas/Login"
> components:
>   schemas:
>     Login:
>       type: object
>       required: ["password"]
>       properties:
>         username:
>           title: Username
>           type: string
>         email:
>           title: Email
>           type: string
>           format: email
>         password:
>           title: Password
>           type: string
>           minLength: 1
> ```
> 
> I've tried another schema and this works well:
> 
> ```yaml
> openapi: '3.0.3'
> info:
>   title: Application API
>   description: Documentation for API
>   version: v1.0.0
> paths:
>   /api/auth/login/:
>     post:
>       requestBody:
>         required: true
>         content:
>           application/json:
>             schema:
>               login:
>               type: object
>               required: ["password"]
>               properties:
>                 username:
>                   title: Username
>                   type: string
>                 email:
>                   title: Email
>                   type: string
>                   format: email
>                 password:
>                   title: Password
>                   type: string
>                   minLength: 1
> ```
> 
> This problem occurs in Insomnia Core too. I'm working on Ubuntu 20.04.1

also work for me. "hard code" schema into content path

**Comment by wdawson** [comment]
Hey folks. We recently added support for OpenAPI version 3.0.3 in Insomnia. Are you still having this problem?

**Comment by twobiers** [comment]
> Hey folks. We recently added support for OpenAPI version 3.0.3 in Insomnia. Are you still having this problem?

I have tested it with the following spec in 22.4.1. Seems to work fine. I guess the issue can be closed now, thank you for your support.

<details>
<summary>Specification</summary>

```yaml
openapi: "3.0.3"

info: 
  title: "Test"
  version: "0.1"

paths:
  "/foo":
    post:
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Foo"
      responses:
        '200':
          description: "Test"
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Foo:
      title: Foo
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
```

</details>

**Comment by kash5811** [comment]
> Hey folks. We recently added support for OpenAPI version 3.0.3 in Insomnia. Are you still having this problem?

yes!!
