### ISSUE TITLE
Cut copy paste (right click) context dialogue is bugged

### ISSUE THREAD

**Issue by TakesTheBiscuit** [getinsomnia/insomnia#253]
## Overview
- `Insomnia Version:` 5.1.0.326
- `Operating System:`  macOS Sierra V10.12.1
- `Summary: ` If you click on 'timeline' in insomnia client, highlight some words, click about in the UI you'll find that eventually wherever you click on your mac desktop (even on different monitors) the context menu appears, very odd

## How To Reproduce
1. Go to timeline on a request 
2. Right click and select COPY (click copy)
3. Without moving mouse... this weird duplication bug appears

## Other Notes
Never seen this problem before, started occuring around 23 or 24/5/2017 
Have to force quit the app to stop the issue quite often, yesterday caused a real headache

**Comment by TakesTheBiscuit** [comment]
Totally embarrassed.  
My Apple mouse is right clicking when it shouldn't, not witnessed it anywhere else but it's not an insomnia bug at all (!)

**Comment by gschier** [comment]
@TakesTheBiscuit this _was_ actually a real bug #218 but it's fixed now 😄
