### ISSUE TITLE
Private Base Environment

### ISSUE THREAD

**Issue by rbrianhazzard** [getinsomnia/insomnia#2541]
**Is your feature request related to a problem? Please describe.**
It would be great if I could have a private base environment for sensitive information.

**Describe the solution you'd like**
I provided a potential solution [here](https://github.com/Kong/insomnia/issues/2540), in that there could just be a second "secrets" base environment that is private.

**Describe alternatives you've considered**
The alternative looks to be implementing each environment that I'd like as secret, which does not work because I want to share regular environment details with teammates.

**Additional context**
Context is available in the Question I asked [here](https://github.com/Kong/insomnia/issues/2540)

**Comment by alexandrim0** [comment]
It would be very useful!
Thank you!

**Comment by develohpanda** [comment]
Hi @rbrianhazzard and @alexandrim0, while private base environments are not supported yet I do have a proposed solution in https://github.com/Kong/insomnia/issues/2593#issuecomment-690679032 using `.env` files. Let me know if that works for your use case?

This way, none of your secrets are actually _in_ Insomnia - just pulled in from private `.env` files on your filesystem. But the structure of environment variables will be shared across your team.

![](https://user-images.githubusercontent.com/4312346/92793717-bf035500-f402-11ea-914f-47dd61b601e5.gif)

**Comment by rbrianhazzard** [comment]
Hi @develohpanda, that looks great. I'll try it out today but looks like it should be a suitable workaround for what I was asking.

**Comment by alexandrim0** [comment]
It looks too complicated.
Maybe I can use this.
But my colleagues won't.
I'd rather wait for the update.

Thank you!

**Comment by develohpanda** [comment]
No worries! I'm not sure we can provide an ETA on if or when something like this might be included in the core application.

The only thing your colleagues will need to do, once you have set up the workspace and environment, is specify where the `.env` file exists (on their filesystem), and install the `insomnia-plugin-dotenv` plugin. 🤗

**Comment by alexandrim0** [comment]
I will try this at some point.
Thank you!

**Comment by rbrianhazzard** [comment]
Hey - this works for my usecase. I will close the ticket since there's a workaround now via the plugin

**Comment by weiannnnn** [comment]
Hi @rbrianhazzard @develohpanda 

I'm having trouble implementing this .env approach in a shared workspace. In all the examples I've seen, the path to the .env file is only for one user, and would not apply for other users using that configuration in a shared workspace. 

<img width="572" alt="Screenshot 2021-04-07 at 08 55 57" src="https://user-images.githubusercontent.com/33024408/113831725-d4194a00-977f-11eb-9351-84624f2354ce.png">

Any advice?
