### ISSUE TITLE
npm run bootstrap failed in windows

### ISSUE THREAD

**Issue by superTinys** [getinsomnia/insomnia#2542]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\tools\\nodejs\\node.exe',
1 verbose cli   'C:\\tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'bootstrap' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebootstrap', 'bootstrap', 'postbootstrap' ]
5 info lifecycle insomnia@1.0.0~prebootstrap: insomnia@1.0.0
6 info lifecycle insomnia@1.0.0~bootstrap: insomnia@1.0.0
7 verbose lifecycle insomnia@1.0.0~bootstrap: unsafe-perm in lifecycle true
8 verbose lifecycle insomnia@1.0.0~bootstrap: PATH: C:\tools\nvm\v10.15.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Server\electron\app\insomnia-7.1.1\node_modules\.bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Program Files\Java\jdk1.8.0_211\jre\bin;C:\Program Files (x86)\Odoo 12.0\PostgreSQL\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;C:\tools\apache-maven-3.6.1\bin;C:\tools\curl-7.65.0-win64-mingw\bin;C:\tools\nvm;C:\tools\nodejs;C:\Program Files (x86)\Odoo 12.0\PostgreSQL\bin;C:\xampp7.1\mysql\bin;C:\xampp7.1\php;C:\Program Files\Git\cmd;C:\Users\Ray\gravitee\pngquant-windows\pngquant;C:\Program Files (x86)\GnuWin32;C:\Program Files\WSO2\API Manager\3.1.0\bin\..\bin;C:\tools\redis\;C:\tools\erl-23.0\bin;C:\tools\RabbitMQ\rabbitmq_server-3.8.6\sbin;C:\Users\Ray\.windows-build-tools\python27\;C:\Python27\;C:\Users\Ray\.windows-build-tools\python27\;C:\Users\Ray\AppData\Local\Microsoft\WindowsApps;C:\Users\Ray\AppData\Roaming\npm;C:\tools\nvm;C:\tools\nodejs;C:\Users\Ray\AppData\Local\Microsoft\WindowsApps;C:\Users\Ray\AppData\Local\Programs\Microsoft VS Code\bin;C:\tools\phantomjs-2.1.1-windows\bin;
9 verbose lifecycle insomnia@1.0.0~bootstrap: CWD: C:\Server\electron\app\insomnia-7.1.1
10 silly lifecycle insomnia@1.0.0~bootstrap: Args: [ '/d /s /c',
10 silly lifecycle   'npm install && lerna bootstrap && lerna run --parallel --stream bootstrap' ]
11 silly lifecycle insomnia@1.0.0~bootstrap: Returned: code: 4294967295  signal: null
12 info lifecycle insomnia@1.0.0~bootstrap: Failed to exec bootstrap script
13 verbose stack Error: insomnia@1.0.0 bootstrap: `npm install && lerna bootstrap && lerna run --parallel --stream bootstrap`
13 verbose stack Exit status 4294967295
13 verbose stack     at EventEmitter.<anonymous> (C:\tools\nvm\v10.15.3\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\tools\nvm\v10.15.3\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid insomnia@1.0.0
15 verbose cwd C:\Server\electron\app\insomnia-7.1.1
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\tools\\nodejs\\node.exe" "C:\\tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "bootstrap"
18 **verbose node v10.15.3**
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 4294967295
22 error insomnia@1.0.0 bootstrap: `npm install && lerna bootstrap && lerna run --parallel --stream bootstrap`
22 error Exit status 4294967295
23 error Failed at the insomnia@1.0.0 bootstrap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294967295, true ]

**Comment by superTinys** [comment]
**insomnia version**: 7.1.1
**windows version**: win10
**node version**: v10.15.3

**Comment by develohpanda** [comment]
Please pull the latest `develop` (the default branch) and try to bootstrap that. There is a pre-install check that will validate you are on the correct version of Node.

The current version is 12.18.3, specified [here](https://github.com/Kong/insomnia/blob/develop/.nvmrc) - since you are on Node 10, that is why bootstrapping is failing for you.

**Comment by superTinys** [comment]
thanks
