### ISSUE TITLE
npm run bootstrap failed in windows 10

### ISSUE THREAD

**Issue by superTinys** [getinsomnia/insomnia#2543]
`
C:\Server\electron\app\insomnia-develop>npm run bootstrap

> insomnia@1.0.0 bootstrap C:\Server\electron\app\insomnia-develop
> npm install && lerna bootstrap && lerna run --parallel --stream bootstrap

> insomnia@1.0.0 preinstall C:\Server\electron\app\insomnia-develop
> node ./scripts/check-version.js

npm WARN babel-loader@8.1.0 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-styled-components@1.11.1 requires a peer of styled-components@>= 2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-semistandard@15.0.1 requires a peer of eslint-plugin-node@>=9.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-semistandard@15.0.1 requires a peer of eslint-plugin-promise@>=4.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@14.1.1 requires a peer of eslint-plugin-node@>=9.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@14.1.1 requires a peer of eslint-plugin-promise@>=4.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\eslint-plugin-html\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 11.131s

63 packages are looking for funding
  run `npm fund` for details

lerna notice cli v3.22.1
lerna info Bootstrapping 29 packages
lerna info Installing external dependencies
**lerna ERR! npm install exited 1 in 'insomnia-send-request'**
lerna ERR! npm install stderr:
]

**node version : 12.18.3
windows 10**`

**Comment by superTinys** [comment]
insomnia version : lastest

**Comment by superTinys** [comment]
rerun : 

npm ERR! code ETARGET
npm ERR! notarget No matching version found for isomorphic-git@1.7.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'insomnia-send-request'
npm ERR! notarget

**Comment by nijikokun** [comment]
It looks like you've truncated the actual error output in your original post. Do you mind following the steps below and pasting the full output should you encounter an error? I've also written a [small development guide](https://github.com/Kong/insomnia/wiki/Development-Guide) while trying to replicate. Mostly requirements to get started.

Can you follow these steps below and provide output?

1. `rm -rf node_modules`
2. `npm run clean` (make sure that you have `lerna` and `rimraf` installed globally)
3. `npm run bootstrap`
4. `npm run app-start`

Also do you mind providing your full environment details? See mine below as well.

- Git Bash
- VSCode
- Windows 10 x64

**Comment by superTinys** [comment]
> It looks like you've truncated the actual error output in your original post. Do you mind following the steps below and pasting the full output should you encounter an error? I've also written a [small development guide](https://github.com/Kong/insomnia/wiki/Development-Guide) while trying to replicate. Mostly requirements to get started.
> 
> Can you follow these steps below and provide output?
> 
> 1. `rm -rf node_modules`
> 2. `npm run clean` (make sure that you have `lerna` and `rimraf` installed globally)
> 3. `npm run bootstrap`
> 4. `npm run app-start`
> 
> Also do you mind providing your full environment details? See mine below as well.
> 
> * Git Bash
> * VSCode
> * Windows 10 x64

**Comment by superTinys** [comment]
Thank you. I'll try it later
