### ISSUE TITLE
Could not expand reference

### ISSUE THREAD

**Issue by Hitmasu** [getinsomnia/insomnia#2548]
When i make a pull in a branch from bitbucket, i've receveid this error: `Could not expand reference "branch-name"`.

![image](https://user-images.githubusercontent.com/13804176/91049216-36f41180-e5f3-11ea-9e07-2dab3b7543e1.png)

`ExpandRefError: Could not expand reference "added-insomnia".
    at Function.expand (C:\Users\Hitmasu\AppData\Local\insomnia-designer\app-2020.3.3\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:2199:11)`

- Steps to reproduce;

1. Create a repository in BitBucket
2. Create an empty branch
3. Configure repository in Insomnia
4. Push something from Insomnia
5. Make a pull from Insomnia

**Comment by 4n70w4** [comment]
The same issue

**Comment by Hitmasu** [comment]
> The same issue

A workaround to fix that, is push at least one commit on branch. If branch is really empty (0 commits) that error will happen, however if branch has more than 1 commit, should work.

**Comment by antempus** [comment]
That's not a complete workaround, I am having this issue pretty consistently on existing repos with or without an `.insomnia` folder.

**Comment by Videl** [comment]
I also have the issue with a new repository. Reading this issue, I added a README file and the same error exists on the branch I added the file.
It would be helpful to have an example repositoy we could fork so we could have a starting base?
If any one could generate one it would be so helpful!

**Comment by cellcoresystems** [comment]
same problem here on Mac and Windows.

**Comment by antempus** [comment]
@develohpanda or someone else 

Can we update the stalebot so these aren't closed prematurely

**Comment by develohpanda** [comment]
Hi @antempus, that was our mistake, we're removing all these tags now but stalebot has definitely been disabled so nothing will be closed automatically. Sorry about that!

**Comment by antempus** [comment]
No worries just wanted to bring attention to the bot more so than the issue itself (even though I have had this issue :D )

**Comment by filfreire** [comment]
Hi @Hitmasu, thank you for reporting this, and sorry for the wait.

It seems I cannot reproduce this specific issue on our [latest 2022.3.0 release](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0).

![Screenshot 2022-05-25 at 12 23 33](https://user-images.githubusercontent.com/11976836/170251171-0e13f05a-e5a0-4c22-8e46-200d1eb888ee.png)

![Screenshot 2022-05-25 at 12 23 38](https://user-images.githubusercontent.com/11976836/170251165-c918d7eb-5172-45b7-bfce-cf77d1e02067.png)


But, there's still some issues with Insomnia creating a branch remotely, or pulling existing changes after a fresh import. See [my comment in issue #2220](https://github.com/Kong/insomnia/issues/2220#issuecomment-1137098066)


Are any of you folks still able to reproduce this on our with [latest beta](https://github.com/Kong/insomnia/releases/tag/core%402022.4.0-beta.1) or even with [latest stable build](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)?

cc @antempus @cellcoresystems @Videl @4n70w4 @Hitmasu

**Comment by Hitmasu** [comment]
> Hi @Hitmasu, thank you for reporting this, and sorry for the wait.
> 
> It seems I cannot reproduce this specific issue on our [latest 2022.3.0 release](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0).
> 
> ![Screenshot 2022-05-25 at 12 23 33](https://user-images.githubusercontent.com/11976836/170251171-0e13f05a-e5a0-4c22-8e46-200d1eb888ee.png)
> 
> ![Screenshot 2022-05-25 at 12 23 38](https://user-images.githubusercontent.com/11976836/170251165-c918d7eb-5172-45b7-bfce-cf77d1e02067.png)
> 
> But, there's still some issues with Insomnia creating a branch remotely, or pulling existing changes after a fresh import. See [my comment in issue #2220](https://github.com/Kong/insomnia/issues/2220#issuecomment-1137098066)
> 
> Are any of you folks still able to reproduce this on our with [latest beta](https://github.com/Kong/insomnia/releases/tag/core%402022.4.0-beta.1) or even with [latest stable build](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)?
> 
> cc @antempus @cellcoresystems @Videl @4n70w4 @Hitmasu

I'm not using Insomnia :( 

However, I installed a new version and worked! Seems to be fixed in sometime ago...

As that issue is a long time inactive, I'll close. Thank you @filfreire
