### ISSUE TITLE
[Improvement] OAuth2 Password field text is in plain view

### ISSUE THREAD

**Issue by christoth** [getinsomnia/insomnia#255]
## Overview
- `Insomnia Version:` _5.1.0_
- `Operating System:`  _Win10 x64 Enterprise 1607_
- `Summary: ` _OAuth2 Password field text in OAuth2 tab is in plain view_

## How To Reproduce
1. _Select OAuth2 authentication for a new request_
2. _Grant Type: select Resource Owner Password Credentials_
3. _Enter text in Password field_

## Other Notes

_First preference would be to implement a password input field that hides the text with '*'_
_Ideally would be the password would be hidden and there would be a show/hide toggle beside the field to temporarily show the password - default state would be hidden_
_Thanks for the great work so far!_

**Comment by gschier** [comment]
Thanks for the report @christoth. I have made this field abide by the "Show passwords in plain-text" option in the Settings for now. #256
