### ISSUE TITLE
Improve the output of the node version check script

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2552]
![image](https://user-images.githubusercontent.com/4312346/91123821-ec0cf380-e6f1-11ea-8079-ca709af26e4e.png)

Currently the response at the top is overpowered by the npm error lines. It would be nice to increase the visibility of the output through console log text colors: https://stackoverflow.com/a/41407246.

Note we cannot use an npm module like chalk for this, as the script runs and errors _before_ node_modules are installed.

**Comment by yashshah1** [comment]
Can I work on this?

**Comment by develohpanda** [comment]
@yashshah1 sure can! 😄
