### ISSUE TITLE
Unit Testing Sidebar Integration

### ISSUE THREAD

**Issue by sonicyeti** [getinsomnia/insomnia#2555]
Integrate our sidebar. Part of the over-arcing unit testing design sweep. See item 1 & 2: https://github.com/Kong/insomnia/issues/2464

**Current state:**
![Screen Shot 2020-08-25 at 3 12 46 PM](https://user-images.githubusercontent.com/52717970/91217408-73a03580-e6e5-11ea-842b-bf5889bf02e2.png)

**Comment by filfreire** [comment]
@wdawson, I'm currently cataloguing through all unit test feature related issues.

Marking this one as closed, don't think it's applicable right now.
