### ISSUE TITLE
File paths not parsed on Windows

### ISSUE THREAD

**Issue by feakuru** [getinsomnia/insomnia#2563]
**Describe the bug**
Seems like slashes are not parsed correctly in the "File" JSON field type.

**To Reproduce**
1. Create a request with JSON body
2. Press Ctrl+Space
3. Choose "File"
4. Choose a file
5. See the error.

**Expected behavior**
File being parsed.

**Screenshots**
![image](https://user-images.githubusercontent.com/14169434/91415383-a7e73380-e856-11ea-8cb6-c7c3540221ce.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: exe
 - App Version 2020.3.3

**Additional context**
None.

**Comment by thewheat** [comment]
This looks to be a dupe of https://github.com/Kong/insomnia/issues/757 so will leave some comments that I've found in that issue 👍

**Comment by ps-tunnelsoft** [comment]
Hi @dimitropoulos , This issue still exists in a similar case. If I define an environment variable with a file content and later want to assign this variable to a query - I get the same error

![image](https://user-images.githubusercontent.com/74701826/223748244-f29924f3-c87e-421b-acbb-4d769ace083c.png)
