### ISSUE TITLE
Unit Testing Suite and Tests UI

### ISSUE THREAD

**Issue by sonicyeti** [getinsomnia/insomnia#2564]
This covers the design integration of the primary test stage within the Unit Testing UI. There is a high degree of confidence that the end result will also resolve the UI lag we've identified when multiple CM instances are rendered.

Additional items to implement:
- Sticky action bar so the functionality isn't lost on scroll
- Keyboard shortcuts for new test & new test suite (hinted on empty state like debug)
- Bundle in item 5 from parent design sweep](https://github.com/Kong/insomnia/issues/2464)

Design Specification (are of focus outlined in green):
![UT-Tests](https://user-images.githubusercontent.com/52717970/91454126-98fc8300-e84e-11ea-9429-bf17dac8bec9.png)

Closes #2562

**Comment by filfreire** [comment]
@wdawson, I'm currently cataloguing through all unit test feature related issues.

Marking this one as closed, don't think it's applicable right now.
