### ISSUE TITLE
Quotes in parameters for template-tags are not escaped

### ISSUE THREAD

**Issue by chaosben** [getinsomnia/insomnia#2567]
**Description**
Double quotes in parameters for template-tags aren't escaped. Therefore the whole json (an environment or an body) becomes invalid.

**To Reproduce**
Steps to reproduce the behavior (this is just an example ... the bug _also concerns other plugins_):
1. Install insomnia-plugin-chance
2. Add template-tag "chance" to an JSON-request-body
3. Edit template-tag: select _Type_ **Pick One**; leave _Custom function_ empty; set _Options_ to **["a", "b"]**
4. Click Done
5. See the invalid JSON `"Param1" : "{% chance 'pickone', '', '["a", "b"]' %}"`

**Expected behavior**
The double quotes should be escaped.
The above example should look like this:  `"Param1" : "{% chance 'pickone', '', '[\"a\", \"b\"]' %}"`

**Screenshots**
![image](https://user-images.githubusercontent.com/1180488/91532805-256e7a80-e90f-11ea-8242-b383436aef31.png)

**Desktop:**
 - OS: Windows 10
 - Installation Method: Installer.exe
 - App Version: 
![image](https://user-images.githubusercontent.com/1180488/91532939-55b61900-e90f-11ea-9cb4-e79b96198517.png)

**Related issues:**
https://github.com/bbbco/insomnia-plugin-faker/issues/4

**Comment by gschier** [comment]
For template tags that need to handle a wide variety of user inputs (eg. quotes), an `encoding` option was added to the parameter option, which can be set to `base64`. If this option is added, the resulting tag will be something like this: `"Param1" : "{% chance 'pickone', '', 'WyJhIiwgImIiXQ==' %}"`

Our 1st-party Response tag uses this for the filter parameter: 

https://github.com/Kong/insomnia/blob/0b4c1eacec8e8ac5e4bf92e31958336650df7f0b/plugins/insomnia-plugin-response/index.js#L47-L49

Please submit a PR or issue on the chance plugin repo. Specifying `encoding: base64` will gracefully handle non-encoded values as well, so adding it isn't a breaking change.

**Comment by chaosben** [comment]
Great!
This solution is much better, then escaping. Well done!
Thanks for the hint!
