### ISSUE TITLE
Request broken if line breaks inside request auth options fields

### ISSUE THREAD

**Issue by SaraivaDaniel** [getinsomnia/insomnia#2569]
**Describe the bug**
The input fields in **Auth** tab allow new lines to be entered if a user types `ENTER` before inputting any text. This new lines are sent in the header of the request, breaking the request.

I inadvertently typed a `ENTER` in the `prefix` field of the Bearer auth option, while the cursor was there, and took a while to figure that there as a line break in the field after the requests stopped working, because the line break was the only character in the field.

On the other hand, the field does **not** accept a `ENTER` after some text has been entered.

This also applies to other auth modes, such as basic/digest/etc.

**To Reproduce**
1. Create a new request
2. Click on 'Auth' and select any mode (e.g. Bearer)
3. Put the cursor in any field (such as token or prefix) and press `ENTER` BEFORE entering any text
4. Check that `ENTER` is not allowed after entering some text
5. Execute the request to see line breaks sent in the header

**Expected behavior**
Line breaks should not be allowed in auth options fields.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: exe
 - App Version: 2020.3.3

**Comment by thewheat** [comment]
I've managed to reproduce the problem and would like to take this on 😃 

A quick dig into the code and seems that there could be 2 possible places to tackle this (am leaning towards option 2 as there could be other single line uses in the future)

**Option 1) In `OneLineEditor` (which uses `CodeEditor` with a `singleLine` prop)**
https://github.com/Kong/insomnia/blob/1bbbf38a9653792fd137662d015846f4334b1989/packages/insomnia-app/app/ui/components/codemirror/one-line-editor.js#L209-L225
- There already is some code to detect enter/return being pressed and we could probably just call `return` to end 
```
if (e.keyCode === 13) {
    ... // existing code
    return;
}
```

**Option 2) In `CodeEditor` by detecting `singleLine` is true**
https://github.com/Kong/insomnia/blob/1bbbf38a9653792fd137662d015846f4334b1989/packages/insomnia-app/app/ui/components/codemirror/code-editor.js#L732-L743

```
async _codemirrorKeyDown(doc, e) {
    if (this.props.singleLine && e.keyCode === 13) {
        return;
    }

    ... // existing code
}
```
