### ISSUE TITLE
Design sidebar seems to jump when expanding a section

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2574]
**Describe the bug**
What it says on the tin - looks a little janky towards the _end of the open animation_

**To Reproduce**
![2020-08-31 14 08 15](https://user-images.githubusercontent.com/4312346/91676313-85755300-eb93-11ea-9c21-dd37976ef2c3.gif)

**Expected behavior**
Smooth animations

![](https://media1.giphy.com/media/84fFptgxiU7cY/giphy.gif)

**Desktop (please complete the following information):**
```
Version: Insomnia Designer 2020.4.0-beta.4
Release date: 31/08/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Comment by filfreire** [comment]
I can reproduce this.

It's almost unnoticeable, but there is indeed a problem there, better noticed when using the dev tools performance tab. There's a split second where we increase the size of the element when it finishes opening up, which causes the visual jankiness:


![Image](https://user-images.githubusercontent.com/11976836/184338772-f82c30de-f30c-4356-9a41-a2e4b8b59b70.jpg)
![Image](https://user-images.githubusercontent.com/11976836/184338786-7219cc76-2d19-408f-8efb-25096e87176f.jpg)


Here's the same but in video:

https://user-images.githubusercontent.com/11976836/184339230-416442b1-c1a7-485c-8ca6-0fc953cc10dd.mov

**Comment by gatzjames** [comment]
This is fixed with latest sidebar update
