### ISSUE TITLE
Insomnia Core & Designer App Icon > Linux

### ISSUE THREAD

**Issue by sonicyeti** [getinsomnia/insomnia#2577]
The branded core & designer icons do not appear post linux install.

**Spotlight**
![Screen Shot 2020-09-01 at 11 56 34 AM](https://user-images.githubusercontent.com/52717970/91876038-40f8be80-ec4a-11ea-8898-9fde0cc29c61.png)

**Favorites** 
![Screen Shot 2020-09-01 at 11 56 52 AM](https://user-images.githubusercontent.com/52717970/91876050-448c4580-ec4a-11ea-90d7-2688cc621f2b.png)

**Comment by DMarby** [comment]
Closing this as it was resolved before the 2020.4 release.
