### ISSUE TITLE
Editor typography muted

### ISSUE THREAD

**Issue by sonicyeti** [getinsomnia/insomnia#2578]
In both designer and core the typography (especially within the editor mode) is extremely muted and hard to visually parse. I checked preferences and they are identical to my OSX settings. The in Ubuntu however, is "Menlo". A switch to Mono or default system sans-serif may be more appropriate, see bottom screenshot.

**Muted display in both light & dark themes**
![Screen Shot 2020-09-01 at 9 36 05 AM](https://user-images.githubusercontent.com/52717970/91861434-caa09000-ec3a-11ea-9bb1-e6bbeeabe767.png)

Quick test to see how default sans-serif compares
![sans-serif](https://user-images.githubusercontent.com/52717970/91861516-e9068b80-ec3a-11ea-98f5-357d3d27ec98.png)

**Comment by sonicyeti** [comment]
I'll test this on a fresh VM as well. There was a number of font management and support provisioning needed to run a branch locally. Something might have been thrown.

**Comment by sonicyeti** [comment]
Quick follow-up, it appears that this happens only when the environment is provisioned to develop where font-manager etc. come into play. 

Everything looks fine, spanning multiple themes, on a fresh instance of Ubuntu. 
![Screen Shot 2020-09-01 at 12 09 25 PM](https://user-images.githubusercontent.com/52717970/91877560-27587680-ec4c-11ea-94e4-bbe5805d9990.png)

**Comment by vitorpedeo** [comment]
I'm having the exact same issue with Insomnia Core, but I'm using Kubuntu. @sonicyeti i didn't undestand your solution, can explain it more please?

**Comment by sonicyeti** [comment]
@vitorpedeo I'm grabbing Kubuntu 20.04.1 LTS now to see if the issue is present on a fresh instance running off  the Core installer. 

Assuming you're working from source, did you perform the following steps during setup?

![Screen Shot 2021-01-08 at 1 54 57 PM](https://user-images.githubusercontent.com/52717970/104053408-2f579280-51b9-11eb-9c3d-3acb8e8deb84.png)

**Comment by vitorpedeo** [comment]
@sonicyeti didn't know about these steps. After I finished to perform them, all the fonts are looking normal. Thanks for the help!
