### ISSUE TITLE
Design Preview and Testing Results pane should be resizable

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2583]
**Describe the bug**
In the design and test tabs, the right-most pane (preview and test results) are not resizable. In the debug tab, we can see that the three panels can be resized independently.

**Expected behavior**
All three panels on each tab should be resizable independently.

**Screenshots**
![2020-09-03 12 27 50](https://user-images.githubusercontent.com/4312346/92051789-1856fd00-ede1-11ea-9f69-fdb82b3f2d1f.gif)

**Desktop (please complete the following information):**
```
Version: Insomnia Designer 2020.4.0-beta.6
Release date: 02/09/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

INS-54

Related: https://github.com/Kong/insomnia/issues/2584

**Comment by develohpanda** [comment]
INS-54

**Comment by simplywondrous** [comment]
I'll take a shot at this :)

**Comment by develohpanda** [comment]
@simplywondrous awesome! Have a look at how it happens on the debug tab (wrapper-debug.js), as we (hopefully) shouldn't need to re-do too much here.

**Comment by simplywondrous** [comment]
@develohpanda Hello! I forked the repo but have been stuck trying to run `insomnia-app` - the build is skipped with `[build] Skipping build for ref ""`. I've tried tracing it, and it seems like `${buildContext.gitRef}` is `""`, and `buildContext.version` is `null`. Am I missing a step? I first ran `npm install` in packages/insomnia-app, and then ran `npm run build`.

**Comment by develohpanda** [comment]
Hi @simplywondrous! Yes the monorepo structure can be a little confusing at times. 😅 From the root of the repository, all you need to do is `npm run bootstrap` to install and prepare all the dependencies and packages, then `npm run app-start` to run the application in dev mode. There are some notes in the README to help you get going. 

You shouldn't need to run the build step as that's used prior to packaging and releasing.

**Comment by simplywondrous** [comment]
Thank you for the explanation! 🤦 Sorry for forgetting the readme - the boostrap was successful! However I ran into 
```
[app]  [5] external "electron" 42 bytes {0} [built]
	...
[app] npm run start:electron exited with code 0
--> Sending SIGTERM to other processes..
[dev] npm run start:dev-server exited with code null
npm ERR! code ELIFECYCLE
```
when running `npm run app-start`. At first I had an electron folder in `~/.cache/electron` so I removed that per instruction and then re-ran `bootstrap` and `app-start`, but am still getting the same error. Would you have an idea for what to try?

**Comment by develohpanda** [comment]
Hmm, that's definitely a little strange, which OS are you developing on? You're running on the latest commit on the develop branch?

Also, when things break I tend to try `npm run clean && npm run bootstrap` to completely delete all my `node_modules` and re-install them. Give that a go, and if it still doesn't work, can you share some extended logs from your console window?

**Comment by simplywondrous** [comment]
Yep, latest on develop. I'm using WSL 2 with Ubuntu 20.04. Turns out / I learned

>[Electron needs to open a chrome browser window](https://stackoverflow.com/questions/49936910/unable-to-run-electron-quick-start-in-wsl). So, when you run it from WSL using a node.js that was installed in WSL, I guess it would try to start the chromium browser for Ubuntu, which will not work out of the box

and

>[ For now, it is necessary to install a third-party App to run the GUI Apps](https://techcommunity.microsoft.com/t5/windows-dev-appconsult/running-wsl-gui-apps-on-windows-10/ba-p/1493242), but Microsoft announced on //build 2020 that they will release soon an improvement that will not require any third-party component to run Linux GUI Apps on Windows Desktop.

so following the second link, I set up X Server and Insomnia's now up and running! 
Also, thanks for being generally friendly, helpful, and responsive. As a beginner, working on open source is quite intimidating, so I really appreciate it!

Looks like there are a couple ways to refactor the code - with the easiest being copying some existing drag logic and adding cases for both design and debug panes, to more involved refactoring to make the current drag logic generic and usable for all three tabs. Is it okay for me to open a draft PR starting with the most straightforward way, and then code reviewing and iterating from there? Of course, if you would prefer for me to come up with as finished of a PR as I can before reviewing I can do that too!

**Comment by develohpanda** [comment]
Wow, nice sleuthing! It might be useful to add a line describing what you had to do differently with WSL 2 into the README, for anybody else that faces the same issue.

> Also, thanks for being generally friendly, helpful, and responsive. As a beginner, working on open source is quite intimidating, so I really appreciate it!

No problem! 🤗 OSS is not some holy grail where every PR is perfect first time. It's still, always, a collaborative process and an opportunity to learn. We all start somewhere; I'm glad you chose this project!

Ideally, generic and reusable logic would be amazing (there might be a fourth tab in the future 👀). If that is a decent chunk of work though, then it would be good to weigh up the different options. Admittedly I have not investigated this issue directly, but I'll let you work through it. 😃 

> Is it okay for me to open a draft PR starting with the most straightforward way, and then code reviewing and iterating from there?

Of course! That's an efficient way to go about it.

**Comment by simplywondrous** [comment]
Hello! The PR's going well - the Test Results pane is now resizable! 

Before I clean it up more, I have a question about how to proceed, written in the PR if you could take a look!
