### ISSUE TITLE
Design and Test tabs should respect vertical layout preferences

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2584]
**Describe the bug**
Currently, if the following preference setting is checked, the layout on the debug tab is forced to be vertical. However the same behavior is not seen on the design and testing tabs.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/4312346/92054590-36712d00-ede2-11ea-96b3-2d7948b7c937.png">

**Expected behavior**
We should adapt the verbiage of this option for Designer (update to "Force Vertical Layout"), and ensure both Design and Test tabs also respect the setting, as well as automatically on resizing.

**Screenshots**
![2020-09-03 12 31 42](https://user-images.githubusercontent.com/4312346/92053622-db3f3a80-ede1-11ea-9517-4b39f9024572.gif)

**Desktop (please complete the following information):**
```
Version: Insomnia Designer 2020.4.0-beta.6
Release date: 02/09/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

INS-59

**Comment by AvDevx** [comment]
I would like to work on this but I have no idea how to get started can you maybe give me some pointers?
Thanks.

**Comment by develohpanda** [comment]
> I would like to work on this but I have no idea how to get started can you maybe give me some pointers?

Key things to note are:

- The `WrapperDesign`, `WrapperDebug`, and `WrapperUnitTest` components correspond to the debug/design/test views you see in the gif above
- Each `Wrapper*` component contains a root `PageLayout`, which contains the [logic](https://github.com/Kong/insomnia/blob/1bbbf38a9653792fd137662d015846f4334b1989/packages/insomnia-app/app/ui/components/page-layout.js#L69) to control layout
- The force vertical layout setting is stored in the database, under the [settings](https://github.com/Kong/insomnia/blob/1bbbf38a9653792fd137662d015846f4334b1989/packages/insomnia-app/app/models/settings.js#L36) model.

Because forcing vertical layout works with `WrapperDebug`, but doesn't work with `WrapperDesign` and `WrapperUnitTest`, there should be enough in the code to identify what is different. I think it will be a matter of passing some missing props down to `PageLayout`.

Let me know if this is sufficient.

**Comment by AvDevx** [comment]
Thank you for the explanation! 
I checked the codebase and in both the `WrapperDesign` & `WrapperUnitTest` in which the force vertical layout is not working.
They have defined the props and state with `{|` `|}` I don't know if this is a typescript thing or a typo but I think this is the reason for it to be not working.

```js

type Props = {|
  gitSyncDropdown: React.Node,
  handleActivityChange: (workspaceId: string, activity: GlobalActivity) => Promise<void>,
  handleUpdateApiSpec: (s: ApiSpec) => Promise<void>,
  wrapperProps: WrapperProps,
|};

type State = {|
  previewHidden: boolean,
  hasConfigPlugins: boolean,
  lintMessages: Array<{
    message: string,
    line: number,
    type: 'error' | 'warning',
  }>,
|};

```

**Comment by develohpanda** [comment]
This has already been resolved, closing

![image](https://user-images.githubusercontent.com/4312346/132640281-b2047e07-5d4b-405a-8106-0f3cc0649a04.png)

![image](https://user-images.githubusercontent.com/4312346/132640311-a213ef80-0384-4240-a8df-fafeaa4bcea5.png)
