### ISSUE TITLE
GraphQL autocomplete query fields losing sorting

### ISSUE THREAD

**Issue by brunovigano** [getinsomnia/insomnia#2585]
**Describe the bug**
Consuming a graphql endpoint when using the shortcut CTRL + Space to autocomplete the query fields and using the arrow keys to navigate between the indexes, Insomnia switches the index to the top of the list by itself.

**Expected behavior**
Be able to navigate between the indexes of the suggested fields without losing their order.

**Screenshots**
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/25367686/92144160-ab496480-edec-11ea-9bbd-63d441aa39bd.gif)

**Desktop (please complete the following information):**
Version: Insomnia Core 2020.4.0-beta.6
Release date: 01/09/2020
OS: Windows_NT x64 10.0.19041
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0

**Comment by develohpanda** [comment]
Closed by #3468
