### ISSUE TITLE
The autocomplete dropdown won't close

### ISSUE THREAD

**Issue by alefduarte** [getinsomnia/insomnia#2591]
This problem has happened to me many times. When I click on a field and the autocomplete shows up, if I rapidly click on another request, the dropdown won't leave, no matter where I click. I either have to restart the application or click on one of the options, which will autocomplete the field and then I have to correct it.
This gif shows the problem: (I have added a white target to hide some sensitive URI from a public API.

![Untitled Project](https://user-images.githubusercontent.com/29279051/92292270-a53dab80-eef2-11ea-8b2c-484ed859a0ec.gif)

**Desktop (please complete the following information):**
 - Windows 10 Pro 120.2212.31.0
 - Installation Method: exe file
 - App Version 2020.3.3

**Comment by joshcull3n** [comment]
I've had this issue for a while too. Very difficult to deal with when it happens, requires a restart if you don't want to edit the field
>Version: Insomnia Core 2020.5.2
Release date: 09/12/2020
OS: Windows_NT x64 10.0.17134
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
