### ISSUE TITLE
Add sort options for folders and requests

### ISSUE THREAD

**Issue by g-industrialist** [getinsomnia/insomnia#2594]
**Is your feature request related to a problem? Please describe.**
Hard to find Folder / Request

**Describe the solution you'd like**
Sort the saved Folder / Request by either create date / name / anything...

**Describe alternatives you've considered**
Nil

**Additional context**
Add more filed to describe the Folder /  Request name , easy for hashtag or find out the resource.

**Comment by develohpanda** [comment]
Sounds reasonable! @erickrico / @nijikokun thoughts on a sort drop-down next to the filter? This drop-down can contain ordering fields such as "name, date created, last updated". Icon withstanding, just used `fa-sort` 😄 
 
![image](https://user-images.githubusercontent.com/4312346/92552225-41313380-f2b4-11ea-8b5b-32c05c37d6c4.png)

As an note for anybody looking to pick this up, it should be somewhat straightforward to implement. The ordering is controlled by a `metaSortKey` property on a request and request-group. The sidebar children are automatically ordered on [fetching](https://github.com/Kong/insomnia/blob/af6a9b6a78a46402bc254e709b31d8dfa9e4b314/packages/insomnia-app/app/ui/redux/selectors.js#L165-L175) from redux.

If the `metaSortKey` properties are updated, the sidebar will reflect that. Use the [`App._moveDoc`](https://github.com/Kong/insomnia/blob/af6a9b6a78a46402bc254e709b31d8dfa9e4b314/packages/insomnia-app/app/ui/containers/app.js#L1509) implementation as inspiration for updating the sort order. 😄 

Additionally, after ordering I would expect that the active/selected request remains the same.

**Comment by asharonbaltazar** [comment]
Hello, I'd like to try my hand at this. Where can I find the request properties?

**Comment by erickrico** [comment]
> Sounds reasonable! @erickrico / @nijikokun thoughts on a sort drop-down next to the filter? This drop-down can contain ordering fields such as "name, date created, last updated". Icon withstanding, just used `fa-sort` 😄
> 
> ![image](https://user-images.githubusercontent.com/4312346/92552225-41313380-f2b4-11ea-8b5b-32c05c37d6c4.png)
> 
> As an note for anybody looking to pick this up, it should be somewhat straightforward to implement. The ordering is controlled by a `metaSortKey` property on a request and request-group. The sidebar children are automatically ordered on [fetching](https://github.com/Kong/insomnia/blob/af6a9b6a78a46402bc254e709b31d8dfa9e4b314/packages/insomnia-app/app/ui/redux/selectors.js#L165-L175) from redux.
> 
> If the `metaSortKey` properties are updated, the sidebar will reflect that. Use the [`App._moveDoc`](https://github.com/Kong/insomnia/blob/af6a9b6a78a46402bc254e709b31d8dfa9e4b314/packages/insomnia-app/app/ui/containers/app.js#L1509) implementation as inspiration for updating the sort order. 😄
> 
> Additionally, after ordering I would expect that the active/selected request remains the same.

agree, we could use this selected state for the sort by dropdown
<img width="261" alt="Screen Shot 2020-09-09 at 11 08 38" src="https://user-images.githubusercontent.com/18429104/92624169-d1f41900-f28c-11ea-85dc-c6c719e17b4b.png">

**Comment by develohpanda** [comment]
Thanks Erick. 🎉 

Hi @asharonbaltazar!

Here are the models with the property on them:
https://github.com/Kong/insomnia/blob/af6a9b6a78a46402bc254e709b31d8dfa9e4b314/packages/insomnia-app/app/models/request.js#L81
https://github.com/Kong/insomnia/blob/af6a9b6a78a46402bc254e709b31d8dfa9e4b314/packages/insomnia-app/app/models/request-group.js#L16

**Comment by asharonbaltazar** [comment]
I've never done something this advanced in someone else's project, but I can try my hand at it for a day.

**Comment by develohpanda** [comment]
Try and break it down into small pieces, and see how you get on. 🤗

**Comment by asharonbaltazar** [comment]
Hello, I'm having trouble setting up the environment. Is there a group where I can ask questions?

**Comment by develohpanda** [comment]
Join our Slack at https://chat.insomnia.rest/, you can just ping in #general

**Comment by cobwebsonsale** [comment]
Hi, I'm trying to work my way through the code to make an attempt here. The details added so far were helpful! I'll try to add one type of sorting and will update here.

**Comment by cobwebsonsale** [comment]
Added a pull request. The basic feature is in, but I had some things I needed help with. I've asked them on the PR itself.
