### ISSUE TITLE
Nested Template Tags

### ISSUE THREAD

**Issue by sc911** [getinsomnia/insomnia#2596]
Hello, it would be great if nested Template Tags would be possible.

For example: retrieve value from previous response, concatenate with environment variable, MD5 on the whole string.

It is possible to concat strings, so combining a body attribute from a previous response and an environment variable is possible. Whats not working is hashing the result.

To reproduce:
* Add two environment variables
  * username: demo
  * accessKey: YPPjJJiagrUA7mo
* Create new GET-request and run it
  * URL: http://demo7.vtexperts.com/vtigercrm7demo/webservice.php?operation=getchallenge&username=demo
* Create new POST-request:
  * URL: http://demo7.vtexperts.com/vtigercrm7demo/webservice.php?operation=login
  * Form:
    * username: {{ accessKey }}
    * accessKey: {% hash 'md5', 'hex', '{% response \\'body\\', \\'**req_06478a94e4134916b6225ae03360b6e5**\\', \\'$.result.token\\', \\'never\\', 60 %}{{ accessKey }}' %}

Here **req_06478a94e4134916b6225ae03360b6e5** should be replaced with ID of first GET-request.

So what is done here is, that both the response body attribute and the environment variable are hashed. 

You can also add the response body attribute and the environment variable to a new parameter, mark and cut the colored boxes, insert a new Hash=>MD5 box and paste the "boxes" into the Input field.

But nothing of the above works, even the GUI shows invalid data.

It would be great if this would be added.

Running on Windows, here is the info from help-menu:
Version 2020.3.3
Shell 3.1.13
Node 10.2.0
V8 6.6.346.32
Architecture x64
libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0

**Comment by nijikokun** [comment]
Welcome @sc911,

While nesting template tags directly does not work, you can achieve the same outcome through variable assignment. First by assigning the result token to a variable, then another variable to join the two variables (`resultToken` and `accessKey`) which then you can pass to the md5 hashing function as the value to be hashed.

You can find an example of assignment being used this way in action here: https://github.com/Kong/insomnia/issues/2271#issuecomment-642176041

**Comment by sc911** [comment]
Thanks @nijikokun! That was what I was searching for! I think this should be mentioned in the docs (more prominent if it is already there).

For everybody reading this, here is the long version of doing this:
* Open "Manage Environments"
* Edit Base Environment like this
```
{
  "token": "{% response 'body', 'req_06478a94e4134916b6225ae03360b6e5', 'b64::JC5yZXN1bHQudG9rZW4=::46b', 'never', 60 %}",
  "accessKeyTokenNoHash": "{{ token }}{{ accessKey }}"
}
```
* Then in your request you can hash the environment variable `accessKeyTokenNoHash`
```
{% hash 'md5', 'hex', accessKeyTokenNoHash %}
```
