### ISSUE TITLE
Prettify GraphQL long query args

### ISSUE THREAD

**Issue by wassimoo** [getinsomnia/insomnia#2600]
**Describe the bug**
Long query args not splitting into multiple lines when prettified making it a bit ugly and harder to read.

**Screenshots**

Current behavior: 

![image](https://user-images.githubusercontent.com/12980387/92825474-7e3a1a80-f3c7-11ea-9feb-611d23ca8683.png)

Would be more reader-friendly to prettify it like this:

![image](https://user-images.githubusercontent.com/12980387/92825660-b6415d80-f3c7-11ea-8e8d-9c4a2aadba5e.png)

**Comment by dimitropoulos** [comment]
Thanks for reporting.  Just curious, do you have a graphql prettifying tool you've used before that you like?

**Comment by rocketraman** [comment]
This seems to be a duplicate of https://github.com/Kong/insomnia/issues/2023.
