### ISSUE TITLE
OAuth 2 "refresh_token" is not populated

### ISSUE THREAD

**Issue by dmythro** [getinsomnia/insomnia#2602]
**Describe the bug**
Checked OAuth2 flow now, seems like Refresh Token from response is not populated (it is empty on UI).

**To Reproduce**
1. Use **OAuth 2**
2. Choose **Client Credentials**
3. Send credentials **In Request Body** in Advanced Options
4. Click **Fetch Token**
5. Refresh Token field is empty

**Expected behavior**
Refresh Token field has data from [OAuth 2 response](https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/) — `refresh_token` (I have checked responses in a separate POST request, `refresh_token` is always there and valid).

**Screenshots**
![image](https://user-images.githubusercontent.com/1391015/92927341-21317980-f446-11ea-8d03-05d72d037b40.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Installation Method: download
 - App Version: v2020.3.3

**Comment by ihatemornings** [comment]
I’m seeing this too in v2021.1.1 using the same settings (client credentials in request body).

**Comment by aeri** [comment]
The specification states that Client Credentials Grant SHOULD NOT return a refresh token:
https://tools.ietf.org/html/rfc6749#section-4.4.3

In Client Credentials Grant it is necessary perform the flow again to retrieve a new access token.
