### ISSUE TITLE
Insomnia designer is missing key validation of API specification

### ISSUE THREAD

**Issue by smacktoid** [getinsomnia/insomnia#2603]
**Describe the bug**
Insomnia designer does not flag up several types of validation problem with API specs in YAML format. I am learning how to write these specs and was hoping the designer would assist in getting the structure correct, but once I exported my spec to editor.swagger.io there were several misplaced properties which were stopping the designer from properly parsing the spec.

The key validation problems that were missed are:

- In the parameters section of an operation, I mistakenly indented the required:true property so that it appeared inside the schema section. The designer did not catch this.
- In the responses section, under '200'.content.application/json I mistakenly indented the schema and $ref properties at the same level. The designer did not catch this.
- In the components.schemas section of the spec I declared an array type, and got the structure of the 'items' property wrong (I did not declare it as a ref to another type in the schema). The editor didn't catch this.

The net effect of these problems meant that Insomnia Designer couldn't show me the responses to expect in the preview panel on the right.

**To Reproduce**
1. Open the Insomnia Designer
2. Paste in the contents of this document [bad-customer-api-spec.txt](https://github.com/Kong/insomnia/files/5209162/bad-customer-api-spec.txt)
3. Note there are no parsing errors, but the preview in the right is not complete.
4. Paste the same contents into editor.swagger.io, it will flag up all of the errors described above.
5. Once fixed, the schema [good-customer-api-spec.txt](https://github.com/Kong/insomnia/files/5209238/good-customer-api-spec.txt) can be imported back into Insomnia Designer, and the documentation will be complete.

**Expected behavior**
All validation errors should have been detected by Insomnia Designer 

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Installation Method: Download of .deb
 - App Version: Insomnia Designer 20202.3.3

**Comment by smacktoid** [comment]
Keep this open.

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

**Comment by gatzjames** [comment]
Closing as the linter is now properly validating the OAS
