### ISSUE TITLE
Allow exporting requests without environments

### ISSUE THREAD

**Issue by pgp** [getinsomnia/insomnia#2604]
**Is your feature request related to a problem? Please describe.**
It may happen that both requests and environments grow over time; in this scenario, when you import some requests (even a single one) from someone else, environments are imported as well - it's likely one's interested only in the request content, for doing further customization, and doesn't want to pollute its own envs with the imported ones (even if some variable binding may fail without them)

**Describe the solution you'd like**
- Either allow discarding envs in import, or
- Allow exporting requests without environments
(or both options, in the best case)

**Additional context**
A preview of what I'm going to import in my workspace would be a great addition as well (but maybe this requires too much effort)

**Comment by develohpanda** [comment]
Firstly, private environments are never exported; does this work for your use case?
![image](https://user-images.githubusercontent.com/4312346/93038196-6f3dbb80-f698-11ea-8774-02c86f15c5c1.png)


I agree that more control over what is imported or exported could be useful. For exporting, it would be a matter of adding to the dialog here. Importing, may be a little more involved. 
![image](https://user-images.githubusercontent.com/4312346/93038088-2a198980-f698-11ea-963c-398e433f23fb.png)

**Comment by pgp** [comment]
I wasn't aware of private environments... This seems a reasonable compromise, thanks!

**Comment by develohpanda** [comment]
You're welcome! I will close this issue.

I will discuss "selective import/export" internally and track as a standalone feature request if appropriate. 😄
