### ISSUE TITLE
Allow selecting with checkboxes multiple requests and perform bulk actions on them (edit, move, delete)

### ISSUE THREAD

**Issue by SimonGodefroid** [getinsomnia/insomnia#2609]
**Is your feature request related to a problem? Please describe.**
I am super frustrated when I imported a configuration file with 20 requests for instance or whenever actually, and I have to:
(
- click on a request
- click on the drop down icon
- click on delete
- click on delete 
)* 20

When deleting a request
When moving requests under a folder (after import especially but whenever).
When changing the name of 

![image](https://user-images.githubusercontent.com/17337190/93089048-060b7780-f69b-11ea-9148-73fe9a96948e.png)

Same if you want to change the name of a variable in request path, header and body...

e.g. here after import resource_type is a variable

![image](https://user-images.githubusercontent.com/17337190/93089127-25a2a000-f69b-11ea-9e35-7067d4b2e2a1.png)

but willing to manage my environment better, I choose to nest resource_type under a "global" key

![image](https://user-images.githubusercontent.com/17337190/93089405-87fba080-f69b-11ea-9e2c-30b1195d300f.png)

Then I have to go every where and do that stuff manually meaning body, path and header

**Describe the solution you'd like**
**Either**

Make multiple selection work with Shift (just for delete)

OR

Make a button that lets appears a checkbox next to each request allowing to select it (akin to gmail inbox) and then allow to perform actions on the requests in bulk within a single environment at first.

Actions could be "Move to Folder", "Delete", "Replace variable"

and then the user could do the above and that's it.

**Describe alternatives you've considered**
First, fixing the OAS json to include tags property so as to map requests in folders straight from the import... but I switched context a bit because it requires different effort on my end although it's completely something that would be a game changer feature for the product.

**Additional context**

![image](https://user-images.githubusercontent.com/17337190/93090033-79fa4f80-f69c-11ea-9d7a-2c3659d2f633.png)

![image](https://user-images.githubusercontent.com/17337190/93090771-8b902700-f69d-11ea-94db-7306331d8d10.png)

**Comment by develohpanda** [comment]
Thanks for the feature request @SimonGodefroid!

Technically, because a request can already be "pinned", the same concept can be used to introduce the concept of being "selected". What will need some thought and design is how to expose bulk actions in a nice manner, and just general UX patterns there.
