### ISSUE TITLE
[Feature] CmdOrCtrl+R to send request

### ISSUE THREAD

**Issue by martyf** [getinsomnia/insomnia#261]
It would be great to be able to adjust keyboard shortcuts.

Or, at the very least, have a second "Send" keyboard shortcut - Cmd+R seems to make sense for testing (as it's a lot of "R"efreshing), and fits in with the web dev world of refreshing a browser too.

This also means I can do it one handed, with the other hand still on the mouse - at the moment, given I "Cmd" with my left hand, and mouse with my right, need to move my right hand back to the keyboard to trigger a reload.

**Comment by gschier** [comment]
One-handed use is a great argument for a `cmdOrCtrl+R` shortcut. Since I only use the trackpad on my laptop my right pinky is always very close to the Enter key so I never noticed the friction this caused. Seems like a good thing to include in the next release.

**Comment by lucraraujo** [comment]
Related to #186
