### ISSUE TITLE
Custom extension x-kong-plugin is not converted to declarative config

### ISSUE THREAD

**Issue by danielkocot** [getinsomnia/insomnia#2610]
The custom extension x-kong-plugin is not converted to declarative config but for Kubernetes config. The extension is placed at OpenAPI level.

![CleanShot 2020-09-14 at 17 38 49](https://user-images.githubusercontent.com/466609/93106938-3e1db500-f6b1-11ea-8e9e-200d681fd988.png)
![CleanShot 2020-09-14 at 17 38 43](https://user-images.githubusercontent.com/466609/93106945-40800f00-f6b1-11ea-876f-f878a1991a1a.png)

**Comment by nijikokun** [comment]
Hi @danielkocot 👋 

To get a plugin to apply to the service, you'll want to nest the plugin under the server you wish to target. This is to differentiate plugins per environment.

Hope this helps!

**Comment by danielkocot** [comment]
Hi @nijikokun 

good to know. I didn't find this in the documentation.

Best,
Daniel

**Comment by nijikokun** [comment]
@danielkocot good observation, we've created a ticket to add this to the support site, for the time being documentation can be found on the npm package, and on the github package readme here - https://github.com/Kong/insomnia/tree/develop/packages/openapi-2-kong
