### ISSUE TITLE
[FEATURE REQUEST] Save OpenAPI as file in local file system

### ISSUE THREAD

**Issue by prakashm1** [getinsomnia/insomnia#2611]
Insomnia needs to work with OpenAPI specs in the local file system. Currently it keeps them in an internal format only.
This has several problems:

1. The specs are not useable outside of Insomnia Designer.
1. One cannot reference definitions from other specs. Each spec has to be entirely self-contained.

It would be much simpler and useful to work with spec yaml's in local file system instead.

**Comment by shortwavedave** [comment]
Is there any way to just grab the openapi yaml besides copy pasting from the ui?

**Comment by filfreire** [comment]
Closing as duplicate of #1638
