### ISSUE TITLE
OpenAPI Extension for Kong Enterprise Workspace

### ISSUE THREAD

**Issue by danielkocot** [getinsomnia/insomnia#2616]
Implementation of something like x-kong-workspace to elaborate the use of workspaces in Kong Enterprise in an easy way and direct from the API spec.

**Comment by nijikokun** [comment]
Do you have an example of what you are thinking the outcome of a feature like this would look like @danielkocot ?

**Comment by danielkocot** [comment]
The x-kong-workspace would generate a workspace-tag in the declarative config. Hopefully this helps. This [link](https://docs.konghq.com/deck/guides/kong-enterprise/) should be the reference.

**Comment by danielkocot** [comment]
Is a example still needed, @nijikokun?

**Comment by danielkocot** [comment]
Hi, is the given example good enough to implement the feature?
