### ISSUE TITLE
Tests are lost when exported

### ISSUE THREAD

**Issue by ashosborne** [getinsomnia/insomnia#2619]
**Describe the bug**
Exporting a workspace appears to lose the tests that have been created.

**To Reproduce**
1. Create a new OAS document
2. Create test suites and some tests
3. Go to preferences >> Data >> Export >> Current workspace >> All requests
4. Delete the original document
5. Go to preferences >> Data >> Import >> From File >> Import the document that was just exported
6. Go back to tests and there will be no tests imported

**Expected behavior**
The imported file should bring over the tests that I have created.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.15.5 ]
 - Installation Method: [Download]
 - App Version [2020.3.3]

**Additional context**

**Comment by develohpanda** [comment]
Thanks for reporting! 🎉 

INS-75
