### ISSUE TITLE
Incorrect verbiage in move folder to workspace modal

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2620]
**Describe the bug**
what it says (or doesn't say, heh) on the tin

**To Reproduce**
1. Go to Insomnia Core
2. Create a new folder
3. Right click on folder
4. Click "move" in the context menu
5. Hover over the `(i)` next to "New Workspace" to see a tooltip

**Current behavior**
Tooltip reads "Workspace will be moved to the root of the new workspace"

**Expected behavior**
Tooltip should read "**Folder** will be moved to the root of the new workspace"

**Screenshots**
![image](https://user-images.githubusercontent.com/4312346/93281656-a048f800-f820-11ea-8bc4-62693ded06f4.png)

**Desktop (please complete the following information):**
```
Version: Insomnia Core 2020.4.0
Release date: 10/09/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Comment by tarunyadav1** [comment]
Hey, Can you assign this issue to me?

Thank you

**Comment by develohpanda** [comment]
Hi @tarunyadav1! Feel free to work on it and send through a PR 😄
