### ISSUE TITLE
PDF Preview broken in Insomnia 2020.4.0

### ISSUE THREAD

**Issue by janispritzkau** [getinsomnia/insomnia#2623]
**Describe the bug**
The response preview is empty and a error is thrown in the console.

**To Reproduce**
Send a GET request with a response of content type `application/pdf`.

**Screenshots**
![insomnia-broken-pdf-preview](https://user-images.githubusercontent.com/1692391/93336838-962af780-f828-11ea-86bc-119c010ceb91.png)

**Desktop:**
 - OS: tested on Linux and macOS
 - App Version: Insomnia Core 2020.4.0

**Comment by DMarby** [comment]
Thank you for reporting this!

INS-127

**Comment by develohpanda** [comment]
A fix to this has been released with [2020.4.1](https://github.com/Kong/insomnia/releases/tag/core%402020.4.1) 😄
