### ISSUE TITLE
Support OAS 3.1

### ISSUE THREAD

**Issue by black-snow** [getinsomnia/insomnia#2625]
**Is your feature request related to a problem? Please describe.**
OAS 3.1 hasn't settled yet but is quite close to being final (afaik). I couldn't find any issue / roadmap tracking progress for this - please close the issue & hint me if I'm blind.

**Describe the solution you'd like**
Support [OAS 3.1 RC0](https://www.openapis.org/blog/2020/06/18/openapi-3-1-0-rc0-its-here) / JSON-Schema 2019-09 and keep on improving until it's final.

**Comment by nijikokun** [comment]
Good call-out @black-snow still waiting for the third-party libraries to catch up 👀

**Comment by black-snow** [comment]
not stale

Haven't check for a while, has anything happened here in the meantime @nijikokun ? https://spec.openapis.org/oas/v3.1.0 is out.
