### ISSUE TITLE
Keyboard shortcut for switching workspace

### ISSUE THREAD

**Issue by RHammar** [getinsomnia/insomnia#2628]
It would be great if there was a keyboard shortcut to switch between different workspaces.

I have set up Insomnia so that each microservice that I am working with is under it's own workspace. I keep switching back and forth between them, it would be great for productivity to be able to do it using a keyboard shortcut.

**Comment by tharun208** [comment]
@RHammar, you can use `command + p` quick switch to switch between workspaces.
