### ISSUE TITLE
[Feature Request] Support for Global Variables

### ISSUE THREAD

**Issue by nsankaranarayanan** [getinsomnia/insomnia#263]
## Overview
- `Insomnia Version: v5.1.0
- `Operating System: Windows 10 Professional
- `Summary: It would be nice to have support default variables like current date time, GUID, global counter, OS, insomnia version.
- Requirement: When we do testing (for example a POST request), I may want to use the date time or GUID as a placeholder in my request body to avoid record duplication. In the below example, the request will succeed the first time as it will insert a new user. The subsequent times it will fail as it would be considered as a duplicate.
- Example Request: 
POST http://www.example.com/Users

Body
{
    "username": "john@example", 
    "firstName": "John", 
    "lastName": "Doe"
}

Thanks

**Comment by gschier** [comment]
Hi @nsankaranarayanan. 

Some of what you have requested already exists. Currently, there are helper functions for the following:

- `UUID` generate unique UUIDs on each request
- `Now` for generating ISO-8601 or Unix timestamps
- `Base64` for encoding/decoding strings
- `Response Value` for referencing values from other request's responses

If you press `CTRL+Space`, you will see a list of possible functions to choose from.

![image](https://cloud.githubusercontent.com/assets/587576/26558427/7c777c78-445d-11e7-8c18-1367c18b27c7.png)

I'm currently tracking ideas for additional template tags as well (#240) and have added your remaining ideas to the list.

**Comment by nsankaranarayanan** [comment]
Thank you and that works. It would be a big help if you can update the documentation.

**Comment by gschier** [comment]
@nsankaranarayanan will do! Thanks for pointing that out.
