### ISSUE TITLE
How do I save a document

### ISSUE THREAD

**Issue by daniel-tavares-osf** [getinsomnia/insomnia#2636]
Hi,

How do I save a document that I have created.

In Insomnia Design I only find the Duplicate, Rename and Delete options.

![Insomnia](https://user-images.githubusercontent.com/48334666/93541772-b7c1d700-f92d-11ea-82b4-7a60dce577fd.jpg)

**Comment by develohpanda** [comment]
Hi @daniel-tavares-osf, this isn't supported within the application right now - we are working on something, but no ETA yet. In the meantime, an alternative option would be to export it using the [CLI](https://support.insomnia.rest/article/125-cli-export-spec).

That drop-down menu can also be extended with a custom plugin as another option.
