### ISSUE TITLE
[Feature Request] Option to disable certificate validation on Git operations in Designer

### ISSUE THREAD

**Issue by rezrov** [getinsomnia/insomnia#2639]
**Is your feature request related to a problem? Please describe.**
Our internal git server uses a company self-signed cert and CA which is installed on our workstations. This causes git operations in Designer to fail because it can not access these certificates (using OSX).

**Describe the solution you'd like**
An option in Designer to disable certificate validation for git operations, similar to the option already available to disable validation for requests.

**Describe alternatives you've considered**
I've done some searching on the subject, and it seems like getting Designer to use the system keychain for validation would be difficult, if it is possible at all. Alternatively, if Designer could import certificates to use for git or other requests, it would solve the problem, but this seems like it would be a much larger effort.

**Additional context**

<img width="779" alt="Screen Shot 2020-09-17 at 11 17 46 AM" src="https://user-images.githubusercontent.com/729823/93616278-89321380-f9a2-11ea-93a7-d6faa5b8fd94.png">

**Comment by smacktoid** [comment]
Just ran into this issue too. I tried to configure Insomnia Designer to point to our internal corporate Git repository, but I immediately got an error that simply reads 'self signed certificate'

![image](https://user-images.githubusercontent.com/3959288/105343969-37acc600-5bda-11eb-95ef-b895bf42477c.png)

**Comment by develohpanda** [comment]
Unfortunately I don't have an exact timeline on this, but we do have in the near-time roadmap to improve certificate use with sync, so this will be covered off eventually. :)

**Comment by smacktoid** [comment]
This is still an issue. It should stay open.
