### ISSUE TITLE
Microbug – autoscroll in response preview scrolls badly upwards

### ISSUE THREAD

**Issue by deep-outcome** [getinsomnia/insomnia#2646]
**Description**
When it is upwards autoscrolled in response preview window the searched term is shown only partially.

**Repro steps**
1. Get some long response.
2. Find some term in the beginning.
3. Scroll down.
4. Search for the term of step 2.

**Expected behavior**
Term is autoscrolled fully.

**Screenshots**
http://software919.cz/__other/Autoscroll%20upwards.png

**Desktop (please complete the following information):**
Version: Insomnia Core 2020.4.0
Release date: 9/10/2020
OS: Windows_NT x64 10.0.19041
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0

**Comment by kreosus** [comment]
@nijikokun may I tackle this issue?
