### ISSUE TITLE
Environment color selection on MacOS

### ISSUE THREAD

**Issue by stvkpln** [getinsomnia/insomnia#2647]
**Describe the bug**
This bug is two-fold:

1. When trying to set an environment color on an environment with no color set, the only option for picking a color is RGB. This was not the case on earlier releases, where you could use the "pencil picker" (sorry, I don't know what this is actually called!!) or any of the usual MacOS options to pick.
2. For environments where you want to change the color, you have to unset, then you're back to the previous issue. Trying to change without brings the menu up for a second, then it disappears.

I am able to work around this for now by reverting back to 2020.3.0

**To Reproduce**

1. Go to manage environments
2. Pick an environment with a color
3. Go to change color on the environment
4. Note no color panel comes up

For the second issue:
Perform steps 1-3
- Note that the color pane that comes up is not the one that is the normal / native MacOS panel for color things; it's a whole other thing that only allows for RGB selection.

**Expected behavior**
I expect to see the color options as captured under screenshots!!

**Screenshots**
This is missing:
![image](https://user-images.githubusercontent.com/17091287/93803357-9432b100-fbf9-11ea-88c7-aaecfb72dc5e.png)

**Desktop (please complete the following information):**
Version: Insomnia Core 2020.4.0
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
Installed either from brew or downloading direct from the website

**Comment by stvkpln** [comment]
I meant to say "specific to 2020.4.0" -- the behavior is as expected on 2020.3.0 (I just reverted to capture that screen shot)

**Comment by Netoun** [comment]
I can take this

**Comment by jgiovaresco** [comment]
For the first issue

>When trying to set an environment color on an environment with no color set, the only option for picking a color is RGB. This was not the case on earlier releases, where you could use the "pencil picker" (sorry, I don't know what this is actually called!!) or any of the usual MacOS options to pick.

It is related to the Electron upgrade (see https://github.com/electron/electron/issues/24830#issuecomment-695369844).
This is now the default behavior for Electron and it could be disabled. IMHO we should keep the default behavior. What do you think about it?

**Comment by develohpanda** [comment]
> This is now the default behavior for Electron and it could be disabled. IMHO we should keep the default behavior. What do you think about it?

I agree to keeping default behavior. If it needs to be changed, can become a custom setting in the future.

**Comment by stvkpln** [comment]
Just wanted to leave a comment to say thank you for solving -- I get this is a pretty corner case thing for people with Mac's who make use of multiple environments and use colors to differentiate them, so to see this resolved quickly is a big part of why I continue to support Insomnia. You folks are awesome!
