### ISSUE TITLE
OAuth 2 not capturing redirection

### ISSUE THREAD

**Issue by nymous** [getinsomnia/insomnia#2657]
**Describe the bug**
I configured an OAuth 2 authentication against a PingOne server with the following parameters:
- Grant type: Authorization Code
- Authorization URL: {pingUrl}/as/authorization.oauth2
- Access token URL: {pingUrl}/as/token.oauth2
- Client ID, Client secret: set correctly
- Redirect URL: {myAppUrl}/api/auth/ping/callback

Unfortunately Insomnia doesn't seem to catch the redirect and never closes the authentication window. Instead I can see my app page, with me logged in (indicating that the login process happened correctly).

For reference, here is what happens in my browser when I load the authorization URL generated by Insomnia (`"https://{pingUrl}/as/authorization.oauth2?response_type=code&client_id=0P1605f5930e32ff16d7208d03ad7c3eb1&redirect_uri=https%3A%2F%{myAppUrl}%2Fapi%2Fauth%2Fping%2Fcallback&scope=openid%20profile%20email"`:
![request_in_browser](https://user-images.githubusercontent.com/4216559/94051709-36a88b00-fdd8-11ea-8269-199a0d8afef5.png)

To help me debug what happens in Insomnia, I unpacked the `app.asar` in order to edit the `bundle.js` to add more logs.
I tried adding logs to all [navigation events](https://www.electronjs.org/docs/api/web-contents#event-will-navigate) from Electron:
```js
function authorizeUserInWindow(...) {
 return new Promise((resolve, reject) => {
    const child = new electron__WEBPACK_IMPORTED_MODULE_0___default.a.remote.BrowserWindow({
      // ...
    });

    child.webContents.on('did-navigate', (e, u) => {
      // Be sure to resolve URL so that we can handle redirects with no host like /foo/bar
      const currentUrl = child.webContents.getURL();
      console.log({"did-navigate": true, currentUrl, e, u})

      _parseUrl(currentUrl);
    });

    child.webContents.on('will-redirect', (e, u) => console.log({'will-redirect': true, e, u}))
    child.webContents.on('will-navigate', (e, u) => console.log({'will-navigate': true, e, u}))
    child.webContents.on('did-redirect-navigation', (e, u) => console.log({"did-redirect-navigation": true, e, u}))
    child.webContents.on('did-frame-navigate', (e, u) => console.log({"did-frame-navigate": true, e, u}))
    child.webContents.on('did-navigate-in-page', (e, u) => console.log({"did-navigate-in-page": true, e, u}))
```
This gives me the following logs in Insomnia developer console:
![request_in_insomnia](https://user-images.githubusercontent.com/4216559/94051601-095bdd00-fdd8-11ea-9d29-4bd49ff35d4e.png)

As you can see the redirect to `https://{myAppUrl}/api/auth/ping/callback?code=abc` is never seen by Insomnia

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Installation Method: AUR `insomnia`
 - App Version: 2020.3.3

**Additional context**
I did find these two issues #619 and #404 that seem related.
Also, with the same configuration in Postman I can retrieve an OAuth token with no issue.

**Comment by nymous** [comment]
The issue hasn't reproduced since, so either something changed in Insomnia or we changed something with our redirects ^^'
Anyway, I'll close the issue.

**Comment by dimitropoulos** [comment]
thanks for the followup and apologies that no one responded.  we're trying to be more responsive than we were able to be in the past.
