### ISSUE TITLE
[Feature Request] Passing Default Headers

### ISSUE THREAD

**Issue by nsankaranarayanan** [getinsomnia/insomnia#266]
## Overview
- `Insomnia Version: v5.1.0
- `Operating System: Windows 10 Professional
- `Summary: Need a way to pass a default set of headers for all requests under a folder.
Currently I am passing the headers like Accept, Authorization, etc for each one of the requests separately. Is there a way to add them at the folder level, so that I don't have to pass them every time.

The objective is to avoid passing it every time and rather the request inherit the parent folder's settings.
It would also be useful to override the parent folder's headers if the request had the same header.

Thanks

**Comment by gschier** [comment]
Hi @nsankaranarayanan. There's no way to do this at the moment, but it's a highly-requested feature. 

I've been trying to think of a clean way to do this for a while, and just had an idea.

The headers tab could include include a `<select>` dropdown at the bottom and let the user choose an environment variable to include headers from. The environment variable could be a simple key-value object and could be included in either the global/sub/folder environment.

Here's what an example environment might look like:

```json
{
  "headers": {
    "Accept": "application/json",
    "Authorization": "token 1234"
  }
}
```

I think I'll play around with this today and see if I can get something working.

**Comment by gschier** [comment]
The existing functionality would be preserved, but there would be an additional option to extend an environment variable. I'm thinking something like this:

![image](https://cloud.githubusercontent.com/assets/587576/26560997/ab22016c-446f-11e7-9c3f-e4f5ec888195.png)

**Comment by wonderbeyond** [comment]
Waiting for release.

**Comment by gschier** [comment]
Closing this one in favor of #447

**Comment by gschier** [comment]
If anyone is still wanting this, I created a simple plugin to do it. It uses a special environment variable to pull header configuration from: https://www.npmjs.com/package/insomna-plugin-default-headers

**Comment by wonderbeyond** [comment]
Yes, Initially, I want such a method to pass authorization header, however I always copy from existing request as walkaround.

**Comment by wonderbeyond** [comment]
@gschier and you've mismatched `insomnia` in the plugin name.

**Comment by gschier** [comment]
@wonderbeyond for authentication, you probably want to follow #447 
Also thanks. I fixed the typo.

**Comment by wonderbeyond** [comment]
@gschier Thanks! #447 is awesome idea!
 I've been always copying existing requests, waiting you save me.

**Comment by m3c-ode** [comment]
I've tried using the plug-in, but it does not seem to create any UI changes for me to define my default header for all my collection. How should it be used?
