### ISSUE TITLE
[Feature Request] Bind value to the URL path. eg: /books/{id}/show

### ISSUE THREAD

**Issue by erlangparasu** [getinsomnia/insomnia#2664]
**Is your feature request related to a problem? Please describe.**
Currently there is Query tab to set query parameters. But i want to set parameters in path too.

**Describe the solution you'd like**
Bind the values to the url path template.

Thank you!

**Comment by erlangp** [comment]
Something like Retrofit `@Path("id") id: Int`

**Comment by smacktoid** [comment]
You can set various tags in the path already. Hit ctrl + space to bring up the list. 

There are all sorts of things you can configure

- Prompt the user to type the value in before sending the request
- Use an environment variable
- Extract a property from another request in the workspace

**Comment by erlangparasu** [comment]
thanks for answer sir, but i actually want that url value is set in UI like Query form, not defined via the environment

**Comment by smacktoid** [comment]
You can use a Prompt Tag to do that. When you send the request it will pop up a dialog asking you to enter the value of the placeholder.

**Comment by ghost** [comment]
using the prompt is slower since you have to click twice to send an http request

**Comment by ghost** [comment]
#203 would fix this issue for me

**Comment by erlangparasu** [comment]
?
