### ISSUE TITLE
Sub environment resets changes (upon sync?) 

### ISSUE THREAD

**Issue by tauinger-de** [getinsomnia/insomnia#2665]
**Describe the bug**
Modifications made to sub environment are reset to previous value after ~10 seconds

**To Reproduce**
1. CTRL-E to edit env
2. Change env content
3. Click Done
4. Repeat pressing CTRL-E to open env and click Done to close for ~ 10 seconds
5. OR perform a "Sync Now"

**Expected behavior**
Changes to env remain. Instead, after some time / after sync the changes disappear and the previous state is restored

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App Version 2020.4.1

**Additional context**
Syncing is enabled.

**Comment by tauinger-de** [comment]
BTW occurs only in sub-env that I received thru sync. Changes in base-env created by me remain.

**Comment by DMarby** [comment]
Hi @tauinger-de,

This issue should be resolved in our new sync system, Version Control Sync. As we are sunsetting legacy sync in favour of it, I'm going to close this issue. You can start using Version Control Sync today by following the instructions here: https://support.insomnia.rest/article/67-version-control#getting-started 
Please send an email to support@insomnia.rest if you run into any further sync issues, and we'll be able to provide better assistance.

More information about the sunsetting and Version Control Sync can be found here:
https://insomnia.rest/blog/sunsetting-legacy-sync/
https://support.insomnia.rest/article/67-version-control
