### ISSUE TITLE
Wrong window icon for Insomnia Core on Windows

### ISSUE THREAD

**Issue by kwielo** [getinsomnia/insomnia#2672]
**Describe the bug**
Window icon for Insomnia Core is from Insomnia Designer, however the taskbar and start menu icon is correct.

When switching between windows it is confusing and takes time to find the write window, especially for visuals (as myself). 

**To Reproduce**
1. Run Insomnia core
2. Look at the window icon
3. Try to switch windows with Alt + Tab

**Expected behavior**
The icon should be the same as the one in task bar or start menu.

**Screenshots**
Invalid icon:
![image](https://user-images.githubusercontent.com/5716991/94422349-3d901e80-0187-11eb-8af5-498d97191bb7.png)

Correct one:
![image](https://user-images.githubusercontent.com/5716991/94422197-002b9100-0187-11eb-8ab5-f71fef1cac90.png)

**Desktop (please complete the following information):**
- Version: Insomnia Core 2020.4.1
- Release date: 23/09/2020
- OS: Windows_NT x64 10.0.19041
- Electron: 9.1.1
- Node: 12.14.1
- V8: 8.3.110.13-electron.0
- Architecture: x64
- node-libcurl: libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0

**Additional context**
N/A

**Comment by develohpanda** [comment]
Thank you for reporting this! INS-80.

**Comment by emelendez89** [comment]
That's odd, I see the right icon on both window and taskbar (Also on Alt+Tab which I can't screenshot):
![Captura de Pantalla 2020-09-29 a la(s) 1 52 33 p  m](https://user-images.githubusercontent.com/1562673/94603057-59fd8b00-025b-11eb-8be4-fa8ea1e8a133.png)

**Comment by develohpanda** [comment]
@emelendez89 you're seeing an icon consistently, but it's the wrong one. You've got Insomnia Core, but the icon you see is the Designer one 😅

**Comment by emelendez89** [comment]
@develohpanda  I see, I thought it was a new design, so yeah, I guess I supported evidence to the issue then. (I didn't even knew about Insomnia Designer, I might use it from now on)
