### ISSUE TITLE
Anti-virus reporting a permissions issue with a build artifact file

### ISSUE THREAD

**Issue by naruto112** [getinsomnia/insomnia#2673]
When installing insomnia on my machine, my anti-virus detected that it is a malicious one and shows that a js file has a problem. Guys is this a bug or purposeful?

**Comment by develohpanda** [comment]
Hi @naruto112, as long as you downloaded from official channels (github releases, Linux snap store, insomnia.rest, etc), it is most definitely **not purposeful**.

Could you please add any further information about particular files your antivirus is reporting? In the past I remember seeing something about a `.crypto` file.

Additionally, which version you are trying to install, was version your OS is, and where you downloaded Insomnia from/method of installation.

Thank you!

**Comment by naruto112** [comment]
Hello, I downloaded it directly from the official website. I will send an image of the file in which the anti-virus relatoy.

![Captura de Tela 2020-09-28 às 09 45 51](https://user-images.githubusercontent.com/9589702/94433977-73c1a400-016f-11eb-9175-a2eef16d53cb.png)

**Comment by develohpanda** [comment]
It looks like FortiClient which is also Electron, contains that file, as well as Skype, just looking at the error messages there. This is just one of the build artifacts, we can take a look but I'm not sure the likelihood of a fix existing for it. Which antivirus are you using?

Note: I will rename this issue to reflect this information. 😄

**Comment by naruto112** [comment]
Hi, the name is  cleaMyMac

site: https://cleanmymac.com/pt

**Comment by kreosus** [comment]
Hi @naruto112 
Do you receive the same error when using our latest release located here: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.4
