### ISSUE TITLE
History – cannot navigate to item (1st in 2nd group)

### ISSUE THREAD

**Issue by deep-outcome** [getinsomnia/insomnia#2675]
**Description**
1st item in second group in history cannot be navigated as long as it is 1st one in 2nd group.

**How to reproduce**
1. Execute 2 request.
2. Wait for about 8 mins.
3. Execute new request.
4. Navigate to history.
5. Open last request (i.e. 1st of step 1).
6. Try open 2nd request from step 1.

**Expected behavior**
History is opened.

**Screenshots**
![History](https://user-images.githubusercontent.com/26486200/94561949-fed09600-0264-11eb-8fdd-08a36552ddd5.png)

**Desktop (please complete the following information):**
Version: Insomnia Core 2020.4.1
Release date: 9/23/2020
OS: Windows_NT x64 10.0.19041
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0

**Additional context**

- Video can be provided in case of misunderstanding.
- Instead of 1st item from 2nd group is chosen 1st item from1st group.

**Comment by schester44** [comment]
On line 74 of response-history-dropdown.js, `null` is being passed to the `value` prop of `<DropdownItem />` when the index is `0`. 

Path: packages/insomnia-app/app/ui/components/dropdowns/response-history-dropdown.js

**Comment by deep-outcome** [comment]
Bugs should no be closed by bot.

**Comment by dimitropoulos** [comment]
@Uzivatel919 We agree.  Since this happened we removed the bot altogether as we were frustrated by the same thing.  Sorry for the annoyance it caused.
