### ISSUE TITLE
Use System Proxy

### ISSUE THREAD

**Issue by emelendez89** [getinsomnia/insomnia#2677]
**Is your feature request related to a problem? Please describe.**
Ex. I'm always frustrated when I have to deal with multiple proxies, the company I work for have this <filename>.pac (proxy autoconfig file) which is actually a Javascript file that Windows use to select the proxy.

**Describe the solution you'd like**
Either a radio button that select from specific proxy (textboxes as now it is) or pick the one used by the system (Same as Postman)

**Describe alternatives you've considered**
You can also do it the same way as Windows10 where you can enter the URL to fetch the pac file and run it before the request to select the proxy according to the PAC file.

**Additional context**
I hope this makes sense.

**Comment by meskill** [comment]
Picking proxy settings from system will make usage of insomnia much easier for me.

For now I have to manually enter proxy settings every time
