### ISSUE TITLE
Validate environment variables against nested keys

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2684]
There is a bug here in that both previously and now, only the root keys are checked. A recursive algorithm needs to be created to validate nested keys appropriately.

_Originally posted by @develohpanda in https://github.com/Kong/insomnia/pull/2601#discussion_r498003061_

Root keys must follow these rules (as currently implemented):
- A key cannot be simply `_`
- A key cannot start with `$`
- A key cannot contain `.`

Nested keys must follow these rules:
- A key cannot start with `$`
- A key cannot contain `.`

Note, these rules do not apply for array _items_, but a complex object inside an array, must have keys that follow the nested rules.

<details>
<summary>Context about $ and . rules</summary>

NeDB has rules to prevent a key from starting with $ or contain a ., so I have updated the regex key check for the environment editor. In the current implementation, errors are presented in console, and the changes do not persist (semi-silent failure), if you try to save something without following these rules which the existing regex did not check for.

![](https://user-images.githubusercontent.com/4312346/94640682-d5cf0480-033b-11eb-9707-bc2adec39c06.png)

</details>

There is some example code [here](https://github.com/Kong/insomnia/blob/1bbbf38a9653792fd137662d015846f4334b1989/packages/insomnia-app/app/templating/utils.js#L33-L60)  that does a similar recursive process.

**Comment by johnhorsema** [comment]
Hi, I'm working on this issue. Do I submit a pull request with the `develop` branch for this issue?

**Comment by develohpanda** [comment]
Hi @johnhorsema, yes, PR against develop please!
