### ISSUE TITLE
Insomnia does not allow inserting dynamic values of the body of the GraphQL request in Windows

### ISSUE THREAD

**Issue by felinto-dev** [getinsomnia/insomnia#2686]
**Describe the bug**
Hello,

I'm a try to insert dynamic values in GraphQL query insomnia doesn't do anything. I press CRTL + SPACE but nothing happens.
![Screenshot_46](https://user-images.githubusercontent.com/32253743/94998879-8e3eb780-058b-11eb-9493-a9e43552f114.png)

If I do it with a REST API, everything works fine:
![Screenshot_47](https://user-images.githubusercontent.com/32253743/94998892-b4fcee00-058b-11eb-9bb8-90351895b1da.png)

A colleague shared with me that this does not happen on the Mac OS operating system.

**Desktop (please complete the following information):**
 - Windows 10 PRO - Version 2004(OS Build 19041.508)
 - Installation Method: Chocolately
 - App Version: Imsomnia Core 2020.4.1 (Release date: 9/22/2020)

**Comment by Gabrielcmp** [comment]
Having the same issue when trying to add environment variables to a graphQL, but they do work if you add them manually.

When I was using directly the post method, passing query string, the variables were being read ok:
![image](https://user-images.githubusercontent.com/29134313/106780322-a2242400-6626-11eb-909c-78bd373ddb18.png)

When I switched it to graphQL query, it continued to work, but the formatting didn't. 
Also, I couldn't add new environment variables with ctrl + space, only autocomplete with what was in the schema. 
![image](https://user-images.githubusercontent.com/29134313/106782022-799d2980-6628-11eb-9b08-421a0195f95d.png)


is it possible to make the formatting work and being able to add environment variables in graphQL mode? 

**Desktop (please complete the following information):**
-  Ubuntu 20.04.1 LTS
- Installation Method: deb package
- App Version: Insomnia Core 2020.5.2

**Comment by jostFT** [comment]
This is already an open issue (#1937)
it has existed for a long time. None of the devs have even glanced over it yet, so who knows when this will be fixed.
I'm personally considering switching to Postman, for various reasons - one being this particular issue

**Comment by jostFT** [comment]
This task has become stale, because the developers haven't given it the time of day.

**Comment by TheRedPanda17** [comment]
Still a problem for me.
