### ISSUE TITLE
Designer - Option for auto refreshing/polling OpenAPI schema

### ISSUE THREAD

**Issue by wkrueger** [getinsomnia/insomnia#2687]
**Target**

Insomnia designer.

**Use case**

I'm loading an auto-generated OpenAPI schema from `http://localhost:3000/api-json`. As I develop the application and it auto-reloads, I have to copy-paste the JSON schema from the browser to Insomnia Designer for updates.

**Feature idea**

Add an option to poll the source from time to time to update the schema. Lock the inline editing if this is enabled.

**Comment by daveharding** [comment]
+1 This would be really useful, same use case for our team as described by @wkrueger

**Comment by nijikokun** [comment]
While we currently don't have any plans to add this functionality ourselves, would be open to a PR which adds this functionality

**Comment by shavo007** [comment]
Its the same for remote right? For example, if i am pulling in github OAS from remote uri, does it automatically refresh or is it point in time?
