### ISSUE TITLE
Bearer Authorization header change prefix

### ISSUE THREAD

**Issue by rickmartensnl** [getinsomnia/insomnia#2689]
**What is your question?**
A clear and concise description of what you are wanting to ask. Ex. I'm always frustrated when [...]
Is there any way to use a bearer authorization header with another prefix? I want to change my prefix to `Token {apiKey}` instead of `Bearer {apiKey}`. How can I do that? If it is possible if not please fix this.

**What is the context?**
If applicable, describe the context in which you are asking the question. Ex. I am trying to do _x_ with _y_ [...]
I'm trying to change `Bearer {apiKey}` in the `Authorization`-header to `Token {apiKey}`

**Comment by jgiovaresco** [comment]
Which authentication mode do you use?

You can change the Header prefix of `OAuth2` authentication in Advanced Options using `HEADER PREFIX` input.

<img width="578" alt="Screenshot 2020-10-06 at 07 36 57" src="https://user-images.githubusercontent.com/4171593/95162940-151bac00-07a7-11eb-99d4-000f98c05128.png">

If you are using the `Bearer Token` mode, there is a `PREFIX` input to change the prefix.

**Comment by rickmartensnl** [comment]
I'm trying to add it in the .yml. I'm using designer not the core version.

**Comment by develohpanda** [comment]
It looks like the OpenAPI 3.0 standard uses `Bearer` as the prefix without any official syntax to alter the prefix, as per the [documentation](https://swagger.io/docs/specification/authentication/bearer-authentication/).

If changing the prefix is officially supported in OpenAPI then I'm sure it's something we can cater for. If not, some more discussions/thought needed here.

**Comment by rickmartensnl** [comment]
Is there a way to do the same thing like bearer authentication but then with apiKey, I have seen some things about template variable inside apiKey authorization header, but for some reason, the Insomnia Designer doesn't detect template.

**Comment by nijikokun** [comment]
> Is there a way to do the same thing like bearer authentication but then with apiKey, I have seen some things about template variable inside apiKey authorization header, but for some reason, the Insomnia Designer doesn't detect template.

OpenAPI 3.0 does allow setting up an API Token with a custom header name but does not allow setting values (see [OpenAPI 3.0 API Keys Documentation](https://swagger.io/docs/specification/authentication/api-keys/))

You would have to use Template Variables within the debug tab of Designer to set the `Token {value}` once your requests are generated

**Comment by nijikokun** [comment]
Closing since the original request is a limitation of the OpenAPI 3.0 specification
