### ISSUE TITLE
Starting two requests and cancelling the first one does not behave as expected

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2690]
**Describe the bug**
I started two long running requests, the first one takes 15 seconds and the second one takes 10 seconds. Then I go to the first request and press cancel, but nothing happens. Then I look at the second one, and see that it has been cancelled.

The _cancel request_ button cancels the last started request, not the active request. I see the correct request duration as I switch between the two, so there is _some_ logic to handle multiple active requests.

<details>
<summary>Here is an example server using express to replicate this</summary>

```js
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
    const delaySec = Number.parseInt(req.query['delaySec'] || '2');
    setTimeout(function () {
        res.send(`Delayed by ${delaySec} seconds`);
    }, delaySec * 1000);
})

app.listen(port, () => {
    console.log(`Example app listening at http://localhost:${port}`)
})
```

</details>

**To Reproduce**
1. Start request A
2. Start request B
5. Go to request A
3. Cancel request A
4. **Nothing happens**
5. Go to request B
6. **Notice it is cancelled**

**Expected behavior**
Cancel only the active request, not the last started request.

**Screenshots**
![2020-10-06 18 47 29](https://user-images.githubusercontent.com/4312346/95163554-9bb2a680-0804-11eb-9074-741e53dfd6f2.gif)

**Desktop (please complete the following information):**
```
Version: Insomnia Core 2020.4.1
Release date: 30/09/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Additional context**
It is likely that the `cancelCurrentRequest` function needs to be made smarter - perhaps storing/clearing the `cancelRequestFunction` in a dictionary indexed by the request id instead of a single function variable.

https://github.com/Kong/insomnia/blob/1bbbf38a9653792fd137662d015846f4334b1989/packages/insomnia-app/app/network/network.js#L112-L119

The timing is updated correctly when switching between two active requests, because the request start time is stored in a dictionary indexed by the request id.

https://github.com/Kong/insomnia/blob/1bbbf38a9653792fd137662d015846f4334b1989/packages/insomnia-app/app/ui/containers/app.js#L1426

**Comment by selamanse** [comment]
@develohpanda I'd be glad like to try this.

**Comment by develohpanda** [comment]
@selamanse sure! Give it a go and reach out if you need any help. 👏
