### ISSUE TITLE
Linux export/import window doest not show properly

### ISSUE THREAD

**Issue by diegogub** [getinsomnia/insomnia#2691]
**Describe the bug**
Trying to export endpoints, the window does not show any character, everything as squares .

**To Reproduce**
1 . Go to Export / Import 

**Screenshots**
![Screenshot_20201006_081237](https://user-images.githubusercontent.com/2489012/95165224-db996f80-07ab-11eb-9f16-0e186071e902.png)

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Installation Method: snap 
 - App Version: insomnia 2020.4.1 from Insomnia (gschier1990)

**Comment by develohpanda** [comment]
This looks very much related to #2614 🤔

**Comment by diegogub** [comment]
yes, it's same issue. . I will close this one then. Thanks!

**Comment by develohpanda** [comment]
No worries, thank you for reporting! From the activity in the other issue we're still trying to get to the bottom of it. Even though this issue is closed it will be linked in #2614 when being investigated. 😄
