### ISSUE TITLE
Blank screen when opening "Applications->Preferences"

### ISSUE THREAD

**Issue by AbrahamNuno** [getinsomnia/insomnia#2707]
I just installed Insomnia in Fedora 32 following the instructions in the Installation page.

The application launches properly and I'm able to create and run some requests, but when I go to "Application -> Preferences" all I get is a blank screen:
![image](https://user-images.githubusercontent.com/43212222/95609847-05a99680-0a25-11eb-8617-f116039cca85.png)

I also noticed that the about screen is not showing properly:
![image](https://user-images.githubusercontent.com/43212222/95609961-2eca2700-0a25-11eb-999c-d76c9e9d4935.png)

**Comment by nijikokun** [comment]
Appears to be related to #2614

**Comment by AbrahamNuno** [comment]
Hi @nijikokun!

Yes, issue #2614 is about unreadable about dialog, but not about blank screen when opening "Application -> Preferences".

So I guess dev team can ignore the about dialog report of this issue and focus only on the "Application -> Preferences" one.

BTW... I followed the steps in #2614 about `fontconfig` but didn't fix the issue for me :(.

**Comment by nijikokun** [comment]
@AbrahamNuno does the console logs have any errors when you open the application preferences? `View > Toggle Dev Tools > Console`

**Comment by schemar** [comment]
I have the same issue. Also on Fedora 32. I use snap. The AppImage works as expected.

The console log deosn't give any output. The last line it logs is this:

```
[ga] Event Modals, Show, SettingsModal                           bundle.js:31781
```

And then it shows this modal:

```
DevTools was disconnected from the page.
Once page is reloaded, DevTools will automatically reconnect.
```

I also get a notification that "insomnia has crashed". It is still responsive, e.g. I can open and close "about", but the main window seems to have crashed unrecoverable.

This is more log output:

```
$ snap run insomnia --enable-logging

...

[14059:1014/213209.412648:INFO:CONSOLE(31781)] "[ga] Event Modals, Show, SettingsModal", source: file:///snap/insomnia/105/resources/app.asar/bundle.js (31781)
Fontconfig warning: FcPattern object weight does not accept value [0 205)

(insomnia:14059): IBUS-WARNING **: 21:32:09.827: Unable to connect to ibus: Could not connect: Connection refused
```

**Comment by johanhammar** [comment]
Other Electron based apps also have this problem, https://github.com/laurent22/joplin/issues/4016, and it does indeed seem to have something with snap to do.

**Comment by alannaidon** [comment]
I have the same problem!  
White screen when accessing Settings and the alian characters when I go to about.

Using fedora 33 workstation and installed Insomnia via Snap

**Comment by alannaidon** [comment]
Same problem here. If I go to _Help > Keyboard Shortcut_ it works. All the tabs works, except the `General`.  
Probably an issue with the `fonts`?

**Comment by ravanscafi** [comment]
I'm having the same issue. Insomnia 2020.5.2 installed on Ubuntu via Snap.

**Comment by gpascual4qima** [comment]
Hello, I got the same issue with Snap bundle but not with the AppImage. I have similar behavior with all tool install with snap and using electron stack.

**Comment by rgiaviti** [comment]
I'm having the same issue here. I've installed insomnia via snap and the installed version is 2020.5.2 (got with `snap info insomnia`. When I ran insomnia with `$ snap run insomnia --enable-logging` and opened the `Preferences` screen. The log is attached. Hope it helps.

[insomnia.log](https://github.com/Kong/insomnia/files/6021954/insomnia.log)

**Comment by apisaint** [comment]
Looks like you've ran into an issue with snap/linux installation, and is doesn't seem to be related to Insomnia but the system font cache, at least according to previous reports. There seems to be a viable fix here https://github.com/Kong/insomnia/issues/2614#issuecomment-700711061

**Comment by Bubelgin** [comment]
Same issue after updating to the latest version just today, getting blank screen if you try to navigate to preferences.
![image](https://user-images.githubusercontent.com/39793716/125328792-a45c7e00-e33c-11eb-9c19-b2b531727e38.png)

**Comment by filfreire** [comment]
Closing as stale. We have updated through a handful of Electron versions since the issue was reported. Please report a new issue if you still face similar problem.
