### ISSUE TITLE
Add help menu item for accessing the logs folder

### ISSUE THREAD

**Issue by DMarby** [getinsomnia/insomnia#2719]
Add a new item to the Help menu to make it easier to access the folder containing the application logs.

**Implementation notes**:
For getting the log folder path, a new method should be added to [common/log.js](https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/app/common/log.js) that returns the folder.
The folder should be able to be retrieved by extracting the directory from `log.transports.file.getFile().path`

For the help menu, a similar approach to what is currently being done for opening the Application Data folder should work: https://github.com/Kong/insomnia/blob/61b27ae3c45bff7bfddd5ddd6e6e0651145b849a/packages/insomnia-app/app/main/window-utils.js#L267-L273

**Comment by ilkerunal** [comment]
Hello, I'd like to solve this. Can you assign it to me ?

**Comment by DMarby** [comment]
Hi @ilkerunal!

Awesome, please give it a go and submit a PR whenever ready, let me know if you require any assistance.
