### ISSUE TITLE
[Feature Request] JSONPath History and/or Autocomplete

### ISSUE THREAD

**Issue by iceberg901** [getinsomnia/insomnia#273]
## Overview
- `Insomnia Version:` _5.1.1_
- `Operating System:`  _MacOS 10.10.5_
- `Summary: ` I need a way to easily access and re-run, possibly with small modifications, previously run JSONPath queries on my response contents.  If possible, it would also be great to have predictive suggestions as I am typing new queries since I find it very hard to remember JSONPath syntax (perhaps this is outside scope and should be considered a separate issue?)

## Other Notes

+ At a minimum, I would like to be able to navigate through a history of previously run queries using up/down arrow keys or some other simple mechanism (similar to the Find text input box in, eg, Sublime Text)
+ Next level would be an autocomplete-style list of suggestions from the history based on what I have already typed in the input box that would update with each modification
+ Final two levels would be predictive suggestion (regardless of history) of what I want to type based on
    + Knowledge of correct XPath syntax
    + Knowledge of the actual structure and content of the specific JSON response I am querying against
+ Depending on time estimate, I am potentially interested in coding this feature myself and submitting a PR

**Comment by gschier** [comment]
Someone emailed me not too long ago also asking for a response filter history, so I think this should be implemented.

The currently active filter is stored in the `RequestMeta.responseFilter` property, so I propose adding an additional `responseFilterHistory` (or something similar) that stored the last `n` used filters. The app could then either make use of the already-existing autocomplete functionality or implement a standalone drop-down beside the filter to show past history items.

The hardest part about this feature is deciding when to store the filter in the history. On every keystroke would be overwhelming but after a timeout (eg. 2 seconds) might miss some. I'd be open to suggestions here.
