### ISSUE TITLE
Adding support for MQTT protocol (Asyncapi)

### ISSUE THREAD

**Issue by giosueDelgado** [getinsomnia/insomnia#2731]
**Is your feature request related to a problem? Please describe.**

It would be nice if the Insomnia tool supported MQTT messages and protocol
I have nowhere found a client that had an mqtt message editor that had both the ability to test them and to document them.

Is there anything planned in this regard? In the IoT sector, MQTT messages are widely used.

**UPDATE**

I found this: https://www.asyncapi.com/ from the discussion on Github of OpenAPI repo, I change my request to adding this support on Insomnia.

**Describe the solution you'd like**

I would like to be able to describe my MQTT posts on topics similar to GraphQL

**Describe alternatives you've considered**

This is an example of configuration and client MQTT: https://mqttfx.jensd.de/

**Additional context**

**UPDATE 16/10/2020 - https://www.asyncapi.com/**

**Comment by nijikokun** [comment]
This is something we have in the product roadmap backlog, much of our movement with gRPC can potentially be leveraged for both the networking layer and the interface.

**Comment by giosueDelgado** [comment]
Is there already an issue about it? If so, which one?

I mean you could take asyncAPI 2.0 protocol support see: https://www.asyncapi.com/docs/getting-started/coming-from-openapi
