### ISSUE TITLE
How to get dynamic token environment variable value?

### ISSUE THREAD

**Issue by syedsimanta03** [getinsomnia/insomnia#2744]
**What is your question?**
How to get dynamic token environment variable value? I mean postman has pm.environment.set("TOKEN", pm.response.json().token)  : means if any res.json() sends token, save that as a value of 'TOKEN' as env variable

**What is the context?**
If user one log in he gets a token, this token will be saved as an env variable. So that, I'll no longer have to keep copying my JWT back and forth from auth responses

I can also use this variable for other endpoint header as bearer token

**Comment by jgiovaresco** [comment]
Do you know the feature `Response -> Body Attribute` template tag? From my understanding, it should fit your needs.

You can define a specific variable (using CTRL + Space) which will be valued with the content of an existing response body.
I've tried to generate a GIF to explain. 

![response-body-attribute](https://user-images.githubusercontent.com/4171593/96467822-a10fe800-122b-11eb-8030-d27d01fe2f69.gif)

**Comment by nijikokun** [comment]
It appears this is answered by @jgiovaresco above so I will be closing, very well done especially with the gif 👏

**Comment by debugging** [comment]
What we really need is the ability to set an environmental variable during login, not having to set this on each and every request endpoint.

Each request should just reference that login_token variable, its much simpler and less of a hassle...thoughts?

**Comment by wret83853** [comment]
How do I get to response @jgiovaresco?

**Comment by nabekabebe** [comment]
> What we really need is the ability to set an environmental variable during login, not having to set this on each and every request endpoint.
> 
> Each request should just reference that login_token variable, its much simpler and less of a hassle...thoughts?

I think you can now use the same response variable presented above in the environment variable and just use the env key name anywhere you want.
#Environment 
{
   "token": "Bearer `**Response -> Body Attribute**`"
}

**Comment by congwenma** [comment]
> Do you know the feature `Response -> Body Attribute` template tag? From my understanding, it should fit your needs.
> 
> You can define a specific variable (using CTRL + Space) which will be valued with the content of an existing response body. I've tried to generate a GIF to explain.
> 


what if I want to do this for multiple values?

**Comment by clfsoft** [comment]
it will be a disaster if you want to set the token/id  to url , auth token of 10 or more requests.  
and then some day the token/id  response  interface changes.

**the postman way is far better and more programmer friendly**.

**Comment by clfsoft** [comment]
using the following plugin      
insomnia-plugin-save-variables

**Comment by webdevilopers** [comment]
> I think you can now use the same response variable presented above in the environment variable and just use the env key name anywhere you want. #Environment { "token": "Bearer `**Response -> Body Attribute**`" }

Indeed this was a great improvement. :partying_face: 

I wonder if there is a way to automate setting the "_token" variable on Auth for every request? 

![Screenshot from 2023-01-23 13-56-50](https://user-images.githubusercontent.com/3479626/214045389-703a13cb-e9ca-44d1-a1b0-4cfaa8237f36.png)

Maybe through DESIGN  for each "path"?

```javascript
      "get": {
        "operationId": "orderDetails",
        "summary": "Show order details",
        "tags": [
          "order"
        ],
        "auth": [
          "$token"
        ] // DEBUG internal
```

But I guess since it is a DEBUG concern it can or should not be mixed with the OpenAPI Docs.

**Comment by cholasimmons** [comment]
this is neater than the way PM does things 😎

**Comment by mehr-licht** [comment]
Hi.
I have tried. It worked, but...
I needed to export the collection+environment and the requests to get the variables from are recorded in this way : req_daac1bc86d1b4cf3b0ed4c84c8a6fa75. By their id hash.
So when I import it anywhere else, even though the request exists because it is imported at the same time, this reference does not exist because the same request has a different hash.

Is there a workaround for this?

**Comment by Misiu** [comment]
Ideally, we should be able to store responses as variables.

Use case:
I have 5 user accounts that I want to use for testing my API.
I would like to have 5 requests (login as user1, login as user2 etc) to be able to generate 5 access tokens and refresh tokens.
I'm able to create a tag in ENV, but this enforces using 5 environments, where I already have 3 env (dev, stage, prod).

something like post-request Script would be a nice feature.

**Comment by rafiqui1987** [comment]
This was my solution to get the token from Firebase, first I checked my response printed by the console responseBody then I was able to validate where my token came from, this is an example, it was not necessary to create the variable previously, to use it you must do it like this _.idToken

```
const responseBody = insomnio.response.json();
insomnio.environment.set("idToken", responseBody.idToken);
console.log('Token:', responseBody.idToken)
```

https://docs.insomnia.rest/insomnia/after-response-script
