### ISSUE TITLE
Unable to create tag for Cookie

### ISSUE THREAD

**Issue by svaldetero-envoc** [getinsomnia/insomnia#2750]
**Describe the bug**
I have cookies in the cookie jar. When I try to create a tag that "references a cookie value from the cookie jar", it tells me there are no cookies for that url.

**To Reproduce**
- Add a tag
- Select Cookie
- Type any url that matches something in the cookie jar

**Expected behavior**
I should be able to choose a cookie from that jar

**Screenshots**
![cookies](https://user-images.githubusercontent.com/54991761/96605499-e7148c80-12bb-11eb-9903-55ebc74db945.png)
![tag](https://user-images.githubusercontent.com/54991761/96605531-ee3b9a80-12bb-11eb-86a3-99e790774a50.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Installation Method: installer
 - App Version Core 2020.4.1

**Additional context**
I'm trying to get the XSRF token from aspnet core site. We call /me and it is returned as a cookie on the response. Then subsequent calls need to use that cookie.

**Comment by jgiovaresco** [comment]
@svaldetero 
I've built a simple test case on my side and I noticed that I should use `http://localhost` in `Cookie Url` (instead of `localhost`) to be able to find cookies.

**Comment by nijikokun** [comment]
Seems like we might need a better description, or error message detailing what format is expected.
