### ISSUE TITLE
[Feature] Ability to override response content-type

### ISSUE THREAD

**Issue by samdash** [getinsomnia/insomnia#276]
## Overview
- `Insomnia Version:` 5.1.1
- `Operating System:`  MacOS 10.12.6
- `Summary: ` NOT able to change the response content Type

**Comment by gschier** [comment]
Hi @samdash.

The response content-type is derived from the `Content-Type` header returned from the response. Are you saying that you have a JSON response comping back with `Content-Type` of `application/xml` instead of `application/json`?

**Comment by samdash** [comment]
Yes i am getting JSON response coming back with Content-Type of application/xml. But i would like to see options on the response as well just like postman does. to select whatever content-type i want to view as.

**Comment by gschier** [comment]
That sounds reasonable. Are you interested in submitting a PR for this?

**Comment by samdash** [comment]
Thank you , but given the workload i have, i will not be able to contribute at this time.

**Comment by gschier** [comment]
No worries @samdash. I think it's a great feature to add, but it's pretty low on the priority list. If someone else wants to take it up, that would be great!

Here's what I'm thinking...

- Add a wrench icon button beside the "Source Code" option in the response type dropdown
- If this button is clicked, pop up a prompt dialog to enter a content-type
  - Should autocomplete content-type with suggestions
- Add a `contentTypeHint` to the `RequestMeta` model to store the info

**Comment by samdash** [comment]
Thanks that sounds great but, isn't it too many clicks? I was thinking to have a dropdown [ or user entered value] option besides content-type value in Header's Tab , just like you have for the request header tab . If not what you have suggested should be fine.

**Comment by gschier** [comment]
I don't think it makes sense to attach it to the response. Conceptually, if you edit a response, you would assume that the value would reset when it is overwritten by the next response. I assume that, if you change the content-type, you would want it to persist for every subsequent response as well.

Moving it up a level (above the response) makes more conceptual sense from a UX perspective, in my opinion, even if it means an extra click or two.

**Comment by samdash** [comment]
Yes if you change content-Type i would want it to persist for every subsequent responses as well.
