### ISSUE TITLE
HTTPS support in Insomnia Designer in Design mode

### ISSUE THREAD

**Issue by skimwpi** [getinsomnia/insomnia#2760]
In the Design mode of Insomnia Designer, testing an API endpoint that requires https fails even if I uncheck the option to validate the cert (thereby choosing not to validate a cert). The current workaround is to use the Debug mode of Insomnia Designer but it would be great to see https work in Design mode too.

**To Reproduce**
1. Write an openapi spec to a server that requires https.
2. If using, self-signed cert, uncheck option to validate the cert
3. Test an endpoint requiring https. Insomnia Designer returns "TypeError: Failed to fetch".

**Expected behavior**
Should be able to fetch server reply in https.

**Desktop (please complete the following information):**
 - OS: mac 10.14.5
 - Insomnia Designer Version:  Insomnia Designer 2020.4.1

**Comment by nijikokun** [comment]
> fails even if I uncheck the option to validate the cert (thereby choosing not to validate a cert

Ah, was going to ask about this 😅
