### ISSUE TITLE
Add ability to see what environment is currently selected, and a way to change environment from Manage Environment modal

### ISSUE THREAD

**Issue by nijikokun** [getinsomnia/insomnia#2761]
**Is your feature request related to a problem? Please describe.**

Currently when managing environments and dealing with sub-environment variables from within the base environment, a user has to close the manage environment modal, to check / switch environments for variables to work.

Here, I have a sub-environment that I have just created (with no way to switch to it, or indicator telling me what is selected) and I am attempting to use the variables defined within my base environment - only to be provided with an error indicated it's not available and no indication as to _why_:

<img width="685" alt="Screen Shot 2020-10-21 at 12 02 00 PM" src="https://user-images.githubusercontent.com/198276/96770421-41cde700-1395-11eb-85a8-5822ba8b7c36.png">

Below we can see that my sub-environment does have the variables defined:

<img width="385" alt="Screen Shot 2020-10-21 at 12 01 25 PM" src="https://user-images.githubusercontent.com/198276/96770359-3084da80-1395-11eb-97e6-5583db6b9957.png">

To get my base environment to work properly, I must close this modal (breaking my flow) and switch to the sub-environment I just created.

<img width="257" alt="Screen Shot 2020-10-21 at 12 04 29 PM" src="https://user-images.githubusercontent.com/198276/96770755-996c5280-1395-11eb-9a43-98b87a616a31.png">

And now I can continue my flow again:

<img width="348" alt="Screen Shot 2020-10-21 at 12 05 01 PM" src="https://user-images.githubusercontent.com/198276/96770799-aa1cc880-1395-11eb-9c7e-e34ef981229c.png">

**Describe the solution you'd like**

Checkbox / radio selector next to sub-environment to indicate what environment is currently active and let me change it from within the manage environments modal

**Comment by ephelsa** [comment]
It looks very helpful.

I want to help with this. 😬

**Comment by nijikokun** [comment]
Looking forward to seeing what you come up with @ephelsa, feel free to ask any questions if you need help!
