### ISSUE TITLE
Support updating environment variables

### ISSUE THREAD

**Issue by Stef-33560** [getinsomnia/insomnia#2767]
**Is your feature request related to a problem? Please describe.**
Environment variables can't be modified during a test suite. Dynamically generated variables can't be updated from a response's body

**Describe the solution you'd like**
I would like, like in Postman, the ability to `pm.globals.set("myVariable", pm.response.json().theNewValueOfMyVariable);`

For example, for chaining a login request and reuse authorization header in the next requests :
1. Send POST  to `{{baseUrl}}/api/auth/login` : 
Its request's body : `{
    "login {{login}},
    "password": {{pwd}}
}`
Answers : `{
    "userId": "<<hashedUserId>>",
    "token": "<<myBearerToken>>"
}`
If HTTP200, set environment variables authToken to `response.body.token` and userId to `response.body.userid`

2. Send POST to `{{baseUrl}}/api/foo`
Header : set with authToken `Authorization: Bearer {{authToken}}`
Request body : a JSON with userId + data stuff
The request checks if Auth header is OK and if `req.body.userId == jwt.verify(req.headers.authorization.split(' ')[1], 'MY_ VERY_SECRET_TOKEN') `
Then it processes the data stuff

**Describe alternatives you've considered**
Dunno how to dynamically update use authToken without compromising it it the previous response body. Possible to reuse Authorization and response body from the previous request ?

**Additional context**
Any good practice about authorization are welcome :)

**Comment by Stef-33560** [comment]
Duplicate issue #1181

**Comment by cweiske** [comment]
I do not think that this is a duplicate.
#1181 is about manually overriding an environment  variable's content, while this here is about setting an environment variable from a test.
