### ISSUE TITLE
inso lint cannot run against local file

### ISSUE THREAD

**Issue by aaronhmiller** [getinsomnia/insomnia#2769]
**Describe the bug**
When linting a file, it is useful to ensure exactly what file is being checked.

**To Reproduce**
1. checkout a repo
2. run `inso lint spec ./spec.yaml`
3. see FATAL error

**Expected behavior**
Expect the file to be read, loaded and linted properly.

**Screenshots**
n/a cli operation

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.15.7]
 - Installation Method: npm for inso, .pkg downloaded from insomnia.rest for ID
 - App Versions: inso 2.2.25 and ID 2020.4.1

```
$> ls
README.md           uuid-generator.yaml
$/uuid-generator-service> inso --verbose lint spec ./uuid-generator.yaml
› Data store configured from app data directory at /Users/amiller/Library/Application Support/Insomnia Designer
› Load api specification with identifier ./uuid-generator.yaml from data store
› Found 0.

 FATAL  Specification not found.
```

**Comment by develohpanda** [comment]
Currently `inso generate config` supports loading from a file on the filesystem:

https://github.com/Kong/insomnia/blob/65a333cac317e7082e9a026e43588c404f026259/packages/insomnia-inso/src/commands/generate-config.js#L46-L60

`inso lint spec` does not support this yet, but adding in a different source is as simple as taking a snippet of the above code, loading the contents of the file, and consuming the contents in the lint-spec implementation:

https://github.com/Kong/insomnia/blob/65a333cac317e7082e9a026e43588c404f026259/packages/insomnia-inso/src/commands/lint-specification.js#L16-L24

the desired process (for `generate config` and `lint spec`) is to:
1. try load from db
2. then try load from file
3. then fail with a fatal error if neither can be found

**Comment by joemirizio** [comment]
Thanks for the info! I can take this one.

**Comment by develohpanda** [comment]
Thanks @joemirizio, awesome!
