### ISSUE TITLE
[Bug] HEAD request is hanging

### ISSUE THREAD

**Issue by reinert** [getinsomnia/insomnia#278]
## Overview
- `Insomnia Version:` 5.0.1
- `Operating System:`  Windows 7
- `Summary: ` HEAD requests do not finish

## How To Reproduce
Make any HEAD request. It will never finish.

## Other Notes
I tested with Postman and the request works.

**Comment by gschier** [comment]
Can you try updating to the latest version? I cannot seem to reproduce this 😕

**Comment by reinert** [comment]
The problem is gone.

**Comment by gschier** [comment]
Thanks for letting me know @reinert 😄 👍 🌮

**Comment by reinert** [comment]
Congrats for the amazing app. It feels wonderful.
