### ISSUE TITLE
Resizing pane visibility in vertical layout in Designer

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2787]
**Describe the bug**
When in Designer on the debug tab (currently the only tab that caters for vertical layout), the horizontal pane is not visible (see screenshot)

**Expected behavior**
The vertical pane should be visible in both Core and Designer (in the debug tab at-least).

**Screenshots**
![image](https://user-images.githubusercontent.com/4312346/97262420-aa313280-1885-11eb-813a-b4e093126ed8.png)

**Desktop (please complete the following information):**
```
Version: Insomnia Designer 2020.4.1-beta.1
Release date: 16/09/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Additional context**
This _might_ be fixed by #2713

**Comment by ARKEOLOGIST** [comment]
Hi, I myself would like to have a look at this. A little bit of guidance is welcome!
