### ISSUE TITLE
[Feature Request] Query parameter schema(constraint, input choices/range, help text etc.)

### ISSUE THREAD

**Issue by wonderbeyond** [getinsomnia/insomnia#280]
Just for ease, and gives good instructions for setting parameters.

![image](https://user-images.githubusercontent.com/228361/33595311-8765a21c-d9d2-11e7-9490-a706fcef3229.png)

**Comment by wonderbeyond** [comment]
@gschier How about a review for this feature request?

**Comment by gschier** [comment]
Sorry, I completely missed this one. 

I think adding description fields to parameters is a desirable feature (both Postman and Paw have it). Defining and enforcing constraints seems like a much larger task and should probably be treated as a separate feature request.

A few random thoughts:

- Additional description fields should not clutter Insomnia's minimal UI. Perhaps they could be toggled on/off? Perhaps documentation in general should be hidden behind a toggle in workspace settings?
- Description fields should not just be added to query parameters, but to headers and multipart/urlencoded form data as well. Luckily, the key-value editor is a shared components so most changes will happen in [one place](https://github.com/getinsomnia/insomnia/blob/3ad8f7ecae26a448e96c94c9bd2e1d381110a02b/packages/insomnia-app/app/ui/components/key-value-editor/row.js)
- Postman data importers need to be updated to handle descriptions

Are you interesting in working on this @wonderbeyond?
