### ISSUE TITLE
Losing requests from source when duplicating Document

### ISSUE THREAD

**Issue by feganmeister** [getinsomnia/insomnia#2800]
**Describe the bug**
When duplicating a Document in Designer, the requests in the target (new) Document are duplicated (as reported on #2080) but the source (existing) Document looses the requests. On the source Document, you need to navigate to Design, then back to Debug to get them back. However, this causes the Environment to reset (as reported on #2228).

**To Reproduce**
Reproduction steps have been confirmed on OpenAPI 2.0 and OpenAPI 3.0.
1. Create a Document (e.g. based on the PetStore example)
2. Change the Environment (see Image 1)
3. Click on Debug and observe the available requests (see Image 2) 
4. Navigate back to Documents and duplicate the Document created in step 1
5. Navigate to the new Document created in step 4 then click Debug. Observe the duplicated requests (see Image 3)
6. Navigate back to the source Document (created in step 1) and observe the reset Environment (see Image 4) and the missing requests (see Image 5)

**Expected behavior**
Duplicating a Document leaves the source in tact (including the Environment). The new Document does not contain two sets of requests.

**Screenshots**

_Image 1_
![image](https://user-images.githubusercontent.com/20923027/97715991-f44f2980-1aba-11eb-868f-cac05f18c5e3.png)

_Image 2_
![image](https://user-images.githubusercontent.com/20923027/97715805-b8b45f80-1aba-11eb-968c-685df1694bf8.png)

_Image 3_
![image](https://user-images.githubusercontent.com/20923027/97716206-409a6980-1abb-11eb-96e4-80a4c9767d97.png)

_Image 4_
![image](https://user-images.githubusercontent.com/20923027/97716291-56a82a00-1abb-11eb-8f68-b42f23f8085b.png)

_Image 5_

![image](https://user-images.githubusercontent.com/20923027/97726774-82c9a800-1ac7-11eb-899a-fa2bdaf784df.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 v2004 Build 19041.572
 - Installation Method: Designer installer downloaded from [website](https://insomnia.rest/download/)
 - App Version 2020.4.2
![image](https://user-images.githubusercontent.com/20923027/97716493-94a54e00-1abb-11eb-9251-135964f68ed5.png)

**Additional context**
No other context to add.

**Comment by kreosus** [comment]
Hi @feganmeister 

Can you try our newest release located here: https://github.com/Kong/insomnia/releases and hopefully it addresses your issue.

**Comment by kreosus** [comment]
closing due to lack of inactivity
