### ISSUE TITLE
White screen after Get

### ISSUE THREAD

**Issue by Sited** [getinsomnia/insomnia#2801]
On my first use ever of the app, and subsequent attempts, when I try to Get a Basic Auth the app goes 'white screen' and never recovers. I've tried numerous times.

I'm connecting to a Wordpress site using the Woocommerce rest api, keys read/write...

**Comment by jgiovaresco** [comment]
👋  @Sited 

If I understand correctly, you are requesting a GET endpoint using the Basic Authentication?

I suggest trying to `Copy as curl` the request (by right-clicking on the request element) and paste the result in a terminal to see if the request succeeds.
By the way, you can look at the `Timeline` tab (on the right pane) to have more information on what is going on when you send the request. Maybe you will find something there 🤔

**Comment by wongstein** [comment]
Piping in here to recommend trying to reproduce this issue with the latest Insomnia 2022.5.1.  A lot has changed!
