### ISSUE TITLE
UI crash

### ISSUE THREAD

**Issue by 3DRaven** [getinsomnia/insomnia#2805]
**Describe the bug**
Sometime I have crash in UI. See attachment screenshot.
**To Reproduce**
Sometime
**Expected behavior**
Version: Insomnia Core 2020.4.0
Release date: 10.09.2020
OS: Linux x64 5.8.0-9.3-liquorix-amd64
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libssh2/1.9.0 nghttp2/1.41.0
**Screenshots**
![Снимок экрана от 2020-11-02 11-22-17](https://user-images.githubusercontent.com/3204467/97858002-cc500800-1cfe-11eb-8b24-68921a54f230.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Installation Method: snap
 - App Version 2020.4.0

**Comment by develohpanda** [comment]
Hi @3DRaven!

Thanks for reporting. Can I ask what you were doing at that point in time, or if you've been able to reproduce it reliably? Seems like there's only one place that uses `lastIndexOf` so this should be simple enough to fix.

https://github.com/Kong/insomnia/blob/a9e22075fb1ece88bb0ce38214d7cf4bf31a16de/packages/insomnia-app/app/ui/components/codemirror/code-editor.js#L316

**Comment by 3DRaven** [comment]
I don't know precisely, but I think at this time I tryed to start request from keyboard shortcut ctrl+enter.

**Comment by MrSnix** [comment]
**EDIT**: 
I moved my proposal for fix here [ PR #2048 ](https://github.com/Kong/insomnia/pull/2840)
