### ISSUE TITLE
Node 15 support

### ISSUE THREAD

**Issue by WhyNotHugo** [getinsomnia/insomnia#2812]
**What is your question?**

I [and many other users] are having issues building / installing Insomnia since it's not compatible with node 15. While installing a secondary node version _can_ be done (e.g.: `nvm`), this kind of tool is usually used for development, not for OS packages.

Also due to this, the [ArchLinux package](https://aur.archlinux.org/packages/insomnia/#comment-774153) for insomnia has been broken for a while with no-one being able to build / install it.

I checked and didn't see any issue around this, so I'm not sure if it's being addressed or not.

**Comment by filfreire** [comment]
Hi @WhyNotHugo, thank you for reporting this, and sorry for only replying now!

I'm closing this ticket as we are supporting Node 16.14.2 in latest development. Feel free to report other issues you come across.
