### ISSUE TITLE
Strange white thing in top left of screen

### ISSUE THREAD

**Issue by bushblade** [getinsomnia/insomnia#2818]
Hi I just upgraded to version 20204.2
And see this weirdness in the app now...
![Screenshot_2020-11-06_19-57-23](https://user-images.githubusercontent.com/21976188/98409393-ab731400-206a-11eb-9d8d-244242513f03.png)

I have seen similar issues in the desktop slack app recently and in Chromium browser, so I'm assuming it's an issue with the version of Electron in use?

Version: Insomnia Core 2020.4.2
Release date: 06/11/2020
OS: Linux x64 5.8.16-2-MANJARO
Electron: 10.1.5
Node: 12.16.3
V8: 8.5.210.26-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1h zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0

**Comment by bushblade** [comment]
Its still an issue after today's update too...
![Screenshot_2020-11-09_17-05-27](https://user-images.githubusercontent.com/21976188/98572706-d4cfb200-22ad-11eb-963f-d2f4f67b9c08.png)

Version: Insomnia Core 2020.4.2
Release date: 09/11/2020
OS: Linux x64 5.8.18-1-MANJARO
Electron: 10.1.5
Node: 12.16.3
V8: 8.5.210.26-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1h zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0

**Comment by ulisesqg** [comment]
```CTRL + ALT + I``` opens the console

Excecute: ```window.location.href="chrome://flags/#enable-vulkan"```

I have an AMD graphic card and this stop the glitches for me.

**Comment by bushblade** [comment]
Thanks for the reply.
That crashes the app for me.
I too have an AMD card though, radeon RX580

**Comment by ulisesqg** [comment]
RX590 here. It crashed for me too. I reopened the app and glitches were gone.

**Comment by bushblade** [comment]
Still have the issue after reopening here.

**Comment by ARKEOLOGIST** [comment]
I think this might be an issue with Electron itself, rather than with Insomnia.

**Comment by filfreire** [comment]
Closing as stale. We have updated through a handful of Electron versions since the issue was reported. Please report a new issue if you still face similar problem.
