### ISSUE TITLE
[Bug] Very large requisitions lock and unuse the application

### ISSUE THREAD

**Issue by andreworks** [getinsomnia/insomnia#282]
Hello,

Requests that are more than 10 mb will stop the application and virtually disable it. I have a service that returns a large volume of data, and since I made the first call, the application hangs and keeps asking me to reboot, now I can not use it anymore. I've already removed and reinstalled the software, but it did not work. I imagine that as soon as it opens the application, it redoes the last request. I'm in the last version.

![fo2](https://cloud.githubusercontent.com/assets/4095186/26730625/f42802c4-4787-11e7-9036-da337afa0fd6.PNG)

Could you take a look?

I really like the software, I would not want to stop using it.

**Comment by gschier** [comment]
Hi @andreworks,

For a temporary fix to this, you can delete `Insomnia/insomnia.Response.db` from the following location.

- `%APPDATA%` on Windows
- `$XDG_CONFIG_HOME` or `~/.config` on Linux
- `~/Library/Application Support` on macOS

This will clear out all response data for the app. I plan on adding improvements for large file handling soon to help prevent this issue in the future.

**Comment by andreworks** [comment]
Hello @gschier ,

Thank you very much! I deleted the file and it worked again.
Cool, I'll be waiting. Congratulations on the work, great app!
