### ISSUE TITLE
Insomnia for snap not starting on Fedora 33

### ISSUE THREAD

**Issue by Flo-Schilli** [getinsomnia/insomnia#2823]
**Describe the bug**
After upgrading to Fedora 33 Insomnia is not starting when installed via snap

**To Reproduce**
1. Go to the terminal
2. Run the following command: `snap run insomnia`
3. Error will be shown in terminal

**Expected behavior**
Insomnia is starting

**Desktop (please complete the following information):**
 - OS: Fedora 33 with kernel 5.8.16-300
 - Installation Method: snap
 - App Version: 2020.4.2

**Additional context**
Error message shown in terminal:
`WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
11:05:56.496 › Running version 2020.4.2
Error org.freedesktop.DBus.Error.Failed: cannot find snap for connection: not supported
Segfault (dump written)
`

dmesg output is:
`insomnia[13218]: segfault at 208 ip 000055bafebdbec3 sp 00007ffd3f640f30 error 4 in insomnia[55baf9040000+5cb5000]`

snap info insomnia output is:
`name: insomnia`
`summary: Insomnia REST Client`
`publisher: Insomnia (gschier1990)`
`store-url: https://snapcraft.io/insomnia`
`contact: https://support.insomnia.rest`
`license: unset`
`description: |
A powerful HTTP and GraphQL Client with cookie management, environment variables, code generation,
and authentication for Mac, Window, and Linux.`
`commands:`
`insomnia`
`snap-id: ZtF4mLp5Bededu3S65ocO6HfGXCtcvZ9`
`tracking: latest/stable`
`refresh-date: today at 10:26 CET`
`channels:`
`latest/stable: 2020.4.2 2020-10-26 (109) 97MB -`
`latest/candidate: ↑ `
`latest/beta: ↑ `
`latest/edge: 2020.4.2 2020-10-26 (109) 97MB -`
`installed: 2020.4.2 (109) 97MB -`

**Comment by carlos3g** [comment]
same here

**Comment by wongstein** [comment]
Is this issue still reproducible in the latest Insomnia 2022.6.0?
