### ISSUE TITLE
Broken rounded corners in Big Sur 

### ISSUE THREAD

**Issue by jvzaniolo** [getinsomnia/insomnia#2835]
**Describe the bug**
Broken rounded corners in Big Sur

**To Reproduce**
1. Run `brew install --cask insomnia`

**Expected behavior**
Rounded corners following Big Sur's UI pattern.

**Screenshots**
![image](https://user-images.githubusercontent.com/54036572/99154888-0243a380-2692-11eb-8f94-ec7731110374.png)

**Desktop:**
 - OS: Big Sur 11.0.1 (20B29)
 - Installation Method: Homebrew
 - App Version v2020.4.2

**Comment by koldoon-qs** [comment]
+1, And it seems that overall window behavior is slow, even such operations like minimizing and maximizing (seems like a sort of overall rendering mode issue). In comparison, other electron-based applications work just fine.

**Comment by jamescodesthings** [comment]
+1 I originally got a blank window for ages, thought compatibility was off and went after postman.

Now works but definitely not quick to load.

**Comment by MrSnix** [comment]
+1 Slowed down since i upgraded to Big Sur, i could see the difference

**Comment by adanpineda** [comment]
Any updates on this issue?
