### ISSUE TITLE
Push rejected with errors

### ISSUE THREAD

**Issue by rastislavcore** [getinsomnia/insomnia#2838]
**Describe the bug**
Cannot push changes to Gitlab instance.

**To Reproduce**
1. Design your API calls in the environment.
2. Setup "Repository Settings"
3. Git URI: `https://myinstance.com/org/repo.git`; Author; Author email; Username; Authentification token
4. Commit changes
5. Push
6. Push rejected; Question: `Do you want to force push?`; Answer: `Force push`
7. `Error: Push rejected`

**Expected behavior**
Should push all changes to the Gitlab instance repository.

**Screenshots**
![Screenshot 2020-11-15 at 9 25 20 PM](https://user-images.githubusercontent.com/537310/99195910-11f1e380-2789-11eb-99f7-baeccf0c77b0.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Installation Method: download Insomnia designer
 - App Version 2020.4.2

```
Version: Insomnia Designer 2020.4.2
Release date: 21/10/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Additional context**
Stack trace:

```
Error: Push rejected with errors: ["refs/heads/master pre-receive hook declined"].

Go to View > Toggle DevTools > Console for more information.
    at GitVCS.push (file:///Applications/Insomnia%20Designer.app/Contents/Resources/app.asar/bundle.js:33444:13)
    at async GitSyncDropdown._handlePush (file:///Applications/Insomnia%20Designer.app/Contents/Resources/app.asar/bundle.js:193916:7)
```

Dev Tools:

```
Uncaught (in promise) TypeError: Cannot read property 'hasGutter' of undefined
    at clearMarks (bundle.js:204507)
    at updateLinting (bundle.js:204593)
    at bundle.js:204586
    at runInOp (bundle.js:12312)
    at CodeMirror.operation (bundle.js:16987)
    at bundle.js:204586
20:58:22.329 › [ga] Event Activity, Change, spec
20:58:22.330 › [ga] Page /spec
20:58:22.339 › Unhandled Promise PromiseRejectionEvent
```

**Comment by develohpanda** [comment]
Hi @raisty, in the console window do you see anything prefixed with `[git]` or `[git-event]`? The error you've shared is unrelated to git (albeit it is still an error).

Here's an example:
![image](https://user-images.githubusercontent.com/4312346/99314556-2daed400-28c6-11eb-9121-e74c830a3f0e.png)

[This PR](https://github.com/Kong/insomnia/pull/2432) contains a gif showing this very error. It's quite likely that the account + token you are using doesn't have the correct permissions.

If you don't see an error as per the screenshot above, please send through your [app logs](https://github.com/Kong/insomnia/pull/2432) after you reproduce this issue to support@insomnia.rest and we can help you out.

**Comment by rastislavcore** [comment]
I found the part related to the mentioned part.
And found out you tested it on the GitHub provider, but in my case is the GitLab instance.
Which rights in the GitLab token should be assigned, please?

![Screenshot 2020-11-17 at 8 56 23 PM](https://user-images.githubusercontent.com/537310/99440783-5b703900-2917-11eb-9875-963d9f18289f.png)

**Comment by develohpanda** [comment]
The `git-event` message says you're not allowed to force push to a protected branch.

I believe Gitlab marks the main/master branch as protected by default, and if your user role doesn't have permissions to force push, this will fail. If you _are_ able to push to another branch, then you've selected the correct scopes for the token.

Also, which version of Gitlab are you using?

**Comment by rastislavcore** [comment]
GitLab 13.5.3

I will test your suggestion, thank you.

**Comment by rastislavcore** [comment]
Seems like unprotect branch enables the Force push for me.
Thank you for your help.

Please, @develohpanda 🐼 update the documentation about GitLab's requirements.

**Comment by develohpanda** [comment]
No worries! I have updated the documentation for pushing changes: https://support.insomnia.rest/article/96-git-sync#Pushing_Changes.
