### ISSUE TITLE
[Feature Request] Table View for JSON response

### ISSUE THREAD

**Issue by wonderbeyond** [getinsomnia/insomnia#284]
![image](https://cloud.githubusercontent.com/assets/228361/26822841/07255594-4ade-11e7-9ab6-1a062b76c41a.png)

**Comment by gschier** [comment]
Hi @wonderbeyond. Can you provide some more information on this request? More details on "what" this is and "why" it would be useful would be awesome 😄

**Comment by wonderbeyond** [comment]
@gschier 

## What is "Table View for JSON response"

Take the following data as example:

```json
[
    {
        "_key": "100",
        "title": "Case#100"
    },
    {
        "_key": "101",
        "title": "Case#101"
    }
]
```

We can display it like this:

| _key           | title     |
| :------------- | :------------- |
| 100            | Case#100       |
| 101            | Case#101       |

## Why it would be useful

- More readable
- Leverage the horizontal space to display items more compactly

![image](https://user-images.githubusercontent.com/228361/26859474-88173258-4b6a-11e7-9789-fac975df6047.png)

**Comment by spookyUnknownUser** [comment]
Yes! Something like [JSON Data Ninja](http://www.jsondata.ninja/) built in would be incredible...

**Comment by gschier** [comment]
Since a table view would only work with a very specific data format, I hesitate to include it as a general feature. However, I _would_ be open to adding something like this instead: https://github.com/alexkuz/react-json-tree

**Comment by spookyUnknownUser** [comment]
@gschier I think that would work just as well! 👍

**Comment by ray-qu** [comment]
The above comment is sort of tech savvy. I was requesting in another thread #529 to go for something like the Altova XML Spy provides. This way it's more user friendly (at least you don't have to keep expanding / collapsing the object hierarchy. It'd be really nice if this is available for both request (for editing or previewing raw JSON body section) and response panes.

Reference URL: http://manual.altova.com/xmlspy/spyenterprise/xseditingviews_gridview_tables.htm
or, http://valentin.dasdeck.com/lingo/dml/screenshots/xmlspy_grid_view.png

**Comment by wonderbeyond** [comment]
@ray-qu @gschier
https://github.com/getinsomnia/insomnia/issues/534 may cover this feature. We can add custom templates for rendering json/xml into table view.

**Comment by gschier** [comment]
Ya. I think the problem is best solved by extending the plugin system to allow for custom content type viewers, which would allow both solutions. I mentioned this over here as well https://github.com/getinsomnia/insomnia/issues/529#issuecomment-339036179
