### ISSUE TITLE
URLs with a `$` are not properly handled

### ISSUE THREAD

**Issue by Nabellaleen** [getinsomnia/insomnia#2850]
**Describe the bug**
The RFC3986 (https://tools.ietf.org/html/rfc3986) about URI list the `$` sign as an allowed subdelimiter, which allows you to expose services on URLs like : `https://www.myservice.com/$graphql`

With the current version of Insomnia, this URI is not well handed, as the `$` is converted into `%24` before the request is sent

**To Reproduce**
I've reproduced the error, in particular with a GraphQL request.

**Expected behavior**
Right now, with Insomnia, the server answer me :
```
{
  "resourceType": "OperationOutcome",
  "text": {
    "div": "POST /%24graphql not found"
  },
  "issue": [
    {
      "severity": "error",
      "code": "not-found",
      "details": {
        "text": "POST /%24graphql not found"
      }
    }
  ]
}
```
Using Postman, everything works well
**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Installation Method: Appimage
 - App Version: 7.1.1

**Comment by night-fury-web** [comment]
Will it be merged soon?

**Comment by night-fury-web** [comment]
Is it fixed?

**Comment by dimitropoulos** [comment]
sorry bout that @sandguardian, we were having some trouble with our bot marking things as `wontfix`.  (we've since disabled the bot altogether).  watch the PR for any happenings on this front.
