### ISSUE TITLE
[Feature] Make it possible to resend request in a method chaining

### ISSUE THREAD

**Issue by gilmishal** [getinsomnia/insomnia#286]
Currently, chaining request values aren't updated unless the chained request is sent again manually. Which is fine, but it could be very useful if you could define cases to expire the existing value, forcing it to be reevaluated.

Assuming, I have a token value that is chained to a login request.
Every time I want to change the credentials/ token expired - I need to manually send the request.

In this example  - I should be able to set that every 401 response for a request that uses the token parameter, or every change to the username or password parameters should expire the token, and force a reevaluation on the next request.

**Comment by AlainPilon** [comment]
Wouldnt just being able to run a JS snippet in a before/after hook on each request solve this (and add even more flexibility)?

**Comment by AlainPilon** [comment]
Am I the only one who think this is a good idea?

**Comment by gschier** [comment]
Going to reopen this. I do think it's a valuable feature to have. Just lost track of it in the sea of issues.

**Comment by huygn** [comment]
Would love to see this, initially I though [chaining request](https://support.insomnia.rest/article/43-chaining-requests) would automatically do but then I realized I had to run the first request again.

**Comment by tadgh** [comment]
Agreed. With a lot of context switching between servers, it would help greatly to have the chained request rerun upon every request. Or at least a toggle allowing this to happen

**Comment by gschier** [comment]
Yep, this should definitely stay open

**Comment by gschier** [comment]
How do you think this would be best configured? Here are the options:

- Add boolean toggle on the tag itself
- Add new tag (with possibly more chaining-specific options)
- Prompt user when sending the request
- Have another option when sending ("Send with dependencies")
- Request-level setting
- Workspace-level setting
- Global setting

**Comment by gschier** [comment]
Also, I totally agree no the docs confusion. It's called chaining now because I wasn't sure what else to call it and planed to add automatic dependency sending sooner.

**Comment by Maxwell2022** [comment]
I would either add a boolean or a cache expiration in ms that could be 0 for no cache. I think changing context should automatically break this cache, or store it under the context itself so you don't have to worry about it.

**Comment by rgarrigue** [comment]
Hi

I'm also interested. And after a quick read, @Maxwell2022 proposal of a cache expiration seems good. Maybe with a prompt for the first usage, just in case triggering a request who trigger another one etc might end up taking too much resource.

**Comment by Tarig0** [comment]
Could we separate the dependency from the value retrieval? I have a case where I need to send a request before another to have the server change its state. Right now there is no way to "link" these two requests except for a dummy header.

**Comment by charlex** [comment]
Not to be just a +1, but this would be very helpful. Is there a status update on this?

**Comment by PTST** [comment]
> How do you think this would be best configured? Here are the options:
> 
> * Add boolean toggle on the tag itself
> * Add new tag (with possibly more chaining-specific options)
> * Prompt user when sending the request
> * Have another option when sending ("Send with dependencies")
> * Request-level setting
> * Workspace-level setting
> * Global setting
> 
> _EDIT: GitHub really needs a voting mechanism_

An option for automatically resending the request when the request referencing the original response returns a 401, and also when changing environment would be nice.

**Comment by gschier** [comment]
🎁

**Comment by gschier** [comment]
I didn't implement the 401 logic but this can now be done by forking the response plugin and making some slight tweaks for a new plugin with whatever behavior you want/need.

for example, to check the status code of the current request from within the response tag plugin:

```js
async run(context, attribute, name, folderIndex) {
  const { meta, util } = context;

  if (!meta.requestId || !meta.workspaceId) {
    return null;
  }

  const response = await util.models.response.getLatestForRequestId(meta.requestId);

  if (!response) {
    return null;
  }

  const shouldResend = response.statusCode === 401;
  
  // Carry on...
}
```
