### ISSUE TITLE
[Bug] Interface is slow on MacOS Big Sur

### ISSUE THREAD

**Issue by koldoon** [getinsomnia/insomnia#2860]
After update to the last Mac OS Big Sur interface became slow, application startup is slow and resizing (and even minimizing the window!) is freezing.

**Comment by reynolek** [comment]
Hi @koldoon!

Can you provide us more information for us to reproduce? Useful pieces of info would be:

1. Are you running Insomnia or Insomnia Designer? What Version?
2. Are you seeing this slow down with any other Electron applications (such as VS Code, Atom, etc)?

**Comment by koldoon** [comment]
I run Insomnia Core 2020.4.2
Release date: 21/10/2020
OS: Darwin x64 20.1.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0

I don't see such a slowdown in any other electron-based application, such as Skype, Microsoft Teams, Slack, Spotify, VS Code - everything just fine.

I tried to delete and reinstall Insomnia with no luck.
I even tried to BUILD Insomnia from sources by myself - the result is the same.

I think this issue is tightly connected to this one: https://github.com/Kong/insomnia/issues/2835.
Something is seriously broken under Big Sur.

**Comment by koldoon** [comment]
Any updates on this?

**Comment by haku-d** [comment]
I was experiencing same issue.

**Comment by reynolek** [comment]
Upgrading electron to `9.3.5` (the above linked PR) we believe will fix the Big Sur issues -- We expect a release very soon that basically just does this bump.
