### ISSUE TITLE
[Performance] Steadily increasing memory usage

### ISSUE THREAD

**Issue by tthayer** [getinsomnia/insomnia#287]
## Overview
- `Insomnia Version:` 5.1.1
- `Operating System:`  Windows 7
- `Summary: ` Insomnia gradually uses more and more RAM regardless of if I'm using it actively or not. I have left it open for several days and have seen it using ~4GB. Watching Task Manager, it appears that Insomnia will consume an additional 1MB every minute or two. Restarting the application frees up memory. I've seen this happen with another Electron app (Slack) too, though it appears they got a handle on it and it doesn't exhibit the same behavior anymore.

## How To Reproduce
_Please list all pertinent information and steps needed to reproduce the issue. For example:_
1. Open Insomnia
2. Observe memory usage. Wait a while. Observe markedly higher memory usage.

## Other Notes

In the time it took me to write this up it consumed +~12MB. Could this be related to logging?

**Comment by gschier** [comment]
Sorry for the delay on this one. I haven't had a big enough time block to dig into this, but I _do_ want to get to it soon. The DB that insomnia uses is in-memory, so large requests and responses will quickly inflate the amount of RAM needed. My initial solution for this will be to pull large blobs (request and response bodies) out of the DB and store them directly on the file system. 

As for leaks, I'm not seeing any on my end when the app is idle. I observe memory increasing for around 30 seconds, but eventually returning back down (probably after garbage collection).

**Comment by tthayer** [comment]
I'll keep an eye on it and see if it continues.

**Comment by gschier** [comment]
Going to close this one for now as I suspect #338 will clear up most memory-related issues.
