### ISSUE TITLE
Support SSO login (e.g. SAML, with Okta)

### ISSUE THREAD

**Issue by guidotrueb** [getinsomnia/insomnia#2877]
**Describe the solution you'd like**

One key feature for teams would be to support SSO login in your paid subscription.

**Describe alternatives you've considered**

A reasonable alternative would be to support login with Google/GitHub/GitLab accounts.

**Additional context**

I believe many companies would consider migrating from Postman if this was available on your platform.

_Thanks and keep the great work!_

**Comment by nijikokun** [comment]
It's on the roadmap! 🎉

**Comment by ericbach** [comment]
@nijikokun Do you have an ETA on this feature? Would you expect something in the next Q1/2 or further down the road?

**Comment by csotiriou** [comment]
This would be a major and very useful feature.

**Comment by iuvalk** [comment]
Any ETA for the SSO feature?

**Comment by manali-bhosale** [comment]
Any links we can follow for the SSO feature updates?

**Comment by filfreire** [comment]
Hi @guidotrueb, I'm closing this as duplicate of #1999
SSO feature is at the moment being worked on by the team, with initial support of GitHub.
Soon other platforms will be added.
