### ISSUE TITLE
provide a version of insomnia for armhf architecture

### ISSUE THREAD

**Issue by tarcisiodelmondes** [getinsomnia/insomnia#2878]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I wish there was a version of insomnia for the raspberry pi.

**Describe alternatives you've considered**
I looked for insomnia-like program solutions for raspberry pi, but I couldn't find.

**Additional context**
I needed to test my api so I looked for programs to help me, so I tried to install the insomnia and
I got the message

_**"error: snap "insomnia" is not available in stable for this architecture (armhf)
       but it exists in other architectures (amd64). "**_

Then I saw that it was not compatible. I think it would be interesting to have a version for this architecture, as it could help many people like me..

**Comment by kreosus** [comment]
reproduced with Raspberry Pi 4 running Ubuntu 20.10:
```
kreos@pitest:~$ sudo snap install insomnia
error: snap "insomnia" is not available on stable for this architecture (arm64) but exists on other
       architectures (amd64).
```
