### ISSUE TITLE
Verifying checksum for Cask insomnia failed

### ISSUE THREAD

**Issue by dumindu** [getinsomnia/insomnia#288]
## Overview
- `Insomnia Version:` brew cask install insomnia
- `Operating System:`  e.g. MacOS 10.12.5 (16F73
- `Summary: ` Verifying checksum for Cask insomnia failed

## How To Reproduce
_Please list all pertinent information and steps needed to reproduce the issue. For example:_
1. brew cask install insomnia

## Other Notes

Error: sha256 mismatch

**Comment by gschier** [comment]
It looks like whoever created the Caskroom package is [using the `/latest` endpoint](https://github.com/caskroom/homebrew-cask/blob/master/Casks/insomnia.rb). This means that the checksum becomes invalid as soon as a new release is out. It's probably worth submitting this bug report to the Caskroom repo instead: https://github.com/caskroom/homebrew-cask

The full URL should be `https://github.com/getinsomnia/insomnia/releases/download/v**<VERSION>**/Insomnia-**<VERSION>**.dmg`

**Comment by gschier** [comment]
It looks like Caskroom has now updated to 5.2.0. Closing this one for now.
