### ISSUE TITLE
Better handling of redirects

### ISSUE THREAD

**Issue by waynegemmell** [getinsomnia/insomnia#2880]
When you POST to url and receive a 301/2 redirect it then hits that URL with a GET. Reading up a little bit on that indicates that it's that sort of bad behaviour that inspired the 307 redirect, but nobody implements a 307. 
I'd like to have Insomnia handle this a little better. Either with a warning of the change from a GET to a POST or just to maintain the same method across the redirect. This had me scratching my head for about an hour the other day and was totally unexpected.

**Comment by kreosus** [comment]
Hi @waynegemmell, thank you for this information. Have you tried our latest release located here: https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.3, to see if it resolves your issue? Thank you

**Comment by waynegemmell** [comment]
It's been almost a year and I don't even remember how to test this. My bad for not adding a test case to the issue. Thanks for sorting it out though. I'll just take your word for it and close this.
