### ISSUE TITLE
Blank Screen on General Preferences window

### ISSUE THREAD

**Issue by alannaidon** [getinsomnia/insomnia#2881]
**Describe the bug**
A blank screen appears when trying to access General preferences window.  

**To Reproduce**
1. Open Insomnia
2. Click on 'Application > Prefrences' OR `Help > Keyboard Shortcuts > General`
3. Behold the blank screen

**Expected behavior**
A window where I can customize `Font Style and Size`

**Screenshots**
![image](https://user-images.githubusercontent.com/13774879/100620732-825a4200-32fd-11eb-962a-e37f6483ff36.png)

**Desktop (please complete the following information):**
 - OS: Fedora 33 Workstation Edition
 - Installation Method: Via snap
 - App Version: 2020.4.2

**Additional context**
You guys noticed that it's really only the `General` window settings... Because I can access any other configuration window from `Help` menu.  

Also, the `ABOUT` window is like this:  

![image](https://user-images.githubusercontent.com/13774879/100620896-b9c8ee80-32fd-11eb-84dc-04340ec7bd3a.png)

I'm also unable to install `any` plugin.  
Tried to install [default headers](https://insomnia.rest/plugins/insomnia-plugin-default-headers), but I always get errors.  

![image](https://user-images.githubusercontent.com/13774879/100621123-08768880-32fe-11eb-9a67-8487ff6e1eb5.png)

**Comment by apisaint** [comment]
Looks like you've ran into an issue with snap/linux installation, and is doesn't seem to be related to Insomnia but the system font cache, at least according to previous reports. There seems to be a viable fix here https://github.com/Kong/insomnia/issues/2614#issuecomment-700711061
