### ISSUE TITLE
Unable to use environment variables in request body (GraphQL)

### ISSUE THREAD

**Issue by MoshePaul** [getinsomnia/insomnia#2886]
Is there a way to use variables for your environment inside the body of a GraphQL query? For example:

`query {
assignRole(roleId: my_role,
account: my_account) {
  data { id}  
  }
}`

**Comment by koldoon** [comment]
You must use `query variables`. It is a little bit overcomplicated but works well:

```
query ($itemId: String!) {
  item(itemId: $itemId) {
    name
  }
}
```

Query Variables:
```
{
  "itemId": "{{ _.itemId }}"
}
```

**Comment by jostFT** [comment]
This won't work if you are working with numeric values. Please refer to the open issue:
#1937 
This issue has existed for a long time, and has yet to be addressed by the devs - so who knows when this will be fixed
