### ISSUE TITLE
[Bug] JSON response formation breaks on encoded sequence of characters

### ISSUE THREAD

**Issue by narqo** [getinsomnia/insomnia#289]
## Overview
- `Insomnia Version:` 5.2.0
- `Operating System:` macOS 10.12.5
- `Summary: ` if *valid* JSON response contains special sequence of characters, e.g. `\\`, Insomnia's JSON formatter failed to pretty-print the response.

## How To Reproduce
_Please list all pertinent information and steps needed to reproduce the issue. For example:_
1. Perform a request which returns a valid JSON with JSON-encoded sequence 
```
{ "name": "~!@#$%^&*()_+`-={}[]:;\\\"|\\\\", "count": 0 }
```
2. Both response preview and response source code failed to pretty-print the response body.

## Other Notes

The screenshot that shows what I get:

![screen shot 2017-06-07 at 12 48 17](https://user-images.githubusercontent.com/88045/26872727-3caf5f0a-4b80-11e7-80a2-b70ee94d752e.png)

**Comment by gschier** [comment]
I can confirm the bug on my end. Working on a fix.
