### ISSUE TITLE
Receive "Cannot read property 'trim' of undefined" error when using Oauth 2 Implicit grant type

### ISSUE THREAD

**Issue by rideron89** [getinsomnia/insomnia#2895]
**Describe the bug**
The below error is shown when trying to use Oauth 2 with **Implicit** grant type:

```
Cannot read property 'trim' of undefined
```

Interestingly, when I set the Oauth 2 type to **Authorization Code** and refresh an access token that way, it works. Then I can switch back to **Implicit** and generate a refresh token from there.

**To Reproduce**
1. Create a new request (any method/URL should do)
2. Set **Auth** to **Oauth 2** - **Implicit**
3. Enter Oauth settings along with refresh token
4. Click **Fetch Tokens**
5. Refresh token is cleared and see error: `Cannot read property 'trim' of undefined`

**Expected behavior**
I'd expect to be able to refresh an access token by using the Implicit Oauth 2 grant type. Or receive a more clear error message about why I cannot.

**Screenshots**
![error](https://user-images.githubusercontent.com/1480914/101042681-7368cf00-354b-11eb-8682-3137da63d789.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - App Version: 2020.5.0
- Node Version: 12.14.1

**Comment by filfreire** [comment]
Hi @rideron89, sorry for not getting back to this issue since. I would recommend opening a new one if you are still able to reproduce this in a [recent insomnia release](https://github.com/Kong/insomnia/releases).
