### ISSUE TITLE
Feature Request: Copy Text In Schema Documentation Panel

### ISSUE THREAD

**Issue by simon1867** [getinsomnia/insomnia#2899]
I'm using `2020.5.0` of Insomnia on Mac. 
It would be really useful if I could select and copy the text in the schema documentation panel (the panel on the right from the screenshot). Right now the text is not selectable.

![Screen Shot 2020-12-03 at 11 36 16 AM](https://user-images.githubusercontent.com/17653830/101080585-33fbac00-3566-11eb-8d50-abfb25a64601.png)

**Comment by lykims** [comment]
Hi!
I've been having the same "issue" when using Insomnia for GraphQL requests, and would like to work on this.
