### ISSUE TITLE
Feature request: Easy way to copy values into environment variables.

### ISSUE THREAD

**Issue by warrenc5** [getinsomnia/insomnia#2903]
Hello, given Insomnia is a simple yet powerful tool and fun to use.

I can't help but think there could be an express way to get selected text (typically from a response) into the variable. 

Our dev team are constantly generating JavaWebTokens and want to put them into the environment variable to reuse them.. Every time they expire (hourly) we have to copy and paste the token into the *Base environment*

Maybe a right click context menu "assign to variable"  that maybe pops up a selector with the same way to autocomplete variable names.  Or some other plugin has solved this.. Open to ideas & suggestions.

**Comment by jgiovaresco** [comment]
👋  @warrenc5 

I have a similar use case, and to handle it, I'm using the "Response -> Body Attribute" tag. Have you tried this? 

FYI, in the autocompletion list, select the following item:
![Screenshot 2020-12-04 at 08 13 14](https://user-images.githubusercontent.com/4171593/101133483-1a5f7080-3609-11eb-8a49-96bae99e8212.png)

Then you would be able to select a request and provide a JSONPath to extract an attribute from the response body.
![Screenshot 2020-12-04 at 08 14 41](https://user-images.githubusercontent.com/4171593/101133536-3236f480-3609-11eb-89df-76f79121e97e.png)

**Comment by warrenc5** [comment]
No, I hadn't tried this but this programmatic approach is exactly what I'm looking for. Thanks.
