### ISSUE TITLE
[Bug] Fails to open preferences on Linux (Installed with Snap)

### ISSUE THREAD

**Issue by louisjrdev** [getinsomnia/insomnia#2904]
Insomnia fails to open the preferences pane on Fedora 33 (Workstation Edition) (Wayland Windowing System) with Insomnia installed with snap.

When I open the preferences I get a blank white screen like so:
![image](https://user-images.githubusercontent.com/17555062/101162760-a5049780-362a-11eb-9da5-5207e74d9be3.png)

and if i run from `snap run insomnia` in the terminal I can see the error:
![image](https://user-images.githubusercontent.com/17555062/101162975-fdd43000-362a-11eb-997d-3ec186c0f8b8.png)

**Comment by rafaelrenanpacheco** [comment]
Which version are you running? On Ubuntu preferences are opening just fine. This is the version I have installed:

```
Version: Insomnia Core 2020.5.1
Release date: 12/3/2020
OS: Linux x64 5.4.0-56-generic
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libssh2/1.9.0 nghttp2/1.41.0
```

**Comment by louisjrdev** [comment]
I am running Insomnia 2020.5.1, unfortunately I can't see the results from the about menu as it shows up like this:
![image](https://user-images.githubusercontent.com/17555062/101189184-9c25bd00-364e-11eb-91f4-75c60756894f.png)

**Comment by jbberinger** [comment]
Insomnia 2020.5.1 completely broke my workflow on Ubuntu. None of my endpoints load, my preferences page is white, and the about screen has font issues like the above image.

**I reverted my snap package to 2020.5.0 and all of the problems went away.**

```
❯ snap list insomnia --all
Name      Version   Rev  Tracking       Publisher    Notes
insomnia  2020.5.0  116  latest/stable  gschier1990  disabled
insomnia  2020.5.1  117  latest/stable  gschier1990  -
❯ sudo snap revert insomnia --revision 116
insomnia reverted to 2020.5.0
```

I'm not moving off of 2020.5.0 until this is fixed.

**Comment by ChristianHuff-DEV** [comment]
I'm facing the same issues with 2020.5.1 on Ubuntu 20.04.
Edit: Using the .deb package instead of snap fixes the issues.

**Comment by crenacer** [comment]
I have the same issue: [comment link](https://github.com/Kong/insomnia/issues/929#issuecomment-755200171)

**Comment by louisjrdev** [comment]
@nijikokun Is it possible to get this flagged and moved along the process? Shame Linux becomes a second class citizen a lot of the time.

**Comment by sidigi** [comment]
same issue manjaro snap package

**Comment by gixxerblade** [comment]
Same issue Fedora 33 also using snap. This is what I get when I try import a file
![insomnia](https://user-images.githubusercontent.com/38958206/106920447-161f0480-66d9-11eb-9d6d-8abbf1678c50.png)

**Comment by louisjrdev** [comment]
@develohpanda Is it possible to get this at least triaged?

**Comment by jsg2021** [comment]
appImage works. snap not so much. (fedora 33, x11, gnome)

**Comment by develohpanda** [comment]
@louisjrdev we're aware of this issue are trying to figure out what to do next; at this stage all of the investigations we have done regarding bugs in the Snap package (there are several tickets) have fallen short. Current suggestion, going by other comments, is to use the appimage.
