### ISSUE TITLE
Too much strict node version

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#2906]
Hello!

I'm trying to contribute to Insomnia with some minor UI enhancement. In order to do that I followed the [Developing - Initial Dev Setup](https://github.com/Kong/insomnia#developing) guideline, and after I run the `npm run bootstrap` I get this error:

```
> node ./scripts/check-version.js

Incorrect node version installed ...

Current node version -> 12.20.0
Expected node version -> 12.18.3
```

Is this the expected strictness for the nodejs version?

To avoid being stuck in this strange validation, I changed the `check-version.js` to ignore this validation. Now the bootstrap is running again just fine.

**Comment by louisjrdev** [comment]
It seems that you are expected to use [nvm](https://github.com/nvm-sh/nvm) as there is an `.nvmrc`. 
Also there is a line in the readme saying: 

> Development on Insomnia can be done on Mac, Windows, or Linux as long as you have NodeJS and Git. See the .nvmrc file located in the project for the correct Node version.

**Comment by rafaelrenanpacheco** [comment]
Oh right, I didn't know about this nvm thing.

Thanks!
