### ISSUE TITLE
Problem with keyboard shortcuts re-assigning on MacOS

### ISSUE THREAD

**Issue by predatorpc** [getinsomnia/insomnia#2920]
Hello Guys,

I am really appreciate using your software for long time,
but I faced a problem with re-assigned keyboard shortcuts on my MacBook Pro, with latest Catalina installed.

Main problem is that ^C, ^V, ^A, ^Z combinations just don't work. CMD+C, CMD+V, CMD+A work as well.

But in system settings I re-assigned this combinations for control button using. As far as I know it takes Menu item by name and use this shortcut, but in Menu items its good as well and written like ^C, ^V, ^A, etc. 

Any input or text area in Insomnia has this problem not only JSON editor. Could you kindly check this and fix it in next release if it is possible. It is very annoying. Really. 

Thanks in advance!

**Desktop:**
Version: Insomnia Core 2020.5.1
Release date: 04.12.2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0

**Comment by wongstein** [comment]
Hotkeys have been an issue for us and we've recently retouched that code.  Can you still reproduce these problems with the latest Insomnia 2022.5.1?

**Comment by wongstein** [comment]
Closing this issue for now, please feel free to re-report when you get a chance to reproduce problems on the latest Insomnia version.
