### ISSUE TITLE
SEARCH HTTP method

### ISSUE THREAD

**Issue by jeanmatthieud** [getinsomnia/insomnia#2924]
Insomnia is missing the SEARCH HTTP Method in the dropdown.

https://trac.tools.ietf.org/id/draft-snell-search-method-00.html

**Comment by nijikokun** [comment]
Welcome 🤗 

Unfortunately, while we do only support the official HTTP methods in the dropdown, that doesn't mean you can't use the SEARCH method while making requests!

Click the method and select "Custom Method":
<img width="271" alt="Screen Shot 2020-12-09 at 9 34 14 AM" src="https://user-images.githubusercontent.com/198276/101665536-eff32600-3a01-11eb-9f74-bf8b4dc81645.png">

Change your method to SEARCH:
<img width="983" alt="Screen Shot 2020-12-09 at 9 34 04 AM" src="https://user-images.githubusercontent.com/198276/101665571-fb465180-3a01-11eb-8eb9-ca4bf13c1bc4.png">

And now your request can be made with the SEARCH method:
<img width="244" alt="Screen Shot 2020-12-09 at 9 36 38 AM" src="https://user-images.githubusercontent.com/198276/101665683-2630a580-3a02-11eb-82ff-870f424bfe89.png">

Hopefully this helps!
