### ISSUE TITLE
Show Password Button. Auth -> Basic -> Password input.

### ISSUE THREAD

**Issue by VictorioBerra** [getinsomnia/insomnia#2929]
**Is your feature request related to a problem? Please describe.**
I pasted a password into the auth -> bassic -> password box and did not know I had over-pasted characters.

**Describe the solution you'd like**
I would like an eyeball icon next to the password dialog to toggle password visibility.

**Comment by tharun208** [comment]
I like to work on this

**Comment by tharun208** [comment]
actually, there is an option to reveal passwords which is available under `Preferences` -> `General` -> `Reveal passwords`.
