### ISSUE TITLE
Outdated 2017-09-20.pem CAfile?

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#2941]
Hello!

Today we got a new certificate for our endpoints, and sending request from Chrome works just fine. When we tried to send a request from Insomnia the TLS handshake failed with the following trace:

```
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /tmp/insomnia_2020.5.2/2017-09-20.pem
*   CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 7
```

This is the certificate shown in the Chrome certificate dialog:

![image](https://user-images.githubusercontent.com/12160864/102134609-8cb82800-3e35-11eb-9ed7-b25e186ff630.png)

One thing that seems odd is the use of the 2017-09-20.pem CAfile, which looks like very outdated.

If this is indeed the issue, any plans to update this CAfile?

**Comment by nijikokun** [comment]
Yes, it's currently slated for the next release `2021.1`
