### ISSUE TITLE
unexpected "underscore and dot" at beginning of preset values

### ISSUE THREAD

**Issue by RealSting** [getinsomnia/insomnia#2942]
**Describe the bug**
Like title

**Screenshots**
![image](https://user-images.githubusercontent.com/198276/102248725-5969ad80-3eb6-11eb-9fb0-388a4e582c78.png)

**Desktop (please complete the following information):**
 - OS: win 10 x64
 - App Version 2020.5.2 CORE

**Comment by nijikokun** [comment]
Hi @buddhabas this is a recent change that came within 2020.5, to give users the ability to use [special characters such as hyphens](https://github.com/Kong/insomnia/issues/2601) in environment variables.

**Comment by opsmun** [comment]
@nijikokun hey there, I know it's probably bad form to comment on a closed issue, so hopefully you can forgive me.  I noticed when I fired up Insomnia this week that all of my environment variables now must be referenced with prepended underscore and dot, like @buddhabas .  This change seems to have broken the references in some of my stored requests, but not others, and a few of my environment variables have simply vanished.  Do you have any advice for a user in my situation?  Thanks!

**Comment by nijikokun** [comment]
> This change seems to have broken the references in some of my stored requests, but not others, and a few of my environment variables have simply vanished. Do you have any advice for a user in my situation?

Hi @buddhabas this shouldn't be occurring as the change should be backwards compat, if you don't mind please open a new PR with examples of your environments that have been broken!

**Comment by dimitropoulos** [comment]
(to me, anyway) @opsmun not bad form at all when it's a comment as constructive as yours was.  if there's something we can do to help make the product better we want to know about it!

I'll keep an eye out for more info from you on this whenever you get a chance.

**Comment by koldoon** [comment]
Is it going to stay forever? I mean, will we always face this messy "_." part for every and each variable even if it is not necessary because I don't use hyphens in my variables? This is kinda strange decision: to solve some very specific issue resulting into such a dirt in everything else. Even if it is used internally in implementation, I believe it is possible to format variables labels in the way when prefix is not displayed when possible.

**Comment by dimitropoulos** [comment]
@koldoon to access a variable the object needs an identifier (in this case, `_`).  please tell me if you have ideas for other solutions to the problem.

**Comment by koldoon** [comment]
@dimitropoulos Please, don't mix up the internal implementation and a simple text label formatting. If internally Insomnia needs an object instance name to resolve a variable - it's ok, this is the matter of implementation, but what's the sense of printing this internal guts to end user and thus flood a nice ui? And by the way, if I explicitly type `{{variable_name}}` (without `_.`) - everything works just fine and as expected. And so this means that variables resolving logic can work well even without this "mandatory" prefix and that it is obviously optional and required for some special cases only.

**Comment by dimitropoulos** [comment]
I don't have full context on this, so I'm just trying to understand what you want.

@develohpanda (the original author on this PR) may have more to say.

**Comment by koldoon** [comment]
@dimitropoulos please refer to https://github.com/Kong/insomnia/issues/2601 for more information

**Comment by develohpanda** [comment]
Hi @koldoon, `{{variable_name}}` still working was kept for backwards compatibility, and it was a product decision at the time, to make all variables in the auto-complete dropdown prefixed with `_.` for consistency.

I hear you though, that we may need to revisit the display aspect, and I agree with your observations that the `_.` prefix is not strictly needed in all cases.

**Comment by tvb** [comment]
I completely agree with @koldoon that from an UX point of view, the addition of `_.`prefix adds nothing for the user. It only confuses. Now I need to fully type out the variable to not have the autocomplete kick in and add the `_.` to my variable. I really can't believe this is designed as intended!

**Comment by SFBorland** [comment]
Any update on this? Particularly removing the _.?

**Comment by koldoon** [comment]
@nijikokun I believe this issue must be re-opened

**Comment by rsalmei** [comment]
That's a disaster on the screen! Ugly as hell.
Please, regardless of what you've set internally, do not externalize it for the user for no gain at all. It has just polluted the screen... 😞

**Comment by koldoon** [comment]
@buddhabas please re-open the issue

**Comment by RealSting** [comment]
Hi @koldoon how can I do? Where I have to click? thanks

**Comment by koldoon** [comment]
@buddhabas I apologise, I guess that question should have been targeted to @nijikokun
