### ISSUE TITLE
[QUESTION] How can I use response body path in JSON request body

### ISSUE THREAD

**Issue by ortonomy** [getinsomnia/insomnia#2949]
**What is your question?**
I'm building a POST request with a JSON request body.

Trying to use `{ {Response}}` + `control + space` doesn't do anything. I can use ENV variables fine, but what's the point of only parsing and using the response values in query params only?!?! 

**What is the context?**
![image](https://user-images.githubusercontent.com/6688676/102298479-2691e900-3f8c-11eb-8244-e2c1dc04188d.png)

**Comment by ortonomy** [comment]
Copying from a query into JSON also doesn't work

![image](https://user-images.githubusercontent.com/6688676/102298793-c0599600-3f8c-11eb-877b-a1bd59c7cfb8.png)

**Comment by develohpanda** [comment]
Hi @ortonomy! It still needs to be valid JSON so you need to wrap the template tag in double-quotes:

```json
{
  "image": "{% response 'raw', ... %}"
}
```

Your current implementation is:
```json
{
  "image": {% response 'raw', ... %}
}
```

**Comment by ortonomy** [comment]
@develohpanda -- doesn't help, thanks. the response from the server is JSON itself. I need it to be an object. Putting inside double quotes makes it a string. 

**MOREOVER** why do I have to create this template string in the address bar of the URL and then copy it over?!?! Seems like the template tag builder should work in JSON body?

I.e. the value that I'm trying to inject into `"image" : ...` is. Putting in double quotes coerces it to a string which is NOT desired behaviour:

```
 {
    "id": "f17ce4adc31041ff5edde3ba3deae2f3.jpg",
    "storage": "cache",
    "metadata": {
      "filename": "example.jpg",
      "size": 440686,
      "mime_type": "image/jpeg",
      "width": 1667,
      "height": 1667
    }
  }
```

**Comment by apisaint** [comment]
> **MOREOVER** why do I have to create this template string in the address bar of the URL and then copy it over?!?! Seems like the template tag builder should work in JSON body?

Why so hostile? It's against the repos Code of Conduct, please stop.

Also, you can, it's done through a hotkey - `CTRL+Space`.

Not sure that this is supported, you can do it with a plugin though - but it's a bit more. Perhaps we will see the support of before and after scripts like other tools! That said, I haven't had much of a need for this though.

**Comment by ortonomy** [comment]
@apisaint -- this isn't hostile. Replies should be reserved for being helpful and bringing answers.

> Also, you can, it's done through a hotkey - CTRL+Space.

This is not helpful. I wouldn't have opened an issue if this was working. I actually think I've discovered a bug -- 

In `POST` request, the `ctrl + space` works fine:

![image](https://user-images.githubusercontent.com/6688676/103874070-ad5d6000-510b-11eb-8124-da6a639cf74e.png)

but in a `PUT` request, it fails completly:

![image](https://user-images.githubusercontent.com/6688676/103874204-d978e100-510b-11eb-836b-1e2badcd1449.png)

**Comment by apisaint** [comment]
The way you communicate is against the repositories code of conduct. I would advise to stop.

Nice, then it looks like it was helpful :) You also learned a new hotkey! Now you don't have to do it in the url bar anymore - except for PUT - haha. Should open a new issue as well :+1:

**Comment by ortonomy** [comment]
> The way you communicate is against the repositories code of conduct. I would advise to stop.

I would advise you to stop with this. It's just noise and hot air.

> You also learned a new hotkey! 

I didn't learn it, I already knew it. It didn't work before in `PUT` requests. I hadn't tried it in `POST`. I advise you stop being patronising. This should probably be against the code of conduct, too.

**Comment by apisaint** [comment]
> I would advise you to stop with this. It's just noise and hot air.

Please read the [code of conduct.](https://github.com/Kong/insomnia/blob/develop/CODE_OF_CONDUCT.md)

**Comment by ortonomy** [comment]
> Please read the code of conduct.

Please leave.

**Comment by apisaint** [comment]
Following up on the hotkey not working for the maintainers of this repository - I could not replicate. Tried on a fresh request, on an existing request, and on a request where I converted from POST to PUT. Since Ortonomy didn't provide replication steps I tried all that I could think of.

I tried with Insomnia Core and Insomnia Designer (versions - develop, 2020.5 and 2020.4)

<img width="507" alt="Screen Shot 2021-01-07 at 1 29 46 AM" src="https://user-images.githubusercontent.com/77082541/103876081-0f748180-5088-11eb-80e3-7f035ce36ba4.png">

As a note, I tried with valid and invalid json just to make sure.

**Comment by apisaint** [comment]
Update. I have found a way to replicate the issue, not sure if intentional, seems to be though. Haven't looked through the code yet.

**Comment by apisaint** [comment]
Second update, for ortonomy. This is an upstream issue from Codemirror, it's intentional, while inside a string or comment the hint menu hotkey will not trigger. To get it to trigger, the maintainers must write their own hint menu helper for each language they wish to support. Unfortunate.

See more details in #2981

**Comment by ortonomy** [comment]
Ummm, no. Here's me, smashing `ctrl + space` outside of a string, in a JSON body

![bug](https://user-images.githubusercontent.com/6688676/103881056-e51cd580-5114-11eb-9573-bea2bf0d25fa.gif)

I can do it inside the JSON if it helps?

**Comment by apisaint** [comment]
> Ummm, no. Here's me, smashing `ctrl + space` outside of a string, in a JSON body

Interesting. Does the console log show anything? View -> Toggle DevTools (`CMD+Option+I`)

For reference, same thing (wanted to make sure that I did nested as well). Maybe I could try the same JSON body that you have too.

<img width="428" alt="Screen Shot 2021-01-07 at 2 29 00 AM" src="https://user-images.githubusercontent.com/77082541/103882228-5797a200-5090-11eb-8c59-8b1b27059d3f.png">

---

Update: (tried with your body as well)

<img width="437" alt="Screen Shot 2021-01-07 at 2 33 28 AM" src="https://user-images.githubusercontent.com/77082541/103882526-c96feb80-5090-11eb-9391-76d47b4d8701.png">

**Comment by apisaint** [comment]
I was actually wrong, there is an autocomplete hint helper for Insomnia - looking through it now. Hopefully there is something in your console @ortonomy.

**Comment by ortonomy** [comment]
Nothing in dev console. It's also first place I looked.

**Comment by apisaint** [comment]
Alright, found out that `autocomplete.js` is controlling the dropdown, however, there are a lot of cases where it won't show up (and I am not aware of all of them - for example _sometimes_ whenever you try when your cursor is positioned after an open square bracket `[`)

<img width="503" alt="Screen Shot 2021-01-07 at 3 04 07 AM" src="https://user-images.githubusercontent.com/77082541/103885656-308f9f00-5095-11eb-9eba-f533454daa02.png">

**Comment by apisaint** [comment]
Figured out the reason @ortonomy looks like it depends on whether or not the matcher thinks that the character you're touching is worth looking up or not, and I think it'll be best to leave it up to the maintainers to decide whether or not to remove support for `[]{}` as matching characters.

<img width="1228" alt="Screen Shot 2021-01-07 at 3 11 11 AM" src="https://user-images.githubusercontent.com/77082541/103886479-6f722480-5096-11eb-84a8-02adc8307dba.png">

As for why it doesn't show up in strings, its trying a partial match against the word value of that string:

`"World|"` where your cursor is on the `d` does a match against `World` within the hint dropdown. No matches, no dropdown.

<img width="709" alt="Screen Shot 2021-01-07 at 3 15 15 AM" src="https://user-images.githubusercontent.com/77082541/103886584-94ff2e00-5096-11eb-84f8-cbea4d32ae81.png">

**Comment by ortonomy** [comment]
Thanks for going to such lengths @apisaint - but it's not just at the boundaries of the chars `{[]}` - I can 'ctrl'+'space' click anywhere in that sample JSON and it just won't show the prompt to insert response info. Sounds like this is definitely a partial reason. I may go back to postman - it's relatively much easier to save response info and pass it back in to a request.
