### ISSUE TITLE
[Feature Request] Nested Form URL Encoded Editing

### ISSUE THREAD

**Issue by LahiruBandara** [getinsomnia/insomnia#295]
## Overview
- `Insomnia Version:` 5.0.5
- `Operating System:`  Fedor 22
- `Summary: ` It's very difficult to enter data and troubleshoot

When request needs to be tested with Form URLencoded, each field has to be entered in a painful way and when you have nested objects, it becomes more difficult to troubleshoot. 

Please refer to my attachments. 

It would be ideal if you enable URL encoded endpoint testing body to be just like the JSON format and programmatically changing to URL encoded prior to request. 

Pain Format :)
![pain-format](https://user-images.githubusercontent.com/10897961/26921624-47a81cd2-4c5a-11e7-8e1a-36f97ec922a7.png)
Cool Format 
![cool-format](https://user-images.githubusercontent.com/10897961/26921623-47a7695e-4c5a-11e7-827d-f23d3ce9eff4.png)

**Comment by gschier** [comment]
Thanks for the suggestion @LahiruBandara.

I've had a small number of other users ask about this as well. Unfortunately, there is no standard for nesting data in `x-www-form-urlencoded` requests. It's up to the API/framework to decide on the implementation. This means that Insomnia would not be able to implement a solution that would work for everyone.

There _is_, however, a plugin system (#51) being written right now, which would be a much better place for a feature like this to be. It's not possible to write one at the moment, but I could imagine a plugin that converts JSON bodies to `x-www-form-urlencoded` at send time.
