### ISSUE TITLE
In big sur top corners not rounded

### ISSUE THREAD

**Issue by adanpineda** [getinsomnia/insomnia#2961]
**Describe the bug**
After updating mac to big sur the app has some weird gray corners on the top left / right. 

**To Reproduce**
Just launch the app and look at the top left and top right. 

![Left](https://user-images.githubusercontent.com/10952330/102671182-bbdbdb80-414c-11eb-8ca5-7be3e8d11b19.png)

**Comment by MrSnix** [comment]
Duplicate of #2835
