### ISSUE TITLE
cut off whitespace and comments in xml body when using soap api

### ISSUE THREAD

**Issue by baermathias** [getinsomnia/insomnia#2966]
**Describe the bug**
If you use comments and/or whitespace, it is being send to the interface, e.g.:

```xml
<ns:entityTypeId>
	<!--4 = project-->
	<!--5 = process-->
	<!--11 = resource-->
        <!--n = others-->
	4
</ns:entityTypeId>
```
If using this code in the request, the response would be:

```xml
    <soapenv:Fault
      xmlns:nsIDc08="http://schemas.xmlsoap.org/soap/envelope/">
      <faultcode>nsIDc08:Client</faultcode>
      <faultstring>Invalid value "
				
				
				
				
				4
			" for element entityTypeId</faultstring>
      <detail/>
    </soapenv:Fault>
```

**Expected behavior**
cut off comments and whitespace, so it looks like this: `<ns:entityTypeId>4</ns:entityTypeId>`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Installation Method: exe file
 - App Version 2020.5.1

**Comment by kreosus** [comment]
Hi @baermathias, have you tried our latest release located here: https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.3, to see if it resolves your issue?

**Comment by kreosus** [comment]
Closing due to lack of response
