### ISSUE TITLE
Alphabetized/Searchable Schema

### ISSUE THREAD

**Issue by MoshePaul** [getinsomnia/insomnia#2967]
**Is your feature request related to a problem? Please describe.**

The schema docs cannot be searched or filtered. In a large code base with hundreds of schema you have to scroll to find the right one.

**Describe the solution you'd like**

An elastic search would be perfect for finding the exact doc you need quickly

**Describe alternatives you've considered**

Alphabetizing the schema somehow would at least make searching them far easier, and possibly be cheaper/faster to get over the line. Not as good of a feature though.

**Comment by apisaint** [comment]
Are you referring to GraphQL or Specs?

**Comment by MoshePaul** [comment]
GraphQL. I know you can command + click but I would like to be able to use a search bar to find the documentation for a specific query/mutation in the bar on the right.

**Comment by develohpanda** [comment]
This seems to be a duplicate so I will close this issue in favor of #2720, feel free to continue there if you have any specific requirements of GQL schema search. Looks like the alternate request for alphabetizing the schema was also resolved with #2732, which would be a part of the upcoming release. Thank you for requesting! 🙂
