### ISSUE TITLE
Updated requests rolled back to default after switching to DESIGN mode and then back to DEBUG mode

### ISSUE THREAD

**Issue by ghimiresdp** [getinsomnia/insomnia#2971]
I have imported the design from the openAPI3.0 file.

I needed a few more requests and tried adding and reordering the requests in the debug mode. but every time I switch back to design mode, my changes are lost and the view resets to the default imported APIs

Here, I added the Auth folder and added a new request `Some New Request`, and ordered the `Login` API inside the `Auth` folder, and renamed it as `Reordered Login inside Auth Folder`.

![image](https://user-images.githubusercontent.com/13810600/103337777-7a302680-4aa4-11eb-9cf8-a4d934ccf21a.png)

When I switched to the design mode and returned back to the debug mode again, all the changes except newer requests are lost and the default environment variables are overridden.
![image](https://user-images.githubusercontent.com/13810600/103337985-0b9f9880-4aa5-11eb-851a-f03112be65bf.png)

It even clears the form data 

### before
![image](https://user-images.githubusercontent.com/13810600/103338466-a2b92000-4aa6-11eb-85ec-10d76e5eed6c.png)

### after
![image](https://user-images.githubusercontent.com/13810600/103338485-ad73b500-4aa6-11eb-8b96-af744a0ca18e.png)

### Steps To Reproduce

1. Create a blank project
2. In the design tab, add OpenAPI 3.0 design
3. switch to the `DEBUG` tab
4. Reorder the requests (create a folder and move the request inside it, rename the request, etc.)
5. switch back to the `DESIGN` tab
6. again switch back to the `DEBUG` tab

**Comment by apisaint** [comment]
Might be able to make something happen here, there are some questions that need to be answered before doing exploration though. Especially about user experience. Perhaps the first step is to prevent them from changing and later on show some form of a dialog or alert that there are "updates", and a button to "update now".

The biggest issue is that the api used to build the requests when switching between these views is also the same one for regular imports. First step would be to declare that it's a specific form of building to prevent side effects.
