### ISSUE TITLE
Add application/yaml body content support

### ISSUE THREAD

**Issue by kapodes** [getinsomnia/insomnia#2999]
**Is your feature request related to a problem? Please describe.**
Right now I can choose json/yaml in body content and get nice syntax highlight.
When I choose json I get Content-type: application/json header
But when I choose yaml I get Content-type: text/yaml header

For working with kubernetes api I need application/yaml content type, but if I manually edit content-type header I loose yaml syntax highlight even though it still says YAML as body type.

**Describe the solution you'd like**
It would be nice if I could have body syntax highlight and proper header. 
As a possible solution I would keep body syntax highlight after manual edit of content-type header and keep the current default initial value of text/yaml.

**Additional context**
Proper body with wrong header
<img width="252" alt="highlight" src="https://user-images.githubusercontent.com/16903630/104498263-c10d3880-55db-11eb-8822-9065b08eb8ed.png">

Wrong body with proper header
<img width="256" alt="no highlight" src="https://user-images.githubusercontent.com/16903630/104498362-df733400-55db-11eb-98b4-b2bdde6573ab.png">

**Comment by develohpanda** [comment]
Interesting bug! I ran a quick investigation and it seems this is a mistake in configuring code-mirror for YAML.

I've fixed that, and also introduced the yaml-lint add-on. :)

**Comment by kapodes** [comment]
Nice!
