### ISSUE TITLE
[Feature Request] Add image/media support to POST/PATCH requests

### ISSUE THREAD

**Issue by PierreMaraisZA** [getinsomnia/insomnia#3003]
Good day, I was hoping there was a way to include an image in a POST request. Im building an API and some Webhook features for our company and there doesn't seem to be a way to send images. I'm not too sure if Postman has that feature, and from quickly googling I didn't find any other client that supports it, so it could definitely put Insomnia far above the competition. 

So yeah, this is a request for Image/media support / array of media

**Comment by ranjan-purbey** [comment]
You can set the POST/PATCH body type to multipart and select a file as the value. See screenshot

![image](https://user-images.githubusercontent.com/6953187/104856345-2ba1d980-5938-11eb-9c06-20d575f0f3e8.png)

**Comment by PierreMaraisZA** [comment]
Fantastic! Wonder why support asked me to open a ticket then instead of
just telling me that. Thanks

**Comment by ranjan-purbey** [comment]
Happy to help. If that solved your issue, please close this one
