### ISSUE TITLE
Cannot Download Insomnia for installation

### ISSUE THREAD

**Issue by mynsteria** [getinsomnia/insomnia#3005]
**Describe the bug**
Followed Insomnia Core for Mac link and get this message:

> Your connection is not private
> Attackers might be trying to steal your information from github-production-release-asset-2e65be.s3.amazonaws.com (for example, passwords, messages, or credit cards). Learn more
> NET::ERR_CERT_INVALID

**To Reproduce**
on Mac go to https://insomnia.rest/download/ and click Insomnia Core for Mac button

**Expected behavior**
Should've downloaded a .dmg for install

**Desktop (please complete the following information):**
Mac OS X Catalina

**Comment by develohpanda** [comment]
Hi @mynsteria, we have tried to download with your reproduction steps (and also ensured it downloaded the same AWS resource), but don't see this error. It may also be related to an AWS S3 issue. What browser are you using to download?

**Comment by mynsteria** [comment]
huh works now. closing.
