### ISSUE TITLE
[Feature]: remember last used URL in import

### ISSUE THREAD

**Issue by sfabriece** [getinsomnia/insomnia#3009]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when Insomnia does not remember my last used URL importing routes from a URL

**Describe the solution you'd like**
Insomnia should remember the last used URL when importing routes. It's unlikely that it'll change often.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/3108592/104901141-434f8100-597d-11eb-86dd-3c8ff47240b0.png)

**Comment by develohpanda** [comment]
This seems like a useful feature! I suggest following an approach similar to this PR: https://github.com/Kong/insomnia/pull/2586, which does the same thing but persists the last used export format.

**Comment by sfabriece** [comment]
I'm gonna submit a PR on this if it's ok @develohpanda
