### ISSUE TITLE
[BUG] Moving requests out of folder

### ISSUE THREAD

**Issue by vertil** [getinsomnia/insomnia#301]
## Overview
- `Insomnia Version:` 5.2.0
- `Operating System:`  Win 8
- `Summary: ` Not possible to move requests into a parent folder with no requests in it.

## How To Reproduce

Let's assume my folder structure looks like this:
* Tool -> news -> #bunch of requests
* Tool -> schedule -> #bunch of requests

Behaviour:
If i drag an request (i'll name it "request-1") from "news" and want to put it in the "Tool"-folder, there's always the "forbidden icon", so i'm not able to move it into an folder where _no other_ request is present.

If i firstly create an random request in my "Tool"-folder and then hover my dragged request-1 over the "Tool"-folder, the line-indicator finally shows up. 

## Other Notes
To simplify, i made a gif:
![capture](https://user-images.githubusercontent.com/2685063/27021071-46b0afa8-4f46-11e7-9f32-d90ce2c8a54b.Gif)

**Comment by gschier** [comment]
Ah yes. This has been a bug since the initial implementation of nested folder. I've been waiting for someone to notice it 😄 

The reason for this behavior is that request can only be moved before or after other requests. (The same thing applies to folders.)

I'll see if I can find some time to fix this properly.

**Comment by gschier** [comment]
So, I spent probably a whole day on this issue a few months ago. Turns out I just needed to take a break. This time it took less than an hour to come up with a nice solution 😄

**Comment by vertil** [comment]
awesome! :-)
nice tool, again!

**Comment by tolgayildizz** [comment]
Is the problem fixed? In the meantime, I'm version version 6.3.2 and I'm having the same problem.
By the way, a really nice tool!

**Comment by gschier** [comment]
@tolgayildizz please create another issue if you are seeing this again
