### ISSUE TITLE
Increase double-click time for editing environments (Double click to edit)

### ISSUE THREAD

**Issue by baermathias** [getinsomnia/insomnia#3016]
**Describe the bug**
Double clicking on a newly created sub environment only works if you click really fast and if you work with a laptop, where your double-clicking is probably a bit slower than with a mouse you can't select or edit the sub environments.

**To Reproduce**
1. Click 'ctrl + e' to manage environments
2. Create one or two sub environments
3. Try to select it with a double-click on a touch pad.

It would be great if the double click-click time could be increased a bit, so have more time to execute the second click.

**Comment by wongstein** [comment]
Is this issue still a problem in the latest Insomnia?  I am not able to reproduce it.
