### ISSUE TITLE
Multipart form POST request client body timeout (408)

### ISSUE THREAD

**Issue by chrisb-c01** [getinsomnia/insomnia#3029]
**Describe the bug**
I'm getting client request timeouts (HTTP code 408) when POSTing Multipart Form data of a certain size (> 1 Mb).

Form data contains 1 key named 'file' with a PDF file as the value.

Remarks:
* Client timeout in Insomnia is set to -1.
* Authorization header includes a Bearer token. If this token is renewed the request succeeds 1 time and then fails consistently (due to timeouts). Server (Nginx) is aborting the connection due to client_body_timeout.
* If I include a file < 1 Mb it works.

What I've tried:
* Remove all timeouts/buffer limitations server side.
* Tried on different clients.
* Changed MTU size.

The same request succeeds consistently in Postman (Version 8.0.2).

**To Reproduce**
1. POST Multipart form data with a file > 1 Mb.
2. Wait for timeout.

**Expected behavior**

**Screenshots**
<img width="501" alt="Screenshot 2021-01-27 at 12 33 22" src="https://user-images.githubusercontent.com/33776709/105986570-68d73b80-609d-11eb-8d02-db2faed5b395.png">
<img width="509" alt="Screenshot 2021-01-27 at 12 33 27" src="https://user-images.githubusercontent.com/33776709/105986582-6b399580-609d-11eb-820c-c1f4f766250a.png">

**Desktop (please complete the following information):**
Version: Insomnia Core 2020.5.2
Release date: 09/12/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0

**Additional context**

Timeline of the request:
```
* Preparing request to https://<hidden
* Current time is 2021-01-27T11:27:33.772Z
* Using libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
* Using default HTTP version
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Too old connection (131 seconds), disconnect it
* Connection 18 seems to be dead!
* Closing connection 18
* TLSv1.2 (OUT), TLS alert, close notify (256):
*   Trying <hidden>...
* Connected to <hidden> (<hidden>) port 443 (#19)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
*   CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=<hidden>
*  start date: Jan 21 17:54:06 2021 GMT
*  expire date: Apr 21 17:54:06 2021 GMT
*  subjectAltName: host "<hidden>" matched cert's "<hidden>"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fa8ed287e00)

> POST /<hidden> HTTP/2
> Host: <hidden>
> user-agent: insomnia/2020.5.2
> content-type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY
> authorization: Bearer <hidden>
> accept: */*
> content-length: 1651688

* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!

| (64 KB hidden)
<hidden>
| (13 KB hidden)

* We are completely uploaded and fine
* HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 1)
* stopped the pause stream!
* Connection #19 to host <hidden> left intact
```

**Comment by kreosus** [comment]
Hi @chrisb-c01 have you had the chance to try out our newest release to see if it resolves your issues.
