### ISSUE TITLE
[Suggestion] Insomnia displays INVALID if HTTP reason phrase is omitted

### ISSUE THREAD

**Issue by bannmann** [getinsomnia/insomnia#303]
## Overview
- `Insomnia Version:` 5.2.0
- `Operating System:`  Windows 10
- `Summary: ` When the server does not send an HTTP reason phrase, Insomnia displays `INVALID` next to the status code.

## How To Reproduce
1. Make a POST request without a body to https://cockpit.biggamedata.com/api/healthcheck
2. You can see that Insomnia renders `405 INVALID`, and the tooltip explains the background of "Method not allowed" errors.

## Other Notes

* The HTTP reason phrase is optional, see https://stackoverflow.com/q/17517086/7641 - HTTP 2 does not even have this concept any longer.
* As Insomnia displays tooltip explanations and thus has knowledge about the meaning of some codes (e.g. 404, 405) it could just as easily display its own "reason phrase".
  * For example, the developer console of Firefox displays its own reason phrase (at least when the server did not send one)
* In my opinion, displaying `INVALID` is a bad choice because it is formatted exactly like `OK` or `NOT FOUND` and is confusing because both the request and the response are perfectly valid.
* Suggestion:
  * Insomnia should default to displaying its own reason phrases for all well-known status codes (those from RFCs).
  * For other codes, if the server gave a reason phrase, Insomnia should display it surrounded by double quotes (to make it obvious it's a foreign value)
  * For other codes, if the server did not give a reason phrase, just leave it out and only render the code.

**Comment by bannmann** [comment]
Note that the behavior is inconsistent - for HTTP `200` responses without a reason phrase, Insomnia shows `SUCCESS`, presumably because that is the name of the `2xx` category. If it applied that logic to `405`, it should display `CLIENT ERROR` which at least is less confusing than `INVALID`. However, I would still favor the suggestion above.

**Comment by gschier** [comment]
@bannmann `INVALID` is the default name for all 4xx within Insomnia, which is short for "invalid request". You can see the code here for handling the fallbacks: https://github.com/getinsomnia/insomnia/blob/develop/app/ui/components/tags/status-tag.js

It would be easy, with a bit of work, to build a list of fallbacks for every response code (400, 401, etc). Would you be interested in contributing a PR for this?

**Comment by bannmann** [comment]
@gschier I would not go for "fallbacks", but only display the built-in values by default, as described above at "Suggestion".

The rationale is that I want to avoid confusing the developer of what the server sent and what it didn't, and only display the server-sent value double-quoted and with a tooltip that says something like "Insomnia does not know about this status code. The text within quotes was sent by the server as the HTTP reason phrase."

If that is okay with you, I will create a PR somewhere in the next few months when I find the time.

**Comment by gschier** [comment]
I was able to quickly find and implement a better HTTP reasons list: https://github.com/getinsomnia/insomnia/commit/5597d331ede805325cb0a791ed285cd9ce7c3730

I have also added an informational icon when the server does not provide its own reason phrase. It will display the following message in your case: `HTTP reason phrase was inferred, as it was not provided in the response`. I know this is the opposite of what you suggested, but I think an HTTP client meant for debugging should always present the server's output by default.

![image](https://user-images.githubusercontent.com/587576/27047064-956f8bf4-4f5b-11e7-97eb-c932f89a0381.png)

Also, I'm not sure you are aware, but you can see more details on the response in the Timeline tab.

![image](https://user-images.githubusercontent.com/587576/27047156-e34a2dca-4f5b-11e7-8eb0-f3dffe5180d1.png)

**Comment by bannmann** [comment]
> I have also added an informational icon when the server does not provide its own reason phrase. It will display the following message ...

That works fine, as well. The main goals for me are completeness (in terms of RFCs) and distinguishing server-sent and inferred reason phrases.

I created PR #307 based on your commit regarding the "completeness" goal.

I like the new backup reason phrases, they should be much less confusing.

Yeah, I was aware of the timeline tab.
