### ISSUE TITLE
Insomnia Designer - Unable to verify the first certificate (SSL)

### ISSUE THREAD

**Issue by eduardohass** [getinsomnia/insomnia#3036]
**Desc.**
When importing the repository from GitLab, I receive the information saying that Insomnia couldn't validate the first certificate.

**To Reproduce**
1. Open Insomnia Designer
2. Click on button **Create** and **Git Clone**
![image](https://user-images.githubusercontent.com/4368558/106307870-a58e6880-623e-11eb-94c4-2faa1ca6ecef.png)
3. Populating the fields with my informations
![00](https://user-images.githubusercontent.com/4368558/106308040-e8504080-623e-11eb-87c6-760d3f9aa97c.png)
4.Click on the button **Done**
![01](https://user-images.githubusercontent.com/4368558/106308102-fd2cd400-623e-11eb-96ba-09aacf44ccfd.png)

**Expected behavior**
I tried the same steps on another Gitlab that don't need the trusted certificate(SSL) and is gone everything working fine.
I tried too to install the certificate on my computer too and without success.
![image](https://user-images.githubusercontent.com/4368558/106309160-7aa51400-6240-11eb-91a6-b49c9cfdc5c4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Git version 2.30.0
 - Version: Insomnia Designer 2020.5.2
 - Release date: 12/9/2020
 - OS: Windows_NT x64 10.0.19042
 - Electron: 9.1.1
 - Node: 12.14.1
 - V8: 8.3.110.13-electron.0
 - Architecture: x64
 - node-libcurl: libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0

**Comment by waciii-ra** [comment]
@eduardohass 

For a rationale I don't understand, Insomnia embeds a curated certificate file from (if I recall correctly) some Mozilla source and (if I'm not mistaken) doesn't properly run the CA Chain (I think it only checks the first ICA).

From Debug after sending a Request, the timeline tab shows where the file is located.  Our workaround has been to manually get the ICA and add it to this PEM file.  The guy in the Reference Link has an alternative to point to the System Trust Store

```
* successfully set certificate verify locations:
*   CAfile: C:\Users\<user_name>\AppData\Local\Temp\insomnia_2020.5.2\2017-09-20.pem
*   CApath: none
```

Reference:
https://kdecherf.com/blog/2018/07/13/force-insomnia-to-use-the-system-trust-store/

**Comment by waciii-ra** [comment]
This kind of problem needs to be fixed.  The Git Integration is one facet of a broader problem.  Insomnia doesn't properly handle certificate chains when executing Requests and Tests as well.
