### ISSUE TITLE
Protocol prepending issue

### ISSUE THREAD

**Issue by ATChustz** [getinsomnia/insomnia#3037]
**Describe the bug**
At some point, after making several successful API GET requests to `https://api.stripe.com/v1/skus/:sku_id/`, started to get `Error: couldn't resolve host name`. In the Timeline view, the textarea said that requests were no longer being prepared for `https://api.stripe.com/v1/skus/:sku_id/` but for `http://https//api.stripe.com/v1/skus/:sku_id/`. This incorrectly-prepended protocol was breaking the request

**To Reproduce**
1. make requests to a URL
2. observe responses, check if we get `Error: couldn't resolve host name`
3. if we do, check the timeline view to see the URL request was prepared for

**Expected behavior**
I expected to receive a response containing a SKU object from stripe

**Screenshots**
<img width="1008" alt="Screen Shot 2021-01-27 at 4 44 06 PM" src="https://user-images.githubusercontent.com/7969994/106323221-e8931080-622b-11eb-82a5-4e3cbbfc6f6d.png">
<img width="1008" alt="Screen Shot 2021-01-27 at 4 48 49 PM" src="https://user-images.githubusercontent.com/7969994/106323228-ea5cd400-622b-11eb-89b6-3ec7c2209f84.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Installation Method: downloaded from website
 - App Version v2020.5.2

**Additional context**
I have one plugin installed for Insomnia that is in use in these screenshots. It is `insomnia-plugin-path-parameters`

**Comment by filfreire** [comment]
Hi @ATChustz, thanks for reporting this. 

I tried using the same plugin, and sending a request similarly to the one you were sending and I'm no longer able to reproduce this:



![Image](https://user-images.githubusercontent.com/11976836/181060834-350fe4b0-3c95-48a5-aa52-41554cd3cb5c.png)

I'm going to go ahead and close this one. Please feel free to reopen this if you can still reproduce it with [latest Insomnia version](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2). Also feel free to report any other issues you come across.
