### ISSUE TITLE
Support for Apple M1 Silicon

### ISSUE THREAD

**Issue by ermirry** [getinsomnia/insomnia#3048]
I'd like to submit this as a feature request for a future build. After using the new 2020 Macbook Pro M1 for awhile, I can see the value in having M1 support in Insomnia. It would be great if it could take advantage of the new chip and would make for more efficient use of Insomnia when running it on an M1 Mac.

**Comment by nijikokun** [comment]
Tracking M1 support request here #2964

**Comment by nirvaansingh47** [comment]
I second @ermirry.
