### ISSUE TITLE
Curl commands that contain -d/--data are not imported as x-www-form-url-encoded

### ISSUE THREAD

**Issue by rossmcdonald** [getinsomnia/insomnia#3049]
**Describe the bug**
Insomnia currently doesn't handle implicit form-urlencoded `curl` commands properly. Per the curl docs, if `-d` / `--data` is specified, then the content-type should set to `application/x-www-form-urlencoded`:

```man
 -d, --data <data>
    (HTTP) Sends the specified data in a POST request to the HTTP server, in the same way that a
    browser does when a user has filled in an HTML form and presses the submit button. This will
    cause  curl  to  pass  the data to the server using the content-type application/x-www-form-
    urlencoded.
```

Currently it is being treated as an "Other" body type. Fixing this discrepancy should help smooth out the experience when pasting `curl` commands that contain the flags referenced above (such as the ones in the Kong documentation, which is where I ran into this issue).

I have a proposed fix for this issue available in a fork [here](https://github.com/rossmcdonald/insomnia/tree/ross/fix-curl-mime-handling). I'd be happy to contribute this as a PR if it has a chance of being accepted.

**To Reproduce**

Use a curl command that specifies `--data`, for example:

```sh
curl -i -X POST http://localhost:8001/services \
  --data name=example_service \
  --data url='http://mockbin.org'
```

And then paste it into URL field within Insomnia to have it imported into the current request.

**Expected behavior**

The pasted command would be inserted into the request as the "Form URL Encoded" body type, like so:

![Screen Shot 2021-02-04 at 12 59 22 PM](https://user-images.githubusercontent.com/4060903/106942421-ca288b80-66e9-11eb-8810-943a03355d43.png)

Instead of the current behavior, where it is treated as "Other":

<img width="1552" alt="Screen Shot 2021-02-04 at 12 59 57 PM" src="https://user-images.githubusercontent.com/4060903/106942361-b8df7f00-66e9-11eb-8545-0bb83020c429.png">

**Desktop (please complete the following information):**

The second screenshot above was taken from the latest Insomnia designer:

```
Version: Insomnia Designer 2020.5.2
Release date: 12/9/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Comment by wongstein** [comment]
Hello, is this issue reproducible with the latest Insomnia?
