### ISSUE TITLE
Automatically sync all workspaces using VCS

### ISSUE THREAD

**Issue by TahirJalilov** [getinsomnia/insomnia#3052]
Hello. Am I correct to understand that VCS not automatically syncs all my workspaces? And every time after adding a new folder or request to the workspace I have to create a snapshot and push it to the VCS?

**Comment by ravindu1024** [comment]
Ah just came here to suggest the same thing. Would be nice to have an auto "sync all" feature or maybe an option to include other workspaces when creating the snapshot.

**Comment by DMarby** [comment]
Hello @TahirJalilov, @ravindu1024!

We are looking into having the VCS automatically sync changes in the future.
One of the issues with the automatic legacy sync system that we'd like to fix when doing so was that it would silently ignore merge conflicts (when something has changed both remotely and locally), what would be your preferred behaviour in such a case for you?

For example, would you prefer it to just pick the most recent change, or get a notification and manually resolve the conflict by picking which version you'd prefer, or something else entirely?

**Comment by skiat** [comment]
> 
> 
> Hello @TahirJalilov, @ravindu1024!
> 
> We are looking into having the VCS automatically sync changes in the future.
> One of the issues with the automatic legacy sync system that we'd like to fix when doing so was that it would silently ignore merge conflicts (when something has changed both remotely and locally), what would be your preferred behaviour in such a case for you?
> 
> For example, would you prefer it to just pick the most recent change, or get a notification and manually resolve the conflict by picking which version you'd prefer, or something else entirely?

Being now used to the old "the last push wins" I'd tend to say that this way one can yes break things.. but another can also repair it once for everyone. 

But after better reflections of course a notification about conflicts & what pick option, will be better!
The important I think is to restore the auto-sync 👍

**Comment by boardy** [comment]
Hi, 
Agreed, that I'm missing auto sync feature, I move between couple of PCs quite often and I've lost count the number of times that I've made a request on one machine and so used to the previous sync system, I've forgotten to push the changes to VCS until I get to my other PC and find I'm missing loads of requests. 

Would agree that the most recent change is very likely to be the correct case, 9 times out of 10, and on the odd time that it might not be, its likely going to be simple to resolve manually. 

Thanks
