### ISSUE TITLE
inso run test command throws error (INSO CLI)

### ISSUE THREAD

**Issue by ganeshsirsi** [getinsomnia/insomnia#3058]
I have created unit tests currently in Insomnia Designer  its working  fine there with UI.
However, INSO CLI is throwing error with below command

**inso run test**
![image](https://user-images.githubusercontent.com/4299424/107198511-3291a880-6a1b-11eb-9aa9-08838f167577.png)

I have tried with command
**inso run test --appDataDir .**
this works but we cannot combine other options as mentioned in this document especially reporting doesn't work
I tried with  > output file as well but this seems to be doesnt work with **inso run test --appDataDir .**

![image](https://user-images.githubusercontent.com/4299424/107198686-72f12680-6a1b-11eb-9a8a-f374aa61941f.png)

This is verify critical feature please fix this asap

Logging after having discussion with Nijji

Neither of this command is working:
inso run test "MyTestSuite"
inso run test spc_ba58e1

I believe these are basic commands for inso not sure why this is also not working.

**Comment by nijikokun** [comment]
@ganeshsirsi I will log an issue for Inso not finding the application data directory by default, but I believe the flag you need for outputting to a file will be the `--ci` flag. See [Global Options](https://support.insomnia.rest/article/117-cli-global-options) for more information. Example below.

```
inso run test --ci --appDataDir . > output.txt
```
