### ISSUE TITLE
White page while accessing application preferences

### ISSUE THREAD

**Issue by mats852** [getinsomnia/insomnia#3060]
**Describe the bug**
I get the Legacy sync warning, but on Linux (Manjaro/i3, installed via snap) I cannot access the application preferences, it's a white page.

**To Reproduce**
1. Go to `Applications Preferences`

**Screenshots**
![image](https://user-images.githubusercontent.com/6082025/107251092-18979c00-6a02-11eb-8089-5b348a902921.png)

![image](https://user-images.githubusercontent.com/6082025/107251372-454bb380-6a02-11eb-8a2b-df3dc352c299.png)

And also, contextual menus are like this:
![image](https://user-images.githubusercontent.com/6082025/107251608-86dc5e80-6a02-11eb-8724-79c308fc7168.png)

**Desktop (please complete the following information):**
 - OS: Linux (Manjaro/i3)
 - Installation Method: snap
 - App Version 118 (not sure, contextual menus are not working)

**Comment by rgagne** [comment]
Same issue for both About and Preferences. OS Fedora 33 / Gnome. Installed through snap which says its the latest version.

**Comment by mats852** [comment]
Had no choice but to stop paying :shrug:

**Comment by serge-wq** [comment]
Same issue here. When I open `Preferences` the app crashes showing a blank page. DevTools also crash and are disconnected from the app. I am using Fedora 33 with KDE, and installed Insomnia via snap.

**Comment by danielroehrig** [comment]
Same Issue with Manjaro, Snap installation, 2020.5.2. Thing is, when I select "Import/Export", I briefly see the preferences dialog for a couple of seconds before the app goes completely white.

**Comment by svaldetero-envoc** [comment]
This happens to me on Windows 2021.2.2 when I try to login to my paid subscription
![image](https://user-images.githubusercontent.com/54991761/114752063-88d0df80-9d1b-11eb-8fe2-8dd064ed0809.png)

**Comment by jimafisk** [comment]
Same problem on Ubuntu 20.04 unity desktop, but mine is a blank black screen when trying to access preferences:

<details>
<summary>Screenshot</summary>

![insomnia](https://user-images.githubusercontent.com/5913244/139944505-801198f2-9233-42f0-b939-1b1198648ae7.gif)

</details>
