### ISSUE TITLE
Sync Not Working 

### ISSUE THREAD

**Issue by scooter3** [getinsomnia/insomnia#3062]
**Describe the bug**
When using the latest beta version, there's an issue with the sync feature. When I create and push a snapshot, no one else in my org can see it. 

**To Reproduce**
1. Click on `master` in the lower left hand corner
2. Notice that the Pull and Push snapshots options is greyed out
3. I can see the changes locally, but no one else can

**Expected behavior**
Every one in the org should be able to see the changes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Installation Method: dmg
 - App Version: 2020.5.2

**Comment by DMarby** [comment]
Hi @scooter3,

Please send an email to support@insomnia.rest and we'll be able to assist you with resolving this issue.
