### ISSUE TITLE
Unable to start insomnia app

### ISSUE THREAD

**Issue by codeasashu** [getinsomnia/insomnia#3067]
**Describe the bug**
I am unable to start/swtich to insomnia app. I am starting the insomnia development using following commands:

```
npm run bootstrap
npm run app-start
```

which **used to** ask me which module I wanted to start, choices being:
- insomnia app
- insomnia designer

Now, I've pulled in latest `develop` branch, ran above steps again, but no choices were asked. Insomnia designer is directly launched, with no way to switch to insomnia app.

Earlier, there was an option in the `developer` menu on the top, to switch to insomnia app anytime. Now it is no longer there.

**To Reproduce**
1. Clone the project (develop branch)
2. Run `npm run bootstrap` and then `npm run app-start`
3. No choices are presented and no way to start `insomnia app`

**Expected behavior**
It should allow me to start insomnia app. 

**Screenshots**
1. This is screenshot of console, where no choices were given and webpack built the modules
![image](https://user-images.githubusercontent.com/1492350/107410445-534d2180-6b33-11eb-8e68-2760060bf97f.png)

2. In the designer, no way to switch to insomnia app
![image](https://user-images.githubusercontent.com/1492350/107410856-d40c1d80-6b33-11eb-8e5a-142779d0a611.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Installation Method: git
 - App Version: Insomnia Core 2020.5.2

**Comment by develohpanda** [comment]
Hi @codeasashu, nice to see you!! We are currently in the process of merging the two applications into one. As this is a work in progress there will be some inconsistencies in UI that exist, but generally it will look like Designer does right now. For this reason the app specific prompt and related app-specific code has been removed.

Feel free to ping on Slack if you have any specific questions around different actions and where they are being/have moved to.

An additional question for you: how do you expect to be notified, as a contributor, about changes being made that would have an impact on _development_? Is it a pinned GitHub issue, a message on the README, a Tweet, a discussion, or something else?

**Comment by codeasashu** [comment]
@develohpanda Thanks, I think I will get connected on the slack for now. Closing this off for now
