### ISSUE TITLE
Is it really impossible to delete workspaces?

### ISSUE THREAD

**Issue by gpasq** [getinsomnia/insomnia#3075]
I just loaded Insomnia after a while of not using it.  After nagging me every 15 seconds to use the new beta sync I turned it on.  When the app re-loaded I was presented with every workspace I've ever used, with no apparent way to delete them.

Is it possible to delete workspaces or do I need to just remove the app?

**Comment by DMarby** [comment]
Hi @gpasq!

You can delete a workspace by using the "Delete" button in the "Workspace Settings", accessible through the workspace dropdown in the top left.
If you need any help in regards to the sync features, please send an email to support@insomnia.rest and we'll be able to better assist you.
