### ISSUE TITLE
GraphQL Schema not updating and showing schema errors

### ISSUE THREAD

**Issue by brettski** [getinsomnia/insomnia#3078]
**Describe the bug**
GraphQL Schema not updating and showing schema errors though the documentation shows correctly. Using ctrl-shift displays stale schema values. Command-q of Insomnia and starting it again refreshes to the current schema

**To Reproduce**
1. Setup a graphQL query and run it
1. Change the schema in the graph end point
2. Using the wrench button and `Refresh Schema`, refresh the schema
3. In your query, see the type changed and that Insomnia still shows the old schema information
4. Using the wrench button and `Show Documentation` navigate to the type where your schema change is and verify that the documentation has updated.
5. Though insomnia shows that the query is incorrect, click send
6. The query runs as expected

**Expected behavior**
When schema is refreshed the GraphQL query editor should update the schema

**Screenshots**
![image](https://user-images.githubusercontent.com/473633/107643150-63e8bf00-6c3b-11eb-97f6-1445125edb6b.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.1
 - Installation Method: homebrew
 - App Version Insomnia Core 2020.5.2

**Additional context**
I don't know if this is at all related, though I recently switch to `version control beta`, which correlates to when this started happening.

**Comment by grean** [comment]
As a workaround, you can change your query context with an other query´s workspace of your own and then return back to the query that is not refreshed yet. It will refresh the editor with the last schema and autocomplete will again work as expected..
Hope it will be corrected soon.
Please insomnia team, make an option to allow auto refresh when the app takes the focus again, ie switching between prefered IDE and Insomnia.
Or at least, add a keyboard shortcut assignable to refresh schema action of the current query context.
Thanks.

**Comment by crispinamuriel1** [comment]
Hi this issue is not stale! I am having this issue now.
