### ISSUE TITLE
Feature: Environment-based warnings or scripts

### ISSUE THREAD

**Issue by jgillick** [getinsomnia/insomnia#3085]
It would be nice to have an additional guardrail or warning before performing requests in certain environments.

Insomnia has become indispensable for my day-to-day work and I use it to run requests in development and sometimes production. I get paranoid about accidentally leaving the environment selector on `Production` and performing a destructive request there.

It would be great to have a toggle that will display a warning before running any task in specific environments. 

**Potential options**

* Simple checkbox in the Manage Environment window for each environment (i.e. "[] Confirm before making any request").
* A specific environment variable that Insomnia looks for. For example: 
  ```json
  {
    "INSOMNIA_ENV_WARNING": "Are you sure you want to make the request in {{_.ENV_NAME}}?"
  }
  ```
* More advanced: Attached a script block to an environment that is run before the request is made.

**Comment by hsul4n** [comment]
Is there an issue when calling variable, because I see all using `{{_.name}}` instead of `{{name}}`.

#3064

**Comment by jgillick** [comment]
@hsul4n That seems unrelated to my feature request. I'm not sure of an issue with using the underscore or not, it's just what the type-ahead recommends.

**Comment by jgillick** [comment]
I found a bit of a workaround using the `prompt` tag. Each environment has an `API_ROOT` variable used to define the domain that the API should hit. Adding the prompt tag to the front of this value will cause a prompt modal to appear. Of course, if the user enters anything in the text area, the request fails, but otherwise, this works alright.

```json
{
  "API_ROOT": "{% prompt 'Are you sure?', '', '', '', false, false %}https://production.com",
}
```

**Comment by jgillick** [comment]
Just found this insomnia plugin that basically does what I need:
https://insomnia.rest/plugins/insomnia-plugin-ask-before-sending
