### ISSUE TITLE
[Bug] Incorrect response type in response history.

### ISSUE THREAD

**Issue by SimpleCold** [getinsomnia/insomnia#309]
## Overview
- `Insomnia Version:` 5.3.3
- `Operating System:` Windows 7 SP1 x64
- `Summary: ` In the response frame, response is 200 OK, but in response history, 200 responses are displayed as ERROR.

## How To Reproduce
1. Create new request
2. Perform a request which returns 200 HTTP response.
3. You can see the ERROR labels in response history and on the screenshot supplied.
![image](https://user-images.githubusercontent.com/9578061/27134371-05ccdd2a-511e-11e7-904a-df557393f16e.PNG)

**Comment by gschier** [comment]
Thanks @SimpleCold! Just fixed this 😄 

This line was the culprit https://github.com/getinsomnia/insomnia/commit/a20a011074fbbb9cb07e18ba5625a138fd0b4c1c#diff-0d2ca91cc7e764d66f68e19d24db47efL78
