### ISSUE TITLE
Have separate billing email for receiving invoices

### ISSUE THREAD

**Issue by ghost** [getinsomnia/insomnia#3090]
**Is your feature request related to a problem? Please describe.**
I get frustrated when I (Insomnia team license owner) get asked every month by management to send them the Insomnia invoices for the last month(s).

**Describe the solution you'd like**
It would be great there would be the possibility to add a separate email address where the invoices (and everything else billing related) is sent to.

**Describe alternatives you've considered**
I tried as workaround to add the 'billing' email to the team license itself and promote it to team license owner. However, then one of the paid license slots, that should be available for a developer and be actively used instead, becomes unavailable for solely reason to receive emails once a month.

**Comment by nijikokun** [comment]
Hi @tozu-hb we plan to tackle this as a part of an upcoming update to Insomnia around Q2. Where you can have a billing manager who does not count towards the plan and manages the billing. Similar to how Github and other organizations operate their billing management systems.

**Comment by ghost** [comment]
That's great to hear! :smiley:

**Comment by nijikokun** [comment]
Closing in favor of #3207 (duplicate) as this users account has been deleted.

**Comment by MrSmoke** [comment]
Did this ever get implemented?
