### ISSUE TITLE
Insomnia designer EnvironmentVariables do not get updated through Test tab

### ISSUE THREAD

**Issue by findrella** [getinsomnia/insomnia#3094]
**Describe the bug**
In Insomnia Designer, I have imported all my requests and Environment variables, among these variables I have a token variable that stores the Bearer token from the authentication Response.
In Insomnia Designer in Debug mode, the variable gets updated as expected each time the request is run, however in the Test tab it does not update the variable after running the test for thge same request. 

**To Reproduce**
1. In Insomnia Designer, add an authorization/Login request  that generates an Access token
2. add a new Base environment that got populated by the Access token value each time the previous request is run

2. Run the authorizatuin request in Test tab
3. Check the base environment value
4. It did not get populated by the new value issued after the request run

**Expected behavior**
The Base environment variable value gets updated after each run of the request, not just in the debug tab of Insomnia Designer but also in Test tab

**Screenshots**
![image](https://user-images.githubusercontent.com/10885283/108191702-bdf1f480-7113-11eb-9a1e-dedb19787e67.png)

Version: Insomnia Designer 2020.5.2
Release date: 9.12.2020
OS: Windows_NT x64 10.0.18363
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0

**Comment by kreosus** [comment]
Hi @findrella Have you tried our newest release located here: https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.3. I hope that it resolves your issue and let us know if you require any further assistance and we will proceed accordingly. Have a nice day.

**Comment by one-ness** [comment]
@kreosus This issue was never resolved. The issue is still present in the most recent version of Insomnia (9.0.0). Are there any plans to actually resolve this issue?

**Comment by lcollet** [comment]
@https://github.com/Kong/insomnia/issues/2515

This issue is dated of year 2020...
Test suites cannot be implemented using tags :(
