### ISSUE TITLE
[Question] Has anyone observed Insomnia occasionally not saving changes?

### ISSUE THREAD

**Issue by Vyoam** [getinsomnia/insomnia#3104]
**What is your question?**
Sometimes, I have observed that Insomnia doesn't save the changes (particularly with respect to requests URLs). Sometimes it has happened even when the gap between the change and exit is >15sec. I've no idea what the reason might be - it could even be an issue with my system.

I'd like to hear from others on this topic.

Ideally, there could just be the standard asterisk in the title bar indicating the 'data-yet-to-be-saved' status.

**What is the context?**
N/A, I think.
Context already covered above - It seems sometimes Insomnia doesn't save changes.

**Comment by nijikokun** [comment]
Few questions:

1. What version of Insomnia are you using?
2. How many workspaces do you have?
3. How many endpoints per workspace?
4. Any bodies >100kb?

**Comment by Vyoam** [comment]
Hi @nijikokun 

1. Insomnia version: 2020.5.2 (in Windows 10)
2. Number of workspaces: 2
3. Main workspace contents: 297 requests in 31 folders
Second workspace contents: 1 request
4. No request body above >100kb. Highest body size is 30k characters (not sure which encoding is used internally)
(There are RESPONSE bodies larger than 100kb though)

I'd be grateful for any insights on improving my workflow or the Insomnia code itself.

**Comment by filfreire** [comment]
Hi @Vyoam thank you for reporting this! Are you still noticing this behavior in [latest insomnia version](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.1)?

**Comment by kreosus** [comment]
Hi @Vyoam 

As we have not heard back from you we are closing this issue out. If you require any further/future assistance please let us know and we will proceed accordingly. Have a nice day.

**Comment by Vyoam** [comment]
Yes. I haven't observed this since quite a while. This can stay closed.
