### ISSUE TITLE
Short issue title

### ISSUE THREAD

**Issue by khyveasna11111908** [getinsomnia/insomnia#3105]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khyveasna11111908** [comment]
ITT technical institute of technology and

**Comment by nijikokun** [comment]
Hey there @khyveasna11111908 I'm going to go ahead and close *this issue* but feel free to open another with more information filled out! Thanks!
