### ISSUE TITLE
It appears that Insomnia is not storing cookies properly when received on a 302

### ISSUE THREAD

**Issue by PeterGrace** [getinsomnia/insomnia#311]
## Overview
- `Insomnia Version:` _5.3.3_
- `Operating System:`  _Windows 10_
- `Summary: ` _Insomnia not storing cookies even though they appear in timeline view_

I created a request that has a Google OAuth2 bearer token.  My website issues a cookie when it translates the bearer token into the authenticated google object.   

The cookie appears in the timeline view on my 302 Found object:

```
< HTTP/1.1 302 Found
< Content-Length: 169
< Content-Type: text/html; charset=UTF-8
< Date: Thu, 15 Jun 2017 01:53:26 GMT
< Location: http://li-dev.redacted:6543/
< Server: waitress
< Set-Cookie: auth_tkt=redacted%3D!userid_type:b64unicode; Path=/
< Set-Cookie: auth_tkt=redacted%3D!userid_type:b64unicode; Domain=li-dev.redacted; Path=/
< Set-Cookie: auth_tkt=redacted%3D!userid_type:b64unicode; Domain=.li-dev.redacted; Path=/
< X-Content-Type-Options: nosniff
```
However, these cookies are not stored:

![image](https://user-images.githubusercontent.com/967365/27161957-a3e2de14-514c-11e7-91b8-102d3986b564.png)

Can someone confirm that this is an issue with Insomnia, or with how I'm trying to return the cookie?

**Comment by gschier** [comment]
Hey @PeterGrace. I can confirm that cookies within redirects are not being handled. I have just started on a PR (#312) that I will make sure is in the next release (before next week).
