### ISSUE TITLE
Redundant items created when duplicating a document

### ISSUE THREAD

**Issue by GigaPrimatus** [getinsomnia/insomnia#3112]
**Describe the bug**
When a document is duplicated in Insomnia Designer, redundant copies are created for all its relevant items such as environment, requests, UnitTest, UnitTestSuite, and Workspace directories. The extra workspace file means that no one can Import a Git Repo after having pushed up a ".insomnia" tree than includes the redundant files. Import Git Repo flow fails because there are multiple "workspace" files.

**To Reproduce**
Steps to reproduce the behaviour:
1) Produce an Insomnia Document with an API and a "Open API env" in the "Design" tab. NOTE: I had a custom ENV as well, not sure if this is necessary for the recreate.
2) Duplicate this Document from the Main Insomnia workspace with the Document Tiles
3) Open the new Document's Design Tab and see TWO "Open API env" environments.
4) Duplicate this 2nd Copy of the Document again and see that there are now 3 "Open API env" environments in the 3rd copy
4) Duplicate this 3rd Copy of the Document again and see that there are now 4 "Open API env" environments in the 4th copy

**Expected behaviour**
There should be only one set of corresponding items created for the duplicate document.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation Method: DEB]
 - App Version 2020.05

**Additional context**
Issue reported by customer and reproduced by myself.

**Comment by filfreire** [comment]
We're still able to reproduce this one when duplicating design documents (for example, using our petstore example):

![Screenshot 2022-06-23 at 14 20 12](https://user-images.githubusercontent.com/11976836/175308705-a19b81ac-c559-4c10-b6a6-86eaeee7c902.png)
![Screenshot 2022-06-23 at 14 19 48](https://user-images.githubusercontent.com/11976836/175308708-cab7e14b-8695-4360-b731-ee6a19719e08.png)

Also note, this happens with the folders on `Debug` as well, we duplicate the generated requests:
![Screenshot 2022-06-23 at 14 47 52](https://user-images.githubusercontent.com/11976836/175314875-2170fb7c-d875-4efe-8788-e387ce8e21cd.png)

**Comment by filfreire** [comment]
This is no longer reproducible in latest `develop`
