### ISSUE TITLE
Configure threshold for "Response over 5MB hidden for performance reasons" message

### ISSUE THREAD

**Issue by mxmlnglt** [getinsomnia/insomnia#3115]
Hello,

Found this old issue #412 that mentioned displaying large JSON data, linked to this commit c4933badba54fb149923d43c8e927c305d4dcce3 limiting displaying data larger than 5MB i.e. when you see this message: "Response over 5MB hidden for performance reasons".

However, for performance testing, I'd like to lower this threshold?

Is it possible?

**Comment by Warkanlock** [comment]
I modify threshold to 2MB which is a good threshold in my opinion, you can try it there but let's see what's dev team opinion here

**Comment by mxmlnglt** [comment]
er... but this is hard-coded!?

**Comment by Warkanlock** [comment]
I think I misunderstood the issue. But before was 5 on the config files and I change to 2MB. We want this reduce of threshold only happens when someone is testing?

**Comment by mxmlnglt** [comment]
I want to *configure* it, I want to put my own value, be it 1 MB or 3 MB or 300 kB.

**Comment by mxmlnglt** [comment]
I'm still looking forward to it...

**Comment by mxmlnglt** [comment]
why what is tagged with "feature-request" then marked as "wontfix" and "closed-by-team"... by a bot?! @nijikokun any idea?

**Comment by mxmlnglt** [comment]
Note: also there's a related PR pending: #3189 but that doesn't really solve the problem, as confirmed by @dimitropoulos

**Comment by dimitropoulos** [comment]
@mxmlnglt sorry about that.  we've since removed the bot that closed this issue (altogether) because of (among other reasons) how many "false positive" closures (just like this) we experienced.

Lemme know how I can be of help if you or anyone else is working on a PR for this.

**Comment by alirezaalavi87** [comment]
I would like to start working on this as my first issue, could you help getting me started?

**Comment by mxmlnglt** [comment]
In January, @alirezaalavi87 asked if he could contribute, and if someone could help him start, but I can't find his message here...

**Comment by jason-karuza-afresh** [comment]
Agreed that this would be nice

**Comment by gatzjames** [comment]
Closing as increasing the size will create other issues.

**Comment by mxmlnglt** [comment]
@gatzjames

> Closing as increasing the size will create other issues.

My original wish was to actually decrease the size... 🤔

**Comment by ThalisonCosta** [comment]
> @gatzjames
> 
> > Closing as increasing the size will create other issues.
> 
> My original wish was to actually decrease the size... 🤔

Based on this, I may implement this same logic but using 5MB as max limit. What do you think @gatzjames?
