### ISSUE TITLE
Insomnia Designer in Snap doesn't start

### ISSUE THREAD

**Issue by ImperadorSid** [getinsomnia/insomnia#3126]
**Describe the bug**
Installing the snap version of Insomnia Designer, the app doesn't open

**To Reproduce**
1. Go to 'Snap Store'
2. Type 'Insomnia Designer'
3. Click 'Install'
4. Wait for download and installation
4. Search in the app icon on the system
5. App doesn't open

**Expected behavior**
Open the app

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04 (Linux)
 - Installation Method: Snap
 - App Version 2020.5.2

**Additional context**
CPU: Ryzen 5 2600
GPU: AMD RX 580 (open source drivers)
RAM: 16 GB
Kernel: 5.8.0

**Comment by sonicyeti** [comment]
Can you give the install a try via downloading the snap package directly: https://github.com/Kong/insomnia/releases/tag/designer%402020.5.2

Head to the directory via CL and `snap install Insomnia.Designer-2020.5.2`

If you run into signature/metadata issue(s), run `snap install --dangerous Insomnia.Designer-2020.5.2`

You should then see it when viewing snap packages via GUI or `snap list`
