### ISSUE TITLE
Attempting to access file system shows gibberish. 

### ISSUE THREAD

**Issue by webdagger** [getinsomnia/insomnia#3129]
**Describe the bug**
When I try to choose a file or export insomnia, the file system simply shows boxes and everything is gibberish
**Screenshots**
[Screenshot](https://ibb.co/vcV9wr6)
**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Installation Method: [terminal]
 - App Version [2020.5.2]

**Additional context**
It was working normally, just broke all of a sudden. I can't access preferences or anything. It just shows a white screen. Attempting to export the existing workspace does not work as well. It simply saves the file Insomnia_2021-02-28 with no suffix.

**Comment by apisaint** [comment]
Looks like you've ran into an issue with snap/linux installation, and is doesn't seem to be related to Insomnia but the system font cache, at least according to previous reports. There seems to be a viable fix here https://github.com/Kong/insomnia/issues/2614#issuecomment-700711061
