### ISSUE TITLE
Insomnia does not work well with an existing repo

### ISSUE THREAD

**Issue by lchari77** [getinsomnia/insomnia#3131]
**Describe the bug**
The insomnia tool's github sync is very brittle and not well documented. After reading the documentation for Insomnia's Github sync (https://support.insomnia.rest/article/96-git-sync) we were able to get it working with a newly created GitHub repo (although this process was less than straightforward).

Our issue is it is incredibly challenging to setup Git Sync on an existing project. The majority of the projects we will be documenting in the portal already exist. We want to sync those existing repos with Insomnia. There is no best practice or documentation on how to do this.

The workaround that has been suggested is very manual and have many potential break points and just have a hacky feel:
- Create a new branch, something like "add-insomnia"
- Make an initial commit from Insomnia
- Push it to remote
- Now, we need to merge "add-insomnia" into "main" but there is no overlapping history.
- So, you need to clone via command line, then rebase "add-insomnia" onto "main"... git rebase main add-insomnia
- Then merge into main git merge add-insomnia main
- Push main git push
- For safe measure, delete your document in designer
- Clone from the dashboard

This is a request for either a better way to accomplish using Insomnia with an existing GH repo or a feature request to improve the process on the product side.

**Comment by apisaint** [comment]
It doesn't look like there is a specific request here, and it's very passive aggressive. I've left some questions to dig deeper into the issue as right now it's hard to find something specific to attach to and fix given this report. The flow given feels like a common Git flow.

> The insomnia tool's github sync is very brittle and not well documented. After reading the documentation for Insomnia's Github sync (https://support.insomnia.rest/article/96-git-sync) we were able to get it working with a newly created GitHub repo (although this process was less than straightforward).

So the documentation helped, but it's not well documented? What part of the documentation was lacking?

> This is a request for either a better way to accomplish using Insomnia with an existing GH repo.

What does this look like for you? 

> The insomnia tool's github sync is very brittle.

What parts are brittle?

> We want to sync those existing repos with Insomnia.

What is preventing you from doing so with the existing tool / sync system?

**Comment by SudoZachCampbell** [comment]
I agree with the sentiment, however I also agree this is not a constructive form of addressing issue.

Personally, I understand the challenges concerning handling merge conflicts and git history, so something like a guide to manually initialising a git repo would be helpful. I've been attempting to do it myself by using the return error messages (Creating the .insomnia directory, creating different content types to attempt to get it to pick up) but nothing has worked yet. An official guide to this or potentially a script/tool that builds a scaffold structure inside the .insomnia directory to get you started would be a life saver.

I'm attempting to move our development team over to using Git Sync but this is a major sticking point for existing repos.

**Comment by nijikokun** [comment]
This is definitely on our radar and slated for upcoming releases, in terms of both documentation and improvements to the tool itself. Right now the team is heads down on the release and we have plans to pick up some of the items below after release.

In terms of what we have heard and what we have on the backlog are as follows:

- Being able to connect to an already established repository with existing files
- Being able to sync to local file system
- Being able to point to files outside of the `.insomnia` directory
- Being able to save the `.insomnia` directory in multiple places in the same repository
- Being able to store multiple collections / documents in the same repository
- Guide to detail how to sync to a new repository
- Guide to detail how to sync to an existing repository

Hopefully this helps, I've been working on a public roadmap but have been bogged down with the latest release and haven't gotten around to finalizing it.

**Comment by xakod** [comment]
Does any opportunity to add insomnia to existing repo but not the main branch? Or another question. Does any opportunity to clone existing repo with insomnia not in the main branch? I cannot find any solution.

**Comment by nbolton** [comment]
Related: https://github.com/Kong/insomnia/issues/3810

**Comment by FreeSoftwareServers** [comment]
Maybe on day.... 4 years for github to work properly is fair.
