### ISSUE TITLE
keyboard shortcut for duplicating request also clears current line

### ISSUE THREAD

**Issue by adcurtin-arbor** [getinsomnia/insomnia#3133]
**Describe the bug**
When I press cmd+d to duplicate a request, the current line wherever the cursor is, is also deleted.

**To Reproduce**
1. Go to a request
2. Click on the url
3. press cmd+d to duplicate the request
4. the new request should be as you expect, with the proper url
5. the original request no longer has a url.

**Expected behavior**
line where the cursor is should remain unmodified.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac os 10.14.6
 - Installation Method: dmg
 - App Version Version: Insomnia Core 2020.5.2
Release date: 12/9/2020
OS: Darwin x64 18.7.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0

**Additional context**
this also occurs if the cursor is in the request body, it will delete the current line there as well.

**Comment by dimitropoulos** [comment]
just confirmed this on linux.  thanks for the report.  cc @nijikokun

**Comment by adcurtin-arbor** [comment]
this is still not working as expected

**Comment by dudeofawesome** [comment]
Seems like maybe the event is bubbling past the delete line and allowing a request duplicate action when it shouldn't be?

**Comment by endo64** [comment]
Duplicate issue is closed now, https://github.com/Kong/insomnia/issues/4974
But the problem still exists.

**Comment by filfreire** [comment]
Fix for this is available on 2022.7.0 beta versions, you can download latest iteration of beta, [2022.7.0-beta.4](https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.4)
