### ISSUE TITLE
Feature request - Hide proxy id and password when provided in http proxy field.

### ISSUE THREAD

**Issue by arafattechstyle** [getinsomnia/insomnia#3138]
**Is your feature request related to a problem? Please describe.**
As part of growing security needs and to conceal private information it is vital that we hide proxy id and password in the http proxy field. We can opt for a password-type proxy id and password text fields in this case. 

**Describe the solution you'd like**
We can come up with a custom proxy configuration approach like what Postman provides.

![image](https://user-images.githubusercontent.com/39654662/109753346-1a6f0c80-7c08-11eb-9d00-55b946904b7d.png)

**Describe alternatives you've considered**
Or just make the field show ***** once the user has typed in the text. 
![image](https://user-images.githubusercontent.com/39654662/109753407-38d50800-7c08-11eb-8170-126bc9861c08.png)

**Additional context**

**Comment by arafattechstyle** [comment]
Any thoughts yet on this one. It's annoying to see proxy id/pwd in the open text and scary during a screen sharing session.

**Comment by arafattechstyle** [comment]
What can be done to get enough attention?

**Comment by MrSnix** [comment]
Hi everyone, I can open a pull request for this if it's okay (@dimitropoulos)

This is the current implementation:

![Sep-13-2021 20-45-24](https://user-images.githubusercontent.com/20780192/133139727-683d70af-8541-4949-bbb5-f396545bcebd.gif)

**Comment by develohpanda** [comment]
@MrSnix my understanding is that the proxy fields are not password masked currently (not at a PC)? If so, yes please raise a PR! This seems like a nice addition.

**Comment by arafattechstyle** [comment]
I believe we were making good progress on this one! Can we gather some attention on the reviews please?

**Comment by develohpanda** [comment]
Thanks for the reminder, I have prompted the team to follow through with reviews :)
