### ISSUE TITLE
All environment variables prefixed with _. and existing ones changed to custom

### ISSUE THREAD

**Issue by LunaticoCR** [getinsomnia/insomnia#3139]
**Describe the bug**
I first noticed this while trying to change a variable on a request, I clicked on the variable I wanted to change to open the Edit Variable dialog and noticed that my variable was set to ```Custom```:
![image](https://user-images.githubusercontent.com/2124383/109795316-b3088b00-7c0e-11eb-84f5-f2e60a65eebd.png)
Clicking on the variable dropdown shows all my variables are now prefixed with ```_.```:
![image](https://user-images.githubusercontent.com/2124383/109795459-db908500-7c0e-11eb-97fd-fe6042a1e4b8.png)
Looking at the Manage Environments window the variables look fine there:
![image](https://user-images.githubusercontent.com/2124383/109795696-27432e80-7c0f-11eb-8ad7-be9136e1e319.png)

**To Reproduce**
1. Close Insomnia
2. Move the application data to start with a fresh instance of insomnia (I'm on macOS so I renamed ```/Users/<user>/Library/Application Support/Insomnia```)
3. Open Insomnia
4. Open the Manage Environments window
5. Add new variable ```"var1": "abc"``` and close this window
6. Create a new request and try the use the variable in any of the fields by pressing ctrl+space
7. See how the variable listed is ```_.var1```:
![image](https://user-images.githubusercontent.com/2124383/109796445-147d2980-7c10-11eb-8f92-02e8bd5b048a.png)

**Expected behavior**
This was not happening before, there's no reason for adding the ```_.``` prefix but what's worst is that all my existing variables are now changed to Custom.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Installation Method: DMG package from the website (a very long time ago)
 - App Version: Insomnia Core 2020.5.2

**Additional context**
This wasn't happening before and I haven't really changed much apart from normal app usage. This is a fairly recent regression.

**Comment by nijikokun** [comment]
Hi @LunaticoCR this is an intentional change that came within 2020.5, to give users the ability to use [special characters such as hyphens](https://github.com/Kong/insomnia/issues/2601) in environment variables. The custom change is a part of the backwards compat code.

**Comment by LunaticoCR** [comment]
Thanks for letting me know @nijikokun . I see that @develohpanda  chose not to hide the _. from the UI render, I don't get why hiding it would be misleading and I think if it had been hidden you wouldn't have received 3 bug reports for this (so far) as it would have made the change completely transparent to the end user. Anyway, now I know this was intentional and I will just get used to seen the _. in my variables along with the old variables showing as custom.
