### ISSUE TITLE
Feature request to introduce customizable wrapper for the output of template tag's `run()` method 

### ISSUE THREAD

**Issue by servernoj** [getinsomnia/insomnia#3141]
## What is proposed for improvement
In situations when template tag's `run()` method returns a non-string value, e.g. an object, it is displayed in the preview box as `[object Object]`.

## Preferred behavior
To be able to separate "display" (or preview) value from the actual returned one. 

## Proposed outcome
To add a user-definable wrapper over returned result for UI preview purposes. In simplest (default) case it would be `x => x`, in case presented above it would be `x => JSON.stringify(x)`.

**Comment by nijikokun** [comment]
This is a good candidate for the Plugin API
