### ISSUE TITLE
How to build the application

### ISSUE THREAD

**Issue by mklemm2** [getinsomnia/insomnia#3147]
**What is your question?**
How can I build an executable from the source code on Windows.

**What is the context?**
What I tried:

```
npm run bootstrap
npm run app-start
```

App starts, everything works. Then I changed some code, ran it again, still worked. Now I need to build an executable to distribute it among my team (until you implemented a feature request of mine, actually ;-) )

So after studying the package.js script, I tried:

```
set BUILD_TARGETS=portable && npm run app-package
```

But it always stops with `[build] Skipping build for ref ""`

Please add instructions on howto build the actual executable to the docs.

**Comment by develohpanda** [comment]
> until you implemented a feature request of mine

Hi @mklemm2, it's awesome that you've got a fix for (I presume) #3117! Would you be interested in opening a PR with that change into this repository? I'm sure we can look to distribute it through the main channels.

Also, you'll be happy to note that we have just published an official [portable](https://github.com/Kong/insomnia/releases/tag/core%402021.1.0) version for Windows as well 😄

**Comment by mklemm2** [comment]
Sorry, so far I have only changed the "Authorization" header to my custom "X-Something" header, I have not made it configurable or anything. JS is not my language and frontend is not my domain, so it might take a while until I have leveled up enough to present a proper pull request.

So, in the meantime, it would be really great to be able to just build Insomnia into an .exe.

**Comment by develohpanda** [comment]
Ah, no worries! The build and packaging scripts fetch information from a git ref (tag) but when packaging for smoke tests we bypass that. On Windows, if you run `npm run app-package:smoke` from the root directory you should have an executable in the `packages/insomnia-app/dist` folder. If that doesn't work for you I can explore another option, let me know how you get on!

**Comment by mklemm2** [comment]
Thanks, works perfectly! Now I'll dig into the rest of the code to make it actually configurable. When I'm done, I'll create a pull request.

**Comment by develohpanda** [comment]
Awesome 😄 I will close this issue as resolved. Feel free to open a new one should you have any more questions!
