### ISSUE TITLE
[Question] Hot to remove "Dashboard bar"

### ISSUE THREAD

**Issue by kovsharov** [getinsomnia/insomnia#3149]
**What is your question?**
How can I remove this "Dashboard bar" on top along with the login and setting icon? 
It takes too much space and I don't use it at all.
Version: Insomnia 2021.1.0

**Comment by nijikokun** [comment]
Hi @AleksandrKovshariov, currently there is no way to remove the header from the dashboard, in the future this may change but we have no immediate plans for this functionality.

**Comment by diegocastro** [comment]
I ask you, please, redesign it or let us hide it. It takes too much precious vertical space for only 3 action buttons.
The old layout was perfect.

**Comment by rstarkov** [comment]
Press Ctrl+Alt+I. Pick the Dashboard bar. Change element style to `display: none`. You're good until next restart.
