### ISSUE TITLE
Special characters in JSON response rendered escaped in visual preview mode

### ISSUE THREAD

**Issue by rvbhute** [getinsomnia/insomnia#315]
## Overview
- `Insomnia Version:` 5.3.6
- `Operating System:` Linux Mint 18.1 (Ubuntu 16.04.2)
- `Summary: ` Special characters in JSON response rendered escaped in visual preview mode.

## How To Reproduce
1. Test an endpoint that returns JSON with escaped characters, in my case, a URL
2. The forward slash (/) of the URL are escaped by backslash (\\).
3. This backslash is visible in the visual preview mode.
![screenshot from 2017-06-16 10-07-31](https://user-images.githubusercontent.com/202365/27212408-7e40a8d0-527d-11e7-9081-cfd8ebf583ed.png)
4. When you drill down into the JSON response ($.store.books...), the output is rendered without backslash. This, I think, is the desired way to render in visual preview mode even without drilling down.
![screenshot from 2017-06-16 10-07-11](https://user-images.githubusercontent.com/202365/27212406-7e12c3d4-527d-11e7-8914-7b2112c31c19.png)
5. This also happens in the source code mode. In fact, both visual preview and source code mode display output in the same way.

**Comment by gschier** [comment]
Thanks for the beautiful issue report @rvbhute!

In the case of an HTTP client, I prefer to show as close to the original server output as possible, especially in the case of escaped quotation marks, which would break the syntax highlighting algorithm if the `\`s were removed.

```json
{
  "sentence": "Karen said \"hi.\""
}
```

The JSONPath/XPath filtering requires the output to be parsed into a JS object, which is where the unescaping is being done. This could probably be prevented by double escaping the escape characters before hand. 

I think it would definitely be good to make it consistent across the board.

**Comment by rvbhute** [comment]
Thanks, I understood the difference now. In the first case, the output is a faithful display of the response, while in the drill-down, it is an interpreted JS object being displayed.

Entering `$` or `$.*` in the drill-down serves to "clean up" the output when one needs to see or copy pretty URLs.

**Comment by rainzhao2000** [comment]
I'm trying to use the Response - reference values from other requests, function template tag. I wish specifying a JSONPath in the tag editor could give me the raw escaped string since I'm using this string again to test another request. E.g my problem is that the newline character is being rendered and messing up the request.
```
"hello \n world"
```
becomes
```
"hello 
 world"
```
so the actual request body fails to be valid json
```
{
    "text": "hello 
 world"
}
```

**Comment by DylanDelobel** [comment]
> I ran into this today. I would say displaying the escape characters is counter intuitive. Specifically it is different to how the chrome console would output the same structure. It also prevents you from copy pasting or clicking on urls.

I totally agree with this, what about a 4th preview mode called "escaped" or "formatted" ?
Or a small plugins?

**Comment by curtinaz** [comment]
Five years later and that problem still exists. Is there any palliative?

**Comment by Harrylepap** [comment]
Has the project been abandoned because this problem still persists?

**Comment by nbarshain** [comment]
[rvbhute](https://github.com/rvbhute)'s solution of the $ is a game changer. Totally solved the problem

**Comment by spencerdcarlson** [comment]
> I'm trying to use the Response - reference values from other requests, function template tag. I wish specifying a JSONPath in the tag editor could give me the raw escaped string since I'm using this string again to test another request. E.g my problem is that the newline character is being rendered and messing up the request.
> 
> ```
> "hello \n world"
> ```
> 
> becomes
> 
> ```
> "hello 
>  world"
> ```
> 
> so the actual request body fails to be valid json
> 
> ```
> {
>     "text": "hello 
>  world"
> }
> ```

I am running into this same problem. Is there a way to references a _Response => Body Attribute_ without processing the escape characters (raw value with `\n`s preserved as is)? -- Seems like there should be a setting in the Filter Settings to enable/disable special character evaluation. 

<img width="735" alt="Screen Shot 2023-01-06 at 12 30 36 PM" src="https://user-images.githubusercontent.com/1206303/211085812-f8e886ac-d230-444d-8848-46a5aa722352.png">



Maybe this should be opened as a separate bug given that this original issues seem to be related to the opposite scenario where the user wants the special characters to be interpreted.

**Comment by mrjimhubbard** [comment]
I really think that Visual Preview should not have escaped characters since doing so essentially replicates Source's output. 

Could we....
- Make Visual Preview "pretty" by removing the escape characters
- or...make the $ sticky in the filter
- or...Have another view like "Pretty JSON"
- or...(and this is my favorite) just add the options in Preferences and let people use Insomnia the way _they_ want to use it?

Until this gets fixed I think I'll just use https://hoppscotch.io/ - it's free and it shows the data the "pretty" way.

**Comment by LunaticoCR** [comment]
Not that it matters but I'm also hit byt this issue. New lists are lost which makes the next request fail.
