### ISSUE TITLE
preference is not saving [2021.1.0]

### ISSUE THREAD

**Issue by thewayur** [getinsomnia/insomnia#3151]
**Describe the bug**
my preference is not saving after using portable(was using previous installed version).
max history and chunk size using null values all the time and not saving histories.

I have tried to delete all local/roam data 3 times for installed version and portable version.
now using older version 2020.5.5.2, which is working fine

**Comment by develohpanda** [comment]
Thanks for reporting this, we'll look to patch ASAP 🙏🏽 this is a regression and not something to do with your data.

**Comment by nijikokun** [comment]
This was fixed in the latest stable release 2021.1.1 🙏 Closing.
