### ISSUE TITLE
Make the Send button more visually prominent

### ISSUE THREAD

**Issue by vivaladan** [getinsomnia/insomnia#3152]
**Is your feature request related to a problem? Please describe.**
The new layout and design (both light and dark mode) in 2021.1.0 makes it harder to quickly locate the 'Send' button on a request. I believe the addition of the new sync button at the top right as well as the extra header space and theme changes has made the 'Send' button merge into the background more. At least for my workflow, the 'Send' button is what I click on the most, so it should more more prominent than everything else.

**Describe the solution you'd like**
I'd like to see the Send button stand out a little more from it's surrounding elements, either by making it's appearance more striking, or additionally toning down some of the surrounding elements slightly.

**Describe alternatives you've considered**
Muscle memory might eventually counter these changes for me, but it's sure to be frustrating to newer users. The design language really needs to lend itself to what's most important.

**Comment by dimitropoulos** [comment]
This is great feedback! Thanks! I definitely understand what you're talkin' about.

**Comment by thewayur** [comment]
yes please, make it more noticeable...

**Comment by dimitropoulos** [comment]
cc: @erickrico
