### ISSUE TITLE
System theme synchronization

### ISSUE THREAD

**Issue by jakubbegera** [getinsomnia/insomnia#3154]
I really enjoying using Insomnia, there is just one thing that can be improved - theme synchronization with the system theme (light/dark). I'm used to switching whole my computer (mac) to light (beach) and dark (office) mode just by "one-click", just insomnia needs to be switched manually in settings.

**Comment by develohpanda** [comment]
Thanks for the feature request! There's already an awesome PR for this, almost ready to merge!
