### ISSUE TITLE
Request timing details

### ISSUE THREAD

**Issue by Zerotask** [getinsomnia/insomnia#3156]
Like in Postman or in the browser dev tools, I'd like to see the request timing details when hovering the response time.
![image](https://user-images.githubusercontent.com/20150243/110205076-b8680e80-7e76-11eb-8018-5de6ca74a12a.png)

**Comment by dimitropoulos** [comment]
I'd love this.  thanks for the suggestion - will definitely keep this in mind.  I use something similar all the time - a feature of wallaby that tells me this kind of information for test runs.

**Comment by Zerotask** [comment]
Any plans to add this feature?
