### ISSUE TITLE
[Bug] Clickable links not including query parameters

### ISSUE THREAD

**Issue by 8888444422** [getinsomnia/insomnia#316]
## How To Reproduce

1. Create new request
2. Perform a request which returns a response with a link in it
3. You can see the link query params aren't properly parsed

**Comment by gschier** [comment]
Can you please update to the latest version and see if the issue persists?

**Comment by gschier** [comment]
Also, if you _can_ reproduce it on the latest version, can you provide a sample response to help me reproduce the issue?

**Comment by gschier** [comment]
Closing this for now since I can't reproduce

![image](https://user-images.githubusercontent.com/587576/27243720-15bc7652-5298-11e7-83bb-2080b638391a.png)
