### ISSUE TITLE
Insomnia - forcing requests directly to HTTP2 instead of upgrade from HTTP 1.1

### ISSUE THREAD

**Issue by cris-725-500** [getinsomnia/insomnia#3163]
Hi, is there any option to force HTTP2 directly without upgrading from HTTP 1.1?  I am talking about an option similar to the curl option --http2-prior-knowledge...

I am running:
Version: Insomnia 2021.1.0
Release date: 3/4/2021
OS: Windows_NT x64 6.1.7601
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0

Thanks!

**Comment by DamianoPellegrini** [comment]
You can set it under `Preferences` > `General `> `Preferred HTTP version`. Insomnia will try to use the preferred version or the latest available.

Hope this will help!

**Comment by cris-725-500** [comment]
Yes, I have set HTTP/2 preferred in settings. When checking with Wireshark what happens is that first HTTP 1.1 is requested (Request Version: HTTP/1.1) with the "Connection: Upgrade, HTTP2-Settings" and "Upgrade: h2c".  What is needed is direct initiation of the HTTP2 connection (with appropriate HTTP2 header structure).

**Comment by dimitropoulos** [comment]
@DMarby do you happen to know if `http2-prior-knowledge` is something we have easy access to set via `node-libcurl`?
