### ISSUE TITLE
Re-import data from URL automatically

### ISSUE THREAD

**Issue by nur557** [getinsomnia/insomnia#3167]
Right now there isn't an option to keep data in sync if a user imports data from URL. This would be very beneficial for teams that won't/can't use Git sync so that we don't have to re-import data manually every time the backend team changes the spec. It could be implemented as a refetch of the URL when the user goes inside the document in question from the Dashboard.

**Comment by nijikokun** [comment]
This definitely isn't the first time it's been raised, but I do have some concerns as we move into maturing the sync capabilities / collaborative parts of the application with regards to designs. 

Would a button to re-import suffice, similar to the schema fetch button for GraphQL?

Side note, this might even be a good candidate for a [plugin](https://support.insomnia.rest/article/173-plugins).

**Comment by nur557** [comment]
> Would a button to re-import suffice, similar to the schema fetch button for GraphQL?

I'm not sure where this button is located but anyway, that would kinda defeat the purpose as the user would have to engage and data wouldn't be synced automatically.
