### ISSUE TITLE
Some preferences are not working.

### ISSUE THREAD

**Issue by Wim-De-Clercq** [getinsomnia/insomnia#3176]
**Describe the bug**
After changing some preferences, the values are not saved or used.
Reopening the preferences windows just shows blank fields.

**To Reproduce**
1. Open the preferences (cogwheel top right)
2. General tab, scroll down to "Request / Response" Section.
3. Edit one of the number fields: Maximum redirects, request timeout, ...
4. Close preferences

**Expected behavior**
The new number settings to be saved and working.

**Screenshots**
This shows after closing and re-opening preferences (Also when restarting the application). The settings are saved as blanks.
![image](https://user-images.githubusercontent.com/4599667/110609643-b6ab8d00-818d-11eb-9cf1-0f38fd96608a.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.10
 - Installation Method: snap
 - App Version v2021.1.0

**Comment by develohpanda** [comment]
Thanks for raising this! A patch release is coming today which fixes this issue 😊
