### ISSUE TITLE
Allow hiding window's the menu bar

### ISSUE THREAD

**Issue by carndog** [getinsomnia/insomnia#3177]
Please could there be a way to turn off the Dashboard at the top displaying the cog?

I can turn off the menu bar but not that area which is new and taking up valuable space. My eyes are always on the response at the right, which is now reduced in size
![thing](https://user-images.githubusercontent.com/7319736/110635906-8a9b0680-81a3-11eb-982a-2a9c40a2c670.PNG)
.

I am surprised at how annoying I am finding it. I just need a tickbox to hide it or something.

**Comment by dimitropoulos** [comment]
@carndog we have another ticket https://github.com/Kong/insomnia/issues/3150 that may make it dark.  I'm curious, if it were dark (and therefore not so harsh on the eyes) would that also solve your core ux-problem?

**Comment by carndog** [comment]
Hi

No, it is the space that is the problem

Thanks

**Comment by dimitropoulos** [comment]
cool cool, thanks for clarifying.

Are you familiar with how vscode handles this?  Are you satisfied with vscode's implementation of this same feature https://code.visualstudio.com/docs/getstarted/userinterface#_hide-the-menu-bar-windows-linux.

It appears to only be for windows and linux, so I'm not sure if whatever limitation they ran into we would also hit (you're on windows, anyway, it looks like).

**Comment by carndog** [comment]
I don’t use vs code but if the implementation involves hiding then I a,
satisfied. Hopefully this ui element is not built in and can be hidden even
if resorting to windows api calls. Yes am on windows

**Comment by dimitropoulos** [comment]
(I updated the title as to not make it semantically collide with some other issues that are open regarding some UI within the app)
