### ISSUE TITLE
New GUI is unusable - switching workspace nightmare

### ISSUE THREAD

**Issue by squalou** [getinsomnia/insomnia#3178]
**Describe the bug**

since version 2021.1.0, the workspace presentation and switching method has made it completely unusable.

- click on "dashboard"
- see a bunch of "tiles" instead of a proper list
- sidenote : you can try to use this without a mouse, congrats if you manage
- click on filter
- fill in a name
- click on workspace

3 clicks, 3 full UI reload

Who the hell can *want* that ? 

**Expected behavior**
Once upon a time : click on workspace name, fill in some keywords : the list of available workspaces displayed and autofilter.

Switching as done in less than 2 seconds and one click.

Please bring this back, or at least add back a "quick search and switch" method if you feel like somebody wants to look at your dashboard view

Seriously, did someone actually **used** the new UI and said : ok, that's great ? 

**Screenshots**

This is the "new" dashboard view.
What the hell is that nightmare ?
Why "cards" ?
Why a dedicated view ?
Why so much lost space and a **scrollbar** ? 

![insomnia-ws](https://user-images.githubusercontent.com/4623644/110768985-0060aa00-8258-11eb-8d69-d42fa0dabfb7.png)

**Desktop (please complete the following information):**
 - OS: [Arch Linux]
 - Installation Method: aur package
 - App Version [2021.1.0]

**Comment by squalou** [comment]
for those not knowing previous UX : 

click on current workspace on top, start typing, enter, done.

You'll also notice that less space is lost for nothing at the top.

Seriously guys .....

![insomnia-better](https://user-images.githubusercontent.com/4623644/110770652-dad4a000-8259-11eb-84e2-cae79e137038.png)

**Comment by abdelhak-ajbouni** [comment]
@squalou i was wondering why they did that too
I also get `failed to execute 'removechild' on 'node': the node to be removed is not a child of this node.` some times when switching between workspaces, I couldn't figure out when exactly it happens tho.

**Comment by symbiat** [comment]
In our case, when creating snapshots, we have a giant flat list which becomes a major problem when you have multiple requests with the same name in different folders. Also hard to find stuff if the list is too long - maybe add a filter and/or paths ? 🤷🏽‍♂️

**Comment by nijikokun** [comment]
Welcome 👋 

Thank you for the feedback, we definitely appreciate it. The dashboard as it is right now definitely isn't perfect but it has to do with adding support for larger organizations, the current dashboard is definitely an MVP and we want to improve it.

To that, the future improvements we are looking at are:

- adding the ability to group documents into folders (#3182)
- sorting options (#3181)
- pin items (#3148)
- quick switching similar to VSCode/Slack (#3180) 
- improved keyboard support (#3183)

> In our case, when creating snapshots, we have a giant flat list which becomes a major problem when you have multiple requests with the same name in different folders. Also hard to find stuff if the list is too long - maybe add a filter and/or paths ?

This seems like a separate ask (snapshots), perhaps a new issue?

**Comment by squalou** [comment]
Dashboard may improve in the future, that's great and fine. 
*but* that won't explain why you would *remove* the existing fast-switching ability.
(we probably don't have the same definition of 'MVP' but crippling an existing functionality isn't part of it)

My ask is simple enough : "as a user, from current workspace, I want to switch fast to another workspace".

More specifically, what I would like :
- from an active workspace : have a keyboard shortcut to access workspace switcher (would be a bonus improvement)
- display existing workspaces *over* existing screen, dont leave current workspace ! (allow users to make mistakes)
- type a name filters the list
- use arrow to navigate remaining ones
- enter *do* the switch

You speak about "quick switching similar to VSCode/Slack (#3181)", but frankly : give me ONE reason why one would start its journey in a global dashboard to begin with ? even more when wanting to switch, why having to actually *leave* what your're doing first ?
VSCode does things right with a keyboard commanded interface, using Ctrl P / Ctrl Shift P  ... from where you're already working. 
Great, inspire yourself from that.

BTW I really wonder what "bigger organizations" you refer to. As part of a medium (paying) one, maybe you should consider asking them, or better : test usability with them on a beta version.

**Comment by nijikokun** [comment]
Not just the dashboard but other areas as well.

> More specifically, what I would like
> * from an active workspace : have a keyboard shortcut to access workspace switcher (would be a bonus improvement)
> * display existing workspaces _over_ existing screen, dont leave current workspace ! (allow users to make mistakes)

Ah, I see what happened, I linked the wrong issue in my original post, see #3180 as it would solve this direct ask!





> BTW I really wonder what "bigger organizations" you refer to. As part of a medium (paying) one, maybe you should consider asking them, or better : test usability with them on a beta version.

We currently do this with a few organizations, if you'd like to be a part of them please send an email to support@insomnia.rest and we can definitely book a session.

**Comment by squalou** [comment]
#3180 looks indeed promising.

I'll stick to version 2020.5 until it's available for testing.

(and will get in touch with my company's official contact with you to see what can be done)

thanks for the answers anyway

**Comment by nijikokun** [comment]
> (and will get in touch with my company's official contact with you to see what can be done)

Looking forward to setting up some time with you!

I'm going to go ahead and close this one in favor of the ones listed in this thread, if there is anything missed please let me know and I can create new ones or re-open 🤗

**Comment by ic3guy** [comment]
Incredibly horrible change. I downgraded to 2020.5 too. Not being able to switch workspaces from a dropdown menu, why would you do that?
