### ISSUE TITLE
[Feature Request] Custom OAuth 2.0 Grant Types

### ISSUE THREAD

**Issue by XaveScor** [getinsomnia/insomnia#318]
Add custom grant_types support to OAuth2.0 tab pls

**Comment by gschier** [comment]
Hi @XaveScor. I'm not very familiar with custom grant types. Can you provide some more information about what they are and what the feature might need to do to support it?

**Comment by gschier** [comment]
Depending on the complexity, this might be a better fit for a custom plugin when the plugin framework is completed (#51).

**Comment by gschier** [comment]
Closing this one for now and will consider re-opening if demand increases. Upvote this comment to vote!

**Comment by bruuff** [comment]
Example where custom grant type is needed: newsletter2go API (https://docs.newsletter2go.com/?version=latest)
->"Also we require you to send along the grant_type https://nl2go.com/jwt."
