### ISSUE TITLE
Add ability to filter modified objects in Create Snapshot dialog

### ISSUE THREAD

**Issue by symbiat** [getinsomnia/insomnia#3184]
Very difficult to use the picker when creating a snapshot since its just a flat list:
- requests with the same in different folders just appear as duplicates with no way to know what they refer to
- list can get very long so lots of scrolling to find an item
- also no way to search to find an item

Need something equivalent to `git status` where at least you have full paths so you can clearly see hierarchy.

Maybe have a filter and / or show paths ? 🤷🏽‍♂️

**Comment by nijikokun** [comment]
Looks like there is already an open issue for improving the display #2597, changing this to be a request for the ability to filter. That way we can reduce scope and handle each ask individually 🤗
