### ISSUE TITLE
[Bug] Using a response body in environment settings gives an "Unexpected token % in JSON" error

### ISSUE THREAD

**Issue by Fritzbraun** [getinsomnia/insomnia#319]
## Overview
- `Insomnia Version:` _5.3.6_
- `Operating System:`  _Win10 Home (Creators Update)_
- `Summary: ` _If I use the new response parsing feature directly within a request it all works perfectly, but if I transpose the same response into the environment settings then it doesn't work. At the bottom of the page I get the error "Unexpected error % in JSON at position 13"_

## How To Reproduce
1. Create new auth request
2. Perform request and auth successfully
3. Go into environment settings
4. Create new variable
5. Assign it to a response body, use JSONPath and confirm that the Live Preview finds the correct field
6. Select OK
7. Observer error at bottom of page and be unable to select "OK" or any other sub-environments

## Other Notes

_Thanks for adding this feature, it's going to make my life that little bit more pleasant as I'll no longer have to keep copying my JWT back and forth from auth responses_

**Comment by gschier** [comment]
Make sure you have quotes around your tag.

![image](https://user-images.githubusercontent.com/587576/27394918-dd215f82-5662-11e7-860a-a85c112ea6d3.png)

Under the hood, the tag is saved as `{% response 'body', 'request_id, '$.json.path.query' %}` so, if there are no quotes, the JSON becomes invalid.

**Comment by Fritzbraun** [comment]
Well, now I feel embarrassed. You're quite right, it was a quoting issue. Thanks for your help.

**Comment by gschier** [comment]
Don't be embarrassed @Fritzbraun! The error doesn't make it clear that that's what the issue is.

Glad that helped and you're welcome 😸

**Comment by gschier** [comment]
Hey @zkghost. Did you end up figuring it out? I'd be happy to answer any questions you have.

There is a brief bit of documentation [here](https://support.insomnia.rest/article/43-chaining-requests) but it could definitely use more examples. Did you find that page?

**Comment by zkghost** [comment]
@gschier I did end up finding it out; I think initially I was using the Nunjucks templates wrong. 
Think my problem was that I was searching for things around "setting variables" instead of chaining requests. 

That page does look pretty good though, I think it was just my bad for not searching for the right thing 👍

**Comment by gschier** [comment]
Right. Perhaps I should also make a page for dynamically setting variables that explains that chaining should be used.

Definitely not your fault. The product should always serve the user 🤵

**Comment by zkghost** [comment]
:) Wouldn't hurt.

Thanks also! Used Postman for months and your product is a refreshing alternative :) really like the way variables are integrated. Keep up the good stuff! And the great service :D!

**Comment by gschier** [comment]
You're welcome! I always love hearing positive feedback 😄

**Comment by 4n70w4** [comment]
@gschier Could you write a user-friendly message? And it is not clear what to do.

> Unexpected token % in JSON

**Comment by danielo515** [comment]
what happens when the thing I want to send is actually an object and not a JSON string?

**Comment by gschier** [comment]
@danielo515 this problem doesn't exist when using a variable in a JSON request. The syntax checker will complain but the request will still send
