### ISSUE TITLE
Preview mode plugin

### ISSUE THREAD

**Issue by tpluscode** [getinsomnia/insomnia#3190]
**Is it possible to implement a custom preview mode?**

I would like to publish a plugin with custom preview rendering for RDF responses.

Is it possible to add custom selection to the "Preview Mode" dropdown?

**Comment by develohpanda** [comment]
Interesting! This might be doable 👀 we are slowly trying to expand on UI plugin capabilities. Currently no plugin API exists for response preview modes, but it can certainly be added. I'm thinking an API like the following might work?

```js
{
  label: string,
  canPreview: (responseMimeType: string) => boolean, // check whether the mime type is supported by your plugin/viewer
  element: (context: Object) => HTMLElement | Promise<HTMLElement>, // render a component and return a DOM node (needs some documentation)
}
```

**Comment by tpluscode** [comment]
Hey! Thanks for coming back to me :)

**canPreview**

I think I would make the `canPreview` optional, for more sophisticated checks, if necessary. How about the default implementation worked like content negotiation?

```js
{
  // named after the request header
  accept: [
    'text/turtle',
    'application/ld+json',
    'application/n-quads',
    // more
    // could also accept ranges and priorities
  ]
}
```

This could be implemented using [`MediumType#sort`](https://github.com/moll/js-medium-type/blob/master/doc/API.md#mediumtypesorttypes-) + [`MediumType#match`](https://github.com/moll/js-medium-type/blob/master/doc/API.md#mediumtypeprototypematchtype-)

```js
const types = plugin.accept.map(type => new MediumType(type))
const canPreview = MediumType.sort(types).some(type => type.match(responseType))
```

**element**

This can work, or alternatively, the caller could provide a container for the plugin to render inside. Would make it easier for some rendering libs (I intend `lit-html`)

```ts
import { html, render } from 'lit-html'

{
  async render(root: HTMLElement, context: unknown): Promise<void> {
    render(html`<my-element>`, root)
  }
}
```
