### ISSUE TITLE
Environmental Variables No Longer Supported in Basic Auth Password Field

### ISSUE THREAD

**Issue by michaelhofrichter** [getinsomnia/insomnia#3192]
**Describe the bug**
After a recent update, my environmental variables for the password field became replaced with asterisks. Instead of being able to hit ctrl+space and populate the password with a variable from my local environment, I instead get the option instead saved as text instead of code for the variable.

**To Reproduce**
1. Go to My environment and create an environment that has variables for username/password. 
2. Create a new request and set the authentication to basic.
3. set the basic username to the environmental variable for username. 
4. Try to set the password to the environmental variable for password and note that it doesn't work. 
5. Add the environmental variable for password to the username field and then copy it to the password field. 
6. Unhide the password and see something like -- `{% base64 'decode', 'normal', password %}`

**Expected behavior**
I expected environmental variables to be available in the password field. Being able to ctrl+space was so helpful. This used to be supported

**Screenshots**
![image](https://user-images.githubusercontent.com/45667758/111102558-611f0980-851a-11eb-8b1f-b27b55124446.png)
![image](https://user-images.githubusercontent.com/45667758/111102569-6714ea80-851a-11eb-8e39-5407cea26128.png)
![image](https://user-images.githubusercontent.com/45667758/111102586-7431d980-851a-11eb-8a40-528f65a43c4f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2
 - Installation Method: Installer 
 - App Version 2021.1.1

**Additional context**

**Comment by tharun208** [comment]
@develohpanda I like to work on this

**Comment by develohpanda** [comment]
Hi @tharun208, we're looking to get this through ASAP because it's higher priority so I've raised a PR to fix it. Thank you for the offer though, I really appreciate it!
