### ISSUE TITLE
app-package would fail on npm v7

### ISSUE THREAD

**Issue by HarukaMa** [getinsomnia/insomnia#3202]
**Describe the bug**
When using NPM v7, `app-package` would fail as one of the dependences of insomnia is way too outdated:

https://github.com/garycourt/JSV/blob/e539d4d9e03785bd37159ebf9f7169d9d3ae85ae/package.json#L29

In its `package.json`, `dependencies` is an array which should be an object or null. NPM v7 is becoming more strict and this dependency would break the packaging routine.

**To Reproduce**
1. Run `npm run app-package:smoke` using NPM v7

**Expected behavior**
Packaging should success.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: -
 - Installation Method: -
 - App Version -

**Additional context**
Not really a "bug report", but well it throws error when running one of the scripts. Also future-proof surely is a good thing.

**Comment by dimitropoulos** [comment]
I have a spike to look into using yarn: https://github.com/dimitropoulos/insomnia/tree/yarn if you wanna take a look.  Until that happens (or, if it is decided (which I doubt it will be) that it will never happen and we'll stay with npm) I don't think we're going to be looking into this.

It looks like https://github.com/garycourt/JSV/issues/94 already exists, but, alas, is not going to be fixed as the project appears to have been long-since deserted 9 years ago.

**Comment by dimitropoulos** [comment]
it appears that this comes from `jsonlint` which was also abandoned 8 or so years ago.  there is a more active fork we may be able to switch to: https://github.com/zaach/jsonlint/issues/118

**Comment by ssleptsov** [comment]
@dimitropoulos have pushed a fixed version of `jsonlint`, same as `JSV` package too.

`JSV`

- Package - https://www.npmjs.com/package/jsv-fixed
- Repo - https://github.com/ssleptsov/JSV - only fixes for `dependencies` in `package.json`

`JSON Lint`

- Package  - https://www.npmjs.com/package/jsonlint-mod-fixed
- Repo - https://github.com/ssleptsov/jsonlint-mod - forked from one of the most active forks before and only have fixed `JSV` dependency

**Comment by dimitropoulos** [comment]
thanks! looks like as of https://github.com/Kong/insomnia/commit/1f05683fad1078741013e6024e58eacdb1b12eee we're using an updated version now: so unless I misunderstood something: this can be closed.
