### ISSUE TITLE
Window corners are not rounded

### ISSUE THREAD

**Issue by mengoreo** [getinsomnia/insomnia#3204]
**Describe the bug**
Application window corners are not rounded like any other apps.

**To Reproduce**
Just open the app, and check out the window corners on Big Sur.

**Expected behavior**
Window corners are rounded like other apps.

**Screenshots**
![image](https://user-images.githubusercontent.com/23724267/111572239-30252a00-87e3-11eb-9c64-d8148bdc0804.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Installation Method: dmg
 - App Version:
 
```Version: Insomnia 2021.1.1
Release date: 3/10/2021
OS: Darwin x64 20.3.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Comment by develohpanda** [comment]
Thank you for taking the time to report this! 😄 It was resolved recently by https://github.com/Kong/insomnia/pull/3000 and will be published with the next release (likely late March). 🎉
