### ISSUE TITLE
Unable to load app -- tries to automatically reload too-large call

### ISSUE THREAD

**Issue by LairBob** [getinsomnia/insomnia#321]
## Overview
- `Insomnia Version:` _(e.g. 5..3.3)_
- `Operating System:`  _(e.g. Windows 10 Pro - 15063.413)_
- `Summary: ` _Insomnia crashed when I inadvertently triggered a call that returned a huge dataset. Now the app apparently tries to refresh the same call every time I restart the app, and locks up every time I launch it._

## How To Reproduce
As far as I can tell, this happened because I inadvertently called a GET that returned a JSON body with 200K+ records:
1. Create a request that returns a very large body response (my call is to a private db, unfortunately)
2. Wait until Windows displays the "'Insomnia' has become unresponsive. Wait or Reload'" dialog
3. Choose 'Reload'
4. Relaunch the app

## Other Notes

I've also tried uninstalling and re-installing the app, but it seems that the environment settings aren't purged through that process, so even after re-installing, my old workspace displays, and the app locks up. Sometime, there's a small window of time where I can try and pull down the "Workspaces" menu to try and switch workspaces, but I never seem to have enough time to actually get that to happen.

**Comment by gschier** [comment]
@LairBob see #282

**Comment by LairBob** [comment]
That worked fine for me -- thanks so much.
