### ISSUE TITLE
Cannot scroll unit tests when greater than window size

### ISSUE THREAD

**Issue by jswitzer-lulus** [getinsomnia/insomnia#3216]
**Describe the bug**
When adding a large number of unit tests (20+ depending on window size) to a test suite, the unit test list does not scroll. If you run a test suite with a large number of tests then the test results do not scroll either.

**To Reproduce**
1. Go to a design document with requests
2. Click on the Test tab
3. Create a New Test Suite
4. Add Tests until the new tests run off the bottom of the window
5. Try to access the last test
6. Run the tests
7. Try to see all the test results

**Expected behavior**
Once the list of unit tests is longer then can be displayed on screen it should allow scrolling.
Once the list of test results is longer then can be displayed it should allow scrolling

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: windows installer
 - App Version: Insomnia 2021.1.1

**Additional context**
Work arounds include using the view menu to zoom out. Or using dev tools to add "overflow: auto;" to .unit-tests style. The css fix only works on the tests, I'm not sure what class needs to be overridden to fix the results.

**Comment by dimitropoulos** [comment]
@jswitzer-lulus thanks for the report!

I can confirm this is a regression:

2020.5.2 works just fine: ![Screenshot_20210323_093926](https://user-images.githubusercontent.com/15232461/112155419-ab0f8b80-8bbb-11eb-957e-e63b2af06f7d.png)

on `develop` (1052e2c489d3591e0a238c55671cdae092549167) there are no scrollbars
![Screenshot_20210323_094404](https://user-images.githubusercontent.com/15232461/112156096-502a6400-8bbc-11eb-8c9c-c6f3634b510c.png)
