### ISSUE TITLE
Suggest to use pnpm over yarn for shorter installation time and lower disk space footprint

### ISSUE THREAD

**Issue by beenotung** [getinsomnia/insomnia#3217]
**Is your feature request related to a problem? Please describe.**
I prefer a shorter installation time for insomnia.

**Describe the solution you'd like**
insomnia is currently using npm or yarn to install the npm packages.

If we adopt pnpm, it can dowload the packages and run build hooks in parallel. Also, for packages that is already downloaded previously, it setup symbolic links to the local cache.

This approach enables shorter installation time and lower disk space consumption.

**Describe alternatives you've considered**
Alternative way to install insomnia quickly is to install prebuilt binary from aur/insomnia-bin. However this way we cannot always access the latest version.

**Additional context**
I compared installing insomnia with pakku from 'aur/insomnia', 'aur/insomnia-bin', and manually git clone, modify the package.json at project root.
I changed the bootstrap scripts from:
```
    "bootstrap": "npm install && lerna bootstrap && lerna run --parallel --stream bootstrap",
```
into:
```
    "bootstrap": "npx pnpm install --recursive --shamefully-hoist && lerna bootstrap && lerna run --parallel --stream bootstrap",
```

**Comment by dimitropoulos** [comment]
from my testing, just switching to yarn cut the number of downloaded dependencies in half (saving over a GIGABYTE of downloaded code) without even having yarn pnp on.  I've never used pnpm but I'd be curious to hear some actual numbers.

Can you please run `install` with `time` in front of it (e.g. `time npm install` or `time yarn install`) with
1. current develop branch
2. pnpm
3. my (experimental) yarn branch: https://github.com/dimitropoulos/insomnia/tree/yarn

and let me know what the times look like?

Please also run `npx npkill` and delete everything between steps and take note of how large the total deleted was (for each of the above steps).

Npx is slow because it has to pull something that's not already there, in my experience, so I'd suggest that if performance is our goal that we add pnpm as a dependency to the root package.json.  Thoughts?

**Comment by merceyz** [comment]
If you want to save disk space and improve install times your best option would be Yarn 2's PnP https://yarnpkg.com/features/pnp, packages are stored once on disk in zip files and if your cache is already populated the install doesn't have to do much work. For example installing the https://github.com/storybookjs/storybook repo with its 4275 dependencies using Yarn 2's PnP takes ~5 seconds

**Comment by beenotung** [comment]
yarn can save download time because it save the compressed package in the user's local cache space.
When you install a cached package, it skips the download and un-compresses from local cache.

pnpm take one step further. It also save the cache locally, but without compressing the package.
When you install a package, pnpm setup symbolic link to the local copy. Therefore, each package will be kept on the disk only once.
This can save disk space dramatically when you have multiple projects on the system (which is the case for most developers, unless you're putting each project in isolated container)

I'm not sure about yarn2's PnP, but it sounds similar to my previous observation on yarn as merceyz mentioned it save the cache in zip?

**Comment by beenotung** [comment]
Here's the benchmark result of npm and pnpm ran on my local dev machine:

| installer | bootstrap time | repo size | packages cache size | total size |
|---|---|---|---|---|
| npm | 316s | 2.7G | 261M | 2.9G |
| pnpm | 160s | 1.5G | 1020M | 2.5G |


Details in https://github.com/beenotung/insomnia/blob/pnpm/time.md

**Comment by dimitropoulos** [comment]
Thanks for this.  Is it too much to ask that you take a look at my experimental yarn branch and see what the times and sizes are like for it.  I'd also like to follow up on yarn 2 pnp as well, since it looks promising and is built in.

**Comment by beenotung** [comment]
@dimitropoulos I cannot run bootstrap on the yarn branch.

First trial:
```bash
> yarn install
> yarn clean
> time yarn bootstrap
 (...skipped...)
 insomnia-inso: $ webpack --config webpack/webpack.config.development.js --display errors-only
 insomnia-inso: ERROR in ../insomnia-testing/src/generate/index.js
 insomnia-inso: Module build failed (from /home/beenotung/workspace/github.com/dimitropoulos/insomnia/node_modules/babel-loader/lib/index.js):
 insomnia-inso: SyntaxError: /home/beenotung/workspace/github.com/dimitropoulos/insomnia/packages/insomnia-testing/src/generate/index.js: Support for the experimental syntax 'flow' isn't currently enabled (6:8):
 insomnia-inso:   4 | import fs from 'fs';
 insomnia-inso:   5 |
 insomnia-inso: > 6 | export type Test = {
 insomnia-inso:     |        ^
 insomnia-inso:   7 |   name: string,
 insomnia-inso:   8 |   code: string,
 insomnia-inso:   9 |   defaultRequestId: string | null,
 insomnia-inso: Add @babel/preset-flow (https://git.io/JfeDn) to the 'presets' section of your Babel config to enable transformation.
 insomnia-inso: If you want to leave it as-is, add @babel/plugin-syntax-flow (https://git.io/vb4yb) to the 'plugins' section to enable parsing.
 (...skipped...)
 yarn bootstrap  69.14s user 16.74s system 174% cpu 49.266 total
```

Second trial (without clearing the repo):
```bash
> time yarn bootstrap
 (...skipped...)
insomnia-inso: ERROR in ./src/commands/run-tests.js
insomnia-inso: Module not found: Error: Can't resolve 'insomnia-send-request' in '/home/beenotung/workspace/github.com/dimitropoulos/insomnia/packages/insomnia-inso/src/commands'
insomnia-inso:  @ ./src/commands/run-tests.js 81:6-38
insomnia-inso:  @ ./src/cli.js
insomnia-inso: ERROR in ./src/commands/generate-config.js
insomnia-inso: Module not found: Error: Can't resolve 'openapi-2-kong' in '/home/beenotung/workspace/github.com/dimitropoulos/insomnia/packages/insomnia-inso/src/commands'
insomnia-inso:  @ ./src/commands/generate-config.js 1:0-38 52:21-43 57:21-33
insomnia-inso:  @ ./src/cli.js
insomnia-inso: ERROR in /home/beenotung/workspace/github.com/dimitropoulos/insomnia/node_modules/mocha/lib/cli/cli.js 1:0
insomnia-inso: Module parse failed: Unexpected character '#' (1:0)
insomnia-inso: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
insomnia-inso: > #!/usr/bin/env node
insomnia-inso: | 
insomnia-inso: | 'use strict';
insomnia-inso:  @ /home/beenotung/workspace/github.com/dimitropoulos/insomnia/node_modules/mocha/lib/cli/index.js 3:17-33
insomnia-inso:  @ /home/beenotung/workspace/github.com/dimitropoulos/insomnia/node_modules/mocha/lib/utils.js
insomnia-inso:  @ /home/beenotung/workspace/github.com/dimitropoulos/insomnia/node_modules/mocha/lib/mocha.js
insomnia-inso:  @ /home/beenotung/workspace/github.com/dimitropoulos/insomnia/node_modules/mocha/index.js
insomnia-inso:  @ ../insomnia-testing/dist/index.js
insomnia-inso:  @ ./src/commands/run-tests.js
insomnia-inso:  @ ./src/cli.js
insomnia-inso: error Command failed with exit code 2.
insomnia-inso: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
insomnia-inso: error Command failed with exit code 2.
insomnia-inso: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run bootstrap exited 2 in 'insomnia-inso'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn bootstrap  71.60s user 17.32s system 172% cpu 51.505 total
```

But I can see `"insomnia-send-request": "^2.2.29"` and `"openapi-2-kong": "^2.2.29"` in `packages/insomnia-inso/package.json`

**Comment by beenotung** [comment]
Despite the errors, yarn still produced larger footprint than pnpm as expected from the different in design.

| installer | bootstrap time | repo size | packages cache size | total size |
|---|---|---|---|---|
| npm | 316s | 2.7G | 261M | 2.9G |
| pnpm | 160s | 1.5G | 1020M | 2.5G |
| yarn | N./A. | 1.8G | 1.3G | 3.1G |

<details>
<summary>Details of yarn install on yarn branch</summary>

## yarn install on yarn branch

with fresh `~/.cache/yarn`:

```bash
> time yarn install
yarn install  91.50s user 30.29s system 153% cpu 1:19.21 total
> time yarn clean
yarn clean  6.88s user 4.85s system 241% cpu 4.849 total
> time yarn bootstrap
(...error omitted...)
yarn bootstrap  69.14s user 16.74s system 174% cpu 49.266 total
```

the second run:

```bash
> time yarn install
yarn install  51.78s user 16.44s system 162% cpu 42.051 total
> time yarn clean
yarn clean  6.79s user 5.08s system 257% cpu 4.613 total
> time yarn bootstrap
(...error omitted...)
yarn bootstrap  67.56s user 17.10s system 172% cpu 49.156 total
```

repo size:

```bash
> du -sh .
1.8G
> du -sh --apparent-size .
> 1.4G
```

cache size:

```bash
> du -sh ~/.cache/yarn
1.3G
> du -sh --apparent-size ~/.cache/yarn
1.1G
```

</details>

**Comment by dimitropoulos** [comment]
this isn't an apples to apples comparison because you're comparing yarn to pnpm but you're not using yarn 2 pnp:

https://yarnpkg.com/features/pnp

No worries, though, we'll come back to this one TypeScript is done and give it another go.

If you @beenotung or anyone else wants to try with yarn 2 pnp, I'd really love to see it.  Note that it will definitely require a bit of work to get it working appropriately.

**Comment by wdawson** [comment]
Closing this for now. We aren't considering pnpm at this time.
