### ISSUE TITLE
Unknown license in releases

### ISSUE THREAD

**Issue by bfsgr** [getinsomnia/insomnia#3219]
**What is your question?**
I noticed that both the .rpm and .deb packages available in [Releases](https://github.com/Kong/insomnia/releases/) have unknown license in their specifications. I want to know if that's intended or a mistake.

**What is the context?**
Releases

**Comment by bfsgr** [comment]
This issue seems easily resolved by adding `"license": "MIT"` into `packages/insomnia-app/package.json` but a think it should be all of the packages. 

Anyway, I can make a PR to resolve this issue

**Comment by nijikokun** [comment]
@bfsgr PR would be welcomed!
