### ISSUE TITLE
[Feature] Ability to preview PDF from the Preview Mode

### ISSUE THREAD

**Issue by Antoine38660** [getinsomnia/insomnia#323]
It would be useful to be able to preview a PDF file (Based on the `Content-Type: application/pdf`) directly inside the _Preview Mode_.

I read about pdf.js and Electron (but never tried to works with them) and it seems to be possible.

NB: I forked insomnia 2 days ago to try to contribute with this feature, but I’d like to know what you think of it before making a decision :smiley:

**Comment by gschier** [comment]
That would be an awesome addition. I would be hesitant if it required complex modifications or dependencies (like c++ addons), but pdf.js seems simple, safe, and easy 😄 

Let me know if you have any questions along the way 👍

**Comment by gschier** [comment]
This was closed by #325

**Comment by renanmorais** [comment]
its works ?

**Comment by Antoine38660** [comment]
Yes it is

![image](https://user-images.githubusercontent.com/9287184/178467008-f57b14f7-4611-404b-89e8-e4eedce4b034.png)
