### ISSUE TITLE
Can't create Collection with Git Clone

### ISSUE THREAD

**Issue by emilras** [getinsomnia/insomnia#3235]
**Describe the bug**
When creating a collection with Git Clone nothing happens in the UI - only a Console error is visible via the Chrome Developers tools:

```
Uncaught (in promise) TypeError: Cannot read property '_id' of null
    at GitRepositorySettingsModal.onSubmitEdits [as _onSubmitEdits] (bundle.js:188184)
```

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Create'
3. Click on 'Git Clone '
4. Fill in repository URL and authentication details.
5. Click on "Done"

**Expected behavior**
I expect the repository to be created as a Collection

**Screenshots**
![Screenshot 2021-03-24 at 12 22 14](https://user-images.githubusercontent.com/1532192/112302639-96a2c000-8c9b-11eb-8230-1c556f3311b1.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3 
 - Installation Method: Download (updated via in-app updating mechanism)
 - App Version: 2021.2.0

**Additional context**
![Screenshot 2021-03-24 at 12 24 23](https://user-images.githubusercontent.com/1532192/112302882-e2ee0000-8c9b-11eb-89ff-7a9344a2b3ea.png)

**Comment by nijikokun** [comment]
Welcome @emilras does the repository you are trying to use contain existing content?

**Comment by emilras** [comment]
@nijikokun Thank you!

Yes. It looks like this:

![Screenshot 2021-03-24 at 12 29 54](https://user-images.githubusercontent.com/1532192/112303696-e1710780-8c9c-11eb-98e2-552618c59e90.png)

**Comment by nijikokun** [comment]
Perfect - well not that it's not working - but the good news is that this is currently being worked on 🎉 

Related issues #3131 and #2525
