### ISSUE TITLE
Error: Couldn't resolve host name

### ISSUE THREAD

**Issue by eralpkor** [getinsomnia/insomnia#3239]
**Describe the bug**
None of the HTTP methods work with 2021.2.0 release.

**To Reproduce**
1. Go to 'Any of the collections'
2. I tested with all of the methods eg. POST, GET, PUT, DELETE
4. See error Couldn't resolve host name

**Expected behavior**
App should open a connection with the server
For insanity check tested with Postman app. Server responds as expected.
**Screenshots**
https://gyazo.com/c191f8dcbd32040b880635d66e410b00

**Desktop (please complete the following information):**
System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.82
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.57)
Insomnia: 2021.2.0

**Comment by nijikokun** [comment]
Related to (and duplicate-ish of) #3234
