### ISSUE TITLE
Cannot initialize a Git Clone on Gitlab

### ISSUE THREAD

**Issue by bertrandjamin** [getinsomnia/insomnia#3241]
**Describe the bug**
I'm trying to initialize a git  repository to store my collections.

But when I'm entering the asked information I have the following error : 

<img width="772" alt="image" src="https://user-images.githubusercontent.com/4040743/112464035-48f18a80-8d63-11eb-890b-99486911b2a8.png">

ℹ️ It is a new repository initialized with an empty ".insomnia" folder 

<img width="823" alt="image" src="https://user-images.githubusercontent.com/4040743/112464784-3592ef00-8d64-11eb-9b8e-d837d445dea2.png">

**To Reproduce**
1. Go to 'Create > Git Clone'
2. Enter the asked information (Git Uri, Author Name, Author Email, Username, Authentication Token)
3. Click on 'Done'

**Expected behavior**
After clicking on 'Done' I expected to have access to my repository. 
Notably to push my local Collections on it.

**Desktop (please complete the following information):**
 - OS: mac Os 11.2.3
 - Download
 - App Version v2021.2.1

thanks for your help

**Comment by dimitropoulos** [comment]
two questions:

1. can you please share your url format (i.e. replace `yourdns.com` `username` and `repo` if you like to maintain privacy).  E.g. is it the scp style that begins with `git@`, or is it the `http` or `https` style.  Does it end with `.git`?
2. is it possible that you could pull down https://github.com/Kong/insomnia/pull/3111 and run it locally and report back if you get the same error? no worries if not, but it'd be helpful if you are able to do so. lemme know if you need any assistance in doing so.

**Comment by develohpanda** [comment]
It's also possible this is related to the fact that an empty `.insomnia` directory exists in your repository. I have some work coming up that should handle that case better, but if you:
- remove the `.insomnia` folder 
- create a new design document (don't clone since it's not an existing insomnia directory, git sync is also not supported with request collections yet)
- Click "setup git sync"
- Then commit and push, you should be all set up.

We have some documentation [here](https://support.insomnia.rest/article/193-git-sync#Remote_Repository_Settings) that might be helpful.

**Comment by dimitropoulos** [comment]
good call, what @develohpanda is talking about sounds more plausible to me.

**Comment by bertrandjamin** [comment]
Hi, 
thanks for your help, indeed this error occured because I have missed the final ".git" in the url 🤦 . 

FYI after adding this I have seen a new fail but with a clear explanation about a missing "Workspace" directory in the ".insomnia" one.

Right after that the command seems to work well.

However, after reading more accuratly the tutorial (https://support.insomnia.rest/article/193-git-sync) I have realized that those explanation was about Api design documentation . 

My initial goal was to share Requests Collections on my gitlab repo and so I hope it could be realized by the "Create > Git clone" option in the Dashboard screen.

But, it seems that this capability requires a paying susbscription, am I right ?

Thanks for your help

**Comment by develohpanda** [comment]
Hi @bertrandjamin, makes sense that the `.git` suffix was causing issue, and the second issue you're seeing about a missing "Workspace" should be resolvable if you run through the steps I mentioned. 🙂 

To sync Request Collections you currently need a paying subscription, although Design Documents can be used the same way as Request Collections are. This is a work in progress however, we will be consolidating the sync systems with Insomnia Spaces (over the coming months).

**Comment by bertrandjamin** [comment]
Hi @develohpanda. 
Yes no worries with the "missing Workspace" alert, I had solved it by my side.

Ok I understood well. I will certainly go on a paid subscription to use this sync option. 

Thanks for your help and for your great job on this product 💪.

I close this issue as it is resolved in my opinion
