### ISSUE TITLE
[umbrealla] use a true graphql prettifier (i.e., one designed for prettifying)

### ISSUE THREAD

**Issue by dimitropoulos** [getinsomnia/insomnia#3242]
**Describe the bug**
There are a number of bugs that arise from our current approach to prettifying graphql:
- comments are destroyed https://github.com/Kong/insomnia/issues/1124
- indentation is not respected https://github.com/Kong/insomnia/issues/2301
- very long query parameters (which is not terribly uncommon) don't wrap https://github.com/Kong/insomnia/issues/2600
- (and probably more that I haven't yet found - let me know if so).

**To Reproduce**
1. Create a GraphQL request
2. click `Pretify GraphQL` and observe the results

**Expected behavior**
The above issues have different solutions, but the over-arching concept is that the prettifying should work as one might naturally expect (and definitely without destroying information).

I think we should look at other tools and graphql clients to see how they approach this problem and go with the most widely adopted solution.  I believe prettier may be an option, but the docs are down at the time of writing this issue.

**Comment by dimitropoulos** [comment]
<img src="https://user-images.githubusercontent.com/15232461/112511463-d2578b80-8d68-11eb-888d-ba7932032c2f.png" height="600px" />

```graphql
type Book {
  title: String, asdflnasdf: String, oqweroiyweroiyqwreoiqwer: String, nbiuiwrogiuwn: String, oineoinvoiunaouinaoiubhj: String,   nasgoinaionabionafb: String, author: Author
}

# comment that should not be removed
type Author {
  name: String
  books: [Book]
}
```

The above is an example of a formatter that would fix all of the above 3 bugs (and probably more).  It can be found at https://mtp.tools/formatters/graphql-formatter but I don't see what editor it's uses (it makes a network request with your query :face_with_head_bandage:)


----

Interestingly, the `GraphiQL` editor (the one I'm the most familiar with) doesn't seem as capable (for one thing, it destroys the comments).

<img src="https://user-images.githubusercontent.com/15232461/112512124-76d9cd80-8d69-11eb-962b-424dd06ef524.png" height="300px" />

**Comment by ariasmn** [comment]
Hi!

I have (kinda) looked into it, and the problem with the comments comes from the [Javascript GraphQL library AST](https://github.com/graphql/graphql-js/issues/2241), since it can't parse comments. If they implement it, making a small library to correctly prettify the code should not be much of a problem, but modifying the parser is out of my league sadly.

My guess is that the one from [mtp.tools](mtp.tools) is using a whole different GraphQL AST that parse comments correctly.

I hope that this information helps you!

**Comment by ariasmn** [comment]
Actually, [Prettier](https://github.com/prettier/prettier) should work to correctly solve the bugs mentioned. I might look into it later and try to make a PR if that's ok!

EDIT: @dimitropoulos May I have any pointer on how/where to load the Prettier package?

**Comment by dimitropoulos** [comment]
@ariasmn I would love to see a PR for this!!  You'd add it to the `insomnia-app` package and run it using the prettier API (https://prettier.io/docs/en/api.html).

Lemme know how I can help!

**Comment by ariasmn** [comment]
@dimitropoulos I just submitted a PR for this. Sorry it took that long, I have been a bit busy. :sweat_smile: 
Please let me know if any changes are needed!
