### ISSUE TITLE
Invalid route names generated for operation IDs with spaces or special characters

### ISSUE THREAD

**Issue by rossmcdonald** [getinsomnia/insomnia#3244]
**Describe the bug**
The openapi-2-kong package currently generates invalid route names if an operation ID (OID) contains special characters that are not supported by Kong.

**To Reproduce**
Generate a declarative config from an OpenAPI specification that contains characters that are invalid. For example:

```yml
  /pets/{id}:
    get:
      operationId: find pet by id
```

This is a valid operation ID in [OpenAPI](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#operation-object), however it is not a valid route name in Kong. The same issue occurs for OIDs with any special characters (ie, `/pets/{id}`)

**Current behavior**

Currently OIDs are not modified before getting included in a deck config, causing errors when attempting a sync operation. The example above currently renders as a route with the name:

```json
        {
          "methods": ["GET"],
          "strip_path": false,
          "tags": ["OAS3_import", "OAS3file_petstore-expanded.yaml"],
          "name": "find pet by id",
          "paths": ["\/pets\/(?<id>\\S+)$"]
        },
```

**Expected behavior**
I'm of the opinion that operation ID's should be slugified. Using the example above, I would expect the route name to be `find_pet_by_id`:

```json
        {
          "methods": ["GET"],
          "strip_path": false,
          "tags": ["OAS3_import", "OAS3file_petstore-expanded.yaml"],
          "name": "find_pet_by_id",
          "paths": ["\/pets\/(?<id>\\S+)$"]
        },
```

**Proposed Fix**
I have a naive fix for this issue in https://github.com/rossmcdonald/insomnia/commit/8df39acb930d8b9d23057ac231df2cb2379609da that I'd be happy to open a PR for. The reason I say 'naive' is that it introduces a breaking change if the OID is kebab-cased, making them snake-cased instead. See the test updates for more info.

**Comment by filfreire** [comment]
Hi @rossmcdonald thanks for reporting this!

We can close this one, it has been fixed about a month after you reported it in https://github.com/Kong/insomnia/pull/3318

You should see proper OIDs now in [latest Insomnia version](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2).
