### ISSUE TITLE
APT repository at bintray.com apparently discontinued

### ISSUE THREAD

**Issue by pavilalopes** [getinsomnia/insomnia#3253]
The APT repository at https://dl.bintray.com/getinsomnia/Insomnia is now returning 403 for all requests.

According to this post the service has been discontinued:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

What is the upgrade path for APT users?

**Comment by reynolek** [comment]
Hey @pavilalopes -- It looks like Bintray has added rate limiting to our account. We are going to reach out to them about this and see if we can rectify the situation.

**Comment by reynolek** [comment]
To more directly answer your question in the mean time, the work around would be to download the `.deb` package from the release assets and use APT to install it.

**Comment by pavilalopes** [comment]
Thanks, I tried it now and it's working.

But presumably you will still need to migrate away from bintray.com soon?

**Comment by reynolek** [comment]
Yup, and we will be. Another team at Kong is working on that project and we will be using their work once its complete.

Glad you are up and running!
