### ISSUE TITLE
OpenSSL SSL_read: Connection was reset, errno 10054 causes duplicate post request

### ISSUE THREAD

**Issue by BeckKC** [getinsomnia/insomnia#3254]
**To Reproduce:** 
1. POST to RestAPI using Basic Authentication
2. Authenticated via Insomnia request. 2021-03-31T10:45:09.2482452-05:00.
3. Use a large request payload (mine was106 KB / 109,057 bytes).
4. Service request completes. 2021-03-31T10:55:22.0984506-05:00. (5 min 12 sec duration)
**BUG:** 
Insomnia displays error: **Error**: "Failure when receiving data from the peer"
The request completes running, but result is never returned to Insomnia client.
Insomnia initiates a second, duplicate POST, resulting in double the records posted to the API. 

**Expected behavior**
Expect that one request will produce a single post without retrying. 

**Screenshots**
![image](https://user-images.githubusercontent.com/21689135/113201605-4d201b00-922f-11eb-8ceb-eb49eb5c7266.png)

**Timeline Output**
Insomnia Timeline:
* Preparing request to https://myserver.com/Service/Records
* Current time is 2021-03-31T15:45:09.107Z
* Using libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0
* Using default HTTP version
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Found bundle for host myserver.com: 0x25d048eeb40 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#41) with host myserver.com
* Connected to myserver.com (172.27.51.1) port 443 (#41)
* Server auth using Basic with user 'myUserId'

> POST /PspRestService.uat/Records HTTP/1.1
> Host: myserver.com
> Authorization: Basic MTA2MzE6VGVzdGluZ3VzZXIxIQ==
> User-Agent: insomnia/2020.4.1
> Content-Type: application/json
> Accept: application/json
> Content-Length: 105253

| (64 KB hidden)
| (38.8 KB hidden)

* We are completely uploaded and fine
* OpenSSL SSL_read: Connection was reset, errno 10054
* Connection died, retrying a fresh connect
* Closing connection 41
* Issue another request to this URL: 'https://myserver.com/Service/Records'
*   Trying 172.27.51.1:443...
* Connected to myserver.com (172.27.51.1) port 443 (#42)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:\Users\REBEKA~1.PRI\AppData\Local\Temp\insomnia_2020.4.1\2017-09-20.pem
*   CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Kansas; L=Olathe; O=My Company, LLC; CN=*.com
*  start date: Sep  8 00:00:00 2020 GMT
*  expire date: Oct 10 00:00:00 2021 GMT
*  subjectAltName: host "myserver.com" matched cert's "*.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
* Server auth using Basic with user 'myUserId'

> POST /Service/Records HTTP/1.1
> Host: myserver.com
> Authorization: Basic MTA2MzE6VGVzdGluZ3VzZXIxIQ==
> User-Agent: insomnia/2020.4.1
> Content-Type: application/json
> Accept: application/json
> Content-Length: 105253

| (64 KB hidden)
| (38.8 KB hidden)

* We are completely uploaded and fine
* OpenSSL SSL_read: Connection was reset, errno 10054
* Closing connection 42

The service urls, server certificate info and userid in the timeline output has been altered for the sake of security. 

**Desktop:**
 - OS: Windows 10 Enterprise, Version 1909, Build 18363.1440
 - Installation Method: https://insomnia.rest/download -> Download for Windows
 - App Version 8.2.110.13.electron.0
![image](https://user-images.githubusercontent.com/21689135/113201917-bacc4700-922f-11eb-959f-93db196c15ec.png)

**Additional context**
Windows errno 10054 (from timeline output) is An existing connection was forcibly closed by the remote host.

**Comment by kreosus** [comment]
@BeckKC have you been able to reproduce the issue with our newest release, https://github.com/Kong/insomnia/releases/tag/core%402022.7.5
