### ISSUE TITLE
Telemetry is being sent even whilst opted-out + includes personal identifiers

### ISSUE THREAD

**Issue by pcjmfranken** [getinsomnia/insomnia#3255]
Edit: The Insomnia team released a fix within only a few short days (#3264). I was even offered the opportunity to go over these changes before they were merged. My faith has been fully restored and I'm properly amazed at how this was handled!

---

Today I noticed requests were being made regularly to `https://api.insomnia.rest/notification`. These turned out to be `POST` requests, and they are sending precisely the telemetry that I have explicitly opted out of sharing.

Contrary to the config screen claim that only anonymous data will be sent if one should opt in, several datapoints are included that both the CCPA and GDPR list as personal identifiable information:  `deviceId`, `firstLaunch`, IP address, OS version. It is impossible for a property that is referred to by the word "identifier" (`deviceId`) to be anonymous to any degree, especially when it is combined with other data.

Additionally, Google Analytics appears to happily be collecting events and who knows what else (all the things). You can never legally process this data anyway as it was collected during a period without consent - which, even if it were to be given at a later date, would not apply retroactively. Please consider disabling data collecting completely when the user has not opted in. Close the holes.

--

![optout](https://user-images.githubusercontent.com/17924090/113234876-6c0bc500-92a2-11eb-9905-cf28cf2f8106.jpg)

The configuration setting that I have disabled says:

> Data Sharing
> Help Kong improve its products by sending anonymous data about features and plugins used, hardware and software configuration, statistics on number of requests, collections, documents, etc.
Please note that this will not include personal data or any sensitive information, such as request data, names, etc.

However the following data is being transmitted:

```json
Common HTTP request data
{
  "firstLaunch":[redacted],
  "launches":[redacted',
  "platform":"darwin",
  "app":"com.insomnia.app",
  "version":"2021.2.2",
  "requests":[redacted],
  "requestGroups":[redacted],
  "environments":[redacted],
  "workspaces":[redacted],
  "updatesNotSupported":false,
  "autoUpdatesDisabled":false,
  "disableUpdateNotification":false,
  "updateChannel":"stable",
  "deviceId":[redacted],
  "createdRequests":[redacted],
  "deletedRequests":[redacted],
  "executedRequests":[redacted[
}
```

The fact that this data is being sent to such an inconspicuous URL, one containing the word "notifications" no less, left a very bad taste in my mouth.

However this came about, it is a serious breach of trust and confidence. Today it's telemetry, tomorrow it might be sensitive work data.

I kindly request for this to be fixed as soon as possible.

**Comment by reynolek** [comment]
Hi @pcjmfranken -- Thanks for reporting this. I agree with many of your points and one in particular interests me (that GA is collecting data still). We will take a look into this, as this is unintended.

**Comment by khyveasna11111908** [comment]
I'll

khyveasna

**Comment by dimitropoulos** [comment]
just wanted to chip in here and say that I know for a fact that every Kong employee involved with insomnia takes privacy and security seriously and we are actually talking about this / looking into it.

**Comment by pcjmfranken** [comment]
Thanks @dimitropoulos, a clear and confident public statement such as that goes a long way, and the quick turnaround time for the resolving PR shows that you mean it.

I'll add a mention of this to the original ticket message for anyone coming across it in the future.

Thank you again for the quick resolution.
