### ISSUE TITLE
Can't sync git with gitlab self hosted

### ISSUE THREAD

**Issue by pchmn** [getinsomnia/insomnia#3257]
I can't pull/push on my repo that is hosted on a private host.

**Describe the bug**
I can clone the project (no error), but when I try to pull or push a commit I have a "400 Bad Request" :
```
HTTPError: HTTP Error: 400 Bad Request
    at Function.discover (C:\Users\pchemin\AppData\Local\insomnia\app-2021.2.2\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:6481:13)
    at async Object.getRemoteInfo (C:\Users\<user>\AppData\Local\insomnia\app-2021.2.2\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:8429:20)
    at async GitVCS.canPush (file:///C:/Users/<user>/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:31624:24)
    at async GitSyncDropdown._handlePush (file:///C:/Users/<user>/AppData/Local/insomnia/app-2021.2.2/resources/app.asar/bundle.js:203519:17)
```
FYI I had correctly configured my personal access token on gitlab.

**To Reproduce**
1. Click on Git button
2. Click on 'Pull'
3. See error

**Expected behavior**
To be able to pull/push data from my git remote.

**Screenshots**
![image](https://user-images.githubusercontent.com/12658241/113420474-ac199780-93c9-11eb-8078-ed7ca9b07f6c.png)

![image](https://user-images.githubusercontent.com/12658241/113420654-fe5ab880-93c9-11eb-9626-cc039ed5ce21.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Installation Method: .exe
 - App Version: 2021.2.2

**Comment by dimitropoulos** [comment]
We have _just_ merged two PRs (https://github.com/Kong/insomnia/pull/3111 and https://github.com/Kong/insomnia/pull/3247) that addressed quite a few git-related items.  One of those items was testing syncing to GitLab.  Is it possible for you to run the app locally (from the develop branch) and see if the 400 is resolved.  I think there's a good change it will be now.

**Comment by pchmn** [comment]
Hi, sorry for the late response.

So I struggled to make it work on local with windows 10, I had to install [nasm](https://www.nasm.us/) to build `node-libcurl`. I made a PR (#3281) to update the docs.

There is still a problem with develop sources when I tested it. Now I can't even make a git clone:
![image](https://user-images.githubusercontent.com/12658241/114535602-82c1fc80-9c50-11eb-92c7-b2a9cc4e9d39.png)

I use Insomnia behind a proxy, I don't know if it can be part of the problem. But on desktop app (downloaded from the site) there is no problem when cloning a repo, even behind a proxy.

**Comment by develohpanda** [comment]
Thanks for that PR!

> Now I can't even make a git clone

That's interesting, thanks for posting that stack trace. We're looking at releasing a beta next week which will include these changes to allow for better testing. We've historically had issues with GitLab so I wouldn't be surprised if it has some specific requirements.

Could you please tell me what permissions you have provided to your access token, and what version of GitLab self-hosted?

**Comment by pchmn** [comment]
We use Gitlab v13.9.5, and for the access token permissions, I set them all (api, read_user, read_api, read_repository, write_repository, read_registry, write_registry).

Yes no problem, I will test the beta, and if I see new commits related to git sync on develop branch, I will test it too and report any issues I find.

**Comment by wdawson** [comment]
Are you still seeing an issue here?

**Comment by pchmn** [comment]
I don't use gitlab anymore, so I can't say sorry. But if no one has the same problem, we could close the issue maybe.

**Comment by Sakiut** [comment]
Hello, I have the exact same problem:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/27028806/202691043-16e04c2e-0780-4bfb-ab0e-9908cdc371b1.png">

I'm barely in the same situation as well: behind a proxy, trying to reach a self-hosted gitlab instance.

I'm on the latest stable desktop client (2022.6.0), the gitlab is also barely up to date (15.2.x I guess).

**Comment by jadjay** [comment]
Same tickets : 
- https://github.com/Kong/insomnia/issues/6791
- https://github.com/Kong/insomnia/issues/5510

**Comment by Antonina23** [comment]
Hello everyone! I have an absolutely the same issue. I have the latest Insomnia app version. Log out / Log in couple times (GitLab and Insomnia as well) - nothing helps. There was no problem a day before.
