### ISSUE TITLE
[Bug] Generate Code and Copy as cUrl silently fails with empty query values

### ISSUE THREAD

**Issue by Chocrates** [getinsomnia/insomnia#3259]
**Describe the bug**
Copy as cURL and Generate code silently fails when your query parameters have names with no values.
DevTools error samples
```
bundle.js:172255 Uncaught (in promise) HARError {name: "HARError", message: "validation failed", errors: Array(1), stack: "HARError: validation failed"}
```

**To Reproduce**
1. Create a REST call
2. validate that you can generate code
3. Add a new Query Parameter and leave the value blank
4. validate that the curl generation fails
5. Add a query parameter value or uncheck the query parameter
6. Valdiate you can generate code

*Note:* This seems sporadic.  Sometimes I have to restart Insomnia to get it to reproduce, so maybe when I alter query params it fixes itself?

**Expected behavior**
Either an error message or just work ignoring the invalid query params

**Screenshots**
<img width="1323" alt="Screen Shot 2021-04-02 at 4 19 49 PM" src="https://user-images.githubusercontent.com/1758164/113455047-46c8a500-93cf-11eb-99b2-49ba7acd253e.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Installation Method: [e.g. homebrew] DMG download from website
 - App Version [e.g. v7.0.3] 2021.2.2

**Additional context**

**Comment by nathHy** [comment]
Empty cookie expiry will cause this as well.

**Comment by udivankin** [comment]
I confirm that emptying all cookies in "Manage Cookies" fixes this problem

**Comment by filfreire** [comment]
Hi folks, this one is no longer reproducible, so I'll go ahead and close it.

We do still have another similar issue happening, but it's only with environment variables: https://github.com/Kong/insomnia/issues/4825
