### ISSUE TITLE
Sending a request sends the request plus an improper (seems to be cached) request

### ISSUE THREAD

**Issue by PhilipeFernandino** [getinsomnia/insomnia#3262]
**Describe the bug**
There are two requests in my insomnia document. POST (/user/login) and POST (/manager/login). Sending any one of them also sends what appears to be an unwanted cached request.

**To reproduce**
1. Clone [node.js app](https://github.com/PhilipeFernandino/insomnia-bug.js)
2. Clone [insomnia-document](https://github.com/PhilipeFernandino/insomnia-bug) on Insomnia
3. Run npm start on node app
4. Send one of the two configured requests on Insomnia to see the odd behavior

**Expected behavior**
When sending one of the requests, I expect to send only the request itself.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 10.0.19042
 - Installation Method: https://insomnia.rest/download
 - App Version: 2021.2.2

**Additional context**
Creating a new equal Insomnia document does not produce the same behavior. It only reproduces in that document specifically.

**Comment by PhilipeFernandino** [comment]
Oh well, I didn't change anything and the issue is magically not happening anymore, can't say it's fixed, but I don't see how to continue investigating. As far as I'm concerned, this can be closed.

**Comment by dimitropoulos** [comment]
no worries, and thanks for the update.  intermittent (and real) bugs do occur from time to time so if you find a way to reproduce please let us know :)
