### ISSUE TITLE
Git sync on Windows 10: Commits are very very slow

### ISSUE THREAD

**Issue by stadja** [getinsomnia/insomnia#3269]
I have a fairly large collection of Requests (+100), sorted by GroupRequests synced with Git sync on my up to date Amnesia.
On Windows 10, the Git Pull and Git Push are working really well, but the commit action is very slow.
For exemple, this morning I just changed the name of one Request and the commit action took at least 5mn.
Even when I make a commit with no changes, just to see the time it takes, it is more than 5mn.

I am working on an SSD with plenty of space.
During the "Loading" part of the commit, my processeur is well under the 60% and Insomnia doesn't take more than 20% of my procs.
My colleague on MacOs doesn't have this issue.

Anyway, I love your work, thank you for everything !

**Comment by stadja** [comment]
No error in the DevTools:

09:19:38.610 › [ga] Event Modals, Show, GitStagingModal
**click commit**
09:26:53.755 › [git] List files

**Comment by etienne-bechara** [comment]
+1 this is very annoying

I have three documents with 100+ request and a design file and they all behave like you describe
The biggest takes around 8 minutes to display the commit analysis

v2021.3.0 / Windows 10

**Comment by ryanholden8** [comment]
Also having an extremely slow experience with the git-sync feature. At this considering moving to a OpenAPI spec file in our git repo and using the [OpenAPI VS Code extension](https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi) to execute our APIs.

v2021.7.2 / Mac Mini M1 16GB / macOS 11.6.1

**Comment by sodanhama** [comment]
I'm waiting for 30 minutes after committing but they have not reached my repository. I'm on Windows 10 using VScode.

Edit: Now its 1 hour+

**Comment by kosgug** [comment]
MacOS 12.2.1 , the same.

**Comment by blgo** [comment]
I have been experiencing this issue since I started using Git sync in MacOS too.

When I click on "commit", it takes a long time to load the commits page: ~5 minutes.

It seems the longer is the commit history the slower it becomes.

I think is something to do with how Insomnia transforms/parses the Git history into files in the filesystem, which is what Insomnia reads the collections/tests from.

**Comment by john-james-ai** [comment]
Is anyone taking a look at this. Tried pushing and 'publishing branch' in vs code, but syncing is taking over 10 minutes.

**Comment by filfreire** [comment]
Hey folks, the potential fix by @PatrickMurrell will go out in this week's beta, let us know if it improved the slowness.

**Comment by dimi-lcq** [comment]
Hi, for me that change doesn't work, it's always too long to load my changed files.

**Comment by brauchle** [comment]
for me this issue also still is there, even with the most recent version.
It's showing the "Loading changes" message for at least 30 minutes before actually showing the changes, and I have multiple hundreds of requests in Insomnia.

![image](https://github.com/Kong/insomnia/assets/5851590/3e077507-22db-42c6-806a-d8e1e50f938d)

**Comment by bryangateley** [comment]
Same this is ridiculous. It takes several dozen minutes to sync even the smallest changes. Has anyone had any luck finding where the .git file is saved? I am guessing it would be a lot faster to just do the commits through a CLI, tried to find the file to do this from but could not locate it, was only able to find where insomnia saves its version control files.

**Comment by dimi-lcq** [comment]
Several months without progress.
You have to push this new ticket....
https://github.com/Kong/insomnia/issues/6454
