### ISSUE TITLE
gRPC requests do not appear in request navigation (Quick Switch, Recent)

### ISSUE THREAD

**Issue by ches** [getinsomnia/insomnia#3271]
**Describe the bug**

Invoking the Quick Switch dialog or the Recent Requests dialog do not list any gRPC requests.

**To Reproduce**
1. Create a new collection "gRPC Bug Repro"
2. Add a gRPC request, add a proto file with a copy of `grpcbin.proto` from https://grpcb.in/
3. Duplicate the request, choose a different RPC like `/GRPCBin/Empty`
4. Invoke keyboard shortcut for "Switch Requests", see nothing in dialog
5. Invoke keyboard shortcut for "Show Recent Requests", see nothing in dialog
6. Add a new HTTP request to the collection
7. Invoke the same shortcuts, see the HTTP request present

**Expected behavior**
Request listings for gRPC just as I get with requests using HTTP, GraphQL, etc.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Installation Method: homebrew
 - App Version 2021.2.2

**Comment by reynolek** [comment]
~This is likely related to #3272 -- If I had to wager a guess, we didnt enable shortcuts in the grpc views, or that code path isnt executing as expected.~

EDIT: Re-read what you wrote after trying to reproduce and I see why you listed this as different from the other issue.

**Comment by ches** [comment]
Right, the two dialogs do appear, they just list only HTTP and GraphQL requests, no gRPC ones (typical that you may have only gRPC requests in a particular collection, so they'll appear empty in that common case).

Thanks for verifying these!

**Comment by ches** [comment]
Fundamental missing functionality for gRPC usage, I don't feel stalebot should wontfix this.

**Comment by dimitropoulos** [comment]
@ches apologies.  we've had some trouble with the stalebot (we recently just turned it off altogether).

**Comment by ches** [comment]
No worries!
