### ISSUE TITLE
gRPC: Send Request keyboard shortcuts don't work

### ISSUE THREAD

**Issue by ches** [getinsomnia/insomnia#3272]
**Describe the bug**
In the editor, the usual keyboard shortcuts that send the request do not work for a gRPC request. I must click the Send UI button.

**To Reproduce**
1. Create a gRPC request. You can Add Proto File using a copy of `grpcbin.proto` from https://grpcb.in/
2. Select the new gRPC request
3. Invoke a keyboard shortcut for Send Request (I have three defined, all Insomnia defaults I believe, none work)
4. Nothing happens

**Expected behavior**
Request is sent, as it is with HTTP or GraphQL requests.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Installation Method: homebrew
 - App Version 2021.2.2

**Additional context**
I use the Vim key map, for what it's worth. Whether I'm in normal or insert mode, the shortcuts don't work either way. With HTTP and GraphQL the shortcuts work in either Vim mode.

**Comment by reynolek** [comment]
Hi @ches -- Thanks for reporting the issue. I am able to reproduce this with my editor set to default bindings, so its not related to Vim bindings.

**Comment by gAmUssA** [comment]
+1 to fix this, please
