### ISSUE TITLE
MSI Package

### ISSUE THREAD

**Issue by alec-hs** [getinsomnia/insomnia#3280]
**Is your feature request related to a problem? Please describe.**
Deploying to multiple users via tools like MS Intune/ PDQ Deploy is much easier when devs provide MSI installers. 

**Describe the solution you'd like**
An MSI package with silent/user-based/whole-machine switches.

**Comment by dimitropoulos** [comment]
Do you happen to have any pointer to another electron app that does this.  E.g. I didn't see vscode offering this.  It would be helpful to gauge how much work it might be.

**Comment by alec-hs** [comment]
This npm package makes most of the work trivial if you already use WIX or most other windows CI systems. 

https://www.npmjs.com/package/electron-wix-msi

Here's a few Open Source examples that use it.

https://github.com/tiagovtristao/clipmir-desktop
https://github.com/Pexeus/LCSS
https://github.com/iPzard/media-file-renamer
