### ISSUE TITLE
Add getHeaders to context.response on the Plugin API

### ISSUE THREAD

**Issue by monrax** [getinsomnia/insomnia#3282]
**Is your feature request related to a problem? Please describe.**
There is no way to get all response header keys

**Describe the solution you'd like**
Create a getHeaders method for `context.response` similar to the `context.request` one

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by develohpanda** [comment]
Thanks! Just adding notes for anybody looking to pick this up. 🙌🏽 

Looks like `context.request` has a `getHeaders` method: https://github.com/Kong/insomnia/blob/28e7d928a809402660293189eeccd5bb2c773bb4/packages/insomnia-app/app/plugins/context/request.js#L73-L78

But `context.response` is missing it: https://github.com/Kong/insomnia/blob/28e7d928a809402660293189eeccd5bb2c773bb4/packages/insomnia-app/app/plugins/context/response.js#L60-L73

Should be a fairly straightforward fix! I believe this is just an oversight. 🤗
