### ISSUE TITLE
[FEATURE REQUEST] Looping through a Data File like in the Postman Collection Runner

### ISSUE THREAD

**Issue by eoinion** [getinsomnia/insomnia#3294]
From what i've gathered Insomnia doesn't offer this solution like Postman does: 
https://blog.postman.com/looping-through-a-data-file-in-the-postman-collection-runner/

or if it already exists, is there documentation to follow to use with Insomnia.

**Comment by cldeluna** [comment]
Wondering if this type of capability is on the roadmap?   I would be moving to Insomnia completely (the variable prompt capability is fantastic!) but for the lack of this feature.

**Comment by andrepazleal** [comment]
Hi folks, any updates on this, it was ever implemented? Thanks.

**Comment by subnetmarco** [comment]
This is a great feature request and I am eyeing it for later this year (Dec?). I have more questions around this:

1. Postman also has a "Monitor" capability to execute the runner once in a while, how needed is this feature?
2. For the runner - just to confirm - the request is to be able to run collection endpoints sequentially?

**Comment by eoinion** [comment]
> This is a great feature request and I am eyeing it for later this year (Dec?). I have more questions around this:
> 
> 
> 
> 1. Postman also has a "Monitor" capability to execute the runner once in a while, how needed is this feature?
> 
> 2. For the runner - just to confirm - the request is to be able to run collection endpoints sequentially?

Yes, ideally the ability to load in a csv file to run on endpoints sequentially. For example, POST request to:
www.test.com/api/v1/{deviceId}
With body:
{
"Configuration": {deviceConfig}
}

Where deviceId and deviceConfig are pulled from each row of CSV file

**Comment by lobo235** [comment]
+1 to this request. I would find it very useful to use a CSV (or JSON) file as input to set variables for a request and run the request once for each row in the CSV or each item in an array within a JSON file.

**Comment by zachwolf** [comment]
2024 bump, this would be awesome!

**Comment by subnetmarco** [comment]
Yes, this is coming soon, perhaps even by September/October.

**Comment by subnetmarco** [comment]
Here is a preview of the new **Collection Runner** that is shipping on September which will also support the ability to load a CSV/JSON file:

https://github.com/user-attachments/assets/38a7fcff-2faf-425f-8ba4-3b7db703406b

**Comment by kemccoy** [comment]
@subnetmarco can you provide an example of how to call variables from the CSV file? The instructions only refer to variables contained in environments or globally. If you could post instructions or a video of you iterating through a CSV that would be great!

**Comment by subnetmarco** [comment]
@ihexxa can help with your request @kemccoy

**Comment by kemccoy** [comment]
Hi @ihexxa. Do you have some examples regarding the above question about Collection Runner? I am looking to see how variables from a CSV sheet can be called from my Insomnia body to iterate through all rows in the sheet.

**Comment by pwilliams-checkr** [comment]
I am seconding this. The documents seem to be lacking in providing an example of 1. an example csv or json file, and 2. how to reference the variables from the uploaded data. @ihexxa any insight you have here would be great. I'd help update the docs as well once this information is provided. Thanks!

**Comment by ihexxa** [comment]
Hello @kemccoy @pwilliams-checkr sorry for unawaring of this thread.

You could try this:
1. Upload a csv file:
```csv
id,name
1,Tom
2,Mary
```
![image](https://github.com/user-attachments/assets/62f0a0ed-15e1-4cde-b38c-fc9710cbe74e)

2. Add follow scripts to pre-request or after-response script, for nth iteration, they are able to access data from the nth row by the column names (`id`, `name`):
```javascript
console.log(insomnia.iterationData.get('id'));
console.log(insomnia.iterationData.get('name'));
```
![image](https://github.com/user-attachments/assets/8f3da070-061d-4012-b52a-d8b57bb2e06c)


3. Run the runner, then you can see outputs in the `Console` Tab:
![image](https://github.com/user-attachments/assets/0476d8eb-f43b-441e-945b-5fffa6fe43ad)
![image](https://github.com/user-attachments/assets/bf1ac519-5078-4652-9e9f-1c21ed494e3a)

You could try to add more columns to the csv and do other operations by calling `insomnia.iterationData.get('xxx')`. Let me know if you see problems in using it.

**Comment by pwilliams-checkr** [comment]
Do we also have an example for a JSON file?

**Comment by kemccoy** [comment]
Hello @ihexxa,

This doesn't explain how you call the variable from the body its self. That is where I would want to call one or more variables from the CSV to go row by row. For example:

CSV input:

DEVICE_ID,NAME
1234,DEVICE1
5678,DEVICE2

I want to iterate through the entire CSV sheet to search for each "DEVICE_ID" but I need to call this variable from the body. Below is an example body that would be used from PM:

{
    "$match": {
        "devices": {{DEVICE_ID}}
    }
}

How do you do this??

**Comment by ihexxa** [comment]
@kemccoy IIUC you could try to add a tag with the column name (`{{ NAME }}`) in the body as normal:

![image](https://github.com/user-attachments/assets/09f1362e-065a-45c0-9aa1-c024ebbb4217)

And when you run the request with the devices csv, you should be able to see device names rendered in the body (see text in purple in the right), and the request will be triggered for each row:

![image](https://github.com/user-attachments/assets/1670c2b1-1fd2-4426-bed8-e9298a6db338)

**Comment by ihexxa** [comment]
@pwilliams-checkr Here is one example:
```
[
    {"id": 66, "vm": "vm1" },
    {"id": 77, "vm": "vm2" }
]
```

**Comment by kemccoy** [comment]
Hello @ihexxa please see the screen shots below. I can see the values of the CSV sheet when I upload but not when I call the variable from the body. Is there something I am missing?

<img width="773" alt="Screenshot 2024-10-09 at 10 46 21 AM" src="https://github.com/user-attachments/assets/28f636b2-f218-428d-bf6b-5fae02500d5d">
<img width="554" alt="Screenshot 2024-10-09 at 10 44 11 AM" src="https://github.com/user-attachments/assets/48bd03cb-6981-43f8-bf0c-50e3683aed36">
<img width="617" alt="Screenshot 2024-10-09 at 10 42 42 AM" src="https://github.com/user-attachments/assets/27e3a97e-77da-46e4-b3fd-ab4def4ef864">

**Comment by ihexxa** [comment]
@kemccoy Hm this is expected, the upload file only works together with runner, not for one request.
Which means, if you run this request in the runner, you will see that the `{{ DEVICE_ID }}` tag is replaced by its value in the row.
But if you just send the request, it won't be replaced.

**Comment by ihexxa** [comment]
Closing this old thread 🧵  as the collection runner for UI and CLI have been delivered in the latest release.
Please log a new ticket if there's an issue.
