### ISSUE TITLE
Add support for folder/request group descriptions

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#3306]
Currently, collection descriptions and request descriptions can be added from their respective settings:
<img width="446" alt="image" src="https://user-images.githubusercontent.com/4312346/115331577-452e1800-a1ea-11eb-8f91-f61b852b102d.png">
<img width="420" alt="image" src="https://user-images.githubusercontent.com/4312346/115331593-4cedbc80-a1ea-11eb-9536-39e760f8eb77.png">

However the same does not exist for request groups/folders.

The initial feature request (https://github.com/Kong/insomnia/issues/196) was closed by a PR which only adds UI request descriptions), so there is a clear gap here for request group settings.

I imagine we should change the "rename" button and modal of request group actions to be "Settings", and allow for the addition of a description like the screenshots above.

There is some related conversation here: https://github.com/jozsefsallai/insomnia-documenter/issues/29.

**Comment by jessescn** [comment]
Hey, can i try working on that?

**Comment by NickHackman** [comment]
I'd be happy to work on this as my first feature in Insomnia, just would like some clarification on what the documentation for a folder/group would look like, I assume something similar to a request, but that would require that click on a group/folder would open up a page for docs.

I think opening the docs (in the request view/area) and expanding the folder/group is an obvious and solid approach. It would also have the benefit of being easily expanded upon, allowing in the future to have Folder Plugins as buttons on the far right side of where requests have headers/authorization or other group/folder features (ie: authorization, headers, etc). Anyways, just like to ensure that I'm on the same page here.
