### ISSUE TITLE
[Feature Request] Undoable request/folder deletion

### ISSUE THREAD

**Issue by JayAndCatchFire** [getinsomnia/insomnia#332]
Currently, to delete something, you have to click on delete twice.  This is to confirm it's what you actually want to do.  I appreciate this.  It's certainly better than an "Are you sure?" modal.

But wouldn't it be better if you could delete with a single action and then undo the deletion if necessary?  Just a thought.

**Comment by gschier** [comment]
I think it's fairly subjective whether or not it would be better. 

In my opinion, the current implementation is better in places where accidental clicks are frequent, such as key-value forms (headers, form-data, etc). However, I think for more substantial things like requests/folders/workspaces an undo button makes sense. For example, the user might think they are deleting a certain workspace and not realize they actually deleted a different one until it's too late.

After thinking about it for a minute, I think a more appropriate solution might be to have an "archive" for workspaces/environments/folders/requests. Archived items could then be restored at a later date on the user's demand.

**Comment by gschier** [comment]
Closing this one for now due to its subjectivity and low priority.
