### ISSUE TITLE
Import collection succeeds, but collection doesn't appear

### ISSUE THREAD

**Issue by benovard** [getinsomnia/insomnia#3325]
I'm having an issue when I try to import a collection from a json file. It says that the import succeeds, but the collection never actually shows up in insomnia.

To recreate:
1. 'Import from File' in Insomnia
2. Choose a collection file in json format and import
3. The popup window states that the import was successful
4. Nothing appears in the main window. No api calls, nothing

I have attached an image of the success message.
![image](https://user-images.githubusercontent.com/31526744/116108924-f7962d00-a679-11eb-8f8a-37e4cd9caf81.png)

I've tried uninstalling and reinstalling Insomnia a couple times as well as deleting all the data files. Nothing has worked so far.

**Comment by ereastman616** [comment]
@benovard did you ever get a resolution for this?  I'm having the same issue
