### ISSUE TITLE
Unable to install/update Debian package hosted on Bintray, Bintray services are deprecated

### ISSUE THREAD

**Issue by Leezio** [getinsomnia/insomnia#3326]
**Describe the bug**
The https://dl.bintray.com/getinsomnia/Insomnia repository is no longer accessible.
![Capture d’écran du 2021-04-26 18-48-13](https://user-images.githubusercontent.com/28710712/116121168-a5c4c580-a6c0-11eb-808b-a5d1ac11d6c1.png)
As mentioned here: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/, the services are deprecated

**To Reproduce**
Follow the installation guide, Section Ubuntu/Debian: https://support.insomnia.rest/article/156-installation

**Desktop:**
 - OS: Ubuntu 20.04.02 LTS

**Comment by healeyio** [comment]
It's a scheduled brown-out reminder running on April 26th from 6 am - 2 pm PDT. May 1st is the actual deprecation of bintray.

![image](https://user-images.githubusercontent.com/9313140/116134726-12ba6a00-a685-11eb-84d8-6eac31561e4c.png)

![image](https://user-images.githubusercontent.com/9313140/116134628-fcaca980-a684-11eb-8080-864afa9942a8.png)

**Comment by Leezio** [comment]
> It's a scheduled brown-out reminder running on April 26th from 6 am - 2 pm PDT. May 1st is the actual deprecation of bintray.
> 
> ![image](https://user-images.githubusercontent.com/9313140/116134726-12ba6a00-a685-11eb-84d8-6eac31561e4c.png)
> 
> ![image](https://user-images.githubusercontent.com/9313140/116134628-fcaca980-a684-11eb-8080-864afa9942a8.png)

Oh ! thanks for the precision ^^

**Comment by white-gecko** [comment]
So the new repo is also documented in https://support.insomnia.rest/article/156-installation now, which is:

```
deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all
```
