### ISSUE TITLE
[Bug] Method dropdown persists after "New Request" modal closure

### ISSUE THREAD

**Issue by JayAndCatchFire** [getinsomnia/insomnia#333]
## Overview
- `Insomnia Version:` 5.4.0.610
- `Operating System:` MacOS 10.12.5 (16F73)
- `Summary: ` The method dropdown in the "New Request" modal remains onscreen after the closure of its parent modal.

## How To Reproduce
![32-nodither](https://user-images.githubusercontent.com/10983817/27551514-57c6529c-5a69-11e7-83ba-9338ef69850f.gif)

**Comment by gschier** [comment]
Thanks for reporting this @JayAndCatchFire! It was a quick fix 😄
