### ISSUE TITLE
Unable to collapse some of the folder after drag and drop a folder.

### ISSUE THREAD

**Issue by fd6130** [getinsomnia/insomnia#3330]
**Describe the bug**
When i drag and drop some of my folder to another folder, i think it triggered a bug which cause some of my folder remain open and unable to collapse it.

**To Reproduce**
1. Just drag a folder to another folder
2. The folder which you dragged to will drop collapse (open)  before release the left click.
3. Continue to drag the (1) folder to another folder (without releasing the left click) .
4. After release the left click, the folder you drag is placed at new location.
5. See error.

The above step are not 100% correct since it is occur randomly.

**Expected behavior**
Should be able to collapse (close) the other folder.

**Screenshots**

![image](https://user-images.githubusercontent.com/11419744/116217594-5fcd3780-a77c-11eb-9eae-7b2028a0cbd8.png)

Now I can't collapse (close) the `Property Tag` folder.

**Desktop (please complete the following information):**
 - OS: Zorin OS 15.3
 - Installation Method: download from official website and install from .deb
 - App Version: ~~2021.1.0~~ 2021.2.2

**Additional context**

**Comment by lastnamehurt** [comment]
I'm experiencing the same issue where I'm unable to collapse folders; however, I do not have to perform drag-and-drop. My app behaves like this on load. 

This also means I'm unable to expand already collapsed directories. To work around this, I'm having to duplicate the directory in order to expand, and then change test cases to the expandable directory if any of them are updated.

**Comment by fd6130** [comment]
> I'm experiencing the same issue where I'm unable to collapse folders; however, I do not have to perform drag-and-drop. My app behaves like this on load.
> 
> This also means I'm unable to expand already collapsed directories. To work around this, I'm having to duplicate the directory in order to expand, and then change test cases to the expandable directory if any of them are updated.

Yea current workaround is to duplicate the directory and then remove the bugged one.

**Comment by jackkav** [comment]
fixed in #6323
