### ISSUE TITLE
New update not working on macOS

### ISSUE THREAD

**Issue by MeganClo** [getinsomnia/insomnia#3342]
After the new Insomnia update, I can no longer perform a simple GET request using local server: Have tested multiple APIs and am now always getting "TypeError: Cannot read property '1' of null"

**To Reproduce**
1. I run my server.
2. I have tested that the server is active as I can access the API from my browser and POSTMAN
3. I go into Insomnia and run a GET request on localhost
4. I get a TypeError

**Expected behavior**
I expected that the GET request would behave as expected, before the update. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur /version 11.3
 - Installation Method: automatic update
 - App Version: newest 2021.3.0

**Additional context**
reach out with additional questions
megs.close@gmail.com

**Comment by develohpanda** [comment]
Thank you for reporting! To help us diagnose would you be able to test with an express server we have in the code-base?

Run `npm install` then `npm run serve` in https://github.com/Kong/insomnia/tree/develop/packages/insomnia-smoke-test and a local server will launch at `http://localhost:4010`, and you can hit endpoints such as `/file/dummy.csv` or `/pets/123` to test.

Do you experience the same behavior? I just tested on macOS Catalina 10.15 with that server and it seems to work okay, so it might be something specific with your API and request/response info.

Some other things to try would be to create a brand new request in Insomnia and try hit your API, in case there is any residual filter data in your request. Are you using any template tags or have a JSONPath response filter applied (in the case you're working with JSON)?

Let me know how you get on!

**Comment by MeganClo** [comment]
I have reinstalled again, and messed around with the header settings and finally got it working for me. It must have been an issue here.

**Comment by reynolek** [comment]
Glad you got it working @MeganClo!
