### ISSUE TITLE
apt-get update leads to broken insomnia link  

### ISSUE THREAD

**Issue by minaf1** [getinsomnia/insomnia#3349]
**Describe the bug**
I received this error trying to run apt-get update on my machine:
'E: Failed to fetch https://dl.bintray.com/getinsomnia/Insomnia/InRelease  403  Forbidden [IP: 35.161.90.47 443]'
When I try to go to the above link in a browser, I also get the forbidden error. It seems like the download link is broken.

**Comment by Leezio** [comment]
Same problem on my side.

**Comment by GuilhermeTerriaga** [comment]
Same here.

**Comment by zvalcav** [comment]
Same here. I have one more line explaining the problem:

`E: The repository 'https://dl.bintray.com/getinsomnia/Insomnia  InRelease' is no longer signed.`

**Comment by Steiniche** [comment]
Seems related to this issue from when the apt repo was created: https://github.com/Kong/insomnia/issues/182

**Comment by zvalcav** [comment]
Yes, it may be related. I have tried to reimport `https://insomnia.rest/keys/debian-public.key.asc` key, but it didn't help.

**Comment by DMarby** [comment]
Hi there,

Bintray [recently shut down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) their apt repository hosting which we previously used for Insomnia, which is what's causing the above errors.

Please see the following blog post for information on how to migrate to our new apt repository to resolve the issue: https://insomnia.rest/blog/new-insomnia-apt-repository

**Comment by Steiniche** [comment]
@DMarby thanks for clearing that up.
Will it be possible to get a key instead of using `trusted=yes`?
It could lead to nasty things simply just trusting a repo.

**Comment by DMarby** [comment]
@Steiniche It's not currently possible to get a key for the repo unfortunately.
We are hoping to be able to sign the repo so that we can provide one in the future, but I can't currently provide an ETA as to when that will be.

**Comment by Steiniche** [comment]
@DMarby okay thanks for the update.
What issue is the progress tracked in?

**Comment by Ldev007** [comment]
@DMarby Thanks for the update finally resolved it !
