### ISSUE TITLE
Manage Environment Modal doesn't respect Filter Responses by environment

### ISSUE THREAD

**Issue by NickHackman** [getinsomnia/insomnia#3354]
**Describe the bug**
Template Tags that rely on `Filter Responses by Environments` are incorrectly evaluated when the active environment differs from the selected in the Manage Environments modal. This doesn't actually impact the environments or the values, but they're displayed improperly as it doesn't factor in that the selected environment and active environment aren't the same. 

**To Reproduce**
1. Check `Filter responses by environment` in Settings
2. Create a Template Tag Response that varies based on environment (say a JWT)
3. Have Response run and create the JWT in one environment (should be valid)
4. Have Response run and create the JWT in another environment (should be valid)
5. Open `Manage Environment` modal
6. Switch environments
7. See that the Environment specific variable isn't evaluated properly and depends on the active environment
8. Be confused why your plugin isn't working and has bizarre behavior 😆 

**Expected behavior**
The `Manage Environment` Modal should evaluate Template Tags with respect to `Filter responses by environment`. 

**Screenshots**
Can't because the values are JWTs

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Installation Method: Downloaded from website
 - App Version: v2021.3.0

**Additional context**

**Comment by filfreire** [comment]
Hi @NickHackman, sorry for not getting back to this sooner. We recently fixed [a similar issue](https://github.com/Kong/insomnia/commit/e5084c9335ddb3689b6359e035b3e7f2dc939afd). 

Are you still able to reproduce this issue in our [latest release](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)?


I'm not able to reproduce as of now, using [this jwt token creator](https://www.npmjs.com/package/insomnia-plugin-jwtcreator). Here's two screenshots as example, each with it's own JWT generated, and a fixed env var:
<img width="1237" alt="Screen Shot 2022-05-10 at 09 10 48" src="https://user-images.githubusercontent.com/11976836/167581153-3c2ce6bf-209e-49a4-81e7-d01aa5b161d7.png">
<img width="1246" alt="Screen Shot 2022-05-10 at 09 10 55" src="https://user-images.githubusercontent.com/11976836/167581163-ecaaa77f-8a00-44cd-9cc5-7c03bc53b013.png">

**Comment by wongstein** [comment]
Closing this issue due to lack of response and activity.
