### ISSUE TITLE
Snap package is broken for Ubuntu 20.04

### ISSUE THREAD

**Issue by selivan** [getinsomnia/insomnia#3355]
**Describe the bug**

On Ubuntu 20.04  Insomnia installed with snap package crashes with an error:

`ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.`

**To Reproduce**

* Use Ubuntu 20.04 with latest updates
* `sudo snap install insomnia`
* `insomnia`

**Expected behavior**

Application launches.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation Method: snap
 - App Version: `latest/stable: 2021.3.0 2021-04-28 (132) 100MB`

**Additional context**

Insomnia installed from repository at https://download.konghq.com/insomnia-ubuntu/ works fine.

Restarting `snapd.service` (advice from documentation on installation) didn't help.

```
$ cat /etc/os-release  | grep VERSION
VERSION="20.04.2 LTS (Focal Fossa)"

$ snap info insomnia
name:      insomnia
summary:   Insomnia REST Client
publisher: Insomnia (gschier1990)
store-url: https://snapcraft.io/insomnia
contact:   https://support.insomnia.rest
license:   unset
description: |
  A powerful HTTP and GraphQL Client with cookie management, environment variables, code generation,
  and authentication for Mac, Window, and Linux.
commands:
  - insomnia
snap-id:      ZtF4mLp5Bededu3S65ocO6HfGXCtcvZ9
tracking:     latest/stable
refresh-date: today at 21:43 MSK
channels:
  latest/stable:    2021.3.0 2021-04-28 (132) 100MB -
  latest/candidate: ↑                               
  latest/beta:      ↑                               
  latest/edge:      2021.3.0 2021-04-28 (132) 100MB -
installed:          2021.3.0            (132) 100MB -

$ /snap/bin/insomnia
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
```

**Comment by filfreire** [comment]
@selivan are you still facing this issue with [latest Insomnia version (2021.7.2)](https://github.com/Kong/insomnia/releases/tag/core@2021.7.2)?

**Comment by filfreire** [comment]
bump 

@selivan we have since last time update a few dependencies that were causing problems when running Insomnia on some distros. Are you by any chance still facing this issue with [latest insomnia](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)?

**Comment by selivan** [comment]
> bump
> 
> @selivan we have since last time update a few dependencies that were causing problems when running Insomnia on some distros. Are you by any chance still facing this issue with [latest insomnia](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)?

I am not using Ubuntu as desktop system anymore, so I can not check if the issue was fixed. I suppose this can be closed.
