### ISSUE TITLE
Unable to install on Debian Bullseye due to libappindicator3 dependency

### ISSUE THREAD

**Issue by Trim** [getinsomnia/insomnia#3357]
**Describe the bug**

I'm unable to use the provided `.deb` package to install Insomnia on Debian Bullseye (which is currently the testing release).

The error from `dpkg` is clearly indicating the issue is due to the dependency of `libappindicator3`:

```
$ sudo dpkg -i Insomnia.Core-2021.3.0.deb 
Selecting previously unselected package insomnia.
(Reading database ... 454024 files and directories currently installed.)
Preparing to unpack Insomnia.Core-2021.3.0.deb ...
Unpacking insomnia (2021.3.0) ...
dpkg: dependency problems prevent configuration of insomnia:
 insomnia depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.

dpkg: error processing package insomnia (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for gnome-menus (3.36.0-1) ...
Errors were encountered while processing:
 insomnia
```

As announced in the Debian Bug Tracker, libappindicator3 will be indeed removed from Debian: [#895037](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037).

From this bug report, it seems there's a maintained alternative named `libayatana-appindicator`, but it requires patching insomnia to be usable.

Fortunately [libayatana-appindicator is also available on Ubuntu](https://packages.ubuntu.com/search?keywords=libayatana-appindicator), but I don't know if it's currently used by default on Ubuntu, as I don't use Ubuntu myself.

**Expected behavior**

I expected to be able to install Insomnia on Debian Bullseye even if `libappindicator3` is not available.

**Desktop (please complete the following information):**
 - OS: Debian Bullseye
 - Installation Method: debian package
 - App Version: 2021.3.0

**Additional context**

As libappindicator3 should not be a core dependency, I suggest to update the debian package to __recommend__ libappindicator3 instead to depend on it.

For your information, I've tried to directly hack the application `.deb` package by doing libappindicator3 only a recommendation:

```diff
diff --git a/control b/control
index 5b67e56..2a6311e 100644
--- a/control
+++ b/control
@@ -5,7 +5,8 @@ Vendor: Kong <office@konghq.com>
 Architecture: amd64
 Maintainer: Kong <office@konghq.com>
 Installed-Size: 369838
-Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libappindicator3-1, libsecret-1-0
+Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0
+Recommends: libappindicator3-1
 Section: default
 Priority: extra
 Homepage: https://konghq.com
```

(to hack the debian package, I've followed [this article](https://coderwall.com/p/hes3ha/change-the-dependencies-of-a-deb-package))

With such modification I was able to install and run Insomnia on Debian Bullseye.

**Comment by CLTanuki** [comment]
Same for version 2021.5.2
![Screenshot at 2021-09-03 14-21-05](https://user-images.githubusercontent.com/5824716/131997881-88b84080-0f7e-4bf0-b610-37ef7a91f5cd.png)
Thanks @Trim for solution. Waiting for an official patch, as a paying customer.

**Comment by CLTanuki** [comment]
Now Bullseye is stable Debian release and version 2021.5.3 is still non-installable.
Please, fix this, because even after repacking it throws errors.
Still paying, but not using.

**Comment by carxwol** [comment]
2021.7.2 is still non-installable on Debian bullseye due to libappindicator3-1 instead of libayatana-appindicator3-1.

I had the same problem with slack, but i was able to unpack, fix debian/control and repack like this https://stackoverflow.com/a/69087954

It's not possible with your Debian package.

Please consider this issue.

**Comment by felixdst** [comment]
I ran into the same issue and ended by downloading the two packages `libindicator3-7` and `libappindicator3-1` from the debian buster repository and install it with apt. After that you can install the .deb-Package version 21.7.2. 

This solution worked for me.

**Comment by Eduard-gan** [comment]
Alternatively you can add old repo paths:

append to /etc/apt/sources.list

```
deb http://deb.debian.org/debian buster main contrib non-free
deb-src http://deb.debian.org/debian buster main contrib non-free
```

**Comment by Trim** [comment]
I was able to install the upstream 2022.4.1 Ubuntu package on Debian Bullseye.

Thanks !
