### ISSUE TITLE
OAuth secret can't contain Nunjucks comment symbols

### ISSUE THREAD

**Issue by LeandroBarone** [getinsomnia/insomnia#3365]
My OAuth secret cointains the Nunjucks comment opening symbol `{#`, so this request can't be made:

![image](https://user-images.githubusercontent.com/8425029/117452506-377ecf00-af1a-11eb-9164-47b9acb5fc70.png)

My workaround was generating a different secret that doesn't include `{#`

**Comment by madrigal1** [comment]
in insomnia, nunjunks environments are used to get the definitions of the template tags

relevant file:
insomnia-app->app->templating->index.ts
function: getTagDefinitions

official docs reference:
https://support.insomnia.rest/article/171-template-tags

**Comment by kreosus** [comment]
Hi @madrigal1, are you able to reproduce the issue on our latest release: https://github.com/Kong/insomnia/releases/tag/core%402022.7.5?
