### ISSUE TITLE
[Bug] Window do not restore maximized state on start

### ISSUE THREAD

**Issue by SylwesterZarebski** [getinsomnia/insomnia#339]
## Overview
- `Insomnia Version:` 5.4.0
- `Operating System:`  Windows 10 v 1607 (Anniversary Update) - Polish version
- `Summary: ` Window on start do not restore maximized state (when closing) and is slightly off to left and up.

## How To Reproduce
1. Open Insomnia on Windows
2. Maximize window
3. Close Insomnia
4. Reopen Insomnia and see that window is not maximized

## What is expected
Window is maximized on start when has been closed in maximized state.

**Comment by gschier** [comment]
I'm a Mac user (Mac doesn't have maximize) so I never noticed this. Should be working in the next update. Thanks @SylwesterZarebski!

**Comment by SylwesterZarebski** [comment]
Thanks a lot for Your great work :).

**Comment by gschier** [comment]
No problem!
