### ISSUE TITLE
Allow Git Sync to target local filesystem

### ISSUE THREAD

**Issue by rbedger** [getinsomnia/insomnia#3403]
**Is your feature request related to a problem? Please describe.**
The Git Sync feature doesn't work with my company's self-hosted BitBucket instance, which uses a self-signed, internal certificate.

**Describe the solution you'd like**
Allow the Git Sync feature to simply target a repository on disk, leaving the git push up to the user.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by sethgw** [comment]
☝️
