### ISSUE TITLE
Long file name should break line

### ISSUE THREAD

**Issue by danitrod** [getinsomnia/insomnia#3412]
**Describe the bug**

Using Multipart form, when sending a file as body, if the file has a very large name, it minimizes the field name so it can't be seen.

**To Reproduce**
1. Create any request
2. Add a body of Multipart form and add a field of type file
2. Add a file with a long path name to the field value
4. See that the filename occupies the whole section, hiding the field name

**Expected behavior**

The field name should be displayed entirely, and the long file name should be either cropped, as it is, displaying a tooltip with the complete path when hovering, or more interestingly break a line and show the entire path.

**Screenshots**

<img width="1130" alt="Captura de Tela 2021-05-20 às 23 32 13" src="https://user-images.githubusercontent.com/45438149/119073401-a43aa480-b9c3-11eb-8497-b01cf83d2ae5.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.3.1 (don't mind the windows-like path)
 - Installation Method: Homebrew
 - App Version 2021.3.0

**Comment by thewheat** [comment]
Looks like current behaviour has changed since this report and the behaviour is

- it just displays the file name without the path
- hovering shows the full path

![image](https://user-images.githubusercontent.com/892961/136534278-ace7f1f8-899a-4e45-b09a-5e025433130f.png)

**Comment by kreosus** [comment]
Hi @thewheat, have you tried to see if this issue is still happening with our newest release, located here: https://github.com/Kong/insomnia/releases/tag/core%402022.7.5. Thank you.

**Comment by jackkav** [comment]
perhaps only showing the file name is best, @danitrod thanks for the report. Welcome to contribute a fix.

**Comment by andrea-mauro** [comment]
I think this issue should be closed since in the latest release the multipart form shows a button for the file with only the file name as a label and a hover to reveal the complete file path
<img width="563" alt="image" src="https://github.com/Kong/insomnia/assets/54074100/4bbc4696-c891-47cc-90a2-069a3b873a19">
