### ISSUE TITLE
[Feature] AWS Authentication/Signing

### ISSUE THREAD

**Issue by focusaurus** [getinsomnia/insomnia#344]
## Overview
- `Insomnia Version:` 5.5.2
- `Operating System:`  macOS 10.12.5
- `Summary: ` Would like to be able to do use AWS IAM credentials and make signed requests to AWS services

## Other Notes

The node.js `request` module has built-in support for this and it comes in handy. I don't know all the details but the end user provides AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY (for non-MFA accounts) and the timestamp and some headers are factored into a digest that gets calculated. MFA-enabled accounts are a bit trickier and also require AWS_SESSION_TOKEN.

In the mean time, I have worked around this by using a node.js script and the `request` package.

**Comment by gschier** [comment]
Hey @focusaurus. The signing seems like a straightforward process. 

AWS has some docs (along with Python source code examples) here: http://docs.aws.amazon.com/general/latest/gr/sigv4_changes.html

Would you be interested in taking a shot at implementing this? If not, I should be able to get around to it, eventually.

**Comment by focusaurus** [comment]
OK taking a crack at this. Almost certainly will need some commits from you to get into mergable shape but I'll see how much I can get working locally basing code off existing patterns for AUTH_NTLM.

**Comment by focusaurus** [comment]
Have the UI rendering OK and just got my first 200 OK back from AWS so getting the basics in place is looking promising so far.

**Comment by gschier** [comment]
@focusaurus that's awesome! Nice work.

I don't mind throwing some of my own commits at this, as long as you can get the hard part (request signing algorithm) working. It's probably also a good idea to put this into its own function with some basic tests, if you haven't done that already.

**Comment by focusaurus** [comment]
FYI the signing algorithm there's the `aws4` package on npm which I have integrated and working nicely. We don't need to implement the guts of the signing from scratch, just get the options and credentials ready to pass to `aws4`. No tests yet but will look at that next. The code structure follows the pattern in place for NTLM.

**Comment by gschier** [comment]
Oh nice. May not be worth writing tests if the `aws4` package handles all the hard parts 👍
