### ISSUE TITLE
My requests panel is gone....?

### ISSUE THREAD

**Issue by HeCorr** [getinsomnia/insomnia#3444]
**Describe the bug**
The requests panel, containing all the collection's requests is just... gone.. and I can't get it to show again..
I tried restarting multiple times, zooming in and out.. nothing works.

**To Reproduce**
I have **no** idea.

**Expected behavior**
The panel wouldn't be gone and I would be able to show it again / reset the layout.

**Screenshots**
![image](https://user-images.githubusercontent.com/75134774/120679552-ab57bd00-c46f-11eb-8778-3f9a5d230f6d.png)

**Desktop:**
 - OS: Windows 10
 - Installation Method: Installer I think
 - App Version `v2021.3.0`

**Comment by HeCorr** [comment]
I tried creating a new collection and the panel is there, but it's still gone from the main collection:

![image](https://user-images.githubusercontent.com/75134774/120679990-2faa4000-c470-11eb-8596-4ba2f85c794b.png)

**Comment by HeCorr** [comment]
~~I also tried the "Toggle Sidebar" shortcut but it does nothing. Not even in the collection that has the panel visible.~~

Nevermind.. that was it.. for some reason it wasn't recognizing the `\` key in the default shortcut `Ctrl + \`.
I set it to `Ctrl + Alt + Shift + P` and it works.

Also I just noticed that there's a "Toggle Sidebar" option in the View menu.. *facepalm*

**Comment by dimitropoulos** [comment]
no worries, have a good day, at least :)
