### ISSUE TITLE
Not all fixed width fonts are listed

### ISSUE THREAD

**Issue by mdcclxv** [getinsomnia/insomnia#3488]
**Describe the bug**
In the settings window, "Text Editor Font" doesn't show all fixed width fonts. In fact it shouldn't even have this "fixed width" limitation, showing ALL fonts would be the best.

**To Reproduce**

**Expected behavior**
Show all fixed width fonts. Better yet, show all fonts, give the user freedom.

**Desktop (please complete the following information):**
Windows 10

**Comment by dimitropoulos** [comment]
So that we can reproduce this more easily: please share information about the font you want to see but can't (as well as, please share the font file format).

**Comment by mdcclxv** [comment]
I've attached the font that I can't see.

[TerminusTTF-4.47.0.zip](https://github.com/Kong/insomnia/files/6701362/TerminusTTF-4.47.0.zip)

**Comment by dimitropoulos** [comment]
Thank you very much.  While I can't provide an estimate on when we'll get to this (the team is very focused on a new feature, "spaces" right now), it will really speed things up to have this to test with when we are prioritizing this.

As always, I welcome  you to make a PR if you'd like to expedite the process.

**Comment by filfreire** [comment]
Hi @mdcclxv, we no longer display a list of fonts, but you should be able to use fixed width fonts both on UI and text editor of Insomnia:
<img width="390" alt="Screenshot 2022-07-25 at 14 27 02" src="https://user-images.githubusercontent.com/11976836/180788403-5b67e294-3493-477a-a9c4-1eb0cafc094d.png">

<img width="758" alt="Screenshot 2022-07-25 at 14 26 05" src="https://user-images.githubusercontent.com/11976836/180788415-b28b6b01-5b2a-4d0d-b64f-01e3b3fe3c1d.png">
