### ISSUE TITLE
Allow multiple results for JSONPath in JSON bodies

### ISSUE THREAD

**Issue by keklabs** [getinsomnia/insomnia#3490]
**Describe the bug**
The JSONPath is not working in situations where the result is Array of values.  But it should be supported, because I can have the request, where the result is collection of JSON objects and I need to select IDs by JSONPATH query  and the resulting Array should be provided as single value of Array type

**To Reproduce**
1) Call some  REST API with  LIST of JSON objects as response
2) Use JsonPath to select values from previous response
3) expresion like `$.result[0].itemid` is working, but we need choose all items, so `$.result[*].itemid`  - but this is not working

**Expected behavior**
 resulting Array should be provided as single value of Array type

**Screenshots**

![image](https://user-images.githubusercontent.com/2360881/122807044-60410500-d2cb-11eb-8a12-12e8f7710988.png)

**Desktop (please complete the following information):**
Version: Insomnia 2021.3.0
Release date: 4/28/2021
OS: Windows_NT x64 10.0.19043
Electron: 9.3.5
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0-DEV OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.41.0

**Additional context**

https://github.com/Kong/insomnia/issues/944   - because there is no response to closed issue, I reopened this new one.

**Comment by dimitropoulos** [comment]
I'd rather not duplicate issues: and so I've reopened the old one that the stalebot closed.

**Comment by jquexxx** [comment]
this is also true when getting "Bearer 1234567890" for header Authorization

{
  "token_type": "Bearer",
  "access_token": "1234567890",
...
}



Returned more than one result: $..[token_type,access_token]
