### ISSUE TITLE
[Bug] Template variable 'now' behaves strangely

### ISSUE THREAD

**Issue by VladV** [getinsomnia/insomnia#350]
## Overview
- `Insomnia Version:` 5.5.2
- `Operating System:`  Windows
- `Summary: ` "now" is inconsistently processed by the filters. Preview on hover works as expected, but the real request is broken.

## How To Reproduce
Example: POST request with JSON body.
```
{
	"t1": "{{now}}",
	"t2": "{{now | urlencode}}",
	"t3": "{{now | replace('Z', '+0000')}}",
	"t4": "{% now 'custom', 'YYYY-MM-DDTHH:mm:ssZZ' %}"
}
```
Rendered like this:
```
> POST / HTTP/1.1
> Host: localhost
> User-Agent: insomnia/5.5.2
> Accept: */*
> Accept-Encoding: deflate, gzip
> Content-Type: application/json
> Content-Length: 152
| {
| 	"t1": "2017-07-10T17:30:56.297Z",
| 	"t2": "%7B%25%20now%20'ISO-8601'%20%25%7D",
| 	"t3": "2017-07-10T17:30:56.297Z",
| 	"t4": "2017-07-10T20:30:56+0300"
| }
```
It seems, "now" is fed to the filters as a literal value, not a substituted timestamp.
{% now %} works as expected (but cannot be used with filters?).

**Comment by gschier** [comment]
Quick question. To get `{{ now }}` to work, did you set it as a variable in your environment? If so, can you attach your environment configuration as well?

Note: I've already reproduced this on my end, but wanted to clarify before going further.

**Comment by gschier** [comment]
I have addressed this in the PR linked above ^

Here's what it looks like now (as it should have from the start):

```
> GET / HTTP/1.1
> Host: insomnia.rest
> User-Agent: insomnia/5.5.2
> Accept: */*
> Accept-Encoding: deflate, gzip
> Cookie: __cfduid=d043e237717ba12d6964b5fe50d8cb3e81499109443
> Content-Type: application/json
> Content-Length: 158
| {
| 	"t1": "2017-07-10T15:22:13-07:00",
| 	"t2": "2017-07-10T15%3A22%3A13-07%3A00",
| 	"t3": "2017-07-10T15:22:13-07:00",
| 	"t4": "2017-07-10T15%3A22%3A13-07%3A00"
| }
* upload completely sent off: 158 out of 158 bytes
```

**Comment by VladV** [comment]
Sorry, my bad. It is defined as `"now": "{% now 'ISO-8601' %}"`, I completely forgot that and assumed "now" being a builtin.

Thanks for the timely fix!

**Comment by gschier** [comment]
No problem!
