### ISSUE TITLE
Snap crashes when opening 'Help' > 'About' in Ubuntu 21.04

### ISSUE THREAD

**Issue by santiagofn** [getinsomnia/insomnia#3505]
**Describe the bug**

Installed insomina 2021.3.0 using snap in Ubuntu 21.04.  When trying to open 'Help' > 'About', the app crashes.

**To Reproduce**

1. Go to 'Help'
2. Click on 'About.'
3. The app crashes

**Expected behavior**

The 'About' window should be opened.

**Screenshots*

https://user-images.githubusercontent.com/8375708/123530327-4a6a8000-d6cf-11eb-8cd6-9e8ed2bc6a7c.mp4

**Desktop:**
 - OS: Ubuntu 21.04
 - Installation Method: snap
 - App Version 2021.3.0

**Additional context**

This is the info shown in the terminal debug:

```
22:20:30.630 › [ga] Page /debug

(insomnia:217360): Gtk-WARNING **: 22:20:39.242: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/insomnia/132/data-dir/icons/Yaru/48x48/status/image-missing.png: Unable to load image-loading module: /snap/insomnia/55/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/insomnia/55/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
Aborted (core dumped)
```

**Comment by filfreire** [comment]
@santiagofn are you still able to reproduce this on latest 2021.7.2? 

Here's my attempt on that version, using Kubuntu 21.10 and installing/running with snap:
![Screenshot 2021-12-16 at 17 39 19](https://user-images.githubusercontent.com/11976836/146421481-87715275-5660-4fd0-a5e0-d50b04bc9ed9.png)

**Comment by santiagofn** [comment]
Hi @filfreire! I've gave it shot with my current Ubuntu (21.10) and the bug isn't reproducible any more:

![image](https://user-images.githubusercontent.com/8375708/146644388-31efbd3f-9700-49ba-9085-c36bebcd8607.png)

Thanks!
