### ISSUE TITLE
[Suggestion] Provide snap package to support all GNU/Linux distributions

### ISSUE THREAD

**Issue by nmabhinandan** [getinsomnia/insomnia#354]
Snaps are universal Linux packages which work on any distribution or device. Snaps are faster to install, easier to create, safer to run, and they update automatically and transactionally so your app is always fresh and never broken. Snap packages are supported by all major Linux distributions and integrate well with desktop environments.

#### Ref:
https://snapcraft.io
https://build.snapcraft.io
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

**Comment by owais** [comment]
This would be great as it would give users an auto updating channel and would work on major linux distributions.

**Comment by daincredibleholg** [comment]
I would also love to see this as a Snap - I love the frequent updates, but having them applied during my (semi-)daily `sudo snap refresh` would make it perfect

**Comment by flexiondotorg** [comment]
Please see pull request #688 :smile:

**Comment by gschier** [comment]
It's here! https://snapcraft.io/insomnia
