### ISSUE TITLE
[Question] `Chaining Requests`  accessToken set expire date

### ISSUE THREAD

**Issue by xinshangshangxin** [getinsomnia/insomnia#356]
## Overview
- `Insomnia Version:` 5.4.0.610
- `Operating System:` 10.12.5 (16F73)

some api have call limit, like access-token;
when i request access-token, it will return `expireTime`, like:
```js
{
   token: 'XXXX',
   expireTime: 3600,
}
```

then, i can use token in an hour; and the request limit 200 times;

if use `Chaining Requests`, is it preRequest every time when i call the real request?

**Comment by gschier** [comment]
Currently, previous requests in a "chain" are not sent at all. In order to refresh a value you are using, you must go to that request and send it again manually. 

Automatic sending of chained requests will come in a future version.
