### ISSUE TITLE
[Suggestion] Generated Curl does not work with Postman import

### ISSUE THREAD

**Issue by xinshangshangxin** [getinsomnia/insomnia#361]
## Overview
- `Insomnia Version:` _(e.g. 5.0.2)_
- `Operating System:`  _(e.g. MacOS 10.12.4 (16E195))_
- `Summary: ` _(A few sentences describing the issue. Try to include as much detail as possible.)_

although I use insomnia,  colleague use postman.
postman not support the curl text export from insomnia (the url must put at first, not as a param)
and if there many request, I can not export many curl text
thanks~

**Comment by gschier** [comment]
I appreciate the suggestion @xinshangshangxin.

This seems like an issue that should be fixed on Postman's end. The `--url http://myurl.com` flag is perfectly valid and should be handled properly by Postman. 

Insomnia's Curl requests are generated by [`httpsnippet`](https://github.com/Mashape/httpsnippet) so there isn't much I can do here, unfortunately.

**Comment by xinshangshangxin** [comment]
if there many request, I can not export many curl text
is there any export json postman format to reimport to postman?
