### ISSUE TITLE
[Feature Request] Collapse attributes

### ISSUE THREAD

**Issue by kud** [getinsomnia/insomnia#362]
We already can collapse objects but it'll be great to be able to collapse also attributes. I've got some huge responses like attribute `text` I would like to collapse. :)

**Comment by gschier** [comment]
Hi @kud! 

The collapsing functionality is currently provided by the [Codemirror](https://codemirror.net/) text editor. I don't have time at the moment to look into such a minor feature, but I'd be happy to take a look at a PR if you feel like making an attempt at this.

**Comment by gschier** [comment]
Closing this one for now
