### ISSUE TITLE
[Feature Request] Option to select timezone for Timestamp tag

### ISSUE THREAD

**Issue by jainr1** [getinsomnia/insomnia#363]
Currently for Timestamp tag local timezone is used by default, but there should be an option to select timezone/ or timezone offset for date format.
eg:
moment().tz($timeZone).format($format);
moment().tz('utc').format('DD MM YYYY HH:mm:ss');

**Comment by maxsitu** [comment]
Anyone looking into this? I think it is useful especially for authentication/authorization

**Comment by crstauf** [comment]
Just now running into this issue myself; disappointing to see it was brought up (over a year ago) but hasn't been tended to. 😞

**Comment by thanhtoan1196** [comment]
I also encountered the same problem, I solved using this plugin with the function: Add / Subtract time from current time
https://github.com/Gabb1995/insomnia-plugin-customtimestamp
