### ISSUE TITLE
[Improvement] Request Parameter Description

### ISSUE THREAD

**Issue by xinshangshangxin** [getinsomnia/insomnia#364]
## Overview

- if I write url like `http://www.example.com/api/v1/:organization/test?a=1`, postman will parse organization to be a param, then I can set different value like query params, 
- at the end, there is a `Description` input,  I can set rules or other information. I do not want to write description to  `insomnia` `Docs Tab` 

![image](https://user-images.githubusercontent.com/8779091/28347160-01e9a606-6c68-11e7-85dd-9a5ee7f673ae.png)

![image](https://user-images.githubusercontent.com/8779091/28347136-d7b448f0-6c67-11e7-91ae-11289f3da03e.png)

**Comment by gschier** [comment]
Hi @xinshangshangxin. I have renamed this issue to be request parameter description, because your first point is already being tracked on #203

**Comment by ggicci** [comment]
Looking forward to this enhancement!

**Comment by starx** [comment]
I also think having a description of the parameters would be good. Maybe the docs should pull these descriptions as well.

**Comment by gschier** [comment]
FYI This was implemented a couple releases ago by https://github.com/Kong/insomnia/pull/1789
