### ISSUE TITLE
[Bug] Cmd+Enter for sending request in "JSON" Tab creates new line

### ISSUE THREAD

**Issue by Gennnji** [getinsomnia/insomnia#365]
## Overview
- `Insomnia Version:` 5.6.3
- `Operating System:` MacOS 10.12.5 (16F73)
- `Summary: ` I'm trying to send request with JSON body by Cmd+Enter. While request is being sent, Enter creates new line in JSON tab.

## How To Reproduce
1. Create new request with JSON body and application/json Content-Type
2. Focus JSON tab and press Cmd+Enter
3. You can see successful response and a new empty line under cursor

**Comment by gschier** [comment]
I've heard someone else mention this before. I think it only happens with the `sublime` keymap? Not quite sure whether it would be better to try and disable the Sublime keymap, or not send the request under this keymap.

As a temporary workaround, you can also use CMD+R or F5 to send requests.
