### ISSUE TITLE
[Bug] Click and drag to select has some quirks

### ISSUE THREAD

**Issue by cinnamennen** [getinsomnia/insomnia#366]
## Overview
- `Insomnia Version:` 5.5.2
- `Operating System:`  10.12.5 (16F73)
- `Summary: ` When clicking and dragging in the main bar, if the cursor ends the motion while being outside the bar, the selection is completely invalidated.

## How To Reproduce
1. Click and hold within the status bar to start selection.
2. Drag to the end of selection.
3. Keep dragging past the end of the bar (e.g. past `Send`)
4. See that the selection is invalidated.

## Other Notes
For context, I keep running into this primarily when I am trying to quickly modify the end of a URL.

**Comment by gschier** [comment]
Hmm, can you provide a screencast of this? I can't seem to reproduce it. Here's my attempt, which seems to behave correctly.

![screenflick movie 16](https://user-images.githubusercontent.com/587576/28377658-6652455e-6c62-11e7-9ff6-488d0749382a.gif)

**Comment by cinnamennen** [comment]
Made a video [here](https://www.dropbox.com/s/43tyc0dnc5trfmy/insomnia%20demo.mov?dl=0)

**Comment by gschier** [comment]
Hey @cinnamennen. Was able to reproduce this and finally got a fix in!
