### ISSUE TITLE
[Improvement] To add a feature to work with RAML, Swagger, Paw, Postman…

### ISSUE THREAD

**Issue by IlyaBelitser** [getinsomnia/insomnia#367]
To add a feature to work (import/export) with RAML, Swagger, Paw, Postman…

**Comment by gschier** [comment]
Closing as a duplicate of #281

**Comment by JayAndCatchFire** [comment]
https://github.com/getinsomnia/importers/issues/13
https://github.com/getinsomnia/importers/issues/14
