### ISSUE TITLE
[Feature Request] Beautify XML on response

### ISSUE THREAD

**Issue by vision8tech** [getinsomnia/insomnia#368]
## Overview
- `Insomnia Version: 5.6.3`
- `Operating System: Windows / OSX`
- `Summary: "Beautify XML" on response`

Working with SOAP-based services, it is very useful to have the same `Beautify XML` feature available on response as it is already available on request.

![image](https://user-images.githubusercontent.com/14140226/28468053-80d86820-6e3a-11e7-8fc1-64e56ac0213d.png)

Thanks!

**Comment by gschier** [comment]
@vision8tech Insomnia currently does this already, but relies on `Content-Type: application/xml` to  to tell whether or not it's XML. Maybe a solution could be to also look for `<?xml version="1.0" encoding="UTF-8"?>` in the document if the `Content-Type` header is missing?

![image](https://user-images.githubusercontent.com/587576/28473614-36cf0436-6dfa-11e7-98f4-4e251d24a400.png)
