### ISSUE TITLE
[Feature Request] Option to save the response

### ISSUE THREAD

**Issue by vision8tech** [getinsomnia/insomnia#369]
## Overview
- `Insomnia Version: 5.6.3`
- `Operating System: Windows / OSX`
- `Summary: Option to save also the response`

One useful option is to save the response corresponding to the request previously sent.
This is one of the nice things that exists on SoapUI.

Thanks.

**Comment by gschier** [comment]
Hi @vision8tech. You can already do this in two ways.

1. Click "Save Response" at the bottom of the dropdown on the response preview tab
2. Right-click the "Send" button and set the request to "Download After Send"

Let me know if that is what you meant.

![image](https://user-images.githubusercontent.com/587576/28473491-a77d6714-6df9-11e7-9019-7cdc62e405c9.png)

![image](https://user-images.githubusercontent.com/587576/28473483-a0174e68-6df9-11e7-9dce-1505163853d1.png)

**Comment by vision8tech** [comment]
Hi Gregory,

Thanks for the feedback. I know that I can save the response to an external resource (e.g. file).

What I was mention is to persist the response (of the last time the request was saved, as an option) of specific/all requests.

The scenario looks like this:
1. Click a request on the workspace (left side).
2. The request is open.
3. The response of the request may also open.

If there is an option to save the response of the request, later on the user can simply browse and study the API, having both request & response available.

I have noticed right now that most (if not all) of the requests that were sent and have a successful response (not a 404, for example) keep also the response. I assume that actually this is already happening and therefore I should close this issue.

**Comment by gschier** [comment]
Hey @vision8tech. I'm still not quite sure what you are asking. 

> I have noticed right now that most (if not all) of the requests that were sent and have a successful response (not a 404, for example) keep also the response. I assume that actually this is already happening and therefore I should close this issue.

Right now, the last 20 responses for each request are persisted regardless of the status code (2XX/3XX/4XX/5XX). I _think_ this is what you are asking for so I'm going to close this issue for now. Feel free to re-open and clarify in more detail what you are wanting.

**Comment by vision8tech** [comment]
Hi @gschier ,

That is exactly what I was looking for and it is great that the feature already exists.
But could you please increase (or at least to be configurable) the number of saved responses, please?

Thanks!
