### ISSUE TITLE
[Feature Request] Make the URL PREVIEW editable

### ISSUE THREAD

**Issue by roblav96** [getinsomnia/insomnia#370]
![img](http://i.imgur.com/1wofvxy.png)
Making this editable would be awesome since the top input field is always so small =]

**Comment by gschier** [comment]
I feel like this is solving the problem in the wrong way. I'd rather come up with a solution to make the top bar more usable. Maybe show multiple lines in the top bar if it has focus?

**Comment by roblav96** [comment]
Something like that. The biggest problem I see is that when you need to change something at the very end of the URL. I just feel like there's gotta be a better way.

**Comment by gschier** [comment]
Closing this one as stale for now.
