### ISSUE TITLE
[Development] npm install errors on windows.

### ISSUE THREAD

**Issue by keesee** [getinsomnia/insomnia#372]
I seem to be having issues with NPM install on windows. 
Hangs for a bit few seconds and then  errors out.

I see the following in my  npm debug log.  seems to be related to node-libcurl. 

2124 verbose afterAdd C:\Users\jimmy\AppData\Roaming\npm-cache\codemirror\5.28.0\package\package.json written
2125 error git fetch -a origin (git://github.com/getinsomnia/node-libcurl.git) fatal: read error: Invalid argument
2126 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true fetch -a origin
2126 silly fetchPackageMetaData fatal: read error: Invalid argument
2126 silly fetchPackageMetaData
2126 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:205:12)
2126 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
2126 silly fetchPackageMetaData     at ChildProcess.emit (events.js:194:7)
2126 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:899:16)
2126 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
2126 silly fetchPackageMetaData  error for node-libcurl@git://github.com/getinsomnia/node-libcurl.git#b3968130cbaeef6b432e617a5e835baf0f856880 { Error: Command failed: git -c core.longpaths=true fetch -a origin
2126 silly fetchPackageMetaData fatal: read error: Invalid argument

any thoughts on resolving this?  Thanks in advance.  :)

**Comment by gschier** [comment]
Hmm, I'm not sure what this could be @keesee. It looks like the Git command to install `node-libcurl` is failing. What version of Git do you have installed on your Windows machine?.

This seems less related, but you also need to make sure you have the requirements installed to build `node-libcurl` on Windows? https://github.com/JCMais/node-libcurl/#window

**Comment by gschier** [comment]
Hey @keesee,

I just spent the last day fixing a Windows-specific bug, and ran into this same problem. I ended up converting all Git npm dependencies to regular dependencies to get around it. If you pull down the latest `develop` branch it should (hopefully) work for you.

**Comment by gschier** [comment]
Going to close this one for now, but I will reopen if it still doesn't work for you.
