### ISSUE TITLE
Export did not work anymore in version 2021.4.0

### ISSUE THREAD

**Issue by mreduar** [getinsomnia/insomnia#3777]
**Describe the bug**
When exporting the insomnia configuration it does not export a valid json file and the extension is now `.null` with a content of `undefined`.

**To Reproduce**
1. To start, click the dropdown arrow next to workspace name and select ‘Import/Export’.
2. Click the ‘Export Data’ dropdown and click ‘Current Workspace’.
3. Select which (if not all) requests you’d like to export and click the ‘Export’ button.
4. Select ‘Insomnia v4 (JSON)’ and click ‘Done’.

**Expected behavior**
A valid .json file

**Screenshots**
![image](https://user-images.githubusercontent.com/22550119/124138080-4da99700-da54-11eb-9193-808c35935083.png)

**Desktop:**
 - OS: Microsoft Windows 10 Pro Versión 10.0.19042 compilation 19042
 - Installation Method: Installer
 - App Version 2021.4.0

**Additional context**
Yesterday, before the update, it was possible to export without problems.

**Comment by dimitropoulos** [comment]
Thanks for reporting.  I was able to reproduce.  I'm looking into this right away (now).

**Comment by dimitropoulos** [comment]
update: I debugged it was unable to find an obvious culprit.  I bisected (which, because you have to wipe everything takes _forevzzz_) and narrowed it down to this commit: https://github.com/Kong/insomnia/commit/0b38c68c1fcc91af171b98e8145eb51fa77504cc

Trying to see if I can find a fix now.

While I do that @mreduar could you say a little more about your environment (maybe things like how many collections/requests you have, etc).  I ask because I am not able to reproduce this when running from my existing set of collections.  It works when I do that. I can only reproduce this if I clear everything and completely start from scratch.  I haven't gotten to the bottom of why that is (although it's definitely strange).

**Comment by mreduar** [comment]
Hello, thank you for the quick response.

I have 20 collections (all different projects), and requests within the project I am trying to export I have like 180 request.
However, I have tried with 20 request collections and the result is the same.

**Comment by develohpanda** [comment]
Hi @mreduar, we were able to reproduce this as well and have a hotfix on the way! Here's a workaround for the time being.

Open DevTools (View > Toggle DevTools) then run `window.localStorage.setItem('insomnia.lastExportFormat', 'json');`. That's all!

There is a bug we found where a code path is not reached if that key is not specified, so the workaround is just to specify that key.

**Comment by mreduar** [comment]
Great! Now it works fine. Thank you very much! You guys are the best.

**Comment by develohpanda** [comment]
Awesome! 🙌🏽 hotfix on the way!

**Comment by arboleya** [comment]
@develohpanda I found another variant regarding **private** environments.

If I chose to export them, the workaround works fine.

Otherwise, it doesn't.

**Comment by mreduar** [comment]
I just tested and @arboleya is right. When you select not to export the private variables, the export does not work. It keeps loading infinitely due to an error in the console.
![image](https://user-images.githubusercontent.com/22550119/124609282-7c9d7f80-de3d-11eb-82b1-18db8eac6fe7.png)
![image](https://user-images.githubusercontent.com/22550119/124609906-0f3e1e80-de3e-11eb-8fad-0a6e9991436c.png)

**Comment by jstephensxoi** [comment]
I am getting the same error when trying to export just a part of my collection but I am selecting to not export private variables 

![image](https://user-images.githubusercontent.com/74548829/124643023-27ba3300-de56-11eb-87a3-16ef996c00eb.png)


using version 2021.4.0 on  Mac OS X Catalina

**Comment by develohpanda** [comment]
Thank you for reporting this additional regression! I have [fixed it](https://github.com/Kong/insomnia/pull/3778/commits/ff49cb30937f4702e129cab4332bf750bcbd03ef) and included it with the 2021.4.1 RC 🙌🏽

**Comment by develohpanda** [comment]
This has been released with [2021.4.1](https://github.com/Kong/insomnia/releases/tag/core%402021.4.1)!
