### ISSUE TITLE
[Bug] curl command import imports incorrect arguments

### ISSUE THREAD

**Issue by Euphorbium** [getinsomnia/insomnia#378]
## Overview
- `Insomnia Version: 5.5.2.677
- `Operating System:`  MacOS 10.12.5
- `Summary: ` When importing a curl command, if request headers conatain values that contain colon character `:` the value gets imported only untill first colon

## How To Reproduce
1. _Create new request_
2. paste this command in request url field: `curl 'https://test.test.com' -H 'Referer: before://after'`
3. Observe Header referer value.

**Comment by gschier** [comment]
Thanks for reporting this @Euphorbium. I've fixed it over in the `insomnia/importers` project, so it should be working as expected in the next release 👍 

https://github.com/getinsomnia/importers/commit/b996183953d876614ffd4dd21d74468d223306ff
