### ISSUE TITLE
dump nested json

### ISSUE THREAD

**Issue by dobau** [getinsomnia/insomnia#3785]
**Describe the bug**
dump function don't work when has a variable with 4 tears nested on object.

```
  "payload_request": {
    "claims": {
      "id_token": {
        "acr": {
          "value": "urn:mace:incommon:iap:silver",
          "essential": "true"
        }
      }
    }
  }
```

```
{{ _.payload_request | dump }}
```

**To Reproduce**
1. Go to 'Manage Enviroments'
2. Use that objects
3. Click on dump to preview

**Expected behavior**
It should show

```
  "payload_request": {
    "claims": {
      "id_token": {
        "acr": {
          "value": "urn:mace:incommon:iap:silver",
          "essential": "true"
        }
      }
    }
  }
```

instead of 

```
  "payload_request": {
    "claims": {
      "id_token": {
        "acr": {}
      }
    }
  }
```

**Screenshots**

![image](https://user-images.githubusercontent.com/126471/124336057-f3ebbe80-db72-11eb-8206-a29c347790e4.png)

![image](https://user-images.githubusercontent.com/126471/124336049-eb938380-db72-11eb-876d-544686251151.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Installation Method: -
 - App Version 2021.4.0

**Comment by filfreire** [comment]
Hi @dobau, thank you for reporting this!

I wasn't able to reproduce the issue on the latest Insomnia release 2022.3.0. 
<img width="762" alt="Screen Shot 2022-05-10 at 10 31 02" src="https://user-images.githubusercontent.com/11976836/167597542-f28716e5-d1ef-4ac6-9645-fd01160094de.png">
<img width="555" alt="Screen Shot 2022-05-10 at 10 31 06" src="https://user-images.githubusercontent.com/11976836/167597549-206ce7b5-943f-42e1-b40a-678c1ae45ad3.png">



Are you able to reproduce it on latest version?

**Comment by wongstein** [comment]
Hello, I'm going to close this issue due to lack of response.  Please feel free to reopen when it's reproducible in the latest Insomnia
