### ISSUE TITLE
The URL preview does not update when working with queries

### ISSUE THREAD

**Issue by DusanLesan** [getinsomnia/insomnia#3788]
**Describe the bug**
The URL preview in query section does not refresh after switching parameters on and off

**To Reproduce**
1. Select one request
2. Go to Query section
3. Note the value of URL in URL Preview
4. Enable one more query

**Expected behavior**
After switching queries on and off, URL preview needs to me updated

**Screenshots**
![image](https://user-images.githubusercontent.com/20520590/124575110-6696bb80-de4b-11eb-8477-42f38a56909f.png)
In image the expected URL in preview should be `http://10.42.0.97:8060/launch/dev?contentId=5c5dc3a0e78ba537db1af5e8%7C5c5debbb2e1a27473d9caa3f&cacheclean=true`

**Desktop (please complete the following information):**
 - OS: Arch 5.12.14-arch1-1
 - Installation Method: insomnia-bin from AUR
 - App Version v2021.4.0

**Additional info**
The preview is updated after moving focus to another request and then back.
I have reproduced the issue on appimage too. I have tried running fresh by removing my config files from ~/.config/Insomnia

**Comment by acaaleksandar** [comment]
I have the same problem here, on Windows 10.

**Comment by wowdyaln** [comment]
> Version: Insomnia 2021.4.0
> Release date: 6/30/2021
> OS: Darwin x64 19.6.0
> Electron: 9.3.5
> Node: 12.14.1
> V8: 8.3.110.13-electron.0

same problem here.

**Comment by GIT-chandra** [comment]
> Version: Insomnia 2021.4.1
Release date: 7/7/2021
OS: Windows_NT x64 10.0.19042
Electron: 9.3.5
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0-DEV OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.41.0

Same issue here

**Comment by Gabrz** [comment]
I have the same issue.

When I change something in the field with the url, the preview doesn't update.
Also when I enable or disable a Query Parameter the preview doesn't update.

I have to navigate to another request and back for the url preview to update.

Luckily, when I press Send the correct values are used. So this is a minor inconvenience.

**Comment by idrtabd** [comment]
same issue 
2021.4.1
node 12.14.1
x64
V8: 8.3.110.13-electron.0
Electron: 9.3.5

**Comment by warwickpalm** [comment]
> Version: Insomnia 2021.4.0
> Release date: 6/30/2021
> OS: Darwin x64 20.5.0
> Electron: 9.3.5
> Node: 12.14.1
> V8: 8.3.110.13-electron.0
> Architecture: x64

Same

**Comment by baermathias** [comment]
Same issue here. The preview is not reactive and changes its value after restarting Insomnia

**Comment by oreid-zd** [comment]
Same issue here using `v2021.5.1`.

**Comment by dimitropoulos** [comment]
Just verified this - taking a look.  Apologies for the radio silence everyone - this one slipped under the radar.

I can confirm that this worked in 2021.3.0 and broke in 2021.4.0.

**Comment by dimitropoulos** [comment]
Update: got a PR up with a fix.  Apologies again.  We'll try to get this out sooner than later!
