### ISSUE TITLE
The DOWNLOAD URL is dead:  http://insomnia.rest/download/ 

### ISSUE THREAD

**Issue by melodyWxy** [getinsomnia/insomnia#3789]
**Describe the bug**
The DOWNLOAD URL is dead:  http://insomnia.rest/download/ 

**To Reproduce**
I Can not  get http://insomnia.rest/download/ , 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.15.1]
 - Installation Method: [e.g. homebrew]
 - App Version [e.g. v7.0.3]

**Additional context**

**Comment by dimitropoulos** [comment]
Thanks for letting us know, however I was not able to reproduce this.

![image](https://user-images.githubusercontent.com/15232461/124614845-adcc7e80-de42-11eb-9dd8-1de26f8c5504.png)

Please let me know if I missed something and we can reopen right away.
