### ISSUE TITLE
Insomnia implies non-private certificates will be git synced but does not

### ISSUE THREAD

**Issue by kalvinwang** [getinsomnia/insomnia#3797]
**Describe the bug**
The checkbox in Client Certificates for "Private" has helper text that says "Private certificates will not be synced", which implies that if the "Private" box isn't checked, the certificate will be synced, but no certificates are ever synced.  

This seems like a bug, and could also be considered a feature request to (re-)add certificate syncing, since David from Insomnia support confirmed that certificate syncing is not currently supported.

**Screenshots**
![image](https://user-images.githubusercontent.com/82277/124958692-70a1f100-dfe8-11eb-9898-9f4d5028bc04.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - App Version: latest

**Comment by filfreire** [comment]
Hi @kalvinwang, thank you for reporting this!

I can confirm this still applies, at least for sync'ing Design Documents with Git, regardless of folks enabling or disabling that option, the certificates are not synced.

fyi @DMarby @wdawson - this could be an easy fix, remove that option and just add a text mention that certificates aren't synced at all?

**Comment by wongstein** [comment]
The wording will be fixed in 2022.7.2
