### ISSUE TITLE
insomnia-inso `generate config` with `--type kubernetes` produces Ingress Resources with deprecated apiVersion (extensions/v1beta1)

### ISSUE THREAD

**Issue by msmith93** [getinsomnia/insomnia#3811]
**Describe the bug**
The latest version of insomnia-inso produces a Kubernetes configuration file with Ingress resources with apiVersion "extensions/v1beta1". This apiVersion is deprecated as of k8s 1.16 https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ 

inso generate config should instead produce Ingress resources with apiVersion "networking.k8s.io/v1"

**To Reproduce**
```
inso generate config --type kubernetes --output out.yaml
```
Resulting out.yaml contains Ingress resources with apiVersion `extensions/v1beta1`

**Expected behavior**
out.yaml should contain Ingress resources with apiVerion `networking.k8s.io/v1`

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Installation Method: npm
 - App Version 2.3.0

**Comment by supercairos** [comment]
I have the same issue

**Comment by filfreire** [comment]
Hi @msmith93, thanks for reporting this!

This is indeed already fixed/updated, it was introduced in this PR: https://github.com/Kong/insomnia/pull/4667

And it exists since Insomnia version `2022.3.0` and up.
