### ISSUE TITLE
https://support.insomnia.rest/article/116-cli-run-test

### ISSUE THREAD

**Issue by Foorack** [getinsomnia/insomnia#3813]
The "git-repo" link at https://support.insomnia.rest/article/116-cli-run-test is broken.

Old: https://github.com/Kong/insomnia/tree/develop/packages/insomnia-inso/src/db/__fixtures__/git-repo
New: https://github.com/Kong/insomnia/tree/develop/packages/insomnia-inso/src/db/fixtures/git-repo/

**Comment by reynolek** [comment]
Thanks for the report! Fixed.
