### ISSUE TITLE
Basic auth issue

### ISSUE THREAD

**Issue by shokoladova** [getinsomnia/insomnia#3817]
**Describe the bug**
If you send some http request under basic auth with right creds, insomnia cashes the password and even retyping password will return 200 instead of 401.

**To Reproduce**
1. Execute some request to protected (basic auth) endpoint with valid creds -> 200 OK
2. Change password for invalid
3. Send request again -> 200 OK

**Expected behavior**
Im expecting application not cache passwords

I've been testing the same API with cURL -> i got expected behaviour.

**Comment by aeri** [comment]
Is it possible that when you authenticate for the first time you are given an access Cookie?
That way even with incorrect access parameters the system will be able to authenticate you.

**Comment by filfreire** [comment]
Hi @shokoladova thanks for reporting this issue!

I'm not able to reproduce this locally and I believe you might be facing the case that @aeri mentioned. Feel free to reopen the issue and add more details (perhaps screenshots) into how to reproduce.

Also feel free to report any other problems you come across!
