### ISSUE TITLE
[Bug] bulk editing does not work

### ISSUE THREAD

**Issue by Euphorbium** [getinsomnia/insomnia#382]
## Overview
- `Insomnia Version:` 5.5.2.677
- `Operating System:`  _MacOS 10.12.5_
- `Summary: ` If you import a request from curl, then modify it in bulk editing mode and then switch to regular editing, it gets messed up. Probably triggered by splitting keys and values on some symbol incorrectly.

## How To Reproduce
_Please list all pertinent information and steps needed to reproduce the issue. For example:_
1. _Create new request_
2. _Paste this command in url field `curl 'https://test.test.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8,lt;q=0.6,de-DE;q=0.4,de;q=0.2,nb;q=0.2,sv;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36' -H 'Accept: application/json, text/plain, */*' -H 'context: 5:0:en_US' -H 'Cookie: __utmt=1; mbox=PC#1501065092813-582393.26_20#1502359200|session#1501149537759-375345#1501151460|check#true#1501149660; __utma=58209327.1714326150.1501065092.1501098585.1501149538.5; __utmb=58209327.2.10.1501149538; __utmc=58209327; __utmz=58209327.1501098585.4.4.utmcsr=ssdfsdf.sdfdfs.it|utmccn=(referral)|utmcmd=referral|utmcct=/scommesse/avvenimenti.html; s_cc=true; s_sq=%5B%5BB%5D%5D' -H 'Connection: keep-alive' --compressed`_
3. _Modify context variable value value in bulk mode from 5 to 56_
4. Switch to regular editing mode.

## Other Notes

_Notice, that context value was imported incorrectly. This could be already solved in issue #378_

**Comment by gschier** [comment]
Thanks for reporting @Euphorbium! I've reproduced the problem and am working on a fix now 👍
