### ISSUE TITLE
Sub Environments are being re-ordered after leaving environment screen

### ISSUE THREAD

**Issue by destumme** [getinsomnia/insomnia#3822]
**Describe the bug**
Sub Environments are being arbitrarily re-ordered after leaving environment screen

**To Reproduce**
1 - Open managed envs
2 - Order multiple sub environments in desired order
3 - close screen
4 - Envs are now moved to a seemingly arbitrary order.

**Expected behavior**
Order is persisted when changed

**Screenshots**

Initial Order
![Screen Shot 2021-07-16 at 9 00 19 AM](https://user-images.githubusercontent.com/6454319/125960058-7744bf43-db6c-4969-a77d-f86115b157cd.png)

Re-ordered to desired order

![Screen Shot 2021-07-16 at 9 00 39 AM](https://user-images.githubusercontent.com/6454319/125960070-9e6ec8f4-eb54-42e2-8ee5-c01ea574e75a.png)

Clicked 'done' and viewed envs, this was order

![Screen Shot 2021-07-16 at 9 00 51 AM](https://user-images.githubusercontent.com/6454319/125960073-83702f56-2e5c-4a4a-92f2-680017907bd9.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.15.1]
 - Installation Method: [e.g. homebrew]
 - App Version [e.g. v7.0.3]

**Additional context**

**Comment by irontoby** [comment]
If this is driving anyone else crazy like it was me, give this a try:

* Close any running instances of Insomnia.
* Navigate to your Insomnia settings directory. On Windows, this is `%APPDATA%\Insomnia`.
* Make a backup copy of `insomnia.Environment.db`, then open in a text editor (it's "mostly" just a JSON file; it has one object per line but no comma/square brackets to denote an array).
* At the end of each object is a property `metaSortKey`. It looks like these should be defaulted to `Date.now()` [when they're created](https://github.com/Kong/insomnia/blob/0178533e5284cbcaff2c39a4ba2d560b16422e4c/packages/insomnia-app/app/models/environment.ts#L35), but a bunch of them are set to `1` instead.
* Manually change all of the `metaSortKey` values to unique values in the order you'd like (I used 101, 102, etc.) I have about a dozen so it was easier to first reorder them line-by-line as I wanted, then update each consecutive line.
  * I also had settings for "New Environment" and "Base Environment"; I didn't edit these. 
* Save the changes, and make a backup of the "good" copy.

It appears that the correct order will now persist across app restarts, and you can open "Manage Environments" and make changes to variables/colors etc., but DO NOT manually sort them from the GUI or they'll get scrambled again.

**Comment by develohpanda** [comment]
Hey everyone, my apolgies for the radio silence on this issue, it slipped under our radar. This appears to be a regression as it certainly shouldn't be re-ordering automatically. We'll aim to get it triaged, and fixed up!
