### ISSUE TITLE
URL preview hangs on old value

### ISSUE THREAD

**Issue by jarimayenburg** [getinsomnia/insomnia#3831]
**Describe the bug**
The URL preview hangs on the old value when changing the query parameters.

**To Reproduce**
1. Create a request
2. Fill in the URL and some query parameters
3. Watch the URL preview update
3. Wait a little
4. Change the query parameters
5. Observe that the URL preview hangs on the old value (or somewhere in the middle of the change)

Also, when clicking the "Copy URL" button, the incorrect value of "URL preview" is copied.

**Expected behavior**
I would expect the URL preview to update (almost) instantaneously, like it did in older versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/11874892/126286262-a21434b3-66fa-4612-86b1-49d9694af464.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - Installation Method: Installed package insomnia-bin 2021.4.1-1 from the AUR
 - App Version 2021.4.1

**Comment by khyveasna11111908** [comment]
Inn at little rock AR Rahman khan

**Comment by jarimayenburg** [comment]
Duplicate of #3788
