### ISSUE TITLE
Symlinks to Nested Directories cause ENOENT on Git Sync

### ISSUE THREAD

**Issue by schrodingersket** [getinsomnia/insomnia#3845]
**Describe the bug**
When working with a Git project which contains symlinks to a nested directory on Linux (e.g., `ln -s .my/directory/path directory-link`) which are unrelated to the `.insomnia` folder at the root of the Git repository, performing any Git action (push/pull/commit) triggers the following in the developer console (tested with the repository linked to below in steps to reproduce):

```
12:31:07.316 › Error: ENOENT: no such file or directory, symlink '/home/schrodingersket/.config/Insomnia/version-control/git/git_3a44eed139764a3187ec54ea7daa2f64/other/.docker/prod/Dockerfile' -> './nginx/Dockerprod'
```
This seems to sometimes be relatively benign - in the example repository below, it is still possible to pull repository changes and commit new ones, but in a separate private (work-related) project, it precludes committing, pushing, or pulling changes entirely - the commit operation simply hangs, and the other operations fail silently.

**To Reproduce**
1. Import  https://github.com/schrodingersket/insomnia-symlink-example via Git Sync.
2. Open the developer console.

**Expected behavior**
Repositories with symlinks to nested directories should not affect `.insomnia` Git directory management.

**Desktop (please complete the following information):**
 - OS: `Linux schrodinger 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux`
 - Installation Method: Arch AUR (also tested and reproduced by compiling from source commit Kong/insomnia@eb6795884660ef8a024af97af5d6c5857f0804c8
 - App Version `2021.3.0`

**Comment by MariusJam** [comment]
Hi,

I'm having this issue as well with a private repository. I don't know whether it's related, but I have difficulties to setup the Git Sync and when the initial config is successful I'm unable to commit/push/pull as described above. At the moment, I can't use Git Sync feature at all with my project.

Here are my logs from the Insomnia's dev tool:

```
15:02:43.153 › [git-event] Compressing objects:  96% (1770/1843)
15:02:43.153 › [git-event] Compressing objects:  97% (1788/1843)
15:02:43.153 › [git-event] Compressing objects:  98% (1807/1843)
15:02:43.153 › [git-event] Compressing objects:  99% (1825/1843)
15:02:43.154 › [git-event] Compressing objects: 100% (1843/1843)
15:02:43.154 › [git-event] Compressing objects: 100% (1843/1843), done.
15:02:43.180 › [git-event] Total 2213 (delta 584), reused 1310 (delta 295), pack-reused 0
15:02:46.242 › Error: ENOENT: no such file or directory, scandir '../prod/deprecations.yaml'
    at new SystemError (bundle.js:201085)
    at mem_client_MemClient._assertExists (bundle.js:214943)
    at mem_client_MemClient.symlink (bundle.js:214879)
    at FileSystem.writelink (/opt/Insomnia/resour…-git/index.cjs:4329)
    at /opt/Insomnia/resour…-git/index.cjs:5744
    at async Promise.all (index 44)
    at async /opt/Insomnia/…-git/index.cjs:5716
    at async /opt/Insomnia/…c-git/index.cjs:882
15:02:46.243 › Error: ENOENT: no such file or directory, scandir '../prod/doctrine.yaml'
    at new SystemError (bundle.js:201085)
    at mem_client_MemClient._assertExists (bundle.js:214943)
    at mem_client_MemClient.symlink (bundle.js:214879)
    at FileSystem.writelink (/opt/Insomnia/resour…-git/index.cjs:4329)
    at /opt/Insomnia/resour…-git/index.cjs:5744
    at async Promise.all (index 64)
    at async /opt/Insomnia/…-git/index.cjs:5716
    at async /opt/Insomnia/…c-git/index.cjs:882
15:02:46.243 › Error: ENOENT: no such file or directory, scandir '../prod/routing.yaml'
    at new SystemError (bundle.js:201085)
    at mem_client_MemClient._assertExists (bundle.js:214943)
    at mem_client_MemClient.symlink (bundle.js:214879)
    at FileSystem.writelink (/opt/Insomnia/resour…-git/index.cjs:4329)
    at /opt/Insomnia/resour…-git/index.cjs:5744
    at async Promise.all (index 68)
    at async /opt/Insomnia/…-git/index.cjs:5716
    at async /opt/Insomnia/…c-git/index.cjs:882
15:02:46.407 › [fsClient] Created in /home/marius/.config/Insomnia/version-control/git/git_a59a9ee646e84611a40ce1487283755a
15:02:46.408 › [fsClient] Created in /home/marius/.config/Insomnia/version-control/git/git_a59a9ee646e84611a40ce1487283755a/other
15:02:48.953 › [git-event] Auth Success: https://gitlab.com/xxxxx/pfe.git
15:03:08.247 › Error: ENOENT: no such file or directory, symlink '/home/marius/.config/Insomnia/version-control/git/git_cb95a135d8f24be3bd784adcf5b04680/prod/deprecations.yaml' -> './api/config/packages/dev/deprecations.yaml'
15:03:08.248 › Error: ENOENT: no such file or directory, symlink '/home/marius/.config/Insomnia/version-control/git/git_cb95a135d8f24be3bd784adcf5b04680/prod/doctrine.yaml' -> './api/config/packages/qualif/doctrine.yaml'
15:03:08.249 › Error: ENOENT: no such file or directory, symlink '/home/marius/.config/Insomnia/version-control/git/git_cb95a135d8f24be3bd784adcf5b04680/prod/routing.yaml' -> './api/config/packages/qualif/routing.yaml'
15:03:08.429 › [git] Clones repo to git from https://gitlab.com/xxxxx/pfe.git
15:03:08.433 › [git] Add Remote url=https://gitlab.com/xxxxx/pfe.git
```

**Desktop (please complete the following information):**

    OS: Ubuntu 20.04.3
    Installation Method: using apt-get after having added the package's apt repository
    App Version 2021.7.2

**Comment by kreosus** [comment]
Hi @schrodingersket, have you tried to see if this issue persists with our newest release, located here: https://github.com/Kong/insomnia/releases/tag/core%402022.7.5
