### ISSUE TITLE
[Improvement] Don't change content type header when choosing a binary file as body when one is already defined

### ISSUE THREAD

**Issue by iddo** [getinsomnia/insomnia#385]
Currently, as soon as one chooses a raw file as the request body, the content type is automatically changed to application/octet-stream regardless of the type of file that is chosen, even if a content-type header was already manually entered as header.

This behavior is annoying if the endpoint accepts another content type (application/zip for example), so every time a zip file is chosen the header has to be manually reverted.

This can be fixed in several ways:
1. Allow changing this behavior via the preferences page
2. Do not change the header if it already exists
3. [Enhancement] Automatically detect the mime type and use it as the content type
4. Add ability to "lock" the content type header for specific requests
5. Ask every time a file is chosen whether to change to content type header

**Comment by iddo** [comment]
Please don't close, I still would like this fixed

**Comment by gschier** [comment]
I will try to get to this one soon 😄
