### ISSUE TITLE
Template Tags Don't Run In Tests

### ISSUE THREAD

**Issue by epiqueras** [getinsomnia/insomnia#3858]
**Describe the bug**

When running requests in the tests tab of the designer, template tags that produce random values reuse cached values instead of executing again.

**To Reproduce**

1. Create a request that uses a random number template tag in the debug tab.
2. Use the request in the tests tab multiple times.

**Expected behavior**

The template tag should be executed every time a new request is made.

**Desktop (please complete the following information):**

 - OS: macOs 11.4
 - Installation Method: Website Download
 - App Version: Insomnia 2021.4.1
   - Release date: 7/6/2021
   - OS: Darwin x64 20.5.0
   - Electron: 9.3.5
   - Node: 12.14.1
   - V8: 8.3.110.13-electron.0
   - Architecture: x64
   - node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0

**Comment by develohpanda** [comment]
Thank you for the report! We don't have support for custom plugins with Inso just yet but we have been thinking about it. I'll close this and cross-link in an existing discussion: https://github.com/Kong/insomnia/discussions/3633

**Comment by epiqueras** [comment]
Hi, thanks for the prompt reply.

Does the tests tab UI use Inso under the hood?

**Comment by develohpanda** [comment]
It doesn't use inso, but inso and Insomnia both use `insomnia-testing` which implements all of the testing functionality. Even the networking and stack to expand the template tags is shared (through `insomnia-send-request`).

The problem arises from inso not having access to the custom plugins installed within Insomnia (eg. the random number generator). Although I can't say where it falls on the roadmap at the moment, it's definitely on our radar.

**Comment by epiqueras** [comment]
Got it; thanks for the explanation.
