### ISSUE TITLE
[Feature Request] HTML5 fetch code generation

### ISSUE THREAD

**Issue by Lizhooh** [getinsomnia/insomnia#387]
`Generate Client Code` 

**Wish to add**
- `Javascript - > fetch`
- `nodejs - > node-fetch`

**Comment by gschier** [comment]
Hey @Lizhooh. The code snippets are generated by [`httpsnippet`](https://github.com/Mashape/httpsnippet). If you'd like to contribute one or both of those, I'd be happy to update the dependency within Insomnia afterwards.

**Comment by gschier** [comment]
Hmm, it looks like there is already a PR for this on that repository. Maybe I'll fork it and merge that in.

https://github.com/Mashape/httpsnippet/pull/98
