### ISSUE TITLE
Linter error never clears despite return to valid schema

### ISSUE THREAD

**Issue by cwurm** [getinsomnia/insomnia#3882]
**Describe the bug**
When introducing a certain error in an OAS spec and reverting it, Insomnia continues showing a parser error even though it's now a valid spec again.

**To Reproduce**
1. Start with a valid spec
2. Break it by removing the trailing quote around a response status code
3. Insomnia can no longer render the left-hand side navigation and right-hand side preview (as expected)
4. Re-insert the quote
5. Navigation and preview render correctly again, but now a parser error shows up at the bottom

**Expected behavior**
The parser error should show up when things are broken (it does not) and disappear when things are fixed again.

**Screenshots**
Quote removed:
<img width="1440" alt="Screenshot 2021-08-04 at 15 01 42" src="https://user-images.githubusercontent.com/694597/128195057-f72b5af3-633b-41d1-9c13-5ae73ace2f24.png">

Quote re-inserted - parser error at the bottom that wasn't there before:
<img width="1439" alt="Screenshot 2021-08-04 at 15 01 57" src="https://user-images.githubusercontent.com/694597/128195097-f16c99bd-98bc-4b03-9ce1-050d3fb1bce1.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Installation Method: Download from website
 - App Version: Insomnia 2021.4.1

**Additional context**
OAS file from the screenshots above:
```
openapi: 3.0.0
info:
  title: This is my API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```

**Comment by filfreire** [comment]
Hi @cwurm, thank you again for reporting this other issue.

I'm no longer able to reproduce it in latest versions of Insomnia (e.g. [2022.3.0](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)), example:

https://user-images.githubusercontent.com/11976836/167607216-7c55ef3a-e021-4bc6-8ef5-0b9a728ec21a.mp4


I'm going to go ahead and close this issue. Please feel free to re-open and tag us if you are still able to reproduce it in latest Insomnia version.
