### ISSUE TITLE
Possibility to hide menubar on the top

### ISSUE THREAD

**Issue by ramizdemiurge** [getinsomnia/insomnia#389]
## Overview
- `Insomnia Version:` 5.6.3
- `Operating System:`  ubuntu 16.04.1 (amd54)
- `Summary: ` Visual improvement

I think, it will be really cool, if you will make possibility to hide menubar on the top. :)
It makes insomnia little bit ugly.

Thanx. Love insomnia :+1:

**Comment by gschier** [comment]
Thanks for the suggestion @ramizdemiurge! This has been discussed quite a bit before and is a duplicate of #314
