### ISSUE TITLE
Insomnia freezes when focused (Ubuntu 20.04)

### ISSUE THREAD

**Issue by JoaoPedroMDP** [getinsomnia/insomnia#3907]
**Describe the bug**
  When i defocuse Insomnia, e.g go to PHPStorm window, and get back to Insomnia, it freezes for about 2 approx. Then a "app not responding" window appears but at same time Insomnia gets back to work. 
  Although i do not think that is the case, PHPStorm is a heavy app, so maybe when Insomnia tries to compete for resources with heavy applications is when the bug happens. But my Notebook is not that weak to cause these bugs.

**To Reproduce**
1. Open another window (or defocuse Insomnia)
2. Use "Alt + Tab" to go back to Insomnia

**Expected behavior**
It should just get back to Insomnia.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation Method: snap
 - App Version: v2021.4.1
 - 16 Gb RAM
 - HDD 1Tb
 - Intel core i7 7500U

**Additional context**
I have about 100 requests. Already cleaned all responses (had about 1Gb of responses) on app folder.
Insomnia also lags when i am using it, sporadically, but it definitely lags in this issue context (defocusing -> focusing)

Maybe related with #2956 ?

**Comment by lyrixx** [comment]
Hello,

I ran into the same issue for a couple of month. Before that, insomnia was really fluid, but now It's really not pleasant to work with.

Note: In my case, the app does not freeze every single time I swith application. It's random

* OS: Ubuntu 18.0.4
* Installation method: APT
* 16Gb RAM
* 500Gb SSD
* intel 

```
Version: Insomnia 2021.5.3
Release date: 9/13/2021
OS: Linux x64 5.4.0-87-generic
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1i zlib/1.2.11 brotli/1.0.7 zstd/1.4.9 libidn2/2.3.0 libssh2/1.9.0 nghttp2/1.42.0
```

**Comment by lyrixx** [comment]
OK, I think I understood something: I'm using a web framework that allow me to dump some variables in HTML with some JS support.

Insomnia plays really well with it, but I think the memory is never released from the webview, or something like that.

I made a video 

1. In the webview I have some HTML + JS
2. I remove the dump from my page, and I click on the "send" button of insomnia
3. The interface freeze during 15/20 secondes where I'm unable to click anywhere
4. after that, it's OK (and I write "OKKKK" in an input text

https://user-images.githubusercontent.com/408368/136210189-0d3ef6ea-ce7b-48ea-8960-9930c06f1871.mp4

**Comment by oliverjanik** [comment]
Similar experience after upgrading from Win 10 to Win 11. Must be something with Electron.

**Comment by lyrixx** [comment]
I managed to fixed it BTW. I exported all my config. I cleared all the data stored by insomnia. Re-imported my data and now it's ok. 

FYI, the preference file (something like that, I don't remember) weighed about 800mb)
