### ISSUE TITLE
AWS auth bug prevents GET requests

### ISSUE THREAD

**Issue by focusaurus** [getinsomnia/insomnia#391]
## Overview
- `Insomnia Version:` 5.6.3.750
- `Operating System:`  MacOS 10.12.6
- `Summary: ` AWS auth doesn't work for GET requests

## How To Reproduce
_Please list all pertinent information and steps needed to reproduce the issue. For example:_
1. Define a GET request to an AWS service
2. Configure AWS Auth
3. Try to send. You get an error about body type not being supported.

## Other Notes

I'm pretty sure the fix is in the logic [here](https://github.com/getinsomnia/insomnia/blob/fb675159bd4a12a9c1adb23a3ca6ef19399a7060/app/network/network.js#L456) where we should be checking `expectsBody` as well.

Working on a fix but struggling with a separate libcurl issue preventing me from running insomnia in dev mode.

**Comment by gschier** [comment]
@focusaurus what's the libcurl error?

**Comment by gschier** [comment]
Hmm, ya. Should the check be changed to

```js
if (!noBody && !requestBody) {
```

**Comment by focusaurus** [comment]
I'm separately googling this. Probably something to do with recent macos update and possibly homebrew and me needing to futz with LD_LIBRARY_PATH or something along those lines. Help appreciated, but I haven't researched the error on my own much yet.

```
Uncaught Error: dlopen(/Users/plyons/projects/insomnia/node_modules/node-libcurl/lib/binding/node_libcurl.node, 1): Library not loaded: /Users/travis/lib/libcurl.4.dylib
  Referenced from: /Users/plyons/projects/insomnia/node_modules/node-libcurl/lib/binding/node_libcurl.node
  Reason: Incompatible library version: node_libcurl.node requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
```

**Comment by gschier** [comment]
Looks like you need to run

```
npm run rebuild
```

**Comment by gschier** [comment]
Just pushed a [fix](https://github.com/getinsomnia/insomnia/commit/766b15a3d309a906ddd516a9f89250bf83236be9) for this. I didn't actually test it with an AWS API, but it no longer throws an exception.

**Comment by gschier** [comment]
@focusaurus this should be released now: https://insomnia.rest/changelog/5.7.0/

**Comment by focusaurus** [comment]
Confirmed the new release fixes the bug. Thanks!

**Comment by gschier** [comment]
Awesome!
