### ISSUE TITLE
Unusable after pasting large curl command

### ISSUE THREAD

**Issue by h0wXD** [getinsomnia/insomnia#3915]
**Describe the bug**
App keeps showing Unresponsive dialog, more than once, on startup. Can't use insomnia anymore.

**To Reproduce**
1. Go to chrome dev tools
2. Copy as curl command that has a large json body (talking in megabytes large)
3. Paste it in the url bar, which is loaded on next app startup
4. Insomnia just hangs, and keeps crashing
5. On startup keeps hanging - app becomes unusable as it gets stuck on startup
6. Insomnia is unresponsive dialog keeps popping up every minute or so (even when previous one isn't closed)

**Expected behavior**
Perhaps improve performance of handing large curl commands, 
or don't load curl commands on startup after an app crash / unresponsive
or any other approach that allows people to use the app

**Screenshots**
![image](https://user-images.githubusercontent.com/10574115/129508357-ae33b961-7de6-496b-8b5f-dab3d303b46f.png)
![image](https://user-images.githubusercontent.com/10574115/129508586-7b0fc596-221e-4f1b-9235-86bc43ab03b0.png)

**Desktop (please complete the following information):**
Version: Insomnia 2021.4.1
Release date: 7/7/2021
OS: Windows_NT x64 10.0.19043
Electron: 9.3.5
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0-DEV OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.41.0

**Additional context**

**Comment by dimitropoulos** [comment]
Do you have a way you can think of (preferably using mockbin.org) that we can more easily reproduce this?  We certainly want to avoid any situation that leads to "brick"ing your insomnia instance.

**Comment by h0wXD** [comment]
@dimitropoulos I believe this one would do: [curl.txt](https://github.com/Kong/insomnia/files/7032720/curl.txt)

**Comment by jackkav** [comment]
fixed
