### ISSUE TITLE
Feature request:  Copy Folder from one Collection to another

### ISSUE THREAD

**Issue by t-reppert** [getinsomnia/insomnia#3917]
I would like to suggest that the ability to copy a 'folder' and its associated requests from one collection to another be added to Insomnia.  It would be similar to how the individual requests can be copied to other collections except in this case an entire folder and its contents could.

**Comment by filfreire** [comment]
Hi @t-reppert, sorry for only getting back to you now, but thanks for reporting this one!

I'm going to go ahead and mark it as an improvement/feature request.

Also tagging @wdawson and the @Kong/team-insomnia.

@t-reppert feel free to report any other issues you come across!

**Comment by bport** [comment]
This feature already exist
Right click on folder => settings => Move/copy to workspace

**Comment by t-reppert** [comment]
@bport 
When I submitted this feature request on **August 16, 2021,**   Insomnia version 2021.4.1 was the current stable version.  You could only do a MOVE of a folder from one workspace to another.  It did not at that time have the right click on a folder option to select settings and to then move or copy it to another workspace.

This feature appears to have been added since I made this request back on August 16, 2021.

**Comment by bport** [comment]
@t-reppert yes the message was only to inform you and future user (I found your issue by searching how to copy a request to a different collection)
