### ISSUE TITLE
[Bug] "Copy" context menu action in response pane does not change clipboard

### ISSUE THREAD

**Issue by seh** [getinsomnia/insomnia#392]
## Overview

"Copy" context menu action in response pane does not copy selected text to clipboard.

## How To Reproduce
1. _Create new request._
2. _Perform a request which returns at least one byte of a response entity._
3. _In the response pane on the right, use the drop-down menu across the top to select a preview mode of either "Source Code" or "Raw."_
4. _Select some or all of the text._
5. _Right-click and select "Copy" in the context menu._
6. _Change focus to another application that accepts text content pasted in from the clipboard, and attempt to past the current clipboard content._
7. _Observe that the clipboard remains unchanged.  
    If it had content in it before the attempted "Copy" operation, that content remains._

**Comment by gschier** [comment]
Hey @seh, thanks for the report! However, I can't seem to reproduce this on MacOS 10.12.5 and Insomnia 5.6.3.

Does this happen after a fresh launch of Insomnia?

**Comment by seh** [comment]
It took another few hours for me to realize that it wasn't just Insomnia suffering clipboard trouble; the same symptom started popping up in other applications too. Rebooting my computer fixed the problem all around.

I apologize for the invalid report, and thank you for Insomnia.

**Comment by gschier** [comment]
No worries @seh. It happens to the best of us 😸
