### ISSUE TITLE
MacOS : The application “Insomnia” can’t be opened. 9.

### ISSUE THREAD

**Issue by dimpu** [getinsomnia/insomnia#3924]
**Describe the bug**
New Mac update unable to open insomina.

[image](https://user-images.githubusercontent.com/1271995/129807644-0a3efeee-931f-4331-8ef2-27d64020495e.png)

MacOS: 11.5.2 (20G95)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.15.1]
 - Installation Method: [e.g. homebrew]
 - App Version [e.g. v7.0.3]

**Additional context**

**Comment by reynolek** [comment]
Hi @dimpu -- Can you provide the following information:

* What version of insomnia are you using?
* Was it a fresh install?
* How did you install it initially?

My first recommendation would be to make usre you are using the most up to date version of Insomnia.

**Comment by develohpanda** [comment]
Hi @dimpu, thanks for reporting! I just checked with our current stable release of 2021.4.1 on MacOS 11.5.2 and it seems to be working okay

![image](https://user-images.githubusercontent.com/4312346/129821156-9360f135-fd13-4ffd-9fd7-3df45bc291ae.png)

**Comment by dimpu** [comment]
Closing this issue. Since it's issue with my internal firewall. Now resolved.
