### ISSUE TITLE
[Improvement] GraphQL queries sends variables as string

### ISSUE THREAD

**Issue by philippguertler** [getinsomnia/insomnia#393]
## Overview
- `Insomnia Version:` 5.7.0
- `Operating System:`  Fedora 26 (Using generic package)
- `Summary: ` When sending a graphql query, the variables for the query are stringified and then the string is sent in the request.

## How To Reproduce
Send any GraphQL query, for example:
```GraphQL
{
	project {
		uuid
		name
	}
}
```
With variables:
```json
{
	"page": 1
}
```
This will result in this request body:
`{"query":"{\n\tproject {\n\t\tuuid\n\t\tname\n\t}\n}","variables":"{\n\t\"page\": 1\n}"}`
I would like it to be
`{"query":"{\n\tproject {\n\t\tuuid\n\t\tname\n\t}\n}","variables":{"page": 1}}`
The variables are not stringified here.

## Other Notes
First of all: Really like the GraphQL integration, especially the autocompletion. Great stuff!

Is there a reason why the variables for the query are sent as a string instead of just JSON? The request is already JSON, and the variables have to be in JSON format, so it would make sense to just put the variables object in the request object.

GraphiQL sends the variables as JSON and the server I'm using also parses it as JSON and rejects strings as variables.

**Comment by gschier** [comment]
Seems like just an oversight. The GraphQL server I was using accepted it, so I didn't notice. Will fix for the next release 😄
