### ISSUE TITLE
Inso converting "off" string to primitive value

### ISSUE THREAD

**Issue by dmortim** [getinsomnia/insomnia#3938]
**Describe the bug**
Inso CLI converts "off" string to a primitive value in decK. When running inso generate config on an openapi spec a string with the value "off" is converted to a boolean in kong decK. 

**To Reproduce**
As an example:
The openid-connect plugin has a configuration field authorization_cookie_samesite where the default value is "off". When this is declared in the openapi spec yaml and we run inso generate config, it makes it NOT a string but a seemingly boolean value, in the outputted decK. Then when running decK sync we get an error as it expects a string.  It seems YAML 1.1 sepcification supported  booleans  such as on | ON | off | OFF, which may be causing the issue. 

**Expected behavior**
Inso should keep values as string (when they are  declared  as a string)   when converted from openapi to kong  decK

**Desktop (please complete the following information):**
Inso version 2.3.0
Installation  method brew 
Catalina Mac 10.15.7

**Comment by jackkav** [comment]
@dmortim Thanks for the report.
This specific setting can be set to `lax` or `authorization_cookie_samesite` can be removed from the yaml.

**Comment by jackkav** [comment]
Closed by #4129
