### ISSUE TITLE
[Question] How to add Insomnia project to local Git repo?

### ISSUE THREAD

**Issue by minimedj** [getinsomnia/insomnia#394]
## Overview
- `Insomnia Version:` _(5.7.0 (5.7.0.911))_
- `Operating System:`  _(e.g. MacOS 10.12.5 (16F73))_
- `Summary: ` _I want to save my project locally_

After I created API examples in Insomina app I want to save it as a file to my git repo. How would I do this?

**Comment by gschier** [comment]
Most people I've talked to use the export feature (produced a JSON file) which they then commit into their Git repo.

![image](https://user-images.githubusercontent.com/587576/28933065-acd1a54a-7830-11e7-9569-260bc3844556.png)
