### ISSUE TITLE
Website is inaccessible for browser zoom users

### ISSUE THREAD

**Issue by streats** [getinsomnia/insomnia#3945]
At certain zoom levels (in particular, 150%) the homepage breaks and cuts off content. This makes it inaccessible for users who need to use browser zoom. 

For example, I use 150% zoom at 1152x720 resolution as this is the most comfortable for my eyesight. 

I noticed that at 175% it becomes single width (like what I would expect on a tablet) so it seems this might just be an issue related to the break points?

**Comment by dimitropoulos** [comment]
Was there any page in particular that need attention?  I poked around at 200% at 400px width and the only one that I could find that gets cut off was the plugin pages (e.g. https://insomnia.rest/plugins/insomnia-plugin-prettyprint-request-response).  I've made a PR to our (private) website repo to fix that page, at least.  I'll let you know when it's deployed.

**Comment by streats** [comment]
It was on the homepage I saw it (https://insomnia.rest/). I didn't see how to attach an image before but now I see it so here are some screenshots from my work computer (Chrome at 150% zoom on a 16-inch MacBook Pro at 1152x720 resolution). 

<img width="1152" alt="Screenshot 2021-08-25 at 11 47 00" src="https://user-images.githubusercontent.com/12902836/130846703-e2fd7fe4-60f7-46b4-9017-179899cfb43d.png">
<img width="1152" alt="Screenshot 2021-08-25 at 14 32 09" src="https://user-images.githubusercontent.com/12902836/130846716-54fa5222-6ff4-4804-a679-bad460580dbe.png">
<img width="984" alt="Screenshot 2021-08-25 at 14 31 59" src="https://user-images.githubusercontent.com/12902836/130846724-d87fba86-4def-4bbd-b483-076bf59339ad.png">

On my personal computer (Chrome at 150% on a 13-inch MacBook Air at 1024 x 640 resolution) it doesn't seem to be a problem.

**Comment by reynolek** [comment]
I have merged and deployed this fix.

**Comment by dimitropoulos** [comment]
(check out the fix we put in and let us know if it did the trick.  it at least definitely improved the plugin pages.  if it's still an issue we can reopen and keep investigating - no problemo)

**Comment by streats** [comment]
Sweet, looks good now. It's still a little narrow and close to the edge, but that's fine and it's no longer cut off! 
<img width="1152" alt="Screenshot 2021-08-26 at 18 49 18" src="https://user-images.githubusercontent.com/12902836/131011856-309dd02d-5034-4ca4-be6d-9970f0e5008c.png">

**Comment by dimitropoulos** [comment]
sweet!  thanks again and let us know if anything else is cut off.  I'll advocate to keep these zoom levels more top-of-mind when we work with the website!

**Comment by streats** [comment]
Thank you for such a quick fix!
