### ISSUE TITLE
Testimonial faces have distorted aspect ratio at higher browser zooms

### ISSUE THREAD

**Issue by streats** [getinsomnia/insomnia#3946]
On the [Insomnia homepage](https://insomnia.rest/), the circular photos of 'users' get distorted when the page is zoomed above 110% - the container gets stretched into an oval and the photo's aspect ratio is distorted. It doesn't seem to happen to all of them - for example, 'Paula' remains a circle. Expected behaviour is that the circles and photos increase proportionately. 

This is a bug because websites and their content should still perform and display properly up to 200% zoom (or even 400%) zoom to be accessible to users with different visual needs. For more information see [WCAG success criteria on resizing text](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html), for example. 

I'm using Chrome at 150% zoom, on a Mac with resolution 1152x720.

**Comment by dimitropoulos** [comment]
Thanks for letting us know!  I've just put in a PR to the (private) website repo to get this fixed.  I'll report back when it's deployed.

now:
![Screenshot_20210825_130206](https://user-images.githubusercontent.com/15232461/130833862-1bd6a8df-3cb0-474b-84ba-b16de3d9a0ba.png)

fixed:
![Screenshot_20210825_130226](https://user-images.githubusercontent.com/15232461/130833914-e9ae55ce-c7d9-4ad4-876e-76abd45687f8.png)

**Comment by reynolek** [comment]
I have merged and deployed this fix.
