### ISSUE TITLE
[Bug] JSON pretty printing

### ISSUE THREAD

**Issue by sewalsh** [getinsomnia/insomnia#395]
## Overview
- `Insomnia Version:` _5.7_
- `Operating System:`  _Windows Server 2012R2_
- `Summary: ` _JSON response body doesn't pretty print_

## Example of JSON response that doesn't pretty print

```json
{"response":{"CCItems":{"CCItem":[{"routing_id":13,"asset_id":204,"routed_to":"","revision":"0_4","title":"Department of Blah_1501586343799.xml","dateRequested":"01/08/2017 12:31:47","documentType":"CONSULT","sentFrom":"testuser22@education.foobar.com","requesting_department":"","remarks":"Note i'm sending this back"},{"routing_id":8,"asset_id":203,"routed_to":"","revision":"0_2","title":"Test department name_1501584359087.xml","dateRequested":"01/08/2017 12:01:16","documentType":"MEMO","sentFrom":"joe.bloggs@foobar.com","requesting_department":"","remarks":"Any information to add to this memo"}],"lastItemNum":[1,2]},"responseState":{"message":"","status":"SUCCESS"},"totalItemCount":2}}
```

**Comment by gschier** [comment]
Hey @sewalsh. What is the value of the `Content-Type` header returned with your response?

The last version changed the logic that was used to auto-detect JSON, so that might be what the problem is.

**Comment by sewalsh** [comment]
`Content-Type` being returned is `text/plain;charset=UTF-8` although that's incorrect since the body of the response is JSON.
