### ISSUE TITLE
`Hide menu bar` stopped working after 2021.5.0

### ISSUE THREAD

**Issue by ghost** [getinsomnia/insomnia#3952]
![2021-08-26_121406](https://user-images.githubusercontent.com/11320080/130936578-9a38ed23-efc5-4020-aa73-2b28bff0e8ed.png)

Win 10

**Comment by develohpanda** [comment]
Thank you for reporting! Verified that this worked in 2021.4 and broke in 2021.5. We'll be looking into this to resolve it!

**Comment by ghost** [comment]
Fixed in https://github.com/Kong/insomnia/pull/3961 / 2021.5.2 / Thanks!
