### ISSUE TITLE
Insomnia duplicating Swagger requests defined in Design

### ISSUE THREAD

**Issue by heliommsfilho** [getinsomnia/insomnia#3968]
**Describe the bug**
When designing an API, every time I switch to _DEBUG_ tab there is a new request. If I keep switching from _DESIGN_ to _DEBUG_ new requests are created.

**To Reproduce**
1. Define a Swagger 2.0 API in _DESIGN_ tab
2. Click on _DEBUG_ tab
3. Click on _DESIGN_ tab
4. Click on _DEBUG_ tab
5. ...

**Expected behavior**
Each time you enter in _DEBUG_ tab, there is a duplicated request for each request defined in _DESIGN_ tab.

**Screenshots**
![Screen Recording 2021-08-29 at 10 34 00](https://user-images.githubusercontent.com/10871439/131246018-2b5abb80-11e5-45ab-a538-9361a6298cb7.gif)

**Desktop:**
 - OS: macOS 11.5.2
 - Installation Method: Binary downloaded from official site
 - App Version: 2021.5.0

**Additional context**
[YAML from example](https://github.com/Kong/insomnia/files/7072240/bug_test.txt)

**Comment by develohpanda** [comment]
Hiya, thank you for the report 🙌🏽 According to the implementation in the code, if you provide an `operationId` the generator will use that id for requests.

```diff
paths:
  /test:
    get:
      tags: ["Test"]
+     operationId: "test-get"
      summary: "Get all data"
      produces: ["application/json"]
      responses:
        "200":
          description: "Success"
```

Unfortunately this is not well documented and is likely going to go through some improvements. There's also a side-effect of this approach and an open [PR](https://github.com/Kong/insomnia/pull/3804/) but we haven't quite figured out how to resolve this best, yet.

**Comment by develohpanda** [comment]
I will close this issue as resolved but please let me know if you have any other questions!

**Comment by heliommsfilho** [comment]
Thanks @develohpanda. I confirm that adding _operationId_ solves the problem.
