### ISSUE TITLE
Pull changes dissapear

### ISSUE THREAD

**Issue by amrinaas** [getinsomnia/insomnia#3971]
![image](https://user-images.githubusercontent.com/76085854/131301319-1239da3b-1e33-4456-8aeb-aef637129d1e.png)
My pull request dropdown is dissapear. I can't find the button

**Comment by develohpanda** [comment]
I see this issue has been closed, I assume you found how to pull collections, but in case anybody else stumbles across this issue, as of version 2021.5 you need to open a remote project (from the top left on the dashboard) and then you can pull collections available to that project/team. Some documentation [here](https://support.insomnia.rest/article/163-team-collaboration)!
