### ISSUE TITLE
 Insomnia Test tab crashes when object.prototype is used

### ISSUE THREAD

**Issue by Droptests** [getinsomnia/insomnia#3979]
**Insomnia Test tab crashes**
When executing code in Test tab Insomnia crashes.

**Steps to reproduce the behavior:**

1. Go to 'Test tab.'
2. Create New Test Suite
3. Select POST request
4. Enter this code:
    ```ts
    const res = await insomnia.send();
    expect(res.status).to.equal(200);

    expect(res.data).to.be.an('string');

    const body = JSON.parse(res.data);
    expect(body).to.be.an('object');

    Object.prototype.b ='Ongoing task';
    console.log(res)
    ```
5. Click on Run tests

**Expected behavior**
1. Test to pass successfully 

**Screenshots**
![Code](https://user-images.githubusercontent.com/82899589/131446176-707735dd-11ac-4afe-8577-ea8bcb991a49.png)
![error log](https://user-images.githubusercontent.com/82899589/131446178-05adaf52-70a4-4f9b-ae34-356931292e5d.png)

**Desktop (please complete the following information):**
 - OS: 
![Insomnia ver 1](https://user-images.githubusercontent.com/82899589/131446828-ae634808-e091-404f-b200-4a93e45486c3.png)

 - Installation Method: From official website.
 - App Version 
![Insomnia ver](https://user-images.githubusercontent.com/82899589/131446842-dea8459d-6bed-437e-832c-fa23e9efaf59.png)

**Additional context**
Removing prototype from "Object.prototype.b ='Ongoing task';" solves the problem for some reason.

**Comment by dimitropoulos** [comment]
I was able to reproduce on `develop`.

By the way, I was able to reduce the reproduction steps:
1. create a new test with the following code:
   ```ts
    Object.prototype.asdf ='Ongoing task';
    expect(true).to.be.equal(true)
    ```
1. run the test

I'll note, that this crashes the test list portion of the UI: (it looks like it broke in two places but it's just one section)

![image](https://user-images.githubusercontent.com/15232461/131722084-f4e32030-0e44-4a93-a5c9-0365fb7c4f16.png)

**Comment by dimitropoulos** [comment]
Can you please tell me what you are trying to do, such that you need to mutate the Object prototype?

**Comment by Droptests** [comment]
Hello,
I wanted to compare the object.prototype.b with specific part of the JSON
response, when converted to String as much as I could remember.

Hope this helps.

**Comment by dimitropoulos** [comment]
When you get a moment could you please provide that use-case.  It's relevant here because what we will do to fix this (I'm fairly sure) is disallow modifying prototypes of builtins (like Object and Array and String and Number).  Modifying prototype like this is known as "prototype pollution" and comes with a lot of potential problems.  I want to verify that there's another way to do what you are trying to do (but, without modifying the Object prototype).

**Comment by filfreire** [comment]
Hi @Droptests this is no longer reproducible if you try with the [latest stable Insomnia version (2022.4.2)](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2)

![Image](https://user-images.githubusercontent.com/11976836/181061593-a203abd2-2174-4e0c-945e-084fbe3c709f.png)


![Image](https://user-images.githubusercontent.com/11976836/181061686-45ef24fb-f2f6-4700-91b6-080f8399aa5f.png)

Please feel free to reopen this issue if you are still able to reproduce it with latest Insomnia, and also report any other issues you come across!
