### ISSUE TITLE
[Feature] Consider wildcards in proxy exclusion list

### ISSUE THREAD

**Issue by vision8tech** [getinsomnia/insomnia#398]
## Overview
- `Insomnia Version:` 5.7.0
- `Operating System:` macOS 10.12.6
- `Summary: ` Can you please improve the proxy exclusion list to allow wildcards?

![image](https://user-images.githubusercontent.com/14140226/28938329-71ed353c-7896-11e7-8165-929662bb8a65.png)

Thank you!

**Comment by gschier** [comment]
Hey @vision8tech! 

For the example in your screenshot, `.intranet.tech` should do the trick. Insomnia delegates proxy handing to libcurl, so it's pretty hard to change this behavior.

You can find more documentation here: https://curl.haxx.se/libcurl/c/CURLOPT_NOPROXY.html
