### ISSUE TITLE
Dashboard doesn't handle overflowing names

### ISSUE THREAD

**Issue by jackkav** [getinsomnia/insomnia#3984]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.1

### What operating system are you using?

macOS

### Operating System Version

N/A

### Installation method

N/A

### Expected Behavior

Overflow should have ellipses or something

### Actual Behavior

![image](https://user-images.githubusercontent.com/3679927/131524429-4b512df0-6c94-4dae-b9cb-6364bea37153.png)

### Reproduction Steps

Long nameeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by dimitropoulos** [comment]
<details>
<summary>testing text for this example</summary>
```
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
```
</details>

It seems there are two obvious solutions (among others, I'm sure):

on the left is what we have now.
in the middle is with a y-scroll
on the right is an ellipsis 

![_snap_insomnia_150_resources_app asar_renderer html](https://user-images.githubusercontent.com/15232461/131526314-80322dba-69c5-4b6d-8753-2e361f551d83.png)

I'd also like to note that this means it will spill onto any rows below:
![_snap_insomnia_150_resources_app asar_renderer html](https://user-images.githubusercontent.com/15232461/131526439-1bbce8e9-15e0-4a47-bcea-ee7e730be0f4.png)

**Comment by jackkav** [comment]
I like the ellipsis as it means we could also include collection description below a long title.

**Comment by dimitropoulos** [comment]
As a note: we can use `line-clamp` for this https://css-tricks.com/almanac/properties/l/line-clamp/

**Comment by dimitropoulos** [comment]
As another note: let's be sure to test this with different fonts and font sizes - no matter how we solve it.  It might be best to put an overflow-y on the container as a backup, anyway.  A scroll is less bad than it actually escaping out of the container like it does now.

**Comment by jackkav** [comment]
True, scroll appears to be more robust.

**Comment by mikaoelitiana** [comment]
Is anyone working on this? I am interested to take it

**Comment by dimitropoulos** [comment]
not so far as I'm aware!  please feel free to give it a shot!
