### ISSUE TITLE
APT repository returns 400 Bad Request

### ISSUE THREAD

**Issue by weirdan** [getinsomnia/insomnia#3988]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux portable-ws 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

### Installation method

Deb download

### Last Known Working Insomnia version

2021.3.0

### Expected Behavior

When I do `apt update` with insomnia repo in `/etc/apt.sources.d/` I expect apt to produce no errors and see updated insomnia packages.

### Actual Behavior

The following error is reported:

```
[.....snip.....]
Ign:31 https://download.konghq.com/insomnia-ubuntu default/all all Contents (deb)
Ign:32 https://download.konghq.com/insomnia-ubuntu default all Contents (deb)
Ign:33 https://download.konghq.com/insomnia-ubuntu default amd64 Contents (deb)
Err:22 https://download.konghq.com/insomnia-ubuntu default/all amd64 Packages
  400  Bad Request [IP: 3.20.242.208 443]
[.....snip.....]
Ign:32 https://download.konghq.com/insomnia-ubuntu default all Contents (deb)
Reading package lists... Done
E: Failed to fetch https://download.konghq.com/insomnia-ubuntu/dists/default/all/binary-amd64/Packages  400  Bad Request [IP: 3.20.242.208 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Reproduction Steps

1. Follow instructions from https://insomnia.rest/blog/new-insomnia-apt-repository
2. run `apt update`

### Additional Information

It was working after I had updated repo information following the instructions from that blogpost, but it stopped at some moment later.

**Comment by dimitropoulos** [comment]
Thank you for your clear writeup!  I followed your steps and was not able to reproduce:

```
Ign:9 https://download.konghq.com/insomnia-ubuntu default InRelease 
Hit:10 https://download.konghq.com/insomnia-ubuntu default Release                                 
Ign:12 https://download.konghq.com/insomnia-ubuntu default Release.gpg   
```

some questions:
1. could you please try again (now) and let us know your results.  there was some downtime the other day with download.konghq.com and I'd like to verify that you didn't happen to run this command during that downtime.
1. are you able to fire up a VPN, by any chance, and try from another area of the world (e.g. the US)?  There may be some geo restrictions (although, this is a longshot) on where you can access the repository from, so I'd be nice (but not mandatory) to see if this is related.  If not, would you mind saying which country you're connecting from so I can try to reproduce with a VPN, myself?

**Comment by weirdan** [comment]
1. I got same results, 400 Bad Request.
2. Using VPN via Frankfurt (Germany) worked. Previously, I was connecting from Ukraine.

**Comment by dimitropoulos** [comment]
Thanks for confirming.  That was it then, huh.  Sorry for the inconvenience but I don't think there's anything we can do about that.  If you think there is lemme know and we can reopen and investigate.

**Comment by weirdan** [comment]
I wonder why would there be any geographic restrictions in the first place?

**Comment by dimitropoulos** [comment]
I wonder that too, but all I know is that this is the way the repository works for some locations.

**Comment by weirdan** [comment]
Do you know if there's someone at kong (?) I can contact regardign this? Or could you raise that internally (seeing that you're a member of kong gh org)?

**Comment by rozhok** [comment]
Can confirm this behavior. I'm also connecting from Ukraine.

**Comment by reynolek** [comment]
Unfortunately this has to do with US restrictions on companies around I believe cryptography and Russia. Since we didn't have an easy way to only block connections from Crimea, we had to add a restriction to all of Ukraine.

**Comment by weirdan** [comment]
Well, I can still download insomnia deb file manually from updates.insomnia.rest, or from Github releases, so restriction is not that thorough. It's just apt repo that doesn't work, meaning it's just an inconvenience but not a blocker.

Is apt repo set up that way because some other kong product needed those restrictions?

**Comment by reynolek** [comment]
> Is apt repo set up that way because some other kong product needed those restrictions?

That is my understanding after talking to the team that runs the apt repo. Since we are hosting the repo ourselves, I can imagine our lawyers gave us requirements to fulfill -- I know its annoying to not be able to use apt. Sorry about that :(
