### ISSUE TITLE
[Question] Why does Insomnia send content-type 'text/plain' for GraphQL introspection and no content-type on normal requests?

### ISSUE THREAD

**Issue by tomelm** [getinsomnia/insomnia#400]
## Overview
- `Insomnia Version:` _5.7.0_
- `Operating System:`  _MacOS 10.12.6_
- `Summary: ` _content-type on GraphQL introspection query is sent as text/plain by default and empty otherwise_

## How To Reproduce
1. Open app and select 'GraphQL Query', introspection request is sent automatically
2. Write a GraphQL request and send it to the server, no content-type is set

## Other Notes
I was testing Insomnia against our API and noticed the requests were failing. Looking at the request that came in, it's structured as JSON so it seems like the content-type sent should be application/json by default:

```
ipdb> request.body
b'{"query":"\\n  query IntrospectionQuery {\\n    __schema {\\n      queryType { name }\\n      mutationType { name }\\n      subscriptionType { name }\\n      types {\\n        ...FullType\\n      }\\n      directives {\\n        name\\n        description\\n        locations\\n        args {\\n          ...InputValue\\n        }\\n      }\\n    }\\n  }\\n\\n  fragment FullType on __Type {\\n    kind\\n    name\\n    description\\n    fields(includeDeprecated: true) {\\n      name\\n      description\\n      args {\\n        ...InputValue\\n      }\\n      type {\\n        ...TypeRef\\n      }\\n      isDeprecated\\n      deprecationReason\\n    }\\n    inputFields {\\n      ...InputValue\\n    }\\n    interfaces {\\n      ...TypeRef\\n    }\\n    enumValues(includeDeprecated: true) {\\n      name\\n      description\\n      isDeprecated\\n      deprecationReason\\n    }\\n    possibleTypes {\\n      ...TypeRef\\n    }\\n  }\\n\\n  fragment InputValue on __InputValue {\\n    name\\n    description\\n    type { ...TypeRef }\\n    defaultValue\\n  }\\n\\n  fragment TypeRef on __Type {\\n    kind\\n    name\\n    ofType {\\n      kind\\n      name\\n      ofType {\\n        kind\\n        name\\n        ofType {\\n          kind\\n          name\\n          ofType {\\n            kind\\n            name\\n            ofType {\\n              kind\\n              name\\n              ofType {\\n                kind\\n                name\\n                ofType {\\n                  kind\\n                  name\\n                }\\n              }\\n            }\\n          }\\n        }\\n      }\\n    }\\n  }\\n"}
ipdb> request.content_type
'text/plain'
```

I also noticed if you don't specify a content-type explicitly none is added but the query is still JSON:
```
ipdb> request.body
b'{"query":"{\\n\\tbusiness(id: \\"garaje-san-francisco\\") {\\n\\t\\tname\\n\\t}\\n}","variables":"{}"}'
ipdb> request.content_type
''
```

**Comment by tomelm** [comment]
I wasn't sure if this was intentional behavior so marked this as a question. Happy to help debug further if need!

**Comment by gschier** [comment]
Hey @tomelm!

Hmm, switching to GraphQL should automatically add a `Content-Type: application/json` header under the Header tab of the app. Did you delete this auto-added header? 

The introspection request copies the headers from the current request, but it seems to default to `text/plain` if no `content-type` header is found. 

![image](https://user-images.githubusercontent.com/587576/28946521-03ab9d74-7860-11e7-9b8d-3b8afb324088.png)

**Comment by tomelm** [comment]
@gschier I can't recall if one got added. I swapped a pre-existing query to GraphQL that might've had a different content-type added, I might have deleted it by accident.

Appreciate you adding a small fix for this though! :D
