### ISSUE TITLE
Unable to install insomnia-plugin-uuid 

### ISSUE THREAD

**Issue by weiann-tractable** [getinsomnia/insomnia#4006]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.4.1

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur

### Installation method

Insomnia.rest

### Last Known Working Insomnia version

n/a as this is a plugin issue

### Expected Behavior

Able to download `insomina-plugin-uuid` with no issue

### Actual Behavior

Get this error when attempting to download plugin 

`Error: Yarn error warning insomnia-plugin-uuid > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`

![Uploading image.png…]()

### Reproduction Steps

1. Go to Insomnia Preferences
2. Go to plugin tab
3. Type `insomina-plugin-uuid` and attempt to install

### Additional Information

Seems like an issue with the version of the `uuid` dependency

**Comment by develohpanda** [comment]
Hi! Thanks for reporting this :) while we do need to update the uuid dependency, the good news in this instance is that this plugin is [pre-installed](https://github.com/Kong/insomnia/blob/develop/packages/insomnia-app/config/config.json#L29) within Insomnia. You should be able to use the UUID template tags by typing in any text field and triggering the auto-complete (cmd + space).

![image](https://user-images.githubusercontent.com/4312346/132205215-20c56493-98b9-4c0b-b64c-02b4f742bf46.png)

I'll close this issue, but if you do face issues please do comment and I can re-open if necessary! 😄
