### ISSUE TITLE
Installation fails during setup phase on Debian due to incorrect path

### ISSUE THREAD

**Issue by mpavkovic** [getinsomnia/insomnia#4010]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.2

### What operating system are you using?

Other Linux

### Operating System Version

Debian 10 (buster)

### Installation method

apt

### Expected Behavior

Installation should carry out without errors, proper symlink should be created in /usr/bin and correct SUID set for chrome-sandbox binary

### Actual Behavior

Postinstall script for deb package is using incorrect installation path (wrong capitalization) which results in binary not being linked from /usr/bin and failing to setup correct SUID for chrome-sandbox binary.

I've extracted the content of deb package and I'm submitting a fix
```diff
--- a/postinst
+++ b/postinst.fix
@@ -1,10 +1,10 @@
 #!/bin/bash
 
 # Link to the binary
-ln -sf '/opt/insomnia/insomnia' '/usr/bin/insomnia'
+ln -sf '/opt/Insomnia/insomnia' '/usr/bin/insomnia'
 
 # SUID chrome-sandbox for Electron 5+
-chmod 4755 '/opt/insomnia/chrome-sandbox' || true
+chmod 4755 '/opt/Insomnia/chrome-sandbox' || true
 
 update-mime-database /usr/share/mime || true
 update-desktop-database /usr/share/applications || true
```

I would submit a PR but I couldn't find the file in the repo

### Reproduction Steps

1. Follow the install instructions from the docs (linux, using an apt package manager)
2. Run apt-get install insomnia

**Comment by DMarby** [comment]
Hi @mpavkovic,

Thank you for reporting this! We'll be releasing a patch release shortly to address this.
