### ISSUE TITLE
Document/Collection settings modal an interact with panels beneath it

### ISSUE THREAD

**Issue by dimitropoulos** [getinsomnia/insomnia#4018]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.2

### What operating system are you using?

Ubuntu

### Operating System Version

Kubuntu 21.04

### Installation method

apt

### Expected Behavior

An open Document/Settings modal should not allow interactions with panels below it.

### Actual Behavior

You can resize the collection's sidebar with the modal open (but only on first load of the app!)

https://user-images.githubusercontent.com/15232461/132734903-ce7ff226-5d48-44b9-860f-dbdc073fcdba.mp4

### Reproduction Steps

1. open the app fresh
1. open a collection
1. open the collection settings
1. hover your mouse to a place where a panel exists below the modal

**Comment by alk-mandrianarijaona** [comment]
I see the same behaviour on macOs

**Comment by alk-mandrianarijaona** [comment]
@dimitropoulos I can work on this issue, can you assign it to me please?
