### ISSUE TITLE
[Bug] Environment editor does not update after import

### ISSUE THREAD

**Issue by noplanman** [getinsomnia/insomnia#402]
## Overview
- `Insomnia Version:` 5.7.4 (5.7.4.933)
- `Operating System:`  MacOS 10.11.6 (15G1510) (El Capitan)
- `Summary: ` After importing a modified exported file, the environment field doesn't update.

## How To Reproduce
1. Create a new workspace
2. Add some environment variables
3. Export workspace
4. Edit exported file and change environment data
5. Import the modified export
6. Edit the environment and see that the values are still the same

## Other Notes

Even though the input in the environment editor isn't updated, the values themselves are! So they can be used in requests etc.
Restarting Insomnia or closing and reopening the Insomnia window does a correct reload of the editor values.

**Comment by gschier** [comment]
Hi @noplanman. It seems like this might have been fixed unintentionally. I just tried in v5.10.1 and cannot reproduce what you reported in 5.7.4.
