### ISSUE TITLE
Failed to parse multipart response: content-type missing boundary

### ISSUE THREAD

**Issue by mfulton26** [getinsomnia/insomnia#4021]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.2

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.5.2

### Installation method

https://insomnia.rest/download

### Expected Behavior

Insomnia's "Visual Preview" intelligently parses `multipart/form-data` response bodies to detect the `boundary` whenever the `boundary` parameter is missing in the `content-type` response header.

![image](https://user-images.githubusercontent.com/5588957/132948731-4d912fe2-bdbc-40df-aadb-9afc75cd0761.png)

### Actual Behavior

Insomnia correctly received the `multipart/form-data` response but fails to parse it whenever the `boundary` parameter is missing in the `content-type` response header.

> Failed to parse multipart response: content-type missing boundary

![image](https://user-images.githubusercontent.com/5588957/132948322-2f8acf1a-5aeb-46f7-a8fc-6bd8df0d5623.png)

### Reproduction Steps

1. Run an HTTP server that returns a `multipart/form-data` response without a `boundary` parameter in the `content-type` response header. See https://github.com/oakserver/oak/issues/400 for an example.
2. Create a new request in Insomnia which will cause such an HTTP server to return the desired response (e.g. `GET http://localhost:8000/ HTTP/1.1`).
3. Send the request
4. View the "Visual Preview" for the response

**Comment by filfreire** [comment]
Hi @mfulton26, thank you for reporting this, and sorry for the long time to reply back here.

The problem seems to have been solved since you last reported it. For example, as of our [latest version (2022.3.0)](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0), we are sending `boundary` field like:

```
"content-type": "multipart/form-data; boundary=X-INSOMNIA-BOUNDARY",
```

Let us know if you're still somehow able to reproduce this with the latest version. If so, feel free to reopen this issue.
