### ISSUE TITLE
[Feature Request] Move requests between workspaces

### ISSUE THREAD

**Issue by anothernode** [getinsomnia/insomnia#403]
## Overview
- `Insomnia Version:` _5.7.4_
- `Summary: ` _I would like to be able to move requests from one workspace to another_

I spread lots of requests that actually belong to the same project over different workspaces because I was a little bit stupid. Now I find it awkward that I have to switch workspaces so often.

I would like to consolidate the requests belonging to the project in one workspace but I can't find any way to do it. As far as I can see, this is not a provided use case in insomnia so far and using export/import isn't an option either because you can only export and import whole workspaces but not requests or folders of requests.

**Comment by SingleShot** [comment]
+1

**Comment by multirealm** [comment]
+1

**Comment by multirealm** [comment]
+1

**Comment by ric2016** [comment]
+1

**Comment by partty** [comment]
+1
This can be anything from drag&drop, copy&paste to dedicated 'move to workspace' or 'copy to workspace' option. 
It'll be really nice if you can move or copy entire folders too.
It's a pain to recreate 20-30 requests with authentication, headers and data only to be able to export the workspace and include it in a project.

**Comment by njleonzhang** [comment]
This feature is so important. Any plan to support?

**Comment by rsantellan** [comment]
+1

**Comment by cocevk** [comment]
+10000

**Comment by bigsee** [comment]
+1

**Comment by gschier** [comment]
Finally getting around to this one!

**Comment by evgeny-degtyarev** [comment]
I can move some requests via drag&drop but i cannot move others

**Comment by darkguy2008** [comment]
Is there a way to move request **collections** between workspaces?
