### ISSUE TITLE
[Bug] Response Caching Prevents Chained Request from Seeing Latest Response

### ISSUE THREAD

**Issue by SingleShot** [getinsomnia/insomnia#405]
I have a request the checks the status of a job. The job is initially "executing" but eventually I will check it and it will be "completed". However, when I run a chained request that uses the status field parsed from the JSON response body as input, it is always "executing" even if the most recent status check request was "completed" (as displayed in Insomnia's response panel). There seems to be some caching of the original response when running chained requests, limiting their value for use with interfaces that require occasional polling.

**Comment by gschier** [comment]
Hi @SingleShot.

There's actually no response caching for the response tag. I just tested it on my end with a JSONPath query and confirmed it to be working as expected.

Here's my test case:

1. Create `Request A` to fetch some JSON
2. Send `Request A` to populate response
3. Reference `Request A` JSON property in a query parameter via a different `Request B` using the "Response -> body" template tag
4. Send `Request B`
5. Check the Timeline view to make sure the referenced value was correct
6. Update the value on the server
7. Resend `Request A`
8. Resend `Request B`
9. Check the Timeline view to make sure the referenced value was correct (updated to new value)

**Comment by gschier** [comment]
If you could provide a reproducible test case that I could try, that would be awesome.

**Comment by gschier** [comment]
I'm going to close this one for now, as it seems to be working as expected on my end. Will readdress if someone can provide a reproducible test case.

**Comment by Maxwell2022** [comment]
@gschier It looks like the parent request get cached somehow.

I have a similar issue where I need to authenticate the user to set the header of the next request. I'm using `Response -> body (attribute)` in the header and reference the response of my `POST /auth` request.

When the user token expires, the chained request return an auth error.

If I call manually the parent request (/auth) and the the chained one it's working.
I'm using `Version 5.15.0 (5.15.0.1953)`

**Comment by gschier** [comment]
@Maxwell2022, if I understand correctly, I think you may be referring to this issue instead: https://github.com/getinsomnia/insomnia/issues/286

**Comment by Maxwell2022** [comment]
@gschier Sorry for the late reply but yes, that is exactly this issue I have. Maybe it's not a bug but a feature request, however it's how I understand it was working. I'll follow this Github issue to get updates on it. Thanks
