### ISSUE TITLE
Query url preview display error.

### ISSUE THREAD

**Issue by anyforever** [getinsomnia/insomnia#4051]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.3

### What operating system are you using?

Windows

### Operating System Version

Win10

### Installation method

download and install

### Last Known Working Insomnia version

2021.5.3

### Expected Behavior

![preview](https://wx3.sinaimg.cn/mw2000/001P2Lxcly1gusq8qqeg9j60gw07ht9p02.jpg)

#3934 but it still exist.

### Actual Behavior

none

**Comment by develohpanda** [comment]
Thanks for reporting @anyforever! This has been resolved by #3995 but not released yet. We aim to have a beta or stable release towards the end of October, which will include this fix.
