### ISSUE TITLE
[Feature Request] Pin tabs on per-request basis

### ISSUE THREAD

**Issue by xinshangshangxin** [getinsomnia/insomnia#406]
## Overview
- `Insomnia Version:` 5.7.4 (5.7.4.933)

![image](https://user-images.githubusercontent.com/8779091/29055003-5fff16d0-7c2c-11e7-9d2f-fadaf8ecda1a.png)

Mostly, When a `POST` request, I want to see the `JSON/Body` tab
When a `GET` request, I want to see the `query` tab

**Comment by adius** [comment]
Also the ratio of input data to request preview should be pinnable!

**Comment by adius** [comment]
Well, here is some activity! I still would like to have this feature :grin:
