### ISSUE TITLE
Problem with Let's Encrypt - Commit/Pull/Push to Git Repository

### ISSUE THREAD

**Issue by amirzandi** [getinsomnia/insomnia#4067]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.3

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.6

### Installation method

download from website

### Last Known Working Insomnia version

2021.5.3

### Expected Behavior

It was working fine with my own Gitlab server since yesterday.

PS. my gitlab server is secured with Let's Encrypt Free certificate.

### Actual Behavior

Problem occurred when I wanted to push my changes into my own Gitlab server (with Lets Encrypt Free Certification) and it shows the following error:

Cannot read property 'request' of undefined.

TypeError: Cannot read property 'request' of undefined
    at Object.request (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:130995:27)
    at async Function.discover (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:6559:13)
    at async Object.getRemoteInfo (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/isomorphic-git/index.cjs:9343:20)
    at async GitVCS.canPush (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:87139:28)
    at async GitSyncDropdown._handlePush (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:309511:23)

### Reproduction Steps

Set up a gitlab server with Let's Encrypt Certification and try to push your commits, error would be occurred.

**Comment by develohpanda** [comment]
Thanks for reporting this! It seems related to https://github.com/Kong/insomnia/issues/2458 because the stack trace is identical, but it's useful to know the specifics of your environment. It's interesting you note that this was working fine on the latest release of Insomnia (2021.5.3), and then it stopped working all of a sudden.

**Comment by amirzandi** [comment]
@develohpanda Thanks for the comment. Yes it was working fine on previous versions.

**Comment by develohpanda** [comment]
In the description you mention that the last known working Insomnia version was 2021.5.3, and we haven't made any updates since then, which is what I find curious, but there could be something else at play considering there are other, similar bug reports too.

**Comment by bugi89** [comment]
Temporary solution 1, run Insomnia by CLI: 

```
export NODE_TLS_REJECT_UNAUTHORIZED=0
insomnia
```

Temporary solution 2, paste followed code in DevTools: 

```
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;
```

**Comment by wdawson** [comment]
Probably associated with Let's Encrypt's Root cert expiring? https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by tom-at-bowntie** [comment]
Unfortunately neither of the temporary solutions posted by @bugi89 doesn't seem to be working for me. I'm at a point where I can't even go through the Set Up Git Sync flow anymore.

**Comment by tom-at-bowntie** [comment]
I wanted to follow up and also highlight that I'm unable to git clone any repositories either, public or private 😅 The console error logs in the dev tools are actually very sparse in the information given:

`11:36:40.337 › [ga] Event Modals, Show, GitRepositorySettingsModal
11:37:24.362 › [ga] Event Git, Clone
11:37:24.379 › [ga] Event Modals, Show, AlertModal`

<img width="396" alt="Screen Shot 2021-10-07 at 11 37 34 AM" src="https://user-images.githubusercontent.com/66454382/136427527-7f2e59fc-2905-4fff-b305-28e3bed83b60.png">

**Comment by jackkav** [comment]
You can disable SSL verification in the insomnia settings to get around this.

![image](https://user-images.githubusercontent.com/3679927/136921314-1e51eb3c-65f0-434c-a18d-21c2300f5559.png)

**Comment by amirzandi** [comment]
@jackkav I have tested with this option, not worked.

**Comment by tom-at-bowntie** [comment]
I'm still running into the same error when attempting to clone the repo with the validate certificates option turned off

<img width="780" alt="Screen Shot 2021-10-19 at 10 32 35 AM" src="https://user-images.githubusercontent.com/66454382/137943500-388a2a45-ee0c-4c85-8a4c-41694926e2bb.png">

**Comment by johnwchadwick** [comment]
I suspect this is happening because Insomnia is currently running on Electron 11.2.3, and the isomorphic-git client is using the Node.JS HTTP client, which by default uses a bundled set of root CAs, and the newer Let's Encrypt root certificate is not included. I wonder if the Validate Certificates option should control validation of TLS certificates when using Git, too.

The issue should be fully resolved when Insomnia is updated to a newer version of Electron. Setting the environment variable `NODE_TLS_REJECT_UNAUTHORIZED` to `0` before running Insomnia should also work around the issue, though obviously it will also disable Node.JS certificate checking in general.

**Comment by johnwchadwick** [comment]
Ah, I wasn't paying attention. The Validate Certificates option also applies to Git operations as of #4042, which should land in the next release.

**Comment by develohpanda** [comment]
Hi all, [2021.6](https://github.com/Kong/insomnia/releases/tag/core%402021.6.0) has been released which should include some better error messaging here to help narrow down the issue. Could you please report back any findings and whether you still experience this error after upgrading?

**Comment by wongstein** [comment]
Want to further pipe in that if the issue originates with Insomnia's Electron version, we have since upgraded that to latest.  Let us know if you can still reproduce this error.

**Comment by wongstein** [comment]
Closing this issue for now, due to inactivity.  Feel free to open again when the error is reproduced with latest Insomnia
