### ISSUE TITLE
[Feature Request] Converst JS to JSON during Beautify

### ISSUE THREAD

**Issue by xinshangshangxin** [getinsomnia/insomnia#407]
## Overview
- `Insomnia Version:`  5.7.4 (5.7.4.933)
![image](https://user-images.githubusercontent.com/8779091/29055084-e238e220-7c2c-11e7-825a-2af37c55afbc.png)

If I write a js object,  I want to format to a json (like [`jsoneditoronline`](http://jsoneditoronline.org/)), or when send it transform to json;

**Comment by gschier** [comment]
This is a fairly difficult problem to solve. Do you know of any existing libraries for converting JS syntax to JSON?

**Comment by gschier** [comment]
That seems rather _unsafe_ ☠️

**Comment by LouisRitchie** [comment]
`JSON.stringify()`.

**Comment by gschier** [comment]
@LouisRitchie it would need to be a JS object to do that. Hence the unsafe eval suggestion above to turn it from a string to a JS object.

**Comment by gschier** [comment]
Hmm, found a few suggestions here. https://stackoverflow.com/questions/9637517/parsing-relaxed-json-without-eval

**Comment by jonjaques** [comment]
Would [JSON5](https://github.com/json5/json5#features) be acceptable? The project has been around for quite awhile and is based of Crockford's original implementation.

**Comment by gschier** [comment]
I think JSON5 could possibly work.

**Comment by jonjaques** [comment]
Do you think it would work better as it's own body type (ie. JSON & JSON5) or do we just patch JSON to try and parse and if it fails fallback to JSON5?

I have not looked at the nunjucks templating code yet, but do you forsee any issues integrating with that?

**Comment by gschier** [comment]
Ya, I'm not quite sure about that yet. Currently, Insomnia uses a custom parser to prettify JSON in order to modify it as little as possible. It might actually be possible to modify it to do things like add quotes and ignore comments. It already does this with Nunjucks tokens.

**Comment by gschier** [comment]
Comments are actually  pretty tricky though since you want to keep them in but you don't want to send them with the request. In that case, a new body type may be desirable.

**Comment by gschier** [comment]
Actually, this issue wasn't really about comments so maybe that doesn't matter.

There is actually already a way to do comments and that's using Nunjucks sytax `{# a comment #} `

**Comment by jonjaques** [comment]
Sure, thanks for the info! I think I will have some time this weekend to start hacking on this.

**Comment by gschier** [comment]
Awesome! What's your rough plan? Just want to make sure we're on the same page since a lot has been discussed here.

Also, let me know if there's anything I can help with. 😀

**Comment by jonjaques** [comment]
Hmm. I think the main scope of this and what I personally would like as well is just unquoted keys and single-quoted strings (trailing commas would be nice too).

Plan would be to see if we can just hack those into the existing parser and call it a win? As I said, have not looked at the code very closely at all (except to see that it is nicely organized 😄 ), so I think I will need to dig in a bit before I know more.

**Comment by gschier** [comment]
That sounds perfect. We were on the exact same page.
