### ISSUE TITLE
Windows 10 Problem to start insomnia

### ISSUE THREAD

**Issue by trireme** [getinsomnia/insomnia#4088]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 1709

### Installation method

download from Insomnia

### Expected Behavior

I should see something if I start the App. I never used Insomnia before therefore an empty black panel is not I expected.

### Actual Behavior

After Starting there is only black panel nothing more.

### Reproduction Steps

1. Start the app
2. Black empty Panel
3. I can navigate to View-DevTools
4. There is an Error in the console: Not allowed to load local resource: file:///C:/Users/OW#1114\AppData\Local\insomnia\app-2021.5.3\resources\app.asar/renderer.html
5. I can navigate to the Directory with Filemanager and copy, read, and delete app.asar.

### Additional Information

![grafik](https://user-images.githubusercontent.com/304338/136569449-47fb98b4-ca57-452b-858d-4c112ca28727.png)

**Comment by filfreire** [comment]
Hi @trireme, thank you for reporting this.

Are you by any chance still able to reproduce this using the [latest Insomnia release (2022.3.0)](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)?

**Comment by trireme** [comment]
I am not able to reproduce it as before, the latest version of insomnia worked for me, I assume the main problem is the path "file:///C:/Users/OW#1114\" I used before, the # is a common problem for most apps. As I don't use it now, it could have been the cause for the error. For me the issue is closed.
