### ISSUE TITLE
Insomnia does not recognize OAuth2 authentication scheme properly

### ISSUE THREAD

**Issue by MartinThoma** [getinsomnia/insomnia#4095]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.3

### What operating system are you using?

Ubuntu

### Operating System Version

Linux pc08 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

downloaded from insomnia.rest

### Expected Behavior

The OAuth 2 security scheme with  client credientials is recognized as it is specified correctly in the YAML

### Actual Behavior

No authentication is recognized:

![image](https://user-images.githubusercontent.com/1658117/136849037-99ff9e25-6200-45c1-8081-a5ab0ca3a776.png)

### Reproduction Steps

1. Save https://gist.github.com/MartinThoma/d144aeccfa4e68419a6b5105f34a606b as swagger.yaml
2. Import it as a file
3. Look at the only endpoint `/v2/investors` in the Auth-Tab

### Additional Information

Only when the `scheme: bearer` is added, Insomnia recognizes OAuth2 with client credentials. However, doing so is invalid according to OpenAPI 3 specs: https://swagger.io/specification/#security-scheme-object

**Comment by martin-thoma** [comment]
I don't see this in the release notes: https://insomnia.rest/changelog

Will this be part of the next release?
