### ISSUE TITLE
Password can be copy & pasted into clear text.

### ISSUE THREAD

**Issue by benlime** [getinsomnia/insomnia#410]
## Overview
- `Insomnia Version:` _5.7.4_
- `Summary: ` _If you choose NTLM Auth and enter a password, the password can be copy & pasted into clear text._

## How To Reproduce
_Please list all pertinent information and steps needed to reproduce the issue. For example:_
1. _Create new request_
2. _Add NTLM Auth_
3. _Enter password_
4. _Select and copy password_
5. _Paste into any text editor_

**Comment by gschier** [comment]
Hi @benlime,

Thanks for letting me know about this. Just pushed a fix for it.
