### ISSUE TITLE
Insomnia ignores environment variables with valid JSON keys

### ISSUE THREAD

**Issue by RobJacobson** [getinsomnia/insomnia#4103]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

Download of Windows installer

### Expected Behavior

Given the following workspace:

```
{
  "key": "apiaccesscode=0123456789",
  "fares": "https://www.wsdot.wa.gov/ferries/api/fares/rest",
  "schedules": "https://www.wsdot.wa.gov/ferries/api/schedule/rest",
  "today": "2021-10-12",
  "tomorrow": "2021-10-13",
  "Anacortes": 1,
  "Bainbridge Island": 3,
  "Bremerton": 4,
  "Clinton": 5,
  "Coupeville": 11,
  "Edmonds": 8,
  "Fauntleroy": 9,
  "Friday Harbor": 10,
  "Kingston": 12,
  "Lopez Island": 13,
  "Mukilteo": 14,
  "Orcas Island": 15,
  "Point Defiance": 16,
  "Port Townsend": 17,
  "Seattle": 7,
  "Shaw Island": 18,
  "Sidney B.C.": 19,
  "Southworth": 20,
  "Tahlequah": 21,
  "Vashon Island": 22,
  "ana-sj-sid": 272,
  "ed-king": 6,
  "f-s": 13,
  "f-v-s": 14,
  "muk-cl": 7,
  "pd-tal": 1,
  "pt-key": 8,
  "s-v": 15,
  "sea-bi": 5,
  "sea-br": 3
}
```

Expected behavior: Keys like "Bainbridge Island", "Sidney B.C." and "f-s" are valid strings and should be treated as valid keys for the Insomnia URL.

In "cromulent" JSON, a key can be any valid quoted string. There are just a handful of characters that must be escaped:

```
   The representation of strings is similar to conventions used in the C
   family of programming languages.  A string begins and ends with
   quotation marks.  All Unicode characters may be placed within the
   quotation marks, except for the characters that MUST be escaped:
   quotation mark, reverse solidus, and the control characters (U+0000
   through U+001F).

...

  string = quotation-mark *char quotation-mark

      char = unescaped /
          escape (
              %x22 /          ; "    quotation mark  U+0022
              %x5C /          ; \    reverse solidus U+005C
              %x2F /          ; /    solidus         U+002F
              %x62 /          ; b    backspace       U+0008
              %x66 /          ; f    form feed       U+000C
              %x6E /          ; n    line feed       U+000A
              %x72 /          ; r    carriage return U+000D
              %x74 /          ; t    tab             U+0009
              %x75 4HEXDIG )  ; uXXXX                U+XXXX

      escape = %x5C              ; \

      quotation-mark = %x22      ; "

      unescaped = %x20-21 / %x23-5B / %x5D-10FFFF```
```
Source:
https://datatracker.ietf.org/doc/html/rfc8259

### Actual Behavior

1. Insomnia complains about the periods in the key "Sidney B.C.": 
```"Sidney B.C." cannot begin with '$ or contain a '.'```

It does not allow you to save the workspace until the periods are eliminated.

![image](https://user-images.githubusercontent.com/23462125/137063833-c0d4461e-98fa-410e-8289-ad443485009c.png)

2. Insomnia silently ignores any keys that have spaces in them (like "Bainbridge Island") and any keys that have hyphens (like "f-s"). If you attempt to insert a key into a URL, but the key has either a space or a hyphen, then Insomnia simply won't show those keys.

(In my opinion, this "silent failure" is worse than the explicit failure concerning periods. With "Sidney B.C.", I was alerted to the fact that the periods weren't allowed. I did not receive a similar warning with keys like "Bainbridge Island" or "f-s." These keys simply didn't show up in the autocomplete suggestions. This confused me.)

### Reproduction Steps

1. Create a workspace with the above content.
2. Note the warning about periods in "Sydney B.C." -- and the lack of warnings for other keys.
3. Place the cursor in the Insomnia "URL bar" and type "." to get autocomplete suggestions. The autocomplete list does not show any keys that contain a space (like "Bainbridge Island") or a hyphen (like "p-t").

### Additional Information

Ideally, Insomnia should be compatible with any valid JSON key. Since keys are shown in the URL bar as colored blocks, phrases like "Bainbridge Island" are obviously keys and not literal strings. In other words, keys should be valid even if they contain characters, like spaces, that aren't allowed in URLs.

Alternatively, Insomnia should warn about invalid punctuation in keys. For example, it should warn that the space in "Bainbridge Island" and the hyphen in "f-s" isn't valid, rather than failing silently.

Thanks!

**Comment by filfreire** [comment]
Hi @RobJacobson, appreciate you for reporting this, and apologies for us not getting back sooner with any feedback to your issue.

I was able to reproduce this, thank you for sharing detailed steps.

I'm not entirely sure if we want to support environment keys with literal spaces and punctuation marks, as I believe, and someone else from the team can correct me here, that it would affect/impact how we store and handle environment variables internally on Insomnia.

With that said, I agree with you, that at the very least insomnia should not silently fail for the cases where clearly we wouldn't support a given environment key, and similarly to how we warn users about a key like `Sydney B.C.` we should warn as well about a key with spaces like `Bainbridge Island`.

This latter improvement might be more achievable in the short time. We will update you here on GitHub if there's any changes for this.

Feel free to report other issues you might come across 👍

**Comment by RobJacobson** [comment]
Thanks for looking into this! I'd forgotten about this by now. I realize that it's an edge case. I'm not sure why I spent so much time reporting it.  :-)

**Comment by Kaned1as** [comment]
Why is this closed? I can't use valid JSON keys with hyphen `-` in the name
