### ISSUE TITLE
[Performance] Application become unresponsive for large JSON

### ISSUE THREAD

**Issue by madmax** [getinsomnia/insomnia#412]
## Overview
- `Insomnia Version:` _5.7.4.933_
- `Operating System:`  _10.13 Beta (17A330h)_
- `Summary: ` When request return very big JSON (2MB) application become unresponsive.

## How To Reproduce
When request return very big JSON (2MB) application become unresponsive. 

## Other Notes
It will be nice to have settings to limit size of JSON that is displayed.

**Comment by gschier** [comment]
This is an interesting problem because it depends on o the hardware. What kind of computer are you running Insomnia on?

Insomnia does, in fact, implement a size limit but it's currently set to 3MB: https://github.com/getinsomnia/insomnia/blob/develop/app/common/constants.js#L57
Maybe a solution is to lower this default value and let the user increase it via a setting?

**Comment by madmax** [comment]
Macbook pro 2013 8gb i7

**Comment by madmax** [comment]
I think the problem is that Insomnia calculate respond size before it is ungziped and my 2.9mb response is actually 45MB response :)

**Comment by gschier** [comment]
Ah, that's definitely the issue then. I've noticed things start slowing down after around 50MB of JSON on my 2016 Macbook Pro. I guess I should change it to account for the raw size instead.

**Comment by madmax** [comment]
I have tested this json (45mb) on Paw app and it work very fast compared to insomnia.

**Comment by gschier** [comment]
Insomnia wasn't designed to work for responses that large. I might spend some time working on improving this eventually, but it hasn't been a priority so far.

**Comment by madmax** [comment]
@gschier perfectly understand it not usual to get so big json. Its probably because Paw use native components not Electron. But it will be nice to have ability to see raw json fast or just not render it in the same thread and block rest of UI (if it is possible).

**Comment by gschier** [comment]
Totally agree. One day, one day 😄

**Comment by madmax** [comment]
@gschier what about fixing limit check on decompressed response?

**Comment by gschier** [comment]
Ya, I'm releasing the next version of the app today, but I'll make sure that's fixed in the next one 😄

**Comment by madmax** [comment]
Currently I downloaded development branch and changed 3mb to 0.5mb :) Its not perfect but application start working again.

**Comment by gschier** [comment]
Oh ya, sorry about that. If you want, you can also delete the individual response file(s) manually. On Mac, responses are stored in `$HOME/Library/Application Support/Insomnia/responses`

**Comment by iquirino** [comment]
I'm having the same issue on v6.3.2
But with a image as the response.

The application crashed at the first time and continues crashing when i open it.

Where is this path for Windows?

Thank you!

**Comment by gschier** [comment]
Should be in the %APPDATA% directory I think @iquirino
