### ISSUE TITLE
[Usability] There should be an indication that `Send` has a context menu

### ISSUE THREAD

**Issue by helpermethod** [getinsomnia/insomnia#413]
## Overview
- `Insomnia Version:` _5.7.4_
- `Operating System:`  _Win 10_
- `Summary: ` _There is no visual indication that you can right-click the Send button. I've search for nearly half an hour on how to generate code from the current request._

**Comment by gschier** [comment]
Hey @helpermethod! 

Ya, there is no indicator on the Send button because there isn't enough room to put one. Maybe I'll add a "title" attribute which will show on hover.

The code generation feature is actually intended to be accessed from the sidebar request menu.
