### ISSUE TITLE
Launching Insomnia Core with Ozone/Wayland causes a SIGSEGV

### ISSUE THREAD

**Issue by nermolov** [getinsomnia/insomnia#4131]
### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.3

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 35

### Installation method

AppImage

### Expected Behavior

Launching Insomnia with Ozone/Wayland enabled launches the application and it functions.

### Actual Behavior

Launching Insomnia with Ozone/Wayland enabled opens the main window, then crashes with the following log:

```
./Insomnia.Core-2021.5.3.AppImage --enable-features=UseOzonePlatform --ozone-platform=wayland
14:26:23.339 › Running version 2021.5.3
14:26:23.359 › [electron client protocol] FAILED to set default protocol 'insomnia://'
14:26:23.374 › [electron client protocol] the current executable is not the default protocol for 'insomnia://'
14:26:23.486 › [electron client protocol] the default application set for 'insomnia://' was not found
14:26:23.673 › [fix] Running database repairs
14:26:23.730 › [db] Initialized DB at /home/nik/.config/Insomnia/insomnia.$TYPE.db
14:26:23.730 › [db] Init responses DB
14:26:23.732 › [localstorage] Initialized at /home/nik/.config/Insomnia/localStorage
14:26:23.871 › [main] Loading file:///tmp/.mount_InsomnaBrDek/resources/app.asar/renderer.html
14:26:23.886 › [ga] Non-interactive General, Updated, 2021.5.3
14:26:23.902 › [ga] Queued event [
  { name: 't', value: 'event' },
  { name: 'ec', value: 'General' },
  { name: 'ea', value: 'Updated' },
  { name: 'ni', value: '1' },
  { name: 'el', value: '2021.5.3' }
]
fish: Job 1, './Insomnia.Core-2021.5.3.AppIma…' terminated by signal SIGSEGV (Address boundary error)
```

### Reproduction Steps

1. Launch Insomnia with the following flags: `--enable-features=UseOzonePlatform --ozone-platform=wayland`

### Additional Information

I'm running on a HiDPI display, so using XWayland as a rendering backend makes the UI really blurry, hence the draw towards using Wayland rendering. This works under other Electron applications I've used (Discord, Slack, Signal).

**Comment by frysztak** [comment]
Native Wayland support came with Electron 12, Insomnia is currently at Electron 11. Related PR:  #4160

**Comment by filfreire** [comment]
Hi folks! Sorry for long wait, and thank you for reporting this issue!

We upgraded Insomnia to [Electron 17 on version 2022.2.0](https://insomnia.rest/changelog#2022.2.0).

Recently we merged @matthew-jones-uk's PR that has a particular fix for this issue by upgrading to [electron 17.3.1](https://www.electronjs.org/releases/stable?page=2#17.3.1).

It should be included tomorrow in our [upcoming beta release](https://github.com/kong/insomnia/releases) (`2022.3.0-beta.4`). Let us know if you still have issues with that release once it's out.

cc @nermolov @frysztak @matthew-jones-uk

**Comment by leonardehrenfried** [comment]
I've tried out this feature just now and now see Insomnia in all its HPDI glory - thanks!

However, the window doesn't have any window borders and I cannot move it.

I'm starting Insomnia like this:

```
 /opt/Insomnia/insomnia --enable-features=UseOzonePlatform --ozone-platform=wayland
 ```

Am I missing a flag? Is anyone else experiencing this?
