### ISSUE TITLE
Failed on install InsomniaCli with Node16.11.1 in M1

### ISSUE THREAD

**Issue by rafarocha** [getinsomnia/insomnia#4136]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.3

### What operating system are you using?

macOS

### Operating System Version

11.4

### Installation method

npm install --global insomnia-inso

### Last Known Working Insomnia version

-

### Expected Behavior

Just complete the installation successfully.

### Actual Behavior

Receive this logs on install via npm/node on mac m1 11.4 
https://gist.github.com/rafarocha/8c826b28c8ccba759307b2f58d8f152b
https://gist.github.com/rafarocha/378d25ffe3f4ffa09849109cc6d7ae50

node v16.11.1
npm npm@8.1.0
nvm v0.39.0 
macbook 2020 M1 big sur 11.4

Version: Insomnia 2021.5.3
Release date: 9/13/2021
OS: Darwin x64 20.5.0
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0

### Reproduction Steps

Run command bellow with node 16.11.1 on Mac 11.4

1. npm install --global insomnia-inso
2. Receive this log bellow

logs
https://gist.github.com/rafarocha/8c826b28c8ccba759307b2f58d8f152b
https://gist.github.com/rafarocha/378d25ffe3f4ffa09849109cc6d7ae50

### Additional Information

Is there a recommended node/npm version for my setup?

**Comment by wdawson** [comment]
Hi @rafarocha ! Right now inso is only compatible with Node.js 12.x LTS per the [inso docs](https://docs.insomnia.rest/inso-cli/install).

Regarding the M1 macs, we currently have [a PR out to the dependency](https://github.com/JCMais/node-libcurl/pull/312) that looks like it's failing for you. For the Apple silicon issues, we're tracking those in #2964 so I'm going to close this issue. We're all hoping for a quick resolution!
