### ISSUE TITLE
Insomnia hangs when encountering redirect loop

### ISSUE THREAD

**Issue by bannmann** [getinsomnia/insomnia#414]
## Overview
- `Insomnia Version:` 5.7.4
- `Operating System:`  Windows 10 Pro 1703
- `Summary: ` When a server repeatedly responds with redirects, Insomnia seems to hang forever, probably stuck in an endless loop. The request can be cancelled, though.

## How To Reproduce
1. Perform a `GET` request to https://ethereal-deposit.glitch.me/redirect-loop, a test URL I set up that redirects to itself.

## Other Notes

After a few redirects, Chrome and Firefox react with a "too many redirects" error page. This is the behavior I'd expect from Insomnia as well. Note that a redirect loop could be indirect as well, e.g. A redirecting to B, B to C, C to A.

Fun fact: In this situation, Postman claims it "could not connect" which is a plain lie.

**Comment by gschier** [comment]
Thanks @bannmann! I just added a fix for this. Going forward, the max redirects will be 20, which is apparently what most browsers use.
