### ISSUE TITLE
Couldn't install on debian 11

### ISSUE THREAD

**Issue by hiwyn** [getinsomnia/insomnia#4144]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021 5.0

### What operating system are you using?

Other Linux

### Operating System Version

debian 11

### Installation method

Ubuntu/Debian

### Expected Behavior

trying to follow https://docs.insomnia.rest/insomnia/install#ubuntudebian
it did not work i had to use snap (it is bad)

### Actual Behavior

after: sudo apt-get install insomnia
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 insomnia : Depends: libappindicator3-1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### Reproduction Steps

```
echo "deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all" \
    | sudo tee -a /etc/apt/sources.list.d/insomnia.list
```
    
- works

```
# Refresh repository sources and install Insomnia
sudo apt-get update
```

- works

### Additional Information

on debian 9 it was working

**Comment by jackkav** [comment]
Related: https://github.com/electron/electron/issues/27527
