### ISSUE TITLE
 Broken Alt+Shift keyboard layout switcher interaction with Alt menu key 

### ISSUE THREAD

**Issue by Maia-Everett** [getinsomnia/insomnia#4145]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.0

### What operating system are you using?

Ubuntu

### Operating System Version

Kubuntu 21.10 (KDE)

### Installation method

download from insomnia.rest

### Expected Behavior

Upon pressing Alt+Shift, the keyboard layout is switched and the menu doesn’t gain focus.

### Actual Behavior

Upon pressing Alt+Shift, the keyboard layout is switched and the menu gains focus.

### Reproduction Steps

1.  Install KDE.
2.  Have at least two keyboard layouts.
3.   Set the keyboard layout switch to Alt+Shift.
4.    Open Insomnia.
5.    Press Alt+Shift to switch keyboard layouts.

### Additional Information

See Electron bug https://github.com/electron/electron/issues/28088

This bug should be fixed in Electron 13.1.0 and above: https://github.com/electron/electron/releases/tag/v13.1.0

**Comment by filfreire** [comment]
@Maia-Everett I couldn't reproduce this on Kubuntu 21.10, using latest Insomnia build 2021.6.0

Example recording:
https://user-images.githubusercontent.com/11976836/141478552-06f56de1-f828-42b3-bdc3-77cbcd5eb11e.mp4

Can you still reproduce this using latest Insomnia version?

**Comment by Maia-Everett** [comment]
Still happens for me with the 2021.6.0 AppImage build on Kubuntu 21.10.

It also happens in your video: when you press the key combination, the "Application" menu gains focus. For me it doesn't happen when switching *away* from the English layout, but does happen when switching *to* the English layout.

**Comment by MurzNN** [comment]
To fix this issue seems we need to simply upgrade Electron dependency to version `^13.1`, regarding https://github.com/electron/electron/issues/28088#issuecomment-869549125

**Comment by Maia-Everett** [comment]
Fixed for me in version 2022.2.1. Thanks!
