### ISSUE TITLE
[Installer] deb package needs to ensure /usr/local/bin exists

### ISSUE THREAD

**Issue by vfaronov** [getinsomnia/insomnia#415]
## Overview
- `Insomnia Version:` 5.7.4-933
- `Operating System:`  Ubuntu 16.04
- `Summary: ` The `insomnia` Debian/Ubuntu package attempts to create a symbolic link `/usr/local/bin/insomnia`, but it does not ensure that the `/usr/local/bin` directory exists.

## How To Reproduce
```
$ sudo dpkg -i insomnia_5.7.4_amd64.deb 
Selecting previously unselected package insomnia.
(Reading database ... 260939 files and directories currently installed.)
Preparing to unpack insomnia_5.7.4_amd64.deb ...
Unpacking insomnia (5.7.4-933) ...
Setting up insomnia (5.7.4-933) ...
ln: failed to create symbolic link '/usr/local/bin/insomnia': No such file or directory
dpkg: error processing package insomnia (--install):
 subprocess installed post-installation script returned error exit status 1
```

## Other Notes

I think you need to list `usr/local/bin` in `debian/dirs` (wherever you have that), but I’m not sure.

**Comment by gschier** [comment]
Thanks for submitting this @vfaronov 😄 

Curious why you don't have a `usr/local/bin`? 

Insomnia uses a (very popular) [3rd-party package](https://github.com/electron-userland/electron-builder) to do the deb generation so I feel like this is a rare case.

**Comment by vfaronov** [comment]
> Curious why you don't have a `usr/local/bin`?

Good question. I had assumed that Ubuntu did not have it by default. But I just checked another Ubuntu system of mine, and it’s there. Could be that I accidentally deleted this directory when uninstalling something from there.

So this issue is probably wrong, sorry.

**Comment by gschier** [comment]
Thanks for the reply @vfaronov. I'll close this for now but would consider re-opening if more people run into it.
