### ISSUE TITLE
Git Sync reporting expired certificate incorrectly

### ISSUE THREAD

**Issue by nektru** [getinsomnia/insomnia#4153]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.3

### What operating system are you using?

Other Linux

### Operating System Version

Linux psnt 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

### Installation method

deb package

### Last Known Working Insomnia version

-- no information --

### Expected Behavior

Document successfully created from the git repository.

### Actual Behavior

TypeError: Cannot read property 'request' of undefined
    at Object.request (file:///opt/Insomnia/resources/app.asar/bundle.js:130995:27)
    at async Function.discover (/opt/Insomnia/resources/app.asar/node_modules/isomorphic-git/index.cjs:6559:13)
    at async _fetch (/opt/Insomnia/resources/app.asar/node_modules/isomorphic-git/index.cjs:7251:22)
    at async _clone (/opt/Insomnia/resources/app.asar/node_modules/isomorphic-git/index.cjs:7628:42)
    at async Object.clone (/opt/Insomnia/resources/app.asar/node_modules/isomorphic-git/index.cjs:7751:12)
    at async Object.shallowClone (file:///opt/Insomnia/resources/app.asar/bundle.js:309737:5)
    at async GitRepositorySettingsModal.onSubmitEdits [as _onSubmitEdits] (file:///opt/Insomnia/resources/app.asar/bundle.js:168922:25)

### Reproduction Steps

**Got an error while creating new document**
1. Click the "Create" button on the dashboard
2. Select the "Git Clone" option
3. Fulfill requested data
4. Got error "Cannot read property 'request' of undefined"

**Got an error while syncing existing document to the git**
1. Go to the existing document
2. Click "Setup Git Sync"
3. Fulfill requested data
4. Got error "Cannot read property 'request' of undefined" but now with the stacktrace.

**Comment by nektru** [comment]
![Screenshot from 2021-10-26 15-43-17](https://user-images.githubusercontent.com/9137294/138881824-692ccd31-cf3c-4122-a5cd-91ee307cea18.png)
![Screenshot from 2021-10-26 15-43-07](https://user-images.githubusercontent.com/9137294/138881827-af93bbe2-ea6a-46d0-8f90-c9a066e629d5.png)

**Comment by develohpanda** [comment]
Hiya! Sorry about this, thank you for the report. We have a release coming out planned for this week (2021.6.0) which should have some additional logging for this specific error. Once that is out, we would appreciate if you could please report back findings. 😄

**Comment by nektru** [comment]
Ok. I'll await the next release and update this issue.

**Comment by pouyasalimi** [comment]
After digging many times in Google and Github, I noticed it's a bug, and not related to let's encrypt certificate.

**Comment by develohpanda** [comment]
Hi @nektru, [2021.6](https://github.com/Kong/insomnia/releases/tag/core%402021.6.0) has been released. Could you please see if you are still experiencing this and what errors you see now?

**Comment by pouyasalimi** [comment]
@develohpanda I can confirm that checked the new version and got no errors while working with Git

**Comment by develohpanda** [comment]
Thanks! I will close this issue as resolved for now, please comment if it's still an issue and I will reopen.

**Comment by nektru** [comment]
In my case there is a new error:
```
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)
```

But it isn't expired:
```
$ echo | openssl s_client -servername gitlab.webvork.ru -connect gitlab.webvork.ru:443 | openssl x509 -noout -dates
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = gitlab.webvork.ru
verify return:1
DONE
notBefore=Oct 13 06:07:28 2021 GMT
notAfter=Jan 11 06:07:27 2022 GMT
```

**Comment by develohpanda** [comment]
Hmmm, okay, I'll re-open and update the title

**Comment by jackkav** [comment]
@nektru thanks for the update, you can workaround with issue by disabling `Validate Certificates` in the insomnia preferences. It appears to be related to openssl version. https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/


```
$ echo | openssl s_client -servername gitlab.webvork.ru -connect gitlab.webvork.ru:443 | openssl x509 -noout -dates
depth=1 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:0
depth=1 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:0
depth=3 O = Digital Signature Trust Co., CN = DST Root CA X3
verify error:num=10:certificate has expired
notAfter=Sep 30 14:01:15 2021 GMT
verify return:0
DONE
notBefore=Oct 13 06:07:28 2021 GMT
notAfter=Jan 11 06:07:27 2022 GMT
```
