### ISSUE TITLE
Manage environments modal does not support theme/dark mode

### ISSUE THREAD

**Issue by erwinw** [getinsomnia/insomnia#4156]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6 (20G165)

### Installation method

Download from insomnia.rest

### Last Known Working Insomnia version

n/a

### Expected Behavior

Manage environments modal display follows theme colours, or at the least has a dark background when the theme has a dark background, and light when the theme has a light background.

### Actual Behavior

The Manage Environments modal is a glaring white search light burning my retinas.

Well, maybe not that bad but pretty uncomfortable anyway.

### Reproduction Steps

1. Launc Insomnia, select a dark-background theme;
2. Put on sunglasses
3. Press Cmd-E to show the Manage Environments modal

### Additional Information

![Manage Environments modal over dark theme background](https://user-images.githubusercontent.com/54856303/139226376-3729130d-d65c-467b-9754-9cf0b45d3f97.png)

**Comment by dimitropoulos** [comment]
This is a design choice of the `Core Default` theme that no other dark theme has.  For example, here is that same window with `Simple Dark`:

![Screenshot_20211028_135524](https://user-images.githubusercontent.com/15232461/139309476-dbc3d602-8f4c-4f46-b669-cc9e9a36a2eb.png)

I verified that `Designer Dark`, `Material`, `Simple Dark`, `One Dark`, `Gruvbox Dark`, `Hyper`, `Railscasts`, `Solarized Dark`, and `Dark Colorblind` all dark backgrounds for this window, like above.

If using any of the above options doesn't work, please let me know and we can re-open and take a look! :)
