### ISSUE TITLE
text/plain responses with json are not displayed properly

### ISSUE THREAD

**Issue by marcomrdagsasc** [getinsomnia/insomnia#4163]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.6.0

### What operating system are you using?

macOS

### Operating System Version

11.6

### Installation method

dmg

### Last Known Working Insomnia version

2021.5.3

### Expected Behavior

Json with text/plain Content-Type responses to be displayed as beautified

### Actual Behavior

Response is without format

**Comment by iceblair** [comment]
Can confirm this is affecting Windows 10, version 10.0.19043

JSON data that previously was syntax-highlighted and beautified is now coming across as plain white text. This appears to be the case for every response preview that had been returned historically as well.

Upon opening the application for the first time in ~week, all previously beautified JSON is formatted like plaintext.

I did not experience this issue in version 2021.5.3

**Comment by develohpanda** [comment]
Hi all, this appears to be a regression as we have seen several reports about it, but unfortunately I haven't been able to reproduce it. Could you please supply any specific URLs that are causing this behavior, and also a screenshot? The `Content-Type` response header is used to display a rich view, so there may be something in that check we have missed.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/4312346/139604986-dc642f44-6a0c-4376-8065-22c42f67bfff.png">

**Comment by jmluang** [comment]
same here

<img width="569" alt="screenshot" src="https://user-images.githubusercontent.com/11557732/139633533-1fd5c67e-5010-4197-a4d1-e380758bbea8.png">

append a SP after the "content-type:" solve my issues

<img width="566" alt="screenshot2" src="https://user-images.githubusercontent.com/11557732/139634154-267dd8f8-1e16-42ab-95b2-7657d364e3fa.png">


Maybe my situation can provide some help

**Comment by dimitropoulos** [comment]
I was able to reproduce this using https://mockbin.org/bin/48236712-b20f-4f17-a11e-cf8dcfa6c2ae.

| 2021.5.3 | 2021.6.0 |
| - | - |
| ![Screenshot_20211101_161349](https://user-images.githubusercontent.com/15232461/139735536-af88084b-a1d3-4cd1-9efe-ace497bcab54.png) | ![Screenshot_20211101_161431](https://user-images.githubusercontent.com/15232461/139735642-84b83b36-32ac-478e-a3d2-fada638f8534.png) |
| ![Screenshot_20211101_161516](https://user-images.githubusercontent.com/15232461/139735736-5afc7c89-99bd-45c7-a03f-bdf705799e42.png) | ![Screenshot_20211101_161502](https://user-images.githubusercontent.com/15232461/139735701-0b38a9a9-35bc-4337-8fc4-2eea10acd662.png) |

@develohpanda I think the problem you had with your example is that the endpoint you hit (httpbin.org/json) has a Content-Type of `application/json`, while the response the users are talking about here is when it's `text/plain`.

The other problem is that httpbin.org/json, for whatever reason, actually sends a response that's pre-formatted.
![Screenshot_20211101_161633](https://user-images.githubusercontent.com/15232461/139735881-1cc86a6c-5c04-40b9-a8c2-b576eec803fb.png)

The mockbin above doesn't do either of those two things, which helps to reproduce.
