### ISSUE TITLE
Version 2021.6.0 breaks graphql preview

### ISSUE THREAD

**Issue by ellucianBret** [getinsomnia/insomnia#4168]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6

### Installation method

download

### Last Known Working Insomnia version

2021.5.x

### Expected Behavior

The "Preview" should show a pretty printed view of the JSON response when Accept-Encoding is set to gzip

### Actual Behavior

The "Preview" shows the same as the "Source" view

### Reproduction Steps

Execute a graphql query with a Header of Accept-Encoding gzip.

With the response view set to "Preview" it should show a pretty printed response, but it shows the "source" view

If you uncheck the Accept-Encoding gzip Header, the preview works correctly

Unchecking the Accept-Encoding gzip Header causes the Schema refresh to fail for large schemas.

With this issue I have to keep toggling the Header to get the behavior I need.

**Comment by dimitropoulos** [comment]
I can reproduce using the following express server that uses compression.

```js
const compression = require('compression');
const express = require('express');
const app = express();
app.use(compression());
app.get('/', (_, res) => {
  res.send(JSON.stringify({ test: true }));
});
app.listen(3000, () => {
  console.log('listening on port 3k');
});
```

| 2021.5.3 | 2021.6.0 |
| - | - |
| ![Screenshot_20211103_153903](https://user-images.githubusercontent.com/15232461/140180846-5d83894a-3c99-4a46-b019-a6df4103804a.png) | ![Screenshot_20211103_153741](https://user-images.githubusercontent.com/15232461/140180773-2d336b44-08a2-4f4d-b13d-ec1ca29dc00f.png) |

**Comment by dimitropoulos** [comment]
upon further investigation, this is solved by https://github.com/Kong/insomnia/pull/4171 to the best of my knowledge.

GraphQL and gzip is incidental to the situation, in the end, the cause is the same.  Still, I'd like to have more testing in this area in the future, but that PR _does_ introduce testing that would have prevented the bug in this issue from occurring, so at least it's a start.

**Comment by ellucianBret** [comment]
@dimitropoulos one difference is that the GraphQL server is going to send back an application/gzip response even though the compressed data is always JSON.

If I could specify that the schema is fetched with application/gzip as an Accept-Encoding but use Accept application/json in the request, then this would as well.
