### ISSUE TITLE
[Suggestion] Implicit encoding of the comma character inside the query part of an URL

### ISSUE THREAD

**Issue by arapoport** [getinsomnia/insomnia#417]
## Overview
- `Insomnia Version:` 5.7.4
- `Operating System:`  Windows 10
- `Web service:` nginx
- `Summary: ` URL gets altered without user knowing it

## How To Reproduce

1. Send a request to an URL like  `http://example.org/test?,,,,,`
2. Check what another side will receive 
3. It will be `/test?%2C%2C%2C%2C%2C`

In my understanding commas don't have to be encoded. At least they work unencoded with nginx 
and as long as I correctly understand URI spec they are totally allowed in the query part.

I also expect such a tool for web service debugging to send exactly what I am giving to it.

## Other Notes

Excerpt from RFC 3986 "URI Generic Syntax":

```

   pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"

   query         = *( pchar / "/" / "?" )

   fragment      = *( pchar / "/" / "?" )

   pct-encoded   = "%" HEXDIG HEXDIG

   unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
   reserved      = gen-delims / sub-delims
   gen-delims    = ":" / "/" / "?" / "#" / "[" / "]" / "@"
   sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "="

```

**Comment by gschier** [comment]
Hi @arapoport,

There is a preference in the request settings (accessible from request in sidebar) to disable automatic encoding. However, it's only applied to parameters specified in the URL bar (not in the Query tab).

> I also expect such a tool for web service debugging to send exactly what I am giving to it.

I generally agree with this too but, unfortunately, this is legacy behavior left over from when Insomnia was a Chrome application (Chrome used to automatically encode no matter what).

**Comment by arapoport** [comment]
@gschier I didn't notice that setting... Anyway, I was copy-pasting the URL because it was big and ugly.

I can give you some background. I had to deal with a web service which takes all arguments via URL and  uses sort of checksum of the URL being called. Any change would break that checksum. I was using Postman, but it has the same problem but with "!" character :-) soapUI is my current solution :-)

**Comment by gschier** [comment]
Oh, the classic SoapUI 😄 

Going to close this one for now but will keep it in the back of my mind as a potential pain point.
