### ISSUE TITLE
Insomnia can't resolve ipv6-only domains

### ISSUE THREAD

**Issue by matrozov** [getinsomnia/insomnia#4173]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10  Pro version 21H1

### Installation method

Download from insomnia.net

### Expected Behavior

Request works correclty

### Actual Behavior

Insomnia displays "Error: Couldn't resolve host name"

### Reproduction Steps

1. Create new request
2. Specify: GET ipv6.google.com
3. Click "Send"

### Additional Information

If you are specifying the actual ipv6 as a host and specifying domain to the Host request header, then it works fine.
Example:
GET https://[2a00:1450:4010:c0d::66]:443
Host: ipv6.google.com
That means the problem appears only when domain only has the AAAA record.

**Comment by filfreire** [comment]
Couldn't reproduce this issue on a slightly different Win10 version, Windows 10 Pro 20H2, using Insomnia 2021.6

**Update:** Also can't reproduce on Windows 10 Pro 21H1, using Insomnia 2021.6

Insomnia export:
[Insomnia_2021-11-03.zip](https://github.com/Kong/insomnia/files/7467315/Insomnia_2021-11-03.zip)

**Comment by papajojo** [comment]
Insomnia 2021.6.0, Windows 10 Home, reproduces the issue, I've got "Error: Couldn't resolve host name" after requesting ipv6.google.com

**Comment by matrozov** [comment]
> Couldn't reproduce this issue on a slightly different Win10 version, Windows 10 Pro 20H2, using Insomnia 2021.6
> 
> **Update:** Also can't reproduce on Windows 10 Pro 21H1, using Insomnia 2021.6
> 
> Insomnia export: [Insomnia_2021-11-03.zip](https://github.com/Kong/insomnia/files/7467315/Insomnia_2021-11-03.zip)

I've tried your export file and reproduced it on Ubuntu 20.04.3 LTS (even from another location).

**Comment by matrozov** [comment]
> Couldn't reproduce this issue on a slightly different Win10 version, Windows 10 Pro 20H2, using Insomnia 2021.6
> 
> **Update:** Also can't reproduce on Windows 10 Pro 21H1, using Insomnia 2021.6
> 
> Insomnia export: [Insomnia_2021-11-03.zip](https://github.com/Kong/insomnia/files/7467315/Insomnia_2021-11-03.zip)

Sorry, it seems that there wasn't any problems: I found that my Windows 10 wasn't configured for IPv6 support. And at the same time my previous example (requesting ipv6 address and passing host header) worked only because of my work VPN I was connected to (which supports ipv6).

**Comment by filfreire** [comment]
@matrozov no worries 👍  
Is this also the case for @papajojo ?

**Comment by papajojo** [comment]
Yep, all fine now, thanks!
