### ISSUE TITLE
GraphQL Query/Mutation syntax highlight partially has less opacity 

### ISSUE THREAD

**Issue by seanghay** [getinsomnia/insomnia#4181]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.0.1

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

2021.4.0

### Expected Behavior

It should have full opacity like this

![image](https://user-images.githubusercontent.com/15277233/140319357-f6f10539-94f5-4526-937c-ac9ce8093d42.png)

### Actual Behavior

Some parts of the GraphQL code has less alpha that the rest

![image](https://user-images.githubusercontent.com/15277233/140319424-07c05904-34f4-4073-9cb8-e44781bea925.png)

### Reproduction Steps

1. Create a new Request
2. Switch to GraphQL
3. Put this in the request body

```gql
{
  wishlists:paginateWishlists {
    totalCount
    hasNextPage
      nodes {
      _id
      title
      items {
        __typename
        ...WishlistPlace
        ...WishlistArticle
        ...WishlistVideo
        ...WishlistProduct
      }
    }
  }
}


fragment WishlistPlace on PlacePayload {
  _id
  name
}

fragment WishlistArticle on ArticlePayload {
  _id
 
  thumbnailUrl
}


fragment WishlistVideo on VideoPayload {
  _id
}

fragment WishlistProduct on ProductPayload {
  _id
  
}
```

**Comment by dimitropoulos** [comment]
Hi, I was able to reproduce (this is independent of theme):

with the URL `https://rickandmortyapi.com/graphql`

and the body:

```graphql
query {
  characters(page: 2, filter: { name: "rick" }) {
    info {
      count
    }
    ...characterFragment
  }
  location(id: 1) {
    id
  }
  episodesByIds(ids: [1, 2]) {
    id
  }
}

fragment characterFragment on Characters {
  results {
    name
  }
}
```

it looks like:

![Screenshot_20211104_114415](https://user-images.githubusercontent.com/15232461/140366475-8a06bae2-8f2b-4b16-a22d-0c8c5c1d8b83.png)

**Comment by christianheld** [comment]
Looks like the issue affects only unnamed queries:

This query is always rendered with less opacity:
```graphql
query { 
  launchpads { name }
}
```

When named the selected query is rendered correctly:
```graphql
query pads { 
  launchpads { name }
}
```

![unnamed query](https://user-images.githubusercontent.com/11472622/140486484-ae066635-91a8-4243-bab8-1b4ed123ef26.png)
![named query](https://user-images.githubusercontent.com/11472622/140486663-0d760b4b-16d6-484c-99a0-60641d27dd0e.png)

**Comment by seanghay** [comment]
@dimitropoulos Do you know what causes that? I've tried to find where to fix it but couldn't.

**Comment by dimitropoulos** [comment]
yes, I bisected yesterday to find the commit and I'm working on it today.
