### ISSUE TITLE
Pull and push Snapshot icon

### ISSUE THREAD

**Issue by man0790** [getinsomnia/insomnia#4182]
Just a one feedback about pull snapshots and push snapshots icon. They both have same icon. Shouldn't pull snapshot have icon facing downward. its a minor thing but I thought its good have different icons for pull (downward facing) and push snapshots (upward facing).

**Comment by wdawson** [comment]
@man0790 , I'm seeing different icons on 2021.6.0. Are you on an older version? Or looking at a different place in the app?

<img width="112" alt="push-pull" src="https://user-images.githubusercontent.com/132961/140528564-03378dfa-a827-46a0-8950-a24ee2001c31.png">

**Comment by man0790** [comment]
Hi Wils,

I got 2021.6.0. version of Insomnia. I am looking at right side of where we get branch name. Snapshot is attached for your reference.

Thanks,
Manpreet

***@***.***

**Comment by wdawson** [comment]
@man0790 , thanks! I found it under the Insomnia Sync for Request Collections. Looks like a small oversight.

<img width="210" alt="push-pull" src="https://user-images.githubusercontent.com/132961/141161603-2c515b13-91ce-4502-931b-b4273c421e23.png">

**Comment by filfreire** [comment]
@wdawson @man0790 this should be fixed on https://github.com/Kong/insomnia/pull/4211
