### ISSUE TITLE
inso-linux-2.4.0.tar.xz is really a bzip2 compressed archive

### ISSUE THREAD

**Issue by ckujau** [getinsomnia/insomnia#4185]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

Inso CLI 2.4.0

### What operating system are you using?

Other (specify below)

### Operating System Version

N/A

### Installation method

download from Github

### Last Known Working Insomnia version

Inso CLI 2.3.3-alpha.1

### Expected Behavior

According to the release assets, the [Inso CLI 2.4.0 release](https://github.com/Kong/insomnia/releases/tag/lib%402.4.0) holds a file called `inso-linux-2.4.0.tar.xz` which is supposed to be a XZ compressed file.

### Actual Behavior

Upon downloading, the file `inso-linux-2.4.0.tar.xz` turns out to be a Bzip2 compressed file.

### Reproduction Steps

```
$ curl -sL https://github.com/Kong/insomnia/releases/download/lib%402.4.0/inso-linux-2.4.0.tar.xz | file -
/dev/stdin: bzip2 compressed data, block size = 900k
```

### Additional Information

Possible solutions: rename to `inso-linux-2.4.0.tar.bz2` or really compress `inso-linux-2.4.0.tar` via `bzip2` :-)

FWIW, [Inso CLI 2.3.3-alpha.1](https://github.com/Kong/insomnia/releases/tag/lib%402.3.3-alpha.1) really holds an XZ compressed file, the next version [Inso CLI 2.3.3-alpha.2](https://github.com/Kong/insomnia/releases/tag/lib%402.3.3-alpha.2) sneaks in a bzip2 file.

**Comment by develohpanda** [comment]
> FWIW, Inso CLI 2.3.3-alpha.1 really holds an XZ compressed file, the next version Inso CLI 2.3.3-alpha.2 sneaks in a bzip2 file.

Thank you for reporting this and for checking against the previous alphas! It really helped to narrow down what had changed. It appears that during a refactor one of the tar flags was switched from uppercase to lowercase (`tar -J` to `tar -j`). We'll have it fixed up with the next release!
