### ISSUE TITLE
Regex tags don't work 

### ISSUE THREAD

**Issue by 4ekki** [getinsomnia/insomnia#4187]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.6.0

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.6

### Installation method

download from insomnia.rest

### Expected Behavior

Able to extract substring of some variable by regex, as I was able before

### Actual Behavior

Unable to extract substring of some variable. 
Existing tags cannot be opened, showing error 'unknown block tag: regex' in Live Preview: 
![image](https://user-images.githubusercontent.com/38757986/140745893-93b1bbf1-4f20-412f-82b4-f3ba1dee2897.png)

**Comment by dimitropoulos** [comment]
Are you using https://www.npmjs.com/package/insomnia-plugin-regex? Could you provide any more context on reproduction steps?

I was able to get to something _similar_ but not identical by installing `insomnia-plugin-regex`, making a regex, and then uninstalling (without changing my usage of the plugin):

![Screenshot_20211108_155210](https://user-images.githubusercontent.com/15232461/140816304-e03f4416-7e39-40d7-a366-ada13364f648.png)

That said, it's not identical to what you're showing so I want to verify.

**Comment by develohpanda** [comment]
Here's an example environment to try and reproduce this.

```json
{
  "foo": "abcd",
  "bar": "{% regex _.foo, '.+', 0 %}",
  "baz": "{{ _.bar }}"
}
```

This will render as the following if `insomnia-plugin-regex` is installed and enabled 

![image](https://user-images.githubusercontent.com/4312346/140844038-0e41f774-ef1c-4ceb-b9e5-87f773d4c9a5.png)

And this is what will render if the plugin is installed and disabled

![image](https://user-images.githubusercontent.com/4312346/140844210-05d5a770-d9ac-4511-8e5c-5343e4707d50.png)

Disable the plugin and then click on the `_.bar` template tag, we see the same error as the user sees:

![image](https://user-images.githubusercontent.com/4312346/140844309-a2eceda3-a93d-4344-9713-2684537119dd.png)

@4ekki could you please validate that the plugin is installed and enabled under Preferences > Plugins?

**Comment by 4ekki** [comment]
Well, my bad totally - I've changed workstation some time ago, installed clean Insomnia and didn't install the plugin. I don't use this request with regex tag often, so noticed this problem only now, right after receiving fresh update. So I blamed it. 
After installing the plugin, issue is resolved. 

@dimitropoulos , @develohpanda , thank you for your help!
