### ISSUE TITLE
Sorting request sidebar doesn't work on 2021.6

### ISSUE THREAD

**Issue by johnliappnexus** [getinsomnia/insomnia#4191]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.5.2

### Installation method

Insomnia.rest

### Last Known Working Insomnia version

NA

### Expected Behavior

Expecting to be able to sort requests and collections/folders by name.

### Actual Behavior

Sort buttons don't appear to do anything.

https://www.screencast.com/t/vh5ww6rA1a

### Reproduction Steps

Deleted old version of Insomnia.app
Installed Insomnia rest client from web (https://insomnia.rest/)

### Additional Information

Version: Insomnia 2021.6.0
Release date: 28/10/2021
OS: Darwin x64 20.6.0
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0

**Comment by develohpanda** [comment]
Thank you for reporting this! We'll have it fixed up in an upcoming release 🙌🏽 (internal reference INS-1107)
