### ISSUE TITLE
request setBody is failing to send object

### ISSUE THREAD

**Issue by StefanVrecic** [getinsomnia/insomnia#4193]
### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 10.0.19042 

### Installation method

npm run bootstrap, npm run app-start as per instructions

### Expected Behavior & Actual Behaviour

setBody should send an object with '{xxx: "hello"}' , however express server only receives req.body of empty object {} when body modification is attempted. 

It works fine with no plugin and it prints the actual request body put into insomnia. Other request context modification such as setHeader works fine, but setBody does not.

**Note, plugin loads fine and I have tested it with print statements, it's just the setBody**

### Reproduction Steps

I have a plugin with main.js below. The try block executes succesfully.

```
module.exports.requestHooks = [
  async ctx => {
    try{
      ctx.request.setHeader('xxx', 'hello')
      ctx.request.setBody({'xxx': 'hello'}); // also tried xxx without quotations
    } catch {
      console.log("request modification failed");
    }
  }
]
```
I put JSON and body in Insomnia. POST http://localhost:3002/
```
{
	"original": "hello"
}
```

### Additional Information

Node: 12.18.3
Test Suites: 105 passed, 105 total
Tests:       4 skipped, 1045 passed, 1049 total
Snapshots:   3 passed, 3 total
Time:        249.214 s
Ran all test suites.

### Timeline

With no setBody:
```
> POST / HTTP/1.1
> Host: localhost:3002
> User-Agent: insomnia/2021.6.0
> Content-Type: application/json
> xxx: hello
> Accept: */*
> Content-Length: 24

| {
| 	"original": "hello"
| }
```

with Setbody:

```
> POST / HTTP/1.1
> Host: localhost:3002
> User-Agent: insomnia/2021.6.0
> Content-Type: application/json
> xxx: hello
> Accept: */*
> Content-Length: 0
```

**Comment by develohpanda** [comment]
Hi! Thanks for raising this, I realized that the API reference in our documentation didn't outline the object type expected by `setBody`. I've expanded the docs in the PR above with some examples of how to use the `setBody` method.

`setBody()` is expecting a `RequestBody`, in which the `text` property contains a stringified version of your request body.

https://github.com/Kong/insomnia/blob/9353a6fb00782e2e5b8adb417f8c58f6d8e53224/packages/insomnia-app/app/models/request.ts#L69-L74

I'll close this issue in anticipation of https://github.com/Kong/insomnia-docs/pull/60 being merged!
