### ISSUE TITLE
Pressing the tab key on a Request non-multi-line text field inserts four spaces

### ISSUE THREAD

**Issue by jbylsma** [getinsomnia/insomnia#4206]
(I kept getting 400 Bad Request responses when trying to create this issue with the Bug Report template. I've manually created this ticket from a blank issue and tried to mimic the template as close as possible, knowing the labels are missing)

### Is there an existing issue for this?
* [x]  I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Expected Behavior
With a Request non-multi-line text field focused:
- Pressing Tab will focus the next text field
- Pressing Shift-Tab will focus the previous text field

### Actual Behavior
With a Request non-multi-line text field focused with no user input, pressing Tab will insert four spaces.

With a Request non-multi-line text field that has user input beginning with spaces, pressing Shift-Tab will delete up to four spaces.

### Reproduction Steps
1. Create new Request
2. Change Body to "Multipart Form"
3. Select the "New name" text field
4. Press Tab

### Additional Information
It appears that all non-multi-line text fields are impacted; the columnar fields on Body, Query, and Header, as well as the non-columnar fields in Auth all exhibit the same behavior.

The behavior does seem desirable on multi-line field inputs, such as Body's GraphQL and JSON or Query's Text (Multi-Line).

The bug is present in the current `develop` HEAD (4c906ccae5a4a003bc1365358de9ab87f8c50964). I Git bisected the issue back to 381cf74a19918ffa7e54908e458b0d2939ca023b, which is the merge commit for #3993.

Thanks!

### Insomnia Version
2021.6.0

### What operating system are you using?
macOS

### Operating System Version
macOS Monterey 12.0.1

### Installation method
homebrew

### Last Known Working Insomnia version
2021.5.3

**Comment by dimitropoulos** [comment]
Thanks for this, I've been trying to create this exact issue for a few minutes now but GitHub kept `400`ing as well.  I'm going to look into that asap.

**Comment by jbylsma** [comment]
Sure thing! I sent a message in the Insomnia #general Slack channel with what I found on the GitHub 400s, too.

**Comment by dimitropoulos** [comment]
It's fixed: https://github.com/Kong/insomnia/pull/4207.  Very infuriating.  I did test this template before the PR (that broke it) merged. 
 Here https://github.com/dimitropoulos/insomnia-test/issues/3 for example is a successfully submitted template with a checkbox without a label. 
 Somehow... in between the time I did that and now it broke.

**Comment by jbylsma** [comment]
Nice sleuthing. Have been conceptually there, have been similarly infuriated.
Would you like me to re-open this issue using the updated template so it can get the proper tags and anything I didn't mimic right?

**Comment by dimitropoulos** [comment]
no, that's ok.  I have already verified this issue.  Thank you for bisecting!!
