### ISSUE TITLE
[Behavior] Subdomain cookies not sent unless the cookie starts with dot

### ISSUE THREAD

**Issue by tebruno99** [getinsomnia/insomnia#422]
## Overview
- `Insomnia Version:` 5.7.2
- `Operating System:`  MacOS 10.12.6
- `Summary: ` When my service sets a cookie without a "." as the first character, the cookie is not sent to subdomains. We removed the . as the first character in our cookies because we found documentation that Chrome and Firefox have stopped using the . to signify that the cookie is for use in subdomains and now you just create cookies with the top level domain without a .

## How To Reproduce
Made a request, Cookie is not provided automatically to subdomains unless our API server puts a . as the first character

## Other Notes

There are various conflicting resources about the ., but we tested the current behavior of Chrome and Firefox and found that Cookies are sent with and without the .

**Comment by gschier** [comment]
Hi @tebruno99.

I just tried this out quickly and it seemed to work for me as you described that it should. Here's what I did:

1. Make request to `https://insomnia.rest`
2. Observe the cookie `__cfduid` is stored for `insomnia.rest` in the cookie editor
3. Make request to `https://api.insomnia.rest`
4. Observe in the Timeline view that the `__cfduid` cookie stored under `insomnia.rest` is indeed sent

Can you please follow my test case and see if you get the same result? Also, if you could provide a public endpoint and reproduction steps that I could use to reproduce your issue, that would be awesome 😄

**Comment by tebruno99** [comment]
@gschier I'm very sorry about the noise, I did your test and it did indeed work correctly.  I've been holding onto this one for a long time trying to make sure it was legit and it just started working for me. Definitely user error, though I don't know how.

Thanks for your awesome work on this App and quick response, I love it

**Comment by gschier** [comment]
Hmm, that's odd. There may have very well been a problem on an older version of the app.

Thanks, I'm glad you're enjoying it! 😊
