### ISSUE TITLE
Version 2021.6.0 doesn't beautify response json anymore if Content-Type is text/html

### ISSUE THREAD

**Issue by BlueOceanI** [getinsomnia/insomnia#4233]
### Expected Behavior

In version 2021.5.3 and older, the json response was formatted regardless of Content-Type header.

![image](https://user-images.githubusercontent.com/56826213/142638695-e3bc7fa3-703f-4625-9aaa-0e843241ee46.png)

### Actual Behavior

It would seem 2021.6.0 breaks this behavior. Since there are some apis out there which return the header wrong if the body is indeed application/json, I'd believe this would be correct behavior going further too.

![image](https://user-images.githubusercontent.com/56826213/142639744-cdfc7465-376d-4082-b891-5f075e6818e7.png)

### Reproduction Steps

Any request with Content-Type not application-json or application/json will probably do, I noticed with text/html.
![image](https://user-images.githubusercontent.com/56826213/142639853-5f1bab3d-de12-4bee-8ab6-5c1567ebb7e8.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.6.0

### What operating system are you using?

Windows

### Operating System Version

21H1

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

2021.5.3

**Comment by wdawson** [comment]
Thanks for filing @BlueOceanI . This should be already fixed in #4171 but it hasn't been released yet. Keep an eye out for a patch soon!
