### ISSUE TITLE
[Bug] Generate Code Snippet doesn't work behind proxy server

### ISSUE THREAD

**Issue by klauern** [getinsomnia/insomnia#424]
## Overview
- `Insomnia Version:` `5.7.4`
- `Operating System:`  Manjaro Linux
- `Summary: ` Attempting to generate code snippets for a service request and it just sits there saying "Generating Code":

![image](https://user-images.githubusercontent.com/4735/29225553-60ac917e-7e94-11e7-9eb5-9e841eaca7a5.png)

Even with the Preferences setting an HTTP proxy, and checking "Enable HTTP Proxy", it is not used as far as I can tell.

**Comment by gschier** [comment]
Hi @klauern. Thanks for reporting this. 

The proxy setting shouldn't have anything to do with this. Code snippets are generated locally within the app. I feel like there is probably a bug somewhere that prevented the generation from happening. 

Can you do me a favor and start the application with the environment variable `INSOMNIA_FORCE_DEBUG=1`. Then you should be able to open the Chrome devtools (Developer >  Toggle DevTools > Console) and see any errors that may have been thrown.

**Comment by klauern** [comment]
That's easy enough to do.  Here's what happens:

![image](https://user-images.githubusercontent.com/4735/29230297-f70b42d8-7ea7-11e7-938e-e070a41be647.png)

And the associated log that I saved off:
```log
database.js:92 [db] Initialized DB at /home/klauer/.config/Insomnia/insomnia.$TYPE.db
google.js:51 [ga] Set platform linux
google.js:60 [ga] Set version 5.7.4
google.js:42 [ga] Initialized for 72b3f9bd-df7a-46ec-800b-dd829f5e4987
google.js:74 [ga] Send event [General, Launched, 5.7.4, [object Object]]
google.js:74 [ga] Send event [Plugins, Refresh]
logger.js:33 [sync] Initialized
google.js:74 [ga] Send event [Request, Generate Code, Request Action]
index.js:35 Unhandled Promise PromiseRejectionEventbubbles: falsecancelBubble: falsecancelable: truecomposed: falsecurrentTarget: globaldefaultPrevented: falseeventPhase: 0isTrusted: truepath: Array[1]promise: Promisereason: HARErrorreturnValue: truesrcElement: globaltarget: globaltimeStamp: 6728.08type: "unhandledrejection"__proto__: PromiseRejectionEvent
window.addEventListener.e @ index.js:35
generate-code-modal.js:99 Uncaught (in promise) HARErrorerrors: Array[4]name: "HARError"__proto__: Object
google.js:74 [ga] Send event [Error, Uncaught Promise]
```

**Comment by klauern** [comment]
Not sure if this simplifies the issue or not:

![image](https://user-images.githubusercontent.com/4735/29230324-1b47b230-7ea8-11e7-9251-012d454a8974.png)

**Comment by gschier** [comment]
That helps a lot, thanks! Can you expand the `value: Object` property of one of those error objects? _Note: there may be some sensitive data in there_.

**Comment by klauern** [comment]
![image](https://user-images.githubusercontent.com/4735/29231535-2ffa5700-7ead-11e7-8347-8f5eb35f9a6e.png)

**Comment by klauern** [comment]
domain is a url, and path is a base path to the API.  They don't seem out of the ordinary, so you could say they are `example.com` and `/APIUrl/`.

**Comment by gschier** [comment]
So it looks like the error is saying that the `value` property is missing. If you open the cookie dialog, can you see a value in the cookie string?

![image](https://user-images.githubusercontent.com/587576/29231740-2e02d8f6-7e9d-11e7-8e46-6f58e1ab7f14.png)

**Comment by gschier** [comment]
Apparently cookie strings. I did some reading and, apparently, a cookie with an empty value is valid. I just tried deleting "value" in Insomnia and was able to get the same error you posted.

**Comment by klauern** [comment]
Well, that's good to know.  I didn't know that was related either.  I also don't know where the cookies were even generated from, as I was using `Response => Body` in a lot of places to tease out and re-use a `/Login` call so I could use the associated token, and it wouldn't be surprising if I had a cookie that wasn't valid between calls.

**Comment by gschier** [comment]
Well the good news is that it should work if you delete/fix those cookies. The fix I added should prevent that case from things breaking in the next release

**Comment by tharsik** [comment]
I was using insomia and working fine absolutely and today i got white screen when launched  it. I see the below error in console
C:\Users\chant_000\AppData\Local\insomnia\app-5.11.0\resources\app.asar\node_modules\nedb\lib\datastore.js:77 Uncaught Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
    at Persistence.treatRawData (C:\Users\chant_000\AppData\Local\insomnia\app-5.11.0\resources\app.asar\node_modules\nedb\lib\persistence.js:242:11)
    at C:\Users\chant_000\AppData\Local\insomnia\app-5.11.0\resources\app.asar\node_modules\nedb\lib\persistence.js:281:38
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)

tried reinstalling the app but no luck.

**Comment by gschier** [comment]
Hi @tharsik. That's strange, I've never seen that before. It looks like one of the database files got corrupted somehow. Here's how you can debug it.

## Option 1 – Delete all data

This method will delete all application data. If you don't care about losing a few things, this is the easiest option.

To delete all application data, remove this folder from your hard drive: `C:\Users\chant_000\AppData\Roaming\Insomnia`.

## Option 2 – Recover as much data as possible

This method is more involved, but you may be able to save some of your data depending on which database file was corrupted.

- Open `C:\Users\chant_000\AppData\Roaming\Insomnia`
- Go through each file that looks like `insomnia.*` and rename it to something else
    - I recommend trying `insomnia.Response.db` first, as it is the least important
- After renaming a file, restart Insomnia and see if it works
- If it doesn't work, change the name back to what it was and try another one

Once you find the corrupted file, you can delete it. Depending on which file was corrupted, you may still be still have most of your data. However, if a lot of your data is still missing, I recommend doing step 1.

**Comment by tharsik** [comment]
@gschier thanks for the recommendation. Found the one corrupted. It is fine now.

**Comment by gschier** [comment]
Hi @tharsik. Which one was corrupted?

**Comment by mojobiri** [comment]
Had the same issue today on Ubuntu.
`insomnia.WorkspaceMeta.db` file was causing an issue.
`mv ~/.config/Insomnia/insomnia.WorkspaceMeta.db ~/.config/Insomnia/insomnia.WorkspaceMeta.db.old` solved the issue.

**Comment by tharsik** [comment]
insomnia.Response.db this was the file got corrupted. @gschier

**Comment by jon64digital** [comment]
Had the same problem today and deleted 1 file at a time from AppData/Roaming/Insomnia.

3 files were corrupted...

insomnia.environment.db
insomnia..Request.db
insomnia..Workspace.db

**Comment by imechemi** [comment]
I am facing same issue on **v2020.3.3** on OS X Mojave. Can anyone point me where these db locations are in OS X?


UPDATE: Never mind, deleted few recent cookie entries and it started generating again. Thank @gschier for the cue 🙂
