### ISSUE TITLE
Insomnia very slow and hangs on a >6000 line file

### ISSUE THREAD

**Issue by chaosKP** [getinsomnia/insomnia#4241]
### Expected Behavior

If the DESIGN is used the toggle of a menu entry inside the preview is nearly instantious.
If a change is made inside the editor the lag is neglectable (1-2 seconds).

### Actual Behavior

If a path entry inside the preview is toggled it takes up to 5 seconds to respond.
If a change is made inside the editor it takes more than 25 seconds until the tool is updated and responsive again.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

There is no difference if Preview is On or Off.

We also tried a local version of swagger editor and the expected behavior is given

### Insomnia Version

2021.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Build 19043

### Installation method

download from insomnia.rest

**Comment by tuscen** [comment]
Can confirm, the same behaviour on macOS 12.1 on Macbook with Intel Core i7. I have an openapi schema with 17k lines and Insomnia handles it very badly. Changing from design to debug tab can take up to several seconds (4-6 seconds).

```
Version: Insomnia 2021.7.2
Release date: 12/10/2021
OS: Darwin x64 21.2.0
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0
```

**Comment by poiuytrez** [comment]
I struggle to edit a 1.2k lines file in the design tab. Every time I type a few characters, the editor hangs for about 5-10 seconds which makes the edition very painful.

This is what I often get:
![Screenshot 2022-04-08 at 10 20 44](https://user-images.githubusercontent.com/1167433/162395676-7ac75511-c1e6-44eb-9960-b4b7b0443af2.png)

Any tip to disable real-time syntax checking is welcome.

```
Version: Insomnia 2022.2.1
Release date: 3/21/2022
OS: Darwin x64 20.6.0
Electron: 17.1.0
Node: 16.13.0
V8: 9.8.177.11-electron.0
Architecture: x64
```
I am on macOS 11.6.5 on Macbook Air 2018.

**Comment by ArnaudPel** [comment]
Same issue on macOS 12.3.1 on MacBook Air M1, 2020.

```
Version: Insomnia 2022.2.1
Release date: 3/21/2022
OS: Darwin arm64 21.4.0
Electron: 17.1.0
Node: 16.13.0
V8: 9.8.177.11-electron.0
Architecture: arm64
```

**Comment by ChristoNel** [comment]
I see the same issue on my Windows machine after downloading the latest version.
My file though is allot smaller with juts 2500 lines.

After opening up the .yaml file Insomnia simply becomes unresponsive and I need to close it.

![image](https://user-images.githubusercontent.com/22051310/170451971-7cab4e3f-30d3-4398-86af-1f043ace11c6.png)


![image](https://user-images.githubusercontent.com/22051310/170451763-5d11b595-2447-4c47-b239-bbe8d38618e9.png)

**Comment by GeoffreyCoulaud** [comment]
Happens to me too, this issue is still relevant.
I tried it with the Jellyfin OpenAPI:

https://api.jellyfin.org/openapi/jellyfin-openapi-stable.json

**Comment by subnetmarco** [comment]
We are actively working to solve this issue, stay tuned.

**Comment by subnetmarco** [comment]
We are actively working to solve this issue, stay tuned.

**Comment by CurryYangxx** [comment]
We optimized for this in version 9.2, now file opening and editing are now faster

**Comment by cdbuescher** [comment]
I have v 9.2 and this issue is still happening.  
It takes more than 25 seconds until the tool is updated and responsive again.

**Comment by CurryYangxx** [comment]
> I have v 9.2 and this issue is still happening. It takes more than 25 seconds until the tool is updated and responsive again.

Hi @cdbuescher .Could you please describe in detail what‘s you operation and how you reproduce the issue, I try to edit a more than 10000 lines file and no non-response occurred

**Comment by chrisciokler** [comment]
Very slow, request gets hang, response takes a long time to show in the UI. I was a big fan, but is a much worse experience now.

**Comment by CurryYangxx** [comment]
@chrisciokler Could you please elaborate on the usage scenario when you encountered the lag, and what is your current insomnia version?
This issue is just for design document editing, if your use case is different, please open another new issue if possible. Thanks!
