### ISSUE TITLE
[Bug] Failed to contact HTTPS GraphQL to fetch schema

### ISSUE THREAD

**Issue by tphan18** [getinsomnia/insomnia#425]
## Overview
- `Insomnia Version:` 5.7.4
- `Operating System:`  Windows 7
- `Summary: ` Failed to contact https://graphql_endppoint to fetch schema

## How To Reproduce
_Please list all pertinent information and steps needed to reproduce the issue. For example:_
1. Create new POST request to HTTPS GraphQL endpoints
2. Perform a request
3. You can see the results but the autocomplete feature is not working

## Other Notes
The introspection queries run normally in `graphiql`.

**Comment by gschier** [comment]
Hi @tphan18,

Can you give this another try on 5.7.9? I made some improvements to GraphQL schema fetching in that release. Let me know if you're still having problems.

**Comment by tphan18** [comment]
Thanks @gschier, 5.7.9 fixed the issue if the GraphQL endpoints are not protected by any authentication layer. I am not sure whether or not we should have another enhancement or feature issue. The desired behavior for schema fetching is that use the current authen config on the request to make introspection query.  I will close this issue because it might be to specific for my use cases. Thanks again.

**Comment by gschier** [comment]
@tphan18, authentication should be sent with the introspection query in the latest update. What type of authentication are you using?

**Comment by tphan18** [comment]
Just simple bearer token. I see `Fetching schema...` forever.

**Comment by tphan18** [comment]
I am using environment which the token is pulled from it.

**Comment by gschier** [comment]
Where are you using the token. In a header?

**Comment by tphan18** [comment]
Under the `auth` tab, I chose the bearer. I got the results correctly. Let me try the header.

**Comment by tphan18** [comment]
It doesn't work in 3 cases:
 - Use `Auth` -> `Bearer`
 - Manually `Authorization: Bearer {{token}}`
 - Use both

**Comment by Ruben-E** [comment]
Mine also hangs on `Fetching schema...` forever. Endpoint is not protected by any authentication. Happened when I used an environment variable for the host.

**Comment by driesvints** [comment]
Heya. Using Insomnia 5.9.6 and I'm still experiencing this issue. Sending an `Authorization` header with a JWT bearer token. Any idea what might be causing this?

**Comment by gschier** [comment]
Hi @driesvints. Can you verify that the `Authorization` header is indeed not making it to your server?

**Comment by driesvints** [comment]
@gschier the authorization header gets sent along fine. What does insomnia expect back? It seems to just perform the call to the graphql endpoint that defined in the insomnia client. How does it know about the schema?

**Comment by driesvints** [comment]
Also: how do you send along the `operationName` when you have multiple queries defined?

**Comment by gschier** [comment]
@driesvints there are to requests being sent in the case of GraphQL.

1. Schema Introspection Query
  - This request fetches the GraphQL schema using a GraphQL introspection query
  - Triggered when a new request is selected, when the URL is modified, or when you manually click the refresh button above the Query Variables pane
  - The result of this query is what powers autocomplete and linting of your queries
2. User-defined GraphQL query
  - This request sends your actual GraphQL query to the server just like a regular Insomnia request

This issue is related to request 1 (the introspection query) not working. Are you seeing a specific error like this in Insomnia?

<img width="437" alt="image" src="https://user-images.githubusercontent.com/587576/31666645-4aaed038-b34d-11e7-81c2-b7c043ee47b2.png">

If so, can you let me know what it is? If you are having problems with request 2, that should be submitted as a separate issue.

> Also: how do you send along the operationName when you have multiple queries defined?

`operationName` is not currently supported by Insomnia.

**Comment by driesvints** [comment]
@gschier hey Gregory. Thank you so much for the detailed explanation! 

Currently, when I check the access log for nginx, these are all the calls that are being made:

```
192.168.22.1 - - [17/Oct/2017:13:02:54 +0000] "GET /graphql?operationName=GetEvents HTTP/1.1" 200 5326 "-" "insomnia/5.9.6"
192.168.22.1 - - [17/Oct/2017:13:02:56 +0000] "GET /graphql?operationName=GetEvents HTTP/1.1" 200 5327 "-" "insomnia/5.9.6"
192.168.22.1 - - [17/Oct/2017:13:03:04 +0000] "GET /graphql?operationName=GetEvents HTTP/1.1" 200 97 "-" "insomnia/5.9.6"
192.168.22.1 - - [17/Oct/2017:13:03:16 +0000] "GET /graphql?operationName=GetEvents HTTP/1.1" 200 97 "-" "insomnia/5.9.6"
```

I get this message:

<img width="537" alt="screen shot 2017-10-17 at 3 23 37 pm" src="https://user-images.githubusercontent.com/594614/31667419-afb70f84-b34f-11e7-96a5-36b72b529d8d.png">

**Comment by gschier** [comment]
Oh, I think I know what the issue is. Since you blanked out the start of the URL, I assume it does not have a protocol specified? Can you try adding `http://` or `https://` in front if there isn't one?

**Comment by driesvints** [comment]
@gschier it does have the protocol in front of it. Sorry for obfuscating that part.

**Comment by gschier** [comment]
@driesvints what version of Insomnia are you using? That error message looks different from what is in the most recent codebase.

**Comment by gschier** [comment]
Oh, nvm. Looking in the wrong place. It looks like there is some extra error info printed to the console when that happens. Can you check it by going to View > Toggle DevTools > Console?

**Comment by driesvints** [comment]
@gschier we found out what happened. Apparently something went wrong in the library we used to parse the query. We managed to fix the problem. Sorry for the hassle 😞

**Comment by gschier** [comment]
Well, I'm glad you figured it out! No worries 😄

**Comment by LorenVeri** [comment]
![image](https://user-images.githubusercontent.com/71799122/159204793-1982fec6-c9f2-4b42-b415-8b15ed464304.png)
Help me!
 I get this message
