### ISSUE TITLE
Filename is incorrectly determined from Content-Disposition header

### ISSUE THREAD

**Issue by rupert-madden-abbott** [getinsomnia/insomnia#4252]
### Expected Behavior

When saving a file, I expect the filename to be named according to the Content-Disposition header.

GIven a Content-Disposition header of 'attachment; filename="foo.json"', I expect the saved file to be named "foo.json"

### Actual Behavior

The file is named according to the entire contents of "Content-Disposition" and not just the filename.

In the above example, the file is named 'attachment; filename="foo.json"'

### Reproduction Steps

1. Create a get request for an endpoint that will return a Content-Disposition header
2. Right click on "Request" and select "Start auto-download"
3. Choose a directory location
4. Click download

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The bug occurs on [this line](https://github.com/Kong/insomnia/blob/177d6adf38852aae2aef72717fa28dc4d9fef35e/packages/insomnia-app/app/ui/containers/app.tsx#L770) where the entire contents of the header is used, rather than being parsed to see if it contains a filename.

Please note the following recommendations [from MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) on handling of the filename directive of this header:

> Is followed by a string containing the original name of the file transmitted. The filename is always optional and must not be used blindly by the application: path information should be stripped, and conversion to the server file system rules should be done. This parameter provides mostly indicative information. When used in combination with Content-Disposition: attachment, it is used as the default filename for an eventual "Save As" dialog presented to the user.

### Insomnia Version

2021.6.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.2

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment]
Hi @rupert-madden-abbott, thank you for reporting this issue!

As of [Insomnia version 2022.3.0](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0) it seems as though we are both in the case of `Download after Send` and also in `Send and Download` ignoring the `Content-Disposition` header data.

<img width="190" alt="Screen Shot 2022-05-12 at 11 32 57" src="https://user-images.githubusercontent.com/11976836/168051759-0b410fc8-67c2-4037-83d8-697ebee2da49.png">

In the `Download after Send` case, it ends up with an altered version of the request name:
<img width="1070" alt="Screen Shot 2022-05-12 at 11 31 04" src="https://user-images.githubusercontent.com/11976836/168051813-72fdf58f-75cd-4649-9125-a7ddccd896af.png">

In the `Send and Download` case we also don't consider the header data, and pre-fill in the filename on the `Save as` dialogue as `Untitled`:
<img width="326" alt="Screen Shot 2022-05-12 at 11 25 38" src="https://user-images.githubusercontent.com/11976836/168051993-33012a2c-9f92-45c5-8e58-3f20467a5eeb.png">

We'll update you here if we at any point release something to improve each of these cases.

In the meantime feel free to report other issues, and thank you for your patience!

**Comment by sbrattla** [comment]
I'd very much like to see this issue fixed as well (`Download after send`). I need to rename files downloaded from API's, because Insomnia isn't treating the `Content-Disposition` header correctly. This is a quite annoying bug.

**Comment by danrodagu** [comment]
It doesn't seem working on the last version of the Windows client at least. The filename remains empty to be manually set, or uses the last filename used
