### ISSUE TITLE
how to seach a keyword in requestbody(jsonrequest or formdata)

### ISSUE THREAD

**Issue by VinterHe** [getinsomnia/insomnia#4257]
### Expected Behavior

now we can search keyword in title,but i want to seach a keyword in requestbody(jsonrequest or formdata) too,just like postman.
the feature  name in postman is "Find and Replace",location is in the left of bottom.

### Actual Behavior

now we can search keyword in title,but i want to seach a keyword in requestbody(jsonrequest or formdata) too,just like postman.
the feature  name in postman is "Find and Replace",location is in the left of bottom.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.10.28

### What operating system are you using?

Windows

### Operating System Version

windows 10

### Installation method

download exe and install

**Comment by wdawson** [comment]
Thanks for submitting this @VinterHe ! I'll move this to GitHub Discussions as an Idea so we can better keep track of this.
