### ISSUE TITLE
Inso installed via NPM doesn't work on WSL2

### ISSUE THREAD

**Issue by chrissmithptml** [getinsomnia/insomnia#4265]
### Expected Behavior

Inso CLI tests run in WSL bash should work the same as they do in Windows command prompt

If I run a test from the WSL bash prompt, the npm-installed cli an exported design collection, it should function the same as it does in a Windows command prompt.

### Actual Behavior

So using the inso cli on Windows command line (installed from npm) works great.

If, however, I switch to one of my WSL Linux distros, install the same inso cli via NPM, I get no love.

The test is ridiculously simple, to POST a JSON payload to a locally-running API endpoint.  On Windows, the test passes successfully. On WSL, sad face.

The actual test logic is blindingly simple:

```
const response1 = await insomnia.send();
expect(response1.status).to.equal(200);

```

Here's me running the command in a windows command prompt succesfully, then immediately switching to WSL (bash) and running the very same command, but with a weird error showing the response1.status is 'undefined'

**Windows Command Line**

```
D:\dev\na\na
λ  inso run test Test-To-Run --src api-automation\insomnia-file.json --env dev --verbose --disableCertValidation
» Data store configured from file at D:\dev\na\na\api-automation\insomnia-file.json
» Load api specification with identifier Test-To-Run from data store
» Found 0.
» Load workspace with identifier Test-To-Run from data store
» Found 0.
» Load unit test suite with identifier Test-To-Run from data store
» Found 1.
» Load base environment for the workspace wrk_07456ff1e3f84bc9a356155084502515 from data store
» Found 1.
» Load sub environment with identifier dev from data store
» Found 1


  Test-To-Run
    √ Request-Being-Run (1699ms)


  1 passing (2s)

```

**WSL / BASH**

```
D:\dev\na\na
λ bash
 /mnt/d/dev/na/na$ inso run test Test-To-Run --src api-automation/insomnia-file.json --env dev --verbose --disableCertValidation
› Data store configured from file at /mnt/d/dev/na/na/api-automation/insomnia-file.json
› Load api specification with identifier Test-To-Run from data store
› Found 0.
› Load workspace with identifier Test-To-Run from data store
› Found 0.
› Load unit test suite with identifier Test-To-Run from data store
› Found 1.
› Load base environment for the workspace wrk_07456ff1e3f84bc9a356155084502515 from data store
› Found 1.
› Load sub environment with identifier dev from data store
› Found 1


  Test-To-Run
    1) Request-Being-Run


  0 passing (974ms)
  1 failing

  1) Test-To-Run
       Request-Being-Run:
     AssertionError: expected undefined to equal 200
      at Context.<anonymous> (/tmp/insomnia-testing/0.5711905741178316-test.ts:11:33)

```

As you can see in the error message at the bottom, it appears the response is not populated / is 'undefined' 

### Reproduction Steps

Create an API endpoint which is available to both windows command line and WSL bash.  A wget or tracert should confirm that both command lines can access the URL in question.

Create a simple design collection with a test and request which does a POST or GET to this endpoint

Call this test from the Insomnia desktop client.  Works great.
Call this test from the inso cli from a Windows command prompt.  Works great.
Call this test from the inso cli  from a WSL bash prompt.  Fails

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Inso version: 2.4.0

### What operating system are you using?

Windows

### Operating System Version

Windows Version	10.0.19043 Build 19043,    WSL version: 2

### Installation method

npm install --global

### Last Known Working Insomnia version

?

**Comment by wdawson** [comment]
Thanks @chrissmithptml , just to confirm, what are your node/npm versions?

**Comment by filfreire** [comment]
Couldn't reproduce this one so far.

```
filipe@win10:~/personal/insomnia-sync-experiment$ inso run test "Example tests" --env "OpenAPI env" --verbose --disableCertValidation
› Data store configured from git repository at /mnt/c/Users/filipe/personal/insomnia-sync-experiment
› Load api specification with identifier Example tests from data store
› Found 0.
› Load workspace with identifier Example tests from data store
› Found 0.
› Load unit test suite with identifier Example tests from data store
› Found 1.
› Load base environment for the workspace wrk_840ae195af1a4094a403b75e097ca988 from data store
› Found 1.
› Load sub environment with identifier OpenAPI env from data store
› Found 1


  Example tests
    ✓ Returns 200 (1322ms)
    ✓ Returns 404 (230ms)


  2 passing (2s)
```

- This was running on a WSL 2, distro is `Ubuntu 20.04.3 LTS`
- Windows info: `Windows 10 Pro 21H2 19044.1387`
- node version `v12.18.3`
- npm version `6.14.6`



Running on node in windows directly (same node and npm versions as mentioned above):
```
C:\Users\filipe\personal\insomnia-sync-experiment>inso run test "Example tests" --env "OpenAPI env" --verbose --disableCertValidation
» Data store configured from git repository at C:\Users\filipe\personal\insomnia-sync-experiment
» Load api specification with identifier Example tests from data store
» Found 0.
» Load workspace with identifier Example tests from data store
» Found 0.
» Load unit test suite with identifier Example tests from data store
» Found 1.
» Load base environment for the workspace wrk_840ae195af1a4094a403b75e097ca988 from data store
» Found 1.
» Load sub environment with identifier OpenAPI env from data store
» Found 1


  Example tests
    √ Returns 404 (1388ms)
    √ Returns 200 (262ms)


  2 passing (2s)


C:\Users\filipe\personal\insomnia-sync-experiment>
```

**Comment by chrissmithptml** [comment]
ha!  I was just looking at that.  I'm on v14.18.2.  I noted when trying to build the inso cli locally, there's a nasty error in there relating to one of the package versions you use not being supported on 14+

Let me try your version of node and see what happens.

**Comment by chrissmithptml** [comment]
Just to be 100% sure that it wasn't some jiggery pokery with my Ubuntu 20.04 LTS distro, I nuked my WSL distro completely, reinstalled a fresh one, installed the versions of nodejs and npm you outlined above
```
$ node --version
v12.18.3
$ npm --version
6.14.6
$ inso --version
2.4.0
```

After much back and forth and then debugging through the inso code locally, it came down to WSL networking.  It relates back to calling inso (or any command for that matter) attempting to hit a url on the host Windows workstation, which is NOT supported on WSL2 at this point without all kinds of hacks.

I am instead creating a docker image with inso installed which can more easily call the host workstation using docker-compose 'extra_hosts' values.
