### ISSUE TITLE
[Improvement] Support templating in cookies

### ISSUE THREAD

**Issue by BeeeQueue** [getinsomnia/insomnia#427]
Let cookies use the same templating that request URLs and bodies do.

This would allow easier authentication testing using cookies.

Example:

![insomnia_2017-08-12_15-19-47](https://user-images.githubusercontent.com/472500/29241042-cb9a9d86-7f71-11e7-8c86-b2cd3657e38f.png)

**Comment by gschier** [comment]
This sounds like a great idea and would be fairly easy to implement 👍. 

If you'd like to take a shot at implementing it, that would be awesome. Otherwise, I'll get to it next time I have some spare time.

**Comment by BeeeQueue** [comment]
I'm gonna take a stab at it.

**Comment by gschier** [comment]
Awesome! 😄 

Let me know if you need any guidance.

**Comment by BeeeQueue** [comment]
implemented
