### ISSUE TITLE
"Import suceeded" but nothing changes

### ISSUE THREAD

**Issue by kate-koll** [getinsomnia/insomnia#4274]
### Expected Behavior

I am importing json document (originally insomnia export actually from my colleague) into a collection. 
Message pops up, that I imported Workspace, Enviroments, Requests etc. I would expect to see all imported in my collection.

### Actual Behavior

Message pops up, that I imported Workspace, Enviroments, Requests etc. but my new collection is in fact still empty. 

### Reproduction Steps

1. Insomnia Dashboard
2. Click create - Request Collection
3. Fill in name and click Create
4. Click Import from File 
![image](https://user-images.githubusercontent.com/68288880/144910776-eef07672-c9a6-42a6-8d5e-1ff1943fb9ea.png)
5. Message about successful import shows up
![image](https://user-images.githubusercontent.com/68288880/144910946-aa28a16b-e4ff-4492-a9c4-4b164aad6e12.png)
6. My collection still empty, no environments, no folders with requests...

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I also tried going through import/export by clicking on collection name; also through Preferences-Data-Import Data.
When I tried to export my own Collection and than import it back, didn't work either. 

### Insomnia Version

2021.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

downloaded from https://insomnia.rest/download and run as admin

### Last Known Working Insomnia version

-

**Comment by filfreire** [comment]
@kate-koll it seems you might be trying to import an Insomnia export of a `Design Document` into a `Request Collection`.

I would suggest you try:
A) to import the file from then initial start menu of Insomnia

![import from file](https://user-images.githubusercontent.com/11976836/145017521-83684480-e969-4109-b071-8dc48b3b063b.png)

Or,

B) Create a new Design Document, and inside that new Design Doc, attempt to re-import the file.
![design_doc](https://user-images.githubusercontent.com/11976836/145017509-b1282f5a-bedd-4bf1-8d27-54b03d8b4b27.png)

**Comment by filfreire** [comment]
@develohpanda @wdawson this might be an opportunity for improving UX, as users don't get a warning if they are trying to import a design doc into a request collection.
![req_collection_import_design_doc](https://user-images.githubusercontent.com/11976836/145017653-55dbf36b-e770-4bf3-8ee8-e6ffd439dc3f.png)

**Comment by RadoslavMarinov** [comment]
Same here: 
Version: Insomnia 2021.6.0
Release date: 10/28/2021
Windows 10
Electron: 11.2.3
Node: 12.18.3

**Comment by kate-koll** [comment]
@filfreire Hi, thanks for the reply. Didn't work though :(
![image](https://user-images.githubusercontent.com/68288880/145060432-6fb08795-1feb-4ed4-b512-b22b45469786.png)
![image](https://user-images.githubusercontent.com/68288880/145059915-8f53e196-f41a-4158-9f50-4e2bb0a2d1cd.png)
![image](https://user-images.githubusercontent.com/68288880/145060654-8a1ebc65-2384-4266-8f2c-28e712cedab6.png)

**Comment by gh-andre** [comment]
It actually overwrites the original collection that was exported, so that pop-up describes what was restored in the original collection, possibly overwriting latest changes in that collection. I created an issue for that.

https://github.com/Kong/insomnia/issues/4283

**Comment by blshkv** [comment]
is this report a duplicate of #4034?

**Comment by gh-andre** [comment]
@blshkv 

See this comment in https://github.com/Kong/insomnia/issues/4034#issuecomment-988338896 .

This bug was created, as requested, https://github.com/Kong/insomnia/issues/4283 in the comment above.

So, it's a duplicate of the latter. There's a couple more with the same problem, as far as I can see.

**Comment by demarchenac** [comment]
Are there any updates on this issue?

**Comment by stoccalino** [comment]
Hello guys, i had the same error. I was able to solve it really simple, just click here  (top left corner where it says Insomnia / New document) and you should have the imports made in another collection of insomnia : 

<img width="870" alt="image" src="https://user-images.githubusercontent.com/103459775/164032716-97b29216-7e3f-46b6-b660-db5f665d5876.png">

**Comment by gh-andre** [comment]
@stoccalino 

The bug is that it overwrites the original collection because it uses the same collection IDs as it exported. What most likely happened in your case is that the collection ID didn't exist on this computer and it appeared that it created a new one. If you change the collection you just imported and then import the original file again, your changes most likely will be gone.

**Comment by justindupree01** [comment]
I'm running into this issue as well, even with a install of Insomnia that's never seen the collection before. Exact same behavior, shows all the successful import messages in the pop up and then there's nothing there. 

Any new ideas on how to get around this?

**Comment by gh-andre** [comment]
@justindupree01 I used this hack, which worked that time, but this is not something that could be considered safe. Even if it still works you would need to verify the result really well in that it doesn't have some side effects.

https://github.com/Kong/insomnia/issues/4034#issuecomment-988267447

**Comment by darrenbarklie** [comment]
Encountered this too -- frustrating bug to encounter immediately after paying for a subscription.

I had success by navigating to my INSOMNIA base environment, then Duplicate the Collection from there, selecting the Remote environment as the location.

Interestingly, this then revealed the previously hidden file-migrated Collection.  I then had to delete the cloned remote environment.

**Comment by Phuong5664** [comment]
I have tried all options possible (importing different ways) and also have tried to reinstall with the latest version: Insomnia 2022.3.0 but unable to import any collection.

**Comment by sabatiny** [comment]
I have tried too, but not working

**Comment by vittorio-c** [comment]
If you're like me, importing a collection in remote project, previously existing in local project and exported from there, try first deleting the local one. Because otherwise, since they have same ID or something like that, the import of the collection simply overwrite the local previous collection (the one from which you created the export).

**Comment by adamxi** [comment]
Can confirm. I wanted to move my old insomnia collection to a personal project.

- First export your old old collection.
- Then delete the old collection.
- Then! switch to your personal project and import the old collection.

**Comment by gh-andre** [comment]
For those who just want to move collections/documents between projects, there's a simpler way. 

* Create an empty target project
* Go to the source project
* Click triple dots in the collection/document you want to move and click `Duplicate`
* Change the name to your liking, select the target project and click `Duplicate`

This copies collections/documents/environments to the target project. Check that the copy is good and delete the original from the source project.

I also find this hack useful for committing exported YAML into the repository - duplicating collections/documents to a transient project before exporting what goes into the repository helps with subsequent check-out/import because it won't overwrite the original collection.

**Comment by Hema2810** [comment]
Worst UI ever, wasted a lot of time.  It is definitely not obvious that the word "Insomnia" needs to be clicked to view, a different collection

**Comment by CharlesMavundla** [comment]
**The solution is very simple**. Insomnia imports your collection but it does not show you where to find your imported collection. So import your collection and then to view your imported collection you need to go to the Dashboard. Click on the word "Insomnia" next to the purple circle, you should see 
your dashboard and then after that choose your collection and you should now see all the requests/endpoints in your collection.

<img width="205" alt="1" src="https://user-images.githubusercontent.com/108276776/175941781-e4fbf472-f340-444d-94ab-4354a002eaf4.PNG">
<img width="373" alt="2" src="https://user-images.githubusercontent.com/108276776/175941805-fac1d5fa-7ba0-4097-a88c-db75d9eb8d1a.PNG">

**Comment by gh-andre** [comment]
@CharlesMavundla The real issue here is not so much where imported data ends up, but rather that it will wipe out your existing data after the import. See issue #4283 for details.

**Comment by filfreire** [comment]
Hi folks, we'll try to prioritise this issue, and also #4283  as soon as possible as like many of you mention the current user experience is very stressful or surprising (in a wrong way).

Heads up @wongstein and @subnetmarco - marking these in our internal `Needs Fix` area in the internal [GH triage project](https://github.com/orgs/Kong/projects/20/views/1)

**Comment by samadams412** [comment]
For anyone still having this issue: I exported the collection as HAR - HTTP Archive Format instead of Insomnia V4(JSON) and was then able to successfully import it without any issues.

**Comment by gh-andre** [comment]
@samadams412 
You lose all variables, etc using HAR. Use this instead.

https://github.com/Kong/insomnia/issues/4283#issuecomment-1167459831

**Comment by rehpotsirhc21** [comment]
wow. It took way to long and a lot of bad answers. Are they doing anything to make it more clear as to what is happening? right now the whole file process is terrible you cant tell what happened from the import and its unclear where to navigate.

**Comment by BlakeGardner** [comment]
> 

I just paid for the team version of Insomnia and had issues importing my collections into a team project. This solved my issue.

**Comment by bipsa** [comment]
The same here, it tells me if I want to import it, but I need something to happen after. :/

**Comment by jramiresbrito** [comment]
Any update on this? Using the export feature messed up my Insomnia.

**Comment by BarakAlmog** [comment]
Same problem. I didn't imagine this simple feature would turn out to be such a huge headache.

**Comment by gabuch2** [comment]
Issue from 2021 and still present 🤡

**Comment by subnetmarco** [comment]
@gabuch2 submit a PR if you care about it, rather than calling the contributors clowns, this is an open source project and anybody can contribute. Have some respect.

**Comment by ghost** [comment]
@subnetmarco You are right, I was struggling for hours with this problem and I let myself carry away by the moment.

**Comment by subnetmarco** [comment]
@gabuch2 thank you. I will look into this with the team, and we will try to get it fixed. I understand this is a frustrating issue.

**Comment by maxxyme** [comment]
> @gabuch2 submit a PR if you care about it, rather than calling the contributors clowns, this is an open source project and anybody can contribute. Have some respect.

nice advice pal...  but only valid if you can code... not if you're just a simple end-user... 🤔

**Comment by gh-andre** [comment]
> @gabuch2 submit a PR if you care about it, rather than calling the contributors clowns, this is an open source project and anybody can contribute. Have some respect.

It's a data loss issue at the heart of the product, which requires fundamental changes and is not something a drive-by PR would solve. Yes, people get frustrated when they lose data. It doesn't excuse rudeness, but telling people to fix it on their own isn't quite fair towards Insomnia users, especially for those who paid for subscription and just use in their testing activities.

**Comment by Theobano** [comment]
Is there any update or a workaround on this?

**Comment by gatzjames** [comment]
👋 Hey everyone!
We just released a new [Beta version](https://github.com/Kong/insomnia/releases/tag/core%402023.2.0-beta.1) that includes an improved Import experience for Insomnia. Please try it out and lets us know what you think.
Thanks for all your feedback!

**Comment by subnetmarco** [comment]
@Theobano @gh-andre @gabuch2 @BarakAlmog @jramiresbrito @maxxyme @kate-koll and all, we have released a new Beta version that should fix this issue. @gatzjames has posted a link above in case you would like to try it.

**Comment by goodeye** [comment]
I battled this for a few hours, trying to just export from old computer, then import to new computer. Same symptoms with stable and beta release: Import dialog shows a lot of requests, then nowhere to be found. What finally worked was to export only 1 collection from old computer, uninstall and delete data folders on new computer, install beta, and import the 1 collection. (maybe stable version would have done this too).
Then the beta automatically "updated" back to the stable release.

**Comment by fellypsantos** [comment]
That's too bad, neither the native import feature or the plugin insomnia-plugin-gist-sync are working anymore, as others said, the import dialog shows a bunch of requests, but nothing is shown after complete.

**Comment by hosseio** [comment]
trying the beta with no success

**Comment by edencorbin** [comment]
Okay just commenting here I found that confusing too, you import a request collection and it says it finds the data but then shows an error "insomnia import the provided document does not match". However, if you are in the context of a request collection it imports fine. I suggest making that a little more intuitive.

**Comment by subnetmarco** [comment]
We are re-opening the issue since it seems like this problem keeps happening, and making this our top priority. We are taking a deeper approach now, and the fact that this is happening is unacceptable. This is what we are doing so far:

- We know that version upgrades may trigger data migrations.
- We are now implementing backups for migrations in such a way that data is never lost (https://github.com/Kong/insomnia/pull/6005). The data can be manually restored on a previous version of Insomnia if a problem happens.
- We will then increase the amount of logging that we output during migrations in order to identify the problematic one. We think that there is one migration in particular that is entering an inconsistent state and that is very hard to catch.
- We need to build better error handling 

@gatzjames please chime in on "insomnia import the provided document does not match" error.

**Comment by gh-andre** [comment]
I tried the new version. The original issue of overwriting the source collection seems to be fixed, but after a few of minutes of testing, I can identify a couple of issues. 

1. Environments in the exported YAML are ignored, so imported cannot be used until environments are recreated.

2. When I'm focused on some collection in some project and in the context of that collection I select _Import/Export_ from the top menu, the default collection name is my currently selected one, but the project is defaulted to _Insomnia_, which isn't obvious to begin with, but the import still goes into the selected project, while the focus switches to _Insomnia_ project, which doesn't have the import.

**Comment by gatzjames** [comment]
@gh-andre and everyone here thanks for the feedback!
We have added support for multiple workspace imports alongside with respecting the exported names and scope in 2023.3.0
We have also improved our logging and migration logic in the app.
We aim to have no issues related to data imports/exports and backups so your feedback is really valuable 🙏
Let us now how this release works for you!
