### ISSUE TITLE
Error Cloning Repository

### ISSUE THREAD

**Issue by RadoslavMarinov** [getinsomnia/insomnia#4279]
### Expected Behavior

I would like to clone .insomnia repository that I successfully updated on another machine via insomnia

### Actual Behavior

I see a popup saying Error Cloning Repository
![2021-12-07 111919](https://user-images.githubusercontent.com/15731937/145051182-48c6a634-5894-46e5-9a3c-8a8c403944e9.png)

I used the same git repo configurations as I did on the other machine 

### Reproduction Steps

1. Open Insomnia
2. Click on Create on the upper right corner
3. Clock on Git Clone at the bottom  of the list
4. Fill in the form 
5. Click Done 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

In the developers view console I see the following output (and no errros)

> 16:47:29.311 › [ga] Event Modals, Show, GitRepositorySettingsModal
> 16:47:55.202 › [ga] Event Git, Clone
> 16:47:55.507 › [ga] Event Modals, Show, AlertModal

**_Environment:_**
Version: Insomnia 2021.6.0
Release date: 10/28/2021
OS: Windows_NT x64 10.0.18363
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0-DEV OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.41.0

### Insomnia Version

2021.6.0

### What operating system are you using?

Windows

### Operating System Version

Widnows 10

### Installation method

https://updates.insomnia.rest/downloads/windows/latest

**Comment by filfreire** [comment]
@RadoslavMarinov thank you for reporting this issue!

Is this still happening when you use `2021.7.2`?

Can you provide more details on the repo you are trying to clone, like:
-  is it a private repo on cloud Github / Gitlab / Bitbucket ... 
- is the repo in a self-hosted / on-premises git server?

**Comment by RadoslavMarinov** [comment]
@filfreire 
Thanks for your reply.
I managed to work around this issue by 
1) Uninstalled insomnia 
2) Deleted C:\Users\Chuck Noris\AppData\Roaming\Insomnia\ folder 
3) Installed Insomnia again

I had tried only steps 1) and 3) before this work-around, but that didnt help. It seems that there have been some old setup data into Insomnia folder that prevented connecting to the git repo.

BTW I dont think it is related to the program version because I reinstalled the same Insomnia version.
> is it a private repo on ....

Yes it is a private repo on Github. Unfortunatelly I have some login credentials put into global environment (yes Im still in learning process ) so I cant just share the repo now. 

 
> is the repo in a self-hosted / on-premises git server?

Github hosted private repository.

**Comment by filfreire** [comment]
@RadoslavMarinov I'm going ahead and closing this issue.

Feel free to re-open it if you're still having problems cloning repository with our [latest release](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0) (or our [latest beta release](https://github.com/Kong/insomnia/releases/tag/core%402022.4.0-beta.2)).

Also feel free to report any other issues you find 👍
