### ISSUE TITLE
[Installation] White screen on app launch after fresh install

### ISSUE THREAD

**Issue by ka3de** [getinsomnia/insomnia#428]
This might seem like a ridiculous issue to submit, but.. It's an issue after all i guess..
I was happily using Insomnia in Windows. Now I moved to Ubuntu and got sad as I was unable to make it work :(

## Overview
- Insomnia Version: 5.7.9
- Operating System:  Ubuntu 16.04
- Summary: Insomnia only loads properly when opened with root privileges. Even in this case I'm unable to create a new request. I'm able though, to create new workspaces, folders, environments.

## How To Reproduce
1. Download the .deb package from Insomnia web page. In this case "insomnia_5.7.9_amd64.deb"
2. Open a terminal
3. Install the package: sudo dpkg -i insomnia_5.7.9_amd64.deb
4. Install missing dependencies: sudo apt-get install -f
5. Open insomnia: The window itself is loaded, but the content is all blank, like shown in attached "image1".
![image1](https://user-images.githubusercontent.com/6529572/29242380-a7f1239e-7f8c-11e7-8ec1-6335cc80b258.png)

6. Open insomnia as root. It loads up properly, but when filling the "new request" form, pressing the "Create" button doesn't do anything.

At first I thought it was some permissions problem. But being able to create workspaces, folders and environments makes me doubtful about it..

## Other Notes
I've checked that /tmp folder allows execution.
I've installed libcurl as follows:
sudo apt-get install libcurl4-openssl-dev

**Comment by gschier** [comment]
Hey @ka3de,

Can you follow the instructions in this comment to check for any errors?
https://github.com/getinsomnia/insomnia/issues/424#issuecomment-321907885

**Comment by ka3de** [comment]
Hi @gschier thanks for the tips.
I tried what you said.
So, the white screen problem was due to my use (not root) not having permissions on the Insomnia .db files. Once fixed that I could see the application loading properly.

Now I'm still stuck with the problem trying to create a new request. This is the output that I got with the developer tools.
First, this is the dev tools error output when I clicked on "New request":
![e1](https://user-images.githubusercontent.com/6529572/29243632-1b0cbafc-7fa4-11e7-9749-5eb4c58ea630.png)


And this is the output error when I clicked on "Create".
![e2](https://user-images.githubusercontent.com/6529572/29243638-2a1908fc-7fa4-11e7-8a60-45148a069fcd.png)


Hope that helps.
Thank you for your time.

**Comment by gschier** [comment]
@ka3de, this was a bug but is now fixed in 5.7.10

**Comment by ka3de** [comment]
Now I can enjoy the app again :D
Thank you for the quick response and fix! Nice work!

**Comment by gschier** [comment]
Thanks @ka3de!
