### ISSUE TITLE
Cancel request not working

### ISSUE THREAD

**Issue by night-fury-web** [getinsomnia/insomnia#4287]
### Expected Behavior

Cancel request button should cancel running request.

### Actual Behavior

Cancel request doesn't end request until it's finished.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem, but no same issue reported.

### Insomnia Version

2021.7.0

### What operating system are you using?

Windows

### Operating System Version

Windows10 21H2

### Installation method

download from website

**Comment by develohpanda** [comment]
Thank you for reporting this @sandguardian!

**Comment by develohpanda** [comment]
We've just released [2021.7.1](https://github.com/Kong/insomnia/releases/tag/core%402021.7.1), where this is fixed up. Apologies for any inconvenience, and thank you again for such a prompt bug report! 🙏🏽

**Comment by night-fury-web** [comment]
Thanks @develohpanda  for quick fix!
