### ISSUE TITLE
[BUG] variables in sub environment don't appears immediatly

### ISSUE THREAD

**Issue by evoxmusic** [getinsomnia/insomnia#429]
## Overview
- `Insomnia Version:` _(e.g. 5.7.10)_
- `Operating System:`  _(e.g. MacOS 10.11.6)_
- `Summary: ` _While adding sub environment variables into an existing sub environment document, once validated the variable is available, but when I go back to the editing window the variable does not exist. Closing the window and coming back once again show the variable. Is there any document cache issue or race condition ?_

## How To Reproduce
_Please list all pertinent information and steps needed to reproduce the issue. For example:_
1. _Create sub environment_
2. _add variable `{"hello": "world"}` and click `done`_
3. _CMD+ E to see sub environment variables (variable disappear), then close it_
4. _Reopen window CMD +E, variable re appear (magic :))_

**Comment by gschier** [comment]
Ah yes, I refactored the way modal dialog rendering was done in the last update, so this is a side-effect of that. I'll get it fixed :)

**Comment by gschier** [comment]
@evoxmusic should be fixed now in 5.7.11

**Comment by evoxmusic** [comment]
I confirm that is working correctly now 😎

**Comment by gschier** [comment]
Nice!
