### ISSUE TITLE
Requests with multipart form body keep loading

### ISSUE THREAD

**Issue by Gration1** [getinsomnia/insomnia#4296]
### Expected Behavior

The request sends

### Actual Behavior

When attempting to send a request it keeps loading indefinitely.

### Reproduction Steps

1. Create any request (the actual url doesn't matter)
2. Change the body to "Multipart Form" (contents don't matter)
3. Attempt to send the request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.7.1

### What operating system are you using?

macOS

### Operating System Version

macOS  Monterey 12.0.1

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

2021.6.0

**Comment by Andy045** [comment]
me too2021.6.0

**Comment by screamndigit** [comment]
I concur, same issue happening with me (on Windows,  Insomnia 2021.7.1 -- was working on prior versions)
app log shows error for any multipart form request:
```
[2021-12-09 10:45:36.918] [error] [catcher] Unhandled rejection: TypeError: Cannot read property 'app' of undefined
    at C:\Users\jeff\AppData\Local\insomnia\app-2021.7.1\resources\app.asar\main.min.js:120624:80
    at new Promise (<anonymous>)
    at buildMultipart (C:\Users\jeff\AppData\Local\insomnia\app-2021.7.1\resources\app.asar\main.min.js:120623:10)
    at C:\Users\jeff\AppData\Local\insomnia\app-2021.7.1\resources\app.asar\main.min.js:121253:19
```

**Comment by danielfalsetti** [comment]
My too on both (windows and mac)

**Comment by Volksfeld** [comment]
Same happening on Windows. Request works fine when sending as JSON, loads indefinitely when sending as multipart

**Comment by filfreire** [comment]
Can reproduce this. It was working on `2021.6.0`.

![Screenshot_2021-12-09_at_17_09_17](https://user-images.githubusercontent.com/11976836/145457486-62725442-eb39-481b-a853-1bc777dc6ece.png)

![Screenshot_2021-12-09_at_17_05_13](https://user-images.githubusercontent.com/11976836/145457488-7d070831-ec0c-48c0-b8dd-038628e6fdc5.png)

**Comment by filfreire** [comment]
This has been fixed after latest update (version `2021.7.2`).  Can you kindly confirm it is the case for you folks?

cc @Gration1 / @screamndigit / @danielfalsetti / @Volksfeld

**Comment by Gration1** [comment]
`2021.7.2` seems to have fixed it.

**Comment by abbluiz** [comment]
@filfreire 
Can you guys please update the flatpak release? It's still in `2021.7.1` version and this error keeps happening. Thanks in advance.

**Comment by filfreire** [comment]
@abbluiz the flatpak release is being setup by community efforts outside our team (e.g. by @WhyNotHugo).
I've reached out to @WhyNotHugo so we can also get permissions to update the flatpak release on https://github.com/flathub/rest.insomnia.Insomnia
