### ISSUE TITLE
[Bug] Unable to copy+paste from Preview response view

### ISSUE THREAD

**Issue by matthew-the-analyst** [getinsomnia/insomnia#430]
## Overview
- `Insomnia Version:` 5.7.11
- `Operating System:`  Windows 10 Pro - 1703
- `Summary: ` Unable to copy more than 1000 characters (including line breaks) from the Preview response view.  When pasting, only "-" gets pasted, instead of the selected/copied text.

## How To Reproduce
1. Perform a request which returns a response with more than 1000 characters
2. Copy more than 1000 characters from the the Preview response view (ctrl-c, right click - copy, etc)
3. Paste copied context into notepad.  Only "-" appears. 

## Other Notes

"Raw Data" view does not seem to be affected, only the Visual Preview view.

**Comment by sardaukar** [comment]
Same for `5.7.11` on macOS.
