### ISSUE TITLE
[Improvement] Zipped binaries for Windows (instead of installer)

### ISSUE THREAD

**Issue by alexandrul** [getinsomnia/insomnia#431]
Is it possible to also provide the Windows binaries as a zip archive? The current installer (5.7.11) it's still placed into quarantine by Symantec Endpoint Protection.

**Comment by petertirrell** [comment]
Ran into this same problem this morning.  Glad I'm not the only one.

**Comment by alexandrul** [comment]
You can extract the binaries using 7zip and repackage them, but it's not so funny after a few releases.

**Comment by gschier** [comment]
@alexandrul, do you mean for the installer `exe` or the auto-update `nupkg`? Also, can you explain why zipping the Windows binary would make a difference?

**Comment by alexandrul** [comment]
@gschier I'm extracting the nupkg from the installer, and the binaries from nupkg.

Since not everyone uses Insomnia (yet), it's much slower to send the installer (or the download link) to new users (since the antivirus will move it to quaratine and they have to manually restore it) than simply put the zipped binaries on a local network share.

**Comment by gschier** [comment]
If #498 is finished, this will be a one-line configuration change.

**Comment by gschier** [comment]
Just a quick question for you Windows users. Electron Builder (the packager that Insomnia users) offers both a `zip` and `standalone` build target. Can anyone explain what the difference between those would be, or if one would be better than the other for this case? Also, how would the update process work in this situation? 

https://www.electron.build/configuration/win#WindowsConfiguration-target

**Comment by alexandrul** [comment]
Not sure about the difference, if you can upload the resulting files somewhere I can try them.

E.g.: Grafana

* It has a `conf` subfolder with an existing `defaults.ini`. Users can create a `custom.ini` file that overrides the default values and won't be affected by any upgrades.
* Application data and logs are located by default in subfolders (`data`, `data/log`, `data/plugins`), can be altered in `custom.ini`
* My usual upgrade process consists in keeping only the `data` and `conf` folders then unpacking the new version in the same folder (`defaults.ini` will be updated).

For Insomnia, you can decide based on a marker file if it should use subfolders or the standard windows locations for all necessary data (user settings, history, and so on).

**Comment by Mikecom32** [comment]
Some type of standalone/portable build would be great for when you can't install software. 

Adding my support for this.

**Comment by damajor** [comment]
I support the remark of @Mikecom32 for the portable edition of Insomnia.

**Comment by jialu98** [comment]
Support for a portable edition of Insomnia on windows

**Comment by damajor** [comment]
Please reopen.
