### ISSUE TITLE
[Feature Request] Deduplication of JSON response

### ISSUE THREAD

**Issue by adius** [getinsomnia/insomnia#432]
It would be cool if there was a way to deduplicate the JSON response.
E.g. by removing all duplicates in an array after the json-path filtering.

**Comment by gschier** [comment]
Hi @adius. Thanks for the request, but I hesitate to include such an uncommon feature into the core app. I've started on a plugin system, though, which may eventually be able to facilitate a feature like this.

**Comment by adius** [comment]
Yeah, that was my initial thought as well, but now I think sorting and removal of duplicates are so common and important, they should be included in the core, or if they implemented as plugins bundled per default with the core.

**Comment by gschier** [comment]
Since Insomnia is used frequently for debugging, I think the output should reflect the actual response as closely as possible. Deduplicating JSON keys would be hiding information from the user.
