### ISSUE TITLE
Official snap on snapcraft.io should be published by Insomnia team/Kong

### ISSUE THREAD

**Issue by santiagofn** [getinsomnia/insomnia#4323]
### Expected Behavior

Official [snap built on snapcrat.io](https://snapcraft.io/insomnia) should be published by the Insomia team/Kong. The publisher should be verified.

### Actual Behavior

Snap built is being published by gschier1990, who is not verified.

![image](https://user-images.githubusercontent.com/8375708/146645063-114b1635-c275-4dc2-9789-3729898fded8.png)

### Reproduction Steps

1. Go to snapcraft.io
2. Look for the official snap built

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Having an official/verified publisher gives more confidence in the app being downloaded and in the support that could be given.

### Insomnia Version

2021.7.2

### What operating system are you using?

Ubuntu

### Operating System Version

21.10

### Installation method

Snap

### Last Known Working Insomnia version

2021.7.2

**Comment by filfreire** [comment]
Hi @santiagofn, thank you for reporting this issue!

In the meantime this was fixed, and it's now pointing to `getinsomnia` as publisher ([link](https://snapcraft.io/insomnia)).

<img width="458" alt="Screen Shot 2022-05-12 at 11 48 39" src="https://user-images.githubusercontent.com/11976836/168054288-da5b5982-b927-4649-a399-8fe356f0d0fa.png">

Feel free to report any other issues you may find on Insomnia, in the meantime we'll also try to update you on the other issues you've raised in the past 👍
