### ISSUE TITLE
Request gets executed twice

### ISSUE THREAD

**Issue by sebastianbuechler** [getinsomnia/insomnia#4333]
### Expected Behavior

When I push "Send" in insomnia I expect the HTTP request gets executed once.

### Actual Behavior

When calling a webserver all requests from Insomnia gets executed twice. 

### Reproduction Steps

1. Click on "Send"
2. Inspect local web server for incoming requests and see that it's coming twice

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

For the same webserver this behavior does not appear when using cURL or Postman.

### Insomnia Version

2021.7.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 19043

### Installation method

https://insomnia.rest/download

### Last Known Working Insomnia version

Probably 2021.5.0 (not quite sure)

**Comment by filfreire** [comment]
Hi @sebastianbuechler, thank you for reporting this!

I can't seem to reproduce the behaviour you mention in the latest stable version of Insomnia (`2021.7.2`).

I've tried both on Windows and on MacOS and from the webserver (an [example flask server](https://pythonprogramminglanguage.com/python-flask-example/)) side I see only one successful request:

Example of a few requests on MacOS:
![Screenshot 2022-01-04 at 11 08 09](https://user-images.githubusercontent.com/11976836/148051805-7cdb80c4-398e-4815-aae0-62451957651c.png)

Example on Windows:
![2022-01-04111758](https://user-images.githubusercontent.com/11976836/148051935-e49ed31a-0f17-43da-bb07-7b7383daae9b.jpg)

I've also tried to send a few requests against a [mockbin](http://mockbin.org/) and can't also reproduce.

I suspect it may be something to do with how your Windows installation and the webserver handles dns resolution for localhost.

- Does this still happen regardless if you use `localhost` or `127.0.0.1` on the hostname address?
- Can you share some more information, like screenshots and/or the logs from Insomnia's `Timeline` tab of the request?

**Comment by kaejul** [comment]
It happens to me when I use the keyboard shortcut to run the request `cmd + enter` but not when I click on Send button
```
Version: Insomnia 11.6.1
Build date: 9/18/2025
OS: Darwin arm64 23.5.0
Electron: 37.2.6
Node: 22.17.1
Node ABI: 136
V8: 13.8.258.30-electron.0
Architecture: arm64
```

**Comment by LetrixZ** [comment]
Still happening with `cmd + enter` in v12.3.0

**Comment by jack-arvo** [comment]
same issue on cmd+enter, macos 26.2 (25C56)
```
Version: Insomnia 12.4.0
Build date: 3/5/2026
OS: Darwin arm64 25.2.0
Electron: 38.4.0
Node: 22.20.0
Node ABI: 139
V8: 14.0.365.10-electron.0
Architecture: arm64
```
