### ISSUE TITLE
Plugins Hub's head tag contains unrendered contents

### ISSUE THREAD

**Issue by juzhiyuan** [getinsomnia/insomnia#4343]
### Expected Behavior

Hi, when I share the URL[1], I noticed there has some unrendered content, because I cannot find this page's source codes repo, so I choose to submit an issue.

[1] https://insomnia.rest/plugins

### Actual Behavior

![image](https://user-images.githubusercontent.com/2106987/148312387-dce42bfe-9a9f-4348-bcba-1fad215342e6.png)

### Reproduction Steps

1. Visit https://insomnia.rest/plugins
2. Check its HTML source codes.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

None

### What operating system are you using?

macOS

### Operating System Version

None

### Installation method

None

**Comment by wdawson** [comment]
Thanks for the report @juzhiyuan . I've fixed this and it should roll out to the CDN soon.
