### ISSUE TITLE
[Bug] Clashed eternally on MessagePack request

### ISSUE THREAD

**Issue by rela1470** [getinsomnia/insomnia#435]
- Insomnia Version: 5.7.12
- Operating System: macOS Sierra 10.12.6

## Details
please see my github.
* https://github.com/rela1470/insomnia-msgpack-test

Insomnia for mac clashed eternally for access MessagePack.

# environment
* Insomnia 5.7.12

* mac OS Sierra 10.12.6 … clashed eternally
* Windows 10 Home build 1511 … not clash

# test

## php local build in server
* git clone `git@github.com:rela1470/insomnia-msgpack-test.git`
* cd insomnia-msgpack-test
* php -S localhost:8000
* access
 * http://localhost:8000/json.php
 * http://localhost:8000/msgpack.php

## my host server
* https://rela.red/insomnia-msgpack-test/json.php
* https://rela.red/insomnia-msgpack-test/msgpack.php

# recovery
* uninstall insomnia by AppCleaner.
* re-install

**Comment by gschier** [comment]
Hi @rela1470,

I tried contacting your two public URLs, but am unable to see any problem. What do you mean exactly by "clashed eternally"? Can you post a screenshot of the error?

Here is what it looks like for me:

![image](https://user-images.githubusercontent.com/587576/29439583-7bfa0126-8373-11e7-90b8-d7e5a1174780.png)

**Comment by gschier** [comment]
Closing as stale.
