### ISSUE TITLE
[Question] Is there any way to share authentication (OAuth2) for a group of requests?

### ISSUE THREAD

**Issue by oliverjanik** [getinsomnia/insomnia#436]
As it stands, each request remembers it's own OAuth2 settings. Is there any way to share it?

**Comment by gschier** [comment]
Not yet, but I'd like to get there eventually. I usually extract the settings into environment variables so I can at least edit them in one place: 
![image](https://user-images.githubusercontent.com/587576/29389341-59415c7c-829e-11e7-85a4-37808c064fc0.png)
