### ISSUE TITLE
[Feature] Hawk authentication support

### ISSUE THREAD

**Issue by jgiovaresco** [getinsomnia/insomnia#437]
The only missing feature which prevent me to move totally on Insomnia is the Hawk Authentication missing.

Do you plan to implement this ?

**Comment by gschier** [comment]
Hey @jgiovaresco, thanks for the request. You're the first one who has actually requested it, so I haven't looked into it yet. If it's easy to implement, maybe.

Would you be interested in contributing a PR for this?

**Comment by jgiovaresco** [comment]
@gschier I can try working on this. Not sure this will be easy to implement though :)
