### ISSUE TITLE
Focus Body Keyboard Shortcut

### ISSUE THREAD

**Issue by lefuturiste** [getinsomnia/insomnia#4374]
### Discussed in https://github.com/Kong/insomnia/discussions/3536

<div type='discussions-op-text'>

<sup>Originally posted by **EmperorEarth** June 11, 2020</sup>
In a variety of contexts, I adjust the request body (usually JSON/GraphQL).

Can we get a keyboard shortcut to set it as the focus?

Also would be nice to have a keyboard shortcut to focus "Query Variables" for GraphQL requests</div>

**Comment by filfreire** [comment]
@wdawson tagging you in this one, seems like an interesting suggestion to improve user experience.

**Comment by wdawson** [comment]
Thanks @lefuturiste . Let's have the conversation in the Discussion since this is an idea for a new feature and not an issue with an existing one.
