### ISSUE TITLE
[Question] what if body with variable style content

### ISSUE THREAD

**Issue by yittg** [getinsomnia/insomnia#438]
When i write a body with content contains text like `{{ something }}`, and it will be parsed as `variable` automatically. 
How to just use the very text `{{ something }}` not parsed. Thanks.

**Comment by gschier** [comment]
Hi @yittg,

You can disable this behavior in the request settings (accessible from the sidebar).

![image](https://user-images.githubusercontent.com/587576/29439616-b454c3b2-8373-11e7-8272-f52dfd92ffd6.png)


For finer-grained control, you can also wrap specific content in `{% raw %}...{% endraw %}`

![image](https://user-images.githubusercontent.com/587576/29439640-de772cf2-8373-11e7-947d-5347cc580de1.png)
