### ISSUE TITLE
Password escaping backslash bug

### ISSUE THREAD

**Issue by Zugelato** [getinsomnia/insomnia#4381]
### Expected Behavior

In my Sub environment i have the credentials for a user. There i have defined a password that starts with a backslash, so it has to be escaped in oderer to not throw a parsing error:

 `"password": "\0815"` -> `"password": "\\0815"`

Making any request with validation, via baisc auth using `_.password` should now work.
(I checked the pwd)

### Actual Behavior

However it throws an error, saying there is a render error because of the password.

![grafik](https://user-images.githubusercontent.com/98013902/150089135-94fa9e25-f916-4bdc-ba7a-2fbb7565ab1a.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.7.2

### What operating system are you using?

Windows

### Operating System Version

Version 10.0.19043 Build 19043

### Installation method

https://insomnia.rest/download

**Comment by filfreire** [comment]
@Zugelato can you please check if the sub-environment with the password is selected and setup correctly?

I've tried reproducing your issue, and the only way I can reproduce is if I select a sub environment where the field is not defined. For example, bellow I have 2 environments.

![Screenshot 2022-01-19 at 11 42 55](https://user-images.githubusercontent.com/11976836/150123475-0a6442fe-3a8a-43d1-a6b9-a1cafba60878.png)

One of them does not have the `subenv_password` variable. If I try to use that environment I get the same kind of error message you are getting:

![Screenshot 2022-01-19 at 11 42 46](https://user-images.githubusercontent.com/11976836/150123487-49ead064-ff2c-446c-a17f-2004efc8c66b.png)

**Comment by Zugelato** [comment]
@filfreire you are correct, i had a typo in password/passwort, `\\` works just fine now

**Comment by filfreire** [comment]
@Zugelato happy to help! Don't forget to check out [our Docs](https://docs.insomnia.rest/insomnia/get-started) and stay tuned for upcoming Insomnia releases 😉
