### ISSUE TITLE
Installing on ChromeOS gives me "dependency problems prevent configuration of insomnia"

### ISSUE THREAD

**Issue by bulgariamitko** [getinsomnia/insomnia#4388]
### Expected Behavior

To be installed without any problem

### Actual Behavior

I get this error: 

:~$ sudo dpkg --install Insomnia.Core-2021.7.2.deb 
Selecting previously unselected package insomnia.
(Reading database ... 35501 files and directories currently installed.)
Preparing to unpack Insomnia.Core-2021.7.2.deb ...
Unpacking insomnia (2021.7.2) ...
dpkg: dependency problems prevent configuration of insomnia:
 insomnia depends on libnotify4; however:
  Package libnotify4 is not installed.
 insomnia depends on libnss3; however:
  Package libnss3 is not installed.
 insomnia depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.
 insomnia depends on libsecret-1-0; however:
  Package libsecret-1-0 is not installed.

dpkg: error processing package insomnia (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 insomnia

### Reproduction Steps

1. Open terminal
2. Write: "sudo dpkg --install Insomnia.Core-2021.7.2.deb"
3. Get the error :

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I also tried a workout and change the libappindicator3-1 with libayatana-appindicator3-1 by unpacking the deb file and then repacking it again, but this did not fix my problem. 

### Insomnia Version

2021.7.2

### What operating system are you using?

Other (specify below)

### Operating System Version

ChromeOS 97

### Installation method

both deb and apt install do not work

### Last Known Working Insomnia version

none

**Comment by filfreire** [comment]
Hi @bulgariamitko, I might be mistaken, but we don't officially support ChromeOS, so sadly we are not able to help a lot in the meantime. Are you by any chance still facing this issue with [latest Insomnia release](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)?

fyi @wdawson, in the future we could potentially look into providing some sort of support or at least document some known workarounds for folks wanting to use Insomnia in ChromeOS. If anyone else in the community has already found workarounds, please feel free to share here 👍

**Comment by bulgariamitko** [comment]
@filfreire , I just tried it out and it is working with the latest version of Insomnia! I am soooo happy! Thanks, now I can go back and code 🗡️  🍡
