### ISSUE TITLE
Desktop icon is re-added after every update

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#44]

**Comment by thejonwithnoh** [comment]
It seems like this issue is still occurring in the latest version.  While this is only a minor annoyance, as someone who likes to keep their desktop pristine, it is still an annoyance.  Perhaps it's worth reopening?

**Comment by DominikSerafin** [comment]
Can confirm it still happens (Windows 10)

**Comment by DominikSerafin** [comment]
Still happens (commenting so stale bot won't close it)

**Comment by taviandir** [comment]
I will add that this still happens, and it's quite the nuisance for someone like me who cares greatly what appears on my desktop. Would really appreciate a fix to this!

**Comment by blieque** [comment]
I have one icon on my desktop, with an invisible name and a transparent icon, so it's quite noticeable. Every time I open Insomnia there seems to have been an update, so as soon as I see the toast I press Win+D and delete the new shortcut. As I'm sure you can imagine, this has a great toll on my weekly productivity! 😉

**Comment by DominikSerafin** [comment]
Still happens (commenting again so stale bot won't close it)

**Comment by 2f4f4f** [comment]
Is this fixed now?
No new shortcut on desktop after updating to v5.16.6, but found no mention in the changelog.

**Comment by gschier** [comment]
This hasn't been explicitly fixed but it's possible that a dependency was updated that stopped it from happening? 

Can someone confirm (I'm not a Windows user)?

**Comment by 2f4f4f** [comment]
A shortcut was created again when updating from 5.16.6 to 6.0.2. 🤷‍♂️

**Comment by blieque** [comment]
A shortcut was created for me a week or two ago. Can a setting not be added to disable the shortcut creation? Is it handled by the Electon updater?

**Comment by blieque** [comment]
*activity*

**Comment by mj-nico23** [comment]
Still happens...

**Comment by 4ekki** [comment]
still happens
