### ISSUE TITLE
[Bug] Latest Update v5.7.12 has stopped showing responses

### ISSUE THREAD

**Issue by zusamann** [getinsomnia/insomnia#441]
- Insomnia Version: 5.7.12
- Operating System: Windows 10 Pro

None of the requests are really working, once I click send the spinner keeps loading continuously without showing the response. Have tested 7-8 different requests, which btw are working fine on postman.

**Comment by gschier** [comment]
Hi @zusamann,

I've been trying to debug this for the past day. I'm not able to reproduce it consistently, so it's hard to know whether I'm experiencing the same issue. I've found that it goes away for me if I set an arbitrary timeout in the settings (something longer than the request will take like `5000`ms). 

Are you experiencing this with every domain, or just a subset? Also, can you confirm that it happens with both HTTPS and HTTP urls?

**Comment by zusamann** [comment]
Ok so when I try things on my local environment (which is obviously HTTP) things work fine. But for my dev (HTTP) and my production environment (HTTPS) the requests fail. I've tried with more than one domain, and it consistently fails for all of them.

So the only pattern I've had so far is, all of the localhost requests pass, all of the external requests fail. Hope that can help.

@gschier

**Comment by zusamann** [comment]
Also setting the timeout in the settings didn't help me, the request simply timed out when reaching that point. I gave it a high 30000ms just to be sure it would have enough time.

**Comment by gschier** [comment]
Hmm, okay. As a workaround, I've been told that 5.7.4 is the last release before this problem was introduced. You can download it here: https://github.com/getinsomnia/insomnia/releases/tag/v5.7.4

Just not, the app will try to auto-update itself. As long as you don't restart it, it will stay on the older version.

**Comment by zusamann** [comment]
Is there any way to stop the auto-update? I basically open/close insomnia at least a dozen times a day. If not, I'll try and change my habit.

**Comment by gschier** [comment]
I'm not sure how on Windows, but if you can block all requests to `updates.insomnia.rest` that would do it.

**Comment by gschier** [comment]
@zusamann can you quickly try this release to see if it works for you? https://github.com/getinsomnia/insomnia/releases/tag/test-6

**Comment by zusamann** [comment]
Checking @gschier

**Comment by zusamann** [comment]
BTW I've been facing issues with installers, I tried to install the previous versions when I first came across this bug. Facing the same issue with this one as well.

![image](https://user-images.githubusercontent.com/12589797/29380618-fa0cfea0-82e3-11e7-94b3-75d189eba21c.png)

Not sure if something has been corrupted at my end, I even tried uninstalling the previous version, and same error. And now I'm sitting with nothing :/

**Comment by gschier** [comment]
Ya, that happens if you try to install when Insomnia's already installed. I found that it works if you try it the second time.

**Comment by zusamann** [comment]
But I have uninstalled the previous version, and I'm still getting the same error. Are there any left behind things I need to clean up? If so where can I find them?

**Comment by gschier** [comment]
Everything related to the installation will be in `\Users\YourUser\AppData\Local\insomnia`. You can safely delete this entire folder. 

User data is stored in a separate location `\Users\YourUser\AppData\Roaming\insomnia`, which you should leave alone if you want your data to remain.

**Comment by zusamann** [comment]
I'm not able to delete those files, some weird access rights issue that I can't understand. Sorry will try again tomorrow and let you know.

**Comment by zusamann** [comment]
Ok so was able to delete the folders after a restart, and was able to install the new version 5.7.13, but getting the same issue. The only change I noticed was the countup of the number of seconds it's taking for the requests was no longer granular, just showing seconds and not milliseconds.

**Comment by gschier** [comment]
Thanks for testing that @zusamann. Can you also try https://github.com/getinsomnia/insomnia/releases/tag/test-8? That will be the last one for now.

**Comment by zusamann** [comment]
Ok checking it right now

**Comment by zusamann** [comment]
Issue still there, sorry. 😞 

BTW, I have a colleague who uses insomnia on linux, so I'll ask him tomorrow whether he's facing the same issue or not.

**Comment by gschier** [comment]
Ok, thanks @zusamann. In the meantime, I will keep looking.

**Comment by gschier** [comment]
Ok, I have another one @zusamann. https://github.com/getinsomnia/insomnia/releases/tag/test-9

**Comment by gschier** [comment]
Nvm, disregard that one.

**Comment by gschier** [comment]
@zusamann if you're still around, can you give this one a shot? With this version, I am unable to get the bug to happen again on my machine, so hopefully it will work for you as well:

https://github.com/getinsomnia/insomnia/releases/tag/test-13

**Comment by zusamann** [comment]
So I just tried this instead https://github.com/getinsomnia/insomnia/releases/tag/v5.7.14 and it worked! 🎉

**Comment by gschier** [comment]
Awesome! I was pretty confident I knew what the fix was, so I shipped the update before you confirmed. Glad it worked! 🍰
