### ISSUE TITLE
Auth config is not imported from Postman request

### ISSUE THREAD

**Issue by bertramakers** [getinsomnia/insomnia#4437]
### Expected Behavior

When importing a Postman v2.1 collection with auth config per request, Insomnia imports the auth config.

### Actual Behavior

As commented in https://github.com/Kong/insomnia/blob/develop/packages/insomnia-importers/src/importers/postman.ts#L476-L477 the auth config is not imported when OAuth2 is used, supposedly because Postman does not export it.

However a quick example demonstrates that Postman does in fact export the OAuth2 config:
```
{
	"info": {
		"_postman_id": "73945e9f-0b70-4cf9-aa89-640e807d4200",
		"name": "Example collection",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Example request with OAuth2",
			"request": {
				"auth": {
					"type": "oauth2",
					"oauth2": [
						{
							"key": "audience",
							"value": {
								"5545d202-0633-49d4-810e-83b74b51802e": "exampleAudience"
							},
							"type": "any"
						},
						{
							"key": "clientSecret",
							"value": "exampleClientSecret",
							"type": "string"
						},
						{
							"key": "clientId",
							"value": "exampleClientId",
							"type": "string"
						},
						{
							"key": "accessTokenUrl",
							"value": "exampleAccessTokenUrl",
							"type": "string"
						},
						{
							"key": "authUrl",
							"value": "exampleAuthorizeUrl",
							"type": "string"
						},
						{
							"key": "redirect_uri",
							"value": "exampleCallbackUrl",
							"type": "string"
						},
						{
							"key": "grant_type",
							"value": "authorization_code",
							"type": "string"
						},
						{
							"key": "tokenName",
							"value": "Access token",
							"type": "string"
						},
						{
							"key": "challengeAlgorithm",
							"value": "S256",
							"type": "string"
						},
						{
							"key": "addTokenTo",
							"value": "header",
							"type": "string"
						},
						{
							"key": "client_authentication",
							"value": "header",
							"type": "string"
						}
					]
				},
				"method": "GET",
				"header": []
			},
			"response": []
		}
	]
}
```

### Reproduction Steps

1. Import the example collection mentioned above
2. Go to the example request's auth tab
3. The auth type will automatically be set to OAuth2
4. There will be no OAuth2 configuration

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS 12.1

### Installation method

Download from insomnia.rest

**Comment by filfreire** [comment]
@bertramakers thank you for reporting this issue 🙇 

I did a quick experiment on #4440 with a workaround that would fix this specific case, but need to check first with the Insomnia team how to best "properly" solve this.

I suspect the main reasoning for the import to be empty at the moment is because we don't have any fixed rules on the postman schema itself regarding the config chunk. The fields exported by postman also obey different styles, so maybe are prone to changes/irregular.

**Comment by bertramakers** [comment]
Amazing, thanks for the quick fix! Do you think it would also be possible to add support for the audience parameter?
I can also try to help out myself but it seems like you've got a way better grasp of this than I do 😄 
I just noticed this because we have a script that converts OpenAPI 3.1.0 files into Postman collections and adds some things like OAuth2 config, and a member of our team who uses Insomnia noticed that it wasn't getting imported for him.
