### ISSUE TITLE
[Development] npm install issue

### ISSUE THREAD

**Issue by vellengs** [getinsomnia/insomnia#444]
It can't npm install success.

Tried to download(404): https://github.com/getinsomnia/node-libcurl/releases/download/v1.2.3/node_libcurl-v1.2.3-node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for insomnia-node-libcurl@1.2.3 and node@8.3.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/getinsomnia/node-libcurl/releases/download/v1.2.3/node_libcurl-v1.2.3-node-v57-darwin-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]

**Comment by gschier** [comment]
What is the error you get at the end of `npm install`? The 404 is not an error. I intentionally made it 404 so that it would force it to fall back to building from source.

**Comment by vellengs** [comment]
It's success install modules except the node_libcurl-v1.2.3-node-v57-darwin-x64.tar.gz request error.
After npm installed  I run 
> npm run dev 

Electron stay at screen "Waiting for build server. The initial build can take over a minute on slower hardware." 
error is debug tool
-------------------------------
ELECTRON_ASAR.js:173 Uncaught Error: The module '/Users/xxxxxx/workspace/example/insomnia/node_modules/insomnia-node-libcurl/lib/binding/node_libcurl.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

**Comment by vellengs** [comment]
I check the release list  of https://github.com/JCMais/node-libcurl/releases
there no exist one "node_libcurl-v1.2.3-node-v57-darwin-x64.tar.gz".
What's the node-v57 about?

**Comment by vellengs** [comment]
@gschier 
Thank you for your answer.
"What is the error you get at the end of npm install? The 404 is not an error, just a message. I intentionally made it 404 so that it would force it to fall back to building from source."
Do you mean the 404 , that's normal I can ignore, but after that npm run dev can not success yet.

**Comment by gschier** [comment]
It looks like you just need to run `npm run rebuild`. This will compile the native module for use in electron.

**Comment by vellengs** [comment]
@gschier 
It works. Thanks again.

**Comment by gschier** [comment]
Awesome! 😊
