### ISSUE TITLE
[Feature Request] Auto-select the current environment when opening the manage environments editor

### ISSUE THREAD

**Issue by meagerman** [getinsomnia/insomnia#445]
- Insomnia Version: 5.6.3.750
- Operating System: OSX

## Background

I build APIs and have an environment that mirrors our instance environments (test server, staging server, prod, etc). Each environment has the same fields, but different values for the field based on the environment (for usernames, password, key identifiers, etc). 

## Problem

I switch between these environments constantly, and sometimes need to change the environment variable values. WhenI hit cmd-e, I often make the mistake of changing the wrong environment (test instead of prod) because while prod is the environment I have currently active and am working with, the environment editor opens up the last environment I edited/selected, not the one active in the main window. 

## Feature Request

It would avoid many mistakes if the editor automatically selected the environment I am currently working in for editing.

**Comment by AlainPilon** [comment]
👍  I was about to create the exact same issue. My use case is identical to yours and I can't count the amount of time I waste because of this.

**Comment by gschier** [comment]
Seems like a good idea to me! 😀
