### ISSUE TITLE
Insomnia is unable to import OpenApi 3 with multiple API keys

### ISSUE THREAD

**Issue by mastazi** [getinsomnia/insomnia#4454]
### Expected Behavior

we have an OpanApi 3 collection with multiple API keys, as described at the following link under the paragraph "multiple API keys": https://swagger.io/docs/specification/authentication/api-keys/

When importing this, it is expected that the various endpoints will have both headers (in our case, `x-api-key` and `x-api-secret`).

Feeding the same OpenApi file to ReDoc, both authentication headers are correctly recognised:
<img width="359" alt="Screen Shot 2022-02-08 at 8 47 15 am" src="https://user-images.githubusercontent.com/1661655/152877541-aa319641-f38b-40b0-87b2-3207d21e0ef4.png">

### Actual Behavior

only `x-api-key` is present in the imported collection, while the header `x-api-secret` has to be created manually for each endpoint that is part of the collection.
<img width="453" alt="Screen Shot 2022-02-08 at 1 06 19 pm" src="https://user-images.githubusercontent.com/1661655/152904209-882ef215-c042-4bc9-9842-5851b2296332.png">

### Reproduction Steps

1. create an OpenApi JSON file with multiple keys as explained here https://swagger.io/docs/specification/authentication/api-keys/
2. import the file as a new collection in Insomnia
3. select one of the endpoints in the imported collection
4. open the request headers tab and verify that not all headers have been created

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.7.2

### What operating system are you using?

macOS

### Operating System Version

Reproduced on macOS, Win 10 and Win 11

### Installation method

download from Insomnia.rest

**Comment by filfreire** [comment]
Hello @mastazi thank you for reporting this!

We were able to reproduce this on our latest insomnia stream. We think we have found the place where the bug is happening. We'll try to keep you updated here asap.

Feel free to report other issues you come across!

**Comment by mastazi** [comment]
Thank you for the update @filfreire !

**Comment by filfreire** [comment]
Hi @mastazi, we found out the issue, turns out that for security keys that were defined as pairs, we would only consider the first. We should be able to include the fix in one of our upcoming betas.

You can read more about it in this PR: https://github.com/Kong/insomnia/pull/5047

**Comment by mastazi** [comment]
Amazing, thank yuo @filfreire !

**Comment by filfreire** [comment]
Hi @mastazi the fix I mentioned above is now part of our [latest beta release (2022.6.0-beta.1)](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.1). Feel free to report any other issues you come across!

**Comment by mastazi** [comment]
thank you @filfreire , I just downloaded it and tested I can confirm that the issue is resolved! I can see both keys where created for each endpoint! Thank you so much for the update.
