### ISSUE TITLE
Insomnia Plugin install error

### ISSUE THREAD

**Issue by adeludedperson** [getinsomnia/insomnia#4455]
### Expected Behavior

Install insomnia-plugin-extra-themes plugin

### Actual Behavior

Getting error while installing insomnia-plugin-extra-themes plugin

### Reproduction Steps

1. Go to 'Settings and plugings'
2. Search insomnia-plugin-extra-themes and click on install plugin

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Error I am Facing

![Screenshot_1](https://user-images.githubusercontent.com/83860384/152983646-feaea6e4-4c5c-4b44-81c3-ec18253c5d9f.png)

### Insomnia Version

2021.7.2

### What operating system are you using?

Windows

### Operating System Version

Windows_Nt x64 10.0.19043

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

It Never Worked

**Comment by filfreire** [comment]
Hi @ShaikRehan123 

Are you still able to reproduce this with [latest Insomnia release, 2022.3.0](https://github.com/Kong/insomnia/releases/tag/core%402022.3.0)?

I've tried to reproduce it, but can't so far:
<img width="807" alt="Screen Shot 2022-05-13 at 11 37 05" src="https://user-images.githubusercontent.com/11976836/168266828-4cf7d2b9-0e68-45d1-be90-4cfa93131505.png">
<img width="760" alt="Screen Shot 2022-05-13 at 11 37 54" src="https://user-images.githubusercontent.com/11976836/168266831-b5060ef7-1201-478a-b559-4f5f75395489.png">
