### ISSUE TITLE
Unable to authenticate Confidential Client with OAuth2

### ISSUE THREAD

**Issue by hugoaboud** [getinsomnia/insomnia#4479]
### Expected Behavior

When using `OAuth2` to grant authorization for a _Confidential Client_, the _Client Credentials_ `id:secret` should be sent to the provider through _Basic HTTP Auth_ header. There's also an option to send the credentials on the request body.

### Actual Behavior

- No `Authorization` header is found by the provider.
![insomnia_oauth1](https://user-images.githubusercontent.com/2349393/153562038-1b437e14-544f-4d4f-bb80-06bd029082aa.png)

- Also, when using the `In Request Body` option, the body received by the provider is empty.
![insomnia_oauth2](https://user-images.githubusercontent.com/2349393/153562170-a2d47eaa-f6ad-407a-b2f2-2138da564642.png)

Not directly related to the issue, but possibly helpful to identify the problem:
- No custom headers are received by the provider.
![insomnia_oauth4](https://user-images.githubusercontent.com/2349393/153562642-bd3f5bab-47b3-4b55-bee4-a74cae5c9f85.png)

- When an `Authorization` header is sent, with any value, it seems to skip OAuth2 flow and returns status 200 OK.
![insomnia_oauth3](https://user-images.githubusercontent.com/2349393/153562744-dfb5ef24-e099-449b-acd2-1d5f38447704.png)

### Reproduction Steps

1. Setup a debug OAuth2 provider
2. Register a confidential client with known `client_id` and `client_secret`
3. Configure a route to use OAuth2 authentication
4. Debug the headers received by the `Authorization Endpoint`

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I'm building a small OAuth2 provider for a distributed system, and I'm unable to test confidential clients with Insomnia. Public clients are working fine, the problem is about the `client_secret` not being sent to the provider.
I'm able to reproduce the authorization flow, even for confidential clients, using chained Requests but not with the OAuth2 option.

### Insomnia Version

2021.7.2

### What operating system are you using?

Other Linux

### Operating System Version

Debian 10

### Installation method

apt

**Comment by shlgd1xs** [comment]
您好，您的邮件我已收到！

**Comment by hugoaboud** [comment]
I'm closing this issue since there's no problem with Insomnia.

The `Authorization Endpoint` is not supposed to authorize the client, only the `Token Endpoint`, which is working just fine.
