### ISSUE TITLE
[Question] graphql schema

### ISSUE THREAD

**Issue by xinshangshangxin** [getinsomnia/insomnia#449]
- Insomnia Version:  5.7.11 (5.7.11.978)
- Operating System: mac 10.12.5 (16F73)

## Details

 when I used an environment variable for the host, it always show `Fetching schema`
if i write the host, it correct;
![image](https://user-images.githubusercontent.com/8779091/29495109-a94f896a-85ea-11e7-943a-cea3b3eb9323.png)

**Comment by xinshangshangxin** [comment]
I found a issue, but it closed
https://github.com/getinsomnia/insomnia/issues/425#issuecomment-322137835

**Comment by gschier** [comment]
@xinshangshangxin yes, this was fixed in #425 and released in https://insomnia.rest/changelog/5.7.12/
