### ISSUE TITLE
[Feature Request] Graphql auto complete

### ISSUE THREAD

**Issue by xinshangshangxin** [getinsomnia/insomnia#450]
- Insomnia Version: 5.7.11 (5.7.11.978)
- Operating System: mac 10.12.5 (16F73)

## Details

I want to like `graphiQL`, if I press `enter`, it will auto complete

![graphql-complete](https://user-images.githubusercontent.com/8779091/29495167-c8be0ee2-85eb-11e7-9d90-13945efedb19.gif)

**Comment by gschier** [comment]
@xinshangshangxin can you explain exactly what is happening here? Pressing `Enter` in the GraphiQL demo doesn't seem to yield the same behavior you describe: http://graphql.org/swapi-graphql/

**Comment by xinshangshangxin** [comment]
@gschier

**Comment by gschier** [comment]
Hmm, `cmd+Enter` seems to execute the current query for me.

**Comment by gschier** [comment]
Oh, I figured it out. `cmd+Enter` actually sends the query. The feature is listed in the GraphiQL README:

```js
      // GraphiQL automatically fills in leaf nodes when the query
      // does not provide them. Change this if your GraphQL Definitions
      // should behave differently than what's defined here:
      // (https://github.com/graphql/graphiql/blob/master/src/utility/fillLeafs.js#L75)
      getDefaultFieldNames: null
```

This looks like it might be quite a bit of work to implement. Are you interesting in trying to imlement this @xinshangshangxin?

**Comment by xinshangshangxin** [comment]
This is a challenge, I'll try, but not promise

**Comment by gschier** [comment]
Closing as stale.
