### ISSUE TITLE
Important: preview not working

### ISSUE THREAD

**Issue by hasan-4** [getinsomnia/insomnia#4522]
### Expected Behavior

The Visual Preview mode should render the html page.

### Actual Behavior

The Visual Preview mode does not render the html page.
the html page works fine in browser. but it does not work in Insomnia.

### Reproduction Steps

1. Install laravel 9.*
2. create an error
3. make a get or post request to an endpoint
4. you will see no error page in Visual Preview mode. But, in browser, you will see the error page nicely.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Insomnia preview mode was working nicely with laravel 8.*

### Insomnia Version

2022.1.0-beta.0

### What operating system are you using?

Ubuntu

### Operating System Version

Kubuntu 20.04 LTS

### Installation method

using .deb file

### Last Known Working Insomnia version
it does not work with latest stable version also.

### Relation
- [Laravel Issue 41266](https://github.com/laravel/framework/issues/41266)
- [Ignition Issue 64](https://github.com/spatie/laravel-ignition/issues/64)

**Comment by wdawson** [comment]
Hi @imithu this looks like perhaps an HTML issue with Laravel. For example, Insomnia's homepage renders correctly:

<img width="1934" alt="Screen Shot 2022-02-25 at 07 04 48" src="https://user-images.githubusercontent.com/132961/155738276-1f577272-01b5-4dca-8370-3a6529649590.png">

I wasn't able to test with Laravel to see exactly what is causing the problem, but I'd expect some kind of browser compatibility issue. Insomnia uses Electron, so it's Chromium-based.

**Comment by hasan-4** [comment]
I have created a live endpoint so that you can understand the issue.
```https://insomnia-open-source.imithu.org/api/test```
open this endpoint in,
- any latest browser
- insomnia

I hope, you have found the error.

**Comment by hasan-4** [comment]
# Modern Browser
![modern browser](https://user-images.githubusercontent.com/76824197/155878708-f44f2019-4960-43f2-b203-76410897222b.png)

# Insomnia
![insomnia](https://user-images.githubusercontent.com/76824197/155878710-a40f1e77-cd5b-41be-a52d-eb52f4a53133.png)


@wdawson good luck

**Comment by AlexVanderbist** [comment]
Hi Insomnia team! It looks like this is due to the use of `window.history.replaceState` on the rendered page. We'll remove fix in Ignition but here's the exact console error, should you want to investigate it yourselves:

```
DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://insomnia-open-source.imithu.org/api/test#F28' cannot be created in a document with origin 'null' and URL 'data:...'`
```

**Comment by imithu** [comment]
### Alhamdulillah (all the praises and thanks be to ALLAH)
Huge respect for fixing it quickly in 2022.1.0

**Comment by anyforever** [comment]
I have the same problem.

**Comment by ghost** [comment]
i experiencing same issue now

**Comment by voxcodes** [comment]
i experiencing same issue now

**Comment by abdes-zakari** [comment]
i experiencing same issue now

**Comment by pknaus3** [comment]
+1
