### ISSUE TITLE
URL Suggestion List Stays and Covers Up Screen Even After Focus Out

### ISSUE THREAD

**Issue by Vyoam** [getinsomnia/insomnia#4531]
### Expected Behavior

URL suggestion list seems to come up when one focuses on the url field (probably along with hitting send?). **Then, it should disappear once we click elsewhere**, but it stays stuck.

### Actual Behavior

URL suggestion list seems to come up when one focuses on the url field (probably along with hitting send?) It should disappear once we click elsewhere, but **it stays stuck**. (See the list with the 'c' icons)

![image](https://user-images.githubusercontent.com/1176140/155970702-aec08857-bc87-4277-8296-b8929d23be34.png)

### Reproduction Steps

Not fully sure...
1. Should have a 4-5 requests in collections (I have hundreds BTW).
2. Open a request, focus on the URL field, change something. Hit send.
3. Open another request and focus on the URL field. Hit send.
4. Repeat 2-3. At some point this issue will probably turn up.

Then the only way to remove the list is to select a suggestion (which will be unnecessary from actual usage perspective; hence you'd need to go to the URL field and clean it up)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2021.7.2
Release date: 12/10/2021
OS: Windows_NT x64 10.0.18363
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0-DEV OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.41.0

### Insomnia Version

2021.7.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 v1909 (Windows_NT x64 10.0.18363)

### Installation method

Downloaded frim insomnia.rest

### Last Known Working Insomnia version

Not sure

**Comment by SBlechmann** [comment]
I had this issue like for ever! Sometimes clicking somewhere else worked and somtimes I helped myself by just clicking some suggested URL and then I had to delete the pasted URL again.... but today I finally wanted to write an issue but you were faster ;-) 

For me, this even happens when my mouse is not even on the URL field. 

I'm using the same version although my release date is different?!

**Comment by Vyoam** [comment]
(Not quite related to this issue...) For my own note, there might also be a bug which silently changes the url of a previously selected request to the url of the current one... or something funky might be happening with the env vars. Will explore more later and file that too separately.

**Comment by Vyoam** [comment]
I think this issue is already being tracked here: https://github.com/Kong/insomnia/issues/2991

But it is closed currently. If they re-open that, I'll close this.

**Comment by inqueue** [comment]
The issue reproduces multiple times daily. Sometimes it goes away with a click, here or there, other times relaunching Insomnia is required.

Version: Insomnia 2022.4.2
Build date: 6/22/2022
OS: Darwin x64 21.6.0
Electron: 18.1.0
Node: 16.13.2
V8: 10.0.139.15-electron.0
Architecture: x64

<img width="628" alt="image" src="https://user-images.githubusercontent.com/6099128/181615603-c24b1700-a9e7-4157-a3a0-82d4212d27b4.png">

Configured are ~27 environments, each with a configuration looking something like:

```json
{
  "endpoint": "https://...",
  "username": "user...",
  "password": "pass...",
  "api_key": {
    "id": "some_id",
    "name": "api_key_name",
    "expiration": 1646495853828,
    "api_key": "ek..snipped..GcA",
    "authorization": "ApiKey dTlV..snippped...Q=="
  }
}
```

I would ❤️ to see this fixed and would be happy to provide any info needed that might help.

**Comment by hjbolide** [comment]
Any possibility this bug could be verified?

**Comment by filfreire** [comment]
Hi folks, this should have been fixed recently, please let us know if you can still reproduce this in tomorrow's beta.4 release.
