### ISSUE TITLE
Feature: Group Requests by Category when Importing from OpenApi Spec

### ISSUE THREAD

**Issue by BTripp1986** [getinsomnia/insomnia#4533]
redacted

**Comment by wdawson** [comment]
Thanks @BTripp1986 we'll leave this idea open in the Discussion but close this issue as a duplicate.

**Comment by BTripp1986** [comment]
.

**Comment by wdawson** [comment]
This is the discussion that you opened: https://github.com/Kong/insomnia/discussions/4528 We use Github Discussions for feature requests and ideas like this one, so that's the best place to follow up.

**Comment by BTripp1986** [comment]
.
