### ISSUE TITLE
[Improvement] Dynamic requests chaining

### ISSUE THREAD

**Issue by kakawait** [getinsomnia/insomnia#454]
- Insomnia Version: Version 5.7.14 (5.7.14.1021)
- Operating System: MacOS X 10.11.6

## Details

Requests chaining is working as expected but I would like to ask you a new feature about requests chaining. Today I have request `X` that needs a _token_ to be auth, this token is **one time usage** (unlike _OAuth2 access token_), I used requests chaining to retrieve this token from other request `Y` but since I need a new token for each request I have to call **manually** request `Y` always before `X`.

I would know if it's possible to say _request `X`_ is depending from other request (but not statically) thus when launching _request `X`_, _request `Y`_ should be replay.

Other solution (that does not create direct dependency between request) is a way to launch a _group_ of request (with order), that seems more generic feature and maybe simpler to develop.

**Comment by gschier** [comment]
Being able to send dependent requests automatically is planned to be part of request chaining eventually. I haven't decided yet if it's better to define this behavior as a parameter of the tag or do it externally with a new button for "sending with dependencies".

**Comment by robwasripped** [comment]
I too am looking forward to this. It will be fantastic for rudimentary tests of an API I'm creating, whereby I can test the full CRUD cycle of a resource be sending one request (eg: a DELETE that depends on a PATCH that depends on a GET that depends on a POST). I think having a simple option inside the tag to enable a new request each time would be best personally.

**Comment by gschier** [comment]
Thanks for your feedback on this @robwasripped

**Comment by SylwesterZarebski** [comment]
Note: this issue is similar to #286, but not the same.

**Comment by danielo515** [comment]
I really hate stale bots and all that stuff. This is a genuine feature request, that I would love to see implemented.
I need this, and I don't want the only issue to track it to be closed by a bot that has no idea about what is needed

**Comment by gschier** [comment]
I just forgot to tag it. It won't get closed now

**Comment by robinfla** [comment]
I'd love to see this feature as well. I'm chaining calls and one of them generates a Stripe card token, which is limited to one use only. Hence I can't use the response body attribute because the value is static.

**Comment by gschier** [comment]
Oh this is done actually https://github.com/getinsomnia/insomnia/pull/1470

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by robinfla** [comment]
My bad I didn't see that new feature. I updated my insomnia version to 6.4.2 and tried it out but it seems that the response body attributes doesn't get updated whereas I did use the "always - resend request when needed". 

I have a request where I need a stripe card token, so I used the response body attribute with the "always resend" option to get the token from another saved request to Stripe API. However, the token is always the same.

I'm sorry if I'm missing something here.

**Comment by gschier** [comment]
Thanks for the feedback. I will take a look and see if I can reproduce. You can also take a look at the request that's being referenced to ensure a new response has been triggered 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by robinfla** [comment]
Thanks! I've tried and checked the request that's been referenced and I can confirm no new response was triggered when I hit send on the request with the response body attribute.

**Comment by gschier** [comment]
Sorry about this. There was a small bug in the last release but it should be working now in 6.5.1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by robinfla** [comment]
Awesome, thanks! I've just tried it now and it works. This is gonna save me tons of time :)
