### ISSUE TITLE
[Improvement] Small unobstrusive visual indicator when an update is ready to be installed

### ISSUE THREAD

**Issue by sewalsh** [getinsomnia/insomnia#455]
I rarely shutdown Insomnia so there's always a chance I'm a few releases behind. Could a small indicator be added to the UI for when an update is downloaded and ready to be installed?

I think Insomnia may already hook into OS level alerts but I operate a sorched earth policy on taskbar notifications on Windows due to bad behaviour by (other!) developers/MS.

**Comment by gschier** [comment]
I think this is a problem even for those with working notifications since the notification dismisses after a short period of time. Seems like a good thing to add!
