### ISSUE TITLE
Template tag syntax in Basic Auth password fails to render template

### ISSUE THREAD

**Issue by oedo808** [getinsomnia/insomnia#4587]
### Expected Behavior

Using a randomly generated password that results in syntax similar to below should work:
`{%}`
Or in reality a password generated like this example:
`<R+v?gQ9tqOX?x1$TTs{%[%-ZS[^o}U1HnrG7Jwu-%whf5`

### Actual Behavior

Discovered by accident using a randomly generated password but it appears to be rendering the password value as a template tag name, with similar syntax to this [test](https://github.com/Kong/insomnia/blob/d6ea92e46dcf8886c75f192e7d45b2a5f50d7465/packages/insomnia-app/app/templating/__tests__/utils.test.ts#L116).
Tested and received the same in Windows 11 and macOS Big Sur 11.6
![image](https://user-images.githubusercontent.com/19806045/157891168-b3671323-c7f5-4ed2-9f8e-60832389cbe8.png)

### Reproduction Steps

1. Create a new GET request, or modify an existing one
2. Choose Basic Auth for authorization
3. Enter any URL, user, and a password with {%}, alone or inside an example password and send the request 
 
The important part of the password is {% with no space between (to match the tag template syntax I think) as it will result in the same error as long as there is a closing curly brace.  Sending a request without the closing curly brace results in `TypeError: Cannot read property 'type' of null`

![Insomnia_cYyGnthx1S](https://user-images.githubusercontent.com/19806045/157897284-f239b5f1-09b9-4261-9077-4cba0d6a4d76.gif)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6, Windows 11 22000.493

### Installation method

download from insomnia.rest

**Comment by kreosus** [comment]
Hi @oedo808,

Have you tried this on our newest release, available here: https://github.com/Kong/insomnia/releases/tag/core%402022.5.0?

**Comment by oedo808** [comment]
@kreosus, yes I have and it works.  Thanks!
