### ISSUE TITLE
[Improvement] Additional shortcuts: Switch between requests, new folder, delete request

### ISSUE THREAD

**Issue by mbedded** [getinsomnia/insomnia#459]
- Insomnia Version: 5.7.14
- Operating System: Mac OS X, Win 7, Win 8.1

## Details

Hello gschier,
there should be some additional shortcuts in Insomnia.

- CTRL-SHIFT-N: Create new folder
- DEL: Delete selected request
- CTRL-TAB: Cycle between requests

I have done some screenshots as example:

<img width="250" alt="shortcut_new_folder" src="https://user-images.githubusercontent.com/22235508/29708431-e4b71990-8988-11e7-9df9-27ccc523449e.png">
<img width="250" alt="shortcut delete request" src="https://user-images.githubusercontent.com/22235508/29708433-e62d06ea-8988-11e7-96ca-3351067b6e43.png">

I think ctrl-tab is self-explaining. Like any web browser there should be a easy way to cycle between requests. I think there should be two different modes:

- Cycle in order
- Cycle in last used order

Let me explain this on the following request order:

- Req A
- Req B
- Req C
  
Cycle in order with ctrl-tab is always A -> B -> C -> A -> B -> C ..
Cycle in last used order means, that the order depends on last open tab. If my access order is A (1), C (2), B (3) a ctrl-tab pressed once switches always between A and C (last used ones). When ctrl-button is held and we press tab twice we should swap from A -> B. When we press ctrl-tab once again we go from B -> A. The last used one have changed.

I think there should be an option to switch between "order" and "last used". I love last used order but i guess some people will hate it.

Furthermore we should discuss, how this feature should work within different folders. Will the order be "global" or is it depending on the current folder? So just the current ones are working? I don't know which makes more sense.
Currently i am using a workspace for my project and one folder for one controller. Mostly there is no overlapping between these so i can test them separately. Other users may have overlapping requests or collect a special user-story within one folder.

What do you think? I think the "normal" features like new folder and delete should be clear (compared to other applications). CTRL-Tab is worth a discussion i guess. I don't know how much effort it is to implement new shortcuts.

**Comment by multirealm** [comment]
Hi together, 

I also support more shortcuts in Insomnia. But I would not recommend to set only one key (Del) to delete a selected request. This could lead to too many unintentional deletions. And this could not even be reversed at the moment. I would suggest at least something like Cmd - Del (like deletion of files in Mac Finder).

In addition the following shortcuts would be highly appreciated:

- Open active Environment List: Cmd-Shift-E 
- Quick change environment: Cmd-1, Cmd-2, etc.
- Input Filter: Cmd-F

**Comment by gschier** [comment]
Closing this now, as most were implemented in #487
