### ISSUE TITLE
[Question] Keyboard shortcut to delete request

### ISSUE THREAD

**Issue by mbedded** [getinsomnia/insomnia#460]
- Insomnia Version: 5.7.14
- Operating System: Mac OS X, Win 7, Win 8.1

## Details

Hi gschier,

is there an plan, to disable the "delete request by double check" by options or bypass it by shortcut (see: #459 )?

For clarification see the following screenshot: 
<img width="237" alt="shortcut_delete_confirmation" src="https://user-images.githubusercontent.com/22235508/29708570-58fab99c-8989-11e7-98d3-2d551fbb31f8.png">

We do the following steps: Request -> Rigt mouse -> Delete -> Confirm
I work with Mac and Windows and there is a possibility to delete files or folder without any confirmation. I would like to bypass the double check via program settings or shortcut.

A interruption like DEL (shortcut) -> Confirmation window -> Return (to press OK) would be ok, too. I am mostly using shortcuts instead of mouse-clicks.

Just an spontaneous idea:
What is a about a trash bin? All deleted requests could moved there so users which are miss-clicking could restore the items without any hassle.

**Comment by gschier** [comment]
I don't think there is enough reason to remove this feature, but a keyboard shortcut and trash/archive seem like good ideas. A keyboard shortcut is easy, so I'll add that to the list.

**Comment by gschier** [comment]
@mbedded are you interested in submitting a PR for this?

**Comment by mbedded** [comment]
Sorry @gschier, i read your comment just today. I guess i could do some PRs in the future but i haven't worked with Electron before. Next time i will try to do some changes :)

**Comment by gschier** [comment]
No worries, this was an easy one anyway. It's just usually faster if someone else does the lower-priority things since I usually don't have much time.
