### ISSUE TITLE
0 OK but Response null

### ISSUE THREAD

**Issue by mrpphein** [getinsomnia/insomnia#4608]
### Expected Behavior

"message" : "hello"

### Actual Behavior

null

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

It's ok and working at BloomRPC and grpcurl command-line but not ok at Insomnia

### Insomnia Version

v2202.2.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux pop-os 5.15.23-76051523-generic #202202110435~1644952300~21.10~96763f1 SMP Tue Feb 15 19:52:40 U x86_64 x86_64 x86_64 GNU/Linux

### Installation method

apt

**Comment by filfreire** [comment]
@mrpph can you share more information about the code/ proto file you are using? (and if possible screenshots/video)

I've been trying with the example I have [here](https://github.com/filfreire/grpc-example-python), and I'm able to see the response status code and response body correctly:

- On MacOS:
![Screenshot 2022-03-18 at 12 39 56](https://user-images.githubusercontent.com/11976836/159004673-1f888785-a9da-4ab9-9ff9-b3912e38c806.png)

- On Linux (Ubuntu 20.04):
![Screenshot 2022-03-18 at 12 48 36](https://user-images.githubusercontent.com/11976836/159005790-dd26b877-dd2c-4e39-bc94-4d03a10abf49.png)
