### ISSUE TITLE
First request took very long?

### ISSUE THREAD

**Issue by annie-redso** [getinsomnia/insomnia#4612]
### Expected Behavior

I am testing an API and the procedure is:
1. get token from POST request A
2. get json from POST request B with the token returned by POST request A

When I call POST request B, the first trial should perform as similarly as the other trials i.e. second one, third one, ...

### Actual Behavior

Below is the history of POST request B I called. Note that the first attempt took 35.6s and the later one were fast. I then stopped calling for a while and restarted, the first attempt took 37s. Later ones were fast. Stopped calling for while and restarted, the first attempt took 35.8s.

<img width="443" alt="Untitled 3" src="https://user-images.githubusercontent.com/63767886/159103033-9a69ba2f-d25d-455d-ba6c-05a2b6889ebc.png">

At first I thought it must be the API's problem because I have never encountered such problem with Insomina before and the performance of calling POST request A was consistent.

But then I tried using Postman to call POST Request B and found no such issue. I tried to start the POST request B with Postman and then Insomnia and the result is, Postman got the response pretty quick while Insomina stuck in the loading screen and got the response after dozens of seconds just like the behaviour I described above.

Here is one of the Timeline info of the very long POST request B (sensitive information is masked):
```
* Preparing request to https://xxx
* Current time is 2022-03-19T01:56:38.484Z
* Using libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0
* Using default HTTP version
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 3 cookies
* Too old connection (129 seconds), disconnect it
* Connection 62 seems to be dead!
* Closing connection 62
* TLSv1.2 (OUT), TLS alert, close notify (256):
* Hostname in DNS cache was stale, zapped
*   Trying xxx:443...
* Connected to xxx.com (xxx) port 443 (#63)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /var/folders/d3/k2by8htd2fl9b5bfs0hn46z40000gn/T/insomnia_2021.7.2/ca-certs.pem
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; CN=*.xxx.com
*  start date: Jul  8 04:51:09 2020 GMT
*  expire date: Jul  8 04:51:09 2022 GMT
*  subjectAltName: host "xxx.com" matched cert's "*.xxx.com"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7ffb460b4e00)

> POST /xxx HTTP/2
> Host: xxx.com
> user-agent: insomnia/2021.7.2
> cookie: xxx=yyy
> content-type: application/json
> authorization: Bearer xxx
> accept: */*
> content-length: 39

* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!

| {
| 	"xxx": "yyy"
| }

* We are completely uploaded and fine

< HTTP/2 200 
< date: Sat, 19 Mar 2022 01:57:21 GMT
< content-type: application/json; charset=utf-8
< content-length: 452
< cache-control: No-Cache
< pragma: no-cache
< expires: -1
< x-xxx-request-id: yyy

* Replaced cookie xxx="yyy" for domain xxx.com, path /, expire 0

< set-cookie: xxx=yyy;Path=/


* Received 452 B chunk
* Connection #63 to host xxx.com left intact
* Saved 1 cookie
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.7.2

### What operating system are you using?

macOS

### Operating System Version

Catalina 10.15.6 (19G2021)

### Installation method

https://insomnia.rest/download

**Comment by filfreire** [comment]
@annie-redso can you confirm if you notice the same behaviour with [latest Insomnia version, `2022.2.1`](https://github.com/Kong/insomnia/releases/tag/core%402022.2.1)?

**Comment by filfreire** [comment]
@annie-redso I'm going to close this issue in favor of #5010 which has a bit more in-deep details of how to reproduce consistently this problem.

Thank you for reporting this one, and feel free to report any issues you find in the meantime!
