### ISSUE TITLE
Hide menu bar has stopped working in 2022.2.0

### ISSUE THREAD

**Issue by darcyrush** [getinsomnia/insomnia#4617]
### Expected Behavior

Menu should not show.

### Actual Behavior

Menu shows.

### Reproduction Steps

![image](https://user-images.githubusercontent.com/22768040/159273001-c78e0d5f-bf62-4741-9a5f-681a04a77e9f.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Previous issue; https://github.com/Kong/insomnia/issues/3952
![image](https://user-images.githubusercontent.com/22768040/159273388-06c79c79-0b2a-41bb-8c30-2c09850b916e.png)

### Insomnia Version

2022.2.0

### What operating system are you using?

Ubuntu

### Operating System Version

Linux M720q 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

apt

**Comment by filfreire** [comment]
Hi @darcyrush, thank you for reporting this!

Indeed we missed this regression on 2022.2.0, sorry for that 🙇 

We have prepared a hotfix for this regression already (see https://github.com/Kong/insomnia/pull/4609) and it should be available in an upcoming patch soon.

**Comment by filfreire** [comment]
@darcyrush  - small update, the fix for this regression is included in the [next `2022.2.1` minor patch release](https://github.com/Kong/insomnia/pull/4619). It should be officially published later today.

**Comment by darcyrush** [comment]
@filfreire I can confirm the fix is working in 2022.2.1 on Ubuntu after updating via apt, thank you for the rapid fix!
