### ISSUE TITLE
[BUG] URLs in results panel do not parse special characters

### ISSUE THREAD

**Issue by brennanpayne** [getinsomnia/insomnia#462]
- Insomnia Version: 5.7.14.1021
- Operating System: MacOS 10.12.6 (Sierra)

## Details

The url parsing for JSON responses does not respect special characters.

E.g. I have a JSON response that returns: 
```
{
  "url": "http://catalog.lee.edu/#Declaración_de_Igualdad_en_la_Educación"
}
```

The results pane looks like:
<img width="518" alt="screen shot 2017-08-25 at 11 08 33 am" src="https://user-images.githubusercontent.com/1245874/29722438-64d53df8-8986-11e7-9070-b2dcf3597b52.png">

The link is only parsed out to the `ó` and when clicking results in taking me to `http://catalog.lee.edu/#Declaraci`

Let me know if I can clarify anything.

**Comment by gschier** [comment]
I just made the URL regex a bit more flexible, but it's still not perfect.
