### ISSUE TITLE
Error while pulling collection: Modal was not registered with the app

### ISSUE THREAD

**Issue by NiciusB** [getinsomnia/insomnia#4637]
### Expected Behavior

When Pulling a Collection, it should work correctly.

### Actual Behavior

The following error shows, and the collection is not pulled:
![image](https://user-images.githubusercontent.com/2421121/159925656-dea6473c-772c-46e3-b44f-36cd5563a77c.png)

I tried more times and now it just keeps spinning but doesn't work

### Reproduction Steps

1. Have a collection
2. Be unable to pull or push, for some unknown error
3. Delete collection
4. Try to pull collection again

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Team id: team_4f09017da485413f8d62e849b64d8b71
Collection: Payment Gateways

I had been unable to pull or push to that collection for some months now. I only now tried this to fix it.
Other collections work well

### Insomnia Version

2022.2.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterrey 12.3

### Installation method

Download from insomnia.rest

**Comment by DMarby** [comment]
Hi @NiciusB,

Sorry about the trouble this is causing, please send an email to support@insomnia.rest, and we'll be able to better assist you.

**Comment by NiciusB** [comment]
Will do!

**Comment by DanielSoCra** [comment]
We are having the same problem

**Comment by DanielSoCra** [comment]
We are having the same problem

**Comment by NiciusB** [comment]
@DanielSoCra we ended up contacting their support email, and fixed it by deleting the collection from my insomnia data directory
