### ISSUE TITLE
SessionStorage read error when loading an html page request in visual preview

### ISSUE THREAD

**Issue by daviidmart** [getinsomnia/insomnia#4638]
### Expected Behavior

I cant start insomnia now

![image](https://user-images.githubusercontent.com/10666050/159965116-6a474ffe-f422-4daf-9a6a-4f14e6d2caa8.png)

### Actual Behavior

When I start insomnia it gets stuck and doesn't let me do anything, I only get the following error

### Reproduction Steps

I just start the program and it gives me the error

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 21H2

### Installation method

Download from insomnia rest

### Last Known Working Insomnia version

2022.2.1

**Comment by filfreire** [comment]
Hi @daviidmart, thank you for reporting this issue!

We have managed to reproduce the problem when we use the exact same request you show on your screenshot:

![Screenshot 2022-03-24 at 17 30 23](https://user-images.githubusercontent.com/11976836/159978318-dc9a081d-0469-4154-b00a-e630789bcfe2.png)

Seems the page has some JS that is trying to access Insomnia's localStorage, causing the error. 


When possible, we will be looking into this, but we don't have a fix ready just yet - Note: the page uses local storage, which officially is not supported in Insomnia.

In the meantime and to unblock you @daviidmart, you can do the following:

- Shut down the app (if necessary terminate it using Windows Task Manager), and delete the `responses` folder from AppData (example: `C:\Users\<YourUsername>\AppData\Roaming\Insomnia\responses`)
- Before you send the request, select `Source Code` or `Raw Data` in the Preview mode, and you should no longer get the error:

![Screenshot 2022-03-24 at 17 59 46](https://user-images.githubusercontent.com/11976836/159980653-95572304-e472-4113-a5a7-dbe18ad0797a.png)

**Comment by filfreire** [comment]
Note for @Kong/team-insomnia  - this is reproducible not only on Windows but also on other OSs.

**Comment by DMarby** [comment]
Hi @daviidmart, 

Thank you for reporting this, a fix for the app getting stuck in a loop with error dialogs will be included in the next release.
Unfortunately we are not able to support interacting with localStorage in the response viewer currently.
