### ISSUE TITLE
Insomnia has become unresponsive open api specs 3

### ISSUE THREAD

**Issue by AmmarHassan1** [getinsomnia/insomnia#4653]
### Expected Behavior

Load Specs design document properly.

### Actual Behavior

Showing an error of Insomnia has become unresponsive, and there is no way i can remove this import from my workspace. 

### Reproduction Steps

1. Goto Settings > Data > Import data > From File
2. Open API spec with some error in specification and it has to be large. 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2022.2.1
Release date: 22/03/2022
OS: Windows_NT x64 10.0.19043
Electron: 17.1.0
Node: 16.13.0
V8: 9.8.177.11-electron.0
Architecture: x64

### Insomnia Version

2022.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.19043

### Installation method

download from insomnia.rest

**Comment by relief-melone** [comment]
having the same issues. Portable as well as Core on windows (20H2 Build 19042.1586) affected.

Is there a version that does not show this behaviour to scale down to while this bug is beeing addressed?

**Comment by s0l4r** [comment]
I have the same issue with a large OpenAPI spec with ~4000 lines. Unfortunately I cannot paste the schema, it's an internal API.

I also tried the latest beta.

**Not Working**
Version: Insomnia 2022.2.1
Release date: 3/21/2022
OS: Darwin x64 20.6.0
Electron: 17.1.0
Node: 16.13.0
V8: 9.8.177.11-electron.0
Architecture: x64

Version: Insomnia 2022.3.0-beta.2
Build date: 3/31/2022
OS: Darwin x64 20.6.0
Electron: 17.3.0
Node: 16.13.0
V8: 9.8.177.13-electron.0
Architecture: x64

**Working**
Version: Insomnia 2022.1.1
Release date: 09/03/2022
OS: Darwin x64 20.6.0
Electron: 12.2.3
Node: 14.16.0
V8: 8.9.255.25-electron.0
Architecture: x64
node-libcurl: libcurl/7.79.1 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.10.0 nghttp2/1.41.0 OpenLDAP/2.4.47

If it works for you, don't forget to disable auto updates.

**Comment by nelsonjchen** [comment]
I'm trying to load a variant of this API:

https://github.com/Telecominfraproject/wlan-cloud-services/blob/master/portal-services/src/main/resources/portal-services-openapi.yaml

I think I got @s0l4r beat at 11k. And the example is public, so hopefully that helps. If I use the Design view, Insomnia is bricked until I remove all the Insomnia Preferences/settings/data folder. That's obviously crazy destructive.

**Comment by nelsonjchen** [comment]
FWIW, Postman loads it fine, abet really not fast as usual. It doesn't choke on it, die, or brick.

**Comment by maxshearer** [comment]
Struggling here too...

Version: Insomnia 2022.2.1
Release date: 3/21/2022
OS: Darwin arm64 21.3.0
Electron: 17.1.0
Node: 16.13.0
V8: 9.8.177.11-electron.0
Architecture: arm64

Also had no issues on 2022.1.1

Falling way behind @s0l4r and @nelsonjchen at a tiny 2400 lines. Amateur numbers over here...

**Comment by MrStanDu33** [comment]
Same here,

Running Insomnia 2022.3.0 on w11

It started to slow down when I was near 1000 lines, but now I'm reachin 4.3k lines, and it's taking something like 50s every few characters typed, and prompt me if I want to kill insomnia like 2 or 3 times per freeze

Had to code my spec on my IDE and then paste it in Insomnia 😒

EDIT: tried with Insomnia 2022.4.0-beta.0, same behavior

**Comment by m-gericke** [comment]
Same issue here.

At roughly 3900 lines Insomnia is entirely unusable on version 2022.3.0. This did *not* happen in Insomnia Designer 2020.5.2, I installed it again just to make sure and it's completely fine.

**Comment by james-world** [comment]
Same issue here. Insomnia is unresponsive and unusable importing a 10899 line open api spec into 2022.4.0 on windows 11.

Working fine on portable win11:

Version: Insomnia 2022.1.0
Release date: 3/1/2022
OS: Windows_NT x64 10.0.22000
Electron: 12.2.3
Node: 14.16.0
V8: 8.9.255.25-electron.0
Architecture: x64
node-libcurl: libcurl/7.79.1-DEV OpenSSL/3.0.0 zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.45.1

**Comment by m-gericke** [comment]
@james-world ~~Can confirm that performance is MUCH, MUCH better in the portable version.
Thanks for the workaround, I didn't even consider that.~~

Correction: Even non-portable works fine on 2022.4.0 for me, I simply hadn't updated to it before trying the portable edition.

**Comment by james-world** [comment]
Hmmm. I've just tried portable 20222.4.0 and it was fine too. Weird. I did completely uninstall 2022.4.0 and delete the insomnia folders in AppData Local and Roaming before trying 2022.1.0 portable. Guessing, but perhaps there was a compatibility issue with data created by an earlier version?

**Comment by johngeorgewright** [comment]
I _think_ this is related. I just tried to load the GitHub OpenAPI into insomnia and it began to hang.

https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.json

Version: Insomnia 8.5.1
Build date: 12/21/2023
OS: Darwin x64 21.6.0
Electron: 28.0.0
Node: 18.18.2
Node ABI: 119
V8: 12.0.267.8-electron.0
Architecture: x64

**Comment by vmachacek** [comment]
same here

**Comment by subnetmarco** [comment]
We are actively working to solve this issue, stay tuned.

**Comment by CurryYangxx** [comment]
We optimized for this in version 9.2, now file opening and editing are now faster
