### ISSUE TITLE
[Feature] properly render html responses even if request should be `application/json`

### ISSUE THREAD

**Issue by autoferrit** [getinsomnia/insomnia#466]
Doing this, can in many cases, help show properly formatted output when using php and enabling html errors. I presume there is similar use cases in other languages too.

**Comment by gschier** [comment]
Done! Nice idea @autoferrit  😄

**Comment by autoferrit** [comment]
Hmm, i looked at the PR. most of the time in my experience, especially error html from php, there is no `<!doctype html>` element. it just has html elements. in this one im looking at now, the body starts with

```html
<divstyle="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;"><h4>APHPErrorwasencountered</h4><p>Severity: Warning</p><p>Message: usort()
```
So maybe it would be best to just test if there is a few given elements? You might be able to test if the following is in the document
`<div`
`Line:`
`LineNumber:`
`error`
`Exception:`
`Filename:`

either some or all or a combination. I just tried with the new update that had this PR merged in, and it did not render the html. If anything, the first character of the response will probably always be a `<` character for an opening html bracket.

**Comment by autoferrit** [comment]
@gschier not sure if you saw the above or not since this was closed.

**Comment by gschier** [comment]
Hmm. Checking for an opening bracket in the case of json will probably work since this is impossible for json. However, that check may not work for other, more flexible, content types.

Maybe there should be a user-configurable way to add rules

**Comment by autoferrit** [comment]
maybe check for that opening bracket, then if so, check for some other keywords to make sure like above. check for some possible elements like div, error, exception, in those cases, its likely an error
