### ISSUE TITLE
Timout Setting in milliseconds not seconds. Wrong description

### ISSUE THREAD

**Issue by lucasra1** [getinsomnia/insomnia#4666]
### Expected Behavior

Request timout setting should be in seconds and not ms.

### Actual Behavior

Request timout setting seems to be in ms. Although descriptions states seconds

### Reproduction Steps

Request Timout setting is set to "60". Description states, that this is in seconds. 
Make request longer than 60ms. Get timeout. set to setting to"600". Get no timout. (request took 250ms).

also tried to set the setting to "6" which should still be seconds and got a timout after 6ms. So either the description is wrong or the implementation

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

Zorin OS 16.1

### Installation method

flatpak

**Comment by d4rkd0s** [comment]
Same issue,

<img width="341" alt="image" src="https://user-images.githubusercontent.com/2348814/167681025-b3a400c9-7bd4-4dd7-b21b-2ace13c8d52e.png">

Timed out after ~10ms 

<img width="292" alt="image" src="https://user-images.githubusercontent.com/2348814/167681083-7a06ae12-bd8f-47db-8ec9-45eca5fa8028.png">

I'm on Mac OS 12.3 using Insomnia:

```
Version: Insomnia 2022.2.0
Release date: 3/17/2022
OS: Darwin arm64 21.4.0
Electron: 17.1.0
Node: 16.13.0
V8: 9.8.177.11-electron.0
Architecture: arm64
```

**Comment by filfreire** [comment]
Hi @lucasra1, thank you for reporting this!

I can reproduce this as well on latest stable Insomnia (2022.3.0).

![Screenshot 2022-05-16 at 10 37 57](https://user-images.githubusercontent.com/11976836/168564291-12c8b626-50c0-4b35-8f29-4d43aa119be2.png)
![Screenshot 2022-05-16 at 10 37 49](https://user-images.githubusercontent.com/11976836/168564292-2c773c15-fe7b-46a6-b3c6-b1dc450ced3c.png)

We'll update here if there's any changes or fixes.
