### ISSUE TITLE
Subscribe to plan's team size has overflow problem

### ISSUE THREAD

**Issue by jvfd3** [getinsomnia/insomnia#4674]
### Expected Behavior

Not being able to insert a value bigger than 500 in the field.

### Actual Behavior

In the Team Size on the (Subscribe to Plan)[https://app.insomnia.rest/app/subscribe/] webpage, when you insert a large enough number, a overflow happens:
<details><summary> 10^310 </summary>

![image](https://user-images.githubusercontent.com/10092672/161828530-3d5268fa-25eb-4614-9ea2-f986d9bcc52a.png)

</details>
<details><summary> 10^309 </summary>

![image](https://user-images.githubusercontent.com/10092672/161828622-1e32d176-77d7-4c1b-80ad-e6b50d97bd32.png)

</details>
<details><summary> 10^307 </summary>

![image](https://user-images.githubusercontent.com/10092672/161828704-720dd005-e3cc-4f03-a29c-0182da674a06.png)

</details>

When you try to proceed it gives you this alert:

<details><summary> 10^310 </summary>

![image](https://user-images.githubusercontent.com/10092672/161828868-dc3f4d0f-8ef5-4422-abca-3d0d07319fb7.png)

</details>

<details><summary> 10^309 </summary>

![image](https://user-images.githubusercontent.com/10092672/161828957-69145c23-4d8e-43b4-9645-84ab08b55e58.png)

</details>

### Reproduction Steps

1. Go to the (Subscribe to Plan website)[https://app.insomnia.rest/app/subscribe/]
2. Insert a big quantity of nines.
3. Voilá

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.2.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### Installation method

sudo apt-get install insomnia

### Last Known Working Insomnia version

2022.2.1

**Comment by filfreire** [comment]
@jvfd3 thank you for reporting this issue, and thank you for using Insomnia!

_Surely there are no companies with a workforce bigger than 500 people..._ 😅 

This is a good catch, albeit it's safe to say we will likely not support anything larger than a quadrilion/biliard users ( 10^15 ) anytime soon... save for the cases where we join a Galactic Republic or machines become sentient and replicate exponentially.

I suspect the hard limit of 500 is likely to mimic what most companies do of "_Need more than 500 users? Reach out to our sales team._", but we missing that kind option from the website, which is a problem. We'll need to forward this to our colleagues in Marketing team. Tagging @wdawson.

**Comment by filfreire** [comment]
@jvfd3 I'm going to close this one and reopen it internally, as this is in a part of insomnia repositories that are not public.

Feel free to report any other issues you come across.

@Kong/team-insomnia reopened this one as https://linear.app/insomnia/issue/INS-1686/add-limit-to-team-subscription
