### ISSUE TITLE
Crash when attempting to authorize user with OAuth2 implicit flow (ID and Access Token)

### ISSUE THREAD

**Issue by val1984** [getinsomnia/insomnia#4676]
### Expected Behavior

Insomnia presents me with a popup where I am able to login with my auth provider.

### Actual Behavior

Insomnia crashes shortly after displaying the popup.

### Reproduction Steps

1. Setup a new request with the following parameters:
   - Auth: Oauth2
   - Grant type: Implicit
   - Advanced Options:
       - Response type: ID and Access Token
2. Click Send
3. Authentication popup appears and Insomnia crashes

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

[2022-04-06 15:55:16.829] [info]  [oauth2] will-redirect: Ignoring URL "<oauthurl>". Didn't match /(access_token=|id_token=)/
[2022-04-06 15:55:16.876] [info]  [oauth2] did-navigate: Ignoring URL <oauthurl>". Didn't match /(access_token=|id_token=)/
[2022-04-06 15:55:20.260] [error] Error occurred in handler for 'authorizeUserInWindow': Error: ERR_ABORTED (-3) loading <oauthurl>
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.navigationListener (node:electron/js2c/browser_init:161:7953)
    at EventEmitter.emit (node:events:390:28)

### Insomnia Version

2022.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise version 1909

### Installation method

scoop (download from website exhibits the same issue)

### Last Known Working Insomnia version

2021.7.2

**Comment by dimitropoulos** [comment]
I tried and was unable to reproduce this.  I'm using https://github.com/schrodingersket/keycloak-oauth2-ssl-testbed as a testbed.  Is there any more information you can provide on a reproducible setup to trigger this bug?

Also, want to apologize that it took 9 days to respond on this.  We've been really deep into some back-of-house technical work lately and haven't had much chance to pop our heads up to attend to serious issues like the one you raise here.

**Comment by dimitropoulos** [comment]
hey! to anyone interested: we're going to be looking at this tomorrow on the stream, Tuesday April 19th at 10:30am-11:30am Eastern, which is 2:30pm-3:30pm UTC.

Join us on the `#stream` channel over on the Insomnia community slack: [https://chat.insomnia.rest](https://chat.insomnia.rest).  @val1984 if you're at all able, it could be really helpful if you're able to come on the stream and demonstrate to us how the failure looks since we're having trouble reproducing it.  If not: no worries, we'll try!

**Comment by Horsty80** [comment]
Hi, any news on this ? 
Maybe it's dupplicate with https://github.com/Kong/insomnia/issues/4259  ?

**Comment by dimitropoulos** [comment]
We just took another look at this on the Insomnia stream today.  While we were not able to reproduce it exactly, we were able to show that you can crash the app like is being described here by killing the port that the app uses for communication between the render thread and electron's main thread.

Until we know more, I'm not sure what we can do going forward to debug this.

**Comment by val1984** [comment]
Hello,

I decided to check if this issue was still present in the latest version of Insomnia and I'm happy to report that it is no longer occurring 🙂
