### ISSUE TITLE
[Bug] Insomnia GraphQL preview jumps in position on mouse click

### ISSUE THREAD

**Issue by tomelm** [getinsomnia/insomnia#469]
- Insomnia Version: 5.7.14.1021
- Operating System: macOS Sierra 10.12.16

## Details

It looks like when you have GraphQL body selected (I haven't tested other types) and the body extends the size of the screen (so that the scroll bar appears), if you you mouse click on certain lines it causes the body to automatically jump around instead of just keeping the location as is. It's making editing large queries pretty hard/annoying as things continuously move all over the place. Attaching a recording of this in action.

![insomnia_jumping](https://user-images.githubusercontent.com/153050/30073709-a79161d0-9223-11e7-972c-36f820db4bb7.gif)

**Comment by gschier** [comment]
Thanks for reporting this @tomelm. I've reproduced this and I'm working on a fix now.
