### ISSUE TITLE
[Bug or Question] Insomnia Helper memory leak?

### ISSUE THREAD

**Issue by TakesTheBiscuit** [getinsomnia/insomnia#470]
Question/Maybe a bug

- Insomnia Version: `5.7.4 (5.7.4.933)`
- Operating System: `macOS Sierra 10.12.1 (16B2555)`
- Machine: `MacBook Pro (Retina, 13-inch, Mid 2014) 8GB DDR3 RAM`

## Details

Machine was running like a total dog, opened activity monitor, looked and sorted by memory usage, there was a process called `Insomnia Helper` which was consuming 1.5GB of memory.

My machine background:
I open the lid around 8am, close the lid around 6pm and do the same every day of the week - i never really shutdown, so it's in a constant in-out of sleep cycle. I never close insomnia, it lives with me in my daily workflow. Therefore i'd like to suggest this increase in memory usage/leak could be very small but the overall impact was rather large.

I closed insomnia and killed insomnia helper, which freed the memory, i reopened it before writing this issue.

This is therefore not so much of a bug report as a question; what is insomnia helper, why would it be allowed to climb up to 1.5GB of RAM? Can anything be done to stop that in future?

Since writing this issue (about 5minutes of my time) it's climbed from 134.0 to 135.1MB, i've got insomnia totally minimised and haven't touched it apart from dismissing the 'whats new' dialogue.

Since i reopened it i'm on `Version 5.7.4 (5.7.4.933)` so it seems the issue is present right now.

**Not urgent, not a deal breaker.**

**Comment by gschier** [comment]
Is this still an ongoing issue @TakesTheBiscuit? There haven't been many complaints and I can't reproduce it on my end to that magnitude. 

If so, can you include the output to the following command? 

```
ls -lh ~/Library/Application\ Support/Insomnia/insomnia.*
```

I have a feeling this issue could be amplified by larger-than-average database files.

**Comment by TakesTheBiscuit** [comment]
I think it's fair to say i've not encountered the exact same issue lately but on an average day it looks like 286MB Compressed memory in use -- if this is all database i'd be happy to kill some of my workspaces.
I have approx 15 workspaces each with between 30-40 requests in each, with a mix of folders and loose requests.

I think you should probably close this issue, but i am confident in my original report of high mem usage 1.5GB - damn gremlins! hope it doesn't come back
