### ISSUE TITLE
[Bug] No user interface after executing in root

### ISSUE THREAD

**Issue by maletil** [getinsomnia/insomnia#471]
- Insomnia Version: 5.7.11/14
- Operating System: Linux Mint 18.2

## Details

The other day, I executed Insomnia in a vnc 'root' account session and it worked fine, it had my settings and workspaces.
Before that, whenever I open Insomnia in my normal user account, the 'html' content (the inner part of the app), is blank, it only shows a white color and doesn't do anything. The electron's menu bar works, at least the two options that open a browser (shorcuts and learn more i think)
I've tried reinstalling Insomnia automatically and manually several times, but it doesn't work anymore on my account.
But if I go back to vnc with my root account, it works.
I've tried removing tightvncserver (what I used) but it doesn't matter.
I thought this could be related with electron but other electron apps I have work just fine.

**Comment by gschier** [comment]
This is probably because the root instance wrote the initial database files. You may have to change the file permissions of the app directory to your user.

**Comment by maletil** [comment]
I've tried with dpkg and gdebi but it installs always root permissions and shows a lock.
I did chmod 777 and chown but it still doesn't work. The only way I can use it is with gksudo.

I've revised all directories Insomia installs content to but they are rw 777.

**Comment by gschier** [comment]
Which directories did you check? Everything in `~/.config/Insomnia`?

**Comment by maletil** [comment]
I've modified that directory but requests don't work, they show the same output always

**Comment by gschier** [comment]
Did you change permissions recursively to ensure you got every file? You could also try deleting `~/.config/Insomnia` and starting over without root.

I'm closing this issue for now since it does not seem like a problem with Insomnia itself.
