### ISSUE TITLE
Oauth2 Credentials Setting Doesn't Toggle

### ISSUE THREAD

**Issue by mttrhll** [getinsomnia/insomnia#4715]
### Expected Behavior

When using Oauth2 authentication with Client Credentials users can switch between "As Basic Auth Header" and "In Request Body".

### Actual Behavior

Requests are always sent in request body regardless of setting.

### Reproduction Steps

1. Create a new request
2. Select "Oauth 2" as authentication
3. For "GrantType" select "Client Credentials"
4. Fill in valid client ID, client secret, scope
5. Leave "Credentials" as default value of "As Basic Auth Header"
6. Retrieve a token (this should work so far)
7. Switch "Credentials" to "In Request Body" (many oauth providers will not return a token when the body contains credentials, this must fail to get a token to proceed with this use case)
8. Switch "Credentials" back to "As Basic Auth Header" - this will no longer work, it should go back to headers and succeed.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Further details:

I grep'd through my insomnia data dir and found that the value in "insomnia.Request.db" for "credentialsInBody" seems to toggling correctly. But whatever underlying system gets/needs it doesn't change its behavior.

Also, if you duplicate the request that doesn't work the copy will have this behavior. But if you create an all new request and  leave the default it will retrieve a token successfully.

**My version/system info is below:**
Version: Insomnia 2022.2.1
Release date: 3/21/2022
OS: Darwin x64 21.4.0
Electron: 17.1.0
Node: 16.13.0
V8: 9.8.177.11-electron.0
Architecture: x64

### Insomnia Version

2022.2.1

### What operating system are you using?

macOS

### Operating System Version

macOs Monterey 12.3.1 (21E258)

### Installation method

insomnia.rest DMG

**Comment by dimitropoulos** [comment]
We looked at this today [on the insomnia stream](https://youtu.be/n5nsA_fJ4vI?t=432).  In short.  YEP.

Sorry this is happening and we definitely need to look into it.  If nothing else, this spawned https://github.com/Kong/insomnia/pull/4768 which will at least give us some means to test this behavior as we devise a fix.

Apologies for taking so many days to get back to you on this.

**Comment by reinierkleipool** [comment]
I have the same problem. CREDENTIALS drop down does not toggle between "As Basic Auth Header (default)" and "In request Body"
Token requests are always sent "In request body" regardless of selection.
**Seen in**:
Version: Insomnia 2022.4.2
Build date: 22/06/2022
OS: Linux x64 5.4.0-122-generic
Electron: 18.1.0
Node: 16.13.2
V8: 10.0.139.15-electron.0
Architecture: x64
**OS**  Lunux (Ubuntu)

**Comment by mttrhll** [comment]
Thanks for getting back to me. I love insomnia and I want to help make it
better... it is an easy workaround to create a new request (but you can't
copy it sadly)... but if the setup is complex it is definitely annoying.
Let me know if I can help in any way.

-Matt
