### ISSUE TITLE
[Bug] Decoding %2A (star) in URL

### ISSUE THREAD

**Issue by mthenw** [getinsomnia/insomnia#473]
- Insomnia Version: 5.7.14 (5.7.14.1021)
- Operating System: macOS 10.12.6

## Details

Insomnia is decoding encoded star character (%2A) in URL.

E.g. sending requests to `http://127.0.0.1:3001/%2F%2A` from Insomnia will actually cause a request to `http://127.0.0.1:3001/%2F*`.

As a confirmation, using `curl http://127.0.0.1:3001/%2F%2A` will send a request to `http://127.0.0.1:3001/%2F%2A`.

Node.js server to reproduce below
```
const http = require("http");

const server = http.createServer((request, response) => {
  response.end(request.url);
});

server.listen(3001);
```

**Comment by gschier** [comment]
Thanks for reporting this @mthenw. It will be fixed in the next version 😄
