### ISSUE TITLE
OpenAPI v3.1 Support

### ISSUE THREAD

**Issue by philsturgeon** [getinsomnia/insomnia#4732]
### Expected Behavior

Hello! As the maintainer of [openapi.tools](https://openapi.tools), and as somebody works with Linux Foundation helping out in OpenAPI-land, I'm reaching out to tooling vendors to track the progress towards supporting OpenAPI v3.1, to see what roadblocks there are beyond folks just generally being busy at this ridiculous time.

OpenAPI v3.1 has a bunch of great little changes, solving problems like the the [JSON Schema <!=> OpenAPI Schema Object divergence](https://apisyouwonthate.com/blog/openapi-json-schema-divergence). It also fixes some other inconsistencies and duplicate ways of doing things. It's the best version and everyone should be using it, but we need tooling to catch up. Just in case folks didn't notice, or don't have resources to simplify the process, I'm here to give a friendly prod and send over some handy links.

Here are a few articles showing off the differences between OpenAPI v3.0 and v3.1.

- https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0
- https://www.apimatic.io/blog/2021/09/migrating-to-and-from-openapi-3-1/ 
- https://nordicapis.com/whats-new-in-openapi-3-1-0/

Here are some example files which can make for handy pass/fail test cases:

https://github.com/Mermade/openapi3-examples/tree/master/3.1 

If you're looking for the JSON Schema that defines a valid OpenAPI document, that'll be right over here: 

https://github.com/OAI/OpenAPI-Specification/tree/main/schemas/v3.1 

No rush, but when you're starting work on it, please update this issue so I can update [openapi.tools](https://openapi.tools) to reflect that, and folks will have a way to subscribe for updates.

LMK if you have any questions!

### Actual Behavior

Not a bug.

### Reproduction Steps

1. Hello!

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

latest

### What operating system are you using?

Other Linux

### Operating System Version

NA

### Installation method

NA

### Last Known Working Insomnia version

NA

**Comment by dimitropoulos** [comment]
what a wonderful wonderful check-in!

we're pretty much ready to go, except that we're blocked on https://github.com/APIDevTools/swagger-parser/pull/191.

**Comment by dimitropoulos** [comment]
Also, gotta say how big of a fan I am personally of openapi.tools.  I find it very helpful and I also use it a lot in presentations (internally) about OpenAPI to just show the table of contents to demonstrate how many mutually exclusive things you can do with a spec.

**Comment by philsturgeon** [comment]
@dimitropoulos I finally managed to get a new swagger-parser version release. Let me know if that's working for you!

**Comment by philsturgeon** [comment]
I spoke to soon but hey now you can use `@apidevtools/swagger-parser@10.1.0` and it should work for sure. `swagger-parser` is going to be deprecated so use that scoped version instead.

If you can throw a bit of cash into https://github.com/sponsors/philsturgeon that would be amazing because I just spent about 20 hours trying to get that working, completely unpaid, after I spent most of the week working on completely unpaid work for www.protect.earth and my brain is melting.

**Comment by weeebdev** [comment]
@philsturgeon any openapi v3 client other than postman?

**Comment by philsturgeon** [comment]
@weeebdev I am nort sure I understand the question? What is an openapi v3 client? 

There are lots of tools over on https://openapi.tools/.
