### ISSUE TITLE
[Improvement] Graphql Refresh Schema

### ISSUE THREAD

**Issue by patrickheeney** [getinsomnia/insomnia#474]
- Insomnia Version: 5.7.14
- Operating System: osx

## Details

The graphql integration is awesome, however its been 15 hours since the schema was last fetched. I have my application hot module replacing my schema so it gets severely out of sync. Would be awesome to have a small button next to last fetched to refresh or a button next to Prettify Graphql to refresh the schema from there.

**Comment by gschier** [comment]
That's a good idea. Right now, the schema refreshes when you switch requests or edit the URL. Adding a button should be pretty easy.

**Comment by ganderzz** [comment]
@gschier Is this free to work on? I'm down to take it on. Would be super helpful while debugging GraphQL!

**Comment by gschier** [comment]
Yep, you can take it on if you'd like @ganderzz 😀

Let me know if you have any questions.

**Comment by patrickheeney** [comment]
Thanks @ganderzz . Nice work!!
