### ISSUE TITLE
Pressing the return key no longer triggers request being sent 

### ISSUE THREAD

**Issue by unreleased** [getinsomnia/insomnia#4743]
### Expected Behavior

I am expecting when I press enter on the URL input to submit it that the request is automatically made (Like a regular web form) instead nothing happens. I have to manually click the "Send" button or now press "CMD + Enter"

If "CMD + Enter" is the new command you are using (Which I expect it isn't) It should be reflected when you right-click the "Send" button.

### Actual Behavior

Request does not send.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.1 (M1 MAX)

### Installation method

Website install

### Last Known Working Insomnia version

Previous version I was using before

**Comment by dimitropoulos** [comment]
On the stream just now we were able to reproduce on develop with linux.

**Comment by filfreire** [comment]
@unreleased this issue should now be fixed on our [latest beta (2022.5.0-beta.0)](https://github.com/Kong/insomnia/releases/tag/core%402022.5.0-beta.0), thanks to @marckong's fix on #4868.

Feel free report any other issues you come across.
