### ISSUE TITLE
Inso run test doesn't run out of the box

### ISSUE THREAD

**Issue by pierreozoux** [getinsomnia/insomnia#4747]
### Expected Behavior

It should run out of the box.

### Actual Behavior

It doesn't and print this message:
```
 FATAL  No test suites found; cannot run tests.                                              
```

### Reproduction Steps

1. Use the UI to create a Test Suit
2. Sync the Test Suit with git
3. Go to CLI
4. run `inso run test`

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I'm using the version 3 of the CLI and 2022.3 of the UI.

### Insomnia Version

2022.3.0

### What operating system are you using?

Ubuntu

### Operating System Version

21.04

### Installation method

Relesae from Github

**Comment by filfreire** [comment]
Hi @pierreozoux

Does this still happen if you define the workspace? E.g.

```shell
inso run test -w ~/some-folder/git-repo-folder/
```

**Comment by pierreozoux** [comment]
@filfreire Still the same:
```
pierreo@pierreo:~/f/libre.sh/scim$ inso run test -w ./nextcloud-scim/

 FATAL  No test suites found; cannot run tests.                                                                                                                                              
```

My repo is here if it helps:
https://lab.libreho.st/libre.sh/scim/nextcloud-scim/

Maybe it is because I have no env?

**Comment by filfreire** [comment]
@pierreozoux indeed you need to add both the "Base Environment" and the "API Spec", regardless of them being empty.

As soon as I added placeholders for those, `inso` was able to find the test suite.
![image](https://user-images.githubusercontent.com/11976836/166339036-7054ef8f-7a86-4c54-a2f2-2595f65aee0b.png)

You should see on Insomnia those files still unversioned when you commit changes:
![image](https://user-images.githubusercontent.com/11976836/166338790-919d6db9-ec7f-4be8-bd49-459239ff0d4a.png)

Let us know if it works after adding those.

**Comment by pierreozoux** [comment]
Ok, it works, thanks for the hint!

Maybe it would be good to add some hints in the CLI to help users identify what is going wrong with their env :)

I'm closing for now :)
