### ISSUE TITLE
Github Oauth does not work

### ISSUE THREAD

**Issue by Wazbat** [getinsomnia/insomnia#4748]
### Expected Behavior

When I authenticate with github, I am presented with a code in my web browser. After copy pasting that code into the provided box, I would expect my account to be linked

### Actual Behavior

Clicking the "Add" button in the form does nothing. Inspecting the logs, it appears to be throwing an error

### Reproduction Steps

1. Crete a new design document
2. Click "Set up Git Sync" on the top right
3. Click "Repository settings"
4. Click "Authenticate with github"
5. Continue with the flow, and copy the resulting code
6. Paste it in the box
7. Click "Add"
8. Nothing happens, the app throws an error behind the scenes

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

v2022.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 build 19044.1645

### Installation method

Download from the home page

**Comment by Wazbat** [comment]
I might try to fix this myself, or at least try. Would love to open a PR and contribute to this tool I use often

**Comment by Wazbat** [comment]
Ah... It apperas this is just a case of me being confused by the flow. I saw that modal said to paste the "code", and the url that was shown onscreen had a "code" query param, so I thought that that was what I needed to paste in. There was no error shown, so I assumed the app was broken

I've created a simple pull request #4749 relating to this, but I'm not sure how exactly the error should be shown to the user

**Comment by jackkav** [comment]
This is a great observation, if you got tripped up others will too, I'll try to help you move this forward 🤔

**Comment by dimitropoulos** [comment]
closed by https://github.com/Kong/insomnia/pull/4749
