### ISSUE TITLE
Use Content-Disposition to Name Downloaded File

### ISSUE THREAD

**Issue by SingleShot** [getinsomnia/insomnia#475]
When using the "Download after Send" feature it would be convenient if the `Content-Disposition` header were inspected for a `filename` property. If it exists, use the value for the name of the downloaded file. Otherwise do whatever Insomnia currently does. This would make it easier to open the file after download since it will have the proper extension, etc., if provided by the server.

**Comment by gschier** [comment]
Nice suggestion @SingleShot !
