### ISSUE TITLE
[Feature Request] Negotiate authentication

### ISSUE THREAD

**Issue by simon-p-r** [getinsomnia/insomnia#476]
Hi

Are there any plans to add Windows integrated auth to Insomnia?

Thanks

**Comment by gschier** [comment]
Is that NTLM? If so, Insomnia already has it.

**Comment by simon-p-r** [comment]
No not NTLM, I mean negotiate (sspi, spnego and kerberos) as mentioned in rfc [4178](https://tools.ietf.org/html/rfc4178) and [4559](https://tools.ietf.org/html/rfc4559).

**Comment by gschier** [comment]
Pardon my ignorance. I don't know anything about Windows authentication.

Insomnia supports NTLM because it is included in libcurl (which Insomnia uses). I have no plans to implement negotiate auth myself, nor do I have any idea how much work it would be. Depending on the complexity, you may be able to implement it yourself via a request hook plugin: https://insomnia.rest/documentation/plugins/#request-hook-api

**Comment by simon-p-r** [comment]
If insomnia uses libcurl it maybe possible. I will see if I can get a local fork working.

**Comment by gschier** [comment]
Oh ya, NEGOTIATE is listed as an auth type: https://curl.haxx.se/libcurl/c/CURLOPT_HTTPAUTH.html

Although, it may not be available the way Insomnia is currently built. 

You may have already found it, but the code you want to play around with is probably here: https://github.com/getinsomnia/insomnia/blob/develop/app/network/network.js#L453

Let me know what you find 😄

**Comment by simon-p-r** [comment]
Just got round to looking at the native dependencies, I will try to rebuild node-libcurl with sspi support to test negotiate auth but it looks very fragile and may take some time. Are you looking at alternative bindings to libcurl?

**Comment by simon-p-r** [comment]
The build process used by node-libcurl is very messy, I am trying to test a cleaner build process.  I use cmake to build c/c++/node addons as gyp is legacy tool now.   I have built node-libcurl against a static binary on Windows but all by hand.  Are there any suggestions you have regarding the curl binary you want to use?  To build curl you have many different build options

**Comment by veeveEdwardHalls** [comment]
I am interested in seeing this functionality, SPNEGO support as NTLM is supposedly less secure.

**Comment by Lonli-Lokli** [comment]
So it it possible to have any workaround to get negotiate working?

**Comment by gschier** [comment]
I don't know enough about Windows to work on this unfortunately

**Comment by alekdavis** [comment]
So, is there a way to get Kerberos (`--negotiate` in curl) to work for Windows?

**Comment by ghost** [comment]
It doesn't sound like this is ever going to happen, but I'm also interested in seeing Kerberos support in Insomnia. It's unfortunately not very useful for me without it.

**Comment by Lonli-Lokli** [comment]
@gschier Can we at least keep this open?

**Comment by dimitropoulos** [comment]
@Lonli-Lokli we've since moved to [discussions](https://github.com/Kong/insomnia/discussions/categories/ideas) for feature requests.  If you'd like to open one and give an example of your use-case (and link back to this issue) I'd welcome it.  


> btw, technically we can convert this issue to a discussion, but I can tell from looking at all the stalebot messages that it'll be a lot cleaner to start fresh in this specific case.

**Comment by gueggel** [comment]
Any news? I need this feature also.

**Comment by mos379** [comment]
I vote for this feature too :)
