### ISSUE TITLE
Bug with cookie handle in version 2022.4.0-beta.0

### ISSUE THREAD

**Issue by 0x524c** [getinsomnia/insomnia#4765]
### Expected Behavior

In version 2022.3.0 I can have a cookie received by a graphql backend running on localhost that travels between all requests for the same backend/domain.

### Actual Behavior

I'm using Insomnia to develop a graphql backend, where I'm generating a Cookie. The backend is on localhost. I have two mutations: login and me..
On login I am creating this cookie that was received by Insomnia and saved. After running a new query on another mutation 'me', the cookie doesn't appear available in Insomnia and it wasn't sent to the graphql backend either.

This issue occurred after the 2022.4.0-beta.0 update, with the 2022.3.0 version this issue does not occur.

The cookie data, for example:
`token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjcyN2NjM2Y1Nzk1YmFiYTlhZGU5OWEiLCJlbWFpbCI6InJvZ2VyaW9sdWNhc0BnbWFpbC5jb20iLCJpYXQiOjE2NTIxNTI1MzQsImV4cCI6MTY1Mjc1NzMzNH0.03hzr54bNgvwX6CM3BBSO-zSpNSHOIL_ypa6uJ78KCo; Expires=Tue, 17 May 2022 03:15:34 GMT; Max-Age=604800; Domain=localhost; Path=/; HttpOnly; SameSite=Lax`

It's not very relevant, but here are the mutations schema:
```
mutation LOGIN($email: String!, $password: String!) {
  Login(email: $email, password: $password) {
    _id
    name
    username
    email
    token
  }
}

{
  me {
    _id
    email
  }
}
```

### Reproduction Steps

You will need a graphql server and a mutation that creates a cookie and then makes a request for a new mutation and the cookie will not be sent.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.4.0-beta.0

### What operating system are you using?

macOS

### Operating System Version

Macos 12.3.1

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

2022.3.0

**Comment by 0x524c** [comment]
I understand it a little better now: I re-installed the previous version 2022.3.0 and ran the mutation login which passes a cookie via the backend, and then I updated to 2022.4.0-beta.0.
In this way, with the cookie previously saved by version 2022.3.0, it started to be transferred correctly on all requests in the version 2022.4.0-beta.0. The problem seems to occur when saving the cookie.

**Comment by jackkav** [comment]
Thanks for the issue @524c 
Set-cookies were being ignored, fixed in https://github.com/Kong/insomnia/pull/4769

**Comment by 0x524c** [comment]
@jackkav, great!
Thanks for this excellent tool. Congratulations!

**Comment by filfreire** [comment]
@524c you should be able to use @jackkav's fix in this week's beta release: https://github.com/Kong/insomnia/releases/tag/core%402022.4.0-beta.1
