### ISSUE TITLE
[Performance] Interface unresponsive for a few seconds, then the whole window becomes white when a JSON request contains a javascript comment

### ISSUE THREAD

**Issue by lovasoa** [getinsomnia/insomnia#477]
- Operating System: linux

## Details

When I open insomnia, the UI displays for a few seconds (but is unresponsive), and then becomes white.

![capture du 2017-09-12 09-42-27](https://user-images.githubusercontent.com/552629/30313777-c608367c-979e-11e7-9d9f-27e0b4272254.png)

![capture du 2017-09-12 09-42-00](https://user-images.githubusercontent.com/552629/30313797-e0278094-979e-11e7-98c2-b5d5c0a9cdfd.png)

When using the  debugger, I get `paused before potential out-of-memory crash` :

![capture du 2017-09-12 09-46-29](https://user-images.githubusercontent.com/552629/30313935-5ff031c2-979f-11e7-9d37-f37a97167e73.png)

(Line 31 of prettify.js seems to be an infinite loop.)

On the console, I get:

```
$ INSOMNIA_FORCE_DEBUG=1 ./Téléchargements/insomnia.AppImage 
installed: X-AppImage-BuildId=faa212a0-82d5-11a7-3a91-99578b89251f image: X-AppImage-BuildId=faa212a0-82d5-11a7-3a91-99578b89251f
[localstorage] Initialized at /home/o/.config/Insomnia/localStorage
Installed Extension: React Developer Tools
Installed Extension: Redux DevTools

<--- Last few GCs --->

[19378:0xd2d6bb6f000]     3043 ms: Mark-sweep 2046.7 (2100.5) -> 2046.7 (2100.5) MB, 25.3 / 0.0 ms  allocation failure GC in old space requested
[19378:0xd2d6bb6f000]     3088 ms: Mark-sweep 2046.7 (2100.5) -> 2046.7 (2069.5) MB, 44.8 / 4.1 ms  last resort 
[19378:0xd2d6bb6f000]     3128 ms: Mark-sweep 2046.7 (2069.5) -> 2046.7 (2069.5) MB, 40.1 / 3.7 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x246a59d83bd1 <String[7]: file://>
    1: exec(this=0x4dff3d28781 <JS RegExp>,0x18f8098eded1 <Very long string[1031114]>)
    3: prettifyJson(aka prettifyJson) [file:///tmp/.mount_bXUtFM/usr/bin/resources/app.asar/bundle.js:67874] [bytecode=0x123043e54759 offset=357](this=0xfd080f82311 <undefined>,/* anonymous */=0x36386c302201 <Very long string[1091141]>,/* anonymous */=0x5caf9a5fbf1 <String[1]\: \x09>,/* anonymous */=...

```

**Comment by gschier** [comment]
This seems like it's a problem it prettifying the response body, not the request body. 

Are you able to share the response body of that request so I can use it to debug?

**Comment by lovasoa** [comment]
Unfortunately, I cannot share the body of the response. But I can tell you that it was a JSON containing, among other fields, the sources of several wikipedia articles (in wikicode). Wikicode usually contains a lot of double-braces [see the syntax reference](https://en.wikipedia.org/wiki/Help:Wiki_markup).

A similar bug can be reproduced with this small json file that only contains braces:
```
GET https://gist.githubusercontent.com/lovasoa/3344b45cf41c35fedaec25d48f1fe756/raw/e1a504310deb7b651e327e32051aecec2749a1ce/mustaches.json
```

I think using template strings repeatedly on the same string (line 34 of `prettify.js`) is inefficient.

**Comment by lovasoa** [comment]
Here is an example that might be more realistic: querying 3 long wikipedia articles using mediawiki's API:

```
GET https://en.wikipedia.org/w/api.php?action=query&titles=List_of_shipwrecks_in_1837|List_of_shipwrecks_in_1838|List_of_shipwrecks_in_1839&prop=revisions&rvprop=content&format=json
```

**Comment by gschier** [comment]
Thanks for that URL. I was able to reproduce the problem with it.

I should be able to use an alternative algorithm to get better performance.

**Comment by gschier** [comment]
Should have this fix released by the end of the week!
