### ISSUE TITLE
C# Code Generation for HttpClient Error

### ISSUE THREAD

**Issue by nhoemchenda** [getinsomnia/insomnia#4773]
### Expected Behavior

There shall be no error.

### Actual Behavior

The code produce error:
InvalidOperationException: Misused header name, 'Content-Type'. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.

### Reproduction Steps

1. Have a working Api test in insomnia with headers:
Content-Type: application/json
Accept-Language: en
and Json:
{
	"userName": "somename",
	"password": "somepassword"
}
2. Generate Code Choosing C# and HttpClient
3. There shall be similar to this
var client = new HttpClient();
var request = new HttpRequestMessage
{
    Method = HttpMethod.Post,
    RequestUri = new Uri("https://someurl.tld/action"),
    Headers =
    {
        { "Content-Type", "application/json" },
        { "Accept-Language", "en" },
    },
    Content = new StringContent("{\n\t\"userName\": \"someusername\",\n\t\"password\": \"somepassword\"\n}")
    {
        Headers =
        {
            ContentType = new MediaTypeHeaderValue("application/json")
        }
    }
};
using (var response = await client.SendAsync(request))
{
    response.EnsureSuccessStatusCode();
    var body = await response.Content.ReadAsStringAsync();
    Console.WriteLine(body);
}
4. Apply C# code to project for testing
5. We can have a work around solution by removing { "Content-Type", "application/json" } as below
var client = new HttpClient();
var request = new HttpRequestMessage
{
    Method = HttpMethod.Post,
    RequestUri = new Uri("https://someurl.tld/action"),
    Headers =
    {
        { "Accept-Language", "en" },
    },
    Content = new StringContent("{\n\t\"userName\": \"someusername\",\n\t\"password\": \"somepassword\"\n}")
    {
        Headers =
        {
            ContentType = new MediaTypeHeaderValue("application/json")
        }
    }
};
using (var response = await client.SendAsync(request))
{
    response.EnsureSuccessStatusCode();
    var body = await response.Content.ReadAsStringAsync();
    Console.WriteLine(body);
}

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 21H2 22000.675

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment]
Hi @nhoemchenda, thank you for reporting this issue!

I was able to reproduce two different problems aside from the one you mention, but this needs to be fixed on the underlying library that Insomnia uses,  [httpsnippet](https://github.com/Kong/httpsnippet). I went ahead and created a follow-up issue there, https://github.com/Kong/httpsnippet/issues/261


Left my [reproduction example in this repo](https://github.com/filfreire/insomnia-issue-4773). Notes:
> We're missing `using System.Net.Http.Headers;` which causes:
> 
> ```
> /Users/filipe.freire@konghq.com/work/issue4773/Program.cs(18,31): error CS0246: The type or namespace name 'MediaTypeHeaderValue' could not be found (are you missing a using directive or an assembly reference?) [/Users/filipe.freire@konghq.com/work/issue4773/issue4773.csproj]
> 
> The build failed. Fix the build errors and run again.
> ```
> 
> And then we're adding `{ "Content-Type", "application/json" }` in `Headers`:
> 
> ```csharp
> // (...)
> RequestUri = new Uri("http://mockbin.org/request/anything"),
>     Headers =
>     {
>         { "Accept-Language", "en" },
>         { "Content-Type", "application/json" }, // THIS IS WRONGFULLY ADDED
>     },
> // (...)
> ```
> 
> Which causes:
> 
> ```
> Unhandled exception. System.InvalidOperationException: Misused header name, 'Content-Type'. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
>    at System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor(String name)
>    at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
>    at Program.<Main>$(String[] args) in /Users/filipe.freire@konghq.com/work/issue4773/Program.cs:line 5
>    at Program.<Main>(String[] args)
> ```
> 


In the meantime @nhoemchenda feel free to report any other issues you find 👍

**Comment by filfreire** [comment]
Thank you @nhoemchenda for contributing the PR with the fix 🙇 

Feel free to report any other issues you may find 👍
