### ISSUE TITLE
[Feature Request] Optimize Environment Editor

### ISSUE THREAD

**Issue by multirealm** [getinsomnia/insomnia#478]
- Insomnia Version: 5.8.2
- Operating System: Mac OS X

## Details
Changing environment variables in Json gives you high flexibility on the one hand, but on the other hand it is very error-prone and difficult to read/edit in complex structures.
Therefore a Json extension like json5 or hjson could help to enter and manage environment variables easier and get more syntax error tolerance.

http://json5.org/
https://hjson.org/

**Comment by starJammer** [comment]
I would personally enjoy being able to add comments to the env json.
