### ISSUE TITLE
response code 204

### ISSUE THREAD

**Issue by eeviefogarty** [getinsomnia/insomnia#4784]
### Expected Behavior

insomnia resolves request, says no content but request successful 

### Actual Behavior

insomnia never resolves the request

### Reproduction Steps

create a rest api which responds with no content & http code 204
request it with insomnia

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11, 21H2

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment]
Hi @ian-ok, thank you for reporting this issue!

I'm not able to reproduce this for example requesting to `httpbin.org/status/204` which forces the status code to 204 and returns no content.

![Screenshot 2022-05-16 at 10 28 29](https://user-images.githubusercontent.com/11976836/168562417-5f711c71-200f-4d83-b8ee-4f2a02b93430.png)
![Screenshot 2022-05-16 at 10 28 23](https://user-images.githubusercontent.com/11976836/168562423-3e7e80d2-a76e-4365-88ae-15e6458ea688.png)

Can you provide more details into what you see, and are you able to resolve the same request elsewhere, for example by sending a `curl` request?

**Comment by eeviefogarty** [comment]
i used fastify with nestjs for this to occur, not sure if thats a factor,
to send the request i used:
`return res.code(204)`

**Comment by SethFalco** [comment]
> to send the request i used

I assume you mean to send the response?

I think it's more likely that your request handler is hanging, or is returning before reaching the line you shared.

**Comment by eeviefogarty** [comment]
i dont think so, if i add content to the request it works as expected

**Comment by filfreire** [comment]
@ian-ok this could have something to do with the implementation of your server, not necessarily with Insomnia.

I've tried reproducing with a simple server setup:
```js
const http = require('http');
const port = 3000;

http.createServer(function (req, res) {
	res.writeHead(204, {'Content-Type': 'text/plain'});
	res.end('test');
}).listen(port);
```

And I was able to still get the proper `204 No Content` response.



![Image](https://user-images.githubusercontent.com/11976836/181223918-89b52924-2cc6-4140-8edf-795dfca26047.png)



I'm marking this issue as closed for now, but I would encourage you to check if you notice similar behavior using for example a curl request, or with other API clients, as it might indeed be an implementation problem.

If you still face this problem, or you find new ones, please feel free to open an issue.
