### ISSUE TITLE
Quick Switch text field does not auto-focus when opening it while Preview search box is focused

### ISSUE THREAD

**Issue by Coteh** [getinsomnia/insomnia#4797]
### Expected Behavior

If I press Ctrl-P to pull up the Quick Switch menu while the search box is focused in Preview pane, the Quick Switch text field should auto-focus and I should be able to type right away.

### Actual Behavior

The search box is not focused and thus I'm not able to type into it. I can work around this by explicitly clicking on the Quick Switch text field with my mouse, or pressing Esc then Ctrl-P again.

![image](https://user-images.githubusercontent.com/3276350/169360458-7a719564-629a-4fd5-8558-ef008d5f296e.png)

### Reproduction Steps

1. Perform a request within a collection
2. In the Preview pane, press Ctrl-F to bring up the search
3. Press Ctrl-P while the search box is active and focused

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro version 2004

### Installation method

Downloaded from https://insomnia.rest/download

**Comment by filfreire** [comment]
Hi @Coteh, thanks for reporting this issue!

I can reproduce it myself with the exact steps you mentioned.



https://user-images.githubusercontent.com/11976836/169487346-144a77f4-def2-420d-880e-8aa3a22800bc.mp4


We'll keep this issue updated if there's changes or fixes.

Feel free to report any other issues you find!
