### ISSUE TITLE
[grpc] Support secure grace but ignore problems

### ISSUE THREAD

**Issue by joeyorlando** [getinsomnia/insomnia#4799]
This would be nice to have, any thoughts?

### Discussed in https://github.com/Kong/insomnia/discussions/3796

<div type='discussions-op-text'>

<sup>Originally posted by **gAmUssA** July  8, 2021</sup>
grpcurl has `-insecure` flag that allows ignoring validation. it would be great to have it in insomnia.

`grpcurl -insecure 34.69.7.159:443 io.kong.developer.quoteservice.QuoteService/GetQuote`
</div>

**Comment by filfreire** [comment]
Hi @joeyorlando, thanks for reporting this!

I would suggest you write down any discussion on this on #3796, as this is kind of a duplicate of that discussion.

In the meantime I just opened an [issue on our internal backlog](https://linear.app/insomnia/issue/INS-1547/support-insecure-connection-setup-on-grpc-requests) to look at this "more expeditiously" 😅 .

I'd like encourage you to keep reporting any other issues or improvements you can think off, which will help us at least be aware of 👍
