### ISSUE TITLE
Choose file dialog doesn't show files/folders on Linux

### ISSUE THREAD

**Issue by tqwewe** [getinsomnia/insomnia#4803]
### Expected Behavior

Selecting a file via multipart form upload should allow me to see my files and select one. Files in root are visible, but files in my /home/ari directory are not.

### Actual Behavior

The dialog opens, but the file list is empty. Dragging files into the dialog also fails with a message: `Error: ENOENT: no such file or directory, open '/home/ari/dev/foo.txt'`.

### Reproduction Steps

1. Create a new request
2. Set the body type to be Multipart form
3. Click "Choose File"
4. Dialog opens, but see no files visible in home directory.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

![Screenshot from 2022-05-20 17-50-48](https://user-images.githubusercontent.com/16362377/169485994-c79ac207-ac43-44bd-b9d9-d9d69cc45e47.png)

### Insomnia Version

2022.3.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux ari 5.17.7-300.fc36.x86_64 #1 SMP PREEMPT Thu May 12 14:56:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

Flatpak - dl.flathub.org

**Comment by tqwewe** [comment]
It seems like the flatpak exec command should include the additional argument `--filesystem=home`.

A temporary workaround is to edit the file at `/var/lib/flatpak/exports/share/applications/rest.insomnia.Insomnia.desktop` and add the argument to the `Exec` section.

```
sudo nano /var/lib/flatpak/exports/share/applications/rest.insomnia.Insomnia.desktop
```
```
[Desktop Entry]
Name=Insomnia
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --filesystem=home --command=/app/bin/insomnia --file-forwarding rest.insomnia.Insomnia --no-sandbox @@u %U @@
...
```
Note I added the `--filesystem=home` argument to the entry file.

Once updated, you can press ALT F2, and enter "r" to reload gnome.

**Comment by filfreire** [comment]
Hey @tqwewe, thank you for reporting this!

Indeed this seems to be an issue with the flathub/flatpak "version" of Insomnia. There are other folks reporting this exact same issue on the [flathub/rest.insomnia.Insomnia](https://github.com/flathub/rest.insomnia.Insomnia) repository.

I would suggest you push a fix there, as for now we don't officially maintain or have permissions to that repository yet.

Feel free to report any other issues you come across, and thank you for finding this solution! 🙇

**Comment by tqwewe** [comment]
Thanks for pointing me to that repo, I wasn't aware thats where the flatpak repository was.

Feel free to close this issue if you think it's not in the scope of the official insomnia repo
