### ISSUE TITLE
Disabling Font Ligatures does not disable in Collection Pain

### ISSUE THREAD

**Issue by Midnex** [getinsomnia/insomnia#4813]
### Expected Behavior

When disabling Font Ligatures it should disable them throughout the entire app.

### Actual Behavior

Parts of the GUI continue to show font ligatures. While this is ugly when using a normal font, it is exzaerbated when using Arch and a Nerd font such as NotoSans Mono.

System fonts (notice the Fs) with Ligatures Disabled
![image](https://user-images.githubusercontent.com/702330/169887712-eaf1e5d9-cb98-43be-b163-b7508faff8c4.png)

NotoSans Mono Nerd Font on Arch with Ligatures disabled
![image](https://user-images.githubusercontent.com/702330/169887836-d17457bd-9884-4dda-8ee8-3ebdce37b2e1.png)

### Reproduction Steps

1. Install a font such as NotoSans Mono Nerd Font or other Nerd Font.
2. Create a new folder without adding any request to it.
3. Disable font ligatures
4. Look at Interface, In settings they are shown disabled, and disabled. In Preview response, they are disabled, in request collection they are still enabled.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Using Arch based Linux, there is a known issue with font ligatures on nerd fonts, which only exacerbate the problem, on windows it is far less noticeable. However on Arch Linux it is very noticeable that disabled ligatures only disabled it in some places.

Here you can see the top example with FI not working, and the bottom example it working fine.
![image](https://user-images.githubusercontent.com/702330/169886966-bdf9ae67-de7e-4016-ba34-8da47c2b3a73.png)

### Insomnia Version

2022.3.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux 5.15.32-1-MANJARO x86_64 GNU/Linux

### Installation method

pacman

### Last Known Working Insomnia version

None, been broke ever since I can remember.

**Comment by dimitropoulos** [comment]
We were able to reproduce on the [stream](https://youtu.be/WfsZUuZGyg8?t=1419), and did find the cause but we need to find a fix.  It has to do with a user-agent stylesheet for `button`.  See the link to the stream in the first sentence to see when we discover this.

To reproduce add a font like https://github.com/tonsky/FiraCode/releases/tag/6.2 that supports ligatures and then rename a request to include `===`.  Note that no matter what setting you set in insomnia, it remains with ligatures.
