### ISSUE TITLE
Insomnia with unpacked Electron fails to launch in directories without root package.json

### ISSUE THREAD

**Issue by YakoYakoYokuYoku** [getinsomnia/insomnia#4820]
### Expected Behavior

Running system `electron` (e.g. from the `electron` package from ArchLinux or installed via npm) pointing at the `app.asar`,

```
$ electron path/to/insomnia/packages/insomnia/dist/linux-unpacked/resources/app.asar
```

Unpacked applications are a requirement for distributing some Electron packages in the ArchLinux repositories and testing patched or custom builds of Electron itself.

If I run Insomnia in a folder with the root [`package.json` file](https://github.com/Kong/insomnia/blob/develop/package.json) or inside a local clone with `npm run app-start` then it loads as expected.

```
$ cd path/to/insomnia
$ # Use your corresponding OS *-unpacked folder
$ # packages/insomnia/node_modules/.bin/electron also works
$ electron packages/insomnia/dist/linux-unpacked/resources/app.asar
$ # Or
$ cd /usr/lib/insomnia # The package.json is there too
$ electron resources/app.asar
```

![Screenshot_20220527_113044](https://user-images.githubusercontent.com/39890836/170720150-a178a338-4df3-4b5f-85c8-6670a66facda.png)

### Actual Behavior

When I'm not in a directory with the `package.json` the user interface is not loaded and instead shows a grey screen.

![Screenshot_20220527_112451](https://user-images.githubusercontent.com/39890836/170719149-18e23d7c-f5d0-41f0-bce2-e500e5dcd1d2.png)

### Reproduction Steps

1. Bootstrap with `npm run bootstrap`.
2. Package the app to the `packages/insomnia/dist` directory with `npm run app-package -- -- --dir` (use `npm run app-package -- -- --dir -c.electronDist=path/to/electron -c.electronVersion="$(sed 's/^v//' path/to/electron/version)"` if Electron is installed somewhere else in your system).
3. Run Electron in, e.g. your home folder, with `electron path/to/insomnia/packages/insomnia/dist/linux-unpacked/resources/app.asar` (`electron` can either be in `PATH` or inside `packages/insomnia/node_modules/.bin`).
4. Run Electron in the cloned directory with `electron packages/insomnia/dist/linux-unpacked/resources/app.asar`.
5. Start Insomnia in the same directory with `npm run app-start`.
6. Run Electron in another directory that has both root `package.json` and the `resources` folder from dist, e.g. `/usr/lib/insomnia`, `electron resources/app.asar`.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Structure of a directory that has both `package.json` and `resources`

```
$ exa --tree
.
|-- package.json
`-- resources
   `-- app.asar
   `-- bin
   |  `-- yarn-standalone.js
   `-- opensource-licenses.txt
```

### Insomnia Version

2022.4.0-beta.2 (git clone)

### What operating system are you using?

Other Linux

### Operating System Version

Linux 5.18.0-arch1-1

### Installation method

Unpacked dir

### Last Known Working Insomnia version

2022.2.1

**Comment by filfreire** [comment]
Hi @YakoYakoYokuYoku, thank you for reporting this.

Would you be able to add some context into why you want to run Insomnia locally in this way, e.g. using `electron path/to/insomnia/packages/insomnia/dist/linux-unpacked/resources/app.asar`?

Also are you able to boot up Insomnia using `npm run app-start`?

**Comment by YakoYakoYokuYoku** [comment]
> Hi @YakoYakoYokuYoku, thank you for reporting this.

You welcome

> Would you be able to add some context into why you want to run Insomnia locally in this way, e.g. using `electron path/to/insomnia/packages/insomnia/dist/linux-unpacked/resources/app.asar`?

I want to run Insomnia like this mainly to distribute packages and to test Electron with it. Edited the issue comment to reflect this.

> Also are you able to boot up Insomnia using `npm run app-start`?

Yes, I'm able to run it under the cloned folder.

**Comment by YakoYakoYokuYoku** [comment]
@filfreire actually, I've found out the reason for this, turns out that in newer versions of Electron `process.resourcesPath`, which provides hints for `app.getAppPath()`, points to the `resources` path relative to the `electron` binary due to how Chromium `base::PathService` handles requesting the executable path,

https://github.com/electron/electron/blob/12eade752d38093f9b6abdc6a0b82f64176c4618/shell/common/node_bindings.cc#L306-L316

instead of one relative to the `app.asar` of any Electron application when distributed in an unpacked way such as Arch does, on the other hand, packed apps like tarballs or snaps, don't suffer from this.

This issue can be closed since it's an upstream problem.

**Comment by filfreire** [comment]
Thank you @YakoYakoYokuYoku  - closing this issue then.
