### ISSUE TITLE
Insomnia Does not pick the typed password

### ISSUE THREAD

**Issue by codeater7** [getinsomnia/insomnia#4828]
### Expected Behavior

When the password is entered, it should be able to pick that up.

### Actual Behavior

The same password that was kept initially is being read again and again.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.3.0

### What operating system are you using?

macOS

### Operating System Version

MacOS Big Sur 11.6.5

### Installation method

homebrew

### Last Known Working Insomnia version

2022.3.0

**Comment by filfreire** [comment]
Hi @codeater7, thank you for reporting this!

Would you kindly provide more steps/information and perhaps some screenshots into how and where we can reproduce this problem? Thanks in advance!

**Comment by codeater7** [comment]
I figured that out! It was automatically picking up the token from the base environment and keeping in the header. Despite the change in Password( value), it did not pick (for right reason)
Solution: Clearing the  authorization header worked. :)

**Comment by filfreire** [comment]
@codeater7 no worries! Feel free to report any other issues you find on Insomnia :bow:
