### ISSUE TITLE
[Bug] Workspace Settings only edits default workspace

### ISSUE THREAD

**Issue by themightychris** [getinsomnia/insomnia#483]
- Insomnia Version: 5.8.3
- Operating System: Ubuntu 16.04

## Details

No matter which workspace is active, opening "Workspace settings" from the menu edits the default (originally named "Insomnia") workspace

**Comment by gschier** [comment]
Hmm, I'm not able to reproduce this on my end. Does it happen after a fresh restart of the app?

**Comment by themightychris** [comment]
Seems ok now after a restart. Pretty sure i restarted it before at some point, but it's possible I was only seeing the issue during initial run. I reproduced it several times

**Comment by gschier** [comment]
Ok thanks! Let me know if you are able to reproduce it again.
