### ISSUE TITLE
[Bug] Cookie Editor GUI Bug

### ISSUE THREAD

**Issue by boardy** [getinsomnia/insomnia#484]
- Insomnia Version: 5.8.3
- Operating System: Windows 10

In the new cookie editor there appears to be an extra "Edit" and delete button which is hiding the "Done" button.

![cookie_editor](https://user-images.githubusercontent.com/4533555/30394900-5feca034-98bc-11e7-83fc-208c7f55eca6.PNG)

**Comment by gschier** [comment]
Uh oh. Looks like a simple CSS issue. I'll get this fixed 👍 😄
