### ISSUE TITLE
[Improvement] Less jarring, more convenient updating mechanism

### ISSUE THREAD

**Issue by JayAndCatchFire** [getinsomnia/insomnia#485]
- Insomnia Version: 5.8.3 (5.8.3.1068)
- Operating System: OSX, Ubuntu

## Details

I know I'm being an entitled, whiny baby here.  The update system is more than adequate.  However, wouldn't it be nice if full restarts of the client were only necessary when electron version updates occurred?

Take Slack for example.  It uses electron for its native desktop client.  However, the client only restarts when an update to electron needs to be pushed out.  If there's an update to their js/html/css code, it can usually be pushed out without a hard restart.  The view in the client just reloads.

Perhaps this is something that can be investigated for Insomnia?

**Comment by JayAndCatchFire** [comment]
I should also note that although it would require a restart of the client, https://github.com/getinsomnia/insomnia/issues/182 is probably the preferred method of update for Ubuntu.

**Comment by gschier** [comment]
I'm not quite sure I see the benefit here. In Slack's case, does it not still need to re-initialize the UI when the update happens (like a browser refresh)? Is that really much better than restarting the app?

I'm not exactly sure how Slack is architected, but I would guess bet that it's simply loading the main application in a webview for every team, with some extra _Electron_ logic for handling sessions for team switching. This would allow them to use the same auto-update system as the in-browser version.

Don't get me wrong, I _do_ like the idea of this, but I think it would be a lot more work than it seems. Not to mention the ongoing maintenance cost it would introduce.

**Comment by starJammer** [comment]
I don't think there's much benefit to this to be honest. If there are any bugs with the implementation of the update the first thing a user might try is restarting the app anyway.

**Comment by gschier** [comment]
Going to close this one for now
