### ISSUE TITLE
Insomnia 2022.4 is creating a desktop shortcut each time I open it

### ISSUE THREAD

**Issue by FieteO** [getinsomnia/insomnia#4876]
### Expected Behavior

Opening the `Insomnia.Core-2022.4.1.exe` should open Insomnia and do not create a desktop shortcut (without asking to do so).

### Actual Behavior

Opening the `Insomnia.Core-2022.4.1.exe` opens Insomnia and creates a desktop shortcut.

### Reproduction Steps

1. Download the latest Insomnia for Windows from the [downloads page](https://insomnia.rest/download)
2. Double click the downloaded executable
3. Check your desktop for a shortcut that was created

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.4.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 19044

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

22.02, but that is the only other version I checked

**Comment by filfreire** [comment]
Hi @FieteO, thanks for reporting this issue!

Did you perhaps mean to use the [portable `.exe` of Insomnia](https://github.com/Kong/insomnia/releases/download/core%402022.4.1/Insomnia.Core-2022.4.1-portable.exe) that is on our [release page](https://github.com/Kong/insomnia/releases/tag/core%402022.4.1)?

The portable one should not add a shortcut or perform the same installation behavior you are describing.

**Comment by FieteO** [comment]
Thanks @filfreire, that will perhaps solve my issue.

Even though I find it strange that the version which is supposed to be non-portable behaves exactly like the portable one (no installer) **except for** creating a shortcut. I would expect that there is a confirmation window asking me if I want to create one and not just assume that I do.

**Comment by filfreire** [comment]
@FieteO no problem. This kind of expectation you mention is valid, and has been reported before.

I'm going to go ahead and close this issue in favour of https://github.com/Kong/insomnia/issues/1756. Feel free to report other issues you come across!
