### ISSUE TITLE
Wrong backticks in "Response Filtering Help" Popup

### ISSUE THREAD

**Issue by nstdspace** [getinsomnia/insomnia#4879]
### Expected Behavior

A correct list of examples is expected.

### Actual Behavior

The filtering examples contain backticks ( ` ) in front of @, resulting in incorrect JSONPath expressions.

![grafik](https://user-images.githubusercontent.com/28611589/174763728-747d48a5-b830-4a70-86ec-59ee38ccab00.png)

### Reproduction Steps

1. Make any request with JSON result
2. Click on the '?' button in the bottom right corner of the result box

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.4.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 21H2

### Installation method

download from website

**Comment by filfreire** [comment]
Hi @nstdspace, thank you for reporting this!

I was able to reproduce it:
- with a backtick:
<img width="950" alt="Screenshot 2022-06-23 at 09 01 45" src="https://user-images.githubusercontent.com/11976836/175248324-65faa49e-b903-4a8f-8346-f480bc67a303.png">

- without a backtick:
<img width="948" alt="Screenshot 2022-06-23 at 09 01 52" src="https://user-images.githubusercontent.com/11976836/175248330-d792d893-5657-475c-a188-70c44758d6b7.png">

**Comment by filfreire** [comment]
@nstdspace the fix (https://github.com/Kong/insomnia/pull/4892) you have contributed for this issue is now part of [the latest beta release](https://github.com/Kong/insomnia/releases/tag/core%402022.5.0-beta.3).

Thank you for contributing! 😊 

Feel free to report any other issues and submit improvements 🙇
