### ISSUE TITLE
[Bug] Insomnia shows blank window after deleting a collection

### ISSUE THREAD

**Issue by DamienGarrido** [getinsomnia/insomnia#4885]
### Expected Behavior

Other collections/documents should be shown after deleting a collection.

### Actual Behavior

Insomnia shows a blank window after deleting a collection.
![Screenshot from 2022-06-22 11-59-54](https://user-images.githubusercontent.com/1240351/175002053-81f55264-521b-428d-a6a5-440c077dd12e.png)

### Reproduction Steps

1. Go to collection settings
2. Delete the collection

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.4.1

### What operating system are you using?

Ubuntu

### Operating System Version

Linux ubuntu 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

snap

**Comment by filfreire** [comment]
Hi @DamienGarrido thank you for reporting this!

We've prepared a fix for this issue, and will release it later today in a new [minor patch (2022.4.2)](https://github.com/Kong/insomnia/pull/4887) and it will also be available in tomorrow's latest beta release (`2022.5.0-beta.1`).

We'll update you here once it's out!

**Comment by filfreire** [comment]
@DamienGarrido this should now be fixed on version [2022.4.2](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2).

Feel free to report other issues you find 👍
