### ISSUE TITLE
[Bug] Not rendering PDF response body

### ISSUE THREAD

**Issue by y-luis** [getinsomnia/insomnia#489]
- Insomnia Version:  5.8.4
- Operating System: Ubuntu 17.04

## Details

Hi. After updating to last version (not sure which version I was using, maybe 2 or 3 versions before), the `application/pdf` response body is not rendering right (does not shows anything) on the `Preview` tab `Visual Preview` mode. It shows body on `Source Code` mode and `Raw Data` mode and I can save response body (PDF) successfully.

**Comment by gschier** [comment]
Hi @y-luis. It looks like this probably broke in 5.7.14. I'll get this fixed for the next update but, for now, you can find and install a previous release here: https://github.com/getinsomnia/insomnia/releases
