### ISSUE TITLE
[Improvement] Add "overwrite" prompt when importing data

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#490]
Right now, importing data into Insomnia does a blind merge. This means that new resources are added and existing ones are blindly overwritten (not always wanted). 

A good way to improve this is to copy what every operating system does when moving files between folders.

- If resource doesn't exist, add it
- If resource does exist, ask user if they want to (1) Overwrite, (2) Skip, or (3) Copy as New
  - Also add a "do this for all resources in this import"

**Comment by multirealm** [comment]
This feature would be really great!!

**Comment by TioLuiso** [comment]
Please do something about it. Sometimes you only want to add a new request from swagger, but it just crushes everything you have already configured.

Viable options would be
* Selecting which workspaces / collections / requests to import from swagger before actual importing
* As has been said, ask to overwrite, skip, whatever

**Comment by moymike** [comment]
Has this been addressed?  I just did an export of some examples and sent the output file to a friend.  He imported it and it wiped his collection out without him even realizing.  He said he got no notice as to what he was going to lose.
