### ISSUE TITLE
[Bug] Curl doesn't include `-k` (or `--insecure`) when validate SSL is unchecked

### ISSUE THREAD

**Issue by johngibb** [getinsomnia/insomnia#491]
- Insomnia Version: 5.8.2
- Operating System: macos 10.12.6

### Steps to reproduce

1. Create a working request in Insomnia
2. Open preferences, and under the "General" tab, uncheck "Validate SSL Certificates"
3. Choose "Copy as Curl" for your request.

*Expected*

Command copied to clipboard includes `-k` or `--insecure`.

*Actual*

It does not, and the command fails due to an SSL error.

**Comment by johngibb** [comment]
I briefly investigated submitting a PR for this, but it looks like it's a pretty deep rabbit hole of adding support to the [httpsnippet](https://github.com/getinsomnia/httpsnippet) library, and implementing it for every supported client.

Then there's the issue that it's supposed to be following the [`HAR`](http://www.softwareishard.com/blog/har-12-spec/#request) spec, which doesn't include a field for specifying it's an insecure request.

Maybe not worth doing :)

**Comment by gschier** [comment]
Ah, yes. Insomnia's feature-set is starting to drift away from what `httpsnippet` supports. I would love to be able to support this, but I think you're right that it's probably not worth doing, unfortunately.

Going to close this one for now.

**Comment by 4n70w4** [comment]
the same issue

**Comment by 4n70w4** [comment]
May be add flag (with default value from `Validate SSL Certificates` `General` preferences) to `Generate Client Code` popup for add insecure flags.

![image](https://user-images.githubusercontent.com/38257723/91041024-fb1f7300-e617-11ea-82f4-a58d7bbe97d3.png)
