### ISSUE TITLE
[Bug] xpath cannot read attributes of response body

### ISSUE THREAD

**Issue by pierrelucveilleux** [getinsomnia/insomnia#492]
- Insomnia Version: 5.8.4
- Operating System: MacOs

## Details

Last request is a xml and I want to get the listener id attribute with 

xpath : `//listener/@id`

and xml
`<request>
<listener id="test">
  <location>space</location>
</listener>
</request>`

and receive error 

> TypeError: Cannot read property 'toString' of null

**Comment by gschier** [comment]
Oops, looks like I never added handling of attribute queries. Doing that now..

**Comment by carmineesposito73** [comment]
is there any requirement on a linux box to use xpath filter?

**Comment by gschier** [comment]
@carmineesposito73 no, there's no requirement. If you're having troubles, please submit a new issue with an example so I can help you 👍
