### ISSUE TITLE
Suddenly won't launch. Unable to install.

### ISSUE THREAD

**Issue by ryanppax** [getinsomnia/insomnia#4949]
### Expected Behavior

I expected the program to launch

### Actual Behavior

Trying to run the installer throws a javascript exception
![image](https://user-images.githubusercontent.com/83292188/178058464-2ed8e82b-1181-4841-835c-752a7f0078b8.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.4.2

### What operating system are you using?

Windows

### Operating System Version

Win 10 Pro 21H2 19044.1766

### Installation method

windows installer

**Comment by rusprice** [comment]
Can reproduce. Run an older version. I am running v2022.4.2 and everything works fine.

**Comment by ryanppax** [comment]
So turns out. After checking with my IT department, it was a security policy. Not quite sure what was blocked because he wouldn't tell me but it even stopped local admin account from working
