### ISSUE TITLE
[Question] Sending two authorizations( session_id and WinAuth) as part of the request

### ISSUE THREAD

**Issue by haridak** [getinsomnia/insomnia#495]
[Question] – Unable to send session_id and NTLM Authorization

- Insomnia Version: v5.8.4
- Operating System: Windows 10

## Details
I need to test a REST API by sending Windows Authentication credentials and a session id. But when I pass both the credentials and the session_id, the WinAuth details are not taken into consideration and I get a 401 error. If I include just the WinAuth details, I get sesssion_id as invalid. Could someone please give some inputs on how to go about solving this problem?

**Comment by gschier** [comment]
He @haridak,

Can you give specific details on how you need to pass the WinAuth and session ID? Are they headers, cookies, etc, and what is the required format?

**Comment by haridak** [comment]
The session_id has to be part of the header. I am not sure where the WinAuth credentials need to be passed for the request to consume them. I am up for trying to include the WinAuth as part of cookies or header.

**Comment by gschier** [comment]
I just had a look at https://winauth.com/ and it looks like it would need a custom authentication scheme for Insomnia to support it. I'm not sure how it works exactly, but you may be able to write a plugin for it: https://insomnia.rest/documentation/plugins

**Comment by gschier** [comment]
Closing this issue for now, but feel free to respond if you have any more questions.
