### ISSUE TITLE
Convert Lazy component into a function component.

### ISSUE THREAD

**Issue by pavkout** [getinsomnia/insomnia#4968]
### Expected Behavior

Hello Insomnia,

I'll try to convert the lazy component into a function component.

### Actual Behavior

It's a Class component.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.5.0-beta.2

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey

### Installation method

download from insomnia.rest

**Comment by jackkav** [comment]
Closed by #4981
