### ISSUE TITLE
[Question] Access environmental values in plugins

### ISSUE THREAD

**Issue by chrisvdg** [getinsomnia/insomnia#499]
Is there a way to access or pass environmental values into a plugin?

Usecase: 
I'm trying to make a plug-in that returns a refreshed JWT based on the JWT set in the current environment.

**Comment by chrisvdg** [comment]
Found it, you can access them through the context
```js
module.exports.templateTags = [{
    // plugin properties....,
    async run (ctx, param1, param2) {
        console.log(ctx.context.envProperty);
        ...  
    }
}];
```

**Comment by gschier** [comment]
Hi @chrisvdg. The reason that it's undocumented is that the API for template tags is not finalized yet. You can use that for now but it may change in a future update.

**Comment by chrisvdg** [comment]
@gschier, will keep it in mind ;)
