### ISSUE TITLE
After upgrade i see a blank screen in insomnia, it works if i remove the app data and re-install. how can i get my API data back?

### ISSUE THREAD

**Issue by sathya652** [getinsomnia/insomnia#5007]
### Expected Behavior

i see all my API requests

### Actual Behavior

![image](https://user-images.githubusercontent.com/22477991/181026545-39a23a6a-c20f-450d-8fa3-da76cd27c241.png)

### Reproduction Steps

just update to latest release and you see the issue

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2022.4.2
Build date: 6/22/2022
OS: Windows_NT x64 10.0.19043
Electron: 18.1.0
Node: 16.13.2
V8: 10.0.139.15-electron.0
Architecture: x64

### Insomnia Version

2022.4.2

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.19043

### Installation method

update update by insomnia

### Last Known Working Insomnia version

i dont know

**Comment by filfreire** [comment]
Hi @sathya652 thanks for reporting this!

- Did you fully remove your App data folder when updating Insomnia?
- Have you by any chance used [Insomnia Teams](https://docs.insomnia.rest/insomnia/teams) to sync your collections in the past?

**Comment by sathya652** [comment]
No i copied the apps data to another location.
No i have not synced anything. How can i extract my api requests from
insomnia.Request.db ?
