### ISSUE TITLE
Importing Postman collection shows "Import failed [object Object]" after choosing workspace destination

### ISSUE THREAD

**Issue by CaiusJard** [getinsomnia/insomnia#5008]
### Expected Behavior

Collection imports

### Actual Behavior

A typical javascript failed "[object Object]" alert window appears

### Reproduction Steps

Drop down Create button
Import
From File
Choose File
New Workspace
Error appears

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Postman imports the collection OK. Re-exporting it in Postman as v2.1 produces a binary identical file. Exporting as 2.0 produces a smaller file, but this file still experiences the same error

I will send the file to supp***@ins*****.rest support email and ref this issue

### Insomnia Version

2022.4.2

### What operating system are you using?

Windows

### Operating System Version

Win10 Pro 21H2 19044.1826

### Installation method

Windows exe

**Comment by wongstein** [comment]
I have verified that this is the behavior, while looking at this other issue: https://github.com/Kong/insomnia/issues/2051.  There seem to be several issues related to Insomnia not handling hyphens in the variable names well.  I tested a sample postman import with removing the hyphen in the variable names and stopped seeing the "object Object" error box.

Could @CaiusJard give that a try and see if it works?

**Comment by CaiusJard** [comment]
Not sure I understand; the collection file I sent you guys doesn't have any hyphens in the variable names at all

For clarity, this is what I think of as a hyphen: `-`

And this is what I think is the variables:

![image](https://user-images.githubusercontent.com/68939130/181303175-6de9545c-65f0-4361-9209-2cfbba35e7b5.png)


I've Ctrl-F'd for `-` in the file and I only find them in data items such as negative numbers

**Comment by wongstein** [comment]
Ah, if you have emailed Insomnia Support, then I'll let insomnia support handle this ticket.  Also, a sample json would go a long way to helping us reproduce this issue.

**Comment by CaiusJard** [comment]
I raised this as a bug here, and I sent a sample file already to your support because I did not want to post the file publicly. Please handle the bug here, and use the file I submitted to support, but do not post the file into this ticket

**Comment by wongstein** [comment]
I have confirmed that the issue here are values in the spec which have a "." in them.  My recommendation is the replace them with Camel Case or a "-".  Doing so removes the import error.

**Comment by CaiusJard** [comment]
So, are you going to fix the bug or are you just posting this workaround we have to do?

**Comment by wongstein** [comment]
The unexpected behavior is on our backlog.  I'm posting the workaround because I think it's important for other people who are encountering the same thing, to have at least the work around.  And as always, we would welcome a contribution that fixes this from @CaiusJard or anyone else happening upon this issue in the meantime.

**Comment by MarvinJWendt** [comment]
Hi @wongstein, I don't think this issue should be closed, as it's not fixed. I stumbled over the same error, and it took me a little while to find this issue here.

**Comment by CaiusJard** [comment]
Agree; in our work stream we close issues after we fix them rather than after we put them on our backlog..

**Comment by MarvinJWendt** [comment]
Yes, this issue is also still marked as "unverified". Also, a closed issue will reduce the possibility of contributions from the community dramatically, as contributors look for open issues to fix 😉
