### ISSUE TITLE
"A JavaScript error occured in the main processs" Error popup

### ISSUE THREAD

**Issue by powtac** [getinsomnia/insomnia#5036]
### Expected Behavior

Insomnia should start

### Actual Behavior

A popup shows up, Insomnia does not start

![grafik](https://user-images.githubusercontent.com/36167/182377002-6499047a-0260-4cac-91bd-487d7d099556.png)

### Reproduction Steps

Try to start Insomnia, according to Windows installed programs this is the installed version:

![grafik](https://user-images.githubusercontent.com/36167/182377226-d3114d6e-93fa-407d-8c56-8e957624b855.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.4.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment]
Hi @powtac thanks for reporting this! 

- Do you still get this error if you attempt to run our [latest release (2022.5.0)](https://github.com/Kong/insomnia/releases/tag/core%402022.5.0) ?

Alternatively, I would also recommend you to for now delete (or rename) [Insomnia's data folder](https://docs.insomnia.rest/insomnia/application-data), which might help with this issue.

Let us know if any of this helped.

**Comment by powtac** [comment]
It still occurs at 2022.05.0

**Comment by powtac** [comment]
@filfreire Renaming the data folder did not help.

**Comment by filfreire** [comment]
@powtac I noticed looking at your screenshot the error message says something like:

> The operation could not be completed successfully because the file contains a virus or possibly unwanted software

I wonder - are you by any chance running any antivirus software AND/OR are trying to boot up Insomnia in a windows user account that perhaps doesn't have enough admin permissions?

Are you able to open Insomnia if you check `Run as administrator` in the properties of the Insomnia executable?

**Comment by griggsrl** [comment]
I'm getting this exact same issue trying to install/run the current version (2022.5.1) on Windows 11. 
![image](https://user-images.githubusercontent.com/3331954/187349201-21284928-4d52-4a4f-b046-246d6257cffe.png)

In my case I'm running Acronis Cyber Protect Home Office and it is blocking the generated tmp.node file that's getting created when it tries to start up and I can see it show up in the quarantine. I had an older version of Insomnia working fine on this system from a year or so ago and was trying to get the current version installed tonight but it is now very unhappy with something that has changed either with Insomnia or Acronis. Both clearing the Insomnia data directories and using the `Run as Administrator` option to run it don't seem to help at all unfortunately.

**Comment by kiwikern** [comment]
I have the same problem and also have Acronis Cyber Protect Home Office. I turned it off and switched back to Windows Defender. Now, it is working again.
