### ISSUE TITLE
[Bug] Insomnia reporting SSLRead() return error -9806

### ISSUE THREAD

**Issue by yghorbal** [getinsomnia/insomnia#504]
- Insomnia Version: 5.8.4 (5.8.4.1085)
- Operating System: macOS 10.12.6 (16G29)

## Details

When issuing a GET request to a webservice Insomnia reports ERROR : 

```
* Received 1269 B chunk
* SSLRead() return error -9806
* Closing connection 33
```

Here's the full timeline (anonymized)

```
* Preparing request to https://domain.com/api/v2/axxxxx/login/xxxxx/
* Enable automatic URL encoding
* Disable SSL validation
* Enable cookie sending with jar of 0 cookies
* Hostname domain.com was found in DNS cache
*   Trying xxx.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to domain.com (xxx.xxx.xxx.xxx) port 443 (#33)
* WARNING: disabling hostname validation also disables SNI.
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: domain.com
* Server certificate: TERENA SSL High Assurance CA 3
* Server certificate: DigiCert High Assurance EV Root CA
> GET /api/v2/axxxxx/login/xxxxx/ HTTP/1.1
> Host: domain.com
> User-Agent: insomnia/5.8.4
> Accept: */*
> Accept-Encoding: deflate, gzip
> Authorization: Token XXXXXXXXXXXXXX
> Content-Type: application/json
> Content-Length: 0
< HTTP/1.1 200 OK
< Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
< Vary: Accept, Cookie, Accept-Language
< Content-Type: application/json
< Content-Language: fr
< Strict-Transport-Security: max-age=15768000; includeSubDomains
* no chunk, no close, no size. Assume close to signal end

* Received 1269 B chunk
* SSLRead() return error -9806
* Closing connection 33
```

When doing the same request with curl (the one shipped with macOS) I have the same error message but I have the JSON output anyway :

```
/usr/bin/curl --request GET   --url https://domain.com/api/v2/axxxxx/login/xxxxx/   --header 'authorization: Token 
XXXXXXXXXXXXXX'   --header 'content-type: application/json'
curl: (56) SSLRead() return error -9806
{"id":12457,"login"....}
```

When using MacPorts curl, everything is working great (no error messages) :

```
/opt/local/bin/curl --request GET   --url https://domain.com/api/v2/axxxxx/login/xxxxx/   --header 'authorization: Token 
XXXXXXXXXXXXXX'   --header 'content-type: application/json'
{"id":12457,"login"....}
```

Googling around the error message seems to point to an issue around Apple's SecureTransport Framwork, and the shipped curl is linked to it (the MacPorts curl is linked to OpenSSL) I didn't found anything regarding the root cause of this, but every post regarding it provides a workaround by using the homebrew curl (or rebuilding the homebrew one against OpenSSL instead of SecureTransport.

I don't have enough knowledge regarding Apple internals so I can't digg further (but I can help by running debug stuff if you want)

In the meantime is there anyway to make Insomnia use another curl other that the one shipped with the system ? Or maybe have a similar behaviour as the system's curl (by ignoring this specific error and providing the output anyway)

**Comment by yghorbal** [comment]
I've also found [this Stackoverflow post](https://stackoverflow.com/questions/26461966/osx-10-10-curl-post-to-https-url-gives-sslread-error) explanation that fits our use case :

> I've seen this error happen when php is compiled with a version of cURL that uses Apple's Secure Transport under Yosemite and the target of the URL request doesn't support SSLv3 (which was probably disabled due to the POODLE vulnerability). What is the output of this command?

And I've just checked, SSLv3 is disabled on the target server.

**Comment by gschier** [comment]
Can you try re-enabling SSL validation in the settings? I think that's what's causing the issue.

... On my phone so can't provide details at the moment.

**Comment by yghorbal** [comment]
I've already tested with SSL validation enabled, same outcome.

```
* Preparing request to https://domain.com/api/v2/axxxxx/login/xxxxx/
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Hostname domain.com was found in DNS cache
*   Trying xxx.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to domain.com (xxx.xxx.xxx.xxx) port 443 (#33)
* WARNING: disabling hostname validation also disables SNI.
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: domain.com
* Server certificate: TERENA SSL High Assurance CA 3
* Server certificate: DigiCert High Assurance EV Root CA
> GET /api/v2/axxxxx/login/xxxxx/ HTTP/1.1
> Host: domain.com
> User-Agent: insomnia/5.8.4
> Accept: */*
> Accept-Encoding: deflate, gzip
> Authorization: Token XXXXXXXXXXXXXX
> Content-Type: application/json
> Content-Length: 0
< HTTP/1.1 200 OK
< Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
< Vary: Accept, Cookie, Accept-Language
< Content-Type: application/json
< Content-Language: fr
< Strict-Transport-Security: max-age=15768000; includeSubDomains
* no chunk, no close, no size. Assume close to signal end
```

**Comment by gschier** [comment]
Hmm, that's interesting. I recall that having fixed the problem in some other cases.

Are you able to provide a public URL that I can use to reproduce the problem and debug further?


As for using a different Curl version. There is some discussion of this in #302 but I don't think anyone has been successful at achieving it yet.

**Comment by yghorbal** [comment]
Hello, you can test it by doing a GET on https://pasteurid.pasteur.fr/

**Comment by gschier** [comment]
Do you have a URL that returns a `200` instead of a redirect (`302`)?

**Comment by yghorbal** [comment]
Of course, you can use https://pasteurid.pasteur.fr/password/

**Comment by gschier** [comment]
Hey @yghorbal,

Your last URL seems to be working for me on MacOS 10.13. 

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/587576/32295992-355226ae-bf4b-11e7-8ef1-f05d918fb2e1.png">

**Comment by gschier** [comment]
Going to close this issue for now, as I cannot reproduce it anymore. Feel free to respond if it happens again.

**Comment by hjkelly** [comment]
For what it's worth, I could reproduce @yghorbal's problem (both with his URL and several of ours). Insomnia seems to use the built-in cURL libraries on macOS, and this SSLRead error is a known problem with that cURL library on macOS 10.12. I was able to fix the `curl` command using a Homebrew workaround, but since Insomnia uses the official macOS cURL libraries, it's still affected by this problem. Both `curl` and Insomnia work fine on macOS 10.13, and on Linux. That probably explains why you couldn't reproduce it, @gschier.

The Timeline tab is tremendously helpful now that I know about it, but unfortunately my CTO and I spent about a month unable to use Insomnia because I only saw the generic `Error: Failure when receiving data from the peer`. In contrast, the built-in `curl` command outputs the response data in spite of the SSLRead error, and Postman also works fine (though it may use something different than cURL altogether). To be explicit, there must be some server-side factor that triggers this error, but we're stumped as to why.

Could Insomnia be updated to show the response status, headers, and data it is receiving, even in the case of SSL errors?

**Comment by nguyenjulian** [comment]
@gschier Can we reopen this issue? I am experiencing the same issue here. The URL that I am having issues with is an internal company URL so don't want to share all of the details, but here is what I am seeing from my Timeline. 

```
* Preparing request to **************
* Using libcurl/7.61.1 SecureTransport zlib/1.2.11
* Current time is 2020-05-18T20:46:55.695Z
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 6 cookies
* Hostname ********** was found in DNS cache
*   Trying ************...
* TCP_NODELAY set
* Connected to ********** port 443 (#34)
* ALPN, offering http/1.1
* TLS 1.2 connection using TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate: ********
* Server certificate: COMODO RSA Extended Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority

> GET *********************************
HTTP/1.1
> Host: *****************
> User-Agent: insomnia/7.1.1
> apiKey: ***********************
> Accept: */*

< HTTP/1.1 200 OK
< Date: Mon, 18 May 2020 20:46:55 GMT
< Content-Type: application/json;charset=UTF-8
< Connection: keep-alive
< X-Vcap-Request-Id: ************************
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: origin, x-requested-with, accept
< Access-Control-Max-Age: 3628800
< Access-Control-Allow-Methods: GET,POST

* no chunk, no close, no size. Assume close to signal end



* Received 11.6 KB chunk
* SSLRead() return error -9806
* Closing connection 34
```

I am able to successfully copy the raw CURL command into my Terminal and get a response so I believe Insomnia should be allowing me to get a 200 as well. Thank you!
