### ISSUE TITLE
Insomnia Installation Failed

### ISSUE THREAD

**Issue by avetis-avagyan** [getinsomnia/insomnia#5049]
### Expected Behavior

When I run the `Insomnia.Core-2022.5.0.exe` executable, it is supposed to Install and Setup Insomnia.

### Actual Behavior

[SquirrelSetup.log](https://github.com/Kong/insomnia/files/9269824/SquirrelSetup.log)
I get this setup error log when I try to install

### Reproduction Steps

1. Download the executable from the Insomnia website
2. Run it

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I had Insomnia 4.2 previously that worked perfectly, but when I tried running it, I got an error. I uninstalled it and redownloaded the latest version and now I can't install the app. This issue was closed 4 days ago without any fixes: https://github.com/Kong/insomnia/issues/1903

### Insomnia Version

2022.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Version 10.0.22000 Build 22000

### Installation method

https://insomnia.rest/download

### Last Known Working Insomnia version

2022.4.2

**Comment by filfreire** [comment]
Hi @avetis-avagyan thanks for reporting this!

I noticed on your SquirrelSetup.log that you have a handful of installation attempts with an error similar to:
```
2022-07-12 14:22:37> Program: About to install to: C:\Users\Avetis\AppData\Local\insomnia
2022-07-12 14:22:37> Program: Install path C:\Users\Avetis\AppData\Local\insomnia already exists, burning it to the ground
2022-07-12 14:22:37> IEnableLogger: : System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.Kill()
   at Squirrel.UpdateManager.InstallHelperImpl.<>c__DisplayClass6_1.<KillAllProcessesBelongingToPackage>b__2()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
```

Do you have any limitations on your Windows account and are you able to install Insomnia if you try to run setup as an Admin user (or by going to properties of the file and checking the `Run as administrationr` option)?

Are you able to reproduce this on another windows computer with a different account setup?

**Comment by wongstein** [comment]
Closing this issue due to lack of response
