### ISSUE TITLE
Cannot use Send And Download Feature without a environment selected

### ISSUE THREAD

**Issue by WeskleyP** [getinsomnia/insomnia#5061]
### Expected Behavior

When i try to use send and download feature without an environment is selected, the button doesn't work properly

### Actual Behavior

On the older version, i was able to use send and download feature without a need to select an environment

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

download from insomnia

### Last Known Working Insomnia version

2022.4.2

**Comment by filfreire** [comment]
Thanks for reporting this @WeskleyP, I can also reproduce it 👍  

We'll try to fix this as soon as possible.

**Comment by filfreire** [comment]
Hi @WeskleyP, the fix for this issue is now included in of our [latest beta release (2022.6.0-beta.1)](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.1). Feel free to report any other issues you come across.
