### ISSUE TITLE
Can't sync cloned git repository: "This repository is already connected to Insomnia;"

### ISSUE THREAD

**Issue by calmon-mms** [getinsomnia/insomnia#5070]
### Expected Behavior

Being able to sync my cloned repo so I can commit/pull/push/merge.

### Actual Behavior

Right now, I can simply clone my repository through dashboard, but it is not being synced, no matter what I do:

When cloned from dashboard the repository is downloaded once, but not synced, then I tried to click in the button "Setup Git Sync" > "repository settings" > "Git [tab]",  and always prompt the follow message:

> "This repository is already connected to Insomnia; try creating a clone from the dashboard instead."

I've already deleted and downloaded again, uninstalled the application entirely, deleting all the files, deleted Insomnia folder inside "Library/Application Support" and the issue still persists.

### Reproduction Steps

1. Open Insomnia
2. Create > Git Clone > Github > Login
3. Create > Git Clone > Git > Fill Data > Sync
4. Open the document cloned
5. Project download, but not synced
6. Setup Git Sync > Repository Settings > Git > Fill Data > Sync
7. "This repository is already connected to Insomnia; try creating a clone from the dashboard instead."

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

As a matter of test, I tried manually to create a sync editing the files: insomnia.GitRepository.db and insomnia.WorkspaceMeta.db.
This has partially worked, the sync is recognised and I'm able to commit and create branches, but not able to pull.

Another thing I realised is: My cloned repository is not available in the folder "Library/Application Support/version-control", not even when after 'manually synced', and I don't know if insomnia's git plugin store this data on somewhere else with another name that can't be found via grep (I've search the entire machine so for the repo name and nothing was found).

### Insomnia Version

2022.5.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### Installation method

download from insomnia.rest, homebrew

**Comment by filfreire** [comment]
Hi @calmon-mms, thanks for reporting this! I have a few questions to help us debug this:

- Is there any reason why you are trying to initially clone the repository on `Create > Git Clone > Git` tab instead of `Create > Git Clone > GitHub` tab?

- Are you able to consistently get this behaviour with other Git repositories or even other Git providers? (e.g. Gitlab)

- If you open Dev Tools on Insomnia, do you notice any error or exception logs when doing the initial clone of the repository? (If yes, can you share those?)

**Comment by calmon-mms** [comment]
> Hi @calmon-mms, thanks for reporting this! I have a few questions to help us debug this:
> 
> * Is there any reason why you are trying to initially clone the repository on `Create > Git Clone > Git` tab instead of `Create > Git Clone > GitHub` tab?
> * Are you able to consistently get this behaviour with other Git repositories or even other Git providers? (e.g. Gitlab)
> * If you open Dev Tools on Insomnia, do you notice any error or exception logs when doing the initial clone of the repository? (If yes, can you share those?)

- Yes, I've tried using the other method also, nevertheless without any success. :/
- Yes, I tried another random repository and it seems to work just fine, it is like the repo I need is stored somewhere and not ever been deleted, as I mentioned, even after successfully cloned the repository it is not available inside /version-control folder and therefore the sync can't be stablished.
- This is the only error in the console, doesn't seems related.
- `mem-client.ts:350 Uncaught (in promise) Error: ENOTDIR: not a directory, scandir '.insomnia/insomnia-env.gif'
    at new ip (system-error.ts:36:19)
    at t3._assertDirEntry (mem-client.ts:350:13)
    at t3._assertDir (mem-client.ts:365:5)
    at t3.readdir (mem-client.ts:184:5)
    at j4.onConfirm [as _okCallback2`

**Comment by topsoft-support** [comment]
@filfreire  The tip: "This repository is already connected to Insomnia; try creating a clone from the dashboard instead."

My step:

1. `Dashboard` -> `Create` -> `Git clone`  (Git [tab])
2. `Repository Settings` (in document)
3. click `reset`
4. click `Setup Git Sync`
5. `Repository Settings`
6. (Git [tab]) again...
7. now, you will see the tip.

**Comment by gryphon** [comment]
It is happenning oftern.

First the repository pull/push stopped working with error like "cannot parse repository URL: '' "
Repository URL disappearing every third push.

After entering same URL again this error will prevent to fix the problem.

**Comment by Jayuda** [comment]
> It is happenning oftern.
> 
> First the repository pull/push stopped working with error like "cannot parse repository URL: '' " Repository URL disappearing every third push.
> 
> After entering same URL again this error will prevent to fix the problem.

Bump, i also faced with this problems.

**Comment by caetanoharyon** [comment]
It's happening on ubuntu too

**Comment by caetanoharyon** [comment]
I don't have access to a Dashboard. I only have the individual plan. And the only reason I have this plan isn't working. Please, I kindly ask, fix it

**Comment by gatzjames** [comment]
👋 @calmon-mms and everyone. Thanks for the feedback. We have done some updates to how git sync works in the latest versions. I tried to reproduce this in the latest release and seems that it's not an issue anymore. Going to close this but feel free to reopen if the issue still exists.

@caetanoharyon by Dashboard i think @topsoft-support means the project view where you can select the Create dropdown and chose to clone from git
<img width="890" alt="image" src="https://user-images.githubusercontent.com/12115431/235647003-1e5e0a37-e384-4d53-abce-4fb2da8218ad.png">
