### ISSUE TITLE
New version start consume 50% cpu and became very slow

### ISSUE THREAD

**Issue by p8bin** [getinsomnia/insomnia#5077]
### Expected Behavior

Fast

### Actual Behavior

Very slowly

### Reproduction Steps

Install
Create 400 tabs

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2022.5.0
Build date: 02.08.2022
OS: Windows_NT x64 10.0.19043
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64

### Insomnia Version

2022.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.19043

### Installation method

exe install from https://insomnia.rest/download

**Comment by filfreire** [comment]
Hi @p8bin, thank you for reporting this!

We're aware that there are a handful of performance issues, and we are tracking those [here](https://github.com/Kong/insomnia/issues?q=is%3Aopen+is%3Aissue+label%3AB-performance).

We'll likely be looking into these performance issues sometime in the future. Feel free to report any other issues you come across!
