### ISSUE TITLE
[Bug] 414 returned without explanation

### ISSUE THREAD

**Issue by dukc** [getinsomnia/insomnia#508]
When I was making a "GET" request with JSON content, it one day suddently started returning "414 length required" - codes. Trying to log in again and using the new token didn't help.

It may have something to do with that I used both the header tab and authentication tab to do authentication, trough the tokens were the same. They were bearer tokens. When I switched the auth tab to "no auth" but kept the auth at header it started to work again.

For some reason, the bug didn't kick back in when I tried to use both tabs for the token again. I do not know what triggered it.

Version is 5.8.4.

**Comment by gschier** [comment]
Hmm, that's strange. Did you check the Timeline tab to see if anything strange was being sent by accident?

**Comment by dukc** [comment]
I'm still new. It didn't occur to me to do that, sorry.

**Comment by gschier** [comment]
No worries @dukc! Let me know if it happens again 😄 

Going to close this one for now.
