### ISSUE TITLE
Changes in custom method are not applied

### ISSUE THREAD

**Issue by MarieR12** [getinsomnia/insomnia#5083]
### Expected Behavior

Clicking 'done' or hitting enter after entering a custom method will apply the changes.

### Actual Behavior

Changing the method to a custom method works almost never. I have used custom methods in the past and it does not matter whether I pick one of those methods that I have used before or enter the method manually, the changes are not applied. Picking a standart method from the dropdown does work. 

Duplicating requests with custom methods works. 

Very rarely changing the method to a custom method does also work.
I cannot make out any pattern in this behaviour.

Reinstalling did not help.

### Reproduction Steps

1. Select a request
2. Click the dropdown next to the method
3. Click 'Custom Method'
4. Pick one of the methods from previous changes or enter another method
5. Hit 'Done' or press enter
6. The method of the request remains unchanged

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro, version 21H2

### Installation method

downloaded from insomnia.rest

**Comment by filfreire** [comment]
Hi @MarieR12, thanks for reporting this!

Indeed I can reproduce these behaviours consistently:

- If I try to pick any existing Custom Method, I'm not able to, and whichever I pick is not reflected back:
![Pasted_Image_16_08_2022__13_23](https://user-images.githubusercontent.com/11976836/184878802-3efeb232-2521-4fd4-babf-0750dc0e1566.png)

- Pressing `Enter` on the dialogue right after writing a new custom method does not add it, only by clicking `Done` button is the method added and switched over to. And this is only working if the method didn't exist before.

Seems as well that the first issue was introduced between `2022.4.2` and `2022.5.0`, and the second was existing before that.

We'll update you here as soon as a fix is in place. Feel free to report other issues you come across!
