### ISSUE TITLE
[Bug] AWS IAM auth support not complete

### ISSUE THREAD

**Issue by wonderbeyond** [getinsomnia/insomnia#509]
- Insomnia Version: v5.8.4
- Operating System: Ubuntu 16.04.3 LTS

## Details

When using `GET/POST` methods it works OK, but not for `PUT` method:

![image](https://user-images.githubusercontent.com/228361/31366266-983d71e8-ada2-11e7-9283-6d5087941dda.png)

![image](https://user-images.githubusercontent.com/228361/31366295-bffbe2be-ada2-11e7-92a9-65fcf7508732.png)

**Comment by gschier** [comment]
It looks like the HTTP method isn't being passed into the `aws4` library. This works for `GET` and `POST` currently because the library assumes `GET` or `POST` based on whether a body is passed. I'll push a quick commit to add method.

**Comment by hunterhug** [comment]
@wonderbeyond  You can use my aws IAM v4 proxy tool for walkaround.

https://github.com/hunterhug/GoProxy

@gschier Please note `*`(used in ElasticSearch, e.g. `/m*` to find indices by glob) in URL.
