### ISSUE TITLE
[Epic] Plugin Framework

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#51]
Insomnia should support the ability to build full-featured plugins on top of. Due to the low performance requirements that Insomnia plugins will have, HTTP would be an ideal protocol for plugin communication. HTTP-based plugins are not as easy to write or run, but maybe that's not a problem.

How it would work:

- write a web server with certain endpoints to respond to _hooks_
    - `/plugin-info` to define plugin behavior
    - `/pre-render` to set up env and stuff
    - `/pre-request` to do things like auth and stuff
    - `/post-request` to handle the response (set env vars, etc)
- app would contact plugins when hooks are triggered
- plugins would respond with certain commands for the app
    - `set-env-var`
    - `add-cookie`
    - etc...

## Random List of Use Cases

- Custom authentication
- Storing and refreshing authentication tokens
- Computing environment variables

**Comment by Andreyco** [comment]
How would be plugin associated with Insomnia app?

**Comment by gschier** [comment]
@Andreyco If plugins are HTTP-based like the description states, I don't see any clear elegant solutions. If plugins were run as JS child processes it would be much easier.

Here are a few ideas I had so far:

- plugin contains manifest file which describes how to interact with it
- plugin adds itself by pinging the Insomnia app through a protocol request: `insomnia://plugins/add?...`

Any other ideas?

**Comment by Andreyco** [comment]
Is it possible to associate schema/file extension to Electron application? If so, plugin could be packed as archive of target type. When opened, it could be copied to Insomnia sandbox (or whatever Electron offers) and run after restart.

We should copy Chrome/Firefox behaviour here.

Also, there should be mechanism to run Insomnia without running plugins in case something breaks ;)

**Comment by gschier** [comment]
@Andreyco I think it's an awesome idea to model this system after the way browsers do it. 

Like Chrome's `.crx` extension files, Insomnia could have a `.insomnia` extension. The package format could be a simple zip file with the extension renamed.

There are ways to set an Electron app to open certain file extensions (I'm pretty sure), but they could also be added via an open dialog, drag-n-drop handler, or command line interface.

**Comment by ValeriaVG** [comment]
I believe it can be a good idea to mimic not chrome by atom's plug-ins system http://flight-manual.atom.io/using-atom/sections/atom-packages/
It looks completely possible to store plug-ins remotely, besides that there are some extra pros:

- plug-in can have it own dependencies
- no need to implement a new file type and methods to work with it

I'll leave the link to atom package manager here for you to take a look https://github.com/atom/apm

**Comment by gschier** [comment]
@ValeriaVG there is also https://hyper.is/ which piggy-backs on npm for plugins. That might be a good thing to start with.

After taking a peek, it looks like apm is just a small wrapper around npm.

**Comment by ValeriaVG** [comment]
@gschier Yes, it's just a wrapper. And hyper looks promising at first sight. But how it will work with http - based plug-ins?

**Comment by gschier** [comment]
Closing this one, as a basic plugin system is underway, and future work will be done as smaller, separate tasks.
