### ISSUE TITLE
[Feature Request] Environment Variables in Edit Tag modal

### ISSUE THREAD

**Issue by Gabb1995** [getinsomnia/insomnia#510]
I currently have my own tag which creates a WSSE Header, this accepts 6 parameters and I use it as a header in all my requests. 

When I have to change 1 parameter, I have to change the same parameter in all my requests. If I could set an environment variable for each parameter and be able to edit just the environment variable that would be great.

**Comment by Gabb1995** [comment]
I see that there already is an issue related to this https://github.com/getinsomnia/insomnia/issues/499 I have solved my issue with the comment in that thread. But I think it would still be nice to have this feature implemented.

**Comment by gschier** [comment]
Hi @Gabb1995. I definitely plan to add a way to reference environment variables directly in the tag editor, although I can't give you a release date yet.

There is another workaround, but it's not very pretty.

If you copy the tag, it will look something like this:

```
{% my_tag 'arg1', 'arg2' %}
```

You can change these from static values to variables by specifying args without quotes:

```
{% my_tag 'arg1', my_variable %}
```

It sounds like you have a solution already, but I felt like mentioning this just in case.
