### ISSUE TITLE
Drag and Drop no longer working in sidebar

### ISSUE THREAD

**Issue by darcyrush** [getinsomnia/insomnia#5101]
### Expected Behavior

Folders and requests can be drag and dropped to reorder them in the sidebar, and to move them into folders

### Actual Behavior

Folders and requests can no longer be drag and dropped to reorder them in the sidebar, nor to move them into folders

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.5.1

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### Installation method

apt

**Comment by kreosus** [comment]
Hi @darcyrush 
Do you see the same behavior with our latest release located here: https://github.com/Kong/insomnia/releases/tag/core%402022.6.0-beta.4

**Comment by darcyrush** [comment]
@kreosus Issue still persists with 2022.6 beta.4 installed via deb

**Comment by filfreire** [comment]
Possibly this is closed by - https://github.com/Kong/insomnia/pull/5168

**Comment by filfreire** [comment]
@darcyrush this will be fixed in out upcoming `2022.6.0` release.

**Comment by trojkat** [comment]
@filfreire It still doesn't work 😿 
```
Version: Insomnia 2022.6.0
Build date: 26.09.2022
OS: Linux x64 5.12.19-1-MANJARO
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64
```
![drag-and-drop](https://user-images.githubusercontent.com/97532/197756839-9676e5a2-9e14-4c4d-998c-2a6e1bd257bc.gif)

**Comment by jmoniatte** [comment]
Same here, it does not work on Debian either.

```
Version: Insomnia 2022.6.0
Build date: 9/26/2022
OS: Linux x64 5.10.0-18-amd64
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64
```
