### ISSUE TITLE
[Bug] Uncaught (in promise) TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Gabb1995** [getinsomnia/insomnia#514]
- Insomnia Version: 5.8.4
- Operating System: Ubuntu 17.04

## Details

```
Uncaught (in promise) TypeError: Cannot read property 'type' of undefined
    at getTags (code-editor.js:445)
    at <anonymous>
getTags @ code-editor.js:445
```

Happens when plugin has no variables.

**Comment by gschier** [comment]
Thanks for reporting this @Gabb1995. It was fixed in https://github.com/getinsomnia/insomnia/commit/5b9db10060befc72dbd45c93acbb9b5b1a6a5c69
