### ISSUE TITLE
Pressing the "return" key on Mac to select an environment variable in the URL also sends an HTTP request

### ISSUE THREAD

**Issue by RafaFreitasNog** [getinsomnia/insomnia#5141]
### Expected Behavior

Pressing return key should **only** trigger the environment variable selection in the URL.

### Actual Behavior

Pressing return is triggering the variable selection **and also sending an HTTP request**.

### Reproduction Steps

1. Type something on the URL 2. Use the up and down keys to switch between the recommended suggestions 3. Press the "return" key to select the desired variable 4. The **Bug** where Insomnia also sends and HTTP request will occur 5. <img width="1007" alt="Captura de Tela 2022-09-06 às 18 52 05" src="https://user-images.githubusercontent.com/80215289/188747532-03b61423-f3fb-4909-9f4a-354de9c87bde.png">
6. <img width="1008" alt="Captura de Tela 2022-09-06 às 18 52 22" src="https://user-images.githubusercontent.com/80215289/188747553-6b58d784-8ae8-498a-afe9-7a7d277ec43c.png">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.5.1

### What operating system are you using?

macOS

### Operating System Version

macOs Monterrey v12.5

### Installation method

downloaded at https://insomnia.rest/pricing by clicking "Download App"

**Comment by filfreire** [comment]
Hi @RafaFreitasNog, thanks for reporting this! We can also reproduce it.

**Comment by filfreire** [comment]
This should be fixed in https://github.com/Kong/insomnia/releases/tag/core%402022.7.5
