### ISSUE TITLE
[Bug] Can't manage cookies if used environment variable is deleted

### ISSUE THREAD

**Issue by zygis** [getinsomnia/insomnia#516]
- Insomnia Version: 5.9.1.1184
- Operating System: MacOS 10.13

Steps to reproduce:
1. Create environment variable
2. Create cookie with value {{envVariableName}}
3. Delete environment variable
4. Try to add/edit/delete cookie...

Behavior: 
Nothing happens when clicking "Cookies" or "Manage Cookies"

Expected behavior: 
Ability to change value or at least ability to delete cookie

Workaround:
Remember what environment variables were deleted and restore them

**Comment by gschier** [comment]
Thanks for reporting this @zygis! I'll get it fixed 😄
