### ISSUE TITLE
[Feature Request] support for path variables

### ISSUE THREAD

**Issue by pklopotowski** [getinsomnia/insomnia#519]
Would be nice to have a support for path variables:
`/users/{userId}/numbers`
Currently we can only use an environment variable in that case. But this is a very inconvenient way and inflexible because this parameter may change for each request and is environment independent.

**Comment by gschier** [comment]
Thanks for the request @pklopotowski! This is probably a duplicate of #203

**Comment by pklopotowski** [comment]
@gschier Definitely, this is the same type of requirements. I was searching for _[Feature Request]_ marker, but #203 is marked as _[Proposal]_, my inattention.
But let's focus on the problem. As you wrote, it may be done by placeholders. This gives us flexibility and shows a changeable/configurable part of a request.

**Comment by gschier** [comment]
Exactly, meaning it can work for other things besides URL path variables. 😄

**Comment by gschier** [comment]
Closing this one, as #203 seems like an appropriate solution.

**Comment by pklopotowski** [comment]
ok, thx. I will be waiting for this feature

**Comment by mpern** [comment]
Any chance that #203 gets added to this roadmap?

It has a lot of upvotes and a glaringly missing feature of Insomnia.

**Comment by phylor** [comment]
Note that #203 proposes to use a special kind of template syntax such as `{% my_variable %}` within the URL. When importing Open API specifications, the URL will contain `{my_variable}` (as the OP suggests). So this might not be the exactly same use case.

**Comment by mugi-luffy** [comment]
this should not be closed
insomnia should support open api path parameters {my_variable} and allow to set them the same way as query parameters.
Postman does the exact same thing

**Comment by dmitriybraginets** [comment]
Hi! Any progress here?

**Comment by quiquelhappy** [comment]
why is this closed? lol

**Comment by remy727** [comment]
Any update on this?

**Comment by risalfajar** [comment]
This is so sad, someone has even [done this for them](https://github.com/Kong/insomnia/issues/203#issuecomment-691710227), and they choose to ignore him.
