### ISSUE TITLE
Plugin hub is down

### ISSUE THREAD

**Issue by ppazos** [getinsomnia/insomnia#5194]
### Expected Behavior

Show all plugins, including randomnumber.

### Actual Behavior

Only shows 20 plugins and can't find the randomnumber one I need.

### Reproduction Steps

1. check the plugin hub
2. plugin is not there

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

web

### What operating system are you using?

Other Linux

### Operating System Version

Mint 21

### Installation method

deb

### Last Known Working Insomnia version

web

**Comment by filfreire** [comment]
Hi @ppazos, thanks for reporting this! We can also reproduce this internally.

**Comment by ppazos** [comment]
@filfreire thanks, I was able to install it from the npm repo after I found it there, but took a little searching to find it there.

**Comment by filfreire** [comment]
@ppazos this should be fixed now.

It has something to do with a possible bug on npmjs.com, related with this issue: https://github.com/npm/feedback/discussions/769

Internally some team members have deployed a workaround, and you should see results now on the plugin hub.

Feel free to report any other issues you come across!
