### ISSUE TITLE
[Bug] Can't click on scrolled item in Query tab

### ISSUE THREAD

**Issue by jdmichel** [getinsomnia/insomnia#520]
- Insomnia Version: 5.9.0
- Operating System: Windows 10 latest

## Details

I am using Insomnia to test out a vendor's web api, and depending on the URL they take dozens of different parameters. I have several versions of each parameter value in the Query tab, and I check/uncheck each one depending what I want to send to a particular resource. 

Once there are more params than fit into the Insomnia window, you can scroll to view params at the bottom of the list. The problem is that you can't click them (e.g. checkbox to enable/disable), because MouseDown has a sideeffect of resetting the scroll position to the top. 

A workaround is to move Insomnia to a larger monitor that doesn't need a scroll bar.

**Comment by gschier** [comment]
Hmm, I can't seem to reproduce this on my end. Are you able to paste a quick screen recording of the issue

**Comment by jdmichel** [comment]
In the attached video I simply opened Insomnia, then I left click something at the top, scroll with the mouse wheel to the bottom, left click something at the bottom, scroll with mouse wheel to the top (if necessary), repeat. 
The unwanted scrolling happens as soon as I mouse down (haven't released the mouse button). Even the first click on the value 520 shows a small unwanted/unnecessary scroll, but later in the video the window scrolls more on mouse down making it impossible to use. 
As I workaround I can drag the window to my larger monitor (4K) which eliminates the scroll bar, allowing me to click or delete rows. 

[Bug520_CantClickScrolledItem.zip](https://github.com/getinsomnia/insomnia/files/1382672/Bug520_CantClickScrolledItem.zip)

**Comment by CamusAran** [comment]
Happening to me too.

Another workaround is to use the keyboard. Tab to select input, spacebar to check/uncheck, delete with backspace (the delete button isn't "tabbable").

**Comment by gschier** [comment]
Quick question. Does this also happen in the headers tab if you add a lot of headers?

**Comment by CamusAran** [comment]
> Quick question. Does this also happen in the headers tab if you add a lot of headers?

Yes.

**Comment by gschier** [comment]
Hmm, okay. I will try and have a look this week. Seems like it might be some sort of race condition. I was able to make it happen on my machine but only every 1 and 50 attempts.

**Comment by gschier** [comment]
I'm happy to announce that this is now fixed! Was hard to track down, but ended up being a one line fix 😄
