### ISSUE TITLE
Upgrade to Node 18

### ISSUE THREAD

**Issue by yonas** [getinsomnia/insomnia#5206]
### Expected Behavior

Be compatible with NodeJS v18.

### Actual Behavior

Only compatible with Node v16.

### Reproduction Steps

1. Install Node 18
2. Clone latest repo
3. Run `npm run bootstrap`

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

5c109ac4969bd6a9a29ce60e7fa0550a9fe40e8a

### What operating system are you using?

Other (specify below)

### Operating System Version

FreeBSD 13.1

### Installation method

Git clone ; npm run bootstrap

### Last Known Working Insomnia version

N/A

**Comment by yuhwaa** [comment]
Hi! I'd like to work on this. I am a newbie but this is my understanding:
1. Install Node 18 
2. Clone latest repo
3. Run npm run bootstrap
4. and after this do I send s pull request?
Thank you!

**Comment by yonas** [comment]
@yuhwaa  Yes. A high level overview:

- remove `.nvmrc`
- add the following to `package.json`:
```
"engineStrict": true,
"engines": {
    "node": ">=16.0.0"
 },
```

**Comment by jackkav** [comment]
Hi @yonas and @yuhwaa unfortunately node version and electron version must be in sync. There is no electron build which will work with node 18 currently. The latest electron version is 20 which requires node v16.15.0. I have an open PR for it but its blocked. Can I ask what feature of node 18 would make this desirable?

https://www.electronjs.org/releases/stable
#5173

**Comment by yonas** [comment]
@jackkav On FreeBSD 13, the default node version is 18, although it's possible to install node 16.16.0.

It would be great to be able to build a web app only build so I can run insomnia headless on a dedicated server.

**Comment by jackkav** [comment]
Due to current insomnia architecture a web version is still a long way off, although it would be handy. Electron is moving fast, we might see a node 18 version in the next 12 months 🤞
