### ISSUE TITLE
Environment variables unable to be overridden when nesting past four levels 

### ISSUE THREAD

**Issue by bbbco** [getinsomnia/insomnia#5218]
### Expected Behavior

Given an environment with variables nested more than four levels deep such as:
```
{
	"foo1": {
		"foo2": {
			"foo3": {
				"foo4": {
					"foo5": "bar"
				}
			}
		}
	}
}
```
and a sub-environment that overrides it:
```
{
	"foo1": {
		"foo2": {
			"foo3": {
				"foo4": {
					"foo5": "boo"
				}
			}
		}
	}
}
```

I should be able to refer to it inside of Insomnia using the following nunjuck: `{{ _.foo1.foo2.foo3.foo4.foo5 }}`

### Actual Behavior

When I reference the nunjuck tag like `{{ _.foo1.foo2.foo3.foo4.foo5 }}`:
![image](https://user-images.githubusercontent.com/30680/192051115-db771dd2-a7fa-43e2-a068-bdcb76e77d23.png)

When I click on the tag to edit it, I get a screen like so (only allowing me to select to the fourth level):
![image](https://user-images.githubusercontent.com/30680/192051395-faa9275a-0f4d-4d2a-80e6-14e536158862.png)

So, if I select the fourth level and reference the nunjuck tag like `{{ _.foo1.foo2.foo3.foo4 }}`:
![image](https://user-images.githubusercontent.com/30680/192051537-91b21e93-0ea4-4d58-8298-a1299220806e.png)

### Reproduction Steps

1. Add a new base environment variable that is nested five levels deep, i.e. 
```
{
	"foo1": {
		"foo2": {
			"foo3": {
				"foo4": {
					"foo5": "bar"
				}
			}
		}
	}
}
```

2. Add a new sub environment variable that overrided the nested variable, i.e.:
```
{
	"foo1": {
		"foo2": {
			"foo3": {
				"foo4": {
					"foo5": "boo"
				}
			}
		}
	}
}
```
3. Select to activate the new sub environment
4. Try to use the nested variable in a request
5. Notice that it cannot be used as expected:

When I reference the nunjuck tag like `{{ _.foo1.foo2.foo3.foo4.foo5 }}`:
![image](https://user-images.githubusercontent.com/30680/192051115-db771dd2-a7fa-43e2-a068-bdcb76e77d23.png)

When I click on the tag to edit it, I get a screen like so (only allowing me to select to the fourth level):
![image](https://user-images.githubusercontent.com/30680/192051395-faa9275a-0f4d-4d2a-80e6-14e536158862.png)

So, if I select the fourth level and reference the nunjuck tag like `{{ _.foo1.foo2.foo3.foo4 }}`:
![image](https://user-images.githubusercontent.com/30680/192051537-91b21e93-0ea4-4d58-8298-a1299220806e.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.5.1

### What operating system are you using?

macOS

### Operating System Version

macOS 12.4

### Installation method

download

**Comment by filfreire** [comment]
Hi @bbbco, thanks for reporting this!

We're currently focused on finalizing release 2022.6.0. We will look into community PRs as soon as possible, though it might take a while. In the meantime feel free to contribute other issues you find 👍
