### ISSUE TITLE
Multi-part form data uploads seem to be broken in 5.9.0

### ISSUE THREAD

**Issue by leonbreedt** [getinsomnia/insomnia#522]
- Insomnia Version: 5.9.0
- Operating System: macOS 10.13 High Sierra

## Details

Jersey multi-part parser is no longer able to find the boundary.

Looking at at sample request, the request header declares a boundary of:

`------------------------X-INSOMNIA-BOUNDARY`

In the request body, each boundary is supposed to be prefixed with `--`, at least by going from an existing parser's code. But the boundary for the file part is the exact same string as in the header:

`------------------------X-INSOMNIA-BOUNDARY`

And then the final terminating boundary is also missing two extra `--` characters:

`------------------------X-INSOMNIA-BOUNDARY--`

**Comment by gschier** [comment]
Hey @leonbreedt. Thanks for the report. This was fixed earlier today in 5.9.2 😄

**Comment by gschier** [comment]
Also, that bug was quite embarrassing. That's what I get for relying on unit tests too much.

**Comment by leonbreedt** [comment]
Confirmed, cheers! 👍
