### ISSUE TITLE
[Bug] Request filter search with * character

### ISSUE THREAD

**Issue by dsteveahn** [getinsomnia/insomnia#525]
- Insomnia Version: v5.9.2
- Operating System: MacOS v10.12.6 Sierra

## Details
![oct-13-2017 19-36-46](https://user-images.githubusercontent.com/19622401/31542975-253fceca-b04f-11e7-9d59-d53f4109770c.gif)
I just typed `*` in the `requests filter` then it went completely out of control.
Even after Insomnia restarted

Nothing but `About insomnia` works.
So I had to reinstall the whole app.

**Comment by gschier** [comment]
Uh oh. Fixing now! 😄

**Comment by gschier** [comment]
I'm also working on better error handling so that things like this cannot take down the whole app #527

**Comment by gschier** [comment]
Hi @dsteveahn. This is fixed now in 5.9.6 😄

**Comment by dsteveahn** [comment]
Cool! Thanks for making a great tool

**Comment by gschier** [comment]
You're welcome! 😄
