### ISSUE TITLE
Unable to edit/select environments from Manage Environments modal

### ISSUE THREAD

**Issue by barthol0** [getinsomnia/insomnia#5254]
### Expected Behavior

In the 'Manage Environments' modal:
Double click on sub-environment name - being able to edit the environment 
Click on checkbox - activate/deactivate environment

### Actual Behavior

It looks like any click action triggers drag event which prevents from editing/activating environment

### Reproduction Steps

1. Open 'Manage Environments'.
2. Create new sub environment.
3. Create another sub environment.
4. Double click environment to edit - draggable event gets triggered
5. Click on the checkbox - draggable event gets triggered

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This is a fresh install of Insomnia. 

I am able to edit the sub environments when I first select the environment from the main screen and then open 'Manage environments' modal.

### Insomnia Version

2022.6.0

### What operating system are you using?

Other Linux

### Operating System Version

Pop!_OS 22.04 LTS x86_64 

### Installation method

snap, flatpak

**Comment by kweh** [comment]
It seems that the modal loses the keyboard focus after a couple of seconds. Anything written in the environment modal while it is "unresponsive" instead appears in a text field underneath; the URL or the request body.
This is quite a breaking bug, as I can no longer edit or manage my environments.

Experiencing the same issue here:
Version: Insomnia 2022.6.0
Build date: 9/26/2022
OS: Darwin arm64 21.6.0
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: arm64

**Comment by vaidd4** [comment]
@kweh This looks like this other issue https://github.com/Kong/insomnia/issues/5234

**Comment by vaidd4** [comment]
Same behaviour on Fedora 36:
```
Version: Insomnia 2022.6.0
Build date: 26/09/2022
OS: Linux x64 5.19.11-200.fc36.x86_64
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64
```

Behaviour:
- If you click & hold for too long on any sub environment label (element `li.env-modal__sidebar-item`) you trigger the drag n drop behaviour.
- If you click and release fast enough (wild guess, less than 250ms?) you can access the sub environment.
- Also by being fast enough you can click on the button to activate the environment (element `div.env-status > button`)

The click & hold delay to trigger the drag n drop seams too low for many users.
IMHO, for a better user experience, the drag n drop should only be used via the already existing drag icon (element `i.drag-handle`).

**Comment by dselans** [comment]
Same issue as described by @vaidd4 on macos. Losing focus in manage environments, every few seconds just typing any few characters. Does not seem to be JSON specific - feels like something is attempting to parse input which interrupts input window focus.

```
Version: Insomnia 2022.6.0
Build date: 9/26/2022
OS: Darwin arm64 21.5.0
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: arm64
```

**Comment by filfreire** [comment]
Hi folks, this should be fixed in our latest beta.5 release:  https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.5

> For Fedora users affected by https://github.com/Kong/insomnia/issues/5088, you can use this experimental build which includes all changes included in beta.5:  https://github.com/filfreire/insomnia/releases
