### ISSUE TITLE
WebSocket connection do not allow to debug graphql-ws

### ISSUE THREAD

**Issue by imitko** [getinsomnia/insomnia#5255]
### Expected Behavior

Allow setting a request header 'Sec-WebSocket-Protocol: graphql-transport-ws' and accept server response.

### Actual Behavior

The Insomnia WebSocket client drops connection with "Server sent a subprotocol but none was requested" error.

### Reproduction Steps

1. run a simple WebSocket enabled server e.g. https://github.com/enisdenjo/graphql-ws. following the basic example
2. create a new WebSocket connection via UI
3. setting a request header 'Sec-WebSocket-Protocol: graphql-transport-ws' from 'Headers'
4. enter url e.g. http://localhost:4000/graphql
5. click on connect
6. will lend with "Server sent a subprotocol but none was requested"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS 10.15.7

### Installation method

download from Insomnia

### Last Known Working Insomnia version

n/a

**Comment by filfreire** [comment]
@imitko retry with our [latest beta](https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.1).  We added a fix there to properly support `Sec-WebSocket-Protocol`.

**Comment by imitko** [comment]
@filfreire 
The beta works with sub-protocol, however it appear it has regression bug: all variables defined in already ready to debug GraphQL requests are appear to be lost, reverting back to latest release they become visible :-(

**Comment by mboudreau** [comment]
@filfreire why is this still and issue and not part of a production release? as of version 2023.4.0, I'm still seeing this issue.
