### ISSUE TITLE
[Feature Request] JSON-next(JSON for human writing) support ？

### ISSUE THREAD

**Issue by wonderbeyond** [getinsomnia/insomnia#526]
**Insomnia** Is a REST Client for **human**. But writing JSON by hand is not that friendly!

It's worthy that Insomnia can give support to `JSON-next` anywhere.

Most important of all, **I want do block-comment in my JSON payload**, instead of deletion (I may need them tomorrow).

![image](https://user-images.githubusercontent.com/228361/31544687-a6f9fa72-b04e-11e7-9e46-201c17d47ad4.png)

---

So what's `JSON-next`, I don't know if there is any standards or drafts, [jsonii/json-next](https://github.com/jsonii/json-next) maybe one.

## Other attractive fetures

- Trailing commas e.g. `[1, 2, 3,]`
- More similar javascript object syntax e.g. `{a: 1, b: 2}` or `{'a': 1, 'b': 2}` (This is convenient for coping code from js/python source code)
- Multi-line strings

**Comment by gschier** [comment]
Hi @wonderbeyond,

You can do block comments using the Nunjucks syntax. Just surround your stuff with `{# ... #}`

Also, more flexible JSON is being discussed over here #407 so I'm going to close this one for now.
