### ISSUE TITLE
Graphical Glitches in virtual machines. UI unusable. 

### ISSUE THREAD

**Issue by zuernBernhard** [getinsomnia/insomnia#5261]
### Expected Behavior

Consistent rendering 

### Actual Behavior

UI is not usable - see screen record 

### Reproduction Steps

Try to use insomnia client in a virtual machine (in my Case Guest and Host where Monterey on an intel Mac). Tried with parallels and vmware. Tried with and without hardware acceleration for graphics.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

perhaps related to : https://github.com/electron/electron/issues/33735 

https://user-images.githubusercontent.com/1442798/195173013-fad61fe7-5c30-469c-b28d-8aaa47aea610.mp4

### Insomnia Version

2022.6.0

### What operating system are you using?

macOS

### Operating System Version

Monterey in a Virtual machine on an intel Mac. 

### Installation method

Download from insomnia.rest

### Last Known Working Insomnia version

2022.6.0

**Comment by filfreire** [comment]
Hi @zuernBernhard, seems this is indeed related to the issue you mentioned, which is also related with https://github.com/electron/electron/issues/33685
