### ISSUE TITLE
Unable to trigger find in page/response (CTRL+F)

### ISSUE THREAD

**Issue by okdv** [getinsomnia/insomnia#5262]
### Expected Behavior

When pressing CTRL+F, should popup a search in page/search in response at top of response body to allow free text/regex searching

### Actual Behavior

No longer the case, CTRL+F seemingly does nothing

### Reproduction Steps

1. Make any HTTP/GraphQL request (may occur with others gRPC and websocket too but havent tried)
2. Attempt find in page on response (CTRL+F)
3. Note no find in page prompt appears

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Have not really dug into the changes in this last beta release to get an idea of what the cause might be, did notice #4937 touches on key bindings but again havent looked into if this may be cause

### Insomnia Version

2022.7.0-beta.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 21H2

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

2022.6.0-beta.4

**Comment by filfreire** [comment]
Hi @okdv thanks for reporting this, I can reproduce it as well:
On latest stable:
![Screenshot 2022-10-12 at 08 28 45](https://user-images.githubusercontent.com/11976836/195278113-25936acc-cd6b-4561-9c76-27d19f096d99.jpg)

On latest beta:
![Screenshot 2022-10-12 at 08 29 04](https://user-images.githubusercontent.com/11976836/195278120-914874db-2f43-4714-98d5-47e6b13b818d.jpg)

**Comment by filfreire** [comment]
Heads up @okdv this should be fixed later today in the new beta version (beta.2) we will release. Stay tuned to [releases page](https://github.com/Kong/insomnia/releases).

The fix was done through this PR https://github.com/Kong/insomnia/pull/5269

Feel free to report other issues you bump into.
