### ISSUE TITLE
Insomnia gets crashed when exporting the data

### ISSUE THREAD

**Issue by manbeing** [getinsomnia/insomnia#5263]
### Expected Behavior

Data can be exported

### Actual Behavior

Insomnia gets crashed

### Reproduction Steps

1. Select Import/Export
2. Select Export Data
3. Select 'All Documents and Collections from the insomnia project"
4. Select default Insommnia v4 (JSON)
5. click Done
6. Insomnia gets crashed. No json file is generated.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.5

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### Installation method

snap

**Comment by filfreire** [comment]
@manbeing are there any crash logs that you can provide for this issue?

**Comment by manbeing** [comment]
@filfreire  I went to the Insomnia Crash Report directory. It is empty.
![image](https://user-images.githubusercontent.com/39745132/195609062-215b273c-57ff-4f3a-a710-71d0b00326f5.png)

**Comment by filfreire** [comment]
@manbeing 

- are there any logs you can share that show an error?
![image](https://user-images.githubusercontent.com/11976836/195626208-be249104-232a-41ab-a506-a3509ae5aad0.png)

- Alternatively, when you run `snap run insomnia` on a terminal, are there any particular error log messages that you can see when you try to export the data?

I double checked on a test Ubuntu instance, and I was able to export and import ok. Some version details:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```
```
$ uname -a
Linux parallels-Parallels-Virtual-Platform 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ snap --version
snap    2.57.2
snapd   2.57.2
series  16
ubuntu  22.04
kernel  5.15.0-50-generic
```

**Comment by manbeing** [comment]
@filfreire 
I ran  `snap run insomnia` to launch insomnia, then opened the export window. after I clicked 'Done' button and insomnia got crashed. The console popped up the following errors after I clicked 'Done' button:

`(insomnia:199892): Gtk-WARNING **: 11:30:59.911: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/insomnia/182/data-dir/icons/Yaru/16x16/status/image-missing.png: Unable to load image-loading module: /snap/insomnia/183/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/insomnia/183/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
[1013/113059.911908:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
Aborted (core dumped)
`

**Comment by filfreire** [comment]
@manbeing are you able to reproduce this:

- if you run with `sudo`, e.g. `sudo snap run insomnia`
- if you run a different build of Insomnia, e.g. AppImage, from [latest release](https://github.com/Kong/insomnia/releases/tag/core%402022.6.0)

**Comment by brozeph** [comment]
@manbeing I was able to resolve this by running the following in terminal:

```bash
snap refresh insomnia --classic
```

This reinstalls the snap in classic confinement - after that, I was able to export without crashes.
