### ISSUE TITLE
GraphQL query variables not visible

### ISSUE THREAD

**Issue by okdv** [getinsomnia/insomnia#5265]
### Expected Behavior

When opening a GraphQL request, the query variables from the last request should be visible and editable

### Actual Behavior

When reopening a previously returned GraphQL request, query variables that were used in the request are not visible- however they are still present as subsequent requests will reuse the query variables that were most recently present. 

### Reproduction Steps

1. Create and run a GraphQL query/mutation with variables
2. Note successful use of variables
3. Leave request (go to another request, return to collections, etc) > switch back to the previous GraphQL request
4. Note the previously inserted variables object is absent
5. Without re-adding the variables, run GraphQL request again, note it still uses the variables that were most recently used

Video:
https://user-images.githubusercontent.com/65867719/195391819-7784a5a2-1146-4296-ae35-a793120c1f0e.mp4

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.0-beta.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 21H2

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

2022.6.0-beta.4

**Comment by filfreire** [comment]
@okdv thanks for reporting this, I can reproduce it as well. I can also reproduce it in latest 2022.6.0 stable release it seems.

**Comment by filfreire** [comment]
@okdv fix will be up in our upcoming beta release later today.
