### ISSUE TITLE
URL bar automatically gets focused when clicking SEND or pressing enter.

### ISSUE THREAD

**Issue by seanghay** [getinsomnia/insomnia#5274]
### Expected Behavior

It should not automatically focus the URL bar while my cursor is currently in Request Body or anywhere else. If this is an intended feature, please add an option to disable auto focus when sending requests in the **Preferences**.

### Actual Behavior

Whenever it focuses on the URL bar, it trigger the **Autocompletion Popup** which causes my current URL to be cleared sometimes which is really annoying and frustrating.

<img src=https://user-images.githubusercontent.com/15277233/195652356-352b0572-b8e1-4454-9493-c19817546728.gif width="100%">

The popup: https://github.com/Kong/insomnia/issues/5214

### Reproduction Steps

1. Create POST request 
2. Just add random `application/json` body
3. Hit SEND
4. The cursor will automatically auto focus to the URL bar and open up the autocomplete popup.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I'm happy to help fixing this issue if it's decided to be fixed. However, please help me to locate the code.

### Insomnia Version

2022.6.0

### What operating system are you using?

macOS

### Operating System Version

Darwin Seanghay-Macbook.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment]
The fix for this issue was contributed by @arunnalla and will be included in one of our upcoming beta releases 👍
