### ISSUE TITLE
Escape {{string}}

### ISSUE THREAD

**Issue by fernandomacho** [getinsomnia/insomnia#5280]
### Expected Behavior

Hi, I try to send request similar to:

{ 
  "a": "a",
  "b": "{{1}}"
}
Literally I need send {{1}} and not convert {{1}} into var 1.
I try to scape { and }
I try to create var 1 with value {{1}}

Nothing works.
It's posible send literally, into quotes string with {}?

Thanks

### Actual Behavior

replace literally {{whatever}} by whatever variable

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Version: Insomnia 2022.7.0-beta.1 Build date: 10/6/2022 OS: Darwin x64 22.1.0 Electron: 19.0.3 Node: 16.14.2 V8: 10.2.154.4-electron.0 Architecture: x64

### What operating system are you using?

macOS

### Operating System Version

Ventura

### Installation method

brew

**Comment by filfreire** [comment]
@fernandomacho the closest you can get to this is by opening the request settings and enabling the option to `Skip rendering of request body`:
![image](https://user-images.githubusercontent.com/11976836/195808070-5c68291d-d92a-4d4f-b474-211380c48d34.png)

![Pasted_Image_14_10_2022__10_03](https://user-images.githubusercontent.com/11976836/195807856-d23a796b-cb16-464b-a4e2-b4a1f2d829ee.png)

![image](https://user-images.githubusercontent.com/11976836/195808001-92db1a95-d16c-4436-83b6-25f328f8815a.png)


Keep in mind this will disable the ability to use environment variables, but on the other hand you'll be able to send requests in that way.

**Comment by fernandomacho** [comment]
Thanks!
