### ISSUE TITLE
Loading screen taking minutes, for a request that takes milliseconds

### ISSUE THREAD

**Issue by danielnieto** [getinsomnia/insomnia#5297]
### Expected Behavior

Loading should take a second or two at most

### Actual Behavior

it randomly takes up to 2 minutes to send and show the request, I can see the request on my local server logs that it comes very late, meaning insomnia didn't send the actual request until much later after I supposedly sent it, also, the response takes a while to show in insomnia, even if my server already "finished" processing. You can see that the actual request take less than 100ms, but insomnia took more than 2 minutes to show the result. See how the "loading" screen counts up to `142 seconds`, but after the result is shown, it reports the request to have taken `93.5ms`

https://user-images.githubusercontent.com/2120107/196296714-bcd33a0d-48a1-42cb-883c-f7478309b2d7.mp4

### Reproduction Steps

1. Send a request
2. Wait

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

It's not my server, I copied the request a cURL and executed it several times in my terminal, it shows as fast as it should be

### Insomnia Version

2022.6.0

### What operating system are you using?

macOS

### Operating System Version

MacOS Monterey 12.5.1

### Installation method

download from insomnia.rest

**Comment by danielnieto** [comment]
it seems like this is somehow caused by my "data"? I cloned the repo to try and investigate the problem myself, I used the same request as I show in the video but on the local built insomnia app, I can confirm that the newly built app feels super fast, I cannot reproduce this problem. So, it should have to be something related to the current state of my "production" instance... Could it be the number of cached results? the history? the number of "saved" queries? I've been using insomnia in this computer since about 2 years ago, so I imagine that something might be building up

**Comment by danielnieto** [comment]
[Clearing all responses cache](https://github.com/Kong/insomnia/pull/1317) does not solve the problem

**Comment by filfreire** [comment]
Hi @danielnieto thank you so much for reporting this!

This is unfortunately a know issue  and has been reported before in #3786.

I'm going to go ahead and close this one as duplicate, but we'll update you on the other ticket as soon as we manage to fix the issue.

Please feel free to report other issues you come across!
