### ISSUE TITLE
Cursor loss of focus when typing/edit JSON in Manage Environment menu

### ISSUE THREAD

**Issue by erlangparasu** [getinsomnia/insomnia#5303]
### Expected Behavior

Cursor should not lose focus while typing

### Actual Behavior

Cursor loss of focus when typing

### Reproduction Steps

1. Go to menu Manage Environment
2. Create new environment
3. In text box, type a character
4. Wait for one second
5. Cursor will loss focus

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2022.6.0
Build date: 9/27/2022
OS: Darwin x64 19.6.0
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64

### Insomnia Version

2022.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### Installation method

Insomnia

**Comment by filfreire** [comment]
Hi @erlangparasu thanks for reporting this, this is a known issue, has been reported already in #5234.

We'll be fixing this as soon as possible in one of our upcoming beta releases.
