### ISSUE TITLE
Resolver error; invalid-ref ENOENT: no such file or directory

### ISSUE THREAD

**Issue by 4n70w4** [getinsomnia/insomnia#5311]
### Expected Behavior

Correctly open `openapi.yaml` without errors.

### Actual Behavior

![image](https://user-images.githubusercontent.com/38257723/196935607-33ce0e60-da18-4c68-a5cb-87587c1e7288.png)

### Reproduction Steps

1. I have `C:\api\openapi.yaml` with refs like `$ref: "./auth/paths/login.yaml#/SteamLoginRequest"`. It's correctly works in web ui docs, correctly uses to generate frontend client, and also sucessfull passes `yml` ans `openapi` linters.
2. Press `Input From` -> `File` and select`C:\api\openapi.yaml`.
3. In `Input As` alert select `Design Document`
4. See errors.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

May be similar https://github.com/Kong/insomnia/issues/2082

### Insomnia Version

2022.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2 19044.213

### Installation method

download

**Comment by filfreire** [comment]
Hi @4n70w4, thanks for reporting this! 

Indeed this is related to #2082 and https://github.com/Kong/insomnia/discussions/3749 

We don't support file references, and, I might be mistaken but there are no plans to support these anytime soon. 

As an alternative to unblock you, try to use perhaps [this solution posted by another user](https://github.com/Kong/insomnia/discussions/3749#discussioncomment-1548364).
