### ISSUE TITLE
[Feature Request] Option to disable autocompletion

### ISSUE THREAD

**Issue by albandus** [getinsomnia/insomnia#532]
An option to disable auto-completion in body editor (for chars like `""`, `[]`, ...) would be great for those who do not find this helpful.

**Comment by gschier** [comment]
Hey @albandus. Can you give an example scenario where it's showing the auto-complete when you don't want? Ideally there is a way to make the completion logic less intrusive instead of disabling it altogether. I'm not against such an option, but it's always good to avoide new preferences if possible.

**Comment by AdrianCarreno** [comment]
I'm sorry for reopening this old thread, but I think this is a necesary feature.

When i'm typing a url ending (eg: GET {{myappur}}/users/2) and hit enter, Insomnia autocompletes it and changes my route  (in this example it replaces the 2 with "Hash => SHA256"), so I get an error and have to re-type the route. It's nice to have a suggestion when you type, but it's annoying to have it auto select the first entry when you hit enter. I think it should not auto select with enter, or at least have an option to disable that behavior.

**Comment by albandus** [comment]
- With completion in URL, sometimes there is a small lag before the box gets displayed and I already tried to click on the "Send" button at the same moment the box was displayed: it replaces the query instead of running it.
- My original request was to disable auto-completion about JSON editing: on my most frequent example is with elasticsearch. I do a lot of copy/paste of partial JSON to build queries. This implies most of the time adding/removing only one `{` or `"`, `[`. Auto-completion often ends up adding one more when I do not want or remove one that I do want.

Additionally, I always disable completion in editors as I do not always look at the screen and do not want auto-completion to add things while I'm not looking, but maybe this is more a personal convenience.

**Comment by gschier** [comment]
This was actually fixed by https://github.com/getinsomnia/insomnia/pull/1323 and will be out in the next release
