### ISSUE TITLE
No way to cancel or go back when importing a design document

### ISSUE THREAD

**Issue by srikar99** [getinsomnia/insomnia#5333]
### Expected Behavior

When I import a design document/collection from an OpenAPI spec into an existing workspace, there should be a way for me to cancel/go back.

### Actual Behavior

When I import a design document/collection from an OpenAPI spec into an existing workspace, there is no way for me to cancel it, this causes unnecessary problems if I select an incorrect workspace by mistake.

I would like to cancel if I have selected existing workspace by mista

![image](https://user-images.githubusercontent.com/15083042/198081934-ed92e2cb-2aab-4087-ad87-47d51bcaff1e.png)

### Reproduction Steps

1. Click on create
2. Select import from URL
3. Add the URL to you spec.json
4. Click on Fetch and Import.
5. Select Existing

![image](https://user-images.githubusercontent.com/15083042/198082529-5eef716c-2bbe-4a03-b47a-e965faaa10b4.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment]
Hi @srikar99, this is a known issue, we'll update you here once there's a fix for it. Thank you for reporting this and feel free to report other issues you come across!
