### ISSUE TITLE
[Feature Request]  Add one more preview mode through a template file which send by user.

### ISSUE THREAD

**Issue by Tracy1994** [getinsomnia/insomnia#534]
## Details
Now, there are three ways to preview json response, visual preview,source code and raw data.
I want one more way,which is I sent a html template file to insomnia and show the json in my way through this template file.

**Comment by gschier** [comment]
That's an interesting idea! Can you ellaborate further on what exactly you'd be using this for so I can better understand the problem?

**Comment by gschier** [comment]
An example of a template file you might want woud also be useful 😀

**Comment by Tracy1994** [comment]
A template may be in Nunjucks syntax, tasks the JSON response as context, and renders into a html page.
![image](https://user-images.githubusercontent.com/18595707/31762083-b3458cc2-b4ec-11e7-8936-cfe73985e147.png)

**Comment by lixaotec** [comment]
So: what happened to this?
Wish to have table view
