### ISSUE TITLE
Mouse scroll stops working

### ISSUE THREAD

**Issue by seriousdev-gh** [getinsomnia/insomnia#5341]
### Expected Behavior

You can scroll large request and response bodies.

### Actual Behavior

If request or response has more than ~150 lines (guess dependent on resolution and font size) and you do fast mouse scroll, scroll stops and not respond until cursor is moved or after some time.

### Reproduction Steps

1. Create new HTTP Request
2. Set type to JSON
3. Paste JSON text longer than 150 lines
4. Start scrolling down

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.6.0

### What operating system are you using?

Windows

### Operating System Version

windows 10, windows 11 22H2

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

2021.3.0

**Comment by ryuusama09** [comment]
hey @seriousdev-gh , do you know whats the reason or a possible background reason for this ?

**Comment by seriousdev-gh** [comment]
The issue does not reproduce in version 2022.7.0-beta.4. I think that due to the update of electron.
