### ISSUE TITLE
[Improvement] GraphQL query always send variables even when empty

### ISSUE THREAD

**Issue by ghiscoding** [getinsomnia/insomnia#535]
- Insomnia Version: 5.9.6
- Operating System: Windows 10

## Details

When using a GraphQL query, it seems that Insomnia **always** send `variables` in the http request, even when the `variables` set is empty. Would it be possible to remove it out of the http request when empty? I'm asking this feature because of another issue that is open in the GraphQL with .Net [issue 23](https://github.com/ckimes89/graphql-net/issues/23) library which doesn't support `variables` at the moment (the ticket is open since over a year). 

For example, if we have this GraphQL query
```javascript
query { 
    users () { 
	firstName
	nodes
    }
}
```
then Insomnia sends the following http request (_I stripped the `\n\t` for readability_)
```json
{"query":"query { users () { firstName nodes}}","variables":{}}
```
you can see that it adds `"variables":{}` even though it's empty and this will fail in GraphQL with .Net because of this [issue](https://github.com/ckimes89/graphql-net/issues/23). If I manually remove this `"variables":{}` from the http request, then GraphQL .Net is happy. 

**Note:** I tried to remove the curly braces `{}` from the `variables` section in the Insomnia `Query Variables` section, but it always add it back anyway.

**Comment by gschier** [comment]
Good news! This was fixed in #550. It will be included in the next release.
