### ISSUE TITLE
Environment editor locks with error

### ISSUE THREAD

**Issue by mod42** [getinsomnia/insomnia#5356]
### Expected Behavior

Show an error if needed, and remove the error message when TAB is removed again.

### Actual Behavior

If I hit TAB accidentally in the editor, an error message appears at the bottom and the editor is not leaving that state anymore.
Even deleting the TAB or CTRL-Z does not heal this situation. The only solution I found was, cancel the operation, close and re-open the editor, just the env editor (CMD-E). The error is "Unexpected token in JSON at position X" and the TAB needs to hit inside "". Hitting TAB outside does not make any problem.

### Reproduction Steps

1. Open env editor
2. Click inside a "" value like "host"
3. Hit TAB
4. See the error at the bottom

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.0-beta.3

### What operating system are you using?

macOS

### Operating System Version

Monterey 12.6

### Installation method

downloaded, and update via the update button inside inso

**Comment by tunezoi** [comment]
I'm having the exact same issue in version 2022.7.0-beta.3 on Windows. "Unexpected token..." even though JSON is valid.
![2022-10-31 11_54_41-Insomnia](https://user-images.githubusercontent.com/18231270/199002296-cae9337f-9f32-423d-b380-446d7b775a94.png)

**Comment by filfreire** [comment]
Hi folks, thanks for reporting this!

We also found this internally and will try to have a fix ready asap in one of the follow-up beta iterations for 2022.7.0.

**Comment by filfreire** [comment]
This will be fixed in `beta.4` release later this week.

**Comment by mod42** [comment]
That was really fast, top job.
