### ISSUE TITLE
Can't retrieve schema for GraphQL

### ISSUE THREAD

**Issue by matthewgertner** [getinsomnia/insomnia#536]
I'm using the very latest version (5.9.6) on OS X. Whenever I load a query, a message is displayed: `Failed to contact "http://localhost:3001/graphql" to fetch schema`. However, in my server log I see the following query:

```
"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      subscriptionType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"
```

The server then sends a response starting with:

```
{
  "data": {
    "__schema": {
      "queryType": {
        "name": "query"
      },
      "mutationType": null,
      "subscriptionType": null,
      "types": [
        {
          "kind": "OBJECT",
          "name": "query",
          "description": null,
          "fields": [
            {
              "name": "cities",
              "description": null,
              "args": [
                {
                  "name": "name",
                  "description": null,
                  "type": {
                    "kind": "NON_NULL",
                    "name": null,
                    "ofType": {
                      "kind": "SCALAR",
                      "name": "String",
                      "ofType": null
                    }
                  },
                  "defaultValue": null
                }
              ],
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "String",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": null
            },
```

Since our server is using the Facebook GraphQL reference implementation and seems to be doing exactly what I would expect it to do, I am at a loss as to why Insomnia is displaying this error (which means we can't use autocomplete and the like when authoring queries).

**Comment by gschier** [comment]
Can you open View > Toggle DevTools > Console and see if there is a more detailed error?

**Comment by matthewgertner** [comment]
```
graph-ql-editor.js:136 Failed to fetch GraphQL schema from http://localhost:3001/graphql TypeError: Cannot read property '__schema' of undefined
    at buildClientSchema (buildClientSchema.js:48)
    at GraphQLEditor._fetchAndSetSchema (graph-ql-editor.js:129)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109)
```

**Comment by matthewgertner** [comment]
@gschier I poked around in the debugger a bit. It looks like what `graph-ql-editor.js` is receiving the response data I pasted before with the contents of the `data` key already extracted. So when it grabs the contents at https://github.com/getinsomnia/insomnia/blob/develop/app/ui/components/editors/body/graph-ql-editor.js#L128 it's getting undefined and passing that to `graphql`.

So somewhere in the code it is already retrieving the `data` portion. It looks like chunks returned by `insomnia-node-libcurl` are already missing the outer `data` key so I guess it's `insomnia-node-libcurl` that is pulling out the data and returning it to the caller.

This would seem to be a straightforward bug that can be fixed by passing the `bodyBuffer` directly to `graphql` (inside of deconstructing with `{data}`). If that's true then this must not be working for anyone, however, which seems strange. But we're using the same GraphQL reference implementation that you are so it's hard for me to see exactly what we could be doing wrong.

**Comment by gschier** [comment]
Hmm, so what was the value of `bodyBuffer.toString()` for you? 

Yes, it seems to be working for other users, including myself. Perhaps there was an API change recently?

**Comment by matthewgertner** [comment]
Mystery solved. I took a closer look at our server and it was returning `result.data` from the GraphQL endpoint. It looks to me like GraphQL consumers expect the outer `data` property to be left in the result, hence the failure to parse the schema. Insomnia happily displayed the results of normal GraphQL queries so maybe it should validate the response, if it is true that the outer `data` is required.

**Comment by gschier** [comment]
I think `data` _is_ required since there are other keys like `error` that can be returned on that level as well. Can I ask why you were just returning the `data` key from your service?

**Comment by matthewgertner** [comment]
Presumably just an implementation error on our part. The only API consumer currently is internal so we didn't realize the mistake until Insomnia refused to parse the schema. As I said, I think Insomnia could be stricter about this and display an error message if the result of a normal GQL query is missing the outer `data` key.

**Comment by gschier** [comment]
Ya, a better error message would be good 😀

**Comment by mrbernnz** [comment]
@gschier I'm having a similar problem. But after inspecting the code for my Graphql endpoint. I'm simply returning result. I also tested against similar tools and I'm getting the expected result.

**Comment by gschier** [comment]
@mrbernz so you're not returning the `data` key from your server?

**Comment by mrbernnz** [comment]
@gschier I am actually. This is a screenshot from another interface.
<img width="1014" alt="screen shot 2017-12-02 at 12 30 49" src="https://user-images.githubusercontent.com/9615028/33518047-bcb2a7ee-d75c-11e7-89bc-5243b96fe4a8.png">

**Comment by MartanLV** [comment]
I had the same issue - it turned out introspection query had worked, but one type implementing an interface just lacked few fields. +1 for more descriptive error message.
