### ISSUE TITLE
Make screen readers and other assistive technologies read the response status as soon as the request completes

### ISSUE THREAD

**Issue by thgcode** [getinsomnia/insomnia#5369]
This is related to the discussion #3720. Currently, when we press CONTROL+ENTER to send a request, the screen reader speaks nothing when the request completes, requiring the user to navigate to the status element to view if the request succeeded or not. It would be nice when the request finishes, Insomnia notifies the new HTTP status, so the user won't need to find the element to know it.

**Comment by filfreire** [comment]
@thgcode thank you for reporting and contributing a pull request. Your contribution was merged.

Please feel free to submit more issues and pull requests that will make screen readers and assistive tech experience better.
