### ISSUE TITLE
[Feature Request] Add the ability to do sha1 hash

### ISSUE THREAD

**Issue by jo45** [getinsomnia/insomnia#537]
## Details

It would be nice to be able to do sha1 sum within nunjucks tags like it seems to be possible with jinja2: {{ 'chain' | hash(sha1) }}.

Context: I need add a signature header to authenticate my API requests to OVH cloud services. The signature is the sha1 sum of the concatenation of multiple variables.

**Comment by gschier** [comment]
Working on this tomorrow! 👍
