### ISSUE TITLE
Usage of "CMD+D" deletes URL field

### ISSUE THREAD

**Issue by hirschtec-ep** [getinsomnia/insomnia#5372]
### Expected Behavior

Pressing "CMD+D" duplicates the selected request and does not delete the URL field from the original request.

### Actual Behavior

When I duplicate a request with CMD+D, the URL of the original request is deleted.

### Reproduction Steps

1. Select a stored request in your request-list
2. Focus the URL field
3. Press CMD+D for duplicating request
4. Enter new name for the new request press enter
5. Switch back to original request
6. URL field is empty

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

System:

macOS 12.6.1 (21G217)
Insomnia v2022.6.0

### Insomnia Version

v2022.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS 12.6.1 (21G217)

### Installation method

download from official website

**Comment by hirschtec-ep** [comment]
Found references here https://github.com/Kong/insomnia/issues/3133

**Comment by filfreire** [comment]
Fix for this is available on 2022.7.0 beta versions, you can download latest iteration of beta, [2022.7.0-beta.4](https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.4)

**Comment by hirschtec-ep** [comment]
Thank you @filfreire,
I can confirm that the bug no longer occurs with version 2022.7.0-beta.4.
