### ISSUE TITLE
Workspaces without a parentId don't show up in latest Beta build

### ISSUE THREAD

**Issue by bbbco** [getinsomnia/insomnia#5384]
### Expected Behavior

All workspaces are displayed when Insomnia loads

### Actual Behavior

After upgrading to the latest beta build (I had been on stable builds previously), many of my workspaces suddenly disappeared.

I checked the `insomnia.Workspace.db` file and can see that the workspaces are still there, it's just that they don't display if the `parentId` field is `null`.

### Reproduction Steps

1. In old version of Insomnia, ensure you have one or more workspaces without a `parentId` set
2. Upgrade to latest beta version (2022.7.0-beta.4)
3. Re-open Insomnia
4. Notice that only the workspaces that had a `parentId` are displayed
5. Check the `insomnia.Workspace.db` file and notice that the workspaces are still listed, just don't have a `parentId` set (the value is `null`).

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

```
╭─ ~/Library/Application Support/Insomnia
╰─ jq -s '[.[] | select(.parentId == null)] | length' insomnia.Workspace.db
8

╭─ ~/Library/Application Support/Insomnia
╰─ jq -s '[.[] | select(.parentId != null)] | length' insomnia.Workspace.db
4
```

### Insomnia Version

2022.7.0-beta.4

### What operating system are you using?

macOS

### Operating System Version

MacOS Monterry 12.4

### Installation method

download

### Last Known Working Insomnia version

2022.6

**Comment by filfreire** [comment]
Could be what is causing https://github.com/Kong/insomnia/issues/5167 and https://github.com/Kong/insomnia/issues/2952
