### ISSUE TITLE
Using CTRL+D to duplicate a request clears its URL

### ISSUE THREAD

**Issue by sylvain1811** [getinsomnia/insomnia#5392]
### Expected Behavior

When selecting a request and then using CTRL+D shortcut should open the duplicate request popup.

### Actual Behavior

It works fine, but the URL of the selected request is cleared. It seems that CTRL+D is also the shortcut to clear the (selected) URL. Or CTRL+D is a global shortcut to clear focused field, and when a request is selected, the focus is on the URL field by default

### Reproduction Steps

1. Select a request in the collection
2. (Note that the URL field is focused)
3. Use keyboard shortcut CTRL+D to duplicate the request
4. Enter the new name
5. Open the request that you just copied from
6. Note that the URL is cleared

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 21H2

### Installation method

Download from insomnia.rest

**Comment by filfreire** [comment]
Hi @sylvain1811 this should be fixed in our [latest beta release](https://github.com/Kong/insomnia/releases)
