### ISSUE TITLE
Insomnia does not parse curl request correctly

### ISSUE THREAD

**Issue by tuyen-at-work** [getinsomnia/insomnia#5400]
### Expected Behavior

The form name and value should be seperated:

![image](https://user-images.githubusercontent.com/68000455/200723565-840f1896-2cb2-4de9-9d54-39fda6ec4660.png)

### Actual Behavior

Both the form name and value are in the same place:

![image](https://user-images.githubusercontent.com/68000455/200723486-8ecfa409-77ae-4c0c-ad9d-08a6ea0d9991.png)

### Reproduction Steps

- Create new request
- Paste below curl command into request url box:

  ```text
  curl --request POST https://login.microsoftonline.com/domain.onmicrosoft.com/oauth2/v2.0/token --header "Content-Type: application/x-www-form-urlencoded" --data-urlencode "client_id=9154f684-a955-44a3-b577-8f9134502248" --data-urlencode "scope=https://graph.microsoft.com/.default" --data-urlencode "client_secret=804237f3-1c05-44aa-8bd3-4e38a90fdbf6" --data-urlencode "grant_type=client_credentials"
   ```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.0-beta.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version 21H2

### Installation method

Download from github release

**Comment by SwiTool** [comment]
I got even worse on latest stable : when pasting a curl request, nothing happens.

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/8834915/200779939-197e10e4-df34-4224-b7f5-52c4dca88d70.png">


```
Version: Insomnia 2022.6.0
Build date: 9/26/2022
OS: Darwin x64 21.1.0
Electron: 19.0.3
Node: 16.14.2
V8: 10.2.154.4-electron.0
Architecture: x64
```

**Comment by filfreire** [comment]
@SwiTool can you share an example in `text code` here that reproduces your issue as well?

**Comment by SwiTool** [comment]
> @SwiTool can you share an example in `text code` here that reproduces your issue as well?

I should have done that indeed, because I tried with another request (simpler one) and it worked.

Here is the curl string that is not parsed : 
https://paste.ofcode.org/4zyMNKYTNrEuURUAbAFA5n

I had trouble finding an online tool which accepts to paste this 👎  If the link dies, you can reproduce by POSTing a base64 encoded PDF in a JSON body.

It's a large string indeed. But on previous Insomnia version it worked (took a long time to process but it worked). I don't have the version number in mind of when it worked though.

**Comment by ryuusama09** [comment]
hey @filfreire , I am a new-comer to this project . Is this issue suitable to be solved by for newcomers like me ?. If yes , then 
I would like to help

**Comment by filfreire** [comment]
@ryuusama09 just saw you comment above.

For this issue in particular @tuyen-at-work already contributed a PR #5409 

You can find other issues using [the `E-good-first-issue` label](https://github.com/Kong/insomnia/issues?q=is%3Aopen+is%3Aissue+label%3AE-good-first-issue)
