### ISSUE TITLE
[Feature Request] Add switcher to equal params in header or query

### ISSUE THREAD

**Issue by solofeed** [getinsomnia/insomnia#541]
![image](https://user-images.githubusercontent.com/10532978/32008082-01139fea-b9b4-11e7-8a29-8e2b2c5a7386.png)

**Comment by solofeed** [comment]
Might be useful add switch to the same header values for comfortable user experience.

**Comment by gschier** [comment]
Hmm, this might be better implemented as a new template tag. https://insomnia.rest/documentation/template-tags/

Could have an "enum" template tag that allows the user to enter `n` values that could be switched between with two clicks of the mouse. And, since it's a template tag, it could be used in any part of the app, not just header values. 

What do you think of that?

**Comment by solofeed** [comment]
Thank you for fast answer)
maybe I wrong explain my idea, I told about if using the same headers, I can't use both, only one, like the switch or radio buttons.

**Comment by solofeed** [comment]
For this need one click, not two)

**Comment by gschier** [comment]
I think I understand you correctly. Tell me if thes is correct:

You have a header named _auth-token_ with two possible values and you would like to switch between them instead of toggling off one and toggling on the other.

**Comment by solofeed** [comment]
Yes, that's it)

**Comment by gschier** [comment]
I probably did a bad job at explaining it. If I were at my laptop I would demonstrate it better.

Also, I'm not sure what exactly your use case is, but environments may also help. You can create two environments and put an auth token in each one, then switch between environments depending on which one you want to use. Have you looked into them yet? https://insomnia.rest/documentation/environment-variables/

**Comment by solofeed** [comment]
Yes. It's some workaround for my case.
