### ISSUE TITLE
Add drag and drop to 'Manage Environments'

### ISSUE THREAD

**Issue by darcyrush** [getinsomnia/insomnia#5410]
### Expected Behavior

- You should be able to use drag and drop to re-order environments (Manage Environments)
- The 'Sub Environments' ordering within 'Manage Environments' should match the 'Activate Environment' order (at the top of the sidebar)

### Actual Behavior

- Environments within 'Manage Environments' cannot be reordered
- The 'Sub Environments' ordering within 'Manage Environments' does not match the 'Activate Environment' order

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Likely related to https://github.com/Kong/insomnia/issues/5101

### Insomnia Version

2022.7.0-beta.4

### What operating system are you using?

Ubuntu

### Operating System Version

20.04.1

### Installation method

deb download from github releases

**Comment by filfreire** [comment]
Hi @darcyrush this is indeed a known issue. We've temporarily removed the option to drag and drop within the Environment Editor in order to fix other bugs and do other improvements.

We'll be improving and re-adding drag and drop as soon as possible.

**Comment by metal-gabe** [comment]
@filfreire if possible, I personally would like to add/have the feature to be able to group the sub-environments into folders as well.

**Comment by filfreire** [comment]
@darcyrush we've implemented this change, and it will return in the next patch release / beta release
