### ISSUE TITLE
[Bug] Environment variables problem in GraphQL mode

### ISSUE THREAD

**Issue by luccasmaso** [getinsomnia/insomnia#542]
- Insomnia Version: 5.9.6
- Operating System: Mac Os High Sierra

## Details
When using environment variables inside `Query Variables` graphql panel, it points out a formatting error. 
<img width="510" alt="screenshot 2017-10-25 19 05 08" src="https://user-images.githubusercontent.com/1427231/32023310-990d55ea-b9b7-11e7-974f-8e8973a0eda7.png">

Also, when exiting and entering the request at the left tree visualization, the `Query Variables` replaces the symbols with the actual values, loosing the ability to edit them in one place only.

![screenshot 2017-10-25 19 08 58](https://user-images.githubusercontent.com/1427231/32023497-16878874-b9b8-11e7-968a-3f04525cd3fe.png)

**Comment by luccasmaso** [comment]
Ok, figured out that putting the symbols inside quotas works:

<img width="508" alt="screenshot 2017-10-25 19 13 20" src="https://user-images.githubusercontent.com/1427231/32023640-a2528c46-b9b8-11e7-82df-06fad8860bcc.png">

**Comment by gschier** [comment]
Glad you were able to figure that out! 

Also note that, if the variable section as an error, it does not get saved. This is probably what you saw happened when you left the request and came back to it.
