### ISSUE TITLE
[BUG] Can't use : in JSONPath queries

### ISSUE THREAD

**Issue by kemalenver** [getinsomnia/insomnia#543]
- Insomnia Version: Version 5.9.6 (5.9.6.1223)
- Operating System: Max OSX 10.12.6

## Details

When forming a JSONPath query like below, the parser complains that it is an invalid query:

$._links.['account:details']

I tested the query on here: https://jsonpath.curiousconcept.com and with version 0.3.0 and newer it works.

**Comment by gschier** [comment]
Hi @kemalenver, this seems to be working for me. It might have been fixed when I updated the JSONPath dependency in a previous release.

As you can see here, the original JSON is on the left, and the filtered JSON is on the right.

Also, you have an extra dot before your first bracket that is not supposed to be there.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/587576/32223955-da1a94a8-be3f-11e7-8f38-28748063c5e1.png">

**Comment by gschier** [comment]
I just realized that it was probably the extra dot causing your problems. If you delete that, it should work fine.

**Comment by gschier** [comment]
Closing this for now as it seems to work.
