### ISSUE TITLE
Request body larger than maxBodyLength Limit

### ISSUE THREAD

**Issue by vinod-sl** [getinsomnia/insomnia#5443]
I am getting below error when try to push changes to git. 

![image](https://user-images.githubusercontent.com/75352945/185562787-d38d1a76-01ef-4dc9-a298-6545eca4a54b.png)

**Comment by filfreire** [comment]
@vinod-sl I transfered this issue to the main https://github.com/Kong/insomnia/ repository. Thank you for reporting it!

Are you still facing this problem when pushing to repository in our [latest beta release](https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.5)?
