### ISSUE TITLE
[Feature Request] Open source the Nunjucks editor as a generic CodeMirror extension

### ISSUE THREAD

**Issue by loganvolkers** [getinsomnia/insomnia#545]
The nunjucks editor in Insomnia is quite an invaluable little piece of software, and for the most part it looks like it's been written in a way that could be very re-useable as an open source CodeMirror extension.

We were looking to use this kind of functionality in our product, but instead of just copying the code, I figured first we'd first see if you'd be up for combining efforts on maintenance.

**Comment by gschier** [comment]
Hi @loganvolkers! Open sourcing this seems like it would be a win-win for both of us. There are three parts to the Nunjucks editing experience:

- Syntax highlighting 
- Nunjucks tags (colored buttons)
- Autocomplete 
- Tag and variable editors (modal dialogs) 
- Useful helper utilities

The first three would be fairly easy to split into a library but the last two are fairly integrated into the app and would involve more work, but still doable. 

Which of those parts were you thinking of using exactly?

**Comment by loganvolkers** [comment]
So I got a bit further on my prototype today, including wiring up Autocomplete. If you're interested in seeing it in action, follow these steps:

 1) Clone the repo
 2) `npm install && npm run test:watch`
 3) Open up the karma `debug.html` page to try it in action

My approach has been:

 - Turning global imports into parameters/options. e.g. `getTagDefinitions` and `showModal` for example.
 - Removing internal dependencies.
   - Inlining `escapeRegex`
   - Replacing your custom "`debounce`" with `throttle-debounce/throttle` from npm (note: throttle vs debounce)
 - Using off-the-shelf build tools (thanks `nwb`)

Overall I think I should give you some big props for writing things in a modular way. The biggest problems are because the CodeMirror global module/plugin system makes it hard to trace how data and callbacks flow.

**Comment by gschier** [comment]
Hi @loganvolkers. I took a quick look at the code but didn't have time to try it out. It looks like it's going well!

I will try to take a closer look soon. Just keep posting updates here 😄
