### ISSUE TITLE
Editing Private Environments

### ISSUE THREAD

**Issue by elemanhillary** [getinsomnia/insomnia#5463]
### Expected Behavior

When am editing any key in the environment, the editor shouldn't lose cursor focus on the line am editing

### Actual Behavior

When editing the cursor disappears and loses focus on the input

### Reproduction Steps

- Go to environments 
- Create a private environment
- Add in some environment variables
- Click Done
- Go Back to environments
- Edit recent environment variable

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.6.0

### What operating system are you using?

macOS

### Operating System Version

Monterey 12.4 Beta (21F5058e)

### Installation method

insomnia.rest

**Comment by filfreire** [comment]
@elemanhillary this has been fixed since, and should not be reproducible in [our latest beta build](https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.5)
