### ISSUE TITLE
[Bug] Copy as curl is missing "--insecure" flag if SSL is disabled

### ISSUE THREAD

**Issue by ebuildy** [getinsomnia/insomnia#548]
- Insomnia Version: 5.7.14.1021
- Operating System: Mac OS

## Details

When SSL is disabled (by Insomnia parameters), copy as curl should include ``--insecure`` flag to reflect this configuration.

**Comment by gschier** [comment]
Hi @ebuildy. This is a duplicate of #491 
Since Insomnia uses a 3rd-party library to do code generation, fixing this is a bit tricky. However, you are the second person now to suggest it so maybe it's a common enough problem to fix.
