### ISSUE TITLE
[Feature Request] Passing operationName automatically

### ISSUE THREAD

**Issue by JordiBeen** [getinsomnia/insomnia#549]
_Opening this issue as discussed on Monday 30th October in Slack._

Right now, Insionmia doesn't automatically pass operationName for GraphQL queries. It would be of great use for some back-ends to be able to perform checks on the operationName.

For more info on the GraphQL operation name, see http://graphql.org/learn/queries/#operation-name.

**Comment by gschier** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Send operationName with GraphQL](https://trello.com/c/hCga9AyY/638-send-operationname-with-graphql)
