### ISSUE TITLE
Cannot close popup of suggested urls

### ISSUE THREAD

**Issue by crisz** [getinsomnia/insomnia#5492]
### Expected Behavior

The popup not showing up, or it being easily closable

### Actual Behavior

The popup with suggested urls cannot be closed in any way, if not choosing an item from the list, even if I don't want it

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I'm facing a problem with Insomnia that is driving me crazy. Sporadically, a popup with suggested urls appears and I cannot close it, I tried pressing `esc` or clicking outside the popup, but the only way to get rid of it is selecting an item of the list and then remove it.
I don't know what this popup is and why it appears, probably a key combination, but I never intentionally opened it, and it was never helpful.

I had to censor some url because they belong to my client, but here is the popup I'm talking about:
<img width="566" alt="Schermata 2022-12-07 alle 10 46 18" src="https://user-images.githubusercontent.com/8181922/206145924-8734727f-7811-47db-a8c4-9bc27afc909d.png">

This is driving me crazy and wasting a lot of my time, and I'm thinking about uninstalling Insomnia because of it.
Thank you

### Insomnia Version

2022.6.0

### What operating system are you using?

macOS

### Operating System Version

MacOS Montrey 12.6

### Installation method

Download from insomnia.rest

**Comment by filfreire** [comment]
@crisz try to use the [latest beta release](https://github.com/Kong/insomnia/releases/tag/core%402022.7.0-beta.6). This has been fixed in the latest beta releases.
