### ISSUE TITLE
[Bug] Dropping files 

### ISSUE THREAD

**Issue by crispinb** [getinsomnia/insomnia#551]
- Insomnia Version: _5.9.6 (5.9.6.1223)__
- Operating System: macOS 10.12.6

## Details
- drag any file from Finder onto the Insomnia app window opens the file in Insomnia
- if the file was dropped somewhere other than the Preview pane, this renders Insomnia unusable, requiring an app restart

Expected result would be for Insomnia to either ignore the drop operation, or to respond appropriately to a limited set of file types (eg. for imports)

**Comment by gschier** [comment]
Hey @crispinb, thanks for reporting this. It should definitely be fixed. I think the ideal behavior for this would be to prompt the user to import the file after dropping.
