### ISSUE TITLE
Editing active sub-environment triggers GQL schema fetch refresh/request

### ISSUE THREAD

**Issue by metal-gabe** [getinsomnia/insomnia#5511]
### Expected Behavior

I should be able to edit the environment without Insomnia making new GQL schema requests every time I enter in a single value. 

### Actual Behavior

Right now, when I open the environment editor and select the currently active environment, altering the values triggers a GQL schema refresh/re-fetch. 

An additional side effect of this is the refreshes pull the cursor focus out of the environment editor and into the request, often times it'll go specifically/directly to the URL/location bar. 

This causes me to inadvertently paste things and give me a bad request. Overall, it's just tedious to edit the env vars and it's annoying that I paste things all over the place. 

NOTE: When I have a REST request selected in the main window, the auto-fetch bug doesn't happen, just the loss of cursor focus. 

### Reproduction Steps

1. Select one of your envs in Insomnia 
2. Open up the env editor and select the same active env you chose in step 1 
3. Make any valid edit to the the sub-env and wait a second 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Turning off auto-fetch in the schema menu doesn't affect this. The problem still persists after turning that off. 

UPDATE: Okay, pretty much doing anything in Insomnia is triggering schema re-fetches. I have the setting turned off and it does nothing. 

### Insomnia Version

2022.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.7.1

### Installation method

Homebrew

### Last Known Working Insomnia version

Unknown

**Comment by filfreire** [comment]
Hi @gflujan, thanks for reporting this.

We noticed the bug a few days ago that the Disable Automatic Fetch button doesn't seem to be working.

I can also reproduce this locally - after performing an edit to an environment, I can see in the logs we re-fetch the schema, same for some other actions.

cc'ing @jackkav and @gatzjames - heads up - this is being tracked internally with https://linear.app/insomnia/issue/INS-2205/[bug]-toggling-automatic-fetch-on-graphql-doesnt-work

**Comment by filfreire** [comment]
@gflujan the toggle button should work after PR #5516 , it will be included in the 2022.7.0 release on thursday. Marking this issue as closed in the meantime. Feel free to report other stuff you bump into.
