### ISSUE TITLE
Request docs markdown: Bullet points missing when nesting in ordered list 

### ISSUE THREAD

**Issue by leongzhiyong** [getinsomnia/insomnia#5526]
### Expected Behavior

1. Lorem ipsum
	- Dolor
	- Sit amet

### Actual Behavior

1. Lorem ipsum
&nbsp;&nbsp;&nbsp;&nbsp;Dolor
&nbsp;&nbsp;&nbsp;&nbsp;Sit amet

### Reproduction Steps

1. Create request
2. Edit request docs
3. Input following code

    ```
    1. Lorem ipsum
        - Dolor
        - Sit amet
    ```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22H2

### Installation method

Installer from imsomnia.rest

**Comment by ryuusama09** [comment]
hey @leongzhiyong , I have the same version and windows operatig system . But apparently  iam not facing this issue :
![image](https://user-images.githubusercontent.com/80237556/207785257-c58eeb3b-fecb-4d54-8415-a0c9500268ce.png)

**Comment by leongzhiyong** [comment]
> hey @leongzhiyong , I have the same version and windows operatig system . But apparently iam not facing this issue : ![image](https://user-images.githubusercontent.com/80237556/207785257-c58eeb3b-fecb-4d54-8415-a0c9500268ce.png)

Your unordered bullet points are not nested.

Examples with nested bullet points (#1) vs unnested bullet points (#2)

![image](https://user-images.githubusercontent.com/9491745/207788557-c40e6d01-bee9-40c2-b184-438ae105b043.png)

![image](https://user-images.githubusercontent.com/9491745/207788427-bebf1608-a6c5-40d0-85b7-2b0e56c98669.png)

Edit:
Looks like copying the code block from the instruction set leaves out the leading spaces.

**Comment by leongzhiyong** [comment]
@ryuusama09 I've updated the code block so that copying from it will properly replicate the issue. Thanks.

**Comment by ryuusama09** [comment]
> @ryuusama09 I've updated the code block so that copying from it will properly replicate the issue. Thanks.

alright thanks , now got that issue 👍

**Comment by paoloose** [comment]
The bug seems to be in the list's combinator inside `packages/insomnia/src/ui/css/components/markdown-preview.less`
```less
.markdown-preview__content {
// ...
  & > ul {
    list-style: disc;

    ul {
      list-style: circle;
    }
  }

  & > ol {
    list-style: decimal;

    ol {
      list-style: lower-alpha;
    }
  }
// ...
}
```
The `>` combinator will only match the `ul` and `li` that are first descendants of the container.

Since in `packages/insomnia/src/ui/css/reset.less` 
```less
ol, ul {
  list-style: none;
}
```

all the `list-style`s are set to none, in the example that @leongzhiyong provides:
```txt
1. Lorem ipsum  // <-- first descendant, so will have `list-style` set to `decimal`
    - Dolor     // <-- NOT first descendant, so the CSS rule will not apply and will have `list-style: none`
    - Sit amet
```
Another example:
```txt
1. Lorem ipsum  // <-- first descendant, so will have `list-style` set to `decimal`
    1. Dolor     // <-- NOT first descendant, but it's a descendant of the first descendant, so will have `list-style: lower-alpha`
    2. Sit amet
```

Note in the CSS rules that the "descendants of a first descendant" need to be of the same type (`ul` or `ol`), that's why the bug only occur when they are different types of lists.

Removing these combinators will fix it. I will make a pull request.
