### ISSUE TITLE
[Feature Request] Nested Sub Environments or sub-call overrides

### ISSUE THREAD

**Issue by manfrin** [getinsomnia/insomnia#553]
The sub environment system is great, and I feel it would benefit from either having sub-environments or allowing calls to have individual overrides (irrespective of environment). 

The situation is that I have calls that can take different elements in a payload, and those elements are the same across all my environment, but different depending on what I want to do. For example, I could have a POST /blog-post endpoint which would have a body that has a postType attribute. That body would be the same in all my environments, but different depending on what I wanted to post. Right now the only way to achieve this is to duplicate calls and add e.g. " - (Text)" or " - (Media)", and that just reminds me of my old days saving calls with the ENV in the call name.

**Comment by gschier** [comment]
That seems to be a common use case. I think #283 may be what you're looking for. Going to close this one for now as a duplicate but please let me know if you think it's a separate problem.
