### ISSUE TITLE
[Feature Request] Relative timestamps

### ISSUE THREAD

**Issue by manfrin** [getinsomnia/insomnia#554]
Since the Custom timestamp template tag is already passing user formatted strings to moment, it would be super easy to send moment-style `.add` values, so I could have a timestamp that looked like `{% add "1" "day" "iso1806" %}`.

You could even go a step further and allow chaining of moment methods like
`{% [add, ["1", "day"]], [hours, 19], [minutes, 0], [seconds, 0], "iso1806" %}`
which would yield a timestamp for 7pm tomorrow, relative to the time the call is run.

I took a look at the extensions and this seems relatively straightforward and I may pick this up on my own -- if you have any opinions, suggestions, or directions as to the syntax that should be used, let me know.

**Comment by gschier** [comment]
That seems like a great use case for an extension. I'm not actually sure what the best API for that would be since it's so flexible. Your idea of using arrays sounds a bit hard to use but I can't think of anything better. Hmm....

**Comment by gschier** [comment]
I'm going to close this issue for now but feel free to keep asking questions here or in the [Slack](http://chat.insomnia.rest/) channel.

**Comment by vermgit** [comment]
This makes a lot of sense when having to pass a time period to a remote service. As far as the API is concerned I suggest to implement something like UNIX' `date` has. If that isn't practical, I'd do something like `-4h`, `+20d12h15m`. With `w` for weeks, `d` for days, `h` for hours, `m` for minutes and `s` for seconds.
