### ISSUE TITLE
INTERNAL_SERVER_ERROR in GraphQL queries

### ISSUE THREAD

**Issue by Corentin7301** [getinsomnia/insomnia#5548]
### Expected Behavior

Return GraphQL datas (like Postman after download for test)

### Actual Behavior

I've this error when I run GraphQL query :
```json
{"errors":[{"message":"An unexpected error occurred.","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

### Reproduction Steps

1. Open GraphQL query.
2. Use a schema like this:
```graphql
query home {
	home_page {
		id
	}
}
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Knowing that I had no problem before I retried an old query. If I keep the name of the old query ("HomePage" for example) it works fine and it updates well. If I change the name of the query, I get the error again.

### Insomnia Version

2022.7.0

### What operating system are you using?

macOS

### Operating System Version

MacOS Catalina 13.0.1

### Installation method

download from Insomnia.rest

**Comment by filfreire** [comment]
Hi @Corentin7301 this should be fixed in https://github.com/Kong/insomnia/pull/5611

A patch release will go out today with the fix. Feel free to report any other thing you find

**Comment by Corentin7301** [comment]
Hi @filfreire !
Okay, cool! Thank you very much!
