### ISSUE TITLE
After 2022.7.0 update, my Collections are labeled Documents and are not opening due to errors

### ISSUE THREAD

**Issue by inafil76** [getinsomnia/insomnia#5550]
### Expected Behavior

Be able to open my Collections successfully and see all the APIs, env variables etc. that are setup.

### Actual Behavior

My Collection, has now been labeled as a Document and as a result I get the following error when trying to open it.

![image](https://user-images.githubusercontent.com/121012691/208383593-7d6b9458-84d0-4eb8-9833-0dbcfd2ac96d.png)

![image](https://user-images.githubusercontent.com/121012691/208382035-e5e998f2-f4cb-47c0-a89c-d6ed37046305.png)

### Reproduction Steps

1. Open Insomnia
2. Navigate to the project (created automatically by the latest update) 
3. Open a collection

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The problem occurred after the latest update 2022.7.0.
Before that, I had a bunch of Documents and a collection (with no documents inside, just a list of API calls and env variable setup).
My Documents are opening just fine. The problem is with my Collection specifically.

### Insomnia Version

2022.7.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Download from website (I have been using it for years and updating it regularly)

### Last Known Working Insomnia version

2022.6.0

**Comment by maslbl4** [comment]
Same issue, can't import collection from "insomnia.desktop.app:v2022.6.0"
![image](https://user-images.githubusercontent.com/1502824/208385983-407b82c3-7fb4-4318-a517-33bd0d22e750.png)

**Comment by hilmarp** [comment]
Same here, can't open the collection I had been using to test last Friday.

Using Version: Insomnia 2022.7.0 on Mac Ventura 13.1.

![Screenshot 2022-12-19 at 10 02 36](https://user-images.githubusercontent.com/2643080/208400161-d64ce8fc-5187-441d-8ef9-ed9b212badda.png)

**Comment by prryplatypus** [comment]
Same here.
```
Version: Insomnia 2022.7.0
Build date: 15/12/2022
OS: Windows_NT x64 10.0.22621
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64
```

**Comment by mlh758** [comment]
Same version, same error.

**Comment by krazar** [comment]
Same here.

**Comment by prryplatypus** [comment]
For those who might find this useful, if you select "debug" in the top bar, you're able to see the collection items.
![imagen](https://user-images.githubusercontent.com/25409753/208662466-a00427c9-501a-46d8-8fb8-1f866b4a1b42.png)

**Comment by krazar** [comment]
Thank you ! I now see every items.

**Comment by NatassiaTavares** [comment]
Thank you! Insonmia deleted all my requests and then I had to clone from Github which was sadly, very outdated, but at least it's something!

**Comment by cfsavant** [comment]
Same

**Comment by andrenpt** [comment]
I have he same problem...

**Comment by jackkav** [comment]
This should now be resolved.
