### ISSUE TITLE
2 problems, time to open 'commit' view & file change on open

### ISSUE THREAD

**Issue by dimi-lcq** [getinsomnia/insomnia#5551]
### Expected Behavior

When i click on 'commit' view, Insomnia load faster the listed editedfiles.
When i open a file without change anything he doesn't appear in 'commit' view.

### Actual Behavior

1/ When i click on 'commit' Insomnia take A LOT OF TIME to load my edited files.
I don't know why because with a git repository we just need to make a "git status" because this feature are fully offline.

I have seen it's more longer with a bigger workspace (i don't have a very big workspace with my team)

2/ When i open a file without change anything he appear in 'commit' view and it's not normal. 

### Reproduction Steps

Just take a workspace open some files and click on 'commit' view on your branch.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I can't share my workspace because it's for my work and we have some credentials.

My config : 
Version: Insomnia 2022.1.1
Release date: 09/03/2022
OS: Windows_NT x64 10.0.19042
Electron: 12.2.3
Node: 14.16.0
V8: 8.9.255.25-electron.0
Architecture: x64
node-libcurl: libcurl/7.79.1-DEV OpenSSL/3.0.0 zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.45.1

### Insomnia Version

2022.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.19042

### Installation method

Web

**Comment by filfreire** [comment]
Hey @dimi-lcq, the potential fix by @PatrickMurrell   will go out in this week's beta, let us know if it improved the slowness.

**Comment by dimi-lcq** [comment]
Hi @filfreire & @PatrickMurrell thanx for this.

@filfreire do you have a changelogs page for the beta versions ? This version are online ?
I will test when the version is available and I will report back on this change.
