### ISSUE TITLE
[Feature] Editing of Client Certificates

### ISSUE THREAD

**Issue by emjburns** [getinsomnia/insomnia#556]
My team just signed up for the Teams version, and we make heavy use of client certificates. I'm seeing that we can't edit the certs once we add them in the Workspace Settings > Client Certificates tab. Is this something you plan on adding? Thanks!

- Insomnia Version: v5.9.6
- Operating System: macOS Sierra: 10.12.6

@robzienert

**Comment by gschier** [comment]
Hi @emjburns, 

Right now, the only way to edit certs it to delete one and create a new one. I'm curious, what part of the client certificate do you need to edit frequently that this is a problem? What does your workflow look like?

**Comment by emjburns** [comment]
@gschier thanks for the response! We have a lot of services that we're connecting to, and as we're figuring out how to connect with client certs correctly it's a lot easier to edit something you have almost working than to create a new one, remember the small change you want, then fix that one. 

It's not a huge deal, it would just be a much improved user experience. I don't have the bandwidth now to look into adding this. If it gets sufficiently annoying in the future I'll take a look at it!

**Comment by gschier** [comment]
Thanks for the info @emjburns! I might also pick this one up the next time I have some free cycles, since it's not terribly difficult. 😄

**Comment by ho3einjb** [comment]
maby i'm interested in!

**Comment by gschier** [comment]
😀

**Comment by smithtim** [comment]
I would also like this feature.  Currently we have to delete the entry and re-add it just to update the certificate.

**Comment by JananiBalakrishnan** [comment]
Yup, this feature will be helpful to edit the certs easily.

**Comment by smithtim** [comment]
Why did the bot close this as completed?  Was it completed?
