### ISSUE TITLE
GraphQL request duplication doesn't update to the new query/mutation name 

### ISSUE THREAD

**Issue by metal-gabe** [getinsomnia/insomnia#5563]
### Expected Behavior

I expect that duplicating a GQL request would update it's reference (?) to be the name of the new request/query/mutation. 

### Actual Behavior

After I duplicated an existing GQL request to modify and create a new, but similar, request, I am getting an error of "No operation named `previousRequestName`" in the response. 

### Reproduction Steps

1. Right click on an existing GQL request and select "duplicate" 
2. Update the duplicated/"new" request to be a different name/query/mutation 
3. Try to submit the duplicated request and you should get the "no operation named ..." response 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I wonder if this has to do with, or is at least related to, the failing GQL schema introspection. 

I created a new request from scratch with auto-fetch turned on, and for a split second the "Operations" button? was a drop down that showed the new request name I wanted. But after I got back the 401 of the failed introspection, the drop down no longer appears. 

The new request does succeed though. 

For the images below, notice the difference in the "button" next to the schema button above the request editor. 

# Image 1 - Duplicated Request 

![z1-duplicated-request](https://user-images.githubusercontent.com/26269014/208772567-d560f62c-7a42-45d7-b96b-46539e88d495.png)

# Image 2 - From Scratch Request 

![z2-from-scratch-request](https://user-images.githubusercontent.com/26269014/208772568-4af6c6cc-32e3-4a57-bca5-2d5f06819828.png)

### Insomnia Version

2022.7.0

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.7.2

### Installation method

Homebrew

### Last Known Working Insomnia version

2022.6.0

**Comment by skylersidner** [comment]
+1 as I just noticed this today.  Duplication is my lazy-man's way of creating new instances that are similar to the old and I cannot figure out how to alter the reference to the original query/mutation in the upper left.  Creating a new query worked fine, and I can confirm the flicker of the "Operations" button(?) in the upper left, which immediately goes away (disabled?).

Insomnia Version
2022.7.0

What operating system are you using?
macOS

Operating System Version
Monterey 12.6

Installation method
Download

Last Known Working Insomnia version
2022.6.0

**Comment by filfreire** [comment]
@skylersidner @gflujan, thank you for reporting this, this should be fixed after we merge https://github.com/Kong/insomnia/pull/5611

A patch release will go out today with the fix. Feel free to report any other thing you find
