### ISSUE TITLE
Prettify GraphQL not working

### ISSUE THREAD

**Issue by JoelRomero97** [getinsomnia/insomnia#5573]
### Expected Behavior

I'm expecting to prettify my query variables when creating a mutation/query

### Actual Behavior

Is actually showing me an error "[object Object]" is not valid JSON, which is incorrect because is valid, if I hit `Send`, it works and I retrieve data

<img width="1392" alt="Screenshot 2022-12-21 at 6 07 27 PM" src="https://user-images.githubusercontent.com/23665094/209039784-1531ecd6-5384-40a3-9560-e7c951ff549b.png">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I'm new at setting my insomnia from scratch, so maybe I'm doing something wrong (?), if that's the case please let me know

### Insomnia Version

2022.7.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.0.1

### Installation method

homebrew

**Comment by filfreire** [comment]
Hi @JoelRomero97, thanks for reporting this. I can also reproduce it:

![image](https://user-images.githubusercontent.com/11976836/210755677-c7582888-4b2e-4505-a06f-fd0e396bd40c.png)
