### ISSUE TITLE
Sub-environments no longer sortable

### ISSUE THREAD

**Issue by ctmay4** [getinsomnia/insomnia#5576]
### Expected Behavior

Sub-environments should be able to be dragged and reorders in "Manage Environments".

### Actual Behavior

This no longer works. It was added a long time ago in https://github.com/Kong/insomnia/pull/978. Now it doesn't appear to be working.

### Reproduction Steps

- Go to "Manage Environments"
- Assuming there are multiple sub-environments, you should be able to drag them up or down to order.
- Dragging does nothing.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Company installed it so I'm not sure

**Comment by darcyrush** [comment]
Related; https://github.com/Kong/insomnia/issues/5410

**Comment by ctmay4** [comment]
Thanks. I didn't see that when I was searching. I will close this now.
