### ISSUE TITLE
Sub-Environment Order scrambed after last update

### ISSUE THREAD

**Issue by joshua-wheeler** [getinsomnia/insomnia#5577]
# Expected Behavior
* Sub-environment order does not change after installing update

# Observed Behavior
* Sub-environment order totally scrambled after last update

# Is there an existing issue for this?
- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

# Additional Info
* As detailed in #5576 drag-and-drop no longer works either, so you can't fix the problem either. However, this bug is directed to the install issue where installing update should not scramble existing order of your sub-environment. 

![Insomnia_subenv_issues](https://user-images.githubusercontent.com/2984787/209152883-674b41b1-51b1-4152-acc9-532f89df0290.png)

# Insomnia Version

- Version: Insomnia 2022.7.0
- Build date: 12/15/2022
- OS: Windows_NT x64 10.0.19045
- Electron: 22.0.0
- Node: 16.17.1
- V8: 10.8.168.20-electron.0
- Architecture: x64

**Comment by filfreire** [comment]
Hi @joshua-wheeler, thanks for reporting this! Closing it in favour of #5410 - it's the same issue.
