### ISSUE TITLE
[Bug] Curl import with -i -G -d was imported as a GET with a POST body

### ISSUE THREAD

**Issue by PseudoCoding** [getinsomnia/insomnia#558]
- Insomnia Version: 5.9.6.1223
- Operating System: macOS 10.12.6

## Details

When importing a `curl` by entering in the URL field with the `-i -G -d` flags, data was entered into the body of the GET request. Expected result per `man curl` is for the data after the `-d` flag to be added to the query parameters

>  -G, --get
>> When used, this option will make all data specified with -d, --data, --data-binary or --data-urlencode to be used in an HTTP GET request instead of the POST request that otherwise would be used. The data will be appended to the URL with a '?' separator.
>> If  used  in  combination  with -I, --head, the POST data will instead be appended to the URL with a HEAD request.
>> If this option is used several times, only the first one is used. This is because undoing a  GET  doesn't make sense, but you should then instead enforce the alternative method you prefer.

Example curl:

` curl -X GET 'http://somesite.com/getdata' -i -G -d 'id=1234'`

**Comment by gschier** [comment]
I will try to get this fixed for the next release! 👍
