### ISSUE TITLE
The window stuck at loading

### ISSUE THREAD

**Issue by StarlightIbuki** [getinsomnia/insomnia#5587]
### Expected Behavior

A successful start-up.

### Actual Behavior

![image](https://user-images.githubusercontent.com/100666470/209538050-17aed969-3330-4cf5-b3bd-229bd5218989.png)

### Reproduction Steps

1. Start the App

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Every first time starting up after powering on, it stops there as shown in the picture. When I close the window and restart the App, it works.

How can I get more information for you to diagnose?

Version: Insomnia 2022.7.0
Build date: 2022/12/15
OS: Windows_NT x64 10.0.19045
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

### Insomnia Version

2022.7.0

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.19045

### Installation method

It was downloaded from the official site, and auto-updated.

**Comment by filfreire** [comment]
Hi @StarlightIbuki thanks for reporting this.

Is this still happening for you in latest [2022.7.5 release](https://github.com/Kong/insomnia/releases/tag/core%402022.7.5)?

If it is, when you go into `View` and `Toggle Dev Tools` and in the dev tools switch into `Console` tab, do you notice any error logs while it is stuck in loading screen?

**Comment by StarlightIbuki** [comment]
> Hi @StarlightIbuki thanks for reporting this.
> 
> Is this still happening for you in latest [2022.7.5 release](https://github.com/Kong/insomnia/releases/tag/core%402022.7.5)?
> 
> If it is, when you go into `View` and `Toggle Dev Tools` and in the dev tools switch into `Console` tab, do you notice any error logs while it is stuck in loading screen?

this:
```bash
DevTools failed to load source map: Could not parse content for file:///C:/Users/suika/AppData/Local/insomnia/app-2022.7.2/resources/app.asar/generate.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/suika/AppData/Local/insomnia/app-2022.7.2/resources/app.asar/plugins.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/suika/AppData/Local/insomnia/app-2022.7.2/resources/app.asar/variables.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/suika/AppData/Local/insomnia/app-2022.7.2/resources/app.asar/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/suika/AppData/Local/insomnia/app-2022.7.2/resources/app.asar/declarative-config.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/suika/AppData/Local/insomnia/app-2022.7.2/resources/app.asar/k8s-plugins.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/suika/AppData/Local/insomnia/app-2022.7.2/resources/app.asar/kubernetes-config.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/suika/AppData/Local/insomnia/app-2022.7.2/resources/app.asar/openapi3.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/suika/AppData/Local/insomnia/app-2022.7.2/resources/app.asar/outputs.js.map: Unexpected end of JSON input
```

**Comment by StarlightIbuki** [comment]
After updating, the startup succeeded, but the errors are still there.

**Comment by filfreire** [comment]
Thank you @StarlightIbuki, closing this issue then.
