### ISSUE TITLE
[Feature/Enhancement] Focus Request Body editor upon selecting Content-Type

### ISSUE THREAD

**Issue by taviandir** [getinsomnia/insomnia#559]
- Insomnia Version: 5.9.6
- Operating System: Windows 10 (Creators Update)

## Details

**Current behaviour:** No focus. After choosing Content-Type for the request, I have to click in the request body editor to get keyboard focus and begin typing/pasting JSON.
**Desired behaviour:** When I select "JSON" (or any other content-type) in the Request Body content-type dropdown, I would like the request body editor to get keyboard focus so that I can start to type the JSON immediately (or paste).

I type JSON by hand a lot, or copy-paste from other requests' responses, so a behaviour like this would make that process a bit smoother.

**Comment by besolov** [comment]
JFYI, instead of "copy-paste from other requests' responses" you could use [template tags](https://support.insomnia.rest/article/40-template-tags).

**Comment by gschier** [comment]
Hmm, I can't tell if this would be desired behavior for the general user or not and it seems like quite a small benefit. Your mouse is already likely hovering over the body editor when the dropdown closes. Why not just click it a second time to focus the editor?

**Comment by taviandir** [comment]
Thanks for the tip about the template tags! Will definitely try that out.

I realise that this is an extremely small enhancement, and doesnt need to
be a top priority to implement, but as I see it doesn't break any current
functionality as the keyboard focus ends up on the dropdown menu, which
doesnt really do anything anyway.
Of course I realise that I can just click one more time, but not having to
do that extra click is a bonus in my eyes.
