### ISSUE TITLE
Bulk editor for query params not expanding down to fit all query params

### ISSUE THREAD

**Issue by rickythefox** [getinsomnia/insomnia#5590]
### Expected Behavior

Editor shows all query params.

### Actual Behavior

Editor too small and impossible to use
<img width="503" alt="image" src="https://user-images.githubusercontent.com/1675955/209683257-c7bf8c7e-4550-4fcc-b0d7-7aed05cff86d.png">

### Reproduction Steps

1. Add some query params
2. Trigger bulk editor

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.0

### What operating system are you using?

macOS

### Operating System Version

Monterey

### Installation method

Download

**Comment by kszinhu** [comment]
I'm having the same problem 1 month ago :( (after update, I don't remember the update version that made this happen)

---

### What operating system are you using?
Windows and Manjaro

### Operating System Version
11 22H2 and 22.0 (Sikaris)

**Comment by ghost** [comment]
I have the same issue

### Insomnia Version
2022.7.5

### What operating system are you using?
MacOs

### Operating System Version
Ventura 13.1

further details on insomnia version (about)
```
Version: Insomnia 2022.7.5
Build date: 1/19/2023
OS: Darwin arm64 22.2.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64
```
