### ISSUE TITLE
Bug - Can't select named GraphQL query

### ISSUE THREAD

**Issue by kmccarp** [getinsomnia/insomnia#5593]
### Expected Behavior

In the previous version, I could put multiple GraphQL queries/mutations in the same window and click on the one I wanted to run, and click "send" (or cmd+enter) and it would run just that query/mutation. ([This functionality was added in 2018](https://github.com/Kong/insomnia/issues/733))

### Actual Behavior

Now, it doesn't matter where I click, the query that is run can never be changed, *even if it is deleted*.

![image](https://user-images.githubusercontent.com/910168/209883166-6d87114b-caa8-45fd-8998-413f75b8b096.png)

### Reproduction Steps

1. Update to the newest version with a graphql query still in the editor
2. Click on one of the graphql queries/mutations in the editor
3. Cmd+enter (on Mac)
4. It runs the wrong query/mutation.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.1

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

Whichever the previous one was, not sure.

**Comment by fogush** [comment]
Exactly the same here. Running the selected query/mutations was my favorite feature of Insomnia 😢 
MacOS Big Sur 11.5.2, Insomnia 2022.7.0

**Comment by filfreire** [comment]
Hi @kmccarp @fogush, thank you for reporting this, this should be fixed in https://github.com/Kong/insomnia/pull/5611

A patch release will go out today with the fix. Feel free to report any other thing you find
