### ISSUE TITLE
[Fixed] my entire collection is missing after auto-updated to Insomnia 2022.7.0

### ISSUE THREAD

**Issue by stealthmonkey99** [getinsomnia/insomnia#5600]
### Expected Behavior

I should still see my collection of requests, environments, etc.

### Actual Behavior

the app displays an empty "Insomnia" project and all of my old work is missing

### Reproduction Steps

1. launch Insomnia
2. look for my collection

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### Installation method

do not remember, update was auto-installed without my asking

**Comment by ewallat** [comment]
Hey @stealthmonkey99 I had the same problem, but when I clicked on one of the existing documents (at least one should be there) and then switched from Design to Debug on the title bar, all the content was visible again.

![image](https://user-images.githubusercontent.com/7705645/210104284-f7ec44ee-4a12-4a01-b0ef-e8c519c6db16.png)

Maybe this will help you and a few others.

**Comment by stealthmonkey99** [comment]
Thanks @ewallat!  I didn't even notice those tabs but sure enough that's all I was missing 🤦

**Comment by rodrigoratan** [comment]
It happened to me but it's not a Design Document, it's a Collection, and its empty, only the folders

**Comment by enricoros** [comment]
I thought it was all gone, but it switched to the 'design' tab (all my content was on the 'debug' tab).

**Comment by ghost** [comment]
https://github.com/Kong/insomnia/issues/5167#issuecomment-1370014676

**Comment by heyitsnovi** [comment]
Had the same issue. all my request history are gone after the auto-update happened. it just sucks. uninstalling the app for good

**Comment by betterbuiltcows** [comment]
This can't be [Fixed] as the title indicates. My Insomnia just auto-updated 2 hours ago, two weeks after this ticket was created, and my upgrade did the same thing. Except .... nothing appears on the Debug tab, insomnia.Environment.db is empty... everything gone. Pretty unbelievable that you are still auto-updating the software given this issue. You should stop doing that till it's resolved.

**Comment by tummyacid** [comment]
Also reporting this issue after auto-update. Everything is gone. UI totally unresponsive. All folders clean. I've lost a lot of work.

**Comment by filfreire** [comment]
@betterbuiltcows @tummyacid sorry to hear this happened to you folks. We seem to have some sort of edge-case bug still with data.

If possible, please reply back to this [comment here](https://github.com/Kong/insomnia/issues/5559#issuecomment-1384419758) with any of the information listed there in order to help us hunt down in which edge-case setups this happens.

**Comment by Jailyard90Grad** [comment]
This just happened to me as well. macOS Ventura 13.1. SW downloaded from Insomnia. Not sure what the latest working version was.

Earlier today I started Insomnia for the first time in a couple of weeks and got a note that it had been updated. And everything was gone; my 30+ requests, the folders, the Design/Debug/Test tabs.

I looked through the Workspace.db and saw my requests(!), along with notes about them being deleted, which I never did. Seeing them safely there, I closed the db, thinking I'd come back to it later. Then I stumbled across these Github tickets with possible solutions. When I opened Insomnia again to try them out...it again said that it had updated and now my Workspace.db files have all been wiped. All the info I saw earlier tonight is gone. 

So very disappointing. I had come to prefer this over Postman but I can't see myself trusting this again.

**Comment by danesparza** [comment]
Also completely wiped.  Also on MacOS Ventura 13.1.  This is frustrating, to say the least.

**Comment by gabrielsaviank** [comment]
Updated today here and completely wiped too. Tried to follow what people said on the thread and nothing. This is very frustrating.

**Comment by ColbyWanShinobi** [comment]
LOL, you just wiped out a years worth of my data, why would I help you troubleshoot it?

**Comment by fdimauro** [comment]
This app updated it's self last night and delete all my projects. How do I get them back?

**Comment by fdimauro** [comment]
Also this looks like a totally different product. I was demonstrating it's usefulness to a co-worker just yesterday. Now I see a totally different product and ALL of my projects are gone. WTF happened and how to I fix it ASAP??

**Comment by fdimauro** [comment]
Boy I have to say I am quite pissed off that this happened. What is our course of action to recover from this disaster?

**Comment by WesternGun** [comment]
Same happened when I `sudo apt upgrade` to 2023.3.0. No collections found. Neither can I find "Design/Debug/Test" panel at first. I have to import a previously backup of collections, some recent changes lost but not much. 

I think this is quite big problem, because via `sudo apt upgrade` I cannot downgrade. And, there is no way for any software to let `apt` know that user needs to backup data first before upgrading. So any software in Linux needs to put data in the `.config` and let user recover the previous working environment as soon as the user opens up the new version. Other UI/UX concerns needs to make place for this top priority.

**Comment by ngocle492** [comment]
Entire project just disappeared because `parentId` in the file `insomnia.Workspace.db` is `null `. Just update `parentId` from `null ` to `"proj_default-project"`, then restart Insomnia and see everything is back.

![image](https://github.com/Kong/insomnia/assets/67014925/3da215b9-525c-47eb-a4eb-6875a5059e15)

[My entire project just disappeared](https://github.com/Kong/insomnia/issues/5167#top)

**Comment by tummyacid** [comment]
parentId already shows "proj_default-project". No change in the bug.

**Comment by paulohliima** [comment]
Hope this walkthrough helps too.
In my case, I updated my insomnia through the ubuntu snap, and I lost all the collections I had. The solution was:

1 - Go to the personal folder, enable see hidden files.
2- Enter .config/Insomnia, and copy everything inside.
3 - Go to the newly installed insomnia, and in the help tab - show app data folder.
4 - Enter insomnia, and paste everything, overwrite.
5 - Close and open insomnia and that's it.

I hope it helped you. =)

**Comment by avdyushin** [comment]
> Entire project just disappeared because `parentId` in the file `insomnia.Workspace.db` is `null `. Just update `parentId` from `null ` to `"proj_default-project"`, then restart Insomnia and see everything is back.
> 
> ![image](https://user-images.githubusercontent.com/67014925/260608589-3da215b9-525c-47eb-a4eb-6875a5059e15.png)
> 
> [My entire project just disappeared](https://github.com/Kong/insomnia/issues/5167#top)

That one has to be somewhere in the Wiki/Readme as the issue still present in latest release (Version: Insomnia 2023.5.8
Build date: 9/7/2023)

**Comment by sepccom** [comment]
my version just auto-updated to 2023.5.8 and my whole collection is gone! not very happy. How do I get them back??

**Comment by sxt** [comment]
Same happened to me. Forced to either create an account & log in or use "scratchpad" - none of my requests/collections visible. Breathtaking that anyone would release software that does this.

For now I downgraded Insomnia : https://github.com/Kong/insomnia/releases/tag/core%402023.5.8

I have my stuff back, but only for as long as it takes to find an alternative to this software.

**Comment by padge** [comment]
This was the SECOND TIME I've upgraded Insomnia and lost all of my requests. The first time was a couple months ago and the second time was today with the latest version. Thankfully uninstalling and reverting back to 2023.5.8 brought them back. I just disabled automatic updates and plan to stay on this older version.

**Comment by KelseyDH** [comment]
I found a way to (partially) get my work back.  Go to `Help` -> `Show App Data Folder`

This will open the Insomnia folder.  Look for `backups`, inside the folders e.g. `2023.4.0` grab the `insomnia.insomnia.json` file. Then in the app go to collections, menu down to `Import` and upload this JSON file.  

That recovered part of my old work for me.  Your mileage will vary based on how recent the last backup was.  Inexcusable the devs pulled the rug on people like this.

**Comment by orlandodiaz** [comment]
I downgraded to release 2023.5.8 and that brought all my requests back. How can they force people to auto-update and not have a mechanism to prevent this. Its baffling how they released something like this complete disaster

**Comment by byjrack** [comment]
Even the export using a 2023.x and import to 8.0 using Insomnia v4 including environments didn't work completely for scratchpad.  the only full copy was the migration to the kong account.  Now I could copy paste the env from old to new, but yeah clearly they are funneling folks into using the SaaS for workspace and not try and stay offline.

**Comment by realjjaveweb** [comment]
Have the same issue when I try to upgrade from 2023.5.8 (snap package on Ubuntu(Linux)) - everything is GONE after update and I had to revert the snap version back... there really should have been some auto-migration. To revert snap package:
`sudo snap revert insomnia`

**Comment by nathan-mill** [comment]
https://github.com/ArchGPT/insomnium

**Comment by ereveresmith** [comment]
Just happened after auto update. Way to go Insomnia

**Comment by betterbuiltcows** [comment]
Lolol

**Comment by subnetmarco** [comment]
We are finally fixing this bug in Insomnia 8.4 this week or early next week.

**Comment by kamilszewczyk** [comment]
Yeah, have not been fixed.
I have not been updating for a long time (had version 2022.03 something), but finally today updated to latest 8.5.0. Everything gone, fortunately the tip:
> Entire project just disappeared because parentId in the file insomnia.Workspace.db is null . Just update parentId from null to "proj_default-project", then restart Insomnia and see everything is back.
still works and I was able to get everything back...

**Comment by subnetmarco** [comment]
In 8.5 we are surfacing un-synched projects in the footer, where they can be migrated using the application.

<img width="425" alt="Screenshot 2023-12-20 at 9 55 29 AM" src="https://github.com/Kong/insomnia/assets/964813/4a96b51a-3aec-497d-a6f5-20c3016c6334">

**Comment by kamilszewczyk** [comment]
For testing I have changed back the parentId to null and you're right - the info is there and internal tools do allow for moving the unsynced projects.
I would argue that it's not really a great UX type of notification especially on larger monitors, the bottom bar is super small and notification can be easily missed - but it is working.
Thank you!

**Comment by subnetmarco** [comment]
This has been a tricky bug for us to solve because it is hard to reproduce on our end. You are right that the projects should not be un-synched to begin with, and we are still working to identify the root issue. 

May I ask what operating system you are using?

**Comment by kamilszewczyk** [comment]
I am using Ubuntu 22.04.3LTS. As I said, I was upgrading from an old version (2022.03 something) to the latest one using deb packages downloaded from the website.

**Comment by sideeffffect** [comment]
It's happened again. For the second time already. All my library has disappeared. Again. I'm moving to a different app
https://alternativeto.net/software/insomnia-rest-client/?license=opensource

**Comment by subnetmarco** [comment]
@sideeffffect did this happen after an update? Your data may still be on your computer @marckong

**Comment by notjaywu** [comment]
@sideeffffect Can you check if your data is in the orphaned projects?

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/7dba747b-f3cc-4b11-a2ed-f1b16a8a6008">
