### ISSUE TITLE
Bulk Create in Query limits field of view

### ISSUE THREAD

**Issue by bergercode** [getinsomnia/insomnia#5613]
### Expected Behavior

When swapping to Bulk Edit you should be able to view the query field

### Actual Behavior

When swapping to Bulk Edit the URL preview window is crushed making it difficult to view content.

### Reproduction Steps

1. On any request go to Query table.
![image](https://user-images.githubusercontent.com/23620326/210679601-bfd7cc51-cd0d-41fe-bbdf-36577f02f4b3.png)

2. Select Bulk Edit (Notice the URL preview is crushed and you're not able to view the content properly)
![image](https://user-images.githubusercontent.com/23620326/210679656-3f5333e5-e910-458a-9977-d225a7fda54f.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

![image](https://user-images.githubusercontent.com/23620326/210679736-937386bf-72ae-4841-8fa6-78b8c8251473.png)
Version Insomnia 2022.7.0

### Insomnia Version

2022.7.0

### What operating system are you using?

Windows

### Operating System Version

Windows 64 bit

### Installation method

Download from Insomnia

### Last Known Working Insomnia version

2022.6.0

**Comment by bergercode** [comment]
Reverting to Version 2022.6.0 resolves this

**Comment by filfreire** [comment]
Hi @bergercode thanks for reporting this, I can also reproduce it!

**Comment by jgilbert** [comment]
Hi @bergercode thanks for reporting, I can verify this on MacOS as well.

**Comment by filfreire** [comment]
this is fixed in https://github.com/Kong/insomnia/pull/5795
fix will go out in tomorrows beta

**Comment by manbeing** [comment]
@filfreire  I am using Version: Insomnia 2023.2.2 on mac. 
is there anyway I could get this beta installed on mac? 
(unable to drag to enlarge 'Query Variables' section/region is really inconvenient to me)
