### ISSUE TITLE
Duplicate environment variables leads to Key Error, unusable UI

### ISSUE THREAD

**Issue by jcbeck37** [getinsomnia/insomnia#5617]
### Expected Behavior

1. Add duplicate environment names to different environments
2. A warning can be shown, but you can still use the UI

### Actual Behavior

1. The project file with a duplicate cannot opened.
2. An error is displayed, but with no recourse
3. The error is "Application Error", "Failed to render." "Please send the following error to support@insomnia.rest." "Can't insert key env_92c7fbb142dae52b245b193894f0c2bc2645be0c, it violates the unique constraint" "Try to reload the app"

### Reproduction Steps

1. Add duplicate environment names to different environments

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 22H2 OS build 19045.2364

### Installation method

Download

**Comment by VolodymyrBiryuk** [comment]
Same with following version:

Version: Insomnia 2022.7.0
Build date: 12/15/2022
OS: Darwin arm64 22.2.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64

**Comment by awestphal** [comment]
Maybe it's the same issue that occurs if you export a collection an try to import it. This ends in `Can't insert key env_02f2448da27690815b8e7e0dedf62a96342e3dc6, it violates the unique constraint`

![image](https://user-images.githubusercontent.com/4941139/211865913-8eea2f02-1af8-46cc-91f8-e669b61d38d4.png)
