### ISSUE TITLE
[Bug] Glob matching on certificate ports doesn't work

### ISSUE THREAD

**Issue by robzienert** [getinsomnia/insomnia#564]
- Insomnia Version: 5.10.1.1329
- Operating System: OSX

It would appear that star matching doesn't work with client certificates. Take for example we have two services listening at `localhost:8080` and `localhost:8081` that use the same p12 cert. Adding a certificate where the host is `localhost:*` results in a SSL connect error, however individual cert entries for each port, with the same p12, works fine.

**Comment by gschier** [comment]
Globs currently don't work on ports but this should be an easy thing to implement.

**Comment by gschier** [comment]
Btw thanks for finding and bringing up all the quirks of this little-used feature. It will surely be a lot more usable soon 😀
