### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by SardorMS** [getinsomnia/insomnia#5640]
### Expected Behavior

Good afternoon!
Today I ran into a problem. I don't know what to do, since I can't export my collection of queries

What could be the problem and how can it be fixed?

<img width="507" alt="Снимок экрана 2023-01-10 в 10 48 08" src="https://user-images.githubusercontent.com/76259562/211471544-4cda9131-f9ba-489c-9289-8ec91467b8e2.png">

### Actual Behavior

Just opening the app

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.1

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.1

### Installation method

Insomnia.***.dmg

### Last Known Working Insomnia version

2022.7.1

**Comment by SardorMS** [comment]
The problem is solved. I download it again and install it on top of the current version and it's working.

Everything is fine of course, but what is the problem is still not clear.

**Comment by crisz** [comment]
It happened the same to me this morning. Not a coincidence for sure

**Comment by crisz** [comment]
@SardorMS I advise you to change the title of the issue and include the first line of the error message. In this way other people encountering this error message will happen here

**Comment by SardorMS** [comment]
> @SardorMS I advise you to change the title of the issue and include the first line of the error message. In this way other people encountering this error message will happen here

Done

**Comment by filfreire** [comment]
Hi folks this was happening if you installed Insomnia yesterday for a few hours due to a bad build of `2022.7.1` for MacOS that got wrongfully published. You might be affected if you installed or updated insomnia around 11:00 am and 2:45 pm GMT - you will get this error.

In case you are affected by this - re-download the latest `2022.7.1` from https://github.com/Kong/insomnia/releases and re-install it.

**Comment by Beil1984** [comment]
![Screenshot_2024-10-07-01-51-18-99_c37d74246d9c81aa0bb824b57eaf7062](https://github.com/user-attachments/assets/97b85c57-23b0-4111-98fd-833148ead40d)
