### ISSUE TITLE
 Edit Tag modal doesn't open

### ISSUE THREAD

**Issue by lyrixx** [getinsomnia/insomnia#5642]
### Expected Behavior

https://docs.insomnia.rest/insomnia/chaining-requests#configure-a-tag

According to the documentation, when I click on a tag, insomnia should open a modal

### Actual Behavior

it's not the case anymore. Nothing happens when I click on a tag

![image](https://user-images.githubusercontent.com/408368/211525690-99a3e534-277e-4baa-bbb5-c2307e1d6f54.png)

It's the same for other tag (in JSON body)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2022.7.1
Build date: 1/9/2023
OS: Linux x64 5.15.0-48-generic
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

### Insomnia Version

Insomnia 2022.7.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.1 LTS

### Installation method

from the .deb 

### Last Known Working Insomnia version

"last year" it used to work

**Comment by jackkav** [comment]
Disable `Raw template syntax` in preferences.

**Comment by lyrixx** [comment]
Thanks 👍🏼 💛 
Works like a charm
