### ISSUE TITLE
Importing .json collection in other applications

### ISSUE THREAD

**Issue by brundabharadwaj** [getinsomnia/insomnia#5649]
### Discussed in https://github.com/Kong/insomnia/discussions/5646

<div type='discussions-op-text'>

<sup>Originally posted by **brundabharadwaj** January 11, 2023</sup>
The '**export collection**' feature of insomnia is fantastic . But it would be really helpful if the  json format is compatible such that it could be imported in other tools like postman as well.
 As .json are shared across team it's not necessary that everyone would be using the same tool.
Currently insomnia json is not importable by other application and it's a quite needed feature  . </div>

**Comment by filfreire** [comment]
Closing this one in favour of the #5646 discussion.
