### ISSUE TITLE
Wrong Enum Query Variable breaks rendering

### ISSUE THREAD

**Issue by finsterwalder** [getinsomnia/insomnia#5651]
### Expected Behavior

I can enter anything in the query variable section, even values not understood by my API, and still the UI is rendered and I can keep editing the variables

### Actual Behavior

As soon as I type an invalid enum value into a query variable, the API does not render at all anymore.

### Reproduction Steps

1. Create a GraphQL query with a parameter, that references an enum type.
2. Enter Query variables for this enum type, like "action": "DISCONNECT" in the screenshot below. DISCONNECT is a valid enum value
![Screenshot 2023-01-11 at 13 29 32](https://user-images.githubusercontent.com/206574/211808646-730ce43f-34fa-43d4-a425-e8d519635d52.png)
3. Change the variable to a value, that is not a valid enum value, for example by deleting a single character 
![Screenshot 2023-01-11 at 13 29 51](https://user-images.githubusercontent.com/206574/211809016-fb0100e3-6c14-424b-bbd8-fbc35fd52bac.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This error is unrecoverable. You have to quit Insomnia and restart. When you then open the query again, it immediately breaks again. You have to delete the query to fix it.

### Insomnia Version

2022.7.1

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.1 (22C65)

### Installation method

brew install

### Last Known Working Insomnia version

2022.5.1

**Comment by filfreire** [comment]
This is fixed in https://github.com/Kong/insomnia/commit/bdce88d4d3bfd6981daba264884aac05eac01701, will go out in 2022.7.2

**Comment by finsterwalder** [comment]
Thanks for the quick response. When do you expect to release 2022.7.2 roughly?

**Comment by filfreire** [comment]
@finsterwalder it will go out later today

**Comment by finsterwalder** [comment]
Wonderful! Thanks a lot!
