### ISSUE TITLE
Name resolution failure with gRPC server reflection

### ISSUE THREAD

**Issue by terrakuh** [getinsomnia/insomnia#5659]
### Expected Behavior

When using environments in request collections and using a property for the server endpoint, the actual value should come from the environment.

### Actual Behavior

The field is not resolved and an error is thrown:

```txt
UNAVAILABLE: Name resolution failed for target dns:{{ _.server }}
```

### Reproduction Steps

1. Create an environment with the property `"server"` and set it to the endpoint address of your gRPC server.
2. Create a new gRPC request and set the endpoint to `"_.server"`.
3. Click on "use server reflection".

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Environment:

```json
{
  "server": "127.0.0.1:50051"
}
```

Error message from developer console:

![image](https://user-images.githubusercontent.com/16595452/212062956-3b6ee86f-9e12-49c6-adc9-ac0850e3a1d6.png)

### Insomnia Version

2022.7.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.10

### Installation method

Downloaded .DEB directly

**Comment by jackkav** [comment]
Thanks for the report @terrakuh this is underway.
