### ISSUE TITLE
Requests are not sent when Filter responses by Environment is enabled

### ISSUE THREAD

**Issue by relgames** [getinsomnia/insomnia#5664]
### Expected Behavior

When I click Send, I should see HTTP response on the right

### Actual Behavior

No response is shown, just the keyboard shortcuts:

<img width="1955" alt="Screenshot 2023-01-13 at 11 29 23" src="https://user-images.githubusercontent.com/179605/212298544-09d4dfe8-0ab2-468f-930c-664069d60561.png">

### Reproduction Steps

1. Create a new request for any site, for example https://google.com
2. Click Send

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.2

### What operating system are you using?

macOS

### Operating System Version

MacOS 22.2.0

### Installation method

homebrew

### Last Known Working Insomnia version

2022.7.1

**Comment by relgames** [comment]
I just tried on 2022.7.1 and it works fine there. So the problem is in 7.2

**Comment by filfreire** [comment]
Hi @relgames, on `2022.7.2`, do you happen to see any error logs on the dev tools when sending a request?


<img width="1654" alt="devtools" src="https://user-images.githubusercontent.com/11976836/212303067-dcb48ffc-c451-4644-a71a-2a89eefc1f4c.png">

**Comment by relgames** [comment]
No errors:

<img width="1652" alt="Screenshot 2023-01-13 at 11 55 39" src="https://user-images.githubusercontent.com/179605/212303934-901fd23a-8520-4f58-8c1f-9771b4094039.png">

Here is the video of the issue:

https://user-images.githubusercontent.com/179605/212304111-36087960-6ef2-4d47-affe-8eafd34ea690.mov

**Comment by vlad-s** [comment]
Can confirm on MacOS Ventura 13.1 with Insomnia v2022.7.2. 

However I was able to "fix" it temporarily by unchecking filtering responses by environment. I use multiple environments and having different responses per env. is very useful to me.

![image](https://user-images.githubusercontent.com/7457966/212305348-ac74ce04-08ed-405f-bb46-1f17ece7dd85.png)

**Comment by Fdawgs** [comment]
Also encountering this on Windows 10 Enterprise 21H2 (19044.2486) with Insomnia v2022.7.2.
