### ISSUE TITLE
[Development] error in npm install insomnia-node-libcurl@1.2.3

### ISSUE THREAD

**Issue by mohitsoam** [getinsomnia/insomnia#567]
Hi

Getting below error in npm install... tried with different machines (Windows 8 + Visual Studio 2015) and (windows 10 + Visual studio 2017) same error in both machine... find the log below.

--------------------------

36451 silly install insomnia-node-libcurl@1.2.3
36452 info lifecycle insomnia-node-libcurl@1.2.3 install: insomnia-node-libcurl@1.2.3
36453 verbose lifecycle insomnia-node-libcurl@1.2.3 install: unsafe-perm in lifecycle true
36454 verbose lifecycle insomnia-node-libcurl@1.2.3 install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\insomnia\insomnia\node_modules\insomnia-node-libcurl\node_modules\.bin;D:\insomnia\insomnia\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Rohit\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\Rohit\AppData\Roaming\npm
36455 verbose lifecycle insomnia-node-libcurl@1.2.3 install: CWD: D:\insomnia\insomnia\node_modules\insomnia-node-libcurl
36456 silly lifecycle insomnia-node-libcurl@1.2.3 install: Args: [ '/d /s /c', 'node-pre-gyp install --fallback-to-build' ]
36457 silly lifecycle insomnia-node-libcurl@1.2.3 install: Returned: code: 1  signal: null
36458 info lifecycle insomnia-node-libcurl@1.2.3 install: Failed to exec install script
36459 verbose unlock done using C:\Users\Rohit\AppData\Roaming\npm-cache\_locks\staging-4c22de6916bfba55.lock for D:\insomnia\insomnia\node_modules\.staging
36460 warn optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules\7zip-bin-mac):
36461 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
36462 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
36462 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
36462 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
36462 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: ia32
36463 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.1 (node_modules\fsevents):
36464 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
36465 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
36465 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
36465 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
36465 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: ia32
36466 verbose stack Error: insomnia-node-libcurl@1.2.3 install: `node-pre-gyp install --fallback-to-build`
36466 verbose stack Exit status 1
36466 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
36466 verbose stack     at emitTwo (events.js:135:13)
36466 verbose stack     at EventEmitter.emit (events.js:224:7)
36466 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
36466 verbose stack     at emitTwo (events.js:135:13)
36466 verbose stack     at ChildProcess.emit (events.js:224:7)
36466 verbose stack     at maybeClose (internal/child_process.js:943:16)
36466 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
36467 verbose pkgid insomnia-node-libcurl@1.2.3
36468 verbose cwd D:\insomnia\insomnia
36469 verbose Windows_NT 6.2.9200
36470 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
36471 verbose node v9.0.0
36472 verbose npm  v5.5.1
36473 error code ELIFECYCLE
36474 error errno 1
36475 error insomnia-node-libcurl@1.2.3 install: `node-pre-gyp install --fallback-to-build`
36475 error Exit status 1
36476 error Failed at the insomnia-node-libcurl@1.2.3 install script.
36476 error This is probably not a problem with npm. There is likely additional logging output above.
36477 verbose exit [ 1, true ]

------------------------------------------------------

**Comment by gschier** [comment]
Hmm, I don't actually see any error messages in there except that it exited with status code 1.

I haven't tried this with node 9 yet. Can you try it with node 8 and see if that makes a difference?

Also, it seems like it's failing trying to build `insomnia-node-libcurl`. Maybe the Windows-specific instructions in that repo would help? https://github.com/JCMais/node-libcurl#windows

_Disclaimer: I'm not a Windows user so may not be able to help much further_ :(

**Comment by gschier** [comment]
Also, I just noticed that you are on a 32-bit architecture. I have no idea if that could be the problem, but it's possible as I've never built Insomnia for 32-bit.

**Comment by mohitsoam** [comment]
Thanks Gregory for the quick reply:)

First I tried by moving to node 8, but it didn't work.

Then I dig down the node-libcurl [repo](https://github.com/JCMais/node-libcurl#windows) as suggested as found an issue and after that fix it worked in both the windows machine. Find the details below...
--------------------
npm install is failing in... [Line 6 of update-deps.js](https://github.com/JCMais/node-libcurl/blob/develop/tools/update-deps.js)

**Line 6 -->  'git submodule update --init --recursive && python deps/curl-for-windows/configure.py',**
    
function ( err ) {
        if ( err ) {
            console.log( err.toString() );
**Line 12 -->  process.exit( 1 );**
        }
        process.exit( 0 );
    }

And it was getting exited with status code 1 from Line 12. 
---------------------------
**Fix:** Updated the python path in env. variables

**Comment by mohitsoam** [comment]
Fix: Updated the python path in env. variables

**Comment by gschier** [comment]
Oh wow, nice work finding that one! 👍
