### ISSUE TITLE
Failed to render request in GraphQL

### ISSUE THREAD

**Issue by darwinphi** [getinsomnia/insomnia#5676]
### Expected Behavior

Should work.

### Actual Behavior

Failed to render request.

### Reproduction Steps

1. Run GraphQL request
2. Pop up shows `Failed to render request`

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.2

### What operating system are you using?

macOS

### Operating System Version

MacOS  Version 12.4

### Installation method

Download from website

**Comment by filfreire** [comment]
Hi @darwinphi - can you provide a few more details into how you are getting this and perhaps some screenshots?

Can you also double-check if you are using the correct latest insomnia build?

**Comment by filfreire** [comment]
Hi @darwinphi this should no longer be happening in [2022.7.5](https://github.com/Kong/insomnia/releases/tag/core%402022.7.5)

**Comment by lukasholzer** [comment]
Still happening for me on the latest version: `Version: Insomnia 2022.7.5`
![CleanShot 2023-03-08 at 14 29 12](https://user-images.githubusercontent.com/11156362/223725684-1416b193-c02e-463b-9682-292fc19a8e0b.png)

The same request works fine in graphql playground
