### ISSUE TITLE
I lost all my requests after 2022.7.2 update

### ISSUE THREAD

**Issue by narwajea** [getinsomnia/insomnia#5679]
### Expected Behavior

Open Insomnia and see all my requests.

### Actual Behavior

No collection available.

### Reproduction Steps

Create some requests then update from an old version to 2022.7.2.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro N - version 22H2 - build 22621.1105

### Installation method

Windows installer Insomnia.Core-2022.3.0.exe then internal update

### Last Known Working Insomnia version

2022.7.1

**Comment by filfreire** [comment]
Hi @narwajea, the requests might still be there, please check [this comment](https://github.com/Kong/insomnia/issues/5540#issuecomment-1354706182) and let us know if it helped with your issue.

**Comment by narwajea** [comment]
https://github.com/Kong/insomnia/issues/5600#issuecomment-1368057668 solved my issue. Looks like a regression though, the update shouldn't change the default view.

**Comment by narwajea** [comment]
> Hi @narwajea, the requests might still be there, please check [this comment](https://github.com/Kong/insomnia/issues/5540#issuecomment-1354706182) and let us know if it helped with your issue.

Yes it did, same procedure in distinct comment.
