### ISSUE TITLE
[Improvement] More unique temporary directory

### ISSUE THREAD

**Issue by marcellmars** [getinsomnia/insomnia#568]
probably not a showstopper for most of the users but i would suggest for insomnia devs to use some prefix before insomnia temporary file(s) situatued in /tmp on linux.. it happened that i had a file named insomnia (a long story which would potentially make this issue more hillarious but not really relevant for the suggestion)

**Comment by gschier** [comment]
This should be an easy change. I'd be happy to make the temp dir more unique.
