### ISSUE TITLE
Can no longer reorder headers in the request panel

### ISSUE THREAD

**Issue by RobProductions** [getinsomnia/insomnia#5686]
### Expected Behavior

In previous versions of Insomnia as can be seen by this screenshot, I was able to reorder my headers from the request panel with a little drag panel that was seen on the left of each item. I was also able to add new headers by just typing into the "new header" box that appeared at the bottom of the list.

![image](https://user-images.githubusercontent.com/11141862/212743411-95c62eff-bd9d-4262-996b-e2344a000fbc.png)

### Actual Behavior

Now when opening Insomnia 2022.7.1, I don't see the reorder panel or the "New Header" box and can only add headers via the onscreen button:

![image](https://user-images.githubusercontent.com/11141862/212744474-4b6171c8-1890-45cf-b92d-db8eb32aefcf.png)

I'm not sure if this is some sort of bug I'm facing or intentional removal, but it seems like a regression from earlier versions as I can no longer find a way to order my headers except for deleting them and adding them again. This removes a ton of convenience and organization from my requests and makes it harder to parse through my headers at a glance. The new header box was also convenient as it saved a click when I wanted to add a new header, but for me it's not as drastic an adjustment as the lack of reordering. 

If this is an intentional change, I would hope that there could at least be an option to restore the old behavior as the data organization aspects are why I use Insomnia in the first place. But I'm not seeing anything like that in the preferences right now. 

### Reproduction Steps

1. Create a new request
2. Add 2 headers in the Header panel
3. Observe that there is no way to change the header order

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Here is the "About Info" provided by Insomnia: 

Version: Insomnia 2022.7.1
Build date: 1/9/2023
OS: Windows_NT x64 10.0.19044
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

### Insomnia Version

2022.7.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Downloaded from internet

### Last Known Working Insomnia version

2022.5(?)

**Comment by filfreire** [comment]
@RobProductions this is a valid issue, the reorder functionality was removed in order to fix other bugs for now.

**Comment by ryl** [comment]
The prior interface worked better for me, too. Some headers are nice to have near each other, but if you copy an old request to make a new one, you can't add new headers in a place that keeps them neatly organized.

**Comment by maxcoe** [comment]
> @RobProductions this is a valid issue, the reorder functionality was removed in order to fix other bugs for now.

Thanks for the info. This affects also the other request tabs. Hope reordering will come back!
