### ISSUE TITLE
relaunch the app for it to take effect, no effect.

### ISSUE THREAD

**Issue by erlangparasu** [getinsomnia/insomnia#5689]
### Expected Behavior

lauched newer version

### Actual Behavior

still showing old version

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### Installation method

download

### Last Known Working Insomnia version

-

**Comment by wongstein** [comment]
Hello, have you tried uninstalling and reinstalling the App?

**Comment by erlangparasu** [comment]
@wongstein 
yes i tried reinstalling insomnia, but doesnt solve this issue

```
Version: Insomnia 2022.7.4
Build date: 1/18/2023
OS: Darwin x64 19.6.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64
```

Screenshot-1
![image](https://user-images.githubusercontent.com/20636828/214195799-2ac66fc7-c6ba-4a21-8f94-fefb22d17f4c.png)

Screenshot-2
![image](https://user-images.githubusercontent.com/20636828/214195861-bd4ba74f-d057-49ee-a656-b8ae652406f2.png)

**Comment by wongstein** [comment]
@erlangparasu could you explain the problem you're having more?  From the original description it sounds like you tried upgrading the app and it didn't upgrade.  But from the response you just sent me, you were able to successfully install the app on the newer version.  Is it the auto-update that is the issue?

**Comment by erlangparasu** [comment]
1. i open insomnia (v2022.7.4)
2. i open **Preferences**
3. i click **Check Now** on section **Software Update**
4. insomnia show **Downloading...**
5. insomnia show **Updated (Restart Required)**
6. i exit insomnia
7. i open insomnia (again), it still same version (v2022.7.4)
8. i click **Check Now** on section **Software Update**
9. insomnia show **Downloading...** 
10. insomnia show **Updated (Restart Required)** 
11. i exit insomnia
12. i open insomnia (again), it still same version (v2022.7.4)

**Comment by DanielRouxSA** [comment]
I experienced the same today, also with the update from 2022.7.4 -> 2022.7.5, also on MacOS (13.2 in my case).

I was able to successfully complete the update by leaving the app closed for about a minute before opening it again. It seems as if reopening the app too quickly causes the update to be aborted.

Perhaps it should be considered to implement a function where the app can actively relaunch itself to update, instead of the user having to manually reopen it?

**Comment by ahlixinjie** [comment]
> 

tried, failed :(

**Comment by DaveLak** [comment]
I had the same issue updating from 2022.7.5 -> 2023.1.0 on macOS 13.2.1.

@DanielRouxSA's comment about waiting for a minute or so before relaunching the app also worked for me. After waiting, the app updated successfully.

>I was able to successfully complete the update by leaving the app closed for about a minute before opening it again.

**Comment by erlangparasu** [comment]
@DanielRouxSA @DaveLak Thank you! That solution works for me too

**Comment by kokoshneta** [comment]
Same issue updating from 2023.1.0 to 2023.2.0.

There really should be a way for the app to actively relaunch itself and apply the update as part of the process, as virtually all other apps have. This ‘quit and relaunch the app to update’ thing is very odd to begin with, and when it then doesn’t work unless you give it extra time…

**Comment by sigseg5** [comment]
Same for 2023.2.2 → 2023.3.0

**Comment by erlangparasu** [comment]
I think Insomnia must remember what version has been downloaded. Then in case update not finished yet, in Insomnia Settings should keep showing **Updated (Restart Required)** status rather than showing **Check Now** button, and **Downloading** again.
