### ISSUE TITLE
A javascript error occurred in the main process

### ISSUE THREAD

**Issue by lipecss** [getinsomnia/insomnia#5690]
### Expected Behavior

![image](https://user-images.githubusercontent.com/40566871/212888557-082d570a-e831-4c73-8410-6695df913fac.png)

I am getting the following error when trying to open my insomniac. It was working and after the windows update (I have windows 11) it stayed like this. How could it solve?

### Actual Behavior

When I try to open it, I get this error

### Reproduction Steps

- Open insomnia
- getting this error

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.3

### What operating system are you using?

Windows

### Operating System Version

windows 11 10.0.25272

### Installation method

I downloaded it from the insomnia website

### Last Known Working Insomnia version

2022.7.2

**Comment by filfreire** [comment]
@lipecss do you still get this error message if you do a clean install of latest Insomnia?
