### ISSUE TITLE
Create Snapshot, Pulle and Push not work !

### ISSUE THREAD

**Issue by dcesana** [getinsomnia/insomnia#5697]
### Expected Behavior

Create Snapshot, Pulle and Push not work more from 3 days.

### Actual Behavior

Create Snapshot, Pulle and Push not work more from 3 days.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

Download Insomnia.Core-2022.7.4.exe

**Comment by filfreire** [comment]
@cedaweb, I assume you are using Insomnia Sync instead of Git Sync, correct? 
Do you see any error messages when attempting to create/push/pull snapshots?

**Comment by dcesana** [comment]
yes i use Insomnia Sync, when i press "Creata Snapshot" or "Pusjh" noting happen

**Comment by filfreire** [comment]
@cedaweb Perhaps try to logout and login back into Insomnia.

**Comment by whaaaley** [comment]
Same here on win11. It worked yesterday, and today it does not. :c -- Relogging does nothing.
The issue started when I tried to push but there were other changes. I reverted my changes, pulled, then tried to make a new update, but everything just doesn't work. None of the menu items do anything.

**Comment by brechtvhb** [comment]
Why was this closed? I don't see a working solution (having the same problem).

**Comment by jorgeacaballero** [comment]
This issue still persists. Why is is closed?

**Comment by MaharshiDubasi** [comment]
I'm also still experiencing this issue

**Comment by Mesheo** [comment]
Hey guys I use windows11 and after opening insomnia as **admin** these functions came back to normal, please let me know if anybody had the same experience. 
Hope it helps

_I dont understand why this was already closed when i posted_
