### ISSUE TITLE
OAuth 2.0 authentication issues after 2022.7.4

### ISSUE THREAD

**Issue by Drivez** [getinsomnia/insomnia#5700]
### Expected Behavior

When using OAuth 2 implicit grant type I can authenticate against AzureAD and get authenticated using the response type Access Token I get an error on not chosen response type 

### Actual Behavior

no response type is selected in the OAuth tab, but the dropdown is showing response type Access Token.

### Reproduction Steps

I need to change the response type dropdown to ID Token, then back to Access Token for it to be selected.
Seems like the dropdown selection is not default set, so you need to select something else and back for it to be set.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.4

### What operating system are you using?

macOS

### Operating System Version

13.1 (22C65)

### Installation method

insomnia.rest

### Last Known Working Insomnia version

2022.6.0

**Comment by riley-van-hengstum** [comment]
Same issue here.

**Comment by jackkav** [comment]
Thanks for the report, I've got it defaulting to access token again, will be fixed in the next dot release.
