### ISSUE TITLE
[Feature-request] Re-add OpenAPI/Swagger preview to design

### ISSUE THREAD

**Issue by filfreire** [getinsomnia/insomnia#5712]
Since [2022.7.0 onwards](https://insomnia.rest/changelog#2022.7.0) the OpenAPI/Swagger preview was temporarily removed to add support for OpenAPI 3.1 specs.

Different users are reaching out through insomnia slack and also [through comments on the original PR](https://github.com/Kong/insomnia/pull/5457) that removed the OA spec preview asking if it's possible to add it back.

This GH issue is created so we can track progress on bringing the feature back - perhaps temporarily disabled only for OA 3.1 and above specs.

**Comment by chaz4short** [comment]
Seriously This!. Why remove a feature?? Also the open API Yaml file keeps giving me errors I didnt have before but not sure where place that is issue or if other people are have that problem.

**Comment by MrStanDu33** [comment]
I personally thinks that the Swagger UI preview pannel should have never been deleted.  🫠

From what I have heard, they removed de preview for multiple reasons :
- In documents projects, the `DEBUG` tab makes possible to test documented API, making "useless" to test the documented endpoint from the preview.
- It was "crowding the editing experience".
- The Swagger UI preview was not working with OpenAPI specification version `3.1`.

Here are my thoughts about those points :
- Regarding the first point, I do not think tha it was that "useless", As it still offers a way to check if given response was documented or not and a way to check wether or not our documentation was write correctly, but I can understand this point of view.
- Regarding the second point, I personally think that it was not that much of a problem, and it could be resolved by adding a toggle button, or add a setting inside the user preferences to display or not the preview panel.
- Regarding the third point, as a lot of person already said in #5457, I think that we should have just a warning when we work on OpenAPI specification version `3.1` that the preview panel is not available as Swagger UI is not compatible yet with OpenAPI specification version `3.1` documents.

If we implement a button (or an option in user's settings) to toggle the preview panel, it should solve all current problems that were listed above, and it also could be used to explain to the user that Swagger UI is not compatible with written document. 🤔

A note about the first point, I hear that the test function is available in the `DEBUG` panel, but it does not replace ALL the features that Swagger UI has. Like those :
- Check wether or not the endpoint has authentication protection.
- What are all possible API responses
- All requests payloads types available (`multipart/formdata`, `application/json`, ...)
- Details about all properties of payload (type, format, optional or not ...)
- Description of the endpoints / responses ...

I do not say that I have all the solutions to this problem, but we should discuss around this subject, and maybe find ways to arrange everybody. 🤷‍♂️

**Comment by lucianojs** [comment]
Swagger preview now works with OpenAPI 3.1.0 - https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.0

**Comment by MrStanDu33** [comment]
I really hope they gonna re-implement the preview, and why not add an option as said earlier to toggle preview if they feel it really crowds the editing experience. 🤞

I cannot wait to see what they think about this request. 👀

**Comment by Naxos84** [comment]
I also think that the preview should be readded.
Because in the preview I can provide example values for parameters.
![image](https://user-images.githubusercontent.com/17813025/228813028-e4433afb-e230-4442-b2a9-dbe2d95abb1a.png)

When exploring the API and its capabilities this helps a lot I think.

**Comment by NicholasMata** [comment]
Should probably update https://insomnia.rest as it shows this feature right on the homepage, as well as in docs. 

Kind of misleading now 😛

**Comment by subnetmarco** [comment]
This is coming back soon - we are prioritizing it.

**Comment by MrStanDu33** [comment]
Insomnia has been updated to [2023.2.0](https://github.com/Kong/insomnia/releases/tag/core%402023.2.0)

And preview [has been reintroduced](https://insomnia.rest/changelog#2023.2.0:~:text=Added%20back%20UI%20preview%20mode%20alongside%20OpenAPI/Swagger%20spec%20editor), now supporting OpenAPI 3.1 Specifications 🎉

Thank's to the dev team, it's a great thing to add back this feature.
