### ISSUE TITLE
[Improvement] Plugin Cookie Jar API

### ISSUE THREAD

**Issue by dgoosens** [getinsomnia/insomnia#572]
hi

Following on discussion on Twitter  
<https://twitter.com/GetInsomnia/status/926717993710772224>

As discussed, it should be possible for a plugin to unset, if not any cookie, at least the cookies that were created by the plugin.  
In my particular case, I need to add a cookie named `XDEBUG_SESSION` to enable Xdebug...  
But need to remove the cookie to disable it Xdebug.

*More on Xdebug here: <https://xdebug.org/>*

I did see this note at the bottom of  `app/plugins/context/request.js`:

```js
// NOTE: For these to make sense, we'd need to account for cookies in the jar as well
// addCookie (name: string, value: string): void {}
// getCookie (name: string): string | null {}
// removeCookie (name: string): void {}
```

So these methods have not been implemented yet.  
Also tried to pass and empty string or `null` as value, in the hope these would reset the cookie, but that isn't the case.

Guessing the `removeCookie ()` would be the best solution...  
But accepting `null` as value to `setCookie()` would be perfectly fine for me.

Thanks in advance,  
@dgoosens

**Comment by gschier** [comment]
Quick thought @dgoosens...

`addCookie()` doesn't actually save the cookie in the jar. It just tells the current request to send it. So, simply not calling `addCookie()` the next time should cause it to not be sent.

Does this flow not work for you, or are you somehow getting back a `set-cookie` header that's adding the cookie to the jar?

... Either way, I think modifying the cookies in the jar should be a supported feature of the plugin API.

**Comment by dgoosens** [comment]
hi @gschier 

Not using `addCookie()` but `setCookie()` as it is described in the API's documentation  
(section Request Hook API <https://insomnia.rest/documentation/plugins/#request-hook-api>)

**Comment by gschier** [comment]
Sorry. setCookie is what I meant to say.

**Comment by dgoosens** [comment]
OMG...  
Why didn't I think of that !!

Just tested and that seems to work...  
Nice !

Thanks

**Comment by gschier** [comment]
Haha. Sometimes the simple things are easy to miss. Happens to me all the time 😄
