### ISSUE TITLE
Response not visible

### ISSUE THREAD

**Issue by crimsonvspurple** [getinsomnia/insomnia#5721]
### Expected Behavior

Response will be visible after a call.

### Actual Behavior

It shows the loading during call but after that, back to initial screen.

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/11375716/214611754-f23abd09-7001-4d12-be0b-8b5c232fb7ea.png">

### Reproduction Steps

1. Call any endpoint.
2. Response does not show up

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This started happening since last update I believe. At first I thought it was just one collection or something.

I deleted the whole thing and pulled old working project from git and it is still doing same thing.
Tried another projecct. Same.

Didn't notice any errors in dev tools either.

### Insomnia Version

2022.7.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

downloaded from site

**Comment by filfreire** [comment]
@crimsonvspurple this was reported in https://github.com/Kong/insomnia/issues/5664, and is fixed since then.

Try to update to [latest version 2022.7.5](https://github.com/Kong/insomnia/releases/tag/core%402022.7.5)

**Comment by crimsonvspurple** [comment]
Hey.

Thank you. I just came back after being able to fix it by a full reinstall. For some reason I was still in previous version. I've always seen it auto update itself; not sure why it was not updating for weeks.

The "check now" auto update inside preferences is not very discoverable. I'd suggest adding a check for new version in "HELP" menu or inside "About" dialog box.

Thank you.
