### ISSUE TITLE
[Question] Does streaming responses display in realtime on insomnia?

### ISSUE THREAD

**Issue by Aqueelmiq** [getinsomnia/insomnia#573]
I was wondering if streaming responses are supported in Insomnia.
Does it print out responses as they come or does it wait till the connection closes?

**Comment by gschier** [comment]
@Aqueelmiq right now they only display once the request completes.

**Comment by flavienbwk** [comment]
What's the status now ?

**Comment by praagyajoshi** [comment]
Hello, has there been any movement on this topic? Thanks!

**Comment by Alumniminium** [comment]
I want this too.

**Comment by stouch** [comment]
I'd love this too :)

**Comment by dejavu1987** [comment]
It doesnt seem to end??? Can anyone confirm that this work as mentioned, (once the request completes)
<img width="396" alt="image" src="https://github.com/Kong/insomnia/assets/1720245/4d501ad1-f9eb-4efa-a3d4-d038a94d440c">

**Comment by lucebert** [comment]
+1, why it is closed ?

**Comment by kevinknights29** [comment]
This feature should be added. 
Looking forward to hearing more about this!

**Comment by AAR072** [comment]
Is there any update on this feature?

**Comment by luanhenzo** [comment]
Any update?

**Comment by JohnRhaenys** [comment]
It's been a feature. However, you need to select it when you create the request. You can't change it after having created the request. Just create a new request and select "Event Stream Request (SSE)". It will display the chunks of the stream as they come from the backend.

![image](https://github.com/user-attachments/assets/84d90347-425c-41dc-9b2f-a01ed2e5d563)

**Comment by johnstonmatt** [comment]
This seems to be driven by the Header
`Accept: text/event-stream`

The resulting stream is rendered as a table like the following:
<img width="567" alt="Screenshot 2024-11-19 at 12 21 12 AM" src="https://github.com/user-attachments/assets/785749fd-f7fe-4a39-8d85-db6dae8d920a">

That's fine, but the use-case on my end is to read a document as it loads, the extra formatting with the date makes the whole thing illegible. It would be nice to have a flag where we get a RAW preview which is just growing in length with every chunk/event
