### ISSUE TITLE
HEAD Method not returning a response body

### ISSUE THREAD

**Issue by drGeoBN** [getinsomnia/insomnia#5736]
### Expected Behavior

Making a HEAD request to localhost: 

![image](https://user-images.githubusercontent.com/97281801/215124902-086f6155-adfd-46cd-b653-1766953eaea5.png)

Expecting to see response body like: 

![image](https://user-images.githubusercontent.com/97281801/215125049-62e70cd9-05ca-415a-a94e-e94992206a75.png)

Instead I get:
![image](https://user-images.githubusercontent.com/97281801/215125163-62695851-0507-4dd8-aa5c-483fd7ba9cc7.png)

### Actual Behavior

Actual behavior is that no response body is given.  

### Reproduction Steps

- Setup elasticsearch with docker locally 
- Make HEAD request with insomina

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.5

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.1

### Installation method

download from insomina.rest

**Comment by zImPatrick** [comment]
Are you sure that this is an insomnia issue? [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) says HEAD requests shouldn't return any content; and if it has some content anyway, it should be ignored

**Comment by drGeoBN** [comment]
Ok! That seems resonable that request body should be ignored. Missed the MDN docs, thanks for your time and input.
