### ISSUE TITLE
Right click for dropdowns no longer works on beta

### ISSUE THREAD

**Issue by xXBuilderBXx** [getinsomnia/insomnia#5738]
### Expected Behavior

Right clicking on some collections, projects and http requests would open up the dropdown for that component.

### Actual Behavior

You can no longer right click to open a dropdown for the component.

### Reproduction Steps

1. Go to a collection
2. Right click a http request in sidebar
3. Dropdown does not open

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This is likely bugged due to #5615 reworking of the dropdowns.

### Insomnia Version

2023.1.0-beta.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

Download from main website

**Comment by filfreire** [comment]
Hi @xXBuilderBXx thank you for reporting this! Seems this particular functionality was removed in recent dropdown refactors we did. We'll update you here if there are fixes/changes on this. Feel free to create other issues of things you find 🙇

**Comment by rjcalifornia** [comment]
> Hi @xXBuilderBXx thank you for reporting this! Seems this particular functionality was removed in recent dropdown refactors we did. We'll update you here if there are fixes/changes on this. Feel free to create other issues of things you find 🙇

Why would you do this? This is adding one more extra click to open the drop down menu. This is bad, and you should feel bad about it. Please, return this functionality back.

Also, relevant xkcd: https://xkcd.com/1172/

**Comment by xXBuilderBXx** [comment]
Still missing this very useful feature :(

**Comment by rjcalifornia** [comment]
@filfreire Any update on this? Will we get the functionality back?

**Comment by tfiskgul** [comment]
Same issue here;

```
Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Linux x64 5.19.0-35-generic
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64
```

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"
```

**Comment by nstdspace** [comment]
This is a problem bugging me as well. 
I looked at it for a short time and can confirm that the commit `e38ece1ab7a45671778fef9326fe4c18c4554154` where the dropdown was completely refactored (re-)introduced
the problem. The value `requestActionsDropdown.current` in `sidebar-request-row.tsx` is always null. I am not a react expert and do not fully understand how the `DropdownHandle` refs are supposed to work, but maybe someone is able to dive deeper into this?

**Comment by VictorArsjad** [comment]
Hi @filfreire, do we have any updates on this issue?

**Comment by rjcalifornia** [comment]
> Hi @filfreire, do we have any updates on this issue?

It is over a month, and no response.

**Comment by quanljh** [comment]
I hope we can bring this feature back. :(
