### ISSUE TITLE
[Feature Request]: Remember selected tab

### ISSUE THREAD

**Issue by adius** [getinsomnia/insomnia#574]
I use insomnia like a bookmark system for REST endpoints. The endpoints use all the kinds fo ways to submit data (body, query, header, ...).

It would be cool if insomnia remembered the last selected tab (of body, auth, query, …) and displayed it when focusing the endpoint again. At the moment I always have to manually look for and switch to the tab where the data input happens.

**Comment by adius** [comment]
Or maybe there is something like a tab pinning feature, so that I can decide for every request if the tab should be pinned or not.

**Comment by gschier** [comment]
Do you think this is close enough to https://github.com/getinsomnia/insomnia/issues/406 to mark as a duplicate?

**Comment by adius** [comment]
Uhm yeah, I guess so. Should have searched for "pin", then I would have found it 🙈
