### ISSUE TITLE
Error Cloning Directory - No insomnia directory found in repository.

### ISSUE THREAD

**Issue by the-erwin** [getinsomnia/insomnia#5740]
Hi all,

Since a few weeks we're not able to GIT Clone an empty project anymore, we get the following error:
Error Cloning Directory - No insomnia directory found in repository.

We have on-premise gitlab and create a new project from a template in gitlab, which has no .insomnia directory.
Git Clone this project results in the error, according to documentation on e.g. https://docs.insomnia.rest/insomnia/git-sync
this should not happen, what expect to happen is: The remote repository must contain the root .insomnia directory, otherwise you will be prompted to create a new Design Document.

Same steps worked previously, but stopped since 2022.7.1 (Jan 9, 2023).

Now the only workaround I could manage was copying manually all the insomnia directories and files, change id's and names and then Git Clone, this is not the preferred way to work...

Thanks in advance,
All the best!

**Comment by filfreire** [comment]
@the-erwin I can also reproduce this this, seems it's a recent bug.

Example in 2022.7.0:
![Screenshot 2023-01-31 at 09 33 09](https://user-images.githubusercontent.com/11976836/215722590-fb025efa-3a38-47ee-802a-f923ed48b3d4.jpg)

Example in latest develop / beta build:
![Screenshot 2023-01-31 at 09 29 54](https://user-images.githubusercontent.com/11976836/215722612-d20083bb-1d09-4053-9a91-29f6fc54c3bd.jpg)

We'll update this issue once a fix is available

**Comment by VitorLostada** [comment]
with me too happen this same problem

**Comment by jeffersonjpr** [comment]
I had to copy the .insomnia folder from an older project for the clone to work.
