### ISSUE TITLE
[Feature Request] Address & protocol variables per-environment

### ISSUE THREAD

**Issue by wayneworkman** [getinsomnia/insomnia#575]
So at work, we bounce around from one test VM to another, running different tests and such. And we're all the time needing to change the address portion of all our calls - which is a major pain because I have like 25 calls in one environment saved.

I think it'd be helpful if I could set an address and protocol for an entire environment, and then all of my calls use those settings.

I'm not sure whats the best way to go about this, but I have some ideas:

http or https  (radio buttons)
Address  (text representing DNS Name or IP)

Then in the rest calls for the environment, you might could use variable names in the address section like:
`%protocol%://%address%/my-rest-route/blah`

Or perhaps just a checkbox for using the protocol and address for the environment like:

Use environment protocol & address (checkbox)
`my-rest-route/blah`  And insomnia would tack on the protocol and address and first forward slash.

Other ideas?

**Comment by gschier** [comment]
Hi @wayneworkman,

Are you using Insomnia's environment variables feature? This is what they're made for.

https://support.insomnia.rest/article/18-environment-variables

**Comment by wayneworkman** [comment]
@gschier I didn't know about that. Consider this issue closed - sorry for not researching first.

**Comment by gschier** [comment]
No worries 😊
