### ISSUE TITLE
Project Scroll

### ISSUE THREAD

**Issue by yanuaraditia** [getinsomnia/insomnia#5753]
### Expected Behavior

User can scroll through their request collection list

### Actual Behavior

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/39618526/216753166-dc158631-a615-49b3-a352-d876836bf733.png">

I can't scroll over my all request collections inside Insomnia project

### Reproduction Steps

1. Go Home
2. Personal Projects
3. Click on Some Project
4. Ensure you have more than 20 request collections and then you'll get scroll doesn't appear

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.5

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2 (a) Beta

### Installation method

insomnia.rest

**Comment by filfreire** [comment]
@yanuaraditia thanks for reporting this. This particular issue is fixed if you use the [latest beta release](https://github.com/Kong/insomnia/releases/tag/core%402023.1.0-beta.1)
