### ISSUE TITLE
Reading file in an environment variable does not translate into the query

### ISSUE THREAD

**Issue by Courvoisier13** [getinsomnia/insomnia#5754]
### Expected Behavior

Under windows:
I define an environment variable that points to a file:
```
{
   "file": "File"
}
```
I should be able to use `.file` in the query.

### Actual Behavior

The path fails. It's because the `\\` in the path, get removed when being sent as a string. So the file cannot be read and the `.file` is marked in red.

If I use a custom command in the environment variable definition and switch `\\` to `/` then `.file` works in the query

### Reproduction Steps

1.  define an environment variable that points to a file:
```
{
   "file": "File"
}
```
2. Try to use `.file` in a query
3. Go back to the environment variable, file on `File`, switch to **custom**, and change `\\` to `/`
4. The `.file` env variable can now be used

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2022.7.5
Build date: 1/19/2023
OS: Windows_NT x64 10.0.19045
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

### Insomnia Version

2022.7.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2 19045.2486

### Installation method

download from insomnia.rest

**Comment by palarnab** [comment]
I tried this and it works.. on windows

1. Click on the "File" item in environments
2. Change "Functions to perform" dropdown --> Change to "Custom"
![image](https://github.com/Kong/insomnia/assets/39365010/f6824547-9caf-4f88-bc49-a95287f16660)
4. From the next time it should work
