### ISSUE TITLE
Request sidebar: drag-and-drop feature is broken and very slow

### ISSUE THREAD

**Issue by robbycbennett** [getinsomnia/insomnia#5758]
### Expected Behavior

The request sidebar should be responsive, intuitive, and accessible.

### Actual Behavior

The request sidebar feels unusable. Here are some of the reasons that this is the case.
- The feedback line (shows where it will go when dropping) is delayed by at least 1000 ms. Then, the actual moving of the item takes another 3000 ms.
- If I drag element 2 to be in between 1 and 3, and I'm a little bit too low it should still go in. If element 2 is lower than the midpoint of element 1, and higher than the midpoint of element 3, then it should drop between them.
- Dropping a request onto a folder does not move it into the folder. Instead, it just opens the folder and drops the request outside of the folder. For some reason, I have to open the folder first, then carefully drag the request to the bottom of the folder with perfect precision.

In order to circumvent the drag and drop issue, the keyboard cannot be used.
- The keyboard shortcut actions are too limited. If I can do it with a mouse, I should be able to do it with the keyboard too ([related issue](https://github.com/Kong/insomnia/issues/3095).)
- The keyboard shortcuts I am able to set are complex. In Visual Studio Code, I can use a single keyboard letter to do actions like navigate, copy, paste, delete, open, etc. If I try to do this in Insomnia, then it messes up input elsewhere (environments).

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Download from insomnia.rest

**Comment by robbycbennett** [comment]
Here is a video comparing Postman to Insomnia.

https://user-images.githubusercontent.com/22121365/217148951-0bc013a2-b274-4562-9470-0661461c1dac.mp4

**Comment by Daghall** [comment]
I have a very similar problem on macOS Ventura 13.2 (22D49).

Moving items to folders won't work at all for a while, and then it starts working again.
The feedback seems to ignore folders. It just happens to work, on and off again.

**Comment by whyboris** [comment]
I'm on Mac, I created a folder, and I cannot drag my `POST` or `GET` requests into it 🤯 
It used to work 🤷‍♂️ but does not now -- `v2022.7.5` build date `1/19/2023` 😅

**Comment by maxcoe** [comment]
Also Mac user here and I wonder what happened in the last release. It was working well in earlier versions. I spend my time organising my requests in folders and subfolders, and the current behaviour is barely usable 😔

**Comment by SeijiSuenaga** [comment]
Just started using Insomnia on Windows. Drag-and-drop isn't slow for me, but these things seem broken:
- Dragging an item onto a folder puts it after the folder, not inside of it.
- When a folder is open, can't place an item after the folder. Have to close the folder first (or drag the item *onto* the folder due to the previous bullet point).
- Can't drag an item to the 1st position inside a folder. Have to drag to the 2nd position instead, then drag the 1st item down to 2nd position.

Version: Insomnia 2022.7.5
Build date: 1/19/2023
OS: Windows_NT x64 10.0.19045
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by eqj** [comment]
Same problems here; 

1. moving a request is suuuuuuper slow, it hangs for a second or two
2. once in a while after dragging + dropping, I end up with duplicate requests in both the old and new locations
3. ~dragging + dropping requests into folders or subfolders only works very rarely/sporadically~ see below edit, I figured out why it only works _sometimes_
4. the request settings dialogue move/copy doesn't include subfolders
5. you can only move a single request at a time; there doesn't seem to be a way to move several requests into a folder all at once

Version: Insomnia 2023.1.0
Build date: 2023-03-09
OS: Windows_NT x64 10.0.19045
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

EDIT: I have found a (bad) workaround; if you create two requests inside the folder/subfolder, you can now move requests after any entry (if the folder has zero or one requests in it, the dotted line below it presents the above bug where the request won't move into it; there has to be 2+), and then you can delete the junk requests once the folder is populated enough not to need them anymore X_X 

So it seems like folders that are either empty or only have one item in them don't present valid targets to move requests

**Comment by robbycbennett** [comment]
It's currently fast for me, but the UX is still counterintuitive as shown. The confusing behavior shown in my video is still present.

**Comment by akbortoli** [comment]
Same issue here

Version: Insomnia 2023.2.0
Build date: 4/26/2023
OS: Darwin arm64 21.6.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64
macOS (Apple M1 Pro): 12.6.3

**Comment by rbhosle** [comment]
Is there a fix yet for this issue. i.e. Drag and drop of requests into folders not working.


MacOS version details - 
MacOS Ventura 13.2.1

Insomnia version details - 
Version: Insomnia 2022.7.2
Build date: 1/12/2023
OS: Darwin arm64 22.3.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64

**Comment by taist24** [comment]
Same issue here

Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Darwin arm64 22.5.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64

**Comment by jackkav** [comment]
fixed in #6323
