### ISSUE TITLE
[Feature Request] History

### ISSUE THREAD

**Issue by emjburns** [getinsomnia/insomnia#576]
I'd like to be able to see my history (requests I've sent earlier). This is particularly helpful when developing queries that I don't want to save long term or iterating on a specific request. There's not a workflow that makes a ton of sense if you don't want to work on a saved query. Adding history would allow you to have this workflow without changing the structure of insomnia (to allow unsaved queries or something).

- Insomnia Version: 5.10.1 (5.10.1.1329)
- Operating System: macOS

**Comment by gschier** [comment]
This may not be exactly what you're looking for, but every request keeps its own response history. And, when you revert back, it will restore the request that was used to generate the selected response.

I'm also not quite sure I understand your use case. Can you give some more details on your desired workflow to help me understand?

<img width="599" alt="image" src="https://user-images.githubusercontent.com/587576/32520364-05642dec-c410-11e7-9e3c-f663a9f7f53d.png">

**Comment by emjburns** [comment]
Oh! Didn't realize that existed. Thank you for being so responsive! 

@robfletcher can you chime in here on what you're missing in the switch from Postman?

**Comment by gschier** [comment]
I'm going to close this issue for now, but feel free to comment or open another issue if you had something else in mind.

**Comment by batjko** [comment]
I also didn't see this feature. The little icon is easy to miss.

Also it's not obvious how to revert back to previous queries in that history view (clicking the row does nothing, instead I need to click next to it (where the pin icon is), which is not indicated in any way, as far as I can see.

**Comment by 6utt3rfly** [comment]
A global history would still be nice (similar to Postman) so that I can quickly see some of my most recent requests. Especially if I'm trying to switch environments and compare results between servers
