### ISSUE TITLE
Explore Subscriptions shown when premium features are hidden

### ISSUE THREAD

**Issue by nickserv** [getinsomnia/insomnia#5764]
### Expected Behavior

The panel at the bottom of the sidebar with the **Explore Subscriptions** link should disappear when premium features are hidden

### Actual Behavior

The link is still displayed despite leading to pricing for premium features

![Screenshot with **Explore Subscriptions** link panel circled](https://user-images.githubusercontent.com/927220/217719250-35ac6843-c0c7-42dc-856c-1c6b992e8b8b.jpg)

### Reproduction Steps

1. Open **Settings**
2. Open **General** tab
3. Scroll to **Notifications** section
4. Enable **Do not tell me about premium features**

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.1.0-beta.1

### What operating system are you using?

macOS

### Operating System Version

Darwin x64 21.6.0

### Installation method

GitHub (https://github.com/Kong/insomnia/releases/tag/core%402023.1.0-beta.1)

### Last Known Working Insomnia version

2022.7.5

**Comment by subnetmarco** [comment]
We removed this button.
