### ISSUE TITLE
[Bug] Graphql intellisense no longer works in latest version

### ISSUE THREAD

**Issue by ghiscoding** [getinsomnia/insomnia#577]
- Insomnia Version: v5.10.1
- Operating System: Windows 10

## Details

Installed latest Insomnia version and now the GraphQL intellisense no longer appears when I type (that was working with previous version). I also tried doing a "Ctrl+Space" but that didn't help. I verified that it works in `Graphiql` and it does, in `Insomnia` it also says that the "Schema was fetched x seconds ago", so I'm not sure what else to check. I attached print screen it that helps at all. If I type all the correct query, I do get correct response. 

No intellisense 
![insomnia_grapqhl](https://user-images.githubusercontent.com/643976/32524002-c82fee12-c3eb-11e7-812a-210a01cbdc0a.png)

Works in GraphiQL
![graphiql](https://user-images.githubusercontent.com/643976/32523982-b79f7c2a-c3eb-11e7-9ec4-28223f743745.png)

**Comment by danielrtanner** [comment]
+1 can confirm this issue to this. 
A few members of our team are experiencing this issue verbatim to the summary from @ghiscoding

**Comment by gschier** [comment]
Hmm, I will take a look at this. I think I updated the graphql package version so I'll just revert it if that was the problem.

**Comment by gschier** [comment]
So it _was_ a dependency problem. See this comment if you're curious: https://github.com/getinsomnia/insomnia/blob/76611dc50ae6e6bc510aff1c1eb8d153ebf2b6ad/app/__tests__/package.test.js#L15

**Comment by ghiscoding** [comment]
Thanks for looking into this. When should we expect a new version? :)

**Comment by gschier** [comment]
Deploying now. 😄

**Comment by gschier** [comment]
And it's live! Restart the app to trigger an auto-update or re-download it from the [downloads](https://insomnia.rest/download/) page.

**Comment by ghiscoding** [comment]
Thanks a lot, I already installed it and can confirm autocompletion is back and it is awesome. The fact that is also doesn't include the Query Variables anymore (when empty) is also what I was missing for my usage of GraphQL with .Net

Thanks a lot for the great support :)

**Comment by gschier** [comment]
Oh, that's great news @ghiscoding! I'm glad you're funding it useful! 😄
