### ISSUE TITLE
[BUG] JSON preview mode seems to mangle some spaces

### ISSUE THREAD

**Issue by gradha** [getinsomnia/insomnia#578]
- Insomnia Version: (5.11.0.1377)
- Operating System: OSX 10.12.6

## Details

Sometimes spaces embedded in JSON results seem to be removed from the preview. The following raw data:

    {u'result': {u'id_geopoke': 28, u'avatar_filename': u'Got empty space.jpg', u'id_user': 115, u'id_chat': None}}

Shows up like this in the visual preview or source code modes:

	{
		u'result': {
			u'id_geopoke': 28,
			u'avatar_filename': u'Gotemptyspace.jpg',
			u'id_user': 115,
			u'id_chat': None
		}
	}

In this example the spaces for `avatar_filename` are not visible.

**Comment by gschier** [comment]
Hi @gradha. I think that is because what you have posted is not valid JSON. It looks to me like its a stringified Python map instead. Valid JSON would look like this:

```json
{
	"result": {
		"id_geopoke": 28,
		"avatar_filename": "Got empty space.jpg",
		"id_user": 115,
		"id_chat": None
	}
}
```

**Comment by gradha** [comment]
Indeed, after looking at the backend side a conversion was missing. Thanks.

**Comment by gschier** [comment]
No problem!
