### ISSUE TITLE
Cant download Insomnia pass through website

### ISSUE THREAD

**Issue by Brucennnnn** [getinsomnia/insomnia#5790]
### Expected Behavior

Cant download Insomnia pass through website

### Actual Behavior

Cant download Insomnia pass through website

### Reproduction Steps

Cant download Insomnia pass through website

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Cant download Insomnia pass through website

### Insomnia Version

2021.5.0

### What operating system are you using?

macOS

### Operating System Version

mac m1

### Installation method

insomnia.rest

### Last Known Working Insomnia version

2021.4.0

**Comment by filfreire** [comment]
You can download latest version from here: https://insomnia.rest/download

Or from releases here on Github: https://github.com/Kong/insomnia/releases
