### ISSUE TITLE
url uncheck is http

### ISSUE THREAD

**Issue by night2049** [getinsomnia/insomnia#5792]
### Expected Behavior

response or url title tips: url is fail

### Actual Behavior

if url = http:/github.com
result = Error: Couldn't resolve host name

i think need tips: url is not http url

### Reproduction Steps

![image](https://user-images.githubusercontent.com/69810127/220512352-256bce79-277d-4d80-8287-41c18ce23373.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.5

### What operating system are you using?

Windows

### Operating System Version

windows11

### Installation method

windows install package

**Comment by filfreire** [comment]
you are missing a slash `/` character in `http://`

**Comment by night2049** [comment]
@filfreire hello，i now，but the tips is : could not resolve host name,i think change to url is fail
