### ISSUE TITLE
[Bug] OAuth2 fetch token fails in case of invalid SSL certificate

### ISSUE THREAD

**Issue by CosmicMac** [getinsomnia/insomnia#580]
- Insomnia Version: 5.11.0
- Operating System: Windows 7 Pro

## Details

Despite I unchecked _Validate SSL Certificates_, Insomnia fails to fetch OAuth2 token (`client_credentials` scheme) when _ACCESS TOKEN URL_ has an invalid SSL certificate.
No problem with plain HTTP without SSL.

````
grant-client-credentials.js:33 POST https://pp-nginx1/api/v1/token net::ERR_INSECURE_RESPONSE
module.exports.__webpack_exports__.a @ grant-client-credentials.js:33
_getOAuth2ClientCredentialsHeader @ get-token.js:56
````

**Comment by gschier** [comment]
Oh yes. The OAuth flow does not respect that setting. I'll try and get this fixed soon.

**Comment by CosmicMac** [comment]
Thanks Gregory.
I just discovered Insomnia today and I'm already a big fan. ;)
Keep up the good work!

**Comment by tourili** [comment]
Hi
I am having issue with OAuth 2. 
Now looks like only implicit grant type that is working but never with authorization code.  I used it before I upgrade and the Refresh token was always retrieved properly

I would like to post some tracing here but I can`t find a way to enable it !!

**Comment by gschier** [comment]
There are a few logs from OAuth posted in the console. You can find them in _View > Toggle DevTools > Console_.

If you could somehow provide me with some test credentials I'd be happy to take a look as well.

**Comment by gschier** [comment]
P.S. Can you please open a new issue for this? It's easier to keep track of it that way. Thanks!

**Comment by tourili** [comment]
@gschier  I did that here is the link https://github.com/getinsomnia/insomnia/issues/794
let me know if you still would like me to send you some test credentials I will manage for you on a test environment

Thanks a lot for your help and this nice tool
