### ISSUE TITLE
Git not working properly with new update

### ISSUE THREAD

**Issue by arafth** [getinsomnia/insomnia#5804]
### Expected Behavior

With the new update, git is too much troublesome. Very much slow. Freeze most of the time. Error-prone. And it is showing wrong information.
In a single word, the git feature is totally unusable.

### Actual Behavior

Faster response.
Does not freeze. 
Track changes properly.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version: 21H2 Build: 19044.2604

### Installation method

.exe

### Last Known Working Insomnia version

2022.6.0

**Comment by Basher7** [comment]
Facing the same issue in windows 11. Git syncing not working properly. 
Issues that I have facing:
1. Taking a long time to sync a new project. 
2. During new project syncing, sometimes It suddenly closed (This scenario is rare).
3. Taking a long time to view changes after click ```Commit```
4. Also, taking a long time to ```Pull``` & ```Push```. Sometimes need multiple clicks.

**Comment by lucaspereirasouzat** [comment]
I'm with the same problems, in changelog [changelog](https://insomnia.rest/changelog) will fix this but not date to release this new version

**Comment by filfreire** [comment]
@arafth @Basher7 @Warmachine13 do you still face git issues when using our [latest 2023.1.0-beta.4 build](https://github.com/Kong/insomnia/releases/tag/core%402023.1.0-beta.4)?

**Comment by arafth** [comment]
<img width="577" alt="insomnia_" src="https://user-images.githubusercontent.com/4764682/221553169-989099fa-13bb-4a8c-876b-16b80179972c.png">
It freezes in the Repository Setting section (waited for more than 10 minutes). 
On close manually seems the repository settings are completed. 
Though Gitlab has a main branch it doesn't push to the main but is pushed to the master (auto-created).

Seems like the issue exists with the latest 2023.1.0-beta.4 build too.

**Comment by subnetmarco** [comment]
We are working on this issue as we speak, to improve the Git performance in the application. These performance improvements will be ready this week. + @gatzjames for visibility.
