### ISSUE TITLE
[Question] Change in User Agent or request?

### ISSUE THREAD

**Issue by mmplisskin** [getinsomnia/insomnia#581]
- Insomnia Version: Version 5.11.0 (5.11.0.1377)
- Operating System: OSX 10.10.5 

## Details

Previously I could make requests to my backend with "Content-Type: application/json" and JSON would be returned... I.e. "{{ base_url  }}/api/users/49"   

Was there a change to user agent or the request in this version as now I must specify .json in order to avoid receiving 406 errors?

**Comment by gschier** [comment]
Yes, I think I know what it is. The last version removed the default `Accept` and `Accept-Encoding` headers that were being sent. It's strange that that would cause a problem. What language/webserver/framework is the API using?

For now, you can use this plugin to put the default header back: https://github.com/getinsomnia/insomnia-plugin-default-headers

I'll keep an eye on this one to see if it causes problems for anyone else.

**Comment by mmplisskin** [comment]
Thank you so much I was actually attempting to do this with environment variables this morning but it did not work, seems like this is a good plugin solution. The framework is rails 5.

**Comment by gschier** [comment]
Hmm, that's probably a good thing to support out of the box. Do you know if just the `Accept` header is required, or is `Accept-Encoding` also required?

**Comment by gschier** [comment]
FYI, the defaults before were `Accept: */*` and `Accept-Encoding: deflate, gzip`

**Comment by mmplisskin** [comment]
Just the Accept header is required.

**Comment by gschier** [comment]
Awesome, thanks for that info! Going to add the default `Accept` header back but not `Accept-Encoding`.
