### ISSUE TITLE
[Bug] Visual preview not displaying anything

### ISSUE THREAD

**Issue by retep007** [getinsomnia/insomnia#584]
- Insomnia Version: 5.10.1
- Operating System: OS X 10.13

## Details
For basic response with headers
```
Server: nginx/1.13.4
Date: Fri, 10 Nov 2017 09:41:32 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: Nette Framework
X-Frame-Options: SAMEORIGIN
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since,X-Api-Key
Access-Control-Allow-Methods: GET,OPTIONS,PUT,POST,DELETE
X-UA-Compatible: IE=Edge,chrome=1
```
and html in body visual preview is empty(completely white) even though when switched to source code I see the expected result

**Comment by gschier** [comment]
Can you open the console (View > Toggle DevTools > Console) and let me know if you see any errors?

**Comment by ubani** [comment]
As of today I am seeing the same issue. 
Previews on Source Code and Raw are working - though raw is a bit slow.
View > Toggle DevTools > Console doesn't throw any errors.

Insomnia Version 6.3.2 (6.3.2.2588)
Calling from macOS Mojave 10.14.2

```
Date: Wed, 02 Jan 2019 18:05:54 GMT
Server: Apache/2.4.33 (Ubuntu)
Cache-Control: no-cache, no-store, must-revalidate, max-age=0, proxy-revalidate, no-transform
Expires: Wed, 02 Jan 2019 18:05:54 GMT
Vary: Accept-Encoding
X-Frame-Options: sameorigin
Pragma: no-cache
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
```

**Comment by gschier** [comment]
If you could provide a public endpoint that reproduces this issue, that would help a lot!

**Comment by domainregistrar** [comment]
Also experiencing this behaviour with HTML preview. Extremely frustrating developing to realise the last few requests haven't actually been returning the same output.

Unfortunately no public endpoint as this is local code.

Insomnia 7.0.6 on MacOS.

Going to have to switch to another tool because this is just too painful for dev.

**Comment by jvahldick** [comment]
Hey guys. I am facing the same issue here.
I tried with some public endpoints.

![Image 1](https://raw.githubusercontent.com/jvahldick/public-files/main/file-1.png)
![Image 2](https://raw.githubusercontent.com/jvahldick/public-files/main/file-2.png)

**Comment by dimitropoulos** [comment]
I was unable to reproduce this.. hmm.  Any ideas on how I could reproduce this?


https://www.irishtimes.com

![Screenshot_20210405_114157](https://user-images.githubusercontent.com/15232461/113593037-eec6b400-9603-11eb-87c5-c6271816c0d1.png)


https://www.symfony.com

![Screenshot_20210405_114110](https://user-images.githubusercontent.com/15232461/113592959-d2c31280-9603-11eb-925f-6c967fdf23c7.png)

**Comment by jvahldick** [comment]
Hey @dimitropoulos 

I am trying to figure it out. I asked some other guys to try it too and they couldn't reproduce it as well.

It's a fresh new installation, so I am not sure what can be wrong. I tried to disable all browser's extensions just to be sure (as I don't know if they have some relation with the embedded browser), but still without the preview.

**Comment by jvahldick** [comment]
@dimitropoulos 

I managed to make it work. I followed some old and not understandable instructions (resetting the internet, restart the laptop and reinstalled Insomnia), and it magically worked.

**Comment by dimitropoulos** [comment]
glad you got it working!  if you are able to reproduce it in the future don't hesitate to reach out :)

**Comment by apit** [comment]
i have no luck with SPA app, eg. this [app](https://github.com/kubernetes-up-and-running/kuard)
