### ISSUE TITLE
Application crashes with 401 everytime I access git

### ISSUE THREAD

**Issue by shisshruti** [getinsomnia/insomnia#5860]
### Expected Behavior

I have synced my insomnia project to gitlab. This was working perfectly until a couple days ago. I could switch branches and push/ pull code from the git icon in the top navbar.

### Actual Behavior

For the last couple days, the application crashes as soon as a click on the git icon in the navbar (even before I try to perform an actual git interaction). I tried creating a new insomnia project and connected it to a different git repository, but I got the same result. Everything else works just fine, but it crashes as soon as I hit the git icon.
![image](https://user-images.githubusercontent.com/65809866/227029121-4531a7d6-f510-472c-8c6f-78c063a58fb8.png)

### Reproduction Steps

1. Go to a document and sync it with gitlab
2. Click on the git icon on the top navigation bar
3. 3. the app crashes

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2

### Installation method

insomnia exe

**Comment by mos379** [comment]
same here but I'm using a git repo hosted on azure...

**Comment by enricojonas** [comment]
Same for me. In my case I updated the token, now I cannot access git anymore... Any way to update the token manually?!

**Comment by mos379** [comment]
latest beta is working better, but still having issues

**Comment by AndyBrownlie** [comment]
same here on Windows 10 and using Gitlab :-(

**Comment by subnetmarco** [comment]
Fixed in beta and available in the next release.
