### ISSUE TITLE
WebSocket Binary Message display as `[object Object]`

### ISSUE THREAD

**Issue by hax0r31337** [getinsomnia/insomnia#5864]
### Expected Behavior

Whatever Base64 or Hex

### Actual Behavior

![image](https://user-images.githubusercontent.com/65506006/227778414-90011561-3e81-49e8-9ea5-5bc41d1736b5.png)

### Reproduction Steps

1. create a websocket server which sends binary messages
2. bug reproduced

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.1.0

### What operating system are you using?

Other Linux

### Operating System Version

6.2.8-arch1-1

### Installation method

AUR package `insomnia-bin`

**Comment by subnetmarco** [comment]
We could show a textual representation of the binary information, that will have to be truncated if too long. We could also show a "Download" button to download the un-truncated data. 

If we know that the data is binary, we could even avoid showing the truncated preview. We should instead directly show "You have received binary data, download it".
