### ISSUE TITLE
[Feature] Autocomplete support for variables field when crafting GraphQL queries

### ISSUE THREAD

**Issue by mandx** [getinsomnia/insomnia#587]
GraphiQL already supports this, but having it inside Insomnia would be awesome.

How this works is, for example:
```graphql
mutation NewEntityMutation($input: NewEntityInput!) {
	newEntity(input: $input) {
		entity { id name created updated description type }
	}
}
```
Where `NewEntityInput` is:
```graphql
type NewEntityInput {
    id ID
    name String!
    description String
    type SomeTypeEnum!
}
```

When opening quotes in the variables bottom field, show a list to autocomplete the `input` variable itself, and inside, autocomplete to each of it's fields. It could even expand all the required fields at once (in this example, would insert the `name` and `type` keys). Since GraphQL is strongly typed, I guess autocompletion (to some extent) can be implemented for values as well.

- Insomnia Version: 5.11.5
- Operating System: Ubuntu 17.10

**Comment by EItanya** [comment]
I completely agree with this, it would being incredibly helpful for expediting graphql calls. The other feature that I would love to see is an auto-fill feature for queries and mutations which would automatically enter all of the possible fields.
An example could be as follows:
`mutation NewEntityMutation($input: NewEntityInput!) {
	newEntity(input: $input) {
		entity { ... }
	}
}`
If you enter '...' into then an auto-fill complete feature would pop up and you could automatically populate all of the fields.
I would be willing to try and take these on if they do not exist, or are not top priority.

**Comment by gschier** [comment]
@emil-nasso I was actually working on this this week. Already have a PR up!
