### ISSUE TITLE
Change Method keyboard shortcut not working on mac

### ISSUE THREAD

**Issue by neeraj-ec** [getinsomnia/insomnia#5879]
### Expected Behavior

- Pressing `shift+command+L` should open the HTTP Method dropdown list to choose from.
- Pressing `command+L` should move cursor to url bar.

### Actual Behavior

- Pressing `shift+command+L` does nothing.
- Pressing `command+L` show focus on url bar but cursor still remains on body editor.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

No keybinding overridden. No plugins installed.

### Insomnia Version

v2023.1.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.4 Beta (22F5027f)

### Installation method

download from insomnia.rest

**Comment by neeraj-ec** [comment]
👀 Anyone listening? It kills the productivity. Every time i need to make a change in query param or url, I need to reach out to mouse because Keyboard shortcut (cmd+L) only highlight the address bar, does not move cursor there. In earlier versions it used to work fine.

**Comment by subnetmarco** [comment]
This should have been fixed in Insomnia 9.0, for which a beta is available now.

**Comment by subnetmarco** [comment]
Except the command+L focus problem, let's see if we can get this fixed too.
