### ISSUE TITLE
[Bug] Handle multiple response headers with same name

### ISSUE THREAD

**Issue by cskr** [getinsomnia/insomnia#588]
- Insomnia Version: 5.11.5
- Operating System: Ubuntu 17.04

## Details

When a HTTP response contains more than one header with the same name, insomnia displays only one of the values. For example, response header from `curl` CLI:

```
HTTP/1.1 401 Unauthorized
Server: nginx
Date: Sat, 11 Nov 2017 02:29:03 GMT
Content-Type: application/json
Content-Length: 37
Connection: keep-alive
WWW-Authenticate: api-key
WWW-Authenticate: Basic
```
Headers in insomnia:

![insomnia_headers](https://user-images.githubusercontent.com/173476/32685412-b78ba20e-c6b6-11e7-879f-fb888de76f39.png)

**Comment by gschier** [comment]
Looks like this is an issue in `node-libcurl`. Going to link the issue I submitted here for reference: https://github.com/JCMais/node-libcurl/issues/108
