### ISSUE TITLE
"Application Error" in Project when the current branch no longer exists in Github

### ISSUE THREAD

**Issue by nstuart-at-salesforce** [getinsomnia/insomnia#5885]
### Expected Behavior

Workspace should load, either removing to now-dead remote branch locally or by switching to the `main` branch

### Actual Behavior

Clicking into my Project, after ~5 seconds, the app crashes and needs to reload. 

<img width="628" alt="Screenshot 2023-04-11 at 12 56 10 PM" src="https://user-images.githubusercontent.com/54150165/231275579-6e52c86f-c1a1-4102-a619-2a6d6d20c1b3.png">

### Reproduction Steps

1. Import a project from `Git Clone`
2. In that project, create a new branch
3. Modify/add a file, commit, and push to github
4. Close Insomnia
5. Go to github and delete the new branch from step 2
6. Open Insomnia, navigate to the Project

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.1.0

### What operating system are you using?

macOS

### Operating System Version

13.2.1 (22D68)

### Installation method

Download from Insomnia

**Comment by subnetmarco** [comment]
This will be fixed in the new release (currently the fix is available in the beta release).
