### ISSUE TITLE
Insomnia shows duplicated options in gRPC method dropdown menu

### ISSUE THREAD

**Issue by Tomasito665** [getinsomnia/insomnia#5891]
### Expected Behavior

- The gRPC method dropdown menu shows one option per method.

### Actual Behavior

- The gRPC method dropdown menu shows duplicated options.

**Gif animation**
![InsomniaDuplicatedGrpcMethods](https://user-images.githubusercontent.com/12563382/231725974-27127a9f-b2bb-4ba5-a284-cf8e120af47d.gif)

**Screenshot**
<img width="865" alt="image" src="https://user-images.githubusercontent.com/12563382/231726643-ca5de236-6151-46e4-900f-734d74086cb5.png">

### Reproduction Steps

1. Run `docker pull tkpd/gripmock:v1.11-beta` to pull gRPC mock server docker image.
2. Create a `service.proto` file with the following contents.

```proto
syntax = "proto3";

message FooRequest {
    string foo = 1;
}

message FooResponse {
    string foo = 1;
}

message BarRequest {
    string bar = 1;
}

message BarResponse {
    string bar = 1;
}

service FooService {
    rpc Foo (FooRequest) returns (FooResponse);
}

service BarService {
    rpc Bar (BarRequest) returns (BarResponse);
}
```

4. Go to the directory where the `service.proto` file is located and run the following command to spin up the gRPC server. 

```bash
docker run --rm -p 4770:4770 \
    -v ${PWD}/service.proto:/proto/service.proto \
    tkpd/gripmock:v1.11-beta /proto/service.proto
```

5. Open Insomnia and create a new gRPC request with the host set to `localhost:4770`.
6. Click on the refresh button to use server reflection.
7. Click on "Select Method" to open the dropdown menu.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

It appears as if Insomnia duplicates all methods for every gRPC service after the first one. That is:

- proto file with one service declaration: everything ok
- proto file with two service declarations: gRPC methods duplicated once
- proto file with three service declarations: gRPC methods duplicated twice

### Insomnia Version

2023.1.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.2.1

### Installation method

insomnia.rest

**Comment by nbgraham** [comment]
I am also seeing this issue.

I wanted to look into it more, but I couldn't get the dependencies installed to run locally. 

My initial reaction is that it's something off during the React set state:
https://github.com/Kong/insomnia/blob/bb638b5e945f6360ce4dd4b4e3604fdb7a48eacd/packages/insomnia/src/ui/components/panes/grpc-request-pane.tsx#L189-L190
https://github.com/Kong/insomnia/blob/bb638b5e945f6360ce4dd4b4e3604fdb7a48eacd/packages/insomnia/src/ui/components/panes/grpc-request-pane.tsx#L89-L90
