### ISSUE TITLE
Logo is large in dock on macOS

### ISSUE THREAD

**Issue by mbaumbach** [getinsomnia/insomnia#5922]
### Expected Behavior

The logo width and height should be approximately the same size as the standard apps on the macOS dock.

### Actual Behavior

The new logo on macOS is quite large in comparison to other standard logos on the dock. See screenshot.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/48250/234727288-40fbc588-1ca5-4be5-9d9c-ecb825cf36e8.png">

### Reproduction Steps

1. Open Insomnia on a mac.
2. Compare the logo size to other app icons

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.3.1

### Installation method

download from insomnia.rest

**Comment by rosedalerk** [comment]
Same problem for me. This time I used the auto-download from within the client.

**Comment by filfreire** [comment]
@mbaumbach @rosedalerk we've found the issue, a fix pull-request is up for it and will go out in a future patch / beta release. Thank you for reporting this!

**Comment by filfreire** [comment]
Hi folks, this is now fixed in patch [2023.2.1](https://github.com/Kong/insomnia/releases/tag/core%402023.2.1)
