### ISSUE TITLE
Keyboard shortcut for "Switch Environment" no longer working

### ISSUE THREAD

**Issue by briancsinger** [getinsomnia/insomnia#5923]
### Expected Behavior

Press keyboard shortcut assigned to "Switch Environments" (ex cmd+shift+E) and environment switcher UI appears

### Actual Behavior

When the keyboard shortcut for "Switch Environments" is pressed, nothing happens. I've tried updating the keyboard shortcut keys mutliple times to multiple different, unique/unused key combinations and it still doesn't work.

### Reproduction Steps

1. Press keyboard shortcut assigned to "Switch Environments" (ex cmd+shift+E)
2. See that nothing happens

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I also tried uninstalling and reinstalling but still had the same issue

### Insomnia Version

2023.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.4

### Installation method

downloaded from website 

### Last Known Working Insomnia version

not sure..

**Comment by guyzmo** [comment]
I'm having a similar bug using 2022.7.5: when I'm pressing the `cmd`-`e` shortcut I got the duplicate modal opening up.

My guess is that shortcuts are ignoring the configured layout of the keyboard, so I'm getting qwerty keys instead of my own keyboard, and I'm using a dvorak layout.

Trying with `cmd`-`.` (which maps to qwerty's `cmd`-`e`) made the modal open again.

I'm updating insomnia to latest to see if the bug still stays. And I'd be happy to make a separate bug report if need be.

**Comment by frhgm** [comment]
Hello everyone,
I do not know if it's related, but I can confirm the same behaviour in Windows 10 and 11, even if I change the mapping to another shortcut.

Thanks!

**Comment by filfreire** [comment]
Hi folks, I can also reproduce this. We'll update here once the fix is ready.

**Comment by sebastianjonasson** [comment]
@filfreire  - I made a patch for this https://github.com/Kong/insomnia/pull/5998

**Comment by filfreire** [comment]
Thanks for the contribution @sebastianjonasson, closing this one. From [2023.5.0-beta.3](https://github.com/Kong/insomnia/releases) onwards should be fixed. That beta should go out today.

**Comment by sebastianjonasson** [comment]
> Thanks for the contribution @sebastianjonasson, closing this one. From [2023.5.0-beta.3](https://github.com/Kong/insomnia/releases) onwards should be fixed. That beta should go out today.

Great, thanks!

**Comment by mpasang** [comment]
Hi, I encountered the same problem. I'm using Ubuntu 20.04.06 and here's my installation info:

- Version: Insomnia 2023.5.8
- Build date: 9/7/2023
- OS: Linux x64 5.15.0-83-generic
- Electron: 25.2.0
- Node: 18.15.0
- Node ABI: 116
- V8: 11.4.183.23-electron.0
- Architecture: x64
CTRL+P is not working to switch requests, I tried to reset the settings but nothing happened. Can kindly check? TYIA!

**Comment by sebastianjonasson** [comment]
@mpasang - Different issue: view https://github.com/Kong/insomnia/issues/6301

**Comment by ChesterTheCheese** [comment]
Same problem exists with Insomnia 2023.5.8 9/7/2023 on Mac OS Darwin arm64.

**Comment by mpasang** [comment]
I tried upgrading to the latest version and I still can't switch calls using the keyboard shortcut:

- Version: Insomnia 8.3.0
- Build date: 10/13/2023
- OS: Linux x64 5.15.0-87-generic
- Electron: 25.8.1
- Node: 18.15.0
- Node ABI: 116
- V8: 11.4.183.29-electron.0
- Architecture: x64

Do you have an idea of when this will be resolved? or any workaround?
Thanks in advance!
