### ISSUE TITLE
[Feature request] Allow specifying request payload's charset

### ISSUE THREAD

**Issue by ehmicky** [getinsomnia/insomnia#593]
- Insomnia Version: 5.11.5-1415
- Operating System: Ubuntu 17.10

## Details

Is there a way to specify the request payload's charset?

For example, I want to send some JSON as UTF-16.

The only ways to do this at the moment that I can potentially see are:
  - using "binary file", then changing the `Content-Type` header to `application/json; charset=utf-16`
  - using base64 decoding

**Comment by gschier** [comment]
Hey @ehmicky. To be honest, I don't really know anything about charsets other than the fact that they exist. Your first method seems like the best bet. I'm not sure if the second one would work because it might get read as utf8 at some point before being sent with the request.

Can you elaborate on what you're looking for specifically?

**Comment by ehmicky** [comment]
Yes I confirm the second one does not work. The request that is sent is corrupted, i.e. only the first few bytes get sent. I was going to submit a separate bug issue for this, but wanted to discuss this first.

The first option works, but is not optimal from a UX point of view. E.g. when using local files, they do not get synced across devices.

My use case is that I am developing a web server where the clients might send UTF-8 or UTF-16. I am using Insomnia as a debugging tool. I set up a UTF-16 request to test whether my server handles it properly.

Although the web is overwhelmingly UTF-8, handling at least UTF-16 seems like reasonable. For example, the JSON spec specifies UTF-16 as a possible encoding besides UTF-8, so any JSON implementation should theoretically handle both. 

Also, some file uploads on some website might use other charsets.

It is relatively easy to either encode/decode from/to UTF-8 from/to most charsets using libraries like [iconv-lite](https://github.com/ashtuchkin/iconv-lite). It is as simple as `const string = iconv.encode(buffer, encoding)`.

Where to put this option in UI might be trickier. E.g. since the HTTP header `Content-Type` is the way to specify the payload charset, e.g. `Content-Type: text/plain; charset=ascii`, it could be used. Maybe a different dropdown could be available for people who are not aware of that.

**Comment by ehmicky** [comment]
I am not sure this should be closed, as it's been reported by someone else at #615
