### ISSUE TITLE
Unable to import collection, Insomnia tries to load a Design Document instead

### ISSUE THREAD

**Issue by juanjoms** [getinsomnia/insomnia#5930]
### Expected Behavior

Should import request collection correctly.

### Actual Behavior

Not importing collection, instead, there is a blank Design Document created.

### Reproduction Steps

1. Create a simple Request Collection
2. Add a simple HTTP request
![image](https://user-images.githubusercontent.com/6306888/235336549-5877cbcf-6d33-491e-ba01-d0a915e5b250.png)
3. Click the collection name, then Import/Export
4. In the "Export Data" dropdown select Export the collection
![image](https://user-images.githubusercontent.com/6306888/235336627-971ef868-c236-467f-90f3-a2b3b7aa0efe.png)
5. In the next step click "Export" and select "Insomnia v4(JSON)" or "Insomnia v4(YAML)"
6. Finish exporting the collection by saving the file
7. Go to Dashboard by clicking "Insomnia", then in the saved collection click 3 dots(...) and click "delete"
8.  At the top right dropdown click on "+Create" and then click  "Import"
![image](https://user-images.githubusercontent.com/6306888/235336754-67843a1d-5399-470e-8194-c288940eb9b3.png)
9. Drag and drop the file created at step 6, then click on "Scan"
![image](https://user-images.githubusercontent.com/6306888/235336790-427e2dcb-2461-4b41-a5c7-bca0dc29af7b.png)
10. Insomnia asks to name a new file (Seems to be wrong behavior as it should retrieve the name of the saved collection)
![image](https://user-images.githubusercontent.com/6306888/235336829-78656e4c-40dd-4e09-8ea6-17cbf8b69011.png)
11. Click "Import"
12. No collection is imported, instead, there is just a blank Design Document:
![image](https://user-images.githubusercontent.com/6306888/235336889-f7cf6283-5b55-440d-a504-8a3ae7ae8ec3.png)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I also tried uninstalling and downloading/installing Insonminia, but the bug persists.
Normal drag and drop (without explicitly clicking Import) does nothing, in the previous version I was able to just drag and drop a file and they were imported correctly.

### Insomnia Version

2023.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6.5

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

2023.1.0

**Comment by filfreire** [comment]
@juanjoms if you go to the `Debug` tab on the new workspace that is created after you import, you will find your environment and requests from the imported file.

**Comment by juanjoms** [comment]
Hi @filfreire, yes I can see the environments/requests in the Debug tab. 

Is it possible to import the file directly as a request collection?
and also the drag and drop of a saved collection (without explicitly clicking Import)  will be fixed?
both items were working in v2023.1.0

**Comment by jesseclm** [comment]
This is a PIA. I have to go into the working db to change the classification from `design` to `collection`
