### ISSUE TITLE
[Bug] Accept Header not working anymore

### ISSUE THREAD

**Issue by lukaszgoworko** [getinsomnia/insomnia#595]
[Bug]
- Insomnia Version: Version 5.11.5 (5.11.5.1415)
- Operating System: mac High Sierra 10.13.1 (17B48)

## Details
- We are developing an API where you can choose the format of your response ( Accept Header )
- Formats are
  - application/json
  - text/html
  - application/xml
- I Updated to High Sierra and updated Insomia, so I can't determine witch causes the problem, but the Accept header not working anymore.
  - (Other Rest Clients are working)
- Tested with
  - https://pub.sandbox.orcid.org/v1.2/0000-0002-2389-8429/orcid-bio/
    - ❌ application/json
    - ✅ application/xml (only because its default)

**Comment by gschier** [comment]
Sorry about that. I actually fixed this already a couple days ago but haven't deployed a new release yet: https://github.com/getinsomnia/insomnia/commit/41e903714bc295b8db5bb53284ba58e6bfc4c6af

**Comment by gschier** [comment]
You can actually install this beta release to get the fix early. https://github.com/getinsomnia/insomnia/releases/tag/beta-multipart-response

**Comment by lukaszgoworko** [comment]
really fast response: thanks for that 👍 => working on beta

**Comment by gschier** [comment]
Boom! Dynamite 😄
