### ISSUE TITLE
I can't signup for Insomnia

### ISSUE THREAD

**Issue by 16adixon** [getinsomnia/insomnia#5950]
When I try to signup it says '** There was an unexpected internal server error'. I’ve tried clearing my cache, using different browsers, and making sure I didn’t use any autofill. I've also tried using an entirely different computer all with no luck.

**Comment by filfreire** [comment]
@16adixon have you tried to signup with a different email?

**Comment by 16adixon** [comment]
Yes I ended up doing that and that worked no problem. Any idea why this would be? Also, is there a standard for updating my post and stating it is resolved?

**Comment by filfreire** [comment]
@16adixon it might have been that:

a) the email had already been used for an account
b) the email server could not reach your email to activate the account
c) something else?

Glad you got it solved in the end. Closing this issue now.
