### ISSUE TITLE
dock icon oversized 

### ISSUE THREAD

**Issue by jirizavadil** [getinsomnia/insomnia#5965]
### Expected Behavior

same size as other icons :)

### Actual Behavior

<img width="138" alt="Screenshot 2023-05-16 at 11 22 18 AM" src="https://github.com/Kong/insomnia/assets/1691976/c18f58d9-90c9-4960-9cd0-639ba38a1b2c">

### Reproduction Steps

1. run macOS 13.3.1 (a) (22E772610a)
2. launch latest Insomnia (since icon update version)
3. suffer

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 2023.2.0
Build date: 4/26/2023
OS: Darwin arm64 22.4.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64

### Insomnia Version

2023.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS 13.3.1 (a) (22E772610a)

### Installation method

original download from insomnia.rest, recent via updates

### Last Known Working Insomnia version

last version before icon update

**Comment by filfreire** [comment]
@jirizavadil this is fixed in patch [2023.2.1](https://github.com/Kong/insomnia/releases/tag/core%402023.2.1)
