### ISSUE TITLE
Cannot open Base Environment

### ISSUE THREAD

**Issue by Crisfole** [getinsomnia/insomnia#5969]
### Expected Behavior

When I open my environments to modify them ("Manage Environments" from dropdown that opens when you click the down arrow next to the currently active environment name in the top left of the UI) I am shown the currently active environment. I should be able to click the "Base Environment" to modify shared variables.

### Actual Behavior

I can no longer open the base Environment. When I click it:

<img width="259" alt="image" src="https://github.com/Kong/insomnia/assets/413237/81b8116d-8eef-406b-a389-e61a08d8342c">

Nothing happens. The cursor _does_ change to indicate clickability. The actual click does nothing.

### Reproduction Steps

1. Open a collection containing a base environment and sub environments, with the sub environment active.
2. Click the down arrow next to the active environment name.
3. Select "Manage Environments"
4. Click "Base Environment"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The workaround for this that I just discovered is selecting 'No Environment' then opening the environment management. This works until you click a sub-environment (which works). After which you're back in the same buggy state.

This is the output of the About window:

[Window Title]
Insomnia

[Main Instruction]
Insomnia

[Content]
Version: Insomnia 2023.2.1
Build date: 5/15/2023
OS: Windows_NT x64 10.0.22621
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

[OK] [Copy]

### Insomnia Version

2023.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.22621

### Installation method

Download from Insomnia rest

### Last Known Working Insomnia version

Whatever version this was last night before it auto-updated without asking.

**Comment by filfreire** [comment]
@Crisfole I can reproduce as well, thanks for reporting. Fix for this will come out soon!

**Comment by Crisfole** [comment]
@filfreire no dev tool errors I can see. Outstanding Github Issue experience, by the way. The reporting was easy, well guided, and I love the response too! Let me know when you want me to pull and test.

**Comment by filfreire** [comment]
@Crisfole issue should be fixed on latest patch release https://github.com/Kong/insomnia/releases/tag/core%402023.2.2

**Comment by Crisfole** [comment]
Works for me! Thanks so much!
