### ISSUE TITLE
[Feature Request] Global Headers

### ISSUE THREAD

**Issue by fjwillemsen** [getinsomnia/insomnia#597]
Feature Request: Global Headers

As we have recently switched to Insomnia as our go-to REST client tool (especially for GraphQL) in our Dev environment, we’ve seen a lot of great features in the app. This near-perfection of the tool has also outlined a feature that is, in our opinion, missing: Global Headers. If users can set the headers the way variables can be set, the app will be more dynamic. We have a couple dozen queries we test, and need to apply some header-tokens to all of them to make sure they pass verification. In the current situation, our queries have headers with variable values, with the values entered on sub-domain level. However, if for example headers are changed or added in the future, we’d have to make the same change to every query.
Another example; when a user is logged in, all the following calls will need an Authorization header consisting of a JWT token. With which the back-end determines if and what user is logged in. Without global headers, we need to update our headers in every query we test with the freshly created JWT token. If we could add this as a Global Header, calls would work immediately with the correct headers set globally.
We believe these examples highlight several use cases that would significantly benefit from the addition of the requested feature.

**Comment by gschier** [comment]
Thanks for the request @fjwillemsen!

This has been discussed a lot in the past and is currently planned to be solved [Parent Requests](https://github.com/getinsomnia/insomnia/issues/447)

However, if you can't wait, there is also a plugin that allows you to set default headers using an environment variable: https://www.npmjs.com/package/insomna-plugin-default-headers

Going to close this issue for now in favor of the things mentioned.

**Comment by m3c-ode** [comment]
I've tried installing the plug-in but nothing changed. how can it be used?

**Comment by seniorit** [comment]
La respuesta llega un poco tarde, pero espero que sea de ayuda para otras parsonas. Debe agregarse en el ambiente base lo siguiente:
```json
        {
          "DEFAULT_HEADERS": {
            "Content-Type": "application/json",
            "Authorization": "Bearer {{token}}"
          }
        }
```
Debe respetarse el valor DEFAULT_HEADERS porque al parecer se interpreta como una variable de entorno global por Insomnia
