### ISSUE TITLE
Error pushing Repository

### ISSUE THREAD

**Issue by gioacchino-mauro** [getinsomnia/insomnia#5971]
### Expected Behavior

I can commit changes on my GitHub repository but I should also be able to push

### Actual Behavior

I receive error "Push Failed" as the image belowe
![insomnia_ERROR](https://github.com/Kong/insomnia/assets/81425201/9c572c6d-3d26-4607-b0a0-04b1cd87f20f)

LOG stops on 
`[info]  [git-event] Using OAuth2 credentials`

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I read the code and I believe there is an error in credential retrieval.

![insomnia_BUG](https://github.com/Kong/insomnia/assets/81425201/450726bf-2f15-48e5-8f31-2f2079272226)

is it normal that for the  github section the parameter 'username' is set while for gitlab it's saved to 'password'?

### Insomnia Version

2023.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

download from Insomnia

### Last Known Working Insomnia version

none that I'm aware of

**Comment by filfreire** [comment]
@gioacchino-mauro when you first cloned the repository in Insomnia, did you use the Github tab or the regular Git Sync tab where you need to provide a [personal access token](https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) ?

**Comment by gioacchino-mauro** [comment]
> @gioacchino-mauro when you first cloned the repository in Insomnia, did you use the Github tab or the regular Git Sync tab where you need to provide a [personal access token](https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) ?

Github tab

**Comment by tuyen-at-work** [comment]
Same for me

**Comment by pincelkey** [comment]
I'm facing the same problem :/

**Comment by gioacchino-mauro** [comment]
any news?

**Comment by gioacchino-mauro** [comment]
![image](https://github.com/Kong/insomnia/assets/81425201/c0c5f203-0761-46bd-a218-182bbeb94a77)
with [Insomnia 2023.5.0-beta.6](https://github.com/Kong/insomnia/releases/tag/core%402023.5.0-beta.6)

**Comment by gioacchino-mauro** [comment]
same with [Insomnia 2023.5.0-beta.8](https://github.com/Kong/insomnia/releases/tag/core%402023.5.0-beta.8)

**Comment by gioacchino-mauro** [comment]
same with [Insomnia 2023.5.0-beta.10](https://github.com/Kong/insomnia/releases/tag/core%402023.5.0-beta.10) ...

**Comment by gioacchino-mauro** [comment]
![403](https://github.com/Kong/insomnia/assets/81425201/9092afc8-3f5e-45b2-acae-0bfc6563711e)
now i have this error, Insomnia 2023.5.8

I guess the problem is with business account, I don't have problem with my private repo. Is there some permission I have to enable?

**Comment by gioacchino-mauro** [comment]
solved by giving the grant to the application, in the organization settings
