### ISSUE TITLE
Importing an OpenAPI v3 spec does not set Content-Type for json requests

### ISSUE THREAD

**Issue by cogniveon** [getinsomnia/insomnia#5976]
### Expected Behavior

It should automatically detect content-type from the request media type when importing from an OpenAPI v3 spec.

### Actual Behavior

`Content-Type: application/json` header is not being added for json requests in an OpenAPI v3 spec.

Need to manually switch it to another media type and switch it back to json for the header to be applied.

### Reproduction Steps

1. Import an openapi v3 spec with a json request
2. Make a request (no `Content-Type: application/json` header)
3. Switch to some other content type and switch back to json
4. Make a request (`Content-Type: application/json` header is added now)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.2

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.5 LTS

### Installation method

insomnia.rest

**Comment by filfreire** [comment]
@AlQa-hOlic thanks for reporting this. We have a fix ready on #5982 and it will hopefully go out in one of our upcoming patch or beta releases 👍
