### ISSUE TITLE
Free account password recovery

### ISSUE THREAD

**Issue by MMirabito** [getinsomnia/insomnia#5978]
I  have *free account* on insomnia and I forgot my password. I sent an email to *support@insomnia.rest* and the auto reply responded with the following:

• *For account and password recovery, please note that if you don't remember your old password, a password reset or account deletion is not possible at the moment, due to how account encryption works, as documented on <https://docs.insomnia.rest/insomnia/security-features>. Please keep your password safe.*

What do I do now? I do not mind losing whatever was encrypted if any - it says that "you cannot reset it, delete the account etc."  

I cannot recall where I placed a copy of the password it was over a year ago. 

Do you have a "nuclear option" on your side to simply purge my account so I can start again?

Thanks,
max

Posted message to slack but no luck

[Slack Message](https://getinsomnia.slack.com/archives/C3BBF236C/p1683883678205329?thread_ts=1683883678.205329&cid=C3BBF236C)

**Comment by filfreire** [comment]
Hi @MMirabito we are implementing at the moment some options where you will be able to unblock by yourself (e.g. still login with an email sent code and then delete/recreate your account) but it's still in private alpha. It will be released alongside a complete website revamp.

We'll update you here as soon as it's out.

In the meantime, if you need, you can create another account with the same email, just adding a `+<something>` at the end, eg. `your.email+123@emailprovider.com`

**Comment by MMirabito** [comment]
Hi @filfreire thanks for the update really appreciate  you all working on an option.

max

**Comment by vmrocha** [comment]
Is there a way to request to delete the account so we can create a new one?

**Comment by MMirabito** [comment]
Hi @filfreire has the reset password feature been enabled/fixed? I am not able to rest the password.

Thanks,
max

**Comment by alfangr** [comment]
> Is there a way to request to delete the account so we can create a new one?

You can delete your old account and recreate it with the email you previously deleted (but all data will deleted).

**Comment by filfreire** [comment]
@MMirabito you should now be able to login using email code and delete your account and recreate a new one. All data will be deleted, but if you were a member of other teams/organizations, anyone with Admin permissions can reinvite your account back.

**Comment by MMirabito** [comment]
Hi @filfreire thanks for the update. I delete my account and save my passphrase then I was able to login via insomnia app.

Thanks again, 
max
