### ISSUE TITLE
Does Linux .deb package autoupdate?

### ISSUE THREAD

**Issue by adriandelgg** [getinsomnia/insomnia#5979]
### Expected Behavior

I'm using Ubuntu and I see that on the website you can download a `.deb` package inorder to install Insomnia.

Does this package auto update? Or would I have to redownload the `.deb` package anytime I want to install a new version that releases?

Also, if it doesn't autoupdate, is there some sort of command I can add to import the repo and check for updates?

I know I can use Flatpak or Snap, but I prefer native packages.

NOTE: If this isn't the place to ask questions like this, kindly direct me to where I can.

Thank you!

### Actual Behavior

.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

.

### What operating system are you using?

Ubuntu

### Operating System Version

Kubuntu 23.04

### Installation method

.

**Comment by filfreire** [comment]
Hi @codeonblocks thanks for reporting this!

If I'm not mistaken this is only possible on the AppImage when it comes to Linux releases.

This taking into account the docs of what we use for auto-updating: https://www.electron.build/auto-update.html
