### ISSUE TITLE
libcurl function was given a bad argument

### ISSUE THREAD

**Issue by david-engelmann** [getinsomnia/insomnia#5981]
### Expected Behavior

Making a simple request to /ping would go through and return what is expected ie. {"success": true} etc. This expected behavior was working until 5/18.

### Actual Behavior

no underlying logic changes and test are working fine when making request outside of Insomnia, starting 5/18 all the endpoints are now returning "A libcurl function was given a bad argument"

### Reproduction Steps

spin up a simple app with a ping test. Run the ping test from the browser or a request library, observe the working behavior. recreate the ping request in Insomnia and observe the image below. 
![image](https://github.com/Kong/insomnia/assets/81196676/925e0a45-2e16-4c0e-bae8-6bbc3bbb2ea0)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro

### Installation method

exe

### Last Known Working Insomnia version

2023.2.2

**Comment by filfreire** [comment]
@david-engelmann does this happen for any request at all?  (e.g. for example if you send to to bin service, like https://mockbin.org/ ?


Also can you share what you see on the request timeline:
![image](https://github.com/Kong/insomnia/assets/11976836/1ab52227-465b-4979-b47e-a7f5c46296b5)


And also see if you notice any errors on the Dev Tools:

![image](https://github.com/Kong/insomnia/assets/11976836/ede54644-d772-4eac-80c1-23a92b56fb71)
![image](https://github.com/Kong/insomnia/assets/11976836/fdeb2e41-7a70-4e18-93f2-8b576ef0b031)

**Comment by david-engelmann** [comment]
It can't make any external request, regardless of the site or service. Below is the timeline. 

* Preparing request to https://MESITE.com/ping
* Current time is 2023-05-19T13:10:15.237Z
* Enable automatic URL encoding

I'll include my prefs as well
![image](https://github.com/Kong/insomnia/assets/81196676/e04f18e5-59b0-4a33-9dcf-88293753a46e)

**Comment by filfreire** [comment]
Interesting, seems to be working on my Insomnia instance:
![image](https://github.com/Kong/insomnia/assets/11976836/b5e3cdf0-0217-404e-a3e1-b484500edc02)

Are you able to get anything if you do a regular `curl` on console?
```
curl --request GET \
  --url http://mesite.com/ping
```

**Comment by david-engelmann** [comment]
yes, i can make request outside of insomnia

**Comment by david-engelmann** [comment]
This error still persist, postman it is

**Comment by david-engelmann** [comment]
@filfreire bump

**Comment by david-engelmann** [comment]
Bump

**Comment by david-engelmann** [comment]
great support

**Comment by Keerthanaa-K** [comment]
@david-engelmann any update / were you able to fix this? @filfreire has any work been done on this?

 I am not able to send any request via Insomnia as I'm getting this error for every request.
Very bad, because I have 15 collections with hundreds of requests, and I am unable to use insomnia.

**Comment by david-engelmann** [comment]
@Keerthanaa-K I gave up after months of being ignored. I switched back to Postman with the .har file import feature

**Comment by Keerthanaa-K** [comment]
[subnetmarco](https://github.com/subnetmarco), anything that can be done here?
Reinstalling did not help. Installed an older version - did not help. Installed java 11. Did not help.
As I have mentioned, I have so many collections, with a ton more requests, and really want to continue using Insomnia.

**Comment by Keerthanaa-K** [comment]
@subnetmarco  anything that can be done here?
Reinstalling did not help. Installed an older version - did not help. Installed java 11. Did not help.
As I have mentioned, I have so many collections, with a ton more requests, and really want to continue using Insomnia.

**Comment by david-engelmann** [comment]
> @subnetmarco  anything that can be done here?
> Reinstalling did not help. Installed an older version - did not help. Installed java 11. Did not help.
> As I have mentioned, I have so many collections, with a ton more requests, and really want to continue using Insomnia.

Only thing I can suggest is to try with the following preferences

Maximum Redirects: -1
Request timeout: 0

**Comment by abudimirov** [comment]
@david-engelmann  you have set a very long request timeout. I have encountered the same error and the solution was to change request timeout for smaller value. For me it's 30000000
