### ISSUE TITLE
Insomnia won't update to v2023.2.2

### ISSUE THREAD

**Issue by Christoph-Harms** [getinsomnia/insomnia#5984]
### Expected Behavior

Insomnia should either
1. Auto-update to the newest version or
2. Be updated when updating manually

### Actual Behavior

Insomnia did not auto-update to v2023.2.2. After manually triggering the update process via the settings and restarting, Insomnia is still on v2023.2.1.

### Reproduction Steps

1. Go to 'Preferences'
2. Scroll down to 'Software Updates'
3. Click on 'Check now'
4. Wait for the update to download and (supposedly) install
5. After a while, the button that says 'Check now' changes to 'Updated (Restart Required)' and is greyed out
6. Restart Insomnia
7. Go to 'Preferences' again
8. See that the version is still v2023.2.1

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey (Version 12.6.3)

### Installation method

Don't know anymore, it's been a long time. Probably downloaded from insomnia.rest.

**Comment by rgaino** [comment]
I can confirm this behaviour also happening to me, macOS 13.3.1 (a) (22E772610a). I keep getting the notification to relaunch every time I open it.

<img width="352" alt="image" src="https://github.com/Kong/insomnia/assets/66829/3b4ef80b-c930-48cd-bf5e-27364524f002">

**Comment by Christoph-Harms** [comment]
Some time between the creation of this issue and now, my Insomnia did indeed automatically update itself to 2023.2.2, but it got my environments a little messed up. The reason why I wanted this update is because I had the bug where I could not access my base environment (#5969).

Now that the update did take place, my base environment is empty and all variables there have been distributed to the other environments.

Unsure whether or not I should close this issue.

**Comment by adamjansch** [comment]
I was on version 2023.1.0 (I don't use Insomnia a whole lot) on Mac (Ventura 13.4.1) and was having the same issue.

I assumed that a bug in the software update mechanism wouldn't allow me to update automatically to fix it ;-) – so manually downloaded and installed the latest version today (2023.3.0). Time will tell if this is still an issue.

**Comment by subnetmarco** [comment]
Auto-updates should be working again since this issue was first opened, let me know if that is not the case anymore and we will reopen this issue.
