### ISSUE TITLE
Insomnia won't let you change sub-environment names

### ISSUE THREAD

**Issue by jnerydesigner** [getinsomnia/insomnia#5989]
### Expected Behavior

Insomnia won't let you change sub-environment names

In the image below the sub-environment developer has the default behavior

![image](https://github.com/Kong/insomnia/assets/14322173/1daa49b3-2215-4f5f-9fc0-79cf4eecd814)

### Actual Behavior

When a sub-environment is created, it does not allow me to change its name, it may have been a behavior after the update:

Version: Insomnia 2023.2.2
Build date: 05/17/2023
OS: Linux x64 5.19.0-41-generic
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

Before it was working correctly.

### Reproduction Steps

1. click on the arrow
![image](https://github.com/Kong/insomnia/assets/14322173/8fa4467f-8b8f-4c80-a23c-d452b0acf266)

2. Choose manage environment
![image](https://github.com/Kong/insomnia/assets/14322173/a00e822d-6a12-45c0-b8d1-8bdc33a4841c)

3. Click the plus button
![image](https://github.com/Kong/insomnia/assets/14322173/28fae354-5ba4-48f4-acdc-701b5f86ac21)

4. Try changing the variable name
![image](https://github.com/Kong/insomnia/assets/14322173/843cad18-1861-4951-be4b-a29a9eeb62c8)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.2

### What operating system are you using?

Ubuntu

### Operating System Version

Linux x64 5.19.0-41-generic

### Installation method

sudo apt-get install insomnia

### Last Known Working Insomnia version

2023.2.1

**Comment by filfreire** [comment]
@jnerydesigner - thanks for reporting - you should be able to rename by clickin on environment title:

![rename](https://github.com/Kong/insomnia/assets/11976836/940ab1e9-6406-45dd-a841-c8cedf1034d7)

**Comment by lulzash** [comment]
what a terrible ui!
