### ISSUE TITLE
The request failed tu to unhandled error - Failed to render request: req_fb3a3c7938144834b93ded41dfd40dac

### ISSUE THREAD

**Issue by hjoncour** [getinsomnia/insomnia#5995]
### Expected Behavior

I was going to make a GraphQL request, and when pressing "Send", I received this error:

<img width="483" alt="Screenshot 2023-05-25 at 3 51 25 PM" src="https://github.com/Kong/insomnia/assets/9491486/cbbb12e7-969b-4d13-b6af-fcde9ed25d4e">

The error seems to affect all my requests: GraphQL or HTTP, whether I'm sending the request to a local app, or to a distant one.

### Actual Behavior

The request fails and nothing happens.

### Reproduction Steps

All my request were working fine, but suddenly stopped working. I have no idea what caused it and how to reproduce it, if it disappeared.
A colleague working in a different place seems to have been affected around the same time by the same issue.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.2

### What operating system are you using?

macOS

### Operating System Version

macOS 13.2.1 (22D68)

### Installation method

probably from the insomnia website

**Comment by hjoncour** [comment]
Found the cause:

My requests were using a jwt token that was obtained by exchanging an opaque token, that was itself obtained by sending a request. Every request was dependent on the previous one, and the error wasn't caught.

**Comment by shellygoel06** [comment]
@hjoncour How did you solve it? What did you change?

**Comment by hmtcelik** [comment]
you may getting this error because of that:

if you use Response => Body Attribute, example some token from login endpoint resonse data, check your request about the login endpoint, it should be success otherwise of course it not possible to use token from body
