### ISSUE TITLE
[Help] Spring and CSRF token

### ISSUE THREAD

**Issue by y-luis** [getinsomnia/insomnia#601]
- Insomnia Version: 5.11.7
- Operating System: Ubuntu 17.04

## Details

I need to provide [CSRF token for a Spring](https://docs.spring.io/spring-security/site/docs/current/reference/html/csrf.html#csrf-include-csrf-token) application. Following #296 , I did:
1
![image](https://user-images.githubusercontent.com/8008773/32841404-1df0c700-ca12-11e7-87d6-4aeb481a1f6f.png)
2
![image](https://user-images.githubusercontent.com/8008773/32841447-3c395aba-ca12-11e7-911c-639a0a654e72.png)

But this results in:

![image](https://user-images.githubusercontent.com/8008773/32841572-971c35ec-ca12-11e7-8ad2-b4d0b43ededb.png)

at the first request, later:

![image](https://user-images.githubusercontent.com/8008773/32841599-ab3d563c-ca12-11e7-8525-695cb8603964.png)

Please, can you help me setting this header?

**Comment by gschier** [comment]
Hi @y-luis,

I'm not sure there is much I can do here as it looks like Insomnia is functioning correctly.

Did you initially send a login request to update the initial `JSESSIONID` cookie?

**Comment by y-luis** [comment]
I use basic authentication. I first did a (successful) GET request to get the cookie.

**Comment by gschier** [comment]
Hmm, I'm not sure then, unfortunately. It seems like it's an issue with the way you are using the API. Have you gotten it working without Insomnia?

**Comment by y-luis** [comment]
@gschier , thanks for the tip, the issue is that I was requesting to a REST service, and there is need to implement some configuration for stateless apps to support CSRF in Spring. I based my solution on [this](https://sdqali.in/blog/2016/07/20/csrf-protection-with-spring-security-and-angular-js/) and it worked!

**Comment by gschier** [comment]
That's awesome @y-luis! :smile: So you have everything working in Insomnia now too?

**Comment by y-luis** [comment]
Yes! Now the server returns a cookie which is used as referred at #296 . Keep the great work! ;)
