### ISSUE TITLE
Extra space formatting issue in 'Response => Body Attribute'

### ISSUE THREAD

**Issue by lennertvandevelde** [getinsomnia/insomnia#6020]
### Expected Behavior

[Chaining requests](https://docs.insomnia.rest/insomnia/chaining-requests) in order to get a bearer token from an ROPC-request. It should be able to return the token and fill it into `Authorization: Bearer`.

### Actual Behavior

The token generation and passing works, but the formatting in the headers seems to be wrong. 

<img width="203" alt="image" src="https://github.com/Kong/insomnia/assets/61053080/d70ae22b-c6ad-407c-93d1-26c9cdee377a">

Returns this header
<img width="185" alt="image" src="https://github.com/Kong/insomnia/assets/61053080/59eca913-dbe2-4fcd-a8d2-04348ec16828">
which  yields a `401`.

<img width="428" alt="image" src="https://github.com/Kong/insomnia/assets/61053080/21ab4de2-4d70-466c-8ddd-e4cad3640e6d">

here you can see an extra space is added.

When filling in the same token statically, the call will work.

### Reproduction Steps

1. Go to the Barer tab on any call.
2. Fill in a `Response => Body Attribute` as Token.
3. Send request
4. Watch in Timeline and see an extra space is added after `Authorization: Bearer`

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2

### Installation method

download from insomnia.rest

**Comment by branbarh** [comment]
Based on your first photo, it looks like there's a space in the Token input before the `Response => Body Attribute` tag.

The current behavior that you're showing here may be intentional; however, I can't think of a case where having a leading/trailing space would be useful.

I'll submit a pull request for review; if this behavior is intentional, please feel free to provide further feedback.
