### ISSUE TITLE
[Bug] Do not encode sub-delim characters in query part of URL

### ISSUE THREAD

**Issue by oliverjanik** [getinsomnia/insomnia#604]
- Insomnia Version: 5.11.5
- Operating System: Win 10

## Details

When I sent a get request like this 

```
https://example.com/test?limit(1,1)
```

Insomnia encodes the comma character for me.  And the request ends up being this:
```
https://example.com/test?limit(1%2C1)
```

Please note that Postman does not do this, neither do any HTTP clients that I tried (C# HttpClient, Angular 4 Http service)

If I'm reading the RFC right the comma is a sub-delim and is fully allowed within query part of URL.

https://tools.ietf.org/html/rfc3986#section-3.4

**Comment by gschier** [comment]
There was a similar question in #592 about encoding the `$`. It seems like the best solution to this may be to have URL encoding be configurable.

**Comment by gschier** [comment]
Going to close this in favor of #605
