### ISSUE TITLE
Collections imported into new files are turned into documents

### ISSUE THREAD

**Issue by rmisiakexscientia** [getinsomnia/insomnia#6048]
### Expected Behavior

When a collection is imported into a new file in insomnia it should be imported as a collection

### Actual Behavior

It is imported as a document

### Reproduction Steps

1. Create a new `collection` in a project
![image](https://github.com/Kong/insomnia/assets/117294659/eb65f4e6-9274-43c3-aaef-4058c266dc80)
1. Export it to an insomnia json or yaml file
![image](https://github.com/Kong/insomnia/assets/117294659/25ac17e7-664e-4aab-a720-cac144c2d2a2)
1. observe that the export is marked as a collection
    ```
        {
          "_id": "wrk_b58d5fc055af493cb0ebc05201cc80a1",
          "parentId": null,
          "modified": 1687436793416,
          "created": 1687436793416,
          "name": "My Collection",
          "description": "",
          "scope": "collection",
          "_type": "workspace"
        },
    ```
1. Go back to the project page and import the collection into a new file
![image](https://github.com/Kong/insomnia/assets/117294659/98e1a11e-1f50-4e6d-b650-da3e03587271)

The imported object is now a document
![image](https://github.com/Kong/insomnia/assets/117294659/66e57d0f-49d0-4ccf-95c0-252a4cc0d315)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.2

### What operating system are you using?

macOS

### Operating System Version

mac os ventura 

### Installation method

download

### Last Known Working Insomnia version

2023.1.0

**Comment by subnetmarco** [comment]
@gatzjames any thoughts here?

**Comment by gatzjames** [comment]
Thanks for the report!
This should be fixed 2023.3.0!

**Comment by jmcdl** [comment]
I am having this same issue in version 2023.4.0. An exported collection is imported as a document. 

<img width="781" alt="Screenshot 2023-07-11 at 11 51 17 AM" src="https://github.com/Kong/insomnia/assets/25539870/0aca9a4f-1c43-4b1e-96e8-7d7ca7919211">
<img width="788" alt="Screenshot 2023-07-11 at 11 51 22 AM" src="https://github.com/Kong/insomnia/assets/25539870/96a2c3b8-6205-4ccc-9e73-b55bf21c8221">
<img width="223" alt="Screenshot 2023-07-11 at 11 51 38 AM" src="https://github.com/Kong/insomnia/assets/25539870/77a2114e-34de-440e-812a-cf3d8b8bb572">

**Comment by jackkav** [comment]
Can you confirm your export version and workspace object has the follow structure and values.
```
_type: export
__export_format: 4
__export_date: 2022-11-15T17:31:29.274Z
__export_source: insomnia.desktop.app:v2023.4.0
resources:
```
and
```
  - _id: wrk_0702a57d75d44255a8cecd2c5fa87809
    parentId: null
    modified: 1666867685193
    created: 1666867357067
    name: simple
    description: ""
    scope: collection
    _type: workspace
```

if your `scope` in the workspace object is something besides `collection` that would explain the issue you're having. You can workaround this by changing this field to `collection` in the yaml.

**Comment by jmcdl** [comment]
@jackkav Yes, that was the problem. Our export was from v2023.3.0 and for some reason it had `scope: design`. Changing this line to `scope: collection` allowed me to import it correctly. I then made a new export with v2023.4.0 and it exported with the correct scope. Thanks.
