### ISSUE TITLE
Insomnia crashes with segmentation fault on any request

### ISSUE THREAD

**Issue by fancywriter** [getinsomnia/insomnia#6049]
### Expected Behavior

To work properly

### Actual Behavior

Crashes after I do any request, for example GET https://github.com

### Reproduction Steps

1. Open Insomnia
2. Create new request
3. Press Send button

It gives me "Segmentation fault" error with no useful logs at all.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Originally reproduced on older 2022.7.5, but upgrade to 2023.2.2 didn't help.
![image](https://github.com/Kong/insomnia/assets/1200256/3f8d1a61-2309-4ccf-bd33-12a194a8d114)

### Insomnia Version

2023.2.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux devlin20221-ThinkPad-X1-Carbon-Gen-9 6.1.31-gentoo-x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun  2 10:05:53 IST 2023 x86_64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz GenuineIntel GNU/Linux

### Installation method

DEB package

### Last Known Working Insomnia version

2022.7.5

**Comment by jackkav** [comment]
You are probably missing a [node-libcurl](https://github.com/JCMais/node-libcurl) dependency, theres an exhaustive list here. https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/web/insomnia/default.nix
have fun!

**Comment by fancywriter** [comment]
@jackkav  oh, could it be related that I have updated nodejs from 18 to 20? But it uses bundled version of 16... I thought everything must be inside the DEB package?..

curl-8.0.1 is installed
```
$ qlist curl | grep libcurl.so
/usr/lib64/libcurl.so.4.8.0
/usr/lib64/libcurl.so
/usr/lib64/libcurl.so.4

$ curl --version
curl 8.0.1 (x86_64-pc-linux-gnu) libcurl/8.0.1 OpenSSL/3.0.9 zlib/1.2.13 zstd/1.5.5 c-ares/1.19.1 nghttp2/1.51.0
Release-Date: 2023-03-20
Protocols: dict file ftp ftps http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets zstd
```

**Comment by fancywriter** [comment]
Just for the record, installing node-libcurl globally didn't help.
```
$ qlist curl | grep libcurl.so
/usr/lib64/libcurl.so.4.8.0
/usr/lib64/libcurl.so
/usr/lib64/libcurl.so.4
```

Is there any way to run Insomnia with my own version of NodeJS runtime?.. it seems not possible from the DEB package, right?

**Comment by fancywriter** [comment]
@jackkav running inside GDB gives little more information
```
[New Thread 0x7fff9f1fe6c0 (LWP 26133)]
[Thread 0x7fff9f1fe6c0 (LWP 26133) exited]

Thread 1 "insomnia" received signal SIGSEGV, Segmentation fault.
0x00007fffad9d0ac7 in SSL_get_peer_certificate () from /tmp/.org.chromium.Chromium.UlICUL
```

**Comment by fancywriter** [comment]
Perhaps this binary package is not compatible with some libraries installed in my system... I do not have Chromium installed for sure... it should be part of the package.

**Comment by jackkav** [comment]
From the node-libcurl docs:
> The `brotli`, `nghttp2`, `OpenSSL` and `zlib` versions **must** match the version Node.js uses, this is necessary to avoid any possible issues by mixing library symbols of different versions, since Node.js also exports some of the symbols of their deps.

> In case you are building the addon yourself with the libraries mentioned above, you must make sure their version is ABI compatible with the one Node.js uses, otherwise you are probably going to hit a Segmentation Fault.

**Comment by fancywriter** [comment]
Seems it works now on Insomnia-2023.4.0. @jackkav
