### ISSUE TITLE
Auto-update to 2023.2.2 moved, hid, deleted data

### ISSUE THREAD

**Issue by kelsey-bambi** [getinsomnia/insomnia#6050]
### Expected Behavior

* no auto-updates by default
* no moving data during an update
* no hiding data during an update

### Actual Behavior

* insomnia updated
* was pestered to log in for the first time
* all my data appeared gone

Was able to follow resolution steps on https://github.com/Kong/insomnia/issues/5999 to at least locate my saved requests, hiding in the `DEBUG` tab of a seemingly auto-created New Document.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.2

### What operating system are you using?

macOS

### Operating System Version

macOs 12.6.6

### Installation method

downloaded from website

**Comment by subnetmarco** [comment]
@kelsey-bambi The issue you have experienced is that your collections were transparently moved from your "Collection" file into a "Design Document" file, and by going to the "Design Document" you were able to find your collections again. Is this statement correct?

What other data you have lost that you cannot recover anymore?

**Comment by jackkav** [comment]
Thanks for the report, I'm also curious if anything else was missing.

This issue should be resolved in the next release of Insomnia 2023.3.0

**Comment by kelsey-bambi** [comment]
@subnetmarco that is correct, I believe. (I've never deliberately used the "Design Document" functionality before.)

The collection's environments were moved as well, not just the requests.

Thanks!

**Comment by subnetmarco** [comment]
@jackkav has this issue been resolved with the latest `2023.3.0` ?

**Comment by jackkav** [comment]
This has been resolved as of 2023.4.0, collection exports will no longer be erroneously imported as design documents.
Thanks for the report @kelsey-bambi
