### ISSUE TITLE
Support GraphQL subscriptions via WebSocket

### ISSUE THREAD

**Issue by XChikuX** [getinsomnia/insomnia#6055]
### Expected Behavior

I want to be able to connect to GraphQL subscriptions via insomnia.

### Actual Behavior

I get 403 Forbidden errors

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

As far as I am aware, javascript clients use the apollo graphql client to send and receive over a websocket (wss://url.com/graphql)

connection.

This would be amazing to support for insonmia as there is a gap in testing from the client for this feature.

### Insomnia Version

2023.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

Download from official website

**Comment by socketsguru** [comment]
It would be great to support the web socket link that appsync provides like this:

`wss://<app-id>.appsync-realtime-api.<region>.amazonaws.com/graphql`

**Comment by XChikuX** [comment]
Adding request for "SSE" support now that it is in the roadmap for GraphQL as well.

**Comment by cwangsmv** [comment]
@XChikuX @marcodali I did some investigation on graphql subscription via websocket. It seemed that most people are using apollo client to do this by lib `graphql-ws` with its websocket subprotocol `graphql-transport-ws`. (Refer: https://www.apollographql.com/docs/react/data/subscriptions/#websocket-subprotocols)
It is a standard websocket protocol for Graphql? 

Also for the SSE support, I only find a third-party lib [graph-sse](https://github.com/enisdenjo/graphql-sse) has implemented this.

**Comment by XChikuX** [comment]
@cwangsmv It most definitely is a standard.

There is a bit of confusion among the same, because there is an old standard and a new one. Both standards share the same repository name but a different protocol name, or something of the sorts. It's honestly a big mess.

SSE is going to be standardized as a part of the GraphQL spec. 

Insomnia should implement WS as well as SSE since SSE is nothing more than a unidirectional Websocket.

This gap in testing really needs to be addressed. Not sure why Kong isn't serious about this even after the community has shown a clear need.

**Comment by notjaywu** [comment]
The latest beta [Insomnia 10.1.0-beta.2](https://github.com/Kong/insomnia/releases/tag/core%4010.1.0-beta.2) now supports GraphQL subscription via WebSockets. Any feedback is welcome.

**Comment by XChikuX** [comment]
@notjaywu Please see #9791
