### ISSUE TITLE
API Spec in the Design tab exports well but cannot be imported

### ISSUE THREAD

**Issue by ghost** [getinsomnia/insomnia#6060]
### Expected Behavior

The exported JSON file or the exported YAML file is expected to reproduce the exact copy of the exported document when imported. All features including the ```yaml``` document file, requests, tests, environments and cookies are expected to be the same.

### Actual Behavior

When exporting a document with the "insomnia v4 (JSON)" format or with the "insomnia v4 (YAML)" format, the ```yaml``` file in the "DESIGN" tab is exported well like the images below.
![image](https://github.com/Kong/insomnia/assets/61644589/1b777ebc-d2b8-458e-b266-65e16bc959b1)
![image](https://github.com/Kong/insomnia/assets/61644589/69874ed5-4c38-4d52-8604-868512861163)
![image](https://github.com/Kong/insomnia/assets/61644589/44cd198e-4b75-4b16-ac49-42302c0110b3)
However, when I create a new document by clicking "+ Create" and then "Import" to import the exported JSON/YAML file, the ```yaml``` specification document is not recovered as shown below. 
![image](https://github.com/Kong/insomnia/assets/61644589/35fc9680-2b6d-44d1-b88d-e5085b640ab6)
First, there is no error message when importing. The import process finishes without any popup or failing.  
Second, the requests in the "DEBUG" tab, the tests in the "TEST" tab, environments and cookies are all fully recovered.
Finally, I have tried using other documents and tried making the document with the same name but it still did not work.

### Reproduction Steps

1. In "Personal Projects" create a "Design Document" by pressing "+ Create" and then "Design Document"
2. Name it whatever you want
3. Enter some ```yaml``` text and make some requst. Make soem tests, environments and cookies if you want.
4. Export the document by pressing on the dropdown form on the left of the "DESIGN" tab and press "Import/Export".  
5. Press "Export Data" and then press 'Export the "<document name>" Document'.
6. Select all and press "Export"
7. Select "Insomnia v4 (JSON)" or "Insomnia v4 (YAML)" and press "Done" and save
8. Return to "Personal Projects" and press "+ Create" and then "Import"
9. Choose the saved file and press "Scan"
10. Change Name if you want and press "Import"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2

### Installation method

downloaded from insomnia.rest

**Comment by jackkav** [comment]
Fixed in 2023.3.0
