### ISSUE TITLE
HTTP Status code 509 is unknown

### ISSUE THREAD

**Issue by thibaultmeyer** [getinsomnia/insomnia#6068]
### Expected Behavior

Hello,

HTTP status code 509 is show as "Unknown" in Insomnia. This status code means "Bandwidth Limit Exceeded" (https://http.dev/509)

![image](https://github.com/Kong/insomnia/assets/1005086/9ed25515-f36e-4b5a-a499-a50f66811e78)

Insomnia v2023.3.0

### Actual Behavior

HTTP status code 509 is show as "Unknown"

### Reproduction Steps

1. Call a REST service that returns http 509 status

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

downloaded from insomnia.net

**Comment by jackkav** [comment]
Our list is based upon https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#server_error_responses
According to wikipedia 509 is an Unofficial code, used only in apache web server/cPanel
Supporting unofficial error codes could be quite costly to maintain, but welcome to submit a PR.
