### ISSUE TITLE
Unable to sign up for Insomnia with company email

### ISSUE THREAD

**Issue by ellafeldmann** [getinsomnia/insomnia#6073]
### Expected Behavior

I'm reaching out because my team at Mercury is currently blocked by an issue on Insomnia. 

We are trying to create a team subscription to Insomnia. In order to do that, each one of the team members needs to create an individual Insomnia account with their work email.

### Actual Behavior

However, whenever I try to Sign Up with my Mercury email address, I run into an "unexpected internal server error"

![image](https://github.com/Kong/insomnia/assets/25710397/13f8eb69-aaab-47ab-898b-2fcad08e5339)

I'm pretty sure this is an internal issue on Insomnia. This error is different from the error that occurs if I re-enter my password incorrectly, for example.

I have been able to create an account for my personal email address without any issue.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.2.0

### What operating system are you using?

macOS

### Operating System Version

Apple M1 Max (MacOS 13.4.1 (22F82))

### Installation method

Download from Insomnia REST

**Comment by marckong** [comment]
We recognized the cause for this issue. We will add a fix to it shortly.

**Comment by marckong** [comment]
You may try again this time, but we are wondering if you ever signed up in February and deleted an account.

**Comment by rizaldywirawan** [comment]
is it not possible to just re-register?

**Comment by marckong** [comment]
You can re-register.
