### ISSUE TITLE
[Performance] Better handling of large request bodies

### ISSUE THREAD

**Issue by crakjie** [getinsomnia/insomnia#608]
- Insomnia Version: 5.8.4
- Operating System: ubuntu

## Details

When a big JSON is put in the body (3MB) the application became realy slow.
I think it tries to show the JSON as beautiful as it can, but it's, of course, unnecessary for this size of data.
The application may crash or finally become responsive.
Maybe if we have just a link to a JSON file that could resolve this problem.

**Comment by gschier** [comment]
Hmm, what type of hardware are you running it on? I am able to view JSON responses of over 50MB on my laptop. Right now, if the response is over 5MB, it is hidden by default. Maybe this limit should be lowered by default and made configurable?

**Comment by crakjie** [comment]
sorry I'm talking about the body of the request.

I'm running on 32Gb 4core computer.

**Comment by gschier** [comment]
Oh, for the body you can use the Binary File body type and choose a JSON file.

**Comment by gschier** [comment]
Also, the reason the body viewer is slower than the response viewer is because Insomnia tries to lint the body to check for errors, as well as do a bunch of other stuff around autocompletion and things.

**Comment by crakjie** [comment]
And set Content-Type : application/json good idea !

Yes I was thinking it's the syntax colorer that was taking time. 
Can the linting be run in a parallel to not slow down the user? Or maybe it's could check the size of the file before running the lint?

**Comment by gschier** [comment]
ya, both of those are great ideas! 😄 👍

**Comment by gschier** [comment]
Closed by #614
