### ISSUE TITLE
insomnia 2023.4.0 fail to start on windows 8.1

### ISSUE THREAD

**Issue by SorinGFS** [getinsomnia/insomnia#6089]
### Expected Behavior

I expect to have the app working :smile: 

### Actual Behavior

installing the latest major release on windows 8.1 fails

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.4.0

### What operating system are you using?

Windows

### Operating System Version

8.1

### Installation method

exe

### Last Known Working Insomnia version

2023.3.0

**Comment by br4instormer** [comment]
According to Changelog they upgraded Electron to version 23 and Nodejs to 18.12. Node 18

**Comment by br4instormer** [comment]
According to Changelog they upgraded Electron to version 23 and Nodejs to 18.12. Node 18

**Comment by br4instormer** [comment]
According to [Changelog](https://insomnia.rest/changelog) they upgraded Electron to version 23 and Nodejs to 18.12.
> Node.js does not support running on operating systems that are no longer supported by their vendor. For operating systems where their vendor has planned to end support earlier than April 2025, such as Windows 8.1 (January 2023) and Windows Server 2012 R2 (October 2023), support for Node.js 18 will end at the earlier date.

[Nodejs 18 Changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.16.1)

**Comment by SorinGFS** [comment]
> According to [Changelog](https://insomnia.rest/changelog) they upgraded Electron to version 23 and Nodejs to 18.12.
> 
> > Node.js does not support running on operating systems that are no longer supported by their vendor. For operating systems where their vendor has planned to end support earlier than April 2025, such as Windows 8.1 (January 2023) and Windows Server 2012 R2 (October 2023), support for Node.js 18 will end at the earlier date.
> 
> [Nodejs 18 Changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.16.1)

I use Node 18.15.0 on that specific computer, have no problem with it.  End of support doesn't mean that will stop working.

**Comment by SorinGFS** [comment]
@br4instormer 

electron v23 may be the problem, because vscode also stops providing updates for windows 8.1 this month.

**Comment by jackkav** [comment]
Correct, vscode is also ending support for Windows 8.1
If chromium ends support then so does electron and therefore any electron app that is being actively maintained. You can still download previous versions of insomnia to use on out-of-support operation system versions, but you may want to disable auto updates.
