### ISSUE TITLE
Add ability to save to file in code generation

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#61]
- [ ] Save to a file
- [ ] Remember location so it can easily be overwritten
- [ ] Add real-time sync functionality so you can keep testing it (not sure if actually useful)

**Comment by laterne** [comment]
I think it would be handy to be able to automatically save a workspace to a external file that can be kept in source control. The file could be watched for changes that get reflected in insomnia. This was I don't have to export/import regularly.
