### ISSUE TITLE
[Bug] Can't select sha1 algorithm under Hawk authentication

### ISSUE THREAD

**Issue by c22** [getinsomnia/insomnia#610]
- Insomnia Version: 5.11.7
- Operating System: macOS Sierra 10.12.6

## Details

When I select sha1 from the drop down box, the value doesn't seem to update and sha256 remains ticked. I don't use Hawk for anything, I just noticed it when testing something else. FYI to @jgiovaresco

**Comment by gschier** [comment]
Thanks for reporting this! Fixed
