### ISSUE TITLE
[Bug] Insomnia Not Downloading Files

### ISSUE THREAD

**Issue by lifewcody** [getinsomnia/insomnia#612]
- Insomnia Version: 5.11.7
- Operating System: Windows 10 Pro 64 Bit

## Details

Hello,

I have spent 3 days thinking my code was bad because of this issues. I uploaded a 350MB ISO file to my API to test out big files, but apparently Insomnia doesn't terminate when the end of the file is received. I have waited up to 5 minutes waiting for it to download, but it never does. The content type and content length is set correctly, and it works in chrome so I know it works, just not in Insomnia.

Here is the timeline [It is sort of long, sorry]

```
* Preparing request to http://ias.dev/api/100/application/1/vmware.iso
* Using libcurl/7.51.0-DEV OpenSSL/1.0.2j zlib/1.2.8 libssh2/1.6.1_DEV
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Hostname in DNS cache was stale, zapped
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to ias.dev (127.0.0.1) port 80 (#363)
> GET /api/100/application/1/vmware.iso HTTP/1.1
> Host: ias.dev
> User-Agent: insomnia/5.11.7
> Accept: */*
< HTTP/1.1 200 OK
< Date: Mon, 20 Nov 2017 14:33:43 GMT
< Server: Apache/2.4.27 (Win32) OpenSSL/1.0.2l PHP/7.1.9
< X-Powered-By: PHP/7.1.9
< Transfer-Encoding: chunked
< Content-Type: application/x-iso9660-image

* Received 15.8 KB chunk
* Received 16 KB chunk
[[[ --- Removed all the in-between chunks, they are all about the same size though --- ]]
* Received 225 B chunk
* Curl_http_done: called premature == 0
* Connection #363 to host ias.dev left intact
```

As you can see the content length and content type is correct. Insomnia doesn't display the file or even stop when it is done. Also you can see the last chunk is only 225 B, so that is the end of the file.

**Comment by gschier** [comment]
Hey @lifewcody. Do you have a public URL I can test this with?

**Comment by lifewcody** [comment]
@gschier Hello,
I currently do not have a Public URL as it is being developed locally. I can try to push it to a url later today, but in the meantime is there any other information you could use?

**Comment by gschier** [comment]
There is one more thing that might help. Can you check the console for errors when you make the request? _View > Toggle DevTools > Console_

My first thought is that the request _is_ finishing, but it's taking a long time (or failing) to store the response to disk. 


Also, it could be any URL, such as a download of an Ubuntu ISO. As long as it causes the same problem.

**Comment by lifewcody** [comment]
Would you look at that, there is something in the console
```
google.js:74 [ga] Send event [Request, Activate, Sidebar]
google.js:74 [ga] Send event [Request, Send]
google.js:74 [ga] Send event [Request, Send]
google.js:74 [ga] Send event [Window, Unmaximize]
google.js:74 [ga] Send event [Window, Resize]
google.js:74 [ga] Send event [Window, Move]
index.js:30 Uncaught Error ErrorEvent {isTrusted: true, message: "Uncaught Error: "toString()" failed", filename: "buffer.js", lineno: 503, colno: 11…}bubbles: falsecancelBubble: falsecancelable: truecolno: 11composed: falsecurrentTarget: globaldefaultPrevented: falseerror: Error: "toString()" failed
    at Buffer.toString (buffer.js:503:11)
    at StringDecoder.utf8Text [as text] (string_decoder.js:180:16)
    at StringDecoder.write (string_decoder.js:64:46)
    at Curl._onEnd (C:\Users\lifew\AppData\Local\insomnia\app-5.11.7\resources\app.asar\node_modules\insomnia-node-libcurl\lib\Curl.js:902:46)
    at Multi.<anonymous> (C:\Users\lifew\AppData\Local\insomnia\app-5.11.7\resources\app.asar\node_modules\insomnia-node-libcurl\lib\Curl.js:52:14)eventPhase: 0filename: "buffer.js"isTrusted: truelineno: 503message: "Uncaught Error: "toString()" failed"path: Array(1)returnValue: truesrcElement: globaltarget: globaltimeStamp: 298641329.13000005type: "error"__proto__: ErrorEvent
window.addEventListener.e @ index.js:30
buffer.js:503 Uncaught Error: "toString()" failed
    at Buffer.toString (buffer.js:503)
    at StringDecoder.utf8Text [as text] (string_decoder.js:180)
    at StringDecoder.write (string_decoder.js:64)
    at Curl._onEnd (C:\Users\lifew\AppData\Local\insomnia\app-5.11.7\resources\app.asar\node_modules\insomnia-node-libc…:902)
    at Multi.<anonymous> (C:\Users\lifew\AppData\Local\insomnia\app-5.11.7\resources\app.asar\node_modules\insomnia-node-libc…:52)
Buffer.toString @ buffer.js:503
utf8Text @ string_decoder.js:180
StringDecoder.write @ string_decoder.js:64
Curl._onEnd @ C:\Users\lifew\AppData\Local\insomnia\app-5.11.7\resources\app.asar\node_modules\insomnia-node-libc…:902
(anonymous) @ C:\Users\lifew\AppData\Local\insomnia\app-5.11.7\resources\app.asar\node_modules\insomnia-node-libc…:52
google.js:74 [ga] Send event [Error, Uncaught Error]
```

I am test downloading a ubuntu iso served by apache from my local computer as I don't have the fastest internet right now.

Same error serving locally

```
google.js:74 [ga] Send event [Request, Send]
google.js:74 [ga] Send event [Request, Send]
google.js:74 [ga] Send event [Window, Unmaximize]
google.js:74 [ga] Send event [Window, Resize]
google.js:74 [ga] Send event [Window, Move]
index.js:30 Uncaught Error ErrorEvent {isTrusted: true, message: "Uncaught Error: "toString()" failed", filename: "buffer.js", lineno: 503, colno: 11…}
window.addEventListener.e @ index.js:30
buffer.js:503 Uncaught Error: "toString()" failed
    at Buffer.toString (buffer.js:503)
    at StringDecoder.utf8Text [as text] (string_decoder.js:180)
    at StringDecoder.write (string_decoder.js:64)
    at Curl._onEnd (C:\Users\lifew\AppData\Local\insomnia\app-5.11.7\resources\app.asar\node_modules\insomnia-node-libc…:902)
    at Multi.<anonymous> (C:\Users\lifew\AppData\Local\insomnia\app-5.11.7\resources\app.asar\node_modules\insomnia-node-libc…:52)
Buffer.toString @ buffer.js:503
utf8Text @ string_decoder.js:180
StringDecoder.write @ string_decoder.js:64
Curl._onEnd @ C:\Users\lifew\AppData\Local\insomnia\app-5.11.7\resources\app.asar\node_modules\insomnia-node-libc…:902
(anonymous) @ C:\Users\lifew\AppData\Local\insomnia\app-5.11.7\resources\app.asar\node_modules\insomnia-node-libc…:52
google.js:74 [ga] Send event [Error, Uncaught Error]
```

**Comment by gschier** [comment]
Was able to reproduce! It looks like large responses of that size cause problems. Will need to adjust how responses are handled to fix this but it shouldn't be too much work hopefully.

<img width="604" alt="image" src="https://user-images.githubusercontent.com/587576/33026330-1bc401fa-ce08-11e7-9b87-0438cc4073a2.png">

**Comment by lifewcody** [comment]
@gschier Any ETA when it will be fixed for the public? I really like Insomnia, but I won't be able to use it until it is fixed :(
You won't believe how much I have been pulling my hair, googling everything possibly, changing the same lines of code over and over. So glad I found the issue haha

**Comment by gschier** [comment]
Ugh, ya that sucks. I feel bad for making you lose all that hair! 

I should be able to get a fix out with the next release, hopefully by the end of the week.

**Comment by lifewcody** [comment]
@gschier 
Awesome, could I get some bug credits in the release notes :)

**Comment by gschier** [comment]
Sure! I'll add that to my To-Do list

**Comment by gschier** [comment]
Hey @lifewcody. I should be able to get an update out for this by the end of the week, but I've made a beta available already if you want to give it a try. One note. Be sure to update the update channel to "stable and beta" within the settings screen or it will try to roll itself back to the previous version. https://insomnia.rest/changelog/5.12.0-beta.1/

**Comment by lifewcody** [comment]
@gschier I'll give it a try and let you know :). Thank you so much
