### ISSUE TITLE
Unable to rename "Sub Environment" in "Manage Environments"

### ISSUE THREAD

**Issue by wilsonpage** [getinsomnia/insomnia#6124]
### Expected Behavior

Within "Manage Environments" I should be able to change the name of a "Sub Environment".

### Actual Behavior

Unable to change the name.

### Reproduction Steps

https://github.com/Kong/insomnia/assets/1020551/6ba24ea7-1ba6-445d-8934-ce00c6163b3e

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.4.0

### What operating system are you using?

macOS

### Operating System Version

13.4.1 (22F82)

### Installation method

Download from website

### Last Known Working Insomnia version

?

**Comment by tlund101** [comment]
I believe this commit fixes the issue (as well as the issue of not being able to go between Base Environment and the same sub environment).  I'm unable to test it, however, as the latest code doesn't want to run on my machine due to several "Extension Errors".

https://github.com/Kong/insomnia/commit/eaece7c8636bb887ff18a28b531deb4df2805a46

**Comment by ethancdaniel** [comment]
I'm getting this problem on the same operating system. Using an M1 if that matters. It completely freezes the app, so you have to force quit.

**Comment by TearsOfFears** [comment]
Have the same issue. Windows 11 and 2023.4.0 version

**Comment by filfreire** [comment]
@wilsonpage @ethancdaniel @TearsOfFears 

Double click on the Environment title
![rename](https://github.com/Kong/insomnia/assets/11976836/046598f3-62b6-45e5-bf9b-5d34eb705f42)

**Comment by TearsOfFears** [comment]
Thx)))

**Comment by wilsonpage** [comment]
> @wilsonpage @ethancdaniel @TearsOfFears
> 
> Double click on the Environment title ![rename](https://user-images.githubusercontent.com/11976836/254629384-046598f3-62b6-45e5-bf9b-5d34eb705f42.jpg)

Oh wow, thanks! This definitely changed and is now inconsistent with the rest of Insomnia renaming UX.

<img width="424" alt="image" src="https://github.com/Kong/insomnia/assets/1020551/7ce523be-d34d-4ba8-ba87-0f550472bae4">
