### ISSUE TITLE
Import through plugin created new workspaces instead importing in current one

### ISSUE THREAD

**Issue by sebastiande** [getinsomnia/insomnia#6125]
### Expected Behavior

Import JSON content through plugin context.data into the current workspace or given workspace id (which was possible in the past and seems to be gone now).

### Actual Behavior

With every import Insomnia creates a new workspace instead using the current one.,

### Reproduction Steps

1. Create a plugin with minimal code in index.js eg:

```
module.exports.workspaceActions = [
    {
        label: 'Pull from GIT',
        icon: 'fa-arrow-down',
        action: async (context, data) => {
            const impFilename = 'example.json';
            if (!fs.existsSync(impFilename)) {
                context.app.alert('Error importing',
                    'Seems example.json is not existing!');
                return false;
            }

            fs.readFile(impFilename, "utf8", function (err, fileContent) {
                context.data.import.raw(fileContent, {
                    workspaceId: data.workspace._id,
                });
            });
        },
    }
];
```

Use example.json eg. with the following content

```
{
  "_type": "export",
  "__export_format": 4,
  "__export_date": "2023-07-09T17:27:43.046Z",
  "__export_source": "insomnia.desktop.app:v2023.4.0",
  "resources": [
    {
      "_id": "req_44dcc4a6c60b42b4b91cf8888a2d9b1b",
      "parentId": "__WORKSPACE_ID__",
      "modified": "1637671845661",
      "created": 1688992190875,
      "url": "https://google.de",
      "name": "New Request",
      "description": "",
      "method": "GET",
      "body": {},
      "parameters": [],
      "headers": [],
      "authentication": {},
      "metaSortKey": -1688992190875,
      "isPrivate": false,
      "settingStoreCookies": true,
      "settingSendCookies": true,
      "settingDisableRenderRequestBody": false,
      "settingEncodeUrl": true,
      "settingRebuildPath": true,
      "settingFollowRedirects": "global",
      "_type": "request"
    },
    {
      "_id": "__WORKSPACE_ID__",
      "parentId": null,
      "modified": "1637671845661",
      "created": 1688992188630,
      "name": "My Collection",
      "description": "",
      "scope": "collection",
      "_type": "workspace"
    },
    {
      "_id": "__BASE_ENVIRONMENT_ID__",
      "parentId": "__WORKSPACE_ID__",
      "modified": "1637671845661",
      "created": 1688992188636,
      "name": "Base Environment",
      "data": {
        "url": "https://google.de"
      },
      "dataPropertyOrder": {
        "&": [
          "url"
        ]
      },
      "color": null,
      "isPrivate": false,
      "metaSortKey": 1688992188636,
      "_type": "environment"
    }
  ]
}
```

Try to import it. The ImportOptions were removed so it is not possible anymore to send a workspaceId.  This basically switches the import of workspaces to import of projects and breaks many plugins: https://github.com/Kong/insomnia/pull/6044

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

After this feature: https://github.com/Kong/insomnia/pull/5869, the requests were shown multiple times with every import - reported here: https://github.com/Kong/insomnia/issues/5946
I don't see this behavior within the newer versions anymore, but with every import, a new request collection is created instead of updating the current one.

The issue might be related to the mentioned above one.

### Insomnia Version

2023.4.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.3.1

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

2023.1.0

**Comment by sebastiande** [comment]
@jackkav As far as I see there is no check if the workspace already exists (in importResourcesToProject) and it is always imported as a new workspace:

```
const r = await Promise.all(resources.filter(isWorkspace)
    .map(resource => importResourcesToNewWorkspace(projectId, resource)));
```

shouldn't the method to import resources into a project check if the workspace already exists and then not import into a new workspace?
something like this:

```
const r = await Promise.all(resources.filter(isWorkspace)
    .map(async (resource) => {
      let isExistingWorkspace = false;
      if (resource && resource._id) {
        const existingWorkspace = await models.workspace.getById(resource._id);
        if (existingWorkspace) {
          isExistingWorkspace = true;
        }
      }
      if (isExistingWorkspace) {
        await importResourcesToWorkspace({
          workspaceId: resource._id,
        })
      } else {
        await importResourcesToNewWorkspace(projectId, resource)
      }
    }));
```

**Comment by jackkav** [comment]
@sebastiande thanks for you contributions, there will be improvements to the git sync feature in our next release.

**Comment by sebastiande** [comment]
@jackkav thanks for the answer, but it is not about git sync it is about the functionality for plugins to import or export workspaces. This could be used for git sync but as well for other use cases.

Anyways what does the git sync mean? As far as I know it is only for design documents and not for request collections?

**Comment by NickRimmer** [comment]
I've suggested sync method for plugins some time ago
https://github.com/Kong/insomnia/pull/6078

**Comment by claudioluciano** [comment]
any news on this issue?

**Comment by jackkav** [comment]
> Anyways what does the git sync mean? As far as I know it is only for design documents and not for request collections?

team sync and git sync should now be working on both design docs and collections.

Import and export is for backing up and single instance sharing.

Sync is an important feature to us but we only have plans to support team sync and git sync going forward. I'm sure you can all appreciate that in order to provide better quality features we have to cut scope. We would greatly appreciate ideas on improving the above mentioned sync methods.

Thanks for your patience and understanding.

**Comment by huuphat1908** [comment]
I created a PR to fix this issue https://github.com/Kong/insomnia/pull/7081

**Comment by victoraugustofd** [comment]
Hi @jackkav, I just faced the same problem on a plugin that I am working on. I didn't understand this part of your response:
 
> Import and export is for backing up and single instance sharing.

This feature, following [the documentation](https://docs.insomnia.rest/insomnia/context-object-reference#contextdata), is very clear that we can use it to import something on a specific (optional) workspaceId.
What does that mean, actually? Since this is a known issue and perhaps a feature that does not reflects what the plugins are capable of, I think that the correct is that the documentation should be updated.

Thanks.
