### ISSUE TITLE
`GLIBC_2.32' error not found after updating to 2023.4.0 on Ubuntu 20.04

### ISSUE THREAD

**Issue by zakyvr** [getinsomnia/insomnia#6133]
### Expected Behavior

When running `insomnia` I expect the application to start and for the main window to be displayed.

### Actual Behavior

The application does not display the main window. Instead, the following error is shown in the terminal:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.vHhMbC)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
`````

### Reproduction Steps

1. Install Insomnia 2022.3 on Ubuntu 20.04 using `dpkg`
2. Download Insomnia to 2023.4.0 `.deb` package from the website
3. Update to Insomnia to 2023.4.0 using `dpkg`
4. Start insomnia from the Gnome shell or a terminal using `insomnia`
5. Notice the error and that the main window does not display

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.4.0

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### Installation method

Download `.deb` package and install with `dpkg`

### Last Known Working Insomnia version

2023.2.2

**Comment by jackkav** [comment]
Our github actions end to end tests are working on ubuntu 22.04.2 perhaps an upgrade could work for you.

**Comment by pauloteixeira01** [comment]
I am with the same problem.

**Comment by AntonKrechetov** [comment]
I have the same issue with the fresh installation of 2023.4.0 on Ubuntu 20.04.

**Comment by jackkav** [comment]
Does latest vscode work on Ubuntu 20.04?

**Comment by long76** [comment]
Appimage has the same error

**Comment by jackkav** [comment]
> From your statement that you have GLIBC_2.31 currently available, it seems you are using Ubuntu 20.04. To get GLIBC_2.32 you would need to use Ubuntu 20.10 or another operating system that offers that version. Trying to upgrade glibc on your existing system will likely lead to many problems.

https://unix.stackexchange.com/questions/628021/glibc-2-32-not-found

**Comment by smk762** [comment]
> > From your statement that you have GLIBC_2.31 currently available, it seems you are using Ubuntu 20.04. To get GLIBC_2.32 you would need to use Ubuntu 20.10 or another operating system that offers that version. Trying to upgrade glibc on your existing system will likely lead to many problems.
> 
> https://unix.stackexchange.com/questions/628021/glibc-2-32-not-found

Unless you need it to build, if you change your CI/CD workflows to build in Ubuntu 20, it will create builds that work in both 20 and 22

**Comment by jackkav** [comment]
Alternatively you could clone the repo and run
```
npm install
npm run app-package
```

**Comment by WesternGun** [comment]
Sorry but if I need to keep working on my older Ubuntu OS, is there some older release of Insomnia using previous versions of GLIBC? I see a lot of versions on https://github.com/Kong/insomnia/releases but not sure which is the last version of this usage of new version of GLIBC, and upgrading to 20 or 22 for one application to work is not feasible in my case and maybe it's not for others neither. I am still on 18.

**Comment by Firiks** [comment]
I have similar issue with flatpak package when using Ubuntu 22.04.3 

```A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /run/user/1000/app/rest.insomnia.Insomnia/.org.chromium.Chromium.KftYCz)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/main/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
```

**Comment by Jictyvoo** [comment]
> I have similar issue with flatpak package when using Ubuntu 22.04.3
> 

Same problem here with Flatpak

**Comment by dgasper** [comment]
Same issue with Flatpak version 2023.5.7 on Ubuntu 22.04.
Version 2023.1.0 starts as expected

**Comment by WesternGun** [comment]
> Same issue with Flatpak version 2023.5.7 on Ubuntu 22.04. Version 2023.1.0 starts as expected

Thanks! Confirmed, this version starts now. Another day saved by random stranger on Github. https://github.com/Kong/insomnia/releases/tag/core%402023.1.0

**Comment by HeitorMC** [comment]
Same issue with flatpak version 2023.5.7 on popos 22.04. :(

**Comment by austinwilcox** [comment]
I'm experiencing this issue now on Ubuntu 20.04.6 LTS, and using the version specified by @dgasper and link from @WesternGun fixed the issue for me. I'm fine running the older version of Insomnia, just as long as it works.

**Comment by assertnotnull** [comment]
Version 3.0 works but yeah upgrading an OS is not a solution (in my case latest Zorin OS is based on Ubuntu 20.04)

**Comment by raf-eteg** [comment]
To view all versions: 
`apt-cache showpkg insomnia`

The last without error: 2023.3.0, then:
`sudo apt install insomnia=2023.3.0`

**Comment by muotaz** [comment]
> To view all versions: `apt-cache showpkg insomnia`
> 
> The last without error: 2023.3.0, then: `sudo apt install insomnia=2023.3.0`

Thanks alot, this solved it.

**Comment by mequq** [comment]
Same on Debian 11

**Comment by raf-eteg** [comment]
> To view all versions: `apt-cache showpkg insomnia`
> 
> The last without error: 2023.3.0, then: `sudo apt install insomnia=2023.3.0`

To no longer update, do:
`sudo apt-mark hold insomnia`

**Comment by evoluketion** [comment]
Why is this closed? It is not resolved and very much present. Changing an operating system version or only using an older application version is hardly a good solution...

**Comment by hgc2002** [comment]
I could install 2.32 with https://askubuntu.com/questions/1345342/how-to-install-glibc-2-32-when-i-already-have-glibc2-31 but insomnia didn't work.

this worked as a charm!!!
sudo apt install insomnia=2023.3.0

**Comment by alagane** [comment]
> Why is this closed? It is not resolved and very much present. Changing an operating system version or only using an older application version is hardly a good solution...

This

**Comment by B3QL** [comment]
The error is still present on Ubuntu 20.04.6

**Comment by dimonomid** [comment]
As others have mentioned, the issue is not solved, so this should not be closed. @jackkav tagging you since you marked it as closed; any chance we can reopen it? Ubuntu 20.04 is supported until April 2025, and so until that date, suggesting to upgrade the OS or to install an older version of Insomnia is **not** a solution.

**Comment by diegofsousa** [comment]
Hey guys. I am facing this problem too.any update on?

**Comment by vcschapp** [comment]
> I'm experiencing this issue now on Ubuntu 20.04.6 LTS, and using the version specified by @dgasper and link from @WesternGun fixed the issue for me. I'm fine running the older version of Insomnia, just as long as it works.

Me too. Per @dgasper I installed 2023.1.0 from https://github.com/Kong/insomnia/releases/tag/core%402023.1.0 and it's working fine now on Ubuntu 20.04.

**Comment by xhit** [comment]
> To view all versions: `apt-cache showpkg insomnia`
> 
> The last without error: 2023.3.0, then: `sudo apt install insomnia=2023.3.0`

fixed with this, a shame this is totally ignored for devs on ubuntu (majority).
