### ISSUE TITLE
Bug with Client Certificate Version Insomnia.Core-2023.4.0.deb

### ISSUE THREAD

**Issue by lzferreira** [getinsomnia/insomnia#6145]
### Expected Behavior

I was working with the version Insomnia.Core-2023.2.2.deb with Client Certificate and everything work fine. 

### Actual Behavior

But after I updated it to Insomnia.Core-2023.4.0.deb, the results from my requests with Client Certificate is the message: "Error: Problem with the local SSL certificate"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.2.2

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu

### Installation method

sudo dpkg -i Insomnia.Core-2023.4.0.deb

### Last Known Working Insomnia version

2021.4.0

**Comment by alan-m-thomas** [comment]
g yditd

**Comment by BenMorel** [comment]
Same issue here with `2023.4.0.deb`. It's working on `2023.3.0`.

**Comment by grandsirefr** [comment]
append to me a revert version to 2023.3 resolve it

**Comment by ronanmockett** [comment]
+1 Also an issue with the .dmg release.
