### ISSUE TITLE
A JavaScript error occurred in the main process 

### ISSUE THREAD

**Issue by zaloguj12** [getinsomnia/insomnia#6156]
### Expected Behavior

insomnia to pop up

### Actual Behavior

error saying " A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.Cvyq6L)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/Insomnia/resources/app.asar/node_modules/@getinsomnia/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed "

### Reproduction Steps

1. open terminal
2. write insomnia
3. click enter

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.4.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.6 LTS

### Installation method

from website through software

**Comment by DevangGarg** [comment]
Maybe it supports the latest ubuntu version. The older version of ubuntu may not be compatible.

**Comment by FrancoisCapon** [comment]
Same message, solved by using updated **snap**:
```
$ snap version
snap       2.58+20.04.1
snapd      2.58+20.04.1
series     16
linuxmint  20.1
kernel     5.4.0-96-generic
$ sudo snap install insomnia
........................
$ LANG=C snap list insomnia
Name      Version   Rev  Tracking       Publisher    Notes
insomnia  2023.4.0  204  latest/stable  getinsomnia  -
$ snap run insomnia
........................
```

**Comment by zvalcav** [comment]
Same problem on Debian Bullseye. Downgrading Insomnia to 2023.5.0 didn't help. I've downgraded to Insomnia 2023.3.0 and everything works now.

**Comment by jackkav** [comment]
It appears this is an incompatibility between electron 25 and snap. Perhaps there will be a backwards compatibility change in electron-builder but I wouldn't hold my breath. Update snap or glibc (upgrade the distro) to workaround this issue.

**Comment by batica81** [comment]
> Same problem on Debian Bullseye. Downgrading Insomnia to 2023.5.0 didn't help. I've downgraded to Insomnia 2023.3.0 and everything works now.

Thank you, downgrade solved my issue on Bullseye as well! Don't see how the latest version could possibly work with it.

**Comment by zvalcav** [comment]
> It appears this is an incompatibility between electron 25 and snap. Perhaps there will be a backwards compatibility change in electron-builder but I wouldn't hold my breath. Update snap or glibc (upgrade the distro) to workaround this issue.

I don't even have snap installed. So I suppose I'll have to live with older version for long time. At least before I upgrade which won't be any time soon. Bullseye is still supported release of Debian and Bookworm is too new for me to upgrade to it.

**Comment by terhitormanen** [comment]
Having same problem on Ubuntu 20.04.6 LTS! Tried to install Insomnia 8.0.0. I'm a paying subscriber to Insomnia and this is really, really annoying!

**Comment by ascdi** [comment]
Same Problem with `Insomnia.Core-9.2.0.deb` on `Ubuntu 20.04`
