### ISSUE TITLE
Fonts and rest of interface is too small, at least at 4k screen.

### ISSUE THREAD

**Issue by romanko89** [getinsomnia/insomnia#6165]
### Expected Behavior

I've been using Insomnia without any issues until recently. 

### Actual Behavior

Now I have encountered an issue. When I launch the application, everything appears to be extremely small, including the UI elements, fonts, and blocks. - May it be related to issues with improper scaling on 4k screen? But I've been using Insomnia earlier on that screen resolution and haven't got any issues.

![image](https://github.com/Kong/insomnia/assets/11628801/584dfbde-63b0-486c-ba35-1ad818884133)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.4.0

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.19045 Electron: 23.3.9 Node: 18.12.1 V8: 11.0.226.20-electron.0 Architecture: x64

### Installation method

Download from homepage

**Comment by romanko89** [comment]
Actually zooming-in application helps, but only till next restart. Each time I restart application scale of the app is too small.

**Comment by andreassiegel** [comment]
@romanko89 Did you try configuring the font size in the Insomnia settings?

<img width="944" alt="image" src="https://github.com/Kong/insomnia/assets/13197892/1a91033c-4b0b-4726-a032-ea2209ef86b9">

**Comment by grepusername** [comment]
That maxes out at 24px and is still too small on 4K screens

<img width="1922" alt="image" src="https://github.com/Kong/insomnia/assets/48111513/a85162a8-0204-4e08-a09a-e72bc5c03049">

<img width="1922" alt="image" src="https://github.com/Kong/insomnia/assets/48111513/d1d1dfb8-b07e-4a6d-ac80-90fa89f5534c">

**Comment by arashberlin** [comment]
Have same issues.  I can only use max font size to 24.  I am using a 4K TV as monitor (4096x2160) Scale is to 225%.

How can I increase the font size bigger then 24?


<img width="1392" alt="17-10-2023_10-44-22" src="https://github.com/Kong/insomnia/assets/12381397/92710a60-fbda-4b72-9f9d-0e19d87586e1">

**Comment by romanko89** [comment]
It wasn't only font size - it's the entire application scale so to speak . But lately I haven't experienced the problem, may be it was somehow fixed in newer versions of insomnia, I guess that issue can be closed.
