### ISSUE TITLE
[Improvement] Better OAuth 2.0 redirect handling

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#619]
This issue is a result of the discussion happening on #404 

## Improvement 1 – Also intercept redirects

The current implementation of the auth window only looks at window location changes. So, if the auth form redirects to a URL that then redirects somewhere else, Insomnia will only see the final URL in the chain – the one that ends up getting loaded by the browser window.

It looks like Electron `BrowserWindow` has an [API](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-did-get-redirect-request) that allows inspecting redirects directly.

## Improvement 2 – Option to enable strict `redirect_uri` matching (currently the default)

Because of #396, Insomnia makes sure the redirect URL is prefixed with the `redirect_uri` defined in the OAuth settings. However, this has proved to cause problems for [some users](https://github.com/getinsomnia/insomnia/issues/404#issuecomment-346179486). It's also possible that Improvement 1  will solve this problem instead.

**Comment by Kadrei** [comment]
Is there any timeline/update on this issue as it prevents us from using this REST-Client because we cannot use it with out current OAuth2 Integration as it does not see the token because of the redirect issue.

**Comment by gschier** [comment]
I can't give a definite timeline but I'll try to fix it soon.

@Kadrei Can you describe what exactly is causing the issue for you? I just want to make sure I'm fixing the correct thing.

**Comment by Kadrei** [comment]
As far as I can debug Insomnia does miss a redirect that happens and therefor does not extract the key from the url.

**Comment by gschier** [comment]
Can you include output from View > Toggle DevTools > Console?

**Comment by Kadrei** [comment]
```
[ga] Event Request, Activate, Sidebar
[ga] Google analytics tracking disabled. Not sending
[ga] Non-interactive Notification, Shown, upgrade-support
[ga] Google analytics tracking disabled. Not sending
[oauth2] Loaded "https://<host2>.dev.abcdef.io/oauth2/v1/auth?response_type=code&client_i…session.close%20scopehost.session.create%20scopehost.session.get&state=%2F"
[oauth2] Ignoring URL "https://<host>.dev.abcdef.io/main/#/". Didn't match /https:\/\/<host>\.dev\.abcdef\.io\/auth\/login.*(code=|error=)/i
[oauth2] Ignoring URL "https://gate.dev.abcdef.io/oauth2/v1/auth?response_type=code&redirect_uri=h…ment.*+discovery+&state=%2F". Didn't match /https:\/\/<host>\.dev\.abcdef\.io\/auth\/login.*(code=|error=)/i
```

**Comment by gschier** [comment]
Hmm, I don't see a `code` querystring parameter in either of those URLs that were ignored. At a minimum, this `code` parameter should be present in the final URL. Do you know why this may be?

It's very difficult to figure out what's wrong without knowing the details of your server's authentication flow. Any details you can provide would help a lot.

**Comment by Kadrei** [comment]
Because the url with `code` is not recognized as it is accompanied with a 307 http status code.

**Comment by gschier** [comment]
Got it. So let me know if this is correct (I want to build a test case).

1. Form loads at some authorize URL `http://app.com/auth`
2. User submits form
3. Server validates request and redirects user to `http://app.com/redirect?code=123`
4. Redirect URI then redirects with 307 to `http://app.com/some/other/url`

Since Insomnia never actually loads the URL in step 3, it fails to detect the URL and grab the code.

**Comment by Kadrei** [comment]
Yes, this should be it:

**Comment by unff** [comment]
Just to add another use-case to this fire:

eBay's OAuth 2.0 implementation for their new REST APIs uses a custom redirect_uri that is neither a URI nor optional .  There's no second redirect, it just doesn't match the expected values.  

Pretty sure Improvement #1 will cover this use case, but thought I'd chime in all the same.  Fiddler screenshot attached.
![sshot0320](https://user-images.githubusercontent.com/7915543/36325527-117ec0f0-1326-11e8-8be9-86cdad996a01.png)

**Comment by bjeanes** [comment]
Weighing in here as also affected.

In my case, I think there is the OAuth2 provider performs an internal redirect before redirecting back to the application callback. Then the callback URL performs its own token fetching and redirects into a logged in state.

The logs for my interaction only have the following two noteworthy lines:

```
[oauth2] Loaded "hhttps://test-account.cochrane.org/oauth2/auth?response_type=code&client_id=covidence&redirect_uri=https%3A%2F%2Fstaging.covidence.org%2Foauth%2Fcallback&scope=person%20document"
bundle.js:45462 [oauth2] Ignoring URL "https://staging.covidence.org/reviews/active". Didn't match /https:\/\/staging\.covidence\.org\/oauth\/callback.*(code=)/i
````

The `/reviews/active` path is several redirects after a successful login, during a normal authentication flow.

**Comment by swone1990** [comment]
Any news on this? Because i am still facing this issue

**Comment by lenmarknate** [comment]
I also have this issue, particularly with the eBay API as mentioned above.

@unff, I don't know if it's still relevant to you (and anyone else who runs into this for eBay) but I worked around it for eBay by adding the `redirect_uri` parameter directly to the Authorization URL and Access Token URL (with eBay's special RuName value), and then left the Redirect URL in Insomnia blank. With the Redirect URL in Insomnia blank, it seems to capture all redirects and therefore gets the codes.
