### ISSUE TITLE
Request collections always ordered by "Last Modified"

### ISSUE THREAD

**Issue by alexdev430** [getinsomnia/insomnia#6202]
### Expected Behavior

After navigating back from a collection request, I should see the list of collection requests ordered by the same attribute I selected on the top right selector
![image](https://github.com/Kong/insomnia/assets/123114716/31d345e4-acab-4f84-987e-f60b43ee4741)

### Actual Behavior

After navigating back from a collection request, I always see the list of collection requests ordered by "Last Modified"

### Reproduction Steps

1. Go to a collection request list where there is more than one collection request
2. Click on top right button to order by (for example) "Name Ascending (A-Z)"
3. Click on any collection request to explore it
4. Go back to the list of collection requests by clicking on the breadcrumbs on the top center link
5. Notice the collection request list is order by "Last Modified"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.4.0

### What operating system are you using?

Windows

### Operating System Version

Windows Server 2017

### Installation method

insomnia.rest

### Last Known Working Insomnia version

2023.4.0

**Comment by alexdev430** [comment]
@jackkav when you have time could check the PR #6229  ?

**Comment by yogeshnikam671** [comment]
@gatzjames any update over here ?

**Comment by jackkav** [comment]
Thanks for the PR @alexdev430 we are simplifying the filtering and sort functionality in the PR tagged above. Aiming to fix all the drag and drop issues too. The sort keys are still there in the data so previously defined ordering will return once the above PR is in. Thanks for your help and patience.

**Comment by yogeshnikam671** [comment]
Thanks for the update @jackkav
