### ISSUE TITLE
[Bug] Render Failure: "toString()" failed

### ISSUE THREAD

**Issue by lifewcody** [getinsomnia/insomnia#621]
- Insomnia Version: 5.12.0-beta.2
- Operating System: Windows 10 Pro 64bit

## Details

When downloading a large file, it tries to convert it to a string. If I understand it correctly, it now works by streaming to the filesystem instead of to RAM. You should be storing this file temporarily for each request to then be viewed (if it isn't already doing so) instead of trying to toString() everything.

For example: I am testing an ISO with the header set to: application/x-iso9660-image . When it is done, it says "Reponse body is over 5MB hidden to prevent unresponsiveness" [Show Response] and [Always Show] are the options. When clicking [Show Response] it errors saying "Render Failure: "toString()" failed. There should be an option to view the file instead.

An error is shown:
``` javascript
react-dom.production.min.js:163 Error: "toString()" failed
    at Buffer.toString (buffer.js:503)
    at InternalDecoder.utf8Text [as text] (string_decoder.js:180)
    at InternalDecoder.StringDecoder.write (string_decoder.js:64)
    at StripBOMWrapper.write (C:\Users\lifew\AppData\Local\insomnia\app-5.12.0-beta2\resources\app.asar\node_modules\iconv-lite\l…:35)
    at Object.decode (C:\Users\lifew\AppData\Local\insomnia\app-5.12.0-beta2\resources\app.asar\node_modules\iconv-lite\l…:42)
    at ResponseViewer.render (response-viewer.js:285)
    at h (react-dom.production.min.js:129)
    at beginWork (react-dom.production.min.js:133)
    at d (react-dom.production.min.js:160)
    at f (react-dom.production.min.js:160)
k @ react-dom.production.min.js:163
g @ react-dom.production.min.js:161
z @ react-dom.production.min.js:167
I @ react-dom.production.min.js:167
batchedUpdates @ react-dom.production.min.js:170
tc @ react-dom.production.min.js:53
rd @ react-dom.production.min.js:70
```

**Comment by gschier** [comment]
The reason for the `toString()` in that case is because Insomnia does not know how to show `application/x-iso9660-image` files. When it doesn't know, the default is to show the raw bytes as a string. This is definitely not the best option for large binary files. 

Do you have a sample file that I can test with? All the binary files I've tried don't throw the same error.

**Comment by lifewcody** [comment]
@gschier Since Insomnia doesn't know how to show it, could there be an option to view the file downloaded. Example: If I download a .docx file, Insomnia shows the toString version, instead could there be an 'open file location'

The file I'm using is the same that's been producing all these errors. (https://my.vmware.com/en/group/vmware/evalcenter?p=free-esxi6) It's an ESXi ISO. I chose it because it's relatively big and I'm testing a REST file storage system.

**Comment by gschier** [comment]
Hmm, it seems that I need to be logged in to view that link. Anyway, I'm pretty sure that #625 fixes this issue. I just pushed a new beta release. Can you try it out?

Also, I added an easier-to-access button to save large responses in #625 but there was also already another (slightly hidden) method.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/587576/33190441-abbd220c-d0a4-11e7-9f5c-79251023fae2.png">

**Comment by gschier** [comment]
Going to close this one as it's handled a lot better now in 5.12.0
