### ISSUE TITLE
File as body not attached the selected file

### ISSUE THREAD

**Issue by garulovilla** [getinsomnia/insomnia#6228]
### Expected Behavior

When select the option File as a body, the selected filename must be showed is the field "Selected file", the button "Reset File" must be enabled and when de request is sent, the selected file must be attached.

### Actual Behavior

The field "Selected file" not change, the button "Reset File" is not enabled and when the request is sent the file is not attached.

![insomnia-file-as-body](https://github.com/Kong/insomnia/assets/4468146/a6dbfad2-f7b3-473d-a6c0-d63c00c3cabe)

### Reproduction Steps

1. New request
2. In body, select Binary File.
3. Select Choose File
4. Select file

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The headers are updated according to the selected file

### Insomnia Version

2023.5.0-beta.9

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19045

### Installation method

Github Insomnia 

### Last Known Working Insomnia version

2023.4.0

**Comment by jamesatmarble** [comment]
Reproduced in 2023.5.2. Including binary files as parts in a multipart/form-data request still works.

Version: Insomnia 2023.5.2
Build date: 8/15/2023
OS: Windows_NT x64 10.0.19045
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

**Comment by garulovilla** [comment]
Yeah in multipart/form-data works great, the error is when the is selected as a File: Body > Binary File.

![image](https://github.com/Kong/insomnia/assets/4468146/92ea59c4-365e-4e9c-9c40-31d12d6e87c2)

**Comment by pavelToman** [comment]
Have same issue on Ubuntu 22.04.3 LTS
+ new problem - I can not move HTTP request items in left menu -

**Comment by bolacha** [comment]
Hey guys< i am experienceing the same behavior on my Macbook Pro 14 M2 PRO : 

Version: Insomnia 2023.5.2
Build date: 8/15/2023
OS: Darwin arm64 22.6.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: arm64

No errors shows up in the developer's console inside insomnia.

Tried using the version download from the website and even the same for the using brew cask.

**Comment by nbrosse** [comment]
Same here on MAC

**Comment by bolacha** [comment]
> Hey guys< i am experienceing the same behavior on my Macbook Pro 14 M2 PRO :
> 
> Version: Insomnia 2023.5.2 Build date: 8/15/2023 OS: Darwin arm64 22.6.0 Electron: 25.2.0 Node: 18.15.0 Node ABI: 116 V8: 11.4.183.23-electron.0 Architecture: arm64
> 
> No errors shows up in the developer's console inside insomnia.
> 
> Tried using the version download from the website and even the same for the using brew cask.

I got it working on my machine by running the actual code : 

<img width="576" alt="image" src="https://github.com/Kong/insomnia/assets/2929174/52836e91-0e29-42be-b6f9-c8b21a4b819b">

I cloned the repo and just run "npm run dev" and it works.

**Comment by bolacha** [comment]
It seens it got fixed on the latest version now : 

<img width="640" alt="image" src="https://github.com/Kong/insomnia/assets/2929174/98bee404-e677-4bb8-8f70-7c3920ada11a">

This is using the latest release : 

https://github.com/Kong/insomnia/releases

**Comment by jamesatmarble** [comment]
Thanks @jackkav and @bolacha! Indeed fixed in 2023.5.3

**Comment by bolacha** [comment]
@garulovilla  Check it above. It's probably fixed.

**Comment by garulovilla** [comment]
Thanks! 😄 With the version 2023.5.3 the option work like a charm!
