### ISSUE TITLE
[Feature Request] In multipart form an ability to set content-type for each part - application/json etc.

### ISSUE THREAD

**Issue by janpridal** [getinsomnia/insomnia#623]
## [Feature Request] In multipart form an ability set content-type for each part - application/json etc.

The REST endpoint is accepting multipart/form-data but expects that one part with specific name has a content-type set to application/json. This is currently not possible to achieve in Insomnia client, where it's possible to select only text, text (multi-line) or file part type.

- Insomnia Version: latest as of today, v5.11.7
- Operating System: Windows 10

## Details
Server expects following request:

POST http://localhost:9998/v1/recipes/upload
accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
connection: keep-alive
content-length: 1917
content-type: multipart/form-data;boundary=Boundary_1_1757933443_1511447510179
host: localhost:9998
mime-version: 1.0
user-agent: Jersey/2.23.1 (HttpUrlConnection 1.8.0_144)
--Boundary_1_1757933443_1511447510179
**Content-Type: application/json**
Content-Disposition: form-data; name="recipe"

{"links":[],"id":null,"name":"cool-recipe-900"}
--Boundary_1_1757933443_1511447510179
Content-Type: application/octet-stream
Content-Disposition: form-data; filename="sample.recipe"; modification-date="Thu, 23 Nov 2017 14:31:19 GMT"; size=1297; name="file"

{
 ...
}

--Boundary_1_1757933443_1511447510179--

**Comment by joethejones** [comment]
+1, I'm not sure if this is already possible, but I'd like the ability to do this as I'm struggling with exactly the same issue.

**Comment by o-alexandrov** [comment]
Any news?

**Comment by gschier** [comment]
No news yet but going to mark this as Accepted, as I think it's a good fit for Insomnia.

**Comment by oliverjanik** [comment]
Has this been implemented? Why is the issue closed?

**Comment by ash-eng-spin** [comment]
Has this ever been updated? I'm on Insomnia 8.6.0 and do not see the ability for the user to edit content-types for the parts in a multi-part request. This is a show stopper for us.
