### ISSUE TITLE
[Feature Request] Control over insomnia in plugins

### ISSUE THREAD

**Issue by fjwillemsen** [getinsomnia/insomnia#624]
Allow plugins to control insomnia functions for more versatility.

## Details

In the current situation, plugins have little power. Basically all they can do is return a string or modify requests, which is not nearly enough to satisfy the potential insomnia plugins hold.
My proposal to take insomnia plugins to the next level is as follows:

Allow plugins to have (limited) control over built-in insomnia functions.
Since plugins can be written in Node.js, all that's needed to make them a lot more powerful is a way to control insomnia functions.

Top priority features:
 - query request database (for example: `get_profile = module.request("getProfile")`)
 - executing requests (for example: `module.execute(get_profile)`)
 - reading responses (for example: `module.read(getProfile).data.user.name`)
 - trigger plugin execution (perhaps in a central location, like a separate folder for plugins in every environment)

A use case for a plugin utilizing this would be semi-automated testing, which would work as follows:
 - file containing tests for requests in compatible syntax is taken as input by the plugin
 - requests are retrieved in insomnia (query request)
 - requests are executed (executing)
 - results are verified and result in success or fail per test (reading responses)
 - XML-file containing test results is resulting output of the plugin

**Comment by gschier** [comment]
Thanks for posting this @fjwillemsen. We already talked on Slack about this so I don't have any questions but all of these seem like reasonable and beneficial functions for the plugins API 👍 

I want to do a big update to the plugins system soon so I'll try to include these in that (barring any unforeseen problems).
