### ISSUE TITLE
Rename Name Environment does't work

### ISSUE THREAD

**Issue by fedeValtira** [getinsomnia/insomnia#6253]
### Expected Behavior

I can't rename Environment, I have many duplicates called "New Environment" and none of them can be rename.

### Actual Behavior

It should allow me to rename environments

### Reproduction Steps

Go to any project
Check environment list
try to rename, and nothing happens no UI to edit the name.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.4.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.2 LTS

### Installation method

Manually with file Insomnia.Core-2023.4.0.deb

### Last Known Working Insomnia version

2023.4.0

**Comment by fedeValtira** [comment]
![image](https://github.com/Kong/insomnia/assets/75752158/0fbf732e-c1b0-4876-a741-9f67818eb25c)

**Comment by filfreire** [comment]
@fedeValtira if you double click on `New Environment` title, does it let you rename?

![image](https://github.com/Kong/insomnia/assets/11976836/637f3340-1b13-489b-abad-4198a73bca7a)

**Comment by fedeValtira** [comment]
yep I can, so why is there and not in the left side as endpoint we rename like that.
