### ISSUE TITLE
Could not generate cURL - strict mode: unknown keyword: "afterRequest" error.

### ISSUE THREAD

**Issue by smheaton** [getinsomnia/insomnia#6279]
### Expected Behavior

I should be able to generate a curl statement or a code snippet from a request.

### Actual Behavior

Two request options no longer work for me in 2023.5.0.  If I try the "Generate Code" option:

![image](https://github.com/Kong/insomnia/assets/4925707/81b5eb33-af81-4bf3-8ad5-f21bb3eb8604)

...the dialog that appears won't let me change the dropdown options:

![image](https://github.com/Kong/insomnia/assets/4925707/d0f12788-b05f-483b-af10-84e32d86d03c)

If I try the "Copy as curl" option in the same menu for a request, I get an error dialog:

![image](https://github.com/Kong/insomnia/assets/4925707/7414dfbf-08d6-4673-b82e-97cbed3ad6b1)

### Reproduction Steps

1. Create a New GET Request for "https://www.google.com."
2. In the left pane, click on the down arrow next to the request's name (e.g. "New Request")
3. Select "Copy as curl" in the menu that appears and select "Click to confirm."

Result: A dialog appears that says "Could not generate cURL" with a message below it that says, "strict mode: unknown keyword: "afterRequest""

![image](https://github.com/Kong/insomnia/assets/4925707/6ac5b822-e0c9-44f6-9fe4-5f7960d4d713)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I rolled back using the Insomnia.Core-2023.3.0 executable and did not see either problem anymore.

### Insomnia Version

2023.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 19045.3324 and Windows 11 Enterprise 22621.1992

### Installation method

Automatic Upgrade form Previous Version

### Last Known Working Insomnia version

2023.3.0

**Comment by ignaciospeicys** [comment]
I am experiencing the exact same issue since an hour ago or less.

Alongside this, after the recent automatic upgrade, I've observed a problem where modifications to a request aren't being saved. Specifically, after editing a request, if I navigate to view a different request and then return to the previously modified request, all the changes seem to have been discarded.

**Comment by smheaton** [comment]
Thanks for confirming what I see, @ignaciospeicys !  I also have seen behaviors where changes to requests haven't been getting saved, but I can't repro it consistently (i.e. sometimes it seems to work okay but I have lost a few too).  Hopefully they can get our issues worked out.

**Comment by jackkav** [comment]
@smheaton Thanks for the report, seems like it could be an issue with the httpsnippet and ajv dependency, and a difference between the local dev and packaged release. Will investigate further and get a minor bump out as soon as we can. (I suspect its a bundling issue)

@ignaciospeicys Could you provide more information about the particular fields that didn't persist. We recently moved our state management mechanism from redux to remix-run so I'm very curious if we missed anything in the migration.

**Comment by vhd-luke** [comment]
Also having this issue when trying to Copy as cURL

**Comment by jackkav** [comment]
This issue is fixed in 2023.5.2 which will be available shortly.

**Comment by smheaton** [comment]
Upgraded to 2023.5.2 and both features work great for me now.  Thanks for the quick turnaround, @jackkav !
