### ISSUE TITLE
Requests cannot be filtered

### ISSUE THREAD

**Issue by DanielRouxSA** [getinsomnia/insomnia#6288]
### Expected Behavior

When typing something into the Filter text box above the request list, the visible requests should be filtered by the entered text.

### Actual Behavior

The request list is not filtered by the entered text.

### Reproduction Steps

1. Go to a collection of requests
2. Type something into the Filter text box above the request list.
3. The displayed requests are not filtered by the entered text.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2, macOS 13.5

### Installation method

Downloaded from insomnia.net

**Comment by zImPatrick** [comment]
I also have the same issue on 2023.5.2 (using Windows 10 22H2)

**Comment by rmiyoussef** [comment]
New version so slow

**Comment by tsptylertech** [comment]
I'm having the same problem.  If you type something in the filter box for a collection, Insomnia does not filter the collection.

**Comment by alrashwa** [comment]
Same issue here, was working till a few minutes ago, 2023.5.2 version

**Comment by arafth** [comment]
Same issue. Version: 202.5.2
collapse not working properly. 
Can't rearrange directories. 

OS: Windows
OS Build:  22621.2134

Every update broke something. 
And the git is very much more unstable than last year. 
Very much dissatisfied with insomnia nowadays.

**Comment by CaiqueCastro07** [comment]
same issue, mac os mojave. Please admin, revert all these updates or allows us to download previous versions of the software

**Comment by marchpane** [comment]
+1

**Comment by Caskman** [comment]
@CaiqueCastro07 you can download the previous version here
https://github.com/Kong/insomnia/releases/tag/core%402023.4.0

**Comment by vcruzmj** [comment]
Same here in Linux:
Version Info:
Version: Insomnia 2023.5.3
Build date: 8/16/2023
OS: Linux x64 6.2.0-26-generic
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

**Comment by newfunk** [comment]
Same here:
Version: Insomnia 2023.5.4
Build date: 18-8-2023
OS: Windows_NT x64 10.0.19045
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

**Comment by mathieu-lemay** [comment]
> New version so slow

I have noticed that too, when renaming a request for example. I type the new name, press enter, old name shows up, then new name shows up 2-3 seconds later.

**Comment by DennisGoermannMD** [comment]
same here, thank you

**Comment by juan0101** [comment]
Same Here

OS: Windows_NT
Version: 2023.5.4

**Comment by Eduard-Batiushchenko** [comment]
Same here
OS: macOS Ventura 13.4.1

For those who really struggle, revert insomnia to version - 2023.4.0 (filters work correctly inside collections)

**Comment by stmcox** [comment]
filter still not working even in 2023.5.5, just highlighting the portion of a request name that matches is not useful when you have 40 or 50 or more requests

**Comment by stadja** [comment]
Damned ... it worked on friday and now it doesn't anymore (monday).
It's crucial for me to be able to filter those requests :/

**Comment by kjaquier** [comment]
Same here on Ubuntu 21.04 right after the update notification. It also became very slow on every click / keyboard input. It was fine before that.

Version: Insomnia 2023.5.5
Build date: 8/18/2023
OS: Linux x64 5.11.0-49-generic
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

**Comment by marchpane** [comment]
Hello!

This is, unfortunately, not resolved and I'm not sure why this here got closed with the reference to #6323 

Also, https://github.com/Kong/insomnia/issues/6284 is still an issue and not resolved. Why got it closed, I'm confused?! Anyone has an idea? 

I still can't filter or reoder my requests. 😢

**Comment by andrepazleal** [comment]
Version: Insomnia 2023.5.8

Still trying to filter the request again and I'm not able similar to the previous version before 5.8.

**Comment by andrepazleal** [comment]
I've noticed that if I use without spaces Insominia in version 5.8 will correcly show only that request:
<img width="313" alt="image" src="https://github.com/Kong/insomnia/assets/6593862/7e88d60a-4fd4-448a-bc6d-f5e6fb249878">

And without the space brings everything:
<img width="285" alt="image" src="https://github.com/Kong/insomnia/assets/6593862/4b39418c-913c-4a90-a0e5-3787c3da63e7">
