### ISSUE TITLE
Certificate checkbox removes certificate from list

### ISSUE THREAD

**Issue by AdiDil** [getinsomnia/insomnia#6292]
### Expected Behavior

Clicking a checkbox in the Client Certificates list should check/uncheck a certificate

### Actual Behavior

Clicking a checkbox now removes the certificate from the list with no confirmation!

### Reproduction Steps

1. Go to Settings
2. Select Client Certificates
3. Click the checkbox of any existing certificate
4. Notice that the certificate is immediately removed

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 19044.3208

### Installation method

Download

### Last Known Working Insomnia version

2023.5.0?

**Comment by jackkav** [comment]
Thanks for the catch!
