### ISSUE TITLE
Can't open insomnia

### ISSUE THREAD

**Issue by VOS123** [getinsomnia/insomnia#6293]
### Expected Behavior

The expected behaviour is that I can open it.

### Actual Behavior

I get the next error: Error: Request not found at ii (file:///C:/Users/jdvos/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:17:107223) at Module.me (file:///C:/Users/jdvos/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/request-d9b72a97.js:1:2036) at async Sg (file:///C:/Users/jdvos/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:31:3691) at async Promise.all (index 3) at async oe (file:///C:/Users/jdvos/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:30:21932) at async qe (file:///C:/Users/jdvos/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:30:16866) at async we (file:///C:/Users/jdvos/AppData/Local/insomnia/app-2023.5.2/resources/app.asar/index-205ae130.js:30:15043)

### Reproduction Steps

1. Try to open insomnia
2. Notice the error message
3. The screen doesn't continue
4. rebooting & reloading didn't help

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise

### Installation method

downloaded from insomnia.rest

**Comment by amadeogallardo** [comment]
I'm also getting this since the latest upgrade: Error: Request not found at ii

**Comment by nettnikl** [comment]
@jackkav Wow, quick fix! Could you tag a new version with your change in them? (it's seems quite critical for users where it appears)

**Comment by jackkav** [comment]
Its in 2023.5.3 could you please confirm?

**Comment by amadeogallardo** [comment]
I can confirm that this is fixed for me. Thanks!
