### ISSUE TITLE
Git clone existing Insomnia collection from repository fails

### ISSUE THREAD

**Issue by joaofhenriques** [getinsomnia/insomnia#6304]
### Expected Behavior

Clone existing collection with "git clone" functionality

### Actual Behavior

Insomania crashes with follwoing error

![image](https://github.com/Kong/insomnia/assets/94627478/c7505baf-0219-4755-a2c6-bda51c077e4c)

After clicking reload app, the collection is shown as a Document:

![image](https://github.com/Kong/insomnia/assets/94627478/57c2d60c-2d43-417a-bc57-7044f011cdba)

Entering the document, results in the same crash

### Reproduction Steps

1. Create a collection
2. Create a request
3. Git Sync collection (commit and push)
4. Validate in git that .insomnia folder was created and collection is inside
5. Delete collection
6. Git Clone repository used before
7. Insomnia crashes

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

- There's a closed issue https://github.com/Kong/insomnia/issues/3235 which is already from 2021, don't know if it is related
- Used github integration

### Insomnia Version

2023.5.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2 22621.2134

### Installation method

insomnia.rest

### Last Known Working Insomnia version

none

**Comment by filfreire** [comment]
@joaofhenriques thanks for reporting this. We will try to fix this in an upcoming patch release, and provide an update here as soon as possible.
