### ISSUE TITLE
"Select Requests to Export" dialog empty when trying to export from the project screen

### ISSUE THREAD

**Issue by mnemyx** [getinsomnia/insomnia#6306]
### Expected Behavior

I would expect the "Select Requests to Export" to show the same way it does regardless of whether or not I use the Preferences dialog or the Projects screen to export a collection.

### Actual Behavior

Using this way to to export:
![image](https://github.com/Kong/insomnia/assets/770706/27462736-6acf-41fb-9331-17b9f75bb66a)

results in:
![image](https://github.com/Kong/insomnia/assets/770706/37d7bf9a-4996-4de2-a1c5-77c164144152)

**No errors or stacktrace are present**

### Reproduction Steps

1. Go to project screen
2. Click '...' for a collection
3. Click 'Export'

Screenshots provided in *actual behavior* section

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

If I'm in the collection already though and navigate to Application > Preferences 
![image](https://github.com/Kong/insomnia/assets/770706/f41b6c87-3dea-4ed7-ae3f-fd32bb8c1430)

Then Data > Export Data > Export the "..." Collection
![image](https://github.com/Kong/insomnia/assets/770706/dc9b545d-2efb-460f-8f2a-d43803819392)

I actually get the list of requests that would've been blank when opening this dialog from the projects screen
![image](https://github.com/Kong/insomnia/assets/770706/653d9f8f-d210-40a5-945b-99a9b681f4e9)

For the record, importing data seems to be working well.

### Insomnia Version

2023.5.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise Version 21H2

### Installation method

Download from insomnia.rest

**Comment by jackkav** [comment]
Thanks again for the clear issue description, will have this sorted soon
