### ISSUE TITLE
Variables no longer show value when "Show variable source and value" is checked in options

### ISSUE THREAD

**Issue by jn-novasol** [getinsomnia/insomnia#6309]
### Expected Behavior

Before I updated to v2023.5.3 it would show the value rather than the variable name when option "Show variable source and value" is checked. Now it don't.

### Actual Behavior

Show the variable name, not the value.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.3

### What operating system are you using?

Other Linux

### Operating System Version

v2023.5.3

### Installation method

aur package for archlinux

**Comment by filfreire** [comment]
@jn-novasol this should be fixed in the [latest patch release 2023.5.4](https://github.com/Kong/insomnia/releases/tag/core%402023.5.4)
