### ISSUE TITLE
"Paste cURL to input -> parse and fill all other options" was great feature, why it removed?

### ISSUE THREAD

**Issue by ysm-dev** [getinsomnia/insomnia#6310]
### Expected Behavior

Why the `+ From cURL` Button instead of just pasting curl string to input?

### Actual Behavior

Paste cURL to input no longer parsed anymore

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.3

### What operating system are you using?

macOS

### Operating System Version

MacBook M2 Max (MacOS Ventura 13.5

### Installation method

homebrew

**Comment by jackkav** [comment]
We are trying to improve the discoverability of the paste curl feature. The old method was a little too implicit, and had no way to provide validation feedback if there was an issue with parsing. We are planning to add a modal for this validation.

**Comment by ysm-dev** [comment]
Related: #6338
