### ISSUE TITLE
Regression - Pasted cURL on url fields does not parse

### ISSUE THREAD

**Issue by Scoppio** [getinsomnia/insomnia#6317]
### Expected Behavior

Pasting a curl (single line or multline) in the URL field should be parsed as a request.

### Actual Behavior

Since release version 2023.5.3 the curl parsing on the URL field stoped working, the full curl is left there and never parsed.

### Reproduction Steps

1 - grab a curl:

```
curl 'https://http.cat/images/200.jpg' \
    -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0' -H 'Accept: image/avif,image/webp,*/*' -H 'Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: https://http.cat/'
```
2 - paste it in the request url field on the Insomnia UI

3 - wait for nothing to happen

4 - nothing happens

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.3

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.3.1

### Installation method

downloaded dmg

### Last Known Working Insomnia version

2023.4.0

**Comment by jackkav** [comment]
We are trying to improve the discoverability of the paste curl feature. The old method was a little too implicit, and had no way to provide validation feedback if there was an issue with parsing. We are planning to add a modal for this validation in the next pass.

**Comment by Scoppio** [comment]
You simply REMOVED the functionality without telling anyone because yoiu plan to do something in the future with it? Why would you do that?! I will have to stay locked to an older version forever?
Also, I deeply appreciate not having absolutelly any modal or validation for anything because all my cases 100% of the time work (well the did work before the update, and they are working back now because I rolled back to the previous version that had it).

I stoped my postman subscription exclusivelly because Insomnia have this feature where there is nothing betwen me and adding the curl as a request on it.
