### ISSUE TITLE
[Bug] - Manage Environments not letting me edit existing environments

### ISSUE THREAD

**Issue by Fyb3roptik** [getinsomnia/insomnia#632]
- Insomnia Version: 5.11.7.1431
- Operating System: Macos High Sierra 10.13.1 (17B48)

## Details

I have 4 environments. When I click on Manage Environments all I get now is Base Environment, Sub Environments as if there are none. Please help!!!!

**Comment by gschier** [comment]
See this https://github.com/getinsomnia/insomnia/issues/591#issuecomment-346515327

**Comment by gschier** [comment]
That should work for you, but I'm going to try getting an official release out early this week.

**Comment by gschier** [comment]
This fix is now live in the latest stable release 5.12.0
