### ISSUE TITLE
cUrl not working

### ISSUE THREAD

**Issue by shifoc** [getinsomnia/insomnia#6321]
### Expected Behavior

pasting a curl should fill the corresponding information

### Actual Behavior

pasting a curl is no longer filling the info

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.3

### What operating system are you using?

Windows

### Operating System Version

windows 11

### Installation method

insomnia.rest

**Comment by filfreire** [comment]
@shifoc you can import curl from the new request tab now, see https://github.com/Kong/insomnia/pull/6295 for more context

![image](https://github.com/Kong/insomnia/assets/11976836/55707c21-39a1-4a45-b2a4-4c3f9d84d0e1)
