### ISSUE TITLE
Terms of Service Agreement are no longer correct

### ISSUE THREAD

**Issue by DevTeamDbVertrieb** [getinsomnia/insomnia#6324]
### Expected Behavior

"Send Anonymous Usage Statistic" is off by default

### Actual Behavior

Source: https://insomnia.rest/terms 

In "Application usage information" it is explained that tracking is optional and turned off. With the ticket INS-2697 the behavior was changed

![grafik](https://github.com/Kong/insomnia/assets/73105786/de0767e3-2675-4384-9ec6-d0e07b686fd8)

Line of code with the wrong change:
https://github.com/Kong/insomnia/blame/develop/packages/insomnia/src/models/settings.ts#L40

![grafik](https://github.com/Kong/insomnia/assets/73105786/65e8c5af-f15c-4969-8a80-b27030b16b68)

### Reproduction Steps

Start Application first Time on Windows

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

INS-2697 is not open to public inspection.

### Insomnia Version

2023.5.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

webseite

**Comment by filfreire** [comment]
cc @subnetmarco

**Comment by filfreire** [comment]
@DevTeamDbVertrieb thank you for reporting this. The terms have been updated accordingly.

**Comment by DevTeamDbVertrieb** [comment]
@filfreire 
Hello, you must check all your legal text:
https://insomnia.rest/privacy

> Analytics Data
> 
> Insomnia’s website and (if you **_opt-in_**) applications collect information to improve our Services.

I don't know if you have any other legal texts in other places. You would have to check and adjust all of them now.

**Comment by subnetmarco** [comment]
@DevTeamDbVertrieb Thank you! We have updated all the disclosures.
