### ISSUE TITLE
Missing VCS Button

### ISSUE THREAD

**Issue by lord-haffi** [getinsomnia/insomnia#6328]
### Expected Behavior

The button to pull and push snapshots to being always present.

### Actual Behavior

![grafik](https://github.com/Kong/insomnia/assets/49658102/8050902b-a92d-4b93-b625-94ea15735e27)

Sometimes the VCS button where I can pull and push "snapshots" magically dis- and reappears. In this screenshot the button is not present. (Should be right next to the collection name in the middle.) I couldn't find any hints on how or when this happens. Sometimes it reappears when I relog, sometimes not. Sometimes it reappears when I select another collection sometimes not. I also reinstalled the program but that didn't help. It's a big mysterious to me and I couldn't find any issues related to this.

Interestingly, I'm not the only one in my team having this issue. So this may have something to do with it. I'm using Insomnia only for work.

Are there some preferences or known issues?

### Reproduction Steps

As I said, I couldn't find any reproducable behaviour yet, I'm really sorry. But I'd willingly follow any steps if you have any ideas.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Insomnia -> About:
```
Version: Insomnia 2023.5.4
Build date: 18.8.2023
OS: Windows_NT x64 10.0.22621
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64
```

### Insomnia Version

2023.5.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro version 22H2

### Installation method

download from insomnia webpage and executing the installer

### Last Known Working Insomnia version

never worked properly for me (using it for ~1 year now)

**Comment by jackkav** [comment]
Sync features have been merged together into the same UX in the bottom left.

**Comment by lord-haffi** [comment]
Ah, thats embarrassig... Thanks a lot ^^'
