### ISSUE TITLE
Failed to render error when updating folder via settings

### ISSUE THREAD

**Issue by thanoskoutr** [getinsomnia/insomnia#6334]
### Expected Behavior

I want to create a folder with requests in a collection on Insomnia and add a markdown description to the folder. 

### Actual Behavior

What actually happens is that Insomnia crashes the moment I try to write anything in the text box.

### Reproduction Steps

1. Create a new collection on Insomnia.

2. Create a new folder.
![Screenshot from 2023-08-18 17-57-28](https://github.com/Kong/insomnia/assets/49553753/84f1f5fa-8e0a-4015-8e44-d6e23a5afd42)

3. Click on the folder Settings.
![Screenshot from 2023-08-18 17-57-37](https://github.com/Kong/insomnia/assets/49553753/3d4e9a8b-32e8-400b-ba22-c5098fc4deae)

4. Try to write anything in the text box.
![Screenshot from 2023-08-18 17-57-53](https://github.com/Kong/insomnia/assets/49553753/7c58bdf7-1810-4d40-897e-205674b41b5a)

5. It crashes...
![Screenshot from 2023-08-18 17-58-10](https://github.com/Kong/insomnia/assets/49553753/f79798fe-e1ad-4fbc-803b-4b1ca6b5436f)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The error message that gets displayed is the following (in text form):
``` 
Failed to render. Please report to our Github Issues

Error: No route matches URL "/organization/org_default-project/project/proj_6109ca6b0daf4363b4dc167815ea2a1d/workspace/wrk_8c28c645db9f4589b4ae4e256fca6706/debug/request-group/fld_3d00639ab1194a2cbf0ea1aded1337f1/update"
Try to reload the app
Error: No route matches URL "/organization/org_default-project/project/proj_6109ca6b0daf4363b4dc167815ea2a1d/workspace/wrk_8c28c645db9f4589b4ae4e256fca6706/debug/request-group/fld_3d00639ab1194a2cbf0ea1aded1337f1/update" at Pi (file:///opt/Insomnia/resources/app.asar/index-ae32ab7a.js:31:8269) at Object.Ye [as fetch] (file:///opt/Insomnia/resources/app.asar/index-ae32ab7a.js:30:17838) at Object.submit (file:///opt/Insomnia/resources/app.asar/index-ae32ab7a.js:49:6555) at file:///opt/Insomnia/resources/app.asar/index-ae32ab7a.js:131:22895 at onChange (file:///opt/Insomnia/resources/app.asar/debug-94b4d679.js:35:20727) at file:///opt/Insomnia/resources/app.asar/index-ae32ab7a.js:649:57921 at file:///opt/Insomnia/resources/app.asar/index-ae32ab7a.js:638:4471 at file:///opt/Insomnia/resources/app.asar/index-ae32ab7a.js:17:25974 at file:///opt/Insomnia/resources/app.asar/index-ae32ab7a.js:17:25921 at sentryWrapped (/opt/Insomnia/resources/app.asar/node_modules/@sentry/browser/dist/helpers.js:76:23)
```

### Insomnia Version

2023.5.4

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.3 LTS

### Installation method

apt

**Comment by filfreire** [comment]
@thanoskoutr @skipfire we can reproduce this issue, we're working on a fix and will update you asap.
