### ISSUE TITLE
Feature request: Re-add paste CURL on URL bar

### ISSUE THREAD

**Issue by rogiermulders** [getinsomnia/insomnia#6338]
### Expected Behavior

When I past a curl command (copied from Chrome with 'copy as CURL) I expect Insomnia to parse it and I can replay the chrome call in Insomnia:

This has been working forever and is extremely usefull to ne,

### Actual Behavior

Gives me an error

![Screenshot from 2023-08-20 09-40-32](https://github.com/Kong/insomnia/assets/3762855/c9a9467b-b1d2-4ac2-8654-601589dc63b1)

### Reproduction Steps

Past this:

curl 'https://jsonplaceholder.typicode.com/posts' \
  -H 'authority: jsonplaceholder.typicode.com' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,nl;q=0.8' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json; charset=UTF-8' \
  -H 'origin: http://localhost:3001' \
  -H 'pragma: no-cache' \
  -H 'referer: http://localhost:3001/' \
  -H 'sec-ch-ua: "Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36' \
  --data-raw '{"title":"foo","body":"bar","userId":1}' \
  --compressed

In the address bar of insomnia

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Version: Insomnia 2023.5.5 Build date: 8/18/2023 OS: Linux x64 6.2.0-26-generic Electron: 25.2.0 Node: 18.15.0 Node ABI: 116 V8: 11.4.183.23-electron.0 Architecture: x64

### What operating system are you using?

Ubuntu

### Operating System Version

Linux ubuntu 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

SNAP

### Last Known Working Insomnia version

The version

**Comment by arfathyahiya** [comment]
Same issue here 
I tried both options
- copy as cURL (windows)
- copy as cURL (POSIX)

with these features not working it's kinda annoying to manually input all data in it (which doesn't make sense)
please try to give this bug top priority 

Current Version details:
```
Version: Insomnia 2023.5.5
Build date: 19/8/2023
OS: Windows_NT x64 10.0.19045
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64
```

Thanks :)

**Comment by filfreire** [comment]
@rogiermulders @arfathyahiya you should still be able to import from Curl by using the new request dropdown `From Curl` option:

<img width="327" alt="image" src="https://github.com/Kong/insomnia/assets/11976836/cd0e6295-293e-4373-b8f5-63fbdd6f2a1f">

**Comment by pharmacord-paul** [comment]
Why was this functionality removed? It was very good and intuitive.

**Comment by arfathyahiya** [comment]
> @rogiermulders @arfathyahiya you should still be able to import from Curl by using the new request dropdown `From Curl` option:
> 
> <img alt="image" width="327" src="https://user-images.githubusercontent.com/11976836/261943123-cd0e6295-293e-4373-b8f5-63fbdd6f2a1f.png">


Thanks I didn't knew that and shifted to postman for time being.

But nothing beats the simple paste option working. I hope they add it back.

**Comment by Patamen** [comment]
If this is not a bug - please, return CURL paste feature

**Comment by filfreire** [comment]
changing this to feature request 

the feature was removed due to https://github.com/Kong/insomnia/issues/6290 and fix  https://github.com/Kong/insomnia/pull/6295

**Comment by diasgab** [comment]
After the last update the paste from curl is not working (not even using the option from the menu); the sorting of endpoints changed on itself; the search filter bar doesn't work as expected :( .The previous version was working perfectly but there were many bugs introduced in the new one.

**Comment by PeterWCox** [comment]
I downgraded to Insomnia 2023.4.0 which solved the issue of CURL not importing.

https://github.com/Kong/insomnia/releases/tag/core%402023.4.0

Love Insomnia, and quite disappointed at the removal of this excellent feature.

**Comment by cozzbp** [comment]
This feature is literally the only reason I use Insomnia, anyone got a good alternative?

**Comment by sunspinx** [comment]
I agree, it's kinda frustrating now. I'm switching to Postman temporarily or downgrading the version because it simply ruined your learnt behaviour. Take the CURL from network/bug and everything got prefilled. Now u must click on new request which makes you to do more steps and not intuitive at all.

**Comment by filfreire** [comment]
Re-adding the feature in an upcoming patch release with this PR https://github.com/Kong/insomnia/pull/6384

**Comment by arfathyahiya** [comment]
@filfreire 
Before release can you please also make sure about rename functionality?
Currently I've to use dropdown menu to rename the request name

Previously it was as simple as double clicking

Thank you for your hard work :)

EDIT 
![image](https://github.com/Kong/insomnia/assets/43339946/c2c546a7-9c0e-4204-a887-082c9184d3d8)

The GET and POST requests in color was good and easy to identify

**Comment by sunspinx** [comment]
> @filfreire Before release can you please also make sure about rename functionality? Currently I've to use dropdown menu to rename the request name
> 
> Previously it was as simple as double clicking
> 
> Thank you for your hard work :)
> 
> EDIT ![image](https://user-images.githubusercontent.com/43339946/263267061-c2c546a7-9c0e-4204-a887-082c9184d3d8.png)
> 
> The GET and POST requests in color was good and easy to identify

I fully agree with this just as my colleagues at work. None of them liked removing the colors, renaming and the curl into url bar not working. Those last changes were kinda bad and I'm curious what was the reason of removing it.

**Comment by rogiermulders** [comment]
Hi, 
To start with: Thank you for re-adding the past as curl option.

What I find annoying now is that it creates 'New Request' every time I past a Curl  call. 
Before that did not happen.

Also I can not remove Requests as bulk (or I do not know how) so I end up with a bunch of requests that I have to remove one by one.

PS Don't know if this is a feature request or I can write it here.

**Comment by arfathyahiya** [comment]
> Hi, To start with: Thank you for re-adding the past as curl option.
> 
> What I find annoying now is that it creates 'New Request' every time I past a Curl call. Before that did not happen.
> 
> Also I can not remove Requests as bulk (or I do not know how) so I end up with a bunch of requests that I have to remove one by one.
> 
> PS Don't know if this is a feature request or I can write it here.


Please consider the above issue, also pressing `DELETE` key doesn't delete the request now, have to go through a few clicks to delete it.

Thanks for the tool :)

**Comment by krishna-atkalikar** [comment]
Instead of always creating a new request, is it possible to modify existing request.
