### ISSUE TITLE
[Bug] After updating to 5.12.0 (5.12.0.1718), old responses was displayed as some weird characters.

### ISSUE THREAD

**Issue by hidrodixtion** [getinsomnia/insomnia#634]
- Insomnia Version: 5.12.0 (5.12.0.1718)
- Operating System: MacOS 10.12.6

## Details

Right after updating to 5.12.0, all of old responses, which is JSON in my case, was displayed as some weird characters. Running the request again was fine, showing the response normally. It only happens for the first time after update.

![](https://api.monosnap.com/rpc/file/download?id=krnJJ2RI8fYGpIvO5VhekdM5WK1B5o)

**Comment by mweibel** [comment]
FYI I had the same issue just now. Restart of the app doesn't help but you can just redo the request and you get the proper response back again.

**Comment by gschier** [comment]
Thanks for letting me know! Pushing a fix for this now. Unfortunately, if you already launched the app your responses won't be restored to normal.

**Comment by gschier** [comment]
Should be fixed now in [5.12.3](https://insomnia.rest/changelog/5.12.3/)
