### ISSUE TITLE
The “Application Update” dialog is confusing, does not refer to Insomnia

### ISSUE THREAD

**Issue by mormegil-cz** [getinsomnia/insomnia#6345]
### Expected Behavior

I expected a useful/non-confusing update message.

### Actual Behavior

A dialog in the form of a top-level window appeared out of nowhere (note that I was even using a different application at that moment), stating “Application Update”: “A new version has been downloaded. Restart the application to apply the updates.” “Restart” / “Later”.

The dialog has just a generic (i) icon and contains no indication whatsoever about which “application” it refers to.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The dialog should at the very least mention Insomnia.

Or, it could be a non-top-level window, so that it is obvious it refers to Insomnia. (However, I understand a modal dialog might get in the way.)

Another option would be just a non-obtrusive notification in the kind of VS Code or something.

### Insomnia Version

2023.5.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22H2 (19045.3324)

### Installation method

probably downloaded manually, I guess

**Comment by filfreire** [comment]
@mormegil-cz we added a fix for this, will go out in upcoming versions/patch versions of insomnia. Thanks for reporting!

**Comment by Syazvinski** [comment]
This has been so incredibly annoying, it gives me the update message 20 times and makes me click 'later' 20 times. If I click restart and update it still gives the same message after the update. Is there a fix?
