### ISSUE TITLE
 Sort order not working

### ISSUE THREAD

**Issue by wesleifreitas** [getinsomnia/insomnia#6349]
### Expected Behavior

When I open my IDE it should show my previous requests in the order I had them in

### Actual Behavior

They opened in a random order and I can't resort them. The drag and drop as well as the sort button are broken

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10/11

### Installation method

Windows downloader

### Last Known Working Insomnia version

I do not remember

**Comment by royathan** [comment]
This just started happening me as well, I believe it happened when the client automatically upgraded to 2023.5.5 because I did see the popup for that version in the bottom right.

![Screen Recording 2023-08-21 at 4 04 58 PM](https://github.com/Kong/insomnia/assets/56088145/b42f2bcf-43c5-4ffb-bef2-61d950ea60ad)

**Comment by tsptylertech** [comment]
I have this same problem.  I am on version 2023.5.5.

**Comment by lincolnpjames** [comment]
I also have the same issue - Unable to Sort and Search/Filter
```
Version: Insomnia 2023.5.3
Build date: 8/16/2023
OS: Darwin arm64 22.5.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: arm64
```

and also
```
Version: Insomnia 2023.5.5
Build date: 8/19/2023
OS: Darwin arm64 22.5.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: arm64
```

I've also exported everything, removed application including the `Application Support` Insomnia folder however, issue still persists.

**Comment by Mohnish226** [comment]
It breaks on `2023.5.3`

```
Version: Insomnia 2023.5.3
Build date: 16/08/2023
OS: Windows_NT x64 10.0.22621
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64
```

The sorting works fine on `2023.4.0`
```
Version: Insomnia 2023.4.0
Build date: 7/5/2023
OS: Darwin x64 22.6.0
Electron: 23.3.9
Node: 18.12.1
V8: 11.0.226.20-electron.0
Architecture: x64
```

**Comment by lincolnpjames** [comment]
Looks like it was the Electron update (potentially)

**Comment by aradalvand** [comment]
Same here

**Comment by sw360cab** [comment]
+1

**Comment by alexdev430** [comment]
+1

**Comment by dozer55** [comment]
+1

**Comment by sw360cab** [comment]
@jackkav happy you closed this.

AFAIK the issue is still there in 2023.5.5

```
Version: Insomnia 2023.5.5
Build date: 8/18/2023
OS: Darwin x64 18.0.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64
```

**Comment by jackkav** [comment]
Fix goes out in 5.6

**Comment by royathan** [comment]
After upgrading to v2023.5.6 I have odd rendering changes (new theme or bug?). When trying to reorder the requests I now get this error:

```
Error: MetaSortKey position is required at kn (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:17:107605) 
at Module.Ct (file:///Applications/Insomnia.app/Contents/Resources/app.asar/actions-93c09014.js:5:9142) 
at async Xl (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:31:3691) 
at async je (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:30:18468)
```

![Screen Recording 2023-08-23 at 10 51 42 AM](https://github.com/Kong/insomnia/assets/56088145/08913011-922d-4672-a50d-0cbed7873aa6)

**Comment by robertocerdasilva** [comment]
> Después de actualizar a v2023.5.6, tengo cambios extraños en la representación (¿nuevo tema o error?). Al intentar reordenar las solicitudes, ahora aparece este error:
> 
> ```
> Error: MetaSortKey position is required at kn (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:17:107605) 
> at Module.Ct (file:///Applications/Insomnia.app/Contents/Resources/app.asar/actions-93c09014.js:5:9142) 
> at async Xl (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:31:3691) 
> at async je (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:30:18468)
> ```
> 
> ![Grabación de pantalla 2023-08-23 a las 10 51 42 a.m.](https://user-images.githubusercontent.com/56088145/262709595-08913011-922d-4672-a50d-0cbed7873aa6.gif)

+1
