### ISSUE TITLE
Search doesn't work in Collection

### ISSUE THREAD

**Issue by federicogatti** [getinsomnia/insomnia#6355]
### Expected Behavior

Request in the collection must be searchable

### Actual Behavior

With the last release Requests aren't searchable

### Reproduction Steps

1. Open collection
2. try to search

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.5

### What operating system are you using?

macOS

### Operating System Version

13.5 (22G74)

### Installation method

downalod

**Comment by anthonyhollings** [comment]
Also having this issue after latest release, cannot filter the request list

**Comment by johnnovak** [comment]
Yeah it's completely broken 😩 
I downgraded to this earlier version:

https://github.com/Kong/insomnia/releases/tag/core%402023.4.0

**Comment by blieb** [comment]
It looks like it starts working again in version 2023.5.6. but the results are not clear to me, In old versions the parent folders are visible, but now I only see folders that match the result.

![image](https://github.com/Kong/insomnia/assets/540248/942c8d9a-0425-44e3-adc7-e88d8b0e0762)

in older versions it looks like this:
![image](https://github.com/Kong/insomnia/assets/540248/8ad73e43-a0d7-4f94-908b-644fc97a139d)

**Comment by kevinpfox** [comment]
Filter feature appear to not work at all.

It hasn't been working for weeks. It broke around the same time as moving items in the left column stopped working.

**Expected behavior**: Items not matching search term are hidden, relevant items remain visible in the left column.
**Current behavior**: Nothing happens after search term is submitted from "Filter" entry field. I saw some directories get opened but that is about it. The collection basically remains the same.

Please fix this, this is a crucial feature. We often use this, several times a day. When you have 100s of items, filtering down is a very important feature.

**Comment by johnnovak** [comment]
I have no idea how this went through testing. Many of the essential features have regressed to the point of making the program virtually unusable...

**Comment by anthonyhollings** [comment]
> I have no idea how this went through testing. Many of the essential features have regressed to the point of making the program virtually unusable...

Yes, agree that it is frustrating to use at present. I'm sure we'll see another update soon.

Search is providing results that do not appear to be relevant, performance is slower and visually the tree is weird. Appears to be missing the group headers from the search results and the colorings were very helpful.

Perhaps other people are very organized with their folders, but I'm fairly dependent on search to quickly find what I want to go to.

**Comment by johnnovak** [comment]
> Perhaps other people are very organized with their folders, but I'm fairly dependent on search to quickly find what I want to go to.

I'm very organised, but when you have hundreds of requests in 50+ folders the "only show what passes the filter expression" type of filtering is a must. At the very least, make it a configuration option: old filtering behaviour that only shows what matches, or the new highlighting type.

**Comment by kevinpfox** [comment]
If the new filtering is supposed to be doing highlight positive matches, that is going to be awful for anyone with lists 100+ long. If the match is the 175th item out of 180 items, in a folder, the user is going to be scrolling and scanning for quite awhile to find some highlighted item they are trying to find.

Please have it a subtraction of irrelevant items thing vs a highlight thing. Or at least provide an option, as @johnnovak mentioned above, for subtraction of irrelevant items vs highlight.

**Comment by Farenheith** [comment]
I thought the filter wasn't working either, but I realized that, actually, the interface is really really slow, at the point I had to wait some seconds for the search to take effect. I'm on version 2023.5.6, Windows.

Edit: @johnnovak for the tip! I downgraded to the pointed version and disabled automatic updates, and now I can work with it again!

**Comment by kevinpfox** [comment]
@Farenheith Thank you for point that out.

I tried again and I waited for around 10 seconds, which feels like an eternity when you are staring at a monitor waiting for something to happen, and yes items that didn't match disappeared from the left column (expected behavior). I'll be more patient now, now that I know what to expect.

**Comment by johnnovak** [comment]
> Edit: @johnnovak for the tip! I downgraded to the pointed version and disabled automatic updates, and now I can work with it again!

That's what I'm doing, yeah. I actually thought this was an open-source project maintained by a single guy or something, then realised there's a whole company behind it.

So, don't hold your hopes high, guys. They might have been overtaken by "business people", and the poor devs are just doing what they're told to 😩 (release shit faster, without caring about quality or the users...)

**Comment by kgidewall** [comment]
> @Farenheith Thank you for point that out.
> 
> I tried again and I waited for around 10 seconds, which feels like an eternity when you are staring at a monitor waiting for something to happen, and yes items that didn't match disappeared from the left column (expected behavior). I'll be more patient now, now that I know what to expect.

Yes, I'm seeing this too. Very frustrating to wait. Please fix this!

**Comment by anthonyhollings** [comment]
Looks like the latest release "fixes" search back to old behavior but the performance is still a long way off what it used to be 

https://github.com/Kong/insomnia/issues/6404

**Comment by jcurlier** [comment]
+1 performance issue with latest release - reverted to  2023.4.0 - takes 10s to open a small folder, too long for large folder to know

**Comment by subnetmarco** [comment]
We have improved performance by up to 20x with the [latest 9.3.3 release](https://github.com/Kong/insomnia/issues/6809#issuecomment-2262902452). Are you still experiencing these delays?

**Comment by federicogatti** [comment]
@subnetmarco it works fine now
