### ISSUE TITLE
disable the updater

### ISSUE THREAD

**Issue by tkimpton** [getinsomnia/insomnia#636]
Would like to know how to disable the updater, our users do not have admin rights and it keeps prompting to install a helper tool asking for admin username and password.

- Insomnia Version: ___all
- Operating System: ___mac

**Comment by gschier** [comment]
Starting from version 12.5.0 you can disable auto-update checking in the preferences.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/587576/33343789-80c3e652-d47e-11e7-95e9-0ae90c532a2d.png">

**Comment by tkimpton** [comment]
ah ok i am on version 5.11.7. Is this possible on this version?

**Comment by gschier** [comment]
No, it was just added.

**Comment by tkimpton** [comment]
ok will it take time to update? The download version i am getting is 5.12.3

from https://builds.insomnia.rest/downloads/mac/latest

**Comment by tkimpton** [comment]
ah i can see the option on here, thanks very much

**Comment by gschier** [comment]
Oops. Sorry I made a typo. I meant to say 5.12.0. 

Yep, that's the one you want 😄

**Comment by gschier** [comment]
You're welcome! 💯

**Comment by tkimpton** [comment]
ok i can see the setting is not stored in standard plist but in ~/Library/Application\ Support/Insomnia/insomnia.Settings.db is there a way i can programmatically set this using terminal? If i copied over this file during a reinstall i may wipe over users settings.

**Comment by gschier** [comment]
Would an environment variable work? That would be easy to add support for. You could also block all HTTP requests to `https://updates.insomnia.rest` if you have that ability.

**Comment by tkimpton** [comment]
yeah i think a variable would be good. Thanks

**Comment by gschier** [comment]
Just made an issue for this ^

Would you be interested in contributing a PR @tkimpton?

**Comment by tkimpton** [comment]
sure

**Comment by gschier** [comment]
Awesome. I just updated #637 with some info. Feel free to ask any questions there if you have any.
