### ISSUE TITLE
Copy folder to another workspace copies it into same workspace instead

### ISSUE THREAD

**Issue by skibak** [getinsomnia/insomnia#6361]
### Expected Behavior

Copy folder to another workspace should create copy of the folder in the target workspace

### Actual Behavior

Copy of the folder is created in the original (source) workspace

### Reproduction Steps

I imported 2 Postman collections. They appear in homepage, in Insomnia project as 2 Collections.
All request in each collection are grouped into single root folders in each.
Now I want to copy folder from 1st collection to 2nd.
Click folder dropdown - Settings - Move/Copy to workspace - select other collection - Copy
Copy of the folder appears in current window instead of selected collection.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.5

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.5.1 (22G90)

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

n/a

**Comment by jackkav** [comment]
@skibak Thanks for the report, I have a fix ready to merge
