### ISSUE TITLE
Color of the environment icons is no longer visible in the dropdown menu

### ISSUE THREAD

**Issue by willahh** [getinsomnia/insomnia#6366]
### Expected Behavior

Environment icon filled with color on the dropdown menu :

<img width="342" alt="image" src="https://github.com/Kong/insomnia/assets/18645142/1315734c-2774-40fb-aea0-619904c30aee">

### Actual Behavior

Environment icon is now gray :

<img width="354" alt="image" src="https://github.com/Kong/insomnia/assets/18645142/89b3e755-001b-4cb3-983e-4010c6ea2da1">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.6

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### Installation method

Downloaded from Insomnia website, updated via the auto updater

**Comment by filfreire** [comment]
Hey folks, fix for this will go out in upcoming patch release, thanks for reporting!
