### ISSUE TITLE
Wrong url encoding some sequences with % sign

### ISSUE THREAD

**Issue by jerior** [getinsomnia/insomnia#6367]
### Expected Behavior

url encoding sequence "%aa" should be converted into %25aa

### Actual Behavior

sequence of chars %aa will be encoded into same %aa

### Reproduction Steps

entering url:
http://localhost:4500?a0=%&a1%a&a2=%aa

in timeline get:
http://localhost:4500/?a0=%25&a1%25a&a2=%aa

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.6

### What operating system are you using?

Windows

### Operating System Version

windows 10

### Installation method

dowloaded from insomnia

**Comment by filfreire** [comment]
@jerior go to request Settings
![image](https://github.com/Kong/insomnia/assets/11976836/69e027ba-e6dc-4b92-ba0b-92dd74aecf7d)

And then disable the `Automatically encode special characters in URL` option:

![image](https://github.com/Kong/insomnia/assets/11976836/bd46f4d5-6e05-4e19-a476-58150cf6eefa)


when you resend the request it should not encode the special characters:

![image](https://github.com/Kong/insomnia/assets/11976836/151f804c-69a9-40f3-9d44-32cf4c760d17)

**Comment by jerior** [comment]
It doesn't help that much. You just force me to encode it manually before I'll put it into the URL. But the bug with automatic encoding is still there.  My URL with % sign and %aa sequence works fine in browsers and Postman, but it tooks me some time to realize why it dosen't work into Insomnia.
