### ISSUE TITLE
Color of the request methods is no longer visible in the requests section

### ISSUE THREAD

**Issue by diogo-pma** [getinsomnia/insomnia#6368]
### Expected Behavior

Request methods previously had colors:
![image](https://github.com/Kong/insomnia/assets/82580695/c9b8a4ba-2ccb-42fe-ac34-2f40b7683853)
![image](https://github.com/Kong/insomnia/assets/82580695/f47045c2-fc9f-46ce-9aed-a580aed6bb10)

### Actual Behavior

Request methods are now gray:
![image](https://github.com/Kong/insomnia/assets/82580695/a59379b9-af7a-4a2c-af54-e5a99bdaf2b2)
![image](https://github.com/Kong/insomnia/assets/82580695/09ec955b-370e-4403-bb53-7a572cfc77f0)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.6

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 (22621.2134)

### Installation method

Downloaded from Insomnia website, updated via the auto updater

### Last Known Working Insomnia version

2023.5.5

**Comment by mrgnhnt96** [comment]
This also applies to the Sub Environment color
![image](https://github.com/Kong/insomnia/assets/39742020/8e95cdf1-8421-4b5f-900c-07bcb5a69d14)

**Comment by tsptylertech** [comment]
Same here...

Version: Insomnia 2023.5.6
Build date: 8/22/2023
OS: Windows_NT x64 10.0.19045
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

Insomnia came down this morning and auto-updated... and the request method colors are all grey now... they used to be color coded...

**Comment by lucaspk** [comment]
Same here...

Version: Insomnia 2023.5.6
Build date: 8/22/2023
OS: Darwin arm64 22.6.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: arm64

**Comment by dunklesToast** [comment]
<details>
<summary>This comment duplicates #6366</summary>

Not sure if related, but environments also lost their colors in the dropdown
<img width="42" alt="image" src="https://github.com/Kong/insomnia/assets/17279485/bcbdd48c-b83e-48a7-b553-a4efb307c49f">

</details>

**Comment by diogo-pma** [comment]
Hey @tsptylertech @lucaspk, thanks for your input and giving your Insomnia version info.

### I'd like to ask everyone to resort to just 👍 the main comment if you're going through the same issue, as subscribers to this thread receive each and every single new comment made here.

Thanks for understanding!

**Comment by diogo-pma** [comment]
Hey @tsptylertech @lucaspk, thanks for your input and giving your Insomnia version info.
[@dunklesToast](https://github.com/dunklesToast) please refer to https://github.com/Kong/insomnia/issues/6366 for the issue you brought up.

### I'd like to ask everyone to resort to just 👍 the main comment if you're going through the same issue, as subscribers to this thread receive each and every single new comment made here.

Thanks for understanding!

**Comment by filfreire** [comment]
Hey folks, fix for this will go out in upcoming patch release, thanks for reporting!
