### ISSUE TITLE
[Improvement] Allow disabling auto-updater via environmet variable

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#637]
Related to #636 

My proposed solution is to look for an environment variable named `INSOMNIA_DISABLE_UPDATES` in [updates.js](https://github.com/getinsomnia/insomnia/blob/5873dc9d88efd90c8f7da163bd019d6a661cf4d7/packages/insomnia-app/app/main/updates.js#L36). It if set to a truthy value, console.log that the setting was found and skip the update check.

**Comment by tkimpton** [comment]
great idea pls let me know how i can test it out, thanks

**Comment by gschier** [comment]
@tkimpton I should be able to get this into the next release since it's fairly simple. Stable builds are released on average every week but I can get you an early beta build to test if you'd like.

**Comment by tkimpton** [comment]
that would be great thanks :)

**Comment by gschier** [comment]
@tkimpton here's an early build for you to test https://github.com/getinsomnia/insomnia/releases/tag/v5.12.4-beta.1

**Comment by tkimpton** [comment]
ok great, please can you tell me where is need to set INSOMNIA_DISABLE_AUTOMATIC_UPDATES=true

i have searched for an updates.js file but i cannot find it.

**Comment by tkimpton** [comment]
ok i will give it a go

This is what i have so far and may help someone else. This is designed to run in management systems for mac like Jamf Self Service which run as root user.

#!/bin/bash

# current logged in user
loggedInUser=`python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");'`


# source https://stackoverflow.com/questions/4479579/bash-script-only-echo-line-to-bash-profile-once-if-the-line-doesnt-yet-exis/4480671#4480671

# source to disable update https://github.com/getinsomnia/insomnia/issues?q=is%3Aissue+is%3Aclosed


cat << EOF | base64 -D > /tmp/decoded.sh
IyEvYmluL2Jhc2gKTElORT0nZXhwb3J0IElOU09NTklBX0RJU0FCTEVfQVVUT01BVElDX1VQREFURVM9
dHJ1ZScKCmlmICEgZ3JlcCAtRnggIiRMSU5FIiB+Ly5iYXNoX3Byb2ZpbGUgPi9kZXYvbnVsbCAyPi9k
ZXYvbnVsbDsgdGhlbgogICAgZWNobyAiVXBkYXRpbmciIH4vLmJhc2hfcHJvZmlsZQoKICAgIGVjaG8g
Pj4gfi8uYmFzaF9wcm9maWxlCiAgICBlY2hvICIkTElORSIgPj4gfi8uYmFzaF9wcm9maWxlCmZpCgpl
eGl0IDAK
EOF

# full permission for the temp file
chmod 777 /tmp/decoded.sh

# run the command as the logged in user
su $loggedInUser -c '/tmp/decoded.sh'

# remove the temp file
rm /tmp/decoded.sh

# check the System User Template
if [ -e /System/Library/User\ Template/English.lproj/.bash_profile ]; then
        rm /System/Library/User\ Template/English.lproj/.bash_profile
fi

# write to System User Template
echo "export INSOMNIA_DISABLE_AUTOMATIC_UPDATES=true" >> /System/Library/User\ Template/English.lproj/.bash_profile
chmod 777 /System/Library/User\ Template/English.lproj/.bash_profile
exit 0

**Comment by gschier** [comment]
Awesome, thanks for including that here 👍 😄

**Comment by tkimpton** [comment]
brilliant it is working, thanks very much :)

**Comment by ivansieder** [comment]
Is it possible that this is not working right now on Windows when installing from the PowerShell CLI or am I just missing something?

Tried the following:
- uninstalled Insomnia
- deleted %AppData%\Roaming\Insomnia
- deleted %LocalAppData%\Roaming\insomnia
- opened PowerShell
- ran `$env:INSOMNIA_DISABLE_AUTOMATIC_UPDATES = "true"`
- ran `$env:INSOMNIA_DISABLE_AUTOMATIC_UPDATES` to verify it's been set
- started the installer with `.\Insomnia.Core-2022.6.0.exe`

After those steps (on Windows 11 with the latest feature updates) the option for automatic updates is still enabled. Am I missing something here?
