### ISSUE TITLE
Insomnia getting crashed : Application Error. Failed to render. 

### ISSUE THREAD

**Issue by gsharma01** [getinsomnia/insomnia#6378]
### Expected Behavior

I have been trying a POST request to get the token but it is keep getting crashed. This POST request returns Json response. It is working in Postman

### Actual Behavior

Failed to render. 
Please report to [our Github Issues](https://github.com/Kong/insomnia/issues)

Following Error appears when it crashes: New Response Missing 'parentId'

Error: New Response missing `parentId` at Module.e7e [as create] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:17:73072) at Module.he (file:///Applications/Insomnia.app/Contents/Resources/app.asar/request-33b1c619.js:1:7765) at async Xl (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:31:3691) at async je (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-391c2d16.js:30:18468)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.6

### What operating system are you using?

macOS

### Operating System Version

macOs Ventura Ver 13.3.1

### Installation method

download from website

**Comment by jackkav** [comment]
What kind of auth mechanism are you using?
