### ISSUE TITLE
Export selection broken

### ISSUE THREAD

**Issue by usama-dev** [getinsomnia/insomnia#6385]
### Expected Behavior

During requests export when selecting/unselecting a folder (containing multiple requests) should select/unselect all of those nested requests.

For example when unselecting the 'Azure' folder should unselect all the nested requests:
![image](https://github.com/Kong/insomnia/assets/8113496/33f98a33-94d8-4b53-8e84-48f22623dc05)

And same with the selection of the folder.

### Actual Behavior

This functionality was working fine until a couple of the last updates. Now it's broken as whenever selecting/unselecting the parent folder it doesn't apply to the nested requests.

For example when unselecting the 'Azure' folder the nested requests are not unselected:
![image](https://github.com/Kong/insomnia/assets/8113496/7555233b-7230-4656-8242-d9016b96788e)

Same happens when selecting/unselecting the top parent folder:
![image](https://github.com/Kong/insomnia/assets/8113496/595f7ddb-bb09-4726-afd4-0048b1b8e2a6)

### Reproduction Steps

1. From the top header click the drop down menu and click export
![image](https://github.com/Kong/insomnia/assets/8113496/7e5fa3d6-6dda-41f0-81f7-d91ae2699d71)

2. Export requests screen appears
![image](https://github.com/Kong/insomnia/assets/8113496/69cf0b0e-0ba2-40b0-9dcb-ed8156739f19)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.6

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home

### Installation method

Official website

**Comment by dhoomakethu** [comment]
Also noticing this on MAC OSX with latest version, unselecting the the root folder does not deselect the childs.

```
Version: Insomnia 2023.5.7
Build date: 8/30/2023
OS: Darwin arm64 22.2.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: arm64
```

**Comment by stylianosnicoletti** [comment]
same here version 2023.5.8 on Windows
```
Version: Insomnia 2023.5.8
Build date: 9/7/2023
OS: Windows_NT x64 10.0.19045
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64
```

**Comment by francoiscorporate** [comment]
I agree, this is a real necessary functionality. 
It's most likely like a bug actually
