### ISSUE TITLE
Prompt tag prompts for input twice

### ISSUE THREAD

**Issue by ArcanoxDragon** [getinsomnia/insomnia#6387]
### Expected Behavior

When a request has a single "Prompt" tag in the URL (and nowhere else in the request), it should only prompt for input once.

### Actual Behavior

A prompt appears for the same prompt tag twice in a row. The value from the first prompt is used in the request, but the value for the second prompt is stored as the "previous value".

If the first prompt is canceled, a dialog box shows up indicating the request failed:
![image](https://github.com/Kong/insomnia/assets/816612/66a6ce96-1ca5-46c3-bcdd-df2060527008)

If the second prompt is canceled, the app crashes:
![image](https://github.com/Kong/insomnia/assets/816612/e2231a0c-7fe3-4b4f-ae03-3a14b20d1e4a)

### Reproduction Steps

1. Create a request
2. Somewhere in the URL, add a single Prompt tag
  - In my request, the "Title", "Label", and "Default Value" settings are configured, and "Storage Key" is blank. "Mask Text" is disabled, and "Default to Last Value" is enabled.
3. Send the request
4. Observe that the prompt dialog appears twice

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2, build 19045

### Installation method

Downloaded via website and updated recently using automatic updater

**Comment by kressnick25** [comment]
I am also getting this issue.

**Comment by Tobbe3108** [comment]
Same here

**Comment by jmkraut** [comment]
I'm getting this issue as well.

**Comment by Bastelbaer** [comment]
Same here

**Comment by Dodewaard** [comment]
I confirm I see the same issue here on version 2023.5.6

**Comment by patogordo** [comment]
Same using MacOS

**Comment by Ob1Ju4n** [comment]
Same issue using macOS 13.5.1

**Comment by db-geek** [comment]
I also can confirm this issue with following Insomnia Versions on Linux:
- 2023.5.5
- 2023.5.6
- 2023.5.7

**Comment by Nopraz** [comment]
Same for me

**Comment by synthead** [comment]
Also seeing this with 2023.5.8 :ok_hand:

**Comment by smmcneill** [comment]
Same

**Comment by darkshadow444** [comment]
Same issue for 2023.5.8, 2023.5.7, 2023.5.6, 2023.5.5

**Comment by kalimbra** [comment]
Same here for linux, insomnia 2023.5.8

```
Version: Insomnia 2023.5.8
Build date: 07/09/2023
OS: Linux x64 5.3.0-28-generic
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64
```

**Comment by mdemille** [comment]
Still an issue on Mac after upgrade to 8.0.0

Version: Insomnia 8.0.0
Build date: 9/27/2023
OS: Darwin arm64 22.6.0
Electron: 25.8.1
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.29-electron.0
Architecture: arm64

**Comment by thenoseman** [comment]
Just found out that the prompt works as expected (shown once) when you use a manually entered "Storage Key".
Potentially this is the place to look:
https://github.com/Kong/insomnia/blob/e0ec076fbb12c561288a72dcdf05a318a2ae11fe/packages/insomnia/src/ui/components/templating/local-template-tags.ts#L428-L433

**Comment by mcianc** [comment]
same problem
Linux Ubuntu 22.10
Version: Insomnia 8.2.0

**Comment by pas-sean** [comment]
Same problem on a Mac
Version: Insomnia 8.2.0
Build date: 10/4/2023
OS: Darwin arm64 23.0.0
Electron: 25.8.1
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.29-electron.0
Architecture: arm64

**Comment by aafaque33** [comment]
Same issue getting in v8.x, 2023.5.8, 2023.5.7, 2023.5.6, 2023.5.5, 2023.5.4
OS Mac 12.7.1

**Comment by yabols** [comment]
Same for me 8.30 version, build 10/13/2023.

**Comment by ihexxa** [comment]
Please keep patience, one fix is wip: #6763

**Comment by subnetmarco** [comment]
This has been fixed in 8.4.4, available for download today.

**Comment by aafaque33** [comment]
> This has been fixed in 8.4.4, available for download today.

Is there a possibility for the fix in old versions like 2023.5.8 ? (Don't want to upgrade to 8.x because of the cloud sync restrictions and also having multiple workspaces which are not available in the Local ScratchPad

**Comment by subnetmarco** [comment]
Just so you know, you can still use 8.x with local storage. We reverted back the mandatory cloud sync and from v8.3 onwards you can choose local, cloud or git storage.

**Comment by aafaque33** [comment]
> Just so you know, you can still use 8.x with local storage. We reverted back the mandatory cloud sync and from v8.3 onwards you can choose local, cloud or git storage.

I agree that v8.3 onwards provide the local capability too, but as compared to old versions it is useless as it provides one collection / workspace, while in old versions most people have multiple collection for different API / Projects and each collection has multiple environments. Now everything is merged into one which is kind of not Insomnia famous for.\

Unless multiple collection is provided in local scratch pad version of 8.3 onwards in the future .

**Comment by subnetmarco** [comment]
You can have multiple local collections/projects after logging in for free.

Without logging in you can still use the Scratch Pad which - as you noted - is limited to one collection only.

**Comment by ChristoNel** [comment]
I know this issue is closed but I am seeing the same behavior,
If I don't set a "Storage Key" value, then I get prompted to enter a value twice. 

Version: Insomnia 2023.5.8
Build date: 2023/09/07
OS: Windows_NT x64 10.0.19045
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

**Comment by ArcanoxDragon** [comment]
Really frustrating that the fix is only included in a version that requires signing into an account to be useful. I've got probably a dozen collections I need to use, and I really don't want to sign into a cloud service just to use locally-stored collections in a desktop app.

I'll just have to deal with the bug until I have the time to find a new local-only REST client and convert all my collections...

**Comment by aafaque33** [comment]
> Really frustrating that the fix is only included in a version that requires signing into an account to be useful. I've got probably a dozen collections I need to use, and I really don't want to sign into a cloud service just to use locally-stored collections in a desktop app.
> 
> I'll just have to deal with the bug until I have the time to find a new local-only REST client and convert all my collections...

https://github.com/ArchGPT/insomnium is the replacement I have found so you may want to look into this too. This is the older forked version of insomnia with bug fixed.
