### ISSUE TITLE
On Macbook, the shortcut to launch environment variables caused insomnia crashed

### ISSUE THREAD

**Issue by manbeing** [getinsomnia/insomnia#6389]
### Expected Behavior

On Macbook, you either use the default keyboard shortcut and any customized shortcut to launch the environment variable selection, the insomnia gets crashed immediately. 

### Actual Behavior

the environment variable selection should be launched by keyboard shortcut

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

![image](https://github.com/Kong/insomnia/assets/39745132/2023f9a1-2601-4e81-aafd-07a1b5847792)

### Insomnia Version

Version: Insomnia 2023.4.0

### What operating system are you using?

macOS

### Operating System Version

macos 12.3

### Installation method

homebrew

**Comment by manbeing** [comment]
I just downloaded the latest Version: Insomnia 2023.5.6
This issue also occurs with this version. 
![image](https://github.com/Kong/insomnia/assets/39745132/a58edbd3-4915-40b2-8880-10d0dcbd748d)

**Comment by cunha-ambisis** [comment]
I can confirm that this is still happening on my version: 
Version: Insomnia 8.6.1
Build date: 2/5/2024
OS: Darwin arm64 23.3.0
Electron: 28.0.0
Node: 18.18.2
Node ABI: 119
V8: 12.0.267.8-electron.0
Architecture: arm64
