### ISSUE TITLE
Environment colors in a Document's Debug tab are not displaying correctly

### ISSUE THREAD

**Issue by jovton** [getinsomnia/insomnia#6391]
### Expected Behavior

When working in the Debug mode (tab) inside a Document, the displayed colors of the selected environment as well as those in the drop-down list should be those that were configured in the environment settings.

### Actual Behavior

The colors of the selected environment as well as those in the drop-down list are all displayed as a light-greyish color when working with the requests in the Debug tab of a Document, irrespective of how the colors were set for each configured environment.

### Reproduction Steps

1. In a Document's requests Debug mode, open the Environments configuration settings
![image](https://github.com/Kong/insomnia/assets/5833599/f5a0b89c-3e87-4e7b-8fc1-42c18b5fdd90)

2. Define some environments and set different colors for them that are clearly distinguishable 
![image](https://github.com/Kong/insomnia/assets/5833599/0c1bd72d-cafa-41f1-80e0-5810ef186061)

3. Save/Close the environment settings dialog, and go back to the Document request Debug mode, and look at the colors of the defined environments.
![image](https://github.com/Kong/insomnia/assets/5833599/ac7082fd-b565-4683-a6b2-713f9d7303fc)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The same seems to be happening when working with a request Collection (not Document).

### Insomnia Version

2023.5.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 22H2 Build 19045.3324

### Installation method

https://insomnia.rest/download

### Last Known Working Insomnia version

2023.2.2

**Comment by demipixel** [comment]
Don't know if I'm on an old version or what (no spec/debug/test tabs), but I also opened insomnia yesterday to find those colors missing, as well as the GET/POST/etc sticker colors on each request, which were helpful :( Couldn't find a setting to bring them back.

**Comment by daniel-metronome** [comment]
+1 I miss the colors 😢

**Comment by azebuji** [comment]
the color of the protocols, can be changed? like older version, after being updated? I really don't like this new ui.

**Comment by jovton** [comment]
> the color of the protocols, can be changed? like older version, after being updated? I really don't like this new ui.

If you want to go back to an older version...

1. Backup your current projects and collections by exporting them, just in case something goes wrong.

![image](https://github.com/Kong/insomnia/assets/5833599/77fb3b39-7145-4788-8f7f-860bda63310d)

2. Disable automatic updates (for now) in the Insomnia Preferences, to prevent Insomnia from overwriting your older installation with the latest one without your permission

![image](https://github.com/Kong/insomnia/assets/5833599/c7fa1403-2791-4448-b914-bc779629efe8)

3. Uninstall your current version of Insomnia

![image](https://github.com/Kong/insomnia/assets/5833599/2564c21a-e7f2-4758-ad5f-8fbe777a4e7e) 

4. Download and install your desired (older) version of Insomnia from here [https://github.com/Kong/insomnia/releases](https://github.com/Kong/insomnia/releases)

![image](https://github.com/Kong/insomnia/assets/5833599/9026dcff-7cd7-44e1-b3ef-6e166e63ee08)

**Comment by kirrie** [comment]
![Xnapper-2023-08-25-09 24 53](https://github.com/Kong/insomnia/assets/1829009/f2440ec0-e104-40bc-8794-1d9914feb47f)
mac version (v2023.5.6) has same problem.

**Comment by filfreire** [comment]
Hey folks this has been fixed in a recent pull-request, and will go out in an upcoming patch release.
