### ISSUE TITLE
Error after change the order of requests

### ISSUE THREAD

**Issue by pavelToman** [getinsomnia/insomnia#6393]
### Expected Behavior

In collection I tried to change the order of requests by drag a request by mouse. The request was in a folder.

### Actual Behavior

When I drag a request to the first position in the folder it crashed with an error.

### Reproduction Steps

1. Go to collection
2. In a folder try to drag a request to the first position in a folder.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Error: MetaSortKey position is required at kn (file:///opt/Insomnia/resources/app.asar/index-391c2d16.js:17:107605) at Module.Ct (file:///opt/Insomnia/resources/app.asar/actions-93c09014.js:5:9142) at async Xl (file:///opt/Insomnia/resources/app.asar/index-391c2d16.js:31:3691) at async je (file:///opt/Insomnia/resources/app.asar/index-391c2d16.js:30:18468)

### Insomnia Version

2023.5.6

### What operating system are you using?

Ubuntu

### Operating System Version

22.04.3 LTS

### Installation method

apt

**Comment by jackkav** [comment]
fixed in 2023.5.7
