### ISSUE TITLE
Restore the User-Agent by default or add an option to enable/disable globally.

### ISSUE THREAD

**Issue by vcruzmj** [getinsomnia/insomnia#6399]
### Expected Behavior

After https://github.com/Kong/insomnia/pull/6109, the insomnia client is not sending the User-Agent by default, and you need to add this to every request manually. 
This is complex in extensive collections, and even "curl" requires explicitly removing the User-Agent for a request.
So, the expected behavior is to send the User-Agent by default and globally. The exception should be removed.
In my case, we use AWS, and WAF is blocking all the requests without a User-Agent by the security team.

### Actual Behavior

By default, it's not sending any User-Agent at all, not even empty. The logs of the timeline confirm this.

### Reproduction Steps

1. Fresh installation of insomnia.
2. Create or use an existent collection.
3. Send a request and check the timeline.
5. The user agent is not printed in logs because it's not sending a User-Agent.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

https://github.com/Kong/insomnia/pull/6109 I don't think the remove of the user-agent by default is the standard option of the industry. Not curl, postman (this has a toggle in their preferences), or a browser has this by default.

### Insomnia Version

2023.5.6

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.2 LTS

### Installation method

ppa added to apt from https://download.konghq.com/insomnia-ubuntu

### Last Known Working Insomnia version

2023.4.0

**Comment by filfreire** [comment]
@vcruzmj if you need, you can setup`DEFAULT_HEADERS` on the Base environment to force a specific user-agent across all your requests:

```
{
	"DEFAULT_HEADERS": {
		"User-Agent": "jurassic-park-apiclient-1.1"
	}
}
``` 

<img width="1204" alt="image" src="https://github.com/Kong/insomnia/assets/11976836/8a337f2d-1d7d-427a-a0b9-52b26a43cde8">

<img width="445" alt="image" src="https://github.com/Kong/insomnia/assets/11976836/0d95a643-f5f7-46d9-ba04-67433b7f0328">

**Comment by vcruzmj** [comment]
That is a workaround instead of a solution (I already applied it and can confirm it works). Still, insomnia has a default behavior in the opposite direction of the other clients and tools (Curl and Postman, as an example).
Those tools allow you to disable the User-Agent, and Insomnia (via a workaround) give the option to enable it. In any case, the _facto_ default option should be enabled by default.

Do I need to submit this as a Feature Request then?

**Comment by ocasta** [comment]
@filfreire Unfortunately this doesn't affect the OAuth 2 token request
