### ISSUE TITLE
Could not generate cURL

### ISSUE THREAD

**Issue by chenzz** [getinsomnia/insomnia#6415]
### Expected Behavior

generate curl nomally

### Actual Behavior

show error as follows:

Could not generate cURL
Failed to render "New Request:url" attempted to output null or undefined value

![image](https://github.com/Kong/insomnia/assets/5676311/6788d108-9200-4318-9126-fd449cce439b)

### Reproduction Steps

1. create any  request with PLACEHOLDER,       eg,  https://{{my_domain}}/sayHello
2. right click  -> "copy as cURL"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Too may bug recently, why?

### Insomnia Version

2023.5.6

### What operating system are you using?

macOS

### Operating System Version

13.4.1 (c) (22F770820d)

### Installation method

download

**Comment by vallerydelexy** [comment]
mine is working tho

**Comment by hugogarcia** [comment]
@chenzz I was facing the same problem. I found out that the `Copy as cURL` is using my `Base Environment`. So I had to duplicate my variables to this environment to be able to generate cURL.

**Comment by jackkav** [comment]
What happens if you send the same request do you get the same error?
This error is shown if you have an invalid template somewhere in your request, perhaps in query or headers?

**Comment by davix** [comment]
In my case, the request Send is fine. The error only shows when Copy as cURL is used.

**Comment by oltronix** [comment]
> @chenzz I was facing the same problem. I found out that the `Copy as cURL` is using my `Base Environment`. So I had to duplicate my variables to this environment to be able to generate cURL.

This was not the behaviour before though and is a regression, I used to be able to send relevant curls in an easy way by selecting the right environment, but now I will have to manually edit the curl to set the right variables which will get old fast.

**Comment by joaquinvasquezp** [comment]
same problem here, found an alternative, instead of right click -> "Copy as cURL", right click -> "Generate Code", then select **Shell** and **cURL** on each dropdown and finally "Copy to Clipboard"

![image](https://github.com/Kong/insomnia/assets/90529755/8b44f11f-8a41-4397-8c4b-746f7315a41d)

**Comment by jackkav** [comment]
This is fixed in 2023.5.8

**Comment by sliakhov-mdsol** [comment]
Copy to clipboard do nothing for me in version:
Version: Insomnia 12.5.0
Build date: 4/2/2026
OS: Darwin arm64 25.4.0
Electron: 41.0.3
Node: 24.14.0
Node ABI: 145
V8: 14.6.650202-electron.0
Architecture: arm64

Couldn't generate any client code at all
