### ISSUE TITLE
Add fallback user agent to OAuth requests

### ISSUE THREAD

**Issue by ocasta** [getinsomnia/insomnia#6425]
### Expected Behavior

I don't understand why the User Agent was removed by default (#6109) when it is a key HTTP header. All our firewalls reject requests without a User Agent.

While there is a suggested, not documented, workaround in answer to #6399 this does not add the User Agent to OAuth 2 authentication requests. I also found that it didn't work for API calls when defined in the Base Environment only when defined in the sub-environment

The definition of alternative User Agent strings needs to affect all requests not just API calls

### Actual Behavior

User Agent defined in Base or Sub Environment is not added to OAuth request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.7

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.4.1

### Installation method

Download from Insomnia

### Last Known Working Insomnia version

2023.4

**Comment by subnetmarco** [comment]
@jackkav Just so I understand, we allowed the user-agent to be customizable on the Headers tab for each request, but that's the only change we made? Therefore a user-agent should still appear for each request?

**Comment by jackkav** [comment]
fixed in: #6429
