### ISSUE TITLE
Pinned requests within folders are not visible in the Sidebar

### ISSUE THREAD

**Issue by ekos2001** [getinsomnia/insomnia#6427]
### Expected Behavior

If request is pinned it should always be visible in the SIdebar

### Actual Behavior

Pinned request is not visible in the Sidebar if it is in the Folder and its Folder is closed/collapsed.

### Reproduction Steps

1. Have a Folder with some request.
2. Pin this request.
3. Close the Folder.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Windows installer

### Last Known Working Insomnia version

2023.4.0

**Comment by yotta2040** [comment]
In MacOS we have the same problem. 

Version: Insomnia 2023.5.7
Build date: 8/30/2023
OS: Darwin x64 22.6.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

**Comment by GentSad** [comment]
The pined requests now are only visible if the folder is opened, if I close the folder the requests are hidden.

**Comment by therealrinku** [comment]
Seems to be resolved now.

**Comment by gatzjames** [comment]
Hey @ekos2001  and everyone here thanks for the feedback! Closing this as @therealrinku mentions this is fixed now!
