### ISSUE TITLE
[Feature Request] Include body in Request tag

### ISSUE THREAD

**Issue by jo45** [getinsomnia/insomnia#643]
It would be nice to be able to use the body content of a request as a variable, the same way we can do it with the response body.

{% response 'raw', '', '' %} => {% request 'raw', '', '' %}

Context: I need add a signature header to authenticate my API requests to OVH cloud services. The signature is the sha1 sum of the concatenation of multiple variables, including request body.

**Comment by jo45** [comment]
Does this feature is still being looked at ?

**Comment by gschier** [comment]
Correct, this still needs doing.

**Comment by gschier** [comment]
Actually, I did merge this before the last release: https://github.com/getinsomnia/insomnia/pull/727

It only supports textual request bodies (so forms and files still don't work) but it could potentially solve your problem now.

**Comment by Misiu** [comment]
Looking for this as well 👍 
I need to have md5 hash of full body that can be used in hmac auth header (HmacSHA512 from concatenated variables including md5 of body)

**Comment by Misiu** [comment]
@gschier any updates? 😉

**Comment by gschier** [comment]
@Misiu No updates yet. I think a couple people have made plugins for similar things using the `getBodyText()` method from a plugin https://github.com/getinsomnia/insomnia/blob/develop/packages/insomnia-app/app/plugins/context/request.js#L18
