### ISSUE TITLE
Garbled text on application open

### ISSUE THREAD

**Issue by nguillermin** [getinsomnia/insomnia#644]
- Insomnia Version: v5.12.0
- Operating System: Windows 10

## Details

edit: NEVER MIND, expressly fixed in 5.12.3. Delete this at your leisure.

On application startup, response text is garbled. Example:

![image](https://user-images.githubusercontent.com/2622768/33569163-cbb8b8fa-d8f6-11e7-89b7-4d6f346f455f.png)

Issue is fixed by re-sending requests (so a temporary cosmetic issue). Just thought it might be worth investigating.

**Comment by gschier** [comment]
Yep, it was fixed in 5.12.3. Sorry for the trouble 🙄
