### ISSUE TITLE
Filtering does not display folder content when it should

### ISSUE THREAD

**Issue by Oryss** [getinsomnia/insomnia#6440]
### Expected Behavior

When using the filter search, if a folder matches, it should display all requests inside the folder.

Let's say I have a folder called Github, with a request inside name "GET Something", if I search for "Github", it should display the Github folder and all the content inside.

This is problematic because in my usage of Insomnia, all requests are basically named the same ("GET Products") and all domains are retrieved by a plugin.

### Actual Behavior

Requests are only displayed when they match the filter

### Reproduction Steps

1. Create a Github folder
2. Create a request inside this folder called "something". The request is a GET to example.com
3. Filter by searching "github"
4. Only the folder name is displayed, not the "something" request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.6

### What operating system are you using?

Ubuntu

### Operating System Version

Linux 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

insomnia.rest deb

**Comment by Farenheith** [comment]
On my personal laptop I disabled automatic updates because of this issue, and I've just checked out in what version Insomnia was  in it so I can force it on the company's laptop too:

```
Version: Insomnia 2023.3.0
Build date: 6/27/2023
OS: Linux x64 5.15.0-87-lowlatency
Electron: 22.3.11
Node: 16.17.1
V8: 10.8.168.25-electron.0
Architecture: x64
```

The current version seems to have nice features, but this issue made the daily basis really hard, to the point I preferred to use a different client to work

**Comment by jongomes** [comment]
same problem

**Comment by LeeBear35** [comment]
Filtering has become useless, if you put requests into folders by project and then try to search for the project folder with the filter, you can see the folder, but nothing in it, and selecting the folder and turning off the filter does not position you to the folder, so the filter has become a waste of space. I wish I had retained the earlier release like [Farenheith](https://github.com/Farenheith)] had.

**Comment by Oryss** [comment]
Issue closed, we switched to Bruno 👍
