### ISSUE TITLE
Excessively slow Treeview deployment

### ISSUE THREAD

**Issue by Quijadadp** [getinsomnia/insomnia#6441]
Previously it works fine, after the updates it started to display very slowly the hierarchical structure of the requests. I have a big tree with many items, about a thousand.
[Local_Insomnia_2023-08-21.txt](https://github.com/Kong/insomnia/files/12498348/Local_Insomnia_2023-08-21.txt)

**Comment by vvivanloc** [comment]
I confirm. It becomes sluggish. The only mitigation is to revert to 2023.3.0 and it feels now snappier like good olde days... 

2023.4.0 is a bit slower and 2023.5.0 is the worst of all.

First, the project takes ages to open. 
The swapping between routes also, so much I accidentally send a bad route.
It is the same when I change the environment. It is slow now.

It takes almost 7 seconds to toggle between environment.
![image](https://github.com/Kong/insomnia/assets/7536295/48edaeb2-2bed-4b64-9443-45d48e6566b4)

8 seconds to swap between environment to edit them.
![image](https://github.com/Kong/insomnia/assets/7536295/ba4bbc6e-dd00-4e3e-ba7d-f01d1acd2a77)

I have 300 routes.

Version: Insomnia 2023.5.7
Build date: 30/08/2023
OS: Windows_NT x64 10.0.19044
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

**What operating system are you using?**
Windows

**Operating System Version**
Windows 10

**Installation method**
Portable/Installer version

**Last Known Working Insomnia version**
2023.4.0

**Comment by rikesh-chouhan** [comment]
Seeing same sluggishness on Mac os monterey - 12.6.5

**Comment by filfreire** [comment]
Fixed on #6461
