### ISSUE TITLE
XPath tag filter not working

### ISSUE THREAD

**Issue by Josh-PPI** [getinsomnia/insomnia#6442]
### Expected Behavior

When using an XPath tag filter, in my scenario, it would return my access token.  This used to work, but recently broke with an update that was released.

### Actual Behavior

Live preview shows:  Returned no results.
The call does not work.

Changing the token call to JSON and using a JSONPath filter does work.

See screenshot
[Tag XPath filter not working.docx](https://github.com/Kong/insomnia/files/12499037/Tag.XPath.filter.not.working.docx)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

Maybe 2023.5.5

**Comment by kleitofi** [comment]
I have the same problem

**Comment by TelephoneTan** [comment]
omg!!!!!!!!!!! please fix it! so terrible....😭

**Comment by Josh-PPI** [comment]
I just updated to version 2023.5.8 and this is working now.
Thank you so much!
