### ISSUE TITLE
[Feature Request] Honor Proxy setting in oauth2 windows

### ISSUE THREAD

**Issue by vpopescu** [getinsomnia/insomnia#6444]
### Expected Behavior

If I configure the http proxy inside the application, i expect all network functionality to use that http proxy.

### Actual Behavior

Most things work, however the oauth 2.0 popup is not using the http proxy, but defaulting to system proxy

### Reproduction Steps

1. Create a new request
2. Set authentication to Oauth 2.0, Authorization Code with PKCE. Fill in the rest of the fields
3. Set proxy in Insomnia preferences menu, for both http and https 
4. Attempt to authenticate (click Fetch Tokens)
5. The oauth window will come up, however the OAUTH transaction requests will not use the configured proxy

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Apologies if I missed an existing issue on this, I did try my best to find it.
Incidentally, this is also a long-standing issue with Postman.

### Insomnia Version

2023.5.7

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### Installation method

Downloaded official distribution from project site

**Comment by moritz4004** [comment]
Thank you for identifying this issue. I recently encountered the same difficulties in my environment and was able to reproduce the behavior.

To address this problem, I've developed a solution and created a pull request (https://github.com/Kong/insomnia/pull/7077) that implements the necessary changes.

Please review my pull request and let me know if any further adjustments are needed. I am prepared to provide additional information as necessary.

**Comment by gatzjames** [comment]
Closing as this is now working
