### ISSUE TITLE
[BUG] Environment editor sets Base Environment to active after editing

### ISSUE THREAD

**Issue by jaredblackjcb** [getinsomnia/insomnia#6449]
### Expected Behavior

When I edit my Base Environment, my active environment should not change.

### Actual Behavior

After editing the base environment, the active environment is set to Base Environment. 

### Reproduction Steps

1. I set an active environment.
<img width="191" alt="image" src="https://github.com/Kong/insomnia/assets/40250874/1762e8d4-4364-4109-9924-aa3d7d348da8">

2. I open my environment editor to edit my base environment, then close it.
3. My active environment has changed to Base Environment.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This behavior first appeared in the 2023.5.7 version released on 8/30. Prior to that date, I believe the environment editor was not linked to the active environment selector. It doesn't make sense to link them because URLs are not usually stored in the base environment since they change based on the target environment.

### Insomnia Version

2023.5.7

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

2023.5.6

**Comment by therealrinku** [comment]
This seems to be resolved now, I couldn't reproduce it.
