### ISSUE TITLE
Environment variables not getting rendered in "Copy as CURL"

### ISSUE THREAD

**Issue by kiwitrav** [getinsomnia/insomnia#6458]
### Expected Behavior

Copy as cURL on request includes the current value rendered from the environment; eg if I had:

- an environment variable contentType currently set to "application/json"
- a header "ContentType" set to the contentType environment variable

when I choose to copy cURL I would expect it to include header "ContentType" with value "application/json"

### Actual Behavior

Copy as cURL on request includes the current value rendered from the environment; eg if I had:

- an environment variable contentType currently set to "application/json"
- a header "ContentType" set to the contentType environment variable

when I choose to copy cURL I get a header entry of "ContentType" but no value in the header

### Reproduction Steps

Create an environment variable with a value
Create a call with a Header set to that environment variable

Copy the cURL - value of environment variable is not included

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro

### Installation method

Download from insomnia

### Last Known Working Insomnia version

Unsure.

**Comment by filfreire** [comment]
@kiwitrav thanks for reporting this, we can reproduce as well.

**Comment by jackkav** [comment]
Fixed in #6462
