### ISSUE TITLE
[Feature request] Allow comments in JSON body

### ISSUE THREAD

**Issue by mangefox** [getinsomnia/insomnia#646]
The body of requests often contain IDs which may be hard to distinguish between.
Being able to append a comment with a description to a row would often be of practical value. 

Example:

```
{
  "command": "refresh",
  "user_ids": [
    9842509438, // username steve74
    4581013095, // username nyancat
    609582939   // username wegetitnow
  ]
}
```

**Comment by gschier** [comment]
You can use [Nunjucks](https://mozilla.github.io/nunjucks/) (the template language Insomnia uses) comments for this.

```
{
  "command": "refresh",
  "userIds": [
    9842509438, {# username steve74 #}
    4581013095, {# username nyancat #}
    609582939   {# username wegetitnow #}
  ]
}
```

**Comment by mangefox** [comment]
Thanks @gschier, I wasn't aware! Closing this issue

**Comment by gschier** [comment]
Don't worry. It's not really documented anywhere. Hopefully other people will find this issue, though 👍 😄

**Comment by tooolbox** [comment]
I have foundeth thine issue!
How does one edit these comments, once they're entered?  I click them and I get a modal that says "Edit" and that does nothing.

**Comment by gschier** [comment]
Oh dang, I didn't realize they weren't editable. I'm pretty sure they were at one point. Want to create a new issue for that?

**Comment by tooolbox** [comment]
Sure!

**Comment by gschier** [comment]
Thanks 😄

**Comment by anandvarkeyphilips** [comment]
This issue is back now?? Its not taking as comments and I still cant edit the comments. Any other option??

**Comment by diego-lipinski-de-castro** [comment]
Update?

**Comment by bryanprimus** [comment]
update?

**Comment by Cobertos** [comment]
(Version: Insomnia 2021.2.2)

These still seem to work, but they are hard to work with:

* They cause an error to show
* They show up as a single block when pasted, making it hard to edit them. Clicking on them brings up an edit dialog, but there are no controls or content in the dialog, it's blank.

![image](https://user-images.githubusercontent.com/6759176/114090571-9acb0200-9885-11eb-9116-4209e57f8a05.png)

![image](https://user-images.githubusercontent.com/6759176/114090703-c352fc00-9885-11eb-9c32-8056f773ff36.png)

**Comment by alannaidon** [comment]
Any news on this?

**Comment by mhmmd-ysf** [comment]
> (Version: Insomnia 2021.2.2)
> 
> These still seem to work, but they are hard to work with:
> 
> * They cause an error to show
> * They show up as a single block when pasted, making it hard to edit them. Clicking on them brings up an edit dialog, but there are no controls or content in the dialog, it's blank.

Same here, Version 2021.5.0

**Comment by bukkadev** [comment]
The issue should be reopened. 
Insomnia 2022.2.1. still has no way to label JSON data.

![image](https://user-images.githubusercontent.com/3074666/159672197-4944e6ee-6f8d-4b55-889f-823bcb38398c.png)

**Comment by AEROGU** [comment]
16/05/2022  5 years later and we still can't comment the json body but dont worry you all, there is a PLUGIN to achieve this.
https://insomnia.rest/plugins/insomnia-plugin-jsonc

**Comment by AdrianoAE** [comment]
This is still an issue and the plugin posted above does not work (GRPC)

**Comment by Steen3S** [comment]
Please add normal comments to json body, i really like to comment out some properties of the body during dev. Also make this work with text selection and then cmd + / to toggle the commenting.
