### ISSUE TITLE
[Feature Request] Ability to revoke Oauth2 access

### ISSUE THREAD

**Issue by zarsky-broad** [getinsomnia/insomnia#647]
- Insomnia Version: 5.12.3.1728
- Operating System: Mac OS 10.12.6

## Details

It would be excellent if there was a way to log out of Oauth2 provider.

For example, I work on an application where some endpoints decide what user to fetch data for based on who is authenticated. It would be useful to have an easy way to log out of one test user and into another. Right now, the best option I have is to get a token from somewhere else and paste that in to the auth tab.

Thanks for an awesome app.

**Comment by gschier** [comment]
Oh, you mean for the session used in the authentication window? It's a pain, but the session is cleared when the app is launched so you can restart it as a workaround for now.

**Comment by zarsky-broad** [comment]
Ah, I see. Close, reopen, and then manually refresh.
