### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [getinsomnia/insomnia#6474]
### Expected Behavior

Twitter logo should be changed to X

### Actual Behavior

Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

Screenshot
<img width="960" alt="Screenshot 2023-09-10 090257" src="https://github.com/Kong/insomnia/assets/91591901/27f3fc06-77ea-4a49-a3fb-13c99b6c7890">

### Reproduction Steps

Scroll to footer section and see twitter old logo

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

@benatkin 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

### Insomnia Version

N/A

### What operating system are you using?

Windows

### Operating System Version

Windows

### Installation method

N/A

**Comment by benatkin** [comment]
reported spam @lalitkumawat1m

**Comment by lalitkumawat1m** [comment]
@benatkin 
I apologize for that. I'm new to open source contribution. Could you please correct me if I'm doing something wrong

**Comment by benatkin** [comment]
@lalitkumawat1m no biggie, I don't see why you tagged me, I am not an owner of this repo, that I know of :)

**Comment by benatkin** [comment]
Also it's early to change the logo to X, the site is still at twitter . com so there's a mismatch between the site and the logo, I think it's less confusing with the old logo until that happens.
