### ISSUE TITLE
Option to import request collections missing

### ISSUE THREAD

**Issue by flower7434** [getinsomnia/insomnia#6479]
### Expected Behavior

Some way to import request collections.

### Actual Behavior

Request collection import option missing. 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

10.0.22621 Build 22621

### Installation method

Installer

### Last Known Working Insomnia version

_It worked a couple a versions ago_

**Comment by filfreire** [comment]
![reqcollection](https://github.com/Kong/insomnia/assets/11976836/434a3112-9ab4-4b7d-8d95-f2c3374f6a5b)

**Comment by flower7434** [comment]
> ![reqcollection](https://user-images.githubusercontent.com/11976836/270971267-434a3112-9ab4-4b7d-8d95-f2c3374f6a5b.jpg)

Not at all what the issue is about. It is about the import feature. But I found a workaround. In the middle top thingy. One can import requests to the currently selected request collection.
