### ISSUE TITLE
[Feature Request] Formatting/beautify GraphQL queries

### ISSUE THREAD

**Issue by chrisvis** [getinsomnia/insomnia#648]
## Details
Having a button to format GraphQL would be great.
In my current workflow I sometimes `Copy as cURL` a call to GraphQL from somewhere and import it into Insomnia. Then I switch the body type to GraphQL Query, which works great.
Having a way to easily format it from there would be nice.

Since GraphiQL has the functionality, the formatting logic should be available already.

**Comment by gschier** [comment]
I believe you're looking for this?

<img width="231" alt="image" src="https://user-images.githubusercontent.com/587576/33669637-e9267da0-da9a-11e7-9cd7-264d0269e088.png">

**Comment by chrisvis** [comment]
Oops, I overlooked that, great!

**Comment by gschier** [comment]
:smile:

**Comment by jdorleans** [comment]
@gschier would that be possible to format the "Query Variables" as well? Also, do we have a shortcut for that?

**Comment by italosantana** [comment]
@gschier does anyone know a shortcut for that on linux?
