### ISSUE TITLE
Importing OpenAPI spec doesn't recognise additional files 

### ISSUE THREAD

**Issue by andrei-dascalu** [getinsomnia/insomnia#6480]
### Expected Behavior

When importing an OpenAPI spec, Insomnia should either:
* allow importing a full folder as opposed to single file
* recognise when imported file references external files for addtional specs.

### Actual Behavior

Importing results in spec with errors like

```
invalid-ref ENOENT: no such file or directory, open './timezone/get.yml'
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

macOS

### Operating System Version

13.5.1

### Installation method

brew

**Comment by andrei-dascalu** [comment]
There was an old issue at: https://github.com/Kong/insomnia/issues/2082 which was closed without a clear resolution and move to a discussion.

The discussion is here: https://github.com/Kong/insomnia/discussions/3749 however the last activity on it was roughly 2 years ago. Since we're talking about a feature of OpenAPI spec, I'd consider still not supporting this after all this time a bug.

**Comment by jackkav** [comment]
Please upvote with the discussions feature to help us prioritise it against other feature requests.

**Comment by andrei-dascalu** [comment]
@jackkav pardon me, but it's unclear exactly how prioritisation works. The issue has 10 upvotes and has been upvoted even before later discussions got more upvotes (now it has 10 upvotes and 43 thumbs up, but largely seems because it's just been forgotten for the past 3 years).
At some point there were discussions that hinted that there was a choice to implement solutions for said support and comments were (shortly) focused on that.
So is it still under evaluation? Was the technical implementation that was initiated there stopped for some reason? What exactly is needed? Just upvotes?
