### ISSUE TITLE
CTRL+Space opens "Select Request" window instead of Auto-complete popup.

### ISSUE THREAD

**Issue by faustool** [getinsomnia/insomnia#6482]
### Expected Behavior

When I'm writing the unit test code and I hit CTRL+Space I expect to see a code assistance popup, similar to what I see in most IDEs.

### Actual Behavior

Instead, Insomnia opens the "Select Request" window to choose a request. I do see some code completions in the foreground (see screenshot) so it seems there's a shortcut overlap somewhere. Also, the window that appears doesn't really seem to be about the request I am working with because it does not change the request when I chose one.

![image](https://github.com/Kong/insomnia/assets/2947769/9e8013f8-b9e2-4803-9419-c5d490e5c97e)

### Reproduction Steps

1. Create at least two requests in the "Debug" tab - I'll call them `Request 1` and `Request 2` forward.
2. Switch to the Test tab and create at least one Test.
  ![image](https://github.com/Kong/insomnia/assets/2947769/ed48509b-8ba5-4bd5-b684-4547d12a10d4)
4. In the `--Select Request--` dropdown, select `Request 1` created in the first step.
  ![image](https://github.com/Kong/insomnia/assets/2947769/9f663b60-8378-499c-bb59-a212d50efdc9)
6. Put the cursor between the parentheses in the `send()` code in the first line.
  ![image](https://github.com/Kong/insomnia/assets/2947769/c4f15c65-894d-4582-b355-545c1d0cc770)
7. Press `CTRL+Space`.
8. The issue should happen now.   
  ![image](https://github.com/Kong/insomnia/assets/2947769/5723ddf3-93c7-4d2f-9548-99756dd4062d)

Optionally...
1. Choose `Request 2` in the `Select Request` popup window that should have not appeared and click `Done`.
  ![image](https://github.com/Kong/insomnia/assets/2947769/6b98dd79-0b1b-4b88-9cdb-4ef45295b58d)
3. See that `Request 1` is still selected in the dropdown box.
  ![image](https://github.com/Kong/insomnia/assets/2947769/3632ce76-cc21-4b0e-a82e-1846a02203be)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise version 22H2 build 22621.2134

### Installation method

Download from https://insomnia.rest/

**Comment by filfreire** [comment]
@faustool this is fixed in a merged PR #6477 and will go out in an upcoming release
