### ISSUE TITLE
Latest versions do not work.

### ISSUE THREAD

**Issue by assertnotnull** [getinsomnia/insomnia#6483]
### Expected Behavior

I expect the app window to show

### Actual Behavior

There's no window showing up and I see only the process in htop.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Linux 5.15

### Insomnia Version

5.8

### What operating system are you using?

Ubuntu

### Operating System Version

zorinOS 16.3 (ubuntu 20.04)

### Installation method

deb package

### Last Known Working Insomnia version

3.0

**Comment by filfreire** [comment]
See https://github.com/Kong/insomnia/issues/6133 https://github.com/Kong/insomnia/issues/6445
