### ISSUE TITLE
Cannot clone Azure DevOps project

### ISSUE THREAD

**Issue by faustool** [getinsomnia/insomnia#6484]
### Expected Behavior

I expect to be able to clone an Azure DevOps git repo project just like any other git repository.

### Actual Behavior

When I try to clone an Azure DevOps repository, I get the error:

```plain
HTTP Error: 404 Not Found, TF401019: The Git repository with name or identifier <reponame>.git does not exist or you do not have permissions for the operation you are attempting.
```

The repository was populated with code using Insomnia itself, from a local collection using the `Git Sync` functionality.
![image](https://github.com/Kong/insomnia/assets/2947769/ce133065-0d6d-496b-8163-eba4cfb6f1c8)

### Reproduction Steps

1. Go to your Azure DevOps `Personal Access Tokens` page.
2. Create a PAT with full Code access: Code (Full); Code(Status). Save it because you cannot get this again later.
  ![image](https://github.com/Kong/insomnia/assets/2947769/7d5a6ea4-ebf4-4e2a-9d7d-7d4f32ea18d4)
3. Go to Insomnia and create an empty collection.
4. Add a few requests to it.
5. Go to the bottom left corner of the screen and select `Git Sync`.
6. Click `Setup Git Sync`.
7. Switch to the `Git` tab and fill in the form:
    * Git URI (https): your Azure DevOps repository clone URL (you can get from the Azure DevOps portal).
    * Author name: your name
    * Author Email: your e-mail
    * Username: the username for the PAT (typically what comes before the `@` sign in the URL)
    * Authentication Token: enter the generated PAT
8. Click `Sync`.
9. Click `Git Sync` again and then `Commit`. Add the commends and commit.
10. Click `Git Sync` again and then `Push`.
11. Go back to the Insomnia home screen.
12. Delete the collection using the ellipsis at the top right corner of the collection card.
13. In the grayed background, click `Git Clone` button.
  ![image](https://github.com/Kong/insomnia/assets/2947769/75b5bed4-bc19-4198-8f4e-febf86715b96)
14. Switch to the `Git` tab and fill in the form:
    * Git URI (https): your Azure DevOps repository clone URL (you can get from the Azure DevOps portal).
    * Author name: your name
    * Author Email: your e-mail
    * Username: the username for the PAT (typically what comes before the `@` sign in the URL)
    * Authentication Token: enter the generated PAT
15. Click `Clone`.
16. 🪳🪰🦟🐜🪲🐞

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I have debugged the Insomnia code using the `Toggle DevTools` window (`Alt+Ctrl+I`) in the desktop application and I found the error happens here: C:\..\AppData\Local\insomnia\app-2023.5.8\resources\app.asar\node_modules\isomorphic-git\index.cjs:7024.

![image](https://github.com/Kong/insomnia/assets/2947769/0488b24a-8130-4f03-b362-d0ec4a33b10c)

The error occurs in the second iteration of the for loop. First it tries using an empty password and then tries with the given PAT.

The HTTP request that fails is `GET https://dev.azure.com/<organization>/<project>/_git/<repo>.git/info/refs?service=git-upload-pack`.

I suspect Azure DevOps does not support this because I also tried using a PAT with Full (really full) access and I got the same error.

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise version 22H2 build 22621.2134

### Installation method

Download from insomnia.rest.

### Last Known Working Insomnia version

First time trying.

**Comment by lucaspereirasouzat** [comment]
same problem here, in old versions this works but on last update stops work, I`m on Linux pop os using .deb

**Comment by lucaspereirasouzat** [comment]
I donwgrade to version 2023.5.7 and works, Its seems something change between 2023.5.8 and 2023.5.7 who stops works with git azure

**Comment by jackkav** [comment]
Before 2023.5.8 it used to first attempt without appending `.git` then append it to the url and retry. 
#6567 will stop adding the .git on the end of the url and perhaps fix the azure problem.
However we may see unindended consequences if we don't put the try mechanic back in as I'm not sure how this will behave on an existing git collection so will need some testing.

**Comment by faustool** [comment]
I updated my Insomnia to version 8.3.0 and I was able to clone the repository.
