### ISSUE TITLE
Regression with showing the Recent Requests modal

### ISSUE THREAD

**Issue by miguelespinoza** [getinsomnia/insomnia#6485]
### Expected Behavior

When triggering the keyboard shortcut "Show Recent Requests" I should see the modal

### Actual Behavior

When triggering the keyboard shortcut "Show Recent Requests" nothing happens

### Reproduction Steps

1. Go to the Keyboard tab under the Insomnia Preferences
2. Verify the keyboard shortcut for "Show Recent Requests", in my case I've updated it to CTRL + E
3. Trigger using the keyboard shortcut and nothing happens

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

macOS

### Operating System Version

Darwin arm64 22.6.0

### Installation method

downloaded from website

### Last Known Working Insomnia version

Can't recall, but it definitely worked about a few weeks ago

**Comment by filfreire** [comment]
Related to https://github.com/Kong/insomnia/issues/6301
