### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by jcervera27** [getinsomnia/insomnia#6488]
### Expected Behavior

there is a problem when I try to post a token

![insomnia issue](https://github.com/Kong/insomnia/assets/144824591/e041de4b-3021-4163-9661-e07146d2ef62)

### Actual Behavior

there is a problem when I try to post a token

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.4.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

google

### Last Known Working Insomnia version

2023.4.0

**Comment by filfreire** [comment]
Related to #2310, see https://github.com/Kong/insomnia/issues/2310#issuecomment-907634020
