### ISSUE TITLE
*-portable.exe application is not "portable"

### ISSUE THREAD

**Issue by JLJTGR** [getinsomnia/insomnia#6490]
### Expected Behavior

[Portable applications](https://en.wikipedia.org/wiki/Portable_application) by nature allow you to use/bring the program and settings in a portable manner.  

I expect to be able to put the *-portable.exe application on a USB drive;
Run the application, create a project, quit;
Remove the USB drive, bring it to another computer;
Run the application and be able to use my previously used settings/projects.

### Actual Behavior

The application is extracted to and run from `%TEMP%`.   (*perhaps forgivable?*)
The application data is permanently saved to `%APPDATA%`.   (*breaks the idea of it being portable*)
Bringing the portable application to another computer does not have the benefits of a portable application.  IE, having the projects/settings available.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I feel like your usage of the word "portable" is a misnomer and I'm not certain what your intended definition is.  I've seen some hints that it may be a "more offline" version?

If you have no intention of making a [truly portable](https://en.wikipedia.org/wiki/Portable_application) version, perhaps there should be a disclaimer somewhere obvious as to what your definition of portable means for Insomnia when trying to download it.

*PS. I'm not looking for cloud syncing.*

### Insomnia Version

Insomnia.Core-2023.5.7-portable.exe

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home; 22H2; 22621.2134

### Installation method

GitHub -> Releases -> Insomnia.Core-2023.5.7-portable.exe

**Comment by filfreire** [comment]
@JLJTGR these are good points, thank you for the heads up.
