### ISSUE TITLE
[Accessibility] Keyboard shortcuts and request creation do not work with screen readers

### ISSUE THREAD

**Issue by RonnyG2121** [getinsomnia/insomnia#6491]
Hello.
I have a problem with the accessibility with Insomnia:
the keyboard shortcuts do not work with screen readers and when I go to create new request
I'm a web developer and I want to use this program.
Thanks so much

**Comment by subnetmarco** [comment]
We have fixed all the shortcut problems in the upcoming Insomnia 9.0, for which there is a beta available now in the [releases](https://github.com/Kong/insomnia/releases). Make sure to download Insomnia, not the CLI application.

**Comment by RonnyG2121** [comment]
Thanks so much.
