### ISSUE TITLE
Git Clone fails with 404

### ISSUE THREAD

**Issue by lucaster** [getinsomnia/insomnia#6492]
### Expected Behavior

Should be able to clone a Git repository from a Git URI that does not end with `.git` (e.g. Azure DevOps)

### Actual Behavior

Cloning fails with the following popup message:

### Error Cloning Repository
HTTP Error: 404 Not Found, TF401019: The Git repository with git identifier my-company-insomnia-repo.git does not exist or you do not have permissions for the operation you are attempting.

### Reproduction Steps

1. Click the `+` on the top right
2. Click the `Git Clone` menu item
3. Select the `Git` tab
4. Fill in all the information
5. Click the `Clone` button

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

It seems that Insomnia is appending the `.git` suffix at the end of the Git URI by default when it's missing (see the popup message). However, our repo's URL looks like this:

`https://my-company-resel.visualstudio.com/ProjectX/_git/my-company-insomnia-repo` 

without `.git` at the end.

As a matter of fact, the command:
```sh
git clone https://my-company-resel.visualstudio.com/ProjectX/_git/my-company-insomnia-repo
```
would succeed.

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment]
Related to #6484, see https://github.com/Kong/insomnia/issues/6484#issuecomment-1736945440
