### ISSUE TITLE
Workspace not found render error after deleting a document

### ISSUE THREAD

**Issue by kobenguyent** [getinsomnia/insomnia#6508]
### Expected Behavior

Delete successfully without any error.

### Actual Behavior

Error is showing

![Screenshot 2023-09-15 at 15 28 45](https://github.com/Kong/insomnia/assets/7845001/c68493b5-81c1-4544-9384-61d576d7dd59)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Version: Insomnia 2023.5.8 Build date: 9/7/2023 OS: Darwin arm64 22.6.0 Electron: 25.2.0 Node: 18.15.0 Node ABI: 116 V8: 11.4.183.23-electron.0 Architecture: arm64

### What operating system are you using?

macOS

### Operating System Version

OS: Darwin arm64 22.6.0

### Installation method

upgrade from older version

**Comment by filfreire** [comment]
@kobenguyent are you still able to reproduce this?

**Comment by kobenguyent** [comment]
Currently not. Will keep an eye on this.

**Comment by filfreire** [comment]
Feel free to reopen or create new issue if you spot the issue again.
