### ISSUE TITLE
Automatic application downgrade from v5.12.4 to v5.12.3

### ISSUE THREAD

**Issue by aprasadh** [getinsomnia/insomnia#651]
Today I installed the application (v5.12.4) using `brew cask install insomnia` command. After I open the application for the first time, the app alerted there is an upgrade(surprised). When I restarted the app to apply the upgrade, I found the app was actually downgraded to v5.12.3.

I could not able to upgrade again by going through the preferences menu and click check update button. I believe this is an issue of downgrading. Please fix it.

Note: I didn't do another `brew upgrade` command option

**Comment by gschier** [comment]
Ah yes, it looks like that version is still marked as a beta release. I'll unmark the version as beta today. 

P.S. You should also disable automatic updates if you installed with Brew.

**Comment by gschier** [comment]
v5.12.4 is now marked as a stable release.
