### ISSUE TITLE
[Feature Request] Add keyboard shortcut to close the Edit Environment modal

### ISSUE THREAD

**Issue by kobenguyent** [getinsomnia/insomnia#6511]
hi, I'd like to have a shortcut to close the environment modal as I don't need to move my mouse and click the button.

![Screenshot 2023-09-15 at 16 42 31](https://github.com/Kong/insomnia/assets/7845001/1e01ba66-3118-4e4a-8cc7-22a2093eca33)

my code could be found here https://github.com/Kong/insomnia/compare/develop...kobenguyent:insomnia:feat-shortcut-close-env-form

I updated the UX a bit, when on Edit mode, press the Esc to exit the edit mode then press the shortcut to save the data, this behavior will be the same like user clicks on the Close button.

**Comment by filfreire** [comment]
Closing, see https://github.com/Kong/insomnia/pull/6518#issuecomment-1735165221
