### ISSUE TITLE
Insomnia is considerably slower with the latest updates (2023.5.X onwards)

### ISSUE THREAD

**Issue by aleksandardespotovskiinteligenta** [getinsomnia/insomnia#6523]
### Expected Behavior

I expect the performance of the application to be smooth, as it was a month ago.

### Actual Behavior

With the latest updates, Insomnia got a lot slower. The GUI lags a lot, and it becomes unusable for large API collections. This became apparent with the updates in the past few weeks. Before that, it was working smoothly.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Downloaded from insomnia.rest

**Comment by Nopraz** [comment]
Same slowness on Arch Linux on version 2023.5.7

**Comment by filfreire** [comment]
Added to [performance issues list](https://github.com/Kong/insomnia/issues?q=is%3Aopen+is%3Aissue+label%3AB-performance)

**Comment by DamonLarcom** [comment]
Tried 8.6.0 and 8.5.1 on Fedora 39, both had considerable lag and were completely freezing at some points

**Comment by lcsmobileqa** [comment]
Just to update, this is still true as of the latest:
Version: Insomnia 8.6.0
Build date: 1/18/2024
OS: Windows_NT x64 10.0.22631
Electron: 28.0.0
Node: 18.18.2
Node ABI: 119
V8: 12.0.267.8-electron.0
Architecture: x64

**Comment by marcelaodev** [comment]
I had to stop using it.
Completely unusable

**Comment by subnetmarco** [comment]
We are looking into this. We have identifies slowness when loading the Dashboard or switching across different Organizations, which we will improve. Any other areas that are slower than expected?

**Comment by THERET-C** [comment]
Unable to use since updating to 9.2, lags for everything.
The loading of the first screen take at least 5min before anything is present inside the app and i can get to my collection.

Version: Insomnia 9.2.0
Build date: 15/05/2024
OS: Windows_NT x64 10.0.19045
Electron: 29.3.0
Node: 20.9.0
Node ABI: 121
V8: 12.2.281.27-electron.0
Architecture: x64

Please patch this as soon as possible.

**Comment by kunu96** [comment]
I was running 2020.5.3 up until Wednesday(6/26/2024) when I basically was forced to update since a feature I needed wasn't working anymore. It wasn't working for a few months, but I had a workaround that my org decommissioned. That feature works with the new version 9.3, but everything takes way too long too load whether its going back to select collections, changing environments within the collections, switching between calls, anything. A click is a guarantee that the app is going to lag and this is very frustrating especially since the old version worked so well.

**Comment by subnetmarco** [comment]
Yes this is very frustrating: we have been undergoing weeks-long performance improvements that haven't shipped yet, but will ship soon because we are almost done with them. Performance has my fullest priority and as such I have allocated engineering resources dedicated specifically to improve the performance of Insomnia.

I am aiming to ship the first batch of performance improvements in upcoming v9.4 within a month.

**Comment by CurryYangxx** [comment]
We've made some performance improvements in recent beta releases, include 'fist time loading dashboard', 'switch between organizations', 'switch between projects'. 
You can download the latest beta version to experience it. Looking forward to your feedback and we will continue to make more optimizations.

**Comment by subnetmarco** [comment]
We have improved performance by up to 20x with the [latest 9.3.3 release](https://github.com/Kong/insomnia/issues/6809#issuecomment-2262902452).

**Comment by chrisciokler** [comment]
Very slow, request gets hang, response takes a long time to show in the UI. I was a big fan, but is a much worse experience now.

**Comment by amanfromfrance** [comment]
I have to say Insomnia has also become difficult to use on a daily basis: response time is really slow, a lot of lags browsing between collections and in the collections.
I am considering switching to another tool even though I think Insomnia is great.

**Comment by subnetmarco** [comment]
> I have to say Insomnia has also become difficult to use on a daily basis: response time is really slow, a lot of lags browsing between collections and in the collections.
> I am considering switching to another tool even though I think Insomnia is great.

@amanfromfrance what version of Insomnia are you using?

**Comment by amanfromfrance** [comment]
> > I have to say Insomnia has also become difficult to use on a daily basis: response time is really slow, a lot of lags browsing between collections and in the collections.
> > I am considering switching to another tool even though I think Insomnia is great.
> 
> [@amanfromfrance](https://github.com/amanfromfrance) what version of Insomnia are you using?

Here is my Insomnia info:
- Insomnia version: 11.2.0 
- OS: Windows Windows_NT x64 10.0.22621
- Electron: 35.1.5
- Node: 22.14.0
- Node ABI: 133
- V8: 13.4.114.21-electron.0
- Architecture: x64

**Comment by subnetmarco** [comment]
> > > I have to say Insomnia has also become difficult to use on a daily basis: response time is really slow, a lot of lags browsing between collections and in the collections.
> > > I am considering switching to another tool even though I think Insomnia is great.
> > 
> > [@amanfromfrance](https://github.com/amanfromfrance) what version of Insomnia are you using?
> 
> Here is my Insomnia info:
> - Insomnia version: 11.2.0 
> - OS: Windows Windows_NT x64 10.0.22621
> - Electron: 35.1.5
> - Node: 22.14.0
> - Node ABI: 133
> - V8: 13.4.114.21-electron.0
> - Architecture: x64
> 

@amanfromfrance thank you! I don't want to ask for too much, but is there a possibility that you could record the application (using QuickTime or any other screen recording tool) to see exactly what you are experiencing?

**Comment by amanfromfrance** [comment]
No problem! I don't know if it will be clear in the quick video but the lag when trying to scroll is really important.

https://github.com/user-attachments/assets/7b84c1f7-3ea7-42f2-844d-8e46231348a7

**Comment by subnetmarco** [comment]
Thanks @amanfromfrance , @gatzjames will follow up.

**Comment by gatzjames** [comment]
Hi @amanfromfrance,

Is there any details you could share about your collection?
Could you share any logs with us or specific errors that are shown in the console?
I have a collection with ~9k requests and multiple levels of folders and nesting and I don't notice any lag:

https://github.com/user-attachments/assets/42e01166-93d3-466f-88ad-21365576cff1

**Comment by gbrennon** [comment]
> We are looking into this. We have identifies slowness when loading the Dashboard or switching across different Organizations, which we will improve. Any other areas that are slower than expected?

me too... it was so slow that even clicking in a request is doesnt modify the interface
