### ISSUE TITLE
response is missing content-type and cannot be preview

### ISSUE THREAD

**Issue by atliuhui** [getinsomnia/insomnia#6543]
### Expected Behavior

use plugin, support add content-type to response headers

### Actual Behavior

![Snipaste_2023-09-21_20-58-25](https://github.com/Kong/insomnia/assets/446457/150b3753-2a65-4c6f-928d-2628ff6b958d)
![Snipaste_2023-09-21_21-12-42](https://github.com/Kong/insomnia/assets/446457/fe15b6f7-dd4d-40aa-b8f8-d31ed18cc2d7)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.5

### What operating system are you using?

Windows

### Operating System Version

Windows 11 专业版

### Installation method

insomnia.rest

**Comment by filfreire** [comment]
@atliuhui can you reproduce this with latest Insomnia release?
Also can you share a public example request that we can use to reproduce?

**Comment by atliuhui** [comment]
```
Version: Insomnia 8.2.0
Build date: 2023/10/4
OS: Windows_NT x64 10.0.22621
Electron: 25.8.1
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.29-electron.0
Architecture: x64
```
upgraded, the same problem

I write a mock project (based on aspnetcore net6) <https://github.com/atliuhui/debug-insomnia>
Insomnia run the `http://localhost:5188/sample.jpg`
@filfreire
