### ISSUE TITLE
Unable to sign in using email

### ISSUE THREAD

**Issue by gyles** [getinsomnia/insomnia#6555]
### Expected Behavior

I'm able to signin using email

### Actual Behavior

Unable to sign in using email. Getting error "Error getting email checked"

### Reproduction Steps

1. Click on 'Login'
2. Log in as normal.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.6

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment]
@gyles thanks for reporting this, we had planned downtime that is taking just a little bit longer than expected. Please try again in a couple of hours.

**Comment by suparsana21** [comment]
Hello, already wait and still can't login

**Comment by fleetimee** [comment]
yup same issue ends up exporting my workspace logout and then using no login environment

**Comment by saschaglo** [comment]
I can't authenticate against github also. I think there is a major problem on their side regarding some endpoints, i.e. the one that is used to fetch infos for the authentication: https://api.insomnia.rest/v1/oauth/github/config, it's gone as well...

**Comment by rick-bongers** [comment]
Users with a teamplan is also broken.. Insomnia now asks for a subscription for all users.

**Comment by Xephi** [comment]
Can confirm that as well, Insomnia website redirect me to subscription page when i try to login. (note i'm part of an organization with a team subscription plan.)
If i go back to home page/ dashboard, got this error :
```json
{
  "status": 500,
  "statusText": "Internal Server Error",
  "internal": false,
  "data": {
    "errors": [
      "Failed to fetch organization list"
    ]
  }
}
```

**Comment by StuzoAccounts** [comment]
I'm the owner of our account and I can log-in, but 

- some users cannot log-in (error screenshot below) even though I see their email in the "collaborators" list
- some users can log-in but cannot get past the subscription page even though we already have a subscription (which is paid up)
- we are paid up for 68 seats/users, but we now only have 50 seats and 64 collaborators

![Screenshot 2023-09-25 at 8 28 42 AM](https://github.com/Kong/insomnia/assets/97699651/0d9c16fb-c875-4691-ad69-c1e56653283b)

**Comment by awestphal** [comment]
Is there any advance in this topic? We have a team plan but I'm forced to select a new? subscription after login. Insomnia app ask for reauthentication to use Insomnia Sync but there is no token after login - only selection of the subscription...

**Comment by august-bay1** [comment]
We are also having issues with email login of collaborators directing them to sign up for a subscription. And I can only page through the first 50 collaborators in an org that has 71.

**Comment by subnetmarco** [comment]
Hello, when inviting collaborators to an organization in Insomnia they will be asked to choose a subscription if they didn't have one, but they can choose "Free" and continue to your organization.

It's a little bit like GitHub: I can be a "Free" user on GitHub, but if an "Enterprise" organization invites me to collaborate, I can go ahead and collaborate under their "Enterprise" umbrella.

Therefore a user can always collaborate on every organization in Insomnia, even if they are "Free" on their personal account, because their seat on the organization that they have been invited to, it has already already been paid by the owner of that organization.

Does this help clarify the situation? Let me know if you have further questions.

**Comment by subnetmarco** [comment]
@pavkout Do you know why we are getting "Error getting email checked" in this case?

**Comment by awestphal** [comment]
@subnetmarco Thanks, that worked for us.

Every Team member has to login an choose the "Free plan" although they were already part of an organization of an paid subscription. That's suprising. 
After that every team member has to create a new token for the Insomnia app to enable Insomnia sync again.

**Comment by wladimirgrf** [comment]
The same thing happens to me, I'm stuck outside the application and if I try to use the scratch pad, it's a blank workspace.
No collections or requests.

**Comment by SergioSuarezGil** [comment]
same for me in insomnia 8, I loved insonia many years ago for its simplicity of use and it was also very light, but after the latest updates, I have definitely decided to return to postman...

**Comment by subnetmarco** [comment]
Turns out that "Error getting email checked" happens when logging in with SSO. Can you try to login with a regular email address instead? @gyles

**Comment by gyles** [comment]
@subnetmarco I don't have SSO configured, and I'm certain I was not logging in with SSO. fwiw, I'm able to log in via email now.

**Comment by Yazdanifard** [comment]
Hello everyone. We have a Team plan, but we cannot log in to Insomnia via SSO or the company email section; neither of these options is working. We can only log in using the standard user account, and it prompts us to select a plan. I read we have to choose the Free plan and it then shows the subscription. However, I think it is not user-friendly and confuses people!

![image](https://github.com/Kong/insomnia/assets/2929490/5edbfad8-579a-410a-a505-1a32d5debc54)
