### ISSUE TITLE
The verify code for login comes too late, so login is impossible.

### ISSUE THREAD

**Issue by qkrwnsgh1288** [getinsomnia/insomnia#6559]
### Expected Behavior

When I login, I am requested to input verify code.
However, the code comes after more than 3 minutes, so I can't log in. 
Check please. I'm using "daum.net" mail.

### Actual Behavior

When I login, I am requested to input verify code.
However, the code comes after more than 3 minutes, so I can't log in. 
Check please. I'm using "daum.net" mail.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.6.0

### What operating system are you using?

macOS

### Operating System Version

macos

### Installation method

homebrew

**Comment by qkrwnsgh1288** [comment]
Verify code seems to be valid for 3 minutes. However, when I send a login request, the verify code arrives in the email 3 minutes later, so I keep getting the expired error and can't log in. 
This email works fine for email-linked logins on github and other websites. Please do not reply that there is a problem with my email.
I am currently paying for a monthly subscription, but I am not able to use the service at all. This is a serious issue. Please look into this as soon as possible.

**Comment by subnetmarco** [comment]
We incremented the code timeout to 30 minutes.
