### ISSUE TITLE
[Feature Request] Allow the horizontal divider resize the GraphQL query and its variables

### ISSUE THREAD

**Issue by mandx** [getinsomnia/insomnia#656]
- Insomnia Version: 5.12.4
- Operating System: Ubuntu 17.10

## Details
Currently, when crafting GraphQL queries, the variables section automatically expands to fully contain the JSON object being edited. This is fine for small objects, but for large mutation inputs the query section becomes way to small to edit the query comfortably.

This could be also configurable, using a checkbox in the settings dialog, or placing that checkbox right next to the variables editor.

In any case, the focus I guess would be maintain the usability of the query editor, even for large query variables objects.

**Comment by gschier** [comment]
Hi @mandx,

I think I understand the problem, but can you post a screenshot to clarify the issue you're facing?

**Comment by mandx** [comment]
@gschier Yes, sorry, I should have added some screenshots with this. 

Here is how it looks with vertical layout off:
![Vertical Layout Off](https://user-images.githubusercontent.com/535282/33905345-2cf8ad40-df33-11e7-80db-af7d80e33991.png)

And I specify the state of the vertical layout setting because I just tried it now to see if it improves things, but it is actually worse, the query area is completely gone now (apparently, is all the way on top of the input area):
![screenshot from 2017-12-12 11-37-12](https://user-images.githubusercontent.com/535282/33905620-13459bd2-df34-11e7-8408-2752ee7df385.png)

This is my actual display resolution, with Insomnia's window maximized.

I understand GraphQL makes things a bit harder, in the sense of that, with REST we have a line of text (the URL) paired with a JSON blob/payload. With GraphQL we have a query, which is multi line text, also paired with a JSON blob/input. For example, a variation of the vertical layout could be having the query and the input laid out horizontally, on top of the response (just an idea, I guess that would look good in this resolution, don't know about others...)

**Comment by mandx** [comment]
@gschier Is this issue in consideration?
