### ISSUE TITLE
GitHub Connection does not work

### ISSUE THREAD

**Issue by sdernbach-ionos** [getinsomnia/insomnia#6563]
### Expected Behavior

The authentication flow just starts after clicking "Authenticate with GitHub"

### Actual Behavior

It shows (config 404):

An error occurred!
Please retry the authorization flow.

### Reproduction Steps

1. Click Create
2. Click Git Clone
3. Click "Authenticate with GitHub"
4. Error is happens cause the config API endpoint returns 404

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.4.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.4.1

### Installation method

download from insomnia.rest

**Comment by subnetmarco** [comment]
@jackkav can you take a look at this?

**Comment by jackkav** [comment]
This should be fixed in the backend API now.
