### ISSUE TITLE
Error when to login

### ISSUE THREAD

**Issue by mirket999** [getinsomnia/insomnia#6574]
### Expected Behavior

I should be able to login using my credentials

### Actual Behavior

It directs me to we browser:
`Log Into Your Account

Please login via your web browser.
A new page should have opened in your default web browser. To continue, please login via the browser.

If it did not open, copy and paste the following URL into your browser:`

Then once I provide email, it sends a verification code. After filling with code, I get:
![image](https://github.com/Kong/insomnia/assets/70580818/57bc46d4-fbf1-4b3c-b899-d2c634ead6a9)

### Reproduction Steps

Click on Login button
Follow the steps via web browser
Get the error

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise

### Installation method

insomnia.rest

**Comment by filfreire** [comment]
Hi @mirket999 what is the complete URL is returning the 404 for you?

**Comment by subnetmarco** [comment]
What login method are you trying to use to Login? @mirket999

**Comment by pavkout** [comment]
@mirket999 It should be working properly now, in case you still have any problem please let us know.

**Comment by mirket999** [comment]
> Hi @mirket999 what is the complete URL is returning the 404 for you?

Hi, this is the URL that application forwards me.
[Insomnia](https://app.insomnia.rest/app/auth-app/?loginKey=9o9A%2Bkf1KMySNsB1nOLW14mOGlFHlBhQ%2FuWDVp9yMiQ%3D)

**Comment by mirket999** [comment]
> What login method are you trying to use to Login? @mirket999

I click on Login in the app, it forwards me to login page in web browser.
![image](https://github.com/Kong/insomnia/assets/70580818/74826923-f2e4-4d86-b69b-6c414fd48910)

then I go with "Continue with email"
![image](https://github.com/Kong/insomnia/assets/70580818/4a710970-b7c6-4ba5-80a5-6f46cef9522a)

Then it sends a verification code to my email. Once I enter the code I get 404

**Comment by mirket999** [comment]
> @mirket999 It should be working properly now, in case you still have any problem please let us know.

Still getting same error

**Comment by mirket999** [comment]
Now it seems to be resolved

**Comment by johanrosenson** [comment]
@pavkout i get this error now.

**Comment by pavkout** [comment]
@johanrosenson Sorry for the delayed response, what login option you are using?
