### ISSUE TITLE
Double Click to Rename not working after the update to 8.0.0

### ISSUE THREAD

**Issue by sri-vr** [getinsomnia/insomnia#6580]
### Expected Behavior

Double Click to Rename should be working

### Actual Behavior

Double Click to Rename not working, User needs to right click and hit rename , there isnt any shortcut as well

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8

### What operating system are you using?

macOS

### Operating System Version

Ventura

### Installation method

insomnia.rest

**Comment by subnetmarco** [comment]
@jackkav Let's take a look here.

**Comment by SaintPeter** [comment]
I am having this same issue on Windows 10.

Version: Insomnia 2023.5.8
Build date: 9/7/2023
OS: Windows_NT x64 10.0.19631
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

Double clicking the name of the request in the list doesn't allow me to rename it. I actually came here to open a feature request, but found this bug instead.

**Comment by subnetmarco** [comment]
This regression was introduced in August with the rewrite of the sidebar. We will fix it soon, more of these will be fixed in 8.2 this week.

**Comment by ShadiestGoat** [comment]
F2 shortcut also doesn't work for this, hope to see it in 8.2!

**Comment by subnetmarco** [comment]
@ShadiestGoat 8.2 is out, let me see if we can fix these regressions in 8.3
