### ISSUE TITLE
Cannot log in "Invalid code: Unexpected plaintext response"

### ISSUE THREAD

**Issue by ryber** [getinsomnia/insomnia#6581]
### Expected Behavior

open Insomnia and do some work locally.

### Actual Behavior

After updating to 8.0.0

When I try to SSO it goes to redirect to insomnia but doesn't log in. When I do the manual step of entering the token manually I get an error of "Invalid code: Unexpected plaintext response". I am using the exact thing copied from https://app.insomnia.rest/app/authorize/insomnia-redirect

All of my workspaces are gone because all I have is this "scratchpad" thing.

![unexpected](https://github.com/Kong/insomnia/assets/145359/6afb27d4-5162-4354-8bbd-ecab75fbefc8)

### Reproduction Steps

1. Open Insomnia
2. click "continue with x (github in my case)
3. enter passphrase
4. it redirects to insomnia "Authorizing Insomnia"
5. since it didn't do anything, go back to the web and click "Manually enter token" (it says it copied it)
6. go back to insomnia and paste token
7. error "Invalid code: Unexpected plaintext response"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I don't want my data in your cloud, I don't care if its encrypted. I don't need to work with anyone else.

### Insomnia Version

 8.0.0

### What operating system are you using?

macOS

### Operating System Version

13.2.1 (22D68)

### Installation method

download

### Last Known Working Insomnia version

7

**Comment by gatzjames** [comment]
👋 @ryber can you try again and reproduce this issue?
We faced some issue with our api which should be solved now!

**Comment by ryber** [comment]
It works now @gatzjames thank you.

Unfortunately, I can only use this for personal projects now as my employer has banned developers from using Insomnia due to the recent changes.
