### ISSUE TITLE
Why 8.0 free plan remove "Native Git Sync" ?? 

### ISSUE THREAD

**Issue by LCLLL** [getinsomnia/insomnia#6583]
### Expected Behavior

"Native Git Sync" it should be free to use ! 

### Actual Behavior

This is a very unique feature that can be used without even having to log in to an account, which is very protective for individual users’ data security. Well now, everything has become a fee ! Too disappointed !

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura

### Installation method

auto upgrade from 5.7

**Comment by lucaspereirasouzat** [comment]
same here, I don't know why this bad decision, I use for 2 years this feature and now is paid

**Comment by CleverCoder** [comment]
Yeah. Bad.

**Comment by obukhow** [comment]
Very bad decision. I think this is the death of the app and community

**Comment by Rzpeg** [comment]
Git Sync does not incur any server cost, no idea why it went behind the paywall.
Because of MIT license, I hope someone forks it and fixes it.

**Comment by subnetmarco** [comment]
In 8.0 we are shipping Organizations with Git sync, which is the old way to manage multiple people working together: https://konghq.com/blog/product-releases/insomnia-8-0

When using Git sync, your data will stay in the repository but you will need an account. Exactly how you need an account to comment on GitHub.

**Comment by lucaspereirasouzat** [comment]
> In 8.0 we are shipping Organizations with Git sync, which is the old way to manage multiple people working together: https://konghq.com/blog/product-releases/insomnia-8-0
> 
> When using Git sync, your data will stay in the repository but you will need an account. Exactly how you need an account to comment on GitHub.

We understand that some features should be paid as the part of teams with synchronization with the cloud and the part of ai, but the part of git has nothing to do because we are using another service that for us makes sense. @subnetmarco, some of us uses for own use and won't shares with a company

**Comment by marciodiasdeveloper** [comment]
Bad, Too disappointed!

**Comment by lucaspereirasouzat** [comment]
this screen is a big problem ![image](https://github.com/Kong/insomnia/assets/36778572/38090a2b-e16c-478a-9267-a1ccc9979830)

and the only one of the four options is required upgrade plan 
![image](https://github.com/Kong/insomnia/assets/36778572/26a6d343-ec45-44db-818e-8edf2d86154d)

**Comment by LCLLL** [comment]
> In 8.0 we are shipping Organizations with Git sync, which is the old way to manage multiple people working together: https://konghq.com/blog/product-releases/insomnia-8-0
> 
> When using Git sync, your data will stay in the repository but you will need an account. Exactly how you need an account to comment on GitHub.

I know, I know ...... 
But can you tell us how to use git sync function in free plan? Does it mean you can only spend money to upgrade? Thanks

**Comment by flleeppyy** [comment]
git features shouldn't be a paid thing, wth

this isn't okay

**Comment by JohnStarich** [comment]
Agreed. I understand the desire to make money here, but _removing_ an essential feature from the free and open source client is a sure-fire way to kill enthusiasm from the open source community.

Git is free and open source, hosting isn't paid for by Insomnia/Kong, and this worked before without a paywall. In the short term this is an opportunity cost, in the long term this is a dwindling user base cost. Please, please reconsider.

**Comment by trbtm** [comment]
You could switch to [https://github.com/ArchGPT/insomnium](https://github.com/ArchGPT/insomnium) and avoid problems like this.

**Comment by dungmv** [comment]
switch to bruno to use git sync

**Comment by nabsha** [comment]
Just installed Insomnia for a new project, looked for Git Sync, realised product direction, No place for Insomnia in my setup any more. 
Uninstalling. 
Bye bye Insomnia.

**Comment by ericksonlargura** [comment]
We had a great time together. Goodbye Insomnia! 😞

**Comment by rafetkhallaf** [comment]
Very unfortunate. I just noticed this on my new machine. We were actually considering upgrading earlier this year to have the team collaboration stuff. I understand we don't have the right to tell people how to run their business and we appreciate the application being available all these years, but we do not appreciate the way it was done. We are definitely going to consider a different solution tomorrow.

They could have limited the number of repos as free and anything over x would have to be paid subscription. Again, as the others has well put it, Farewell Insomnia!

**Comment by joaodematejr** [comment]
any alternative ?

**Comment by dungmv** [comment]
@joaodematejr recommend Hoppscotch

**Comment by flleeppyy** [comment]
Yeah hoppscotch is a wonderful alternative.
