### ISSUE TITLE
I can't find any of my projects / requests after upgrading. Bombarded with "LOGIN". No.

### ISSUE THREAD

**Issue by CleverCoder** [getinsomnia/insomnia#6584]
### Expected Behavior

Run Insomnia. See my list of requests / projects.

### Actual Behavior

See aggressive attempts to sign up for cloud sync. I see no way to get to all my saved requests. Extremely frustrated.

### Reproduction Steps

Run Insomnia.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

What has happened? Insomnia used to be the developer-friendly alternative to Postman. Now it's just as bad. I can't support for much longer.

### Insomnia Version

8

### What operating system are you using?

macOS

### Operating System Version

Latest

### Installation method

Automatic update

### Last Known Working Insomnia version

Unsure

**Comment by bendersej** [comment]
Likewise, **I see no way to get to all my saved requests** – this is a *very* sad day for Insomnia – it seems to have been hit with enshittification. 

After Postman, followed with Insomnia, my journey continues, looking for the next "Save these HTTP requests in a UI and allow me to run them"

I would gladly pay a one-time fee, say, 30€ – but not 5€/month to run software locally that AFAIK does not incur any server costs.

EDIT: Insomnia was kind enough to keep the links available for [the previous version: 2023.5.8](https://github.com/Kong/insomnia/releases/tag/core%402023.5.8)

**Comment by gdinko** [comment]
This is crazy , all requests are gone . Does anybody know where insomnia stores the data on mac os ?

**Comment by Rzpeg** [comment]
Wow, that's a sad day for Insomnia for sure.
All the things from "Free" tier (except for cloud sync or whatever) should be accessible WITHOUT LOGIN.

**Comment by Leeloo5E** [comment]
> This is crazy , all requests are gone . Does anybody know where insomnia stores the data on mac os ?

You can find the data in ~/Library/Application Support/Insomnia

See for other OS too: https://docs.insomnia.rest/insomnia/application-data

**Comment by choas** [comment]
I thought Postman is worse, but updating to a new version and afterwards everything is gone - really?
The only solution is to stay on 2023.5.8 until some plugins break.

And all those moving lines are also very disturbing.

**Comment by apalfonso-fln** [comment]
I was able to workaround this by installing an earlier version on top of 8.0, then turning off the auto update. Running the older version shows my old config. wew.

**Comment by subnetmarco** [comment]
You can:

* Export your data (during the onboarding wizard, we are shipping 8.1 to make it easy to do.
* Use Scratch Pad (local with no account needed).
* Create a Free account on Insomnia, exactly how you did in GitHub to be able to comment here.

**Comment by petterroea** [comment]
I used insomnia because it wasn't a commercial piece of garbage like postman. that was your only real selling feature. **Not being prompted to log in all the time was Insomnia's only real selling point**
