### ISSUE TITLE
New 8.0.0 theme has colors that are hard to read

### ISSUE THREAD

**Issue by softlandia** [getinsomnia/insomnia#6586]
### Expected Behavior

After upgrade do not have prev formatting sample

### Actual Behavior

Extremely inconvenient formatting of a response json for a dark schema
[picture](https://ltdfoto.ru/image/y3pWzR)
And this is indeed an error - since it is impossible to read the answer

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 8.0.0
Build date: 9/27/2023
OS: Darwin arm64 21.6.0
Electron: 25.8.1
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.29-electron.0
Architecture: arm64

### Insomnia Version

8.0.0

### What operating system are you using?

macOS

### Operating System Version

Monteray

### Installation method

upgrade from prev

**Comment by softlandia** [comment]
Select simple dark -- success

**Comment by softlandia** [comment]
select other theme

**Comment by subnetmarco** [comment]
There are many other themes you can choose from in "Preferences".

**Comment by subnetmarco** [comment]
Fixed in 8.2 released a few hours ago.
