### ISSUE TITLE
Updating to 8.0 has lost all my queries

### ISSUE THREAD

**Issue by lonpalmer** [getinsomnia/insomnia#6592]
### Expected Behavior

I don't have an account (and I don't want one).  All the queries I had previously are now gone after upgrading to 8.0.

I expect my queries to be there.

### Actual Behavior

They are not there. 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Upgarde to 8.0

### Insomnia Version

8.0

### What operating system are you using?

macOS

### Operating System Version

Macos Catalina

### Installation method

download install

### Last Known Working Insomnia version

<8.0

**Comment by CoolGoose** [comment]
@lonpalmer see https://github.com/Kong/insomnia/issues/6585 at least downgrade worked for me

**Comment by roberto-filho** [comment]
Same problem here. MacOS user too, Ventura version

**Comment by subnetmarco** [comment]
You can downgrade to a previous version https://github.com/Kong/insomnia/releases.

**Comment by lonpalmer** [comment]
So the CTO Tells me to downgrade and then closes the issue?  What a bunch of ...

**Comment by subnetmarco** [comment]
@insomnia-infra Or create an account, the same way you created one on GitHub to comment here.

Or export your data and re-import the data, here is [a video too](https://www.loom.com/share/de7af6f9e06b4452a799a033604f9270?sid=df0baa8f-8916-4560-a8aa-6fe9ba21b0ec).

**Comment by subnetmarco** [comment]
@lonpalmer Or create an account, the same way you created one on GitHub to comment here.

Or export your data and re-import the data, here is [a video too](https://www.loom.com/share/de7af6f9e06b4452a799a033604f9270?sid=df0baa8f-8916-4560-a8aa-6fe9ba21b0ec).

**Comment by somegenericdev** [comment]
@subnetmarco has the thought that HTTP requests contain sensitive information that people don't want to hand over to your greedy datamining ass ever crossed your mind?
It's not too late to back down from this beyond stupid decision. The reason Insomnia has an userbase to begin with is that Postman basically committed suicide when it did the same thing.

**Comment by subnetmarco** [comment]
@somegenericdev The data (unlike Postman) is end-to-end encrypted. We are not moving data in the cloud to look into it, we are moving data in the cloud to remove technical debt and provide collaboration capabilities.

And by the way, you can still use Insomnia in local-only mode: https://www.loom.com/share/de7af6f9e06b4452a799a033604f9270?sid=df0baa8f-8916-4560-a8aa-6fe9ba21b0ec

And if you use Git sync, data is never in the cloud even with an account.

**Comment by somegenericdev** [comment]
@subnetmarco 
> The data (unlike Postman) is end-to-end encrypted. We are not moving data in the cloud to look into it

Yeah and I'm 5 meters tall. You don't believe me? You should, I'm telling you that's the way it is.

> we are moving data in the cloud to remove technical debt and provide collaboration capabilities.

Corporate babble nonsense. If you didn't want to look into it you would just let us store them locally. Anyone with half a brain can tell that when a company pulls a stunt like this they're up to no good.

> And if you use Git sync, data is never in the cloud even with an account.

But I don't want an account, I just want an HTTP client for Christ's sake.

**Comment by subnetmarco** [comment]
> Yeah and I'm 5 meters tall. You don't believe me? You should, I'm telling you that's the way it is.

I don't about that, but you can get in touch with our team to learn about the security controls of Insomnia.

**Comment by somegenericdev** [comment]
@subnetmarco 
> I don't about that, but you can get in touch with our team to learn about the security controls of Insomnia.

There is nothing for me to learn. Not my computer, not my source code, not my keys, not my data. 
You can impress the average technologically illiterate person with this meaningless corpobabble nonsense but I think you forgot this is a tool for developers.

**Comment by subnetmarco** [comment]
> Not my computer, not my source code, not my keys, not my data.

Then you can use local Scratch Pad, or Git Sync, where you have full control.

**Comment by roberto-filho** [comment]
Since this is closed, I am guessing there will not be a fix for this? Just workarounds?
I won't be able to just upgrade my insomnia and have all my data back?

I am also confused why the issue was closed since the issue is still there 🤔

**Comment by roberto-filho** [comment]
FYI: another issue has been created for this same problem: https://github.com/Kong/insomnia/issues/6585

**Comment by lonpalmer** [comment]
> @lonpalmer Or create an account, the same way you created one on GitHub to comment here.
> 
> Or export your data and re-import the data, here is [a video too](https://www.loom.com/share/de7af6f9e06b4452a799a033604f9270?sid=df0baa8f-8916-4560-a8aa-6fe9ba21b0ec).

I trust Github.

**Comment by up209d** [comment]
Kong ve scared the sh*** out of hella developers, luckily I found my collections back. I didn't even need my coffee this morning.
