### ISSUE TITLE
Error importing data from 2023.5.8 to 8.0.0

### ISSUE THREAD

**Issue by jasoncoon** [getinsomnia/insomnia#6593]
### Expected Behavior

Data (workspaces, requests, etc) to be imported.

### Actual Behavior

I get the following error:

```
Application Error
Failed to render. Please report to [our Github Issues](https://github.com/Kong/insomnia/issues)

Project not found.
Try to reload the app
Error: Project not found.
  at a2 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-334620de.js:17:108051)
  at Module.l (file:///Applications/Insomnia.app/Contents/Resources/app.asar/import-9dfc1356.js:1:906)
  at async d8 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-334620de.js:31:3691)
  at async Be (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-334620de.js:30:18468)
```

### Reproduction Steps

1. Export data from Insomnia 2023.5.8
2. Import data to Insomnia 8.0.0
3. Get error

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS 13.5.2 (22G91)

### Installation method

Originally installed from dmg file, it was automatically upgraded to 8

### Last Known Working Insomnia version

2023.5.8

**Comment by subnetmarco** [comment]
@jackkav let's look into this.

**Comment by jackkav** [comment]
Should be solved by 8.1.0, please confirm @jasoncoon

**Comment by jasoncoon** [comment]
Well, I no longer get an error, but it doesn't seem to have imported anything.

I clicked the Scratch Pad drop down, chose Import, selected my export file, clicked Scan. It shows:

```
Import to "Insomnia" Project

INSOMNIA RESOURCES TO BE IMPORTED:
4 Workspaces
526 Requests
3 OpenAPI Specs
9 Environments with 4 Cookie Jars
```

I clicked Import, the modal disappears, but I don't see any of my workspaces, requests, etc.

**Comment by jasoncoon** [comment]
I don't see any errors or mention of the import in the `/Users/jasoncoon/Library/Logs/Insomnia/main.log` file. In renderer.log, I do see a lot of the following line:

```
[2023-09-29 07:51:39.858] [info]  No session expiry found undefined
```

**Comment by jasoncoon** [comment]
OK, progress. I launched Insomnia 2023.5.8, but it had updated to 8.1 automatically, even though I have the option unchecked. So I re-downloaded and installed it, exported just one workspace, which I was then able to import to the scratch pad in 8.1.

```
Import to "Scratch Pad" Workspace

INSOMNIA RESOURCES TO BE IMPORTED:
1 Workspace
107 Requests
1 OpenAPI Spec
6 Environments with 1 Cookie Jar
```

Now all the requests from that workspace are available in 8.1.

Questions:

1. What about my other workspaces?
2. Does scratch pad not support multiple workspaces? If not, shouldn't it warn me about that?
3. Am I not able to create multiple local workspaces without logging in?
4. If I never plan on logging in, how do I get rid of the purple banner at the top?

**Comment by subnetmarco** [comment]
For the banner, that will be dismissible in 8.2 next week.

**Comment by filfreire** [comment]
@jasoncoon closing this one. Some answers to the last questions you posed:

1. Other workspaces you'll need to either create account and login or import the contents of each workspace sequentially into scratchpad

2. Scratchpad does not support multiple workspaces.

3. Without logging in you could in older versions of insomnia pre-8.0.0. Today we'll be launching 8.3.0 version, which will bring back local only projects, but you would still need to login.

4. Purple banner can be dismissed since 8.2 release


Feel free to report other feedback, issues and other problems you face.
