### ISSUE TITLE
Insomnia 8 can't find my projects

### ISSUE THREAD

**Issue by mfortuno-keap** [getinsomnia/insomnia#6596]
### Expected Behavior

Open Insomnia, be able to use my projects

### Actual Behavior

When Insomnia opens, there's just a bunch of login options but none of my projects can be found

### Reproduction Steps

1. Open Insomnia
2. Cannot find how to open projects and use the application
3. Only see login options. I don't think i was using any of those in previous versions.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.6

### Installation method

download

### Last Known Working Insomnia version

2023.?

**Comment by sdkuck** [comment]
Revert to 2023.5.7 and find a good fork.

**Comment by gdw2** [comment]
This suggestion (download the previous version off github releases) worked for me.  https://github.com/Kong/insomnia/issues/6594#issuecomment-1739748908

**Comment by subnetmarco** [comment]
@mfortuno-keap you can:

* Create an account or login.
* Export your data and re-import one collection inside of Scratch Pad.

**Comment by xarses** [comment]
All my projects are also gone.

Forcing me to create an account is not acceptable.
Forcing me to reimport only one collection is also not ok.

Automatically doing any of this with no communication is also not OK

If you want us to use your application you need to be far more transparent about what your doing and why.

**Comment by subnetmarco** [comment]
Here is a video that shows how to import or export data, and use it locally too:

[Watch video](https://www.loom.com/share/de7af6f9e06b4452a799a033604f9270?sid=df0baa8f-8916-4560-a8aa-6fe9ba21b0ec)
