### ISSUE TITLE
[Feature Request] Don't show "UNKNOWN" for 200

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#660]
- Insomnia Version: v5.12.4
- Operating System: Ubuntu 17.10

## Details

Hi there!

Some frameworks like Spring Boot don't return the "OK" text for a successful request on their response header, as you can see here:

![screenshot from 2017-12-13 23-23-36](https://user-images.githubusercontent.com/12160864/33970980-32986c92-e05d-11e7-8c19-247d3f75045f.png)

The response was `HTTP/1.1 200` without the "OK" text, so Insomnia shows in the UI the "200 UNKNOWN" label, which scares a little bit.

I would like to suggest to show just the `200` label if the response header doesn't have an additional text, or even `200 OK` to make the user happy.

Best regards,
Rafael Pacheco.

Edit: Maybe this change could be applied to all the 2** family as well.

**Comment by gschier** [comment]
Thanks for submitting this @rafaelrenanpacheco. I think I agree with you that a missing status message should just display nothing 😄 👍
