### ISSUE TITLE
In dark mode, integer values are hard to read

### ISSUE THREAD

**Issue by exotexot** [getinsomnia/insomnia#6603]
### Expected Behavior

Data should be readable.

### Actual Behavior

Numbers are hard to read.

![Screenshot 2023-09-29 at 10 49 13](https://github.com/Kong/insomnia/assets/10153413/32384209-82e2-4c05-9d58-059e277f747f)

### Reproduction Steps

Make a post request with JSON body.
Add Numbers as values.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.1

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.0

### Installation method

Insomnia.rest

**Comment by subnetmarco** [comment]
This will be updated next week in 8.2

**Comment by subnetmarco** [comment]
8.2 is out: https://insomnia.rest/changelog
