### ISSUE TITLE
Upgrade to 8.1.0 ScratchPad cannot import *** UPDATED ****

### ISSUE THREAD

**Issue by mcdonop** [getinsomnia/insomnia#6607]
### Expected Behavior

Cannot import external collections into scratchpad.  

### Actual Behavior

There is no menu or button on the UI to import... at least did not see.  The only place I saw an import option is in Settings but it is disabled.

### Reproduction Steps

Goto Settings, Click on the Data tab
Import to the "Insomnia" project is not enabled

<img width="1278" alt="Screenshot 2023-09-29 at 9 37 10 AM" src="https://github.com/Kong/insomnia/assets/10000277/f168bbd8-319f-43f3-b9d2-011bffd46776">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.1.0

### What operating system are you using?

macOS

### Operating System Version

Monteray

### Installation method

brew.sh 2023.5.8 then did upgrade from Insomnia notification

### Last Known Working Insomnia version

2023.5.8

**Comment by jackkav** [comment]
Top left corner
<img width="224" alt="image" src="https://github.com/Kong/insomnia/assets/3679927/4cee5b60-8556-4dca-bc4c-7e05993267ed">

**Comment by mcdonop** [comment]
Why did you close... is what you sent in scratchPad and not signed in????????

I do not see that menu... I am using ScratchPad and I am not signed in.

<img width="1278" alt="image" src="https://github.com/Kong/insomnia/assets/10000277/b1fcb7c0-335a-4339-8f42-6ce6588769f2">

**Comment by subnetmarco** [comment]
Click the Scratch Pad drop-down menu on the top left corner. It will appear there. @mcdonop

**Comment by Igorgro** [comment]
@subnetmarco no, there is nothing here:
![image](https://github.com/Kong/insomnia/assets/22894169/2e11d8fc-3dec-47bc-8518-62c50fcbc538)

why it is impossible to create a workpaces and collections without signing in?

**Comment by subnetmarco** [comment]
@Igorgro you can create up to one collection in the Scratch Pad without signing in, potentially you can have them across multiple folders.
