### ISSUE TITLE
8.0.1 No Import, ScratchPad without Signin

### ISSUE THREAD

**Issue by mcdonop** [getinsomnia/insomnia#6608]
### Expected Behavior

see https://github.com/Kong/insomnia/issues/6607

### Actual Behavior

see https://github.com/Kong/insomnia/issues/6607

### Reproduction Steps

see https://github.com/Kong/insomnia/issues/6607

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.10

### What operating system are you using?

macOS

### Operating System Version

Monteray

### Installation method

brew

### Last Known Working Insomnia version

2023.5.8

**Comment by subnetmarco** [comment]
Here is a video that shows how to do it (at 1:30): https://www.loom.com/share/de7af6f9e06b4452a799a033604f9270

Can you confirm this works?

**Comment by Igorgro** [comment]
@subnetmarco no, it is not working as exected, because it imports all workspaces and request collection into that one scratchpad

**Comment by subnetmarco** [comment]
> because it imports all workspaces and request collection into that one scratchpad

You can either import them into the local Scratch Pad, or use the collections with an account.

This is how the Scratch Pad looks like:

<img width="1727" alt="Screenshot 2023-10-02 at 7 30 58 AM" src="https://github.com/Kong/insomnia/assets/964813/fac1a013-6508-4df9-8c49-ac37b5e9bd0f">

And this is how logging in looks like:

<img width="1728" alt="Screenshot 2023-10-02 at 7 31 26 AM" src="https://github.com/Kong/insomnia/assets/964813/1c68b04b-9c36-4e44-8fa9-6b561fab205e">

**Comment by ttelford** [comment]
Not a viable option - I paid for a subscription specifically *because* I cannot use anything that syncs or uses a sign-in, and I wanted to ensure development continues (ie. fund it). I need the features you've just cut off.

Not syncing is a *hard requirement* for my employment, and you've effectively given me the finger by downgrading the software to complete uselessness. How do I request a refund for the tool I paid for and can no longer use?

**Comment by subnetmarco** [comment]
You can ask for refund by making a request to `support@insomnia.rest`. 

I understand that E2EE is not an option for you, even when in the cloud. That seems to be the case for many users and an erroneous understanding that a fully end-to-end encrypted (E2EE) solution would have been _okay_.

As such, we are prioritizing "Local Vault" which will give the option to choose if the projects should be in the cloud or local-only, but we will need until mid-October to release it.

**Comment by ttelford** [comment]
> I understand that E2EE is not an option for you, even when in the cloud. That seems to be the case for many users and an erroneous understanding that a fully end-to-end encrypted (E2EE) solution would have been _okay_.

Realize that there are organizations that have different threat models; and strict control of data ingress and egress from the network is one of them.

Another is that data "in the cloud" is considered _forever_, and it's best to assume a nonzero chance of compromise. No problem, it's encrypted, right?

It's looking likely that quantum computing capable of breaking that encryption is going to be possible to nations or powerful organizations in a decade or so; some of us have data that those would be _very_ interested in.

The elliptic curve encryption that's en vogue for key exchange these days is also _much_ weaker to Shor's Algorithm than RSA or Diffie-Hellman is.

**Comment by subnetmarco** [comment]
Here is an updated discussion: https://github.com/Kong/insomnia/discussions/6626
