### ISSUE TITLE
[Bug] Error: Checksum for Cask 'insomniax' does not match.

### ISSUE THREAD

**Issue by roymunsonstudios** [getinsomnia/insomnia#661]
- Insomnia Version: brew cask install insomnia
- Operating System: macOS High Sierra

## Details

When I run the command `brew cask install insomniax` I get the following error:

```
Error: Checksum for Cask 'insomniax' does not match.

Expected: abbf4b27e86da934042a1dcedd339ffb59e16c4aa8e0c0d44534533be42e3efb
Actual:   41bb5e02515df87a2e6d8463508fa3f95853739445bfdcb9cf429bf9702ddd4f
File:     /Users/<MY_USERNAME>/Library/Caches/Homebrew/Cask/insomniax--2.1.8.tgz

```
I ran `brew update` but the error still occurred. 
I also ran `brew doctor`, but there was no error except for: 
```
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.
```
So I doubt the problem is with my particular installation of homebrew or homebrew-cask. 

A similar problem to this has been reported before: https://github.com/getinsomnia/insomnia/issues/288

Update: Just a few minutes ago, I installed cask-repair and used it to update the insomniax cask by following the instructions in this URL: https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask

When I ran `cask-repair insomniax`, I was given the following prompt: `Type the new version (or leave blank to use current one, or use `s` to skip)`. I just typed in "s" to skip. 

Now when I run: `brew cask install insomniax` I get the following error: 

Error: Checksum for Cask 'insomniax' does not match.

```
Expected: abbf4b27e86da934042a1dcedd339ffb59e16c4aa8e0c0d44534533be42e3efb
Actual:   7c927330495c49417683acc1cd91854e32f569268924070b4afe765ef0471c97
File:     /Users/<MY_USERNAME>/Library/Caches/Homebrew/Cask/insomniax--2.1.8.tgz
```

However, the string of letters and numbers next to "Actual" changes everytime.

**Comment by gschier** [comment]
Hi @roymunsonstudios,

I'm not sure what `insomniax` is. Insomnia should be installed using the `brew cask install insomnia`.

**Comment by gschier** [comment]
Closing this as it seems to have been reported to the wrong project or the wrong package name was being used.
