### ISSUE TITLE
Insomnia 8.0.0 violates Apple's Semantic Versioning Specification

### ISSUE THREAD

**Issue by NoahRJ** [getinsomnia/insomnia#6612]
### Expected Behavior

On macOS, when installing the Insomnia major update over an existing install of the previous major, Insomnia 2023.X, the major update should be versioned in such a way that it allows straightforward installation from the prior version.

Previous Insomnia major releases were all versioned `2023.X.X`, and the newest release is `8.X.X`.

Below are possible examples for how to achieve expected behavior:
- Versioning increments from `2023.5.8` to `2023.8.0` or `2023.8.0.0` so it is recognized as a newer version
- The bundle identifier should be changed from `com.insomnia.app` to something else, so it is seen as a different app introducing different versioning
- The application bundle name should be changed from `Insomnia.app` to something else, so it is seen as a different app introducing different versioning

### Actual Behavior

While Insomnia can update itself from `2023.X.X` to `8.X.X`, enterprise software deployment methods on macOS use semantic versioning when determining whether or not to upgrade an existing app with an identical bundle name (`Insomnia.app`) and bundle identifier (`com.insomnia.app`).

That means when evaluating an existing Insomnia install, major version `2023` is always seen as greater than major version `8`, so `2023` is viewed as the newer update and `8` is never installed.

This violates [Apple's standards](https://developer.apple.com/documentation/packagedescription/version), which follows the [Semantic Versioning Specification](https://semver.org/#semantic-versioning-specification-semver).

> To achieve predictability, the semantic versioning specification proposes a set of rules and requirements that dictate how version numbers are assigned and incremented.

Versions should **always** be incremented if you're maintaining the same key information for your app bundle (name and ID).

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

macOS

### Operating System Version

macOS 11/12/13/14

### Installation method

insomnia.rest

**Comment by subnetmarco** [comment]
Ah, nice find @NoahRJ cc @filfreire

**Comment by filfreire** [comment]
After some investigation, there's not much we can do at the moment, closing this one for now, we can reopen at a later time if needed.
