### ISSUE TITLE
Lack of request names after update

### ISSUE THREAD

**Issue by pilotpirxie** [getinsomnia/insomnia#6614]
### Expected Behavior

See the URL as the request name when name is empty (like it was done before)

### Actual Behavior

Empty name, nothing is shown

![Screenshot 2023-10-01 at 00 11 37](https://github.com/Kong/insomnia/assets/10637666/a9561b84-7991-456e-978e-040a4bea8278)

### Reproduction Steps

1. Create an empty request
2. Fill the url
3. You should see the URL as the name

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

For rapid request creation it was valuable to have the option to skip naming and have just a bunch of URLs to change. I don't care about their names as their URLs are verbose enough to tell me what they represent

### Insomnia Version

v8.1.0

### What operating system are you using?

macOS

### Operating System Version

All

### Installation method

Web

**Comment by subnetmarco** [comment]
Hi @pilotpirxie do you confirm there were custom names before the migration? Or did it just show the URL of the request?

**Comment by pilotpirxie** [comment]
Yes, before migration it showed the URL of the request and now I lost that and my huge collection is useless as I can't navigate.
