### ISSUE TITLE
Unable to hide purple login banner

### ISSUE THREAD

**Issue by jarne** [getinsomnia/insomnia#6621]
### Expected Behavior

Be able to close/ignore the login banner using a button

### Actual Behavior

No way to get the login banner disappear

### Reproduction Steps

1. Open app
2. Open local scratch pad
3. There it is:

<img width="1139" alt="Bildschirmfoto 2023-10-02 um 15 00 05" src="https://github.com/Kong/insomnia/assets/15860314/1aa0c1d4-56e7-45f8-a0a4-374953fefbe3">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Not having to login is the reason I switched from Postman to Insomnia

### Insomnia Version

8.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS 14.0 (23A344)

### Installation method

Homebrew

### Last Known Working Insomnia version

before 8.0.0

**Comment by filfreire** [comment]
Fixed in https://github.com/Kong/insomnia/pull/6620
