### ISSUE TITLE
An update on local projects

### ISSUE THREAD

**Issue by subnetmarco** [getinsomnia/insomnia#6627]
Please check [https://github.com/Kong/insomnia/discussions/6626](https://github.com/Kong/insomnia/discussions/6626)

**Comment by suchislife801** [comment]
# Yeah, OR...

## Last Working Version! Sort Order Fix!
### Also, everything that used to work, works on this version.
# [2023.4.0](https://github.com/Kong/insomnia/releases/tag/core@2023.4.0)
### ANY version ABOVE 2023.4.0 will absolutely WRECK your sort orders.

**Comment by designbyadrian** [comment]
> You will need an account with Local Vault

**Comment by jsejcksn** [comment]
@subnetmarco Is it still possible to use Insomnia after v8

- with all of the local features from before v8
- without having to register with your company (e.g. logging in)
- and without sending any telemetry to your company?

If the answer is _"No, it's not possible"_, then are there plans to restore that functionality? I'm not interested in changing my workflow — I'd just like a direct answer to the above.

**Comment by subnetmarco** [comment]
Local projects are back in 8.3: https://github.com/Kong/insomnia/discussions/6626#discussioncomment-7299800

**Comment by jsejcksn** [comment]
> Local projects are back in 8.3: https://github.com/Kong/insomnia/discussions/6626#discussioncomment-7299800

@subnetmarco After quickly reading through that lengthy post, the only bit I saw which relates to my question is this:

> Scratch Pad is still there, and is local by default and does not require an account.

It looks like at this point in time the answer is "_No, we have no plans to allow users to continue using any of Insomnia's features beyond Scratch Pad without an account._" Is that accurate? Scratch Pad's organizational and functional capabilities are severely restricted in comparison to Insomnia pre-v8.x.

Please help me understand by providing a direct answer to my question.

**Comment by subnetmarco** [comment]
You need an account for everything that is not Scratch Pad. Having an account doesn't mean your project data is in the cloud anymore with 8.3+, that depends on what storage you choose for your projects (and Git also doesn't store your data in the cloud).

The account data is secured in Auth0 (compliant with GDPR, HIPAA, HITECH, CSA STAR, ISO 27001/27018, PCI DDS, SOC2).

You can use the application offline with Local Vault projects after logging-in the first time, in case you lose access to the public Internet for a period of time.

I hope this answers all your questions.

**Comment by jsejcksn** [comment]
@subnetmarco Thanks for a direct answer. Before v8.x, Insomnia offered a number of features beyond what's available in Scratch Pad without requiring an account. Why are they now artificially restricted unless the user registers with your company and logs in?

**Comment by subnetmarco** [comment]
Sure - Insomnia is a large product and an expensive operation to run. In order to finance the continued development of the product in every form (OSS, free and premium plans) we need to make sure that we can convert enough users over time in order to run a sustainable operation. Kong has been subsidizing for years an **unprofitable** operation: 75% or PRs of Insomnia are from Kong employees in the last 12 months. As we hire more people because we want to keep investing in the product, this number will increase.

So to do that we have learned that users that create an account are more likely to engage - over time - with premium capabilities that in turn allows us to continue the development of the project for all users, even for the ones that don't engage with those capabilities. This is pretty much it, and if it was possible for us to run this operation sustainably without requiring an account, of course we would choose it (why wouldn't we?).

The reality is that this situation will be the same for every product that has the complexity, support requirements and ambition as Insomnia does, we are just being upfront and straightforward about it now. I do believe that the inability to have local projects prior to 8.3 was legitimately hurting users with certain requirements (even paying users!), which is why we brought it back with a very fast turnaround.

I hope this clarifies why we are offering most capabilities after creating an account (which can be a Free account) vs without an account (Scratch Pad). Based on this, you may even argue that Scratch Pad actually hurts Insomnia (probably does), but we decided to keep it for users that need a quick API client and don't need the bells and whistles of the full product, and also don't want (or can't) create an account.
