### ISSUE TITLE
Post SSE  send a GET SSE

### ISSUE THREAD

**Issue by jgcb00** [getinsomnia/insomnia#6636]
### Expected Behavior

Normally should send a post request, and list all event received
This should be working several time

### Actual Behavior

At start, it always send a GET request : 
![image](https://github.com/Kong/insomnia/assets/36531554/00ca91d3-c3f8-4b56-b38e-c1a868b3084d)

Then I can not send any request again, nothing is sent

### Reproduction Steps

1.create a SSE request
2. Select POST
3. Close Insomnia
4. Open Insomnia
5. Send the request (click on connect)
6. Look at the server logs
7. Try again, it looks beugy

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.1

### What operating system are you using?

Ubuntu

### Operating System Version

ubuntu 23.04

### Installation method

AppImage

**Comment by jackkav** [comment]
SSE standard does not allow POST. We may support this in the future.

**Comment by Judy0406-CJ** [comment]
would be better to disable `POST` option if it doesn't support

**Comment by Liu-Da** [comment]
I also face the same problem when using insomnia to call OpenAI (GPT3.5) /v1/chat/completions API and returns SSE Response. This is my biggest obstacle currently in switching from postman to insomnia.

**Comment by jackkav** [comment]
Related: #7182

**Comment by subnetmarco** [comment]
OpenAI with SSE and streaming enabled:

![Screenshot 2024-04-09 at 4 07 05 PM](https://github.com/Kong/insomnia/assets/964813/7391ca5c-5a26-4fcb-a70d-57dff3e37a32)
