### ISSUE TITLE
please remove google analytics

### ISSUE THREAD

**Issue by softwareunscrewifier** [getinsomnia/insomnia#665]
google analytics is an invasion of the privacy

**Comment by softwareunscrewifier** [comment]
at the very least, make it possible to disable for the privacy conscious user?

**Comment by gschier** [comment]
Thanks for the concern @softwareunscrewifier. There is already an option in the app preferences to disable tracking. 

<img width="317" alt="image" src="https://user-images.githubusercontent.com/587576/34109944-79b30910-e405-11e7-94c9-cb55dd019715.png">

**Comment by softwareunscrewifier** [comment]
please, any chance to make this OptIn instead of opt out? or at the VERY LEST, Ples ask on first launch, so I won't be tracked before I get to disable it?
if you insist on OptOut, then please present it straight up the way JetBrains or Firefox does it: (WE WOULD LIKE TO SHARE INFORMATION TO ANALYTICS TO SPY ON YOU, and then offer SHARE/DONT" SHARE before it actually starts?)

I am privacy concerned.

**Comment by jackTaw88** [comment]
@gschier I did not see this option. I am using 6.3.2 version.
