### ISSUE TITLE
In 8.0 we are shipping Organizations with Git sync, which is the old way to manage multiple people working together: https://konghq.com/blog/product-releases/insomnia-8-0

### ISSUE THREAD

**Issue by LCLLL** [getinsomnia/insomnia#6656]
In 8.0 we are shipping Organizations with Git sync, which is the old way to manage multiple people working together: https://konghq.com/blog/product-releases/insomnia-8-0

When using Git sync, your data will stay in the repository but you will need an account. Exactly how you need an account to comment on GitHub.

_Originally posted by @subnetmarco in https://github.com/Kong/insomnia/issues/6583#issuecomment-1738963967_
            
I know, I know ......
But can you tell us how to use git sync function in free plan? Does it mean you can only spend money to upgrade? Thanks

**Comment by filfreire** [comment]
Hi @LCLLL, under free plan it's not possible. Git Sync is only available under Team subscription, see https://github.com/Kong/insomnia/issues/6624#issuecomment-1747294730 and https://insomnia.rest/pricing
