### ISSUE TITLE
[Request] please consider moving your enterprise code out of client?

### ISSUE THREAD

**Issue by softwareunscrewifier** [getinsomnia/insomnia#666]
it seems you have included enterprise code in the client?

**Comment by gschier** [comment]
You are correct. The sync client code is indeed part of this open source repository. 

[Transparency](https://insomnia.rest/transparency/) is a huge priority of the Insomnia project and I think the inclusion of this code aligns with that. All the code included in the final build of the application can be seen and inspected in this repository. I think that benefits everyone involved.

If you want to elaborate on the reasons behind your request, I would be happy to discuss further.
