### ISSUE TITLE
Looped in updates

### ISSUE THREAD

**Issue by RobinHerzog** [getinsomnia/insomnia#6662]
### Expected Behavior

Do not ask me to update the software 10x times per days

### Actual Behavior

It asks me to update it and kandji too

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

macOS

### Operating System Version

Mac

### Installation method

dmg

**Comment by filfreire** [comment]
@RobinHerzog thanks for reporting this. You can disable auto-updates in the Preferences. For the update notifications you'll still likely get notified when there's new versions by design.

**Comment by StephenWetzel** [comment]
My work around for this was to add this line to my `/etc/hosts` file.
```
0.0.0.0         updates.insomnia.rest
```
