### ISSUE TITLE
Error while importing insomnia

### ISSUE THREAD

**Issue by gustavolio** [getinsomnia/insomnia#6674]
### Expected Behavior

Import collection exported from old version of insomnia (before 8)

### Actual Behavior

The following error appears even with an unique file:
![image](https://github.com/Kong/insomnia/assets/25930243/cc44c127-933a-40df-810d-e7b4591d791b)

### Reproduction Steps

1 - Open insomnia on scratchpad (without log in)
2 - Click on "Scratch Pad" on the left menu
3 - Import option
4 - Drop the collection exported from old version of insomnia with the extension .json
5 - Click on "Scan"
6 - The error appears

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.2.0

### What operating system are you using?

macOS

### Operating System Version

macOs Sonoma 14.0

### Installation method

homebrew

### Last Known Working Insomnia version

2023.5.8

**Comment by gustavolio** [comment]
The problem was solved after creating an account and log in. So, do we have to create an account to import collections?

**Comment by filfreire** [comment]
@gustavolio yes. The other alternative would have been to import "sequentially" the different workspaces (collections).

Please feel free to report other issues you face.

**Comment by gustavolio** [comment]
I think that is important alert the user about the necessity of login, because my .jseon has only one collection.

Thank you! @filfreire
