### ISSUE TITLE
Cannot Login, asking me for a passphrase that I dont have.

### ISSUE THREAD

**Issue by tulindor** [getinsomnia/insomnia#6678]
### Expected Behavior

Been using insomnia since version 2 what loved most of you is the lack of login and account creation, so i've been using insomnia without account.

Currently acepted to create an account with my github but is not working at all.

### Actual Behavior

Ask me for a passphrase that I dont have since i've created my account with github.

### Reproduction Steps

Create a new account with github
Enter insomnia
Press login
Login with github
Redirect to a page with "enter passphrase" 
I dont have that...

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro

### Installation method

Downloaded from  insomnia

**Comment by JonFP** [comment]
I have the same problem but on a Mac.  Insomnia updated itself just as I was about to give a live demo (not goodness) and once updated all my projects had disappeared.  Like the OP I tried to log in via GitHub and it just doesn't work. Always cycles round asking for a token.

<Updated>
Tried just using an email sign in instead - same problem.

**Comment by filfreire** [comment]
@tulindor @JonFP sorry for the bad experience. Please see and perhaps try the steps mentioned in another similar issue: https://github.com/Kong/insomnia/issues/6683#issuecomment-1761398540

**Comment by HardcoreSoftware12** [comment]
I faced the similar problem then i reset the passphrase where it that all data will be lost.
But nothing happened I got all my projects without loosing them. just reset the passphrase

**Comment by pavul** [comment]
is time to change to another rest client, it was pretty good, but when it asked for login and you lost all your endpoints, it was bad,

**Comment by JeiKeiLim** [comment]
> I faced the similar problem then i reset the passphrase where it that all data will be lost. But nothing happened I got all my projects without loosing them. just reset the passphrase

Do not try this if anyone comes to see this and might be a good idea to try. I did reset the passphrase and everything was gone. Now I have to start from scratch.

-- Update

I thought it was gone but it was under Preferences -> Data -> unassigned project. So do reset if you have not set the passphrase it will be there

**Comment by qlereboursBS** [comment]
What an UX ...

> I thought it was gone but it was under Preferences -> Data -> unassigned project. So do reset if you have not set the passphrase it will be there

**Comment by tulindor** [comment]
I've ended up migrating to a similar well known tool by disgrace... but i've loved the old way to work with insomnia, don't know if its back or not, but i had to re do all my api's lost on insomnia by this issue.

**Comment by qlereboursBS** [comment]
IMO it's not back. I just lost all my data. Insomnia was ruined when they started to make all the sync / account features. It's not that the features are bad, it's that the way it's implemented makes it bad.
I'll just move to something else now

**Comment by kokoshneta** [comment]
> [@tulindor](https://github.com/tulindor) [@JonFP](https://github.com/JonFP) sorry for the bad experience. Please see and perhaps try the steps mentioned in another similar issue: [#6683 (comment)](https://github.com/Kong/insomnia/issues/6683#issuecomment-1761398540)

So the only way to use Insomnia when you created your account _in one of the ways listed on the login screen_ is to recreate your account from scratch and lose (or at least risk losing) all your data?

If creating an account via GitHub doesn’t generate or require setting up a passphrase, which it doesn’t (or at least didn’t when the people commenting on this thread set up their account), then it is **absolutely insanely bad UX** to completely lock down the app behind this nonexistent passphrase. Pure insanity.
