### ISSUE TITLE
Event stream request is always using GET method

### ISSUE THREAD

**Issue by natsu12** [getinsomnia/insomnia#6682]
### Expected Behavior

When I was making an event stream request, I had chosen to use POST method. But Insomnia made a GET request.

### Actual Behavior

![image](https://github.com/Kong/insomnia/assets/7494889/555bc4ff-98a2-45dd-af29-bd129c785e8b)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 8.2.0
Build date: 10/4/2023
OS: Darwin x64 22.6.0
Electron: 25.8.1
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.29-electron.0
Architecture: x64

### Insomnia Version

Insomnia 8.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.5.2 

### Installation method

dmg

**Comment by jackkav** [comment]
> SSE standard does not allow POST.

https://stackoverflow.com/a/34285526

**Comment by filfreire** [comment]
Closing given https://github.com/Kong/insomnia/issues/6682#issuecomment-1759483092

**Comment by jackkav** [comment]
Related: #7182
