### ISSUE TITLE
After updating to MACOS Sonoma, my projects/requests are gone

### ISSUE THREAD

**Issue by zinyosrim** [getinsomnia/insomnia#6683]
### Expected Behavior

See all my requests and folders

### Actual Behavior

I'm asked to login and enter a passphrase which I don't know.  All my projects are missing
<img width="1373" alt="image" src="https://github.com/Kong/insomnia/assets/17767575/82ee824c-3bf4-4f0a-b3ce-31ef6e94f042">

### Reproduction Steps

Launch Insomnia

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.2.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma

### Installation method

app was already installed, probably via website

### Last Known Working Insomnia version

no idea

**Comment by danbeaumont95** [comment]
Same has happened to me on same OS! So frustrating.

**Comment by filfreire** [comment]
@zinyosrim @danbeaumont95 I would suggest you do the following, assuming both of you do not remember the passphrase:

- Press the button on the bottom that says "Export your Data" to export any data that is still stored locally but not being shown. Be sure to save that data somewhere.

- Recreate your Insomnia account. You can do this by logging in on https://app.insomnia.rest using the "Continue with Email" option, go to preferences, and delete your account, and then creating a new one with the same mail. Be sure to save your new passphrase in a safe place.

- With the new account, try to login on the Insomnia app, and the reimport the data export you had.

Alternatively, you can also:

- Import one or more of your previous collections from the data export into scratchpad sequentially
- OR, you can downgrade to [2023.5.8](https://github.com/Kong/insomnia/releases/tag/core%402023.5.8) and disable automatic updates on Insomnia preferences to be able to work locally for now.

Later today we will also release version 8.3 that will bring back the chance to have local-only projects after user has logged in.

**Comment by danbeaumont95** [comment]
> @zinyosrim @danbeaumont95 I would suggest you do the following, assuming both of you do not remember the passphrase:
> 
> * Press the button on the bottom that says "Export your Data" to export any data that is still stored locally but not being shown. Be sure to save that data somewhere.
> * Recreate your Insomnia account. You can do this by logging in on https://app.insomnia.rest using the "Continue with Email" option, go to preferences, and delete your account, and then creating a new one with the same mail. Be sure to save your new passphrase in a safe place.
> * With the new account, try to login on the Insomnia app, and the reimport the data export you had.
> 
> Alternatively, you can also:
> 
> * Import one or more of your previous collections from the data export into scratchpad sequentially
> * OR, you can downgrade to [2023.5.8](https://github.com/Kong/insomnia/releases/tag/core%402023.5.8) and disable automatic updates on Insomnia preferences to be able to work locally for now.
<img width="1416" alt="Screenshot 2023-10-13 at 14 16 49" src="https://github.com/Kong/insomnia/assets/73340749/9278bd91-ef01-45fb-886f-485b9f66c2b3">

> 
> Later today we will also release version 8.3 that will bring back the chance to have local-only projects after user has logged in.

This is not helpful, I have a password etc, and the screen i'm on has no 'export your data' button, it is the usual insomnia page where i can make requests

**Comment by filfreire** [comment]
@danbeaumont95 check if you see your data on the other Project you have there on the list:

![Screenshot 2023-10-13 142943](https://github.com/Kong/insomnia/assets/11976836/a0d474ec-9df0-40cb-b048-a85867131b2b)

**Comment by danbeaumont95** [comment]
> @danbeaumont95 check if you see your data on the other Project you have there on the list:
> 
> ![Screenshot 2023-10-13 142943](https://user-images.githubusercontent.com/11976836/274915038-a0d474ec-9df0-40cb-b048-a85867131b2b.png)

Thats perfect, its all there! Thanks for your help :)
