### ISSUE TITLE
Insomnia RPM conflicts with other eletron-builder built RPMs 

### ISSUE THREAD

**Issue by mhdonnelly** [getinsomnia/insomnia#6687]
### Expected Behavior

Installation of Insomnia RPM via dnf on Fedora succeeds without issue.

### Actual Behavior

The transaction test fails due to build-id metadata included in the RPM conflicting with other installed electron apps. In my case the other app was Draw.io

```
Error: Transaction test error:
  file /usr/lib/.build-id/89/f07820c764ddf1e4ea2494649e20709363714a from install of insomnia-2023.5.8-1.x86_64 conflicts with file from package draw.io-21.6.8-1.x86_64
  file /usr/lib/.build-id/93/3f573c7b0e0cc9fd421bcde32e8e95ab9fcd63 from install of insomnia-2023.5.8-1.x86_64 conflicts with file from package draw.io-21.6.8-1.x86_64
  file /usr/lib/.build-id/a2/f25a35770678a0c1e2edf73ee74f3bbef49da2 from install of insomnia-2023.5.8-1.x86_64 conflicts with file from package draw.io-21.6.8-1.x86_64
  file /usr/lib/.build-id/c8/5e5b51e479004d07d1512708dddee0a83bc042 from install of insomnia-2023.5.8-1.x86_64 conflicts with file from package draw.io-21.6.8-1.x86_64
  file /usr/lib/.build-id/d9/af197bfc9985e842cb0aa3b43ecb37132f13d5 from install of insomnia-2023.5.8-1.x86_64 conflicts with file from package draw.io-21.6.8-1.x86_64
```

### Reproduction Steps

The following steps likely apply to any RPM based Linux distribution. FOr reference, I am encountering the issue on Fedora 37.

1. Install draw.io RPM from https://github.com/jgraph/drawio-desktop/releases/download/v22.0.2/drawio-x86_64-22.0.2.rpm
2. Attempt to then install Insomnia RPM

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 37

### Installation method

Attempting to install RPM using dnf

**Comment by filfreire** [comment]
@mhdonnelly thank you for reporting this and for submitting the PR with a fix, we'll try to get it merged in time for one of the upcoming releases.
