### ISSUE TITLE
Clicking "Settings" for a specific request in the local Scratch Pad leads back to the "Welcome Screen"

### ISSUE THREAD

**Issue by dwiyatci** [getinsomnia/insomnia#6698]
### Expected Behavior

Clicking "Settings" for a specific request in the local Scratch Pad should lead to the settings for the request.

### Actual Behavior

As the title says. Screenshots:
<img width="415" alt="Screenshot 2023-10-16 at 20 21 53" src="https://github.com/Kong/insomnia/assets/4405796/573fafa5-9137-4b48-b9b6-475c5527e0c0">
<img width="1008" alt="Screenshot 2023-10-16 at 20 26 41" src="https://github.com/Kong/insomnia/assets/4405796/899b20d6-6c33-4b7f-b50b-8fe1e9a95d91">

### Reproduction Steps

1. Go to any particular request and open the request's menu.
2. Click on 'Settings'.
3. See bug

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.0

### Installation method

homebrew

### Last Known Working Insomnia version

7.X

**Comment by wesleyeff** [comment]
I'm also seeing this issue. I need to change the body render functionality in a request and can't because of this bug.
