### ISSUE TITLE
[Question] Any interest in an Insomnia plugin that would allow for faker type value creation?

### ISSUE THREAD

**Issue by iDVB** [getinsomnia/insomnia#670]
Just thinking it would be cool to have many of the values in our queries be dynamic, similar to how faker can generate things like...
First name, last name, phone number etc.

https://github.com/marak/Faker.js/

**Comment by gschier** [comment]
That sounds like it could be super useful. The API also looks like it would map to a template tag fairly easily too.

```
{% faker 'name', 'firstName' %}
{% faker 'address', 'country' %}
...
```

**Comment by iDVB** [comment]
@gschier my thoughts as well. However, I'm new to Insomnia and wasn't sure something like this already existed or not or if it would work implementing as a plugin. 

I'm more then happy to take a peak though, if the interest / options are there.

**Comment by gschier** [comment]
There's nothing very similar to this yet.

Another plugin was created recently that does essentially the same thing (maps a Node.js module to a plugin). I suggest taking a look at it because this one would require a very similar approach: https://github.com/Gabb1995/insomnia-plugin-customtimestamp/blob/master/index.js

**Comment by iDVB** [comment]
Cheers, already looking at it. Back in a few...

**Comment by iDVB** [comment]
@gschier wait.... I can't seem to find examples of using plugin template tags inside the GQL request? How is this does from the app itself? I can only seem to get it to work in the Request URL or Header values.

**Comment by gschier** [comment]
You can only use template tags in the variables section of a graphql request. So, you'd have to create a GraphQL variable that uses the plugin, then reference that in your query.

**Comment by iDVB** [comment]
@gschier Ah. Less then ideal. 
Any interest in extending template tag usage into the body of the request?

What if your request is creating an array of things, each needing a unique name? I'd hate to have to create n:1 variables just to make that happen.

Going to hold off on the plugin for now. Was hoping to bash it out today, but its not feasible for our team to have to manually create variables for each dynamic value we want to inject.

**Comment by gschier** [comment]
Can you post some examples of where you want to use a template tag in our GraphQL query? 

The reason it doesn't support it is because I imagined there would be a lot of scenarios where using Insomnia template syntax (`{{ ... }}` and `{% ... %}`) would break the GraphQL syntax, causing linting errors and breaking GraphQL autocomplete.

**Comment by iDVB** [comment]
@gschier Well take my example above...
Ideally, you would not want to test/call your endpoint/methods with the same data each time...
```
mutation createVideo {
  createVideo(
		title: {% faker.lorem.sentence %}, 
		description: {% faker.lorem.paragraph %}, 
		duration: 30000, 
		hasFull: {% faker.random.boolean %}, 
		hasDistilled: {% faker.random.boolean %}, 
		isEspresso: {% faker.random.boolean %}, 
		isFeatured: {% faker.random.boolean %}, 
		isPublished: {% faker.random.boolean %}, 
		isPublic: {% faker.random.boolean %}, 
		recordedAt: {% faker.date.past %}, 
) {
    id
    title
  }
}
```

Agree'd that how it would need to be implemented would be to add a step before the parser that would inject those values. Ideally, it would need to work with many types, String, Int etc.  I'm not familiar with how Insomnia works internally, so not sure how something like this could be done. 

But to be transparent, I actually expected that when I was typing in the body and at the start of typing a value, that `Control+Space` would work to call out the template dropdown which would allow to select one. Then I expected that the GQL query would have those pill looking variable placeholders where the var would be injected, just like the Request URL area does.

**Comment by gatopan** [comment]
👍

**Comment by rafaelrenanpacheco** [comment]
Would be nice if fake data generation were native. Even better if I could choose what fake data I want by using autocomplete dropdown, maybe with a ctrl+shift+space shortcut. This dropdown would list all fake generators available (name, surname, creditcard, etc), and after selecting one, it would have a nice colored box in the json body, just like environment variables. Maybe something like:

```json
{
  "name": fake:name,
  "credit-card": fake:credit-card
}
```

Imagine that on the Insomnia land page screenshots. Oh boy.

**Comment by rafaelrenanpacheco** [comment]
![the office no gif-source](https://user-images.githubusercontent.com/12160864/38473839-972ac960-3b6c-11e8-94a0-3891a0ad961b.gif)

**Comment by gschier** [comment]
That makes me laugh every time, even after all these years.

**Comment by bbbco** [comment]
I actually had the idea to create a Faker wrapper plugin for Insomnia today. Just so happens I came across this thread while looking through the issues for something else unrelated. I recently published the plugin on NPM. https://www.npmjs.com/package/insomnia-plugin-faker

Enjoy!

Brian

**Comment by Gabb1995** [comment]
There is also this which is similar but uses Chance.js https://www.npmjs.com/package/insomnia-plugin-chance

**Comment by gschier** [comment]
Nice one @bbbco!

**Comment by rafaelrenanpacheco** [comment]
Wonderful!

**Comment by starx** [comment]
@bbbco How can I pass date format to your plugin?

**Comment by gschier** [comment]
@starx you may have better luck posting your question to the repo directly: https://github.com/bbbco/insomnia-plugin-faker#readme
