### ISSUE TITLE
[Feature Request] Local-only environment for private or secret variables

### ISSUE THREAD

**Issue by wonderbeyond** [getinsomnia/insomnia#671]
I have a set of services shared with my workmates via insomnia's *import/export*. However I want everybody can use their their own accounts for authentication, So the login credentials should not be exported.

How about implement a local environment, when a request references keys from local-environment for the first time, lazily prompt the user to provide the private values.

![image](https://user-images.githubusercontent.com/228361/34139299-f9200410-e4ae-11e7-85f8-ce5ba546101b.png)

**Comment by wonderbeyond** [comment]
Maybe a specific template tag helps, like this:

```
{% keep_secret "password" %}
```

Before a request having this tag be sent, prompt user to input and save a k/v pair into local-environment.

**Comment by gschier** [comment]
That's a neat idea. After the user enters the values for the first time, would they be stored somewhere for future use after?

I actually just [added something similar](https://github.com/getinsomnia/insomnia/pull/673), a `{% prompt ... %}` tag that will prompt the user for the value every time.

**Comment by wonderbeyond** [comment]
> After the user enters the values for the first time, would they be stored somewhere for future use after?

Yes, the user can also modify again.

**Comment by gschier** [comment]
I have two ideas for where the values could be stored:

1. In the currently active environment
2. In the tag itself `{% keep_secret "password", "actual value" %}`

Any thoughts?

**Comment by gschier** [comment]
I have three ideas for where the values could be stored:

1. In the currently active environment
2. In the tag itself `{% keep_secret "password", "actual value" %}`
3. Somewhere else, saved to a key specified on the tag `{% keep_secret "password", "storage_key" %}`

Any thoughts?

**Comment by wonderbeyond** [comment]
Secret values are stored for self-use, and should not be exported by default.

So,  does “currently active environment” has the ability to seperate public/private values?

The tag expressions are exportable, thus not suitable for containing private values.

If we store them in somewhere else, no extra key is required. the “password” itself (in above example) can form the key (e.g. `keep_secret _password`)

**Comment by orrjosh** [comment]
I was about to put in a similar request.  Another alternative would be an option to not export environments, only requests.  That way the user could maintain their own environment configuration as is and export the requests for checking into a project's repo.
