### ISSUE TITLE
[Question] Storing response value in the environment

### ISSUE THREAD

**Issue by adamaccent** [getinsomnia/insomnia#674]
Is it possible for Insomnia to store a portion of a response, say the `token` from a login request into the environment?

I'm not sure this is covered by request chaining, since it seems like the behaviour is different. Rather than performing a login request every time I want to request a secure endpoint in a chain, I'd like to have the token stored in the environment and only make the calls necessary during testing.

I'd love to ditch Postman and use Insomnia, so does anyone know how I can achieve this?

**Comment by gschier** [comment]
@adamaccent, [Request Chaining](https://support.insomnia.rest/article/43-chaining-requests) does not execute the dependent requests every time (although there will probably be the option for that in the future), it simply pulls the value from the last response.

**Comment by adamaccent** [comment]
@gschier That's fantastic, apologies for the confusion and thanks for your help. I've just set up a Template Tag and it works brilliantly 👍

**Comment by gschier** [comment]
Awesome! 😄 🚀
