### ISSUE TITLE
Macos latest version 8.3.0, can not sign in

### ISSUE THREAD

**Issue by mbrcic-ad** [getinsomnia/insomnia#6743]
### Expected Behavior

To be able to sign into desktop app
- either with google SSO or with email flow

### Actual Behavior

Can not sign in

### Reproduction Steps

Created account on web bound to google account.
After entering passphrase on web, where the desktop app redirected me to, browser doesn't open desktop app any more.
Nor does the manual copying of token and pasting it in desktop app work.
<img width="293" alt="image" src="https://github.com/Kong/insomnia/assets/111586254/fccab734-2f0f-4d2a-9df0-56422fb6948b">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Tried multiple alternatives:
Primarily I downloaded app from web Insomnia profile/account interface.
Later I even tried to download via homebrew, same issue.

Tried using both Chrome and Safari for redirect sign in flow
Uninstalled Choosy to see if that ons is causing issue (with restart in between)
The step which needs to open desktop app initiated by browser after login doesn't work.
Also manually c/p token doesn't work.

MacOS M1 (Ventura 13.5.2)

### Insomnia Version

Latest download Today

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.5.2

### Installation method

From Insomnia and Homebrew one as alternative

### Last Known Working Insomnia version

First time installation

**Comment by brunobely** [comment]
Also stuck on this. Was never asked to create a passphrase, and can sign in normally on web but not on macOS client.

**Comment by filfreire** [comment]
@mbrcic-avy @brunobely are you still facing this issue?

If you are, I recommend you contact support@insomnia.rest and provide the email with the account you are trying to login with.

**Comment by mbrcic-ad** [comment]
@filfreire  Is that recommendation to try 8.4 beta? Since I don't see release notes for that one.

**Comment by subnetmarco** [comment]
8.4.x is out.

**Comment by subnetmarco** [comment]
We have also shipped the ability to autonomously reset the passphrase, let us know if this issue happens still.
