### ISSUE TITLE
After login, all requests are gone

### ISSUE THREAD

**Issue by rusenask** [getinsomnia/insomnia#6744]
### Expected Behavior

All requests should have remained

### Actual Behavior

Empty. Also, when trying to import OpenAPI file, it's showing me "collection" as empty. Then the "spec" does render the file.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.0

### What operating system are you using?

Ubuntu

### Operating System Version

Linux karolis-desktop 5.4.0-164-generic #181-Ubuntu SMP Fri Sep 1 13:41:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

apt

**Comment by marckong** [comment]
Hi @rusenask I am sorry you are having inconvenience from this. I would like to help. We can possibly jump on a call when mutually available. I am currently working on improving the version upgrade in regards to the data, and also adding logging capability, so we can have better discoverability on issues like this. How can we reach out to you?

**Comment by apyatkov** [comment]
Same happened to me. After snap upgraded Insomnia to 8.3.0 I couldn't see my local projects anymore. I had to revert to older cached snap version to export the data.

**Comment by akirayamamoto** [comment]
I am having the same issue, I just upgraded from 2023 to 8.3. All my data is gone.

**Comment by filfreire** [comment]
Hey folks, this is related to recent 8.x changes. Sorry in advance for this situation.

Please refer to my reply here for solutions: https://github.com/Kong/insomnia/issues/6761#issuecomment-1798352848
