### ISSUE TITLE
Since this login migration the app is unusable

### ISSUE THREAD

**Issue by gilmillasseau** [getinsomnia/insomnia#6747]
### Expected Behavior

When navigating and hitting different endpoints I expect the app to be responsive and quick as before the cloud migration. 

### Actual Behavior

Currently the app is buggy and slow, the navigation experience is bad and the app is now unproductive, I used this tool for years and it's now in a state where is not usable anymore.
When navigating between endpoint I expect the app to just open them even is the request has some errors, currently is just not clickable  anymore.
Also it seems the performance is now worst than before. 

### Reproduction Steps

1. Open Insomnia app
2. Make 3 or 4 requests and navigate between the left bar 
3. The endpoint is not clickable anymore and does not give a reason why

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.3.0

### What operating system are you using?

macOS

### Operating System Version

14.0

### Installation method

download from insomnia rest

### Last Known Working Insomnia version

Before this cloud migration everything was working

**Comment by pranavburnwal** [comment]
@gilmillasseau  Try https://github.com/ArchGPT/insomnium
it's not perfect yet, but it's getting there.

**Comment by filfreire** [comment]
@gilmillasseau thank you for reporting this and apologies for the bad experience. We are aware of performance issues and will be tackling these as best as possible in upcoming updates.

Related to https://github.com/Kong/insomnia/issues/6523

**Comment by gilmillasseau** [comment]
Hey @pranavburnwal  I just tried out and it's exactly this I was looking for. Thanks 👍 
@filfreire I think this is not a technical issue and more like a business decision issue, putting cloud login as mandatory is a big no.

**Comment by pranavburnwal** [comment]
> Hey @pranavburnwal  I just tried out and it's exactly this I was looking for. Thanks 👍 
> @filfreire I think this is not a technical issue and more like a business decision issue, putting cloud login as mandatory is a big no. 

Welcome. I struggled a bit on that so yeah.
