### ISSUE TITLE
Multi-line curl is not imported properly if new lines don't have a padding

### ISSUE THREAD

**Issue by mykolasolodukha** [getinsomnia/insomnia#6755]
### Expected Behavior

When importing a cURL like this:
```sh
curl 'https://example.com/index.html' \
-H 'X-Host: example.com'
```

It adds a header to the list of headers.

### Actual Behavior

All the parameters passed (e.g. `-H`) **are _not_ recognized if they _don't_ have a padding** like in:
```sh
curl -X POST https://insomnia.rest/ \
  --data "foo=bar&baz=qux" \
  -H Content-Type:application/x-www-form-urlencoded
  ```
  ([link](https://github.com/Kong/insomnia/blob/54050fe69e3e641c4fadb076e18ca4a1819e31cf/packages/insomnia/src/utils/importers/importers/fixtures/curl/urlencoded-input.sh))

### Reproduction Steps

1. Click "New Request/Import" -> "From Curl"
<img width="520" alt="image" src="https://github.com/Kong/insomnia/assets/39992593/54b60f66-4b66-4ddd-a64c-0219e50d1312">
2. Import a `curl` without paddings.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The issue, I believe, is in https://github.com/Kong/insomnia/blob/54050fe69e3e641c4fadb076e18ca4a1819e31cf/packages/insomnia/src/utils/importers/importers/curl.ts. Although I don't know TS, so 🤷‍♂️

### Insomnia Version

8.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.2 Beta

### Installation method

download from insomnia.rest

**Comment by filfreire** [comment]
@mykolasolodukha thanks for reporting this, I was able to reproduce and submit a fix for it https://github.com/Kong/insomnia/pull/6774

it should go out in one of our upcoming releases
