### ISSUE TITLE
All my data is gone after the update

### ISSUE THREAD

**Issue by fungiboletus** [getinsomnia/insomnia#6761]
### Expected Behavior

I opened Insomnia and expected to see my data.

### Actual Behavior

I got invited to created an account or use the local scratch pad. I was expecting to see my previous local data in my local scratch pad. But no.

### Is there an existing issue for this?

- [ ] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8

### What operating system are you using?

macOS

### Operating System Version

NA

### Installation method

homebrew

### Last Known Working Insomnia version

7

**Comment by akirayamamoto** [comment]
I am having the same issue, I just upgraded from 2023 to 8.3. All my data is gone.

**Comment by filfreire** [comment]
Hey folks, this is related to recent 8.x changes. Apologies in advance for the stress this caused to you.

Solutions:
- If you create an account and login your data should still be there. You should be prompted if you want to keep that data local only or on the cloud.
- You can optionally export data and import it into scratchpad or to an older version of insomnia.

Also see previous replies to similar issues - e.g. https://github.com/Kong/insomnia/issues/6683 

Once you login you can also go to "Preferences > Data" to try to handle any cases where you have orphaned data

![image](https://github.com/Kong/insomnia/assets/11976836/04c0965b-f9c2-4ea0-8beb-975ae498a68c)|

**Comment by fungiboletus** [comment]
Thanks for the help. I can indeed export the data through the preferences and import the data in the local scratch pad again, though the projects are gone in this version.

Please know that I'm not a fan of those changes. Opening the software and be invited to create an account and subscribe while the data is visibly gone isn't a good look.  I'm writing this because perhaps if enough people complain, the responsibles of such strange choices will be asked to do something else.

**Comment by bj-nostra** [comment]
Upgraded to:

```
Version: Insomnia 8.6.1
Build date: 2/5/2024
OS: Darwin arm64 23.3.0
Electron: 28.0.0
Node: 18.18.2
Node ABI: 119
V8: 12.0.267.8-electron.0
Architecture: arm64
```

On  macOS: `14.3.1 (23D60)`

... and my scratchpad is gone.

<img width="762" alt="image" src="https://github.com/Kong/insomnia/assets/126716058/8a5a50b3-220c-40a1-84c1-0ac8647b36c2">

I can export but not import and I cannot do anything with "Untracked Projects"

<img width="1046" alt="image" src="https://github.com/Kong/insomnia/assets/126716058/ed3b87ce-9239-492d-a6d1-894dac657fca">

**Comment by hexpunk** [comment]
If you just want to get rid of that message at the bottom of the window, go to wherever Insomnia stores data on your OS.

 - `%APPDATA%\Insomnia` on Windows
 - `$XDG_CONFIG_HOME/Insomnia` or `~/.config/Insomnia` on Linux
 - `~/Library/Application\ Support/Insomnia` on macOS

Find and edit a file called `insomnia.Project.db`.  It's a text file, so you can use your preferred editor.  It's a newline delimited JSON file. There should be a line that starts with `{"_id":"proj_default-project"`.  If you delete that line from the file, Insomnia should stop showing the message about orphaned projects.

But beware that if there actually are any requests associated with that project, you may be orphaning those in the rest of the files.  I searched the other `*.db` files and the only other reference I found to `proj_default-project` in them was in my `insomnia.Workspace.db` file, so I deleted that line from that file as well.

I hope this helps.  Make backups if you're afraid of losing data before you start editing these files.

---

EDIT: If you want to try to recover items from your old "default project" into the new scratchpad, you're going to have to walk the relationships in the various `*.db` files to check their relationships.  Workspaces belong to Projects.  Requests can belong to Workspaces or RequestGroups.  RequestGroups belong to Workspaces. Etc.  Check the `_id` and `parentId` values.

**Comment by sideeffffect** [comment]
It's happened again. For the second time already. All my library has disappeared. Again. I'm moving to a different app
https://alternativeto.net/software/insomnia-rest-client/?license=opensource

**Comment by ianmh** [comment]
Same happened to me.

**Comment by Lastdough** [comment]
nope, this just happened to me. I upgraded from 2022.06 to 10.3.1, all my data is gone, nothing. 
to get the data back? just downgrade to the original version 2022.06
guess I'll be moving to a safer option and forget that this ever happened

**Comment by Ordiel** [comment]
Back in the day when they [started with all this s....tuff about requiring an account](https://github.com/Kong/insomnia/issues/6610) someone created a fork called [insomnium](https://github.com/AnagataCetana/insomnium) maybe it's time to support the project and make the switch. 

These type of changes are providing close to 0 value for users; sure its "nice" to have things in the cloud, yet it's even nicer to decide what, when and where, not force spyware down people's throats.

**Comment by nomeaning25** [comment]
Is there a way to also get beck environment settings and Certificates? I managed to import all the requests back but I still l have an issue with missing certificates and environment variables. I this is a "feature" with each update then I will be switching to a different solution!

**Comment by brodrigz** [comment]
> Back in the day when they [started with all this s....tuff about requiring an account](https://github.com/Kong/insomnia/issues/6610) someone created a fork called [insomnium](https://github.com/AnagataCetana/insomnium) maybe it's time to support the project and make the switch.
> 
> These type of changes are providing close to 0 value for users; sure its "nice" to have things in the cloud, yet it's even nicer to decide what, when and where, not force spyware down people's throats.

[insomnium](https://github.com/AnagataCetana/insomnium) looks very interesting indeed.

Really sad to see insomnia's team go with this greedy tactic, holding your projects hostage forcing you to create an account, shameful display.

**Comment by frode** [comment]
RIP insomnia, yet another dead api client
