### ISSUE TITLE
My entire collection has disappeared most likely after upgrade to 8.0 version

### ISSUE THREAD

**Issue by makasim** [getinsomnia/insomnia#6773]
### Expected Behavior

It works offline, does not force me to login
All my collections and requests are there.

### Actual Behavior

It looks like the app completly lost the whole history, collections etc.
It does not work offline and force me to login into an account. 
I do not really need cloud, e2e encryption and all that stuff. Just local app that can make api calls, that's it. that simple. 

### Reproduction Steps

Opened the app
Upgrade pop up showed up
I clicked
The app has been updated,
All data has gone.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 8.2.0
Build date: 10/4/2023
OS: Darwin arm64 21.6.0
Electron: 25.8.1
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.29-electron.0
Architecture: arm64

### Insomnia Version

2023.4.10

### What operating system are you using?

macOS

### Operating System Version

Darwin ip-192-168-50-230.eu-central-1.compute.internal 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

### Installation method

insomnia.rest  site, many years ago

**Comment by filfreire** [comment]
@makasim, sorry for the trouble. This has to do with the 8.x changes. Please see my comment here for workaround solutions - https://github.com/Kong/insomnia/issues/6761#issuecomment-1798352848

**Comment by makasim** [comment]
@filfreire thanks, I'll check it out.

**Comment by makasim** [comment]
@filfreire  In order to restore I have to login. I am trying. It asks for a passphrase which I do not know. I am stuck. Also, it says something about old password. I don't know the old password too and I cannot find a place where I could be able to reset the password. 

Does it mean I cannot get access to my local collections? Is there any other way to restore it ? 

<img width="479" alt="Screenshot 2023-11-08 at 17 46 26" src="https://github.com/Kong/insomnia/assets/143206/e1d8fd66-a607-46d7-8c94-90f4d976e002">

**Comment by kolindes** [comment]
This is so bad. Why do i need to connect/login in to access my local collections.

**Comment by opoleshuk-amelia** [comment]
I have the same issue. Tried new version 10.2.0, after installing, all my collections are gone. It forces me to login, after login, it asks for some passphrase. What is that and why do I need it for my local collections? 

Well, I'm back to v2022.7.5

**Comment by relgames** [comment]
I have the same issue. Tried new version 10.2.0, after installing, all my collections are gone. It forces me to login, after login, it asks for some passphrase. What is that and why do I need it for my local collections?

Well, I'm back to v2022.7.5
