### ISSUE TITLE
Update 8.3.0 Completely Breaks Insomnia Functionality Without SSO Account

### ISSUE THREAD

**Issue by cashank** [getinsomnia/insomnia#6775]
### Expected Behavior

The expected behavior is for an open source tool to not require an account with a third-party cloud service provider to use a self-hosted tool that is essentially a wrapper for curl.

### Actual Behavior

Update 8.3.0 requires a cloud-based sign on to access any old project data or any functionality inherent to the program.

### Reproduction Steps

1. Open Insomnia on version <8.3.0
2. Apply automatic update once prompted
3. Restart Insomnia
4. Observe behavior

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This appears to be an unintended side effect. There should be a local-only option enabled for this.

Workaround: Downgrade to previous versions and disable automatic updates.

### Insomnia Version

8.3.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.5.2

### Installation method

Insomnia.rest

### Last Known Working Insomnia version

3.5.8

**Comment by filfreire** [comment]
@cashank thanks for reporting this, I understand your feelings. You can read the discussions that community had with Kong's leadership about this here: https://github.com/Kong/insomnia/discussions/6590 and in other discussions/issues available in the repository.
