### ISSUE TITLE
Auto update installs a version unsupported by OS

### ISSUE THREAD

**Issue by dvandersluis** [getinsomnia/insomnia#6784]
### Expected Behavior

Automatic updates will not be offered if they require an OS version greater than the current one.

### Actual Behavior

Insomnia gave me a popup to auto-update to 8.4.0 but then once installed I could no longer open the app since it requires a higher version of MacOS than I am using.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.0

### What operating system are you using?

macOS

### Operating System Version

10.14.6

### Installation method

Download originally, auto-update through the app since

### Last Known Working Insomnia version

8.3.0

**Comment by subnetmarco** [comment]
We did update the Electron version to `27.x` and it seems like older version of Mac are not supported anymore by Electron itself (well, by Chromium specifically): https://www.electronjs.org/blog/electron-27-0#removed-macos-1013--1014-support

While we would like to have Insomnia run on every version of the OS, we also cannot run on outdated versions of Electron.

**Comment by dvandersluis** [comment]
That’s fine, but what I’m suggesting is that it should not auto update to a version that is unsupported on the current OS because then there is no way to open the app or revert.

**Comment by subnetmarco** [comment]
Ah I see what you mean. We are using the auto-updater capability of Electron which determines the updated based on the version alone.

To keep using an older version on an older OS you can manually download the specific version that you want from our releases and disable the auto-updates in the preferences.
