### ISSUE TITLE
Clicking on folder or request does not behave as expected

### ISSUE THREAD

**Issue by shaunstorey** [getinsomnia/insomnia#6786]
### Expected Behavior

Previously one left click on a folder would make it expand / collapse and same action on a request would load it into left panel.

### Actual Behavior

After updating to 8.4.0 it now makes the item turn a darker gray colour and sets a flashing caret at the end of the name (like if it was editing the name) 

### Reproduction Steps

one left click on a folder with child requests

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 8.4.0
Build date: 11/9/2023
OS: Darwin arm64 23.1.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: arm64

### Insomnia Version

8.4.0

### What operating system are you using?

macOS

### Operating System Version

14.1 (23B74)

### Installation method

Auto update

### Last Known Working Insomnia version

8.3.0

**Comment by ihexxa** [comment]
Hi @shaunstorey,
You are correct, by clicking the folder name area, you are able to quickly rename it, which is enabled from 8.4.
Please click space or icon to toggle folders, feel free to let us know if it works.

**Comment by slaphead** [comment]
Please can this be reverted? It is extremely annoying. The more common scenario is clicking the folder/request to expand the folder or select the request. Changing the name of it I would imagine is less common.

A suggestion is if the request/folder is already selected and the user clicks on it again, then do the name update option. Right now we have folder/request names that are long and almost extend to the drop down icon. This means while working with this on a daily basis it becomes super annoying that it constantly tries to change the name of the element clicked on.

**Comment by shaunstorey** [comment]
Agree with that 100%, menu option gives the ability to change a name which give the frequency of doing that was fine.

**Comment by slaphead** [comment]
Furthermore, and apologies for adding it here. The color selections have become difficult to work with. When a request/folder is selected there is an indigo? marker which is difficult to see:
![Screenshot 2023-11-10 at 9 30 41 AM](https://github.com/Kong/insomnia/assets/10655963/6846a834-0115-45b3-b4fc-dc2807421533)

Could the entire line be somewhat highlighted please?

**Comment by Alex-Jr** [comment]
This new feature makes very hard to open folders or requests because now you have to precisely click on empty space

**Comment by nickvruiz** [comment]
Fully agree with all of the comments here

**Comment by shaunstorey** [comment]
Using it most of the day, I'm pretty convinced there is a lag when you toggle the folder open and closed which sure wasn't noticeable before

**Comment by krististepanek** [comment]
this is SOO annoying, please revert it.  the most commonly desired action should be the thing that happens when you click on something. the most commonly desired action is that i want to switch to the request i'm clicking on (or expand/collapse if it's a folder).  I rarely want to rename my requests.

**Comment by mmaask** [comment]
Please revert this change.

**Comment by jougene** [comment]
Fow now it is absolutely impossible to use due to this annoying feature

**Comment by sdvdxl** [comment]
so slow.
![20231113170238_rec_](https://github.com/Kong/insomnia/assets/3821540/b388ac62-d659-4229-810c-700bd917c5f5)

**Comment by nefsir** [comment]
Fully agree that this 'feature' is a nightmare, how often is a rename compared to folder expand/collapse? It makes Insomnia annoying to use.

**Comment by bkiebdaj** [comment]
Please revert it or make it configurable from settings at least.

**Comment by brauchle** [comment]
yep, totally annoying. Maybe instead of having an edit functionaliy by single click it could be a double click?

**Comment by binaryatrocity** [comment]
Not going to lie, before this change I was a bit annoyed at having to click the arrow to rename my requests and would have voted for this change to be implemented. Now that it's here the "false positives" are much more frequent than my need to rename and I am sorry I didn't know better, but would definitely vote for a reversion :D

**Comment by krististepanek** [comment]
The cherry on top here is that it doesn't even work to rename something! Trying to do any typical edit actions like clicking to place your cursor, double clicking to select a word, or even TYPING A LETTER in the "edit" looking field just toggles it back to not editing.

**Comment by K2ouMais** [comment]
This renaming thing is so annoying.

I hate to click somewhere and it thinks I want to rename something.

Another thing that is annoying is that running a request you loose the focus of wich request you had selected, so after a request you dont know what you runned previously.

This tool seems to get worse with every release and I loved it before.

**Comment by ihexxa** [comment]
It will be fixed in the next minor version soon.

**Comment by subnetmarco** [comment]
[v8.4.2](https://github.com/Kong/insomnia/releases/tag/core%408.4.2) has been released and this issue has been resolved.

**Comment by slaphead** [comment]
Just wanted to say thank you for listening and doing the update!

**Comment by jougene** [comment]
But why it is still so slow then?
