### ISSUE TITLE
Variables are not being saved in Manage Environments

### ISSUE THREAD

**Issue by ccaires** [getinsomnia/insomnia#6798]
### Expected Behavior

When saving variable values ​​in Manage Environments with the command Ctrl + E, you must store the value in the variable.

### Actual Behavior

Variables are not being saved in Manage Environments.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.0

### What operating system are you using?

macOS

### Operating System Version

Darwin Kernel version 22.3.0

### Installation method

brew

**Comment by subnetmarco** [comment]
Hi @ccaires we tried to replicate this issue without luck. Could you please record a [Loom](https://www.loom.com/) to show us what is going on exactly?

**Comment by matthewcaminiti** [comment]
+1 happens all the time, requires restart to re-enable editing of environment values

Ubuntu 20.04.4

**Comment by ccaires** [comment]
Hi @subnetmarco the problem has now been fixed after new updates. Thank you very much!

**Comment by subnetmarco** [comment]
Glad to hear!
