### ISSUE TITLE
There is no way to disable Insomnia auto-update on MacOS.

### ISSUE THREAD

**Issue by manbeing** [getinsomnia/insomnia#6799]
### Expected Behavior

Users should be able to disable auto-update feature in Insomnia on MacOS

### Actual Behavior

Insomnia automatically update.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 8.4.1

### What operating system are you using?

macOS

### Operating System Version

MacOS 14.1 (23B74)

### Installation method

homebrew

**Comment by filfreire** [comment]
@manbeing you can go to Preferences and disable

![image](https://github.com/Kong/insomnia/assets/11976836/963c2e59-d7a0-4381-bcfc-1a6d33d61870)
