### ISSUE TITLE
[Feature Request] Use recursive environment variables in base env from child envs

### ISSUE THREAD

**Issue by rocketraman** [getinsomnia/insomnia#680]
- Insomnia Version: 5.12.4
- Operating System: Linux Fedora 4.13.16-202.fc26.x86_64

## Details

I would like to be able to define a recursive env var in the base env, using variables from the child envs. My use case for this is to be able to define, for example, `scheme`, `host`, and `port` in the child envs, and define `baseUrl` using these values once only in the base env.

The environment editor actually allows this -- the Ctrl+space completion brings up the child env vars while editing the base env.

However, completion in the actual call definition does not bring up the base env variable as an option (which makes me think this might be a bug, not a feature request?).

Currently, I need to define `baseUrl` in every child env, with exactly the same definition in each.

**Comment by gschier** [comment]
Hi @rocketraman,

It should be working as you stated. I just tried it on my end with no issue. Be sure to make sure one of the sub environments is selected in the sidebar.

Base Environment

```json
{
	"base_url": "{{ protocol }}{{ host }}"
}
```

Sub Environment

```json
{
	"host": "insomnia.rest",
	"protocol": "https://"
}
```

**Comment by rocketraman** [comment]
@gschier I think I see the difference. If the value is nested, then it does not work. If it is a top-level value then it works fine. For example:

This works:

Base:

```
{
	"base_url": "{{ protocol }}{{ host }}"
}
```

But this does not:

Base:

```
{
	"foo": {
		"base_url": "{{ protocol }}{{ host }}"
	}
}
```

**Comment by gschier** [comment]
That's correct. Environments are joined together using a _shallow_ merge so nested object overwrite each other.

**Comment by rocketraman** [comment]
> That's correct. Environments are joined together using a shallow merge so nested object overwrite each other.

Aha! Ok, that is easily worked around by inverting the data structure i.e.:

Base:

```
{
	"baseUrls": {
		"foo": "{{ foo.protocol }}{{ foo.host }}"
	}
}
```

Perhaps this should present as a warning in the UX rather than a silent overwrite? Or even better, why not just do a deep merge? I believe the lodash `merge` function does that, doesn't it?

**Comment by gschier** [comment]
A deep merge would be ideal but would potentially break a lot of people's setups if the behavior were changed this late in the app's life.
