### ISSUE TITLE
usability issue: have to double click to switch the request view.

### ISSUE THREAD

**Issue by manbeing** [getinsomnia/insomnia#6800]
### Expected Behavior

Single click to launch the details of a request

### Actual Behavior

have to double click to launch the request detail

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

With the latest update, we found we had to double click the request to switch the request.
Previously, a simple click was able to switch the request.
![image](https://github.com/Kong/insomnia/assets/39745132/dea35b4a-0fbf-4982-b6ef-19b92b2cefdd)

### Insomnia Version

nsomnia 8.4.1

### What operating system are you using?

macOS

### Operating System Version

MacOS 14.1 (23B74)

### Installation method

homebrew

**Comment by VincentDurandChewbi** [comment]
Same issue here, single click start renaming service.
Behaviour present since 8.4.0 version.

**Comment by brianaj** [comment]
Very painful to use 😫!

**Comment by subnetmarco** [comment]
We will change this - I agree it's painful to use.

**Comment by subnetmarco** [comment]
[v8.4.2](https://github.com/Kong/insomnia/releases/tag/core%408.4.2) has been released and this issue has been resolved.
