### ISSUE TITLE
usability issue - Unfortunately, this product is no longer the way I have been used it for years

### ISSUE THREAD

**Issue by arashberlin** [getinsomnia/insomnia#6805]
### Expected Behavior

Filter result shouldn't be change when I clone/kopie an element with the same name.
Preview JSON is not showing a beautiful json.    Where is the difference between  Preview  or Source of JSON: none

Beautiful Json in Request Body:  Is not beautiful. So many tabs and empty spaces.

With every update the font is set to be so small. I need to use a screen magnifier to adjust the settings. I use a 4K monitor.

### Actual Behavior

Unfortunately, the product is no longer the way I have been used to using it for years. Since the last update, the usability has become so bad that I switched back to PostMan App (version 9.31.0). I don't know if it's just me having these problems, but I've already uninstalled insomnia and deleted everything and reinstalled it. Always the subtle result. With every update the font is set to be so small. I need to use a screen magnifier to adjust the settings. I use a 4K monitor.

Reasons for my change:
•	The filter is not working properly. With every clone/copy the filtered results are gone again.
•	"Beautiful Json": only works in the request body and with a lot of tabs and spaces.
•	Preview for JSON output is unfortunately no longer “nice”. I don't see where is the difference between Preview or Source?
•	There is no history like the PostMan app. It takes me minutes to search for the correct endpoints Inefficient.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise, 22H2

### Installation method

download from insomnia.rest

**Comment by subnetmarco** [comment]
@arashberlin regarding the preview issue, this is what I see:

<img width="1142" alt="Screenshot 2023-11-14 at 8 41 56 PM" src="https://github.com/Kong/insomnia/assets/964813/6be2f544-fcf4-430b-b8ba-2f027c958427">

Is this also what you have?

**Comment by arashberlin** [comment]
Hi @subnetmarco. Thank you for your response.

There is no difference between Preview & Source in my results.  And I am aware of "wrap text editor lines" in the Pref section.  By disabling the "wrap text" then you get all the empty spaces.

What I am doing wrong?


Removed Images

**Comment by gatzjames** [comment]
@arashberlin It looks like you have set the `Editor Indent Size` setting to 9.
This makes all tabs have 9 spaces which creates all this space in your preview and other editors in the app.
Try setting this to 2 and let us know how it works for you

**Comment by subnetmarco** [comment]
I am closing this issue now. Let us know if fixing the indentation setting resolves your problem.

**Comment by arashberlin** [comment]
@gatzjames & @subnetmarco   Thank you. That helps.

What's about filters on the left side?
"The filter is not working properly. With every clone/copy the filtered results are gone again."

**Comment by subnetmarco** [comment]
> "The filter is not working properly. With every clone/copy the filtered results are gone again."

Are you duplicating the requests in a collection, or are you duplicating the collection itself?

**Comment by arashberlin** [comment]
just duplicating  a request with same name

**Comment by subnetmarco** [comment]
Wouldn't it be expected for the filter to reset in a new request? It's a new request, with a new response.
