### ISSUE TITLE
Clicking on the text of my request, lets me change the name

### ISSUE THREAD

**Issue by suuunly** [getinsomnia/insomnia#6807]
### Expected Behavior

When I click on the text of a request, I expect it to just open, and then I can proceed to use it as usual.
Like any other piece of software out there

### Actual Behavior

When I click the text of a request, it lets me rename the request.

### Reproduction Steps

1. Click on the title of a request (or folder)
2. Then you get prompted to change the name of the request/folder, and not having it open that request

### Is there an existing issue for this?

- [ ] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I hope this is a bug. Because this is an awful user experience otherwise. Especially, when the downward facing arrow on the RHS of the request already has the option to "rename".

Can't say I've ever seen software do this before.

### Insomnia Version

8.4.1

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 13.4.1

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

the previous version

**Comment by JordyDeGroeve** [comment]
+1 on this. This has reduced my workflow-speed tremendously! 
I get the new functionality, but let the user decide what the expected behaviour should be (by adding an option in the settings 🙏 )

**Comment by mrpjevans** [comment]
+1 It's driving me insane. It was fine as it was.

**Comment by subnetmarco** [comment]
We are changing the single click to double click in 8.4.2 tomorrow. We did that to be consistent with how tests are being renamed, but it is obvious it should have been the other way around.

**Comment by anotherglitchinthematrix** [comment]
@subnetmarco Instead of reverting back the feature, is it possible to consider renaming as the double click action?

**Comment by mrpjevans** [comment]
@subnetmarco Thanks

**Comment by subnetmarco** [comment]
[v8.4.2](https://github.com/Kong/insomnia/releases/tag/core%408.4.2) has been released and this issue has been resolved.
