### ISSUE TITLE
Not showing response in "visual preview"

### ISSUE THREAD

**Issue by aatbtech** [getinsomnia/insomnia#6813]
### Expected Behavior

when i make a request to my api that list orders the "Visual preview" should show an array of orders (12). 

### Actual Behavior

when i tried to list orders from my api, the "Visual preview" list only an empty array, if i change to "raw data" it listed all the response.
![example](https://github.com/Kong/insomnia/assets/143636321/fccc709a-46df-46e6-a24d-dc7b9f5464f3)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

- it started after i updated to the latest version
- i tested the same request on postman and it worked fine (listed the orders)

### Insomnia Version

8.4.1

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.3.1

### Installation method

download from insomnia.rest

**Comment by gatzjames** [comment]
Hi @aatbtech. I am not able to reproduce this even when the content type is not 'application/json' I can still see the response as a JSON list in the Preview.
Can you share a bit more info about your request? e.g. what is the content type you get from the server and what method?

**Comment by william-fireone** [comment]
@gatzjames I just updated to version 10 and this same problem is now occurring on my machine.

![image](https://github.com/user-attachments/assets/44a5ecdc-2284-4c37-a1e7-588fd8605b20)

Raw response:
![image](https://github.com/user-attachments/assets/d0354636-8018-413e-a162-54723aa6e307)

Visual Preview:
![image](https://github.com/user-attachments/assets/07ac033b-56b9-4255-a793-c6eabef63e72)
