### ISSUE TITLE
[Feature Request] Support Import from Postman v2.1.0

### ISSUE THREAD

**Issue by timrs2998** [getinsomnia/insomnia#682]
- Insomnia Version: 5.12.4
- Operating System: macOS Sierra 10.12.6

## Details

I'd like to be able to export from latest Postman and import into Insomnia. There is a new v2.1.0 schema for postman collections available: https://schema.getpostman.com/

Looking around the code, someone probably has to diff for changes between v2.0.0 and v2.1.0, and add another branch to https://github.com/getinsomnia/insomnia/blob/develop/packages/insomnia-importers/src/importers/postman.js#L17

**Comment by timrs2998** [comment]
Please keep the issue open. As a user I expect the latest Insomnia to be compatible with collections from the latest Postman; I should not have to use an earlier Postman version or manually edit a collection's JSON.

**Comment by timrs2998** [comment]
bump

**Comment by gschier** [comment]
Open!

**Comment by csotiriou** [comment]
The implementation for this is long overdue in my opinion.

Has anyone tried to take a look at it?

**Comment by coderjoe** [comment]
I have a hack that I've been using that just ignores the postman jsonspec schema.
I'll try converting that to a more reasonable implementation given the above suggestions.
