### ISSUE TITLE
App is not responding after 8.4.2 upgrade

### ISSUE THREAD

**Issue by diegolamanno** [getinsomnia/insomnia#6820]
### Expected Behavior

Being able to use Insomnia at all and have access to my data

### Actual Behavior

The app doesn't load at all. After logging in the app crashes! 

### Reproduction Steps

Directly related to the issues explained in #6819.

After struggling to get the app to work. I proceeded to try a **clean install**.
1. Completely remove Insomnia from MacOS
2. Download and install Insomnia client 
3. Log in into a non-enterprise account

Right after logging in the following message shows up.

```
Network connectivity issue: Failed to load Organizations. Failed to find personal organization your account appears to be in an invalid state. Please contact support if this is a recurring issue.
```

```
Error: Network connectivity issue: Failed to load Organizations. Failed to find personal organization your account appears to be in an invalid state. Please contact support if this is a recurring issue. at Module.Fm1 [as indexLoader] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:1537:3408) at async k8 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:31:3691) at async Promise.all (index 2) at async oe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:30:21936) at async We (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:30:16867) at async xe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:30:15043) at async Object.ue [as navigate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-d835d28a.js:30:13765)
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 8.4.2
Build date: 11/15/2023
OS: Darwin arm64 22.5.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: arm64

### Insomnia Version

Insomnia 8.4.2

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.4

### Installation method

Download from Insomnia.rest

**Comment by subnetmarco** [comment]
Restarting the application will fix this problem, tracking the issue in https://github.com/Kong/insomnia/issues/6819 and closing this one as duplicate.

**Comment by Calamitous** [comment]
I am having this exact same issue.  Uninstalled, reinstalled, restarted, logged out and back in from both the app and the browser, and still getting the exact error described above.

This is a brand-new account on a new Windows 11 machine.
