### ISSUE TITLE
Not able to open my collection

### ISSUE THREAD

**Issue by Kuldeepdahra** [getinsomnia/insomnia#6825]
### Expected Behavior

Should be able to open collections properly

### Actual Behavior

Not able to open already created collections

### Reproduction Steps

1. Open Insomnia
2. see the below error 
Error: Network connectivity issue: Failed to load Organizations. Cannot read properties of undefined (reading 'find') at Module.Fm1 [as indexLoader] (file:///snap/insomnia/237/resources/app.asar/index-d835d28a.js:1537:3408) at async k8 (file:///snap/insomnia/237/resources/app.asar/index-d835d28a.js:31:3691) at async Promise.all (index 2) at async oe (file:///snap/insomnia/237/resources/app.asar/index-d835d28a.js:30:21936) at async We (file:///snap/insomnia/237/resources/app.asar/index-d835d28a.js:30:16867) at async xe (file:///snap/insomnia/237/resources/app.asar/index-d835d28a.js:30:15043)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.2

### What operating system are you using?

Ubuntu

### Operating System Version

Linux VDISandbox-52 5.4.0-1109-azure #115~18.04.1-Ubuntu 

### Installation method

NA

**Comment by subnetmarco** [comment]
Hello 👋 Insomnia 8.4.4 has been shipped with important **performance improvements** that brings back a ton of speed in the UI. This issue has also been resolved. You can wait for the auto-updater to download it for you, or you can manually download it [here](https://github.com/Kong/insomnia/releases/tag/core%408.4.4).
