### ISSUE TITLE
Exe of 8.4.2 download is not correctly compiled

### ISSUE THREAD

**Issue by BenniSchmiedel** [getinsomnia/insomnia#6826]
### Expected Behavior

Download of 8.4.2-exe file, execute on windows.

### Actual Behavior

It seems that the exe provided for version 8.4.2 was not correctly compiled. Execution not possible.
Had to go for version 8.4.1.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

exe

### Last Known Working Insomnia version

8.4.1

**Comment by filfreire** [comment]
@BenniSchmiedel I've checked on a Windows 10 Pro 22h2 machine and it's working for me.
- Are you presented with any sort of error message?
- Can you provide details of which particular windows 10 build you are using?

**Comment by subnetmarco** [comment]
We just shipped 8.4.4 - Can you please try again and see if this issue has been resolved? I will close the issue now, but we can reopen it if you are still experiencing the problem.
