### ISSUE TITLE
Lost all my collections and requests instantly

### ISSUE THREAD

**Issue by koldoon** [getinsomnia/insomnia#6828]
### Expected Behavior

No proper data migration before update

### Actual Behavior

Complete data loss

### Reproduction Steps

Update to the latest version

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Bye-bye, Insomnia
I loved you and used a lot but it's time to say goodbye...

After the last update, I received some kind of incomprehensible window with an offer to log in, which could not be missed in any way. But what's worse, after I somehow found how to skip it, it turned out that all my collections were gone and how to get them back is completely unclear.

Why didn't developers provide any data migration? Why didn't the app warn me before such an important update? Maybe I would have prepared somehow, made a backup copy or refused to update at all for a while.

In the context of the situation that has happened, I see an irresponsible attitude towards users, a situation in which I can no longer trust this product either for a fee or for free.

### Insomnia Version

8.4.2

### What operating system are you using?

macOS

### Operating System Version

mac

### Installation method

automatic updates

```[tasklist]
### Tasks
```

**Comment by subnetmarco** [comment]
@koldoon After 8.x your data is available either by logging in, or by exporting your data before logging in. Are you saying that clicking on "Export data" (or logging in) doesn't show your data?

If so, I offer to jump on a call with you with one of Insomnia engineers to understand what is going on. But your data should still be there, except it may be in an "unlinked" state which is a bug that should have been fixed already.

**Comment by catskull** [comment]
I've been using and recommending Insomnia for 5 years and thanks to this I'll stop. Sad to see enshittification come to my favorite tools. Be sure to congratulate the exec who made this great decision!

**Comment by koldoon** [comment]
@subnetmarco Why in hell should I log in if I don't need any synchronisation/collaboration? Looking like an attempt to "lock" my data one day until I make some payment. Paid services are good but definitely not this way. By forcing users to login in order just to get their data back you're scaring them. Nobody wanna share their information without absolutely necessity. Please, don't get me wrong. Wanna make Insomnia completely paid? Good luck. But without me. There is Postman that already supports GQL at the same level as Insomnia does and where this step is made much more transparently. From the very beginning the most attentive "killer feature" of Insomnia was clear and blazing fast user interface but with latest changes everything is just gone. And now after last update introducing that mandatory login step I don't see any more reasons to stay with Insomnia at all.

**Comment by catskull** [comment]
https://github.com/usebruno/bruno

**Comment by subnetmarco** [comment]
I have already answered about this topic across many discussions and issues on the project. Closing this now, since this is not an actionable bug report given the new direction of the product. Also removing spam comments (don't spam).

**Comment by catskull** [comment]
> (don't spam).

ironic

**Comment by johnpanos** [comment]
I'm glad I switched to the Rest Client that's in Jetbrains IDEs. RIP Insomnia.

**Comment by davesouthey** [comment]
Sad to see a great tool destroy its reputation like this. You don't win customers by taking away their data.

**Comment by neoromantique** [comment]
I have logged in and migrated the data once, today Insomnia updated again and AGAIN locked me out with login emails not arriving. 

What a shitshow.

**EDIT:** Fifteen minutes later the emails arrived, but few days of changes have been lost. Isn't the sync the whole selling point of this enshittification? 

Anyhow, thanks for the heads up to migrate away my stuff.

**Comment by gatzjames** [comment]
Hi @neoromantique. Sorry this happened. No excuses from our side but we are working hard to improve our service performance and stabilise the app.
I can help you recover your data and debug what the issue was for losing them.
Can I ask how your changes got lost? Did your workspaces disappear or did they go back to what you had a few days ago?

**Comment by igolka97** [comment]
Same problem here. Just updated and the app asked me to log in again. When I logged in, my entire collection was gone. I am very sad to see this wonderful project become a corporate machine. I used it because it was dead simple compared to Postman, which looked like an Airbus control panel. Thanks for the advice, I’ll start using the JetBrains REST client. RIP.
<img width="1525" alt="Снимок экрана 2023-11-28 в 16 27 51" src="https://github.com/Kong/insomnia/assets/3520658/2b3696ee-1459-413e-9e19-d326024ecaff">

UPD:
Just installed Insomnia 2023.5.8 and all collections back. Hope i'll never update this again.

**Comment by zgaze** [comment]
我丢失了我本地的全部collections 和 requests，我已经决定放弃他了，有任何人有合适的替代工具，欢迎告诉我

**Comment by jacobacon** [comment]
I've been using Insomnia for years, but this is enough for me to jump ship. Same reason I stopped using Lens, and Postman. I don't need a login for testing my local APIs.

Anyone looking for an alternative, looks like Bruno is a good fit: https://github.com/usebruno/bruno
