### ISSUE TITLE
[Feature Request] Allow installing in different folder in Windows

### ISSUE THREAD

**Issue by logoff** [getinsomnia/insomnia#683]
- Insomnia Version: 5.12.4
- Operating System: Windows 10 (64 bits)

Insomnia gets installes in user _AppData_ folder. It is a legit and useful behaviour because then admin privileges are not required. But it wastes disk space in multi-user equipment.

**Would it be possible allowing to choose the insatllation folder?** For instance choosing the classical _Program Files_ folder.

**Comment by gschier** [comment]
Unfortunately that's not possible without completely changing the windows install/update framework Insomnia uses (a lot of work). 

Insomnia uses the same install/update system as [Atom](https://atom.io/) editor, which has [made it clear](https://github.com/atom/atom/issues/7095) that they do not plan to support the modification of the install folder.

**Comment by logoff** [comment]
Thank you for the information.
