### ISSUE TITLE
Can't open 1 collection, Performance & POSTS are not kept

### ISSUE THREAD

**Issue by VOS123** [getinsomnia/insomnia#6833]
I have 42 collections, some of which contain a lot of API examples. I can't open the largest collection anymore. Since yesterday I noticed that my posts are lost after reopening insomnia.  Since weeks I also noticed that Insomnia has become less responsive.

I have to continue with postman today, and I'm worried that I loosen my collections.

Who can help me?

**Comment by subnetmarco** [comment]
What happens when you open the collection? What version of Insomnia are you running?

**Comment by ihexxa** [comment]
Hi @VOS123 , would you mind to share your account name then we can check it.
And it would be great you could provide your version and system info.

**Comment by VOS123** [comment]
My login name is ***@***.***

When I log in, in some of my collections, I is slow. For example;  I have
URL variables like APIV1, APIV2, etc. Sometimes it will take a long time
before I can autoselect these variable.s
On on collection, I found that it didn't save my REQUESTS, they were lost
when I reopened Insomnia
Selecting either one of the collection  tiles is unresponsive,
Opening Collection StUF ERPx isn't always possible, I've just tested and it
opened, but collapsing en collapsing a folder doesn't work...



The technical specs.
Version: Insomnia 2023.5.3
Build date: 16-8-2023
OS: Windows_NT x64 10.0.22000
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

**Comment by subnetmarco** [comment]
@VOS123 We made several improvements (up to 20x performance in some cases) in the latest [v9.3.3](https://github.com/Kong/insomnia/releases/tag/core%409.3.3). Can you please try with this new version of Insomnia?

![Screenshot 2024-08-01 at 7 57 08 AM-modified](https://github.com/user-attachments/assets/f301d057-a3a9-434c-a5a6-253114ba881b)

**Comment by subnetmarco** [comment]
@VOS123 Have you had the chance to try the new version? Closing this issue for now, unless the performance issues persist.
