### ISSUE TITLE
[Bug] Custom Nunjucks code as tag

### ISSUE THREAD

**Issue by pslacerda** [getinsomnia/insomnia#684]
- Insomnia Version: 5.12.4
- Operating System: Fedora 27

## Details

I could evaluate some nunjucks code as Custom Tag and it rendered correctly in the live preview field:

```
{% if request['cookie']['csrftoken'] %} {% request 'cookie', 'csrftoken' %} {% else %} {{ token }} {% endif %}
```

![screenshot_2018-01-03_12-40-09](https://user-images.githubusercontent.com/149358/34527115-49ea5212-f083-11e7-8725-f1a20c658ac7.png)
 
However it couldn't be saved or used at all.

What can I do to enable this Custom Tag? Isn't it a missing feature?

**Comment by gschier** [comment]
Hmm, why couldn't it be saved? If you click "Done" it should insert that code into the text field.

Since it's not a single Nunjucks tag, it will not act like one. Instead, it will show up something like this:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/587576/34602120-ebb1f8d0-f1fe-11e7-93ac-8ea3fe23f102.png">

**Comment by gschier** [comment]
If you want to use this "tag" in multiple places, your best bet would be to store it as an environment variable and reference that instead.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/587576/34602457-1659618a-f200-11e7-8363-b2ea17b3f933.png">

**Comment by pslacerda** [comment]
If I starting typing directly into the text field it works as stated. But if I start with "req" and click on "request → cookies" and open the popup editor tag editor (the same in the original picture). It becomes impossible to edit or save.

**Comment by gschier** [comment]
Hmm, can you provide a short screencast of this behavior? I'm not able to reproduce the "impossible to edit or save" part.

**Comment by pslacerda** [comment]
I'm pretty sure the mentioned popup modal custom tag editor does not handle such custom Nunjucks code as the exemplified one. At least when adding a new header using version 5.12.4.
