### ISSUE TITLE
Local scratch pad no longer working

### ISSUE THREAD

**Issue by MarouaneMan** [getinsomnia/insomnia#6853]
### Expected Behavior

Open local scratch pad

### Actual Behavior

After updating insomnia, I can no longer open the local scratch pad by clicking on it on the login page.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.3

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.4.1

### Installation method

insomnia.rest

**Comment by lermontex** [comment]
The same on Windows 11 after update Insomnia  to 8.4.3 version

**Comment by mdelreal** [comment]
Not to add noise, just confirming that this in all current versions of macOS

**Comment by subnetmarco** [comment]
Will be solved in 30 minutes.

**Comment by subnetmarco** [comment]
Solved in https://github.com/Kong/insomnia/pull/6854 and shipping 8.4.4 in half an hour or less. Adding an integration test shortly to make sure it doesn't happen again.

**Comment by subnetmarco** [comment]
[v8.4.4 is now out](https://github.com/Kong/insomnia/releases/tag/core%408.4.4) where ScratchPad works again.
