### ISSUE TITLE
[Performance] High idle CPU usage

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#686]
- Insomnia Version: v5.12.4
- Operating System: Ubuntu 17.10

## Details

As said in #355, Insomnia is using around 10% when idle. I activated the "Disable Usage Tracking" in order to prevent some background process that could be causing this CPU load, but the CPU load remained the same.

Also I'm not logged in nor have a premium account in Insomnia.

Is there something I can run or check in order to help debug this issue?

Best regards,
Rafael Pacheco.

**Comment by gschier** [comment]
Are you, by any chance, running on a single-core machine?

**Comment by rafaelrenanpacheco** [comment]
No, running on an i7 with 4 cores.

**Comment by cdobson** [comment]
I am also observing this behaviour. v5.12.4, Kubuntu 17.10, i7

**Comment by rafaelrenanpacheco** [comment]
On Arch Linux the CPU usage is around 6%. IntelliJ uses around 5% with 2 opened instances. I guess 6% is ok although is should be less compared to IntelliJ, which is a heavy Java IDE.

**Comment by bukajsytlos** [comment]
On my system (Manjaro i7) it uses around 4% when on foreground. On background there is "no" cpu usage

**Comment by hellp** [comment]
Can confirm that it still idles around at 4-5% CPU when in foreground, and 1% when minimized. (Ubuntu 18.04, 4 cores)

**Comment by rafaelrenanpacheco** [comment]
The OP was about Insomnia using 10% CPU when idle, which were kind of a problem. Nowadays (Insomnia 6.5.3) uses around < 2% when idle. I don't see any problem with that, even if using 5% in foreground as reported by @hellp.

**Comment by hellp** [comment]
It's not a huge problem, sure, but I find 5% for doing "nothing" still a bit much. My 50+ tabs Firefox is using only slightly more than that. It could indicate some unwanted or overly busy code running. Just take my comment as a +1 for waking up this stale issue.
