### ISSUE TITLE
Double click on request drop down menu

### ISSUE THREAD

**Issue by mhmmd-ysf** [getinsomnia/insomnia#6873]
### Expected Behavior

It shows the drop down menu when i click on it.

### Actual Behavior

It immediately click a second time, that if it's a folder, will immediately choose any menu that popped up.

https://github.com/Kong/insomnia/assets/46883609/88544ff5-7b0f-41a4-bf34-be96297d37ec

The first click works normally because fortunately it's outside the menu popup area.

### Reproduction Steps

1. Make a list of requests and/or folders until the request list is scrollable.
2. Click on any folder's drop down menu (it has to be folder since the menu is quite many)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home 22H2 build 22621.2715

### Installation method

Download from insomnia.rest

**Comment by xn213** [comment]
And  This issue caused my request folder to be mistakenly deleted!
How can I retrieve it, there are quite a few requests in this folder

**Comment by subnetmarco** [comment]
Newer versions of Insomnia ask for confirmation before deleting requests/folders.

**Comment by mhmmd-ysf** [comment]
> Newer versions of Insomnia ask for confirmation before deleting requests/folders.

While it solves #6874 I don't think it solves mine. It still clicks a second time.

**Comment by gatzjames** [comment]
@mhmmd-ysf it looks like an issue with our menu when there's not enough space for it.
Delete actions should now ask for confirmation but we will add a fix for the click in the next release
