### ISSUE TITLE
just like Issue #6873  This issue caused my request folder to be mistakenly deleted!

### ISSUE THREAD

**Issue by xn213** [getinsomnia/insomnia#6874]
### Expected Behavior

And  This issue caused my request folder to be mistakenly deleted!
How can I retrieve it, there are quite a few requests in this folder

### Actual Behavior

How can I retrieve it, there are quite a few requests in this folder

### Is there an existing issue for this?

- [ ] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

v2023.5.8

### What operating system are you using?

Windows

### Operating System Version

win 11

### Installation method

from update

**Comment by filfreire** [comment]
See https://github.com/Kong/insomnia/issues/6873#issuecomment-1828072577
