### ISSUE TITLE
Postman v2.0 importer fails if request url=null

### ISSUE THREAD

**Issue by stephenykp** [getinsomnia/insomnia#6879]
### Expected Behavior

I should be able to export Postman collections and import them directly into Insomnia. In Postman (and Insomnia!) it's possible to save a request without setting the request `url`. 

### Actual Behavior

When importing a Postman collection into Insomnia where request=null, I am seeing the following error:

> Error while scanning for resources to import:No importers found for file

### Reproduction Steps

1. In Insomnia, open the "import from file" dialogue
2. Open postman export .json file that contains  url=null
3. Click "scan"

The attached json is a minimal example used to reproduce this error. 
[Test.postman_collection.json](https://github.com/Kong/insomnia/files/13481027/Test.postman_collection.json)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I was able to get around this issue by manually updating the null "url" field to an empty string `""`. 

### Insomnia Version

2023.4.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.6.1

### Installation method

insomnia.rest

**Comment by SyloYamtao** [comment]
I have exported Postman file as **"v2.1 collection format"** then import into Insomnia as your step above, it works for me.



![WX20240109-112223@2x](https://github.com/Kong/insomnia/assets/18388766/2d27fe09-ffee-49aa-8821-125858f9b4da)

**Comment by jackkav** [comment]
Addressed in #7166
