### ISSUE TITLE
Upgrading to 8.4.5 and signing in with email on web doesn't get past `Welcome to Insomnia` page in insomnia mac app

### ISSUE THREAD

**Issue by toymachiner62** [getinsomnia/insomnia#6882]
### Expected Behavior

I should be able to see my collections in the mac app. Today I upgraded to 8.4.5 and my collections are gone. Not in scratch. I hesitantly accepted the E2E BS you made us do with version 8.0.0 and was able to live with it for a while but now once again my collections are not visible. 

I clicked Continue with Email

<img width="1512" alt="image" src="https://github.com/Kong/insomnia/assets/485782/973f623a-d6e1-49a3-8fcd-3e100fd0df41">

I get this page and click Go Back because I have no idea what email it's even trying to use here since it's not displayed

![image](https://github.com/Kong/insomnia/assets/485782/234d353b-373a-4bfc-845f-ce1d02a77b1c)

I get this page and click Continue with email 

![image](https://github.com/Kong/insomnia/assets/485782/a8361357-5ee5-4c90-9c58-0f2ba9020102)

I enter my email and click Continue with Email

![image](https://github.com/Kong/insomnia/assets/485782/f3600800-eacf-4c53-afbe-3670a031d71f)

I enter the code on this page 
![image](https://github.com/Kong/insomnia/assets/485782/5039a9de-e187-42d6-9f10-0e8ad17f9d52)

It takes me to this page and I click the Open button

![image](https://github.com/Kong/insomnia/assets/485782/4eddf3cf-2005-48dc-8cf8-0d624078d176)

And my insomnia app opens back to this page

<img width="1214" alt="image" src="https://github.com/Kong/insomnia/assets/485782/4004ee91-2677-4555-ac8b-f915fa48468a">

What is going on here and how can I login to retrieve my collections?

### Actual Behavior

I should be able to login and see my collections.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.5

### What operating system are you using?

macOS

### Operating System Version

Mac Ventura 13.6

### Installation method

I don't remember how I installed it as i've had it for years now. It was either via homebrew or insomnia website.

### Last Known Working Insomnia version

8.4.4

**Comment by marckong** [comment]
@toymachiner62 what happens if you click "Continue with Email" again on the desktop app?

**Comment by toymachiner62** [comment]
> @toymachiner62 what happens if you click "Continue with Email" again on the desktop app?

Takes me back to the web browser. It's just a loop.

**Comment by marckong** [comment]
what browser are you using and is it incognito mode?

**Comment by toymachiner62** [comment]
> what browser are you using and is it incognito mode?

Chrome and not in incognito mode.

**Comment by marckong** [comment]
This is strange. We can hop on a call and help you trouble-shoot. Are you part of our community slack? I am not sure how the 8.0 to 8.4.5 chance would have caused you to lose your collections after having to log in. 8.0 is where Kong introduced it, so you must have experienced it in 8.0. Regardless, we can troubleshoot together.

**Comment by marckong** [comment]
The end to end encryption feature is a feature that has existed even before Kong acquired this product. Previously, e2ee passphrase was used to authenticate accounts, which resulted in people locked out of their accounts when they forgot passphrase. They could not even access their billings. The only thing we did at 8.0+ is to separate end to end encryption from authentication, so people could still access their billings.

**Comment by marckong** [comment]
I am also running 8.4.5.

1. did you see this page from the desktop app
<img width="592" alt="image" src="https://github.com/Kong/insomnia/assets/103070941/e71701da-93d3-474d-a52a-9bb5eb404d1b">

2. see the prompt? 
<img width="638" alt="image" src="https://github.com/Kong/insomnia/assets/103070941/05ca7f94-a173-404e-8535-53972ef88760">

^here you can also click Cancel and click Manually enter token button:
<img width="246" alt="image" src="https://github.com/Kong/insomnia/assets/103070941/56ee2fe7-2671-415a-9a48-fbbfda7bda32">

We are going to improve on this flow UX.

**Comment by marckong** [comment]
@toymachiner62 you skipped the Enter Passphrase step because you clicked "Go Back". Please enter your passphrase, so the desktop app can decrypt the cloud synced files. This is not an issue on our end.

**Comment by toymachiner62** [comment]
This is working today. But yesterday as you can see in my sequence of screenshots, that after entering in the security code, it took me to a webpage of my account and didn't prompt for a password like it did today.

**Comment by maxbry** [comment]
I'm having the same issue. The new Insomnia is absolutely terrible
