### ISSUE TITLE
Program useless without account

### ISSUE THREAD

**Issue by snuggeman** [getinsomnia/insomnia#6884]
### Expected Behavior

Site says:
"You can use Insomnia without an account with Scratch Pad, or you can ceate an account for free to get access to the full capabilities of the product."

### Actual Behavior

After upgrading, product can only handle one collection.   Which is kindof useless since I have accumulated a bunch of collections.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I'm sufficiently annoyed by this to file this bug report knowing that it will be ignored.
But, it's a data point in the analysis of this decision.

### Insomnia Version

8.4.5

### What operating system are you using?

Windows

### Operating System Version

win 10

### Installation method

download

### Last Known Working Insomnia version

2023.5.8

**Comment by jmcinerney** [comment]
Have to agree with this. I switched to Insomnia because Postman was awful but now that we're getting the "must be logged in" treatment to use the full product I think it's time to move on.

**Comment by robert-puttshack** [comment]
I just lost all my prior work and haven't been able to recover it. Furious.

**Comment by grantmcconnaughey** [comment]
Same, @robert-puttshack. I have no idea where my workspaces went. I had like a dozen and now they're gone because the app forced me to sign up for an account for no reason.

**Comment by FixerLT** [comment]
The solution is [Insomnium](https://github.com/ArchGPT/insomnium), which is a fork of Insomnia with all anti-user updates removed

**Comment by adnan-smlatic** [comment]
@FixerLT thank you for mentioning this. I downloaded Insomnia as an alternative to Postman, only to find it's the same. Insomnium is perfect

**Comment by subnetmarco** [comment]
> After upgrading, product can only handle one collection. Which is kindof useless since I have accumulated a bunch of collections.

Can you see them after logging-in?

**Comment by snuggeman** [comment]
I don't have an account, and the computer has no internet connection

**Comment by subnetmarco** [comment]
Insomnia requires an account to access all capabilities, can be a Free account. Or it can work with ScratchPad locally without an account, limited to one collection.

**Comment by petrdvorak** [comment]
@subnetmarco Jesus f**kin' Christ, you guys are morons - you just dropped all the local work we have done ourselves and blocked our clients from using Insomnia. Terrible, terrible update.
