### ISSUE TITLE
The response panel hangs indefinitely when using the Repeat on Interval function

### ISSUE THREAD

**Issue by tjayr** [getinsomnia/insomnia#6891]
### Expected Behavior

The response from the api call should be shown in the response panels.

### Actual Behavior

The response pane hangs when the request is sent,  the api being tested here typically responds in around 30ms

![image](https://github.com/Kong/insomnia/assets/539097/a476f770-b033-4751-af84-6e340e7bfc59)

### Reproduction Steps

1. Create a new GraphQL Request
2. Enter `https://countries.trevorblades.com/` as the POST url 
3. Enter the following graphql as the query body

```graphql
query ListCountriesInNAFTA {
  countries(filter: { code: { in: ["US", "CA", "MX"] } }) {
    code
    name
    languages {
      name
    }
  }
}
```
The typical response times for this api are `30ms`

4. Set the Repeat on Interval to `0.15`
5. Press Send

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This is not limited to GraphQL requests. I have a number of private slow json based apis that respond in the 1 - 3 second time range, setting a repeat on interval value between 0.5-0.9 causes the same behaviour with those endpoints.

From examining the console logs, the requests/responses do appear to be proceeding, but the user interface never updates beyond the initial progress spinner and ultimately you need to cancel the requests. 

HTTP/2 Preferred and a response timeout of 30000ms is set.

### Insomnia Version

8.4.5

### What operating system are you using?

Ubuntu 

### Operating System Version

6.2.0-37-generic # 38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

deb package

**Comment by zhengjitf** [comment]
FYI, from my side, the time interval should start from the previous request response.
Additionally, it's more intuitive to request immediately upon button click.
