### ISSUE TITLE
[Websocket] - Change Status when Disconnect

### ISSUE THREAD

**Issue by Lucasark** [getinsomnia/insomnia#6894]
### Expected Behavior

<img width="348" alt="image" src="https://github.com/Kong/insomnia/assets/31750882/22f18798-6d81-4a45-9718-97ea27ebc1f6">

I think is great improve this section with Connection Status. For example, when we closing connection it still says "Switching Protocols", but it doesn't because it already closed. 

### Actual Behavior

I am not the best guy with UI, but I think just change the conjugation will be better than today, like: For Closed Connections (10XX) change to "SwitED Protocols", or just "Disconnect".

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.5

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.1.2

### Installation method

Download

**Comment by jackkav** [comment]
I'm not sure I understand your report, websocket makes a handshake HTTP request which responds with status code 101, and the connection log is showing "Closing connection with code 1000", because that is what the websocket api close event gives us. The websocket close event code is not a HTTP status code. Could you elaborate further. It may be something we can make clearer in the connection log.

**Comment by Lucasark** [comment]
> I'm not sure I understand your report, websocket makes a handshake HTTP request which responds with status code 101, and the connection log is showing "Closing connection with code 1000", because that is what the websocket api close event gives us. The websocket close event code is not a HTTP status code. Could you elaborate further. It may be something we can make clearer in the connection log.

When we read "Switching" make us thinking that is still "switching" after disconnect.

I dont like to compare, but lets take a example on Postman; after disconnect they make explicit a status "Disconnect" which is HTTP 101 and CODE 10XX from WS.

**Comment by subnetmarco** [comment]
The "Connected/Disconnected" status in Insomnia is being reflected in this button:

<img width="183" alt="Screenshot 2024-01-03 at 9 39 55 AM" src="https://github.com/Kong/insomnia/assets/964813/97aaf42f-8915-4437-8e22-402d96b4e4a5">
