### ISSUE TITLE
Failed to render Hl in 8.4.5 Insomnia version

### ISSUE THREAD

**Issue by mariadrshv** [getinsomnia/insomnia#6899]
### Expected Behavior

have the ability to make requests from my collection

### Actual Behavior

after opening my collection I see the error
<img width="817" alt="image" src="https://github.com/Kong/insomnia/assets/43935649/37a50f89-334c-4584-b6e0-41964df8c57e">

every request has the error message on its page
<img width="862" alt="image" src="https://github.com/Kong/insomnia/assets/43935649/bbd0ad2f-ae5a-4b99-92a8-8c21cdb89732">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

<img width="891" alt="image" src="https://github.com/Kong/insomnia/assets/43935649/250b6407-7d64-491b-84f6-183b4b5b6144">
my app version is the latest

### Insomnia Version

8.4.5

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.1.1

### Installation method

https://docs.insomnia.rest/insomnia/install

**Comment by lukepearce** [comment]
I had this happen to me, when I was entering text into the query variables area for a GraphQL request. I simply made a typo and the app throws this error and won't render anything to let me fix it.

8.4.5

**Comment by marckong** [comment]
@lukepearce @mariadrshv can you guys please confirm this is coming from a HTTP request item, not GraphQL? Also can you please share more info on this.

**Comment by mariadrshv** [comment]
Hi Mark! It’s coming from GraphQL in my case

**Comment by marckong** [comment]
@mariadrshv interesting. The screenshot shows the POST request opened. Do you have availability to hop on a quick call and trouble shoot it?

**Comment by zhengjitf** [comment]
It happened when typing something like `{"foo": []]]}` in the graphql variable area. 
when processed with the last `]`, call `new Array(-1).join(tab)` to generate an indent, however, a negative length is illegal for Array.

**Comment by lpearceh1** [comment]
I have a very similar issue. Do you know when will this fix be available? @marckong @jackkav @zhengjitf 

After the error message, I discovered a typo in my script. When my colleague ran it without the typo, all worked as expected. However, I continue to get this error and cannot proceed or seemingly fix it.

![image_720-1](https://github.com/Kong/insomnia/assets/141424729/5550e96d-fb77-404a-a5d4-bd5efbb07b4a)
![image_720](https://github.com/Kong/insomnia/assets/141424729/f61fa467-25a7-4b16-bd91-ca7ec63e5526)
