### ISSUE TITLE
Multiple collections require a login

### ISSUE THREAD

**Issue by reslip1** [getinsomnia/insomnia#6902]
### Expected Behavior

Expect to be able to use multiple collections in 8.4.5

### Actual Behavior

Requires login for multiple collections

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.5

### What operating system are you using?

macOS

### Operating System Version

13.6.2

### Installation method

Download from insomnia

### Last Known Working Insomnia version

2023.5.8

**Comment by brauchle** [comment]
okay, I guess Insomnia is now as shitty as postman, also forcing cloud usage ...

**Comment by sunny-chung** [comment]
Is it still free to create multiple collections?

**Comment by subnetmarco** [comment]
1. It is still **free** to create multiple collections after logging in into the product and choosing the Free plan.
2. Creating an account doesn't determine the locality of your data, which can still be local (or cloud, or Git).
3. Without creating an account, the Scratch Pad capability is only limited to one collection.
