### ISSUE TITLE
Deleting Scratch Pad causes fatal error and application doesn't recover

### ISSUE THREAD

**Issue by mccoy1** [getinsomnia/insomnia#6910]
### Expected Behavior

Either deleting the Scratch Pad shouldn't be possible or the app recovers correctly after doing so. Ideally _clearing_ the collection in the Scratch Pad would be more ideal.

### Actual Behavior

Insomnia throws fatal error and can't recover without restarting the app

### Reproduction Steps

1. Open Insomnia v8.4.5 and click "Use the local Scratch Pad"
2. Select the arrow next to "Scratch Pad" and select "Delete" from the menu (to delete the Scratch Pad
3. Confirm delete in the delete dialog
![image](https://github.com/Kong/insomnia/assets/33757681/a7169a7c-7663-4120-8345-4c595826bf2d)

4. User is back to the login screen, click the "Use the local Scratch Pad"
5. Error gets thrown, user can't get back to the app without restarting the app

![image](https://github.com/Kong/insomnia/assets/33757681/fac2060a-8ae8-4de5-8755-9d15463b4472)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.4.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2 19045.3570

### Installation method

Download from Insomnia.rest directly

**Comment by zhengjitf** [comment]
In my opinion, just need to hide the delete action to fix this issue. Clearing should be a feature for any collection (not only the Scratch Pad collection), and it has been not implemented.
