### ISSUE TITLE
[BUG] No environment but configured one

### ISSUE THREAD

**Issue by mgohin** [getinsomnia/insomnia#692]
- Insomnia Version: 5.12.4
- Operating System: osx 10.13.2

Just downloaded Insomnia from the website, installed it and launched it.
Added an environment but it's not visible in the list
![image](https://user-images.githubusercontent.com/3430304/34716093-1d602432-f52f-11e7-8bac-3cb345f3ebac.png)

But you can see that it's listed in the edit popin
![image](https://user-images.githubusercontent.com/3430304/34716114-2d7bbd4a-f52f-11e7-88ce-938bd479c294.png)

And when using variables in the URL, it works.

Rebooted the app, still not working.

**Comment by mgohin** [comment]
First thing first, read the doc :)
I created my environment in the "base".

But it's not very helpful when using app without reading the doc, I think you could add some tips to avoid that king of confusion ?

**Comment by gschier** [comment]
Hmm, it seems that some of the behavior around the base environment was broken in a recent release. Previously, the base environment was always named "Base Environment" and the name was not editable.

I have just fixed this in https://github.com/getinsomnia/insomnia/commit/cdd565d2bce797d4e1cefc46eeeca44b7b75d313 to fix this and also added a help tooltip.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/587576/35029328-085dfce4-fb8d-11e7-96c9-277ad507af32.png">
