### ISSUE TITLE
Request feature still not available after +6 years of discussions

### ISSUE THREAD

**Issue by Loown** [getinsomnia/insomnia#6925]
### Expected Behavior

Having global headers

In case you'r asking, plugin are not maintained and deprecated

### Actual Behavior

Not having global headers

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

latest

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22

### Installation method

website

**Comment by subnetmarco** [comment]
@Loown This is a good one. You mean headers that are available across all routs in a collection, or across all routes of all collections in a project?

**Comment by Loown** [comment]
I mean accros all routes of a project

**Comment by subnetmarco** [comment]
A project has collections, collections have routes.

So you mean all routes for every collection in a project?

**Comment by Loown** [comment]
If I can at least have global headers for every routes in a collection it would be nice

**Comment by jackkav** [comment]
Add the key `DEFAULT_HEADERS` to your environment and foo will be sent as a header in all requests associated with this collection.
<img width="226" alt="image" src="https://github.com/Kong/insomnia/assets/3679927/5774503a-f70c-44a6-9bdb-81e34984a2ef">

Also there is a discussion here https://github.com/Kong/insomnia/discussions/4478
