### ISSUE TITLE
App does not remember default collection

### ISSUE THREAD

**Issue by DusanLesan** [getinsomnia/insomnia#6928]
### Expected Behavior

I want last opened collection to be displayed after relaunching the app

### Actual Behavior

After leaving relaunching the app, I always need to select a collection to open. 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I understand that some people with multiple collections might want to select one they want to use after the launch, but I do not want that. I want the app to remember my choice especially since I only have one collection between two workspaces ("Personal workspace" is empty since it is useless because I cannot change its type)

This issue is duplicate of one of several issues listed by user in [#6809](https://github.com/Kong/insomnia/issues/6809) for this release, but I am making this issue since it went unaddressed there

### Insomnia Version

8.4.5

### What operating system are you using?

Other Linux

### Operating System Version

Linux arch 6.6.7

### Installation method

AUR

**Comment by LunaticoCR** [comment]
Same here on the latest version of Insomnia on macOS.

**Comment by subnetmarco** [comment]
We are going to be working on this for 9.3.3

**Comment by subnetmarco** [comment]
@gatzjames My suggestion is:

* Every time we open a file, we store the last opened organization and file locally.
* If the file has been deleted over time (or the user lost permission access to them, ie when invited from another organization), we open the dashboard of the organization as a fallback.
* If the organization has been deleted over time (or the user lost access to it), we open the "Personal Organization" dashboard as a fallback (standard behavior today).

For both soft-close and hard shut down.
