### ISSUE TITLE
[Bug] Can't change body type if GraphQL is selected

### ISSUE THREAD

**Issue by AyubM** [getinsomnia/insomnia#693]
- Insomnia Version: 5.12.4
- Operating System: Win 10

## Details

To recreate:
Create a POST request to an endpoint without GraphQL
Set the body type to "GraphQL Query"
\> You should receive a 404 error saying it couldn't fetch the GraphQL schema
Try to change it back to multipart form or form URL encoded. You won't be able to.

**Comment by gschier** [comment]
I can't seem to reproduce this. Can you provide a short screen recording of the issue?

**Comment by AyubM** [comment]
I forgot to mention, that it requires you to paste in a POST request copied from chrome as "Copy as cURL (bash)" -- and it seems it has to be a POST request specific to what I'm using, as I can't create it using a generic POST request from, say, jQuery. I can't paste in the request I'm using as it has private data.

I would close this, as it seems to be an obscure bug that can be circumvented by recreating the request and not clicking the "GraphQL" option.

**Comment by gschier** [comment]
I would still like to fix this. If possible, could you strip out the sensitive data of the Curl command?
