### ISSUE TITLE
Missing CHANGELOG information for beta releases

### ISSUE THREAD

**Issue by joshmeads** [getinsomnia/insomnia#6931]
### Expected Behavior

Using beta release, [Releases](https://github.com/Kong/insomnia/releases/tag/core%408.5.0-beta.0) instructs you to visit https://insomnia.rest/changelog for the changelog, however this isn't available for beta releases.

Expect the changelog to be available either on https://insomnia.rest/changelog, Github releases, changelog file or in app (which also instructs you to view changes to an incorrect site).

### Actual Behavior

Missing changelog information. Currently only viewable by finding the PR and auto generated comment: https://github.com/Kong/insomnia/pull/6930#issuecomment-1861600291

### Reproduction Steps

N/A

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Beta releases should have a viewable change log. If users are expected to be reporting bugs related to new updates on test delivery channels they need high level information on whats changed.

### Insomnia Version

8.5.0-beta.0

### What operating system are you using?

macOS

### Operating System Version

MacOS 13.4 Ventura

### Installation method

homebrew

**Comment by subnetmarco** [comment]
Absolutely right! I instructed the team to have a more detailed changelog like we do for [Kuma](https://github.com/kumahq/kuma/blob/master/CHANGELOG.md) and [Kong Gateway](https://github.com/Kong/kong/blob/master/CHANGELOG.md) so moving forward I will make sure we do the same for Insomnia, on both beta and GA releases.

Thanks for the +1.

**Comment by subnetmarco** [comment]
+ @filfreire for visibility.

**Comment by subnetmarco** [comment]
Starting from the next release we will have a complete changelog.
