### ISSUE TITLE
Environment window small

### ISSUE THREAD

**Issue by slaphead** [getinsomnia/insomnia#6939]
### Expected Behavior

I don't know who keeps making these terrible design decisions (And I hate to complain), but every time there is a new version of Insomnia there is some new design that makes this app worse to work with.

I am logging this as a bug as I feel this is a regression. When opening the Manage Environment settings the window is now small and I cannot resize it. I have large json data sets and would like to be able to at least resize the window so I can more easily see the data.

### Actual Behavior
Unable to resize manage environments window.

### Reproduction Steps

Open the manage environment window via the settings cog top left.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.5.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.2

### Installation method

Download from insomnia site

### Last Known Working Insomnia version

8.4.x

**Comment by gatzjames** [comment]
Hey @slaphead thanks for the issue!
We focused on improving the UX of editing the environments in the modal and this slipped through. This will be fixed in the next release.
Sorry for the inconvenience but we hope the UX improvements outweigh this issue.
We are open to feedback and want to the app so feel free to make other issues about any other inconveniences or suggestions you might have!

**Comment by mikebridge** [comment]
@gatzjames Are these changes the same ones that caused https://github.com/Kong/insomnia/issues/5858 to revert?  When I go through that dialogue to get to the `Edit Tag`, it doesn't save changes again.

**Comment by mikebridge** [comment]
> I don't know who keeps making these terrible design decisions (And I hate to complain), but every time there is a new version of Insomnia there is some new design that makes this app worse to work with.

I 100% agree---and every time these crazy UX decisions get made, [something major gets broken](https://github.com/Kong/insomnia/issues/6809).  8.5.0 is _yet another_ unusable release for me.  I depend on this tool daily and pay for it, and every "upgrade" is a step backwards that makes me more livid.

**Comment by subnetmarco** [comment]
This has been completed with a very fast turnaround in 8.5.1, available GA.
