### ISSUE TITLE
Selecting a variable in the environement window causes the window to close without saving the change

### ISSUE THREAD

**Issue by Totalus** [getinsomnia/insomnia#6943]
### Expected Behavior

When I open the environment editor:
I expect to be able to select a variable as value of an environment variable.
I expect to be able to edit and save an existing tag variable.

### Actual Behavior

When I open the environment editor, I observe two buggy behavior.

First, if I enter the name of a variable, when I click on the dropdown to select it, the environment window closes right away (without saving the change).

Second, if I click on an existing tag variable to edit it, as soon as I close the tag editor dialog, the environment window closes (without saving the change).

### Reproduction Steps

Select a variable as value
1. Open the environment window
2. Create a new environment variable, press [ctrl+space] to trigger the autocomplete selector.
3. Select one of the items.
4. The environment window will close right away.

Edit a tag variable
1. Open the environment window
2. Click on an existing tag variable (ex: referencing a Response data)
3. Make a change
4. Click Done on the tag editor dialog
6. The environment window will close without saving.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

If someone works on fixing this, make sure to fix https://github.com/Kong/insomnia/issues/6466 at the same time, probably related.

### Insomnia Version

8.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Downloded from insomnia.rest

**Comment by gatzjames** [comment]
Fixed in #6941

**Comment by corebreaker** [comment]
Not fixed, it reapeared in issue #6372

**Comment by corebreaker** [comment]
> Not fixed, it reapeared in issue #6372

It seems solved since Insomnia 9.3 by #6943 .
