### ISSUE TITLE
Cannot change headers in Insomnia 8.5.1

### ISSUE THREAD

**Issue by gweconsulting** [getinsomnia/insomnia#6947]
### Expected Behavior

The Header tab should allow a user to add additional header such as JWT token. But in Insomnia 8.5.1, the number of headers are fixed to 5 including Server, Date, Content-Type, Content-Length, and Connection. There is no option to add additional headers. 

### Actual Behavior

I am new to Insomnia. I saw some videos there have different option in the Herders tab. In Insomnia 8.5.1, there is only a "copy to Clipboard" option. 

### Reproduction Steps

1. Create any http request;
2. Go to Headers tab, and 5 fixed header fields will be present;
3. No option to add additional header field such as JWT token;

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 8.5.1

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura, Version 13.6.3

### Installation method

downloaded from https://docs.insomnia.rest/insomnia/install

### Last Known Working Insomnia version

I am new to Insomnia

**Comment by gweconsulting** [comment]
user error.

**Comment by rsov** [comment]
To anyone stumbling on this:

Add a `Host` header instead of trying to change the `<calculated at at runtime>`

![Image](https://github.com/user-attachments/assets/2b073e6b-b171-49fc-b91b-675a498dd338)

**Comment by TheCarpetMerchant** [comment]
How can I remove both the fixed headers ? This is insane, why is an API testing tool forcing me to use specific headers ?
