### ISSUE TITLE
Masterpiece is becoming shit

### ISSUE THREAD

**Issue by lizihanglove** [getinsomnia/insomnia#6951]
the redundant flow of login, and the data missing. the agile speed of Masterpiece was gone and never come back just like Postman heavier and slower than ever before version by version

**Comment by FixerLT** [comment]
[Insomnium](https://github.com/ArchGPT/insomnium) is a great fork - no login required, but all features available

**Comment by subnetmarco** [comment]
@FixerLT no spam.
