### ISSUE TITLE
Environment variables no longer working

### ISSUE THREAD

**Issue by mrjimhubbard** [getinsomnia/insomnia#6956]
### Expected Behavior

I was using environment variables to avoid having to change tokens in all of my APIs. They were working and I expected them to work today.

### Actual Behavior

The API calls fail with the following message being returned from my API source...

{
	"status": {
		"code": "E0002",
		"description": "The Json request is invalid and can't be parsed",
		"method": "POST"
	}
}
![i7 SNAG- 12-31-2023 2 56 29 AM](https://github.com/Kong/insomnia/assets/90149731/ddb19d54-475e-47cf-89d2-035f8432016b)

### Reproduction Steps

Just open and use any API that uses environment variables.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

If you dispense with the environment variables and replace them with the actual tokens the client seems to retrieve the data.

![i7 SNAG- 12-31-2023 2 58 56 AM](https://github.com/Kong/insomnia/assets/90149731/1562a116-ea39-4863-b3a2-41352404ff53)

Unknown if this is related to the syncing error bug that I reported earlier....
![i7 SNAG- 12-30-2023 10 34 42 PM](https://github.com/Kong/insomnia/assets/90149731/def3fc62-3bf3-4274-93d9-ef675f332ae3)

### Insomnia Version

8.5.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### Installation method

download from the website

### Last Known Working Insomnia version

unknown

**Comment by gatzjames** [comment]
Hi @mrjimhubbard.
Could you try and wrap the variables in double quotes?
It looks like you want them to be treated as strings in the JSON you are sending but you are not wrapping them in quotes.
To verify this you can switch to the Timeline tab in the response panel and see what the body that is being sent looks like.

**Comment by gatzjames** [comment]
Closing as this seems to be an issue with using double quotes to wrap the value in a string.
Feel free to reopen if that's not the case.
