### ISSUE TITLE
To many updates on release channel

### ISSUE THREAD

**Issue by Johannes-Krabbe** [getinsomnia/insomnia#6965]
### Expected Behavior

I would like to be asked maximum once per week but probably rather 1-2 times per month if I would like to update my insomnia client (not multiple times per day)

### Actual Behavior

when selecting automatic updates, with the update channel set to Release, in the preferences I am getting asked, sometimes multiple times per day, if I would like to restart insomnia to apply the latest update.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

v8.5.1

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.0

### Installation method

download from insomnia.rest

**Comment by subnetmarco** [comment]
Hi @Johannes-Krabbe, the last Insomnia release was approximately ~2 weeks ago. Is this something you are experiencing right now, or is it something that you have experienced the past few weeks?
