### ISSUE TITLE
Base Environment Missing From Environment Manager 

### ISSUE THREAD

**Issue by JoshuaBalcitis** [getinsomnia/insomnia#6986]
### Expected Behavior

When opening the Environment Manager I was expecting to see/edit the base environment of my project as well as my sub environments.

### Actual Behavior

When opening the Environment Manager I do not see the base environment, I also can't edit it. Sub environments still appear and can be edited. The base environment variables can still be used in route URLs, headers, and query strings.

### Reproduction Steps

1. Load Project 2. Open Environment Manager

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.5.1

### What operating system are you using?

Ubuntu

### Operating System Version

Linux x64 4.15.0-213-generic

### Installation method

apt-get

**Comment by JoshuaBalcitis** [comment]
I figured out cause the issue. It is styling/positioning issue in the interface. The New Environment button is covering up the Base Environment option. Clicking just left of the grey spinner icon of the New Environment button allows me to access the base environment of the project.

**Comment by soibamohammad** [comment]
brilliant design!

**Comment by BrainBug0815** [comment]
I just had a similar issue after upgrading to v11.0
My Base Environment variable were still working but there was no Base Environment on top of my list of Environments.

But then I found out that the "New Environment" label next to the plus sign (to create a new env), is in fact the "Base Environment"
Clicking on it shows my base env variables.
Furthermore, on double click you can change that label. I reverted it to "Base Environment"

So for me it seems that the label for "Base Environment" was just changed to "New Environment" by mistake.

after renaming it, it looks now that way:
![Image](https://github.com/user-attachments/assets/45a90629-dfc4-42bd-85b3-09b5df2d4582)
