### ISSUE TITLE
A problem with file explorer window in Ubuntu 23.04

### ISSUE THREAD

**Issue by armanTabib** [getinsomnia/insomnia#6987]
### Expected Behavior

When I request to open a file, like when in multipart form, or when importing a collection, when it opens the window to select file, the file names should be shown properly

### Actual Behavior

But I get this instead: 
![image](https://github.com/Kong/insomnia/assets/139352271/eb613fd6-cb0e-43b4-a56f-ea79f69aba81)

### Reproduction Steps

1. Create a collection
2. Create a request with body type as `Multipart Form`
3. Try to upload a file

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.5.1

### What operating system are you using?

Ubuntu

### Operating System Version

23.04

### Installation method

snap

**Comment by armanTabib** [comment]
This version was installed with snap. It had also a problem in installing plugins. 
I just removed this version and installed using apt and the problem was solved.

**Comment by gatzjames** [comment]
Thanks for the info @armanTabib!
Closing since this looks like an issue with snap.
