### ISSUE TITLE
can not input Chinese correct

### ISSUE THREAD

**Issue by sdvdxl** [getinsomnia/insomnia#6988]
### Expected Behavior

can input Chinese

### Actual Behavior

when input “告警” ,can not input
![20240116094102_rec_](https://github.com/Kong/insomnia/assets/3821540/87a4d359-e365-4301-9335-118386f3d68b)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 8.4.5
Build date: 11/24/2023
OS: Darwin arm64 23.2.0
Electron: 27.0.3
Node: 18.17.1
Node ABI: 118
V8: 11.8.172.16-electron.0
Architecture: arm64

### Insomnia Version

8.4.5

### What operating system are you using?

macOS

### Operating System Version

Apple M1 Pro 14.2.1 (23C71)

### Installation method

download

### Last Known Working Insomnia version

8.3.x

**Comment by jackkav** [comment]
Should be fixed in 8.5.1

(arrow keys were causing a loss of focus)
