### ISSUE TITLE
In 8.6.0, Overview, Certificate and Client Certificate tabs are missing in Scratch Pad settings

### ISSUE THREAD

**Issue by sathyarajagopal** [getinsomnia/insomnia#6999]
### Expected Behavior

Insomnia Scratchpad settings should have 3 tabs - Overview, Certificate and Client Certificate.

### Actual Behavior

After upgrading to 8.6.0, Overview, Certificate and Client Certificate tabs are missing in Scratch Pad settings.

### Reproduction Steps

1. Go to Scratch Pad >> Settings

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.2.1

### Installation method

https://insomnia.rest/

### Last Known Working Insomnia version

8.5.2-beta.0

**Comment by gatzjames** [comment]
Hi @sathyarajagopal. In 8.6 we added a new place to manage certificates.
On the sidebar there is now a button bellow the environments and cookies ones that opens a new modal to manage your certificates.

<img width="922" alt="image" src="https://github.com/Kong/insomnia/assets/12115431/d00bea25-0c68-4d07-947f-41c9ebc2300e">
