### ISSUE TITLE
[Bug] GraphQL pane size too big with lots of variables

### ISSUE THREAD

**Issue by Yamilquery** [getinsomnia/insomnia#700]
The Query Variables windows is to big and I can't resize.

<img width="1440" alt="captura de pantalla 2018-01-10 a la s 14 01 37" src="https://user-images.githubusercontent.com/6020065/34792804-d4830320-f60e-11e7-9375-78950bc00ab3.png">

It's seems to be a bug with Insomnia on GraphQL mode in Mac OS X.

**Comment by gschier** [comment]
Yep, this definitely looks like a bug. I'll get it fixed.
