### ISSUE TITLE
Command palette search not working the same as other searches

### ISSUE THREAD

**Issue by JeroenVdb** [getinsomnia/insomnia#7009]
### Expected Behavior

I think [the current code for the filter](https://github.com/gatzjames/insomnia/blob/ab95f6c48d082f79fdb1c909f56ef4afa2edce6b/packages/insomnia/src/ui/components/command-palette.tsx#L48-L51) needs some improvements.

The current filter splits the filter query and adds wildcards between each character. Which leads to some weird items not being filtered out because they "accidentally" have those characters (in that order) somewhere in their text.

I would expect a better "fuzzy" search like in the previous version of the command palette.

For example, search for "scen"

Returns:
- "GET /scenarios {{ _.ServiceBaseUrl }}/scenarios"

### Actual Behavior

WIth the current filter, the search for "scen"

Returns:
- "GET /scenarios {{ _.ServiceBaseUrl }}/scenarios"
- "GET /changes {{ _.ServiceBaseUrl }}/changes"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The previous ["request-switcher" used the `fuzzyMatchAll` util function](https://github.com/Kong/insomnia/blob/d385ffa5d74f3251a32d697051bc0309e98c12af/packages/insomnia-app/app/ui/components/modals/request-switcher-modal.tsx#L220-L226C7). As [this function still exists](https://github.com/Kong/insomnia/blob/d385ffa5d74f3251a32d697051bc0309e98c12af/packages/insomnia-app/app/common/misc.ts#L284) it might be an easy change again use this way of filtering.

**I think people are used to this way of (fuzzy) searching because it is also used like this in the workspace search filter and the workspace requests search functionality.**

**Because at this point the requests search filter returns other results (but more accurate) then the same search via the command palette. Same for the workspaces.**

### Insomnia Version

8.6.0

### What operating system are you using?

macOS

### Operating System Version

13.6 (22G120)

### Installation method

download from website

**Comment by gatzjames** [comment]
Thanks for the issue and PR! This will come out in the next patch release!
