### ISSUE TITLE
Is there a way to disable automatic cookie handling?

### ISSUE THREAD

**Issue by oliverjanik** [getinsomnia/insomnia#701]
When doing deep investigation of issues. I need as little magic as possible. Can I have a configuration to disable automatic cookie handling?

Pure unadulterated http request and response is all I ask for.

**Comment by gschier** [comment]
Yep, you can configure this in the request settings, accessible via the dropdown menu beside the request in the sidebar.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/587576/34973189-0267a5ee-fab9-11e7-9969-8eeab6108ee4.png">
<img width="443" alt="image" src="https://user-images.githubusercontent.com/587576/34973191-05731e6c-fab9-11e7-80d2-87a11ffbecad.png">
