### ISSUE TITLE
Command palette on workspace overview page

### ISSUE THREAD

**Issue by JeroenVdb** [getinsomnia/insomnia#7011]
### Expected Behavior

I would expect the command palette to be available on the "workspace overview" page. The command palette would offer you to search and open workspaces.

I would not expect to search for all calls (over all workspaces) here.

### Actual Behavior

The command palette is not available if you don't have a workspace open.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.0

### What operating system are you using?

macOS

### Operating System Version

13.6 (22G120)

### Installation method

download from website

**Comment by gatzjames** [comment]
👋 @JeroenVdb thanks for the issue and PR. This will be released in the next patch version!
