### ISSUE TITLE
Can't login to Insomnia with Email - get Something went wrong error

### ISSUE THREAD

**Issue by zhimin-gu** [getinsomnia/insomnia#7021]
### Expected Behavior

Hello,

I am trying to login to Insomnia with my email. Once I typed my email address and click Continue with Email button.
I got the screen shot as below:
The url is https://app.insomnia.rest/app/authorize/email
<img width="377" alt="Screenshot 2024-01-24 at 11 40 31 PM" src="https://github.com/Kong/insomnia/assets/50279611/8a43198b-5f60-4d12-a320-1e0bef6193b3">

Looks like this is something that the team is aware of and it is being fixed? 

Thank you for your help!

### Actual Behavior

<img width="377" alt="Screenshot 2024-01-24 at 11 40 31 PM" src="https://github.com/Kong/insomnia/assets/50279611/8e73269b-0bc5-4b8d-b3e9-77cec7f88c33">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.2.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.6

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

same version worked in Dec 2023

**Comment by zhimin-gu** [comment]
Note that I do receive a 6 digits code from my email address. But that is not solving my problem.

**Comment by notjaywu** [comment]
@zhimin-gu Could you send me your account email address?

**Comment by zhimin-gu** [comment]
Thank you @notjaywu My account email address is gzmmin@outlook.com

I tried it today and I saw the same behavior. Appreciate your help!

**Comment by notjaywu** [comment]
@zhimin-gu Could you share your screenshots for both `Console` and `Network` when logging in?

<img width="610" alt="image" src="https://github.com/Kong/insomnia/assets/130019718/75f2a233-260a-4270-b461-7c0e950da20a">

**Comment by zhimin-gu** [comment]
Hello @notjaywu Sure. Looks like it's 403 error. I attached the screenshot.
![Screenshot 2024-02-02 at 2 53 02 AM](https://github.com/Kong/insomnia/assets/50279611/93ee1e94-4098-4e03-a013-28d61bd938ea)
![Screenshot 2024-02-02 at 2 52 50 AM](https://github.com/Kong/insomnia/assets/50279611/0be760c8-b99c-4411-bec0-0a6b974f9fc7)

**Comment by zhimin-gu** [comment]
Also when I am using a new account - google gmail to login, it worked fine.
I have a bunch of API request/response setup configured under gzmmin@outlook.com, is there a way to get the config file so that I can import to my new account?

**Comment by zhimin-gu** [comment]
Hello @notjaywu Thank you for your help! Looks like it's blocked by a security policy configured locally. I have removed it and got it work. Appreciate your help!
