### ISSUE TITLE
request encoding causing an issue

### ISSUE THREAD

**Issue by rcrooks** [getinsomnia/insomnia#703]
one of our APIs includes search parameters like this: ?q=tags:foo+name:bar

it looks like Insomnia is using encodeURIComponent to encode that, so that ":" gets encoded as %3A (which our API misinterprets (thinks it's one sting "name%3Abar")

Not sure if you will consider this your bug or ours, but letting you know.

Thanks!

**Comment by besolov** [comment]
Insomnia supports “Not encode URL” option, so you can use it. You can find it in the request settings:
![image](https://user-images.githubusercontent.com/1052800/35153866-3036844a-fd39-11e7-90cc-b497f2f57002.png)
![image](https://user-images.githubusercontent.com/1052800/35153876-38f28b4c-fd39-11e7-928e-ca71861784dc.png)

**Comment by rcrooks** [comment]
@besolov awesome! I never noticed that....

**Comment by rcrooks** [comment]
Closing issue
