### ISSUE TITLE
[Suggestion] Add support for JSON5

### ISSUE THREAD

**Issue by gmenih341** [getinsomnia/insomnia#704]
If the slogan of this app is **Debug APIs like a human, not a robot**, then perhaps it should add support for [JSON5](https://github.com/json5/json5), since it's slogan is **JSON for humans**.

I can implement this, if you give me some pointers as to where to add this?

**Comment by gschier** [comment]
Hey @gmenih341,

Can you give some more detail as to where and how this would be used inside Insomnia? Do you mean sending JSON5 data directly to the server as the request body, using JSON5 in environments, etc?

**Comment by Gennnji** [comment]
Honestly, I would prefer JSON5 at least for JSON request body textarea. It would be useful to comment/uncomment some lines for JSON just to see different behaviours of API.

**Comment by gmenih341** [comment]
@gschier in the body request builder. It could also be used in the environment setup, but mainly I want this in the body builder.

**Comment by Gabb1995** [comment]
I think it makes sense for both, having comments is huge plus. Obviously I would still need to send json data not json5 and I think you can have some sort of converter from json5 to json.

So basically I think what should happen is all json in Insomnia can be written as JSON5 then converted to JSON before sending the request.

**Comment by gschier** [comment]
FYI you can add comments to the request body using Nunjucks comments.

```json
{
  {# This is a comment #}
  "my": "body"
}
```

It's not the best experience because it causes a linting error to appear, but it's a start. Note, this does not work in the environment JSON because it needs to be valid JSON _before_ rendering is done.
