### ISSUE TITLE
OpenAPI import empty

### ISSUE THREAD

**Issue by loranger** [getinsomnia/insomnia#7047]
### Expected Behavior

Hi,
I would expect the json import create all the request and environment listed.

### Actual Behavior

I import the json file, but it remains empty.
Maybe I didn't understand?

### Reproduction Steps

1. Download the swagger api schema example from https://editor.swagger.io/
2. Import in Insomnia
<img width="801" alt="SCR-20240201-qzud" src="https://github.com/Kong/insomnia/assets/6014/dd82487a-62f3-40f5-ba0b-f106c82c68d2">
3. Insomnia found 19 requests and 2 environments
<img width="814" alt="SCR-20240201-racj" src="https://github.com/Kong/insomnia/assets/6014/4f0bccc6-f694-4b58-b485-ba28071c0444">
4. Import succeeded  <br />
<img width="251" alt="SCR-20240201-rahf" src="https://github.com/Kong/insomnia/assets/6014/99cf758a-2558-43c5-9bf4-dfc93a8aa2fe">

5. Requests collection is empty  <br />
<img width="521" alt="SCR-20240201-raqv" src="https://github.com/Kong/insomnia/assets/6014/d237e21f-961b-4ca3-b790-7c72bf697fa1">

6. Environments either <br/>
<img width="635" alt="SCR-20240201-rbla" src="https://github.com/Kong/insomnia/assets/6014/ff35c787-03d6-4198-8e9d-96ae8250c67d">

Did I miss something?

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.3 (23D56)

### Installation method

homebrew

**Comment by jackkav** [comment]
There is a cog in the top left of the design view with a generate request ms option. This will export the paths in the doc to the collection.

**Comment by loranger** [comment]
Unfortunately, this doesn't work for an [OpenApi v3.0.3](https://nur1.pl-p8-01704-0078.polarisgestionmag.net:3443/api/WebConnect/doc.json) I work with :/


<img width="1285" alt="SCR-20240208-kcgo-2" src="https://github.com/Kong/insomnia/assets/6014/63c20510-0615-48bc-9e4a-74bb10f51b51">
