### ISSUE TITLE
[Feature Request] - Hotkey to switch between recent requests

### ISSUE THREAD

**Issue by benzhou29** [getinsomnia/insomnia#705]
# Feature Request
I am requesting that we introduce a new hotkey that allows you to toggle between your most recent requests. This is very similar to toggling between most recent applications on your OS. 

# Use Case
Often I find myself comparing two more api requests. For example, I might have a (GET) request that returns all the children for a specific resource. Each child has an "id". I then use the "id" of a child to get more information about that child in a different api request. 

Another use case would be comparing the responses of two or more requests. 

Right now, what I have to do is use the "Switch Requests" hotkey, then type in the name of the request, make the request, switch request again, type in the name of the request and repeat.

**Comment by mailsanchu** [comment]
This is a good feature. Not sure why it is closed
