### ISSUE TITLE
UX: Email verification page is confusing without displaying entered email

### ISSUE THREAD

**Issue by CatalanCabbage** [getinsomnia/insomnia#7082]
### Expected Behavior

The text on that verification page says `We've sent a verification email to xyz@example.com`

### Actual Behavior

On logging into the Electron client, a URL is opened.  
To create an account, it prompts us to enter the email.  
On the next screen, it asks for the verification code.

Problem: I didn't receive an email for several minutes and I started to wonder if I'd entered the correct email in the first place. However, the email isn't displayed on this screen. For better UX, it should be.
![image](https://github.com/Kong/insomnia/assets/45961072/016b9f63-44c6-442f-b602-461871b4436f)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

latest

### What operating system are you using?

Windows

### Operating System Version

Windows

### Installation method

downloaded from the website

**Comment by CatalanCabbage** [comment]
I want to submit a PR to fix this. However, the code for this seems to be on the webapp (`app.insomnia.rest`) and it isn't in this repo (which has Electron client code). 

Can someone point me to the correct repo please?

**Comment by subnetmarco** [comment]
Hi @CatalanCabbage, the website repository is private. I passed this feedback to the team, it should be easy to update.

Thanks for wanting to contribute.

**Comment by CatalanCabbage** [comment]
@subnetmarco got it, thanks! Feel free to close the issue/keep it around till the team pushes that. :)

**Comment by subnetmarco** [comment]
This has been deployed.

**Comment by CatalanCabbage** [comment]
That was surprisingly quick. Thanks @subnetmarco! 💯
