### ISSUE TITLE
[Feature Request] Allow application data folder to be a symlink

### ISSUE THREAD

**Issue by browniebroke** [getinsomnia/insomnia#710]
- Insomnia Version: 5.12.4.1752
- Operating System: macOS Sierra 10.12.6

## Details

I recently changed laptop and I had a lot of applications settings backed-up using [Mackup](https://github.com/lra/mackup). It works by actually storing the applications settings in Dropbox, iCloud or similar and adding a symlink to the Dropbox folder where the app is looking for them.

I was [trying to add support for Insomnia](https://github.com/lra/mackup/issues/1115), but when I tested I realised that the app crashes if I create such a symlink:

<img width="422" alt="screen shot 2018-01-15 at 18 56 21" src="https://user-images.githubusercontent.com/861044/34957811-0cbb846c-fa27-11e7-8345-7b4ecc481c23.png">

Would it be possible to make sure the paths are resolved when accessing DBs? I guess it would involve changing [`getDBFilePath()`](https://github.com/getinsomnia/insomnia/blob/549ce23ce8cf202d787ca4df5efc5f25e03311ed/packages/insomnia-app/app/common/database.js#L27-L32) to call [`realPath`](https://nodejs.org/docs/latest/api/fs.html#fs_fs_realpath_path_options_callback)?

**Comment by browniebroke** [comment]
I've tried to start a piece of work on that, but my knowledge in Electron/node might be too limited... It seems there are quite a lot of lines to change which are too close from comments like `// NOTE: Do not EVER change this. EVER!`.

**Comment by gschier** [comment]
Hey @browniebroke. 

I just tried testing this on my end and I can't reproduce the same error. Here's what I did:

1. `mv ~/Library/Application\ Support/Insomnia ~/Dropbox/Insomnia`
2. `ln -s ~/Dropbox/Insomnia ~/Library/Application\ Support/Insomnia`

Everything seems to be working fine after linking the folder. Have you set yours up in a different way?

**Comment by gschier** [comment]
I don't think this is a problem, but `.config/Insomnia` should not be listed in your [commit](https://github.com/browniebroke/mackup/commit/ebebfcd6a8c3c358342a99dfe8cb7a6c1b86e364), as it's not used by Insomnia.

**Comment by gschier** [comment]
Here's some more info on what my setup looks like. If you could share yours, that would be great.

```bash
$ pwd
/Users/gschier/Library/Application Support
$ ls -l Insomnia
lrwxr-xr-x  1 gschier  staff  31 Jan 16 13:47 Insomnia -> /Users/gschier/Dropbox/Insomnia
```

<img width="400" alt="image" src="https://user-images.githubusercontent.com/587576/34975859-6448f8be-fac6-11e7-9d6f-7254430cfa4f.png">

**Comment by browniebroke** [comment]
Hi,

You're right, just tried again with the command line and it works. I was actually creating an alias using the Finder, which I thought was the same, but [they are not](https://www.lifewire.com/aliases-symbolic-links-hard-links-mac-2260189).

Apologies for the confusion this may have caused and thank you for taking the time to trying to reproduce.

This issue may be closed now.

**Comment by gschier** [comment]
No worries. Glad it's working now! 👍 😄
