### ISSUE TITLE
[Bug] GraphQL operationName does not update when query modified

### ISSUE THREAD

**Issue by rocketraman** [getinsomnia/insomnia#712]
- Insomnia Version: 5.12.4
- Operating System: Fedora 26

## Details

For GraphQL queries, Insomnia seems to not update the operation name properly.

For example, doing a query like this:

```
query foo {
  something {
    ...
  }
}
```

works fine. But then, if the above is changed to:

```
query foo1 {
  something {
    ...
  }
}
```

the query that is sent uses the original operationName of `foo`. This can be seen in the timeline:

```
| {"query":"query foo1 {\n  ...\n","operationName":"foo"}
```

NOTE that the operation name is updated, but it doesn't apply until the *next* change. So if the query is changed to `foo2`, then the operation name is sent as `foo1`.

One workaround is to click the "Pretty-print" button, which then seems to cause Insomnia to sync the `operationName`. But clearly this should not be necessary.

**Comment by gschier** [comment]
Thanks for reporting this @rocketraman. Should be fixed in the next release :)
