### ISSUE TITLE
Sort order of project folders reset after restart and drag & drop broken

### ISSUE THREAD

**Issue by RyseSlade** [getinsomnia/insomnia#7130]
### Expected Behavior

When I click the sort icon I expect my folders to sort according to the seletion e.g. Name Ascending (A-Z). Next time I open the IDE the sorting should still be that way.

### Actual Behavior

After I click the sort button the sorting is applied but after restart of the IDE it is reset to "Manual" and the previous sorting is lost. Also drag & drop of folders and requests does not work at all after clicking the sort button.

### Reproduction Steps

Create a new project with a new collection. Create a folder "a" and "b". Close IDE and restart. Click the sort button and select "Name Ascending". Close and restart IDE. Previous sorting is lost. It is set back to "Manual". Also after seleting a sort option drag & drop does not work anymore.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

download from insomnia website

**Comment by rahul-kumar-sdet** [comment]
I can confirm this issue is persisting.

**Comment by z3us22** [comment]
This is a huge issue cause the order of my folders and requests were also destroyed after the last update.

**Comment by gabrielsouza404** [comment]
Same problem here.

**Comment by Farenheith** [comment]
This is a big problem, it really gets in the way of the daily tasks. I'll downgrade the app so the work can flow easily

**Comment by mandarbansod** [comment]
I have the same issue and I guess I can put in a PR to fix this

**Comment by amustaine** [comment]
I still have this problem when restarting or adding a new request. Version - v10.1.1

**Comment by nqdung16** [comment]
Still got this on v10.2.0
