### ISSUE TITLE
Changing the HTTP method in a Server-Sent Events call does nothing

### ISSUE THREAD

**Issue by ttyS0e** [getinsomnia/insomnia#7139]
### Expected Behavior

When using an SSE test call, in Collections, I want to select the "POST" method so that I can test streaming chatbot-response text back from my LLM, e.g. OpenAI.

### Actual Behavior

I get "method not allowed" from OpenAI, even though I have selected POST, which make me think that the method is not changed.

![image](https://github.com/Kong/insomnia/assets/64026310/c72e2225-988a-46ab-9a68-ebf40db55c4f)

I've tested this when running through Kong's AI Gateway too, and I get "No Route matches these values" despite the Kong route itself being a "POST" type matcher. I can change it to "GET" in Kong, and it works which demonstrates to me that it's always sending GET despite what is set in Insomnia UI.

### Reproduction Steps

1. Create an SEE type Request:

- Set method: `POST` 
- Set URL: `https://api.openai.com/v1/chat/completions` 
- Set an OpenAI auth key header :`Authorization: Bearer sk-.......`
- Set header: `Accept: text/event-stream`

2. Set sample body:

```json
{
  "messages": [
    {
      "role": "user",
      "content": "What is 1 + 1?"
    }
  ],
  "model": "gpt-4",
  "stream": true
}
```

3. See "wrong method" failure description comes back from OpenAI.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.1

### What operating system are you using?

macOS

### Operating System Version

14.2.1

### Installation method

Insomnia Website

**Comment by jackkav** [comment]
Closed in #7182
