### ISSUE TITLE
Insomnia.rest Website Not Available

### ISSUE THREAD

**Issue by GeekyADAMS** [getinsomnia/insomnia#7140]
### Expected Behavior

To open up insomina.rest website when visited or when OAuth is used for signin.

### Actual Behavior

Website url not accessible

<img width="865" alt="Screenshot 2024-03-03 at 17 53 36" src="https://github.com/Kong/insomnia/assets/31047369/a1ee1a66-1c3a-4047-a0a2-98cb1947421d">

### Reproduction Steps

1. Go to insomnia.rest

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 8

### What operating system are you using?

macOS

### Operating System Version

MacOS Sonoma 14.1.1

### Installation method

homebrew

**Comment by subnetmarco** [comment]
Is this still happening? It is working fine for me.
