### ISSUE TITLE
flathub/flatpak version is outdated

### ISSUE THREAD

**Issue by Abdull** [getinsomnia/insomnia#7151]
### Expected Behavior

[Insomnia's Flatpak releases at Flathub](https://flathub.org/apps/rest.insomnia.Insomnia) should be up-to-date.

### Actual Behavior

As of this writing, the Insomnia flatpak release at https://flathub.org/apps/rest.insomnia.Insomnia is `2023.5.8` (released September 7, 2023), while the latest release available elsewhere is `8.6.1` (released February 6, 2024).

### Reproduction Steps

```
flatpak install flathub rest.insomnia.Insomnia
```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.1

### What operating system are you using?

Other Linux

### Operating System Version

Linux Abdull 6.5.0-0.deb12.1-rt-amd64 #1 SMP PREEMPT_RT Debian 6.5.3-1~bpo12+1 (2023-10-08) x86_64 GNU/Linux

### Installation method

download from insomnia.rest, as flathub version is too old

**Comment by filfreire** [comment]
Hi @Abdull, this is not maintained by the Insomnia team at the moment but by the community
https://github.com/flathub/rest.insomnia.Insomnia

**Comment by Abdull** [comment]
@filfreire , thank you for following up and reporting https://github.com/flathub/rest.insomnia.Insomnia/issues/79

> Hi @Abdull, this is not maintained by the Insomnia team at the moment but by the community https://github.com/flathub/rest.insomnia.Insomnia

I mistakenly thought the flatpak Insomnia version https://flathub.org/apps/rest.insomnia.Insomnia is maintained by the *Insomnia* team or *Kong*,

* given the reverse DNS application ID `rest.insomnia.Insomnia`
* the details page says *Insomnia by Kong*.
   
  ![image](https://github.com/Kong/insomnia/assets/529862/f46f9d6a-f13a-43d2-b653-c6c4796d9fc2)


So the Insomnia team is currently **not** the only authorized circle of people that can make changes to the Insomnia app as distributed via Flathub?

**Can the Insomnia team trust "[the community](https://github.com/flathub/rest.insomnia.Insomnia/graphs/contributors)" to provide releases free of problems under the name "Kong"/"Insomnia"? Does the Insomnia team know the full list of those with authorization to push changes?**

[Kong/the Insomnia team should consider taking sole exclusive ownership of Insomnia's Flathub representation](https://docs.flathub.org/docs/for-app-authors/submission/#someone-else-has-put-my-app-on-flathubwhat-do-i-do).
