### ISSUE TITLE
Insomnia does not install

### ISSUE THREAD

**Issue by coltonhurst** [getinsomnia/insomnia#7162]
### Expected Behavior

I expected to download Insomnia, run the installer, and see Insomnia in my applications list.

### Actual Behavior

I downloaded Insomnia, ran the installer, and did not see the app.

### Reproduction Steps

On an M1 Mac:

1. Go to the latest releases for Insomnia [here](https://github.com/Kong/insomnia/releases)
2. Download `inso-macos-latest-8.6.1.pkg ` under the `8.6.1` release [here](https://github.com/Kong/insomnia/releases/tag/lib%408.6.1)
3. Run the `.pkg` file and install Insomnia
4. Check the `Applications` folder, Insomnia is not present

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I attempted the installation, did not see the application after the installation completed, restarted my computer, and still did not see it. I re-downloaded the .pkg file, ran the installer again, and still did not see Insomnia.

I ran `find / -type f -name '*insomnia*' 2>/dev/null` in Terminal as an attempt to see if there were any installed Insomnia files. I have never installed Insomnia before. This is was the output:

```
/System/Volumes/Data/private/var/db/receipts/com.insomnia.inso.bom
/System/Volumes/Data/private/var/db/receipts/com.insomnia.inso.plist
/private/var/db/receipts/com.insomnia.inso.bom
/private/var/db/receipts/com.insomnia.inso.plist
```

What am I doing incorrectly?

### Insomnia Version

8.6.1

### What operating system are you using?

macOS

### Operating System Version

Mac OS Sonoma 14.3.1

### Installation method

Downloaded from the GitHub releases page

### Last Known Working Insomnia version

I have never installed Insomnia before

**Comment by subnetmarco** [comment]
We are looking into this problem.

**Comment by subnetmarco** [comment]
@coltonhurst Hello, it seems like you may have downloaded the CLI. Can you try to download Insomnia proper at https://github.com/Kong/insomnia/releases/tag/core%408.6.1

Let me know!

**Comment by coltonhurst** [comment]
@subnetmarco _oooooof_, that was the mistake. Thanks for replying, total misread on my part! 🤦‍♂️ I can't believe I made this mistake 🫠

Any tips on what the CLI might have changed so I can undo it and then install Insomnia normally?

**Comment by subnetmarco** [comment]
The CLI program name is "inso", so if you search for that you should see where it installed it to.
