### ISSUE TITLE
ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

### ISSUE THREAD

**Issue by DesFelasaf** [getinsomnia/insomnia#7188]
### Expected Behavior

Insomnia opens

### Actual Behavior

Insomnia doesn't opens
Processes appear in task manager, but UI doesn't load
in the log:
C:\Program Files\Insomnia\app-2023.4.0>start Insomnia.exe
C:\Program Files\Insomnia\app-2023.4.0>
processing squirrel command `undefined`
16:49:37.999 > Running version 2023.4.0
16:49:38.005 > [electron client protocol] successfully set default protocol 'insomnia://'
16:49:38.316 > [fix] Running database repairs
[15420:0318/165139.102:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

### Reproduction Steps

Start Insomnia

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.4.0

### What operating system are you using?

Windows

### Operating System Version

10

### Installation method

downloaded

### Last Known Working Insomnia version

2021.5.0

**Comment by filfreire** [comment]
Hi @DesFelasaf we don't support that older version of insomnia, I would recommend you attempt a more recent one, like [8.6.1](https://github.com/Kong/insomnia/releases/tag/core%408.6.1)
