### ISSUE TITLE
[Bug] UUID generation breaks layout of documentation markdown code block

### ISSUE THREAD

**Issue by puresick** [getinsomnia/insomnia#720]
- Insomnia Version: 5.12.4
- Operating System: Arch Linux

In my case, I created a code block in the documentation markdown file like this:
```
{
    "relation_id": STRING TYPE uuid
}
``` 
After writing `uuid`, I used the auto completion to generate some UUID v4 string.
This will result in the generated UUID String to break out of the visual code block, overflowing it:

![insomnia_bug](https://user-images.githubusercontent.com/2714266/35146653-eded1e46-fd0b-11e7-9c4c-5f75fbb2be39.png)

Update: This seems to be an issue in general with strings being to long for the max-widht of the code block container.

**Comment by gschier** [comment]
Thanks for reporting this! Code blocks should probably be horizontally scrollable to account for long lines.
