### ISSUE TITLE
Unable to remove/clear `Query Variables` from an API test request

### ISSUE THREAD

**Issue by MKHokinson** [getinsomnia/insomnia#7204]
### Expected Behavior

Deleting the JSON data in the `Query Variables` section should save when sending a request/returning to the request document page. This also stops anyone from switching through multiple requests in the same test document if any of the requests require different query variables. 

### Actual Behavior

Reloading the page in any way (ex. clicking off+on the page or sending a request) will return the JSON body to the input box. 

### Reproduction Steps

1. Open a new test document
2. Begin editing a GraphQL request to an endpoint 
3. Add `Query Variables` to the request 
4. Make a request with those variables (successfully)
5. Try to remove those variables and send a new request which doesn't require the variables

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Full insomnia version info: 

```
Version: Insomnia 8.6.1
Build date: 2/5/2024
OS: Darwin arm64 23.4.0
Electron: 28.0.0
Node: 18.18.2
Node ABI: 119
V8: 12.0.267.8-electron.0
Architecture: arm64
```

### Insomnia Version

v8.6.1

### What operating system are you using?

macOS

### Operating System Version

MacOS 14.4 (23E214)

### Installation method

Web download

**Comment by MKHokinson** [comment]
I've linked a quick fix for this above, looks like it may have been introduced in a recent change [here](https://github.com/Kong/insomnia/commit/8d8560f025769f591322e304945aca440c6fd8b0)

**Comment by subnetmarco** [comment]
@MKHokinson thanks! We will take a look, we may be able to push this in the next release.
