### ISSUE TITLE
CAN'T Login!

### ISSUE THREAD

**Issue by raykle** [getinsomnia/insomnia#7218]
### Expected Behavior

Can't Login the mac app from the website.

<img width="1739" alt="image" src="https://github.com/Kong/insomnia/assets/3097366/ef307971-810a-47ef-b163-f99e31e08682">

### Actual Behavior

Enter the passphrase on the website, and it shows error: "Invalid passphrase, please try again".

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.1

### What operating system are you using?

macOS

### Operating System Version

MacOS Sonoma 14.3.1 (23D60)

### Installation method

download from insomnia.rest

**Comment by marckong** [comment]
Hi @raykle, Insomnia's web app relies on the same site origin policy for all requests. Is there anything that you are doing to remove the origin from the request header sent from the browser? For instance, if you are running a proxy to intercept the request, this can happen. We have not been able to reproduce it. Please let us know.

cc: @subnetmarco

**Comment by marckong** [comment]
@raykle Can you also please share the request header with us?

**Comment by raykle** [comment]
@marckong 
Sorry, it's my fault. It should be the proxy matters.
It's ok now.
