### ISSUE TITLE
Environment variable does not get resolved in the URL (beta)

### ISSUE THREAD

**Issue by solorisx** [getinsomnia/insomnia#7219]
### Expected Behavior

Environment variable gets resolved when sending a request when used in the URL

### Actual Behavior

Environment variable shows up in the preview, but not in the actual request. Using environment variables in headers works.

![image](https://github.com/Kong/insomnia/assets/25752129/3d1d1c8f-a7ca-423c-9d81-a9ddf686a2d0)

### Reproduction Steps

1. Set environment variable
2. Use environment variable in request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.0.0-beta.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

download from Github (exe)

**Comment by subnetmarco** [comment]
We are looking into this.

**Comment by CurryYangxx** [comment]
@solorisx Hi! Do you add any pre-request script?

**Comment by solorisx** [comment]
@CurryYangxx Yes, I did. Without it works indeed. Thanks for the quick response!
