### ISSUE TITLE
The API Key is not added to the query parameters

### ISSUE THREAD

**Issue by alexlenartovich** [getinsomnia/insomnia#7235]
### Expected Behavior

When using an API key in query parameters, the parameter must be appended to the URL.

![image](https://github.com/Kong/insomnia/assets/31478571/9fd748ed-101f-4cb8-be82-f114aa21c501)

### Actual Behavior

The parameter is not being added now

![image](https://github.com/Kong/insomnia/assets/31478571/af59bfa8-82bd-49be-b496-7a95738ccd29)

### Reproduction Steps

1. Select API Key Auth as Auth Type
2. Set Add To to Query Parameters
3. Fill Key and Value fields
4. Done - parameter was not added

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 (Windows_NT x64 10.0.22631)

### Installation method

Download from official site

**Comment by ihexxa** [comment]
Hello @alexlenartovich, this should only happen to the preview, those params are actually sent.
I've added a fix for this, thanks for the feedback.
