### ISSUE TITLE
Pre-request Script command insomnia.request.url.removeQueryParams("foo") removes all parameters but the one named "foo"

### ISSUE THREAD

**Issue by niklam** [getinsomnia/insomnia#7236]
### Expected Behavior

I have URL `https://example.tld/?pretty=0&foo=value1&bar=value2`.

I'm calling `insomnia.request.url.removeQueryParams("foo")`. 

I expect to get URL `https://example.tld/?pretty=0&bar=value2`

### Actual Behavior

The result is `https://example.tld/?foo=value1`

### Reproduction Steps

1. Add a URL `https://example.tld/?pretty=0&foo=value1&bar=value2` for HTTP request
2. Add Pre-request Script with `insomnia.request.url.removeQueryParams("foo")`
3. Send the request.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Using `insomnia.request.url.removeQueryParams(["foo"])` works as expected.

### Insomnia Version

v9.0.0-beta.3

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.4.1

### Installation method

Downloaded from Insomnia, choosing Update Channel "Early access (beta)"

**Comment by ihexxa** [comment]
Thanks for reporting it, this issue is already detected, and the fix is in review: https://github.com/Kong/insomnia/pull/7225/files#diff-80753d0078a8b39246080d56a694cfa6f1427035599276beb5bcf77681fec7a6R286
Hopefully it will be included in the next release.

**Comment by niklam** [comment]
@ihexxa thank you! If there's an issue for this, I must have missed it. Sorry for that!

**Comment by niklam** [comment]
@ihexxa I need to still ask if the fixes in the PR address the issue that if you've done "Import from URL" for params, the params are not seen by `insomnia.request.url`? So you can't remove them, and they are always being added to the final URL. If not, I'm happy to file another issue.

![image](https://github.com/Kong/insomnia/assets/1212395/130395f8-a73e-4a42-abee-d33ba4248307)

![image](https://github.com/Kong/insomnia/assets/1212395/f32dde95-c7ac-4d90-b63d-2d9eecc85f4f)
