### ISSUE TITLE
[Feature Request] Enable change in layout

### ISSUE THREAD

**Issue by kalinchernev** [getinsomnia/insomnia#725]
## Details

First of all - thank you for creating the project! I've been using it in the last couple of weeks in a replacement of Postman, so far I have better user experience!

I was thinking if it could be easily possible to configure, or at least swap the places of the authentication and response panels. At least for GET request flow, the panel on the left is almost useless, and stays empty most of the time. When in GET request flow, the panel could be above or below the response panel, like in [cocoa-rest-client](https://mmattozzi.github.io/cocoa-rest-client/)

At the same time, I think the panel totally makes sense in POST request flows, so it's a matter of adding a bit of flexibility in the UI. First useful iteration might be that I can at least toggle it like the sidebar.

Again, thank you for the project!

**Comment by kalinchernev** [comment]
I actually found an option for that!

**Comment by AndreaFranchini** [comment]
> I actually found an option for that!

Can you tell me where? I can't find it!

**Comment by kalinchernev** [comment]
![Screenshot_20190711_140418](https://user-images.githubusercontent.com/1923476/61049650-47dcc600-a3e5-11e9-9f9a-239bf4b845d8.png)

**Comment by thebestfella** [comment]
Perfect thanks
