### ISSUE TITLE
[Feature Request] Add support for AWS Signature V2

### ISSUE THREAD

**Issue by garnold** [getinsomnia/insomnia#728]
Insomnia currently supports AWS Signature V4, but we are using an API that uses AWS Signature V2. The [signature format is described here](https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html).

A couple of nice to haves:
- Support both the [`Authorization` header](https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#ConstructingTheAuthenticationHeader) and [query string alternative].(https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationQueryStringAuth)
- Support changing the `Authorization` header prefix ("AWS"), ie. `Authorization: Bearer AWSAccessKeyId:Signature` instead of `Authorization: AWS AWSAccessKeyId:Signature`.

**Comment by focusaurus** [comment]
Am I reading this right? 

> Amazon S3 now supports the latest Signature Version 4. This latest signature version is supported in all regions and any new regions after January 30, 2014 will support only Signature Version 4. 

Are you requesting support for something that has been deprecated for 4 years? Which API specifically are you calling?

**Comment by gschier** [comment]
If it's deprecated and there is no other interest, I suggest writing this one as a custom plugin. If you want to submit a PR I'd probably merge it regardless, but I agree that it's probably not worth implementing (from a product perspective) if it's not in wide use.
