### ISSUE TITLE
Double backslash at end of Environment JSON key freezes entire app, corrupts collection

### ISSUE THREAD

**Issue by j1mmie** [getinsomnia/insomnia#7286]
### Expected Behavior

Double-backslash at end of environment JSON key should be valid

### Actual Behavior

Double-backslash at end of environment JSON key freezes entire app and corrupts collection

### Reproduction Steps

1. Create a new "Request collection". Name it anything
2. Click the cog icon near "Base environment"
3. Enter the following JSON:

```
{
  "What": "dafuq"
}
```

4. Click after the letter t in What to move the cursor there. Type in `-\\`, resulting in the following JSON:
```
{
  "What-\\": "dafuq"
}
```

Note that shortly after typing the two backslashes, the app will freeze

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Screencap: https://imgur.com/jD6c4S4

This corrupts the collection. Whenever the collection is loaded again, the app freezes. On macOS, the "unresponsive app" warning dialog shows.

Sometimes "\\" alone will not freeze the app. Sometimes there must be a \ somewhere else in the string, or a - immediately before it. I'm not sure what other characters or patterns cause this.

One way to fix it is to manually edit `insomnia.Environment.db` to remove the backslashes. Then the collection will load just fine

### Insomnia Version

8.6.1

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.2.1 (23C71)

### Installation method

homebrew

**Comment by yaoweiprc** [comment]
It seems objectPath.normalize will enter endless loop if last char in key is backslash
