### ISSUE TITLE
Insomnia UI Alignment: Left Pane Horizontal Lines Misaligned With Rest of App

### ISSUE THREAD

**Issue by UnicodeTreason** [getinsomnia/insomnia#7287]
### Expected Behavior

The horizontal lines align at the same height across the app for consistent visual experience.

### Actual Behavior

The "branch" and "collection name" lines are lower than expected when compared to their neighbouring horizontal lines.

### Reproduction Steps

1. Open GUI
2. Open a collection
3. Visually confirm lines are lower than expected

![image](https://github.com/Kong/insomnia/assets/14937219/c31b1f45-5c4d-429c-b8c1-92db025165a1)
![image](https://github.com/Kong/insomnia/assets/14937219/15265935-4454-416f-9bee-e140dd3d1f06)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Education 22H2

### Installation method

Download from https://insomnia.rest/download

**Comment by subnetmarco** [comment]
We will fix this in a minor release of Insomnia.

**Comment by UnicodeTreason** [comment]
This is looking better in v9.2.0

**Comment by gatzjames** [comment]
Thanks for the feedback! Closing as we updated the UI in 9.2
