### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by mgh121221** [getinsomnia/insomnia#7288]
### Expected Behavior

Network connectivity issue: Failed to load Organizations. Error invoking remote method 'insomniaFetch': Error: net::ERR_CONNECTION_TIMED_OUT

### Actual Behavior

Error: Network connectivity issue: Failed to load Organizations. Error invoking remote method 'insomniaFetch': Error: net::ERR_CONNECTION_TIMED_OUT at Module.wy1 [as indexLoader] (file:///C:/Users/mehra/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:1511:3442) at async j5 (file:///C:/Users/mehra/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:55:3729) at async Promise.all (index 2) at async He (file:///C:/Users/mehra/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:54:23493) at async k1 (file:///C:/Users/mehra/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:54:18675) at async Ue (file:///C:/Users/mehra/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:54:16772) at async Object.s1 [as navigate] (file:///C:/Users/mehra/AppData/Local/insomnia/app-8.6.1/resources/app.asar/index-db9674c5.js:54:15304)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

8.6.1

### What operating system are you using?

Windows

### Operating System Version

windows 10 20h2

### Installation method

doenload from insomnia.com

**Comment by subnetmarco** [comment]
This has been fixed today in the new [9.0 GA release](https://konghq.com/blog/product-releases/insomnia-9-0-pre-request-scripting-api-mocking).
