### ISSUE TITLE
[Feature Request]  : add HTML Preview Mode

### ISSUE THREAD

**Issue by gladx** [getinsomnia/insomnia#729]
- Insomnia Version: 5.12.4
- Operating System:  Ubuntu 17.10

## Details

Some time when use Api, send data in json mode and change header to ```header("Content-Type: application/json"); ```  . when something wrong in php code and show errors in html format without html and body tag like this 
my code for show problem  :   
```php 
<?php
ini_set("display_errors", 1);
error_reporting(E_ALL);

header("Content-Type: application/json");
echo json_encode($undefined_var);
```
and error show without any html and body tag (because header set "Content-Type: application/json")
``` html 
<br/><b>Notice</b>: Undefinedvariable: undefined_varin<b>/var/www/html/error.php</b>online<b>7</b><br/>null
``` 
![screenshot from 2018-01-27 12-52-53](https://user-images.githubusercontent.com/9036557/35470569-0918766a-0361-11e8-968a-2e6a38d82fbb.png)

**when errors are big very hard to read** , and I my solution for read, create a file a.html with html and body tags and past into it and my result is : 
```html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>

    <br/><b>Notice</b>: Undefinedvariable: undefined_varin<b>/var/www/html/error.php</b>online<b>7</b><br/>null
    
</body>
</html>
```
now open a.html in browser and read errors. 
![screenshot from 2018-01-27 12-49-49](https://user-images.githubusercontent.com/9036557/35470564-ece61a06-0360-11e8-98b9-b954cf8f13b3.png)

so I think if we can show this result in HTML preview mode is good :-)

**Comment by gschier** [comment]
Hmm, that's a tricky one because how do you know for sure that the response is HTML without having false positives?

I'm open to suggestions.

**Comment by gladx** [comment]
Hi @gschier , solve my problem in PHP with add this ```php  ini_set('html_errors', false);```
but new problem is remove space and join words together and hard to read.
![image](https://user-images.githubusercontent.com/9036557/37518576-f7dd3f9e-292a-11e8-9837-471be07cbba4.png)

in google chrome 
![image](https://user-images.githubusercontent.com/9036557/37518623-2915183e-292b-11e8-9d92-29117469e38f.png)

PHP Code
```php
<?php

ini_set("display_errors", 1);
error_reporting(E_ALL);
ini_set('html_errors', false);

header("Content-Type: application/json"	);
echo json_encode($undefined_var);
```

**Comment by stalingino** [comment]
Insomnia does not need to know that the content is html. Just a preview as HTML option would be nice

**Comment by Quantiversal** [comment]
Agreed with @stalingino. If we know it's html, would be nice to quickly force a preview for a certain method.
