### ISSUE TITLE
9.0.0 reversed folder/request order

### ISSUE THREAD

**Issue by LunaticoCR** [getinsomnia/insomnia#7308]
### Expected Behavior

After an update I would expect the order of my folders and request to remain the same.

### Actual Behavior

After the last update to v9.0.0 I noticed two UI issues.
1. The left column width was too wide, and it can be dragged back to make it more narrow, but to a certain size which is still to wide.
2. The order of all my folders and requests go completely inverted.The folder that used to be at the top is now at the bottom, and so on.

### Reproduction Steps

1. Accept the recent prompt to update to v9.0.0
2. After restart notice the issues

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 9.0.0
Build date: 4/24/2024
OS: Darwin arm64 23.4.0
Electron: 29.3.0
Node: 20.9.0
Node ABI: 121
V8: 12.2.281.27-electron.0
Architecture: arm64

### Insomnia Version

9.0.0

### What operating system are you using?

macOS

### Operating System Version

14.4.1

### Installation method

So long ago that I can't remember

### Last Known Working Insomnia version

Kept up to date so whatever the previous version was

**Comment by LunaticoCR** [comment]
One more thing, I just reverted to version 8.6.1 and my folders are back in order and the left column can be resized to be narrow.
So I'll be skipping version 9.0.0 I'm afraid.

**Comment by subnetmarco** [comment]
> The left column width was too wide, and it can be dragged back to make it more narrow, but to a certain size which is still to wide.

Can you take a screenshot for us to see the behavior? You mean this section:

![Screenshot 2024-04-24 at 1 16 52 PM](https://github.com/Kong/insomnia/assets/964813/c8f7b087-8a4c-4bc4-a89b-eabed65d747d)

> The order of all my folders and requests go completely inverted.The folder that used to be at the top is now at the bottom, and so on.

This is a bizarre behavior, we will look into it. There is a sorting control, I wonder if the default after the update has been updated to a different value, and using the old one reverts the proper order:

![Screenshot 2024-04-24 at 1 18 30 PM](https://github.com/Kong/insomnia/assets/964813/7518bcd7-cfb4-4e6b-bf3a-9d2aa364ad5a)

**Comment by LunaticoCR** [comment]
Yes @subnetmarco exactly that section, upon opening the app it was very wide, almost half the width of the window. And when I tried to resize it back I could only do it to a certain amount, which to my liking was still very wide.
I did look at the sorting menu, and it was set to manual. It is still set to manual after reverting to the previous version and now the order is correct.
Let me know if there's anything I can do to help you get to the bottom of this.

**Comment by alexvetter** [comment]
Same problem. It feels like the manual order is just reversed. Top-level folder order as well as in-folder request order.

**Comment by jackkav** [comment]
Fixed in #7309

**Comment by subnetmarco** [comment]
The fix will be available in the next `9.1`. Let's see if there are more things we need to improve, I would expect it to ship sometime next week. @LunaticoCR
