### ISSUE TITLE
Cannot open collections after last Insomnia updates on 24 April 2024

### ISSUE THREAD

**Issue by ngojan** [getinsomnia/insomnia#7311]
### Expected Behavior

Open Collection

### Actual Behavior

After clicking on collections nothing happens

### Reproduction Steps

Go to personal workspace
Open project
Open collection 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I have updated Insomnia and I cannot open my collections.

### Insomnia Version

9.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Version 22H2 for x64-based Systems

### Installation method

download from insomnia official site

### Last Known Working Insomnia version

the version before 9.0.0

**Comment by gatzjames** [comment]
Hey @ngojan, can you provide some more info?
Is this happening for all your collections or only for a specific one?

**Comment by ngojan** [comment]
Hi,now it works, I have closed and reopened the app.
Thanks.
