### ISSUE TITLE
Scratch Pad gone after update to 9

### ISSUE THREAD

**Issue by stefandevo** [getinsomnia/insomnia#7312]
### Expected Behavior

After upgrade I would be able to find my local scratch pad I had before in version 8.

### Actual Behavior

Cannot find anything from my requests after updating to 9. I only see a Personal Workspace.

### Reproduction Steps

Have a scratch pad in v8, upgrade to v9 it's gone

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS 14.4.1 (23E224)

### Installation method

download

### Last Known Working Insomnia version

8.x

**Comment by subnetmarco** [comment]
Hi @stefandevo - the Scratch Pad is still available in the product as it used to be in 8.x by clicking on "Use the local Scratch Pad":

![Screenshot 2024-04-24 at 4 26 12 PM](https://github.com/Kong/insomnia/assets/964813/1eb4533d-ddb2-401c-b85e-0c91ff15ffdc)

And then loading it:

![Screenshot 2024-04-24 at 4 27 42 PM](https://github.com/Kong/insomnia/assets/964813/a4fe9577-55e2-4e17-a23f-b958089e1a71)

To better look into this issue, in what part of this UX you find the inability to access the scratch pad?

**Comment by stefandevo** [comment]
So what basically is happening: (I downgraded to get the requests back).
I am not logged in in v8; when I start I do see the login screen with the "Use the local Scratch Pad".
I now get a popup to upgrade.
Insomnia is starting again, but now I don't get the login screen, I am directly logged in.
I don't see an option to get the scratch pad back.
That was the confusion.

I did log out. 
Now I get same login screen with the Scratch Pad.

**Comment by subnetmarco** [comment]
Yes, I think in general it is very confusing that we are not showing the Scratch Pad data inside the account after logging in, we may need to introduce a "Scratch Pad" collection even for users that are logging in so that it doesn't appear that it has been lost.

**Comment by subnetmarco** [comment]
I am going to close this issue for now since your issue has been resolved, and open a more specific one for the idea I just mentioned.
