### ISSUE TITLE
[Feature Request] Improve Clarity of History Menu

### ISSUE THREAD

**Issue by damianb** [getinsomnia/insomnia#732]
- Insomnia Version: 5.12.4
- Operating System: Windows 10 Pro

## Details

Looking for, on requests, a button to clear the prior request's response (basically, resetting the state of the request's response to match a newly created request).  Probably best to put it near the repeat request button on the upper right.

Additionally, a menu bar action to clear *all* prior request's responses would be useful as well.

Justification: When you're testing and iterating through changes, being able to clear everything out and start with a blank slate gives you a better idea of when you last tried an API call for a feature that's in work.

**Comment by Noodlewitt** [comment]
secondary to this, a way of mass deleting lots of requests would be very useful - so ability to shift-click or drag to select multiple requests and delete them.

As a use case, I've imported an xhr request from chrome but it brought in requests for everything on the whole site.. I have no way of mass deleting 100s of requests without right clicking each one and removing it.

**Comment by gschier** [comment]
You can clear the responses of a request in the history menu in the top-right. Is that what you are asking for?

- **Clear Current Response** deletes the response that is currently selected
- **Clear History** deletes all responses for the active request

<img width="375" alt="image" src="https://user-images.githubusercontent.com/587576/35543978-ecd0dd00-05a2-11e8-8b74-6f9744533313.png">

Please post your second request as a separate issue to make things easier to manage 😄

**Comment by damianb** [comment]
...Huh.  Okay - that wasn't very clear.  Judging by the icon, I thought that was for repeating the request.

Going by that - perhaps the ambiguity needs to be cleared up about that icon?  Maybe that's in need of a tooltip or a label? The way it's used leads me to think that it'd execute an action immediately, instead of opening a menu, which....yeah, explains why I never found it.

I'll open a second request for clearing all responses - but if you're fine with it, I'd like to change the focus of this issue to the discoverability of the history menu itself.

**Comment by damianb** [comment]
Opened #734 per request.

**Comment by gschier** [comment]
That's a good point about expecting the button to immediately perform an action. A tooltip is a good solution but maybe the icon could also be changed? Would a plain clock icon be better?

Feel free to rename the issue to make it clear that the discoverability is now the subject.

**Comment by damianb** [comment]
Perhaps changing the icon would be a good start, but at minimum, a chevron or arrow pointing downward would give you the idea of it opening into a menu.  

For example:

![image](https://user-images.githubusercontent.com/121707/35632381-2178227e-066c-11e8-868d-fd3e61183289.png)

One of these performs an action (changing the page), two of these open a menu - and which does which is immediately obvious.  Having that would probably help a ton.

However, if that approach is taken, imo the icon itself needs to be *enlarged* from its current state.  Otherwise you'll have this tiny clock/rotating arrow icon being dwarfed by the arrow/chevron.

**Comment by gschier** [comment]
I pushed a commit to address this earlier but forgot to reference this issue. Here's what it will look like in the next release.

![image](https://user-images.githubusercontent.com/587576/36023571-da58ceda-0dc7-11e8-87c2-3b9e502e2bd2.png)

**Comment by damianb** [comment]
Looks good!  Definitely clearer. Thanks!
