### ISSUE TITLE
Drag and drop request is not working properly under collection tab

### ISSUE THREAD

**Issue by ywidiastuti** [getinsomnia/insomnia#7320]
### Expected Behavior

Drag and drop request for collection tab should work

### Actual Behavior

Drag and drop request under collection tab for reorganizing are not working on the edge of folder

### Reproduction Steps

1. Go to "Collection''
2. Try reorganizing request like this, put the 2nd request above 1st request 
![image](https://github.com/Kong/insomnia/assets/145996165/99715768-057b-44ad-ba85-4f4901f3cc7c)
3. Drag and drop is not possible

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Linux mint 22.1

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

8.6.1

**Comment by subnetmarco** [comment]
I can replicate - we will fix this.

**Comment by ywidiastuti** [comment]
thank you! it is working in version 9.1.1

**Comment by KristianI** [comment]
It's not working on Windows build in 9.1.1
