### ISSUE TITLE
insomniaFetch not respecting proxy settings

### ISSUE THREAD

**Issue by lexithium** [getinsomnia/insomnia#7322]
### Expected Behavior

When trying to authenticate, the insomniaFetch function should check the application's proxy settings and make HTTP requests with the respective settings.

### Actual Behavior

When I try to authenticate, the insomniaFetch function is not using the proxy settings I have set in Insomnia to perform HTTP calls, resulting in an ERR_CONNECTION_REFUSED.

<img width="413" alt="Screenshot 2024-04-25 at 9 08 21 AM" src="https://github.com/Kong/insomnia/assets/6098893/872e2258-2c83-49ad-982a-0130c82dc4f3">

<img width="748" alt="Screenshot 2024-04-25 at 9 49 34 AM" src="https://github.com/Kong/insomnia/assets/6098893/07fa044e-c985-47a1-a798-f342d614d5e4">

### Reproduction Steps

1. Click Login
2. Application opens web browser. Insert passphrase
3. Click `Manually enter token`
4. Paste token into prompt on Insomnia
5. Error is reported

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

From main.log file:

```
[2024-04-25 09:47:17.009] [info]  [main] Error checking for newer version Error: net::ERR_CONNECTION_REFUSED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:109791)
    at SimpleURLLoaderWrapper.emit (node:events:514:28)
    at SimpleURLLoaderWrapper.emit (node:domain:488:12)
[2024-04-25 09:52:27.266] [error] Error occurred in handler for 'insomniaFetch': Error: net::ERR_CONNECTION_REFUSED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:109791)
    at SimpleURLLoaderWrapper.emit (node:events:514:28)
    at SimpleURLLoaderWrapper.emit (node:domain:488:12)
```

### Insomnia Version

9.0.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.4

### Installation method

download from insomnia.rest

**Comment by jackkav** [comment]
You are correct, thanks for the report, quick question what kind of proxy are you using? socks5?

**Comment by lexithium** [comment]
Nah, just a http. I actually managed to workaround this by setting the proxy in my system settings, but I was under the impression that Insomnia would not recognize those.

**Comment by jackkav** [comment]
That's good to hear. We just changed insomniaFetch in 9.1 to use electron fetch. This should allow system proxies to work.
