### ISSUE TITLE
Request list cannot be shrunken down small enough in the V9

### ISSUE THREAD

**Issue by DusanLesan** [getinsomnia/insomnia#7324]
### Expected Behavior

If user have a request list with requests having short names, you should allow them to make space for other panes. You should minimize displaying empty/unneeded space/elements taking up space from other important stuff. 
The point at which the lists is hidden should be moved so it allows dedicating a lot less space for it than now.

### Actual Behavior

The request list is not allowing me to shrink it past some point. The list gets hidden after shrinking past some point, but that is not ok for users switching request often.

![image](https://github.com/Kong/insomnia/assets/20520590/15c00815-e060-4f32-9275-4552bfc0c410)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux arch 6.8.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 x86_64 GNU/Linux

### Installation method

AUR

**Comment by gatzjames** [comment]
Thanks for feedback, the minimum and default sizes for the sidebar will be updated in the next patch 9.1

**Comment by gatzjames** [comment]
Closing as this should be fixed in 9.1
