### ISSUE TITLE
CAn't use delete shortcut

### ISSUE THREAD

**Issue by kristianbendren** [getinsomnia/insomnia#7325]
### Expected Behavior

Tried with default ctrl+shift+del 
Didnt work
Tried change to another ,still same issue

### Actual Behavior

Nothing happens

### Reproduction Steps

1. Select a request
2. Click ctrl+shift+delete
3. Nothing happens

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Other shortcuts works example ctrl + d to duplicate

### Insomnia Version

2021.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

download from insomnia

### Last Known Working Insomnia version

N/A

**Comment by gatzjames** [comment]
👋 Hi @kristianbendren,
Could you be using backspace instead of del? It works fine for me. It might also be that this shortcut is bound by the OS which the app can't override then.
What if you go to Preferences > Keyboard and add another keybinding?

**Comment by kristianbendren** [comment]
HI, no i used DEL key.
I tried to set with some other keyboard keys but still didnt work.

Also it would be good to be able to select many request in list and right click to delete instead on taking one by one.

**Comment by gatzjames** [comment]
Interesting. Not sure if this is related to Windows.
Can you verify that you are using version 2021.5.0?
If so can you upgrade to the latest?

**Comment by kristianbendren** [comment]
Sorry i just thought the preadded value was latest.
Im running 8.6.1 (2024-02-05)

**Comment by gatzjames** [comment]
Our bad 😅 we will update the issue template to reflect the latest.
We fixed a lot of issues related to keybindings in v9 can you try it out and let me know if it's fixed?

**Comment by ghost** [comment]
I also experience the same issue on Windows 11 and I am currently running ver 9.1.0 (4/30/2024).
Tried to rebind it but no change.

**Comment by huzeyfetascsi** [comment]
insomnia 9.3.2
windows 10
request delete shotcut -> `ctrl+shift+delete` | `ctrl+shift+del` |` ctrl+shift+backspace` not works
also I tried to use three shotcut for folder but not worked too

**Comment by yaoweiprc** [comment]
Delete key was bound with wrong keyCode.
