### ISSUE TITLE
Auto completion stopped working after update to Insomnia 9

### ISSUE THREAD

**Issue by DominikSeus** [getinsomnia/insomnia#7327]
### Expected Behavior

When writing GraphQl queries I normally was able to get auto complete suggestions based on the fetched schema when clicking ctrl+space

### Actual Behavior

Since I updated the app to version 9 (from Insomnia 8.6.1) this does not work anymore

### Reproduction Steps

1. Install Insomnia 8.6.1
2. Update to Insomnia 9
3. Create a GraphQl request and enter the URL and necessary authentication headers such that the schema can be fetched
4. Auto completion does not work as it did before

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 22H2

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

8.6.1

**Comment by subnetmarco** [comment]
We are on it. cc @gatzjames

**Comment by DoZiBo1** [comment]
Same is true for Apple Silicon version:
Version: Insomnia 9.0.0
Build date: 4/24/2024
OS: Darwin arm64 23.4.0

**Comment by jackkav** [comment]
Will be in 9.1
