### ISSUE TITLE
[Feature Request] Support multiple operations by letting user choose operationName

### ISSUE THREAD

**Issue by timrs2998** [getinsomnia/insomnia#733]
- Insomnia Version: 5.12.4 (5.12.4.1752)
- Operating System: macOS Sierra 10.12.6

## Details

When using another GraphQL client such as GraphiQL, if you have a body like:

```graphql
query First {
  thing
}
query Second {
  thing
}
```

and you try to send the query, a drop-down menu will let you choose between `First` and `Second`. When using Insomnia, there is no prompt and the server may respond with an error message (ie: "Must provide operation name if query contains multiple operations.").

Without this feature, queries that work in GraphiQL do not necessarily work in Insomnia since you are unable to send an `operationName` to the server without switching the request body to JSON.

**Comment by gschier** [comment]
I agree that this would be a great enhancement to the app.

Just wanted to clarify quickly that Insomnia _does_ send `operationName` but it defaults to the first operation defined. A (horrible) workaround would be to reorder the queries based on the one you want to send. 

Letting the user choose would definitely be a much better way to do it 👍

**Comment by bwlt** [comment]
It would be nice also to decide which operation to run based on the position of the text cursor:
If a user press cmd+enter maybe it is possible to know the position of the cursor inside the GraphQL query, and then automatically choose the operation in which the cursor is blinking.
This is a default behaviour for the GraphiQL IDE

**Comment by bwlt** [comment]
#990 can be related

**Comment by bwlt** [comment]
#990

**Comment by gschier** [comment]
This is done now!

![screenflick movie 66](https://user-images.githubusercontent.com/587576/42010880-cc629afa-7a5e-11e8-8217-425dd56a1533.gif)

**Comment by gschier** [comment]
Thanks @bwlt for the awesome work 👍 😄

**Comment by rogeraime** [comment]
Hi,
 someone here know how to write a operations's query in Multipart using Insomnia for testing single file Upload? I write my own but did not work and I received : 
{
  "timestamp": 1602774721435,
  "status": 422,
  "error": "Unprocessable Entity",
  "message": "",
  "path": "/graphql"
`}
hier is my query : 
{
  "query": "mutation ($numberPlate: String, $country: $String, $file: Upload) {createTicket(numberPlate: $numberPlate, country:  $country, file: $file)}{ id, timestamp}",
  "variables": {
    "numberPlate": "33333",
    "country": "xyz",
    "file": null
  }
}
Thk you in advance!

![att1](https://user-images.githubusercontent.com/61559462/96224608-28d9c600-0f90-11eb-9e1a-7e81fe0c03b0.PNG)
![att2](https://user-images.githubusercontent.com/61559462/96224627-2e371080-0f90-11eb-9f10-1616e54dec71.PNG)
