### ISSUE TITLE
[Feature Request] Clear all request responses

### ISSUE THREAD

**Issue by damianb** [getinsomnia/insomnia#734]
- Insomnia Version: 5.12.4
- Operating System: Windows 10 Pro

## Details

Looking for a menu bar action to clear all prior request's responses - it may not need to reset the history of each request itself, but at minimum clear out what's currently displayed and present the response side as an initial state.

**Comment by gschier** [comment]
Oh this was done a while ago. You can clear all responses for a workspace in the workspace settings dialog

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
