### ISSUE TITLE
9.1.0 & 9..0.0 `Discard all changes` not working

### ISSUE THREAD

**Issue by mo-zza** [getinsomnia/insomnia#7347]
### Expected Behavior

I exptected pull new release docs. And it's works.

### Actual Behavior

`Discard all changes` button not working.

I updated version 8.6.1 to 9.0.0 and 9.1.0. Then all documents have change logs what i didn't changed it.
And i can't pulled new release documents.

### Reproduction Steps

1. Go to shared workspace
2. Click commit button
3. I see too many change logs what i didn't changes that.
![image](https://github.com/Kong/insomnia/assets/59649862/d321ad24-4b9f-4728-a358-80c92e9b5cb6)
4. `Discard all changes` not working.
![image](https://github.com/Kong/insomnia/assets/59649862/426da201-51ed-4531-b7ca-2c9f204ef431)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.1.0 & 9.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.4.1 - Apple M1 Pro

### Installation method

download from insomnia web

### Last Known Working Insomnia version

8.6.1

**Comment by ihexxa** [comment]
Hello @mo-zza , would you mind to to check diff in the commit modal. Probably because pre-request script is introduced from 9.0 so there is one new property is introduced.

**Comment by mo-zza** [comment]
I resolve it. Thanks

**Comment by igaln** [comment]
Do we have to commit, the following below for every endpoint to continue using cloud? We cannot discard these changes.

  "pathParameters": [],
  "preRequestScript": "",

**Comment by brobert6** [comment]
Go to Help/Show App Folder
delete that forlder from you  system (or rename it ti have a backup)
All your data will be lost, but at least after you relog and pull all the data, your issue will be solved
