### ISSUE TITLE
[Feature Request] Make request renaming quicker

### ISSUE THREAD

**Issue by MarlBurroW** [getinsomnia/insomnia#735]
Insomnia Version: 5.12.4
Operating System: MacOSX Sierra

# Details

Sometime I have to duplicate a lot of requests then rename each of them, so I have to click "Settings" on the dropdown and type the new name in the modal. 
It could be very nice to be able to rename a request by double-clicking on the name in the sidebar.

**Comment by MarlBurroW** [comment]
Oups, already done, issue closed

**Comment by ldgmaia** [comment]
How about having a hotkey for that too? It would be great to use CTRL + E to rename the request.

**Comment by sau00** [comment]
> How about having a hotkey for that too? It would be great to use CTRL + E to rename the request.

Hello

Do you have any workaround on this?
