### ISSUE TITLE
Undo history clears after send or changing request focus

### ISSUE THREAD

**Issue by JohnBarhorst-mastery** [getinsomnia/insomnia#7352]
### Expected Behavior

Previously, I could use CMD + Z / undo on JSON payloads after sending requests or after selecting a different request and then going back to the previous request.

### Actual Behavior

Undo no longer works on JSON payloads after sending a request, or after selecting a different request and moving back.

### Reproduction Steps

1. Create or select a request with a JSON payload body.
2. Edit that JSON payload
3. Send the request
4. Focus on the JSON payload and attempt to undo the changes you just made.
5. Make more changes to the JSON payload
6. Select a different request from the collection navigation
7. Re-select the previous request, and attempt to undo the changes you made to the JSON payload.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Noticed in 9.0.0, just tested again in 9.1.0 and the issue persists. 

### Insomnia Version

9.1.0

### What operating system are you using?

macOS

### Operating System Version

Ventura - 13.6.4

### Installation method

Download from website

### Last Known Working Insomnia version

8.6.1

**Comment by jackkav** [comment]
Thanks for the report. We'll take a look

**Comment by leonardogmz** [comment]
Experimenting the same here. In 9.2.0. I think this starts to happen when I switch to a shared by Git workspace. Before, this never happens.

**Comment by rich-grundy-paytently** [comment]
I raised a separate bug but then found this had already been logged here.

@jackkav - Is there any update on this?

Thanks!

**Comment by jackkav** [comment]
It seems like code mirror is losing state between re renders, it has a state cache for cursor and hints perhaps we can as undo history into it.
 @CurryYangxx  could you take a look at this please 🙏

**Comment by letrungtiennbk9** [comment]
This is a big problem for API tester like me 😢  Please take a look at this

**Comment by subnetmarco** [comment]
We are looking at this.

**Comment by ihexxa** [comment]
Closing this, fix will be included in the next release.
