### ISSUE TITLE
Visible lag opening folders in new version, as compared to older version (suspicious fetch logs)

### ISSUE THREAD

**Issue by navin09** [getinsomnia/insomnia#7357]
### Expected Behavior

* Clicking a 'folder' is responsive (time between action and response is within 350ms)
* Clicking a 'folder' to open it should not trigger a fetch to an internet resource of any kind.

### Actual Behavior

* Clicking on 'Folders' takes close to 2 seconds between the action and the response.
* Clicking on a 'Folder' seems to trigger fetches to multiple resources over the Internet.
  - 16:40:14.122 › Fetching https://api.insomnia.rest/v1/organizations/team_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/features
  - 16:40:14.157 › Fetching https://api.insomnia.rest/graphql?projects
  - 16:40:14.381 › Fetching https://api.insomnia.rest/v1/organizations/team_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/storage-rule
  - 16:40:14.416 › Fetching https://storage.googleapis.com/insomnia-production-public-assets/inapp-learning.json 

### Reproduction Steps

1. Open Insomnia
2. Open a Collection
3. Click on any 'folder'

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

**Version of Insomnia which works as intended:**
Version: Insomnia 2023.1.0
Build date: 3/9/2023
OS: Linux x64 5.15.0-105-generic
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Version of Insomnia which exhibits the bug:**
Version: Insomnia 9.1.0
Build date: 4/30/2024
OS: Linux x64 5.15.0-105-generic
Electron: 29.3.0
Node: 20.9.0
Node ABI: 121
V8: 12.2.281.27-electron.0
Architecture: x64

### Insomnia Version

9.1.0

### What operating system are you using?

Other Linux

### Operating System Version

Linux Mint 21.2 (Based on Ubuntu 22.04)

### Installation method

Portable AppImage

### Last Known Working Insomnia version

2023.1.0

**Comment by jackkav** [comment]
3 of these 4 requests are cached on the client, but its true we do need a better story for the /graphql endpoint reloading.

**Comment by navin09** [comment]
> 3 of these 4 requests are cached on the client, but its true we do need a better story for the /graphql endpoint reloading.

@jackkav  thanks for the reply.  If they are cached on the client, why make the fetch at all every time a folder is clicked? Also, this doesn't seem to happen in the older version (2023.1.0) If you want to keep the list of folders updated with a remote resource, maybe using a websocket connection that notifies of any updates or changes would be a better solution, no?

**Comment by Plucks77** [comment]
For me is the same, opening and closing folders takes a long time, so I need to hit command + r. In general the UI is very laggy compared to previous versions...

**Comment by jackkav** [comment]
Over fetching is addressed in 9.1.1. My previous assertion was incorrect there were fetches being made. We recently improved our app fetching observability so we are doing our best to address some of the performance issues now we have a faster learning loop.
