### ISSUE TITLE
Can't login with Google

### ISSUE THREAD

**Issue by k4dm3l** [getinsomnia/insomnia#7359]
### Expected Behavior

Once I select in the authentication process the email account with which I want to login to google, it should display a login confirmation page and open the client.

### Actual Behavior

After selecting the account, first it is taking too much time to redirect to the application, it also fails showing 2 possible errors, a page with a message saying "Invalid authorization code" or "Something went wrong, go back to the dashboard" when the second error message comes up, it does not redirect to the dashboard, instead it redirects to the page to select again the authentication mechanism.

### Reproduction Steps

Client data:
Version: Insomnia 9.1.0
Build date: 4/30/2024
OS: Darwin arm64 22.5.0
Electron: 29.3.0
Node: 20.9.0
Node ABI: 121
V8: 12.2.281.27-electron.0
Architecture: arm64

Steps:
1. Open the Rest app client
2. Hit login button
3. Select "Continue with Google"
4. In the auth process with google select the account that you want to use

After the last step, wait for between 5 and 15 seconds to see the error mentioned before 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.1.0

### What operating system are you using?

macOS

### Operating System Version

Darwin arm64 22.5.0

### Installation method

downloaded from insomnia web page

**Comment by ryanholden8** [comment]
Opened a discussion on removing the forced login: https://github.com/Kong/insomnia/discussions/7362

**Comment by filfreire** [comment]
See https://github.com/Kong/insomnia/issues/7358#issuecomment-2090962167

**Comment by chrismowbray** [comment]
I think this issue is back @filfreire
