### ISSUE TITLE
Application Error: Network connectivity issue: Failed to load Organizations. Failed to load organizations

### ISSUE THREAD

**Issue by joachimbulow** [getinsomnia/insomnia#7360]
### Expected Behavior

I can login

### Actual Behavior

dsadf

### Reproduction Steps

fdsf

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

fdsf

### Insomnia Version

12343

### What operating system are you using?

macOS

### Operating System Version

dsadgreg

### Installation method

greg

### Last Known Working Insomnia version

greg

**Comment by ruankotovich** [comment]
same here

**Comment by sergiobelli** [comment]
Same problem...

This is the app screenshot : 
![Screenshot from 2024-05-02 17-04-41](https://github.com/Kong/insomnia/assets/16143463/ff59fa48-ecd8-4d1a-bb9e-2f23eed66404)

Same problem in accessing the web console.

**Comment by jw-miaem** [comment]
same and now get Invalid authorization code when trying to login via guthub

**Comment by filfreire** [comment]
See https://github.com/Kong/insomnia/issues/7358#issuecomment-2090962167
