### ISSUE TITLE
Error logging in / Connectivity Issues

### ISSUE THREAD

**Issue by marisaignacio** [getinsomnia/insomnia#7361]
### Expected Behavior

Open Insomnia > logged in automatically > open one of my collections and can work freely from there.

### Actual Behavior

When I opened the app, I was logged in, but saw an error that Insomnia was unable to connect. It then led me to this error:
 
> Network connectivity issue: Failed to load Organizations. Failed to load organizations
> 
> Error: Network connectivity issue: Failed to load Organizations. Failed to load organizations at Module.wy1 [as indexLoader] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:1511:3442) at async j5 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:55:3729) at async Promise.all (index 2) at async He (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:54:23493) at async K (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index-db9674c5.js:54:21358)
 
I tried reloading and logging out/in again, but still reach an error. I can no longer log in.

### Reproduction Steps

1. Open Insomnia App.
2. Directed to log in. 
3. Choose 'Continue with Google'.
4. Redirected to new page on my Chrome browser.
5. Click 'Continue with Google'.
6. Receive error 'Something went wrong. We are already working on fixing it!'.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 8.6.1

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.6.4

### Installation method

Download from company self service for applications.

**Comment by NicolaiHerforth** [comment]
Have the same issue. Cannot log in, and therefore cannot access all my requests.

It seems absolutely insane to me that saved content is behind a login server that could go down or prove problematic...

**Comment by Bituum** [comment]
Have the same issue.
`Failed to find personal organization your account appears to be in an invalid state. Please contact support if this is a recurring issue.`

**Comment by mikebridge** [comment]
Same here on version 8.6.1 on Mac.  I do not want to 9.x due to a history of instability in upgrading insomnia versions.

**Comment by stephanepechard** [comment]
@mikebridge you're so right, the 9.X track have been disastrous so far for me :(
Won't be fooled again!

**Comment by ryanholden8** [comment]
Same here too. Login fails with invalid authorization code or rate exceeded

**Comment by ryanholden8** [comment]
Opened a discussion on removing the forced login: https://github.com/Kong/insomnia/discussions/7362

**Comment by sroland-trimble** [comment]
same here, hundreds of people unable to work. This is an insane productivity loss and isn't acceptable

**Comment by CaptainJojo** [comment]
Same here, it's not acceptable to block product if netword it's down. Second thing it's not normal to not see the status directly on website, I need to check issue to see it's not only me but the problem it's for everybody

**Comment by mikebridge** [comment]
> same here, hundreds of people unable to work. This is an insane productivity loss and isn't acceptable

I thought if I stopped upgrading insomnia regularly I could isolate myself the cycle of instability that occurs with every release, but with the migration to the cloud, insomnia has turned itself into a [single point of failure](https://www.techtarget.com/searchdatacenter/definition/Single-point-of-failure-SPOF) for my company.

**Comment by jbenjoy2** [comment]
having the same issue here. version 8.6.1 on macOS 14.4.1 (macbook pro m1pro) receiving this error: `Network connectivity issue: Failed to load Organizations. Failed to load organizations`

**Comment by brandon3123** [comment]
Same thing for me as well.

**Comment by mikebridge** [comment]
As a very unsatisfied paid customer for insomnia, I'm researching other options this morning instead of doing my actual job.

Anyone tried Bruno? https://github.com/usebruno/bruno

> Bruno is offline-only. There are no plans to add cloud-sync to Bruno, ever. We value your data privacy and believe it should stay on your device.

**Comment by ryanholden8** [comment]
> As a very unsatisfied paid customer for insomnia, I'm researching other options this morning instead of doing my actual job.
> 
> Anyone tried Bruno? https://github.com/usebruno/bruno
> 
> > Bruno is offline-only. There are no plans to add cloud-sync to Bruno, ever. We value your data privacy and believe it should stay on your device.

Thanks for this. I haven't heard of it, but love that they promise this. I'm going to suggest our team takes a look at this and migrate away from Insomnia.

**Comment by filfreire** [comment]
See https://github.com/Kong/insomnia/issues/7358#issuecomment-2090962167

**Comment by aventus13** [comment]
> As a very unsatisfied paid customer for insomnia, I'm researching other options this morning instead of doing my actual job.
> 
> Anyone tried Bruno? https://github.com/usebruno/bruno
> 
> > Bruno is offline-only. There are no plans to add cloud-sync to Bruno, ever. We value your data privacy and believe it should stay on your device.

My team has been using it for the past week or so, after being forced to create accounts in Insomnia. It's still in beta but is very decent so far. It already supports scripting (similar to Postman), something's that Insomnia has been missing which is quite telling. It's local, has nice integration with source control if needed, and open source.
