### ISSUE TITLE
Request is being sent twice

### ISSUE THREAD

**Issue by ScodroS** [getinsomnia/insomnia#7367]
### Expected Behavior

When logged in, requests are being sent twice when the send button is pressed. 
If I logout and use the local scratchpad requests are being sent only once as expected.

### Actual Behavior

Request to be sent only once when the send button is pressed

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

22.04.4 LTS

### Installation method

snap

**Comment by subnetmarco** [comment]
I am unable to reproduce. To clarify, how do you see the request being sent twice?

**Comment by ScodroS** [comment]
> I am unable to reproduce. To clarify, how do you see the request being sent twice?

All the servers I was testing at the time were receiving the request twice. I think it was somehow related to the issue I had connecting using my google account (maybe during maintenance?), anyway it's not happening anymore, the issue can be closed
