### ISSUE TITLE
[Feature Request] Ability to create a tag by looking into the Response headers array by position

### ISSUE THREAD

**Issue by daniele-pintus** [getinsomnia/insomnia#738]
Since I could have multiple Set-Cookie entries, or generally speaking, many entries with the same key name, I would be able to pick the the header value in the n-th position from the headers array, like Response.headers[2].
Also it would be useful to be able to pick a cookie directly from the Response cookies list.

**Comment by gschier** [comment]
Neat idea. I think `Set-Cookie` might be the only header that is commonly repeated in a response (correct me if I'm wrong). Perhaps it might be better to make something cookie-specific?

> Also it would be useful to be able to pick a cookie directly from the Response cookies list.
Have you tried the _Request => Cookie_ tag for this?

**Comment by daniele-pintus** [comment]
H,
The Request Cookie is what I would to set, with a cookie value from another response. I have this value in the Set-Cookie headers array in position N (but I can get only the first item) and in the response cookies, but I cannot read from there, that's why of my feature request :)

![insomnia](https://user-images.githubusercontent.com/28985036/36089813-faddc3e6-0fdd-11e8-937d-d98397ac1e28.png)
