### ISSUE TITLE
I cant view my list anymore in the separate window, ive tried shutting insomnia down and restarting but no luck

### ISSUE THREAD

**Issue by keithrickett0** [getinsomnia/insomnia#7381]
I'm new to coding, I'm in a bootcamp currently working on one of my final projects, I'm trying to make a list of cars but I can't see the list in the normal window and I have no idea how to get it back. Like i said I'm new to everything especially insomnia, any help would be much appreciated. 

![Screen Shot 2024-05-06 at 11 08 58 PM](https://github.com/Kong/insomnia/assets/95837279/4293c313-8b9b-4fb7-908b-50dee1ca381d)

**Comment by jackkav** [comment]
Thanks for the report @gatzjames seems this is an unexpected UX issue.

@keithrickett0 If you place your cursor along the right edge of the window you should see that it becomes a horizontal resize icon. You can reopen the response pane by dragging to the left.
