### ISSUE TITLE
[Feature Request] Fuzzy Search Results in Switch Requests (⌘P) Palette

### ISSUE THREAD

**Issue by roblav96** [getinsomnia/insomnia#739]
- Insomnia Version: `Version 5.12.4 (5.12.4.1752)`
- Operating System: `OSX 10.11.5`

## Details
The `Switch Requests` palette should display fuzzy search results on request names, urls, and **folder names**; eg. Sublime Text. I recommend [fuzzy](https://github.com/mattyork/fuzzy) for `Array<Object>` inputs and [bevacqua/fuzzysearch](https://github.com/bevacqua/fuzzysearch) for `Array<string>` inputs. Both provide bare minimum use cases. I would make a PR but for efficiency's sake I'm sure you would be able to implement this far quicker than me since you built this :D

**Comment by gschier** [comment]
Hey @roblav96, thanks for the request. 

The request switcher already performs a fuzzy match, but only on request name. Adding folder as a prefix to match on seems like a great idea though 😄👍 

It's true that I'd be able to implement this fairly quickly but it would end up taking a while because it's not at the top of the priority list. If you wanted to submit a PR for this I'd be happy to provide guidance if needed.

![image](https://user-images.githubusercontent.com/587576/35961061-3b243a4c-0ce7-11e8-875a-b87ff97e1604.png)

**Comment by axs221** [comment]
I would like to take a look at this one. I can take a look at this one maybe this weekend. I love Insomnia, but I was thinking the same thing. Definitely could use URL filtering. Might need better placeholder text to show fuzzy matching is allowed.

**Comment by axs221** [comment]
Progress update. I have basic searching working for folders, URL, querystring, and method. You can search multiple fields by space delimiting the search.

https://github.com/axs221/insomnia/tree/feature/fuzzy-match-request-parameters

Still to do includes evaluating the UI aspect. As in those 3rd party libraries @roblav96 linked, we should consider showing what text is matched, including folder path.

I might split this into two and put up a first PR for discussion with @gschier and implement any UI tweaks in another PR. What I have now is usable, just not as user friendly. But we will need to determine how the UI will need to change to accommodate showing what parts of search matched, especially for fields not currently visible on the Quick Switch window (URL, grandparent folders, querystrings).

**Comment by gschier** [comment]
That sounds great @axs221. Early PR with what you have. Then we can discuss the rest 😀

**Comment by axs221** [comment]
@gschier Sounds like a plan. ^--- Early PR is up! Let me know your thoughts when you get time.

**Comment by axs221** [comment]
@roblav96 With #797, @gschier and I merged in some preliminary changes that will allow you to search on request names, urls, and folder names. There was some discussion in that PR around doing a second PR with UI changes, as I am assuming you originally intended.

This UI for Switch Requests is to be decided, but it will likely involve showing two rows for results, and it may show partial matching as those libraries can do. The difficulty may be in getting as much information as we want while keeping it to two rows. The second row may be showing just the field that it is matching against.

**Comment by shawnaxsom** [comment]
@roblav96 @gschier I opened #856 to discuss the UI changes as @gschier requested, so we can close off this issue here. I will start playing with the UI and we can discuss.
