### ISSUE TITLE
unable to use javascript from environment json file, I wish to generate guid using {{guid}}, its not built in.

### ISSUE THREAD

**Issue by OTonGitHub** [getinsomnia/insomnia#7393]
### Expected Behavior

I want to add to environment something similar to this
{
    "_js_guid": "return math.Rand(1000);"
}

### Actual Behavior

But it just returns the raw string, statement is not evaluated, I even used a plugin called `insomnia-plugin-custom-generated-value`
I believe this should be a basic feature..

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11, Build 22631.3447

### Installation method

downloaded from website.

### Last Known Working Insomnia version

9.1.1

**Comment by subnetmarco** [comment]
With Insomnia 9.2 you can now use Faker's GUID function to do this, will this solve your issue?

![Screenshot 2024-05-15 at 5 48 10 PM](https://github.com/Kong/insomnia/assets/964813/f93a5944-5656-4f36-ada2-e82d4a2e3163)

**Comment by OTonGitHub** [comment]
@subnetmarco yesss, this is exactly what I wanted, this is a much-needed feature, some other global variables, for example, `{{localdatetime iso -2 d}}` etc would be a nice final touch. Please go ahead and close this as I have no issues with generating client side guid on Insomnia now. Thank you.
