### ISSUE TITLE
Invalid RSAES-OAEP paddingi

### ISSUE THREAD

**Issue by fleequid** [getinsomnia/insomnia#7401]
### Expected Behavior

Insomnia application syncs to my organization git repository

### Actual Behavior

Insomnia application tries to sync to my git repo.

I receive the following error:

Invalid RSAES-OAEP padding.

`Error: Invalid RSAES-OAEP padding. at pkcs1.decode_rsa_oaep (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/node-forge/lib/pkcs1.js:255:11) at Object.decode (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/node-forge/lib/rsa.js:1281:30) at key.decrypt (/Applications/Insomnia.app/Contents/Resources/app.asar/node_modules/node-forge/lib/rsa.js:1291:19) at sb1 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CPtKPVYi.js:1307:42482) at p7._getBackendProjectSymmetricKey (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CPtKPVYi.js:1464:504) at async p7._queryBlobs (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CPtKPVYi.js:1385:338) at async p7.customFetch (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CPtKPVYi.js:1319:7829) at async p7.pull (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CPtKPVYi.js:1319:6110) at async V (file:///Applications/Insomnia.app/Contents/Resources/app.asar/remote-collections-ClXUfnPl.js:1:610) at async Module.Q (file:///Applications/Insomnia.app/Contents/Resources/app.asar/remote-collections-ClXUfnPl.js:1:2545) at async file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CPtKPVYi.js:56:4446 at async mhe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CPtKPVYi.js:56:4896) at async Promise.all (index 5) at async hhe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CPtKPVYi.js:56:3544) at async Me (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CPtKPVYi.js:55:24242) at async t1 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-CPtKPVYi.js:55:20906)`

### Reproduction Steps

1. Install the application (Mac OS)
2. Go to your organization workspace
3. Try to synk one of the collections

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.1.1

### What operating system are you using?

macOS

### Operating System Version

14.4.1 (23E224)

### Installation method

from Insomnia.Core-9.1.1.dmg

### Last Known Working Insomnia version

Insomnia 8.6.1

**Comment by notjaywu** [comment]
related issue #7476

**Comment by subnetmarco** [comment]
@marckong what's the update here?

**Comment by marckong** [comment]
We pushed a fix for this issue that should resolve the problem.
