### ISSUE TITLE
Keeps forgetting "Private Environment" settings

### ISSUE THREAD

**Issue by ademcayir** [getinsomnia/insomnia#7402]
### Expected Behavior

I expect to see multiple private environments keep stable and keep whatever I set. not forget or not copied the values from other private environment values.

### Actual Behavior

I several times saved my environment specific variables to few different private environment parameters. but, Insomnia keeps forgetting or mixing up these variables. it is very hard to manage multiple environment. It copied over first private environment to next ones. I have to correct them again, but it is very unreliable that will forget again. Since, this happened few times already 

### Reproduction Steps

- create base environment settings
- create a private environment settings. set some variables over it
- create few more private environment settings. 
- after few switch between private environments, it ends up copied over first private environment values to the rest. so, you lost all the settings except first one

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Version: Insomnia 9.1.1 Build date: 5/7/2024 OS: Darwin arm64 23.4.0 Electron: 29.3.0 Node: 20.9.0 Node ABI: 121 V8: 12.2.281.27-electron.0 Architecture: arm64

### What operating system are you using?

macOS

### Operating System Version

14.4.1 (23E224)

### Installation method

Download from website and install package

**Comment by ademcayir** [comment]
I realize, I have "insomnia.environment.set" in one of the method, and likely this updates the variables. so, I am not sure whether this is an issue or not. But, I would expect insomnia.environment.set , would not update variables permanently but temporary or session based.

**Comment by ihexxa** [comment]
Hi @ademcayir I tried reproduction steps but I don't understand the point, how does `insomnia.environment.set` affect the private environment?

**Comment by ademcayir** [comment]
I have this in my private environment:
`{
"key1":"val1"
}`

and, in the "pre-request script" of the method, I have

`insomnia.environment.set("key1","new val1");`

and this updates the private environment json, and you loose the original values. I am not sure if this is an issue, or implemented as intended.

**Comment by ihexxa** [comment]
@ademcayir Yes, this behavior is by intention because it tries to follow existing tool's behavior.
It could be done by `insomnia.variables.set('key', 'value');` to set transient values but it is not fully supported.
Let me start a change to address it.

**Comment by ademcayir** [comment]
Thanks a lot. Then this can be closed.
