### ISSUE TITLE
[Bug] Electron icon showing after latest update

### ISSUE THREAD

**Issue by Gabb1995** [getinsomnia/insomnia#741]
- Insomnia Version: 5.14.3
- Operating System: Ubuntu 17.10 - artful

Icon shown is now the default Electron icon as shown below. This is after I updated to 5.14.3.

![screenshot from 2018-02-07 09 04 52](https://user-images.githubusercontent.com/20728259/35905071-fc508b38-0be5-11e8-9582-04f3e9ddd36b.png)

**Comment by gschier** [comment]
So strange. Not sure why this is happening all of a sudden. Going to play around with this today and hopefully find a solution.

**Comment by rocketraman** [comment]
Same here on Fedora 27 with KDE.

**Comment by gschier** [comment]
I think it's related to https://github.com/electron-userland/electron-builder/issues/2577

If there isn't a resolution in the next day or two I'll revert to a previous version and push a new update.

**Comment by gschier** [comment]
Just released a new version with a fix for this. Sorry everyone for the hiccup! Please forgive me 😺
