### ISSUE TITLE
[accessibility] Can't read request name in the table with screen reader

### ISSUE THREAD

**Issue by YashSonkiya** [getinsomnia/insomnia#7415]
### Expected Behavior

When I navigate to the table that lists all the requests, under the collection my screen reader should readout the name of requests. 

### Actual Behavior

My screen reader is not telling me the name of request, though it is telling me the type of request, and I am able to select the option related to request, I am not able to read the name.

### Reproduction Steps

Navigate to the table that has request using screen reader.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

9.1.1

### Insomnia Version

9.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### Installation method

downloaded from website

**Comment by gatzjames** [comment]
Hi @YashSonkiya thanks for the feedback!
Using the accessibility panel I see that the aria-label for the request grid row is set to the name of the request.
The issue seems to be that the request method tag gets announced instead of the aria-label.
I have made a PR to fix this issue

**Comment by YashSonkiya** [comment]
Hello @gatzjames, Thank you so much  for your help. I have noticed 1 more issue, I am not able to read inside the edit box using the arrow keys. E.G. when I type url in the edit box it is being typed but I am not able to read it using arrow keys. Could you please check this too? TIA.

**Comment by gatzjames** [comment]
> Hello @gatzjames, Thank you so much for your help. I have noticed 1 more issue, I am not able to read inside the edit box using the arrow keys. E.G. when I type url in the edit box it is being typed but I am not able to read it using arrow keys. Could you please check this too? TIA.

Happy to help and thanks for reporting these issues!
I have tried to use voice over but both the edit box for editing the request name and the one that updates the request's url are announcing the whole text after I stop editing for a while.
This might be different on my operating system since I use the Voice Over feature of macOS and am not familiar with how Windows handles this.
I'll try to run some tests on a Windows machine and let you know. In the meantime any additional info or accessibility feedback is more than welcome!

**Comment by YashSonkiya** [comment]
Thanks @gatzjames, if you want we can sync and I can show it to you. Let me know if this works.

**Comment by gatzjames** [comment]
> Thanks @gatzjames, if you want we can sync and I can show it to you. Let me know if this works.

@YashSonkiya sounds great! What's your preferred way for us to sync?

**Comment by YashSonkiya** [comment]
Google meet and MS teams both works.

**Comment by gatzjames** [comment]
> Google meet and MS teams both works.

Sounds great! Could you send me an email at james.gatz@konghq.com so that we can schedule a call?
