### ISSUE TITLE
Unable to install on Mac OS

### ISSUE THREAD

**Issue by traxeon** [getinsomnia/insomnia#7425]
### Expected Behavior

After copying insomnia to application folder, verification completes successfully

### Actual Behavior

After dragging Insomnia.app to Applications folder, error prompt:
"Insomnia.app" is damaged and can't be opened.  You should move it to the Trash. 

### Reproduction Steps

1. Download app:
https://updates.insomnia.rest/downloads/mac/latest?app=com.insomnia.app&source=website
2. Open installer
3.  Drag to Application folder
4.  Wait for validation bar to complete

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I have downloaded the file 5 times and tried 5 times.
Insomnia 9.2.0 universal.
Mac - Apple M1 Max, 64Gb memory, Sonoma 14.4.1

### Insomnia Version

9.2.0 universal

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.4.1

### Installation method

downloaded from website, see above

**Comment by filfreire** [comment]
@traxeon can you try to open Insomnia again, and share the contents of the following files ` ~/Library/Logs/Insomnia/renderer.log` and ` ~/Library/Logs/Insomnia/main.log`:

you can do so by running in the terminal:
```bash
cat ~/Library/Logs/Insomnia/main.log
cat ~/Library/Logs/Insomnia/renderer.log
```


Or by going to MacOS Console, and checking the log reports there, finding the `renderer.log` and the `main.log`.

![image](https://github.com/Kong/insomnia/assets/11976836/ab75571d-b9f0-471f-9a2f-ebf89abfed75)


Also does it work if you rename the the Insomnia App data folder, e.g.
```
mv ~/Library/Application\ Support/Insomnia ~/Library/Application\ Support/InsomniaBackup
```

**Comment by subnetmarco** [comment]
Closing this unless new updates are being received.

**Comment by KalebJS** [comment]
I had this issue today (i believe it was previously installed on my machine a few years ago) and moving the application support folder worked!
