### ISSUE TITLE
File selection window does not open

### ISSUE THREAD

**Issue by Desalutar20** [getinsomnia/insomnia#7432]
### Expected Behavior

When clicking on the "Choose file" button, open a window for selecting a file

### Actual Behavior

The window for file selection does not open when you click on the "Choose file" button, in another application (e.g. postman) everything works fine

### Reproduction Steps

https://github.com/Kong/insomnia/assets/105574762/7d05d7d1-4cce-4124-8c0b-2c8b3700a8c9

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux x86_64

### Installation method

download from Flathub

**Comment by subnetmarco** [comment]
I tried to replicate and it seems to be working in 9.x.

**Comment by Desalutar20** [comment]
> I tried to replicate and it seems to be working in 9.x.

What are you talking about?

**Comment by gatzjames** [comment]
Closing as this works on latest versions of the app
