### ISSUE TITLE
Unable to make email primary

### ISSUE THREAD

**Issue by ajatkj** [getinsomnia/insomnia#7439]
### Expected Behavior

To be able to make an email account primary.

### Actual Behavior

From account settings, I added a new email ID and verified it. When I click on `Make Primary` I get - `Internal server error`

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

If required, I can provide the new email ID I am trying to link.

### Insomnia Version

Insomnia 9.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

NA

**Comment by pavkout** [comment]
Hey @ajatkj, can you please try again? It should be okay, now!

**Comment by ajatkj** [comment]
Hi @pavkout update works now. Thanks!.

**Comment by pavkout** [comment]
@ajatkj Awesome, thank you for the feedback!
