### ISSUE TITLE
[Improvement] Prohibit (or validate) multiline header values

### ISSUE THREAD

**Issue by besolov** [getinsomnia/insomnia#745]
- Insomnia Version: 5.14.16
- Operating System: Any

## Details
Currently, it's possible to insert multiline header values. This may lead to the incorrect HTTP request. It may difficult to investigate such issues, cause linebreak may accidentally appear at the and of the value.

Suggestion:
Prohibit, or at least warn users about such values.

**Comment by gschier** [comment]
How were you able to create a multiline header value? Copy/paste?

**Comment by besolov** [comment]
Yes, that was copy/paste

**Comment by gschier** [comment]
Turned out to be a one-line fix. Thanks for reporting this!

**Comment by besolov** [comment]
Thanks for fixing :)
