### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by josead** [getinsomnia/insomnia#7450]
### Expected Behavior

Login after passcode introduced should be successful.

### Actual Behavior

<img width="1574" alt="image" src="https://github.com/Kong/insomnia/assets/5884889/b04370ea-7f59-4b26-b329-b79324f365ca">
No login, and error on whoami.

### Reproduction Steps

A) Click on google authentication.
Introduce passcode into box.
Clicking on Launch.
Insomnia does not respond.
B) Copying the code, pasting it into box, clicking login.
"Invalid code: Failed to fetch"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Apart from the fact that, I don't know why you moved things to cloud if this happens but, if I press "forgot passcode" I can change it without any measure of security, I can't login.

### Insomnia Version

5/15/2024

### What operating system are you using?

macOS

### Operating System Version

Version: Insomnia 9.2.0 Build date: 5/15/2024 OS: Darwin arm64 23.1.0 Electron: 29.3.0 Node: 20.9.0 Node ABI: 121 V8: 12.2.281.27-electron.0 Architecture: arm64

### Installation method

i dont know

**Comment by notjaywu** [comment]
@josead The status code is 407 (Proxy Authentication Required). Can you check if the proxy is enabled? If yes, maybe you can disable it and try again, thanks.

<img width="1438" alt="image" src="https://github.com/Kong/insomnia/assets/130019718/b1270154-3bea-4ebb-a2a9-a674295fb39e">

**Comment by josead** [comment]
@notjaywu Excelent, that worked!
