### ISSUE TITLE
Changing request body type

### ISSUE THREAD

**Issue by carloscstl** [getinsomnia/insomnia#7452]
### Expected Behavior

A message is displayed that when changing the type of request body the information will be lost, when canceling the information should not be lost

### Actual Behavior

When you press cancel, the body type changes to the selected one and you lose the information that was in the body

### Reproduction Steps

- Make a request with a body type selected and filled
- Change the body type
- Select cancel on the popup
- Watch the body lost

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2021.5.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Downloaded Insomnia.Core-9.2.0.exe

**Comment by gatzjames** [comment]
👋 Thanks for the feedback,
This is now fixed in the latest beta and will be out on 9.3.0
