### ISSUE TITLE
Query name incorrectly calculated in GQL query

### ISSUE THREAD

**Issue by lstrzebinczyk** [getinsomnia/insomnia#7455]
### Expected Behavior

If a GQL query has a name, it gets extracted to and sent as `queryName` param.

### Actual Behavior

If I send q GQL query with a query name, then remove the query name from query, the `queryName` param is still sent with incorrect value. This causes issues down the line.

First, sending a correct query and seeing correct response:
![bug_before_change](https://github.com/Kong/insomnia/assets/1272828/3a575b5d-5126-4f05-a51a-1650de68baa2)

Then remove the query name and still se it being sent in the additional param:
![bug-after-change](https://github.com/Kong/insomnia/assets/1272828/a291f61b-4394-4105-97b7-bc6e4b63e004)

### Reproduction Steps

1. Send any GQL query with a query name
2. Remove query name from the query

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.2.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.4 LTS

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

Unsure. I'm told "previous".

**Comment by ihexxa** [comment]
Hello @lstrzebinczyk , if possible, could you provide a minimal export file to reproduce it? I tried but was unable to reproduce it.

**Comment by ihexxa** [comment]
I'm able to reproduce this and will create a fix for it.

**Comment by lstrzebinczyk** [comment]
Awesome, thank you: )
