### ISSUE TITLE
Facing issue while importing a postman collection

### ISSUE THREAD

**Issue by Swarnava-Sadhukhan** [getinsomnia/insomnia#7459]
### Expected Behavior

The postman collection with all the requests should have been imported

### Actual Behavior

I tried importing a collection and getting this error.
![image](https://github.com/Kong/insomnia/assets/67735707/e3bc24bb-c195-4439-afbd-e2b584e686bb)
After reloading, none of the requests get imported inside the collection

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 9.3.0-beta.0 

### What operating system are you using?

Windows

### Operating System Version

Windows 10 

### Installation method

Download exe from github releases page

**Comment by ihexxa** [comment]
Hello @Swarnava-Sadhukhan, is it possible to provide a minimal export file to reproduce it? Which could accelerate fixing this issue.

**Comment by subnetmarco** [comment]
@Swarnava-Sadhukhan can you give us an update on this issue?

**Comment by ihexxa** [comment]
Enabled validation for this case, closing this one and will be released in the next minor update.
