### ISSUE TITLE
Cannot log in when update server blocked

### ISSUE THREAD

**Issue by szabopatriklaszlo** [getinsomnia/insomnia#7462]
### Expected Behavior

When blocking the update server on firewall, only the update gets blocked 

### Actual Behavior

We blocked the update server on firewall (updates.insomnia.rest,34.133.30.248)  because we don't wanna allow the update. This works perfecty but when we would like to log in, on the app.insomnia.rest site we cannot authenticate and also the application does not accept the token, it says fetch error. Probably the application wants to authenticate trought updates.insomnia.rest instead of auth.insomnia.rest. What should we do? We want to ban the update packages... Is there a port range for update purposes only, which can be banned safely? Thank you!

### Reproduction Steps

I think you will understand the issue without that.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Please give us a solution which can be implemented on 8.6.1, thank you!

### Insomnia Version

8.6.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

8.6.1

**Comment by notjaywu** [comment]
You should not block the IP address.

**Comment by subnetmarco** [comment]
@szabopatriklaszlo the update server and the login server share the same IP address. Can you block the DNS only?

By the way, for my understanding, why don't you want to update to 9.x?

**Comment by subnetmarco** [comment]
Closing now unless new data comes in.
