### ISSUE TITLE
[Feature Request] Can we make open/collapse caret icon bigger

### ISSUE THREAD

**Issue by ghiscoding** [getinsomnia/insomnia#747]
- Insomnia Version: 5.14.6
- Operating System: Windows 10

## Details
I find the open/collapse caret icon so small, we barely see it on the screen. It would be nice to have it much bigger (like 3x bigger since it's so small), or have a config setting to choose the size in pixel.

See below for a demo, we can barely see the caret on lines 1-3

![insomnia_carret](https://user-images.githubusercontent.com/643976/35984809-32dc7a44-0cc3-11e8-8797-25654aad5f10.png)

**Comment by gschier** [comment]
Hmm, this seems like a font issue. What OS are you on?

They are quite a bit larger on my computer (but still fairly small)

![image](https://user-images.githubusercontent.com/587576/36021804-eb895162-0dc1-11e8-8e7f-b75b9f19c328.png)

**Comment by ghiscoding** [comment]
I'm on Windows 10, is the caret part of a font? If so which Font is that? 
Anyhow, it would still be nice to have a setting somewhere in the configuration, I can barely click on them in my system since it's so small

**Comment by gschier** [comment]
Ya, it's just the character from the font being used. I just updated it so the fold icon uses a font that everyone should have (Times New Roman) so now it should be consistent across platforms.

**Comment by ghiscoding** [comment]
Awesome thanks a lot for the great and fast support. 

I'm lovin this tool compare to previous Postman

Though I think a missing feature vs Postman, is possibly showing a history of maybe last 10 queries (like Postman does). I didn't find anything in the list of issues... 
ahh wait I'm lying since I just found closed issue #732 talking about the history button. wow that was not obvious, a suggestion would be to make it clearer with possibly a text below the icon?!

Thanks for the awesome tool :)

**Comment by ghiscoding** [comment]
@gschier was that supposed to be in latest (Feb 14) `5.14.7` version? I don't see any changes on my side, the caret is still quite small
