### ISSUE TITLE
Collection not being synced from cloud

### ISSUE THREAD

**Issue by AsimAlam** [getinsomnia/insomnia#7476]
### Expected Behavior

On clicking any collection it should open and sync from the cloud.

### Actual Behavior

It is not able to sync automatically even after clicking.
![Screenshot 2024-06-03 135802](https://github.com/Kong/insomnia/assets/78923699/69b9373d-75c7-4e29-ad06-61ab6146694c)
After clicking on any collection it loads and returns to the same state after some time.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 9.2.0

### What operating system are you using?

Windows

### Operating System Version

Window 11

### Installation method

download from insomnia

**Comment by notjaywu** [comment]
Can you share your console logs when clicking on an unsynced file?

<img width="1437" alt="image" src="https://github.com/Kong/insomnia/assets/130019718/5cac3a8b-8582-46a1-8af6-5abedad57af0">

**Comment by AsimAlam** [comment]
Here are my console logs when clicking on the unsynced file.

![Screenshot 2024-06-04 093707](https://github.com/Kong/insomnia/assets/78923699/84873f45-edc1-412e-9ee2-9140a94b45db)

**Comment by marckong** [comment]
@AsimAlam would you be able to let us know your email address?

**Comment by marckong** [comment]
@AsimAlam can you also try to sign out and sign back in?

**Comment by AsimAlam** [comment]
@marckong I've tried every available solution, including reinstalling, but I still can't figure it out.

**Comment by notjaywu** [comment]
Can you try to reset your passphrase at https://app.insomnia.rest/app/settings/encryption? Please back up your local data first, and after resetting the passphrase, you need to be re-invited to this organization again.

**Comment by marckong** [comment]
@AsimAlam being removed and reinvited might help instead of resetting the passphrase. However, can we hop on a call together to run through some tests?

**Comment by marckong** [comment]
@AsimAlam we sent you an email. Let's troubleshoot it together

**Comment by marckong** [comment]
Resetting the passphrase solved this issue. Please reopen it when you continue to experience it
