### ISSUE TITLE
[Question] OAuth generate code doesn't seem to work correctly

### ISSUE THREAD

**Issue by ppazos** [getinsomnia/insomnia#748]
- Insomnia Version: 5.12.4
- Operating System: Mac OS

## Details

I'm trying to test the PayPal API from Insomnia, trying to reproduce a request like this:

```
curl -v https://api.sandbox.paypal.com/v1/oauth2/token \
   -H "Accept: application/json" \
   -H "Accept-Language: en_US" \
   -u "client_id:secret" \
   -d "grant_type=client_credentials"
```

ref: https://developer.paypal.com/docs/api/overview/#get-an-access-token

![screen shot 2018-02-09 at 2 23 09 am](https://user-images.githubusercontent.com/1278556/36012975-5bc41a48-0d40-11e8-9a20-52494e78875b.png)

When generating the curl from Insomnia I get this (doesnt contain the oauth2 data):

```
curl --request POST \
  --url https://api.sandbox.paypal.com/v1/oauth2/token \
  --header 'accept: application/json' \
  --header 'accept-language: en_US' \
  --cookie X-PP-SILOVER=name%253DSANDBOX3.API.1%2526silo_version%253D1880%2526app%253Dapiplatformproxyserv%2526TIME%253D2351660378%2526HTTP_X_PP_AZ_LOCATOR%253Dsandbox.slc
```

Also, I tested curl with oauth2 data and I get the right response, but when I do the request from Insomnia I get [oauth2] Failed to fetch token url= status=0

Because of this, I don't know if I'm doing something wrong on Insomnia oauth2 config or if this is a bug.

**Comment by gschier** [comment]
The first example you posted doesn't actually need the OAuth 2.0 feature at all. The `-u` in Curl means HTTP Basic authentication.

![image](https://user-images.githubusercontent.com/587576/36021426-b0847840-0dc0-11e8-909b-645092a5901b.png)

However, if you want to make use of the OAuth 2.0 feature in Insomnia, you should do something like this:

![image](https://user-images.githubusercontent.com/587576/36021565-29420e14-0dc1-11e8-95eb-9fbfa1586a57.png)

So, you enter the API endpoint you want to interact with, along with the OAuth 2.0 information, and Insomnia will automatically perform the request to fetch the token when needed.
