### ISSUE TITLE
Modal SyncMergeModal not found

### ISSUE THREAD

**Issue by sundas-arooj** [getinsomnia/insomnia#7486]
### Expected Behavior

I tried to pull the remote collection and getting an error. It was expected to fetch the Collection. 

### Actual Behavior

**Getting this error**

`Error: Modal SyncMergeModal not found at kn (file:///C:/Users/<username>/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:17:107603) at Ede (file:///C:/Users/<username>/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:49:17283) at tn (file:///C:/Users/<username>/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:49:16984) at file:///C:/Users/<username>/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:1494:29270 at new Promise (<anonymous>) at f6._conflictHandler (file:///C:/Users/<username>/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:1494:29254) at f6.handleAnyConflicts (file:///C:/Users/<username>/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:196:27981) at f6._merge (file:///C:/Users/<username>/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:196:32836) at async f6.pull (file:///C:/Users/<username>/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:196:30366) at async Uh1 (file:///C:/Users/<username>/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:1494:6575) at async Module.C (file:///C:/Users/<username>/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/remote-collections-d96e9215.js:1:623) at async Xl (file:///C:/Users/<username>/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:31:3691) at async je (file:///C:/Users/<username>/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:30:18468)`

### Is there an existing issue for this?

- [ ] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

https://insomnia.rest/download

**Comment by gatzjames** [comment]
Hi @sundas-arooj this is fixed in newer versions of Insomnia.
