### ISSUE TITLE
Cannot enable data encryption

### ISSUE THREAD

**Issue by wan-rev** [getinsomnia/insomnia#7507]
### Expected Behavior

1. Enter key passphrase
2. Click save
3. Data encryption enabled

### Actual Behavior

1. Enter key passphrase
2. Click save
3. Got error 'Something went wrong, W are already working on fixing it'

### Reproduction Steps

1. Go to account setting
2. Go to Encryption tab
3. Enter key passphrase
4. Click save

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 9.2.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### Installation method

downloaded from insomnia.rest

**Comment by notjaywu** [comment]
@wan-rev A quick workaround: reset your passphrase at https://app.insomnia.rest/app/settings/encryption, and ask the owner to re-invite you. We are working on the fix.
