### ISSUE TITLE
[Feature Request] Interactive JSON Response Tree

### ISSUE THREAD

**Issue by reachui** [getinsomnia/insomnia#751]
Hi,

Let me start by saying that I'm a big fan the Insomnia app and use it daily.

One (slight) frustration I have is when I get a large hierarchical response and need to find a node and how it appears in that hierarchy.  An interactive tree view would help to address this - you could hover over a node and get 

- a summary of the path 
- the JSONPath expression for future requests
- the ability to isolate the parent node

This could be done by adding a new option in the Preview menu "Interactive Tree" for example.

I'd be happy to work on a prototype for this if it sounds like it would be of use.

Thanks
Val

**Comment by gschier** [comment]
Is this what you're looking for? https://github.com/getinsomnia/insomnia/pull/494

It still has quite a bit of work until it's done, but it sounds like what you are asking for.

**Comment by reachui** [comment]
It certainly looks like the beginnings of what I had in mind without trying it out. 

I was thinking that each tree node would keep a reference to the JSON element it's displaying. Then when you hover you get a popup allowing you to get more info like its path in the hierarchy, etc.

It's probably more useful where complex Java objects are serialized into deeply nested JSON
