### ISSUE TITLE
I can't drag the request to another location

### ISSUE THREAD

**Issue by damirqa** [getinsomnia/insomnia#7517]
### Expected Behavior

I expected that if I took the request and dragged it in the list below, it would stay there

### Actual Behavior

When I start dragging a request by scrolling through the list of requests, the indicator disappears where the query will be inserted, so the query remains in place

### Reproduction Steps

1. create a large number of requests so that they do not fit into the screen (scrolling should appear)
2. start dragging the request and scroll to the very bottom, the insertion indicator should disappear

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.2.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.2.1

### Installation method

download

**Comment by notjaywu** [comment]
Can you check if the selected option is `Manual`? 

<img width="461" alt="image" src="https://github.com/Kong/insomnia/assets/130019718/46fd5ad2-06bf-47ef-aa36-82181b789d0f">

**Comment by DamirShaniiazov** [comment]
yes, selected manual

**Comment by subnetmarco** [comment]
@notjaywu any follow up actions we can take here?

**Comment by notjaywu** [comment]
@damirqa @damirshaniyazovmechta Can you upgrade to v9.3.2 to check if it still exists? If it does, please join https://chat.insomnia.rest so I can DM you for more details.

**Comment by damirqa** [comment]
The problem is solved
