### ISSUE TITLE
[Feature Request] Request filter handling

### ISSUE THREAD

**Issue by Hyjan** [getinsomnia/insomnia#753]
Make all XPath & JSON path filtering the same on all places where filtering exists. This would make it easier to try the filtering on response result then paste it as edit tag och create alias.

For exmaple (//something)[4] works on result page but it does not work on edit tag page. 

![image](https://user-images.githubusercontent.com/35093477/36137597-45c66d82-1096-11e8-8b51-915796cc8dcc.png)

![image](https://user-images.githubusercontent.com/35093477/36137866-68f26116-1097-11e8-8ff2-86d70931548b.png)

**Comment by gschier** [comment]
I'm not exactly sure what you are asking. Can you provide more details?

**Comment by Hyjan** [comment]
Well nvm. It seems to be broken due to my 30 or so alias's, because it lagged and broke something. 
Seems to work now when I removed the alias's.
