### ISSUE TITLE
[Feature Request] Show the source of a variable replacement when hover and click

### ISSUE THREAD

**Issue by rocketraman** [getinsomnia/insomnia#754]
- Insomnia Version: 5.14.6
- Operating System: Linux Fedora 27

## Details

I use variables extensively. I have variables at the environment level, a base shared environment, and at the folder level.

This sometimes gets a bit confusing. It would be helpful if, when hovering over a variable placeholder, in addition to the URL a little bit of text like `(from env Foo)` or `(from folder xxx)` was appended. The same information could be shown in the popup when one clicks on the variable.

**Comment by gschier** [comment]
It took some thinking to figure out if this is even possible, but I think it is. 

Here's how I would approach this problem, in case someone wants to submit a PR:

- Add a `getKeysMeta` function to environment that returns a map of path to source name, where source name the name of the environment or folder. See [this](https://github.com/getinsomnia/insomnia/blob/b3e473071824f0e48e7c26507163182acbe01703/packages/insomnia-app/app/common/render.js#L206-L209) for example
- Use `getKeysMeta` function to figure out the source when [setting the `title` attribute](https://github.com/getinsomnia/insomnia/blob/b3e473071824f0e48e7c26507163182acbe01703/packages/insomnia-app/app/ui/components/codemirror/extensions/nunjucks-tags.js#L250) on the tag
