### ISSUE TITLE
Unable to undo (cmd+z) a change once a request has been sent

### ISSUE THREAD

**Issue by rich-grundy-paytently** [getinsomnia/insomnia#7543]
### Expected Behavior

Ability to undo a change to a request payload using cmd+z even after request has been sent.

1) Remove a property from the JSON payload
2) Send request
3) Cmd + z to undo the changes
4) Property removed in step 1 is returned

### Actual Behavior

1) Remove a property from the JSON payload
2) Send request
3) Cmd + z to undo the changes
4) Undo is not possible and it's impossible to revert to the earlier version of the request without using the Discard all changes option in the sync menu

![image](https://github.com/Kong/insomnia/assets/168630986/97fde23b-deea-4f33-bee6-cc81b990b84e)

### Reproduction Steps

1) Remove a property from the JSON payload
2) Send request
3) Cmd + z to undo the changes

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.0

### What operating system are you using?

macOS

### Operating System Version

macOs 13.5

### Installation method

Download from website

**Comment by rich-grundy-paytently** [comment]
Just found that this is a duplicate of:
https://github.com/Kong/insomnia/issues/7352

I've closed but it would be great to have an update

**Comment by leonardogmz** [comment]
Same here from:

![image](https://github.com/Kong/insomnia/assets/3417976/e839e82a-26ba-4e3b-8715-54d584359bfb)
