### ISSUE TITLE
Pre Request Script - Incorrect value of a recursive env Variable

### ISSUE THREAD

**Issue by karan221** [getinsomnia/insomnia#7548]
### Expected Behavior

Pre Request Script
```
console.log(insomnia.environment.get('recursive_variable'));
// log: "value"
```

### Actual Behavior

Pre Request Script
```
console.log(insomnia.environment.get('recursive_variable'));
// log: "{{ _.base_variable }}"
```

### Reproduction Steps

Add base env variable -> { "base_variable": "value" }
Add sub env recursive variable -> { "recursive_variable": "_.base_variable" }

Run the pre-request script

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

v9.2.0

### What operating system are you using?

macOS

### Operating System Version

13.6.3

### Installation method

hombrew

**Comment by ihexxa** [comment]
Hello @karan221 Rendering is not enabled in the script as you are able to read variables directly from script, may I know the use case?

If you really want to render it, you could try something like this:
```javascript
console.log(
	insomnia.collectionVariables.replaceIn(
		insomnia.environment.get('recursive_variable')
	)
);
```

**Comment by karan221** [comment]
Thanks this will work
