### ISSUE TITLE
Cannot destructure property 'activeWorkspace' of 'z(...)' as it is undefined.

### ISSUE THREAD

**Issue by hientm4-minhhien** [getinsomnia/insomnia#7557]
### Expected Behavior

I expected that after clicking on try to reload the app, the issue would be solved

### Actual Behavior

In fact, after trying to reload the app, nothing happened.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.2.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### Installation method

download from insominia directly

### Last Known Working Insomnia version

8.6.1

**Comment by gatzjames** [comment]
Hi @hientm4-minhhien could you provide more context?
Could you upgrade to the latest version and let me know if this issue still happens for you?

**Comment by gatzjames** [comment]
Closing as it cannot be reproduced. Please feel free to reopen if it still happens for you
