### ISSUE TITLE
Header item always gets deleted on sending the request

### ISSUE THREAD

**Issue by ywidiastuti** [getinsomnia/insomnia#7559]
### Expected Behavior

Header item stays after sending request

### Actual Behavior

Header item always gets deleted on sending the request

### Reproduction Steps

See video

https://github.com/Kong/insomnia/assets/145996165/fb6af996-82a0-4886-bb34-dc9575f91056

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

 v9.3.0-beta.5

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

v9.2.0

**Comment by gatzjames** [comment]
👋 Thanks for the feedback, closing this as it looks to be working in latest develop.
