### ISSUE TITLE
Can't login (openSUSE)

### ISSUE THREAD

**Issue by thommierother** [getinsomnia/insomnia#7565]
### Expected Behavior

Login successful

### Actual Behavior

Login fails with "invalid code: failed to fetch"

### Reproduction Steps

- web login through mail or Github OIDC is successful
- re-direct from browser fails with KioExec error on KDE Plasma 6.x, see https://api.kde.org/frameworks/kio/html/dir_7e4425f14179b49130a4955a9af1fa4d.html
- using the copied token instead
- results in error message, no login in the electron app, only in the browser session

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Note: I paid for the product and can not use it

### Insomnia Version

9.2

### What operating system are you using?

Other Linux

### Operating System Version

openSUSE Tumbleweed with KDE Plasma 6 on Wayland

### Installation method

AppImage (as there is only an outdated version from 2023 on flatpak)

### Last Known Working Insomnia version

none

**Comment by thommierother** [comment]
![Bildschirmfoto_20240620_070911](https://github.com/Kong/insomnia/assets/6594120/8e31bfa4-2858-4379-aa27-193ed9e2c220)

**Comment by subnetmarco** [comment]
@thommierother can you try to disable the proxy from the Preferences? You can access the preferences from the Scratch Pad.

![Screenshot 2024-06-20 at 2 33 30 PM](https://github.com/Kong/insomnia/assets/964813/c97eb77b-289c-439e-baff-d0ad358dba54)

**Comment by subnetmarco** [comment]
Closing in favor of https://github.com/Kong/insomnia/issues/7358#issuecomment-2180565794 where we are having a discussion.
