### ISSUE TITLE
Pre-request script doesn't get executed

### ISSUE THREAD

**Issue by ywidiastuti** [getinsomnia/insomnia#7567]
### Expected Behavior

Pre-request script should be executed

### Actual Behavior

I checked using console.log, the script inside pre-request script doesn't get executed at all 

### Reproduction Steps

https://github.com/Kong/insomnia/assets/145996165/7093ea5e-f1de-4eee-8c0d-459717313a39

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

v9.2.0 

### What operating system are you using?

Ubuntu

### Operating System Version

Linux Mint 21.3

### Installation method

tar.gz

### Last Known Working Insomnia version

-

**Comment by ihexxa** [comment]
Hello @ywidiastuti , the `console.log` doesn't print to the dev tool, could you check outputs in the "timeline" tab in the right bar?

**Comment by ywidiastuti** [comment]
Thank you for the information @ihexxa . I found them 👍
