### ISSUE TITLE
[Feature Request]  Option to save response to file automatically

### ISSUE THREAD

**Issue by jlcs-es** [getinsomnia/insomnia#758]
Just like in a curl command you would redirect the output to a file with `> response.xml`, it would be nice to add a tab to handle what to do with the response, aside from previewing in the right panel.

The tab could be implemented as a list, where for each item that is usually shown in the right panel (Body Response, Full Response, Header, Timeline) could be assigned a file path to be saved as.

The use-case scenario for me is a series of third party services that return XML documents as response, and the same document is fed to another service through the `File` tab as a binary file. The workflow could be automatized even further if the steps for saving the Body Response where a feature of Insomnia.

**Comment by gschier** [comment]
This actually already exists, although it's quite hidden. You can access it by right-clicking (or cmd+clicking) the Send button.

![image](https://user-images.githubusercontent.com/587576/36202736-fa9e4b74-11bf-11e8-83a8-2a675263763e.png)

It isn't quite as full-featured as you are describing, but give it a try and let me know your feedback.

**Comment by gschier** [comment]
Closing this one for now but let me know if my answer missed something!

**Comment by robross0606** [comment]
This is okay but it a completely terrible location.  Put this down in the response section.  The places I intuitively checked for this feature were on the size of the response ("4.5MB") and the drop down on the right side of the response area that says something like "7 minutes ago".  That drop down already has things like "Delete current response".  Adding a "Save current response" would make perfect sense here.  Also, use of the term "download" is completely misleading.  The response is not being "downloaded" from anywhere if you already have it. This is simply "saving" a response from volatile to non-volatile storage.

**Comment by simontom** [comment]
Hi, would by great to be able to specify format/part of the response.
Like an extraction of some parts and creating e.g. JSON file on local storage for another processing on computer.

(I'm aware it's already closed but ... :-D )

**Comment by PHBMdeveloper** [comment]
It would be great too if the repetition saved a list .. ;-)

**Comment by ghost** [comment]
This is not really helpful as it is currently.

I need to download a file from one endpoint and re-post it to another endpoint via request chaining.

With this as it is such things are not possible and only allows me to manually download a file and then specifically select it every time.
