### ISSUE TITLE
Can't login, authorization page is not properly configured

### ISSUE THREAD

**Issue by OneComputerGuy** [getinsomnia/insomnia#7587]
### Expected Behavior

When clicking the "Continue with GitHub" button, a page opens and redirects to the page to select the provider and shows the code/launches the application

### Actual Behavior

Page doesn't properly load and shows a bunch of errors related to MIME types after redirecting to the authorization page

<img width="3004" alt="image" src="https://github.com/Kong/insomnia/assets/44152511/adc5f7a4-0f45-4dde-820c-f0a0591b093b">

### Reproduction Steps

- Open the application brand new
- Click "Continue with GitHub"
- Wait until the page loads in the browser
- Click on any of the providers, which does nothing

Tried with different networks, different browsers and the behavior is the same.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

No extensions or anything else was enabled (tried using the "Guest" profile on Chrome and the same behavior was seen)

### Insomnia Version

9.2.0

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### Installation method

Homebrew

**Comment by 10ego** [comment]
same here. bump.

**Comment by marckong** [comment]
@OneComputerGuy @10ego it should be resolved now.
