### ISSUE TITLE
[Improvement] Display version number more obviously

### ISSUE THREAD

**Issue by Mardoxx** [getinsomnia/insomnia#760]
- Insomnia Version: Hold on while I try and figure it out (5.14.7)
- Operating System:  w10

## Details

Would be nice to have Help->About to show about page with version number.

Wasn't very intuitive to go Application->Preferences and then find the version number at the top of the modal.

**Comment by gschier** [comment]
I'm not a Windows user so maybe you can answer this. Are About screens common in Windows? If so, can you provide some screenshots examples of about screens from some popular apps?

**Comment by Mardoxx** [comment]
Not sure if it's just a windows thing! It's certainly a common theme in windows and xplat apps.

I tried to find out if this sort of UI feature had a name, but I came up short :(

Here are some examples!

All found `Help->About`

Chrome just links to `chrome://settings/help`

VS Code's is simple like this 
![image](https://user-images.githubusercontent.com/239665/36262094-640e2fc2-125e-11e8-85c6-689232f3dec8.png)

Slack:
![image](https://user-images.githubusercontent.com/239665/36262152-7fdd3dec-125e-11e8-8f6c-02fa2adda050.png)

Visual Studio:
![image](https://user-images.githubusercontent.com/239665/36262110-6aaaa310-125e-11e8-89e0-7e19e3a8989c.png)

Photoshop:
![image](https://user-images.githubusercontent.com/239665/36262283-e311cbd0-125e-11e8-80c7-56513133402e.png)

**Comment by Mardoxx** [comment]
Something like VSCode's would be easiest to implement I suppose https://github.com/Microsoft/vscode/blob/c869fef06cd7edcc0c26eee143bea4695a1a8a67/src/vs/platform/windows/electron-main/windowsService.ts#L416-L449

**Comment by gschier** [comment]
Ah yes, it's definitely a cross-platform thing but Electron provides it for free on Mac using the native OS APIs. So I guess my question was "Is there a _specific_ way to do it in Windows", which it seems like there isn't. 

Both Slack and VS Code are Electron too, so it's probably worth looking at how they implement it for non-mac platforms. Thanks for the response! 😄 

![image](https://user-images.githubusercontent.com/587576/36262689-240b4438-12a3-11e8-84ea-a7ecba8b067a.png)

**Comment by Mardoxx** [comment]
Haha! Completely misunderstood what you were asking! I had no idea macOS did that 😄 

Can take a look at this after I've gone through that file-plugin bug, unless you get round to it before me 😄

**Comment by gschier** [comment]
Would be awesome if you could take a look at this one, but no worries if you can't 😄 I've got a few other things to tackle first.
