### ISSUE TITLE
Manage Cookies Fails to Load

### ISSUE THREAD

**Issue by redbaran** [getinsomnia/insomnia#7604]
### Expected Behavior

Clicking Manage Cookies should show a list of cookes

### Actual Behavior

An application error is shown:
Error: [object Object] at Object.validate (C:\Users\myUsername\AppData\Local\insomnia\app-9.3.0\resources\app.asar\node_modules\tough-cookie\lib\validators.js:91:13) at formatDate (C:\Users\myUsername\AppData\Local\insomnia\app-9.3.0\resources\app.asar\node_modules\tough-cookie\lib\cookie.js:322:14) at Cookie.toString (C:\Users\myUsername\AppData\Local\insomnia\app-9.3.0\resources\app.asar\node_modules\tough-cookie\lib\cookie.js:952:29) at wS1 (file:///C:/Users/myUsername/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:110:16004) at Ze (file:///C:/Users/myUsername/AppData/Local/insomnia/app-9.3.0/resources/app.asar/workspace-environments-edit-modal-Bf0HPEMW.js:1:16292) at Ok (file:///C:/Users/myUsername/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:43:17033) at NK (file:///C:/Users/myUsername/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:45:44104) at kK (file:///C:/Users/myUsername/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:45:39822) at Z9e (file:///C:/Users/myUsername/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:45:39748) at Yh (file:///C:/Users/myUsername/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:45:39598) at ME (file:///C:/Users/myUsername/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:45:35960) at EK (file:///C:/Users/myUsername/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:45:34907) at L (file:///C:/Users/myUsername/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:30:1594) at Immediate.oe [as _onImmediate] (file:///C:/Users/myUsername/AppData/Local/insomnia/app-9.3.0/resources/app.asar/mainWindow-BuUzBfxG.js:30:1965) at process.processImmediate (node:internal/timers:478:21)

### Reproduction Steps

1. Create a collection
2. Call an API that returns cookies
3. Click Manage Cookies

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The following cookies were returned and are visible in the Cookies Tab for the API that was called:
<html>
<body>

.AspNetCore.Identity.Application | CfDJ8BkV4O4AgntFqx8WQYHTRoY25A8ZWWnsJJNIg170eeO7G6gSUeGyqiB8WTtyz28_RxWG4jK4u1fuCQR6qhGm-dLZm6OuLOr4ucqfj8YeI1AQ6DM2JBcHmEASzZto09Y3v2lJNGbyRIhgQvdz001y6PsAsOW4nXRmoIr-cuZ9OqND7HdoT55W3jI2fYOp5E5mxIcDn3eiEi87gVnfx5KOq--jcMto9RT9AiqmU1Hdxpz0GhryHIyxpG2q4KKG4M354SiGyBx4w99M0efy_K5xsL3rGgHfXNOVnNWv7kPXZ_hYr6HtXaZmzPoDSeHDsTmKb3k0PUmvS0dByIfCsuYDbz3eV-lLMs7ZTalYziri7BI8xOQuaXQJLvusAaqqos91PENYu35nxsLY3E0TwdzKnrxiTBnUMMfb1xSTDvX1DChyESt6vNGQIl77QCS1ICoW1p1mmlxBbkEBVVK7n7pjkm6nPfQKcjg3N89T2w6OQ8hZewwJwJWKYCvRW2ukY6CjJ83EORMke5RbUtUJ2SiiT3Ut1DWu4pEWo2O-TZuHg1yS
-- | --
TS015b6bdd | 01d9737dc75e2c48bcb1f318d910416cd0ec4b25125195374fec30a9186c2064b4c81a816e4c74c098a1f7c87d1170fa37cd808f03
TS01baf3a3 | 01d9737dc7e9e34e2b59f9fd6f7efa0e20f03d5adc5195374fec30a9186c2064b4c81a816ee5bb279f65bfa0cde36cbb751b90e682877a184daab0aded3fbd2df76f1f09aa

</body>
</html>

![image](https://github.com/Kong/insomnia/assets/8302838/65cc7c50-b74f-4d1b-bf9d-9266a7963251)

### Insomnia Version

9.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Download from insomnia.rest, app self updated

### Last Known Working Insomnia version

N/A

**Comment by subnetmarco** [comment]
We are looking into this issue.

**Comment by doorfsimite** [comment]
I'm building a API and the session is managed with cookies, with this cookie problem, I'm not able to send authenticated requests. So this problem is basically preventing me to use insomnia

**Comment by nataliakeller** [comment]
I'm having the same problem. When I try to click the "manage cookies" button, it gives me the red warning "Render Failure: [object Object]".

**Comment by leofernandesbh** [comment]
I have the same problem with Insomnia on Mac. My application manages sessions through cookies and as a result I can no longer perform my tests.

**Comment by umut-sar** [comment]
I am experiencing the same problem. When I switch to version 9.2.0, it works again.

**Comment by subnetmarco** [comment]
Update: we found the issue and working on releasing 9.3.1 that will fix this regression.

**Comment by gatzjames** [comment]
Thanks for the feedback. Closing as this was fixed in 9.3.1
