### ISSUE TITLE
UI resets after every request

### ISSUE THREAD

**Issue by kevmurray** [getinsomnia/insomnia#7606]
### Expected Behavior

When I send a GQL request, the UI should only update the response panel

### Actual Behavior

After sending a graphql request
1. The request list scrolls to the bottom of the panel and I have to scroll back to the top.
2. The Query Variables panel resizes to the default size

### Reproduction Steps

1. Scroll to GQL request
2. Resize Query Variables panel
3. Click "Send"
4. Request list scrolls to bottom & query variables panel reverts to previous size

Video: https://youtu.be/q6qNYQJjcIs

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 9.3.0
Build date: 6/27/2024
OS: Darwin x64 22.5.0
Electron: 30.0.9
Node: 20.11.1
Node ABI: 123
V8: 12.4.254.20-electron.0
Architecture: x64

### Insomnia Version

9.3.0

### What operating system are you using?

macOS

### Operating System Version

MacOS 13.4.1 (c) 

### Installation method

downloaded from insomnia originally, then auto-updated since

### Last Known Working Insomnia version

previous version before upgrade (not sure what that was)

**Comment by subnetmarco** [comment]
Closing this as fixed in https://github.com/Kong/insomnia/pull/7626 and will be released in the upcoming 9.3.2
