### ISSUE TITLE
The app constantly crashing

### ISSUE THREAD

**Issue by dimusik** [getinsomnia/insomnia#7612]
### Expected Behavior

The app doesn't crash

### Actual Behavior

After 30-60 seconds of running the app crashes without any message

### Reproduction Steps

1. Open Insomnia
2. Choose collection of requests 
3. Wait or perform request, switch between windows
4. The app crashes

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The problem occurred after the last update

### Insomnia Version

9.3.0

### What operating system are you using?

macOS

### Operating System Version

Mac OS Ventura 13.6.6

### Installation method

Downloaded from insomnia.rest

**Comment by subnetmarco** [comment]
@dimusik Was this happening even in 9.2, or did it start happening now in 9.3?

**Comment by dimusik** [comment]
> @dimusik Was this happening even in 9.2, or did it start happening now in 9.3?

Hi @subnetmarco, it happening now, in 9.3, right after the update. 

I updated the app today, reloaded it and it started crashing.

**Comment by subnetmarco** [comment]
@gatzjames @marckong what logs can we gather to understand why it crashes?

**Comment by filfreire** [comment]
@dimusik would you be able to provide us with the contents of these 2 files:
- `~/Library/Logs/Insomnia/main.log`
- `~/Library/Logs/Insomnia/renderer.log`

**Comment by dimusik** [comment]
Hi @filfreire, here's the contents of main.log

`
cat ~/Library/Logs/Insomnia/main.log
[2024-06-28 15:41:23.350] [info]  Running version 9.3.0
[2024-06-28 15:41:23.370] [info]  [electron client protocol] successfully set default protocol 'insomnia://'
[2024-06-28 15:41:38.594] [info]  [fix] Running database repairs
[2024-06-28 15:41:38.749] [info]  [main] creating new window for MacOS activate event
[2024-06-28 15:41:38.764] [info]  [main] App not ready to "activate" yet
[2024-06-28 15:41:39.302] [info]  [db] Initialized DB at /Users/xxx/Library/Application Support/Insomnia/insomnia.$TYPE.db
[2024-06-28 15:41:39.302] [info]  [db] Init responses DB
[2024-06-28 15:41:39.303] [info]  [db] Init websocket-responses DB
[2024-06-28 15:41:39.309] [info]  [localstorage] Initialized at /Users/xxx/Library/Application Support/Insomnia/localStorage
[2024-06-28 15:41:39.805] [info]  [main] Loading file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.html
[2024-06-28 15:41:40.126] [info]  [main] Registering the hidden window restarting handler
[2024-06-28 15:41:40.141] [info]  [updater] Using url https://updates.insomnia.rest/builds/check/mac?v=9.3.0&app=com.insomnia.app&channel=stable
[2024-06-28 15:41:40.142] [info]  [updater] Checking for updates url=https://updates.insomnia.rest/builds/check/mac?v=9.3.0&app=com.insomnia.app&channel=stable
[2024-06-28 15:41:42.129] [info]  [updater] Not Available
[2024-06-28 15:41:44.888] [info]  [main] Window ready, handling command line arguments [ '/Applications/Insomnia.app/Contents/MacOS/Insomnia' ]
[2024-06-28 15:41:44.890] [info]  [main] Check args and create windows []
[2024-06-28 15:41:44.890] [info]  [main] Checking for newer version than  9.3.0
[2024-06-28 15:41:45.146] [info]  [main] Found newer version
[2024-06-28 15:41:45.149] [info]  [main] Backup found at: /Users/xxx/Library/Application Support/Insomnia/backups/9.3.0
`

And renderer.log
`
 1	[2024-06-28 15:41:42.693] [info]  [db] Initialized DB client
     2	[2024-06-28 15:41:42.809] [info]  [plugin] Loading
     3	[2024-06-28 15:41:43.740] [info]  [project] Fetching org_afe32a08-44f8-4f03-a5ae-cbefa8e11120
     4	[2024-06-28 15:41:43.938] [info]  [project] Redirecting to last visited project proj_default-project
     5	[2024-06-28 15:41:43.953] [info]  [FileSystemDriver] Initialized in "/Users/xxx/Library/Application Support/Insomnia/version-control"
     6	[2024-06-28 15:41:50.658] [info]  [sync] Activated project prj_c4f20d37b57c45e9bf5a63397085bde6
     7	[2024-06-28 15:41:50.658] [info]  [FileSystemDriver] Writing to /projects/prj_c4f20d37b57c45e9bf5a63397085bde6/meta.json
     8	[2024-06-28 15:41:50.659] [info]  [FileSystemDriver] Writing to /Users/xxx/Library/Application Support/Insomnia/version-control/projects/prj_c4f20d37b57c45e9bf5a63397085bde6/meta.json.af450218-d9f6-4b03-86e3-5122d8fdddc7.tmp then renaming to /Users/xxx/Library/Application Support/Insomnia/version-control/projects/prj_c4f20d37b57c45e9bf5a63397085bde6/meta.json
     9	[2024-06-28 15:41:50.770] [info]  [sync] Activated project prj_c4f20d37b57c45e9bf5a63397085bde6
    10	[2024-06-28 15:41:50.770] [info]  [FileSystemDriver] Writing to /projects/prj_c4f20d37b57c45e9bf5a63397085bde6/meta.json
    11	[2024-06-28 15:41:50.771] [info]  [FileSystemDriver] Writing to /Users/xxx/Library/Application Support/Insomnia/version-control/projects/prj_c4f20d37b57c45e9bf5a63397085bde6/meta.json.85bc7570-f3a4-4319-9ad1-b49b910ea43f.tmp then renaming to /Users/xxx/Library/Application Support/Insomnia/version-control/projects/prj_c4f20d37b57c45e9bf5a63397085bde6/meta.json
`

**Comment by dimusik** [comment]
Also looked over the system logs and here's what I found:

Process - spindump, `Insomnia [57192]: slow hid response: not sampling due to conditions 0x80208102`

From process insomnia, last message was the following

`LSExceptions shared instance invalidated for timeout.`

After that I'm getting messages from runningboardd

`[app<application.com.insomnia.app.232272091.232272097(501)>:57192] termination reported by launchd (2, 5, 5)`

UPD

Also noticed the following messages by runningboardd:

`
Invalidating assertion 172-166-326730 (target:[app<application.com.insomnia.app.232272091.232272097(501)>:57192]) from originator [osservice<com.apple.WindowServer(88)>:166]
`

and symptomsd:
`
defusing ticker tickerFatal having seen progress by flow for com.insomnia.app, rxbytes 7176 duration 25.183 seconds started at time: Fri Jun 28 15:46:50 2024
`

form window manager I'm getting this
`
Connection invalidated | (57192) Insomnia
`

This is the complete trace of everything related to insomnia in system log during shutdown

<img width="1395" alt="image" src="https://github.com/Kong/insomnia/assets/1124913/5ad32043-1676-4172-bb7c-44fe7d4994f2">

**Comment by subnetmarco** [comment]
@dimusik Are you using Windows, MacOS, or Windows on MacOS?

**Comment by dimusik** [comment]
Hi @subnetmarco, I'm using native Mac OS Ventura 13.6.6

**Comment by dimusik** [comment]
@subnetmarco, maybe I can provide some other info? I see that insomnia uses Electron.js, could it be related to it?

**Comment by subnetmarco** [comment]
@filfreire what other information do you need to debug this issue?

**Comment by filfreire** [comment]
@dimusik, we use Electron -  this could be some sort of bug with the latest Electron version and your particular MacOS version. I will open a separate PR with a patched version of Electron and you can attempt to use that one instead.

Would you mind in the meantime to attempt 3 different experiments to help us further debug the issue:

- Make sure the app is closed, download the latest .app from the website and before opening the app run `mv ~/Library/Application\ Support/Insomnia ~/Library/Application\ Support/InsomniaBackup`, and see if it still crashes

- Also, alternatively, try to run `INSOMNIA_DATA_PATH=~/Desktop/Insomnia-experiment /Applications/Insomnia.app/Contents/MacOS/Insomnia` and see if it crashes after some minutes of use.

- Lastly, please confirm the crash does not happen in 9.2.x

**Comment by attvegso** [comment]
Hi. The same crash happens in windows 11. And it happened in the previous version too
Version: Insomnia 9.3.2
Build date: 7/4/2024
OS: Windows_NT x64 10.0.22631
Electron: 30.0.9
Node: 20.11.1
Node ABI: 123
V8: 12.4.254.20-electron.0
Architecture: x64

**Comment by subnetmarco** [comment]
We suspect this is an error in Electron. We just updated from Electron `30.0.9` to `30.2.x` in the latest 9.3.3-beta1 release. Can you please try to download the beta at https://github.com/Kong/insomnia/releases/tag/core%409.3.3-beta.1 and see if it now works?

Thanks

**Comment by attvegso** [comment]
> We suspect this is an error in Electron. We just updated from Electron `30.0.9` to `30.2.x` in the latest 9.3.3-beta1 release. Can you please try to download the beta at https://github.com/Kong/insomnia/releases/tag/core%409.3.3-beta.1 and see if it now works?
> 
> Thanks

I was able to crash it only twice. Other that that 99% better. This way is much more usable. :)
Thanks for you help

**Comment by subnetmarco** [comment]
@attvegso thank you, we will keep monitoring the situation. Let us know if this ticket needs to be re-opened.

**Comment by trapcodeio** [comment]
I am currently facing this issue:

Version: Insomnia 10.2.0
Build date: 11/27/2024
OS: Darwin x64 23.5.0
Electron: 31.4.0
Node: 20.16.0
Node ABI: 125
V8: 12.6.228.30-electron.0
Architecture: x64

MAC OS
