### ISSUE TITLE
After 9.3.0 Update can no longer edit requests.

### ISSUE THREAD

**Issue by nickpelton** [getinsomnia/insomnia#7619]
### Expected Behavior

I expect to select a request and then be able to edit the request options. (eg. url, headers, parameters, etc)

### Actual Behavior

I can no longer see or activate the edit request toolbar when selecting or creating a new request. I can see the request history. If I make a new request or clear the history, I just get a blank screen. I can't find a setting or option that toggles the request editing toolbar.  

<img width="1597" alt="Screenshot 2024-06-28 at 10 16 37 AM" src="https://github.com/Kong/insomnia/assets/289422/46a7f341-69bc-4531-82da-39d2dbbf7873">

### Reproduction Steps

1. Make a new request.
2. Try and edit the request. 
3. SEE there are no toolbars, tabs, or ways to actually edit the request.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This worked fine yesterday. Today, toolbar is missing after upgrade to 9.3.0. I downgraded to 9.2.0 and issue now persists.

### Insomnia Version

9.3.0

### What operating system are you using?

macOS

### Operating System Version

14.4.1

### Installation method

Download from insomnia.net. Also downloaded downgrade from gihub. 

### Last Known Working Insomnia version

9.2.0

**Comment by gatzjames** [comment]
Hi @nickpelton, I can't seem to reproduce this issue.
Is this happening on all your collections or a specific one?
Also could you share if there are any errors in the app logs?
To find the logs in macOS: `View` > `Toggle DevTools` and select the `Console` tab on the panel that opens up.

**Comment by nickpelton** [comment]
This has occurred for all my collections as well as any new collections and requests.  Opened debug and not seeing any errors. Screenshot of after these steps:

1. Open Insomnia (already logged in).
2. Select my collection.
3. Select the "New Request" 

<img width="1603" alt="Screenshot 2024-06-28 at 11 52 10 AM" src="https://github.com/Kong/insomnia/assets/289422/bd3f1000-4580-4721-bd60-b30f1b58d53f">

You can see there is no tooling available to edit the request.

**Comment by nickpelton** [comment]
I exported all my collections. Deleted the Insomnia App, deleted the Application Support and Log folders, and reinstalled 9.3.1 and now it seems to be working again. Got in some sort of bad state after the upgrade.
