### ISSUE TITLE
Very simple bug | Query Parameter not changing opacity when I disable it

### ISSUE THREAD

**Issue by caionobrex** [getinsomnia/insomnia#7621]
### Expected Behavior

The below is the expected behavior. Insomnia used to down the opacity when I disabled the parameter and set the opacity to normal when I activated it.
![Screenshot 2024-06-29 at 13 03 25](https://github.com/Kong/insomnia/assets/20375933/c6182be0-823d-4eb0-af4f-4cf4613233f4)

### Actual Behavior

Not changing opacity anymore
![Screenshot 2024-06-29 at 13 06 18](https://github.com/Kong/insomnia/assets/20375933/b510b8de-0322-4e5a-b386-162f6f39e2ab)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I have made the fix already. If you guys allow me to open PR, I can do it ASAP

### Insomnia Version

v9.3.1

### What operating system are you using?

macOS

### Operating System Version

mac Sonoma 14.5

### Installation method

download from Insomnia

**Comment by Halkyon64** [comment]
yes, this is very strange and sad behavior after last update (
consider this bug and the fact, that request doesn't sent with changed parameters after pressing CMD+enter, I roll backed to 9.2.0. Hope some day this raw release will fixed
