### ISSUE TITLE
Folder is not expanding 

### ISSUE THREAD

**Issue by wangmir** [getinsomnia/insomnia#7622]
### Expected Behavior

When click the folder of the collection, expand.

### Actual Behavior

Sometimes, expanding, but mostly staying without any changes.

### Reproduction Steps

1. Go to collection
2. Click folder

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

https://github.com/Kong/insomnia/assets/6769075/7b829d49-2ef4-4fc6-b21e-0acdee4af662

### Insomnia Version

9.3.1

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

9.2.0

**Comment by Ayzkub** [comment]
As a workaround for this issue you can search for a request from that folder and it will expand after some time.

**Comment by AdiDil** [comment]
This reproduces everytime if the folder you're trying to click is 'selected', ie. has the purple bar to the left. An easy workaround is to just select another folder before clicking the icon of the folder you want to expand.

**Comment by lmorganl** [comment]
same issue (since all first 9.3 beta versions) and also 9.3.1

**Comment by tbuck-webstaurantstore** [comment]
can confirm this is happening on windows with version 9.3.1  

**alternative workaround:** single-click the "name" (not folder icon) on a different folder to 'select' it. Now single-click the 'folder-icon' you wish to expand.

**Comment by subnetmarco** [comment]
Prioritizing for 9.3.2 this week.
