### ISSUE TITLE
Cannot export environment

### ISSUE THREAD

**Issue by wangmir** [getinsomnia/insomnia#7629]
### Expected Behavior

Export environment works.

### Actual Behavior

<img width="823" alt="image" src="https://github.com/Kong/insomnia/assets/6769075/abc4391a-218f-400c-b783-8e08b12d20e0">

Export cannot be done.

### Reproduction Steps

1. create environment
2. export

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

When I import the collection json to environment, then it can be exported, but with including the request too.
So it seems, from the `export` feature, you didn't consider export environment only from environment side yet.

### Insomnia Version

9.3.1

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### Installation method

download from insomnia.rest

**Comment by subnetmarco** [comment]
Prioritizing for 9.3.2 this week.
