### ISSUE TITLE
Deserialize error on deleting an environment

### ISSUE THREAD

**Issue by XavierFronius** [getinsomnia/insomnia#7630]
### Expected Behavior

I would like to be able to delete an environment.

### Actual Behavior

There is an error when I try to delete an environment.

![image](https://github.com/Kong/insomnia/assets/162583192/e5185f2f-20d5-44e5-a881-66e500e38d34)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.19045

### Installation method

download from insomnia.rest

**Comment by subnetmarco** [comment]
Prioritizing for 9.3.2 this week.

**Comment by jackkav** [comment]
Looks like https://github.com/nodejs/node/issues/29481 
👀

**Comment by subnetmarco** [comment]
Insomnia v9.3.2 [has been released](https://github.com/Kong/insomnia/releases/tag/core%409.3.2) fixing this issue.

**Comment by XavierFronius** [comment]
With the 9.3.2 version, there is always a deserialization error at the creation of an environment.
![image](https://github.com/Kong/insomnia/assets/162583192/d213092d-0057-4b87-950f-3fcff83044a5)
And also at the deletion
![image](https://github.com/Kong/insomnia/assets/162583192/5a742105-976b-4282-bc61-6f966f998e0e)

**Comment by notjaywu** [comment]
@XavierFronius Upgrading to v9.3.2 wouldn't fix this issue automatically if it had happened already before upgrading.

You can do the following:
1. `Help` -> `Show App Data Folder`
2. Go to `.\version-control\projects\prj_77d4bde23194a748a4821ad14945ead`
3. There should be a `meta.json.{uuid}.tmp` file
    3.1. Delete the file `meta.json`
    3.2. Rename `meta.json.{uuid}.tmp` to `meta.json`

This issue should be fixed, please let us know if it happens again.

**Comment by NosMaisons** [comment]
version 10.3.0
After moved (duplicate) a collection to another projet folder, I got error when trying to delete the old collection 
![image](https://github.com/user-attachments/assets/f8204904-d8c2-45db-9637-4cf134a59f12)

**Comment by ngoclentq** [comment]
> [@XavierFronius](https://github.com/XavierFronius) Upgrading to v9.3.2 wouldn't fix this issue automatically if it had happened already before upgrading.
> 
> You can do the following:
> 
> 1. `Help` -> `Show App Data Folder`
> 2. Go to `.\version-control\projects\prj_77d4bde23194a748a4821ad14945ead`
> 3. There should be a `meta.json.{uuid}.tmp` file
>    3.1. Delete the file `meta.json`
>    3.2. Rename `meta.json.{uuid}.tmp` to `meta.json`
> 
> This issue should be fixed, please let us know if it happens again.

Thanks, That helps fix my issue
