### ISSUE TITLE
Problem updating fields in Multipart Form Data update version 9.3.1

### ISSUE THREAD

**Issue by ragepro** [getinsomnia/insomnia#7633]
### Expected Behavior

When we click to access the field it takes a while to access, we update the data, but when we exit it keeps the previous values, if we enter again the new values ​​are there, when exiting the previous values ​​return

https://github.com/Kong/insomnia/assets/24938967/ad3ada86-6760-4865-b57c-ba8b9e44efbf

![image](https://github.com/Kong/insomnia/assets/24938967/dcf00cb5-5f55-45e8-a1d3-e8466605d5a5)

### Actual Behavior

When we click to access the field it takes a while to access, we update the data, but when we exit it keeps the previous values, if we enter again the new values ​​are there, when exiting the previous values ​​return

### Reproduction Steps

I attached the video

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I attached the video

### Insomnia Version

9.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2 ORIGINAL

### Installation method

site oficial

### Last Known Working Insomnia version

prior to update 9.3.1

**Comment by subnetmarco** [comment]
Prioritizing for 9.3.2 this week.

**Comment by subnetmarco** [comment]
Insomnia v9.3.2 [has been released](https://github.com/Kong/insomnia/releases/tag/core%409.3.2) fixing this issue.
