### ISSUE TITLE
Manage Environment option is missing under folders

### ISSUE THREAD

**Issue by petergummerunifii** [getinsomnia/insomnia#7634]
### Expected Behavior

In the menu for each folder, there used to be an option to manage its environment.

### Actual Behavior

This option has disappeared in 9.3.1.
Despite that the option is not visible anymore, I can tell that the environment that I have set up in an earlier version of insomnia is still working (i.e., variables that I set up there to override the request URL are still working). I just can't make any modifications anymore, because the environment option is gone.

### Reproduction Steps

1. Click on the down arrow for a folder.
2. Look for the option to manage the folder's environment: it's not there!

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Automatic update

### Last Known Working Insomnia version

9.2.0

**Comment by subnetmarco** [comment]
If you click on a folder, you can see it here:

![Screenshot 2024-07-02 at 10 31 05 AM](https://github.com/Kong/insomnia/assets/964813/a9bcdf07-cac5-4882-9dab-33b27fc6c78a)

Is this what you are referring to?

**Comment by petergummerunifii** [comment]
Thanks Marco, that's what I've been looking for all day. So you have moved it? I missed any mention of that change in the release notes.

**Comment by subnetmarco** [comment]
Yes we added folder-level auth, scripting, headers, docs and environment in a new section when clicking on the folder.
