### ISSUE TITLE
Pre-request script in folder level doesn't work when the request's pre-request script is empty

### ISSUE THREAD

**Issue by ShakedAharonn** [getinsomnia/insomnia#7637]
### Expected Behavior

editing the insomnia.request.auth as described in the docs, on the folder level pre-request script, should modify the auth of the sent request

### Actual Behavior

simply having pre-request script in the folder level isn't enough, and the request isn't updated unless the request itself also has a pre-request script (even if a dummy one)

### Reproduction Steps

1st attempt - create a folder level pre request script to modify the request.auth, and in the inner request rely on this change - this will fail.
2nd attempt - add a simple statement (e.g x=4) to the request's pre-request script, while leaving the folder level script as is - this will work

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.1

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### Installation method

download from insomnia rest

**Comment by subnetmarco** [comment]
Prioritizing for 9.3.2 this week.

**Comment by wallace-camarinha** [comment]
It also happens for headers, query params, anything in the folder level pre-request script.
You don't even need a dummy script in the request itself, just a whitespace makes it work

**Comment by subnetmarco** [comment]
@ihexxa ^

**Comment by ihexxa** [comment]
Hello @wallace-camarinha ,  ah sorry I don't understand what do you mean "also happens to headers and so on"? Could you elaborate a bit?

**Comment by wallace-camarinha** [comment]
What I meant is the problem didn't happen only when editing `insomnia.request.auth`, but also didn't work when editing

**Comment by ihexxa** [comment]
Closing this issue, headers, query params will also be enabled in parents' scripts.
It will be released in the next minor update.
