### ISSUE TITLE
Non-Active/Non-Selected Query Params not greyed out

### ISSUE THREAD

**Issue by R-Oakley** [getinsomnia/insomnia#7642]
### Expected Behavior

Prior to the 9.3.0 release the query params that were not active or selected in the list were greyed out. This made for a simple UX in knowing exactly which ones were selected and which were not. 

### Actual Behavior

Now since 9.3.0 all query params just show the same whether they are selected or not. The only indication is a tiny checkmark. This makes it extremely cumbersome for anyone who might have repeated query params saved that they can turn off and on instead of typing out new values all the time. 

![image](https://github.com/Kong/insomnia/assets/28991055/3ff17fc6-d9a5-466f-a8ae-cb623a5d1233)

### Reproduction Steps

Install version 9.3.x and this feature will no longer be available

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.1

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.4.1

### Installation method

Homebrew

### Last Known Working Insomnia version

9.2.0

**Comment by subnetmarco** [comment]
I believe this has already been fixed in `main` by @gatzjames and will be released in 9.3.2 this week.

**Comment by subnetmarco** [comment]
Insomnia v9.3.2 [has been released](https://github.com/Kong/insomnia/releases/tag/core%409.3.2) fixing this issue.
