### ISSUE TITLE
Cannot open highlighted folder in 9.3.1 release

### ISSUE THREAD

**Issue by jamesgkong** [getinsomnia/insomnia#7652]
### Expected Behavior

Folder in a collection should collapse or expand as appropriate when clicking the folder icon, whether or not the folder is currently highlighted/selected.

### Actual Behavior

When a folder in a collection is highlighted/selected it is impossible to collapse or expand the folder.
![folder-open-issue](https://github.com/Kong/insomnia/assets/124253552/98e3fa6f-31e8-44b0-b29c-83083aab8961)

Issue seems to have started with 9.3.1 release

### Reproduction Steps

1. Create Collection
2. Add several folders
3. Highlight a specific folder then try to expand / collapse it

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.1

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### Installation method

.DMG file from Download page

**Comment by filfreire** [comment]
@jamesgkong this will be fixed in 9.3.2

Was fixed in PR https://github.com/Kong/insomnia/pull/7639

**Comment by subnetmarco** [comment]
Shipping this week in 9.3.2
