### ISSUE TITLE
Projects keep reverting to Cloud Sync

### ISSUE THREAD

**Issue by davidnorrishill** [getinsomnia/insomnia#7653]
### Expected Behavior

When I create a project and select Local Vault I would expect that project to remain a Local Vault.

### Actual Behavior

I create a new project and select Local Vault and click on Create. When I open the the project settings again its showing as a Clouc Sync:

Create new Project:
![image](https://github.com/Kong/insomnia/assets/64267052/1cf2c480-c331-4c43-8f93-13c9b62ac5ec)

Project type when opening Project settings:
![image](https://github.com/Kong/insomnia/assets/64267052/d94d7b2e-8b82-4587-9a70-5eb919f81615)

### Reproduction Steps

1. Create a new project
2. Select Local Vault
3. Click Create
4. Select project Settings
5. Project type is now Cloud Sync

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro Version 23H2

### Installation method

Chocolatey

**Comment by subnetmarco** [comment]
Your project is still local vault if you see this icon next to it:

![Screenshot 2024-07-03 at 3 55 44 PM](https://github.com/Kong/insomnia/assets/964813/9ce06fe2-47e5-4fa5-a4a0-81bb9e19307f)

This seems to be a UI enhancement request: today in the project settings we focus on the first option (Cloud Sync) always, even if the project itself is Local Vault. As such, we will make an improvement to make sure that the selection stays on local vault if the project is local indeed. This is simple to fix and we may ship an improvement this week in 9.3.2

**Comment by davidnorrishill** [comment]
Great thanks for the update...
