### ISSUE TITLE
Folders do not expand and do not allow access to their contents

### ISSUE THREAD

**Issue by StereoSoda** [getinsomnia/insomnia#7659]
### Expected Behavior

Folders that expand to access their contents

### Actual Behavior

When I click on a folder, nothing happens

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

Download from insomnia web

**Comment by DusanLesan** [comment]
I have experienced that as well, but it was inconsistent. Today, I figured out why it happens for me:

- If you click on the folder name, the focus indicator will be given to the folder, but it will not open. As long as the focus is on the collapsed folder, I cannot expand it.
- If you avoid clicking on request names, it will open as expected.

Video of the issue:

https://github.com/Kong/insomnia/assets/20520590/97926508-f76f-4b93-9640-2277a4e09e8d

**Comment by StereoSoda** [comment]
> I have experienced that as well, but it was inconsistent. Today, I figured out why it happens for me:
> 
> * If you click on the folder name, the focus indicator will be given to the folder, but it will not open. As long as the focus is on the collapsed folder, I cannot expand it.
> * If you avoid clicking on request names, it will open as expected.
> 
> Video of the issue:
> 
>  output.mp4

This worked for me, however it should be able to expand and collapse from the name 😊

**Thanks!!**

**Comment by wandersonsousa** [comment]
> I have experienced that as well, but it was inconsistent. Today, I figured out why it happens for me:
> 
> * If you click on the folder name, the focus indicator will be given to the folder, but it will not open. As long as the focus is on the collapsed folder, I cannot expand it.
> * If you avoid clicking on request names, it will open as expected.
> 
> Video of the issue:
> 
>  output.mp4

What terrify bug

**Comment by gatzjames** [comment]
Thanks for the feedback everyone. This is now fixed in the latest beta and will be released in the coming patch version!
