### ISSUE TITLE
[Feature Request] Keep Json-Path on Request

### ISSUE THREAD

**Issue by SiNEXiST** [getinsomnia/insomnia#766]
- Insomnia Version: 5.14.17

## Details

Currently the Json-Path that can be used at the bottom of the Response tab is static over all Responses/Requests. This is quite troublesome for my testing because I have to use multiple requests and see their output.
Filtering it with the Json-Path is really convenient as it filters out the content I don't need, but it applies to every response. When you switch between requests which have different response-formats, you'll always have to re-write the Path for each format since it's the same for all.

## Proposal

Each Request should store the Json-Path on it's own, rather than saving it globally.

**Comment by gschier** [comment]
This is currently a UI bug that was introduced in the latest release. Will get this fixed this week.

**Comment by SiNEXiST** [comment]
Ah, didn't see that. Well then, the Bug should be tracked in the corresponding Ticket and therefore this is getting closed
