### ISSUE TITLE
Headers keep resetting to previous saved value

### ISSUE THREAD

**Issue by mohit-kumar-bechtel** [getinsomnia/insomnia#7663]
### Expected Behavior

If I'm updating the "headers" values for saved headers, it should keep that value while switching between tabs and while sending the requests, it should use the updated value in headers and not the last saved value.

### Actual Behavior

![image](https://github.com/Kong/insomnia/assets/99176125/541fb2cf-30d4-4321-8dd5-95608c95270c)

As soon I switch tab and come back to Headers
![image](https://github.com/Kong/insomnia/assets/99176125/f1bdc55f-8f5a-4fdc-913c-57b5dc7e4820)

Headers reset to previous value
![image](https://github.com/Kong/insomnia/assets/99176125/0bc7b444-31a8-4731-b3e5-49cf4947185b)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 9.3.1
Build date: 6/28/2024
OS: Windows_NT x64 10.0.22621
Electron: 30.0.9
Node: 20.11.1
Node ABI: 123
V8: 12.4.254.20-electron.0
Architecture: x64

### Insomnia Version

9.3.1

### What operating system are you using?

Windows

### Operating System Version

WINDOWS_NT x64 10.0.22621

### Installation method

from insomnia.rest

**Comment by subnetmarco** [comment]
Insomnia v9.3.2 [has been released](https://github.com/Kong/insomnia/releases/tag/core%409.3.2) fixing this issue.
