### ISSUE TITLE
Folders only open and close when clicking folder and not name

### ISSUE THREAD

**Issue by R-Oakley** [getinsomnia/insomnia#7667]
### Expected Behavior

Previous to 9.3 update I am sure you could expand/collapse folder you could do so by clicking the folder name or the folder icon. When 9.3.0 release this was broken. 

### Actual Behavior

This was fixed in 9.3.2 but now you can only expand/collapse by clicking on the folder icon and not the folder name 

### Reproduction Steps

Click on folder icon and see collapse/expand

Click on folder name and nothing happens

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I'm not sure if this was intentional or just an oversight in the bug fix. It was a big quality of life thing to just be able to click the folder name. If this was intentional to make it only the Icon itself then it is what it is I guess. At least it's fixed from 9.3.1 which I am thankful for

### Insomnia Version

9.3.2

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### Installation method

Homebrew

### Last Known Working Insomnia version

9.2.0

**Comment by wandersonsousa** [comment]
Not even click in home icon its working for me, sometimes click above the collapse icon work, sometimes dont

**Comment by mrohlof-protofy** [comment]
Drag and Drop also works only for the Padding-Area around the name and the icon. It does work for requests on the icon, though. My guess would be that the whole event handling is broken in some way and elements can only have one event handler: The folder name has a double click handler to change the name. The folder icon has a single click handler to open / close. The whole folder element has a mouse down handler to drag and drop, which is prevented by icon / name handlers.

**Comment by subnetmarco** [comment]
Is this issue currently describing this problem? https://www.loom.com/share/173759bbc027456bb5449d6a1c9b3373
