### ISSUE TITLE
OAuth request no longer made with a default User Agent

### ISSUE THREAD

**Issue by ocasta** [getinsomnia/insomnia#7672]
### Expected Behavior

A request is made to the token endpoint with a User Agent

### Actual Behavior

Fails to authenticate with the OAuth server (403 error)

The token request is being made without a User Agent. Without a user agent the request is rejected by our WAF. This is an issue that was fixed about a year ago in https://github.com/Kong/insomnia/issues/6425

### Reproduction Steps

Existing request that worked with 9.3.1
Auth settings
OAuth 2.0
Grant Type: Resource Owner Password Credentials
Credentials - Basic Auth

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.2

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### Installation method

Upgrade

### Last Known Working Insomnia version

9.3.1

**Comment by subnetmarco** [comment]
What's the status of this option in your Preferences? 

![Screenshot 2024-07-06 at 9 28 47 AM](https://github.com/Kong/insomnia/assets/964813/a94002a3-5a76-4546-a692-22bc813802ab)

**Comment by ocasta** [comment]
Unchecked
The Auth works in 9.3.1 but not 9.3.2

**Comment by filfreire** [comment]
@ocasta fix for this will be available in the next patch release
