### ISSUE TITLE
imported environment is empty

### ISSUE THREAD

**Issue by AndreaZari1** [getinsomnia/insomnia#7680]
### Expected Behavior

I expect to import an environment and see all the requests inside of it

### Actual Behavior

when i import it, insomnia says that the import went well and creates the collection but it is empty

### Reproduction Steps

open insomnia
click 'import' on the right
select the json file
click 'import'
click on the collection that appeared
it is empty

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

i have seen other similar problems but i can't find a solution that works.

I used insomnia last year on an other PC of mine and it used to work. I don't know what I'm dooing wrong right now.

these are the steps that i take:

![image](https://github.com/Kong/insomnia/assets/174119937/9c0cd614-2d50-4566-848a-ac86f9c86376)
![image](https://github.com/Kong/insomnia/assets/174119937/f8f52cbe-0e7a-4519-8bb4-0d4f27530d8d)
![image](https://github.com/Kong/insomnia/assets/174119937/97505feb-ea90-4968-ae87-d2c50fa01358)
![image](https://github.com/Kong/insomnia/assets/174119937/47d878f8-16b9-4a97-9966-87ec2a65f565)

### Insomnia Version

insomnia V9.3.2

### What operating system are you using?

Windows

### Operating System Version

windows 10

### Installation method

i just downloaded the latest verison from the official site

**Comment by gatzjames** [comment]
Hi @AndreaZari1 it looks like you have hidden your sidebar and response panels.
Could it be that you need to expand them and import works as expected?

**Comment by AndreaZari1** [comment]
Yes, i managed to find it under View -> toggle sidebar.
It was disabled by default, i had just installed insomnia

**Comment by gatzjames** [comment]
Thanks closing this issue then!
