### ISSUE TITLE
Environment is not showing for Folder on latest release

### ISSUE THREAD

**Issue by LeeBear35** [getinsomnia/insomnia#7684]
### Expected Behavior

Trying to update the environment for a folder and there is not option.
![image](https://github.com/Kong/insomnia/assets/11964590/4e170235-19ca-4815-b3c0-c061bd7bfe11)

### Actual Behavior

Nothing is showing for Environment

### Reproduction Steps

right click on folder...option is not present

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

n/a

### Insomnia Version

9.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Download

**Comment by subnetmarco** [comment]
If you click on the folder (like you would do for a request), do you see this section?

![Screenshot 2024-07-10 at 4 00 38 PM](https://github.com/Kong/insomnia/assets/964813/c08c4e10-7f8a-42bf-a0c7-a3975ef947db)

**Comment by gatzjames** [comment]
Closing as the environment for folders can be found in the folder view
