### ISSUE TITLE
No "minimize" or "close" button on windows

### ISSUE THREAD

**Issue by waterlx** [getinsomnia/insomnia#7687]
### Expected Behavior

1. No button for "minimize" or "close" on the top-right.
2. The windows taskbar is also covered by the whole insomnia application window

My env:
- Version: Insomnia 9.3.2
- Build date: 2024/7/4
- OS: Windows_NT x64 10.0.22631
- Electron: 30.0.9
- Node: 20.11.1
- Node ABI: 123
- V8: 12.4.254.20-electron.0
- Architecture: x64

### Actual Behavior

Have buttons for "minimize" or "close". And the windows taskbar is not covered

### Reproduction Steps

Just open the application

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

N.A.

### Insomnia Version

9.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Windows_NT x64 10.0.22631

### Installation method

Downloaded from https://objects.githubusercontent.com/github-production-release-asset-2e65be/56899284/9e053183-93a1-4d8c-8b0e-084a7dfd53c1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240710%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240710T031456Z&X-Amz-Expires=300&X-Amz-Signature=5e39c0d55d0367f8dd57bf24abb91634f66cfec324a0f31d4d8392ec5885f9cc&X-Amz-SignedHeaders=host&actor_id=13976495&key_id=0&repo_id=56899284&response-content-disposition=attachment%3B%20filename%3DInsomnia.Core-9.3.2.exe&response-content-type=application%2Foctet-stream

### Last Known Working Insomnia version

N.A.

**Comment by notjaywu** [comment]
@waterlx Can you check if these view options help? It may be in the `Full Screen` mode.

<img width="463" alt="Screenshot 2024-07-23 at 09 40 52" src="https://github.com/user-attachments/assets/a1857d2e-5b72-4bf6-b4b1-8d05ca2feef4">

**Comment by waterlx** [comment]
@notjaywu My bad, I clicked "Toggle Full Screen" somehow. I will close this ticket. Thanks!
