### ISSUE TITLE
OAuth2.0 - New Response missing 'parentId' (failed to generate token)

### ISSUE THREAD

**Issue by MarxoSvk** [getinsomnia/insomnia#7689]
### Expected Behavior

Using OAuth2.0 after clicking Fetch Tokens button I should get new auth token

### Actual Behavior

Using OAuth2.0 after clicking Fetch Tokens button I will get error "New Response missing 'parentId'". No token will be generated.

### Reproduction Steps

1. Go to Auth tab and select OAuth2.0 (folder or request level)
2. Grant type: Authorization Code; provided Auth URL; Auth Token URL; client ID; Use PKCE checked; Code Challenge method: SHA-256; provided redirect URL; scope; credentials: In Request Body; Header prefix: Bearer 
3. click Fetch Tokens button

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

on version 9.3.1 same setup is working. Tried with and without plugins enabled = same result. 

### Insomnia Version

9.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

installer from insomnia webpage

### Last Known Working Insomnia version

9.3.1

**Comment by gatzjames** [comment]
Hi @MarxoSvk I've tried to reproduce the issue but fetch tokens and refresh tokens works as expected for me.
I've also tried to manipulate the request with the new scripting feature and couldn't reproduce.
Could you provide more context?

**Comment by MarxoSvk** [comment]
I have dug deeper, issue was because of plugin OAuth2 Token Provider (which was throwing error in console with missing parentId) but even after disabling it, it somehow was throwing same error (restart of insomnia helped with this) 
-> after which I have had different error with 403 from redirected callback URL. But this was fixed with 9.3.3-beta.1 version. 

Thanks for all the effort. I am closing ticket.
