### ISSUE TITLE
Last edited parameter is not saved when sending requests

### ISSUE THREAD

**Issue by DusanLesan** [getinsomnia/insomnia#7693]
### Expected Behavior

Whenever I send a request, it should include all the values I set before sending it

### Actual Behavior

If I am editing a parameter value and send the request, the request is sent with the old value, and the new value is reverted

### Reproduction Steps

1. Go to query parameters of a request
2. Edit one query parameter value
3. Hit ctrl+enter

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The value appears to be saved if the input looses focus before sending a request

https://github.com/Kong/insomnia/assets/20520590/eebc124e-f96e-421c-9b2d-a39d102d966d

### Insomnia Version

9.3.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux arch 6.9.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 05 Jul 2024 22:11:24 +0000 x86_64 GNU/Linux

### Installation method

AUR

**Comment by jabrown93** [comment]
Also seeing this on macOS 14.5 on both 9.3.2 and 9.3.1, ended up going back to 9.2.0 and it works there. If I hit enter after modifying the param and them cmd+entry, the edit is saved and works as expected

**Comment by RestfuI** [comment]
Bump, this is also happening on Windows, if it isn't fixed shortly I'll be moving back to Postman.

**Comment by subnetmarco** [comment]
We are looking into this for 9.3.3

**Comment by khanifikhsanudin** [comment]
I'm still facing this issue on MacOS Insomnia v9.3.3-beta.1 😢

**Comment by subnetmarco** [comment]
We are still working on it and it will be available in a subsequent beta for 9.3.3 - I believe there is already a PR open.

**Comment by gatzjames** [comment]
Thanks for the feedback everyone. This is now fixed in the latest beta and will be released in the coming patch version!
