### ISSUE TITLE
Recently changed varable in header or parameter values is reverted after sending a request

### ISSUE THREAD

**Issue by DusanLesan** [getinsomnia/insomnia#7696]
### Expected Behavior

Whenever I make a request, I would expect for it to be sent with the visible info

### Actual Behavior

If I replace a variable I am using for my query/header value, it will not be applied for the next request. Even clicking around sometimes do not make new variable to stick and it is reverted when sending

### Reproduction Steps

1. Go to query parameters for a request
2. Replace one existing variable with another
3. Send request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

https://github.com/Kong/insomnia/assets/20520590/476cbf6c-57b1-4779-9b30-61822c7d0c7a

Additional issue I've seen is that opening variables now requires two clicks: first click fails and the box flickers and only the second click is working. Should I make additional issue for that?

### Insomnia Version

9.3.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux arch 6.9.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 05 Jul 2024 22:11:24 +0000 x86_64 GNU/Linux

### Installation method

AUR

**Comment by AdivonSlav** [comment]
Can confirm I have the same issue on a Fedora 40 KDE installation. Running Insomnia 9.3.2 on Wayland

**Comment by gatzjames** [comment]
Thanks for the feedback @DusanLesan and @AdivonSlav. This is now fixed in the latest beta and will be released in the coming patch version!

**Comment by DusanLesan** [comment]
@gatzjames Thanks!

**Comment by DusanLesan** [comment]
@gatzjames Is this fixing additional issue mentioned?

> Additional issue I've seen is that opening variables now requires two clicks: first click fails and the box flickers and only the second click is working. Should I make additional issue for that?
