### ISSUE TITLE
All Saved Requests lost

### ISSUE THREAD

**Issue by bschnitz** [getinsomnia/insomnia#7699]
### Expected Behavior

After opening Insomnia all Request show up.

### Actual Behavior

After opening, Insomnia requests to login using one of several methods. Since I only want to work locally I choose "Use the local Scratchpad". This is empty.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.1

### What operating system are you using?

Other Linux

### Operating System Version

5.15.161-1-MANJARO

### Installation method

pacman

**Comment by opalenet-adrien** [comment]
I'm just encountering the same issue after an auto-update to the 9.3.1. All my professional requests are lost. I also work locally, on Pop!_OS 22.04, with the Flatpak installation.

**Comment by bschnitz** [comment]
@opalenet-adrien It seems like Insomnia changed it's path a bit. Fortunately I found an export button somewhere, with which I was able to export the old request data. After that, it can be imported to an alternative client (like e.g. https://github.com/ArchGPT/insomnium).

**Comment by opalenet-adrien** [comment]
@bschnitz through the export feature in "preferences" menu, that shows me empty data. In downgrading to a previous version, all the collections and requests returned, so I tried to do the exports but the app is buggy (only one collection export worked, now the app shuts down each time I try to export the others...). Thank you for the alternative, I'm gonna try it :+1:

**Comment by bschnitz** [comment]
@opalenet-adrien There are many alternatives. But insomnia and insomnium seem to offer many auth types out of the box, where other alternatives are lacking implementation. I think in the future I will move to httpie.

**Comment by opalenet-adrien** [comment]
On the version 9.3.1, I found my old collection here (see the screenshot). But we have to create an organization (and an account) to be able to retrieve our own data. And the "export all data (19 files)" that I assume containing my data doesn't work: it asks for a folder then confirms that all data are successfully exported but the folder remains empty...
So this isn't possible to work locally unless scraping all data... Thanks to Insomnia!
![image](https://github.com/Kong/insomnia/assets/64809293/86333fc0-77dc-4ae9-bef6-8d8ebbf959f0)

So, @bschnitz thanks again for the alternatives. After all these years, it's time to move on!

**Comment by bschnitz** [comment]
@opalenet-adrien Ouch, I feel for You. I had more Luck ...

**Comment by subnetmarco** [comment]
@bschnitz from what version did you update from?

All the projects, collections and other data is available both locally or in the cloud **while logged in**. The Scratch Pad allows to use Insomnia without an account and local-only for people that need a "visual curl". The collection management is available after logging in.

This is Scratch Pad:

![Screenshot 2024-07-11 at 9 48 12 AM](https://github.com/Kong/insomnia/assets/964813/12d9dd56-6dd3-48a5-a354-40097d7a125f)

This is the view after logging in:

![Screenshot 2024-07-11 at 9 48 48 AM](https://github.com/Kong/insomnia/assets/964813/c6b0cb35-b4a5-484e-b391-eb77f9d911c2)

After logging in, you can choose which projects are cloud, local or choose a mix of both based on your use-case. For example in the following screenshot the "Hobby" project is 100% local, while the "ACME Cloud" project is using Cloud Sync:

![Screenshot 2024-07-11 at 9 51 16 AM](https://github.com/Kong/insomnia/assets/964813/eb0d1d13-ef55-4223-bdcf-5b2d790704c3)

**Comment by subnetmarco** [comment]
> So this isn't possible to work locally unless scraping all data...

@opalenet-adrien It is possible to work locally and data is not being "scraped" if you choose to keep you 100% local storage. Having an account does not determine where your data lives, as described in my comment above.

Even when using Cloud Sync, if your have E2EE enabled, the data is end-to-end encrypted and it is not possible for anyone but you to decrypt it.

**Comment by bschnitz** [comment]
@subnetmarco Hi, thank You for your reply. I prefer not to be logged in. Also I cannot tell You the version I had before 9.3.1. I found a solution, so everything is all right for me. I hope you can help @opalenet-adrien though.

**Comment by subnetmarco** [comment]
@bschnitz 👍

@opalenet-adrien you can export the data by going to Scratch Pad, and from Scratch Pad you can open the "Preferences" and see the data to export. 

There is a bug that I already planned to release in the next minor: the "Data" section of the "Preferences" dialog doesn't load properly if it's being opened from the login dialog. Opening "Preferences" from the Scratch Pad seems to be working instead.

This is most likely a regression introduced in 9.3.2 when we worked on making the proxy settings more identifiable in the login dialog. Already fixed in https://github.com/Kong/insomnia/pull/7702.

**Comment by opalenet-adrien** [comment]
@subnetmarco thank you for your reply. As @bschnitz, I prefer not to be logged in. So, I just want to get my data even if they're not organized as collection anymore. But I don't understand why a solid, smooth migration process hasn't been done between the two versions. I waste my work time since yesterday trying to recover them.

Anyway, about the "Preferences" from the Scratch Pad screen, this doesn't work too. Like explained in my previous comment. Here a screencast.
[Screencast 2024-07-11 11:56:35.webm](https://github.com/Kong/insomnia/assets/64809293/fc3097f6-61dd-411a-ac66-4d979e81d73e)

**Comment by subnetmarco** [comment]
@opalenet-adrien thanks for the screencast, let us look into this. I cannot replicate on MacOS but perhaps it's a problem specific to Linux.

**Comment by MarcGoekce** [comment]
> @subnetmarco thank you for your reply. As @bschnitz, I prefer not to be logged in. So, I just want to get my data even if they're not organized as collection anymore. But I don't understand why a solid, smooth migration process hasn't been done between the two versions. I waste my work time since yesterday trying to recover them.
> 
> Anyway, about the "Preferences" from the Scratch Pad screen, this doesn't work too. Like explained in my previous comment. Here a screencast. [Screencast 2024-07-11 11:56:35.webm](https://github.com/Kong/insomnia/assets/64809293/fc3097f6-61dd-411a-ac66-4d979e81d73e)

Same here. Guess this is the end of another great tool, gone to misery and greed,,,

**Comment by subnetmarco** [comment]
> Same here. Guess this is the end of another great tool, gone to misery and greed

@MarcGoekce how many contributions to Insomnia have you done over the years? Can't do nothing and expect everything.
