### ISSUE TITLE
[Bug] Json path not saving per request

### ISSUE THREAD

**Issue by Gabb1995** [getinsomnia/insomnia#772]
- Insomnia Version: 5.14.7
- Operating System: Ubuntu 17.10 - artful

JsonPath is saving globally for me not per request as was before, therefore if I set it to `$.class` it will show that across all the requests/environments. Before it used to save them per request.

**Comment by Gabb1995** [comment]
Related to #766

**Comment by gschier** [comment]
Forgot to close this. Was fixed in the last release.
