### ISSUE TITLE
Git Clone - Collection - Folder - Auth cannot be pulled from repo

### ISSUE THREAD

**Issue by hmundle** [getinsomnia/insomnia#7724]
### Expected Behavior

Inside of a company collaboration project, we created a "git clone" and inside of that a collection with a folder structure and inside of that some request. Everything works so far for the first user. If another user retrieves the same git repository in a git clone on his computer, it is expected, that everything look identical. Even the Auth tab of a folder.

### Actual Behavior

For another users the retrieved git repository shows up with broken "Auth" tab inside of the folders. Inside of the Auth tab the messages shows up: Render Failure: Cannot convert undefined or null to object
![image](https://github.com/user-attachments/assets/2dfa9dfc-8af7-4256-886a-3fa26d40091f)

If the Auth tab of the request is set to "Inherit from parent", which is the default, sending the request fails with an unhandled error: TypeError: Cannot convert undefined or null to object
![image](https://github.com/user-attachments/assets/7819414d-b726-429e-8b15-c6308c441d15)

Probably both is the same object with is set to null.

### Reproduction Steps

1. create new git clone
2. create a folder in a collection
3. create a request, Auth is supposed to inherit
4. commit to git
5. push to git
6. delete git clone from insomnia
7. create a git clone on same git repository potentially on another computer with another user
8. select the folder in collection
9. check the "Auth" tab, this will show an error message
10. send the request, and an error dialog pops up

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 9.3.2
Build date: 2024-07-04
OS: Windows_NT x64 10.0.19045
Electron: 30.0.9
Node: 20.11.1
Node ABI: 123
V8: 12.4.254.20-electron.0
Architecture: x64

### Insomnia Version

9.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise, 22H2, 19045.4651

### Installation method

downloaded installer

**Comment by subnetmarco** [comment]
We are looking into this, thanks for the report.

**Comment by gatzjames** [comment]
Hi @hmundle can you verify that the user that pulls the repo is using the latest version too?

**Comment by hmundle** [comment]
> Hi @hmundle can you verify that the user that pulls the repo is using the latest version too?

The user that pulls uses Insomnia 9.3.2 for sure, because that's me. We started using Insomnia recently with 9.3.0. Maybe some people pushing to git with version between 9.3.0 and 9.3.2 (inclusive).
