### ISSUE TITLE
Edit Tags Not Persisting

### ISSUE THREAD

**Issue by WandersonGSantos** [getinsomnia/insomnia#7726]
### Expected Behavior

When I add a new 'Edit Tag', it doesn't persist and remains empty. The same issue occurs when I update an existing 'Edit Tag'.

Now:
![image](https://github.com/user-attachments/assets/b2555ddb-996e-46ae-bc43-26b8e87bb13d)

When I try to update to a new token, it reverts to the previous token.
![image](https://github.com/user-attachments/assets/6b87c40b-d150-4573-a29e-896412933998)

Now I'm going to save by clicking done, and I'm going to hit the route and after opening the 'Edit Tag' again it went back to where it was first and hit it with the wrong token
![image](https://github.com/user-attachments/assets/3de6ed2a-9d53-4e21-aba9-d07f9bb958f0)

### Actual Behavior

Edit Tags Not Persisting

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2

### Installation method

Download from https://insomnia.rest/download

**Comment by gatzjames** [comment]
Thanks for the feedback @wandersonDeve. This is now fixed in the latest beta and will be released in the coming patch version!
