### ISSUE TITLE
[Feature Request] - Hotkey to lookup the actual values of all environment variables

### ISSUE THREAD

**Issue by meknil** [getinsomnia/insomnia#773]
I like to use Environment Variables where possible to reuse customized requests as much as possible.

I know that I can see the actual value of a environment-variable by hoovering the mouse over the placeholder, but sometimes, I like to get a quick overview of the actual values of all visible environment-variables at once by pressing a hotkey.

Ideally, this happens inline. Just replace in the placeholder the variable name by the actual value.

**Comment by gschier** [comment]
I like this idea.

**Comment by 4ekki** [comment]
Not sure whether this should be a separate improvement or enhancement of this one, but it would be very nice to have an ability to copy variable value to the clipboard. F.e., on right-clicking the tag.
