### ISSUE TITLE
Scrollbar UI not correctly displayed

### ISSUE THREAD

**Issue by lmorganl** [getinsomnia/insomnia#7732]
### Expected Behavior

Scroolbars UI are correct

### Actual Behavior

Scroolbars UI are not correct

9.3 -> 9.3.3-beta.1 
<img width="944" alt="Capture d’écran 2024-07-17 121514" src="https://github.com/user-attachments/assets/e0686a50-4e9f-4044-bdb1-bca993ca6ecb">
9.2
<img width="954" alt="Capture d’écran 2024-07-17 121016" src="https://github.com/user-attachments/assets/386eacb8-30b9-4d2e-ae2b-58c43e9510c9">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23h2

### Installation method

exe

### Last Known Working Insomnia version

9.3.2

**Comment by subnetmarco** [comment]
Thanks for the screenshots - I am asking the team to review this behavior.

**Comment by cesarribeirobdevima** [comment]
This might be related (or not), but when you pick a pre-existing request and then you click on a request's field to start editing, the scroll bar in the left (requests section) moves a bit in a way I can't see the highlighted request I'm editing anymore, I have to scroll back where it was - and this is very annoying.

```
Version: Insomnia 9.3.2
Build date: 7/4/2024
OS: Darwin arm64 23.5.0
Electron: 30.0.9
Node: 20.11.1
Node ABI: 123
V8: 12.4.254.20-electron.0
Architecture: arm64
```
