### ISSUE TITLE
Headers are not instantly updated

### ISSUE THREAD

**Issue by moetezch** [getinsomnia/insomnia#7733]
### Expected Behavior

A change in headers should be immediately reflected once clicking on send request 

### Actual Behavior

If clicked fast on the send request after changing headers the request is send with old values

### Reproduction Steps

1. GO insomnia 
2. Create a request that uses headers 
3. Send request 
4. quickly change the headers 
5. SEND again

https://github.com/user-attachments/assets/8e1dbd10-a5ae-43ce-b214-643fa270112f

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.2

### What operating system are you using?

macOS

### Operating System Version

14.5

### Installation method

insomnia.rest

**Comment by stevenchu31** [comment]
and if you try with `command + enter`, after updating the header. It will go back to the previous value.

**Comment by mwasif7** [comment]
I am also facing a similar issue. The timeline updates only on the second request, so if I do a GET request with changed parameters, I have to send it twice to get the correct data back.

I have already disabled cookies for the request for individual requests.

Insomnia Info:
Version: Insomnia 9.3.2
Build date: 04/07/2024
OS: Windows_NT x64 10.0.22631
Electron: 30.0.9
Node: 20.11.1
Node ABI: 123
V8: 12.4.254.20-electron.0
Architecture: x64

**Comment by camargosproj** [comment]
Facing the same issue after update!

Version: Insomnia 9.3.2
Build date: 7/4/2024
OS: Linux x64 6.9.3-76060903-generic
Electron: 30.0.9
Node: 20.11.1
Node ABI: 123
V8: 12.4.254.20-electron.0
Architecture: x64

**Comment by mwasif7** [comment]
@subnetmarco  can you please have a look at this issue?

**Comment by subnetmarco** [comment]
We are looking into this issue.

**Comment by gatzjames** [comment]
Thanks for the feedback everyone. This is now fixed in the latest beta and will be released in the coming patch version!
