### ISSUE TITLE
[Feature Request] Allow to chain multiple request

### ISSUE THREAD

**Issue by moduval** [getinsomnia/insomnia#774]
It would be useful to have a feature like PostMan's Runner feature. It would let us chained the execution of multiple request without having to manually run them.

**Comment by Xuanwo** [comment]
Any update for this feature? Support or not?

**Comment by gschier** [comment]
I'm definitely not against adding it but the demand is not very high relative to the technical complexity of the implementation. I'll mark it as _accepted_ so it doesn't get close.

Note: the tricky part is updating the tag editor and plugin API to support a dynamic amount of inputs. A hacky implementation would be to only support a fixed number (say 5) and, since the tag editor supports hiding inputs, only show the next input if the previous has been filled.

**Comment by gschier** [comment]
This should be possible via the plugin system sometime in the future. Will leave it open until then

**Comment by loopion** [comment]
+1

Really interested as well!

**Comment by mornindew** [comment]
This would be a very interesting feature for me too!

+1

**Comment by gabokr** [comment]
another vote for useful feature! I'd like to execute all request stored in a folder, top down, in sequence.

**Comment by MatijaTeamFocus** [comment]
Extremely usefull feature!!!

**Comment by ljuba95** [comment]
+1
Would make API testing much easier!

**Comment by stefanik95** [comment]
+1
Very interesting and useful feature!

**Comment by IvaJovicic** [comment]
> Useful feature!
 +1

**Comment by gschier** [comment]
It wouldn't be possible to implement a plugin for this quite yet. There's no way for plugins to trigger sending of requests. In general, Insomnia isn't currently meant for tasks that require automation, which is why it does not yet exist.

**Comment by gschier** [comment]
That said, if someone wants to take a look at making the Response Template Tag resend the dependent requests, that would be awesome!

**Comment by serkand** [comment]
+1 

Absolutely critical to have in any API testing tool and not just for test automation.

**Comment by yozlet** [comment]
@gschier Now that the Response Template tag is resending dependent requests (#1470 - thank you for that!), what's the next step here?

**Comment by gschier** [comment]
Just added the ability to define folder actions within plugins.

![image](https://user-images.githubusercontent.com/587576/57184533-b738b580-6e8a-11e9-8e28-f4e05f7ffcad.png)

Wrote a quick plugin to test if it works:

```js
module.exports.requestGroupActions = [
  {
    label: 'Send Requests',
    action: async (context, data) => {
      const { requests } = data;

      let results = [];
      for (const request of requests) {
        const response = await context.network.sendRequest(request);
        results.push(`<li>${request.name}: ${response.statusCode}</li>`);
      }

      const html = `<ul>${results.join('\n')}</ul>`;

      context.app.showGenericModalDialog('Results', { html });
    },
  },
];
```

This ability will be live in the next release

**Comment by gschier** [comment]
Here's a link to the docs: https://support.insomnia.rest/article/26-plugins#folder-actions
