### ISSUE TITLE
encryption bug setup E2EE 

### ISSUE THREAD

**Issue by tomermaz** [getinsomnia/insomnia#7749]
<img width="479" alt="Screen Shot 2024-07-23 at 15 14 43" src="https://github.com/user-attachments/assets/5b6e234f-8c3e-448e-b76a-3d6d15eecf13">
### Expected Behavior

encryption bug, Enable E2EE modal has bug 
![Screen Shot 2024-07-23 at 15 08 35](https://github.com/user-attachments/assets/1e675a0c-3886-436f-9ca9-9f24bf125d0a)

### Actual Behavior

always getting error 
![Screen Shot 2024-07-23 at 15 08 35](https://github.com/user-attachments/assets/19e46841-699b-4570-a8f6-3e71744a7c3e)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

latest

### What operating system are you using?

macOS

### Operating System Version

mac 

### Installation method

browser

**Comment by marckong** [comment]
@tomermaz can you DM me with your email that you used to create an account through our Slack channel? https://getinsomnia.slack.com/

**Comment by notjaywu** [comment]
it may relate to #7401

**Comment by subnetmarco** [comment]
@tomermaz We believe we resolved this issue, can you try again?
