### ISSUE TITLE
Base enviroment not working between different operating-systems

### ISSUE THREAD

**Issue by SkonWodrich** [getinsomnia/insomnia#7750]
### Expected Behavior

I could save a collection in e.g. Linux, chekc it out on a windows desktop and use the pushed and local "enviroments".

### Actual Behavior

i check out a collection (on windows 10) that was created on linux. Everytime i try a request i get: 
![image](https://github.com/user-attachments/assets/3db770f3-5afb-4697-b30d-a20c8781af0f)
When  i click on a folder in the collection i get: 
![image](https://github.com/user-attachments/assets/fe050872-0e82-4328-8f31-7e46dd1f2ba5)

This works both ways. When i push the collection from a windows machine it does not work on linux. It worked perfect in the Version before v9.3.2 

### Reproduction Steps

1. Create a new Branch (on a linux machine)
2. Use Insomnia to push a collection to this branch
3. Check out the collection on a windows machine
4. Try a request from this collection. 
5. You get this error: 
![image](https://github.com/user-attachments/assets/3db770f3-5afb-4697-b30d-a20c8781af0f)

This works both ways. When i push the collection from a windows machine it does not work on linux. It worked perfect in the Version before v9.3.2 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 and Ubuntu Linux

### Installation method

insomnia website executable

**Comment by subnetmarco** [comment]
We are looking into this. + @gatzjames

**Comment by gatzjames** [comment]
Hi @SkonWodrich thanks for the feedback!
This has been fixed and will be available in the next patch release

**Comment by SkonWodrich** [comment]
@gatzjames  great work! do we have a relasedate?

**Comment by subnetmarco** [comment]
Early August, perhaps first week of August.
