### ISSUE TITLE
Can generate the token but it showed signal timed out after log in button was pressed 

### ISSUE THREAD

**Issue by Kimdl5** [getinsomnia/insomnia#7753]
### Expected Behavior

I used passphrase to log in and it showed
"You are successfully authenticated. You can click Launch button or manually enter the token." and I hope I can launch the Insomnia

### Actual Behavior

I tried to click Launch button and also tried manually enter token. It will go back to authorizing Insomnia and tried to log in but it showed signal time out 
![Issue](https://github.com/user-attachments/assets/c6a745c7-f5af-41e4-a471-4fa19a637010)

### Reproduction Steps

1. Launch Insomnia
2. Click Continue with SSO
3. Was led to log in page 
4. Enter my passphrase 
5. Click manually enter token 
6. Go back to Insomnia and enter my token and click log in 
7. It show signal timed out 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 9.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

download from website

### Last Known Working Insomnia version

9.2.0

**Comment by notjaywu** [comment]
@Kimdl5 Can you join this Slack channel https://chat.insomnia.rest? I will DM you for more information.

**Comment by notjaywu** [comment]
If any more log-in issues, please post to #7358. Close.
