### ISSUE TITLE
Request panel scroll position moves to bottom of request folder when sending or editing requests

### ISSUE THREAD

**Issue by JoeyBoolean** [getinsomnia/insomnia#7760]
### Expected Behavior

The scroll position should not move on the request panel unless I scroll

### Actual Behavior

The scroll position appears to move to the bottom of the open folder the request is in
![insomnia_scroll_issue](https://github.com/user-attachments/assets/0bef3f11-5d42-45f5-86b1-cf147fa7b9f1)

### Reproduction Steps

1. Select a request from the side panel
2. Hit send or edit the request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This appears to be the sames as this issue but for HTTP requests
https://github.com/Kong/insomnia/issues/7606

### Insomnia Version

9.3.2

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma Version 14.5 (23F79)

### Installation method

download

### Last Known Working Insomnia version

9.2 I think

**Comment by subnetmarco** [comment]
Thanks for the video, this helps a lot. I will sync with the team to see if we can ship this in the upcoming 9.3.3

**Comment by gatzjames** [comment]
Hi @JoeyBoolean this is now fixed in the latest beta and will be out on the next patch release.
Thanks for the feedback!

**Comment by JoeyBoolean** [comment]
> Hi @JoeyBoolean this is now fixed in the latest beta and will be out on the next patch release. Thanks for the feedback!

It works perfectly now. Thanks!
