### ISSUE TITLE
Body Form fields are not setting correctly

### ISSUE THREAD

**Issue by jbonzohln** [getinsomnia/insomnia#7761]
### Expected Behavior

When I create a form field in the Body tab, the value should be persisted and sent as part of the request.

### Actual Behavior

When I create a form field in the Body tab, the value is not persisted once I send the request and no value is sent in the request.

### Reproduction Steps

1. Create a POST request
2. Set Body to Form
3. Add a field
4. Set the field key and value
5. Click send
6. The value was not sent and reverts to the previous value (or blank)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.2

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.5

### Installation method

homebrew

**Comment by jbonzohln** [comment]
https://github.com/user-attachments/assets/33fc6ed3-cb21-4e8e-9d21-4ced86b6d5ca

**Comment by gatzjames** [comment]
Hi @jbonzohln  this is now fixed in the latest beta and will be out on the next patch release.
Thanks for the feedback!
