### ISSUE TITLE
Endpoint list window scrolls to bottom every time I click Send, or click into the URL bar.

### ISSUE THREAD

**Issue by afeinland** [getinsomnia/insomnia#7768]
### Expected Behavior

When I click "Send" to make an api call, I expect the left column (where the list of folders/endpoints is) to remain unchanged.

This is the endpoint list I'm referring to here, enclosed in red (screenshot taken from insomnia.rest):
<img width="980" alt="Screenshot 2024-07-26 at 1 50 33 PM" src="https://github.com/user-attachments/assets/d65d5ab2-bcc9-44ea-8fc9-227e3438661c">

### Actual Behavior

When I click "Send" to make an api call, the left column (where the list of folders/endpoints is) scrolls all the way to the bottom.

### Reproduction Steps

1. in Insomnia, have several folders filled with endpoints.
2. open a couple of folders so that a scroll bar appears in the endpoint list window.
3. scroll up in the endpoint list and select an endpoint near the top.
4. click Send to make the api call

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

This also happens when clicking into the URL bar.

v 9.3.2 enterprise.
Macbook M2 Pro

### Insomnia Version

9.3.2

### What operating system are you using?

macOS

### Operating System Version

14.4.1

### Installation method

insomnia.rest, I believe.

### Last Known Working Insomnia version

whatever was before 9.3.2

**Comment by subnetmarco** [comment]
@gatzjames I believe we fixed this in the [latest beta](https://github.com/Kong/insomnia/releases/tag/core%409.3.3-beta.3), correct?

**Comment by afeinland** [comment]
Thanks for your response @subnetmarco. Glad to hear it should be fixed. Perhaps my org has us locked to v9.3.2 at the moment. I checked for an update in insomnia but after a min or two of searching, it found nothing. I'll check with IT department on Monday.

**Comment by subnetmarco** [comment]
9.3.2 is the latest GA, you can try the fix with 9.3.3 beta today, which will also be GA next week. 

So you could just wait for the GA to be announced in a few days, if your company doesn't allow beta releases to be used.

**Comment by gatzjames** [comment]
Closing as this is fixed and available in 9.3.3
Thanks for the feedback!
