### ISSUE TITLE
[Bug] Importing requests from a Postman Collection v2 doesn't properly import query string parameters

### ISSUE THREAD

**Issue by EpocDotFr** [getinsomnia/insomnia#778]
- Insomnia Version: 5.14.7
- Operating System: Windows 10

## Details

Using the latest standalone version of Postman on Windows: I exported a collection of requests to a Postman Collection v2 JSON file.

I then imported this file in the lastest Insomnia on Windows (by dragging / dropping the file directly in the window): the import were successful, however query strings parameters weren't properly imported. Specifically:

  1. Disabled query string parameters in Postman weren't imported at all in Insomnia
  2. The resulting URL in Insomnia contains the full URL with query string parameters. Query string parameters should have been imported in the Query tab of Insomnia instead of being put in the request URL.

## Steps to reproduce

  1. Create a new GET request in the latest Postman pointing to this URL: `https://httpbin.org/get`
  2. Add a query string parameter in this request: `first`: `test`
  3. Add a query string parameter in this request: `second`: `test`, then disable this one
  4. Export this request as a Postman Collection v2 JSON file
  5. Import this file in the latest Insomnia

Results:

  - The URL (the one next to the HTTP method selector) in Insomnia is `https://httpbin.org/get?first=test` instead of `https://httpbin.org/get`
  - No query strings are displayed in the Query tab. There should have been:
    - `first`: `test`
    - `second`: `test` (with disabled status)

**Comment by EpocDotFr** [comment]
Okay, I just saw the Import from Url button at the very bottom of the screen in the Query tab that would have done the job... But still, query string parameters should have been properly imported.

**Comment by beeblebrox3** [comment]
AFAIK insomnia doesn't support URL parameters like postman :/
See this: https://github.com/getinsomnia/insomnia/issues/203

**Comment by gschier** [comment]
I think the original issue is referring to query parameters, not the `:param` syntax of Postman. 

The problem is that right now, query params defined in Postman in key-value form are imported into Insomnia as a single string, appended to the URL. Instead of this, it should be imported into Insomnia's key-value form within the Query tab.

**Comment by EpocDotFr** [comment]
@gschier is absolutely right :smile:
