### ISSUE TITLE
9.3.3 broke Environment Variable display

### ISSUE THREAD

**Issue by jandreaucodes** [getinsomnia/insomnia#7787]
### Expected Behavior

A variable shows the Environment it's from and when clicked on, shows you the value it's pulling from the variable.

### Actual Behavior

Now it just shows the variable name. 

![Insomnia-hfDDOMcn-001210](https://github.com/user-attachments/assets/4b007749-d2e1-4bf5-9bd7-d0f6fb4b2fe7)

### Reproduction Steps

Load any API call with an Environment Variable in it.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 9.3.3
Build date: 7/31/2024
OS: Darwin arm64 23.6.0
Electron: 30.2.0
Node: 20.15.0
Node ABI: 123
V8: 12.4.254.20-electron.0
Architecture: arm64

### Insomnia Version

9.3.3

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.6

### Installation method

From website, I think, it's been a while. Might have been homebrew.

### Last Known Working Insomnia version

Whatever I had an hour ago before 9.3.3.

**Comment by subnetmarco** [comment]
Thanks @jandreaucodes, we are looking into this.

**Comment by notjaywu** [comment]
@jandreaucodes Can you check if the `Raw template syntax` option has been enabled in the Perference? If so, you can disable it.

<img width="792" alt="image" src="https://github.com/user-attachments/assets/901fece0-158a-40f9-ba20-ec8bcd87f27d">

**Comment by jandreaucodes** [comment]
@notjaywu Yep, that was somehow checked. I unchecked that and now things are back to normal. Thanks for the help ya'll!
