### ISSUE TITLE
Cookies do not get saved when there is any After-Response script

### ISSUE THREAD

**Issue by JafarEadeh** [getinsomnia/insomnia#7808]
### Expected Behavior

Cookies get saved after the after-response script runs

### Actual Behavior

Adding any character in the after-response script prevents cookies from getting automatically saved

### Reproduction Steps

1. Go to any request that saves cookies
2. Put in anything in the after-response script (like '//')
3. Send the request
4. Notice that cookies do not get saved 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

downloaded from insomnia

**Comment by subnetmarco** [comment]
@ihexxa

**Comment by ihexxa** [comment]
Will check this.
