### ISSUE TITLE
[Improvement] Add enable/disable toggle to all auth schemes

### ISSUE THREAD

**Issue by EpocDotFr** [getinsomnia/insomnia#781]
- Insomnia Version: 5.14.7
- Operating System: Windows 10

## Details

When setting an Auth method with parameters, and then when changing to another Auth method or when disabling Auth, the current Auth settings are lost. Why this behavior? It's very annoying when switching from an environment using an Auth of type "foo" to another using an Auth of type "bar" (for the same API / workspace). Postman is persisting those settings.

**Comment by gschier** [comment]
Can you give a concrete example of this? Auth fields are preserved when no information will be lost. For example, both Basic and NTLM have username/password fields, so switching between them preserves the settings. However, switching between something like OAuth 2 and Basic don't have any shared fields, so settings are lost.

I'm curious, why is the situation you are in where you need to use the same request with multiple authentication types? Can you describe your setup and use case so I can better understand your problem?

**Comment by EpocDotFr** [comment]
> However, switching between something like OAuth 2 and Basic don't have any shared fields, so settings are lost.

Yes, that's the case I'm talking about.

My use case is when requests in the same API (workspace) can either don't use any Auth method (typically dev or beta environments) or use OAuth (typically production environments).

  - When I'm developing on my local (dev) environment, I don't set any Auth method (because we have a special mechanism that bypass OAuth using a special query string parameter)
  - When I'm debugging a production environment, OAuth is required. So in Insomnia I switch the Auth method to OAuth, but as settings aren't preserved because of what you wrote above, I have to re-enter OAuth credentials (actually I have to re-enter Insomnia environment variables that contains the needed OAuth credentials, crednetials that different for each Insomnia environment)

I'm not sure if I'm explaining correctly, don't hesitate to ask for clarification.

**Comment by gschier** [comment]
I'm pretty sure I understand now. Thanks for clarifying your use case.

If you are only switching between OAuth2 and No Auth, maybe a toggle to enable/disable auth would work for you? In the last release, I added this toggle to a few of the simpler authentication schemes (Basic, NTLM, Digest, etc) but not OAuth. 

If there were an enable/disable checkbox in the OAuth 2 settings, would that solve your problem? Or, do you have cases where you are mixing other auth schemes as well?

**Comment by EpocDotFr** [comment]
In my use case I'm only using either No Auth or OAuth 1.0 (remember, I'm the annoying OAuth 1 guy on Twitter and in #197 😄). So yes, this will do the trick if you add this toggle for OAuth 1.0.

Out of curiosity; why not adding this toggle for all Auth methods?

**Comment by gschier** [comment]
Awesome. I'll update this issue name to reflect the task.

> Out of curiosity; why not adding this toggle for all Auth methods?
I don't really have a good reason, other than I was feeling lazy at the time 😛

**Comment by gschier** [comment]
Ah, this was done a while ago
