### ISSUE TITLE
Failed to query createProject: ERROR: insert or update on table "projects" violates foreign key constraint "projects_team_project_id_fkey" (SQLSTATE 23503)

### ISSUE THREAD

**Issue by yaohy2014** [getinsomnia/insomnia#7820]
### Expected Behavior

sync success

### Actual Behavior

sync occurred error
Failed to query createProject: ERROR: insert or update on table "projects" violates foreign key constraint "projects_team_project_id_fkey" (SQLSTATE 23503)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Version: Insomnia 9.3.3 Build date: 2024/7/31

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### Installation method

https://insomnia.rest/

**Comment by notjaywu** [comment]
@yaohy2014 What operation did you perform? Converting a local vault to a cloud project, or creating a new project?

**Comment by yaohy2014** [comment]
> @yaohy2014 What operation did you perform? Converting a local vault to a cloud project, or creating a new project?

Converting a local vault to a cloud project

**Comment by notjaywu** [comment]
Can you check if the option `Duplicate` helps here?

<img width="400" alt="Screenshot 2024-08-08 at 12 26 25" src="https://github.com/user-attachments/assets/7a280072-4425-4590-8a3a-eec97d099de9">

**Comment by yaohy2014** [comment]
> Can you check if the option `Duplicate` helps here?
> 
> <img alt="Screenshot 2024-08-08 at 12 26 25" width="400" src="https://private-user-images.githubusercontent.com/130019718/356081849-7a280072-4425-4590-8a3a-eec97d099de9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTE1MzQsIm5iZiI6MTcyMzA5MTIzNCwicGF0aCI6Ii8xMzAwMTk3MTgvMzU2MDgxODQ5LTdhMjgwMDcyLTQ0MjUtNDU5MC04YTNhLWVlYzk3ZDA5OWRlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwNDI3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDNkZjUxZmM2N2I2N2IyYTk0MDliOGMxMWJiOTM0YWYzYzQ3ZjQ1NmJkYjUwMGNlYWZjYTE3MGMwM2RjMTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IELbLMinYM1rSceypYA7QfskRvOP40ccLls4K6Wdo1M">

I use the Duplicate option, and the cuplicated collection occurred the same error

**Comment by notjaywu** [comment]
The application should be using some stale ID. Could you log out of the application and log in again?

One more thing to confirm the steps of how it happened:
1. Convert the Personal Workspace to a local vault, is there any existing collections in this workspace?
2. Convert it back to a cloud project, then the error happened?

**Comment by yaohy2014** [comment]
> The application should be using some stale ID. Could you log out of the application and log in again?
> 
> One more thing to confirm the steps of how it happened:
> 
> 1. Convert the Personal Workspace to a local vault, is there any existing collections in this workspace?
> 2. Convert it back to a cloud project, then the error happened?

I log out and log in, and foud the sync module missed 
![image](https://github.com/user-attachments/assets/72b4ca4b-4b4c-4eae-b448-ce328121b184)

**Comment by notjaywu** [comment]
This `Personal Workspace` is still treated as a local vault, so it doesn't show the sync module.
So far, I can't replicate this issue on my local. Can you turn it into a cloud project again?

**Comment by yaohy2014** [comment]
> This `Personal Workspace` is still treated as a local vault, so it doesn't show the sync module. So far, I can't replicate this issue on my local. Can you turn it into a cloud project again?

I turn it into a cloud project.
When I push a commit, the following error occurred
`Cannot destructure property 'blobsCreate' of '(intermediate value)' as it is undefined`
![image](https://github.com/user-attachments/assets/af32ef0e-2131-4cae-9d14-4a585766d667)

**Comment by yaohy2014** [comment]
> > This `Personal Workspace` is still treated as a local vault, so it doesn't show the sync module. So far, I can't replicate this issue on my local. Can you turn it into a cloud project again?
> 
> I turn it into a cloud project. When I push a commit, the following error occurred `Cannot destructure property 'blobsCreate' of '(intermediate value)' as it is undefined` ![image](https://private-user-images.githubusercontent.com/118656244/356218027-af32ef0e-2131-4cae-9d14-4a585766d667.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjU3MDgsIm5iZiI6MTcyMzE2NTQwOCwicGF0aCI6Ii8xMTg2NTYyNDQvMzU2MjE4MDI3LWFmMzJlZjBlLTIxMzEtNGNhZS05ZDE0LTRhNTg1NzY2ZDY2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwMTAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGI0ZTc1MWVlMDNmNzkxNDc0MTEyODliODcxZThjYzIwYTBhMGM2M2RlYTljMjgzZDllMTUyODQ4NTFlOGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ldEC7C3A2YCjlDRvXNHWr3cIuwx1dRg0W29XqV4JEL0)

I think I find the reason. When I use fiddler to catch my system reqeusts. I found the insomnia sync request may be forbidded by my system proxy.
Thanks a lot.

**Comment by notjaywu** [comment]
Thanks for your information! I will close this issue, feel free to reopen it if it still happens.
