### ISSUE TITLE
Insomnia failed save enviroment variable using after-response script

### ISSUE THREAD

**Issue by thinisde** [getinsomnia/insomnia#7829]
### Expected Behavior

```
const jsonBody = insomnia.response.json();

const refreshToken = jsonBody.body.refreshToken;
const accessToken = jsonBody.body.accessToken;

console.log(refreshToken, accessToken);

if(refreshToken) {
	insomnia.environment.set("refreshToken", refreshToken);
}

if(accessToken) {
	insomnia.enviroment.set("accessToken", accessToken);
}
```

This code should work

### Actual Behavior

< HTTP/1.1 200 OK
< Date: Mon, 12 Aug 2024 20:14:09 GMT
< Content-Type: application/json
< Content-Length: 609
< Vary: Origin

* Received 609 B chunk
* Connection #1 to host localhost left intact
* Cannot read properties of undefined (reading 'set')

![image](https://github.com/user-attachments/assets/84e54af9-6d46-4ad6-aac3-f0190736457f)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 9.3.3

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 24

### Installation method

From Insomnia.rest website using .deb package

**Comment by subnetmarco** [comment]
@ihexxa Can you look into this?

**Comment by ihexxa** [comment]
Hello @CutieCat6778 , there is a typo in your code, pls let us know if the fix works.

<img width="254" alt="Screenshot 2024-08-13 at 10 23 42" src="https://github.com/user-attachments/assets/b6028fff-8293-4fe8-92e4-fa0d1bff4f81">

**Comment by ihexxa** [comment]
The issues seems resolved, closing this.
