### ISSUE TITLE
[Feature Request] custom fonts with optional support for ligatures

### ISSUE THREAD

**Issue by benatkin** [getinsomnia/insomnia#784]
Along with #353 it would really be great to have the ability to set a custom font with ligatures. This would enable [Fira Code](https://github.com/tonsky/FiraCode) which shows multiple-character programming symbols integrated.

I realize most JSON and XML doesn't have a lot of character sequences that invoke the intricate ligatures of fira code, but I hope to extend insomnia to support multiple text files which would make it more useful for the now.sh, heroku, netlify, AWS Lambda, Azure Functions, Google Cloud Functions, and Firebase APIs. In those text files there would be a lot of ligatures.

**Comment by gschier** [comment]
I hope to get to #353 eventually which should hopefully cover this one as well.

**Comment by gschier** [comment]
Going to close this one as a duplicate.
