### ISSUE TITLE
[Bug] Assigning the same color to different environments randomly fails on Windows

### ISSUE THREAD

**Issue by EpocDotFr** [getinsomnia/insomnia#785]
- Insomnia Version: 5.14.7
- Operating System: Windows 10

## Details

Assigning the same color to several different environments either sets the selected color or the violet color (I think it's the default base color of the theme I'm using).

I think it's specific to Windows and its color picker. Something related to the default selected color when opening the picker.

**Comment by gschier** [comment]
Anyone Windows users out there that want to take a shot at fixing this?

**Comment by gschier** [comment]
This is done! Was closed in a duplicate report (#811)

**Comment by EpocDotFr** [comment]
Mmmh hoping it was the same issue as mine is a little bit different :smiley:

**Comment by gschier** [comment]
I assumed it was the same but I can reopen this if it's still broken for you in the next release

**Comment by EpocDotFr** [comment]
Of course, I'll keep you updated.
