### ISSUE TITLE
When pasting CURL request into url input and importing the request,  insomnia creates new request, and keeps old one with corupted imput from CURL

### ISSUE THREAD

**Issue by petermilan** [getinsomnia/insomnia#7853]
### Expected Behavior

After pasting CURL and importing the data into recent Request, it should update the request tab - where the CURL was imported.

### Actual Behavior

This behavior is quite anoying as when I want to import new CURL
even if I prepare a new request in advance and paste CURL into its url input and  confirm input modal, 
I end with 2 requests 
- one succesfully imported
- second - which I prepared for import with broken URL which colds the CURL string and it is useless

Any time I import CURL I need manually cleanup second request

<img width="496" alt="image" src="https://github.com/user-attachments/assets/74a41513-4e3f-4e76-ba8c-2445a612b400">

### Reproduction Steps

1. Open insomnia request
2. paste CURL string into  url input
3. Wait for import popup
4. hit IMPORT

as resolution you end with 2 Request  tabs, where one is corrupted by pasted CURL text

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.2

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.5

### Installation method

download

**Comment by notjaywu** [comment]
Can you update to `v9.3.3` and see if it still happens?

You can also try this option `From Curl`:
<img width="809" alt="image" src="https://github.com/user-attachments/assets/1ebc6493-8123-4779-8799-1dd942d82fe5">

**Comment by petermilan** [comment]
Thank you for your reply, the error is still present in  9.3.3, however the import from CURL option works great.
For me the option `From Curl` is enough and perhaps this issue might be closed.

**Comment by notjaywu** [comment]
Thanks @petermilan
