### ISSUE TITLE
Where did folder environments go in 9.3.3?

### ISSUE THREAD

**Issue by cpoulsen-dezide** [getinsomnia/insomnia#7855]
### Expected Behavior

We have a big setup that heavily relies on folder environments. That is now broken :( 

### Actual Behavior

`{{ _.base_url }}/guides/87f0a274-1314-4476-a1b9-852c14`  
now resolves to:
`http:///%7B%7B%20_.root_url%20%7D%7D/api/sessionviewer/guides/87f0a274-1314-4476-a1b9-852c14?subject=123`

And Insomnia complains about undefined environment variables when I try to execute the request.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Version: Insomnia 9.3.3

### What operating system are you using?

Other Linux

### Operating System Version

Arch (insomnia-bin from AUR)

### Installation method

pacman

### Last Known Working Insomnia version

I dont know

**Comment by filfreire** [comment]
@cpoulsen-dezide do you see them when you click on the folder in the environments tab?
![Screenshot 2024-08-21 at 12 36 39](https://github.com/user-attachments/assets/55433eb9-1c5c-4f6f-8aed-fb94d117abf1)

**Comment by cpoulsen-dezide** [comment]
Thank you for the quick reply. Yes, I see the stuff in the tab (pheew :) ) 

After clicking a lot around on environments all over the place it seems like things are back in order. It was like the environment selection that was pre-selected in the UI during startup was not really/fully selected until I changed the selection to something else and back again.
