### ISSUE TITLE
Cookies are still not being set if there is any after-request script

### ISSUE THREAD

**Issue by manuelfesantos** [getinsomnia/insomnia#7877]
### Expected Behavior

Adding a script to edit an environment variable after a request still allows the Set-Cookie header from the response to set the cookie in insomnia

### Actual Behavior

With the script present, the cookie is not added to insomnia cookies

### Reproduction Steps

Add a request to an endpoint which returns a set-cookie header
Add an after-response script to edit an environment variable
Make the request
Check if the cookie has been set

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I saw that an issue was created with this problem and it was closed, but I am still unable to add cookies while having after-response scripts present

### Insomnia Version

9.3.3 / Build date: 7/31/2024

### What operating system are you using?

macOS

### Operating System Version

14.6 (23G80)

### Installation method

Download from website

**Comment by ihexxa** [comment]
This is a known issue and will be fixed in the next release #7808 , thanks for the feedback.
