### ISSUE TITLE
[Bug] misleading error "parseSignature: expected comma after expression" when using JSONPath in template tag

### ISSUE THREAD

**Issue by sbusch** [getinsomnia/insomnia#788]
- Insomnia Version: 5.14.7.1871
- Operating System: macOS 10.13.3

## Details

I'm using a "Response->Body Attribute" template tag to dynamically retrieve an id using JSONPath from another response and use it as a query parameter of another request.

Although this works as expected, the Insomnia user interface indicates an error by coloring the tag 
with the hint "parseSignature: expected comma after expression".

![parsesignature error](https://user-images.githubusercontent.com/91866/36716134-7b4c64d0-1b99-11e8-8fb2-fb9919078107.png)

Template tag configuration:

![edittag](https://user-images.githubusercontent.com/91866/36716328-4b8c33aa-1b9a-11e8-9f71-ee9ad96cf5a1.png)

JSONPath from template tag:

    $.folderList[?(@.subject=='mySubject')].id

Referenced response, reduced to the minimum:

    {
        "folderList": [
            {
                "id": "123",
                "subject": "aSubject",
            },
            {
                "id": "456",
                "subject": "anotherSubject",
            },
            {
                "id": "789",
                "subject": "mySubject"
            }
        ]
    }

**Comment by sbusch** [comment]
Followup: when I try to use the same template tag for an environment variable in the "Manage Environments" dialog, and error is indicated aswell for the template tag:

![bildschirmfoto 2018-02-27 um 09 59 52](https://user-images.githubusercontent.com/91866/36719333-113cad78-1ba5-11e8-906f-0fa605232ca2.png)

And at the bottom of the dialog:

![bildschirmfoto 2018-02-27 um 09 59 14 1](https://user-images.githubusercontent.com/91866/36719338-13b93f9e-1ba5-11e8-8f8c-c514af6c98b9.png)

**Comment by gschier** [comment]
Thanks for reporting this @sbusch! There was a problem where backslash characters were getting stripped before rendering the tag preview.

Nice little one-line fix: https://github.com/getinsomnia/insomnia/commit/676ac58b8b83df645e0d7913184262f61b68409f
