### ISSUE TITLE
Typo on Settings/Account page https://app.insomnia.rest/app/settings/account

### ISSUE THREAD

**Issue by BassJunkieeeee** [getinsomnia/insomnia#7887]
### Expected Behavior

Not a bug, just a small typo

Expected Email address field box to say Enter your email address

### Actual Behavior

On the account page the Add email  field states 'Ender your email address' not 'Enter your email address'
https://app.insomnia.rest/app/settings/account

![image](https://github.com/user-attachments/assets/c15e3b04-9490-408f-a8e7-69227be39ac6)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

Windows Installer

**Comment by subnetmarco** [comment]
@pavkout

**Comment by subnetmarco** [comment]
I see a PR, this should be fixed. Thanks for the report.
