### ISSUE TITLE
[Bug] POST fails with readonly file source

### ISSUE THREAD

**Issue by OwenBorstad** [getinsomnia/insomnia#789]
- Insomnia Version: v5.14.7
- Operating System: Windows 10

## Details

When using a POST with a file source, if that file is read only (not checked out in perforce), then Insomnia will fail to load the file and give an error: "EPERM: operation not permitted, open '<filepath>'"

There shouldn't be any blocker on trying to load a file if it's read only, and the action you are performing is a read of the file (POST/PUT with file contents).

**Comment by gschier** [comment]
I was able to reproduce this issue. Will get it fixed right away! 👍
