### ISSUE TITLE
Cookie not getting set when using post response script

### ISSUE THREAD

**Issue by shubhendu-enable** [getinsomnia/insomnia#7891]
### Expected Behavior

When using post response script , cookie should be reflected in Manage Cookies, similar to behaviour when no post response script is set

### Actual Behavior

Cookies doesn't appear  in Managed Cookies when post response script is set

### Reproduction Steps

1. Add Request : GET https://google.com
2. Add post response script : console.log("hello")
3. Execute Request
4. No Cookie appears in Manage Cookie 
5. Remove post response script
6. Execute Request
7. Two cookies appear in Manage Cookie

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.3

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.6.1

### Installation method

download from insomnia website

### Last Known Working Insomnia version

NA

**Comment by ihexxa** [comment]
This is one known issue (#7808 ) and will be fixed in the next release , thanks for the feedback.
