### ISSUE TITLE
[Question/Feature Request] Custom Auth Plugins

### ISSUE THREAD

**Issue by Friss** [getinsomnia/insomnia#790]
Would it be possible to support custom plugins for auth? It would go beyond just setting a cookie / header on the request as we would need to get the creds from the user. 

I looked around briefly but didn't see anything that currently exists that allows for a plugin to ask for user input.

**Comment by hsanson** [comment]
I would like this feature too. Currently I have a plugin that can do HMAC authentication but would be nice if it could be registered as an Auth plugin and appear in the Auth tab of the request editor.

  https://github.com/sujrd/insomnia-plugin-hmac-auth

**Comment by gschier** [comment]
I want to get to this right after finishing #768

The long term plan is to, one by one, add a way for plugins to extend core functionality, then refactor the core functionality to be written using the plugin system. This is very similar to how modern text editors like Atom do things. The app is just a core set of functionality with an awesome plugin API. The only difference between "native" features and 3rd-party plugins is that they are bundled by default.

**Comment by Friss** [comment]
Hey @gschier any update on this? Would love to use Insomnia for more parts of my daily workflow.
