### ISSUE TITLE
[Feature Request] Remember "Text (Multi-line)" selection for form inputs

### ISSUE THREAD

**Issue by chrismeller** [getinsomnia/insomnia#791]
When sending a POST request with one of the form input types the ability to select "Text" or "Text (Multi-line)" for each input field is awesome. It would be awesomer still if it remembered this selection when you navigate back to the same request in the future.

- Insomnia Version: 5.14.8.1893
- Operating System: macOS 10.13.3

**Comment by gschier** [comment]
Hmm, Insomnia is supposed to remember which one was selected. (I can't reproduce the issue). 

Would you be able to post a screen recording that demonstrates the bug?

**Comment by gschier** [comment]
Oh nvm. It seems that it _is_ remembered for multipart forms but it _is not_ remembered for urlencoded forms. Will fix!

P.S. Can you confirm that this is the case for you as well?
