### ISSUE TITLE
Too many pinned requests hide the un-pinned request list

### ISSUE THREAD

**Issue by jamesgkong** [getinsomnia/insomnia#7914]
### Expected Behavior

Pinned request list should not prevent navigation of unpinned requests.

### Actual Behavior

When too many requests are pinned this area of the request list does not keep its ratio of screen-height in the overall Request list window, and does not share a scroll-bar with the unpinned request list elements. This means if it reaches the full height of the window the unpinned requests can no longer be scrolled to or reached as per the gif below:
![pinned-request-scrollbar-issue](https://github.com/user-attachments/assets/f04f642a-7207-49e0-b024-1d80ad3fc3e7)

### Reproduction Steps

1. Create a new Collection
2. Add a large number of requests
3. Pin a sufficient number of these requests until the "pinned requests" take up the full height of this part of the screen and other requests now cannot be scrolled to.

Replicated in latest Insomnia 10.0.0-beta.0

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.0.0-beta.0

### What operating system are you using?

macOS

### Operating System Version

OS: Darwin arm64 23.6.0

### Installation method

Downloaded

**Comment by subnetmarco** [comment]
I see, the solution would be to have a max height (not greater than 50%) in the pinned section and potentially show a scrollbar there too. if the screen is too small. @CurryYangxx
