### ISSUE TITLE
Change body to JSON or XML for new requests not changing

### ISSUE THREAD

**Issue by DuncanFaulkner** [getinsomnia/insomnia#792]
[Bug] – Upgraded to 5.14.8 (1st March)  not able to change body type

- Insomnia Version: 5.14.8
- Operating System: ubuntu 16.04

Clicking the body drop down shows menu selecting JSON or XML does not switch body type. This works for existing requests but not new ones.

**Comment by gschier** [comment]
Doh! That shouldn't have made it in. Thanks for reporting this. Going to push out a fix in the next hour or two.

**Comment by jalberto** [comment]
@gschier is this already out?

**Comment by gschier** [comment]
Yep!

**Comment by jalberto** [comment]
thanks!
