### ISSUE TITLE
Manage Environments: second time selection not working

### ISSUE THREAD

**Issue by BrainCrumbz** [getinsomnia/insomnia#7920]
### Expected Behavior

Hi, thanks for this great application. I'm attaching a GIF to show what's happening, then describing the steps:

![environment-switch-issue](https://github.com/user-attachments/assets/b4f800c6-fb29-4691-af69-747121c4628a)

1. Open Manage Environments, where previously a single Sub Environment has been added
2. Click on Sub Environment, right pane updates accordingly
3. Click on Base Environment, right pane updates accordingly
4. Click again on Sub Environment, right pane should update accordingly again

### Actual Behavior

1. Open Manage Environments, where previously a single Sub Environment has been added
2. Click on Sub Environment, right pane updates accordingly
3. Click on Base Environment, right pane updates accordingly
4. Click again on Sub Environment: nothing happens, right pane still shows Base Env.

### Reproduction Steps

See previous fields

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2 Build 22631.4112

### Installation method

Download from site

**Comment by notjaywu** [comment]
The version `2023.5.8` is out of date, you can upgrade to the latest release version. This issue should have been fixed already.

**Comment by BrainCrumbz** [comment]
Thanks!
