### ISSUE TITLE
Insomnia 9.3.2 Login issue  not able to login

### ISSUE THREAD

**Issue by deepeshk0102** [getinsomnia/insomnia#7935]
### Expected Behavior

It should be login.   facing issue with insomnia
Please help to resolve

### Actual Behavior

Getting Error While Login.  Insomnia  is not rendered properly
Failed to find personal organization your account appears to be in an invalid state. Please contact support if this is a recurring issue.

![image](https://github.com/user-attachments/assets/b6a2b49e-b15b-4497-abfe-00ccd532c643)

### Reproduction Steps

![image](https://github.com/user-attachments/assets/2d386b3a-8a35-40b3-b548-b87cc3b73f81)
![image](https://github.com/user-attachments/assets/00c13e80-abda-4caf-af42-43f522abb4cb)

Getting Errors.  Not able to login

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

![image](https://github.com/user-attachments/assets/6730204a-8def-4692-be75-0af5e71e4223)

### Insomnia Version

9.3.2

### What operating system are you using?

Windows

### Operating System Version

Microsoft Windows 11 Enterprise      Version	10.0.22631 Build 22631

### Installation method

Downloaded from insomnia Website

### Last Known Working Insomnia version

8.3.0

**Comment by subnetmarco** [comment]
@notjaywu please take a look at this

**Comment by notjaywu** [comment]
@deepeshk0102 Your account is in good standing. Could you try again?

**Comment by deepeshk0102** [comment]
![image](https://github.com/user-attachments/assets/e6744e70-cf47-4ce6-b766-7bd0cedf5663)
@notjaywu  same issue

**Comment by deepeshk0102** [comment]
@notjaywu 

![image](https://github.com/user-attachments/assets/b540c2bf-9381-4a0b-8c88-28e3872da047)

**Comment by notjaywu** [comment]
@deepeshk0102 Can you check if you have enabled proxy in Preferences? Or are you using any VPN which may block this request?

**Comment by deepeshk0102** [comment]
@notjaywu could Please provide list of URL which creating Problem for sign In Insomnia  (Using Private Network Using ZScaler)

So I will check with Network Team

**Comment by notjaywu** [comment]
all requests `https://api.insomnia.rest/*`, for example, `https://api.insomnia.rest/auth/whoami` the request you can see in the console.

**Comment by subnetmarco** [comment]
@deepeshk0102 Please let us know what was the outcome of your investigation.

**Comment by subnetmarco** [comment]
@deepeshk0102 any update? I will close this issue for now.

**Comment by notjaywu** [comment]
link to similar issue #7969
