### ISSUE TITLE
Collection runner shows request names in white when using light theme

### ISSUE THREAD

**Issue by suttonb** [getinsomnia/insomnia#7939]
### Expected Behavior

Request names are visible in collection runner when using light theme

### Actual Behavior

Folder nesting level and request method are visible, but the request name blends into the background (see screenshot below):

![image](https://github.com/user-attachments/assets/ea702bff-1462-4973-86d2-84df02e40904)

When switching to dark theme, the request names show up:

![image](https://github.com/user-attachments/assets/33c65fec-4811-4cff-9876-ba2b8ae0bcac)

### Reproduction Steps

1. Create requests in a collection
2. Open collection runner
3. Switch Insomnia theme to any of the light themes

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home version 23H2

### Installation method

download from insomnia.rest

**Comment by subnetmarco** [comment]
@ihexxa to take a look

**Comment by ihexxa** [comment]
@suttonb Would you mind to try a dark theme？

**Comment by suttonb** [comment]
Ah yep, the names show up in white when switching to a dark theme. I'll update the original description/title.

**Comment by ihexxa** [comment]
The fix has been merged and will be released in the next minor version.
