### ISSUE TITLE
Collection Runner iteration data is imported with "\r" character from CSV file with CRLF EOL

### ISSUE THREAD

**Issue by gsiles** [getinsomnia/insomnia#7947]
### Expected Behavior

The variable name and values are imported without the "\r" character when uploading a CSV file with CRLF EOL

### Actual Behavior

Variable name and values are imported with the "\r" character when uploading a CSV file with CRLF EOL

### Reproduction Steps

1. First you need a CSV file with CRLF EOL like the one shown below:
![pages-crlf](https://github.com/user-attachments/assets/4f6fc741-9237-4b97-8d36-ab1a59ed6b70)
2. Select a request from your collection, click the "Script" tab and select "Pre-request". Then paste the code below:
```javascript
console.log(insomnia.variables.iterationDataVars.toObject())

console.log("Check if 'page' exists")
console.log(insomnia.variables.iterationDataVars.has("page"))

console.log("Check if 'page\r' exists")
console.log(insomnia.variables.iterationDataVars.has("page\r"))
``` 
3. Go to the collection runner by clicking the "play" button to the right of the collection name.
4. Click in "Upload data" then in "Select Data File", choose the CSV file and click "Upload".
5. Select the requests to run and click "Run".
6. After the run has ended select the "Console" tab and check the logs:
![pages-crlf2](https://github.com/user-attachments/assets/50cb11d3-a88b-453b-903c-069c5d0d5fa2)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

For a CSV file with LF EOL seems to work fine
![pages-lf](https://github.com/user-attachments/assets/dc0f1c20-23d4-4374-893c-09f9457b578c)
![pages-lf2](https://github.com/user-attachments/assets/3c4d8263-e0a7-41b0-9f98-d1cc91325250)

### Insomnia Version

10.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro version 22H2

### Installation method

download from insomnia.rest

**Comment by gsiles** [comment]
I guess that the issue might be in this line of code: https://github.com/Kong/insomnia/blob/9734d1e117407f547f066ad0aa8916d1ea0e029b/packages/insomnia/src/ui/components/modals/upload-runner-data-modal.tsx#L80C25-L80C32

`const csvRows = content.split('\n').map(row => row.split(','));`

**Comment by subnetmarco** [comment]
@ihexxa to take a look

**Comment by cwangsmv** [comment]
Thanks for the findings, the issue has been fixed and will be available in next minor release
