### ISSUE TITLE
当我们给接口新增一个参数密钥时，但参数的值为空时

### ISSUE THREAD

**Issue by antlcl** [getinsomnia/insomnia#7964]
### Expected Behavior

可以正常发送请求并得到结果

### Actual Behavior

当我们给接口新增一个参数密钥时，但参数值为空时，我点击发送，接口返回报错：缺少参数xxxxx

### Reproduction Steps

当我们给接口新增一个参数密钥时，但参数值为空时  我点击Send ，接口返回报错：缺少参数xxxxx   但是我生成shell-->cURL 重新请求  一切正常🤔

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.0.0

### What operating system are you using?

macOS

### Operating System Version

macos

### Installation method

官网下载

**Comment by ihexxa** [comment]
因与#7965 重复, 关闭此卡片.
