### ISSUE TITLE
当我给接口新增一个参数密钥时，但参数值为空时

### ISSUE THREAD

**Issue by antlcl** [getinsomnia/insomnia#7965]
This is the address for a get request: http://xxxxxxxxxx?certificateNo=18925491&securityCode=&rechargeAccountId=0

1.It works like this on Postman:
![image](https://github.com/user-attachments/assets/4d41f191-22a6-468d-b459-526d51defac5)

2.It works like this on CURL:
![image](https://github.com/user-attachments/assets/d8d3532b-6416-47ca-9c65-b8bb4e554e1a)

3.It works like this on insomnia:
   (1) new httpRequest   --> Fill in the URL directly(Do not click import from URL button)  --> it`s  ok
![image](https://github.com/user-attachments/assets/cbe0d75b-0b5e-4aaa-b113-7fa1a4dc7799)

   (2) new httpRequest  -->  Fill in the URL directly   ---->  click import from URL button  ---> fail 
![image](https://github.com/user-attachments/assets/fa7aba0b-e0f1-4077-a588-fbeb2ffb1037)

**Comment by notjaywu** [comment]
@cwangsmv to take a look

**Comment by subnetmarco** [comment]
@notjaywu What is the next step here?

**Comment by cwangsmv** [comment]
> @notjaywu What is the next step here?

Will fix this by adding equal sign for empty query params in editor
