### ISSUE TITLE
Folder environment option gone from folder dropdown menu

### ISSUE THREAD

**Issue by LunaticoCR** [getinsomnia/insomnia#7968]
### Expected Behavior

Right clicking in a folder dropdown used to have an 'Environment' option where one could store variables that would apply only to requests within that folder.
According to [the documentation](https://docs.insomnia.rest/insomnia/environment-variables#folder-environments) this should still be supported?

### Actual Behavior

The 'Environment' option is gone from the dropdown menu, I'm not sure after which update this started happening but it must be a recent one.
![image](https://github.com/user-attachments/assets/a185c960-e37a-4479-9648-01ceedbda22c)

The folder environments must still be there because requests that rely on variables in those environments are working fine for me, it's just the menu option that is gone and I can't find a way to open them.

### Reproduction Steps

1. Right click on a folder down arrow to open the dropdown menu
2. Look for the 'Environment' option

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.6.1

### Installation method

Downloaded

### Last Known Working Insomnia version

Unsure

**Comment by subnetmarco** [comment]
If you click on a folder, it opens the ability to setup environments and scripting, or mutual headers too:

![Screenshot 2024-09-17 at 2 37 01 PM](https://github.com/user-attachments/assets/7bbe67fb-bcd8-4e84-bf43-daa6ac729f18)

**Comment by LunaticoCR** [comment]
Oh wow! I completely missed that. The documentation [here](https://docs.insomnia.rest/insomnia/environment-variables#folder-environments) needs to be fixed though @subnetmarco .
Should this issue be used to track that or do you guys track documentation issues differently internally?

**Comment by subnetmarco** [comment]
@filfreire for the documentation
