### ISSUE TITLE
[Bug] GraphQL instospection query ignores plugins.

### ISSUE THREAD

**Issue by hsanson** [getinsomnia/insomnia#798]
- Insomnia Version: 5.14.8
- Operating System: Ubuntu 16:04

## Details

My graphql endpoint requires some custom headers in order to authorize the requests. I have a [HMAC Plugin](https://github.com/sujrd/insomnia-plugin-hmac-auth) that adds these headers to every request and it work perfectly.

Unfortunately, it seems that the GraphQL instrospection query to get the schema totally ignores the plugin. I get "Got status 401 fetching schema from /graphql" error that tells me this request is not getting the auth headers from the plugin.

Maybe this MR is related PR #418

**Comment by gschier** [comment]
I see the issue. Will include a fix in the next release :)
