### ISSUE TITLE
[Improvement] Clear response files from FS after response history deletion

### ISSUE THREAD

**Issue by josdejong** [getinsomnia/insomnia#799]
First, thanks for developing insomnia, it really works like a charm!

I'm working with large requests (returning over 1 GB), and I noticed that the folder where the responses are stored, `.config/Insomnia/responses`, keeps growing. It looks like when I clean up responses via "Clear History" in the menu top right, the list is cleared from the UI, but the actual responses in `.config/Insomnia/responses` are still there. 

I can work around this by manually clearing this folder, but it would be great if "Clear History" cleans up these responses.

Running on Linux (Mint).

**Comment by gschier** [comment]
Thanks for reporting this @josdejong! It's true that no cleanup is done with the responses folder at this time. I'll add this to the list 😄

**Comment by josdejong** [comment]
Thanks Gregory!

**Comment by josdejong** [comment]
Any news on this already?

**Comment by gschier** [comment]
Sorry. I lost track of this one. I had a few minutes so I implemented it quickly (wasn't that hard 😄)

**Comment by josdejong** [comment]
wow, cool! Looking forward to the first next release.
