### ISSUE TITLE
Blank screen on Insomnia start-up

### ISSUE THREAD

**Issue by simonl65** [getinsomnia/insomnia#800]
- Insomnia Version: 5.14.9
- Operating System: Win10 x64

## Details

Have been using Insomnia all morning OK but after reloading it the application window is blank.

DevTools Console shows `[db] Initialized DB client`

### Steps to reproduce:

Open Insomnia (with or without admin' priv's)

### Outcome:
Blank application window.

### Expected outcome:
Insomnia application!

**Comment by simonl65** [comment]
FYI: Still the same after uninstalling and re-installing.

**Comment by simonl65** [comment]
Still fails after PC reboot. Will try uninstall / removing all insomnia file / re-install...

**Comment by simonl65** [comment]
Well it's working again, but - of course - I don't have any of my settings. Is there any way I can retrieve them from the files I saved earlier?

**Comment by simonl65** [comment]
Figured it out - I copied the following files back into the `%APPDATA%\Insomnia` folder:
```
insomnia.Environment.db
insomnia.Request.db
insomnia.RequestGroup.db
insomnia.RequestGroupMeta.db
insomnia.requestMeta.db
insomnia.RequestVersion.db
insomnia.Settings.db
insomnia.Workspace.db
insomnia.WorkspaceMeta.db
Preferences
```

**Comment by gschier** [comment]
That's quite strange. I can't think of a scenario where it would show a white screen without there being an error in the Console. Perhaps it was stuck loading something. Did you have any large request or response bodies?

**Comment by simonl65** [comment]
There _may_ have been a larg response body (most of my API calls result in such) but it had been working just fine (been using Insomnia for some months now 🥇). Since re-installation and file copying everything has been working fine. Thanks for your response though.

**Comment by gschier** [comment]
You can delete the responses folder within Insomnia's data directory 

%APPDATA% on Windows
$XDG_CONFIG_HOME or ~/.config on Linux
~/Library/Application Support on macOS

**Comment by SiliconValet** [comment]
Success! not sure which of localStorage or plugins folder was the cause in my case for future readers. (I deleted both)

**Comment by ViggoV** [comment]
I have a similar issue on Mac, but deleting `localStorage/`, `plugins/` and `responses/` didn't help. When launching Insomnia I get a blank screen for about 20s and then a crash.. No info, no log, no option to do anything.. Just the little beachball of death :/

**Comment by toymachiner62** [comment]
You only have to delete all the responses (or at a minimum find the large one that's causing the issue) from `~/Library/Application Support/Insomnia/responses`. You won't lose all your data this way!

**Comment by ViggoV** [comment]
As described above I removed the three folders that have been suggested in this thread first, including responses, but it didn’t work.. So yes, in my case I did have to lose all my data..

**Comment by altbrace** [comment]
Having the same issue on Windows, version 2021.5.0. A complete wipe of the data directory did help, but not before a restart. Weird behavior

**Comment by ferencgyenezs** [comment]
~~In my case, deleting `Session Storage` from the `%APPDATA%\Insomnia` | `.config\Insomnia` solved the issue.~~

What I would recommend is to backup your config folder %APPDATA%\Insomnia` | `.config\Insomnia`, and delete all the folders (but not the files) in the config folder.
