### ISSUE TITLE
[Help] Insomnia opens itself until crash if a plugin that uses sync-request is loaded

### ISSUE THREAD

**Issue by hsanson** [getinsomnia/insomnia#801]
- Insomnia Version: 5.14.9
- Operating System: Ubuntu 16.04

## Details

I am creating a plugin that uses [sync-request](https://github.com/ForbesLindesay/sync-request) to refresh an auth token before making the actual request.

The problem  is that as soon as I require the module in the plugin code, insomnia starts opening several instances of itself until it crashes. The following line causes the issue when added to the top of a plugin:

```
var request = require('sync-request');
```

BTW: is there a way to make sync http requests using insomnia tools within a plugin?
The server I need to work with has short lived request tokens so I need to get new tokens and set them in the headers from time to time.

**Comment by gschier** [comment]
There's no official way (yet) to trigger a request in Insomnia, but you can make use of any Node.js request library.

I think the popups have something to do how the `sync-request` plugin spawns child processes. I'm not sure of the details, but I had to set this environment variable when creating a child process: https://github.com/getinsomnia/insomnia/blob/feecc8f203ea7c7b9fa1bf701c56e9f6586d3e27/packages/insomnia-app/app/plugins/install.js#L54

One thing to note is that your plugin does not have to by synchronous (it can be async). 

```js
const axios = require('axios');
module.exports.requestHooks = [
    // Using async/await
    async function (context) {
        try {
            const response = await axios.get('https://google.com');
            console.log('Request succeeded', response);
        } catch (err) {
            console.error('Request failed', error);
        }
    }
];
```

Or you can use promises instead.

```js
const axios = require('axios');
module.exports.requestHooks = [
    // Using promises
    function (context) {
        return new Promise((resolve, reject) => {
            axios.get('https://google.com')
                .then(function (response) {
                    console.log('Request succeeded', response);
                    resolve();
                })
                .catch(function (err) {
                    console.error('Request failed', err);
                    reject();
                });
        });
    }
];
```

I'm here if you have any more questions 😄

**Comment by hsanson** [comment]
@gschier thanks for the response. I managed to get my plugin working using the node-fetch npm package.
Just would like to mention that only your second example works. If we do not return a promise then insomnia will proceed with the request before node-fetch or axios completes getting the token and setting the headers.

**Comment by gschier** [comment]
@hsanson be sure you have included both the `async` and `await` keywords. In JavaScript, using async/await is functionally the same as returning and using promises.

I just tested with this example and it works as expected:

```js
const axios = require('axios');
module.exports.requestHooks = [
  async function (context) {
    try {
      const response = await axios.get('https://api.insomnia.rest/changelog.json');
      console.log('Changelog:', response.data);
      context.request.setHeader('X-Insomnia-Version', response.data[0].version);
    } catch (err) {
      console.error('Request failed', error);
    }
  }
];
```

Verified the correct header was sent using the Timeline tab.

```
> GET /?test=789 HTTP/1.1
> Host: api.insomnia.rest
> User-Agent: insomnia/5.14.9
> X-Insomnia-Version: 5.14.9
> Accept: */*
> Content-Length: 8
```

**Comment by gschier** [comment]
Closing this issue as you've solved your problem 😄
