### ISSUE TITLE
Slow and not responding when using the Git-Functions

### ISSUE THREAD

**Issue by SkonWodrich** [getinsomnia/insomnia#8017]
### Expected Behavior

It should be possible to use any Git-Function without slowing the whole workstation down

### Actual Behavior

when changing the branch, fetch or use any other git function the cpu and memory usage goes up to crazy amounts and using insomnia is not possible. 

Some things i noticed: 
- Only on the windows-version. linux does not slow down that hard. but it does. 
- When i switch the branch, close insomnia and open it again. the branch is switched. 

![image](https://github.com/user-attachments/assets/ee692852-c36f-467a-b4b8-31f14a9f0151)

### Reproduction Steps

1. Open Insomnia
2. switch branch / fetch / commit ....

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

it is a realy sad experience. we thought about switching from postman to insomnia with all our devs (40). After a 3 Month test i had to review 3 bugs after a update, that would be a desaster when we used it in production. at least the 50% windows-devs could not use the maintool for several days. we are still doing 3 month of testing. when this bugs are still that risky, we stay with postman.

### Insomnia Version

10.0.0

### What operating system are you using?

Windows

### Operating System Version

10 and 11

### Installation method

insomnia website executable / update

**Comment by CurryYangxx** [comment]
duplicate with #7946 

Hi @SkonWodrich, you can update to the latest beta version here to experience: https://github.com/Kong/insomnia/releases, we made some improvements for git sync in the beta version after 10.0. And we continue to optimize git performance and will release version 10.1 in two weeks which will have significant improvements.

**Comment by SkonWodrich** [comment]
![image](https://github.com/user-attachments/assets/2e3aa3a4-7904-4129-89cc-d74d9f2ab8c9)

I tried the beta. It is faster with the switch of branches, but the CPU and Memory consuption is the same / worse

**Comment by SkonWodrich** [comment]
i am pretty sure the is a memory-leak somewhere: 

![image](https://github.com/user-attachments/assets/49c30521-f087-4132-a410-d13d82c8d86c)
![image](https://github.com/user-attachments/assets/7ba709fe-cf11-49cb-8596-1538baa849f8)

it is not working like it should
