### ISSUE TITLE
[Bug] Double quotes in Curl body get stripped

### ISSUE THREAD

**Issue by ripley** [getinsomnia/insomnia#802]
- Insomnia Version: V5.14.9
- Operating System: Windows 10 Enterprise 2016 LTSB
## Details
The double quotes in post body got striped after copying a curl request from firefox web dev tool and paste into insomnia.

For example the body in curl request is like:
--data "{""numberReportDays"":1,""includePoolName"":true,""includeVirtualMachineName"":true}"

After pasting it's like:
{numberReportDays:1,includePoolName:true,includeVirtualMachineName:true}

In Mac and Linux client I didn't see this issue.

**Comment by gschier** [comment]
Can you provide a full curl request example that I could test with?

**Comment by gschier** [comment]
... I tried your specific example on Mac and Insomnia _did_ indeed remove the quotes because they are doubled up. 

I believe the snippet should look like this to work:

```
curl --data '{"numberReportDays":1,"includePoolName":true,"includeVirtualMachineName":true}` https://google.com
```

Or the quotes should be escaped:

```
curl --data "{\"numberReportDays\":1,\"includePoolName\":true,\"includeVirtualMachineName\":true}" https://google.com
```

**Comment by ripley** [comment]
I looked into it again and found this not necessarily issue of insomnia.

ON WINDOWS:

For a same request, different browser copied it to different formats, I mean right click on a request in browser's developer tool and select "Copy as curl".

**Firefox:**
  "Copy as curl":
      "{""numberReportDays"":1,""includePoolName"":true,""includeVirtualMachineName"":true}"

**Chrome:**
  "Copy as curl(cmd)":
 "^{^\^"numberReportDays^\^":1,^\^"includePoolName^\^":true,^\^"includeVirtualMachineName^\^":true^}"
  "Copy as curl(bash)":
 '{"numberReportDays":1,"includePoolName":true,"includeVirtualMachineName":true}' --compressed --insecure

Insomnia works fine for the last situation (copied as curl (bash)) and it's fair to only deal with that.

Maybe you would like to handle other situations, otherwise feel free to close this request.

Thanks !

**Comment by gschier** [comment]
Thanks for the info @ripley! 

That's quite strange. I'm not that familiar with Window command line so have a question about this. Does using an additional quote act as an escape character in Windows? ie. Does `"Hello ""World"""` translate to the string `Hello "World"`? On other platforms, quotes simply end the string, so `"Hello ""World"""` is the same as concatenating the strings `Hello `+ `World` + ` ` which turns into `Hello World`. 

This is the reason why Insomnia _strips_ out the quotes.

**Comment by ripley** [comment]
Thank you for the explanation @gschier 
I don't think request of that format makes sense either, seems the "copy as curl" function in firefox is bug prone, I saw related defect report in their website.

It's a wonderful feature of insomnia to allow pasting curl request! It's the best way I've used to edit a request (from a browser or my colleagues) and review the response.

**Comment by gschier** [comment]
I'm glad you like it! 😀

**Comment by Dhroov7** [comment]
@ripley Can you add the link here of the report on their website?

> Thank you for the explanation @gschier
> I don't think request of that format makes sense either, seems the "copy as curl" function in firefox is bug prone, I saw related defect report in their website.
> 
> It's a wonderful feature of insomnia to allow pasting curl request! It's the best way I've used to edit a request (from a browser or my colleagues) and review the response.
