### ISSUE TITLE
High CPU and memory consumption

### ISSUE THREAD

**Issue by SkonWodrich** [getinsomnia/insomnia#8020]
### Expected Behavior

like in https://github.com/Kong/insomnia/issues/8017

the beta is even worse now .. you closed the issue .. that i could not respond.

### Actual Behavior

I tried the beta like you asked me. 

the switch of branches is fast now. But CPU and esp. memory consumption is WAY WORSE! 

![Screenshot 2024-09-27 112452](https://github.com/user-attachments/assets/dc5b6cac-67b7-4a40-aa39-c01c8766d24e)
![Screenshot 2024-09-27 112739](https://github.com/user-attachments/assets/fbe980e2-bb7f-4e3f-90d4-f15e1845fcf3)
![Screenshot 2024-09-27 112819](https://github.com/user-attachments/assets/431c1f5f-0d86-416e-a3bc-5a24249c6a28)

There must be a memoryleak somewhere. it took 4 GB memory in 1 1/2 min .. then i closed insomnia. 

### Reproduction Steps

i tried the latest beta

switch branch, fetch, switch branch ... 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

latest beta 

### What operating system are you using?

Windows

### Operating System Version

10 and 11

### Installation method

insomnia website executable Beta!!

**Comment by subnetmarco** [comment]
@CurryYangxx

**Comment by jackkav** [comment]
@SkonWodrich could you give us some idea of how to reproduce what you are seeing? We've tried large collections but not seeing nearly 4GB of memory load. We've seen large API Specs and lots of nested folders causing performance issues in the past, curious what might be different in your case.

**Comment by SkonWodrich** [comment]
hello @jackkav . Thanks for the response .. i tried to get the memonry up lik ein my first test. I didnt manage to. "Only" around 2 GB and 70-80% cpu usage. But to be fair this was the the peak. I tried everythink around the git functions. I fetched (with the highest peak) i tried to switch branches from the server (250 MB selfhosted repo). we saved the insonia files in the repo.  everything looks ok ...  

![image](https://github.com/user-attachments/assets/58c5d757-bfb3-4305-b409-975e200197eb)

Now while i write u i have the same problem again ...  the memory consumptions wont stop. 9 GB and i closed insomnia. maybe some thing that is happening while insomnia is not in use an idling in the background.  

![image](https://github.com/user-attachments/assets/4aafa8b3-b099-443b-bae6-d33611c7e22c)

Is there a way to have a log or something? i could provide it.

**Comment by SkonWodrich** [comment]
opened it again. fetched and switched a branch and still: 
![image](https://github.com/user-attachments/assets/146bc3e0-baeb-4710-ac96-acb42f21ae11)

the only thing i noticed is the efficency mode from windows. the first time i open insomnia there it wasnt in the "efficency mode" mode .. after it switched the memory went up.

**Comment by jackkav** [comment]
https://docs.insomnia.rest/insomnia/application-data
Take a look for repeating errors or put it all in a gist, there should be a main and a render log

**Comment by SkonWodrich** [comment]
hey jack, nice profile pic. can i send u the logs via mail? i already tried to anonymise it. but you never know. :) @jackkav

**Comment by SkonWodrich** [comment]
Hey there, i found out, that it is strongly depending on a "larger" collection. When i am on the one collection insomnia is idleing ok. but when i  chekc out the other collction it is going up .. no matter what i do. @jackkav

**Comment by jackkav** [comment]
Sure jack at konghq dot com

High numbers of folders are a common cause of performance problems.

**Comment by SkonWodrich** [comment]
i cant change the ammount of folders in the project to suit insomnia. ;) do we have another solution?

**Comment by jackkav** [comment]
We're looking in to optimising the slow database query which causes this. Using git sync compounds it too. Are you using git or cloud sync in this collection?

**Comment by SkonWodrich** [comment]
git sync with a selfhosted gitlab.

**Comment by jackkav** [comment]
That explains it, our team is currently working on a git repo parsing optimisation to resolve this. Thanks for your patience.
