### ISSUE TITLE
[Feature Request] – Delete all parameters in 'query' tab

### ISSUE THREAD

**Issue by PierrickG34** [getinsomnia/insomnia#803]
- Insomnia Version: 5.12.4
- Operating System: Win 7

## Details
Hi ! 

When I use the 'Query' tab with a lot of parameters (~20-30) and I want to delete all, I have to delete them one by one, so 20*2 clicks = 40 clicks is a bit annoying!
Would it be possible to add an option to remove them all at once?
A bit like the button **'Import from Url'** at the bottom could have **'Delete all params'** ?

Thanks ! :)

**Comment by gschier** [comment]
Was holding off on this because I wasn't sure how to fit it in, but I think I have a solution now. What do you think of a new menu in the bottom-left?

![image](https://user-images.githubusercontent.com/587576/37942607-def00e52-3128-11e8-9eca-2bdc5ab6e418.png)

**Comment by PierrickG34** [comment]
Hello,

Thank you for your answer, yes I'm okay with this options it sounds good for me :)
