### ISSUE TITLE
I cant login to version 10.0.0

### ISSUE THREAD

**Issue by siegblade** [getinsomnia/insomnia#8034]
### Expected Behavior

Code received in email to approve login

### Actual Behavior

After several times trying, the code was not received

### Reproduction Steps

Login in web browser (easy)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.0.0

### What operating system are you using?

Windows

### Operating System Version

...

### Installation method

Default installer

**Comment by subnetmarco** [comment]
Hello, we are looking into this issue: closing in favor of https://github.com/Kong/insomnia/issues/8033#issuecomment-2387317172.

Seems to be a mail deliverability issue with our email provider.
