### ISSUE TITLE
[Bug] Template tag 'File' not working

### ISSUE THREAD

**Issue by EnilPajic** [getinsomnia/insomnia#804]
- Insomnia Version: 5.14.9
- Operating System: Windows 10, 64bit

## Steps to reproduce
1. Go to environment variables (in my case on specific folder: right click -> Environment)
2. Add a variable, key: value where value is a _File_ template tag. File is red because it is not configured.
3. Click on it to configure it, and select file:
![Image 1](https://user-images.githubusercontent.com/11429744/37208976-ba13c48a-23a3-11e8-8c07-0e4e69bd5f38.png)
Clearly selection is working because Live Preview is showing the right content. Also file `C:\WAMP\www\abc.txt` is public, so Insomnia can read it (proven by live preview).

4. Click _Done_ to save File configuration. And, File 'icon' is again red, this time with message `ENOENT: no such file or directory, open 'C:\Users\enilp\AppData\Local\insomnia\app-5.14.9\WAMPwwwabc.txt'`. It seems that the file path is appended to Insomnia's CWD, but without path separator?
![Image 2](https://user-images.githubusercontent.com/11429744/37208997-c6c79a12-23a3-11e8-829b-eb5edf45e662.png)

5. [Bonus] Again click on the File icon, and live preview is not working:
![Image 3](https://user-images.githubusercontent.com/11429744/37209006-d2ec1caa-23a3-11e8-86e1-15b3b175fdc5.png)

## Related issues
I did a search and found this issue (#757: [Bug] Can't load file for file token) that seems related but it is 24 days old and affects version 5.14.3.

**Comment by gschier** [comment]
Yes, this is the same issue as #757. Going to close this one as duplicate. Thanks for reminding me of this.

**Comment by keihuli** [comment]
Still Open
