### ISSUE TITLE
Application does not recognized login

### ISSUE THREAD

**Issue by ShadowDaneFoster** [getinsomnia/insomnia#8047]
### Expected Behavior

1. Launch app
2. Login 
3. Use app

### Actual Behavior

1. Launch app
2. Login
3. App doesn't recognize that I've logged in so I'm permanently stuck on the "Authorizing Insomnia" screen

### OR
1. Launch browser to app.insomnia.rest
2. Login
3. Click on workspace I want to use
4. App launches and doesn't recognize that I'm already logged in
5. App presents login dialog
6. I login
7. App still doesn't recognize that I've logged in so I'm permanently stuck on the "Authorizing Insomnia" screen

### Reproduction Steps

1. Launch app
2. Login

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.0.0

### What operating system are you using?

macOS

### Operating System Version

MacOS Ventura 13.7

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

9.3

**Comment by ShadowDaneFoster** [comment]
https://github.com/user-attachments/assets/67dc914a-1618-485b-b6fe-01484d0522c9

**Comment by juwan-jin** [comment]
I solved it by creating a new passphrase

**Comment by ShadowDaneFoster** [comment]
@juwan-jin The resetting passphrase dialog is saying I will lose access to the organizations I've been invited to. That's a non starter for me because that's where all my work is. 😞

**Comment by notjaywu** [comment]
@ShadowDaneFoster You can copy your passphrase and paste it into the passphrase dialog. The passphrase dialog seems to disappear automatically when you click on the 1password icon.

<img width="604" alt="image" src="https://github.com/user-attachments/assets/06e0f22d-a333-4451-b2a2-5120f30bdebf">

**Comment by notjaywu** [comment]
After that, you should see the `Launch Insomnia Desktop` dialog and click the `Launch` button. Then if you click the `Open` button, it will open the specific organization now.

<img width="607" alt="image" src="https://github.com/user-attachments/assets/62274e50-2c46-499f-8e52-1752310fffb9">

**Comment by ShadowDaneFoster** [comment]
@notjaywu Your instructions did the trick. Thank you! 😍
