### ISSUE TITLE
Missing Space in Import Dialog

### ISSUE THREAD

**Issue by miranyx** [getinsomnia/insomnia#8051]
### Expected Behavior

It would show "Error while scanning for resources to import: File is required"

### Actual Behavior

It shows "It would show "Error while scanning for resources to import:File is required""

### Reproduction Steps

1. click on postman
2. do not select a file
3. click on "Scan"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

https://github.com/Kong/insomnia/blob/9d76c80725af6e452ba6daa8c6a67f368db77ba3/packages/insomnia/src/ui/components/modals/import-modal.tsx#L539-L542

### Insomnia Version

10.1.0-beta.2

### What operating system are you using?

macOS

### Operating System Version

Darwin arm64 23.5.0

### Installation method

homebrew

**Comment by rohitpatilok** [comment]
Can i work on this issue?
