### ISSUE TITLE
[Feature Request] Support multi-line (display) for query parameter

### ISSUE THREAD

**Issue by thePanz** [getinsomnia/insomnia#806]
When editing a query request parameter, sometime the value is longer than the area to display it.
It becomes quite tedious moving among the line with the cursor to edit the value in the middle or the end of it.
Can the UI used to enter the value be made multi-line?

**Comment by gschier** [comment]
Hmm, it would be trivial to apply the same "Multi-Line" option used for form data (forgive me if that's what you meant). Sounds like a great idea!

**Comment by thePanz** [comment]
@gschier Yes, having the same UI used for the `form data` would be great! :)
Thanks!

**Comment by nzagorsky** [comment]
First of all I'd like to thank you for developing such a great product! It appears to be that this awesome feature that I've been relying on for past year seems to be disappeared now. What I have to do now is to copy previous requests created previously when feature were available and use them to work with multi-line parameters. 

Attaching screenshot to prove that this button no longer exists:
![image](https://user-images.githubusercontent.com/7213838/71900529-0c8e3a80-316f-11ea-871f-54eff43386bb.png)

**Comment by gschier** [comment]
Woops, not sure how that happened. Thanks for finding that!
