### ISSUE TITLE
[Question] It is possible to remove the  attribute “query” of the body of “payload” when selecting the “GraphQL” mode?

### ISSUE THREAD

**Issue by macndesign** [getinsomnia/insomnia#807]
- Insomnia Version: 5.14.9
- Operating System: Ubuntu 16.04 LTS

## Details

"message": "Syntax Error GraphQL request (1:2) Expected Name, found String \"query\"\n\n1: {\"**query**\"

**Comment by gschier** [comment]
Can you explain what you would like the body to be instead? Insomnia follows the  official GraphQL spec.

**Comment by macndesign** [comment]
of course.
For example: 
{ book(id: "09c97e60-5eb0-4c4a-bad1-15598ccba100") { id description } }
Insomnia inject:
{ query: { book(id: "09c97e60-5eb0-4c4a-bad1-15598ccba100") { id description } } }

**Comment by gschier** [comment]
Sorry for the delay! 

Is this custom behavior specific to your company? I've never seen GraphQL requests being sent like that. GraphQL requests are usually sent with a `variables` and `operationName` key as well. How do you send these fields in your server implementation?

http://graphql.org/learn/serving-over-http/#post-request
