### ISSUE TITLE
Insomnia won't start after importing kubernetes open-api spec.

### ISSUE THREAD

**Issue by damieneichhorn** [getinsomnia/insomnia#8074]
### Expected Behavior

I was hoping to import a openapi-json spec for kubernetes into insomnia as a document.

### Actual Behavior

After extracting the open-api json from my kubernetes cluster, I tried importing it and hoped to have everything show up in a document. However when clicked on it, it froze Insomnia and now i can no longer use insomnia as it just show blank pages.

![Screenshot 2024-10-14 at 08 34 34](https://github.com/user-attachments/assets/242926ab-a119-4f0f-b3a9-2c56d72ce1b9)
![Screenshot 2024-10-14 at 08 34 43](https://github.com/user-attachments/assets/e857ac98-fa2f-45c9-8109-35704e8a2bb3)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia 10.0.0

### What operating system are you using?

macOS

### Operating System Version

MacIOS Sequoia 15.0

### Installation method

Installed from the website

**Comment by CurryYangxx** [comment]
<img width="1172" alt="image" src="https://github.com/user-attachments/assets/68fc76b1-a753-4c7e-9cba-0efc27eabc57">
hi @damieneichhorn Can you click the view -> toggle dev tools, and see if there is any error in the console tab?

**Comment by damieneichhorn** [comment]
Hey @CurryYangxx, It doesn't show anything really and after a couple seconds it also goes to a fully white screen and says disconnected.

![Screenshot 2024-10-14 at 11 05 24](https://github.com/user-attachments/assets/75d6d01c-c834-4ab1-9747-b8c18c09b17c)


![Screenshot 2024-10-14 at 11 04 36](https://github.com/user-attachments/assets/f836b3c4-e888-4296-886e-72e0501e8d46)

**Comment by CurryYangxx** [comment]
Seems this spec file causes some performance issues. 
Can you join our Slack channel https://chat.insomnia.rest/, so we can DM you how to reproduce it, thanks.

**Comment by CurryYangxx** [comment]
Discuss in the Slack channel and the issue has been fixed. The problem is that the JSON file is not formatted and all the content is on the same line. It is ok when we use the formatted file.
