### ISSUE TITLE
[Help] Clear migration rules for Postman users

### ISSUE THREAD

**Issue by maciekdragan** [getinsomnia/insomnia#808]
I really want to try Insomnia, but don't have time to migrate all my Postman environment manually.

I need:
1. Docs about Insomnia for Postman users. What Postman actions are possible in Insomania, and what aren't. E.g. I'm using Postman runner, which greatly simplifies (automates) my work. I'll not migrate completly without it (nonetheless I'll consider using both if Insomnia meets rest of my expectations)

2. Better import from postman. I managed to import requests but what about:
- environments
- tests (scripts)

I just want to sit and start using Insomnia :)

**Comment by gschier** [comment]
Hey @maciekdragan, thanks for pointing out the lack of docs for this. I agree that there should be more info.

For now, I'll answer it here:

**Postman Runner**: Insomnia does not currently have anything similar and there aren't yet plans to do something similar.

**Scripts**: Similar answer to above. There aren't any plans to support scripting as a core feature. Most uses for scripting can either be covered by the [plugin system](https://support.insomnia.rest/article/26-plugins) or [request chaining](https://support.insomnia.rest/article/43-chaining-requests).

**Environments**: You can individually export Postman environments and import them into Insomnia. This is done from the environment manager using the Download Environment button.
