### ISSUE TITLE
Desktop logo is missing and showing electron logo

### ISSUE THREAD

**Issue by hannyiszoltan** [getinsomnia/insomnia#8092]
### Expected Behavior

Show the insomnia Logo

### Actual Behavior

Show the electron logo
![image](https://github.com/user-attachments/assets/9a1e52fe-5f75-4b77-a45f-1214c624eebc)

### Reproduction Steps

1. Open up insomnia desktop app on Windows OS

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

download from official website

**Comment by DJ-caddev** [comment]
+1
Updated to 10.1.0 and it broke the icon

**Comment by subnetmarco** [comment]
@filfreire

**Comment by subnetmarco** [comment]
Welp, we are making a patch release to fix this early next week in 10.1.1.

**Comment by filfreire** [comment]
Fix is ready here: https://github.com/Kong/insomnia/pull/8097

@hannyiszoltan thank you for reporting.
