### ISSUE TITLE
Inso CLI with --src option is giving error

### ISSUE THREAD

**Issue by ywidiastuti** [getinsomnia/insomnia#8098]
### Expected Behavior

--src should still work on Inso CLI

### Actual Behavior

Error on executing ./inso run test XXX --src ABC

### Reproduction Steps

![image](https://github.com/user-attachments/assets/238d8288-4ca9-4d63-a66b-cf1d998bb04c)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

9.3.2

**Comment by jackkav** [comment]
`-w` can be used in place of `--src` to pass in a file as a source of data.

**Comment by ywidiastuti** [comment]
`-w` solves my problem, thank you!
