### ISSUE TITLE
code generate error

### ISSUE THREAD

**Issue by xinshangshangxin** [getinsomnia/insomnia#810]
- Insomnia Version:  5.14.9 (5.14.9.1895) or 5.14.1
- Operating System: mac 10.13 (17A365)

## Details
if query same key is over three, generate code will be wrong,

![image](https://user-images.githubusercontent.com/8779091/37394081-e42d525a-27ad-11e8-9e4d-53b98b26391b.png)

![image](https://user-images.githubusercontent.com/8779091/37394204-39206428-27ae-11e8-84a1-e17cc5d105b0.png)

**Comment by xinshangshangxin** [comment]
@gschier any update?

**Comment by gschier** [comment]
Will take a look this week

**Comment by xinshangshangxin** [comment]
![image](https://user-images.githubusercontent.com/8779091/38187891-1e8c07f6-368c-11e8-942a-2708a2c4be5a.png)

@gschier 
5.15.0 not work

**Comment by gschier** [comment]
Got it. Just forgot to publish one of the dependent packages. Will get it fixed for the final release.

**Comment by gschier** [comment]
Should be good now, although you'll have to re-download and install the latest version since I published it under the same version number:

https://github.com/getinsomnia/insomnia/releases/tag/v5.15.0

**Comment by xinshangshangxin** [comment]
it worked, thanks
@gschier
