### ISSUE TITLE
Insomnia.Core-10.1.0.exe adding Electron icon to desktop on Win11 23H2

### ISSUE THREAD

**Issue by JHorvath-MaxetaTech** [getinsomnia/insomnia#8100]
### Expected Behavior

Running [Insomnia.Core-10.1.0.exe](https://github.com/Kong/insomnia/releases/download/core%4010.1.0/Insomnia.Core-10.1.0.exe) on any version of Windows, should NOT add an Electron icon to the desktop.

### Actual Behavior

Running [Insomnia.Core-10.1.0.exe](https://github.com/Kong/insomnia/releases/download/core%4010.1.0/Insomnia.Core-10.1.0.exe) on Windows 11 23H2 adds an Electron icon to the desktop (for some unknown reason).

### Reproduction Steps

1. Download [Insomnia.Core-10.1.0.exe](https://github.com/Kong/insomnia/releases/download/core%4010.1.0/Insomnia.Core-10.1.0.exe) on Windows 11 23H2 (other windows versions may also be affected).
2. Run Insomnia.Core-10.1.0.exe
3. Verify Electron icon is created on the desktop.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

Insomnia.Core-10.1.0.exe

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### Installation method

Download from https://github.com/Kong/insomnia/releases/download/core%4010.1.0/Insomnia.Core-10.1.0.exe

**Comment by n0spaces** [comment]
Same issue, also Windows 11 23H2. Looks like the Insomnia.exe icon was replaced with the default Electron icon.

Current icon (under `%LocalAppData%\insomnia` and `%LocalAppData%\insomnia\app-10.1.0`):
![image](https://github.com/user-attachments/assets/e7239b8b-bd56-42a9-9e26-20b3605723ec)

Previous `app-10.0.0` icon for reference:
![image](https://github.com/user-attachments/assets/c3cae350-bc35-495f-9951-207e763984a2)

**Comment by AsimAlam** [comment]
Hey, I think this issue is resolved. Please check this [#8092 ](https://github.com/Kong/insomnia/pull/8097).

**Comment by subnetmarco** [comment]
Yes, we will make a patch release shortly.
