### ISSUE TITLE
UnitTest folder is deleted on Git Commit/Push

### ISSUE THREAD

**Issue by ywidiastuti** [getinsomnia/insomnia#8102]
### Expected Behavior

UnitTest folder should stay on Git Commit/Push otherwise Inso CLI will throw error
`[Error: ENOENT: no such file or directory, scandir '../.insomnia/UnitTest']`

### Actual Behavior

UnitTest folder is deleted on Git Commit/Push and error is thrown on Inso CLI
`[Error: ENOENT: no such file or directory, scandir '../.insomnia/UnitTest']`

### Reproduction Steps

Git Commit and Push and see that all UnitTest is set to "null"
![image](https://github.com/user-attachments/assets/d32c59d4-ccfc-449a-ae78-b52309cc72ae)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

9.3.3

**Comment by ywidiastuti** [comment]
@gatzjames i saw your commit in here https://github.com/Kong/insomnia/pull/8095.

Will this fix the problem?

Currently Git has problem with "TESTS" tab i think, no changes is recognized in Git.

**Comment by gatzjames** [comment]
Hi @ywidiastuti you are right this is related and should be fixed in 10.1.1
