### ISSUE TITLE
Visual Preview does not display data

### ISSUE THREAD

**Issue by william-fireone** [getinsomnia/insomnia#8105]
### Expected Behavior

Prior to v10 of Insomnia I would see the JSON response data from sent requests

### Actual Behavior

After upgrading to v10 (including latest update to v10,1,0) the Visual Preview of the response data is displaying as an empty JSON array. Looking at the Raw Data tab shows that all the data did return from the query.  This had previously been reported and closed in issue #6813 

The GET request:
![image](https://github.com/user-attachments/assets/c221ef43-a206-4071-886f-9fff04195b34)

The Visual Preview tab content:
![image](https://github.com/user-attachments/assets/8ff83a06-6e17-43ea-9a22-28cfd50a8808)

The Raw Data tab content:
![image](https://github.com/user-attachments/assets/2eb800b0-bcc0-4571-ba0f-9d90957c4b20)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2 build 22631.4317

### Installation method

Through the insomnia auto updater

### Last Known Working Insomnia version

9.3.3

**Comment by notjaywu** [comment]
@william-fireone Could you share the headers of the response?

**Comment by cwangsmv** [comment]
@william-fireone  Could you pls check if there's any filter input in your response preview panel:
<img width="971" alt="Screenshot 2024-10-25 at 14 51 15" src="https://github.com/user-attachments/assets/b5c1be6b-fef3-4d7a-acb5-50d1c57028a1">

If there's any invalid json filter here, the preview will only show empty array

**Comment by william-fireone** [comment]
@cwangsmv Yes, that was it. I removed the filter, and it displayed the results properly. Thanks!
