### ISSUE TITLE
Some requests don't have history

### ISSUE THREAD

**Issue by pollux1314** [getinsomnia/insomnia#8112]
### Expected Behavior

Auto save response to history

### Actual Behavior

![image](https://github.com/user-attachments/assets/f9a41503-ceb8-452a-b332-76885bd91013)
No historic response for this request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

v10.1.0

### What operating system are you using?

Windows

### Operating System Version

win11

### Installation method

github release

### Last Known Working Insomnia version

v10.1.0

**Comment by ihexxa** [comment]
Hello @pollux1314 , have you checked "filter responses by environment" in the preference -> general ?

![image](https://github.com/user-attachments/assets/b76a1ae2-eec3-492f-bbbe-bc349242d16d)

**Comment by ihexxa** [comment]
Hey @pollux1314 I tend to close this as there seems no further feedback from your side.

**Comment by ihexxa** [comment]
Closing it as no further feedback.
