### ISSUE TITLE
[Question] File upload is copying file

### ISSUE THREAD

**Issue by pulse14** [getinsomnia/insomnia#812]
When I try to upload a file (10gbyte from a network folder on windows) the file seem to be copied in a temp folder. It causes disk to be quickly full.

**Comment by gschier** [comment]
Hey @pulse14,

This is correct. For multipart form requests, Insomnia builds each part and writes the whole body to the filesystem before sending. It should be deleting each one after the request is sent though. Can you confirm this?

**Comment by pulse14** [comment]
I think files, are not deleted if I cancel the upload or if I close the client.
But the problem is the fact files are not streamed directly. I don't have this problem with Postman.

**Comment by gschier** [comment]
Correct. I actually tried to implement streaming functionality early on but was prevented by the layer Insomnia uses to interact with `libcurl`. Hopefully this will be able to be resolved in the future.

**Comment by bukajsytlos** [comment]
+1, it would be really useful to directly stream files and dont mess with tmp
