### ISSUE TITLE
After the recent update, giving error ownerAccountId undefined

### ISSUE THREAD

**Issue by jnuthula** [getinsomnia/insomnia#8121]
### Expected Behavior

It should load properly

### Actual Behavior

TypeError: Cannot read properties of undefined (reading 'ownerAccountId') at InviteModalContainer (file:///C:/Users/u7mj8qa/AppData/Local/insomnia/app-10.1.0/resources/app.asar/mainWindow-Rjg7fX-s.js:1064:7596) at Nh (file:///C:/Users/u7mj8qa/AppData/Local/insomnia/app-10.1.0/resources/app.asar/mainWindow-Rjg7fX-s.js:43:18469) at cj (file:///C:/Users/u7mj8qa/AppData/Local/insomnia/app-10.1.0/resources/app.asar/mainWindow-Rjg7fX-s.js:45:3395) at Vk (file:///C:/Users/u7mj8qa/AppData/Local/insomnia/app-10.1.0/resources/app.asar/mainWindow-Rjg7fX-s.js:45:47812) at Uk (file:///C:/Users/u7mj8qa/AppData/Local/insomnia/app-10.1.0/resources/app.asar/mainWindow-Rjg7fX-s.js:45:42469) at Tk (file:///C:/Users/u7mj8qa/AppData/Local/insomnia/app-10.1.0/resources/app.asar/mainWindow-Rjg7fX-s.js:45:42399) at Ik (file:///C:/Users/u7mj8qa/AppData/Local/insomnia/app-10.1.0/resources/app.asar/mainWindow-Rjg7fX-s.js:45:42252) at Nk (file:///C:/Users/u7mj8qa/AppData/Local/insomnia/app-10.1.0/resources/app.asar/mainWindow-Rjg7fX-s.js:45:38395) at Gk (file:///C:/Users/u7mj8qa/AppData/Local/insomnia/app-10.1.0/resources/app.asar/mainWindow-Rjg7fX-s.js:45:37273) at wt (file:///C:/Users/u7mj8qa/AppData/Local/insomnia/app-10.1.0/resources/app.asar/mainWindow-Rjg7fX-s.js:30:1726) at Immediate.jt [as _onImmediate] (file:///C:/Users/u7mj8qa/AppData/Local/insomnia/app-10.1.0/resources/app.asar/mainWindow-Rjg7fX-s.js:30:2135) at process.processImmediate (node:internal/timers:483:21)### 

### Reproduction Steps

restart after the update, it show the above error

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

inomnia auto update

### Last Known Working Insomnia version

10.0.0

**Comment by yaoweiprc** [comment]
I'll take a look.

**Comment by yaoweiprc** [comment]
Please try 10.2 beta. https://github.com/Kong/insomnia/releases/tag/core%4010.2.0-beta.0
If you can still reproduce this bug, feel free to reopen this issue.
