### ISSUE TITLE
After update to 10.1.0 insomnia become unresponsive

### ISSUE THREAD

**Issue by brzezinol** [getinsomnia/insomnia#8124]
### Expected Behavior

Start and be responsive. 
What is solution to clear last response for app be responsive?

### Actual Behavior

After start, last request is loaded with 60kB json and it freezes.

![image](https://github.com/user-attachments/assets/ebdffc01-23d8-4f87-b106-a193953628fc)

### Reproduction Steps

1. start app
2. make request with big response
3. restart app

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

![image](https://github.com/user-attachments/assets/9ea72203-4508-4475-b4f3-4bc81c896f3b)

### Insomnia Version

10.1.0

### What operating system are you using?

Windows

### Operating System Version

Win 10

### Installation method

download from https://insomnia.rest/

### Last Known Working Insomnia version

before 10.1.0

**Comment by verglor** [comment]
I have the same problem - it never happened before the update.

**Comment by subnetmarco** [comment]
We just made a new `10.1.1` patch release, can you try with the latest version? @gatzjames for visibility.

**Comment by brzezinol** [comment]
> We just made a new `10.1.1` patch release, can you try with the latest version? @gatzjames for visibility.

Still the same problem:
![image](https://github.com/user-attachments/assets/0a63baba-8570-4584-8ea8-9250a3ef0347)

**Comment by subnetmarco** [comment]
Do you see this slowness when using Git Sync, or in general?

@yaoweiprc @CurryYangxx @gatzjames what have we changed in 10.1.x that could have affected performance?

**Comment by yaoweiprc** [comment]
@verglor @brzezinol Does the collection which holds the last request turn on git sync?

**Comment by yaoweiprc** [comment]
@brzezinol I can not reproduce it. Can you share me the response data?

**Comment by brzezinol** [comment]
> @verglor @brzezinol Does the collection which holds the last request turn on git sync?

I don't use any synchronization.

I think problem is not strictly related to insomnia update.
I got such behavior in previous versions too when I manipulate option of response visibility mode. Raw, Beautify etc.
After update to 10.1.x I have problem with login, some issue is reported too by somebody.
With prev versions if problem exists I can change query to another with non blocking response and Insomnia was responsive.
Now I cannot switch to another query, and I stuck with broken query witout any way to clear it.

Where insomnia stores actually loaded queries? Maybe I could clear or reload it?

**Comment by brzezinol** [comment]
> @brzezinol I can not reproduce it. Can you share me the response data?

Sample response in file attached.
[route (14).json](https://github.com/user-attachments/files/17544754/route.14.json)

**Comment by brzezinol** [comment]
I fixed problem by delete insomnia.Response.db file.

**Comment by notjaywu** [comment]
> I have the same problem - it never happened before the update.

@verglor did you encounter the same problem that some request has too many big responses?

**Comment by yaoweiprc** [comment]
> > @brzezinol I can not reproduce it. Can you share me the response data?
> 
> Sample response in file attached. [route (14).json](https://github.com/user-attachments/files/17544754/route.14.json)

I tried with this big json file as response and upgraded from 10.0.0 to 10.1.1. The response preview screen loads normally after restart. Based on the existing information, I am unable to reproduce this issue. I will close this issue for now. If the same problem occurs in the future, feel free to open a new issue.
