### ISSUE TITLE
Local Variables Feature (Request Scope)

### ISSUE THREAD

**Issue by pgorin** [getinsomnia/insomnia#813]
Hi guys!

First of all, congrats for the application. It's awesome! I have been using Postman as my primary rest client for a long but after started using Insomnia there is no chance for other application jejeje!

I don't know if already exists a feature like this, but I think that will be great if you can use variables on a request scope. I mean, I can use environment scoped variables but I'm wondering if you can just define and use local variables for a given request (for example an entity ID used in the URL can be a local variable just for the underlying request,......using environment scope will be a bit confusing I think).

I hope you can understand the feature I'm proposing, and, if you can jaja, help to improve a little Insomnia!

Again, congrats for the excellent work!
Patricio.

**Comment by gschier** [comment]
This is a pretty popular request. It is also being discussed in #203. Going to close this one as a duplicate.

**Comment by gschier** [comment]
P.S. I'm glad you're enjoying the app! That me happy to hear 😄
