### ISSUE TITLE
Insomnia does not create an application shortcut

### ISSUE THREAD

**Issue by anzor1qqqqq** [getinsomnia/insomnia#8138]
### Expected Behavior

must create an application shortcut

### Actual Behavior

insomnia does not create an application shortcut and not only on the desktop, but even it does not exist on the PC itself

### Reproduction Steps

download insomnia -> CRITICAL BAGS!

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

![Снимок экрана 2024-10-29 102638](https://github.com/user-attachments/assets/61cc66d5-3024-4773-95c2-2988f49a4884)

### Insomnia Version

10.10

### What operating system are you using?

Windows

### Operating System Version

windows 10

### Installation method

official site

### Last Known Working Insomnia version

9.1.1

**Comment by anzor1qqqqq** [comment]
insomnia opens only when I click on the exe extension file

**Comment by anzor1qqqqq** [comment]
![Снимок экрана 2024-10-29 102638 — ярлык lnk](https://github.com/user-attachments/assets/11e095ad-e6cc-44f6-832b-65b44ae72fcd)

**Comment by anzor1qqqqq** [comment]
I found the folder with the application, but it runs only inside this folder
if I try to take the application to the desktop and run it, nothing will happen

**Comment by subnetmarco** [comment]
@filfreire

**Comment by anzor1qqqqq** [comment]
a day later, everything worked by itself. Thank you for the self-directed timely

**Comment by anzor1qqqqq** [comment]
thank
