### ISSUE TITLE
[Bug] Incorrectly de-escapes escaped slashes

### ISSUE THREAD

**Issue by richie5um** [getinsomnia/insomnia#814]
- Insomnia Version: 5.14.9
- Operating System: Windows 10

## Details

If I add a string to an environment that is escaping slashes, those get incorrectly deescaped when I re-open the environment editor.

i.e.:
{ "string": "\\\u003ccc" }

**Comment by gschier** [comment]
I'll see if I can get this fixed!

**Comment by richie5um** [comment]
Fantastic. Thank you!

**Comment by gschier** [comment]
No problem! Will be included in the next release
