### ISSUE TITLE
I can not copy bearer token from request to another request

### ISSUE THREAD

**Issue by DamirShaniiazov** [getinsomnia/insomnia#8145]
### Expected Behavior

Open the request, copy the token, paste it into another request

### Actual Behavior

I open the request, I try to copy it, but it doesn't copy

### Reproduction Steps

1. select an existing query
2. go to the Auth (bearer) tab
3. I copy the value from the token field
4. I open another request
5. open the Auth (bearer) tab
6. Nothing is inserted or the old value is inserted from the buffer

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.10.1

### What operating system are you using?

macOS

### Operating System Version

Mac OS Sonoma 14.6.1 (23G93)

### Installation method

from site

**Comment by russtam** [comment]
Same problem.
Version: Insomnia 10.1.1
Build date: 24.10.2024
OS: Windows_NT x64 10.0.19044
Electron: 31.4.0
Node: 20.16.0
Node ABI: 125
V8: 12.6.228.30-electron.0
Architecture: x64

**Comment by https-eduardo** [comment]
Hi Guys, I was having the same problem. I opened a pull request to fix this issue.

**Comment by banana-bread** [comment]
+1
