### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by tema32rus2000** [getinsomnia/insomnia#8146]
### Expected Behavior

I wanted to install insomnia

### Actual Behavior

I downloaded core and runned, got error and this file
[SquirrelSetup.log](https://github.com/user-attachments/files/17590139/SquirrelSetup.log)

### Reproduction Steps

1. Run "Insomnia.Core-10.2.0-beta.1.exe"
2. Error, got file 
[SquirrelSetup.log](https://github.com/user-attachments/files/17590083/SquirrelSetup.log)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

10.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22H2

### Installation method

downloaded from insomnia.rest

### Last Known Working Insomnia version

None

**Comment by filfreire** [comment]
Similar to https://github.com/Kong/insomnia/issues/7743

**Comment by godfrzero** [comment]
Closing in favor of #7743.
