### ISSUE TITLE
[Improvement] Ability to cancel "prompt" tag

### ISSUE THREAD

**Issue by supersonicclay** [getinsomnia/insomnia#815]
- Insomnia Version: 5.14.9
- Operating System: Mac OS 10.13.3 

## Repro
Insert a prompt into a request
Send request

## Actual Result
No way to cancel request once prompt shows

## Expected Result
User should be able to cancel the prompt by hitting ESC and/or clicking a cancel button and/or clicking a close button.

**Comment by gschier** [comment]
Hey @supersonicclay. 

What would you expect to happen after clicking cancel? Should the request also cancel, or should the prompt return a `null` value?

**Comment by supersonicclay** [comment]
I would expect it to just cancel the request. A use case that prompted me to create the ticket is building up a set of requests. I wanted to preview what the prompt dialog would look like, but didn't want to actually issue the request. I think another use case is someone that is exploring an API and based on the prompt message (e.g. "Enter the ID you want to DELETE") may have another opportunity to cancel the request.

**Comment by gschier** [comment]
Ya I think that makes sense too. If this is an easy change I'll include it in the next release 😄

**Comment by gschier** [comment]
Was implemented in https://github.com/getinsomnia/insomnia/commit/d0d6c4b57fb2b6654553317160737057d2a38da8
