### ISSUE TITLE
Can't resolve *.localhost

### ISSUE THREAD

**Issue by LausEquites** [getinsomnia/insomnia#8160]
### Expected Behavior

If I make a request to http://test.localhost or any other subdomain to .localhost it should resolve to 127.0.0.1 as specified in RFC 6761 part 6.3 (https://www.rfc-editor.org/rfc/rfc6761#section-6.3)

### Actual Behavior

I get the following error: "Could not resolve host: test.localhost"

### Reproduction Steps

1. Make a request to http://test.localhost
2. See you get "Could not resolve host: test.localhost"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

It works fine in Firefox and with curl in the terminal `curl -v http://test.localhost`

### Insomnia Version

10.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Sequoia 15.1

### Installation method

Download from insomnia.rest

**Comment by filfreire** [comment]
@LausEquites thanks for reporting, we're working on a [fix for it here](https://github.com/Kong/node-libcurl/pull/70)

We'll update this ticket when fix is merged into Insomnia.

**Comment by filfreire** [comment]
@LausEquites fix for this will go out in next beta/GA release

**Comment by LausEquites** [comment]
Awesome! You guys rock :)
