### ISSUE TITLE
Cannot Receive Emails

### ISSUE THREAD

**Issue by sem6x3ag** [getinsomnia/insomnia#8173]
### Expected Behavior

Email should be send so I can access my account.

### Actual Behavior

I open Insomnia and I am brought to a website https://app.insomnia.rest/app/authorize. I enter my email address, and it says it sends me an email and wants me to put in a code. I never receive the email and cannot access my data that I spent months writing. The is a free account. How do I get access to this account again? 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [ ] Insomnia Cloud sync.
- [X] Local only

### Insomnia Version

Unknown. Cannot launch it.

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

Website

**Comment by notjaywu** [comment]
Can you check your spam folder?

**Comment by filfreire** [comment]
@sem6x3ag besides checking spam folder, please send an email to [support@insomnia.rest](mailto:support@insomnia.rest) so we can confirm if the email you're trying to use for login is on our email bounce list.

**Comment by subnetmarco** [comment]
Closing as we are moving this to the support channel.
