### ISSUE TITLE
[Question] Data transformation pipeline plugin

### ISSUE THREAD

**Issue by nmaro** [getinsomnia/insomnia#818]
I'd like to know if anyone else is interested in a feature like this. Right now the structure of insomnia is this:

* request1
  * result 1
  * result 2
* request2
  * result 1
  * result 2

imagine now that you can transform each result with a javascript function that you can write, and do so recursively. You would then get something like this:

* request1
  * result 1.1
    * transform: data => data.filter(x => ...), result 1.1.1
      * transform: data => data.length, result 1.1.1.1
  * result 1.2
    * transform: ..., result 1.2.1
* request2
   * result 2.1
   * result 2.2

We found it useful to be able to transform the results we get to analyze the data we get.

A follow-up question would be: does the current plugin API allow for a feature like this?

**Comment by carlskii** [comment]
Yes I would be interested in this. I'm trying to build a simple experimental plugin that iterates over some JSON data and converts it to a CSV. Any pointers here would be useful.
