### ISSUE TITLE
Unable to Import Postman Collection

### ISSUE THREAD

**Issue by nistee-so** [getinsomnia/insomnia#8188]
### Expected Behavior

The Postman collection should import successfully into Insomnia without any errors.

### Actual Behavior

When attempting to import the Postman collection, Insomnia does not recognize the file and fails to import it.

### Reproduction Steps

1. Go to File > Import > From URL
2. Enter the URL: https://raw.githubusercontent.com/emartech/developer-hub-public-assets/master/resources/EmarsysV2PostmanCollection.json
3. Click Scan
4. Observe the error message indicating the file is not recognized
<img width="935" alt="image" src="https://github.com/user-attachments/assets/9638ffa8-8207-492a-bddd-a56097d820fd">

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [ ] Insomnia Cloud sync.
- [X] Local only

### Additional Information

The Postman collection is in v2.0 format, which should be compatible with Insomnia. The issue persists despite multiple attempts and verifying the file format.

### Insomnia Version

Insomnia 10.1.1

### What operating system are you using?

macOS

### Operating System Version

Darwin x64 24.1.0

### Installation method

homebrew

### Last Known Working Insomnia version

/

**Comment by notjaywu** [comment]
@yaoweiprc take a look at this issue

**Comment by yaoweiprc** [comment]
It looks that this format is of Postman Collection Format v2.0, while we support importing Postman Collection Format v2.1 well.
You can import it in Postman and re-export it as Collection v2.1 format, then you can import the new file in Insomnia.
![image](https://github.com/user-attachments/assets/f3509380-7eec-4cb7-a0b9-931c357d3b1d)
