### ISSUE TITLE
Application Error Failed to render: Cannot read properties of undefined (reading 'ownerAccountId')

### ISSUE THREAD

**Issue by shifoc** [getinsomnia/insomnia#8202]
### Expected Behavior

to open the App

### Actual Behavior

TypeError: Cannot read properties of undefined (reading 'ownerAccountId') at InviteModalContainer

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [ ] Insomnia Cloud sync.
- [X] Local only

### Insomnia Version

10.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

insomnia.rest

**Comment by notjaywu** [comment]
@shifoc Can you upgrade to the latest v10.2 and retry?

**Comment by notjaywu** [comment]
Similar to #8121

**Comment by shifoc** [comment]
it's fixed thanks
