### ISSUE TITLE
Error: Timeout: Running script took too long

### ISSUE THREAD

**Issue by NatanB4** [getinsomnia/insomnia#8217]
### Expected Behavior

I'm trying make a request with a Pre-request script but i recipe an error "Error: Timeout: Running script took too long" 

![image](https://github.com/user-attachments/assets/8e628d50-2873-4864-9f12-a81152db3c28)

### Actual Behavior

My script is lazy for load and insomnia has a timeout preset config that i don't know how change.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [ ] Insomnia Cloud sync.
- [X] Local only

### Insomnia Version

10.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Installation method

insomnia.rest

**Comment by notjaywu** [comment]
@NatanB4 do you mean `Request timeout` in the `Preferences`?
<img width="794" alt="image" src="https://github.com/user-attachments/assets/17abb76c-c53a-48b4-9c3a-69cfbb19e712">

**Comment by NatanB4** [comment]
I’m setting this 'timeout' config to 0. It should not run correctly, right?

**Comment by notjaywu** [comment]
You can set it with a proper value. The default value should be 30000 (ms).

**Comment by ihexxa** [comment]
Will take a look at the case of timeout=0 which is abnormal and please work around temporarily as @notjaywu mentioned.

**Comment by NatanB4** [comment]
> Will take a look at the case of timeout=0 which is abnormal and please work around temporarily as @notjaywu mentioned.

In the case of timeout=300000 run normally thanks.

@ihexxa @notjaywu

**Comment by notjaywu** [comment]
thanks for your update @NatanB4
