### ISSUE TITLE
Git error ("Index file is empty (.git/index)") on pull, no changes showed in commit window

### ISSUE THREAD

**Issue by solorisx** [getinsomnia/insomnia#8222]
### Expected Behavior

Pull works without errors, commit window shows actual changes

### Actual Behavior

Pull fails with this error:
An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)
![image](https://github.com/user-attachments/assets/455c3673-9056-4b28-b767-eacd84e70a4e)

Commit window shows no changes
![image](https://github.com/user-attachments/assets/db9e4d41-b3d1-4312-a6e9-532989696d3b)

Push shows "Nothing to push" (which makes sense if nothing is committed)

Error occurred first with 10.1.0, upgrade to 10.2.0 did not solve the problem - neither did creating a new branch. Checkout of an existing branch shows the same error as on Fetch.

### Reproduction Steps

1. Create new branch from main
2. Add new requests
3. Click on commit or fetch

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [X] Git sync.
- [ ] Insomnia Cloud sync.
- [ ] Local only

### Insomnia Version

10.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise, build 19045.5131

### Installation method

exe from github

**Comment by yaoweiprc** [comment]
Does this bug occur in any git repo or especially in your repo?

**Comment by solorisx** [comment]
This does occur in a specific repo (although other users do not experience the same error with the same repo). Other repos work fine for me.

**Comment by yaoweiprc** [comment]
It seems that your git index file was damaged. Could you try to git clone the repo again and  work on the new file?
![image](https://github.com/user-attachments/assets/db0802e2-36b7-42f4-8ee9-e673d3f85985)

**Comment by yaoweiprc** [comment]
I'll close it for now, feel free to reopen it if you need more help.
