### ISSUE TITLE
Local folder paths to certificates no longer displayed on mouse hover

### ISSUE THREAD

**Issue by AdiDil** [getinsomnia/insomnia#8231]
### Expected Behavior

Hovering over the document icon in the 'Manage Certificates' menu displays the local folder path of the certificate

### Actual Behavior

Hovering over the icon of the file icon in the certificate management screen no longer displays the path to the certificate.
This is very frustrating when there are multiple certificates set up for the same domain, as there's no other way to tell which certificate is which.

![image](https://github.com/user-attachments/assets/fbdd37ec-427d-45fd-a07c-35e391cb43eb)

### Reproduction Steps

1. Add any certificate to the collection
2. Open the Manage Certificates menu
3. Hover over the file icon

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [X] Insomnia Cloud sync.
- [ ] Local only

### Additional Information

This was working fine prior to version 10.2.0

### Insomnia Version

10.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise

### Installation method

Download from Insomnia

### Last Known Working Insomnia version

Not sure which version was prior to 10.2.0, but it worked fine before this version

**Comment by ryan-willis** [comment]
Thanks for the report @AdiDil, we have a fix ready to go that will be available when we release 10.2.1
