### ISSUE TITLE
CTLR+enter doesn't send the request after selecting the request from the left menu.

### ISSUE THREAD

**Issue by ppazos** [getinsomnia/insomnia#8238]
### Expected Behavior

When I select a request, I want to CTRL+enter to send the request.

### Actual Behavior

I need to click in the middle column (request details) to make the CTRL+enter to work.

### Reproduction Steps

1. create a request
2. create another request
3. on the request list (left menu) click on the first request created
4. now CTRL+enter
5. that doesn't fire the request
6. now click on the request details (middle column)
7. now CTRL+enter
8. that fires the request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [ ] Insomnia Cloud sync.
- [X] Local only

### Additional Information

I use Linux Mint which is based on Ubuntu.

### Insomnia Version

2023.5.8

### What operating system are you using?

Other Linux

### Operating System Version

Linux Mint 21.3

### Installation method

mint software manager, I guess it uses apt internally

**Comment by godfrzero** [comment]
Thanks for reporting this issue, @ppazos! I think we can track this on #8163 as it's the same underlying issue, and both symptoms will be addressed by the same fix. Closing this issue to avoid tracking duplicates.
