### ISSUE TITLE
Depending on position of your folders, you can not open the context menu because of automatic click on the item available

### ISSUE THREAD

**Issue by JanVerstuyft** [getinsomnia/insomnia#8242]
### Expected Behavior

No automatic click should be done on the menu item that is by accident just on your mouse pointer

### Actual Behavior

When the context menu is positioned on a place where your mouse pointer is just hovering, it will automatically click on that.

### Reproduction Steps

1. Position your folder from the collections at a point where the context menu area overlapps the current "dropdown button". 
2. Click on the arrow done button to open the context menu.
3. [screen-capture (2).webm](https://github.com/user-attachments/assets/617126c6-dc3a-4a97-8e4a-b61a1d03c3f6)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [ ] Insomnia Cloud sync.
- [ ] Local only

### Insomnia Version

10.2.0

### What operating system are you using?

Windows

### Operating System Version

Version: Insomnia 10.2.0 Build date: 27/11/2024 OS: Windows_NT x64 10.0.22000 Electron: 31.4.0 Node: 20.16.0 Node ABI: 125 V8: 12.6.228.30-electron.0 Architecture: x64

### Installation method

downloaded from the website

**Comment by godfrzero** [comment]
I just checked and this is happening on macOS as well.

**Comment by IV-R** [comment]
The issue you’ve referenced, Kong/insomnia#8242, describes a problem where the context menu in the Insomnia application inadvertently triggers a click on a menu item if the mouse pointer is positioned over it when the menu appears.

Proposed Solution:

To address this issue, the application should be modified to ensure that the context menu does not automatically select or activate any menu item upon opening, regardless of the mouse pointer’s position.

Implementation Steps:
	1.	Prevent Automatic Selection on Open:
	•	Modify the context menu component to ensure that no menu item is pre-selected or highlighted when the menu is first rendered.
	•	Ensure that menu items are only highlighted or selected in response to explicit user actions, such as mouse movements or keyboard navigation.
	2.	Handle Mouse Events Appropriately:
	•	Ensure that the context menu only responds to deliberate user interactions, such as clicking on a menu item after the menu has been opened.
	•	Implement event handling to prevent unintended clicks or selections when the menu is displayed.
	3.	Test Across Different Scenarios:
	•	Test the context menu behavior in various scenarios to ensure that it does not automatically select or activate any menu items upon opening.
	•	Verify that the menu behaves correctly when opened in different positions on the screen and with varying numbers of menu items.

Next Steps:
	•	Implement the Fix:
	•	Developers should implement the changes as described to prevent the context menu from automatically selecting or activating any menu items upon opening.
	•	Submit a Pull Request:
	•	Once the fix has been implemented and tested, submit a pull request to the Kong/insomnia repository for review.
	•	Review and Merge:
	•	The maintainers will review the pull request, and upon approval, merge it into the main codebase.

By following these steps, the issue can be resolved, ensuring that the context menu in the Insomnia application behaves as expected without inadvertently triggering actions upon opening.
