### ISSUE TITLE
No GraphQL options

### ISSUE THREAD

**Issue by OutOfDo** [getinsomnia/insomnia#8248]
I don't see any GraphQL options. I've clicked all over the + sign, the POST, right clicked, etc. Why am I not seeing any mention of GraphQL?

**Comment by subnetmarco** [comment]
You can create a GraphQL request within a collection:

![Screenshot 2024-12-11 at 11 53 07 AM](https://github.com/user-attachments/assets/8dbd1546-b37b-4f16-8b29-16fbc40f2c9d)
