### ISSUE TITLE
[Development] Build fails with "lerna ERR! execute callback with error"

### ISSUE THREAD

**Issue by BakirRabiaSalma** [getinsomnia/insomnia#826]
- Insomnia Version: ___ 5.14.9
- Operating System: ___win

## Details
I  get this error when i try to run insomia : whith the first command   npm run bootstrap
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\fathi.fathi-PC\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'bootstrap' ]
2 info using npm@5.7.1
3 info using node@v8.9.4
4 verbose run-script [ 'prebootstrap', 'bootstrap', 'postbootstrap' ]
5 info lifecycle insomnia@1.0.0~prebootstrap: insomnia@1.0.0
6 info lifecycle insomnia@1.0.0~bootstrap: insomnia@1.0.0
7 verbose lifecycle insomnia@1.0.0~bootstrap: unsafe-perm in lifecycle true
8 verbose lifecycle insomnia@1.0.0~bootstrap: PATH: C:\Users\fathi.fathi-PC\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\fathi.fathi-PC\Documents\postman\insomnia-master_complet\node_modules\.bin;C:\oracle\product\10.2.0\db_13\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Java\jre1.8.0_77\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Users\fathi.fathi-PC\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SDKs\Azure\CLI\wbin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;c:\Program Files\Microsoft SQL Server\110\DTS\Binn\;c:\Program Files\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Brackets\command;C:\Users\fathi.fathi-PC\AppData\Local\Microsoft\WindowsApps;C:\Users\fathi.fathi-PC\AppData\Roaming\npm
9 verbose lifecycle insomnia@1.0.0~bootstrap: CWD: C:\Users\fathi.fathi-PC\Documents\postman\insomnia-master_complet
10 silly lifecycle insomnia@1.0.0~bootstrap: Args: [ '/d /s /c', 'lerna bootstrap && lerna run rebuild' ]
11 silly lifecycle insomnia@1.0.0~bootstrap: Returned: code: 1  signal: null
12 info lifecycle insomnia@1.0.0~bootstrap: Failed to exec bootstrap script
13 verbose stack Error: insomnia@1.0.0 bootstrap: `lerna bootstrap && lerna run rebuild`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\fathi.fathi-PC\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\fathi.fathi-PC\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid insomnia@1.0.0
15 verbose cwd C:\Users\fathi.fathi-PC\Documents\postman\insomnia-master_complet
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fathi.fathi-PC\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "bootstrap"
18 verbose node v8.9.4
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error insomnia@1.0.0 bootstrap: `lerna bootstrap && lerna run rebuild`
22 error Exit status 1
23 error Failed at the insomnia@1.0.0 bootstrap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by gschier** [comment]
Hey @BakirRabiaSalma,

I'm not really sure what this could be since there is no description message in the above error.

After some Googling I found that most people with a similar error were behind some sort of corporate proxy/firewall. Is this the case for you?

**Comment by saiedkia** [comment]
any one any solution?
same problem here
node: v8.12.0
npm: 6.4.1
windows: 10

**Comment by Thejas007** [comment]
Facing the same issue. 

PS C:\OpenSource\insomnia> npm run bootstrap

> insomnia@1.0.0 bootstrap C:\OpenSource\insomnia
> npm install && lerna bootstrap && lerna run --parallel --stream bootstrap

npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\OpenSource\insomnia\node_modules\@babel\cli\node_modules\fsevents\node_modules'
npm WARN babel-loader@8.0.5 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\@babel\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 907723 packages in 13.404s
found 8 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
lerna notice cli v3.13.4
lerna info versioning independent
lerna info Bootstrapping 20 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in 'insomnia-libcurl'
lerna ERR! npm install stdout:

> insomnia-node-libcurl@2.0.0-alpha.0-1 install C:\OpenSource\insomnia\packages\insomnia-libcurl\node_modules\insomnia-node-libcurl
> node-pre-gyp install --fallback-to-build

Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\OpenSource\insomnia\packages\insomnia-libcurl\node_modules\insomnia-node-libcurl\lib\binding\node_libcurl.node --module_name=node_libcurl --module_path=C:\OpenSource\insomnia\packages\insomnia-libcurl\node_modules\insomnia-node-libcurl\lib\binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

lerna ERR! npm install stderr:
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.0.0-alpha.0-1/node_libcurl-v2.0.0-alpha.0-1-node-v64-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for insomnia-node-libcurl@2.0.0-alpha.0-1 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\OpenSource\\insomnia\\packages\\insomnia-libcurl\\node_modules\\insomnia-node-libcurl\\lib\\binding\\node_libcurl.node" "--module_name=node_libcurl" "--module_path=C:\\OpenSource\\insomnia\\packages\\insomnia-libcurl\\node_modules\\insomnia-node-libcurl\\lib\\binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd C:\OpenSource\insomnia\packages\insomnia-libcurl\node_modules\insomnia-node-libcurl
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\OpenSource\insomnia\packages\insomnia-libcurl\node_modules\insomnia-node-libcurl\lib\binding\node_libcurl.node --module_name=node_libcurl --module_path=C:\OpenSource\insomnia\packages\insomnia-libcurl\node_modules\insomnia-node-libcurl\lib\binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\OpenSource\insomnia\packages\insomnia-libcurl\node_modules\insomnia-node-libcurl\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\OpenSource\\insomnia\\packages\\insomnia-libcurl\\node_modules\\insomnia-node-libcurl\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\OpenSource\insomnia\packages\insomnia-libcurl\node_modules\insomnia-node-libcurl
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
npm WARN insomnia-libcurl@0.0.27 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insomnia-node-libcurl@2.0.0-alpha.0-1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the insomnia-node-libcurl@2.0.0-alpha.0-1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thejas\AppData\Roaming\npm-cache\_logs\2019-05-08T05_58_30_583Z-debug.log

lerna ERR! npm install exited 1 in 'insomnia-libcurl'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insomnia@1.0.0 bootstrap: `npm install && lerna bootstrap && lerna run --parallel --stream bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the insomnia@1.0.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thejas\AppData\Roaming\npm-cache\_logs\2019-05-08T05_58_30_863Z-debug.log

**Comment by gschier** [comment]
@Thejas007 

Your error message is more clear. You need to have Python installed.

```
...
stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
...
```

**Comment by Thejas007** [comment]
@gschier Thanks for noticing it. 

I was thinking npm will resolve all dependencies and runs the app smoothly. 

After fixing python issue , start getting vcbuild.exe not found issue. Looks like other dependecies needs few more dev tools before run. 

Is there any set of dev tools to be installed before running npm run bootstrap?

**Comment by gschier** [comment]
On Windows and Linux, there are not usually any other required steps. I thought that I had outlined the Windows-specific steps on the README but I must have misremembered.

The library that causes these failures is node-libcurl, which lists an NPM module that will setup what you need automatically: https://github.com/JCMais/node-libcurl#building-on-windows

**Comment by Thejas007** [comment]
Thanks.
 Finally I could resolve the build issue. 

1. As I was having VS2017 installed in my machine,  Installed VC++ as per below. 
https://stackoverflow.com/questions/33154696/msbuild-error-the-builds-tools-for-v140-platform-toolset-v140-cannot-be-f
 
2. Set Environment variable VCTargetsPath
VCTargetsPath to C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets

**Comment by SalahAdDin** [comment]
It is happening on Linux too!
