### ISSUE TITLE
 URL lock occurs after WebSocket connection and cannot be unlocked until switching requests

### ISSUE THREAD

**Issue by rodkevich** [getinsomnia/insomnia#8265]
### Expected Behavior

    Given I have a WebSocket request in Insomnia
    When I connect to the WebSocket server
    Then the URL input field should be locked and not editable
    And the URL input field should remain locked
    But the URL input field should unlock when the WebSocket connection is closed without switching to another request
    And I should be able to change the parameters in the URL input field after unlocking

### Actual Behavior

the URL input field remains locked until I switch to a different request

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?
- Local only

### Insomnia Version

Version: Insomnia 10.3.0

### What operating system are you using?

macOS

### Operating System Version

15.1.1 (24B91)

### Installation method

download

### Last Known Working Insomnia version

idk (made a request in discussions for help)

**Comment by notjaywu** [comment]
I can’t reproduce this issue with `v10.3.0` on my end. Can you share more information? Is it a local WebSockets server?

Verified the following cases:
1. `Disconnect` worked, and the field was unlocked correctly.
2. The WebSockets server closed the connection and it unlocked as expected.

**Comment by rodkevich** [comment]
> I can’t reproduce this issue with `v10.3.0` on my end. Can you share more information? Is it a local WebSockets server?
> 
> Verified the following cases:
> 
>     1. `Disconnect` worked, and the field was unlocked correctly.
> 
>     2. The WebSockets server closed the connection and it unlocked as expected.

@notjaywu hello
thanks for responding
I forgot to show that after switching to another and back everything will work as expected
but it will, if anything

https://github.com/user-attachments/assets/617f9f34-9ca8-4456-a816-220a33857639

**Comment by notjaywu** [comment]
Thanks for your information. We are looking into it.
