### ISSUE TITLE
[Performance] Slow startup on MacOS

### ISSUE THREAD

**Issue by ribice** [getinsomnia/insomnia#827]
- Insomnia Version: 5.14.9 (5.14.9.1895)
- Operating System: macOS High Sierra (10.13.3)

## Details

Since latest version (5.14.9) the app takes around 15-20 seconds to load, instead of usual 3-4 seconds. I haven't changed much around my system, didn't install anything new.

If you need more info please let me know.

**Comment by tianp** [comment]
I'm a Mac user with latest macOS 10.13.3 and Insomnia 5.14.9 (5.14.9.1895) with several Workspaces and dozens of Directories and the app starts normally within 5 seconds.

Maybe it's not Insomnia related issues?

**Comment by ribice** [comment]
Maybe, but I am not aware of anything that could cause it. Is there a profiler for Electron?

**Comment by gschier** [comment]
@ribice you can see the Chrome profiler in View > Toggle Devtools. Although I'm not sure if it's possible to start a profiler right when the app launches.

**Comment by gschier** [comment]
The only things I can think of that would slow down start time are having a lot of data in the app or possibly opening the app to a response that is large.

What time are you measuring, specifically? The time until the window shows or the time until the app is rendered within the window?

**Comment by ribice** [comment]
The window shows in ~5 secs. Then it takes another ~20 secs to render the app.

I have just few requests in Insomnia (2 workspaces with ~10 requests each).

Approximately 20+ days ago it would start in less than 5 secs.

**Comment by gschier** [comment]
That's really strange because nothing much has changed in a while. Do you see Insomnia using a lot of CPU on start?

**Comment by ribice** [comment]
Just checked, Insomnia Helper used around 60% of CPU during start time, then dropped to %1 once it started. Is that normal?

**Comment by gschier** [comment]
Checked mine and it got to 69% and took ~2 seconds to start on a low-end 13" 2016 Macbook Pro

**Comment by ribice** [comment]
I'm using exactly the same Macbook. Perhaps I could try reinstalling it?
I assume I need to export my workspaces prior to that?

**Comment by gschier** [comment]
Reinstalling won't delete your data. You could try doing that too though. Yes, you'll need to export your Workspaces first.

App data is stored in `~/Library/Application Support/Insomnia`

**Comment by ribice** [comment]
FYI: It's still slow, haven't 'reinstalled' it.
