### ISSUE TITLE
[Feature Request] Response history pop-up - group in dates.

### ISSUE THREAD

**Issue by barell** [getinsomnia/insomnia#831]
- Insomnia Version: 5.14.9
- Operating System: Ubuntu 16.04

## Details

This is a feature request to improve "Response history" pop-up. At the moment it shows:
Past Responses list with: [Status Code] [URL] [Time] [Size] which is fine but I would like it to also show time when the response has been made.

Current view:
![historypopup](https://user-images.githubusercontent.com/1502894/37964548-ca2fe5f0-31b9-11e8-97aa-e949e5eeedec.png)

So instead of flat list, it could be grouped in date ranges, e.g.:
[Today - Tuesday 27 Mar]
Entry
Entry
[Yesterday - Monday 26 Mar]
Entry
Entry
[Earlier this week]
Entry
Entry 

I use responses history a lot, and such an improvement would make it much easier to find which request from the history am I looking for.

**Comment by gschier** [comment]
Oo that sounds useful and would be pretty easy to add using the `<DropdownDivider/>` component.

**Comment by barell** [comment]
@gschier I will look if I can implement this feature. But first I will have to clone the project and play around to see what is where...

**Comment by barell** [comment]
I was thinking about implementing something like below:
![history-dropdown](https://user-images.githubusercontent.com/1502894/52164462-9628c300-26e9-11e9-83b6-0a3fb86b9068.png)

I could find some library to calculate relative time and then group history items... Any suggestions?

**Comment by barell** [comment]
@gschier have you got any suggestions on that? If not I could start doing some coding.

**Comment by gschier** [comment]
@barell your mockup looks awesome!

**Comment by NilayMajorwar** [comment]
Since this feature was left unimplemented, I did some work on it:

![res-history](https://user-images.githubusercontent.com/18032938/67861791-e5036c00-fb46-11e9-93b8-c299c49050fb.png)

- "Today" group shows the calendar day's responses (not simply 24 hours ago).
- Similarly, "This Week" group shows the calendar week's responses (not simply 7 days ago).

@gschier Would this be fine - any improvements/modifications required?
