### ISSUE TITLE
[Bug] If autocomplete shows URLs, variables and tags don't show

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [getinsomnia/insomnia#833]
- Insomnia Version: 5.14.9
- Operating System: Windows 10

## Details

When you type "https://" in the address bar and then ctrl-space, the variables/functions don't appear in the list. They do for "http://".

**Comment by gschier** [comment]
Looks like the presence of URLs in general prevents the rest of the items from showing. I updated the issue title to reflect this.
