### ISSUE TITLE
[Feature Request] Ability to link to external docs

### ISSUE THREAD

**Issue by Cam** [getinsomnia/insomnia#834]
I'd love to be able to set a documentation URL on folders/environments for quick access to docs for the relevant API. Currently I'm using something like the below for quick reference, but it is a poor workaround at best.

I spend almost all my API referencing/testing time in Insomnia, so I feel it would be ideal to be able to store this reference there too. One API resource to rule them all, so to speak.

```
  {
     "docs": "https://developer.platform.com/docs"
  }
```

**Comment by gschier** [comment]
It seems like this should maybe be covered by extending Insomnia's current documentation feature. 

I can see the use case for folder-level docs but not for environments. Environments are usually dev/staging/prod, which would all have the same docs. What kind of environments are you using that would require different docs for each?

**Comment by Cam** [comment]
I think you're right that folder-level docs makes the most sense. Using the environments to store that info is definitely not ideal. It was just the easiest to access, giving me [quick access to the info by right-clicking the folder](http://share.elkfox.com/e3nT3h).

**Comment by gschier** [comment]
Oh I see. By folders/environments I thought you meant folder environments AND top-level environments. got it 👍

**Comment by Cam** [comment]
Yeah, sorry, I was being annoyingly ambiguous.
