### ISSUE TITLE
[Bug] GraphQL schema fetching is stuck with an outdated refresh token

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#835]
- Insomnia Version: 5.14.9
- Operating System: Arch Linux

## Details

When using GraphQL and OAuth2 (Resource Owner Password Credentials) as authentication, looks like the Schema fetching stores and keep the first refresh token received, and never updates it again, ignoring the refresh token set at the OAuth2 tab.

In the GraphQL tab I'm getting the following error:

![image](https://user-images.githubusercontent.com/12160864/38064230-58afefae-32d3-11e8-8807-abe6cc568975.png)

In the backend I got an expired refresh token exception, which tried to use the following token (just the signature ending part):
```
...zw76QdqtOBZFVID6eakxHHgKdtJK3w
```

At the OAuth2 tab, the refresh token is the following:

```
...Qk3ly07AwOBKgOjY2aIcZlZcuLYRIQADIfyZA
```

If I send the GraphQL request, it works as expected because the OAuth2 has a valid refresh and access token.

Looks like the `fetch schema` does not use the updated tokens from the OAuth2 tab.

If I create a new GraphQL request, the fetch schema works just fine... but will stop work when the refresh token expires.

Best regards,
Rafael Pacheco.

**Comment by gschier** [comment]
Correct. The schema fetch uses it's own tokens. I'll see if it's easy enough to make it use the same one.

**Comment by gschier** [comment]
Boom! 💣A bit hacky but it works

**Comment by rafaelrenanpacheco** [comment]
Marvelous!

Thank you very much!

**Comment by tm1000** [comment]
Duplicate of 699
