### ISSUE TITLE
[Question] Why does Insomnia fail but curl works?

### ISSUE THREAD

**Issue by bootstraponline** [getinsomnia/insomnia#836]
- Insomnia Version: Version 5.14.9 (5.14.9.1895)
- Operating System: macOS 10.13.3

## Details

In Insomnia I see this error when executing a request:

```
< HTTP/1.1 422 Unprocessable Entity
< Server: Cowboy
< Date: Thu, 29 Mar 2018 03:06:54 GMT
< Connection: keep-alive
< Content-Type: text/html; charset=UTF-8
< X-Request-Id: 7ed2f55d-2160-4ba2-90b7-74f60b3dd0fd
< X-Runtime: 0.012431
< Content-Length: 1334
< Via: 1.1 vegur

* Received 1334 B chunk
* Connection #5 to host www.bitrise.io left intact
```

however when I `Copy as Curl` the request succeeds. How do I debug the difference between the generated curl command and what Insomnia is doing?

**Comment by bootstraponline** [comment]
I think it has something to do with `X-XSRF-TOKEN` in headers.

**Comment by davibusanello** [comment]
I have the same problem, and I don't have tokens in these requests like `login` endpoint.
I'm also using in my local development server and the request doesn't reach the server with Insomnia however in `curl` works normally.

- OS `Ubuntu 18.04 bionic x86_64 Linux 4.15.0-48-generic`

- Insomnia `v6.5.1`

```
Version 6.5.1
Shell 3.0.4
Node 10.2.0
V8 6.6.346.32
Architecture x64

libcurl/7.61.1 OpenSSL/1.1.0h zlib/1.2.11 nghttp2/1.29.0
```
