### ISSUE TITLE
[Bug] HAR export omits some headers

### ISSUE THREAD

**Issue by vfaronov** [getinsomnia/insomnia#840]
- Insomnia Version: 5.14.9
- Operating System: Ubuntu 16.04

## Details

1. Send a POST request with a body, without any extra headers.
2. Export it as HAR (Preferences → Data → Export Data → Current Workspace → HAR).

You get a file like [`insomnia-post.har.txt`](https://github.com/getinsomnia/insomnia/files/1865814/insomnia-post.har.txt). In this file, `log.entries[0].request.headers` only contains the header `Content-Type: application/x-www-form-urlencoded`. However, if you inspect the actual request sent (e.g. with tcpdump or [mitmproxy](https://mitmproxy.org/)), you can see that of course Insomnia also sends other headers as required in an HTTP request:

```
Host: httpbin.org
User-Agent: insomnia/5.14.9
Proxy-Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded
Accept: */*
Content-Length: 7
```

So, the HAR export does not faithfully reflect what was sent.

**Comment by bernhardriegler** [comment]
please reopen - this is still an issue in the latest version.

**Comment by gschier** [comment]
Hmm, this one may take some work, since a lot of those headers are added by `libcurl` at send-time.

**Comment by gschier** [comment]
Going to mark this as accepted so it doesn't get closed but FYI it's pretty low priority for now.
