### ISSUE TITLE
[BUG] Font rendering on ubuntu is bad

### ISSUE THREAD

**Issue by luispabon** [getinsomnia/insomnia#843]
In general, fonts for Insomnia in Ubuntu 17.10 render really badly - hinting is probably wrong as the smaller the font, the less readable they are. 

- Insomnia Version:
```
Version 5.15.0
Shell 1.7.13
Node 7.9.0
V8 5.8.283.38
Architecture x64
```

- Operating System: Ubuntu 17.10 / Unity 7

I'm attaching a number of partial screenshots:

![image](https://user-images.githubusercontent.com/6388823/38249944-4af90604-3745-11e8-9c03-351eef3a5179.png)

![image](https://user-images.githubusercontent.com/6388823/38249960-56a57a3c-3745-11e8-92f6-c45291977175.png)

![image](https://user-images.githubusercontent.com/6388823/38249980-66385078-3745-11e8-8015-af16bc499025.png)

Some of the other electron apps I'm using (eg VSCode) do not show this problem and indeed render fonts just like any other native app.

Seems to be all fonts, not just the interface fonts I've highlighted - embiggening the text editor font mitigates the problem in there, but by no means fixes it.

**Comment by gschier** [comment]
I don't think your screenshots are high enough quality for me to tell what's wrong with the font. Maybe a screenshot that shows side-by-side with another app with better font rendering?

**Comment by luispabon** [comment]
![untitled](https://user-images.githubusercontent.com/6388823/39058615-3e84132e-44b4-11e8-8932-284fe98b0a56.png)

**Comment by luispabon** [comment]
![untitled](https://user-images.githubusercontent.com/6388823/39058947-27b41530-44b5-11e8-91d4-34b806988d24.png)

**Comment by luispabon** [comment]
You need to open the image to remove github's zooming as the blur masks the issue. This is on a 1920x1080 screen. In 4K the problem is less apparent.

You can see both JSON render very similarly, same font but insomnia's sizing is a little lower. That's fine.

The issue comes on the interface elements, like the tabs, the POST button, the URL. Rendering is pretty bad there and makes the labels hard to read. It is quite possible it's the font being used, since the comparing screenshot is vscode which also uses electron. vscode is using the default system font, in my case this is Ubuntu.

**Comment by gschier** [comment]
Oh ya, I think I see it now. The JSON looks much smoother. 

This is likely an issue with the default interface font. Do you know what font-face visual studio is using?

**Comment by gschier** [comment]
Hmm, ya I should probably just copy what VSCode uses for it's default fonts. Right now Insomnia includes the Open Sans font from Google Fonts (only the .woff2 format) which might not behave well with Ubuntu.

**Comment by luispabon** [comment]
:+1: do gimme a shout if you need a hand with testing it out

**Comment by gschier** [comment]
Sure, thanks 😄

**Comment by luispabon** [comment]
@gschier I just got updated to 5.16.1, did this fix make it in there? I see no real change on font rendering.

**Comment by gschier** [comment]
Ya it's in there. I guess that wasn't the correct fix, then 😿

**Comment by gschier** [comment]
Since yesterday I now have a "retina" install of Ubuntu running in VMWare so I can test it out 👍

**Comment by gschier** [comment]
Can you do me a favor and check which font-family is actually showing for you? In Ubuntu 18.04 it's `Liberation Mono` but I don't have a 17.10 to test with.

![screenflick movie 29](https://user-images.githubusercontent.com/587576/39367734-9cc7572e-4a05-11e8-8efd-19edeea6ffcd.gif)

**Comment by luispabon** [comment]
It is liberation mono local as per your screegrab, and it is just fine  on the editor and the response preview, timeline etc.

The place where weird font rendering remains is on the UI elements such as folder names, tabs etc. which is also liberation local. This is really puzzling though because the same font at the same size on a plain html loaded in chrome renders much better

**Comment by luispabon** [comment]
I'm messing about with the dev tools and styles see if I can hit the spot

**Comment by gschier** [comment]
Oh right, got confused again as to which font was messed up. Let me know if you can figure out a font that works for you 😄

**Comment by luispabon** [comment]
Ubuntu works better, but still renders with the hinting all messed up. How old is the version of electron you're using in here?

**Comment by gschier** [comment]
Nice, I can change it to the Ubuntu font for now and see what happens. Changing the UI font size is actually pretty tricky because all of the padding/margin/etc is tied to it (scaled using `rem`). I'd consider it though. Note that you can also change the zoom level using ctrl +/-

**Comment by luispabon** [comment]
Understood, and thank you for your help :+1: I use insomnia constantly so good fonts are important to avoid eye strain

**Comment by jdorleans** [comment]
I'm having similar problem on Ubuntu 18.04 with Insomnia version 5.16.1. 
I've checked the font family in dev tools and it is using: **Courier New**.
Is there any way I can change the font myself?

![image](https://user-images.githubusercontent.com/1254399/39388946-e5429d3c-4a51-11e8-950d-6adab39947f0.png)

**Comment by gschier** [comment]
Going to close this now that there is the ability to select a custom font. Hopefully the user will be able to chose one with more weight.
