### ISSUE TITLE
[Bug] xpath containing single quotes causes "Unexpected token"

### ISSUE THREAD

**Issue by neontuna** [getinsomnia/insomnia#844]
- Insomnia Version: 5.15.0
- Operating System: macOS

## Details

Using an XPath filter that looks like this `//meta[@name='csrf-token']/@content`.  The issue is the single quotes around `csrf-token`.  

That gets rendered into this nunjucks template `{% response 'body', 'req_b73584b54f414f888c2d207852ddabbc', '//meta[@name=\'csrf-token\']/@content' %}`.  Even though the single quotes look to be escaped, they still cause Insomnia to throw an error.

<img width="662" alt="screen shot 2018-04-03 at 8 27 09 pm" src="https://user-images.githubusercontent.com/7414827/38282337-961937a2-377d-11e8-8eaf-ed9595e9c2eb.png">

**Comment by verglor** [comment]
I have the exact same problem in vesion 5.16.6.
I think that @neontuna described the bug exactly.
If I use double quotes in xpath it also fails because they are not escaped:
```
{% response 'body', 'req_37c185c43c0c4a308efc142dd3dbfd4d', '//input[@name="_csrf_token"]/@value' %}
```

**Comment by neontuna** [comment]
Yeah unfortunately this issue got auto closed, I never found a workaround or solution just using a different REST client for testing now.

**Comment by verglor** [comment]
Hi @gschier, could you please reopen this issue ?

**Comment by gschier** [comment]
There's a more recent one here: #1030

**Comment by carmineesposito73** [comment]
@verglor 
I've found a workaround: use double quotes escaping them manually
```
"ext_net_href": "{% response 'body', 'req_63e53c90ca7e40bdb711f2ed575ecbb4', '//*[@name=\"Internet_01\"]/@href' %}"
```

**Comment by carmineesposito73** [comment]
@verglor @neontuna 
To define env vars I use the form with xpath filter:

![insomnia-env-xpath-filter-hidden](https://user-images.githubusercontent.com/38761873/43507264-e40fc08c-956c-11e8-9180-09ea29a5b0bb.png)

then, after clicking "done", I get "unexpected token" message:

![insomnia-env-json-unexpted-token](https://user-images.githubusercontent.com/38761873/43507299-0669dfbe-956d-11e8-85ad-451d79b22602.png)

I copy the full json and paste it on a text editor, the text is the following (look at the string "Pilota"):

```
! unexpected token
{
	"var": "{% response 'body', 'req_63e53c90ca7e40bdb711f2ed575ecbb4', '//*[@name="Pilota"]/@href' %}"
}
```
I escape manually the double quotes
```
! manually escaped " -> \"
{
	"var": "{% response 'body', 'req_63e53c90ca7e40bdb711f2ed575ecbb4', '//*[@name=\"Pilota\"]/@href' %}"
}
```
then copy and past back the json to insomnia, the "unexpected token" message disappears:

![insomnia-env-json](https://user-images.githubusercontent.com/38761873/43507512-a5c663a2-956d-11e8-9c67-95b6d6fb39e0.png)

I'm not sure is your case, I hope it helps.

**Comment by gschier** [comment]
Oh, yep, thanks for reminding me! I reopened https://github.com/getinsomnia/insomnia/issues/1030
