### ISSUE TITLE
[Help] Error when exporting to HAR

### ISSUE THREAD

**Issue by jhalterman** [getinsomnia/insomnia#845]
Hit an error when exporting my workspaces to HAR

Insomnia 5.14.9 (5.14.9.1895)
MacOS 10.12.6

## Details

```
Error: Failed to render "Get Index:url"
 attempted to output null or undefined value
    at exportHarWithRequest (file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:54551:13)
    at <anonymous>
```

**Comment by gschier** [comment]
Hey @jhalterman,

Looks like the URL of your "Get Index" request failed to render. Do you see any errors when you inspect that request?

**Comment by jhalterman** [comment]
So that request uses some variables that are only defined in some environments. I assume that's the issue.

**Comment by qwelias** [comment]
I've got similar error
```
Error: Failed to render "sobjects:url"
 attempted to output null or undefined value
    at exportHarWithRequest (file:///opt/Insomnia/resources/app.asar/bundle.js:54784:13)
    at <anonymous>
```

**Comment by qwelias** [comment]
And I suppose title should be changed to **[BUG]**

**Comment by gschier** [comment]
I don't think this is a bug (since failure is expected) but I think the app could do a better job at showing the error to the user.
