### ISSUE TITLE
[Bug] GraphQL variable error

### ISSUE THREAD

**Issue by DiederikvandenB** [getinsomnia/insomnia#846]
- Insomnia Version: 5.15.0
- Operating System: Mac OS 10.13.3

## Details

The variable in the GraphQL URL is not replaced (anymore?), see screenshots.

![image](https://user-images.githubusercontent.com/6132723/38326806-0e3e5108-3847-11e8-97a7-89d37be2a991.png)

![image](https://user-images.githubusercontent.com/6132723/38326849-22caaa0e-3847-11e8-8cb6-d788d0bc6917.png)

**Comment by gschier** [comment]
It looks like the error message is just spitting out the raw URL string. The actual request being sent will have been rendered, though. 

What type of auth are you using on your GraphQL endpoint? The more details you can provide about the request you're sending the better 👍 

Note: The only GraphQL thing that changed in the last version is that it now uses the same OAuth 2.0 token as its parent request. Does your parent request have a valid token?

**Comment by DiederikvandenB** [comment]
The auth method is oAuth 2 with a password grant. I'm not too sure what you mean by parent request? But the request itself completes successfully, so the oAuth 2 settings in Insomnia are definitely correct.

**Comment by DiederikvandenB** [comment]
Fixed. There was an issue in my schema causing the error. For future reference: I had a mutation which accidentally referenced a ListOf type, instead of the regular type.
