### ISSUE TITLE
[BUG] Trial ended dialog

### ISSUE THREAD

**Issue by nathanwaldman** [getinsomnia/insomnia#847]
- Insomnia Version: 5.15.0
- Operating System: macOS 10.12.6

## Details

I cancelled my Insomnia Plus subscription.  Now when I open Insomnia it gives me a dialog with "Insomnia Plus Trial Ended" with "Cancel Subscription" and "Update Billing" buttons.  When I click "Cancel Subscription" it changes to "Click to confirm" when I click that it changes to "Done".  When I click "Done" it takes me back to "Cancel Subscription" and "Update Billing".  I would expect this to close the dialog instead.

Using the X to close the dialog makes it all go away.

**Comment by gschier** [comment]
I have a feeling the cancelation is throwing an exception because you're already cancelled. Will get this fixed.
