### ISSUE TITLE
[Improvement] Show remaining time for the refresh token expiration

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#848]
- Insomnia Version: 5.15.0
- Operating System: Arch Linux

## Details

Hi there!

In the OAuth2 tab, Insomnia calculates the remaining time for the access token, but does not for the refresh token, as you can see here:

![image](https://user-images.githubusercontent.com/12160864/38342821-f4511b3a-3856-11e8-82ab-e765c4f11216.png)

Would be possible to calculate and show the remaining time for the refresh token as well? If the refresh token has exp claim, show remaining time, else, don't.

Also, looks like the expired label is wrong:

![image](https://user-images.githubusercontent.com/12160864/38342904-7ac11bac-3857-11e8-9253-acd11fdb2ee7.png)

Shouldn't it be "**Expired** a few seconds ago"?

Best regards,
Rafael Pacheco.

**Comment by gschier** [comment]
This should remain open.

**Comment by KarthikSiddarth** [comment]
Hi Greg,
I would like to contribute on implementing the mentioned improvement.

**Comment by gschier** [comment]
I'm not actually sure if there is a way to know the refresh token expiry date. The OAuth 2.0 RFC states that the response looks like this:

```json
{
   "access_token":"2YotnFZFEjr1zCsicMWpAA",
   "token_type":"example",
   "expires_in":3600,
   "refresh_token":"tGzv3JOkF0XG5Qx2TlKWIA",
   "example_parameter":"example_value"
}
```

The `expires_in` key relates to the `access_token` and it doesn't look like there is anything else that would indicate the expiry of the refresh token.

Perhaps someone with more OAuth 2.0 experience could clarify this?

**Comment by samovertonjr** [comment]
I'll do a more research as well. Thanks.

**Comment by rafaelrenanpacheco** [comment]
The expiration time is actually in the refresh token. For example, we have the following refresh token:

```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXByZXNhX2lkIjoxLCJ1c3VhcmlvX2lkIjoxLCJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJhdGkiOiJjYmI2NGNkNC1lMzlmLTQ4MjQtYTE1OS1hZTAxMDM3ZDMyZGMiLCJub21lIjoiQWRtaW5pc3RyYWRvciIsImV4cCI6MTU0MDIxNTg0NiwianRpIjoiZGM4NzFhMzUtMTJmZS00ODZmLWI0MjUtNGFmMDYzZTEyMTU0IiwiY2xpZW50X2lkIjoidWFhLWNsaWVudCJ9.abc
```

If you decode that (https://jwt.io/), you can see that there is a claim called `exp`, which is a `Registered Claim Name` at [RFC 7519](https://tools.ietf.org/html/rfc7519), so it is not a magical string. Also it is not mandatory, which means the refresh token may or may note have it. So, if the `exp` claim is present in the refresh token, Insomnia will be able to show the expiration time in the UI.

**Comment by samovertonjr** [comment]
Thanks @rafaelrenanpacheco

**Comment by gschier** [comment]
@rafaelrenanpacheco it's my understanding that JWT is not part of the OAuth 2.0 standard. It's possible that an API might use JWT as convention but is not common.

**Comment by rafaelrenanpacheco** [comment]
@gschier you are right, JWT is just one of many possibilites to generate access and refresh token. I'm so used to use OAuth2 with JWT that I forgot that.

As you said about the OAuth 2.0 RFC, there's nothing about refresh token expiration. It is entirely up to the backend to accept it indefinitely, to blacklist it or refuse it after some period.

I'm closing this issue, thanks for your attention :+1:

**Comment by gschier** [comment]
I appreciate the insight @rafaelrenanpacheco 😄
