### ISSUE TITLE
[Bug] [URGENT] Environments broken since 5.15.0 update

### ISSUE THREAD

**Issue by EpocDotFr** [getinsomnia/insomnia#851]
- Insomnia Version: 5.15.0
- Operating System: Windows 10

## Details

Since the latest update (5.15.0), environments doesn't looks like they are working anymore. Selecting a different environment doesn't change the env variables: the same are always used. Looks like variables from the last selected environment before the update are used (but I'm not sure).

I'm encountering this issue when using environment variables in OAuth 1 authentication parameters. I didn't changed anything major before and after the update.

**Comment by EpocDotFr** [comment]
The issue wasn't Insomnia itself. It was my fault.

**Comment by DiederikvandenB** [comment]
Could you share what you did wrong? Since I'm facing the same issue, I'd like you know your solution.
