### ISSUE TITLE
[Improvement] UI should show matches when filtering requests by folder, URI, method, query string

### ISSUE THREAD

**Issue by axs221** [getinsomnia/insomnia#857]
- Insomnia Version: Version 1.7.9 (1.7.9)
- Operating System: Version 10.13.3 (17D47) - macOS High Sierra

## Details

I previously implemented the business logic for searching by folder, URI, method, and query string in #797 as a fix for #739. This has been merged.

This is a follow up to that, to show in the UI what field and value has been matched. This needs to apply to the Quick Switch window, possibly as well as the filter in the sidebar.

For Quick Switch, we can consider libraries like [fuzzy](https://github.com/mattyork/fuzzy) or [fuzzysearch](https://github.com/bevacqua/fuzzysearch), like @roblav96 recommended. We will likely need to make the search results show at least 2 rows, to be able to fit the matching text, otherwise matches on e.g. long URLs won't fit as easily at smaller widths.

**Comment by shawnaxsom** [comment]
@gschier Here is what I have so far. What do you think? It is essentially working for the Quick Switch window. 

Screenshot: https://cl.ly/0p1i2c2e3N18
GIF: https://cl.ly/011H001a2J3k

**Comment by axs221** [comment]
@gschier Here is what I have so far. What do you think? It is essentially working for the Quick Switch window.

Screenshot: https://cl.ly/0p1i2c2e3N18
GIF: https://cl.ly/011H001a2J3k

**Comment by gschier** [comment]
Woah, I'm really liking that @axs221. You want to put up a PR soon so we can finalize it?

**Comment by axs221** [comment]
@gschier Sure thing, here is a PR: https://github.com/getinsomnia/insomnia/pull/864.

It is a work in progress (see section `What is left to do or discuss?`), but it is usable. Feel free to review/comment if you want.

**Comment by gschier** [comment]
Oh, this was done a while ago!
