### ISSUE TITLE
[Feature Request] View GraphQL Schema like GraphiQL Docs

### ISSUE THREAD

**Issue by vning93** [getinsomnia/insomnia#867]
- Insomnia Version: 5.15.0
- Operating System: Mac OS High Sierra

## Details

I love the tool and how there's a native way to execute GraphQL queries now, but the one major thing this is missing is the ability to view the GraphQL schema documentation. Will this be supported soon?

**Comment by gschier** [comment]
Hey @vning93! Ya, this is outlined in #451 

Now that Insomnia seems to be fairly popular for GraphQL users I might take on that issue myself (was previously going to leave it for the community).

Going to close this one as a duplicate.
