### ISSUE TITLE
[Feature Request] Make height of URL Preview text adjustable in query string area

### ISSUE THREAD

**Issue by sebwas** [getinsomnia/insomnia#869]
## Details
Good day everyone,

so today I ran into the problem that the URL Preview textarea wan't adjustable in height, which just didn't feel right. (and also is slightly annoying)

Only a few longer query string parameters will get the textarea to its limits.

![Example screenshot](https://i.imgur.com/fD7Prva.png)

Thanks!

**Comment by j-collier** [comment]
I can take this one
