### ISSUE TITLE
[Feature Request] Do not include passwords when exporting workspaces.

### ISSUE THREAD

**Issue by jonthegiant** [getinsomnia/insomnia#871]
- Insomnia Version: v5.15.0
- Operating System: Win7

## Details

For example: I have a workspace with various endpoints that use NTLM credentials for authentication. 

Credentials are stored with the endpoint configurations so If I export this workspace, **not only are passwords included in the export, they are exported in plain text.**

Please change the default behavior to **NOT** include passwords when exporting workspaces.

**Comment by gschier** [comment]
Hey @jonthegiant. To get around this you can create a private [environment](https://support.insomnia.rest/article/18-environment-variables) and put your passwords in there. Private environments are neither synced or exported so this should do what you want.

**Comment by jonthegiant** [comment]
Hi @gschier. Thanks for the suggestion.

If I were to save API keys, passwords, sensitive data, etc in these private environment variables, how are they saved on disk (plaintext/encrypted)?

**Comment by gschier** [comment]
Ya, everything is plain text on disk

**Comment by gschier** [comment]
In general, I think this feature is a good idea but would be worried that it would be too difficult to catch every case. It would also need some way to let the user know that this is happening.

An alternative solution, which also gets you disk encryption, would be to create a [template tag](https://support.insomnia.rest/article/40-template-tags) that encrypts a string value with a given password. The field would still get exported of course, but it's contents would not be readable to anyone without the password.
