### ISSUE TITLE
[Bug] Keyboard Shortcut Menu Incorrect

### ISSUE THREAD

**Issue by stevestock** [getinsomnia/insomnia#872]
- Insomnia Version: 5.15.0 (5.15.0.1953)
- Operating System: 
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E199
```
## Details
On Mac OS, the keyboard shortcut for Show Autocomplete is ⌃Space
But in the Help->Keyboard Shortcuts Menu it is incorrectly displayed as ⌘Space

It looks like the hotkeys are set up as combinations of [`const {alt, shift, meta}`](https://github.com/getinsomnia/insomnia/blob/549ce23ce8cf202d787ca4df5efc5f25e03311ed/packages/insomnia-app/app/ui/components/hotkey.js#L18), where meta =  [`MOD_SYM = isMac() ? '⌘' : 'Ctrl'`](https://github.com/getinsomnia/insomnia/blob/4e0fe5d78a672e350723254745ffb05e564f5f55/packages/insomnia-app/app/common/constants.js#L72), which equates to [`CmdOrCtrl`](https://electronjs.org/docs/api/accelerator#platform-notice).  The problem is that some shortcuts like Autocomplete ([`'Ctrl-Space': 'autocomplete',`](https://github.com/getinsomnia/insomnia/blob/298db4bf58cfb4bdb7a5e52a17ac55af605cf05e/packages/insomnia-app/app/ui/components/codemirror/code-editor.js#L59)) are simply the ctrl key on all platforms.  

I only found this one example, but after looking through the code, I'm sure there are more... and I suspect similar issues with the Alt key, which seems to be oddly defined as [`ALT_SYM = isMac() ? '⌃' : 'Alt';`](https://github.com/getinsomnia/insomnia/blob/4e0fe5d78a672e350723254745ffb05e564f5f55/packages/insomnia-app/app/common/constants.js#L73)

**Comment by gschier** [comment]
Oh ya, I've been meaning to fix that. Thanks for reminding me. That should be the only non-CmdOrCtrl hotkey. I'll just hack it for now so it works 👍

**Comment by stevestock** [comment]
No problem, let me know if I can be of any help!
