### ISSUE TITLE
[Feature Request] GraphQL Tracing plugin

### ISSUE THREAD

**Issue by falkenhawk** [getinsomnia/insomnia#875]
- Insomnia Version: 5.15.0
- Operating System: win10

It would be great to convert extensions/tracing in the response into some pretty report ;)

![image](https://user-images.githubusercontent.com/14310995/39042529-53ec522c-448b-11e8-8cfe-d89a71b0ff73.png)

Example how graphql playground does that:
![image](https://user-images.githubusercontent.com/14310995/39042586-7eb10e62-448b-11e8-8075-9c21f6c627f6.png)

**Comment by gschier** [comment]
That's really neat. Are GraphQL extensions an official way of extending GraphQL? This is the first extension I've seen.

**Comment by unhawkable** [comment]
Yes it seems it's an official way. But the specs are really vague on this matter ( http://facebook.github.io/graphql/October2016/#sec-Response-Format )
https://github.com/apollographql/apollo-tracing

**Comment by smeijer** [comment]
Too bad this one has been closed. It's a reason for me to use playground over insomnia.
