### ISSUE TITLE
[Feature Request] Rename current request by pressing F2

### ISSUE THREAD

**Issue by sasavilic** [getinsomnia/insomnia#877]
- Insomnia Version: 5.15.0
- Operating System: Ubuntu 16.04

## Details

When you duplicate a request with keystroke Ctrl-D, there is no way begin renaming it without using mouse. Making F2 begins renaming would be really helpful.

**Comment by gschier** [comment]
Good suggestion. I'll try to add this to the next release.

BTW, there _is_ a way to rename a request using only the keyboard, but it's not at all convenient:

1. Open request settings dialog `Cmd+Shift+Ctrl+,` (Mac) or `Ctrl+Alt+Shift+,`
2. Press `TAB` twice to focus name field
3. Rename request
4. Press `ESC` to close dialog

**Comment by lmittmann** [comment]
any update on this feature?
