### ISSUE TITLE
[Feature Request] Allow toggling of Authentication `Enabled` Flag with Environment Variable

### ISSUE THREAD

**Issue by hughgardiner** [getinsomnia/insomnia#880]
## Details
It would be awesome to be able to toggle whether or not your Authentication is enabled via an environment variable so you can toggle for all requests at once rather than toggling each request individually.

![screen shot 2018-04-20 at 6 19 24 pm](https://user-images.githubusercontent.com/16827788/39076126-83a9f9e2-44c7-11e8-8afe-89f22dad7002.png)

**Comment by gschier** [comment]
That's interesting! 

This is definitely possible with a simple plugin that just deletes the `Authorization` header for every request. It could even look at the env for a specific user-defined value.
