### ISSUE TITLE
[Bug] Unix Socket error

### ISSUE THREAD

**Issue by DrSensor** [getinsomnia/insomnia#883]
- Insomnia Version: 5.15.0
- Operating System: Ubuntu 16.04

#### About
```
Version 5.15.0
Shell 1.7.13
Node 7.9.0
V8 5.8.283.38
Architecture x64

libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.11 libidn/1.32 librtmp/2.3
```

## Details
I'm trying to follow this post https://insomnia.rest/blog/unix-domain-sockets/ but when I click Send in preview tabs it say
```
Unknown option given. First argument must be the option internal id or the option name. You can use the Curl.option constants. (undefined n/a)
```

![screenshot from 2018-04-22 07-49-30](https://user-images.githubusercontent.com/4953069/39090172-bef64146-4601-11e8-9851-743a9ac02c1b.png)

**Comment by gschier** [comment]
Hmm, that's really strange. I just tested it on Mac and it seems to work.

Can you post the result from running the following command in your command line?

```
curl --version
```

![image](https://user-images.githubusercontent.com/587576/39243900-f47515a6-485c-11e8-91ce-61380471a195.png)

**Comment by DrSensor** [comment]
`curl --version`
```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

However, it works fine if I do request using
```
curl --unix-socket /var/run/docker.sock http://localhost/v1.24/images/json
```

![screenshot from 2018-04-27 05-43-58](https://user-images.githubusercontent.com/4953069/39335646-1208d4ae-49de-11e8-814b-ea20244f7eb4.png)

**Comment by gschier** [comment]
Hmm, what header are you sending with the request?

I just tried on Insomnia v16.0.1 on Ubuntu 18.04 (via deb package) and was able to successfully connect to the docker socket. It might be that your libcurl version is extremely old and Insomnia is sending it an option that it didn't support yet? The latest Insomnia release switches from dynamic linking to statically linking libcurl (v7.59.0). Can you give that release a try and see if it helps?

![image](https://user-images.githubusercontent.com/587576/39337241-e2af2a54-4989-11e8-88c4-0adcd3bad8c9.png)

**Comment by DrSensor** [comment]
I just installed from snap store `snap install insomnia` and here what I got
![screenshot from 2018-04-27 07-32-20](https://user-images.githubusercontent.com/4953069/39338500-5465c76c-49ed-11e8-8b5b-1506cce3a46c.png)
Is something missing in `snap.yml`? Seems like [Unix sockets file permission](https://docs.snapcraft.io/build-snaps/syntax#socket-mode) is not set

**Comment by gschier** [comment]
Ya, the snap didn't work for me (I should have mentioned that). Thanks for the link. I didn't realize it would be possible to make that work.

**Comment by gschier** [comment]
Hmm, that link makes it seem like you need to be very specific about what sockets the app has access to, which may not work for Insomnia's use case.
