### ISSUE TITLE
[Bug] Reveal hidden content type header

### ISSUE THREAD

**Issue by mastern2k3** [getinsomnia/insomnia#884]
- Insomnia Version: 5.15.0
- Operating System: Windows 10

## Details

Currently whenever I'm picking a body type, a header is added to the outbound headers tab.
When I check the headers tab it looks empty.
My only deduction is that the extra header is the content type header, and that it's just filtered.

I would love if it were possible to un-hide it.

![capture](https://user-images.githubusercontent.com/4235611/39093667-eceedc78-462b-11e8-89df-bcb722a01c1b.PNG)

**Comment by gschier** [comment]
That's definitely a bug. It should be showing up. I'll get that fixed right away.
