### ISSUE TITLE
Request time measurement is inaccurate (can't show anything below 15 ms, values are rounded)

### ISSUE THREAD

**Issue by dzek69** [getinsomnia/insomnia#886]
- Insomnia Version: 5.15.0
- Operating System: Windows 10 x64 ver 1709 (build 16299.371)

When I send a request its measured time never shows values between 1-14 (included). It's either 0, or 15 or more.

See the screenshot of request history:
![insomnia_2018-04-22_14-44-15](https://user-images.githubusercontent.com/4936805/39095115-b9de7f90-463b-11e8-915b-98dcf820aac4.png)

Additionally time values are always rounded to nearest whole milisecond. It looks broken, as the value is formatted to have 3 more numbers after the coma.

**Comment by gschier** [comment]
This is a duplicate of #668. It seems to be a downside of how windows timers work. Going to re-open that issue as it was closed by Stale Bot.
