### ISSUE TITLE
[Feature Request] Autocomplete in GraphQL variables editor

### ISSUE THREAD

**Issue by unhawkable** [getinsomnia/insomnia#887]
- Insomnia Version: 5.15.0
- Operating System: win10

an excerpt from graphql schema:
```
cards(filters: FilterInput): CardResults!
input FilterInput {
  where: [FilterWhereInput]
  sort: [FilterSortInput]
  range: FilterRangeInput
}

```

autosuggestion/autocomplete in inline parameters of a query works great:
![obraz](https://user-images.githubusercontent.com/14310995/39097523-9a2b654c-465d-11e8-9eb0-015f675d2725.png)

but not in Query Variables:
```
query cards($filters: FilterInput) {
  cards(filters: $filters) {
     id
  }
}
```

![obraz](https://user-images.githubusercontent.com/14310995/39097533-dad78008-465d-11e8-8101-c67942050aec.png)
![obraz](https://user-images.githubusercontent.com/14310995/39097538-eca34a6a-465d-11e8-83bc-d50fd7636b95.png)

**Comment by gschier** [comment]
Got it working! 
![image](https://user-images.githubusercontent.com/587576/39098622-a2ee8654-463b-11e8-8386-f6e515530449.png)

**Comment by gschier** [comment]
@unhawkable what would be the purpose of autocompleting fields inside the variables editor?

**Comment by unhawkable** [comment]
Well, basically, for easier typing of complex input variables :) In my example filters variable is of FiltersInput input type which consist of several other fields. These fields are another nested input types (arrays or single) etc. with their own subset of allowed fields.
Autocomplete for all of this works in the query editor, when typing an inline argument of a query.

**Comment by unhawkable** [comment]
I've just checked graphiql and yes, it actually does.
![obraz](https://user-images.githubusercontent.com/14310995/39305652-22671d9a-495e-11e8-85d3-f801b3090cfd.png)

It even wraps props with double quotes ;)

**Comment by gschier** [comment]
Well that's strange. I'll have to take a look at how it's doing it. Can you make a separate issue for that?
