### ISSUE TITLE
Size of everyhing

### ISSUE THREAD

**Issue by TerkiKerel** [getinsomnia/insomnia#889]
Hi,

It would be great if we can increase the size of everything. When we browser with Firefox/chrome and CTRL+/- (or CTRL + mouse scroll) increases/decreases all object sizes. Not only text font size. 

I increased the "text editor font size" inside insomnia options but it only worked for repose body textarea.

Thank you

Using version:

Version 5.15.0
Shell 1.7.13
Node 7.9.0
V8 5.8.283.38
Architecture x64

libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.11 libidn/1.32 librtmp/2.3

**Comment by TerkiKerel** [comment]
Sorry I see the increase option now..

**Comment by gschier** [comment]
😄
