### ISSUE TITLE
[Feature Request] Option to Rember Last Value of Prompt

### ISSUE THREAD

**Issue by jGleitz** [getinsomnia/insomnia#891]
- Insomnia Version: 5.15.0
- Operating System: Ubuntu 17.10

## Details

I like to use prompts to enter variables into my requests. However, they can also be distracting when repeating a request.

I would find it helpful to have an option on prompts that will make them preserve the value I entered last. This way, I could re-send a request by just hitting enter twice, without having to type in anything.

**Comment by gschier** [comment]
Hey @jGleitz,

This is actually already implemented and will show up in the next version 😀 

It adds a new field to the prompt tag to enable this. 

![image](https://user-images.githubusercontent.com/587576/39243693-5e1b2afa-485c-11e8-90e3-06fb2213a227.png)

**Comment by gschier** [comment]
Here's the commit for reference: https://github.com/getinsomnia/insomnia/commit/d0d6c4b57fb2b6654553317160737057d2a38da8

**Comment by jGleitz** [comment]
Hey, @gschier, very cool that you already implemented it! Looking forward to the release!

**Comment by gschier** [comment]
😄
