### ISSUE TITLE
[Bug] Error rendering query when GraphQL body includes a comment

### ISSUE THREAD

**Issue by NinnOgTonic** [getinsomnia/insomnia#895]
- Insomnia Version: Version 5.16.0 (5.16.0.2017)
- Operating System: OSX 10.13.3 (17D102)

## Details

When trying to render the following query (at any or an empty target endpoint) the insomnia client fails:

```
# query {
#	viewer {
#		serviceConsents {
#			id
#			externalVehicleId
#			externalUserId
#			serviceId
#			vehicleId
#			scope
#			startTime
#			endTime
#		}
#	}
#}

query {
	services {
		id
		name
		scope
	}
}
```

The error can be seen here: https://i.imgur.com/ENDSB5u.png

But writes:
```
Render error
> unexpected end of comment

Caused by the following field
> Request.body.text
```

This is obviously not correct so there appears to be a bug in the query parsing, as the above query, including the comment is compleatly valid, and the linter picks it up perfectly? Perhaps do not try to strip comments to begin with, graphiql doesn't either?

**Comment by gschier** [comment]
Hmm, this might be tricky to fix. Specifically, it's because of this line: `#}`. All requests are rendered by Nunjucks before sending (to power environments) and `#}` signifies the end of a `{# nunjucks comment #}`.

As a temporary workaround for now, just make sure there's a space between the "#" and the "}"

**Comment by NinnOgTonic** [comment]
Hmm fair point, perhaps it would be solved by implementing https://github.com/getinsomnia/insomnia/issues/852 prior to the nunjucks rendering?

**Comment by NinnOgTonic** [comment]
Or perhaps not, i think i misunderstood what that issue actually ment, i.e. just on send, render it prettified, rather than an "auto format on send". None the less, i will keep the work around in mind.
