### ISSUE TITLE
[Bug] Undo after Prettify GraphQL blanks the query editor

### ISSUE THREAD

**Issue by NinnOgTonic** [getinsomnia/insomnia#896]
- Insomnia Version: Version 5.16.0 (5.16.0.2017)
- Operating System: OSX 10.13.3 (17D102)

## Details

If you undo after pressing `Prettify GraphQL` the query editor will simply blank out instead of reverting to the previous contents of the query editor, no matter how many times you press Undo (CMD+Z). Thus there appears to be some bug that some how destroy basic and native undo functionality that is otherwise alive and well in the editor window.

I tested on the following contents:

```
# query {
#	viewer {
#		serviceConsents {
#			id
#			externalVehicleId
#			externalUserId
#			serviceId
#			vehicleId
#			scope
#			startTime
#			endTime
#		}
#	}
#}

query {
	services {
		id
		name
		scope
	}
}
```

**Comment by nahid-amini** [comment]
Any updates on this bug fix?
Insomnia version 6.0.2 (6.0.2.2311) 

Thanks
