### ISSUE TITLE
[BUG]: Certificate with aumlat not showing..related to #859

### ISSUE THREAD

**Issue by nmat** [getinsomnia/insomnia#898]
- Insomnia Version: 5.16.0
- Operating System: Windows 10

## Details

The output for the certificate is also only showing ? on aumlat.

This is related to: https://github.com/getinsomnia/insomnia/issues/859

Output in timeline should most likely also follow output for UTF-8 to be able to handle certificates using special characters.

**Comment by gschier** [comment]
Hey @nmat. Any chance you can provide an example endpoint for me to test with that showcases this?

**Comment by nmat** [comment]
https://www.oru.se/

Is the örebro university. In the certificate in timeline you can see the output as ? for the ö in the name.
