### ISSUE TITLE
[Bug] Error: libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lovasoa** [getinsomnia/insomnia#899]
Since the latest update, insomnia doesn't open anymore when using the appImage

- Insomnia Version: v5.16.0 (latest)
- Operating System: Linux Fedora 27

## Details

The following error is printed on the console:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libssl.so.1.0.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_insomnIbLHJr/app/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:40:29)
    at Object.<anonymous> (/tmp/.mount_insomnIbLHJr/app/resources/app.asar/node_modules/insomnia-node-libcurl/lib/Easy.js:280:3)
```

**Comment by gschier** [comment]
Hmm, that's strange. It should be statically linking libssl on build time. I should be able to fix this but for now, just continue using the previous version.

**Comment by rocketraman** [comment]
Same error here with 5.16.1, Linux Fedora 27 same as the OP.

**Comment by kabo** [comment]
Same here with 5.16.1 on Debian Buster.

**Comment by mahtuag** [comment]
Same error here with Fedora 27

**Comment by simoniz0r** [comment]
Same problem on openSUSE Tumbleweed.

**Comment by gschier** [comment]
Working on a fix today. Hopefully it won't take too long.

**Comment by gschier** [comment]
Did it! Finally got OpenSSL compiled into the app. I'll ship a new AppImage later today (hopefully).

![image](https://user-images.githubusercontent.com/587576/39382007-0bf688e6-4a32-11e8-8d0c-8438f15d55a7.png)

**Comment by gschier** [comment]
I just uploaded a new `Appimage` to the github release. You can download it here https://github.com/getinsomnia/insomnia/releases/download/v5.16.1/insomnia-5.16.1-x86_64.AppImage

**Comment by gschier** [comment]
False alarm. I got it _working_ but it doesn't include `zlib` or `nghttp` (for HTTP/2 support) anymore 😢

**Comment by gschier** [comment]
Okay, I hopefully have something working now. I uploaded it to the last release.

👇 ⬇️ 🔽 🙃 
https://github.com/getinsomnia/insomnia/releases/download/v5.16.1/insomnia-5.16.1-x86_64.AppImage

**Comment by simoniz0r** [comment]
Seems to be working again, thanks!

**Comment by rocketraman** [comment]
Confirmed, thanks!

**Comment by gschier** [comment]
🍾 😄
