### ISSUE TITLE
Cannot Login into Insomnia account ** 'n' == 'BigInteger' error

### ISSUE THREAD

**Issue by jdorleans** [getinsomnia/insomnia#900]
- Insomnia Version: 5.16.0
- Operating System: Ubuntu 18.04

## Details

I cannot Login into Insomnia account, although I'm able to login through the website. I'm also getting a weird error: `** 'n' == 'BigInteger'`

![image](https://user-images.githubusercontent.com/1254399/39296681-8c895110-490f-11e8-984e-556601e2b571.png)

**Comment by gschier** [comment]
Hmm, this is strange. It seems something in the Linux build changed that's now causing this. Easy fix, though. Will git it fixed today 👍 ⚡️

**Comment by gschier** [comment]
Correction, this is a problem on ALL production builds across all platforms.

**Comment by gschier** [comment]
Forgot to close this in the commit message but it should be fixed and live now via https://github.com/getinsomnia/insomnia/commit/00223ad1a077fcfc0b3aa9b26f071f9fa75b216e

**Comment by jdorleans** [comment]
I can confirm the issue was fixed with in my case with version 5.16.1. Thx!

**Comment by gschier** [comment]
Woo! Happy to hear that. Thanks for letting me know
