### ISSUE TITLE
[Improvement] Bad quality of icon in desktop client

### ISSUE THREAD

**Issue by PavelDemyanenko** [getinsomnia/insomnia#901]
[Improvement] – bad quality of icon in desktop client

- Insomnia Version: 5.15.0
- Operating System: win7 pro

## Details
Low quality of icon in taskbar. Very minor, but would be great to see high quality
[img preview](https://imgur.com/a/H4OU5CL)

**Comment by gschier** [comment]
Oh no, that looks awful. I'll see if I can get it fixed.

**Comment by PavelDemyanenko** [comment]
@gschier on win10 there is no icon at all in taskbar =/

**Comment by pundoo** [comment]
Same here in Windows 8.1. Seems like a generic issue!

**Comment by gschier** [comment]
So I have a Windows 10 VM and a Windows 10 Bootcamp install on my Mac. In the VM, I can confirm the icon issue (it appears to be missing) but on the native Bootcamp install it looks fine. 

Are you familiar enough with Windows @PavelDemyanenko to debug this issue?

**Comment by PavelDemyanenko** [comment]
@gschier later today i can up win10 vm and check from latest changes if the icon is still missing
