### ISSUE TITLE
[Improvement] Support Postman Collection format v2.1

### ISSUE THREAD

**Issue by TerkiKerel** [getinsomnia/insomnia#903]
Hi

I export my requests from Rester (add-on for Firefox). It exports as postman format. I will not put all the file here but it starts as below:

{
    "info": {
        "name": "RESTer",
        "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    "item": [
        {
            "name": "projectname",
            "item": [
                {
                    "request": {
                        "url": "http://google.com",
                        "method": "POST",
                        "header": [
                            {
                                "key": "Accept",
                                "value": "application/json"
                            },
                            {
                                "key": "Content-Type",
                                "value": "application/json"
                            }
                        ],
                        "body": {
                            "mode": "raw",
                            "raw": "{ }"
                        }
                    },
                    "id": "rester-37",
                    "name": "info"
                },

...

When I try to import this file to insomnia it does nothing. I opened insomnia from console to see the outputs, but nothing it prints.

I would be happy if you can help me.

Thank you

------------------
Details of my insomnia:

Version 5.15.0
Shell 1.7.13
Node 7.9.0
V8 5.8.283.38
Architecture x64

libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.11 libidn/1.32 librtmp/2.3

**Comment by gschier** [comment]
Hey @TerkiKerel. Right now, Insomnia only supports Postman collection format v2.0. Support for v2.1 should be arriving in the future.

**Comment by coderjoe** [comment]
This may be fixed as of #1233

**Comment by gschier** [comment]
Yes, I think it does! 😄
