### ISSUE TITLE
[Bug] Lots of extra text is selected when selecting all 'Live Preview' text in 'Edit Variable/Tag' window

### ISSUE THREAD

**Issue by 4ekki** [getinsomnia/insomnia#904]
- Insomnia Version: 5.16.1
- Operating System: win 10

## Details
Background text (like names of saved requests, buttons labels) is also selected when selecting whole 'Live Preview' text in 'Edit Variable' or 'Edit Tag' window. 

Steps to reproduce: 
1. Open 'Edit Tag' or 'Edit Variable' window
2. Triple-click value in 'Live Preview' field (or click within it and press Ctrl+A)
![image](https://user-images.githubusercontent.com/38757986/39308202-8a988c1e-496d-11e8-9b28-728109e9e09d.png)
3. Copy selected value and Paste it somewhere 

As a result, tons of extra text is copied instead of value.  Expected that 'select all' action doesn't select text out of the field (only "No request specified" for the case on the screenshot)
On the screenshot, you can note extra trailing 'space' selected. Looks like this is related.

**Comment by gschier** [comment]
Hmm that preview will have to be changed from `<div>` to `<textarea>` to prevent over-selection. I don't think there's any other way to do it in web dev.
