### ISSUE TITLE
Kali Linux - Insomnia 5.16 / 5.16.1 client start issue

### ISSUE THREAD

**Issue by Os3r3um** [getinsomnia/insomnia#906]
Hi there, 

Got an issue with Insomnia REST client(5.16 until 5.16.1) as the app does not start after an upgrade or a fresh install. 

```Reproduction:```

Have installed Insomnia REST client with any Kali Linux 2018, fully patched. Try to launch it. Nothing happens. 

Downgrade the client to a previous version like 5.15 and everything goes back to normal. 

- Insomnia Version: 5.16 and 5.16.1
- Operating System: Kali Linux(a Debian Based distro)

[Question] – How do I fix this? 

Cheers.

**Comment by gschier** [comment]
Can you try launching it from the terminal and see if there are any errors?

**Comment by Os3r3um** [comment]
Yep. Here's the output: 

![image](https://user-images.githubusercontent.com/3704868/39411340-6117942e-4c5c-11e8-8598-7f10256003bd.png)

**Comment by gschier** [comment]
Oh I've seen that before. I just fixed this yesterday but thought it was only present in the AppImage build.

I just uploaded a fixed `deb` to the latest GitHub release. For now, you can download the manually here https://github.com/getinsomnia/insomnia/releases/download/v5.16.1/insomnia_5.16.1_amd64.deb

Let me know if that works for you 😄

**Comment by Os3r3um** [comment]
It worked like a charm :+1:  Much appreciated.

**Comment by gschier** [comment]
Woo! 😄
