### ISSUE TITLE
[BUG] AWS SigV4 Override Values Not Respected

### ISSUE THREAD

**Issue by c22** [getinsomnia/insomnia#907]
- Insomnia Version: 5.16.1
- Operating System: MacOS

## Details

As far as I can tell, the changes made in #830 / e0bfed5 are not working as intended. The region seems to be always set to us-east-1 unless the region appears in the URL and the service is also seemingly only being determined from the URL even if you try to override it.

Steps to reproduce:

GET: https://ec2.amazonaws.com
REGION: us-west-2
SERVICE: ec3

Result:
`Credential=[MY_KEY_ID]/20180401/us-east-1/ec2/aws4_request`

Expected Result:
`Credential=[MY_KEY_ID]/20180401/us-west-2/ec3/aws4_request`

**Comment by gschier** [comment]
You know, you're right! I just took a look at that PR and it looks like the entire thing is UI but I never actually added the code to _use_ the values.

I don't have an API to test this with so I never noticed.

**Comment by gschier** [comment]
I didn't make a new release for this yet but I've uploaded a new build to the last release page. Let me know if it works!

https://github.com/getinsomnia/insomnia/releases/download/v5.16.1/Insomnia-5.16.1-mac.zip
or
https://github.com/getinsomnia/insomnia/releases/download/v5.16.1/Insomnia-5.16.1.dmg

**Comment by c22** [comment]
I suggest actually using `https://ec2.amazonaws.com/?Action=DescribeRegions&Version=2013-10-15` in your URL as the test because this is a valid API call (it seems AWS endpoints validate the API call before checking authorization). Also I am not sure if your test will work as the date part of the authorization header will change depending on what the time is when you run the tests (it won't always be 20180430).

Aside from all that, it seems that SigV4 auth doesn't actually work. Your changes work perfectly, the information is being substituted correctly in the right spot, but the authorization header seems to be incorrect. I tried on the original 5.16.1 build and the build you linked above, both don't work. Seems like it should be a new issue.

I am surprised nobody has noticed this wasn't working before? Please correct me if I am wrong.

**Comment by gschier** [comment]
Thanks for the info about the date @c22. I didn't even realize that parameter was a date. I'll change it to a looser match inside the regex.

Ya, feel free to submit a new issue. If you could provide a specific test case (request + expected token) it would help make the issue easier to debug. Also, if you want to take a look at debugging the issue from your end that would be much appreciated too 😄
