### ISSUE TITLE
Documentation links pointing to helpscout

### ISSUE THREAD

**Issue by bejoyjaison** [getinsomnia/insomnia#909]
- Insomnia Version: 5.16.1
- Operating System: Windows 7

## Details

Documentation Page: https://support.insomnia.rest/article/43-chaining-requests
Links: "Template Tags" or "Environment Variables" (found in line 4 or 5 just after the note box) are pointing to https://secure.helpscout.net rather than https://support.insomnia.rest/

**Comment by gschier** [comment]
Forgot to close this. These links were fixed a while back 😄 👍
