### ISSUE TITLE
[BUG] AWS SigV4 Doesn't Work Without Manually Setting Content-Type Header

### ISSUE THREAD

**Issue by c22** [getinsomnia/insomnia#910]
- Insomnia Version: 5.16.1
- Operating System: macOS

## Details

As discovered in #907, Insomnia doesn't behave quite well with SigV4 signing. This is because  `content-type` is being set in the SignedHeaders section of the auth string, even if there is no Content-Type header set. SigV4 only _requires_ that Host and x-amz-date be signed (DynamoDB requires that content-type and x-amz-target be set), `RequestSigner.prototype.signedHeaders` in `yarn-standalone.js` essentially signs all headers. I haven't been able to work out where content-type is erroneously being included in this list of headers to sign, whether this is because of something in `yarn-standalone.js` or somewhere else.

The workaround is to add a Content-Type header with *some* value in it, it doesn't matter what you put in there as long as it's not empty. I recommend using `text/xml;charset=UTF-8` if working with the AWS APIs.

**Comment by c22** [comment]
AFAIK this is still an issue. Will take a quick look on Monday. It seems unlikely that this would be a bug in Yarn, but it might be?

**Comment by gschier** [comment]
Yarn is currently only used to fetch plugins so wouldn't be the cause. You'll find the AWS signing logic in `network.js`. I'm pretty sure there are also some tests around this logic in `network.test.js`. 

If you'd like to take a look that'd be awesome. I'd also be happy to look if you can give me a sample input/output that I can use to verify the behavior.

**Comment by gschier** [comment]
I think I fixed it! Apparently there was a already a test case that didn't use `content-type` but the test was asserting an incorrect result.

**Comment by c22** [comment]
Well I feel silly for not seeing that when I looked at this earlier 😅 thanks Greg, LGTM! I'll give it a test on Monday.
