### ISSUE TITLE
[Bug] OAuth 2 ACCESS TOKEN URL does not accept environment variable

### ISSUE THREAD

**Issue by DCRichards** [getinsomnia/insomnia#911]
- Insomnia Version: 5.16.1 (5.16.1)
- Operating System: Mac OS 10.12.6

## Details

When using the OAuth 2 authentication within a request, Resource Owner Password Credentials takes `ACCESS TOKEN URL`. However, when this is used with a nunjucks variable, such as `{{ tokenUrl }}`, the request fails with the following message:

> [oauth2] Failed to fetch access token url= status=0

It seems that Insomnia is not correctly parsing variables for this particular field, as the variable is a valid URL such as `https://domain.tld/api/token`. A screenshot of the fields is shown below:

![](https://i.imgur.com/6zVXLHN.png)

**Comment by gschier** [comment]
I think part of the problem is that the changes are debounced at 500ms. Going to remove the debouncing on that form as it isn't really needed.

**Comment by gschier** [comment]
I have a feeling that removing the debouncing probably "fixed" this issue. Feel free to comment if it's still happening but I'm going to close it for now.
