### ISSUE TITLE
[Build] Icon on linux looks bad

### ISSUE THREAD

**Issue by DracotMolver** [getinsomnia/insomnia#913]
Version 5.16.1
Shell 1.8.4
Node 8.2.1
V8 5.9.211.38
Architecture x64

Operating System: Solus os (linux)

## Details
The icon looks like this.
![icon_insomnia](https://user-images.githubusercontent.com/13334764/39495856-83f662e2-4d72-11e8-8262-1e892922d776.png)

I used AppImage

**Comment by gschier** [comment]
Can you provide a larger screenshot? It's hard to tell what it's a screenshot of.

**Comment by gschier** [comment]
P.S. did this just start happening in the latest version?

**Comment by DracotMolver** [comment]
@gschier yes. It is not the first time I have Insomnia on this Linux OS.
![captura](https://user-images.githubusercontent.com/13334764/39554827-768a9694-4e4b-11e8-9b4b-b4cedd1cc479.png)

Maybe it's an issue of the OS. But, I have others app that I ran using AppImage

**Comment by gschier** [comment]
Thanks. I think I might have fixed this in 5.16.2, although I wasn't able to test it. Can you let me know if it's still happening? Going to close this for now but will re-open if it's still an issue.

**Comment by DracotMolver** [comment]
@gschier The image now is displaying well!. Beautiful, thanks! :smiley: :+1:

**Comment by gschier** [comment]
Woo!
