### ISSUE TITLE
Overriding "Follow redirects automatically" in request settings

### ISSUE THREAD

**Issue by silversmurf** [getinsomnia/insomnia#915]
- Insomnia Version: 5.16.1
- Operating System: Win 10

## Details

Is it possible to override the global preference "Follow redirects automatically" within any request settings?
Maybe something like "OFF <-> GLOBAL <-> ON", whereas GLOBAL will be the default.

It's really annoying, every time to disable the redirects, for just a couple of requests (OAuth location token, etc.).

I would appreciate, if you implement this feature. Thanks...

**Comment by jdempster** [comment]
Still an issue.

**Comment by martyglaubitz** [comment]
I just had the same problem - i was trying to debug whether the server sends the correct Location header

**Comment by namaggarwal** [comment]
@martyglaubitz Are you saying there is already a global setting to turnoff follow redirects ?

**Comment by martyglaubitz** [comment]
@namaggarwal yes - but not on a per-request basis...

**Comment by NilayMajorwar** [comment]
Can I take this up?

**Comment by jmevel** [comment]
It seems the `global setting` is by default to `Follow redirects` but where is this setting in the preferences?
For the life of me I can't find it anywhere

**Comment by TheoKondak** [comment]
> It seems the `global setting` is by default to `Follow redirects` but where is this setting in the preferences? For the life of me I can't find it anywhere

A couple of years too late, but the setting is in Pref -> General -> Request/Response -> Follow Redirects. This is not a per-request redirect, rather a general rule.

In v12.5.0 this option is disabled by default
