### ISSUE TITLE
[Bug] Insomnia freezes on long JSON lines

### ISSUE THREAD

**Issue by nguillermin** [getinsomnia/insomnia#916]
- Insomnia Version: 5.16.1
- Operating System: Win10

## Details

I'm using a specific service (Heartland OneCard) who base64-encodes user pictures in their REST API for an "Account Summary" type request. The size of this string can be on the order of 250kB+. Clicking on the request in the sidebar will temporarily freeze Insomnia as it parses the response. After it resumes, scrolling is smooth. Is it possible to either speed the parsing up or otherwise decouple the parsing so that the UI doesn't lock up while it's thinking?

**Comment by gschier** [comment]
Quick question. Is it still slow when "Wrap Long Lines" is enabled in the app settings?
