### ISSUE TITLE
[Bug] Swagger importer does not use latest changes

### ISSUE THREAD

**Issue by avdv** [getinsomnia/insomnia#918]
- Insomnia Version: 5.16.1
- Operating System: Arch Linux 

## Details

I am using the latest version of insomnia (installed from AUR), supposedly including the fix for #861 but when trying to import a swagger definition, the path is still not properly handled.

E.g. `/api/v1/{channel}/items/{asset}` still results in `/api/v1/{{ channel}/items/{asset }}` just as if the latest changes were not packaged into the app.

I also rebuild insomnia from the develop branch (commit e8aba9941760ade6f76553a436269a0b21038507) running `packages/insomnia-app/dist/linux-unpacked/insomnia` afterwards, but this shows the same problem.

However, using `bin/cli swagger.json` from the `packages/insomnia-importers` folder directly works as expected and shows `/api/v1/{{ channel }}/items/{{ asset }}` in the output. Importing the generated file also works as expected.

Where is the old behaviour coming from?

**Comment by avdv** [comment]
@gschier Yes, it is working with 5.16.2 :tada: !

**Comment by gschier** [comment]
Nice!
