### ISSUE TITLE
Installation failed on Windows 10

### ISSUE THREAD

**Issue by mburakkalkan** [getinsomnia/insomnia#923]
- Insomnia Version: 5.16.2
- Operating System: Windows 10 Home x64 (1709)

## Details

Downloaded Insomnia 5.16.2 and started the setup but it failed. Tried by run as administrator but no success. Here is the setup log: https://paste.ubuntu.com/p/Q5F7TYv5jN/

**Comment by gschier** [comment]
Sorry for missing this one. It looks like you don't have access to write to the following directory `C:\Users\mbura\AppData\Local\insomnia\app-5.16.2\`

**Comment by ASing0** [comment]
I'm having the same issue on Windows 10. I have permissions on the folder. I have tried several steps to remove temp files, grant other permissions etc. but the issue persists. 
![image](https://user-images.githubusercontent.com/29284114/79927033-7d025400-840c-11ea-8380-a19c39ffd452.png)

**Comment by vigamage** [comment]
i am also having the same issue

**Comment by rveda1** [comment]
Any update on this issue? I am have the same issue.

**Comment by Rubendvb** [comment]
I also have the same problem. Has anyone solved it?

**Comment by augustoaraujoo** [comment]
i am also having the same issue

**Comment by dimitropoulos** [comment]
Could you say a little more about what the circumstance is - and by that I mean, is this a company computer where there are restrictions on writing?  It's always useful if you can provide a screenshot or a log, and also some OS information (and insomnia version).

**Comment by Angus1811** [comment]
I had the same Problem. I found that the reason this was happening was due to **low disc space**.
