### ISSUE TITLE
[Bug] – io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: Unknown Params: \"__export_source\": \"insomnia.desktop.app:v5.15.0\",

### ISSUE THREAD

**Issue by binque** [getinsomnia/insomnia#924]
[Bug] – io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: Unknown Params: \"__export_source\": \"insomnia.desktop.app:v5.15.0\",

- Insomnia Version: 5.15.0
- Operating System: mac 10.13.4

Exception print 
 io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: Unknown Params: \"__export_source\": \"insomnia.desktop.app:v5.15.0\";
when upload a file to a vertx server.

But I made this request in postman, it works.

**Comment by gschier** [comment]
Can you post the request you are trying to make?
