### ISSUE TITLE
[Bug] URL preview covers edit form

### ISSUE THREAD

**Issue by murame** [getinsomnia/insomnia#927]
- Insomnia Version: 5.16.2
- Operating System: Windows 7 Professional x64

## Details

The same issue as #300 is occurring.
Url preview takes up the entire screen, and query parameter can not be added or edited.
Also, it takes time to display long query parameter values in the url preview.
Is there a way to hide url preview?

**Comment by gschier** [comment]
There's no way to hide the preview right now but I'll make sure it doesn't cover the whole thing in the next release 👍

**Comment by murame** [comment]
I confirmed that it is not covered by URL preview with version 5.16.4.
Thank you!
![screenshot_4](https://user-images.githubusercontent.com/39079071/40459601-4499e1c8-5f3d-11e8-9b2c-630877e34f6e.png)

**Comment by gschier** [comment]
Oo, nice! I forgot to close this issue so will do it now 👍
