### ISSUE TITLE
Disable creating shortcut on update

### ISSUE THREAD

**Issue by joshuaavalon** [getinsomnia/insomnia#928]
- Insomnia Version: 5.16.2
- Operating System: Win 7 Pro

## Details
After every time Insomnia update, it creates a shortcut on desktop. Can I disable it?

**Comment by 2f4f4f** [comment]
Duplicate of https://github.com/getinsomnia/insomnia/issues/44 ?

**Comment by joshuaavalon** [comment]
@2f4f4f Yes, I will close this in favor of #44
