### ISSUE TITLE
[Feature Request] - Allow multiple env variables in base64 encode/decode

### ISSUE THREAD

**Issue by Fyb3roptik** [getinsomnia/insomnia#930]
With oauth2 I need to be able to send Authorization Basic encode(client_id:secret)

Right now I can only do 1 variable at a time

**Comment by gschier** [comment]
You have to options for this one.

1. Use Insomnia's built-in Basic Auth

![image](https://user-images.githubusercontent.com/587576/40032771-9094af1c-57c3-11e8-99f6-d2e90105a8ca.png)

2. Use two tags

![image](https://user-images.githubusercontent.com/587576/40032783-9fe52b9a-57c3-11e8-8e62-6060e38a548b.png)

**Comment by gschier** [comment]
You have two options for this one.

The easiest solution is to use Insomnia's built-in Basic Auth support

![image](https://user-images.githubusercontent.com/587576/40032831-bbef7624-57c3-11e8-832b-0330528a4481.png)

You _can_ also do it manually but it's a bit of work. You'll need to use a temporary variable:

![image](https://user-images.githubusercontent.com/587576/40032912-09cea522-57c4-11e8-92cd-d0814611bd4c.png)

**Comment by gschier** [comment]
Sorry, I just noticed you mentioned OAuth 2. Are you using Insomnia's built-in OAuth 2 support or doing it manually?

**Comment by Fyb3roptik** [comment]
I tried to use OAUTH2 and Basic and neither add Authorization Basic base64_encode(client_id:client_secret) to the header as required

**Comment by Fyb3roptik** [comment]
Ah right...making it another variable works...would be nice to be able to keep these separate, but this works for now! Thanks!

**Comment by gschier** [comment]
Ya no problem!
