### ISSUE TITLE
[Usability] Request pane loses focus after changing body type

### ISSUE THREAD

**Issue by mlambley** [getinsomnia/insomnia#931]
https://github.com/getinsomnia/insomnia/blob/63ec162cb81c6ac943910d947fdf2e4416896bbe/packages/insomnia-app/app/ui/containers/app.js#L386

Can the above be refactored please? When I switch from No Body to JSON, I immediately click into the request pane to change the json. But it then loses focus because of the 300ms delay before refreshing it.

![insomnia blur](https://user-images.githubusercontent.com/17264636/40030885-59336cd0-5830-11e8-9fac-6cf31cff59ca.gif)

Thank you.

**Comment by gschier** [comment]
I forgot about that one. Quite a bad hack. Remove that will take quite a bit of effort but, you're right, it needs to be done.

**Comment by mlambley** [comment]
Your bot wants to close this. Any ideas on how it might be done?

**Comment by gschier** [comment]
I haven't had time to take a look at it yet. That code was written a long time ago so I'd have to refresh my memory.

**Comment by mlambley** [comment]
Bump or close?

**Comment by gschier** [comment]
On it!
