### ISSUE TITLE
[Bug] GraphQL replaying last query param

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#933]
- Insomnia Version: 5.16.2
- Operating System: Arch Linux

## Details

Hey there!

I have the following query:

```
{
  papeis(order: "nome") {
    content {
      nome
    }
  }
}
```

Which generates the following content when sending the request:
```
{"query":"{papeis(order: \"nome\") {content {nome}}}"}
```

But if I remove the query param, like this:
```
{
  papeis() {
    content {
      nome
    }
  }
}
```

Insomnia generates the following content when sending the request:
```
{"query":"{papeis(order: \"nome\") {content {nome}}}"}
```

As you can see, `order: "nome"` was sent again even tho I removed it from the query.

In order to strip this param, I have to remove the query brackets, like this:

```
{
  papeis {
    content {
      nome
    }
  }
}
```

I guess this is a bug, because Insomnia is sending the last query param when actually I'm sending none.

Best regards,
Rafael Pacheco.

**Comment by gschier** [comment]
I think it's doing that because it's invalid GraphQL to have empty params like that.

Insomnia should probably still send the invalid query in that case though even if it fails to parse it.

**Comment by gschier** [comment]
Hmm, I tried to reproduce your bug just and and wasn't able to. It sends invalid GraphQL queries just fine for me 😕 

Anyway, the errors should be showing up now again in the latest release.
