### ISSUE TITLE
[Improvement] Plugin (Template Tag) Run Context

### ISSUE THREAD

**Issue by evanrobertson** [getinsomnia/insomnia#934]
When creating a plugin it would be great to know what context it is being run in. Currently run will be called in a few different scenarios that can't be differentiated.

The scenarios I currently see are:

1. Initial creation
2. Opening tag UI - i.e. clicking on the tag
3. Refresh clicked in tag UI
4. Request send

An  example of why this becomes useful can be seen in the built in uuid plugin. 

- Add the uuid tag to the body of a request you can hover the item and see it's value. 
- You then click the tag and it creates a new uuid in the UI that appears. 
- Send the request and neither the uuid you see when hovered or when generated in the tag UI are actually the uuid sent in the request as it gets regenerated on request.

See example:
![uuid](https://user-images.githubusercontent.com/4754029/40093680-a9d5cbac-5906-11e8-8fe5-bbfb8fbeff6e.gif)

**Comment by gschier** [comment]
After thinking about this a bit, I'm not sure exposing the purpose solves your issue very well.

I might have a better idea for how you can do this. The following code implements a basic UUID template tag that will always return the same value for a request until the request is sent. 

```js
const uuid = require('uuid');

const __cache = {
  // <RequestID>: <UUID>
};

module.exports.responseHooks = [
  context => {
    const requestId = context.response.getRequestId();

    // Delete cached uuid on response so a new one will be generated next time
    delete __cache[requestId];
  }
];

module.exports.templateTags = [{
  displayName: 'Cached UUID',
  name: 'cached_uuid',
  run (context) {
    const {requestId} = context.meta;

    // If there isn't a uuid in the cache yet for this request, set one
    if (!__cache[requestId]) {
      __cache[requestId] = uuid.v4();
    }

    // Return cached uuid for request
    return __cache[requestId];
  }
}];
```

Essentially, the above plugin maintains its own internal render cache for each request that gets cleared whenever a new response is received.

**Comment by gschier** [comment]
Hmm, that doesn't actually seem to work because `__cache` isn't a true global (it's different for the hook and template tag. Will keep trying..

**Comment by gschier** [comment]
Here we go. Added a `store` API that plugins can use to globally store values:

```js
const uuid = require('uuid');

module.exports.responseHooks = [
  context => {
    const requestId = context.response.getRequestId();

    // Delete cached uuid on response so a new one will be generated next time
    context.store.clearItem(requestId);
  }
];

module.exports.templateTags = [{
  displayName: 'Cached UUID',
  name: 'cached_uuid',
  async run (context) {
    const {requestId} = context.meta;

    const cachedValue = await context.store.getItem(requestId);

    // If no cached value, set one
    if (cachedValue === null) {
      await context.store.setItem(requestId, uuid.v4());
    }

    // Return cached uuid for request
    return context.store.getItem(requestId);
  }
}];
```
