### ISSUE TITLE
[Feature Request] Navigate sidebar similar to a File Manager using keyboard arrows

### ISSUE THREAD

**Issue by jdorleans** [getinsomnia/insomnia#936]
- Insomnia Version: 5.16.2
- Operating System: Ubuntu 18.04

## Details
Since I rarely use a mouse, I'd like to navigate the sidebar similar to a File Manager by using keyboard arrows and enter key. 

### Navigation (arrows key)
When having the focus on the sidebar, we should be able to navigate folder/files similar to a File Manager. This would be by moving the selector (focus) up and down using the keys :arrow_up: and :arrow_down: in addition to expanding (:arrow_right:) or collapsing (:arrow_left:) folders with right and left arrows, respectively. 

### Selection (enter/return key)
In order to visualise a selected file, we then press Enter key (:leftwards_arrow_with_hook:). In case a folder is selected instead of a file, Enter should expand or collapse the folder depending on its current state.

### Renaming folder or file
This is also a huge plus IHMO. While evolving my API, often times I duplicate folders with several pre-made requests I want to reuse and thus have to rename all copied folders and files. In order to do so today, I'm forced to click-right and select rename a folder or go to settings in case of a file request or quickly double-click each of them to rename in-local (this btw, doesn't work very well because of double-click timing). Instead I'd just prefer to press the traditional **F2** key and rename them in-place (no pop-ups showing up).

### Focus
Finally, it'd also be super useful to jump the focus from sidebar to the current file or vice-versa by just using a key such as **ESC**.

**Comment by gschier** [comment]
Will leave this one open. Sorry I haven't responded to it yet.
