### ISSUE TITLE
[Bug] preview shows empty json when actual data is returned from the server

### ISSUE THREAD

**Issue by rvwoens** [getinsomnia/insomnia#938]
- Insomnia Version: 5.16.2 (5.16.2.2044)
- Operating System: macOS 10.13.4

## Details
Sometimes preview AND source  shows empty json while raw shows the actual content. This seems to be related to something beeing stuck in the insomnia request cache, because re-creating the request solves this issue:

![screen shot 2018-05-19 at 11 50 18](https://user-images.githubusercontent.com/97624/40267293-d4f8cb80-5b5a-11e8-9178-f34ce9b9bf61.png)

While the raw view shows that there is data received from the server:
![screen shot 2018-05-19 at 11 51 15](https://user-images.githubusercontent.com/97624/40267301-f935e05a-5b5a-11e8-8721-8bb23d6b5dcd.png)

This is all very valid JSON, but for some reason preview does not seem to like it. Resending the request does not fix this, restarting insomnia does not fix this. The only way to fix it is to completely re-create the request in insomnia.

This is a very annoying thing as this sends me on the complete wrong path wondering why the server does not give any data where in fact is does.

This is the header result from the server
![screen shot 2018-05-19 at 11 53 17](https://user-images.githubusercontent.com/97624/40267371-493c14ac-5b5b-11e8-8ce3-3ee905c04d29.png)

**Comment by Gabb1995** [comment]
Are you sure you didn't have the jsonpath written in the bottom right?

**Comment by gschier** [comment]
@Gabb1995 seems like that's probably the case. Going to close this one for now but will re-open if @rvwoens can provide some more info.

**Comment by molp** [comment]
Hey, not sure if I should resurrect this, or create a new issue. I have the exact same problem: The preview doesn't show the result returned from the server.

This is the preview:
![image](https://user-images.githubusercontent.com/1836282/161069345-1fda5c30-dc4a-4b3a-8aa3-9dc903d04a88.png)

This is the actual result:
![image](https://user-images.githubusercontent.com/1836282/161069437-7c48d043-7cd5-4c71-bcf3-eadd9617915e.png)

In case the json itself is relevant:
```json
{"lines":[{"ticker":"DW.IC1","date":"2022-03-31T00:00:00.000+02:00","currencyCode":"ICA","open":121.0,"close":121.0,"low":121.0,"high":121.0,"trades":1,"tradedUnits":1,"tradedVolume":121.0}],"source":null}
```

Version
![image](https://user-images.githubusercontent.com/1836282/161069271-18d198fb-2950-457f-a4ad-0b5f7fad2da9.png)
