### ISSUE TITLE
[Feature Request] Provide a Flatpak as software package — for Linux systems

### ISSUE THREAD

**Issue by x80486** [getinsomnia/insomnia#939]
[Flatpak](http://docs.flatpak.org/en/latest/introduction.html) is a technology for building, distributing, installing and running applications – primarily targeted at the Linux desktop and desktop applications.

I use **Arch Linux**, and while there is an "official" package for **Insomnia** (though I don't use `AUR`), it would be awesome to have the option to install it via a Flatpak.

**Comment by mpdeimos** [comment]
Here is some further context as you provide already a Snap and AppImage of Insomnia:
On ArchLinux Flatpak is a first-class application distribution method officially supported by the maintainers (you can install the Flatpak packages from the official repositories). Like Insomnia, AppImage and Snap have to be installed from AUR and some users prefer to keep the list of AUR to a minimum (there are no automatic updates unless you fiddle with AUR helpers).
Having Insomnia packaged as Flatpak (e.g. on flathub.org) will allow easy installation and updates for Arch Linux and also other distributions like Fedora or RHEL.

**Comment by baszczewski** [comment]
I just created Flathub package:
https://github.com/flathub/flathub/pull/504
We can close this issue probably.

**Comment by x80486** [comment]
Pull Request for Insomnia [here](https://github.com/flathub/flathub/pull/504/).

**Comment by gschier** [comment]
Omg this is awesome @baszczewski!

**Comment by baszczewski** [comment]
@gschier 
My pull request was just reviewed and new some actions. So I have few questions here:

- Are you interested in future maintenance of this package or at least to gain access to write on Flathub repository?
- To finish this package I have to provide at least two additional files. App manifest (.xml) where you can provide some descriptions and details about yours application and desktop file (.desktop) important for DE. Do you have preferred place for that? What you say about *flathub* directory on top of this repository? You have *screenshots* there already so I think is this nice place.

**Comment by x80486** [comment]
It would be nice if this can move forward. The `AppImage` doesn't work anymore in my system. It's throwing this error: `Aug 19 15:24:52 uplink org.gnome.Nautilus[989]: /tmp/.mount_insomn8plZ5p/app/insomnia: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory`.

Looks like it doesn't bundle GTK2+ libraries:

```
Aug 19 15:24:52 uplink org.gnome.Nautilus[989]: /tmp/.mount_insomn8plZ5p/app/insomnia: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
Aug 19 15:24:52 uplink nautilus[11501]: gdkselection-wayland.c:261: error reading selection buffer: Operation was cancelled
Aug 19 15:24:52 uplink gnome-shell[1022]: Object Meta.WindowActor (0x56362bb18be0), has been already finalized. Impossible to get any property from it.
```

**Comment by keeferrourke** [comment]
Can this issue be reopened? The PR https://github.com/flathub/flathub/pull/504 was closed and Insomnia is _not_ packaged as a Flatpak. It would be really great if it could be.

**Comment by doums** [comment]
Hi,
I'm also a user of Flatpak and Insomnia is still not available as a package.
What is the state of the process ?

**Comment by WhyNotHugo** [comment]
See https://github.com/flathub/flathub/pull/2406
