### ISSUE TITLE
[Feature Request] Send and download response to disk

### ISSUE THREAD

**Issue by oliverjanik** [getinsomnia/insomnia#940]
If my API hits a larger response, say 10mb. The UI just freezes on me. Can we pls have send and stream to disk ?

I think postman has this feature.

**Comment by gschier** [comment]
You can do this in the advanced send options (right click send button)

**Comment by oliverjanik** [comment]
That works, thanks. I completely missed I can right click that button.

**Comment by oliverjanik** [comment]
Actually, this feature is really weird.

Instead of right click and download immediately (my expectation) it does something weird:

1) It asks for a directory? Why not file name?
2) Then it does nothing, Send changes to Download button
3) I press download I see the spinner but no file is downloaded
4) This Download button now persists for all other requests

Very odd UX.

Can we please have just a simple straight "Send & Download" and ask for a full file path? Done.

**Comment by norppa** [comment]
Also, when doing this I get file named "attachment; filename=foo.txt". Probably not how it was meant to interpret Content-Disposition.

**Comment by gschier** [comment]
@norppa can you open another issue for that one?

**Comment by gschier** [comment]
@oliverjanik the UX was chosen to satisfy a specific use-case. I'm open to adding another option to do a combined send and download.

**Comment by oliverjanik** [comment]
Reopen please, I really despise the stale bot.

**Comment by gschier** [comment]
Sometimes stalebot is annoying, but it's good for cleaning up issues that don't have much demand. This issue does not seem to be that popular but I'm open to changing it or adding a new option if the demand goes up.

I'll re-open it for now.

**Comment by oliverjanik** [comment]
We're a paying customer @gschier and this would be a very nice feature for us.

**Comment by gschier** [comment]
![image](https://user-images.githubusercontent.com/587576/47113788-ead22c00-d227-11e8-8e4b-31388b523162.png)

**Comment by oliverjanik** [comment]
Awesome!

**Comment by gschier** [comment]
😄

**Comment by mattiasflodin** [comment]
How is this meant to work? I selected "send and download" but it behaves exactly the same as always, doesn't ask for a file path or anything. I also see no information about the feature in the documentation.

**Comment by oldo** [comment]
I am also experiencing the same as @mattiasflodin

**Comment by oldo** [comment]
I was able to get around this by copying request as cURL

![image](https://github.com/Kong/insomnia/assets/4557648/a9029d5f-33fe-4fe7-a462-2b6d8ffe3353)

And then in terminal pipe response into a file.

```
{{ cURL request... }} > export.zip
```

**Comment by geekbeast** [comment]
Also just hit this. Working with an annoying binary API extension and I really need to flush to file.
