### ISSUE TITLE
[Feature Request] Reference the values of Template Tags within the Edit Tag Input Type

### ISSUE THREAD

**Issue by bbbco** [getinsomnia/insomnia#941]
- Insomnia Version: 5.16.2
- Operating System: Linux Mint

## Details

I'd like to be able to refer to the resulting value of a Template Tag to dynamically populate a field inside another Template Tag. This would allow for "Template Tag chaining", so that I could use a template tag plugin to call a template tag request, and use the value of the request template tag to pass to my template tag for further modification or manipulation.

I would envision a new option to be listed here: 
![selection_265](https://user-images.githubusercontent.com/30680/40313153-e42c3bb2-5ce2-11e8-9ff9-c6e2334ee3b6.jpg)

OR

Enable the user to use the same type of CTRL+SPACE keyboard function to add an environment/template tag within a string field type.

**Comment by Gomah** [comment]
Sorry to bump an old issue, but is there an alternative/solution to dynamically populate a field inside another Template Tag?

cc @gschier
