### ISSUE TITLE
[Bug] OAuth1 - if url get query contains chars which get percent encoded generated signature string is wrong

### ISSUE THREAD

**Issue by nenad82** [getinsomnia/insomnia#943]
- Insomnia Version: ___ 5.16.2
- Operating System: ___ Win10

## Details

Title says all...

Ofc, additional verification is required, because only test environment available to me is Magento2

But, Postman generated requests get expected response from Magento2, while requests from Insomnia fail.

I understand that oAuth1 is deprecated, but nevertheless you should support it.

I can provide more detail on how to address this issue, contact me if needed.

Also very useful resource on oAuth1 is here: http://lti.tools/oauth/

**Comment by gschier** [comment]
Can you provide a concrete example of a URL that triggers this bug?

**Comment by nenad82** [comment]
sure thing, glad you asked... this is common mage2 api call: 

> https://www.yourawesomemagento2shop.com/rest/V1/products?searchCriteria[pageSize]=20&searchCriteria[currentPage]=0 

(and before you ask, yes, brackets need to be there, it's part of call)

if you point out the general direction of part of the code which does the calculation of the signature i might be able to help to solve this one quickly... :)

**Comment by evs-xsarus** [comment]
Continued in https://github.com/Kong/insomnia/issues/4407
