### ISSUE TITLE
[Bug] Not able to filter with special keys in json

### ISSUE THREAD

**Issue by jagan120** [getinsomnia/insomnia#945]
- Insomnia Version: v5.16.2
- Operating System: MacOS 10.13.4

## Details

Not able to use special characters in JSONPath filtering

JSON Looks like this(live preview) : 

<img width="780" alt="screen shot 2018-05-23 at 12 35 16 pm" src="https://user-images.githubusercontent.com/2940021/40441535-f9147bf2-5e86-11e8-9b2f-d4a95405f9a6.png">

and this is what happens :

<img width="779" alt="screen shot 2018-05-23 at 12 35 34 pm" src="https://user-images.githubusercontent.com/2940021/40441616-2cef5d20-5e87-11e8-8ee4-33b0d6de95fe.png">

**Comment by gschier** [comment]
Hmm, not sure why that could be. Possibly a bug in the JSONPath library that Insomnia uses. Does this work as a temporary workaround?

```
$.application.instance.port["$"]
```

**Comment by jagan120** [comment]
The workaround did work. Thanks!

**Comment by gschier** [comment]
Nice! Going to close this issue for now as it seems like a very niche case. I can open it up if it continues to be an issue.
