### ISSUE TITLE
[Feature Request] Arbitrary Environment Inheritance

### ISSUE THREAD

**Issue by skang0601** [getinsomnia/insomnia#946]
- Insomnia Version: 5.16.4.2066
- Operating System: 10.13.4
## Details

I have noticed the need to arbitrarily extend sub-environments. The use case is as follows: I have sub-environments setup for TST/STG/PRD for example. Each of those sub-environments contains information such as URLs. This is something that's okay to sync across members of my team. But I also have information that I'd like to change only on my machine, such as usernames and credentials that I do not want to sync across. Credentials are pretty obvious in why I don't want to sync them, as they're sensitive information. But I need to change things like what user I'm using and other user information to test how my services respond to different users. This is something I do not want to be synced since this is something relevant only to my local development.

The ability to arbitrarily extend sub-environments would solve the above use case, then I'd be able to extend my TST environment with a private sub-environment with information I'm attempting to test and I would be able to change regularly without impeding my team members.

**Comment by skang0601** [comment]
I'll get a PR up this weekend for this. I have some ideas on how to implement this.

**Comment by gschier** [comment]
That sounds like this, which I've been wanting to implement for a while. https://github.com/getinsomnia/insomnia/issues/283

Was that similar to what you were thinking?

**Comment by skang0601** [comment]
Yeah, that's very similar but the precedence is very important. Just enabling multiple environments is not sufficient, the nested environment as per the second comment is what I'm thinking of. 

After enabling this feature, Insomnia can also start providing sane defaults for the environment. Each environment can provide a local/private sub-environment that local users can modify without worrying about it being synced.

**Comment by gschier** [comment]
Implementation of multiple active environments would also need/have explicit precedence. It would be needed in order to have predictable and useful merging of duplicate keys (like you are suggesting). My idea would be that the sort order of the activated environments would determine the merge precedence.

**Comment by gschier** [comment]
Can you describe what you were thinking?

**Comment by gschier** [comment]
The sort order would probably be arrangeable via drag-n-drop so you could switch them around with ease. I could also imagine each one being a drop-down menu so you could quickly switch it out for a different one (eg. USER-1 --> USER-2).

Unless I'm misunderstanding, I think this implementation would still cover the case you outlined.

You would have your four environments (TST, TST-PRIVATE, USER-1, USER-2), then activate TST, TST-PRIVATE, and the USER environment you want to test with. 

What kind of experience/interface were you imagining?

**Comment by paulleduc** [comment]
This feature would be awesome. Our team has been loving Insomnia and this is the only major feature that's a bit of a stumbling block, as right now we have to either share API keys, or each create our own private Local / Staging / Production env objects, or not use an env variable for API keys at all.

**Comment by jhalterman** [comment]
I have the exact same use case as the OP - the desire to share my workspace with environments but not share credentials.

My own take on this is that rather than having sub-environments and have to worry about precedence and whatnot, an environment can simply have a `private` section that is not shared. Thoughts?

**Comment by pernielsentikaer** [comment]
That would be really awesome, I'm looking forward for this feature to be implemented ;0)

**Comment by Ordiel** [comment]
Are there any news on this one? I would really like to have this functionality
