### ISSUE TITLE
[Bug] Sidepanel renaming broken

### ISSUE THREAD

**Issue by NickFitton** [getinsomnia/insomnia#947]
- Insomnia Version: 5.16.4
- Operating System: OSX 10.13.4

## Details
Previously you could rename requests/folders by double-clicking them in the sidebar, this no longer works.

## Steps to reproduce
* Confirm the latest version of insomnia is installed,
* Create a request or a folder
* Rename the folder by double clicking it

## Workaround
For now, you can rename requests/folders by right clicking the item and clicking settings, there is an input box there you can change the name in.

**Comment by gschier** [comment]
Oh yes, that's a bug caused by the latest sidebar filtering changes. Will try getting a fix out today
