### ISSUE TITLE
[Improvement] Indicate default headers are in use

### ISSUE THREAD

**Issue by garyking** [getinsomnia/insomnia#949]
Hello, I am using the `insomnia-plugin-default-headers` plugin. It's very useful, except that it doesn't indicate when a request is importing default headers. 

There is a number next to the "Header" tab title whenever there are headers, so perhaps just increment this number by the number of default headers imported, at the very least? If it's otherwise too difficult to modify the UI too much. 

Best yet would be to show the default headers as regular headers, but they are uneditable.

**Comment by gschier** [comment]
I agree that this would be very useful but it's actually not possible to implement right now without a lot of work.

The default headers plugin makes use of the "request" hook to add any missing headers right before the request is sent. That means there's no way for the app to tell what the headers are going to be before you click the Send button.

The best we could do here in the short term would be to add some sort of plugin debug log that shows what the plugin(s) modified during the request.
