### ISSUE TITLE
[Feature Request] Default queries

### ISSUE THREAD

**Issue by garyking** [getinsomnia/insomnia#950]
Similar to `insomna-plugin-default-headers`, it would be nice to be able to set default queries. Some APIs require API keys in the query rather than headers, so this would be very useful in those cases.

**Comment by rickychandra** [comment]
Hi @garyking @gschier, has this feature been on progress or completed? I would like to submit a PR for it if possible :smile:.

**Comment by rickychandra** [comment]
Sorry, I didn't notice this has been implemented [here](https://github.com/wwselleck/insomnia-plugin-defaults).
