### ISSUE TITLE
[Bug] Visual Preview encoding

### ISSUE THREAD

**Issue by ilyaskorik** [getinsomnia/insomnia#954]
I have problems with the encoding in the visual preview. Instead of Russian letters in the utf8 encoding I see incomprehensible Unicode characters.

It will be nice if we can customize the encoding of the visual preview.

**Comment by gschier** [comment]
Can you provide a public URL that can reproduce this?

**Comment by gschier** [comment]
Just following up.

Can you provide an example @ilyaskorik?

**Comment by gschier** [comment]
I think this was fixed in a recent update
