### ISSUE TITLE
[Question] Where are the plugin logs stored

### ISSUE THREAD

**Issue by mdzhigarov** [getinsomnia/insomnia#955]
Hi,

I am using Insomnia REST on Windows. 
I installed this plugin https://www.npmjs.com/package/insomnia-plugin-validator and I configured it as explained in the description.
For some reason though - it seems it is not working. I am not sure if my plugin configuration is correct.
I see in the plugin.js of this plugin that it is supposed to log some messages.

Where are these logs stored? The ...\AppData\Roaming\Insomnia\logs directory is empty.

Best regards,
Marin

**Comment by gschier** [comment]
You can view the logs by opening View > Toggle DevTools > Console

**Comment by mdzhigarov** [comment]
Yes, thanks. That does it
