### ISSUE TITLE
[Bug] AWS auth doesn't support custom regions or services

### ISSUE THREAD

**Issue by darkliquid** [getinsomnia/insomnia#956]
- Insomnia Version: 5.16.1
- Operating System: Windows 10

### What am I doing?
Making a request to a service using AWS4 compatible request signing for authentication, with a region and service name not part of the standard AWS set.

### What am I expecting to happen?
The request to work, and the timeline to display the correct headers.

### What actually happens?
The request 403s and the timeline displays the wrong headers.

### Reproduction steps

1. Setup an AWS authenticated request
2. Set the region to any string not actually a AWS region name
3. Set the service to any string no actually a AWS service name
4. Send the request
5. Observe the time shows the Authorisation header with the service set to blank and the region set to us-east-1

**Comment by gschier** [comment]
Please make sure you are on the latest version of Insomnia and try again. This was fixed in 5.16.2
