### ISSUE TITLE
[Bug] URL preview pushes options out of view

### ISSUE THREAD

**Issue by stepjanssen** [getinsomnia/insomnia#958]
- Insomnia Version:  5.16.2
- Operating System: MacOS

## Details

I'm working with an application where I need to add full text documents to the query string. This causes the URL to become huge. Currently, I have a request where I can't make any more changes, since the URL preview is so big that it got outside of the viewable area and since the options are below the preview, I can't access them anymore.

**Comment by gschier** [comment]
Please make sure you are on the latest version of thm app (5.16.6). This should be fixed.
