### ISSUE TITLE
[Feature] Update environment variable by right-clicking on highlighted text

### ISSUE THREAD

**Issue by bbbco** [getinsomnia/insomnia#960]
- Insomnia Version: 5.16.2
- Operating System: Linux Mint

## Details

It would be helpful to be able to update individual environmental variables on the fly with textual data that is already available instead of having to go into the Manage Environment section. This would help make my workflow easier when running ad-hoc tests/requests.

The way I envision it working is by adding a new menu option to Right-Click context menu, "Update Environmental Variable" -> {{ environment variable }}. So, you highlight some text, and then right-click, select "Update Environmental Variable", and select the environmental variable to update. Selecting an environmental variable will then replace the existing value with a value of the highlighted text.

This would allow me to do a request for a list of objects, and select an id from the list of objects and update an {{ id }} environmental variable in order to quickly run another request that utilizes the {{ id }} variable.

**Comment by gschier** [comment]
There's an even easier way already https://support.insomnia.rest/article/43-chaining-requests

**Comment by bbbco** [comment]
Yeah, chaining is nice, and I have used it myself. But sometimes I just want to update an environment variable to a different string very quickly on an ad hoc basis. It would be nice to be able to easily and quickly update a single environmental variable.

**Comment by cbdelavenne** [comment]
I know this has been closed for 2 years+, but our team would also benefit from this feature.
