### ISSUE TITLE
[Feature Request] Add support brotli decompression response 

### ISSUE THREAD

**Issue by podolskyi** [getinsomnia/insomnia#961]
- Insomnia Version: 5.16.2
- Operating System: macOS

## Details
support new type Content-Encoding **Brotli** https://github.com/google/brotli

reference to testing http://httpbin.org/#/Response_formats/get_brotli

**Comment by gschier** [comment]
Looks like Curl just added support for this in a recent version https://daniel.haxx.se/blog/tag/brotli/

Since Insomnia uses a dynamically-linked version of libcurl for MacOS we'll have to rely on Apple updating Curl (currently still on 7.54.0).

**Comment by ikeblaster** [comment]
Still an issue on Windows though. It uses bundlel libcurl binary, which is probably 7.51.0. Any chance for update?

**Comment by gschier** [comment]
Perhaps! It looks like the library we use has updated to 7.57 now https://github.com/JCMais/curl-for-windows/tree/445e537cb2f5656e3a3ede09e9e4782a6b62c299

**Comment by 7rulnik** [comment]
@gschier seems that it's still an issue nevermind of libcurl version?
https://monosnap.com/file/5F5wkHkiWvIbTTlAlzWk74AzN8DhO7

**Comment by VojtaStanek** [comment]
I am using recent version of insomnia, but it still doesn't allow brotli:
```
< content-encoding: br


* Received 13.8 KB chunk
* Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.
```


My version of insomnia:
```
Version: Insomnia Core 2020.4.2
Release date: 10/21/2020
OS: Windows_NT x64 10.0.19041
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0
```
