### ISSUE TITLE
[Feature Request] Prompt for secrets

### ISSUE THREAD

**Issue by flipxfx** [getinsomnia/insomnia#962]
- Insomnia Version: 5.16.6
- Operating System: macOS

## Details
Support prompts that mask user input when typing to better support prompts for username/password type fields. The prompts currently work great for username/password fields except that the user has to type the password in plain text on their screen. A "Secure Text" option when editing the prompt tag, that would then mask the input like a normal password field, would make the prompt safer to use for secure info.

**Comment by gschier** [comment]
This would be a great enhancement
