### ISSUE TITLE
[Feature] Support Multiple Logins

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#964]
As Insomnia becomes more and more popular, it is becoming more common for users to be part of multiple teams, possibly with different accounts for each. 

Currently, there is no way to support this use-case besides logging out and in to each account when needed. This is painful, but may also lead to accidentally syncing workspaces to the wrong account/team.

Multiple logins should solve this. Here's what is needed to make this happen.

- Change session store to support multiple tokens and account details
- Modify the workspace sync menu to 
- Combine Sync Mode and Share Settings into a single dialog (to simplify configuration)
- Similar to selecting a team in the share settings, the user should also select the appropriate account if there are more than one

**Comment by gschier** [comment]
Closing this for now due to low demand

**Comment by mattwelke** [comment]
Not sure how relevant this is today, but this:

```
This is painful, but may also lead to accidentally syncing workspaces to the wrong account/team.
```

actually happened to me today. One of my team members ended up with one of my private workspaces on their machine, because apparently I had accidentally synced it when switching back to my work account.

Be careful of this.

**Comment by heiytor** [comment]
Will this feature be added in the future?
