### ISSUE TITLE
[Bug] Window doesn't load after open on fullscreen

### ISSUE THREAD

**Issue by Djaler** [getinsomnia/insomnia#966]
- Insomnia Version:  5.16.6 (from Snap)
- Operating System: elementary OS Juno (based on Ubuntu 18.04)

## Details

Steps to reproduce:
1. Open Insomnia
2. Maximize window
3. Reload Insomnia
4. See that window doesn't load. But process is active. Looks like it just transparent.

I can provide screencast or logs, if needed

**Comment by gschier** [comment]
A screencast would be useful 😄

**Comment by gschier** [comment]
I can't seem to reproduce it on MacOS

**Comment by Djaler** [comment]
Looks like I did something wrong last time. Bug occurs not when I Zoom In, but when I open Insomnia on Fullscreen. Apparently, the last time just coincided. https://youtu.be/8RjgDkon_70

**Comment by gschier** [comment]
Hmm, that's strange. It must be receiving (and storing) some strange window coordinates after you trigger the window maximization. 

Can you post the contents of the following three files when the bug happens? (note, the file path may be slightly different on your OS)

`~/.local/insomnia/localStorage/bounds`
`~/.local/insomnia/localStorage/maximize`
`~/.local/insomnia/localStorage/fullscreen`

---

P.S. as a temporary fix, deleting the above file should reset the window position.

**Comment by Djaler** [comment]
bounds: `{"x":0,"y":63,"width":1920,"height":1017}`
maximize: `true`
fullscreen: `false`

**Comment by Djaler** [comment]
Deleting only `maximize` file works for me

**Comment by gschier** [comment]
Thanks for the info! That's quite strange.

What happens if you keep the maximize `true` and delete only the bounds file?

---

For reference, here's the code. Not sure why maximizing the window could cause it to disappear. 

https://github.com/getinsomnia/insomnia/blob/develop/packages/insomnia-app/app/main/window-utils.js#L58

**Comment by Djaler** [comment]
It open normally for a first time. But not in next time. (because of the bounds reverted to the same state)

**Comment by gschier** [comment]
Ok, thanks for this. I think it might be related to maximizing the window before it's shown. I'll play with it in a Linux VM and see if I can reproduce/fix the issue.

**Comment by gschier** [comment]
Not yet. I haven't had time.

**Comment by Djaler** [comment]
Maybe this is not Insomnia issue. https://github.com/elementary/gala/issues/305

**Comment by riker09** [comment]
I was affected by this. Removing the file `rm ~/.config/Insomnia/localStorage/maximize` fixed it for me.

Background: I did an upgrade from elementary OS 0.4 (Loki) to 5 (Juno) and manually copied the folder `~/.config/Insomnia/` to my new user account.

After launching Insomnia from dock or the app launcher the process was running, but the window was invisible. I could close the app through the dock (or kill it with `kill` command).

**Comment by Djaler** [comment]
Hmm. Looks like it was fixed for me. @riker09 can you test? I'm using daily elementary repos

**Comment by gschier** [comment]
There's some more discussion happening in a newer issue https://github.com/getinsomnia/insomnia/issues/1255

Going to close this one and move the discussion there.
