### ISSUE TITLE
[Feature Request] Folder & Request titles as variables

### ISSUE THREAD

**Issue by TheTimmaeh** [getinsomnia/insomnia#971]
I'd love to see **folder and request titles** extend the list of variables (Space + Ctrl).

I'm using Insomnia for APIs that are mostly organized in interfaces and methods, like this: `{{ base_url }} / {{ interface }} / {{ method }}`
Thus I structure them the same way in Insomnia, folders representing interfaces and requests representing methods.

Currently I'm using a workaround for the interface/folder part by creating a variable inside the interface environment called 'interface'. This way I only have to change the value once when renaming/cloning the whole folder. Though when renaming/cloning a method, I always have to change both the title and the part in my URL.

I dream of a world where all my URLs look like this:
![](https://imgur.com/F269iEc.png)

**Comment by gschier** [comment]
Note, this can also be useful in the Markdown documentation.

![image](https://user-images.githubusercontent.com/587576/41072196-62f0848c-69ca-11e8-903e-1d977830b488.png)
