### ISSUE TITLE
[Question] how to use xpath on response body

### ISSUE THREAD

**Issue by carmineesposito73** [getinsomnia/insomnia#974]
- Insomnia Version: 5.16.6
- Operating System: Ubuntu 18.04 LTS

## Details

I have a body response xml but I'm not able to filter using xpath, even using the line under the response (botton-right corner of insomnia windows) I got <result></result>.

I checked the syntax of xpath with notepad++ and also with xpath command (on body saved by insomnia)

this is the line I want to get
$ cat get-admin-1528367171121.xml | grep Org | grep Pilota
        <OrganizationReference href="https://host.mydomain/api/admin/org/486e3ea9-8633-4939-95fa-ca953225f9b7" name="Pilota" type="application/vnd.vmware.admin.organization+xml"/>

I want to match the attibute 'name' and get the attribute 'href'
xpath: //OrganizationReference[@name="Pilota"]/@href

$ xpath -e '//OrganizationReference[@name="Pilota"]/@href' get-admin-1528367171121.xml
Found 1 nodes in get-admin-1528367171121.xml:
-- NODE --
 href="https://host.mydomain/api/admin/org/486e3ea9-8633-4939-95fa-ca953225f9b7"

but even simpler filter do not work on insomnia, for example
xpath: //OrganizationReference

the body I'm working on is quite big
ls -l get-admin-1528367171121.xml 
-rw-rw-r-- 1 carmine carmine 125070 giu  7 12:26 get-admin-1528367171121.xml

but even on small body I cannot filter based on xpath.

I was able to filter using the JSONpath (of course on json on response body)

thanks
carmine

**Comment by gschier** [comment]
Hey, thanks for the question. Can you post an example body to make it easy to reproduce?

**Comment by carmineesposito73** [comment]
this is an examples (less lines than the real ones)

[get-admin.txt](https://github.com/getinsomnia/insomnia/files/2082099/get-admin.txt)

**Comment by gschier** [comment]
Hmm, it looks like `xmlns="http://www.vmware.com/vcloud/v1.5"` is breaking it. After removing that, it works.

**Comment by gschier** [comment]
The XPath library Insomnia uses mentions how to handle namespaces but I wasn't able to get a query to work https://github.com/goto100/xpath#namespaces

**Comment by carmineesposito73** [comment]
do you mean you need a url to test it?

**Comment by gschier** [comment]
No, I was able to test it, I just wasn't able to get it working 😞

**Comment by Kantankerus** [comment]
Lol, well at least I know why this exact use case isn't working for me either.
[xml.txt](https://github.com/getinsomnia/insomnia/files/2239395/xml.txt)

/OrgList/Org/@href should give me what I'm looking for but I'm getting empty results.  Improper XML from VMware or is this a bug in the XML interpreter in Insomnia?

**Comment by Kantankerus** [comment]
Found a work around for me, might work for @carmineesposito73  

(//@href)[2]

**Comment by carmineesposito73** [comment]
thanks @Kantankerus, it's useful but actually this does not help me, I need a filter to get one specific line (match a name and get href, for example)
//OrganizationReference[@name="Pilota"]/@href
to make a query using href a a variable.

**Comment by Kantankerus** [comment]
@carmineesposito73 I had to come up with another workaround since calling element nodes by name seems to fail every time on this particular XML.  See if this works...
//*[@name='Pilota'/@href

**Comment by carmineesposito73** [comment]
@Kantankerus it works!!!! (I've added "]")
//*[@name='Pilota']/@href
thanks a lot

**Comment by carmineesposito73** [comment]
@gschier @Kantankerus 
after few more tests I can say it's better use " instead of ', so:
//*[@name="Pilota"]/@href
to avoid unexpected token in env variable definition
{
    "org_href": "{% response 'body', 'req_63e53c90ca7e40bdb711f2ed575ecbb4', '//*[@name=\\"Pilota\\"]/@href' %}"
}
