### ISSUE TITLE
[Bug] - Docs Markdown not working with numbered lists

### ISSUE THREAD

**Issue by Fyb3roptik** [getinsomnia/insomnia#977]
- Insomnia Version: 5.16.1
- Operating System: macos

## Details

I am editing a doc for an endpoint and I am trying to add a numbered list:

1. Item 1
2. Item 2

Actual Results
Item 1
Item 2

Expected Results:
1. Item 1
2. Item 2

**Comment by gschier** [comment]
Ah, looks like there isn't any CSS for ordered lists yet. I'll get this fixed for the next release
