### ISSUE TITLE
[Packaging] Arch Linux AUR PKGBUILD broken

### ISSUE THREAD

**Issue by b0o** [getinsomnia/insomnia#983]
The PKGBUILD on the Arch Linux AUR [Insomnia package](https://aur.archlinux.org/packages/insomnia) is broken. According to the comments on the AUR, this issue has been known by users for a few weeks.

The fix is simply to remove `'!upx'` from the `options` array in the PKGBUILD. 

Quoting cyrevolt's comment on the AUR:

> upx support was removed with the recent release of pacman 5.1.0, see https://git.archlinux.org/pacman.git/commit/?id=1a29744d0da8aa945b96b234574e0d5c80f13b62

I'm opening an issue here because it seems the maintainer of the AUR package is @gschier, who I'm guessing wasn't aware of this and wasn't receiving notifications from the AUR.

**Comment by gschier** [comment]
Ah yes, I did actually see that comment but didn't realize it's severity. I just removed the `upx` flag and resubmitted the package so it should be working now. 👍 

Thanks for pointing this out! 😄
