### ISSUE TITLE
[Bug] Remove \n from generated code payload

### ISSUE THREAD

**Issue by rgarrigue** [getinsomnia/insomnia#984]
![image](https://user-images.githubusercontent.com/1872031/41292964-4a275668-6e54-11e8-87a3-d5374af5e00a.png)

- Operating System:  Windows 7

## Details

I'm doing a quite simple query

![image](https://user-images.githubusercontent.com/1872031/41293004-62cb799c-6e54-11e8-965e-692c979d3ef6.png)

Then generating python code, either http-client or request, here it is

```
import requests

url = "http://192.168.60.10/api/index.php"

payload = "{\n    \"action\": \"SHOW\",\n    \"object\": \"STPL\"\n}\n"
headers = {
    'content-type': "application/json",
    'centreon-auth-token': "bla bla bla"
    }

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)
```

As you can see, the payload is somehow messed up. I've the same issue for all the others language, like go `	payload := strings.NewReader("{\n    \"action\": \"SHOW\",\n    \"object\": \"STPL\"\n}\n")` & so on.

And thanks for the awesome client :+1: 
Best regards,

**Comment by gschier** [comment]
Hi @rgarrigue,

I'm not sure I understand the problem. The `\n` characters represent the newlines in your request body. Is there an alternate way you'd like to see them represented?

**Comment by gschier** [comment]
I'm sorry to refute your comment, but I don't believe that's correct. 

Newlines _were_ part of your original data. The difference is that the Insomnia editor chooses to show them visually (as new rows) instead of literally (as `\n`). However, the underlying data is the same in both cases.

To demonstrate this, removing the `\n` characters from your original data would look like this:

![image](https://user-images.githubusercontent.com/587576/41523482-1e53a82c-72a8-11e8-8168-ed69d89ae089.png)

**Comment by rgarrigue** [comment]
Uh, okay. Yeah my bad obviously. It bugged me since json is usually a big one liner, and I've to ask my browser via an extension or my IDE to display this nicely, without the formating being a visible part of the data.

Well, I'm gonna close this one then. Sorry for the disturbance

**Comment by gschier** [comment]
No worries. If you (or anyone else) needs/wants to send compressed (minimal whitespace) request bodies, it's possible to write a [Request Hook Plugin](https://support.insomnia.rest/article/26-plugins#request-hook-api) that looks for all `application/json` requests, parses and compresses the request body, and overwrites the request body with the compressed one.
