### ISSUE TITLE
[Feature Request] Multiple authentication schemes per request

### ISSUE THREAD

**Issue by jhalterman** [getinsomnia/insomnia#986]
I have a large set of requests that I have saved. The problem is I need to use bearer auth with those requests in some environments and basic auth in others. With Insomnia, I get a single auth type per request that isn't selectable per environment.

Ideally, Insomnia would allow configuring a _list_ of auths and each environment would be able to specify which auth to use, if not some default.

**Comment by jhalterman** [comment]
... Alternatively, instead of having to configure my list of auths in each request, I could store it as part of an environment. This would actually be more convenient in most cases.

**Comment by jhalterman** [comment]
I'm not sure if I'm the right person to create it, but a plugin would be cool. 

@gschier Are you thinking that the approaches suggested here would be too disruptive to normal behavior to make good top level features? The second idea of storing auth at the environment level doesn't seem too bad.

**Comment by jhalterman** [comment]
Would this plugin be doable with the current state of plugins framework? Any pointers on how to proceed for anyone who attempts it?

**Comment by bfmcneill** [comment]
> Would this plugin be doable with the current state of plugins framework? Any pointers on how to proceed for anyone who attempts it?

https://insomnia.rest/plugins/insomnia-plugin-env-authentication
