### ISSUE TITLE
[Feature Request] Disable Cookies

### ISSUE THREAD

**Issue by Bizarrus** [getinsomnia/insomnia#987]
Currently i want to set the a `Cookie` for a Session (`Session-ID`), but the old session will be stored as Cookie and will be prepended in the request.

Sample `Timeline`:

```
> GET /s/upload/arr/6554138_6554138/edit HTTP/1.1
> Host: www.smule.com
> User-Agent: insomnia/5.16.6
> Cookie: _smule_web_session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiJTlkM2Y2ZDA0MTk4NzBlMTRkNTI0YzIzMjNjOGNkMTA1BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMURMVGw0OHUwVXRLdUVoVmNyQW5ZWkZTUzkxYksyUkpJLzFXN3Uwb0hyQUE9BjsARkkiFHJlZGlyZWN0aW9uX3VybAY7AEZJIjxodHRwczovL3d3dy5zbXVsZS5jb20vcy91cGxvYWQvYXJyLzY1NTQxMzhfNjU1NDEzOC9lZGl0BjsAVA%3D%3D--a68b1bd399b2ada8018be3537843657645e23b6e; smule_id_production=eyJ3ZWJfaWQiOiI2MDlhOGYwMy02MmU2LTQ5NzMtYjUwNy1iYTA3MmQ4NGE5YTAifQ%3D%3D--c92abf112d4c4c9ab756fa33193c19f62b398dd1
> Cookie: _smule_web_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTI1MjAxNzM1NmQyZTgwZmU3YzRhOTcwNDA1ZTBhOTAwBjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMWwvS1ByM0M5d3hnbk5nTFB3VkhnMkEwSm1OaEpkWnllOG9GNnI5WWV5dEE9BjsARg%3D%3D--1123d53c1dd3358caf0fbc8c9bc6df26e9456c81
> Accept: */*
```

You see, `_smule_web_session` is presented two times - The first entry is from the `Cookies`, the second from `Custom Header` entry on the Request.

**Comment by gschier** [comment]
Hey @Bizarrus,

You can disable the sending of cookies on a per-request basis via the request settings dialog.

![image](https://user-images.githubusercontent.com/587576/41446849-e2c6adac-701f-11e8-83b4-22d6116c1d89.png)

![image](https://user-images.githubusercontent.com/587576/41446861-e9f71882-701f-11e8-8749-e7d20855863d.png)

**Comment by 0ptimusrhyme** [comment]
Let me know if I should create another issue **but**: it would be really nice if we could disable sending cookies _globally_ instead of just on a per-request basis. Is that something up for consideration? I didn't see an issue open or closed for this specifically. @gschier

**Comment by gschier** [comment]
@0ptimusrhyme yes, please create another issue 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
