### ISSUE TITLE
[Feature Request] Add ability to clear search pattern

### ISSUE THREAD

**Issue by 4ekki** [getinsomnia/insomnia#989]
- Insomnia Version: 5.16.6
- Operating System: win10

## Details
Now, to return back to all requests from searching, user should select all text in the search field and delete it manually. Please add button for one-click clearing it: 
![image](https://user-images.githubusercontent.com/38757986/41453995-7d0c7f4e-7080-11e8-9868-ae82ac845943.png)

**Comment by gschier** [comment]
Yep, this seems like a great idea!

**Comment by 4ekki** [comment]
As a possible enhancement of this button, it would be nice if after clearing the result, currently selected request becomes visible. Now, on clearing search pattern, first request becomes shown, disregarding of which one is currently opened.

**Comment by gschier** [comment]
Do you mean scrolling the sidebar to the current request?

**Comment by 4ekki** [comment]
Exactly

**Comment by gschier** [comment]
That should be doable 👍

**Comment by gschier** [comment]
![filter](https://user-images.githubusercontent.com/587576/42109548-f7c14d56-7bab-11e8-822a-69dcca5dfe83.gif)
