### ISSUE TITLE
[Feature request] Ability to disable default headers

### ISSUE THREAD

**Issue by tippl** [getinsomnia/insomnia#993]
I have just discovered the `insomnia-plugin-default-headers` plugin and it is really useful. However there are use cases where it could make life harder.

The one i'm talking about mainly: 

you have some kind of header you want to send most of the time, but sometime you might want to test what happens if you didn't send it.
With the current implementation, you have to go to the environment where the header is defined and remove it, then once you are done put it back in.

This really disrupts the ease of work with headers insomnia provides. Would it be possible to include the default headers in the header tab? My idea was to display them with inputs and delete disabled, so that you can't edit them, but still can make use of the enabled checkmark.

This would additionaly solve another problem of the plugin, different environments and subfolders can add on to the header object, if all were visible in the header tab you would know exactly which headers you are sending. Since currently that is not possible unless you read the timeline log or generate a curl command.

![screenshot_20180620_075159](https://user-images.githubusercontent.com/2827500/41639620-d4640000-745e-11e8-9774-d206ee61a20a.png)

How it could look. (Of course better than that since you wouldn't be just deleting the button)

**Comment by gschier** [comment]
As a short-term workaround, you can also set the header value to `__Di$aB13d__` to prevent it from being sent entirely.

**Comment by gschier** [comment]
This is quite similar to #949. Because of the way the plugin works, it's impossible for the app to know what the default headers are before the request is triggered. For this to work, default headers would probably need to be included as a core feature.

I think there might be an easier middleground though. We could add a header value option to disable a header so that it won't be sent. This is actually how it used to work when a header provided an empty value, but this "bug" was recently fixed.

**Comment by tippl** [comment]
It would be nice, if the functionality could be implemented as a core feature because you can't really be sure at a glance if you have any headers set now.

However that also means there has to be someone willing to dedicate the time to do it.

**Comment by privettoli** [comment]
The solution that @gschier suggested (to set value to __Di$aB13d__) worked for me. Thanks!
