### ISSUE TITLE
[Bug] Multipart generated code miss pieces of the payload

### ISSUE THREAD

**Issue by rgarrigue** [getinsomnia/insomnia#994]
- Insomnia Version: ___
- Operating System: Win 7

## Details

I've a multipart with two fields, username and password. It works in Insomnia. 

![image](https://user-images.githubusercontent.com/1872031/41715687-85fa6930-7554-11e8-8ee6-51047ccb7691.png)

Whenever I generate the code for any language, I've the following (here in python requests)

```python
import requests

url = "http://192.168.60.10/api/index.php"

payload = "-----011000010111000001101001\r\nContent-Disposition: form-data; name=\"username\"\r\n\r\nadmin"
headers = {'content-type': 'multipart/form-data; boundary=---011000010111000001101001'}

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)
```

The payload is missing its data past the first one. I've tried a bit with more data, changing data name just in case, swapping order between username and password : only the first data is in the generated code.

**Comment by gschier** [comment]
FYI I know what the bug is but it's quite a tricky fix.

https://github.com/getinsomnia/insomnia/blob/a4517eb87e574af6401d184543a310f58d0ca452/packages/insomnia-httpsnippet/src/index.js#L119

I think the problem lies with `form.pipe`'s asynchronous nature being used in synchronous code.

**Comment by thewheat** [comment]
Thanks! Yeah I dug into it and found the same thing. Will see how best to go about it 😄 🤞

**Comment by develohpanda** [comment]
Likely fixed by https://github.com/Kong/httpsnippet/pull/173
