### ISSUE TITLE
[Enhancement] Ability to better visually distinguish environments

### ISSUE THREAD

**Issue by tippl** [getinsomnia/insomnia#995]
Insomnia supports coloring the environment, however that creates a tiny dot that i think can be overlooked pretty easily.

Could you add an option for the color to be used more visibly?

**Comment by gschier** [comment]
What do you suggest?

**Comment by gschier** [comment]
I like that it's prominent across the entire app window. It might not look great on the default theme though. However, it's good inspiration! Thanks for that awesome mockup 😄

**Comment by tippl** [comment]
Well, that is where the color support comes in, as it allows you to choose any color. Sure there are colors that won't look good on dark theme and colors that won't work on default, but you usually won't change a theme once you set it, so you just choose colors that work for you.

**Comment by tippl** [comment]
![screenshot_20180621_215146](https://user-images.githubusercontent.com/2827500/41742105-4e4e0e26-759d-11e8-815b-cb5c5d01ac93.png)
hmm

**Comment by gschier** [comment]
That's a good point. And your screenshot doesn't actually look that bad (compared to my intuition) 👍

**Comment by Hackjaku** [comment]
This feature was available until the last update, has it been removed?

**Comment by greathouse** [comment]
I would love to see this feature returned.
