### ISSUE TITLE
[Feature Request] Generate rest-client ruby rest-client

### ISSUE THREAD

**Issue by adam-koblentz** [getinsomnia/insomnia#996]
- Insomnia Version: _5.16.6.2073__
- Operating System: _MacOS HS__

## Details

It would be really nice if insomnia also supported generating rest-client instead of just net::http for Ruby.
![screenshot 2018-06-21 11 43 59](https://user-images.githubusercontent.com/30735546/41729881-6bb94a70-7548-11e8-899c-4a8f73932a29.png)

**Comment by gschier** [comment]
If you submit a PR to the `httpsnippet` project (the library Insomnia uses) I'd be happy to update the dependency in Insomnia.
