### ISSUE TITLE
[Feature Request][Installation]Custom installation path in Windows

### ISSUE THREAD

**Issue by T-One** [getinsomnia/insomnia#998]
Hello,

please add the possibility to install Insomnia on windows in a custom path instead of %appdata%
In enterprise environments with binary signation and executable lockdown on paths (like appsense) it's not possible to run software from %appdata%.

Kind Regards
T-One

**Comment by gschier** [comment]
Thanks for submitting this @T-One! 

This is a duplicate of an older issue https://github.com/getinsomnia/insomnia/issues/683
