### ISSUE TITLE
[Improvement] More token types for syntax highlighting in docs

### ISSUE THREAD

**Issue by crimsonvspurple** [getinsomnia/insomnia#999]
- Insomnia Version: 5.16.6
- Operating System: Win10

## Details

Writing a code block in markdown with specific language (like ```java), there seems to be some form of syntax highlighting in "WRITE" tab but everything is gone in "PREVIEW" or in actual "DOCS" tab.

Can this be fixed?

Thanks.

**Comment by gschier** [comment]
Hmm, this should be possible with something like `highlight.js`.

**Comment by gschier** [comment]
Actually, highlight is already in there. Maybe there's just no support for Java.

![image](https://user-images.githubusercontent.com/587576/41863706-a36de6b2-7875-11e8-94f9-17944edc11ae.png)

**Comment by gschier** [comment]
Hmm, nope. Java seems to be working for me

![image](https://user-images.githubusercontent.com/587576/41863788-dc937074-7875-11e8-9b4a-3b56012ab5ee.png)

**Comment by gschier** [comment]
It looks not very many of the token types have associated colors. I will add some more

**Comment by gschier** [comment]
There, that's a bit better 
![image](https://user-images.githubusercontent.com/587576/41864258-4f49c662-7877-11e8-9194-ce7a5a73da7f.png)
